Create migration guide - Closes #1025
LiskArchive/lisk-legacy-docs pull request #1037
Opened 2021-03-25 13:24 UTC by Tschakki

Closes #1025

2021-03-31 19:41 UTC, ManuGowda reviewed
LGTM, made some minor comments

2021-03-31 19:41 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +curl -o lisk-migrator.tar.gz <file name>
hope you plan to update `lisk-migrator.tar.gz` with actual url when tar is available?
Also, it's nice to give `file name` by default? 
ex: `curl -o https://downloads.lisk.io/lisk/main/lisk-migrator.tar.gz lisk-migrator.tar.gz` like this? then user can just copy past each step.

2021-03-31 19:41 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +cp ~/lisk-core/config/testnet/config.json ~/lisk-core/custom-config.json <1>
hope nobody run both instance on one node, but for safe side we can add network 
`cp ~/lisk-core/config/testnet/config.json ~/lisk-core/testnet/custom-config.json`, because both test and main copy same path and it might get overridden

2021-04-07 10:32 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +If you are using a different distribution of Lisk Core 2.1.6, like Docker, Commander or Source, you need to xref:{url_core_2_install}[install the application/binary distribution].
```suggestion
If you are using a different distribution of Lisk Core 2.1.6, such as Docker, Commander or Source, it will be necessary to xref:{url_core_2_install}[install the application/binary distribution].
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +{counter:seq3}) Run the following command in the terminal and ensure the output is `sha256sum: <file name>: OK` (note: command name and output may vary on macOS).
```suggestion
{counter:seq3}) Run the following command in the terminal and ensure the output is `sha256sum: <file name>: OK` (Note: The command name and output may vary on a macOS).
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +The height is needed as parameter of the `lisk-migrator` script in the next step.
```suggestion
The height is needed as a parameter of the `lisk-migrator` script in the next step.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +A snapshot of the blockchain will be created at this particular height, which then will be used to create the genesis block for the new blockchain.
```suggestion
A snapshot of the blockchain will be created at this particular height, which will then be used to create the genesis block for the new blockchain.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Check the current block height of your node directly in the terminal by running:
```suggestion
Check the current block height of your node directly in the terminal by executing the following commands:
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +If you have added the `lisk-migrator` to the PATH like described in section <<setting-up-the-lisk-migrator>> you can start the migration script by running the following command in the terminal:
```suggestion
If you have added the `lisk-migrator` to the PATH as described in section <<setting-up-the-lisk-migrator>> you can start the migration script by running the following command in the terminal:
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +The snapshot height will be announced seperately.
```suggestion
The snapshot height will be announced separately.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Observe if `lisk-migrator` finishes successfully (takes about 30-60 min from the snapshot height).
```suggestion
Observe if `lisk-migrator` finishes successfully, (this takes about 30-60 minutes from the snapshot height).
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +After the snapshot height is reached, delegates have approximately 2 hours time to start their Lisk Core 3.0.0 and enable forging on them, to ensure they wont miss any blocks after the hardfork.
```suggestion
After the snapshot height is reached, delegates have approximately 2 hours time to start their Lisk Core 3.0.0 and enable forging, to ensure they won't miss any blocks after the hardfork.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Is case the node is started at a later point in time, the node will simply sync to the current network height.
```suggestion
In case the node is started at a later point in time, then the node will simply sync to the current network height.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +For delegates, this might mean they miss a block, for every one else it has no further effect.
```suggestion
For delegates, this might mean they miss a block, for everyone else it will not have any further impact.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +After the lisk-migrator script has finished and the announced snapshot height has passed, there is no reason annymore to run Lisk Core 2.1.6 and it is recommended to stop it.
```suggestion
After the lisk-migrator script has finished and the announced snapshot height has passed, there is no reason to continue running Lisk Core 2.1.6 and therefore it is recommended to stop it.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Create a pm2 config as below for example:
```suggestion
Create a pm2 config as shown below for example:
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +After creating the config, start it with the following command:
```suggestion
After creating the config, to start it execute the following command:
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +You can verify that the node is running correctly by running:
```suggestion
You can verify that the node is running correctly by executing the following command:
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +This will return some general node information like:
```suggestion
This will return some general node information, for example as shown below:
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +As last step, enable forging on the node for your delegate.
```suggestion
As the last step, enable forging on the node for your delegate.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +The `0 0 0` stand for the three variables `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`.
```suggestion
The `0 0 0` stands for the three variables `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which is true for every delegate participating in the migration.
```suggestion
These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which is required for every delegate participating in the migration.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +When a delegate has already forged in the network, they need to check which values to use for `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`.
```suggestion
When a delegate has already forged in the network, it is necessary to check which values to use for `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`.
```

2021-04-07 10:32 UTC, chris529 commented on modules/ROOT/pages/management/pm2.adoc
> +Create a pm2 config as below for example:
```suggestion
Create a pm2 config, for example as shown below:
```

2021-04-08 08:55 UTC, Tschakki commented on modules/ROOT/pages/management/migration.adoc
> +{counter:seq3}) Run the following command in the terminal and ensure the output is `sha256sum: <file name>: OK` (note: command name and output may vary on macOS).
```suggestion
{counter:seq3}) Run the following command in the terminal and ensure the output is `sha256sum: <file name>: OK` (Note: The command name and output may vary on macOS).
```

2021-04-08 09:00 UTC, Tschakki commented on modules/ROOT/pages/management/migration.adoc
> +These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which is true for every delegate participating in the migration.
```suggestion
These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which is the case for every delegate participating in the migration.
```

2021-04-08 09:23 UTC, chris529 reviewed
Looks excellent! There is just one 'full stop' missing that needs to be added at the end of one sentence. 👍

2021-04-08 09:23 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +For more information, how self-voting affects the vote weight, see xref:{url_sdk_protocol_voteweight}[Delegates, voting and delegate weight (Lisk Protocol)]
```suggestion
For more information, how self-voting affects the vote weight, see xref:{url_sdk_protocol_voteweight}[Delegates, voting and delegate weight (Lisk Protocol)].
```

2021-04-08 09:38 UTC, Tschakki commented on modules/ROOT/pages/management/migration.adoc
> +For more information, how self-voting affects the vote weight, see xref:{url_sdk_protocol_voteweight}[Delegates, voting and delegate weight (Lisk Protocol)]
```suggestion
For more information how self-voting affects the vote weight, see xref:{url_sdk_protocol_voteweight}[Delegates, voting and delegate weight (Lisk Protocol)].
```

2021-04-08 10:05 UTC, chris529 submitted a review, later dismissed
LGTM!

2021-04-08 10:55 UTC, ManuGowda submitted a review, later dismissed
LGTM, maybe we can fine tune minor details when we have dry-run

2021-04-08 10:55 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +curl -o <file name>.SHA256 https://downloads.lisk.io/lisk/main/lisk-migrator.tar.gz.SHA256
```suggestion
curl -o lisk-migrator.tar.gz.SHA256 https://downloads.lisk.io/lisk/main/lisk-migrator.tar.gz.SHA256
```

2021-04-08 10:55 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +curl -o <file name>.SHA256 https://downloads.lisk.io/lisk/test/lisk-migrator.tar.gz.SHA256
```suggestion
curl -o lisk-migrator.tar.gz.SHA256 https://downloads.lisk.io/lisk/test/lisk-migrator.tar.gz.SHA256
```

2021-04-08 10:55 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +sha256sum -c <file name>.SHA256
```suggestion
sha256sum -c lisk-migrator.tar.gz.SHA256
```

2021-04-08 10:55 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +cp ~/lisk-core/config/mainnet/config.json ~/lisk-core/config/mainnet/custom-config.json <1>
is the path correct? isn't it start from `~/.lisk/lisk-core` something like this?

2021-04-08 10:55 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +cp ~/lisk-core/config/testnet/config.json ~/lisk-core/config/testnet/custom-config.json <1>
same here

2021-04-08 12:35 UTC, Tschakki commented on modules/ROOT/pages/management/migration.adoc
> +cp ~/lisk-core/config/mainnet/config.json ~/lisk-core/config/mainnet/custom-config.json <1>
Should be correct for binary installation, see: https://lisk.io/documentation/lisk-core/v3/setup/binary.html#download-and-execute-the-installation-script

2021-05-06 08:55 UTC, Nazgolze requested changes

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +All actively forging delegates on the Lisk Mainnet and the Lisk Testnet need to follow this guide to correctly migrate their nodes to the new network, in order to don't miss any blocks after the netw
```suggestion
All actively forging delegates on the Lisk Mainnet and the Lisk Testnet need to follow this guide to correctly migrate their nodes to the new network, in order to not miss any blocks after the network hard fork.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +Optionally, every one else having running a Lisk Core 2.1.6 who is not an actively forging delegate can participate in the migration process.
```suggestion
Optionally, anyone running a Lisk Core 2.1.6 who is not an actively forging delegate can participate in the migration process.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +If your version is lower than 2.1.6 make sure to xref:{url_core_2_update}[update Lisk Core] before you proceed with the migration.
```suggestion
If your version is lower than 2.1.6, make sure to xref:{url_core_2_update}[update Lisk Core] before you proceed with the migration.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +<1> Replace `$HOME` with the absolute path of where the `lisk-migrator` folder is located, in case you extracted it someewhere else than your home directory.
```suggestion
<1> Replace `$HOME` with the absolute path of where the `lisk-migrator` folder is located, in case you extracted it somewhere other than your home directory.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +Next, use the CLI of Lisk Core 3.0.0 to generate the delegate configruation data.
```suggestion
Next, use the CLI of Lisk Core 3.0.0 to generate the delegate configuration data.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +After running the command, you will be prompted for your delegates passphrase and for the password that will be used to encrypt the passphrase, so it can be stored securely in the delegate configurat
```suggestion
After running the command, you will be prompted for your delegate passphrase and for the password that will be used to encrypt the passphrase, so it can be stored securely in the delegate configuration data.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +The height is needed as a parameter of the `lisk-migrator` script in the next step.
```suggestion
The height is needed by `lisk-migrator` in the next step.
```
This one was technically correct, but a bit wordy, so I slimmed it down here

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +In case the node is started at a later point in time, then the node will simply sync to the current network height.
```suggestion
If the node is started at a later point in time, it will simply sync to the current network height.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +After running the command, you will be prompted for your delegates passphrase.
```suggestion
After running the command, you will be prompted for your delegate passphrase.
```

2021-05-06 08:55 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +After creating the config, to start it execute the following command:
```suggestion
After creating the config, start it with the following command:
```

2021-05-06 09:35 UTC, chris529 reviewed
Looking good, just a few minor points 👍

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +All actively forging delegates on the Lisk Mainnet and the Lisk Testnet need to follow this guide to correctly migrate their nodes to the new network, in order to don't miss any blocks after the netw
```suggestion
All actively forging delegates on the Lisk Mainnet and the Lisk Testnet need to follow this guide to correctly migrate their nodes to the new network, in order not to miss any blocks after the network hard fork has occurred.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Optionally, every one else having running a Lisk Core 2.1.6 who is not an actively forging delegate can participate in the migration process.
```suggestion
All other users running Lisk Core 2.1.6 who are not actively forging delegates, can optionally participate in the migration process.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +In this case you can skip the steps 1.4, 2.7, 2.8 and 2.9 in the guide, as they are only relevant for delegates.
```suggestion
In this case, the following steps 1.4, 2.7, 2.8, and 2.9 in this guide can be skipped, as they are only relevant for delegates.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +* Machines with minimum 4 GB RAM for Mainnet
```suggestion
* Machines with a minimum of 4 GB RAM for the Mainnet
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +* Machines with minimum 2 GB RAM for Testnet
```suggestion
* Machines with a minimum of 2 GB RAM for the Testnet
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Unpack it, and add it to the system path, in order to use it in the terminal:
```suggestion
Unpack it, and then add it to the system path, in order to use it in the terminal:
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Make the `lisk-migrator` command available in the PATH, e.g. by executing
```suggestion
Make the `lisk-migrator` command available in the PATH, e.g. by executing the following command:
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +<1> Replace `$HOME` with the absolute path of where the `lisk-migrator` folder is located, in case you extracted it someewhere else than your home directory.
```suggestion
<1> Replace `$HOME` with the absolute path of where the `lisk-migrator` folder is located, in case it was extracted somewhere else than in your home directory.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Next, use the CLI of Lisk Core 3.0.0 to generate the delegate configruation data.
```suggestion
Next, use the CLI of Lisk Core 3.0.0 to generate the delegate configuration data.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +NOTE: For seeing the current height of Lisk Testnet, use the network switcher of Lisk Desktop, which can be enabled in the settings.
```suggestion
NOTE: To view the current height of the Lisk Testnet, use the network switcher of Lisk Desktop, which can be enabled in the settings.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +The absolute path to the directory, where the newly generated genesis block should be saved to.
```suggestion
The absolute path to the directory, where the newly generated genesis block should be saved.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +After the snapshot height is reached, delegates have approximately 2 hours time to start their Lisk Core 3.0.0 and enable forging, to ensure they won't miss any blocks after the hardfork.
```suggestion
After the snapshot height is reached, delegates have approximately 2 hours time to start their Lisk Core 3.0.0 and enable forging, to ensure they will not miss any blocks after the hardfork.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +For delegates, this might mean they miss a block, for everyone else it will not have any further impact.
```suggestion
For delegates, this might result in them missing a block, for everyone else it will not have any impact.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +First ensure, that Lisk Core wont start again by removing the existing cronjob:
```suggestion
First ensure, that Lisk Core will not start again by removing the existing cronjob:
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Last but not least, remove the folder with Lisk Core 2.1.6, e.g. by executing:
```suggestion
Last but not least, remove the folder with Lisk Core 2.1.6, e.g. by executing the following commands:
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Run the following command in the terminal and check the logs in the console to verify Lisk Core starts successfully:
```suggestion
Run the following command in the terminal and check the logs in the console to verify that Lisk Core starts successfully:
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Create a pm2 config as shown below for example:
```suggestion
Create a pm2 config as shown in the example below:
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +Use the following command to see your new account address.
```suggestion
Use the following command to view your new account address.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +This will return an object including `privateKey`, `publicKey`, `address` and `binaryAddress`.
```suggestion
This will return an object including the `privateKey`, `publicKey`, `address`, and `binaryAddress`.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +As the last step, enable forging on the node for your delegate.
```suggestion
The final step is to enable forging on the node for your delegate.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +The `0 0 0` stands for the three variables `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`.
```suggestion
The `0 0 0` stands for these three variables, `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, and `MAXHEIGHTPREVOTED`.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which is the case for every delegate participating in the migration.
```suggestion
These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which will be the case for all delegates participating in the migration.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +When a delegate has already forged in the network, it is necessary to check which values to use for `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, `MAXHEIGHTPREVOTED`.
```suggestion
When a delegate has already forged in the network, it is necessary to check which values to use for `HEIGHT`, `MAXHEIGHTPREVIOUSLYFORGED`, and `MAXHEIGHTPREVOTED`.
```

2021-05-06 09:35 UTC, chris529 commented on modules/ROOT/pages/management/migration.adoc
> +A delegate can check these values by running the following command:
```suggestion
These values can be checked by running the following command:
```

2021-05-06 10:23 UTC, Nazgolze requested changes

2021-05-06 10:23 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +NOTE: If you are on macOS, dowload the file `lisk-migrator-v1.0.0-rc.0-darwin-x64.tar.gz` instead.
```suggestion
NOTE: If you are on macOS, download the file `lisk-migrator-v1.0.0-rc.0-darwin-x64.tar.gz` instead.
```

2021-05-06 10:26 UTC, Nazgolze commented on modules/ROOT/pages/management/migration.adoc
> +NOTE: If you are on macOS, dowload the file `lisk-migrator-v1.0.0-rc.0-darwin-x64.tar.gz` instead.
That's all I noticed on the proofreading side, otherwise it's looking good :+1:

2021-05-06 10:34 UTC, Tschakki commented on modules/ROOT/pages/management/migration.adoc
> +NOTE: If you are on macOS, dowload the file `lisk-migrator-v1.0.0-rc.0-darwin-x64.tar.gz` instead.
thanks, but we just discussed to remove this note again ^^ we only document linux now 👍

2021-05-06 11:37 UTC, ManuGowda commented on modules/ROOT/pages/management/forging.adoc
> +  ADDRESS                    Address of an account in a hexadecimal format.
```suggestion
  ADDRESS                    Address of an account in a Lisk 32 Address format.
```

2021-05-06 11:37 UTC, ManuGowda commented on modules/ROOT/pages/management/forging.adoc
> +  ADDRESS  Address of an account in a hexadecimal format.
```suggestion
  ADDRESS  Address of an account in a Lisk 32 Address format.
```

2021-05-06 11:37 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +Copy the generated delegate data object and add it to your custom configuration under the `forging.delegates` key:
now that the `lisk-core forging:config` generates the forging config which is mergeable format, should we use option `--output custom-forging.json` and then add the merge step
`jq --slurp '.[0] * .[1]' path/to/custom-config.json custom-forging.json > /path/to/merged.json`.

2021-05-06 12:05 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +  ADDRESS                    Address of an account in a hexadecimal format.
afaik its hexadecimal format needed here

2021-05-06 12:05 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +  ADDRESS  Address of an account in a hexadecimal format.
same as above

2021-05-06 14:38 UTC, ManuGowda submitted a review, later dismissed

2021-05-06 14:38 UTC, ManuGowda commented on modules/ROOT/pages/management/migration.adoc
> +jq --slurp '.[0] * .[1]' ~/lisk-core/config/mainnet/custom-config.json custom-forging.json > ~/lisk-core/config/mainnet/custom-config.json
LGTM, please get it verified with @fchavant or @Nazgolze once, just to be sure

2021-05-06 14:45 UTC, fchavant commented on modules/ROOT/pages/management/migration.adoc
> +jq --slurp '.[0] * .[1]' ~/lisk-core/config/mainnet/custom-config.json custom-forging.json > ~/lisk-core/config/mainnet/custom-config.json
I don't have a `custom-forging.json` with which to test but the command looks good.

2021-05-06 14:49 UTC, fchavant commented on modules/ROOT/pages/management/migration.adoc
> +jq --slurp '.[0] * .[1]' ~/lisk-core/config/mainnet/custom-config.json custom-forging.json > ~/lisk-core/config/mainnet/custom-config.json
```suggestion
TEMP_FILE=$( mktemp )
jq --slurp '.[0] * .[1]' ~/lisk-core/config/mainnet/custom-config.json ./custom-forging.json >$TEMP_FILE
mv $TEMP_FILE ~/lisk-core/config/mainnet/custom-config.json
```

2021-05-06 15:02 UTC, fchavant approved these changes
`jq` invocation looks good

2021-05-06 15:36 UTC, merged