Update forging example (docker) - Closes #103
LiskArchive/lisk-legacy-docs pull request #104
Opened 2018-11-02 15:02 UTC by Tschakki

Closes #103

2018-11-07 10:15 UTC, diego-G requested changes

2018-11-07 10:15 UTC, diego-G commented on user-guide/administration/docker/admin-docker.md
> +![info note](../../../info-icon.png "Info Note") | Adding an array component as environment variable in your docker compose is a bit tricky. For example, if you aim to enable forging on your node, yo
Please, check again the formatting.

2018-11-08 09:16 UTC, diego-G requested changes

2018-11-08 09:16 UTC, diego-G commented on user-guide/administration/docker/admin-docker.md
> +To do so, open the `.env` file, that you created during [docker installation](../../setup/install/docker/installation-docker.md), and adjust the values to your needs.
Link doesn't work.

2018-11-08 09:16 UTC, diego-G commented on user-guide/administration/docker/admin-docker.md
> +Instead, one can make use of the environmental variables to change values of configuration options.
```suggestion
Instead, one can use environment variables to change values in the configuration.
```

2018-11-08 09:17 UTC, diego-G commented on user-guide/administration/docker/admin-docker.md
> +Instead, one can make use of the environmental variables to change values of configuration options.
Please check this across the file. There are several cases.

2018-11-08 11:39 UTC, Tschakki commented on user-guide/administration/docker/admin-docker.md
> +To do so, open the `.env` file, that you created during [docker installation](../../setup/install/docker/installation-docker.md), and adjust the values to your needs.
fixed

2018-11-08 11:42 UTC, diego-G commented on user-guide/administration/docker/admin-docker.md
> +![info note](../../../info-icon.png "Info Note") | Adding an array component as environment variable in your docker compose is a bit tricky. For example, if you aim to enable forging on your node, yo
```suggestion
![info note](../../../info-icon.png "Info Note") | Adding an array component as environment variable in your docker compose is not straightforward. For example, if you aim to enable forging on your node for several delegates, you need to add the next variable which will be inserted in the array `forging.delegates`: _LISK_FORGING_DELEGATES=publicKey1&#x7c;encryptedPassphrase1,publicKey2&#x7c;encryptedPassphrase2_
```

2018-11-08 11:47 UTC, diego-G approved these changes

2018-11-08 11:49 UTC, merged