Update responses in subscribe API - Closes #1049
LiskArchive/lisk-legacy-docs pull request #1051
Opened 2021-04-09 12:21 UTC by Tschakki

Closes #1049

2021-04-26 10:45 UTC, MichalTuleja requested changes

2021-04-26 10:45 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +[source,json]
This change makes comments illegal according to the specs. As a result they are marked red in GitHub, not sure about the other systems. I would consider keeping it JavaScript (js) or JSON with comments (jsonc) when possible.

2021-04-26 10:45 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +[source,json]
Same as above.

2021-04-26 10:45 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +[source,json]
Same as above.

2021-04-26 10:45 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +[source,json]
This change makes comments illegal according to the specs. As a result they are marked red in GitHub, not sure about the other systems. I would consider keeping it JavaScript (js) or JSON with comments (jsonc) when possible.

2021-04-26 11:04 UTC, Tschakki commented on modules/ROOT/pages/references/subscribe-api.adoc
> +[source,json]
I only saw comments in one example and exchanged them with code callouts, should be fine now!

2021-05-03 15:58 UTC, MichalTuleja approved these changes
LGTM 👍

2021-05-03 16:01 UTC, merged