Update docker setup steps - Closes #1063
LiskArchive/lisk-legacy-docs pull request #1064
Opened 2021-04-22 15:51 UTC by Tschakki

Closes #1063

2021-04-28 14:22 UTC, MichalTuleja requested changes

2021-04-28 14:22 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
>  ==== The HTTP API
The HTTP API can be mentioned first, as it's the most common one. Then RPC and then subscribe.

2021-04-28 14:22 UTC, MichalTuleja commented on modules/ROOT/pages/setup/docker.adoc
> +- 9901: Default API port (HTTP & WeSocket)
WeSocket -> WebSocket

2021-04-28 14:22 UTC, MichalTuleja commented on modules/ROOT/pages/references/rpc-api.adoc
>  = WebSocket JSON 2.0 RPC API
Please refer to this document when updating the WebSocket RPC API:
https://github.com/LiskHQ/lisk-service/blob/development/docs/api/version2.md

2021-04-28 15:24 UTC, Tschakki commented on modules/ROOT/pages/references/rpc-api.adoc
>  = WebSocket JSON 2.0 RPC API
thanks, I created a new issue for this: https://github.com/LiskHQ/lisk-docs/issues/1068

2021-04-30 09:38 UTC, chris529 reviewed
Looks very good, just a few minor points 👍

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The xref:{url_api_rpc}[]  provides blockchain data in standardized JSON format over a WebSocket connection.
```suggestion
The xref:{url_api_rpc}[] provides blockchain data in standardized JSON format over a WebSocket connection.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The xref:{url_api_subscribe}[], or sometimes called the publish/subscribe or Event-Driven API.
```suggestion
The xref:{url_api_subscribe}[], Subscribe API is also sometimes known as the Publish/Subscribe or Event-Driven API.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
>  The Lisk Service WebSocket API uses the `socket.io` library and it is compatible with JSON-RPC 2.0 standard.
```suggestion
The Lisk Service WebSocket API uses the `socket.io` library and it is compatible with the JSON-RPC 2.0 standard.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
>  The specification below contains numerous examples how to use the API in practice.
```suggestion
The specification below contains numerous examples of how to use the API in practice.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
>  The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to HTTP standard (GET, POST, PUT, etc
```suggestion
The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to the HTTP standard (GET, POST, PUT, etc.) and the `entity` is a part of the application logic, ex. `accounts`, transactions and so on.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +Lisk Service is installed in addition to a Lisk blockchain application like Lisk Core, in order to provide enriched network data about the network for third party services.
```suggestion
Lisk Service is installed in addition to a Lisk blockchain application such as Lisk Core, in order to provide enriched network data for third-party services.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +We recommend using NPM to install Lisk Core conveniently through the command line:
```suggestion
It is recommended to use NPM to conveniently install Lisk Core through the command line:
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +Check out the xref:{url_core_setup_npm}[Lisk Core NPM setup] guide to find more information how to install Lisk Core on your machine.
```suggestion
Check out the xref:{url_core_setup_npm}[Lisk Core NPM setup] guide for more information on how to install Lisk Core on your machine.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +`--api-ws-port` allows to define the port for the WebSocket connection.
```suggestion
`--api-ws-port` allows the user to define the port for the WebSocket connection.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +Make sure to have the port open which allows external services communication with the Lisk Service APIs.
```suggestion
Ensure the port which allows external services communication with the Lisk Service APIs is open.
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +To connect Lisk Service to a local Lisk Core node, set the environment variable `LISK_CORE_WS` before you start Lisk Service like this:
```suggestion
To connect Lisk Service to a local Lisk Core node, set the environment variable `LISK_CORE_WS` before starting Lisk Service as shown below:
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +Alternatively, it is possible to define a file with all desired environment variables and use it to start Lisk Service like this:
```suggestion
Alternatively, it is possible to define a file with all the desired environment variables and use it to start Lisk Service as shown below:
```

2021-04-30 09:38 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +This will start Lisk Service with all environment variables which you previousely defined in `my-env.env`.
```suggestion
This will start Lisk Service with all the environment variables previously defined in `my-env.env`.
```

2021-04-30 10:48 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The xref:{url_api_subscribe}[], or sometimes called the publish/subscribe or Event-Driven API.
```suggestion
The xref:{url_api_subscribe}[], or sometimes called the Publish/Subscribe or Event-Driven API.
```

2021-05-03 14:51 UTC, MichalTuleja requested changes
Nicely done :) I've mentioned mostly mixed URLs, these have to be updated for sure.
The rest looks fine.

2021-05-03 14:51 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> +:url_api_mainnet: http://service.lisk.io/api/
`https://` (Important, you'll get Permanent Redirect with cURL)

2021-05-03 14:51 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> +:url_api_testnet: http://testnet-service.lisk.io/api/
`https://`

2021-05-03 14:51 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> +:url_api_betanet: http://betanet-service.lisk.io/api/
`https://betanet5-service.lisk.io`

2021-05-03 14:51 UTC, MichalTuleja commented on modules/ROOT/pages/setup/docker.adoc
> +vim my-env.env
Shall we advice people to use `nano` which is default in most distros?

Update: just checked, these files are not that relevant anymore.
The default file path is `docker/network/core3-default.env` and it is not advised to change its content.

User can create a `my-env` file but it's important in more complicated deployments only.

`LISK_CORE_WS`, `ENABLE_HTTP_API`, `ENABLE_WS_API` are the only supported params by default.

However, if we want to mention it at all, the current text is good to go 👍

2021-05-03 15:59 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +vim my-env.env
Ok np, I now commented out the section about the env file, and updated the above section about exporting the env variables accordingly.

2021-05-04 11:01 UTC, MichalTuleja requested changes

2021-05-04 11:01 UTC, MichalTuleja commented on modules/ROOT/pages/setup/docker.adoc
> +<<<<<<< HEAD
This is a leftover from last merge, isn't it?

2021-05-04 14:04 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +<<<<<<< HEAD
true, removed it now

2021-05-07 08:45 UTC, MichalTuleja approved these changes

2021-05-21 08:23 UTC, merged