Update lisk-genesis reference - Closes #1067
LiskArchive/lisk-legacy-docs pull request #1069
Opened 2021-04-29 10:03 UTC by Tschakki

Closes #1067

2021-05-04 08:50 UTC, nazarhussain requested changes

2021-05-04 08:50 UTC, nazarhussain commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +	// dpos: {...}
`DPOS` is kind of required schema, you can't skip it. Because without a initDelgates list you can't create a genesis block and for that we must need to include the `dpos` module schema.

2021-05-04 08:50 UTC, nazarhussain commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +	}
People may get confused about this hardcoded schema. We should refer it directly to the framework. 

```
import {TokenModule} from 'lisk-sdk';

const accountAssetSchemas = { token: new TokenModule().accountSchema }
```

Must test it before, there my be some parameters required to create TokenModule object.

2021-05-04 08:50 UTC, nazarhussain commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +	accounts,
Accounts must contains all the account including the delegate accounts. In here you are passing only normal accounts.

2021-05-04 10:31 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +	}
You seem to need the genesis config to create instances of all default modules. How to best retrieve it from the application?

2021-05-04 14:10 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +	}
the genesis config is needed as parameter.
I have now made changes that use the genesis config of the `configDevnet` sample as parameter to get the corresponding account schemas.

There is one issue with the account schemas, `createGenesisBlock()` does not accept them without that a new property `fieldNumber` is added to the account schemas.

I added it manually as a workaround, but it is kind of weird like this. Is that a known issue?

2021-05-06 15:44 UTC, nazarhussain approved these changes

2021-05-06 15:49 UTC, merged