Updates in the intro section - Closes #1078
LiskArchive/lisk-legacy-docs pull request #1079
Opened 2021-04-30 15:58 UTC by Tschakki

Closes #1078

2021-05-05 15:47 UTC, shuse2 commented on modules/ROOT/pages/index.adoc
> +In addition, the logic executed in a blockchain application can be much more complex compared to the logic that can be executed as part of a smart contract.
I think it's better to say in blockchain application, the complex logic can be written a lot easier than smart contract.

In theory, smart contract is turing complete so they can write any logic, it's just harder

2021-05-05 15:47 UTC, shuse2 commented on modules/ROOT/pages/index.adoc
> +This can cause problems because the smart contract applications can affect other smart contract applications negatively.
This can cause problems because the smart contract applications need to share the same resource.

Since the smart contracts are isolated, they dont affect each other directly. The problem is the shared resource. Same thing for the security. Security flaw on a smart contract does not affect other smart contract, but the security flaw on the base blockchain will potentially affect all the smart contract.

2021-05-06 08:58 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +This can cause problems because the smart contract applications can affect other smart contract applications negatively.
ok, replaced it with your suggestion

2021-05-06 10:19 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +In addition, the logic executed in a blockchain application can be much more complex compared to the logic that can be executed as part of a smart contract.
in what way is it harder, can you provide an example?

2021-05-06 10:42 UTC, shuse2 commented on modules/ROOT/pages/index.adoc
> +In addition, the logic executed in a blockchain application can be much more complex compared to the logic that can be executed as part of a smart contract.
i can't think of any specific example, but in general, because of the current state of evm and solidity, some logic are hard to manage to be able to calculate the gas fees effectively.
Meanwhile, in the blockchain application, you can write the logic in the familiar language. (js/ts), which have more mature syntax and functions to describe the logic

2021-07-19 08:18 UTC, nazarhussain requested changes

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/index.adoc
> +
I think this section highlighted in this style under "Getting Started" does not give a good impression. If someone want's to get started they just know it. Or we can add this a s normal heading before "Features" heading or we can remove it as well. 

![image](https://user-images.githubusercontent.com/112468/126121680-c7065abc-7ac3-4e96-b0d7-a485f7e8a25a.png)

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/index.adoc
> +* Programming language: **JavaScript/Typescript**
I don't think mentioning programming language as **Feature** of the SDK is a good idea.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/index.adoc
> +** xref:{url_references_test_suite}[SDK test suite]: simplifies to test all components of a blockchain application by providing dedicated fixtures, mocks and utility functions.
I will not call it as **SDK test suite**, rather **SDK testing utilities**. Test suite refers to the tests we actually have for the SDK.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/index.adoc
> +NOTE: Please note that the SDK does not run on the MS Windows operating systems.
I suggest rather stating that it does not run, we should be a bit neutral here and say: 

> SDK does not come with official support of Windows.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +A blockchain application is any kind of application which uses its' own blockchain as database layer.
I am not aligned with this definition here. Let's say a mobile wallet app is using blockchain, but its not a blockchain application in reference Lisk SDK ecosystem.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
I don't see any segregation between blockhchain and application in our use case. In Lisk ecosystem, the application it self is a blockchain, not the case that application runs on blockchain. 

e.g. Consider Lisk-Core, so the Lisk-Core itself is a blockchain, its not an application running on a blockchain. If that would be the case then theoretically anyone can run other applications on top of Lisk-Core as well.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +image:intro/node-network.png[]
The whole architecture you describe here and in below diagram can't be fitted on a general definition of a blockchain. Every blockchain can have a way different architecture. We should explicitly mentioned it as **Architecture of Lisk Blockchain** or **Architecture of Lisk Application**

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +****
This can better go under their on respective sections.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +****
Why do we have to highlight this section like below and not just explain it as normal content? 

![image](https://user-images.githubusercontent.com/112468/126124571-5b9322a8-90d7-423d-8725-92051ae62757.png)

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +image:architecture.png[lisk-framework-architecture]
The styling of this diagram is way different than the diagram above, which looks really odd.

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +
In this section heading for **On-chain logic** is smaller than **When to create a module**, which should be opposite. 

![image](https://user-images.githubusercontent.com/112468/126125302-b231c2b5-1ea2-4782-88b5-006722441b39.png)

2021-07-19 08:18 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +== Blockchain applications vs. dApps
That's a very opinionated topic, do we really need to put this section under "Introduction"?

2021-07-19 09:36 UTC, nazarhussain requested changes

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +};
In react the convention `use***` is used for particular purpose. So it should return the client object rather block for better understanding of user.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +The channel is used inside of the xref:{url_intro_modules_lifecycle}[load() and unload()] functions of a plugin.
Channel is not passed to `unload` function.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +});
I don't think we should list this section under `Communication` page here. It should be part of `Modules` page, otherwise users will get confused.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
We should not list `Application` in this diagram. Application can't publish any event nor can reply to any action directly.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +Reducers are part of the module-internal request / response API, and are invoked via xref:{url_glossary_rpc}[Remote-Procedure-Calls (RPCs)].
Reducers can't be invoked by RPC calls. So why I earlier mentioned to not list reducers in the **Communication** page.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +To see a full list of all available actions and events of your blockchain application, invoke the actions <<appgetregisteredactions>> and <<appgetregisteredmodules>>.
Can't review each single action/event req/res format here. Hope we have some automated way to generate this doc from code.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +Schemas::
```suggestion
Asset Schemas::
```

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +* `required`
You didn't omitted in the example. So better remove from here.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +These data types are used to save the respective data in the *database*.
In database everything is always saved as binary as we are using an embedded key/value store which is not aware of any data types. 

So I suggest to completely remove this section from here and rename the heading **Database** in the table as **Data Type**

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +);
For an example `Decoding and encoding data` its irrelevant to showcase example of the state store.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/introduction/modules.adoc
> +image:intro/module-asset.png[]
In this diagram `apply` step is mentioned as `optional`. Where its required for the transaction asset. 

![image](https://user-images.githubusercontent.com/112468/126137627-eb9a1065-588d-4ff7-842b-b1b9c7df2bb0.png)

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/introduction/modules.adoc
> +* fatal
Do we really need a complete section for `logger` in here?

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/introduction/modules.adoc
> +== Interfaces
Under this heading you explained the Actions and Events but missed the Reducers. Would be nice to move reducer section from Communication page to here. Its more relevant here.

2021-07-19 09:36 UTC, nazarhussain commented on modules/ROOT/pages/introduction/plugins.adoc
> +image::intro/plugin-diagram.png[]
As of the current implementation of SDK5.x the `load, unload, actions, events` are required not optional. Check in the code for `BasePlugin`, everything declared as `abstract` is **required** for user to implement. 

![image](https://user-images.githubusercontent.com/112468/126138806-f43a412f-e3e5-4096-ba29-c1953d41755c.png)

2021-07-19 09:44 UTC, nazarhussain requested changes

2021-07-19 09:44 UTC, nazarhussain commented on modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
> +:url_architecture_registering_plugins: advanced-explanations/architecture.adoc#registering-modules-and-plugins
On this page you have a heading `Registering the plugin`, this heading is general to all plugins. So either copy it over to every plugin page or just remove it here and refer registration to **Plugins** page under **Introduction**

2021-07-19 12:18 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +image:architecture.png[lisk-framework-architecture]
Styling of diagrams is not final yet. I am requesting thee final diagrams  from design, once the review is done, so then they should all have a nice styling.

2021-07-19 12:22 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
I would disagree here. A blockchain is just a chain of blocks, as the name suggests. A blockchain application is an application that uses the blockchain as database layer. Very simple imho.

2021-07-19 12:25 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +A blockchain application is any kind of application which uses its' own blockchain as database layer.
I would assume a mobile app is only using API endpoints of nodes, but not really managing the blockchain data, so I would not agree it is a blockchain app after this definition.

2021-07-19 12:27 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +* Programming language: **JavaScript/Typescript**
Maybe we can rename the "Features" to "Highlights"? I think it's still important to highlight it.

2021-07-19 12:27 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +
I like the statement, bubt maybbe we can remove the heading "what is the Lisk SDK?"

2021-07-19 12:30 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +image:intro/node-network.png[]
It is mentioned before, every time we say "blockchain applicaton" in the documentation, we refer to apps built with the Lisk SDK. So it is clear, as everywhere else, and we don't need to repeat it all the time. Should also be kind of clear from the context.

2021-07-19 12:33 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +****
This is a way to visually highlight certain content, and I thought this is something to highlight. I can also remove it if you disagree.

2021-07-19 12:34 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +
I think it's OK like this, as the box is not a subsection of the on-chain logic section

2021-07-19 12:37 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +== Blockchain applications vs. dApps
I personally think this is a very interesting topic, and as many people will be asking themselves this question if they are already familiar with dApps. Wee should find therefore a good answer to this. If you have issues with certain statements please point them out, I am happy to discuss them to improve this section further :)

2021-07-19 12:39 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +};
ok thanks, I will rename the function `apiRequest` or something similar

2021-07-19 12:41 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
What about these actions and events? https://lisk.com/documentation/lisk-sdk/rpc-endpoints.html

2021-07-19 13:04 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +****
This is below the diagram, because it explains what the diagram also illustrates. To make the connection clearer, I will add the terms "Modules" to on-chain logic and "Plugins"  to off-chain logic in  the explanation.

2021-07-19 13:22 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +Reducers are part of the module-internal request / response API, and are invoked via xref:{url_glossary_rpc}[Remote-Procedure-Calls (RPCs)].
I moved the reducer handler section as suggested to the module intro, but this section I would leave because it is referring to the diagram above. And in the diagram, It makes sense to have reducers listed as well to get the whole picture. The page is explaining communication in general, including internal communication that is relevant to the developer, and explains at the same time if interfaces are public or not.

2021-07-19 13:24 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +To see a full list of all available actions and events of your blockchain application, invoke the actions <<appgetregisteredactions>> and <<appgetregisteredmodules>>.
Not yet. But when I find time I would want to work on a  integration of typedoc generated content.

2021-07-19 13:28 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +* `required`
Does this mean the format of account schemas is the same as for every other schema? Then I would actually remove one of the examples and just have one general schema example.

2021-07-19 13:34 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +);
The stateStore is part of the example, because it is giving the purpose why we are encoding/decoding the data here.

And it is also giving a code example for a very common task: getting data from the DB, decoding it, altering it, encoding it and saving it again.

2021-07-19 13:35 UTC, Tschakki commented on modules/ROOT/pages/introduction/modules.adoc
> +* fatal
Where else would you put it?

2021-07-19 13:36 UTC, Tschakki commented on modules/ROOT/pages/introduction/modules.adoc
> +== Interfaces
There is already a reducer section, but it is under `state changes` section, because reducers can change the state of the blockchain I put it there.

2021-07-19 13:45 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/http-api-plugin.adoc
> +:url_architecture_registering_plugins: advanced-explanations/architecture.adoc#registering-modules-and-plugins
Not sure what you mean here? For me on every plugin reference page there is the already same heading.

But yes the reference pages would need some updates too, didn't focus on this in these updates.

2021-07-20 10:41 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
Yes these are the application events/actions but one can't use application instance to subscribe to events or call those actions. e.g. Below code can't be possible. 

```
const app = Application.defaultApplication();

app.invoke("app:getNodeInfo")
```

So all those events/actions can only be accessed through channels a.k.a. API client. But the diagram gave impression that these are accessible through the app instance.

2021-07-20 10:47 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +Reducers are part of the module-internal request / response API, and are invoked via xref:{url_glossary_rpc}[Remote-Procedure-Calls (RPCs)].
There is a clear and distinct line between On-Chain architecture, Off-chain architecture and Communication architecture. So I suggest we should mix any of these together. 

Reducers are very strict feature of on-chain architecture and have no comparison/relation with the actions/events so should not be listed together in the diagram. It will make users confused rather helpful.

2021-07-20 10:48 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +* `required`
Yes format for schemas are always same everywhere.

2021-07-20 10:49 UTC, nazarhussain commented on modules/ROOT/pages/index.adoc
> +* Programming language: **JavaScript/Typescript**
Yes "Highlights" will be good idea.

2021-07-20 10:53 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
Yes that could be true for Smart Contacts or Defi apps. But not in our case. In Lisk Ecosystem, an **Application** itself is a blockchain. Without application there can't be any chain of blocks, and without an application there can't the rules of data transition, or even the data itself. So we better not mix our `Application` concept with smart contracts or other Defi apps which runs on some blockchain.

2021-07-20 10:54 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +****
I don't see its that important in context of the page. Also visually the less content is highlighted the more focused user would be there. In our case we have so much content sections highlighted on one page that user can loose the focus from the actual content.

2021-07-20 10:57 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +
Not really. Content in a page must be structured visually. Section Headings MUST always be visually larger than the content inside. In this case the section heading is "On-Chain Logic" and "When to create a module" is a tip or side notes.

2021-07-20 11:45 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +
Ah ok, yes I think that is an UI issue, it cannot bee fixed as part of this PR, but feel free to create a new issue for this :)

2021-07-20 11:48 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
Hm, I think you are misunderstanding the diagram. The diagram actually states that an application cannot invoke any actions, it can only reply to application actions, which have been invoked by other components or external tools.

2021-07-20 11:51 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +Reducers are part of the module-internal request / response API, and are invoked via xref:{url_glossary_rpc}[Remote-Procedure-Calls (RPCs)].
Hm ok I understand, then I will remove the reducer column from the diagram, and also the reducers section.

2021-07-20 12:33 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
Hm, I would not call an Ethereum client "the blockchain", nor would I call Lisk Core "the blockchain". They are just nodee server who manage the blockchain, ubt the lockchain itself is just the decentralized database. For example, when you download a "snapshot of thee blockchain" you would get a snapshot of the database, not of the software Lisk Core. So imho calling the whole application blockchain is highly confusing, also in our context.

2021-07-23 14:23 UTC, nazarhussain commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
To me this diagram still is very confusing and some what inaccurate by listing `Application` object along with modules, plugins and external tools. @shuse2 Please suggest what you think. 

![image](https://user-images.githubusercontent.com/112468/126796128-c7eeb57c-c9ec-429c-ad06-b05b26e8c423.png)

2021-07-23 14:25 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
Let @shuse2 to be arbitrary on it and go with what most think is right.

2021-07-23 14:28 UTC, nazarhussain commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +
https://github.com/LiskHQ/lisk-docs/issues/1157

2021-07-23 14:28 UTC, nazarhussain approved these changes, later dismissed

2021-07-28 15:38 UTC, shuse2 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
In general, `Lisk Core` is a blockchain client/application that runs a `node` that operates / participate in `blockchain` network.
therefore, maybe `we refer to applications which are runnning oblockchains which are compatible with xref:{url_protocol}[]` is more correct?

2021-07-28 15:45 UTC, shuse2 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
I think application can be omitted as @nazarhussain mentioned here. Application handles all the request/response, but it's not something that user can touch.

2021-08-09 14:25 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +image::intro/sdk-interfaces.png[]
ok, the diagram is updated now @shuse2

2021-08-11 16:57 UTC, chris529 reviewed
Wow!...this was a large one...Looking very good :-)

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +This consists of a collection of libraries providing blockchain application functionalities (xref:{url_references_elements}[Lisk Elements]), and a powerful Command Line Interface (xref:{url_reference
```suggestion
It contains a collection of libraries providing blockchain application functionalities (xref:{url_references_elements}[Lisk Elements]), and a powerful Command Line Interface (xref:{url_references_commander}[Lisk Commander]), which allows developers to bootstrap and manage their xref:{url_introduction_bapps}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +| xref:{url_references_elements}[Lisk Elements] | Lisk Elements is a collection of libraries, each of them implementing some form of blockchain application functionality such as cryptography, transac
```suggestion
| xref:{url_references_elements}[Lisk Elements] | Lisk Elements is a collection of libraries, each of them implements a certain type of blockchain application functionality such as cryptography, transactions, p2p, etc.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +For example, it allows to xref:{url_guides_setup}[bootstrap] a complete blockchain application with 1 command.
```suggestion
For example, it allows to xref:{url_guides_setup}[bootstrap] a complete blockchain application with just 1 command.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +The framework architecture is constructed of three different layer of abstractions: `Node`, `Modules` and `Plugins` (see the xref:{url_introduction_bapps_diagram}[architecture diagram] of a blockchai
```suggestion
The framework architecture is constructed of three different layers of abstractions: `Node`, `Modules` and `Plugins` (see the xref:{url_introduction_bapps_diagram}[architecture diagram] of a blockchain application).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +It can be instantiated in two ways:
```suggestion
It can be instantiated in the following two ways:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +It defines the initial state of the blockchain on start of the network.
```suggestion
It defines the initial state of the blockchain at the start of the network.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +TIP: Check the xref:{url_guides_genesis_block}[] guide to learn how to create a valid genesis block.
```suggestion
TIP: Check out the xref:{url_guides_genesis_block}[] guide to learn how to create a valid genesis block.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +To enable the API to be reachable from remote, use the `ws` option.
```suggestion
To enable the API to be reachable remotely, use the `ws` option.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +The xref:{url_references_elements_apiclient}[] simplifies to send API requests to a blockchain application via IPC or WS.
```suggestion
The xref:{url_references_elements_apiclient}[] simplifies sending API requests to a blockchain application via IPC or WS.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +The channel in modules has one purpose: it allows a module to publish events to the application which were defined in the <<events>> property of the module.
```suggestion
The channel in modules has only one purpose: it allows a module to publish events to the application which were defined in the <<events>> property of the module.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +This is an example how to use the channel to publish an event:
```suggestion
An example how to use the channel to publish an event is shown below:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +The following components can *expose* actions
```suggestion
The following components can *expose* actions:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +If input data is required, it is provided as second argument.
```suggestion
If input data is required, it is provided as a second argument.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +The `channel` is available inside the lifecycle hooks, which allows to subscribe and publish to events, as well as invoking actions in the network.
```suggestion
The `channel` is available inside the lifecycle hooks, which offers the possibility to subscribe and publish to events, as well as invoking actions in the network.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +Events and actions are addressed with their xref:{url_advanced_communication_aliases}[alias] in the following way:
```suggestion
Events and actions are addressed with their xref:{url_advanced_communication_aliases}[alias] in the following manner:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +NOTE: It's required to use camelCase for the key naming.
```suggestion
NOTE: It is required to use camelCase for the key naming.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +To conveniently decode and encode the data structures stored on the blockchain, such as such as blocks, transactions, account state, and chain state, use the `codec` library.
```suggestion
To conveniently decode and encode the data structures stored on the blockchain, such as blocks, transactions, account state, and chain state, use the `codec` library.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +Some data is stored as `Buffer` in the database, but in other parts of the application, the data is expected as hexadecimal string.
```suggestion
Some data is stored as `Buffer` in the database, but in other parts of the application, the data is expected as a hexadecimal string.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/schemas.adoc
> +In that cases, it is needed to convert between `Buffer` and `string` as described below.
```suggestion
In these cases, it is necessary to convert between `Buffer` and `string` as described below:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
>  To follow this guide, the following is assumed:
```suggestion
To follow this guide, the following criteria below is assumed:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +While in the root folder of the blockchain application, generate a skeleton for the new asset with Lisk Commander.
```suggestion
In the root folder of the blockchain application, generate a skeleton for the new asset with Lisk Commander.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +As can e seen above, the command `generate:asset` already created the asset class `CreateHelloAsset` which contains skeletons of all important components of an asset.
```suggestion
As can be seen above, the command `generate:asset` already created the asset class `CreateHelloAsset` which contains skeletons of all important components of an asset.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +If the validation does not throw any errors, it means the validation has been successfull, and the `apply()` function will be executed as next step.
```suggestion
If the validation does not throw any errors, it means the validation has been successful, and the `apply()` function will be executed as next step.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +To get and set the blockchain state, the xref:{url_intro_modules_statestore}[stateStore] is used again, which we already know from the lifecycle hooks of the xref:{url_guides_module}[module guide].
```suggestion
To get and set the blockchain state, the xref:{url_intro_modules_statestore}[stateStore] is used again, which is already known from the lifecycle hooks of the xref:{url_guides_module}[module guide].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +Until now, it was not needed to use any custom configurations for the Hello World application.
```suggestion
Until now, it was not necessary to use any custom configurations for the Hello World application.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +But if we want to interact with the application, like described in the next guide xref:{url_guides_dashboard}[], we need to change the RPC configuration of the application, so that the dashboard plug
```suggestion
However, if we want to interact with the application as described in the next guide xref:{url_guides_dashboard}[], it is necessary to change the RPC configuration of the application, so that the dashboard plugin can connect to it.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +We now want to enable the RPC API and change the communication protocol to `ws`.
```suggestion
It is now necessary to enable the RPC API and change the communication protocol to `ws`.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +The application will use {url_github_config_schema_default}[the default configuration options^] in case a config option is not specified.
```suggestion
The application will use {url_github_config_schema_default}[the default configuration options^] in the case whereby a config option is not specified.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +. a new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```suggestion
. A new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +. a new asset `HelloAsset` is created, as explained in the guide xref:{url_guides_asset}[].
```suggestion
. A new asset `HelloAsset` is created, as explained in the guide xref:{url_guides_asset}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +. a new plugin `LatestHelloPlugin` is created, as explained in the guide xref:{url_guides_plugin}[].
```suggestion
. A new plugin `LatestHelloPlugin` is created, as explained in the guide xref:{url_guides_plugin}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Save and close `plugins.ts` and start the lockchain application again:
```suggestion
Save and close `plugins.ts` and start the blockchain application again:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +At the bottom of the dashoard is the "Recent events" window, which allows to subscribe to various events by selecting them from a dropdown.
```suggestion
At the bottom of the dashboard is the "Recent events" window, which allows the possibility to subscribe to various events by selecting them from a dropdown box.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +NOTE: It can happen that the same event is received multiple times, like in the below example, where the `hello:newHello` is received 3 times.
```suggestion
NOTE: It can happen that the same event is received multiple times, as shown in the example below where the `hello:newHello` was received 3 times.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +The transaction type is selected from the dropdown.
```suggestion
The transaction type is selected from the dropdown box.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +NOTE: The accounts in your `accounts.json` file will be different, because the file was created newly before in the guide xref:{url_guides_genesisblock}[].
```suggestion
NOTE: The accounts in your `accounts.json` file will be different, because the file was newly created before in the guide xref:{url_guides_genesisblock}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Once all needed parameters are provided, hit the kbd:[Submit] button.
```suggestion
Once all the necessary parameters are provided, click on the kbd:[Submit] button.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +If the transaction got accepted, you will see a confirmation:
```suggestion
If the transaction was successfully accepted, you will see the following confirmation:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Provide the address which is belonging to the passphrase which was used to create the hello transaction in the action input field and hit the kbd:[Submit] button.
```suggestion
Provide the address which is belonging to the passphrase that was used to create the hello transaction in the action input field, and click on the kbd:[Submit] button.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +In the response, you can see that the hello message of the account was updated successfully.
```suggestion
In the response, it can be seen that the hello message of the account was updated successfully.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +In the previous guides we created the following two new actions:
```suggestion
In the previous guides the following two new actions were created:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +. the action `hello:amountOfHellos` of the xref:{url_guides_module_actions}[hello module]
```suggestion
. The action `hello:amountOfHellos` of the xref:{url_guides_module_actions}[hello module]
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +. the action `latestHello:getLatestHello` of the xref:{url_guides_plugin_actions}[latest hello plugin]
```suggestion
. The action `latestHello:getLatestHello` of the xref:{url_guides_plugin_actions}[latest hello plugin]
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +You can directly hit the kbd:[Submit] button to see the results.
```suggestion
You can directly click on the kbd:[Submit] button to view the results.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +We don't need to provide any input, because the action doesn't require any.
```suggestion
It is not necessary to provide any input, because the action doesn't require any.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +As we already sent two hello transactions, the action responds as follows:
```suggestion
As two hello transactions were already sent, the action responds as follows:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +You can directly hit the kbd:[Submit] button to see the results.
```suggestion
You can directly click on the kbd:[Submit] button to view the results.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Again, we don't need to provide any input, because the action doesn't require any.
```suggestion
Again, it is not necessary to provide any input, because the action doesn't require any.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +The Dashboard plugin provides various more features, most of them very self-explanatory.
```suggestion
The Dashboard plugin provides more features, most of them very self-explanatory.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +. a new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```suggestion
. A new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +. a new asset `HelloAsset` is created, as explained in the guide xref:{url_guides_asset}[].
```suggestion
. A new asset `HelloAsset` is created, as explained in the guide xref:{url_guides_asset}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +. a new plugin `LatestHelloPlugin` is created, as explained in the guide xref:{url_guides_plugin}[].
```suggestion
. A new plugin `LatestHelloPlugin` is created, as explained in the guide xref:{url_guides_plugin}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
>  Now that we are able to create a new account and receive some initial tokens, let's build a new component that allows to send tokens from an account to another.
```suggestion
Now that it is possible to create a new account and receive some initial tokens, we can build a new component that allows the possibility to be able to send tokens from an account to another.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
>  The only difference is, that the sender is not essentially a genesis account, but can be any account in the network.
```suggestion
The only difference is that the sender is not essentially a genesis account, but can be any account in the network.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +They can be used to update the forging information of the genesis delegates in the configuration of the blockchain application. This needs to be done, because each new generation of a genesis block w
```suggestion
They can be used to update the forging information of the genesis delegates in the configuration of the blockchain application. This is a necessary requirement as each new generation of a genesis block will generate a new random set of genesis delegates.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +* Anyone can be notified immediately, if a new hello message was sent.
```suggestion
* Anyone can be notified immediately if a new hello message was sent.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +To follow this guide, the following criteria is assumed:
```suggestion
To use this guide, the following criteria is assumed:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Though you will notice, once the <<defining-an-account-schema,account schema>> is implemented into the module, that the application wont start successfully anymore.
```suggestion
Though you will notice, once the <<defining-an-account-schema,account schema>> is implemented into the module, that the application will not start successfully anymore.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +That is, because the accounts in the genesis block are not including the account schema for the new module yet.
```suggestion
This is due to the fact that the accounts in the genesis block are not including the account schema for the new module yet.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +To solve this, simply generate a new genesis block by using the application CLI, like explained in the next guide xref:{url_guides_genesis}[].
```suggestion
In order to solve this, simply generate a new genesis block by using the application CLI, as explained in the next guide xref:{url_guides_genesis}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
>  In fact, with these 2 properties, it is already a complete module that can be registered with the application.
```suggestion
In fact it can be stated that with these 2 properties, it is already a complete module that can be registered with the application.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
>  The properties `name` and `id` are prefilled by the values we used when <<generate-module,generating the module skeleton>> in the previous step.
```suggestion
The properties `name` and `id` are pre-filled by the values that were used when <<generate-module,generating the module skeleton>> in the previous step.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +If that is the case, it is required to define the corresponding account schema in the module.
```suggestion
If that is the case, then it is required to define the corresponding account schema in the module.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +TIP: For more information about the account schema in modules, check out the section about account schemas on the xref:{url_intro_modules_accountschema}[Modules] introduction page.
```suggestion
TIP: For more information about the account schema in modules, check out the section about account schemas in the xref:{url_intro_modules_accountschema}[Modules] introduction page.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +For the Hello application, we want to store a hello message in each user account, as defined in the application overview of the guide xref:{url_guides_setup_helloapp}[Creating a new blockchain applic
```suggestion
For the Hello application, it is required to store a hello message in each user account, as defined in the application overview of the guide xref:{url_guides_setup_helloapp}[Creating a new blockchain application].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +This event shall be published, every time someone is updating their hello message.
```suggestion
This event shall be published every time someone is updating their hello message.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +It is recommended to store the different schemas in a separate file, e.g. `schemas.js`, and import them in the module and asset where needed.
```suggestion
It is recommended to store the different schemas in a separate file, e.g. `schemas.js`, and import them in the module and asset where it is required.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +. a new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```suggestion
. A new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +. a new asset `HelloAsset` is created, as explained in the previous guide xref:{url_guides_asset}[].
```suggestion
. A new asset `HelloAsset` is created, as explained in the previous guide xref:{url_guides_asset}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
>  If you prefer to not use Lisk Commander to get started with development, the <<manual-setup-alternative-without-lisk-commander>> is explained below.
```suggestion
If you prefer not to use Lisk Commander to get started with development, the <<manual-setup-alternative-without-lisk-commander>> is explained below.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +In the example, the `HelloPlugin` will contain one action, which will return the latest hello message which was send to the network, and its sender address.
```suggestion
In the example, the `HelloPlugin` will contain one action, which will return the latest hello message which was sent to the network, and its sender address.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +NOTE: Please note that the SDK does not come with official support of Windows.
```suggestion
NOTE: Please note that the SDK does not come with any official support for Windows.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +To check the successful installation of Lisk Commander, run for example:
```suggestion
To check the successful installation of Lisk Commander, run the following command:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +After updating the `.bashrc` file, make it directly available in the terminal by exwcuting:
```suggestion
After updating the `.bashrc` file, make it directly available in the terminal by executing the following:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Now it is possible to convenieently run thee application CLI commands from anywhre, by referring to the alias.
```suggestion
Now it is possible to conveniently run these application CLI commands from anywhere by referring to the alias.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +As next step, proceed with the guide xref:{url_guide_module}[].
```suggestion
For the next step, proceed with the guide xref:{url_guide_module}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +It is most likely, because the `validate()` or `apply()` function of the asset isn't implemented yet.
```suggestion
This is most likely due to the fact that the `validate()` or `apply()` function of the asset isn't implemented yet.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
>  The remainder of the tests will need to be created by the developer, to test all the custom logic of the asset which was implemented after the initialization of the application.
```suggestion
The remainder of the tests will need to be created by the developer, in order to test all the custom logic of the asset which was implemented after the initialization of the application.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it throws an error, if the hello message equals some illegal statement
```suggestion
. An error is thrown, if the hello message equals some illegal statement
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
>  . it does not throw any error for a valid schema
```suggestion
. No error is thrown for a valid schema
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +If all tests pass, it verifies that the `validate()` function behaves exactly as expected.
```suggestion
If all tests pass, this verifies that the `validate()` function behaves exactly as expected.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +As the context is the same for every test,  it is convenient to prepare everything in or before the `beforeEach()` hook and directly call the `apply()` function with the context in each test.
```suggestion
As the context is the same for every test,  it is recommended to firstly prepare everything before the `beforeEach()` hook and directly call the `apply()` function with the context in each test.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +<2> `CreateHelloAsset`: useed to creeate a valid test transaction with a hello asset.
```suggestion
<2> `CreateHelloAsset`: used to create a valid test transaction with a hello asset.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it sets the hello counter to zero, after the genesis block is applied
```suggestion
. The hello counter is set to zero, after the genesis block is applied.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it returns the absolute amount of sent hello transactions, when the action is invoked.
```suggestion
. The absolute amount of sent hello transactions are returned, when the action is invoked.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +If the logic and the tests of the asset & module was implemented correctly, all tests should pass:
```suggestion
If the logic and the tests of the asset & module were implemented correctly, all tests should pass:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +This is done by choosing a unique delegate name, and posting a corresponding xref:{url_protocol_tx_registerdelegegate}[Register Delegate] transaction to the network.
```suggestion
This is achieved by choosing a unique delegate name, and posting a corresponding xref:{url_protocol_tx_registerdelegegate}[Register Delegate] transaction to the network.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option B - Creating the data with Lisk Commander::
```suggestion
Option B - Creating the data with Lisk Commander:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option A - Updating the forging status with the application CLI::
```suggestion
Option A - Updating the forging status with the application CLI:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option B - Updating the forging status via application action::
```suggestion
Option B - Updating the forging status via application action:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +* Completely modular: Configure, exchange or extent any of the blockchain related logic in the application with *xref:{url_introduction_modules}[] and xref:{url_introduction_plugins}[]*.
```suggestion
* Completely modular: Configure, exchange or extend any of the blockchain related logic in the application with *xref:{url_introduction_modules}[] and xref:{url_introduction_plugins}[]*.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +*** Generate skeletons for modules, assets and plugins.
```suggestion
*** Generate skeletons for modules, assets, and plugins.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +*** Many other convenient CLI tools like creating accounts, encrypting passphrases / messages and more.
```suggestion
*** Many other convenient CLI tools such as creating accounts, encrypting passphrases / messages and more.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +** xref:{url_references_test_suite}[SDK testing utilities]: simplifies to test all components of a blockchain application by providing dedicated fixtures, mocks and utility functions.
```suggestion
** xref:{url_references_test_suite}[SDK testing utilities]: simplifies the testing of all components of a blockchain application by providing dedicated fixtures, mocks, and utility functions.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +* *Interoperable* (coming soon, see {url_lisk_roadmap}[roadmap^]): Make your app interoperable with other blockchain applications, by registering it as sidechain on the Lisk Mainchain.
```suggestion
* *Interoperable* (coming soon, see {url_lisk_roadmap}[roadmap^]): Make your app interoperable with other blockchain applications, by registering it as a sidechain on the Lisk Mainchain.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The Lisk SDK will run on both the Ubuntu and MacOS operating systems shown below:
```suggestion
The Lisk SDK will run on both the Ubuntu and MacOS operating systems listed below:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +NOTE: Please note that the SDK does not come with official support of Windows.
```suggestion
NOTE: Please note that the SDK does not come with any official support for Windows.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +If the start was successful, the application will enable forging for all genesis delegates and will start to add new blocks to the blockchain every 10 seconds.
```suggestion
If the start was successful, the application will enable forging for all genesis delegates and will begin adding new blocks to the blockchain every 10 seconds.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To see an overview of all the available CLI commands, execute the following in the root folder of the application:
```suggestion
To see an overview of all the available CLI commands, execute the following commands in the root folder of the application:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +<1> Adjust to the path where your `new_app` is located.
```suggestion
<1> Navigate to the path where your `new_app` is located.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +After updating the `.bashrc` file, make it directly available in the terminal by executing:
```suggestion
After updating the `.bashrc` file, make it directly available in the terminal by executing the following command:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Now it is possible to conveniently run the application CLI commands from anywhere, by referring to the alias.
```suggestion
Now it is possible to conveniently run the application CLI commands from anywhere by referring to the alias.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +Examples of blockchain applications can be found in the tutorials, like the xref:{url_tutorials_nft}[] or the xref:{url_tutorials_srs}[] application.
```suggestion
Examples of blockchain applications can be found in the tutorials, such as the xref:{url_tutorials_nft}[] or the xref:{url_tutorials_srs}[] application.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +A typical network of nodes looks like this:
```suggestion
A typical network of nodes is illustrated in the diagram below:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +They scale great even for big networks with thousands of connected nodes.
```suggestion
They also possess the ability to scale extremely well, even for large networks with thousands of connected nodes.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +Unstructured partial mesh networks allow nodes to share information in the network very fast and secure with all other nodes.
```suggestion
Unstructured partial mesh networks allow nodes to share information in the network in a very expeditious and secure manner with all other nodes.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +The following modules are already inlcuded in the xref:{url_advanced_architecture_application}[default application], they provide a basic blockchain application with a DPoS blockchain which allows ba
```suggestion
The following modules are already included in the xref:{url_advanced_architecture_application}[default application], they provide a basic blockchain application with a DPoS blockchain which allows basic token transfers between users:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +xref:{url_introduction_plugin}[] are able to...
```suggestion
xref:{url_introduction_plugin}[] are able to perform the following:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +* automate the blockchain logic, such as automatically seeding transactions.
```suggestion
* automate the blockchain logic, such as automatically sending transactions.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +It is recommended to use the IPC/WebSocket protocols where possible, because they provide a much better performance in regards to response times (see the blog post: {url_blog_benchmark}[Benchmarking
```suggestion
It is recommended to use the IPC/WebSocket protocols where possible, as they provide a more enhanced performance in regard to the response times (see the blog post: {url_blog_benchmark}[Benchmarking Lisk Core v3.0.0 against Lisk Core v2.1.6]).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +However, if you prefer an HTTP API, it is possible to add support for custom APIs by registering additional plugins, like the xref:{url_references_http_plugin}[].
```suggestion
However, if you prefer an HTTP API, it is possible to add support for custom APIs by registering additional plugins, such as the xref:{url_references_http_plugin}[].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +Blockchain application usually have a frontend and a backend part, like normal web applications.
```suggestion
Blockchain applications usually consist of a frontend and a backend part, just as normal web applications.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +It can be achieved for example in the following ways:
```suggestion
For example, this can be achieved in the following ways:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +An example implementation of a frontend as plugin is the {url_github_lns_dashboard}[LNS UI plugin] for the example application *Lisk Name Service*.
```suggestion
An example implementation of a frontend as a plugin is the {url_github_lns_dashboard}[LNS UI plugin] for the example application *Lisk Name Service*.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +. For later requirements in a production environment, a middleware similar to Lisk Service should be used. which will aggregate the data from the blockchain network and maybe other 3rd party sources.
```suggestion
. For later requirements in a production environment, a middleware similar to Lisk Service should be used, which will aggregate the data from the blockchain network and possibly other 3rd party sources as well.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +In short, the main difference between dApps and blockchain applications is, that blockchain applications each run on their own blockchain/sidechain, while dApps are sharing the blockchain network wit
```suggestion
In short, the main difference between dApps and blockchain applications is that blockchain applications each run on their own blockchain/sidechain, while dApps are sharing the blockchain network with other dApps.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +Most functionalities of smart contracts can be implemented in blockchain applications much easier and straight forward.
```suggestion
Most functionalities of smart contracts can be implemented in blockchain applications much easier and in a more straight forward manner.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +But here is one important difference to dApps, when it comes to applying new <<on-chain-logic>> to the application:
```suggestion
However, there is one important difference here to dApps, when it comes to applying new <<on-chain-logic>> to the application:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +Additionally, smart contracts can reuse an already existing blockchain, which saves time when launching the application, because it is not needed to take care of setting up an independent blockchain
```suggestion
Additionally, smart contracts can reuse an already existing blockchain, which saves time when launching the application, as it is not necessary to take care of setting up an independent blockchain network, finding delegates footnoteref:[delegate_footnote,For more information about delegates, check the xref:{url_protocol_consensus}[Consensus algorithm\] page of the Lisk protocol.], etc.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +In the beginning, this will make the launch of the application a little more complex, but having an independent network comes along with a lot of benefits, which are listed in the next paragraphs.
```suggestion
In the beginning, this will make the launch of the application a little more complex, but having an independent network comes along with a lot of benefits, which are covered in the following paragraphs.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +The Lisk documentation is referring to applications built with the Lisk SDK as blockchain applications and not dApps to clarify the difference, that applications are not sharing a common blockchain,
```suggestion
The Lisk documentation is referring to applications built with the Lisk SDK as blockchain applications and not dApps. So to clarify the difference, the applications are not sharing a common blockchain, but instead are each running on their own chain.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +As an effect, blockchain applications have the following advantages:
```suggestion
As a result blockchain applications have the following advantages:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +Therefore it is growing much slower in size, and doesn't suffer so much from possible bottlenecks in the network, which can happen during times of high workload on a lot of different dApps.
```suggestion
Therefore it is growing much slower in size, and doesn't suffer so much from potential bottlenecks in the network, which can happen during times of high workload on many different dApps.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +* Interoperability: Register a blockchain application as sidechain to connect it to the Lisk Mainchain (coming {url_lisk_roadmap}[soon^]).
```suggestion
* Interoperability: Register a blockchain application as a sidechain to connect it to the Lisk Mainchain (coming {url_lisk_roadmap}[soon^]).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +Modules hold all logic that is changing the state of the blockchain; or in other words, all logic that makes changes on the blockchain.
```suggestion
Modules hold all logic that is changing the state of the blockchain; or in other words all logic that makes changes on the blockchain.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +Modules enable to...
```suggestion
Modules enable the possibility to accomplish the following:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +Registering a new module requires the generation of a new genesis block, if the module defines an <<account-schema>>.
```suggestion
Registering a new module requires the generation of a new genesis block if the module defines an <<account-schema>>.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +All important parts of a module are shown in the below diagram and explained in more detail below.
```suggestion
All important parts of a module are explained in more detail and are shown in the diagram below.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +The base module provides an interface which needs to be completed by implementing the below described components of a module.
```suggestion
The base module provides an interface which needs to be completed by implementing the described components of a module as listed below.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +That means, the minimum ID for a new module is `1000`.
```suggestion
This means that the minimum ID for a new module is `1000`.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +The maximum value for a module ID is `2^32 - 1`(equals 4,294,967,295), because it is stored as `uint32` value.
```suggestion
The maximum value for a module ID is `2^32 - 1`(equals 4,294,967,295), because it is stored as a `uint32` value.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +It is also important to note, that module IDs do not need to be in succession, the only requirement is, that they are unique within the blockchain application.
```suggestion
It is also important to note, that module IDs do not need to be in succession, the only requirement is that they are unique within the blockchain application.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +So as an example, it is valid to register multiple modules to the application which have the following module IDs: `1003`, `1000`, `2500001` because they are in the allowed number range, and each ID
```suggestion
So as an example, it is valid to register multiple modules to the application which have the following module IDs: `1003`, `1000`, `2500001` as they are in the allowed number range, and each ID is different.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +It is used as prefix in the xref:{url_advanced_communication_alias}[alias] of events and actions, and as key label to to add the properties of the <<account-schema>> to the user accounts footnoteref:
```suggestion
It is used as a prefix in the xref:{url_advanced_communication_alias}[alias] of events and actions, and as a key label to to add the properties of the <<account-schema>> to the user accounts footnoteref:[account_footnote. For more information about accounts, check the xref:{url_protocol_accounts}[\] page of the Lisk protocol.].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +As the name suggests, the logger enables to create log messages for the module for the different log levels:
```suggestion
As the name suggests, the logger creates log messages for the module for the different log levels:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +TIP: View the "Interfaces" section of the xref:{url_advanced_communication_interfaces}[Communication] page to see an overview about the different interfaces and their accessibility in modules, plugin
```suggestion
TIP: View the "Interfaces" section of the xref:{url_advanced_communication_interfaces}[Communication] page to see an overview about the different interfaces and their accessibility in modules, plugins, and external services.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +The parts which contain the logic to do state mutation on the blockchain are maybe the most important part of the module, as they define the underlying business logic and general behavior of a module
```suggestion
The parts which contain the logic to perform state mutation on the blockchain are possibly the most important part of the module, as they define the underlying business logic and general behavior of a module.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +To add support for a new transaction to the application, it is required to implement a new asset, and to add the asset to a module.
```suggestion
To add support for a new transaction to the application, it is required to implement a new asset and to add the asset to a module.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +The base asset provides an interface which needs to be completed by implementing the below described components of an asset.
```suggestion
The base asset provides an interface which needs to be completed by implementing the described components of an asset listed below.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +As the name suggests, the `validate()` function validates the posted transaction data, to check it has the expected format.
```suggestion
As the name suggests, the `validate()` function validates the posted transaction data to check it contains the expected format.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +Lifecycle hooks allow to execute logic at distinct moments in the xref:{url_advanced_architecture_lifecycle}[block lifecycle] of the application.
```suggestion
Lifecycle hooks allow the execution of logic at distinct moments in the xref:{url_advanced_architecture_lifecycle}[block lifecycle] of the application.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +The definition of this schema is totally flexible and it is possible to define very complex data structures as well, if needed.
```suggestion
The definition of this schema is totally flexible and it is possible to define very complex data structures as well if necessary.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +If a module with module name `hello` is registered in a xref:{url_advanced_architecture_defaultapp}[default application] with the above example of an account schema, the user accounts would look like
```suggestion
If a module with module name `hello` is registered in a xref:{url_advanced_architecture_defaultapp}[default application] with the above example of an account schema, the user accounts would appear as shown below:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +NOTE: The properties `token`, `sequence`, `keys`, `dpos` exist in the user account, because the blockchain application has already several modules xref:{url_intro_bapps_defaultmodules}[registered by
```suggestion
NOTE: The properties `token`, `sequence`, `keys`, `dpos` exist in the user account, because the blockchain application already has several modules xref:{url_intro_bapps_defaultmodules}[registered by default].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +Plugins are able to...
```suggestion
Plugins are able to perform the following:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +* automate the blockchain logic, such as automatically seeding transactions.
```suggestion
* automate the blockchain logic, such as automatically sending transactions.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +It is used as prefix in the xref:{url_advanced_communication_alias}[alias] of events and actions, and as key label to to add the properties of the <<plugin-defaults>> to the xref:{url_advanced_archit
```suggestion
It is used as prefix in the xref:{url_advanced_communication_alias}[alias] of events and actions, and as a key label to to add the properties of the <<plugin-defaults>> to the xref:{url_advanced_architecture_config}[application configuration].
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +After registering the plugin with the application, it can be configured in the xref:{url_advanced_architecture_config}[application configuration], using the here defined schema.
```suggestion
After registering the plugin with the application, it can be configured in the xref:{url_advanced_architecture_config}[application configuration], using the defined schema here.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +TIP: View the "Interfaces" section of the xref:{url_advanced_communication_interfaces}[Communication] page to see an overview about the different interfaces and their accessibility in modules, plugin
```suggestion
TIP: View the "Interfaces" section of the xref:{url_advanced_communication_interfaces}[Communication] page to see an overview of the different interfaces and their accessibility in modules, plugins, and external services.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +Other plugins and external services can subscribe to these events and as a result, they will be notified immediately, every time a new event is published.
```suggestion
Other plugins and external services can subscribe to these events and as a result, they will be notified immediately every time a new event is published.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +The `channel`, which is available inside of the `load()` function, allows access to the xref:{url_rpc_endpoints}[] in order to subscribe to events or to invoke certain actions within the application,
```suggestion
The `channel`, which is available inside of the `load()` function, allows access to the xref:{url_rpc_endpoints}[] in order to subscribe to events or to invoke certain actions within the application to retrieve the desired data.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/introduction/plugins.adoc
> +The `unload()` method will be invoked by controller to unload the plugin correctly.
```suggestion
The `unload()` method will be invoked by the controller to unload the plugin correctly.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  Display autocomplete installation instructions.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  help          display help for hello_app
```suggestion
  help          Display help for hello_app.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -d, --distance=distance  [default: 1000] Distance between each hashes
```suggestion
  -d, --distance=distance  [default: 1000] Distance between each hashes.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -c, --count=count        [default: 1000000] Total number of hashes to produce
```suggestion
  -c, --count=count        [default: 1000000] Total number of hashes to produce.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -o, --output=output      Output file path
```suggestion
  -o, --output=output      Output file path.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -o, --output=output        The output directory. Default will set to current working directory.
```suggestion
  -o, --output=output        The output directory. Default will be set to the current working directory.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -c, --count=count            [default: 1000000] Total number of hashes to produce
```suggestion
  -c, --count=count            [default: 1000000] Total number of hashes to produce.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -d, --distance=distance      [default: 1000] Distance between each hashes
```suggestion
  -d, --distance=distance      [default: 1000] Distance between each hashes.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                             	- --password=pass:password123 (should only be used where security is not important)
```suggestion
                             	- --password=pass:password123 (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  --overwrite                Overwrites the forger info
```suggestion
  --overwrite                Overwrites the forger info.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                             	- --password=pass:password123 (should only be used where security is not important)
```suggestion
                             	- --password=pass:password123 (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  --overwrite                Overwrites the forger info
```suggestion
  --overwrite                Overwrites the forger info.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                           	- --password=pass:password123 (should only be used where security is not important)
```suggestion
                           	- --password=pass:password123 (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                               	- --passphrase='my secret passphrase' (should only be used where security is not important)
```suggestion
                               	- --passphrase='my secret passphrase' (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                               	- --password=pass:password123 (should only be used where security is not important)
```suggestion
                               	- --password=pass:password123 (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  transaction:create  Create transaction which can be broadcasted to the network. Note: fee and amount should be in Beddows!!
```suggestion
  transaction:create  Create transaction which can be broadcast to the network. Note: fee and amount should be in Beddows!!
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +Create transaction which can be broadcasted to the network.
```suggestion
Create transaction which can be broadcast to the network.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -a, --asset=asset                          Creates transaction with specific asset information
```suggestion
  -a, --asset=asset                          Creates transaction with specific asset information.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                                             	- --passphrase='my secret passphrase' (should only be used where security is not important)
```suggestion
                                             	- --passphrase='my secret passphrase' (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -s, --sender-public-key=sender-public-key  Creates the transaction with provided sender publickey, when passphrase is not provided
```suggestion
  -s, --sender-public-key=sender-public-key  Creates the transaction with the provided sender public key, when the passphrase is not provided.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  --no-signature                             Creates the transaction without a signature. Your passphrase will therefore not be required
```suggestion
  --no-signature                             Creates the transaction without a signature. Your passphrase will therefore not be required.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  TRANSACTION  A transaction to be sent to the node encoded as hex string
```suggestion
  TRANSACTION  A transaction to be sent to the node encoded as hex string.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  TRANSACTION  The transaction to be signed encoded as hex string
```suggestion
  TRANSACTION  The transaction to be signed encoded as hex string.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                                             	- --passphrase='my secret passphrase' (should only be used where security is not important)
```suggestion
                                             	- --passphrase='my secret passphrase' (should only be used where security is not important).
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -s, --sender-public-key=sender-public-key  Sign the transaction with provided sender public key, when passphrase is not provided
```suggestion
  -s, --sender-public-key=sender-public-key  Sign the transaction with provided sender public key, when passphrase is not provided.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/token-module.adoc
> +Specifically:
```suggestion
Specifically the following criteria:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/token-module.adoc
> +Allows to send a transfer transaction, which transfers token from one account to another.
```suggestion
Allows the possibility to execute a transfer transaction, which transfers tokens from one account to another.
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +Follow the development guides to learn how to:
```suggestion
Follow the development guides to learn how to perform the following:
```

2021-08-11 16:57 UTC, chris529 commented on modules/ROOT/pages/tutorials/srs.adoc
>  In the SRS tutorial, you learn step-by-step how to create a blockchain application which offers users a feature to recover the balance of their accounts for the scenario that they have lost/forgotten
```suggestion
In the SRS tutorial, you learn step-by-step how to create a blockchain application which offers users a feature to recover the balance of their accounts in the event whereby their passphrase has been lost or forgotten.
```

2021-08-11 16:57 UTC, chris529 reviewed
Wow!...this was a large one...Looking very good :-)

2021-08-19 10:05 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option B - Creating the data with Lisk Commander::
this is correct, it's Asciidoc formatting

2021-08-19 10:05 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option A - Updating the forging status with the application CLI::
this is correct, it's Asciidoc formatting

2021-08-19 10:05 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option B - Updating the forging status via application action::
this is correct, it's Asciidoc formatting

2021-08-19 10:06 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +<1> Adjust to the path where your `new_app` is located.
`navigate` is incorrect in this context

2021-08-19 10:10 UTC, Tschakki commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +The Lisk documentation is referring to applications built with the Lisk SDK as blockchain applications and not dApps to clarify the difference, that applications are not sharing a common blockchain,
```suggestion
The Lisk documentation is referring to applications built with the Lisk SDK as "blockchain applications" and not "dApps", to clarify the difference that applications are not sharing a common blockchain, but instead are each running on their own chain.
```

2021-08-20 07:59 UTC, chris529 reviewed
Looks very good, there are a few points as it is a massive PR! 👍

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +The recommended method to create an `Application` instance is to use the *defaultApplication*, since it comes with the xref:{url_introduction_bapps_defaultmodules}[SDK default modules].
```suggestion
The recommended method to create an `Application` instance is to use the *defaultApplication*, as it comes with the xref:{url_introduction_bapps_defaultmodules}[SDK default modules].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/architecture.adoc
> +If a node receives a new block, it always performs the following actions.
```suggestion
If a node receives a new block, it always performs the following actions:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +If the validation does not throw any errors, it means the validation has been successful, and the `apply()` function will be executed as next step.
```suggestion
If the validation does not throw any errors, it means the validation has been successful, and the `apply()` function will be executed as the next step.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +. a new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```suggestion
. A new module `HelloModule` is created, as explained in the guide xref:{url_guides_module}[].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +. a new asset `HelloAsset` is created, as explained in the guide xref:{url_guides_asset}[].
```suggestion
. A new asset `HelloAsset` is created, as explained in the guide xref:{url_guides_asset}[].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +. a new plugin `LatestHelloPlugin` is created, as explained in the previous guide xref:{url_guides_plugin}[].
```suggestion
. A new plugin `LatestHelloPlugin` is created, as explained in the previous guide xref:{url_guides_plugin}[].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +Making updates in this config file will have no further effect on the blockchain application, so make always sure you are updating the correct `config.json` file.
```suggestion
Making updates in this config file will have no further effect on the blockchain application, so please ensure you are updating the correct `config.json` file.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Now open `plugins.ts`, import the Dashboard plugin and register it with the application:
```suggestion
Now open `plugins.ts`, import the Dashboard plugin, and register it with the application as shown below:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +We subscribe to the newly created event `hello:newHello`
```suggestion
We can now subscribe to the newly created event `hello:newHello`
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Another very useful component of the Dashboard is the "Send transaction" section.
```suggestion
An additional very useful component of the Dashboard is the "Send transaction" section.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +Of course, we want to try out the newly created hello asset from the guide xref:{url_guides_asset}[]: `hello:createHello`.
```suggestion
It is now possible to try out the newly created hello asset from the guide xref:{url_guides_asset}[]: `hello:createHello`.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +The action `app:getAccount` is part of the xref:{advanced_rpc_appactions}[application actions] and returns the account data for the account address that is specified in the action input.
```suggestion
The action `app:getAccount` is part of the xref:{advanced_rpc_applications}[application actions] and returns the account data for the account address that is specified in the action input.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +As two hello transactions were already sent, the action responds as follows:
```suggestion
As two hello transactions were already sent, the action responds as shown in the illustration below:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +The Dashboard plugin provides more features, most of them very self-explanatory.
```suggestion
The Dashboard plugin provides more features, and most of them are very self-explanatory.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +Now update the file to include the above defined React components and to build a basic navigation.
```suggestion
Now update the file to include the above-defined React components and to build a basic navigation structure.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +NOTE: It is also needed to start the corresponding blockchain application, if it is not running already.
```suggestion
NOTE: It is also necessary to start the corresponding blockchain application if it is not running already.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
>  To start it, run the following command:
```suggestion
To start, run the following command:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +As defined in the xref:{url_guides_setup_helloapp}[Hello World application overview], the module shall provide the following functionality:
```suggestion
As defined in the xref:{url_guides_setup_helloapp}[Hello World application overview], the module shall provide the following functionalities:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +As defined in the xref:{url_guides_setup_helloapp}[Hello World application overview], the module shall provide the following functionality:
Hey Mona! As we are referring to all of these points below, I think this should be mentioned plurally, so ''functionalities"...Thoughts..?

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +* A hello message shall be stored in the user accounts
```suggestion
* A hello message shall be stored in the user accounts.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Though you will notice, once the <<defining-an-account-schema,account schema>> is implemented into the module, that the application will not start successfully anymore.
```suggestion
Please be aware that once the <<defining-an-account-schema,account schema>> is implemented into the module, that the application will not start successfully anymore.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Publishes for every applied `hello` transaction asset a new event `hello:newHello`, and adds information about the sender of the transaction, and the corresponding hello message.
```suggestion
Publishes a new event `hello:newHello` for every applied `hello` transaction asset, and adds information about the sender of the transaction, and the corresponding hello message.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The action simply returns the current value of the hello counter, which is retrieved from the database.
```suggestion
This action simply returns the current value of the hello counter, which is retrieved from the database.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +As a reminder, the `apply()` function of the asseet `createHelloAsset` is shown below:
```suggestion
As a reminder, the `apply()` function of the asset `createHelloAsset` is shown below:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it updates the hello message in the sender account with the specified hello string
```suggestion
. The hello message is updated in the sender account with the specified hello string.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it increments the hello cpunter by +1
```suggestion
. The hello counter is incremented by +1.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +* `testing`: contains the functions of the Lisk SDk test suite.
```suggestion
* `testing`: contains the functions of the Lisk SDK test suite.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it publishes a new event for each applied hello transaction.
```suggestion
. A new event is published for each applied hello transaction.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it doesn't publish a new event for each applied other transaction (not hello).
```suggestion
. A new event is not published for each applied other transaction (not hello).
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Before it is possible to enable forging on a node, it is required to register as delegate.
```suggestion
Before it is possible to enable forging on a node, it is required to register as a delegate.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option B - Creating the data with Lisk Commander::
OK, yes good point, then you can commit it.

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option A - Updating the forging status with the application CLI::
👍

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +If the blockchain application was xref:{url_guides_setup_bootstrap}[bootstrapepd with Lisk Commander], it is possible to generate the relevant forging data conveniently with the command xref:{url_ref
```suggestion
If the blockchain application was xref:{url_guides_setup_bootstrap}[bootstrapped with Lisk Commander], it is possible to generate the relevant forging data conveniently with the command xref:{url_references_cli_forgingenable}[forging:enable].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Option B - Updating the forging status via application action::
👍

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +<1> Adjust to the path where your `new_app` is located.
OK, understood, then let's leave it as it is.

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +More specifically, in the Lisk documentation, everytime we talk about blockchain applications, we refer to applications which are runnning on blockchains which are compatible with xref:{url_protocol}
```suggestion
More specifically, in the Lisk documentation, every time we talk about blockchain applications, we refer to applications that are running on blockchains that are compatible with xref:{url_protocol}[].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +xref:{url_introduction_module}[] are able to...
```suggestion
xref:{url_introduction_module}[] are able to perform the following:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +* define how data is stored on the blockchain
```suggestion
* Define how data is stored on the blockchain.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +* define logic which is executed per block footnoteref:[block_footnote]
```suggestion
* Define logic which is executed per block footnoteref:[block_footnote].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +* define logic which is executed per transaction footnoteref:[tx_footnote].
```suggestion
* Define logic which is executed per transaction footnoteref:[tx_footnote].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +The default application does not include any plugins by default, but the SDK is bundled with a few common plugins which can be directly imported from the Lisk SDK:
```suggestion
The default application does not include any plugins by default, however, the SDK is bundled with a few common plugins which can be directly imported from the Lisk SDK:
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +It is possible to communicate to modules and plugins directly by invoking xref:{url_advanced_communication_actions}[actions] via RPC request, or by subscribing to xref:{url_advanced_communication_eve
```suggestion
It is possible to communicate to modules and plugins directly by invoking xref:{url_advanced_communication_actions}[actions] via a RPC request, or by subscribing to xref:{url_advanced_communication_events}[events].
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +New smart contracts can be directly applied on the running blockchain, while adding new on-chain logic to blockchain applications requires always a hard fork in the network.
```suggestion
New smart contracts can be directly applied on the running blockchain while adding new on-chain logic to blockchain applications always requires a hard fork in the network.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/blockchain-applications.adoc
> +In the beginning, this will make the launch of the application a little more complex, but having an independent network comes along with a lot of benefits, which are covered in the following paragrap
```suggestion
In the beginning, this will make the launch of the application a little more complex, but having an independent network comes along with numerous benefits, which are covered in the following paragraphs.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +* define how data is stored on the blockchain
```suggestion
* Define how data is stored on the blockchain.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +* define logic which is executed per block
```suggestion
* Define logic that is executed per block.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +* define logic which is executed per transaction
```suggestion
* Define logic that is executed per transaction.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +. data of the log message (object)
```suggestion
. Data of the log message (object).
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +. message of the log message (string)
```suggestion
. Message of the log message (string).
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +If a transaction object does not match the corresponding schema, the transaction wont be accepted by the node.
```suggestion
If a transaction object does not match the corresponding schema, the transaction will not be accepted by the node.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +If the function throws any error, the transaction will not be applied by the node.
```suggestion
If the function throws any errors, the transaction will not be applied by the node.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/introduction/modules.adoc
> +Lifecycle hooks allow the execution of logic at distinct moments in the xref:{url_advanced_architecture_lifecycle}[block lifecycle] of the application.
```suggestion
Lifecycle hooks allow the execution of logic at specific moments in the xref:{url_advanced_architecture_lifecycle}[block lifecycle] of the application.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +  -f, --force                Delete and overwrite existing blockchain data
```suggestion
  -f, --force                Delete and overwrite existing blockchain data.
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                               	- --passphrase='my secret passphrase' (should only be used where security is not important)
```suggestion
                               	- --passphrase='my secret passphrase' (should only be used where security is not important).
```

2021-08-20 07:59 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +                               	- --password=pass:password123 (should only be used where security is not important)
```suggestion
                               	- --password=pass:password123 (should only be used where security is not important).
```

2021-08-20 08:14 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +The action `app:getAccount` is part of the xref:{advanced_rpc_appactions}[application actions] and returns the account data for the account address that is specified in the action input.
this would break the link attribute

2021-08-20 08:17 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +Now update the file to include the above defined React components and to build a basic navigation.
```suggestion
Now update the file to include the above defined React components and build a basic navigation.
```

2021-08-20 09:25 UTC, chris529 approved these changes
LGTM!!!! 🥇

2021-08-20 12:12 UTC, merged