Fixes broken link in What is Lisk Core page in Core docs v3-beta-5 - Closes #1057
LiskArchive/lisk-legacy-docs pull request #1081
Opened 2021-05-05 09:50 UTC by chris529

Closes #1057

2021-05-06 15:53 UTC, Tschakki approved these changes

2021-05-07 15:22 UTC, Tschakki requested changes
@chris529 I just noticed there is a conflict in this PR, please resolve it, so I can proceed with the merge

2021-05-11 10:38 UTC, Tschakki requested changes

2021-05-11 10:38 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_admin_binary_snapshot: management/application.adoc#create_snapshot
I think this link can be removed.

2021-05-11 10:38 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
This link can bbee removed as well, it is not used on the page.

2021-05-12 08:27 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:url_admin_binary_snapshot: management/application.adoc#create_snapshot
As discussed we decided to leave this one 👍

2021-05-12 08:36 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
👍

2021-05-17 12:03 UTC, Tschakki approved these changes

2021-05-18 12:25 UTC, merged