Add faucet page - Closes #1072
LiskArchive/lisk-legacy-docs pull request #1095
Opened 2021-05-19 09:57 UTC by Tschakki

Closes #1072

2021-05-31 14:47 UTC, mitsuaki-u requested changes

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +. `captchaSecretkey`: The re-captcha secret key.
Maybe we should add a link to the google recaptcha docs here to make it easier for users to find these keys.

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +.Dashboard options in the configuration
```suggestion
.Dashboard options in the configuration:
```

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +. `encryptedPassphrase`: The passphrase of the genesis account which is encrypted with xref:{url_cryptography_encrypt_pw}[encryptPassphraseWithPassword()]
this url is not working

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +            captchaSitekey: ""
```suggestion
            captchaSitekey: "",
```

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +.Dashboard options in the configuration
```suggestion
.Faucet options in the configuration
```

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +    token: string  (optional)
token is required to get the funds

2021-05-31 14:47 UTC, mitsuaki-u commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +|===
The "Table of Contents" should be header/bolded

2021-06-01 09:23 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +|===
this needs to be changed in the CSS of UI

2021-06-01 10:01 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +. `encryptedPassphrase`: The passphrase of the genesis account which is encrypted with xref:{url_cryptography_encrypt_pw}[encryptPassphraseWithPassword()]
Will work on website, see: https://liskhq.github.io/lisk-docs/lisk-sdk/references/lisk-framework/faucet-plugin.html#plugin-configuration

2021-06-02 10:00 UTC, mitsuaki-u submitted a review, later dismissed

2021-06-02 12:31 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-06-02 12:31 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +`@liskhq/lisk-framework-faucet-plugin` is a plugin for the Lisk Framework that provides a user interface to receive an certain amount of tokens on request.
```suggestion
`@liskhq/lisk-framework-faucet-plugin` is a plugin for the Lisk Framework that provides a user interface that can receive a certain amount of tokens on request.
```

2021-06-02 12:31 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +The faucet plugin is a useful tool during development or in testing networks.
```suggestion
The faucet plugin is a useful tool during development and also in testing networks.
```

2021-06-02 12:31 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +* enables to send tokens to different accounts from a faucet for testing
```suggestion
* enables sending tokens to different accounts from a faucet for testing
```

2021-06-02 12:31 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +* allows to customize the faucet UI with a custom logo and application URL
```suggestion
* allows customizing the faucet UI with a custom logo and application URL
```

2021-06-02 12:31 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> +There are three required config options that need to be defined for the faucet plugin to funciton correctly:
```suggestion
There are three required config options that need to be defined in order for the faucet plugin to function correctly:
```

2021-06-02 12:31 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/faucet-plugin.adoc
> + For testing purposes you don't need own keys, simply use the {url_recaptcha_test_keys}[test API keys recaptcha^].
```suggestion
 For testing purposes, it is not necessary to use your own keys, simply use the {url_recaptcha_test_keys}[test API keys recaptcha^].
```

2021-06-02 14:07 UTC, merged