Update setup guide - Closes #1075
LiskArchive/lisk-legacy-docs pull request #1097
Opened 2021-05-20 13:20 UTC by Tschakki

Closes #1075

2021-06-02 10:10 UTC, nazarhussain requested changes

2021-06-02 10:10 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +npm install --global lisk-commander
As per commander README we recommend to use `--production`
```suggestion
npm install --global --production lisk-commander
```

2021-06-02 10:10 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Therefore, create a dedicated folder `newApp/`, which will contain the files for the application.
Since everywhere in our code we use practice of  `underscore` directory/file names, so I recommend to use the same here in the docs as well.

2021-06-02 10:10 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +alias newApp="./bin/run"
This alias will not work outside the app directory. And also will be confusing to use in another boostrapped app. You can add `pwd` to make this alias available in the shell no matter which directory. 

```suggestion
alias newApp="$(cwd)/bin/run"
```

2021-06-02 11:02 UTC, nazarhussain approved these changes, later dismissed

2021-06-03 10:08 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +To get started with the development of a blockchain application the most simple and efficient way, it is *recommended* to follow the guide <<bootstrapping-a-new-blockchain-application-with-lisk-comma
```suggestion
To get started with the development of a blockchain application in the most simple and efficient manner, it is *recommended* to follow the guide <<bootstrapping-a-new-blockchain-application-with-lisk-commander>>.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Lisk Commander offers various commands related to <<initializing-a-new-blockchain-application>>, or generating skeletons for modules, transactions and plugins which can be used to conveniently get st
```suggestion
Lisk Commander offers various commands related to <<initializing-a-new-blockchain-application>>, including generating skeletons for modules, transactions, and plugins which can be used to conveniently get started with developing a blockchain application.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +If you are using NVM, install the correct version like this:
```suggestion
If you are using NVM, install the correct version as shown below:
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +It is recommended to install Lisk Commander globally with NPM for a convenient usage of the Lisk Commander CLI.
```suggestion
It is recommended to install Lisk Commander globally with NPM to facilitate the convenient usage of the Lisk Commander CLI.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Inside of this folder, execute the `init` command of Lisk Commander like shown below:
```suggestion
Inside of this folder, execute the `init` command of Lisk Commander as shown below:
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +The user is asked for the application name, description, author and license after running `lisk init`.
```suggestion
The user is asked for the application name, description, author, and license after running `lisk init`.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Next, all required files are created by Lisk Commander.
```suggestion
Next, all the required files are created by Lisk Commander.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +NOTE: The application CLI offers various commands to manage your blockchain application conveniently.
```suggestion
NOTE: The application CLI offers various commands to conveniently manage your blockchain application.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +To run the application CLI, run the following command in the root folder of the application:
```suggestion
To run the application CLI, execute the following command in the root folder of the application:
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  Display autocomplete installation instructions.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +  help          display help for new_app
```suggestion
  help          Display help for new_app.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +<1> `bin/`: Contains the script to run the CLI of the aplication.
```suggestion
<1> `bin/`: Contains the script to run the CLI of the application.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +The files for the different commands can we adjusted and extended as desired, for example to include new flags and commands.
```suggestion
The files for the different commands can be adjusted and extended as desired, for example, to include new flags and commands.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +The `start` command offers various options, allowing to further configure the application.
```suggestion
The `start` command offers various options, allowing further configuration of the application.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +For example it is possible to define ports or to enable plugins which will be used by the application.
```suggestion
For example, it is possible to define ports or to enable plugins that will be used by the application.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +  --overwrite-config                                     Overwrite network configs if they exist already
```suggestion
  --overwrite-config                                     Overwrite network configs if they already exist.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +  --seed-peers=seed-peers                                Seed peers to initially connect to in format of comma separated "ip:port".
```suggestion
  --seed-peers=seed-peers                                Seed peers to initially connect to, in the format of comma separated "ip:port".
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +That's already pretty cool, but now it is needed to extent the application further.
```suggestion
That's already pretty cool, however, now it is necessary to extend the application further.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +To do this, you need to register additional modules and/or plugins with your application.
```suggestion
To perform this it is necessary to register additional modules and/or plugins with your application.
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Find more information on the following pages:
```suggestion
More information can be found on the following pages:
```

2021-06-03 10:08 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +If you are using NVM, install the correct version like this:
```suggestion
If you are using NVM, install the correct version as shown below:
```

2021-06-03 10:28 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Lisk Commander offers various commands related to <<initializing-a-new-blockchain-application>>, or generating skeletons for modules, transactions and plugins which can be used to conveniently get st
```suggestion
Lisk Commander offers various commands related to <<initializing-a-new-blockchain-application>> which can be used to conveniently get started with the development of a blockchain application.
```

2021-06-03 10:32 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +That's already pretty cool, but now it is needed to extent the application further.
```suggestion
```

2021-06-03 10:32 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +To do this, you need to register additional modules and/or plugins with your application.
```suggestion
To extend the application further, you need to register additional modules and/or plugins with your application.
```

2021-06-03 10:52 UTC, merged