Update the module guide - Closes #1076
LiskArchive/lisk-legacy-docs pull request #1102
Opened 2021-06-03 10:53 UTC by Tschakki

Closes #1076

2021-06-08 07:47 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The command `generate:module` already created the class `NftModule` which contains already skeletons for the most important components of a module.
```suggestion
The command `generate:module` already created the class `NftModule` which contains skeletons for the most important components of a module.
```

2021-06-08 08:05 UTC, nazarhussain requested changes

2021-06-08 08:05 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/module.adoc
> +    public transactionAssets = [CreateNFT];
It needs to be instance of the asset. 
```suggestion
    public transactionAssets = [new CreateNFT()];
```

2021-06-08 09:27 UTC, nazarhussain submitted a review, later dismissed

2021-06-10 14:22 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +  MODULEID    Module Id, should be atleast 1000 or more
```suggestion
  MODULEID    Module Id, should be at least 1000 or more
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Needs to be a string that only consists of small and capital letters [a-z,A-Z].
```suggestion
Needs to be a string that only consists of upper and lower case letters [a-z, A-Z].
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +No numbers, hyphen, etc allowed.
```suggestion
No numbers, hyphens, etc., are allowed.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +As example, we use the module name `nft` and the module ID `1000`:
```suggestion
As an example, we use the module name `nft` and the module ID `1000`:
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +First take a look at the module skeleton in `nft_module.ts`:
```suggestion
The module skeleton can be viewed in `nft_module.ts`:
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The only properties which are set at the moment are the module ID and the module name, which we defined before.
```suggestion
The only properties which are set at this point are the module ID and the module name, which were defined previously.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +To give the module a purpose, it is needed to implement certain logic inside of the module.
```suggestion
To give the module a purpose, it is necessary to implement certain logic inside of the module.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +In fact, these 2 properties make it already a complete module, which can be registered with the application.
```suggestion
In fact, with these 2 properties, it is already a complete module that can be registered with the application.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The only problem is, that this module isn't doing anything yet.
```suggestion
However, this module is not performing any functions yet.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Modules, plugins and external services can subscribe to these events.
```suggestion
Modules, plugins, and external services can subscribe to these events.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +What events, actions and reducers are used within a module, or if these interfaces are actually required at all, will be a specific individual requirement for every module; as it is heavily dependant
```suggestion
Which events, actions, and reducers are used within a module, or if these interfaces are actually required at all, will be a specific individual requirement for every module; as it is heavily dependant on which functionality the module intends to provide to the application.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The best way to understand the necessary requirements here is to look at existing examples in the Lisk SDK default modules, or examples of other blockchain applications built with the Lisk SDK, for e
```suggestion
The easiest way to understand the necessary requirements here is to look at existing examples in the Lisk SDK default modules, or examples of other blockchain applications built with the Lisk SDK, for example, the xref:{url_tutorials_hello}[] application.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +In some cases, the new module will require to store some new data in the user accounts.
```suggestion
In some cases, the new module will require storing some new data in the user accounts.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +So e.g. in case the module name is `nft`, the data will be stored under the key "nft" in each user account.
```suggestion
So for example, in case the module name is `nft`, the data will be stored under the key "nft" in each user account.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +If a module includes an account schema, it is needed to update the genesis block after registering the module with the application.
```suggestion
If a module includes an account schema, it is necessary to update the genesis block after registering the module with the application.
```

2021-06-10 14:22 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +You can use the application CLI to generate a new genesis block like this:
```suggestion
The application CLI can be used to generate a new genesis block as shown below:
```

2021-06-10 14:52 UTC, chris529 approved these changes
LGTM!

2021-06-10 15:11 UTC, merged