Add new documentation about the test suite - Closes #1074
LiskArchive/lisk-legacy-docs pull request #1110
Opened 2021-06-07 14:49 UTC by Tschakki

Closes #1074

2021-06-16 07:42 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +To get rid of this error, it is required to update the genesis block of the application.
```suggestion
To fix this error, it is required to update the genesis block of the application.
```

2021-06-16 07:42 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/module.adoc
> +import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
formatting issue?

2021-06-17 08:21 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
what do you mean exactly?

2021-06-18 09:53 UTC, ManuGowda submitted a review, later dismissed

2021-06-18 14:13 UTC, mehmetegemen requested changes

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +  getAllNFTTokensAsJSON,
Where is this function in the example? Maybe not needed?

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +If a module includes an account schema, it is necessary to update the genesis block after registering the module with the application, to update the accounts in the genesis block with the new propert
Why double dot?

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +If a module includes an account schema, it is necessary to update the genesis block after registering the module with the application, to update the accounts in the genesis block with the new propert
Why double dot?

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +For more information about the `create:genesis-block` command, run the help:
contradicts with line 89

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +The above script will create thee following output:
Double e at the "the"

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/module.adoc
> +import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
Need spaces after commas

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/module.adoc
> +import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
Manu is right, need spaces after commas

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/module.adoc
> +import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
Can't see on my device but also line is probably too long

2021-06-18 14:13 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/module.adoc
> +`getAllNFTTokensAsJSON()` is imported from a new file `nft.js`, which is created manually to stor the utility functions for the NFT module.
Stor must be store

2021-06-18 15:26 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +  getAllNFTTokensAsJSON,
It was added to the file in the module guide, which is a prerequisite for the asset guide. The file should therefore already exists with the missing functions. They are not pasted in the asset guide again, because they are not used here.

2021-06-18 15:26 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +For more information about the `create:genesis-block` command, run the help:
in what way?

2021-06-18 15:27 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +If a module includes an account schema, it is necessary to update the genesis block after registering the module with the application, to update the accounts in the genesis block with the new propert
typo

2021-06-18 15:30 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +import { BaseModule,AfterBlockApplyContext,TransactionApplyContext,BeforeBlockApplyContext,AfterGenesisBlockApplyContext } from 'lisk-sdk';
Added spaces. 
I put it all in 1 line on purpose, to make the snippet smaller.

2021-06-18 16:56 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +For more information about the `create:genesis-block` command, run the help:
Line 86 says command is `create:genesis-block` whereas line 89 says command is `genesis-block:create`

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +For more information about the `create:genesis-block` command, run the help:
:+1 `genesis-block:create` is correct

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +  $ mft genesis-block:create
this doesn't look good, `mft`?

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +To get rid of the error, either remove the unused variables or implement logic which uses them in the corresponding function.
```suggestion
To fix the error, either remove the unused variables or implement logic which uses them in the corresponding function.
```

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +		describe('schema validation', () => {
format

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +<4> `getAllNFTTokens` and `createNFTToken` are utility functions for the NFT module which are also used in thee tests for the `apply()` function.
```suggestion
<4> `getAllNFTTokens` and `createNFTToken` are utility functions for the NFT module which are also used in the tests for the `apply()` function.
```

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +TODO: Write sections / pages for functional and integration testing
is this comment ok to leave?

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/references/lisk-framework/test-suite.adoc
> +      ... 3 more items
i am not sure how much useful this is, maybe copy one delegate config and then do ...
```
{
				"encryptedPassphrase": "iterations=10&cipherText=c6eb47b7588d578602850c7c3d657515ce9c3b15f0d8335803f08825176e3fcf3da69b76af81c9b819902772f6e7738ad5ec9184589d4af43cf808130205f7560b4b1b151be74221846013fe&iv=3b4b5b901edb52521f78f0bf&salt=c2dbd7ee2ba11ae9ad20c1ffe44a8460&tag=e51a1770bae9a93af5c0f2fcd4579061&version=1",
				"hashOnion": {
					"count": 10000,
					"distance": 1000,
					"hashes": [
						"8903ea6e67ccd67bafa1c9c04184a387",
						"719142332e71b58d2cfd24aeabef0666",
						"02dcf8bd4e8427aaa0ef9af8ff903015",
						"3c2b51970af795a5d584342c603daef3",
						"208a25f33cd3f6979983228b181118f3",
						"eb67f12d52d3726628ecfb539517ea46",
						"c89a3f3edd3661436fe1150e5c2f77cf",
						"dc3636677cac81c2720187aad64d186f",
						"5465dd9c1e107d0397aa93a5e607e908",
						"1b0fa3ed0491078e5be78528687f7b14",
						"7cab3ad7089480de104c2d4b3fe58be0"
					]
				},
				"address": "463e7e879b7bdc6a97ec02a2a603aa1a46a04c80"
			},
			... 102 more items
```

2021-06-21 06:16 UTC, ManuGowda commented on modules/ROOT/pages/references/lisk-framework/test-suite.adoc
> +//TODO: Need to import the asset class from somewhere (lisk-sdk does not expose them?)
need this?

2021-06-21 08:24 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +		describe('schema validation', () => {
what do you mean?

2021-06-21 08:25 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +TODO: Write sections / pages for functional and integration testing
Yes, it is still a valid todo, we only explain unit tests in this guide atm.

2021-06-21 08:29 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/test-suite.adoc
> +//TODO: Need to import the asset class from somewhere (lisk-sdk does not expose them?)
This is a problem I have, I was not able to import the asset classes from the SDK, to actually use it to create a transaction and then post thee example output below. I left this note, to ask you how I can get the Asset class. :)

2021-06-21 10:41 UTC, ManuGowda commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +		describe('schema validation', () => {
Now it looks ok 👍🏼

2021-06-21 10:43 UTC, ManuGowda commented on modules/ROOT/pages/references/lisk-framework/test-suite.adoc
> +//TODO: Need to import the asset class from somewhere (lisk-sdk does not expose them?)
it looks like its been exposed
```
export {
	BaseModule,
	BaseAsset,
	TokenModule,
	TokenTransferAsset,
	SequenceModule,
	KeysModule,
	KeysRegisterAsset,
	DPoSModule,
	DPoSRegisterAsset,
	DPoSVoteAsset,
	DPoSUnlockAsset,
	DPoSPoMAsset,
} from './modules';
```

2021-06-21 10:44 UTC, ManuGowda approved these changes, later dismissed

2021-06-21 10:57 UTC, mehmetegemen approved these changes, later dismissed

2021-06-21 15:17 UTC, chris529 reviewed
Looks good, just a few points 👍

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +TIP: The min and max values for the different properties of the schema do not need to get validated again in the `validate()` function.
```suggestion
TIP: The minimum and maximum values for the different properties of the schema do not need to be validated again in the `validate()` function.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +In this example, we want to validate, that no NFT can be created with the name "Mewtwo".
```suggestion
In this example, we want to validate that it is not possible to create an NFT with the name "Mewtwo".
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +Of course, what to validate here exaclty is up to the developer.
```suggestion
Consequently, exactly what to validate here is up to the developer.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +The name "Mewtwo" is choosen randomly for the example.
```suggestion
The name "Mewtwo" has been chosen randomly for the example.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +If some account sends a `createNFT` transaction, with `asset.name` equal to `Mewtwo`, it will throw the error `Illegal NFT name: Mewtwo`
```suggestion
If any other account sends a `createNFT` transaction, with the `asset.name` equal to `Mewtwo`, it will throw the error `Illegal NFT name: Mewtwo`
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +To get and set the blockchain state, the `stateStore` is used again, which we know already from the lifecycle hooks of the xref:{url_guides_module_statestore}[module guide].
```suggestion
To get and set the blockchain state, the `stateStore` is used again, which we already know from the lifecycle hooks of the xref:{url_guides_module_statestore}[module guide].
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +The file `nft.js` was already used in the guide xref:{url_guides_module_nft_utils}[Creating a new module], the functions `getAllNFTTokens()`, `setAllNFTTokens()`, `createNFTToken()` can simply be add
```suggestion
The file `nft.js` was already used in the guide xref:{url_guides_module_nft_utils}[Creating a new module], the functions `getAllNFTTokens()`, `setAllNFTTokens()`, `createNFTToken()` can simply be added, if they are not present yet:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +After the application bootstrap, the default devnet genesis block was generated under `config/default/`.
```suggestion
After the application bootstrap, the default devnet genesis block will be generated under `config/default/`.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +TIP: The recommended way to generate a new genesis block, is <<using-the-cli-to-generate-a-new-genesis-block>>, as it is much more convenient.
```suggestion
TIP: The recommended and most convenient method to generate a new genesis block is <<using-the-cli-to-generate-a-new-genesis-block>>.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +If then a new module is registered with the application, which includes an account schema, it will fail with an error similar to this:
```suggestion
If a new module is then registered with the application, which includes an account schema, it will fail with an error similar to this:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +Then wait, until the new genesis block is generated.
```suggestion
Now, wait until the new genesis block is generated.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +Then copy the following content to `config/default/config.json`:
```suggestion
Now, copy the following content to `config/default/config.json`:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +Try it by running:
```suggestion
To test it, run the following command:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +For more information about the `genesis-block:create` command, run the help:
```suggestion
For more information about the `genesis-block:create` command, run the help command:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
>  If they are not included in the application, other modules need to be included, which replace their functionalities.
```suggestion
If they are not included in the application, other modules need to be included which replace their functionalities.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +==== Generation a fresh list of genesis delegates
```suggestion
==== Generating a fresh list of genesis delegates
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
>  If you don't have a list of already existing account details, it is necessary to newly generate the accounts.
```suggestion
If you don't have a list of the already existing account details, it is necessary to newly generate the accounts.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +TIP: For more information how to write unit test for the blockchain application, check out the xref:{url_guides_testing}[] guide.
```suggestion
TIP: For more information on how to write a unit test for the blockchain application, check out the xref:{url_guides_testing}[] guide.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The implementation of the function goes as follows:
```suggestion
The implementation of the function is shown below:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +* a new module has been generated like described in the guide xref:{url_guides_module}[].
```suggestion
* a new module has been generated as described in the guide xref:{url_guides_module}[].
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +* a new asset has been generated like described in the guide xref:{url_guides_asset}[].
```suggestion
* a new asset has been generated as described in the guide xref:{url_guides_asset}[].
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +To test the functionality of modules, plugins or assets conveniently, adjust the already generated test skeletons in the `test` folder of your application.
```suggestion
To conveniently test the functionality of modules, plugins, or assets, adjust the already generated test skeletons in the `test` folder of your application.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +It is already possible to run the test at this point, though only the most basic tests will be already implemented.
```suggestion
It is already possible to run the test at this point, though only the most basic tests will be implemented.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +The test results are then shown in the console:
```suggestion
The test results can then be viewed in the console:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +Use the existing structure to implement the tests needed for the module, and add more tests as required.
```suggestion
Use the existing structure to implement the tests required for the module, and add more tests as needed.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +The test skeleton for the asset contains already a few simple test right from the beginning.
```suggestion
The test skeleton for the asset already contains already a few simple tests right from the beginning.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +The rest of the tests needs to be created by the developer, to test all the custom logic of the asset, which was implemented after the initialization of the application.
```suggestion
The remainder of the tests will need to be created by the developer, to test all the custom logic of the asset which was implemented after the initialization of the application.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +In this example, we want to write unit tests for the example asset from the previous guide xref:{url_guides_asset}[].
```suggestion
This example shows how to write unit tests for the example asset from the previous guide xref:{url_guides_asset}[].
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +<3> `NftModule`: Used in `createDefaultAccount()` to create a default account with the correct accouunt properties.
```suggestion
<3> `NftModule`: is used in the `createDefaultAccount()` to create a default account with the correct account properties.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +As a reminder, the `validate()` function of the createNFT asset looks like this:
```suggestion
As a reminder, the `validate()` function of the createNFT asset is shown below:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +To verify that the function is implemented correctly, write 2 tests to check, if:
```suggestion
To verify that the function is implemented correctly, write 2 tests to check if the following occurs:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +In the first test, where an error is expected, a context with an invalid `asset` parameter with `name: 'Mewtwo'` is created, whereas in the second test a valid `name` property is passed
```suggestion
In the first test, where an error is expected, a context with an invalid `asset` parameter with the `name: 'Mewtwo'` is created, whereas in the second test a valid `name` property is passed.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +As a reminder, the `apply()` function of the createNFT asset looks like this:
```suggestion
As a reminder, the `apply()` function of the createNFT asset is shown below:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +To verify that the function is implemented correctly, write 4 tests to check, if:
```suggestion
To verify that the function is implemented correctly, write 4 tests to check if the following occurs:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +. it updates sender account with a unique NFT ID
```suggestion
. it updates the sender account with a unique NFT ID
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +Similar to the unit tests for the `validate()` function, we prepare a context using `createApplyAssetContext()` for the `apply()` function which can be passed to the function when calling it in each
```suggestion
Similar to the unit tests for the `validate()` function, a context is prepared using the `createApplyAssetContext()` for the `apply()` function which can be passed to the function when calling it in each test.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +As the context is for every test the same, prepare everything in the `beforeEach()` hook and directly call the `apply()` function with the context in each test.
```suggestion
As the context is the same for every test, it is necessary to prepare everything in the `beforeEach()` hook and directly call the `apply()` function with the context in each test.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +The tests for the `valid cases` test are implemented like shown below:
```suggestion
The tests for the `valid cases` test are implemented as shown below:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +The test for the `invalid cases` test is implemented like shown below:
```suggestion
The test for the `invalid cases` test is implemented as shown below:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +After the tests have been implemented, run the test suite again to check, if all tests pass successfully:
```suggestion
After the tests have been implemented, run the test suite again to check if all tests pass successfully:
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/test-suite.adoc
> +A default configuration for a blockchain applicaiton.
```suggestion
A default configuration for a blockchain application.
```

2021-06-21 15:17 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/test-suite.adoc
> +==== Paramters
```suggestion
==== Parameters
```

2021-06-21 15:28 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +If some account sends a `createNFT` transaction, with `asset.name` equal to `Mewtwo`, it will throw the error `Illegal NFT name: Mewtwo`
```suggestion
If any account sends a `createNFT` transaction, with `asset.name` equal to `Mewtwo`, it will throw the error `Illegal NFT name: Mewtwo`
```

2021-06-21 15:31 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/genesis-block.adoc
> +Try it by running:
```suggestion
To start it, run the following command:
```

2021-06-21 15:35 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +<3> `NftModule`: Used in `createDefaultAccount()` to create a default account with the correct accouunt properties.
```suggestion
<3> `NftModule`: is used in `createDefaultAccount()` to create a default account with the correct account properties.
```

2021-06-21 15:38 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +Similar to the unit tests for the `validate()` function, we prepare a context using `createApplyAssetContext()` for the `apply()` function which can be passed to the function when calling it in each
```suggestion
Similar to the unit tests for the `validate()` function, a context is prepared using `createApplyAssetContext()` for the `apply()` function which can be passed to the function when calling it in each test.
```

2021-06-21 15:39 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/testing.adoc
> +As the context is for every test the same, prepare everything in the `beforeEach()` hook and directly call the `apply()` function with the context in each test.
```suggestion
As the context is the same for every test, prepare everything in the `beforeEach()` hook and directly call the `apply()` function with the context in each test.
```

2021-06-21 15:42 UTC, merged