List supported platforms in SDK docs v5 -Closes #1108
LiskArchive/lisk-legacy-docs pull request #1111
Opened 2021-06-07 15:53 UTC by chris529

2021-06-08 07:53 UTC, Tschakki requested changes
The note should be added in the Quickstart and Setup guides.

Might be good to create the note as a partial.

Also please make sure to mention the specific versions of operating systems which are supported.

And provide the information in an easy to read way, bullet points would be nice for example.

2021-06-14 15:58 UTC, chris529 commented
Hey Mona! Good points, I think it looks better now.

2021-06-15 08:56 UTC, Tschakki requested changes

2021-06-15 08:56 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +* 20.04.02 (LTS) +
```suggestion
* 18.04 (LTS)
* 20.04 (LTS)
```

no need to mention patch versions here

2021-06-15 08:56 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +* 20.04.02 (LTS) +
```suggestion
* 18.04(LTS) 
* 20.04 (LTS) 
```

2021-06-15 08:56 UTC, Tschakki commented on modules/ROOT/partials/install-node.adoc
> +and ensure that the latest version is used. As previously mentioned, please be aware that both the MacOS and Ubuntu operating systems are supported, and that the MS Windows operating system is not su
please remove this sentence, it is not really fitting here.

2021-06-15 08:56 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +=== Operating Systems
This whole section should e moved to the Quickstart guide.

2021-06-15 12:03 UTC, chris529 commented on modules/ROOT/partials/install-node.adoc
> +and ensure that the latest version is used. As previously mentioned, please be aware that both the MacOS and Ubuntu operating systems are supported, and that the MS Windows operating system is not su
OK, now done 👍

2021-06-15 12:50 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +=== Operating Systems
OK, now done 👍

2021-06-17 07:59 UTC, Tschakki requested changes

2021-06-17 07:59 UTC, Tschakki commented on modules/ROOT/partials/install-node.adoc
> +and ensure that the latest version is used.
why this change? the sentence sounds weird to me like this.

2021-06-22 08:59 UTC, chris529 commented on modules/ROOT/partials/install-node.adoc
> +and ensure that the latest version is used.
Apologies, this was a typo error. I have now modified it 👍

2021-06-22 11:44 UTC, Tschakki approved these changes, later dismissed
LGTM! I left only a suggestion for the header title, which just came to my mind :)

2021-06-22 11:44 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +=== Operating Systems
```suggestion
=== Supported Operating Systems
```

2021-06-22 11:44 UTC, Tschakki commented on modules/ROOT/pages/quickstart.adoc
> +== Operating Systems
```suggestion
== Supported Operating Systems
```

2021-06-23 09:12 UTC, merged