Glossary updates in SDK docs v5 - Closes #1117
LiskArchive/lisk-legacy-docs pull request #1118
Opened 2021-06-16 12:48 UTC by chris529

Faucet and Validator descriptions added in Glossary.

Closes #1117

2021-06-17 08:03 UTC, Tschakki requested changes

2021-06-17 08:03 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +In addition, the Lisk faucet plugin has the ability to send tokens to different accounts from a faucet.
This sentence sounds weird. What exactly are you referring to?

2021-06-17 08:03 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The validator is essentially a validation library according to the Lisk Protocol. The @liskhq/lisk-validator package is a wrapper of validation packages, that includes custom validation utilities rel
I don't think this is the validator wee want to explain here. This should refer to validators in the DPoS system. Please clarify, if and how we want to use the word validator at all, because we always speak of delegates in the documentation at the moment.

2021-06-17 13:18 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +In addition, the Lisk faucet plugin has the ability to send tokens to different accounts from a faucet.
OK, I have reworded it 👍

2021-06-17 13:18 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The validator is essentially a validation library according to the Lisk Protocol. The @liskhq/lisk-validator package is a wrapper of validation packages, that includes custom validation utilities rel
Also have tried to reword it accordingly 👍

2021-06-17 15:36 UTC, Tschakki requested changes

2021-06-17 15:36 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +In addition, the Lisk faucet plugin has the ability to send tokens to different accounts from a faucet.
Hm, I was not really referring to the first sentence, as you see my comment is under the third sentence.

For me it is confusing to say "in addition", as it is not really something additionally, as this is already implied by the second sentence.

2021-06-17 15:36 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Lisk has a faucet plugin for the Lisk Framework that provides a user interface to receive an certain amount of tokens on request.
This I would keep or update to something like this

```suggestion
A Faucet is generally defined in the blockchain world as tool where users can receive a certain amount of tokens for free. For Lisk blockchain apps, the faucet plugin can be registered with the application to provide a basic faucet, which is useful during the development and for proof-of-concept blockchain applications.
```

thats my suggestion :)

2021-06-17 15:36 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A validator can be described as a user who is authorized to secure the network. In a DPoS system there are a fixed number of validators that are able to vote on who will validate transactions. The va
We should clarify if and how we want to use the word validator in the docs.
As mentioned, we are now only referring to them as delegates, so I wonder why add this entry to the glossary.

2021-06-21 12:20 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Lisk has a faucet plugin for the Lisk Framework that provides a user interface to receive an certain amount of tokens on request.
Hey Mona, It looks very good, although I just noticed a couple of minor errors here so I have slightly adapted it and cut and pasted the following into this branch: 
"A Faucet is generally defined in the blockchain world as a tool whereby users can receive a certain amount of tokens for free. For Lisk blockchain apps, the faucet plugin can be registered with the application to provide a basic faucet, which is useful during the development phase, and also for proof-of-concept blockchain applications".

2021-06-21 12:26 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A validator can be described as a user who is authorized to secure the network. In a DPoS system there are a fixed number of validators that are able to vote on who will validate transactions. The va
Agreed..After our discussion, I did some research with a view to possibly adding in the term'Validators' under the ''Delegate'' description. However, I am now of the opinion that actually we don't need to mention this term yet (at least not at his point anyhow). so if you are in agreement, I have just deleted the Validator description.

2021-06-22 11:35 UTC, Tschakki approved these changes
Thanks!

2021-06-22 11:39 UTC, merged