Add page about performance monitoring, Closes #107
LiskArchive/lisk-legacy-docs pull request #112
Opened 2018-11-15 10:40 UTC by Tschakki

Closes #107

2018-11-15 14:31 UTC, nazarhussain requested changes

2018-11-15 14:31 UTC, nazarhussain commented on user-guide/monitoring/monitoring.md
> +
Please mention here what are the blew given points.

2018-11-15 14:31 UTC, nazarhussain commented on user-guide/monitoring/monitoring.md
> +### Register on Website
Better to change it to "Get New Relic license key"

2018-11-15 14:31 UTC, nazarhussain commented on user-guide/monitoring/monitoring.md
> +### Start Lisk Core node
Start or Restart if already running.

2018-11-15 14:31 UTC, nazarhussain commented on user-guide/monitoring/monitoring.md
> +npm test -- mocha:untagged:network
Unit tests can't be used for newrelic monitoring. As they don't execute in the context of running app.

2018-11-15 14:31 UTC, nazarhussain commented on user-guide/monitoring/monitoring.md
> +![New Relic UI](new-relic-ui.png)
You may refer or copy the output we used previously in two other issues. API performance benchmarking bu Lucas, and BYTE comparison by Mehmat.

2018-11-15 16:14 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +npm test -- mocha:untagged:network
I added a note with that info and removed unit test from examples.

2018-11-16 11:22 UTC, ghost requested changes

2018-11-16 11:22 UTC, fchavant commented on user-guide/monitoring/monitoring.md
> +bash lisk.sh start # start lisk core binary
This will not restart core, `./lisk.sh reload` will.

2018-11-16 11:22 UTC, fchavant commented on user-guide/monitoring/monitoring.md
> +docker start container_id # start lisk core docker
This will not restart a container, `docker restart <container>` will. To keep in line our docker example we should recommend adding `NEW_RELIC_LICENSE_KEY` to `docker-compose.override.yml` and running `docker-compose up -d`.

2018-11-16 13:26 UTC, MaciejBaj requested changes

2018-11-16 13:26 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +We use [New Relic](http://newrelic.com/) to monitor the activities inside of the application. It enables to have detailed insight
```suggestion
We use [New Relic](http://newrelic.com/) to monitor the activities inside of the application. It enables to have detailed insight into the system and keep track of the performance of any activity, e.g. an HTTP API call or a background process from Lisk Core jobs queue.
```

2018-11-16 13:26 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +of the system and keep track of performance of each activity. E.g. an HTTP API call or a background job from queue.
```suggestion

```

2018-11-16 13:26 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Below are the steps you need to follow to get the statistics for New Relic:
Following steps should provide you with the insights of why and how to monitor your Lisk Core node using NewRelic instrumentation: 
```suggestion
Following steps should provide you with the insights of why and how to monitor your Lisk Core node using NewRelic instrumentation: 
```

2018-11-16 13:26 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +   3. [Start Lisk Core node](#restart-lisk-core-node)
Is it (Re)start?

2018-11-16 14:22 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +~/lisk_repo $ npm start
Just to be not confusing, I would use the same command here as we already described above to start the node.
```suggestion
~/lisk_repo $ pm2 start lisk
```

2018-11-16 15:02 UTC, Tschakki reviewed
Overall really great job @nazarhussain :)
Just made a few grammar corrections.

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +3. It take couple of minutes to show analyzed results in newrelic interface so be patience.
```suggestion
3. It may take a couple of minutes to show the analyzed results in the New Relic interface so be patient. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +Now our results will be compiled lets look towards it. First login to https://rpm.newrelic.com, and select `APM` from top menu.
```suggestion
Now login to https://rpm.newrelic.com, and select `APM` from top menu. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +The first screen you see will be list of applications. Depending on which network you run your node in, you will see the applications. As shown in the image below.
```suggestion
The first screen is the list of applications. Depending on which network you run your node in, you will see the application title as shown in the image below. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +To know fine grained details of this dashboard, would be recommended to read https://learn.newrelic.com/courses/intro_apm. But for now since we are interested only in the our use case of `GET /api/tr
```suggestion
To know fine grained details of this dashboard, please read https://learn.newrelic.com/courses/intro_apm. For now since we are interested only in our use case of `GET /api/transactions` we will move to transactions page. Please select "Transactions" from the left menu in above screen. See detailed instructions in the below image. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +In the above image the most valuable information we had is highlighted in the rectangle, with key information:
```suggestion
In the above image the most valuable information for us is highlighted in the rectangle, which provides us with the following information: 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +1. Most of the time (56%) was spent in ExpressJS which is a nodejs module.
```suggestion
1. Most of the time (56%) was spent in ExpressJS which is a Node.js module. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +3. Querying to database table `delegates` was quick
```suggestion
3. Querying to database table `delegates` was quick.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +If you want this information in a tabular form to present somewhere. Please click on "Show all transactions table" link. Then you will see a view like this.
```suggestion
If you want this information in a tabular form to present somewhere, please click on "Show all transactions table" link. Then you will see a view like this:
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +1. In selected time range we made 14252 total requests to `GET /api/transactions`
```suggestion
1. In selected time range we made 14252 total requests to `GET /api/transactions`.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +2. The worst request took 2.17 seconds time
```suggestion
2. The worst request took 2.17 seconds time.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +3. The fastest request took 10ms
```suggestion
3. The fastest request took 10ms.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +Now if we want to debug deeper which transactions actually took 2.17 seconds, please go back to old screen, scroll down a bit and you wills see transaction traces.
```suggestion
Now if we want to debug deeper which transactions actually took 2.17 seconds, please go back to previous screen, scroll down a bit and you will see transaction traces. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +Here you can see individual transaction which took longer time and considered slow. The threshold which defines the slow transactions are configured in file `newrelic.js` under `transaction_tracer.ex
```suggestion
Here you can see individual transaction which took longer time and considered slow. The threshold which defines the slow transactions is configured in file `newrelic.js` under `transaction_tracer.explain_threshold`. Which is currently 100ms, so every request took more than 100ms will be considered slow and will be logged as trace in New Relic. Let's debug further and see what makes this request slow, by clicking on any of the trace links in the list. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +Now coming back to original information we want to achieve, we need find the database query which is taking most of the time. For it click on the left side menu for "Database". There sort by "Most ti
```suggestion
Now coming back to the original information we want to achieve, we need to find the database query which is taking most of the time. To do this, click on the left side menu for "Database". There sort by "Most time consuming" and then select top of the list.  
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +Hope above use case helps you to understand the usage and benefits of NewRelic. Please let us know if you want to know more.
```suggestion
We hope the above use case helps you to understand the usage and benefits of New Relic. Please let us know if you want to know more. 
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +2. Had you exported the license key on the node where you are running Lisk
```suggestion
2. Have you exported the license key on the node where you are running Lisk?
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +3. Had you selected proper time range in New Relic APM
```suggestion
3. Have you selected proper time range in New Relic APM?
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +**Is the performance measures are consistent?**
```suggestion
**Are the performance measures consistent?**
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +1. Performance of the machine may effect the behavior of interacting with the node
```suggestion
1. Performance of the machine may effect the behavior of interacting with the node.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +2. You can create alert policies on New Relic to inform you when your app taking more memory
```suggestion
2. You can create alert policies on New Relic to inform you when your app taking more memory.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +3. You can set alerts to see if database is getting slow
```suggestion
3. You can set alerts to see if database is getting slow.
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +1. Are you using a valid license key to your account
```suggestion
1. Are you using a valid license key to your account?
```

2018-11-16 15:02 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +4. Are you looking on right page e.g. You may be searching web transactions but you had selected Non-Web transactions in UI.
```suggestion
4. Are you looking on right page? E.g. you may be searching web transactions but you had selected Non-Web transactions in UI.
```

2018-11-16 15:06 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +1. You may disable the cache on the node to get real performance analysis.
Might be helpful to add a short description here how to disable cache.

```suggestion
1. You may disable the cache on the node to get real performance analysis. To do this, set `cacheEnabled` in configuration to `false`.
```

2018-11-16 15:30 UTC, nazarhussain submitted a review, later dismissed

2018-11-16 15:32 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Then, save your changes and update docker, so that it can use the new environment variable.
```suggestion
Then, save your changes and update Dockerfile, so that it can use the new environment variable.
```

2018-11-16 15:33 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +The second way of adding the license key is by editing `newrelic.js` which can be found in the root directory of the Lisk Core installation.
```suggestion
The second way of adding the license key is to edit `newrelic.js` file which can be found in the root directory of the Lisk Core installation.
```

2018-11-16 15:39 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +As second step, keep your node busy by running various API request against it.
An explanation of why it's important to keep your node busy is missing here. Please add it.

Also, only one way of keeping a node busy is given in example here - by running various API requests. Please make it clear that NewRelic can be also use to monitor more actions (snapshotting, syncing etc)

2018-11-16 15:42 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Now start making some requests with siege.
usin
```suggestion
Now start making some requests using Siege:
```

2018-11-16 15:45 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +The script will automatically be finished in 5 minutes and then we proceed to results. But during that time please keep in mind:
```suggestion
The script will automatically send 10 parallel requests 
```
```suggestion
The script will automatically be keep on sending requests against your node for 5 minutes (`-t 5m`). During that time please keep in mind: 
```

2018-11-16 15:46 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +The script will automatically be finished in 5 minutes and then we proceed to results. But during that time please keep in mind:
```suggestion
The script will automatically keep on sending the HTTP requests against your node for 5 minutes (`-t 5m`). During that time please keep in mind: 
```

2018-11-16 15:47 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +2. You should use some real data e.g. testnet to run your tests to have viable results.
We're sending the requests against of the port 4000 though, which suggest it's a devnet.

2018-11-16 15:53 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Now our results will be compiled lets look towards it. First login to https://rpm.newrelic.com, and select `APM` from top menu.
```suggestion
To see the NewRelic instrumentation results, please log in to https://rpm.newrelic.com, and select `APM` from the top menu. 
```

2018-11-16 15:55 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Please select the specific application by clicking its name. And you will see following dashboard.
```suggestion
Please select the specific application by clicking its name. You will see following dashboard.  
```

2018-11-16 15:59 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +To know fine grained details of this dashboard, would be recommended to read https://learn.newrelic.com/courses/intro_apm. But for now since we are interested only in the our use case of `GET /api/tr
```suggestion
To know fine-grained details of this dashboard, please read https://learn.newrelic.com/courses/intro_apm. For now, since we only executed the HTTP requests against our node (`GET /api/transactions`) there is only one section having interesting results. Please select "Transactions" from the left menu in above screen. See detailed instructions in the below image. 
```

2018-11-16 16:04 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +2. It involved one database view and one table during the transactions.
```suggestion
2. During the experiment, one database view (`trs_list`) and one database table (`trs`) were involved on the persistence layer.
```

2018-11-16 16:08 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +3. Querying to database table `delegates` was quick
.. it took X% of time.

2018-11-16 16:09 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +3. Querying to database table `delegates` was quick
", whereas the query to database view `trs_list` was 3 times more expensive - X& of time.

2018-11-16 16:09 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +4. While query to database view `trs_list` was a bit expensive.
Then, after https://github.com/LiskHQ/lisk-docs/pull/112/files#r234259649, this line can be removed.

2018-11-16 16:14 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Here you can see individual transaction which took longer time and considered slow. The threshold which defines the slow transactions are configured in file `newrelic.js` under `transaction_tracer.ex
```suggestion
Here you can see an overview of an individual transaction which took longer time and is considered as "slow". The threshold which defines the "slow" transactions is configured in file `newrelic.js` under `transaction_tracer.explain_threshold`, which is currently 100ms- every request which took more than 100ms will be considered as "slow" and logged as the trace by NewRelic. Let's debug further and verify what made this request "slow", by clicking on any of the trace links in the list. 
```

2018-11-16 16:16 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +So you can see here most of time was spent in two functions `modules.transactions.shared.getTransactions` and `Middleware: bound logClientConnections`. You can go to trace detail to see more informat
```suggestion
As shown on the above trace summary, the most of the transaction's time was spent in two functions `modules.transactions.shared.getTransactions` and `Middleware: bound logClientConnections`. You can go to trace detail to see more information and call stack. You can also click on "Database queries" to see which queries were executed during this request.
```

2018-11-16 16:18 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Now coming back to original information we want to achieve, we need find the database query which is taking most of the time. For it click on the left side menu for "Database". There sort by "Most ti
```suggestion
It's also possible to find the database query which is taking most of the time. To do it, please click on the left side menu for "Database" and then sort by "Most time consuming" and then select the top of the list.  
```

2018-11-16 16:19 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Scroll down on this page.
What's that?

2018-11-16 16:21 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +So here we can find information as seen:
```suggestion
By analyzing the above diagrams, we can conclude the following:
```

2018-11-16 16:21 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +1. The slowest queries in the system are queries for `trs_list` view.
Overall during the system or only during the experiment?

2018-11-16 16:22 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +2. For that view the slowest query is the `SELECT count(*) FROM trs_list` which took 2.13 seconds.
It's not clear what is "that view", please consolidate this information with point 1.

2018-11-16 16:23 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +4. If you click on the top slow query, you will notice the query was executed during `GET /api/transactions`
"." missing.

2018-11-16 16:24 UTC, MaciejBaj commented on user-guide/monitoring/monitoring.md
> +Hope above use case helps you to understand the usage and benefits of NewRelic. Please let us know if you want to know more.
contact us, how?

2018-11-16 16:25 UTC, MaciejBaj requested changes
Please reply to the suggested changes and comments I left. Cheers, great job on that!

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +vim docker/docker-compose.override.yml
We should be agnostic on which tools to use.
`vim` is just an editor and any editor can be used.
I suggest just saying that the license key should be added to the `docker-compose.override.yml` file and then show how it will look like.

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +:wq # save changes and quit vim afterwards
Same as before. This is not necessary as the user should use the editor he/she is more familiar with.

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +vim newrelic.js
Same here.

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +If you use "vim", press `i` to get into the insert mode.
Same here.

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +:wq # save changes and quit vim afterwards
Same here.

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +To know fine grained details of this dashboard, please read https://learn.newrelic.com/courses/intro_apm. For now since we are interested only in our use case of `GET /api/transactions` we will move
Maybe its worth it to mention that the transactions page has nothing to do with Lisk transactions itself. It's just how New Relic group the requests to be analysed.

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +2. The worst request took 2.17 seconds time.
```suggestion
2. The slowest request took 2.17 seconds time.
```

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +Here you can see individual transaction which took longer time and considered slow. The threshold which defines the slow transactions is configured in file `newrelic.js` under `transaction_tracer.exp
```suggestion
Here you can see individual transaction which took longer time and considered slow. The threshold which defines the slow transactions is configured in file `newrelic.js` under `transaction_tracer.explain_threshold`. Which is currently 100ms, so every request which takes more than 100ms will be considered slow and will be logged as trace in New Relic. Let's debug further and see what makes this request slow, by clicking on any of the trace links in the list. 
```

2018-11-19 09:42 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +1. As far as you are using same machine specification to run different scenarios, the stats will consistent.
```suggestion
1. As far as you are using same machine specification to run different scenarios, the stats will be consistent.
```

2018-11-19 10:39 UTC, nazarhussain submitted a review, later dismissed

2018-11-20 09:19 UTC, nazarhussain commented on user-guide/monitoring/monitoring.md
> +vim docker/docker-compose.override.yml
We may be following same pattern around documentation, so we should fix those everywhere. https://github.com/LiskHQ/lisk-docs/issues/117

2018-11-20 10:53 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +![info note](../../info-icon.png "Info Note") | To clarify New Relic transactions have no relation with Lisk Transactions. Its just the grouping term, newrelic use to show analytics.
```suggestion
![info note](../../info-icon.png "Info Note") | To clarify, New Relic transactions have no relation with Lisk Transactions. It's just the grouping term New Relic use to show analytics. 
```

2018-11-20 10:58 UTC, lsilvs submitted a review, later dismissed

2018-11-21 10:08 UTC, ghost requested changes

2018-11-21 10:08 UTC, fchavant commented on user-guide/monitoring/monitoring.md
> +We use [New Relic](http://newrelic.com/) to monitor the activities inside of the application. It enables to have detailed insight into the system and keep track of the performance of any activity, e.
> It enables to have detailed
That does not sound right.

2018-11-21 10:08 UTC, fchavant commented on user-guide/monitoring/monitoring.md
> +available and set:
```suggestion
set:
```

2018-11-21 10:08 UTC, fchavant commented on user-guide/monitoring/monitoring.md
> +      - NEW_RELIC_LICENSE_KEY=XXXXXXXXX
Above we used `export NEW_RELIC_LICENSE_KEY=your-personal-license-key` and here `NEW_RELIC_LICENSE_KEY=XXXXXXXXX`; shouldn't we stay consistent?

2018-11-21 10:08 UTC, fchavant commented on user-guide/monitoring/monitoring.md
> +```bash
This isn't a bash script.

2018-11-21 10:18 UTC, nazarhussain submitted a review, later dismissed

2018-11-21 10:20 UTC, Tschakki commented on user-guide/monitoring/monitoring.md
> +      - NEW_RELIC_LICENSE_KEY=XXXXXXXXX
I will change it to XXXX then, as we already use that in migration and configuration pages

2018-11-21 10:24 UTC, Nazgolze requested changes

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +We use [New Relic](http://newrelic.com/) to monitor the activities inside of the application. It enables to have detailed insight into the system and keep track of the performance of any activity, e.
I would reword the second sentence.
```suggestion
We use [New Relic](http://newrelic.com/) to monitor the activities inside of the application. It enables detailed insight into the system and keeps track of the performance of any activity, e.g. an HTTP API call or a background process from Lisk Core jobs queue.
```

``

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +First thing you need to do is registering an account at https://rpm.newrelic.com, if you have not already done that.
```suggestion
First thing you need to do is register an account at https://rpm.newrelic.com, if you have not already done that.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +To enable the performance monitoring on your node make sure you have an environment variable `NEW_RELIC_LICENSE_KEY`
```suggestion
To enable the performance monitoring on your node, make sure you have an environment variable `NEW_RELIC_LICENSE_KEY`
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +Then, save your changes and update Dockerfile, so that it can use the new environment variable.
```suggestion
Then, save your changes and update Dockerfile so that it can use the new environment variable.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +Inside the file search for the option `license_key` and add your license key as string value.
```suggestion
Inside of the file, search for the option `license_key` and add your license key as string value.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +Then start the node normally,
```suggestion
Then start the node normally.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +To monitor activities in the system, you need to perform some. So keep your node busy by performing actions like taking a snapshot, synching your node, or running various API request against it.
```suggestion
To monitor activities in the system, you need to perform some. So keep your node busy by performing actions like taking a snapshot, syncing your node, or running various API request against it.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +`-c`: Number of requests to perform in parallel.
To make consistent with the option above
```suggestion
`-c`: The number of requests to perform in parallel.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +2. You might not see the viable results if your development Blockchain dataset is empty. This could be changed by running your tests against the Testnet data.
```suggestion
2. You might not see the viable results if your development blockchain dataset is empty. This could be changed by running your tests against the Testnet data.
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +To know fine-grained details of this dashboard, please read https://learn.newrelic.com/courses/intro_apm. For now, since during the experiment we only executed the HTTP requests against our node (`GE
```suggestion
To know fine-grained details of this dashboard, please read https://learn.newrelic.com/courses/intro_apm. For now, since during the experiment we only executed the HTTP requests against our node (`GET /api/transactions`), there is only one section having interesting results. Please select "Transactions" from the left menu in above screen. See detailed instructions in the below image. 
```

2018-11-21 10:24 UTC, Nazgolze commented on user-guide/monitoring/monitoring.md
> +It's also possible to find the database query which is taking most of the time. To do it, please click on the left side menu for "Database" and then sort by "Most time consuming" and then select the
```suggestion
It's also possible to find the database query which is taking most of the time. To do this, please click on the left side menu for "Database" and then sort by "Most time consuming" and then select the top of the list.   
```

2018-11-21 12:58 UTC, Nazgolze submitted a review, later dismissed

2018-11-21 13:16 UTC, ghost approved these changes

2018-11-21 13:25 UTC, Nazgolze approved these changes

2018-11-21 17:04 UTC, MaciejBaj approved these changes

2018-11-22 08:08 UTC, lsilvs approved these changes

2018-11-22 09:01 UTC, merged