Small Updates in Lisk Service docs - Closes #1144
LiskArchive/lisk-legacy-docs pull request #1154
Opened 2021-07-22 08:26 UTC by Tschakki

Closes #1144

2021-08-04 11:45 UTC, nagdahimanshu requested changes
Looks good apart from some minor changes.

2021-08-04 11:45 UTC, nagdahimanshu commented on modules/ROOT/pages/setup/source.adoc
> +The market service is required to be started separately:
There is no need to start `market` service separately. Running `npm run start` in root dir would start all services. We can remove this section.

2021-08-04 11:45 UTC, nagdahimanshu commented on modules/ROOT/pages/index.adoc
>  :url_api_mainnet: https://service.lisk.io/api/
We have already updated domain lisk.io to lisk.com with the PR #[664](https://github.com/LiskHQ/lisk-service/pull/664). I think it should reflect here as well. We can confirm it with @MichalTuleja

2021-08-04 11:45 UTC, nagdahimanshu commented on modules/ROOT/pages/configuration/docker.adoc
> +      ENABLE_HTTP_API: http-status,http-version
```suggestion
      ENABLE_HTTP_API: http-status,http-version
```
It should be:
```
ENABLE_HTTP_API=http-version1-compat,http-status,http-version2
ENABLE_WS_API=rpc,blockchain,rpc-v2
```

2021-08-05 07:00 UTC, nagdahimanshu submitted a review, later dismissed
LGTM 👍

2021-08-05 11:34 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
>  :url_api_mainnet: https://service.lisk.io/api/
👍

2021-08-05 11:52 UTC, MichalTuleja requested changes
Looks almost perfect, some sections are missing options that were recently added to the 0.4.2.

Compare this document: https://github.com/LiskHQ/lisk-service/blob/v0.4.2/docs/config_options.md

Can you also please add the new sections such as [caching](https://github.com/LiskHQ/lisk-service/blob/v0.4.2/docs/config_options.md#caching)?

2021-08-05 11:52 UTC, MichalTuleja commented on modules/ROOT/pages/references/configuration.adoc
> +EXCHANGERATESAPI_IO_API_KEY=EXCHANGERATESAPI_IO_API_KEY
That would be meaningful to add some indicator that key is custom and not mandatory (can be left empty).

2021-08-10 13:32 UTC, MichalTuleja approved these changes
LGTM 👍

2021-08-11 14:19 UTC, merged