Add LNS tutorial - Closes #1151
LiskArchive/lisk-legacy-docs pull request #1158
Opened 2021-07-26 11:58 UTC by Tschakki

Closes #1151

2021-09-20 14:10 UTC, shuse2 requested changes
Good detailed contents, but It's a quite big tutorial.
What is the main purpose of the tutorial (ie: the learning points which you want developer to understand?
Maybe it's good to divide into different parts?

2021-09-20 14:10 UTC, shuse2 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +=== Node.js
Do we add these things to every tutorial? maybe, we could omit this with `if you havent prepared the environment, try tutorial XXX`?
Reason being we would need to update everywhere if we change the version etc

2021-09-20 14:10 UTC, shuse2 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +== Bootstrapping the default application
Similar to above but maybe we can link to dedicated tutorial for the bootstrap?
Reason being we would need to update everywhere if we change the bootstrapping

2021-09-20 14:10 UTC, shuse2 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +image:tutorials/lns/lns-overview.png[]
It's too hard read anything on yellow 🤔

2021-09-20 14:10 UTC, shuse2 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +== LNS application overview
maybe, it would be nice to say what each hooks/asset does as well?

2021-09-20 14:10 UTC, shuse2 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +    $id: 'lns/register-asset',
indentation is wrong here

2021-09-21 14:49 UTC, Tschakki commented
@shuse2 the main learning points are summarized on the tutorials overview page: https://liskhq.github.io/lisk-docs/lisk-sdk/tutorials/index.html

Yeah, maybe I could divide it in the following parts:
- Part 1: Development
- Part 2: Frontend
- Part 3: CLI
- Part 4: Testing

What do you think?

2021-09-22 14:45 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +== Bootstrapping the default application
Good point. I adjusted now the setup guide and refer to it in the LNS tutorial

2021-09-22 14:46 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +image:tutorials/lns/lns-overview.png[]
yeah, but its same color scheme for all our app diagrams. I would update this in aseparate issue.

2021-09-22 14:49 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +== LNS application overview
hm, I think the assets are described, and the module does not contain any lifecycle hooks.

2021-09-23 20:12 UTC, shuse2 approved these changes, later dismissed
Following current structure, i think it looks good.
Below is more for some improvements in the future

What I meant by
> What is the main purpose of the tutorial (ie: the learning points which you want developer to understand?

is that each tutorial should have goal to explain specific feature we provide (this doesn't need to be stated in the documentation itself).
For example, `Hello World` is explaining how to create module / plugin etc, so that NFT should explain some new feature. and maybe for this tutorial how to use faucet/dashboard, or commander?

> Part 1: Blockchain
Part 2: Frontend
Part 3: CLI
Part 4: Testing

the separation looks good. Also, if there are some part already explained in other tutorial it can reference other tutorial and just give the result.

2021-09-23 20:12 UTC, shuse2 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +│   │   │   └── lns.ts
```suggestion
│   │   │   └── lns
```
same for other places

2021-09-24 14:20 UTC, Tschakki commented
> What I mean is that each tutorial should have goal to explain specific feature we provide (this doesn't need to be stated in the documentation itself).
For example, Hello World is explaining how to create module / plugin etc, so that NFT should explain some new feature. and maybe for this tutorial how to use faucet/dashboard, or commander?

@shuse2 

I think these specific learning topics should mainly bee covered in the How-to Guides.
For most of the topics, a guide is already existing. If we explain something new inn a tutorial (i.e. here, how to extend the CLI, and how to add the faucet plugin) - then this actually indicates a respective how-to guide is missing.

The tutorials are not really redundant in their content, even if they don't cover any completely new topics, because they just explain step by step how to build a specific blockchain app. I don't think it makes sense for the NFT tutorial to just refer to the Guide "how to create a module", because the implementation of the module is very specific to the application, I cannot refer to any other guide for this.

So imho criteria for tutorials to add is, are it interesting use cases, and not that it covers completely new topics how to do something (that is what the guides are for).

2021-09-28 08:01 UTC, chris529 reviewed
Great tutorial! Just some minor points 👍

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +<10> `test/`: Contains the test files for unit, functional and integration tests.
```suggestion
<10> `test/`: Contains the test files for unit, functional, and integration tests.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +<1> Creates blockchain application with the default modules.
```suggestion
<1> Creates a blockchain application with the default modules.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +Once it is verified that the application runs correctly, stop the node again with kbd:[Ctrl] + kbd:[C].
```suggestion
Once it is verified that the application is functioning correctly, stop the node again with kbd:[Ctrl] + kbd:[C].
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +The Lisk Name Service allows users to register domain names for their accounts.
```suggestion
The Lisk name service allows users to register domain names for their accounts.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Please refer to the section xref:{url_guide_setup_dependencies}[Lisk SDK Dependencies] of the setup guide to set up all the required dependencies to follow this tutorial, if you haven't done so alrer
```suggestion
Please refer to the section xref:{url_guide_setup_dependencies}[Lisk SDK Dependencies] of the setup guide to set up all the required dependencies to follow this tutorial, if you have not done so already.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Please use `lisk-name-service/lns` as root folder for the LNS blockchain application, and `lns` as application name.
```suggestion
Please use `lisk-name-service/lns` as the root folder for the LNS blockchain application, and `lns` as the application name.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Create the module skeleton by executing the command `lisk generate:module` like shown below:
```suggestion
Create the module skeleton by executing the command `lisk generate:module` as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This will information will be used to create the corresponding module skeleton.
```suggestion
This information will be used to create the corresponding module skeleton.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Read the following sections to learn how to further extend the LNS module to suit the desired use case.
```suggestion
To learn how to further extend the LNS module to suit the desired use case, please read the following sections.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The first part of the module that we implement here are the assets to handle the different transaction types `register`, `reverse lookup` and `update records`.
```suggestion
The first part of the module that we implement here are the assets to handle the different transaction types `register`, `reverse lookup`, and `update records`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As first step for creating the asset, use Lisk Commander again, this time, to create the asset skeleton.
```suggestion
As the first step for creating the asset, use Lisk Commander again, this time to create the asset skeleton.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +When you open `register.ts` at this point, it will look like this:
```suggestion
Upon opening `register.ts` at this point, it will appear as shown below:

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As you can see, the asset name and ID are already pre-filled with the values we provided when creating the asset skeleton.
```suggestion
As can be seen, the asset name and ID are already pre-filled with the values we provided when creating the asset skeleton.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As next step, we want to define the asset schema, which defines which kind of data is expected by the application to successfully register a new domain for a user account.
```suggestion
For the next step, it is necessary to define the asset schema, which defines which kind of data is expected by the application to successfully register a new domain for a user account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This folder is created to maintain a better overview, and will store all account and asset schemas which are relevant to the LNS module.
```suggestion
This folder is created to maintain an enhanced overview and will store all account and asset schemas that are relevant to the LNS module.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The first thing we define in the file, is an interface  for the expected asset data of a `register` transaction.
```suggestion
Firstly it is necessary to define an interface in the file for the expected asset data of a `register` transaction.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +It describes in a straight-forward way, what data is expected to be in the transaction asset for a successful registration of a new domain.
```suggestion
This describes in a straightforward manner, what data is expected to be in the transaction asset for the successful registration of a new domain.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* `ttl`(number): Time-To-Live: Time which needs to pass, until the records for the domain can be updated again.
```suggestion
* `ttl`(number): Time-To-Live: The time which needs to elapse, until the records for the domain can be updated again.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The corresponding interface looks like this:
```suggestion
The corresponding interface will appear as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Now,  just include the schema in the asset file:
```suggestion
Now, just include the schema in the asset file:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This file is created to maintain a better overview, and will store all constants which are relevant to the LNS module and its' assets.
```suggestion
This file is created to maintain an enhanced overview and will store all constants which are relevant to the LNS module and its' assets.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Add the following two constants.
```suggestion
Add the following two constants as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +We want to validate the following:
```suggestion
Now it is required to validate the following:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The corresponding checks look like this:
```suggestion
The corresponding checks should appear as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* Checks, if the domain name was already registered, and throws an error in this case.
```suggestion
* Checks if the domain name was already registered, and throws an error in this case.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The stateStore allows to perform state changes on the blockchain.
```suggestion
The stateStore allows performing state changes on the blockchain.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Implement the following interfaces and schemas, which are be used inside the utility functions:
```suggestion
Implement the following interfaces and schemas, which are to be used inside the utility functions:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The interface for an LNS node record looks like this:
```suggestion
The interface for an LNS node record appears as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<1> `type`: Type of the records as number.
```suggestion
<1> `type`: Type of the records as a number.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Based on this interface, we can create the corresponding schema, which looks like this:
```suggestion
Based on this interface it is possible to create the corresponding schema, which should appear as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +First define an interface which illustrates, how the LNS object will look like:
```suggestion
First define an interface that illustrates how the LNS object will look like as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<1> `ownerAddress`: The address of the domain owner as Buffer.
```suggestion
<1> `ownerAddress`: The address of the domain owner as a Buffer.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<2> `name`: The domain name as String.
```suggestion
<2> `name`: The domain name as a String.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<3> `ttl`: The TTL in seconds as number.
```suggestion
<3> `ttl`: The TTL in seconds as a number.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<4> `expiry`: The amount of years until the domain registration expires as number.
```suggestion
<4> `expiry`: The amount of years until the domain registration expires as a number.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<6> `createdAt`: Date of the domain registration as number.
```suggestion
<6> `createdAt`: Date of the domain registration as a number.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<7> `updatedAt`: Date of the last update of the domain and its' records as number.
```suggestion
<7> `updatedAt`: Date of the last update of the domain and its' records as a number.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Based on this interface, we can create the corresponding schema, which looks like this:
```suggestion
Based on this interface, it is possible to create the corresponding schema which should appear as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Now that the first asset is prepared, and first utility functions to store and get LNS objects from the database are implemented, let's move on to implement the second required asset for updating the
```suggestion
Now that the first asset is prepared, and the first utility functions to store and get LNS objects from the database are implemented, it is now possible to implement the second required asset for updating the reverse lookup of a domain for an account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Because an account can register multiple domains, it is important to define, to which domain the address should resolve to by default.
```suggestion
As an account can register multiple domains, it is important to define to which domain the address should resolve to by default.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +To do this, the account owner needs to send a reverse lookup transaction to update the default domain, their account address should default to.
```suggestion
To do this, the account owner needs to send a reverse lookup transaction to update the default domain, which their account address should default to.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The validation is not required for the reverse lookup transaction asset, so we can directly move on to implement the apply()` function.
```suggestion
The validation is not required for the reverse lookup transaction asset, so it is now possible to directly implement the apply()` function.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* Check, if the domain name was already registered and if the transaction sender owns this domain, and throw an error if not.
```suggestion
* Check if the domain name was already registered and if the transaction sender owns this domain, and throw an error if not.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* Add the hash value of the domain as reverse lookup domain to the senders account under the key `lns.reverseLookup`.
```suggestion
* Add the hash value of the domain as the reverse lookup domain to the sender's account under the key `lns.reverseLookup`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +A different handling of the records can be implemented at later stage.
```suggestion
Different handling of the records can be implemented at a later stage.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +I.e. if you build any DNS provider service on top of the LNS app, then you can use CNAME and TXT records differently there.
```suggestion
I.e. if you build any DNS provider service on top of the LNS app, then it is possible to use CNAME and TXT records differently there.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Then, import the constants inside of `update_records.ts` and implement the `validate` function as follows:
```suggestion
Now import the constants inside of `update_records.ts` and implement the `validate` function as follows:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* Throw an error, sender of the transaction is not the owner of the registered domain name.
```suggestion
* Throw an error, if the sender of the transaction is not the owner of the registered domain name.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The final step is now to add them to module, which will be done in the next chapter, where the LNS module is implemented.
```suggestion
The final step is now to add them to the module, which will be performed in the next chapter where the LNS module is implemented.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +To implement the LNS module, take a look at the module skeleton:
```suggestion
To implement the LNS module, please see the module skeleton below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As you can see, the following values have been pre-filled when creating the LNS module with Lisk Commander in step <<bootstrapping-the-default-application>>.
```suggestion
As can be seen below, the following values have been pre-filled when creating the LNS module with Lisk Commander in step <<bootstrapping-the-default-application>>.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +We will now implement the following parts of the skeleton:
```suggestion
The next step is to implement the following parts of the skeleton shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The events and lifecycle hooks are not required in this use case, so you can leave the skeletons as they are.
```suggestion
The events and lifecycle hooks are not required in this use case, so the skeletons can remain as they are at this point.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Now, let's add the assets we created before in step <<creating-the-lns-module-assets>>.
```suggestion
Now add the assets previously created in step <<creating-the-lns-module-assets>>.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Then, create a new instance of each asset and add them as array to the `transactionAssets` property of the LNS module.
```suggestion
Then create a new instance of each asset, and add them as an array to the `transactionAssets` property of the LNS module.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +That's all that is needed to add new assets to the LNS module.
```suggestion
This is now all that is required for adding new assets to the LNS module.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +All three actions are returning an <<lns-node-schema, LNS object>>, based on different input parameters like the address it is registered to, the domain name that is registered in the LNS object, or
```suggestion
All three actions are returning an <<lns-node-schema, LNS object>>, based on different input parameters such as the address it is registered to, the domain name that is registered in the LNS object, or a hash of the LNS object, which is typically stored in user account under the key `lns.ownNodes`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The only difference is, that the `StateStore` is available inside of reducers, so let's use it instead of `dataAccess` to query the database:
```suggestion
The only difference is that the `StateStore` is available inside of reducers, so please use it instead of `dataAccess` to query the database:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +With this last step, all required parts of the LNS module are implemented.
```suggestion
With this final step, all required parts of the LNS module will be now implemented.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +NOTE: In case the LNS tutorial was cloned from the `lisk-sdk-examples` repository, this step can be skipped, as the example application already contains the correct genesis block.
```suggestion
NOTE: In the case whereby the LNS tutorial was cloned from the `lisk-sdk-examples` repository, this step can be skipped as the example application already contains the correct genesis block.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If the blockchain application was bootstrapped newly with `lisk init`, it still contains a default genesis block, which doesnt include the account schema of the new LNS module.
```suggestion
If the blockchain application was just bootstrapped with `lisk init`, be aware it still contains a default genesis block, which does not include the account schema of the new LNS module.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Therefore it is needed to create a new genesis block with genesis accounts that include the new account properties of the LNS module.
```suggestion
Therefore it is necessary to create a new genesis block with genesis accounts that include the new account properties of the LNS module.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +TIP: A lot of detailed information about this process can be found in the guide xref:{url_guide_genesisblock}[].
```suggestion
TIP: More comprehensive and detailed information about this process can be found in the guide xref:{url_guide_genesisblock}[].
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Save the file `accounts.json` somewhere safe, it contains the credentials for all genesis accounts.
```suggestion
Save the file `accounts.json` somewhere secure as it contains the credentials for all genesis accounts.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +After the genesis block and config are updated, the application should start again successfully. To start, run the following command:
```suggestion
After the genesis block and config are updated the application should start again successfully. To start, run the following command:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Before we go on with developing the frontend part of the LNS application, let's quickly check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapter
```suggestion
Before continuing with developing the frontend part of the LNS application, it is advisable to quickly check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapter.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The Faucet plugin provides a web interface with a faucet, allowing account in the network to receive free tokens conveniently.
```suggestion
The Faucet plugin provides a web interface with a faucet, allowing accounts in the network to receive free tokens conveniently.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +By enabling the Dashboard and Faucet plugins in the blockchain application, we are able to test the functionality of the application by interacting with it through the browser.
```suggestion
By enabling the Dashboard and Faucet plugins in the blockchain application, it is possible to test the functionality of the application by interacting with it through the browser.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Among other things, it will be possible to ...
```suggestion
Amongst various other issues, it will now be possible to perform the following ...
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Before the Dashboard and Faucet plugins can be used for this purpose, it is first needed to install them and to register them with the LNS application, which is done in the next step.
```suggestion
Before the Dashboard and Faucet plugins can be used for this purpose, it is first necessary to both install and register them with the LNS application, which is performed in the next step.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +You can skip this step, if you don't create a new account in step <<create-new-account>>, but rather use on of the existing genesis accounts.
```suggestion
You can skip this step if you do not wish to create a new account in step <<create-new-account>>, but would rather use one of the existing genesis accounts.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Genesis accounts normally have an initial amount of tokens in their balance, so in this case, it is not needed for them to receive funds via the faucet.
```suggestion
Genesis accounts normally have a nominal amount of tokens in their balance, so in this case, it is not necessary for them to receive funds via the faucet.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Choose one of the genesis delegate to be the faucet account, e.g. the first account in `lisk-name-service/.secret/accounts.json`.
```suggestion
Choose one of the genesis delegates to be the faucet account, e.g. the first account in `lisk-name-service/.secret/accounts.json`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Save the password somewhere, it is needed to enable and disable the faucet later.
```suggestion
Save the password and store it safely, as it will be required to enable and disable the faucet later.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The last step to use the Faucet plugin is to enable it via the action `faucet:authorize`.
```suggestion
The final step required to use the Faucet plugin is to enable it via the action `faucet:authorize`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Wait until the application start is completed.
```suggestion
Wait until the application starting process is completed.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The actions expects as input a boolean, if the plugin should be enabled, and a password the decrypt the encrypted passphrase that was saved in `config.json` above.
Line 1590 is unclear to me, would it be correct in your opinion if we reword it as follows...?  " The actions expect a boolean expression as an input in the case whereby the plugin should be enabled. The password to decrypt the encrypted passphrase that was saved in `config.json` above will be required ''.

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Hit the kbd:[Submit] button to invoke the action.
```suggestion
Click on the kbd:[Submit] button to invoke the action.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Now let's go to the dashboard under {url_dashboard} .
```suggestion
Now navigate to the dashboard under {url_dashboard}.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Clicking on the account will open again the above window with the account credentials.
```suggestion
Clicking on the account will open the above window again with the account credentials.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Before it is possible to send any transactions, it is first needed to receive a certain amount of tokens to the new account.
```suggestion
Before it is possible to send any transactions, it is first necessary to receive a certain amount of tokens to the new account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Copy the Lisk32 address of the newly created account, go to the Faucet page, and receive tokens by pasting the address, checking the captcha, and hitting kbd:[Request].
```suggestion
Copy the Lisk32 address of the newly created account, go to the Faucet page, and receive tokens by pasting the address, checking the captcha, and click on the kbd:[Request] button.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If the tokens were transferred successfully, you will see the following confirmation message:
```suggestion
If the tokens were transferred successfully, the following confirmation message will appear:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Let's use the new account to register a domain name to it, which will be used as human-readable identifier for this account.
```suggestion
Now use the new account to register a domain name to it, which will be used as a human-readable identifier for this account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Hit the kbd:[Submit] button to post the transaction.
```suggestion
Click on the kbd:[Submit] button to post the transaction.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If the transaction was transferred successfully, the following confirmation message will show up:
```suggestion
If the transaction was transferred successfully, the following confirmation message will appear:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This new LNS object can be queried by invoking the two actions `lns:resolveName` and `lns:resolveNode` which we defined before in section <<actions>>.
```suggestion
This new LNS object can be queried by invoking the two actions `lns:resolveName` and `lns:resolveNode` which were previously defined in the section <<actions>>.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Go to the section `Call action` on the dashboard and select `lns:resolveName` from the dropdown menu.
```suggestion
Navigate to the section `Call action` on the dashboard and select `lns:resolveName` from the dropdown menu.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This should return the corresponding LNS object, which was just created by registering the domain name in the step before:
```suggestion
This should return the corresponding LNS object, which was just created by registering the domain name in the previous step:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Let's now add the newly created domain name as reverse lookup address for our account.
```suggestion
Now add the newly created domain name as a reverse lookup address for your account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Paste the passphrase of the account like before, and add the <<schema-2,required asset data>> for the `lns:reverse-lookup` transaction.
```suggestion
Paste the passphrase of the account just as done before, and add the <<schema-2,required asset data>> for the `lns:reverse-lookup` transaction.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Hit the kbd:[Submit] button to post the transaction.
```suggestion
Click on the kbd:[Submit] button to post the transaction.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If the transaction was transferred successfully, the following confirmation message will show up:
```suggestion
If the transaction was transferred successfully, the following confirmation message will appear:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +In the section `Recent Transactions` on the dashboard, it is possible to see an overview about all sent transactions so far:
```suggestion
In the section `Recent Transactions` on the dashboard, it is possible to see an overview of all sent transactions so far:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +At the beginning, there are no existing records yet, so let's create a first one:
```suggestion
At the beginning, there are no existing records yet, so now create the first one:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Again, paste the passphrase of the account like before, and add the <<schema-3,required asset data>> for the `lns:update-records` transaction.
```suggestion
Again, paste the passphrase of the account just as before, and add the <<schema-3,required asset data>> for the `lns:update-records` transaction.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Hit the kbd:[Submit] button to post the transaction.
```suggestion
Click on the kbd:[Submit] button to post the transaction.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If the transaction was transferred successfully, the following confirmation message will show up:
```suggestion
If the transaction was transferred successfully, the following confirmation message will appear:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +In the section `Recent Transactions` on the dashboard, the overview about all sent transactions now looks like this:
```suggestion
In the section `Recent Transactions` on the dashboard, the overview regarding all sent transactions will now appear as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Please be aware that the action expects the account address in hexadecimal representation (not Lisk32), like shown in the example below.
```suggestion
Please be aware that the action expects the account address in hexadecimal representation (not Lisk32), as shown in the example below.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As a result, we receive an object which contains all the account data.
```suggestion
As a result, an object is received which contains all the account data.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Finally, let's check if the reverse lookup of the account address is working as expected.
```suggestion
Finally, check if the reverse lookup of the account address is working as expected.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The reverse lookup was successful, if the expected LNS object is returned.
```suggestion
The reverse lookup was successful if the expected LNS object is returned.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +All important features of the LNS blockchain application have now been successfully tested with help of the Dashboard plugin.
```suggestion
All important features of the LNS blockchain application have now been successfully tested with the help of the Dashboard plugin.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The dashboard plugin is nice to use during development of th blockchain application, because it offers a simple way to interact with the blockchain application through a user interface.
```suggestion
The dashboard plugin is straightforward to use during development of the blockchain application, as it offers a simple way to interact with the blockchain application through a user interface.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +To make it more convenient for normal users to use the application, add a frontend to the application which is specialized on the respective use case of the LNS applicationn.
```suggestion
To ensure it is more convenient for normal users to use the application, add a frontend to the application which is specialized with regard to the respective use case of the LNS application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +For the LNS app, we want to provide a simple *frontend as a plugin*, which is registered to the LNS blockchain application.
```suggestion
For the LNS app, it is necessary to provide a simple *frontend as a plugin*, which is registered to the LNS blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +TIP: If you want to learn more about how to develop a React frontend application, check out the {url_reactjs_docs}[React.js documentation^].
```suggestion
TIP: If you wish to learn more about how to develop a React frontend application, check out the {url_reactjs_docs}[React.js documentation^].
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +<1> Move out of the `lisk-name-service` folder.
```suggestion
<1> Navigate out of the `lisk-name-service` folder.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As you might notice when looking at the files, the LNS Dashboard plugin is based on the code of the {url_sdk_dashboardplugin}[Dashboard plugin^] from the Lisk SDK Framework.
```suggestion
As you may notice when viewing the files, the LNS Dashboard plugin is based on the code of the {url_sdk_dashboardplugin}[Dashboard plugin^] from the Lisk SDK Framework.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The main logic of the React application is located under `lns-dashboard-plugin/src/ui/`, and the main logic fie the LNS UI Plugin is located in `lns-dashboard-plugin/src/app/`.
```suggestion
The main logic of the React application is located under `lns-dashboard-plugin/src/ui/`, and the main logic file the LNS UI Plugin is located in `lns-dashboard-plugin/src/app/`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +There is no need to generate any files newly, as we simplified the process by downloading the prepared frontend plugin for the LNS blockchain application.
```suggestion
There is no need to generate any new files, as we simplified the process by downloading the prepared frontend plugin for the LNS blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +But in case you want to create your own standalone plugin from scratch, you can use Lisk Commander to generate a plugin skeleton, just like it was done when generating the <<bootstrapping-the-default
```suggestion
However, in case you wish to create your own standalone plugin from scratch, then use Lisk Commander to generate a plugin skeleton, just the same as when generating the <<bootstrapping-the-default-application, Modules>> and <<assets>> skeletons:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Use the credentials of the account that was created newly in the previous step <<create-new-account>> to connect to the LNS frontend.
```suggestion
Use the credentials of the account that was newly created in the previous step <<create-new-account>> to connect to the LNS frontend.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +At the top right corner you will now see the domain that was defined as <<define-a-reverse-lookup-address,reverse lookup>> for the account address.
```suggestion
In the top right-hand corner, you will now see the domain that was defined as <<define-a-reverse-lookup-address,reverse lookup>> for the account address.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If you tick of the slider `Enable LNS`, the address of the account will be displayed again, instead of the domain name.
```suggestion
If you tick the checkbox of the slider `Enable LNS`, the address of the account will be displayed again, instead of the domain name.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +By clicking on your account you will reach the following page, giving all important information about your account and the domain names that are registered for this account.
```suggestion
By clicking on your account you will reach the following page, which provides all important information regarding your account, together with the domain names that are registered for this account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This was done in step <<register-domain>> via the Dashboard plugin.
```suggestion
This was done in the <<register-domain>> step via the Dashboard plugin.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Go back to the index page of the LNS Dashboard and search for a new domain name to add to your account.
```suggestion
Return back to the index page of the LNS Dashboard and search for a new domain name to add to your account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If no other user has registered tis domain at the moment, it will provide a link to a dialog to register the new domain.
```suggestion
If no other user has registered this domain at the moment, it will provide a link to a dialog to register the new domain.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +In the screenshot, we search for the domain `awesome.lsk`, and luckily, it isn't taken, yet.
```suggestion
The screenshot below shows the search for the domain `awesome.lsk`, and fortunately, it is still available.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Please make sure to always use at least the minimum fee for the transaction, or it will bee rejected by the blockchain application.
```suggestion
Please ensure to always use at least the minimum fee for the transaction, or it will be rejected by the blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Hit kbd:[Register] to send the domain name registration to the LNS blockchain application.
```suggestion
Click on the kbd:[Register] button to send the domain name registration to the LNS blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Wait for confirmation of the LNS app to have received your transaction.
```suggestion
Wait for confirmation of the LNS app to ensure your transaction has been received.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Now go back to your account page.
```suggestion
Now return back to your account page.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +So let's update the reverse lookup of the account to point to the new domain name `awesome.lsk`.
```suggestion
So now update the reverse lookup of the account to point to the new domain name `awesome.lsk`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Open the Dialog for updating the reverse lookup by clicking on kbd:[Update reverse lookup] in the top right.
```suggestion
Open the Dialog for updating the reverse lookup by clicking on the kbd:[Update reverse lookup] button on the top right-hand side.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Choose `awesome.lsk` fromt he dropdown menu, enter the account passphrase and the minimum fee.
```suggestion
Choose `awesome.lsk` from the dropdown menu, enter the account passphrase and the minimum fee.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Click kbd:[Update] to update the reverse lookup entry for this account.
```suggestion
Click on the kbd:[Update] button to update the reverse lookup entry for this account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As a result, you can verify that the LNS Dashboard now resolves the account address automatically to the new domain name `awesome.lsk`.
```suggestion
It is now possible to verify that the LNS Dashboard now resolves the account address automatically to the new domain name `awesome.lsk`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The search results should now inform you that this domain name is already reserved.
```suggestion
The search results should now indicate that this domain name is already reserved.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Play around as much as you like with the LNS application UI.
```suggestion
It is now possible to experiment and fully familiarize yourself with the LNS application UI.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The development of frontend and backend of the LNS application is now complete, and the application has all the features that were described in chapter <<lns-application-overview>> at the top.
```suggestion
The development of the frontend and backend of the LNS application is now complete, and the application has all of the features that were previously described in the chapter <<lns-application-overview>>.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This allows to interact with the blockchain application directly via the command-line, which can be beneficial for developers and/or node operators.
```suggestion
This allows interaction with the blockchain application directly via the command-line, which can be beneficial for developers and/or node operators.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +To further enhance the LNS blockchain application, let's create two new LNS specific commands, which can be exeecuted directly from the command line:
```suggestion
To further enhance the LNS blockchain application, create the following two new LNS specific commands, which can be executed directly from the command line:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The application CLI already contains a lot of general commands by default.
```suggestion
The application CLI already contains many general commands by default.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +They are directly created when the application isa bootstrapped with Lisk Commander with `lisk init`.
```suggestion
These are directly created when the application is bootstrapped with Lisk Commander with `lisk init`.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +You can see an overview of all existing CLI commands by navigating to the root folder of the blockchain application, and running
```suggestion
An overview of all existing CLI commands can be viewed by navigating to the root folder of the blockchain application, and running the following command:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +  help          display help for lisk-name-service
```suggestion
  help          display help for lisk-name-service.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +It also contains an API client to the node which we will use to invoke actions in the LNS application via the CLI.
```suggestion
It also contains an API client to the node which will be used to invoke actions in the LNS application via the CLI.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +In this particular use case, we also need one argument, the name to resolve.
```suggestion
In this particular use case, one argument is required here which is the name to resolve.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This is all code needed to add the new command to the LNS blockchain application.
```suggestion
This is all the code required to add the new command to the LNS blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As you see, there is not much logic needed to implement.
```suggestion
As is evident here, there is not much logic needed to implement.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +We can reuse the action <<actions,lns:resolveName>> to get the address, based on the address that was provided as command argument.
```suggestion
The action <<actions,lns:resolveName>> can be reused to get the address, based on the address that was provided as a command argument.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This is all code needed to add the `lns:lookup` command to the LNS blockchain application.
```suggestion
This is all the code required to add the `lns:lookup` command to the LNS blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The implementation is analog to the previous command, but now use the corresponding action `lns:lookup` to get the domain name for the provided account address.
```suggestion
The implementation is analog to the previous command, however, now use the corresponding action `lns:lookup` to get the domain name for the provided account address.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The new topic `lns` should now show up under `TOPICS`:
```suggestion
The new topic `lns` should now appear under `TOPICS`:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  display autocomplete installation instructions.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +  help          display help for lisk-name-service
```suggestion
  help          display help for lisk-name-service.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +If the LNS application os not already running, start it again:
```suggestion
If the LNS application is not already running, start it again as shown below:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Now resolve the domain name `my-name.lsk`, which we registered before.
```suggestion
Now resolve the domain name `my-name.lsk`, which has already been previously registered.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. Environment variable "LISK_DATA_PATH" can also be
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As last topic of this tutorial, we'll explore how the application can be tested with unit and network tests.
```suggestion
In the final topic of this tutorial, how the application can be tested with both unit and network tests will be explored.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Writing tests for the application gets more and more important, the more complex the blockchain application gets.
```suggestion
Writing tests for the application becomes more and more important, as the complexity of the blockchain application increases.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Once it reaches a certain complexity, it won't be convenient anymore to test the application functionality with the dashboard plugin, the CLI or via a frontend, and writing tests becomes a crucial pa
```suggestion
Once it reaches a certain level of complexity, it will not be convenient anymore to test the application functionality with the dashboard plugin, the CLI, or via a frontend; and therefore writing tests will become crucial in order to verify the correct behavior of the blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +For this purpose, we will first add a couple of unit tests to the application in this chapter, and then a couple of network tests in the next chapter.
```suggestion
For this purpose, a couple of unit tests will be added to the application in this chapter, and this will be followed by a couple of network tests in the next chapter.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +To make the creation of tests convenient, we will make use of xref:{url_reference_testsuite}[].
```suggestion
To ensure the creation of tests can be performed in a convenient manner, the xref:{url_reference_testsuite}[] will be used.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Navigate into the `test/` folder of the LNS application.
```suggestion
Navigate into the `test` folder of the LNS application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The `test` folder is the place to store all the kind of different tests for th blockchain application.
```suggestion
The `test` folder is the correct location to store all types of different tests for the blockchain application.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As you can see, there are already some existing test files for the lns module and the assets.
```suggestion
As can be seen, there are already some existing test files for the LNS module and the assets.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The complete code of the tests for the Register asset is described below.
```suggestion
The entire code of the tests for the Register asset is described below.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Most of the code is self-explanatory, but the most important parts of the tests are summarized here for a better overview:
```suggestion
Most of the code is self-explanatory, however, the most important parts of the tests are summarized here to provide a better overview:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* It should throw error if name is registered for less than a year.
```suggestion
* It should throw an error if the name is registered for less than a year.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* It should throw error if name is registered for more than 5 years
```suggestion
* It should throw an error if the name is registered for more than 5 years.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* It should throw error if domain contains invalid tld.
```suggestion
* It should throw an error if the domain contains an invalid tld.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* It not throw any error, if all asset parameters are valid.
```suggestion
* It does not throw any error if all asset parameters are valid.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +No need to put a real address here in this case, as it isn't used in the tests.
```suggestion
It is not necessary to put a real address here in this case as it is not used in the tests.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should update the state store with updated sender account.
```suggestion
** It should update the state store with an updated sender account.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should update the state store with correct ttl value.
```suggestion
** It should update the state store with the correct ttl value.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should update the state store with correct expiry date.
```suggestion
** It should update the state store with the correct expiry date.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should throw error if name is already registered.
```suggestion
** It should throw an error if the name is already registered.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This allows to check in the tests, if the respective functions have been called or not.
```suggestion
This allows checking in the tests if the respective functions have been called or not.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +The complete code of the tests for the Reverse Lookup asset is described below.
```suggestion
The entire code of the tests for the Reverse Lookup asset is described below.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +Most of the code is self-explanatory, but the most important parts of the tests are summarized here for a better overview:
```suggestion
Most of the code is self-explanatory, however, the most important parts of the tests are summarized here to provide a better overview:
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should update the lns reverse-lookup of the sender account with given node if not already set.
```suggestion
** It should update the lns reverse-lookup of the sender account with the given node if not already set.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should update the lns reverse-lookup of the sender account with given node even if already set.
```suggestion
** It should update the lns reverse-lookup of the sender account with the given node even if already set.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should throw error if node to set-lookup is not owned by sender.
```suggestion
** It should throw an error if the node to set-lookup is not owned by the sender.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +This allows to check in the tests, if the respective functions have been called or not.
```suggestion
This allows checking in the tests if the respective functions have been called or not.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +{url_wikipedia_functionaltesting}[Functional testing] is a quality assurance (QA) process and a type of black-box testing that bases its test cases on the specifications of the software component und
```suggestion
{url_wikipedia_functionaltesting}[Functional testing] is a quality assurance (QA) process and a type of black-box testing that bases its test cases on the specifications of the software component under test. Functions are tested by feeding them input and examining the output, and internal program structure is rarely considered here (unlike white-box testing).
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +As a last exercise, write a functional test, that checks if a domain name was correctly resolved after calling the action `lns:resolveName`.
```suggestion
Finally, as the last exercise here, write a functional test, that checks if a domain name was correctly resolved after calling the action `lns:resolveName`as described below.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +* `resolveName` action of the LNS module
```suggestion
* `resolveName` action of the LNS module.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should throw error on resolving non-registered name.
```suggestion
** It should throw an error on resolving the non-registered name.
```

2021-09-28 08:01 UTC, chris529 commented on modules/ROOT/pages/tutorials/lisk-name-service.adoc
> +** It should resolve name after registration.
```suggestion
** It should resolve the name after registration.
```

2021-09-28 08:01 UTC, chris529 reviewed
Great tutorial! Just some minor points 👍

2021-10-01 08:28 UTC, chris529 reviewed
Looks good, just minor points,.. 👍

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Please refer to the section xref:{url_guide_setup_dependencies}[Lisk SDK Dependencies] of the setup guide to set up all the required dependencies to follow this tutorial, if you haven't done so alrer
```suggestion
Please refer to the section xref:{url_guide_setup_dependencies}[Lisk SDK Dependencies] of the setup guide to set up all the required dependencies to follow this tutorial, if you have not done so already.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +To customize the default blockchain application to suit our desired use case, we will now generate the LNS module skeleton.
```suggestion
To customize the default blockchain application to suit our desired use case, it is necessary to generate the LNS module skeleton.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Create the module skeleton by executing the command `lisk generate:module` like shown below:
```suggestion
Create the module skeleton by executing the command `lisk generate:module` as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +This will information will be used to create the corresponding module skeleton.
```suggestion
This information will be used to create the corresponding module skeleton.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +When you open `register.ts` at this point, it will look like this:
```suggestion
When you open `register.ts` at this point, it will appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +As you can see, the asset name and ID are already pre-filled with the values we provided when creating the asset skeleton.
```suggestion
As can be seen, the asset name and ID are already pre-filled with the values we provided when creating the asset skeleton.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +As next step, we want to define the asset schema, which defines which kind of data is expected by the application to successfully register a new domain for a user account.
```suggestion
For the next step, it is necessary to define the asset schema, which defines which kind of data is expected by the application to successfully register a new domain for a user account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The first thing we define in the file, is an interface  for the expected asset data of a `register` transaction.
```suggestion
Firstly, it is necessary to define an interface in the file for the expected asset data of a `register` transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +It describes in a straight-forward way, what data is expected to be in the transaction asset for a successful registration of a new domain.
```suggestion
This describes in a straightforward manner, what data is expected to be in the transaction asset for the successful registration of a new domain.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* `ttl`(number): Time-To-Live: Time which needs to pass, until the records for the domain can be updated again.
```suggestion
* `ttl`(number): Time-To-Live: The amount of time required, until the records for the domain can be updated again.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The corresponding interface looks like this:
```suggestion
The corresponding interface should appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now,  just include the schema in the asset file:
```suggestion
Now, include the schema in the asset file:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +We want to validate the following:
```suggestion
It is now necessary to validate the following:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The corresponding checks look like this:
```suggestion
The corresponding checks are shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* Checks, if the domain name was already registered, and throws an error in this case.
```suggestion
* Checks if the domain name was already registered, and throws an error if this is the case.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The implementation of these functions is explained in the next section in detail.
```suggestion
The implementation of these functions is explained in detail in the next section.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Next, open the file `lns/constants.ts`, which was created in step <<validation>> and add the following constant:
```suggestion
Next, open the file `lns/constants.ts`, which was created in the step <<validation>> and add the following constant:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now implement the function to save a new LNS object in the database by reusing the above defined functions <<getnodefornamename>> and <<getkeyfornodenode>> and the below defined <<lns-node-schema>>.
```suggestion
Now implement the function to save a new LNS object in the database by reusing the above defined functions <<getnodefornamename>> and <<getkeyfornodenode>> and the <<lns-node-schema>> defined below.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The stateStore allows to perform state changes on the blockchain.
```suggestion
The stateStore allows performing state changes on the blockchain.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The stateStore allows to perform state changes on the blockchain.
```suggestion
The stateStore allows performing state changes on the blockchain.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Implement the following interfaces and schemas, which are be used inside the utility functions:
```suggestion
Implement the following interfaces and schemas, which are to be used inside the utility functions:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The interface for an LNS node record looks like this:
```suggestion
The interface for an LNS node record should appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Based on this interface, we can create the corresponding schema, which looks like this:
```suggestion
Based on this interface, we can create the corresponding schema as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +First define an interface which illustrates, how the LNS object will look like:
```suggestion
First, define an interface that illustrates how the LNS object will look like as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<1> `ownerAddress`: The address of the domain owner as Buffer.
```suggestion
<1> `ownerAddress`: The address of the domain owner as a Buffer.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<2> `name`: The domain name as String.
```suggestion
<2> `name`: The domain name as a String.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<3> `ttl`: The TTL in seconds as number.
```suggestion
<3> `ttl`: The TTL in seconds as a number.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<4> `expiry`: The amount of years until the domain registration expires as number.
```suggestion
<4> `expiry`: The amount of years until the domain registration expires as a number.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<6> `createdAt`: Date of the domain registration as number.
```suggestion
<6> `createdAt`: Date of the domain registration as a number.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<7> `updatedAt`: Date of the last update of the domain and its' records as number.
```suggestion
<7> `updatedAt`: Date of the last update of the domain and its' records as a number.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Based on this interface, we can create the corresponding schema, which looks like this:
```suggestion
Based on this interface, it is now possible to create the corresponding schema as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now that the first asset is prepared, and first utility functions to store and get LNS objects from the database are implemented, let's move on to implement the second required asset for updating the
```suggestion
Now that the first asset is prepared, and the first utility functions to store and get LNS objects from the database are implemented, it is now possible to move on to implement the second required asset for updating the reverse lookup of a domain for an account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +While a 'regular' lookup involves mapping from a name to an address, reverse lookup maps from an address back to a domain.
```suggestion
While a 'regular' lookup involves mapping from a name to an address, a reverse lookup maps from an address back to a domain.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Because an account can register multiple domains, it is important to define, to which domain the address should resolve to by default.
```suggestion
As an account can register multiple domains, it is important to define which domain the address should resolve to by default.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +To do this, the account owner needs to send a reverse lookup transaction to update the default domain, their account address should default to.
```suggestion
To achieve this, the account owner needs to send a reverse lookup transaction to update the default domain, which their account address should default to.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Use `reverse_lookup`  as asset name and `2` as asset ID.
```suggestion
Use `reverse_lookup` as the asset name and `2` as the asset ID.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now include the schema in the asset file:
```suggestion
Now include the schema in the asset file as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The validation is not required for the reverse lookup transaction asset, so we can directly move on to implement the apply()` function.
```suggestion
The validation is not required for the reverse lookup transaction asset, so it is possible to directly move on to implement the apply()` function.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* Check, if the domain name was already registered and if the transaction sender owns this domain, and throw an error if not.
```suggestion
* Check if the domain name was already registered and if the transaction sender owns this domain. If not then an error should be thrown.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* Add the hash value of the domain as reverse lookup domain to the senders account under the key `lns.reverseLookup`.
```suggestion
* Add the hash value of the domain as the reverse lookup domain to the senders account under the key `lns.reverseLookup`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +A different handling of the records can be implemented at later stage.
```suggestion
Different handling of the records can be implemented at a later stage.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* Throw an error, sender of the transaction is not the owner of the registered domain name.
```suggestion
* Throw an error, if the sender of the transaction is not the owner of the registered domain name.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Open the file `storage.ts` which was previously created in step <<utility-functions>>, and define a new function `updateLSNObject()` which updates a certain LNS object in the database, based on provi
```suggestion
Open the file `storage.ts` which was previously created in the step <<utility-functions>>, and define a new function `updateLSNObject()` which updates a certain LNS object in the database, based on the provided parameters.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The final step is now to add them to module, which will be done in the next chapter, where the LNS module is implemented.
```suggestion
The final step is now to add them to the module, which will be performed in the next chapter, where the LNS module is implemented.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +To implement the LNS module, take a look at the module skeleton:
```suggestion
To implement the LNS module, firstly view the module skeleton as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +As you can see, the following values have been pre-filled when creating the LNS module with Lisk Commander in step <<bootstrapping-the-default-application>>.
```suggestion
As can be seen, the following values have been pre-filled when creating the LNS module with Lisk Commander in step <<bootstrapping-the-default-application>>.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +We will now implement the following parts of the skeleton:
```suggestion
Now the following parts of the skeleton can be implemented:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The events and lifecycle hooks are not required in this use case, so you can leave the skeletons as they are.
```suggestion
The events and lifecycle hooks are not required in this use case, so the skeletons can remain as they are.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now, let's add the assets we created before in step <<creating-the-lns-module-assets>>.
```suggestion
Now add the assets that were created previously in the step <<creating-the-lns-module-assets>>.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Then, create a new instance of each asset and add them as array to the `transactionAssets` property of the LNS module.
```suggestion
Now create a new instance of each asset and add them as an array to the `transactionAssets` property of the LNS module.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +That's all that is needed to add new assets to the LNS module.
```suggestion
That's all that is required to add new assets to the LNS module.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +All three actions are returning an <<lns-node-schema, LNS object>>, based on different input parameters like the address it is registered to, the domain name that is registered in the LNS object, or
```suggestion
All three actions are returning an <<lns-node-schema, LNS object>>, based on different input parameters just as the address it is registered to, the domain name that is registered in the LNS object, or a hash of the LNS object, which is typically stored in user account under the key `lns.ownNodes`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The main logic of the different actions is imported from the file `storage.ts`, and is explained in detail in step <<utility-functions-3>> below.
```suggestion
The main logic of the different actions is imported from the file `storage.ts`, and is explained in detail in the step <<utility-functions-3>> below.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The methods needed in reducers are very similar to the methods in <<actions>> above.
```suggestion
The methods required in reducers are very similar to the methods in the <<actions>> above.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The only difference is, that the `StateStore` is available inside of reducers, so let's use it instead of `dataAccess` to query the database:
```suggestion
The only difference is that the `StateStore` is available inside of reducers, so it can be used instead of `dataAccess` to query the database:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +If the blockchain application was bootstrapped newly with `lisk init`, it still contains a default genesis block, which doesnt include the account schema of the new LNS module.
```suggestion
If the blockchain application was newly bootstrapped with `lisk init`, it still contains a default genesis block, which does not include the account schema of the new LNS module.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Therefore it is needed to create a new genesis block with genesis accounts that include the new account properties of the LNS module.
```suggestion
Therefore it is necessary to create a new genesis block with genesis accounts that include the new account properties of the LNS module.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +TIP: A lot of detailed information about this process can be found in the guide xref:{url_guide_genesisblock}[].
```suggestion
TIP: A myriad of detailed information about this process can be found in the guide xref:{url_guide_genesisblock}[].
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Save the file `accounts.json` somewhere safe, it contains the credentials for all genesis accounts.
```suggestion
Save the file `accounts.json` somewhere secure as it contains the credentials for all genesis accounts.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Before we go on with developing the frontend part of the LNS application, let's quickly check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapter
```suggestion
Before proceeding with developing the frontend part of the LNS application, it is necessary to check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapter.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The Faucet plugin provides a web interface with a faucet, allowing account in the network to receive free tokens conveniently.
```suggestion
The Faucet plugin provides a web interface with a faucet, allowing accounts in the network to receive free tokens conveniently.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +By enabling the Dashboard and Faucet plugins in the blockchain application, we are able to test the functionality of the application by interacting with it through the browser.
```suggestion
By enabling the Dashboard and Faucet plugins in the blockchain application, it is possible to test the functionality of the application by interacting with it through the browser.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Among other things, it will be possible to ...
```suggestion
Furthermore, it will also be possible to perform the following :
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* ... create new accounts with the Dashboard
```suggestion
* ... create new accounts with the Dashboard.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +* ... fund accounts with tokens via the Faucet
```suggestion
* ... fund accounts with tokens via the Faucet.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Before the Dashboard and Faucet plugins can be used for this purpose, it is first needed to install them and to register them with the LNS application, which is done in the next step.
```suggestion
Before the Dashboard and Faucet plugins can be used for this purpose, it is firstly required to install them and to register them with the LNS application, which is performed in the next step.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +You can skip this step, if you don't create a new account in step <<create-new-account>>, but rather use on of the existing genesis accounts.
```suggestion
This step can be skipped if you do not create a new account in the step <<create-new-account>>, but rather use one of the existing genesis accounts instead.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Genesis accounts normally have an initial amount of tokens in their balance, so in this case, it is not needed for them to receive funds via the faucet.
```suggestion
Genesis accounts normally have an initial amount of tokens in their balance, so in this case it is not necessary for them to receive funds via the faucet.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Save the password somewhere, it is needed to enable and disable the faucet later.
```suggestion
Save the password securely as it is needed to enable and disable the faucet later.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The password will be needed later to enable the faucet plugin through the action `faucet:authorize`.
```suggestion
The password will be required later to enable the faucet plugin through the action `faucet:authorize`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The actions expects as input a boolean, if the plugin should be enabled, and a password the decrypt the encrypted passphrase that was saved in `config.json` above.
```suggestion
The actions expect a boolean as an input, defining if the plugin should be enabled, and also a password to decrypt the encrypted passphrase that was saved in `config.json` above.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<1> Change this to the password you used above to encrypt the passphrase in the Faucet plugin configuration.
```suggestion
<1> Change this to the password used above to encrypt the passphrase in the Faucet plugin configuration.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Hit the kbd:[Submit] button to invoke the action.
```suggestion
Click on the kbd:[Submit] button to invoke the action.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +You should see a confirmation that the action was invoked successfully.
```suggestion
It should now be possible to see a confirmation that the action was invoked successfully.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now let's go to the dashboard under {url_dashboard} .
```suggestion
Now navigate to the dashboard under {url_dashboard}.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Reloading the page will delete all temporary data in the accounts, block and transaction logs of the Dashboard.
```suggestion
Reloading the page will delete all temporary data in the accounts, block, and transaction logs of the Dashboard.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Clicking on the account will open again the above window with the account credentials.
```suggestion
Clicking on the account will open the above window with the account credentials again.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Before it is possible to send any transactions, it is first needed to receive a certain amount of tokens to the new account.
```suggestion
Before it is possible to send any transactions, it is first necessary to receive a certain amount of tokens to the new account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Copy the Lisk32 address of the newly created account, go to the Faucet page, and receive tokens by pasting the address, checking the captcha, and hitting kbd:[Request].
```suggestion
Copy the Lisk32 address of the newly created account, go to the Faucet page, and receive tokens by pasting the address, checking the captcha, and clicking on the kbd:[Request] button.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +If the tokens were transferred successfully, you will see the following confirmation message:
```suggestion
If the tokens were transferred successfully, the following confirmation message will appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Let's use the new account to register a domain name to it, which will be used as human-readable identifier for this account.
```suggestion
Now use the new account to register a domain name to it, which will be used as human-readable identifier for this account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Hit the kbd:[Submit] button to post the transaction.
```suggestion
Click on the kbd:[Submit] button to post the transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +If the transaction was transferred successfully, the following confirmation message will show up:
```suggestion
If the transaction was transferred successfully, the following confirmation message will appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +This new LNS object can be queried by invoking the two actions `lns:resolveName` and `lns:resolveNode` which we defined before in section <<actions>>.
```suggestion
This new LNS object can be queried by invoking the two actions `lns:resolveName` and `lns:resolveNode` which were previously defined in the section <<actions>>.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Go to the section `Call action` on the dashboard and select `lns:resolveName` from the dropdown menu.
```suggestion
Navigate to the section `Call action` on the dashboard and select `lns:resolveName` from the dropdown menu.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Provide the expected input for the action in the field below.
```suggestion
Provide the expected input for the action in the field below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +This should return the corresponding LNS object, which was just created by registering the domain name in the step before:
```suggestion
This should return the corresponding LNS object, which was just created by registering the domain name in the previous step:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Provide the expected input for the action in the field below.
```suggestion
Provide the expected input for the action in the field below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Let's now add the newly created domain name as reverse lookup address for our account.
```suggestion
Now add the newly created domain name as the reverse lookup address for our account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +This will tell the LNS app to which domain name the address should resolve to by default.
```suggestion
This will inform the LNS app to which domain name the address should resolve to by default.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +This is important, because a single account can register many different domain names at once.
```suggestion
This criteria is important as a single account can register many different domain names at once.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Paste the passphrase of the account like before, and add the <<schema-2,required asset data>> for the `lns:reverse-lookup` transaction.
```suggestion
Paste the passphrase of the account as before, and add the <<schema-2,required asset data>> for the `lns:reverse-lookup` transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Hit the kbd:[Submit] button to post the transaction.
```suggestion
Click on the kbd:[Submit] button to post the transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +If the transaction was transferred successfully, the following confirmation message will show up:
```suggestion
If the transaction was transferred successfully, the following confirmation message will appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +In the section `Recent Transactions` on the dashboard, it is possible to see an overview about all sent transactions so far:
```suggestion
In the section `Recent Transactions` on the dashboard, it is possible to see an overview regarding all the sent transactions so far:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Now, last but not least, test the `lns:update-records` transaction, which allows a user to update the records of a registered domain name.
```suggestion
Lastly, it is necessary to test the `lns:update-records` transaction, which allows a user to update the records of a registered domain name.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +At the beginning, there are no existing records yet, so let's create a first one:
```suggestion
At the beginning, there are no existing records yet, so it is now possible to create the first one as described below.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Again, paste the passphrase of the account like before, and add the <<schema-3,required asset data>> for the `lns:update-records` transaction.
```suggestion
As performed previously, paste the passphrase of the account, and add the <<schema-3,required asset data>> for the `lns:update-records` transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Hit the kbd:[Submit] button to post the transaction.
```suggestion
Click on the kbd:[Submit] button to post the transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +If the transaction was transferred successfully, the following confirmation message will show up:
```suggestion
If the transaction was transferred successfully, the following confirmation message will appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +In the section `Recent Transactions` on the dashboard, the overview about all sent transactions now looks like this:
```suggestion
In the section the `Recent Transactions` on the dashboard displaying the overview of all sent transactions, will now appear as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Please be aware that the action expects the account address in hexadecimal representation (not Lisk32), like shown in the example below.
```suggestion
Please be aware that the action expects the account address in hexadecimal representation (not Lisk32), as shown in the example below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +As a result, we receive an object which contains all the account data.
```suggestion
As a result, an object is received which contains all the account data.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Finally, let's check if the reverse lookup of the account address is working as expected.
```suggestion
Finally, check if the reverse lookup of the account address is working as expected.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +The SDK Dashboard plugin is nice to use during development of th blockchain application, because it offers a simple way to interact with the blockchain application through a user interface.
```suggestion
The SDK Dashboard plugin is convenient to use during development of the blockchain application, as it offers a simple way to interact with the blockchain application through a user interface.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +To make it more convenient for normal users to use the application, add a frontend to the application which is specialized on the respective use case of the LNS applicationn.
```suggestion
To make the application even more user-friendly, add a frontend which is specialized for the respective use case of the LNS application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +For the LNS app, we want to provide a simple *frontend as a plugin*, which is registered to the LNS blockchain application.
```suggestion
For the LNS app, it is recommended to provide a simple *frontend as a plugin*, which is registered to the LNS blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +A simple {url_reactjs}[React.js web^] application is used as frontend.
```suggestion
A simple {url_reactjs}[React.js web^] application is used as a frontend.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +The development of the React application is not covered in this tutorial in detail.
```suggestion
The development of the React application is not covered in detail in this tutorial.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Instead, we will use the existing React frontend in the {url_sdkexamples_lns_uiplugin}[lisk-sdk-examples repository^] and see how it can be included as a standalone UI plugin for a blockchain applica
```suggestion
Instead, use the existing React frontend in the {url_sdkexamples_lns_uiplugin}[lisk-sdk-examples repository^] and see how it can be included as a standalone UI plugin for a blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +TIP: If you want to learn more about how to develop a React frontend application, check out the {url_reactjs_docs}[React.js documentation^].
```suggestion
TIP: If you wish to learn more about how to develop a React frontend application, check out the {url_reactjs_docs}[React.js documentation^].
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +<1> Move out of the `lisk-name-service` folder.
```suggestion
<1> Navigate out of the `lisk-name-service` folder.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +As you might notice when looking at the files, the LNS Dashboard plugin is based on the code of the {url_sdk_dashboardplugin}[Dashboard plugin^] from the Lisk SDK Framework.
```suggestion
As you may notice when viewing the files, the LNS Dashboard plugin is based on the code of the {url_sdk_dashboardplugin}[Dashboard plugin^] from the Lisk SDK Framework.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +The main logic of the React application is located under `lns-dashboard-plugin/src/ui/`, and the main logic fie the LNS UI Plugin is located in `lns-dashboard-plugin/src/app/`.
```suggestion
The main logic of the React application is located under `lns-dashboard-plugin/src/ui/`, and the main logic file the LNS UI Plugin is located in `lns-dashboard-plugin/src/app/`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +There is no need to generate any files newly, as we simplified the process by downloading the prepared frontend plugin for the LNS blockchain application.
```suggestion
It is not necessary to generate any new files, as the process has been simplified by downloading the prepared frontend plugin for the LNS blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +But in case you want to create your own standalone plugin from scratch, you can use Lisk Commander to generate a plugin skeleton, just like it was done when generating the <<bootstrapping-the-default
```suggestion
However, in the case whereby you wish to create your own standalone plugin from scratch, it is possible to use Lisk Commander to generate a plugin skeleton, just as was done when generating the <<bootstrapping-the-default-application, Modules>> and <<assets>> skeletons:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Use the credentials of the account that was created newly in the previous step xref:{url_lns_1_newacc}[Create new account] of Chapter 1 to connect to the LNS frontend.
```suggestion
Use the credentials of the account that was newly created in the previous step xref:{url_lns_1_newacc}[Create new account] of Chapter 1 to connect to the LNS frontend.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +By clicking on your account you will reach the following page, giving all important information about your account and the domain names that are registered for this account.
```suggestion
By clicking on your account you will reach the following page, which contains all important information about your account, and the domain names that are registered for this account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +You can also see the new TXT record that was added to the LNS object.
```suggestion
It can also be seen that the new TXT record that was added to the LNS object.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +If no other user has registered tis domain at the moment, it will provide a link to a dialog to register the new domain.
```suggestion
If no other user has registered this domain at the moment, it will provide a link to a dialog to register this new domain.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +In the screenshot, we search for the domain `awesome.lsk`, and luckily, it isn't taken, yet.
```suggestion
In the screenshot below, searching for the domain `awesome.lsk`is depicted, and as can be seen here, it is still available.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Please make sure to always use at least the minimum fee for the transaction, or it will bee rejected by the blockchain application.
```suggestion
Please ensure to always use at least the minimum fee for the transaction, or it will be rejected by the blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Hit kbd:[Register] to send the domain name registration to the LNS blockchain application.
```suggestion
Click on the kbd:[Register] button to send the domain name registration to the LNS blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Wait for confirmation of the LNS app to have received your transaction.
```suggestion
Wait for confirmation that the LNS app has received your transaction.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Now go back to your account page.
```suggestion
Now return back to your account page.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +You should see the new domain name listed there.
```suggestion
The new domain name should now be visible there.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Unfortunately, on the top right, our address is still resolving to the `my-name.lsk` domain (if LNS is enabled).
```suggestion
Unfortunately, as can be seen on the top right, our address is still resolving to the `my-name.lsk` domain (if LNS is enabled).
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +So let's update the reverse lookup of the account to point to the new domain name `awesome.lsk`.
```suggestion
So now update the reverse lookup of the account to point to the new domain name `awesome.lsk`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Open the Dialog for updating the reverse lookup by clicking on kbd:[Update reverse lookup] in the top right.
```suggestion
Open the Dialog for updating the reverse lookup by clicking on the kbd:[Update reverse lookup] button in the top right.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Click kbd:[Update] to update the reverse lookup entry for this account.
```suggestion
Click the kbd:[Update] button to update the reverse lookup entry for this account.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +As a result, you can verify that the LNS Dashboard now resolves the account address automatically to the new domain name `awesome.lsk`.
```suggestion
As a result, it is possible to verify that the LNS Dashboard now resolves the account address automatically to the new domain name `awesome.lsk`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +The search results should now inform you that this domain name is already reserved.
```suggestion
The search results should now indicate that this domain name is already reserved.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Play around as much as you like with the LNS application UI.
```suggestion
Familiarize yourself with the LNS application UI.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +The development of frontend and backend of the LNS application is now complete, and the application has all the features that were described in the xref:{url_lns_0}[LNS application overview] at the t
```suggestion
The development of the frontend and backend of the LNS application is now complete, and the application has all the features that were described in the xref:{url_lns_0}[LNS application overview] at the top.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +This allows to interact with the blockchain application directly via the command-line, which can be beneficial for developers and/or node operators.
```suggestion
This allows interaction with the blockchain application directly via the command-line, which can be beneficial for developers and/or node operators.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +To further enhance the LNS blockchain application, let's create two new LNS specific commands, which can be exeecuted directly from the command line:
```suggestion
To further enhance the LNS blockchain application, create two new LNS specific commands which can be executed directly from the command line:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +The application CLI already contains a lot of general commands by default.
```suggestion
The application CLI already contains numerous general commands by default.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +You can see an overview of all existing CLI commands by navigating to the root folder of the blockchain application, and running
```suggestion
An overview of all existing CLI commands can be seen by navigating to the root folder of the blockchain application, and running the following command:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  display autocomplete installation instructions.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +  help          display help for lisk-name-service
```suggestion
  help          display help for lisk-name-service.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +Now, the plan is to create a new topic `lns`, and to define the two new commands `lns:resolve` and `lns:lookup` to be part of it.
```suggestion
Now, create a new topic `lns`, and to define the two new commands `lns:resolve` and `lns:lookup` to be part of it.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +It also contains an API client to the node which we will use to invoke actions in the LNS application via the CLI.
```suggestion
It also contains an API client to the node which will be used to invoke actions in the LNS application via the CLI.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +In this particular use case, we also need one argument, the name to resolve.
```suggestion
In this particular use case, one argument is needed, the name to resolve.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +This is all code needed to add the new command to the LNS blockchain application.
```suggestion
This is all the code required to add the new command to the LNS blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +As you see, there is not much logic needed to implement.
```suggestion
As can be seen, there is not much logic required to be implemented here.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +We can reuse the action <<actions,lns:resolveName>> to get the address, based on the address that was provided as command argument.
```suggestion
The action <<actions,lns:resolveName>> can be reused to get the address, based on the address that was provided as the command argument.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +This is all code needed to add the `lns:lookup` command to the LNS blockchain application.
```suggestion
This is all the code required to add the `lns:lookup` command to the LNS blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +The implementation is analog to the previous command, but now use the corresponding action `lns:lookup` to get the domain name for the provided account address.
```suggestion
The implementation is analog to the previous command, nevertheless, now use the corresponding action `lns:lookup` to get the domain name for the provided account address.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +The new topic `lns` should now show up under `TOPICS`:
```suggestion
The new topic `lns` should now appear under `TOPICS`:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  display autocomplete installation instructions.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +  help          display help for lisk-name-service
```suggestion
  help          display help for lisk-name-service.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +If the LNS application os not already running, start it again:
```suggestion
If the LNS application is not already running, start it again as shown below:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +Now resolve the domain name `my-name.lsk`, which we registered before.
```suggestion
Now resolve the domain name `my-name.lsk`, which was registered previously.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +When the resolve command works as expected, copy the `ownerAdress` from the returned LNS object and provide it as argument for the `lns:lookup` command:
```suggestion
When the resolve command works as expected, copy the `ownerAdress` from the returned LNS object and provide it as an argument for the `lns:lookup` command:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +As last topic of this tutorial, we'll explore how the application can be tested with unit and network tests.
```suggestion
In the final section of this tutorial, how the application can be tested with unit and network tests is covered.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +Writing tests for the application gets more and more important, the more complex the blockchain application gets.
```suggestion
Writing tests for the application is more and more important, the more complex the blockchain application becomes.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +Once it reaches a certain complexity, it won't be convenient anymore to test the application functionality with the dashboard plugin, the CLI or via a frontend, and writing tests becomes a crucial pa
```suggestion
Once a certain complexity is reached, it will not be convenient anymore to test the application functionality with the dashboard plugin, the CLI or via a frontend; and writing tests becomes a crucial part to verify the correct behavior of the blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +For this purpose, we will first add a couple of unit tests to the application in this chapter, and then a couple of network tests in the next chapter.
```suggestion
For this purpose, a couple of unit tests are added to the application in this chapter, which is followed by a couple of network tests in the next chapter.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +To make the creation of tests convenient, we will make use of xref:{url_reference_testsuite}[].
```suggestion
To ensure the creation of the tests can be performed in a convenient manner, the  xref:{url_reference_testsuite}[] will be used.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +The `test` folder is the place to store all the kind of different tests for th blockchain application.
```suggestion
The `test` folder is the correct location to store all kinds of different tests for the blockchain application.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +As you can see, there are already some existing test files for the lns module and the assets.
```suggestion
As can be seen, there are already some existing test files for the lns module and the assets.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +Most of the code is self-explanatory, but the most important parts of the tests are summarized here for a better overview:
```suggestion
Most of the code is self-explanatory, but the most important parts of the tests are summarized here to provide a better overview:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +* It not throw any error, if all asset parameters are valid.
```suggestion
* If no errors are thrown, then all asset parameters are valid.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +* It should throw error if name is registered for less than a year.
```suggestion
* It should throw an error if the name is registered for less than a year.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +* It should throw error if name is registered for more than 5 years
```suggestion
* It should throw an error if the name is registered for more than 5 years.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +* It should throw error if domain contains invalid tld.
```suggestion
* It should throw an error if the domain contains an invalid tld.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +No need to put a real address here in this case, as it isn't used in the tests.
```suggestion
It is not necessary to put a real address here in this case, as it is not used in the tests.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +** It should throw error if name is already registered.
```suggestion
** It should throw an error if the name is already registered.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +This allows to check in the tests, if the respective functions have been called or not.
```suggestion
This allows checking in the tests if the respective functions have been called or not.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +The complete code of the tests for the Reverse Lookup asset is described below.
```suggestion
The entire code for the tests of the Reverse Lookup asset is described below.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +Most of the code is self-explanatory, but the most important parts of the tests are summarized here for a better overview:
```suggestion
The majority of the code is self-explanatory, however, the most important parts of the tests are summarized here to provide a better overview:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +** It should update the lns reverse-lookup of the sender account with given node if not already set.
```suggestion
** It should update the lns reverse-lookup of the sender account with the given node if it is not already set.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +** It should update the lns reverse-lookup of the sender account with given node even if already set.
```suggestion
** It should update the lns reverse-lookup of the sender account with the given node even if it is already set.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +** It should throw error if node to set-lookup is not owned by sender.
```suggestion
** It should throw an error if the node to set-lookup is not owned by the sender.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +This allows to check in the tests, if the respective functions have been called or not.
```suggestion
This allows checking to be performed in the tests, if the respective functions have been called or not.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +As a last exercise, write a functional test, that checks if a domain name was correctly resolved after calling the action `lns:resolveName`.
```suggestion
As a final exercise, it is recommended to write a functional test that checks if a domain name was correctly resolved after calling the action `lns:resolveName`.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +* `resolveName` action of the LNS module
```suggestion
* `resolveName` action of the LNS module.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +** It should throw error on resolving non-registered name.
```suggestion
** It should throw an error on resolving a non-registered name.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +** It should resolve name after registration.
```suggestion
** It should resolve the name after registration.
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/index.adoc
> +This chapter covers how to...
```suggestion
This chapter covers how to perform the following:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/index.adoc
> +This chapter covers how to...
```suggestion
This chapter covers how to perform the following:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/index.adoc
> +This chapter covers how to...
```suggestion
This chapter covers how to perform the following:
```

2021-10-01 08:28 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/index.adoc
> +This chapter covers how to...
```suggestion
This chapter covers how to perform the following:
```

2021-10-01 08:28 UTC, chris529 reviewed
Looks good, just minor points,.. 👍

2021-10-01 10:03 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +To make it more convenient for normal users to use the application, add a frontend to the application which is specialized on the respective use case of the LNS applicationn.
```suggestion
To make the application more user-friendly, add a frontend which is specialized for the respective use case of the LNS application.
```

2021-10-01 10:04 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +For the LNS app, we want to provide a simple *frontend as a plugin*, which is registered to the LNS blockchain application.
it is not really recommended, it is more one of multiple approaches how to add a frontend to the application.

2021-10-01 10:06 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +The main logic of the React application is located under `lns-dashboard-plugin/src/ui/`, and the main logic fie the LNS UI Plugin is located in `lns-dashboard-plugin/src/app/`.
```suggestion
The main logic of the React application is located under `lns-dashboard-plugin/src/ui/`, and the main logic of the LNS UI Plugin is located in `lns-dashboard-plugin/src/app/`.
```

2021-10-01 10:10 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +You can also see the new TXT record that was added to the LNS object.
```suggestion
The new TXT record, which was added to the LNS object, can also be seen.
```

2021-10-01 10:20 UTC, Tschakki commented on modules/ROOT/pages/tutorials/index.adoc
> +* ...create a blockchain application with a module which provides a Lisk name service.
```suggestion
* ...create a blockchain application with a module which provides a name service for Lisk addresses.
```

2021-10-01 10:21 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +To customize the default blockchain application to suit our desired use case, we will now generate the LNS module skeleton.
```suggestion
To customize the default blockchain application to suit our desired use case, generate the LNS module skeleton.
```

2021-10-01 10:24 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The first thing we define in the file, is an interface  for the expected asset data of a `register` transaction.
```suggestion
Firstly define an interface for the expected asset data of a `register` transaction.
```

2021-10-01 10:25 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +We want to validate the following:
```suggestion
Validate the following:
```

2021-10-01 10:26 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The corresponding checks look like this:
```suggestion
The corresponding code looks like this:
```

2021-10-01 10:31 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Based on this interface, we can create the corresponding schema, which looks like this:
```suggestion
Based on this interface, create the corresponding schema, as shown below:
```

2021-10-01 10:46 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +All three actions are returning an <<lns-node-schema, LNS object>>, based on different input parameters like the address it is registered to, the domain name that is registered in the LNS object, or
```suggestion
All three actions are returning an <<lns-node-schema, LNS object>>, based on different input parameters, like: the address it is registered to, the domain name that is registered in the LNS object, or a hash of the LNS object, which is typically stored in user account under the key `lns.ownNodes`.
```

2021-10-01 10:51 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +TIP: A lot of detailed information about this process can be found in the guide xref:{url_guide_genesisblock}[].
```suggestion
TIP: Detailed information about this process can be found in the guide xref:{url_guide_genesisblock}[].
```

2021-10-01 10:51 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Before we go on with developing the frontend part of the LNS application, let's quickly check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapter
```suggestion
Before proceeding with developing the frontend part of the LNS application, let's quickly check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapter.
```

2021-10-01 10:55 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +You can skip this step, if you don't create a new account in step <<create-new-account>>, but rather use on of the existing genesis accounts.
```suggestion
This step can be skipped if you do not create a new account in the step <<create-new-account>>, and rather use one of the existing genesis accounts instead.
```

2021-10-01 10:57 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The actions expects as input a boolean, if the plugin should be enabled, and a password the decrypt the encrypted passphrase that was saved in `config.json` above.
```suggestion
The action expects a boolean  as input, defining if the plugin should be enabled, and also a password to decrypt the encrypted passphrase that was saved in `config.json` above.
```

2021-10-01 11:08 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +Play around as much as you like with the LNS application UI.
```suggestion
Familiarize yourself as much as you like with the LNS application UI before moving on.
```

2021-10-01 11:12 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +If the LNS application os not already running, start it again:
```suggestion
If the LNS application is not already running, start it again:
```

2021-10-01 11:15 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +As last topic of this tutorial, we'll explore how the application can be tested with unit and network tests.
```suggestion
In the last chapter of this tutorial, it is covered how the application can be tested with unit and network tests.
```

2021-10-01 11:17 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +As last topic of this tutorial, we'll explore how the application can be tested with unit and network tests.
```suggestion
In the final chapter of this tutorial, we'll explore how the application can be tested with unit and network tests.
```

2021-10-01 11:27 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +This allows to check in the tests, if the respective functions have been called or not.
```suggestion
This allows checking in the tests, if the respective functions have been called or not.
```

2021-10-01 11:28 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +As a last exercise, write a functional test, that checks if a domain name was correctly resolved after calling the action `lns:resolveName`.
```suggestion
As a final exercise, write a functional test, that checks if a domain name was correctly resolved after calling the action `lns:resolveName`.
```

2021-10-04 07:54 UTC, chris529 reviewed
Looks great! just a few minor points 👍

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Please use `lisk-name-service/lns` as root folder for the LNS blockchain application, and `lns` as application name.
```suggestion
Please use `lisk-name-service/lns` as the root folder for the LNS blockchain application, and `lns` as the application name.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<1> The newly created skeleton for the LNS module
```suggestion
<1> The newly created skeleton for the LNS module.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The first part of the module that we implement here are the assets to handle the different transaction types `register`, `reverse lookup` and `update records`.
```suggestion
The first part of the module to be implemented here are the assets to handle the different transaction types `register`, `reverse lookup`, and `update records`.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +As first step for creating the asset, use Lisk Commander again, this time, to create the asset skeleton.
```suggestion
As the first step for creating the asset, use Lisk Commander again, this time to create the asset skeleton.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The corresponding code looks like this:
```suggestion
The corresponding code can be seen below:
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +<1> `type`: Type of the records as number.
```suggestion
<1> `type`: Type of the records as a number.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Open the file `lns/constants.ts`, which was created in step <<validation>>, and add the following constants:
```suggestion
Open the file `lns/constants.ts`, which was created in the <<validation>> step, and add the following constants:
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Then, import the constants inside of `update_records.ts` and implement the `validate` function as follows:
```suggestion
Now import the constants inside of `update_records.ts` and implement the `validate` function as follows:
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +As can be seen, the following values have been pre-filled when creating the LNS module with Lisk Commander in step <<bootstrapping-the-default-application>>.
```suggestion
As can be seen, the following values have been pre-filled when creating the LNS module with Lisk Commander in the step <<bootstrapping-the-default-application>>.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The methods required in reducers are very similar to the methods in the <<actions>> above.
```suggestion
The methods required in the reducers are very similar to the methods in the <<actions>> above.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The only difference is that the `StateStore` is available inside of reducers, so it can be used instead of `dataAccess` to query the database:
```suggestion
The only difference is that the `StateStore` is available inside of the reducers, so it can be used instead of `dataAccess` to query the database:
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Add the code of the functions `resolveNode()`, resolveName()` and `lookupAddress()` to the file `storage.ts`, to complete the implementation of the actions and reducers of the LNS module.
```suggestion
Add the code of the functions `resolveNode()`, resolveName()`, and `lookupAddress()` to the file `storage.ts`, to complete the implementation of the actions and reducers of the LNS module.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Before proceeding with developing the frontend part of the LNS application, let's quickly check if the blockchain application is working as expected by enabling the Dashboard plugin in the next chapt
```suggestion
Before proceeding with developing the frontend part of the LNS application, quickly check if the blockchain application is working as expected by enabling the Dashboard plugin as described in the next chapter.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +The action expects a boolean  as input, defining if the plugin should be enabled, and also a password to decrypt the encrypted passphrase that was saved in `config.json` above.
```suggestion
The action expects a boolean as an input, defining if the plugin should be enabled, and also a password to decrypt the encrypted passphrase that was saved in `config.json` above.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +Click on the button kbd:[Generate new account] in the top right corner of the page to create a new account:
```suggestion
Click on the kbd:[Generate new account] button in the top right corner of the page to create a new account:
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/2-frontend.adoc
> +This was done in step xref:{url_lns_1_register}[Register Domain] of Chapter 1 via the Dashboard plugin.
```suggestion
This was done in the step xref:{url_lns_1_register}[Register Domain] of Chapter 1 via the Dashboard plugin.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/3-cli.adoc
> +They are directly created when the application isa bootstrapped with Lisk Commander with `lisk init`.
```suggestion
They are directly created when the application is bootstrapped using Lisk Commander with `lisk init`.
```

2021-10-04 07:54 UTC, chris529 commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +{url_wikipedia_functionaltesting}[Functional testing] is a quality assurance (QA) process and a type of black-box testing that bases its test cases on the specifications of the software component und
```suggestion
{url_wikipedia_functionaltesting}[Functional testing] is a quality assurance (QA) process and a type of black-box testing that bases its test cases on the specifications of the software component under test. Functions are tested by feeding them input and examining the output, although the internal program structure is rarely considered here (unlike white-box testing).
```

2021-10-04 08:20 UTC, chris529 submitted a review, later dismissed
LGTM!

2021-10-04 09:38 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +I.e. if you build any DNS provider service on top of the LNS app, then you can use CNAME and TXT records differently there.
```suggestion
For example if you build any DNS provider service on top of the LNS app, then you can use CNAME and TXT records differently there.
```

2021-10-04 09:40 UTC, merged