Fixes broken links in core docs v2.1.6 - Closes #1150
LiskArchive/lisk-legacy-docs pull request #1174
Opened 2021-08-24 12:35 UTC by chris529

2021-08-24 12:57 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_getting_started: master@lisk-core::setup/npm.adoc
```suggestion
:url_getting_started: setup/application.adoc
```

this needs to point to the v2 setup pages

2021-08-24 12:57 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +//:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
why is this line added?

2021-08-24 13:05 UTC, Tschakki requested changes

2021-08-24 13:05 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_getting_started: master@lisk-core::setup/npm.adoc
```suggestion
:url_getting_started: setup/application.adoc
```

this needs to point to the v2 setup pages

2021-08-24 13:05 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +//:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
Why is this line added?

2021-08-24 13:05 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +NOTE: To learn how to set up a node, please go to the xref:{url_getting_started}[npm setup] page.
```suggestion
NOTE: To learn how to set up a node, please go to the xref:{url_getting_started}[appllication setup] page.
```

2021-08-24 13:05 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +:url_management_api: {v_sdk}@lisk-sdk::references/lisk-framework/http-api-plugin.adoc
This guide is does not exist anymore. Please remove the reference completely from the page.

2021-08-24 13:05 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +:url_management_ssl: {v_sdk}@lisk-sdk::guides/node-management/non-forging-node-protection.adoc#ssl-termination
This guide is does not exist anymore. Please remove the reference completely from the page.

2021-08-24 13:05 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
> +:url_config_api_access: {v_sdk}@lisk-sdk::references/lisk-framework/http-api-plugin.adoc#default-configuration
This documennt is does not exist anymore. Please remove the sentence with the reference completely from the page.

2021-08-24 13:20 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:url_getting_started: master@lisk-core::setup/npm.adoc
Ah yes..OK thanks Mona 👍

2021-08-24 13:21 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +NOTE: To learn how to set up a node, please go to the xref:{url_getting_started}[npm setup] page.
There is a typo in the change above..(application)

2021-08-24 15:07 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +//:url_config_api: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
I put the double slash // in front so it would be ignored, however, I have now removed it 👍

2021-08-24 15:17 UTC, chris529 commented on modules/ROOT/pages/management/configuration.adoc
> +:url_management_api: {v_sdk}@lisk-sdk::references/lisk-framework/http-api-plugin.adoc
👍

2021-08-24 15:19 UTC, chris529 commented on modules/ROOT/pages/management/configuration.adoc
> +:url_management_ssl: {v_sdk}@lisk-sdk::guides/node-management/non-forging-node-protection.adoc#ssl-termination
👍

2021-08-24 15:24 UTC, chris529 commented on modules/ROOT/pages/setup/application.adoc
> +:url_config_api_access: {v_sdk}@lisk-sdk::references/lisk-framework/http-api-plugin.adoc#default-configuration
Done 👍

2021-09-06 15:25 UTC, Tschakki approved these changes, later dismissed
LGTM

2021-09-06 15:28 UTC, Tschakki requested changes

2021-09-06 15:28 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_getting_started: master@lisk-core::setup/npm.adoc
Please apply my suggestion above, it should point to the setup for v2, not v3

2021-09-13 12:30 UTC, Tschakki approved these changes
Thanks!

2021-09-16 08:20 UTC, merged