Improve forging guide - Closes #1182, #1177
LiskArchive/lisk-legacy-docs pull request #1185
Opened 2021-09-27 14:57 UTC by Tschakki

Closes #1182, #1177

2021-10-06 12:52 UTC, MaximeGagnebin requested changes
Looks good, only left a few typo style comments.

2021-10-06 12:52 UTC, MaximeGagnebin commented on modules/ROOT/pages/management/forging.adoc
> +.. Never activate forging for the same delegate on two or more nodes at the same time(a.k.a double-forging).
```suggestion
.. Never activate forging for the same delegate on two or more nodes at the same time (a.k.a double-forging).
```

2021-10-06 12:52 UTC, MaximeGagnebin commented on modules/ROOT/pages/management/forging.adoc
> +The following tools can be used to simplify the process of enabling forging:
Should we stress here that they are community tools?

2021-10-06 12:52 UTC, MaximeGagnebin commented on modules/ROOT/pages/management/forging.adoc
> +* `MAX_FORK_DEPTH = 8640`: An upper bound on the largest chain of off-chain blocks for which the validator generator a block, i.e., for every block at height `h` generated by the validator, the paren
```suggestion
* `MAX_FORK_DEPTH = 8640`: An upper bound on the largest chain of off-chain blocks for which the validator generated a block, i.e., for every block at height `h` generated by the validator, the parent block at height `h - MAX_FORK_DEPTH` must be contained in the canonical chain that is eventually finalized.
```

2021-10-06 12:52 UTC, MaximeGagnebin commented on modules/ROOT/pages/management/forging.adoc
> + parentBlock.height = finalizedBlock.header.height - MAX_FORK_DEPTH
```suggestion
 parentBlock.header.height = finalizedBlock.header.height - MAX_FORK_DEPTH
```

2021-10-06 13:32 UTC, MaximeGagnebin submitted a review, later dismissed
LGTM

2021-10-06 15:51 UTC, shuse2 requested changes

2021-10-06 15:51 UTC, shuse2 commented on modules/ROOT/pages/management/forging.adoc
> +====
im not sure if we should put this in the official documentation because we never tested nor checked if it's valid

2021-10-07 06:26 UTC, MaximeGagnebin commented on modules/ROOT/pages/management/forging.adoc
> +====
Do we have a place in the documentation where we could have those ? Maybe a separate "Community Tools" page, where we can have a longer disclaimer. 
Because, the community does write useful things and  they are pretty hard to find for new comers.

2021-10-07 08:33 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +====
Imho we should create a Wiki post in the Dev Forum, summarizing all existing (community) tools & services for the Lisk eecosystem (see https://meta.discourse.org/t/what-is-a-wiki-post/30801) - we will discuss this in the next STM concerning the topic. So imho we can remove this info here now, and put it in the forum.

2021-10-07 09:33 UTC, shuse2 approved these changes

2021-10-07 09:38 UTC, merged