Update issue templates - Closes #1188
LiskArchive/lisk-legacy-docs pull request #1194
Opened 2021-10-06 13:49 UTC by Tschakki

Closes #1188

2021-10-06 14:53 UTC, shuse2 reviewed
I think all repositories are following the same format
docs repo can also align on the same format?
https://github.com/LiskHQ/lisk-sdk/tree/development/.github/ISSUE_TEMPLATE

2021-10-12 08:11 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-10-12 08:11 UTC, chris529 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +about: Create a report to help us improve
```suggestion
about: Create a report to help us further improve.
```

2021-10-12 08:11 UTC, chris529 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Describe the current documentation content that is buggy.
```suggestion
Describe the specific content of the documentation that you feel could be improved.
```

2021-10-12 08:11 UTC, chris529 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +about: Suggest an idea for thee Lisk documentation
```suggestion
about: Suggest a recommendation for improving the Lisk documentation.
```

2021-10-12 08:11 UTC, chris529 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Please describe what functionality is needed.
```suggestion
Please describe what functionality is required.
```

2021-10-12 08:11 UTC, chris529 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Please describe why it is needed.
```suggestion
Please describe why it is required.
```

2021-10-12 08:11 UTC, chris529 commented on .github/ISSUE_TEMPLATE/update-request.md
> +about: Describe this issue template's purpose here.
```suggestion
about: Describe the objective and reason for this issue here.
```

2021-10-12 08:55 UTC, Tschakki commented on .github/ISSUE_TEMPLATE/update-request.md
> +about: Describe this issue template's purpose here.
```suggestion
about: Report outdated content in the documentation.
```

2021-10-13 08:20 UTC, chris529 submitted a review, later dismissed
LGTM!

2021-10-13 08:35 UTC, shuse2 requested changes
just minor point, LGTM

2021-10-13 08:35 UTC, shuse2 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Expected content**
```suggestion
### Expected content
```
We use h3 `###` in general

2021-10-13 08:54 UTC, merged