Fix bugs in frontend guide - Closes #1196
LiskArchive/lisk-legacy-docs pull request #1197
Opened 2021-10-11 10:45 UTC by Tschakki

Closes #1196

2021-10-14 09:10 UTC, ricott1 submitted a review, later dismissed
LGTM

2021-10-20 10:03 UTC, shuse2 requested changes
Overall LGTM. just one minor format issue

2021-10-20 10:03 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/frontend.adoc
> +=== Send Transfer transaction
There is link to this title, so that also needs to be updated in `3. Create basic components`

2021-10-21 20:49 UTC, shuse2 approved these changes

2021-10-22 08:47 UTC, merged