Add update guide (binary) - Partially closes #1026, Closes #1205
LiskArchive/lisk-legacy-docs pull request #1209
Opened 2021-10-15 10:19 UTC by Tschakki

Partially closes #1026
Closes #1205

2021-10-15 11:25 UTC, ManuGowda commented on modules/ROOT/pages/management/forging.adoc
> +//TODO: Add examples/description/warnings on the --overwrite flag
do you plan to add them?

2021-10-15 11:25 UTC, ManuGowda commented on modules/ROOT/pages/update/binary.adoc
> +wget -O lisk-core-v3.0.2.tar.gz https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
I think we should write this steps for more general updates? this looks more specific to 3.0.2? which is kinda already take care in devpost? this guide should be useful for all upcoming updates?

2021-10-15 12:23 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +wget -O lisk-core-v3.0.2.tar.gz https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
Not sure, it might be also beneficial for readers to have examples they can copy paste directly to update to the latest version. I think most people would like to update to the latest version always, so it saves them time. We can update the update guides quickly for each new version, as we need to bump the version in docs anyway.

2021-10-15 12:28 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +//TODO: Add examples/description/warnings on the --overwrite flag
yes, but not as part of this PR

2021-10-15 12:31 UTC, ghost requested changes

2021-10-15 12:31 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +wget -O lisk-core-v3.0.2.tar.gz https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
Why change the downloaded file name? (`-O lisk-core-v3.0.2.tar.gz`)

2021-10-15 12:31 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar cf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
Call the file `backup_lisk.tar.gz` or actually gzip it.

2021-10-15 12:31 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
Inconsistent: at the top of this file we used relative paths, then `~/` and now the absolute paths.

2021-10-15 12:31 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +grep unlockFixHeight /home/lisk/.lisk/lisk-core/config/testnet/config.json
Maybe suggest using `jq` if instanlled? Or at least show the expected output of `grep`? (which won't be as neat as `jq`'s)

2021-10-15 12:42 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +grep unlockFixHeight /home/lisk/.lisk/lisk-core/config/testnet/config.json
User suggested to check the value with `lisk-core node:info | jq` sounds better for me, what do you think?

2021-10-15 12:47 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +wget -O lisk-core-v3.0.2.tar.gz https://downloads.lisk.io/lisk/main/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
Forgot to remove them. Would make next steps easier to explain, but I realised checksum are not working if renamed.

2021-10-15 12:49 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +tar cf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
What do you mean here?

2021-10-15 12:51 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
I will then change to `~/` it's more generic

2021-10-15 12:56 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +grep unlockFixHeight /home/lisk/.lisk/lisk-core/config/testnet/config.json
Or better `lisk-core node:info --pretty | grep unlockFixHeight`

2021-10-15 13:01 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar cf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
Pick either `tar cf ~/backup_lisk.tar ~/.lisk/ ~/lisk-core/` or `tar czf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/`

2021-10-15 13:02 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar cf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
Side node: I don't think it's useful to backup `~/lisk-core/`.

2021-10-15 13:26 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +tar cf ~/backup_lisk.tar.gz ~/.lisk/ ~/lisk-core/
It can be, as for example many people have their custom configs stored in there. Though if you give the file a custom name, it will stay, but if you customized one of the original configs it will be overwritten by the update I think.

2021-10-15 13:28 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
Why can we extract `tar.gz` with `tar xf`, shouldn't it be `tar xzf`?

2021-10-15 13:31 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
btw should we include a step ` rm -r ~/lisk-core` before extrating the new version?

2021-10-15 13:36 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
> Why can we extract `tar.gz` with `tar xf`, shouldn't it be `tar xzf`?

GNU tar (which you will find in pretty much any linux distributions) will detect that the tarball is `gzip`ed and handle that just fine. That might not be true for other `tar` implementations. So it might be safer to recommend using `tar xzf`, yes.

2021-10-15 13:37 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar xf /home/lisk/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
> btw should we include a step ` rm -r ~/lisk-core` before extrating the new version?

Yes, we should. My suggestion was:

```
mv ~/lisk-core ~/lisk-core_
tar czf ~/dot_lisk.tar.gz ~/.lisk/
tar xf lisk-core-v3.0.2-linux-x64.tar.gz
# make sure everything works
rm -rf ~/lisk-core/
```

2021-10-15 14:26 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +rm -rf ~/.lisk/lisk-core/
I am not sure about that. Why?

2021-10-15 14:26 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar xzf ~/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
```suggestion
tar xzf ~/lisk-core-v3.0.2-linux-x64.tar.gz -C ~/
```

2021-10-15 14:27 UTC, Tschakki commented on modules/ROOT/pages/update/binary.adoc
> +rm -rf ~/.lisk/lisk-core/
Ah, good point... yes probably the `data/` folder is important to keep ^^ will remove this line

2021-10-15 14:35 UTC, ghost commented on modules/ROOT/pages/update/binary.adoc
> +tar xzf ~/lisk-core-v3.0.2-darwin-x64.tar.gz -C /home/lisk/
```suggestion
tar xzf ~/lisk-core-v3.0.2-darwin-x64.tar.gz -C ~/
```

2021-10-15 15:15 UTC, ghost submitted a review, later dismissed

2021-10-18 06:10 UTC, ManuGowda submitted a review, later dismissed
At the moment the following guide seems more specific to 3.0.2, e.g `unlockFixHeight` section is not required for future. So for now I will approve, but please create an issue to make it generic update section?

2021-10-18 06:10 UTC, ManuGowda commented on modules/ROOT/pages/management/forging.adoc
> +  ADDRESS                    Address of an account in hexadecimal representation.
```suggestion
  ADDRESS                    Address of an account in hex format.
```
all other commands have `hex format`, lets keep it the same way for now, we can change it together.

2021-10-18 07:38 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +  ADDRESS                    Address of an account in hexadecimal representation.
@ManuGowda I replied concerning making it generic already above, please take my above comment into account.

2021-10-18 08:19 UTC, merged