Create npm update guide - Partially closes #1026, #1212
LiskArchive/lisk-legacy-docs pull request #1210
Opened 2021-10-15 12:25 UTC by Tschakki

Partially closes #1026, #1212

2021-10-17 14:40 UTC, mrv777 commented on modules/ROOT/pages/update/binary.adoc
> +tar xzf ~/lisk-core-v3.0.2-linux-x64.tar.gz -C /home/lisk/
Why assume the user is `lisk`?

2021-10-18 09:31 UTC, ghost requested changes

2021-10-18 09:31 UTC, ghost commented on modules/ROOT/pages/setup/binary.adoc
> +:description: How to install and setup up a Lisk Core (binary distribution).
```suggestion
:description: How to install and setup a Lisk Core (binary distribution).
```

2021-10-18 09:31 UTC, ghost commented on modules/ROOT/pages/setup/npm.adoc
> +npm install --global lisk-core
What is the reason behing dropping the `--production` flag?

2021-10-18 09:31 UTC, ghost commented on modules/ROOT/pages/setup/npm.adoc
> +Lisk Core will be installed under the path `/usr/local/bin/node` for most systems.
Isn't `/usr/local/bin/node` the path to the node binary (file)? (And not the path (directory) where core will be installed.)

2021-10-18 09:31 UTC, ghost commented on modules/ROOT/pages/setup/source.adoc
> +:description: How to install and setup up a Lisk Core node from Source.
```suggestion
:description: How to install and setup a Lisk Core node from source.
```

2021-10-18 09:31 UTC, ghost commented on modules/ROOT/pages/update/npm.adoc
> +tar czf ~/backup_lisk.tar.gz ~/.lisk/lisk-core ~/.nvm/versions/node/v12.22.7/lib/node_modules/lisk-core/
Why include `~/.nvm/versions/node/v12.22.7/lib/node_modules/lisk-core/` in the tarball? I can imagine that some people will wan to save their `~/lisk-core/config.json` but will there ever be something one wants to keep under `~/.nvm/versions/node/v12.22.7/lib/node_modules/lisk-core/`?

2021-10-18 09:31 UTC, ghost commented on modules/ROOT/pages/update/npm.adoc
> +npm outdated -g --depth=0
```suggestion
npm outdated --global --depth=0
```
For consistency (and in general) we should use long option names.

2021-10-18 09:36 UTC, Tschakki commented on modules/ROOT/pages/setup/npm.adoc
> +npm install --global lisk-core
I don't think it is required, or is it?

2021-10-18 09:46 UTC, Tschakki commented on modules/ROOT/pages/update/npm.adoc
> +tar czf ~/backup_lisk.tar.gz ~/.lisk/lisk-core ~/.nvm/versions/node/v12.22.7/lib/node_modules/lisk-core/
I thought in case they have their custom configs there, but probably they will store them in another location, will remove

2021-10-18 09:52 UTC, ghost commented on modules/ROOT/pages/setup/npm.adoc
> +npm install --global lisk-core
I don't know but I think we should not remove it without a justification.

2021-10-18 10:11 UTC, Tschakki commented on modules/ROOT/pages/setup/npm.adoc
> +npm install --global lisk-core
@ManuGowda can you please verify the `--production` flag is not required anymore to setup Core with NPM?

2021-10-18 16:03 UTC, Tschakki commented on modules/ROOT/pages/setup/npm.adoc
> +npm install --global lisk-core
For reference, the tag is also not mentioned here: https://www.npmjs.com/package/lisk-core

2021-10-19 14:26 UTC, ManuGowda commented on modules/ROOT/pages/setup/npm.adoc
> +npm install --global lisk-core
No longer required, please remove it

2021-10-20 08:31 UTC, ManuGowda approved these changes
except the comment already mentioned, LGTM

2021-10-20 08:36 UTC, ghost approved these changes

2021-10-20 08:50 UTC, merged