Update constants package - Closes #118
LiskArchive/lisk-legacy-docs pull request #122
Opened 2018-11-21 12:10 UTC by Tschakki

Closes #118

2018-11-22 13:30 UTC, shuse2 requested changes
There is one constants added in `lisk-cryptography`

2018-11-22 13:50 UTC, Tschakki commented
@shuse2 where exactly? don't see it.

2018-11-22 15:59 UTC, shuse2 commented
New constants has been added here

https://github.com/LiskHQ/lisk-elements/pull/857/files#diff-bdb2ea94c1e1061b8d186fdefa04b3b5R15

2018-12-03 13:18 UTC, shuse2 approved these changes

2018-12-07 09:32 UTC, merged