Updates and all associated links in the glossary in sdk docs v5.1.4 - Closes #1189
LiskArchive/lisk-legacy-docs pull request #1228
Opened 2021-11-01 15:57 UTC by chris529

Major overhaul in the SDK glossary removed ambiguous terminologies and added in all associated links throughout the SDK docs pertaining to all relevant glossary entries.

2021-11-04 11:53 UTC, Tschakki requested changes

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +==== Load via CDN (Content Delivery Network)
Would remove it either from the title , or in the description below, 1 time is enough

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +A blockchain application communicates via <<actions>> and <<events>> which can be invoked (actions) or subscribed to (events) via RPCs (Remote-Procedure-Calls).
No need to explain a terminology twice on the same page, please remove

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +In all front-end products, addresses are displayed in a human-readable representation called <<Lisk32 representation>>.
this anchor link doesnt look right

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +The Lisk32 representation of an <<Account Address>> starts with the letters "lsk" followed by a custom Base32 encoding of the 20 bytes of the address appended with a BCH checksum.
wrong link format

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
>  === BCH Codes - Bose, Chaudhuri and Hocquenghem codes
BIP should be removed as well.

Blockchain application description should be improved, as it is very short, also, we have now a page dedicated to explain blockchain applications, the glossary should link to it.

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
>  The official main network of Lisk.
Description could be improved, as it very short. Also, we have a page in the docs explaining the different networks, the glossary should link to it.

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +A reducer is classed as a function which takes two arguments, namely an action and the previous state of the application, and returns the new state.
I don't think this description is correct

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +The state store is a data structure that holds a temporary state while processing a block.
Description should be improved, as it is very short. Also, we are explaining the state store in the docs, the glossary can link to it.

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
>  The official testing network of Lisk.
Description is veery short, should be improved

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
>  An interaction with the Lisk blockchain which permanently writes data to it.
Description here can be improved as well, e.g. describing which properties a transaction object has in general

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +The optional function `validate()` validates the data of a xref:{url_transaction_asset}[transaction asset], before it is passed to the `apply()` function.
no need to link again to the glossary

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +The most important part of the xref:{url_module_asset}[module asset] is the `apply()` function.
no need to link again to the glossary

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +The xref:{url_lisk_sdk}[Lisk SDK] will run on both the Ubuntu and MacOS operating systems shown below:
no need to link again to the glossary

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/references/application-cli.adoc
> +Lisk interactive REPL (Read-eval-print loop), session to run commands.
No need to explain it twice on the same page

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +Lisk interactive REPL (Read-eval-print loop), session to run commands.
No need to explain it twice on the same page

2021-11-04 11:53 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +The PeerBook exposes actions to perform CRUD (Create, Read, Update & Delete), operations based on peerId whereby the caller is agnostic to newPeers, triedPeers and their bucketing system.
No need to explain it twice on the same page

2021-11-04 11:53 UTC, Tschakki commented on modules/protocol/pages/appendix.adoc
> +The passphrase is then hashed using the SHA-256 (Secure Hash Algorithm 256), into a 256-bit string. The resulting hash is used as the seed to generate the [#index-private_key-1]#*private key*# and th
No need to explain it twice on the same page

2021-11-05 10:31 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +In all front-end products, addresses are displayed in a human-readable representation called <<Lisk32 representation>>.
As discussed, it is now updated 👍

2021-11-05 10:50 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +==== Load via CDN (Content Delivery Network)
Done 👍

2021-11-05 10:56 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +A blockchain application communicates via <<actions>> and <<events>> which can be invoked (actions) or subscribed to (events) via RPCs (Remote-Procedure-Calls).
Done, I have removed the duplicated explanation in the "Actions" paragraph which occurs after the "Interfaces" paragraph. 👍

2021-11-05 12:44 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
>  === BCH Codes - Bose, Chaudhuri and Hocquenghem codes
We agreed in the Glossary & Ambigous terminologies STM that we would keep BIP (See excel sheet in Trello card).
I have expanded the description of 'Blockchain Application' and also now added a link to the Blockcahin App page 👍

2021-11-05 14:26 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
>  The official main network of Lisk.
Updated the mainnet description and added a link 👍

2021-11-05 14:38 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +A reducer is classed as a function which takes two arguments, namely an action and the previous state of the application, and returns the new state.
I have amended it, please feel free to add/amend/update if you feel there is something else we could add here..?

2021-11-05 15:02 UTC, ishantiw requested changes
Looks good, just a couple of comments

2021-11-05 15:02 UTC, ishantiw commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +. Only domains with valid TLDs (Top-level domain), can be registered.
```suggestion
. Only domains with valid TLDs (Top-Level Domain), can be registered.
```

2021-11-05 15:02 UTC, ishantiw commented on modules/ROOT/pages/tutorials/lns/1-blockchain.adoc
> +. Only domains with valid TLDs (Top-level domain), can be registered.
or `top-level domain`

2021-11-05 15:02 UTC, ishantiw commented on modules/ROOT/pages/tutorials/nft.adoc
> +The minimum value for it is `1024`, as the other IDs are reserved for future default modules of the xref:{url_lisk_sdk}[Lisk SDK].
```suggestion
The minimum value for it is `1000`, as the other IDs are reserved for future default modules of the xref:{url_lisk_sdk}[Lisk SDK].
```

2021-11-08 16:50 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +The state store is a data structure that holds a temporary state while processing a block.
Done 👍

2021-11-08 17:02 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
>  The official testing network of Lisk.
Have now updated the Testnet description, please feel free to add/amend if necessary 👍

2021-11-08 17:30 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
>  An interaction with the Lisk blockchain which permanently writes data to it.
I have expanded on the description, please free free to add/amend if necessary 👍

2021-11-09 07:58 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +The optional function `validate()` validates the data of a xref:{url_transaction_asset}[transaction asset], before it is passed to the `apply()` function.
Good point..it has now been removed 👍

2021-11-09 08:32 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +The most important part of the xref:{url_module_asset}[module asset] is the `apply()` function.
Done 👍

2021-11-09 08:33 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/setup.adoc
> +The xref:{url_lisk_sdk}[Lisk SDK] will run on both the Ubuntu and MacOS operating systems shown below:
Done 👍

2021-11-09 09:57 UTC, chris529 commented on modules/ROOT/pages/references/application-cli.adoc
> +Lisk interactive REPL (Read-eval-print loop), session to run commands.
Done 👍

2021-11-09 09:59 UTC, chris529 commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +Lisk interactive REPL (Read-eval-print loop), session to run commands.
Done 👍

2021-11-09 10:05 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +The PeerBook exposes actions to perform CRUD (Create, Read, Update & Delete), operations based on peerId whereby the caller is agnostic to newPeers, triedPeers and their bucketing system.
Done 👍

2021-11-09 10:10 UTC, chris529 commented on modules/protocol/pages/appendix.adoc
> +The passphrase is then hashed using the SHA-256 (Secure Hash Algorithm 256), into a 256-bit string. The resulting hash is used as the seed to generate the [#index-private_key-1]#*private key*# and th
Done 👍

2021-11-09 10:13 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +The Lisk32 representation of an <<Account Address>> starts with the letters "lsk" followed by a custom Base32 encoding of the 20 bytes of the address appended with a BCH checksum.
Corrected 👍

2021-11-11 10:16 UTC, ishantiw submitted a review, later dismissed

2021-11-11 16:42 UTC, Tschakki requested changes

2021-11-11 16:42 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +A blockchain application communicates via <<actions>> and <<events>> which can be invoked (actions) or subscribed to (events) via RPCs (Remote-Procedure-Calls).
I think the first time you explain it on line 36, so you can remove it here as well :) Also, `WebSocket` is actually more correct here, as RPC only refers to actions I think.

```suggestion
A blockchain application communicates via <<actions>> and <<events>> which can be invoked (actions) or subscribed to (events) via WebSocket.
```

2021-11-11 16:42 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +A transaction can have multiple purposes, e.g. a balance transfer or delegate registration, and posseses a common set of properties. Each transaction induces a specific operation on the accounts and
```suggestion
A transaction can have multiple purposes, e.g. a balance transfer or delegate registration.
Each transaction contains a module ID and an asset ID, defining the transaction type.
All properties of a transaction object are described on the xref:protocol:transactions.adoc#transaction-properties[Lisk protocol > Transactions] page. The input data for the different <<module-asset, module assets>> is stored inside the <<transaction-asset>> of a transaction.
```

2021-11-11 16:42 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
>  An interaction with the Lisk blockchain which permanently writes data to it.
I added my suggestion below!

2021-11-11 16:42 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +A reducer is classed as a function that determines changes to the state of an application. It can use the previous state and action to execute another state.
```suggestion
Reducers are functions which can be invoked via Remote-Procedure-Calls (RPC) by other modules.
Reducers are able to perform state changes on the blockchain.
Modules and module assets can invoke reducers through the `reducerHandler`.
See xref:introduction.adoc#reducers[Modules > Reducers] for more information.
```

2021-11-11 16:42 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +The xref:{url_state_store}[state store] is a data structure that holds a temporary state while processing a block. It is used to retrieve data from the blockchain, and exposes an interface to create,
That the state store exposes `an interface to create, restore, and finalize snapshots` is new to me.
Also, the third state `consensus` seems new to me, and is also not reflected in the stateStore interface:
https://lisk.com/documentation/lisk-sdk/introduction/modules.html#the-state-store

Please double check if the explanation is correct.

2021-11-11 16:47 UTC, Tschakki requested changes

2021-11-11 16:47 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +:url_mainnet: introduction/blockchain-applications.adoc
Lisk Mainnet is referring to the Lisk Core mainnet, not general blockchain applications

```suggestion
:url_mainnet: master@lisk-core::index.adoc#mainnet
```

2021-11-11 17:28 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +:url_mainnet: introduction/blockchain-applications.adoc
Ah yes...well spotted Mona! 👍

2021-11-11 17:33 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +A reducer is classed as a function that determines changes to the state of an application. It can use the previous state and action to execute another state.
Excellent! 👍

2021-11-12 09:12 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +The xref:{url_state_store}[state store] is a data structure that holds a temporary state while processing a block. It is used to retrieve data from the blockchain, and exposes an interface to create,
Thanks, I have reworded it accordingly 👍

2021-11-12 09:41 UTC, Tschakki approved these changes
Thank you, LGTM :)

2021-11-12 10:27 UTC, merged