Fixes broken links in sdk docs v5.2.0 - Closes #1220
LiskArchive/lisk-legacy-docs pull request #1230
Opened 2021-11-05 09:46 UTC by chris529

Closes #1220

2021-11-10 09:30 UTC, Tschakki requested changes

2021-11-10 09:30 UTC, Tschakki commented on modules/protocol/pages/index.adoc
> +:url_mainnet: pages/nav.adoc
The Mainnet protocol content was moved to the Core docs, so please remove the section to Mainnet related protocol here, or add the corresponding link to the Core protocol docs

2021-11-10 15:37 UTC, mitsuaki-u reviewed
LGTM besides @Tschakki comment

2021-11-11 16:50 UTC, chris529 commented on modules/protocol/pages/index.adoc
> +:url_mainnet: pages/nav.adoc
Good point Mona, OK I have now inked it to the Core docs, can you please check this..many thanks 👍

2021-11-11 16:55 UTC, Tschakki approved these changes
Looks good now!

2021-11-12 10:35 UTC, merged