Bump Node.js version from 8.12 to 8.13 - Closes #124
LiskArchive/lisk-legacy-docs pull request #126
Opened 2018-11-23 11:14 UTC by Tschakki

Closes #124

2018-12-07 13:40 UTC, diego-G approved these changes

2018-12-07 13:42 UTC, diego-G requested changes
Please, check bookmark links in the table of content.

2018-12-07 15:57 UTC, Tschakki commented
This got already fixed on another branch, I merged the changes now into this branch, please check again.

2018-12-10 08:24 UTC, diego-G approved these changes

2018-12-11 10:55 UTC, merged