Fixes broken links in Core docs v2 - Closes #1232
LiskArchive/lisk-legacy-docs pull request #1268
Opened 2021-11-10 17:20 UTC by chris529

2021-11-16 09:17 UTC, Tschakki requested changes
Not sure, why are you adding the v_core attribute, but never using it? If it is not used, it should be removed. Also, the links are not fixed correctly. Main issue seems to be the `v2/` is missing in the links. I added it now for a few, please correct the rest yourself. Please also check for all other next /  previous links for v2, they actually might have the same problem, even if not broken.

2021-11-16 09:17 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
>  :page-next: /lisk-core/interact-with-the-api.html
```suggestion
:page-next: /lisk-core/v2/interact-with-the-api.html
```

2021-11-16 09:17 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:v_core: v2
remove this

2021-11-16 09:17 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +:v_core: v2
remove

2021-11-16 09:17 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +:page-next: /management/configuration.html
```suggestion
:page-next: /lisk-core/v2/management/configuration.html
```

2021-11-16 09:17 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
>  :page-previous: /lisk-core/setup/commander.html
```suggestion
:page-previous: /lisk-core/v2/setup/commander.html
```

2021-11-17 15:44 UTC, chris529 commented on modules/ROOT/pages/index.adoc
>  :page-next: /lisk-core/interact-with-the-api.html
OK, will check...Many thanks Mona 👍

2021-11-17 16:18 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:v_core: v2
Done 👍

2021-11-17 16:38 UTC, chris529 commented on modules/ROOT/pages/management/commander.adoc
> +:v_core: v2
Done 👍

2021-11-18 15:13 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:v_core: v2
Hey Mona! Ref, your comments above...Yes, you are correct, I found some more broken links with missing instances of 'v2' so have also fixed them as well 👍

2021-11-19 10:44 UTC, Tschakki requested changes

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
> +:page-previous: /lisk-core/interact-with-the-api.html
```suggestion
:page-previous: /lisk-core/v2/interact-with-the-api.html
```

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +:v_core: v2
```suggestion
:v_core: 2.1.7
```

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
>  :page-next: /lisk-core/monitoring.html
```suggestion
:page-next: /lisk-core/v2/monitoring.html
```

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
> +:page-next: /lisk-core/docker.html
```suggestion
:page-next: /lisk-core/v2/monitoring.html
```

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
> +:page-next-title: Docker image
```suggestion
:page-next-title: Monitoring
```

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/update/docker.adoc
>  :page-next: /lisk-core/monitoring.html
```suggestion
:page-next: /lisk-core/v2/monitoring.html
```

2021-11-19 10:44 UTC, Tschakki commented on modules/ROOT/pages/update/source.adoc
>  :page-next: /lisk-core/monitoring.html
```suggestion
:page-next: /lisk-core/v2/monitoring.html
```

2021-11-19 12:07 UTC, chris529 commented on modules/ROOT/pages/update/source.adoc
>  :page-next: /lisk-core/monitoring.html
Cool, thanks, Mona, so there were even more!

2021-11-19 13:39 UTC, Tschakki approved these changes
Thanks, looking good now!

2021-11-19 15:36 UTC, merged