Add "What is Lisk Core?" video to Lisk Core introduction page - Closes #20
LiskArchive/lisk-legacy-docs pull request #128
Opened 2018-11-26 13:06 UTC by Tschakki

Closes #20

2018-11-26 13:59 UTC, RachBLondon commented on introduction.md
> +Lisk Core is releasing new versions regularly.
Maybe change `Lisk Core is releasing new versions regularly` to `We release new versions of Lisk Core regularly`

2018-11-26 14:00 UTC, RachBLondon submitted a review, later dismissed

2018-11-28 12:16 UTC, RachBLondon submitted a review, later dismissed

2018-12-07 13:36 UTC, diego-G requested changes

2018-12-07 13:36 UTC, diego-G commented on introduction.md
> +- [Lisk Core Version Reference](#versions)
I miss a top level bullet for introduction. It is misleading otherwise.

2018-12-07 13:36 UTC, diego-G commented on introduction.md
> +| | A Lisk Node connected to other Lisk Nodes is referred to as a Lisk **Peer**.
I miss an icon in here. Also, can we have more meaningful icons or even customised icons coming from the video? It would be awesome to follow the same thematic Julian has introduced.

2018-12-07 13:36 UTC, diego-G commented on introduction.md
> +We release new versions of Lisk Core regularly. As documentation on [lisk.io](https://lisk.io/documentation) will keep up to date with version updates, the table below provides an overview about docu
`As documentation on lisk.io, we will keep up to date with version updates. The table...`

2018-12-07 13:36 UTC, diego-G commented on introduction.md
> +[![What is Lisk Core?](https://img.youtube.com/vi/RfF9EPwQDOY/0.jpg)](https://www.youtube.com/watch?v=RfF9EPwQDOY)
Can we make it wider and reproducible?

2018-12-07 14:01 UTC, Tschakki commented on introduction.md
> +[![What is Lisk Core?](https://img.youtube.com/vi/RfF9EPwQDOY/0.jpg)](https://www.youtube.com/watch?v=RfF9EPwQDOY)
I think this is not straight forward in github markdown.

We can include the actual video in our documentation on the website though.

2018-12-07 15:45 UTC, Tschakki commented on introduction.md
> +| | A Lisk Node connected to other Lisk Nodes is referred to as a Lisk **Peer**.
it is the second row of the same table, and therefore doesn't need an extra icon. I Joined the 2 notes because they have related content and therefore it is not necessary to add 2 seperate note boxes.

2018-12-10 08:21 UTC, diego-G commented on introduction.md
> +| | A Lisk Node connected to other Lisk Nodes is referred to as a Lisk **Peer**.
It looks weird. It is empty.

2018-12-11 09:23 UTC, RachBLondon commented on introduction.md
> +We release new versions of Lisk Core regularly. As documentation on [lisk.io](https://lisk.io/documentation) will keep up to date with version updates, the table below provides an overview about docu
`We release new versions of Lisk Core regularly. Documentation on [lisk.io](https://lisk.io/documentation) will keep up to date with version updates`

2018-12-11 10:45 UTC, Tschakki commented on introduction.md
> +| | A Lisk Node connected to other Lisk Nodes is referred to as a Lisk **Peer**.
Have you seen it rendered? I think it looks fine. 2 Icons would look here weird to me, as did the 2 separate info boxes for me. So I think it's a good compromise.

I aggree in future we should use our own styling. But be aware these icons are only workaround for our docs on github - on the website we use the different styled info boxes, which have no icons atm.

2018-12-11 11:16 UTC, diego-G approved these changes

2018-12-11 11:22 UTC, merged