Fixes broken links in SDK docs v3.0.2 - Closes #1282
LiskArchive/lisk-legacy-docs pull request #1283
Opened 2021-11-12 14:59 UTC by chris529

2021-11-18 09:14 UTC, ishantiw approved these changes, later dismissed

2021-11-18 12:14 UTC, Tschakki requested changes

2021-11-18 12:14 UTC, Tschakki commented on modules/ROOT/pages/references/index.adoc
> +:v_sdk: v3
Why is this added?

2021-11-18 12:14 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +:v_sdk: v3
Why is this added?

2021-11-18 15:05 UTC, chris529 commented on modules/ROOT/pages/references/index.adoc
> +:v_sdk: v3
Now removed 👍

2021-11-18 15:08 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +:v_sdk: v3
Also removed 👍

2021-11-18 16:11 UTC, ishantiw approved these changes

2021-11-19 13:40 UTC, Tschakki approved these changes
LGTM

2021-11-19 15:39 UTC, merged