Agnostic documentation editing tools - Closes #117
LiskArchive/lisk-legacy-docs pull request #129
Opened 2018-11-26 14:28 UTC by Tschakki

Closes #117

2018-11-29 10:03 UTC, lsilvs requested changes

2018-11-29 10:03 UTC, lsilvs commented on setup/binary/binary.md
>  ```
I would change the sentence above and remove these commands.

Something like:
```
Next, create a new file called `lisk` in the logrotate directory `/etc/logrotate.d` with the following content:
```

2018-11-29 10:03 UTC, lsilvs commented on setup/source/source.md
> +  5. [Node.js](#node-js)
This anchor is not working

2018-11-29 10:03 UTC, lsilvs commented on setup/source/source.md
>  ```
Same here.

2018-11-29 10:03 UTC, lsilvs commented on user-guide/administration/source/admin-source.md
> +Will remove Lisk Core process from pm2 list.
```suggestion
Remove Lisk Core process from pm2 list.
```

2018-11-29 10:03 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +cd lisk_repo/docker # navigate into docker directory
This is unnecessary imo

2018-11-29 10:03 UTC, lsilvs commented on user-guide/monitoring/monitoring.md
> +After adding the license key, save your changes and exit the file.
```suggestion
After adding the license key, save your changes and reload your node.
```

2018-11-30 08:49 UTC, nazarhussain requested changes

2018-11-30 08:49 UTC, nazarhussain commented on setup/source/source.md
> +  5. [Node.js](#node-js)
```suggestion
  5. [Node.js](#nodejs)
```

2018-11-30 08:49 UTC, nazarhussain commented on setup/binary/binary.md
>  ```
Although @lsilvs suggestion makes it completely agnostic, but I believe having such simple commands as `cd` and `touch` is not bad. These are kind of operating system commands, and every user must be aware of these. Also that's the easiest way to communicate such tasks to user. 

May be we add text description as well but keep the script there.

2018-11-30 08:49 UTC, nazarhussain commented on user-guide/administration/source/admin-source.md
>  pm2 show lisk
```suggestion
pm2 status lisk
```

2018-12-07 10:14 UTC, lsilvs approved these changes

2018-12-07 13:14 UTC, nazarhussain approved these changes

2018-12-07 13:26 UTC, merged