Improve Docker setup guide - Closes #1275
LiskArchive/lisk-legacy-docs pull request #1300
Opened 2021-11-22 14:48 UTC by Tschakki

Closes #1275

2021-11-25 11:54 UTC, sameersubudhi requested changes
Please check the following recommendations.

2021-11-25 11:54 UTC, sameersubudhi commented on modules/ROOT/pages/setup/docker.adoc
> +If this option is not set, it defaults to `127.0.0.1`.
Kindly consider adding this information as a `Note:`. Please feel free to adjust the document syntaxes.
```suggestion
Note: Allows remote servers to connect to the Lisk Core WS API. The `_host_` property defaults to `127.0.0.1`.
```

2021-11-25 11:54 UTC, sameersubudhi commented on modules/ROOT/pages/setup/docker.adoc
> +The `--network` flag defines which blockchain network Lisk Core will connect to.
```suggestion
The `--network` flag determines the blockchain network Lisk Core connects to.
```

2021-11-25 11:54 UTC, sameersubudhi commented on modules/ROOT/pages/setup/docker.adoc
> +====
The table alignment doesn't seem to be not centred. Please check: https://github.com/LiskHQ/lisk-docs/blob/06ea2857bd76f6fc3d6ad413c5b081e49a858926/modules/ROOT/pages/setup/docker.adoc#3-setting-up-lisk-service

2021-11-25 12:51 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +====
that is only an issue on GitHub, on the docs-UI it will be rendered centered :)

2021-11-25 12:54 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +If this option is not set, it defaults to `127.0.0.1`.
this is a code comment, indicated by the prepended `<1>`, which is also referenced in the code snippet. So I wouldn't make it a note here.

2021-11-25 17:10 UTC, sameersubudhi approved these changes, later dismissed
LGTM 👍

2021-11-26 12:31 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-11-26 12:31 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +To do this, create a custom configuration file, for example by copying one of the default config files:
```suggestion
To accomplish this, create a custom configuration file, for example by copying one of the default config files:
```

2021-11-26 12:31 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +The `--network` flag determines the blockchain network Lisk Core connects to.
```suggestion
The `--network` flag determines the blockchain network that will connect to Lisk Core.
```

2021-11-26 12:31 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +`--api-ws` enables the WebSocket API of the node, if not already enabled in the config.json.
```suggestion
`--api-ws` enables the WebSocket API of the node, if not already enabled in the config.json file.
```

2021-11-26 12:31 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +It is strongly recommended that you synchronize your Lisk Core node with the network **before** starting the Lisk Service.
```suggestion
It is strongly recommended to synchronize your Lisk Core node with the network **before** starting the Lisk Service.
```

2021-11-26 12:31 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +== Starting LIsk Service
```suggestion
== Starting Lisk Service
```

2021-11-26 16:58 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +The `--network` flag determines the blockchain network Lisk Core connects to.
I think this changes the meaning. It's more like the node connecting to the network, not the network connecting to the node.

2021-11-29 09:07 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +The `--network` flag determines the blockchain network Lisk Core connects to.
OK, I can see how it could be interpreted the wrong way here, Ok then let's leave it as it is Mona, although generally, it is not good to end a sentence with 'to'

2021-11-29 09:09 UTC, chris529 approved these changes
LGTM! 👍

2021-11-29 11:05 UTC, merged