Add public WebSocket APIs to index page - Closes #1277
LiskArchive/lisk-legacy-docs pull request #1301
Opened 2021-11-22 17:02 UTC by Tschakki

Closes #1277

2021-11-25 13:58 UTC, chris529 approved these changes, later dismissed
LGTM! 👍

2021-12-01 10:22 UTC, MichalTuleja requested changes
Looks good, with some minor remarks and typos.

2021-12-01 10:22 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
>  IMPORTANT: Specify version 2 of the socket.io client, as the current version 3 is not compatible with Lisk Service.
It's not important anymore, Lisk Service already migrated to socket.io version 4.

2021-12-01 10:22 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
>  IMPORTANT: Specify version 2 of the socket.io client, as the current version 3 is not compatible with Lisk Service.
Same as above

2021-12-01 10:22 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> +:url_subscribe_api_testnet: wss://testnet-service.lisk.com/blocckhain
```suggestion
:url_subscribe_api_testnet: wss://testnet-service.lisk.com/blockchain
```

2021-12-01 10:22 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
>  	});
`Received data from ${WS_SUBSCRIBE_ENDPOINT}/${eventName}: ${newData}`

2021-12-02 10:45 UTC, MichalTuleja approved these changes
👍

2021-12-02 11:23 UTC, merged