Update guides and config reference - Closes #1278
LiskArchive/lisk-legacy-docs pull request #1305
Opened 2021-11-25 16:43 UTC by Tschakki

Closes #1278

2021-11-29 13:41 UTC, sameersubudhi requested changes
Please find the following observations.

2021-11-29 13:41 UTC, sameersubudhi commented on modules/ROOT/pages/configuration/source.adoc
> +The ecosystem file^]
Did you intend to remove this line?

2021-11-29 13:41 UTC, sameersubudhi commented on modules/ROOT/pages/configuration/source.adoc
> +The default confoguration file is `ecosystem.core3.config.js`, located in the root folder of `lisk-service`:
```suggestion
The default configuration file is `ecosystem.core3.config.js`, located in the root directory of `lisk-service`:
```

2021-11-29 13:41 UTC, sameersubudhi commented on modules/ROOT/pages/configuration/source.adoc
> +# pm2 start ecosystem.core3.config.js
Kindly consider updating it to the following as we do not have a default `ecosystem.config.js` file.
```suggestion
pm2 start ecosystem.core3.config.js
```

2021-11-29 13:41 UTC, sameersubudhi commented on modules/ROOT/pages/management/source.adoc
> +----
Kindly update
```suggestion
To check the logs for the different microservices of Lisk Service, use the command `pm2 logs PROCESS_NAME`, where `PROCESS_NAME` is the respective PM2 managed process you want to see the logs of.

For example, to see the logs for the Gateway microservice, execute:

[source,bash]
----
pm2 logs lisk-service-gateway
----
```

2021-11-29 13:41 UTC, sameersubudhi commented on modules/ROOT/pages/references/configuration.adoc
> +SERVICE_LOG_LEVEL=info    # Default log level. TRACE < DEBUG < INFO < WARN < ERROR < FATAL < MARK
`FATAL` is the logging level with the highest severity.

```suggestion
SERVICE_LOG_LEVEL=info    # Default log level. TRACE < DEBUG < INFO < WARN < ERROR < FATAL
```

2021-11-29 16:34 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +The ecosystem file^]
Yes you are right! Removed now :)

2021-11-29 17:46 UTC, sameersubudhi submitted a review, later dismissed
Thank you for the changes! LGTM 👍

2021-11-30 08:53 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
```suggestion
The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
```

2021-11-30 09:03 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
Can't really spot it - what is the difference here?

2021-11-30 10:18 UTC, chris529 reviewed
Looks good, just a few minor point 👍

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
Hey Mona, I think the latter part of this statement should read as "the **log** files of Lisk Service with PM2" Thoughts...?

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +The default configuration file is `ecosystem.core3.config.js`, located in the root folder of `lisk-service`:
```suggestion
The default configuration file is `ecosystem.core3.config.js`, and is located in the root folder of `lisk-service`:
```

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +To check the logs for the different microservices of Lisk Service, use the command `docker container logs CONTAINER`, where `CONTAINER` is the respective Docker container you want to see the logs of.
```suggestion
To check the logs for the different microservices of Lisk Service, use the command `docker container logs CONTAINER`, where `CONTAINER` is the respective Docker container that holds the logs you wish to view.
```

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/management/source.adoc
> +To check the logs for the different microservices of Lisk Service, use the command `pm2 logs PROCESS_NAME`, where `PROCESS_NAME` is the respective PM2 managed process you want to see the logs of.
```suggestion
To check the logs for the different microservices of Lisk Service, use the command `pm2 logs PROCESS_NAME`, where `PROCESS_NAME` is the respective PM2 managed process that contains the logs you wish to view.
```

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +# Number of connections per second can be set using
```suggestion
# Number of connections per second can be set using the
```

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +# variable. currently defaults to `5 connections per second`
```suggestion
# variable. It currently defaults to `5 connections per second`
```

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +# The `HTTP Rate limit` directives can be set using `HTTP_RATE_LIMIT_WINDOW` and `HTTP_RATE_LIMIT_CONNECTIONS` environment
```suggestion
# The `HTTP Rate limit` directives can be set using the `HTTP_RATE_LIMIT_WINDOW` and the `HTTP_RATE_LIMIT_CONNECTIONS` environment
```

2021-11-30 10:18 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +HTTP_RATE_LIMIT_WINDOW=10 # To keep record of requests in memory (in seconds). Defaults to 10 seconds
```suggestion
HTTP_RATE_LIMIT_WINDOW=10 # To keep a record of requests in the memory (in seconds). Defaults to 10 seconds
```

2021-11-30 11:09 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
Sorry, I should have written the entire sentence..here it is:
The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the log files of Lisk Service with PM2.             (Not logs files)

2021-11-30 12:13 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
ah, I see, yes you are right :)

2021-11-30 12:47 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the logs files of Lisk Service with PM2.
```suggestion
The {url_pm2_ecosystem_file}[PM2 ecosystem file^] provides the possibility to configure behavior, options, environment variables, and the log files of Lisk Service with PM2.
```

2021-11-30 13:49 UTC, chris529 approved these changes
LGTM! 👍

2021-11-30 15:32 UTC, merged