Update on glossary and abbreviations in SDK docs - Closes #1284
LiskArchive/lisk-legacy-docs pull request #1306
Opened 2021-11-26 09:33 UTC by chris529

Closes #1284

2021-11-29 09:06 UTC, Tschakki requested changes

2021-11-29 09:06 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +=== Self Vote
Did we discuss to add this to the glossary?

2021-11-29 09:06 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +=== Reclaim LSK
Imho it should be `Reclaim LSK transaction` not just `Reclaim LSK`, same for the other transaction types

2021-11-29 09:11 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +=== Self Vote
Shu requested that we add it, in the latest issue #1284

2021-11-29 09:22 UTC, Tschakki commented on modules/ROOT/pages/glossary.adoc
> +=== Self Vote
Ah, ok then!

2021-11-29 11:10 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +=== Reclaim LSK
Good point, OK I have now updated it to Reclaim LSK transaction 👍

2021-11-29 15:16 UTC, shuse2 requested changes

2021-11-29 15:16 UTC, shuse2 commented on modules/ROOT/pages/glossary.adoc
> +Non-initialized accounts don’t have a public key associated with them yet.
here, probably better to emphasise initialization was only required for v2 chain

2021-11-29 15:16 UTC, shuse2 commented on modules/ROOT/pages/glossary.adoc
> +A self vote is a vote that a delegate account casts for themselves. Self votes are always at least 10% of the delegate weight.
```suggestion
A self vote is a vote that a delegate casts for themselves. Self votes are always at least 10% of the delegate weight.
```

2021-11-29 15:16 UTC, shuse2 commented on modules/ROOT/pages/glossary.adoc
> +The self-votes are always at least 10% of the delegate weight, in order to ensure each delegate is able maintain an adequate amount of votes.
Maybe add explanation for below.

Because delegate weight will be capped by self-vote, total votes received might not be equal to the delegate weight

2021-11-29 15:16 UTC, shuse2 commented on modules/ROOT/pages/glossary.adoc
> +=== Unlock token
some transaction has transaction at the end. ex: `Reclaim LSK transaction`. it would be nice to make it consistent

2021-11-30 14:05 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +Non-initialized accounts don’t have a public key associated with them yet.
I have expanded on this in the description...Let me know your thoughts Shu 👍

2021-11-30 14:22 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +The self-votes are always at least 10% of the delegate weight, in order to ensure each delegate is able maintain an adequate amount of votes.
Also expanded on this.. 👍

2021-11-30 14:44 UTC, chris529 commented on modules/ROOT/pages/glossary.adoc
> +=== Unlock token
Yes, good point.. OK, I have updated them 👍

2021-12-01 09:30 UTC, Tschakki approved these changes
Thanks, LGTM!

2022-01-12 08:48 UTC, shuse2 approved these changes

2022-01-12 09:26 UTC, merged