Fixes broken links in Lisk Service v0.5.0 - Closes #1302
LiskArchive/lisk-legacy-docs pull request #1310
Opened 2021-12-01 15:30 UTC by chris529

2021-12-02 09:45 UTC, Tschakki requested changes

2021-12-02 09:45 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_api_testnet: https://testnet-service.lisk.com
No need to remove the `/api/` part, this is standard path for HTTP API

2021-12-02 09:45 UTC, Tschakki commented on modules/ROOT/pages/references/subscribe-api.adoc
> +The blockchain update API can be accessed by the following path wss://service.lisk.io/blockchain.
```suggestion
The blockchain update API can be accessed by the following path wss://service.lisk.com/blockchain.
```

I think we updated everything to `lisk.com`, don't use `.io` anymore.

2021-12-02 09:45 UTC, Tschakki commented on modules/ROOT/pages/references/subscribe-api.adoc
> +If you are interested in accessing the testnet network, this can be accomplished by using the wss://testnet-service.lisk.io/blockchain endpoint.
```suggestion
If you are interested in accessing the testnet network, this can be accomplished by using the wss://testnet-service.lisk.com/blockchain endpoint.
```

2021-12-02 09:45 UTC, Tschakki commented on modules/ROOT/pages/references/subscribe-api.adoc
> +const connection = io.connect('wss://service.lisk.io/blockchain', { transports: ['websocket'] });
```suggestion
const connection = io.connect('wss://service.lisk.com/blockchain', { transports: ['websocket'] });
```

2021-12-02 10:49 UTC, chris529 commented on modules/ROOT/pages/references/subscribe-api.adoc
> +The blockchain update API can be accessed by the following path wss://service.lisk.io/blockchain.
Ok, Cool 👍

2021-12-02 10:53 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> +:url_api_testnet: https://testnet-service.lisk.com
Both look equally fine. Devs know they need to prefix it with the right API version.

2021-12-02 10:53 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> +:url_api_testnet: https://testnet-service.lisk.com
Both look equally fine. Devs know they need to prefix it with the right API version.

2021-12-02 10:56 UTC, MichalTuleja commented on modules/ROOT/pages/index.adoc
> -* API specification: xref:{url_api_http_testnet}[Lisk Service HTTP API reference (Testnet)]
Is the testnet URL completely removed or moved to other sections?

2021-12-02 10:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:url_api_testnet: https://testnet-service.lisk.com
OK, done 👍

2021-12-02 11:05 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> -* API specification: xref:{url_api_http_testnet}[Lisk Service HTTP API reference (Testnet)]
There is a page in the Reference section which links to the Testnet, which I think we should also update to Lisk.com?
Actually, it appears we still have a page in the Reference section which links to the Betanet there as well, shouldn't this page be removed?

2021-12-02 11:09 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> -* API specification: xref:{url_api_http_testnet}[Lisk Service HTTP API reference (Testnet)]
Why is the testnet section removed here?

2021-12-02 11:15 UTC, Tschakki requested changes

2021-12-02 11:15 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> -* API specification: xref:{url_api_http_testnet}[Lisk Service HTTP API reference (Testnet)]
Why is the testnet section removed here?

2021-12-02 11:17 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> -* API specification: xref:{url_api_http_testnet}[Lisk Service HTTP API reference (Testnet)]
You are right Mona, It has now been reinstated 👍

2021-12-02 11:30 UTC, Tschakki requested changes

2021-12-02 11:30 UTC, Tschakki commented on modules/ROOT/pages/references/subscribe-api.adoc
> +The blockchain update API can be accessed by the following path wss://service.lisk.com/blockchain.
```suggestion
The blockchain update API can be accessed by the following path `wss://service.lisk.com/blockchain`.
```

To mitigate that broken links are identified, please display the URLs in monospace here.

2021-12-02 11:30 UTC, Tschakki commented on modules/ROOT/pages/references/subscribe-api.adoc
> +If you are interested in accessing the testnet network, this can be accomplished by using the wss://testnet-service.lisk.com/blockchain endpoint.
```suggestion
If you are interested in accessing the testnet network, this can be accomplished by using the `wss://testnet-service.lisk.com/blockchain` endpoint.
```

2021-12-02 11:42 UTC, chris529 commented on modules/ROOT/pages/references/subscribe-api.adoc
> +The blockchain update API can be accessed by the following path wss://service.lisk.com/blockchain.
Good point Mona! Thanks 👍

2021-12-03 09:30 UTC, Tschakki requested changes
Hey, I just looked again at the list of broken links at ohdear, and I think you missed the links on the index page, please check again.

2021-12-03 11:39 UTC, Tschakki approved these changes
Thanks!

2021-12-03 11:40 UTC, Tschakki commented
@chris529 I didn't check, there is a conflict in your PR, please resolve it

2021-12-03 11:50 UTC, Tschakki requested changes

2021-12-03 11:50 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> -:url_subscribe_api_testnet: wss://testnet-service.lisk.com/blockchain
This shouldn't be removed

2021-12-03 11:56 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> -:url_subscribe_api_testnet: wss://testnet-service.lisk.com/blockchain
oops...yes that was an error..thanks, it has now been replaced 👍

2021-12-03 15:06 UTC, Tschakki approved these changes
LGTM

2021-12-10 10:27 UTC, MichalTuleja approved these changes

2021-12-10 14:23 UTC, merged