Add sections how to reset the mysql db - Closes #1270
LiskArchive/lisk-legacy-docs pull request #1311
Opened 2021-12-01 16:58 UTC by Tschakki

Closes #1270

2021-12-02 11:03 UTC, sameersubudhi requested changes
Kindly consider the following.

Also, please add the steps to reset the Redis instances as well. Redis and MySQL go hand-in-hand.

Step to reset all the DB in Redis: `redis-cli flushall;`
To clear a particular DB in Redis: `redis-cli -n <db_number> flushdb`

It is important to highlight for `FLUSHALL` (source: https://redis.io/commands/FLUSHALL):
> Delete all the keys of all the existing databases, not just the currently selected one. This command never fails.

2021-12-02 11:03 UTC, sameersubudhi commented on modules/ROOT/pages/management/docker.adoc
> +NOTE: When Lisk Service is stsrted again after a database reset, it takes a long time to reindex all the data. This might take up to 1 or 2 hours.
```suggestion
NOTE: When Lisk Service is started again after a database reset, it takes a long time to reindex all the data. Currently, this might take up to 2 hours.
```

2021-12-02 11:03 UTC, sameersubudhi commented on modules/ROOT/pages/management/source.adoc
> +NOTE: When Lisk Service is stsrted again after a database reset, it takes a long time to reindex all the data. This might take up to 1 or 2 hours.
```suggestion
NOTE: When Lisk Service is started again after a database reset, it takes a long time to reindex all the data. Currently, this might take up to 2 hours.
```

2021-12-03 09:17 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +Now connect to the Docker container in which you wish to reset the database. If you are not sure what to pick here, check the available containers via <<show-status-of-docker-containers>>.
```suggestion
Now connect to the Docker container in which you wish to reset the database. If you are not sure what to choose here, check the available containers via <<show-status-of-docker-containers>>.
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +The `flushall` command removes all existing redis databases:
```suggestion
The `flushall` command removes all existing Redis databases:
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +To flush only a particular DB in Redis, run instead:
```suggestion
To flush only a particular DB in Redis, execute the following command instead:
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +NOTE: When Lisk Service is started again after a database reset, it takes a long time to reindex all the data. Currently, this might take up to 2 hours.
```suggestion
NOTE: When Lisk Service is started again after a database reset, then the process to reindex all the data is initiated. This can be quite time-consuming and may take up to 2 hours.
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/source.adoc
> +NOTE: When Lisk Service is started again after a database reset, it takes a long time to reindex all the data. Currently, this might take up to 2 hours.
```suggestion
NOTE: When Lisk Service is started again after a database reset, then the process to reindex all the data is initiated. This can be quite time-consuming and may take up to 2 hours.
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/source.adoc
> +The `flushall` command removes all existing redis databases:
```suggestion
The `flushall` command removes all existing Redis databases:
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +> Deletes all the keys of all the existing databases, not just the currently selected one. This command never fails.
```suggestion
> Deletes all the keys of all the existing databases, not just the current selected one. This command never fails.
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/source.adoc
> +> Deletes all the keys of all the existing databases, not just the currently selected one. This command never fails.
```suggestion
> Deletes all the keys of all the existing databases, not just the current selected one. This command never fails.
```

2021-12-03 09:17 UTC, chris529 commented on modules/ROOT/pages/management/source.adoc
> +To flush only a particular DB in Redis, run instead:
```suggestion
To flush only a particular DB in Redis, execute the following command instead:
```

2021-12-03 09:52 UTC, sameersubudhi submitted a review, later dismissed
Thank you for the changes. LGTM 👍

2021-12-06 08:33 UTC, chris529 approved these changes
LGTM! 👍

2021-12-06 08:49 UTC, merged