RPC config updates - Closes #1287
LiskArchive/lisk-legacy-docs pull request #1317
Opened 2021-12-13 13:43 UTC by Tschakki

Closes #1287

2021-12-14 13:59 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-12-14 13:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +The currently used configuration of a blockchain application is stored under the following path, after the applications was started for the first time:
```suggestion
The currently used configuration of a blockchain application is stored under the following path after the applications were started for the first time:
```

2021-12-14 13:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +The best way to create a custom configuration for your app is to copy an existing `config.json` and adjust it to your needs.
```suggestion
The optimal method to create a custom configuration for your app is to copy an existing `config.json` and adjust it to suit your requirements.
```

2021-12-14 13:59 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +See for reference the guide xref:{url_guides_non_forging_pretection}[]
```suggestion
For reference see the guide xref:{url_guides_non_forging_protection}[]
```

2021-12-17 09:05 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +The currently used configuration of a blockchain application is stored under the following path, after the applications was started for the first time:
```suggestion
The currently used configuration of a blockchain application is stored under the following path after the application was started for the first time:
```

2021-12-17 09:06 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +:url_guides_non_forging_pretection: guides/node-management/non-forging-node-protection.adoc
```suggestion
:url_guides_non_forging_protection: guides/node-management/non-forging-node-protection.adoc
```

2021-12-20 10:10 UTC, Incede requested changes

2021-12-20 10:10 UTC, Incede commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +The currently used configuration of a blockchain application is stored under the following path after the application was started for the first time:
```suggestion
The current configuration of a blockchain application is stored under the following path after the application is started for the first time:
```

2021-12-20 10:10 UTC, Incede commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +----
> copy an existing `config.json` and adjust it to suit your requirements.
Since you're giving the example to copy maybe also give an example to "adjust it" to complete the narrative

2021-12-20 10:10 UTC, Incede commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +Restart the app to apply the new configuration.
Looking at the flow, I think this come before the section "Config file location"

2021-12-20 10:10 UTC, Incede commented on modules/ROOT/pages/guides/app-development/configuration.adoc
>          "mode": "ws", //"ws" or "ipc"
A short explainer b/w `ws` & `ipc`(when to use which) would be helpful here or is it already mentioned somewhere else ?

2021-12-20 12:02 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +----
I rearranged the sections accordingly.

2021-12-20 12:02 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +Restart the app to apply the new configuration.
I rearranged the sections accordingly.

2021-12-20 12:36 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/configuration.adoc
>          "mode": "ws", //"ws" or "ipc"
Added the explanation to the communications page as discussed

2021-12-20 13:48 UTC, Incede approved these changes, later dismissed

2021-12-20 13:48 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +There are two different protocols each node can choose to enable the API:
```suggestion
There are two ways through which a node can communicate via the API:
```

2021-12-20 14:01 UTC, merged