How to calculate the min fee of a tx - Closes #1255
LiskArchive/lisk-legacy-docs pull request #1318
Opened 2021-12-14 11:53 UTC by Tschakki

Closes #1255

2021-12-16 09:52 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +The minimum fee allowed is calculated the following way for every transaction:
```suggestion
For every transaction it is possible to calculate the minimum fee required by using the short formula listed below:
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +It is directly connected to the size of the transaction object in bytes, after it has been encoded, and to the optional `baseFee` of a transaction.
```suggestion
It is directly connected to the size of the transaction object in bytes after it has been encoded, and also to the optional `baseFee` of a transaction.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +Luckily, the `apiClient` is capable of doing all necessary steps of the calculation:
```suggestion
Fortunately, the `apiClient` is capable of performing all the necessary steps of the calculation:
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +All required to calculate the fee of a transaction is the transaction itself, which is passed as parameter to the `computeMinFee()` function of the API client.
```suggestion
All that is required to calculate the fee of a transaction is the transaction itself, which is passed as a parameter to the `computeMinFee()` function of the API client.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +A new transaction can be created with the API client in a convenient way, assuming that the respective transaction asset type known to the respective blockchain application.
```suggestion
A new transaction can be created with the API client in a convenient manner, assuming that the respective transaction asset type is known to the respective blockchain application.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +Generally, a blockchain application knows only about the assets that are part modules registered to the application.
```suggestion
Generally, a blockchain application is only aware of the assets that are part modules registered to the application.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +In this example, we connect to the xref:{url_hello_world}[Hello World blockchain application], so we can use the Hello transaction asset in this example.
```suggestion
In this example, connect to the xref:{url_hello_world}[Hello World blockchain application], so we can use the Hello transaction asset.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +Therefore, just use some arbitrary default value.
```suggestion
Therefore, just use an arbitrary default value.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +In this example, we use 1 LSK.
```suggestion
In this example below, we have used 1 LSK.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +In the next function, the minimum fee is directly used as fee for the transaction that is sent to the node.
```suggestion
In the next function, the minimum fee is directly used as the fee for the transaction that is sent to the node.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +As last step, all above defined functions are called and the calculated minimum fee and the node API response are logged in the terminal.
```suggestion
For the final step, all the above defined functions are called and the calculated minimum fee and the node API response are logged in the terminal.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +Also, it will directly try to send the transaction with the minimum fee.
```suggestion
In addition, it will directly try to send the transaction with the minimum fee.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +If the transaction was accepted by the node, the respective trasnaction ID will be returned in the terminal.
```suggestion
If the transaction was accepted by the node, the respective transaction ID will be returned in the terminal.
```

2021-12-16 09:52 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +Then, when executing the script again, you should see the following error in the terminal
```suggestion
Then when executing the script again, you should see the following error in the terminal:
```

2021-12-16 10:44 UTC, chris529 submitted a review, later dismissed
LGTM! 👍

2021-12-17 13:30 UTC, Incede requested changes

2021-12-17 13:30 UTC, Incede commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +Generally, a blockchain application is only aware of the assets that are part modules registered to the application.
```suggestion
Generally, a blockchain application is only aware of the assets that are part of modules registered to the application.
```

2021-12-17 13:30 UTC, Incede commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +The Hello asset is part of the Hello module which is registered in the 'Hello World' application.
```suggestion
The Hello asset is part of the Hello module which is registered to the 'Hello World' application.
```

2021-12-17 13:30 UTC, Incede commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +A value for the transaction fee is already required to create and sign a transaction.
```suggestion
A value for the transaction fee is already required to create and sign the transaction.
```

2021-12-17 13:30 UTC, Incede commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +This value will be overwritten with the calculated minimum fee for the transaction in the next step.
I think we should avoid the word `overwritten`. That's not an accurate way of describing what's happening.

2021-12-17 13:30 UTC, Incede commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +In addition, it will directly try to send the transaction with the minimum fee.
```suggestion
In addition, it will try to send the transaction with the minimum fee.
```

2021-12-17 13:30 UTC, Incede commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +If the transaction was accepted by the node, the respective transaction ID will be returned in the terminal.
```suggestion
If the transaction was accepted by the node, the respective transaction ID will be logged in the terminal.
```

2021-12-17 13:55 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/min-fee.adoc
> +This value will be overwritten with the calculated minimum fee for the transaction in the next step.
```suggestion
This value will be replaced with the calculated minimum fee for the transaction in the next step.
```

2021-12-17 14:09 UTC, Incede approved these changes

2021-12-17 14:17 UTC, chris529 approved these changes
LGTM! 👍

2021-12-17 14:54 UTC, merged