Add RPC example outputs - Closes #870
LiskArchive/lisk-legacy-docs pull request #1322
Opened 2021-12-28 14:19 UTC by Tschakki

Closes #870

2021-12-29 14:26 UTC, Incede requested changes

2021-12-29 14:26 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +]
Question: Would you prefer the output format like for `app:chain:validators:change` or as it is now ?

something like 
```
{ peers: [ { }, { } .... { } ] }
```

And maybe add an example output with multiple peers.

2021-12-29 14:26 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[
same, multiple peer output example if possible

2021-12-29 14:26 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
What is this address in the example conveying here ?

2021-12-29 14:26 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[source,js]
Are you adding source for only selected examples ?

2021-12-29 14:26 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +  "0a14d6a79b4f59f7da027405277b55783ba7dd255aa912070880d6d2c881031a020800220208002a190a170a0c64656c65676174655f313031180120ac1628003000c23e0e0a0c48656c6c6f20576f726c6421",
It does not say here if it Is input or output

2021-12-29 15:18 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[source,js]
Can you explain more? I am not sure I understand what you mean

2021-12-29 15:23 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +]
I don't have a strong opinion here, either is fine for me I guess.

About multiple outputs: It is a little cumbersome to generate these, and I don't think it is adding new information, so I would prefer to keep it as is.

2021-12-29 15:23 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[
See my reply above

2021-12-29 15:25 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
This is the data that is returned when disabling forging via RPC action (see label of the snippet)

2021-12-29 15:26 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +  "0a14d6a79b4f59f7da027405277b55783ba7dd255aa912070880d6d2c881031a020800220208002a190a170a0c64656c65676174655f313031180120ac1628003000c23e0e0a0c48656c6c6f20576f726c6421",
Yes it does, in the label above the snippet.

2021-12-29 16:16 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +  "0a14d6a79b4f59f7da027405277b55783ba7dd255aa912070880d6d2c881031a020800220208002a190a170a0c64656c65676174655f313031180120ac1628003000c23e0e0a0c48656c6c6f20576f726c6421",
ah yes! It was truncated in Github in default view

2021-12-29 16:19 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
hmm yea ik but I am trying to understand what does it mean... How is it related to `updateForgingStatus` ?

2021-12-29 16:24 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[source,js]
I saw in some places the source code for some examples was removed (L169, L235) or not present in others.

2021-12-30 11:35 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
it is an example of what it returns

2021-12-30 11:38 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[source,js]
I wanted to include one example of decoding an account, which I think is missing in the docs atm.
Probably there should be a guide covering this, but for now I added a simple example here.

The other two examples were kind of old and covered elsewhere in the docs, so I removed the examples for them.

2021-12-30 12:50 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[source,js]
I'd suggest using a consistent approach for providing source code with examples (either do for all or none) but in the end it's up to you.

2021-12-30 12:52 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
hmm idk if it's the right behavior but returning only an address as the output of `app:updateForgingStatus` doesn't make sense for me.

2021-12-30 14:03 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
Maybe you can verify it yourself, for me this was exactly what was returned when disabling forging.
If you don't like what it returns, I suggest to create a new issue for it on the lisk-sdk repo.
I agree personally, more info, and maybe a general more standardized format for RPC replies would be great.
Also for `app:ready` and `app:shutdown` it only returned `{}` / undefined when the event was fired.

2021-12-30 14:04 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +[source,js]
For now it is OK like this, but if I create the guide, I will consider remove it here for consistency 👍

2021-12-30 17:48 UTC, Incede commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
Thanks for the feedback. Created an [issue](https://github.com/LiskHQ/lisk-sdk/issues/6967). Would be nice if you could also specify details what you expect in terms of "more information and standardized format" in the issue itself.

2021-12-30 17:53 UTC, Incede approved these changes

2021-12-31 11:30 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/rpc-endpoints.adoc
> +}
Thanks!

2021-12-31 11:35 UTC, merged