Fixes minor errors/updates in Core docs v3.0.2 - Closes #1334
LiskArchive/lisk-legacy-docs pull request #1335
Opened 2022-01-12 16:01 UTC by chris529

Closes #1334

2022-01-14 09:23 UTC, Tschakki requested changes
Looking good, thanks! Just two small remarks :)

2022-01-14 09:23 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +  $ lisk-core account:create.
These dots don't belong here, it is a command example.

Please remove. Same in the command examples below

2022-01-14 09:23 UTC, Tschakki commented on modules/ROOT/pages/management/enabling-misbehavior-report.adoc
> +Start Lisk Core with the flag `--enable-report-misbehavior-plugin`
Why remove the colon?

2022-01-14 11:03 UTC, chris529 commented on modules/ROOT/pages/management/account-management.adoc
> +  $ lisk-core account:create.
Good point...I have now removed them, as well as other instances in the command examples on this page, so they are now back to their original state 👍

2022-01-14 11:07 UTC, chris529 commented on modules/ROOT/pages/management/enabling-misbehavior-report.adoc
> +Start Lisk Core with the flag `--enable-report-misbehavior-plugin`
Thanks, that was an error...It's now corrected 👍

2022-01-14 11:31 UTC, Tschakki requested changes

2022-01-14 11:31 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +  account:create.
```suggestion
  account:create
```

2022-01-14 11:31 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +  transaction:send.
```suggestion
  transaction:send
```

2022-01-14 15:33 UTC, ishantiw approved these changes
Just a minor comment, LGTM

2022-01-14 15:33 UTC, ishantiw commented on modules/ROOT/pages/management/forging.adoc
> +These  three variables are required for enabling forging for the corresponding delegate.
```suggestion
These three variables are required for enabling forging for the corresponding delegate.
```

2022-01-17 16:39 UTC, Tschakki approved these changes
LGTM!

2022-01-18 12:32 UTC, merged