Update Source Upgrade section, Closes #133
LiskArchive/lisk-legacy-docs pull request #134
Opened 2018-12-07 09:59 UTC by Tschakki

Closes #133

2018-12-07 13:44 UTC, diego-G requested changes
Check comments

2018-12-07 13:44 UTC, diego-G commented on upgrade/source/upgrade-source.md
> +    pm2 start lisk
Is this really working?

2018-12-07 13:44 UTC, diego-G commented on upgrade/source/upgrade-source.md
> +    git checkout v1.1.0 -b v1.1.0 # check out latest release tag
Change it to `git checkout vM.m.b-b vM.m.b `

2018-12-07 13:48 UTC, Tschakki commented on upgrade/source/upgrade-source.md
> +    git checkout v1.1.0 -b v1.1.0 # check out latest release tag
I am not so sure if this will be less confusing tbh 😄

2018-12-07 13:54 UTC, Tschakki commented on upgrade/source/upgrade-source.md
> +    git checkout v1.1.0 -b v1.1.0 # check out latest release tag
what about `git checkout v1.x.x -b v1.x.x # check out latest release tag` ?

2018-12-07 13:59 UTC, diego-G commented on upgrade/source/upgrade-source.md
> +    git checkout v1.1.0 -b v1.1.0 # check out latest release tag
I was thinking about that at first sight but it is better to follow standard semver notation to avoid changes in the future. Check this https://semver.org/

2018-12-07 15:15 UTC, Tschakki commented on upgrade/source/upgrade-source.md
> +    pm2 start lisk
Sure.

We expect that the user has followed the installation instructions for Source ofc.

2018-12-11 11:15 UTC, diego-G approved these changes

2018-12-11 11:22 UTC, merged