Update next & previous link styles - Closes #1357
LiskArchive/lisk-legacy-docs pull request #1384
Opened 2022-02-08 16:20 UTC by Tschakki

Closes #1357

2022-02-08 20:28 UTC, shuse2 requested changes
I think there should be 30px between boarder and the next/prev

2022-02-08 20:28 UTC, shuse2 commented on ui/src/css/extensions/common-custom.css
> +  font-weight: 400;
font-size should be 16px

2022-02-08 20:28 UTC, shuse2 commented on ui/src/css/extensions/common-custom.css
> +  content: "";
this is not taking effect?

2022-02-09 08:39 UTC, Tschakki commented on ui/src/css/extensions/common-custom.css
> +  content: "";
for me it does 🤔

2022-02-09 08:43 UTC, shuse2 commented on ui/src/css/extensions/common-custom.css
> +  content: "";
![Screenshot 2022-02-09 at 09 42 44](https://user-images.githubusercontent.com/2367565/153158149-058d6ca2-0304-4b41-bbe2-55e46ee2a232.png)

This one?

2022-02-09 09:20 UTC, Tschakki commented on ui/src/css/extensions/common-custom.css
> +  content: "";
I discussed with Anna to keep the default design of the links with some small adjustments, the `content: ""` removes the old chevron icon and replaces it with ours, not affecting the texts `Next` or `Prev`.

2022-02-09 09:30 UTC, shuse2 approved these changes

2022-02-09 09:34 UTC, merged