Overall review of SDK docs v5 - Closes #1035
LiskArchive/lisk-legacy-docs pull request #1395
Opened 2022-02-11 16:37 UTC by chris529

2022-02-15 15:56 UTC, Tschakki requested changes
Thank you, looking very good!

Just a few remarks :)

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +For each action and event displayed below in green, the following statements apply:
There are no actions and events listed in green below, it is more about what are the interfaces for events and actions in the different components.

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +<2> `string` is defined as a data type for the `helloString`.
we are referring to a particular variable here, no `the` needed

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +NOTE: It can happen that the same event is received multiple times, as shown in the example below where the `hello:newHello`.
Sentence seems incomplete

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +For this example, we reduce the value of the `count` to  4000, with a default distance of `1000` this will only produce 5 hashes in the hash onion.
As we are referring to a variable, there shouldn't be `the` before the name of it.
```suggestion
For this example, we reduce the value of `count` to  4000, with a default distance of `1000` this will only produce 5 hashes in the hash onion.
```

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Generally though, it is recommended to use high values for the `count`, so the delegate has enough hashes to forge for a long time.
same here
```suggestion
Generally though, it is recommended to use high values for `count`, so the delegate has enough hashes to forge for a long time.
```

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +The generate genesis block object.
```suggestion
The generated genesis block object.
```

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +Please note that both inbound and outbound peers can be used for 2-way communication. However, a node chooses only outbound connections to make a request, and prioritizes outbound peers for sending i
```suggestion
Please note that both inbound and outbound peers can be used for 2-way communication.
However, a node chooses only outbound connections to make a request, and prioritizes outbound peers for sending information.
```

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +Listen to various events on the network to observe the network activities more closely and takes the appropriate action if necessary.
```suggestion
Allows to listen to various events on the network, to observe the network activities more closely and take the appropriate actions, if necessary.
```

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/keys-module.adoc
> +The keys module adds the new property `mandatoryKeys`,`optionalKeys`, and the `numberOfSignatures` under the key `keys` to every account in the network as follows:
```suggestion
The keys module adds the new properties `mandatoryKeys`,`optionalKeys`, and `numberOfSignatures` under the key `keys` to every account in the network as follows:
```

2022-02-15 15:56 UTC, Tschakki commented on modules/ROOT/pages/tutorials/lns/4-tests.adoc
> +In the final chapter of this tutorial, how to test the application with both unit and network tests is covered in detail here.
```suggestion
In the final chapter of this tutorial, it is covered how to test the application with both unit and network tests.
```

2022-02-15 15:56 UTC, Tschakki commented on modules/protocol/pages/accounts.adoc
> +These public keys can be either [#index-mandatory-1]#mandatory# or [#index-optional-1]#optional#. All mandatory keys have to sign the transaction, and the total number of signatures (mandatory plus o
```suggestion
These public keys can be either [#index-mandatory-1]#mandatory# or [#index-optional-1]#optional#. All mandatory keys have to sign the transaction, and the total number of signatures (mandatory plus optional), has to be equal to `numberOfSignatures` (also stored in `keys`).
```

2022-02-16 09:44 UTC, chris529 commented on modules/ROOT/pages/advanced-explanations/communication.adoc
> +For each action and event displayed below in green, the following statements apply:
Ah yes, good point Mona... I have removed the reference to 'green' regarding the actions and events 👍

2022-02-16 09:51 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/asset.adoc
> +<2> `string` is defined as a data type for the `helloString`.
Good point, it has now been removed 👍

2022-02-16 09:56 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/dashboard.adoc
> +NOTE: It can happen that the same event is received multiple times, as shown in the example below where the `hello:newHello`.
Good catch Mona, this was an error 👍

2022-02-17 17:16 UTC, Tschakki approved these changes
Looking great, thank you! 👍

2022-02-18 12:24 UTC, merged