Add notes about updating param in guides - Closes #1399
LiskArchive/lisk-legacy-docs pull request #1400
Opened 2022-02-15 15:15 UTC by Tschakki

Closes #1399

2022-02-16 09:16 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2022-02-16 09:16 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Otherwise, you will run in the following error, when trying to start the application:
```suggestion
Otherwise, you will run into the following error, when trying to start the application:
```

2022-02-16 09:16 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> + reference errotr : app is not defined
```suggestion
 reference error : app is not defined
```

2022-02-16 09:16 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +Otherwise, you will run in the following error, when trying to start the application:
```suggestion
Otherwise, you will run into the following error, when trying to start the application:
```

2022-02-16 09:16 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> + reference errotr : app is not defined
```suggestion
 reference error : app is not defined
```

2022-02-16 09:45 UTC, chris529 submitted a review, later dismissed
LGTM! 👍

2022-03-04 10:43 UTC, mehmetegemen requested changes

2022-03-04 10:43 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +                type: 'boolean'
Do you think it's necessary to remove comma here? In my opinion it's not JSON but a Javascript code, so a comma is valid and omitting it might be a trouble in git history when we want to add a line below it.

2022-03-04 10:43 UTC, mehmetegemen commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +            enable: true
Do you think it's necessary to remove comma here? In my opinion it's not JSON but a Javascript code, so a comma is valid and omitting it might be a trouble in git history when we want to add a line below it.

2022-03-04 11:36 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +                type: 'boolean'
Ok, I don't mind adding the comma

2022-03-04 11:36 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +                type: 'boolean'
```suggestion
                type: 'boolean',
```

2022-03-04 11:36 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +            enable: true
```suggestion
            enable: true,
```

2022-03-04 11:39 UTC, mehmetegemen approved these changes

2022-03-04 12:02 UTC, merged