Add content from SDK docs - Closes #1405
LiskArchive/lisk-legacy-docs pull request #1411
Opened 2022-03-02 14:35 UTC by Tschakki

Closes #1405

2022-03-03 18:04 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2022-03-03 18:04 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/configure-app.adoc
> +Allowing arbitrary machines to access the rpc port (ws) is dangerous and strongly discouraged -- access should be strictly limited to trusted machines.
```suggestion
Allowing arbitrary machines to access the rpc port (ws) is dangerous and strongly discouraged -- access should be strictly limited only to trusted machines.
```

2022-03-03 18:04 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +It is recommended to install Lisk Commander globally with NPM (Node Packet Manager),  to facilitate the convenient usage of the Lisk Commander CLI.
```suggestion
It is recommended to install Lisk Commander globally with NPM (Node Packet Manager), in order to facilitate the convenient usage of the Lisk Commander CLI.
```

2022-03-03 18:04 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +Both objects can be customized before passing them to the `Application` instance, if desired.
```suggestion
Both objects can be customized before passing them to the `Application` instance if desired.
```

2022-03-03 18:04 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/non-forging-node-protection.adoc
> +This is a bit of a 3-pronged approach to rate limiting.
```suggestion
This is somewhat of a 3-pronged approach to rate limiting.
```

2022-03-04 10:14 UTC, shuse2 requested changes

2022-03-04 10:14 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/api.adoc
> += API
This should still remain as `Reducers` for v5

2022-03-04 10:14 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/endpoints.adoc
> +:sdk_docs: lisk-sdk::
`Endpoints` should be kept as `Actions` for v5

2022-03-04 10:14 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/modules-commands.adoc
> += Modules and commands
This should be Modules and `assets` for v5

2022-03-04 10:14 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/create-command.adoc
> +:docs_sdk: lisk-sdk::
This document also should remain as `new asset` for v5

2022-03-04 10:14 UTC, shuse2 commented on docs/modules/ROOT/nav.adoc
> +** xref:lisk-sdk::index.adoc[]
Title shown on the left navigation looks off. Can we change it to
- Lisk SDK
- Lisk Core
- Lisk Service
?

2022-03-04 11:38 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/endpoints.adoc
> +:sdk_docs: lisk-sdk::
What about events?

2022-03-04 16:58 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/endpoints.adoc
> +:sdk_docs: lisk-sdk::
I thought this is about public APIs in general, doesn't it include events as well? I wouldn't mind talking about both on one page here, like it is done currently. Otherwise we should probably have a second page for events?

Imho we can leave it as it is including the name, or change `endpoints` to `public interfaces` or so.

2022-03-04 17:48 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/endpoints.adoc
> +:sdk_docs: lisk-sdk::
changing the name now will probably confusing as `actions` is the actual name now on v5.
Events are events on v5 and v6, but the specification/behavior will be slightly different on v6. (still in research)

2022-03-04 17:50 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/endpoints.adoc
> +:sdk_docs: lisk-sdk::
Also, actions doesnt include `events`. there are different things although they are both exposed through JSON RPC

2022-03-09 07:46 UTC, shuse2 approved these changes

2022-03-09 08:52 UTC, merged