Improve Core docs - Closes #1407
LiskArchive/lisk-legacy-docs pull request #1420
Opened 2022-03-07 15:03 UTC by Tschakki

Closes #1407

2022-03-10 09:10 UTC, sameersubudhi requested changes
Please find my observations below.

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/partials/core-post-installation.adoc
> +To make use of all commands of the Lisk Core xref:{url_ref_cli}[], enable IPC in the config.
```suggestion
To make use of all the Lisk Core commands xref:{url_ref_cli}[], enable IPC in the config.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/setup/snap.adoc
> +This is the recommended setting for reducing th amount of logs for a running node.
```suggestion
This is the recommended setting for reducing the number of logs for a running node.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/setup/snap.adoc
> +However, to verify the correct start of the node, just update the log levels in the config to info or lower.
It might be better to explicitly highlight the constants.

```suggestion
However, to verify that the node started correctly, update the log levels in the config to `info` or lower.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/setup/npm.adoc
> +However, to verify the correct start of the node, just update the log levels in the config to info or lower.
```suggestion
This is the recommended setting for reducing the number of logs for a running node.
However, to verify that the node started correctly, update the log levels in the config to `info` or lower.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/setup/docker.adoc
> +However, to verify the correct start of the node, just update the log levels in the config to info or lower.
```suggestion
This is the recommended setting for reducing the number of logs for a running node.
However, to verify that the node started correctly, update the log levels in the config to `info` or lower.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +However, to verify the correct start of the node, just update the log levels in the config to info or lower.
```suggestion
This is the recommended setting for reducing the number of logs for a running node.
However, to verify that the node started correctly, update the log levels in the config to `info` or lower.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +| | Mainnet | Testnet | Devnet
Should we be mentioning the `Devnet` over here? It is not a public network and the `Network Identifier` would vary if someone used their own modified version of the genesis block to start their personal `Devnet`.

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/management/configuration.adoc
> +To quickly connect to a specific network with Lisk Core, specify the desired network with the `--network` or `-n` flag.
```suggestion
To quickly connect your Lisk Core node to a specific network, specify the desired network with the `--network` or `-n` flag.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/management/configuration.adoc
> +NOTE: If the node will connect to the Mainnet, change `testnet` to `mainnet` in the snippet above.
```suggestion
NOTE: If you intend to connect the node to the Mainnet, change `testnet` to `mainnet` in the snippet above.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/management/forging.adoc
> +The command will ask for the delegate passphrase, and in order to symmentrically encrypt the passphrase for the config, it will also ask for a password.
```suggestion
The command will ask for the delegate passphrase, and in order to symmetrically encrypt the passphrase for the config, it will also ask for a password.
```

2022-03-10 09:10 UTC, sameersubudhi commented on modules/ROOT/pages/management/forging.adoc
> +<1> Set the console log level to `info` to view all relevant logs in the console.
```suggestion
<1> Set the console log level to `info` to view all relevant logs on the console.
```

2022-03-10 14:14 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +| | Mainnet | Testnet | Devnet
Yes  agree, it is no public network. I can remove it here.

2022-03-11 13:33 UTC, sameersubudhi submitted a review, later dismissed
LGTM overall. Please consider the minor remark below before merging the PR.

2022-03-11 13:33 UTC, sameersubudhi commented on modules/ROOT/pages/management/configuration.adoc
> +NOTE: Remember to xref:{url_pm2_restart}[restart] the node properly, to change to the new config.
```suggestion
NOTE: Remember to xref:{url_pm2_restart}[restart] the node for the new config changes to take effect.
```

2022-03-11 14:58 UTC, merged