Add new/missing content to general docs -  Closes #1417
LiskArchive/lisk-legacy-docs pull request #1423
Opened 2022-03-11 11:14 UTC by Tschakki

Closes #1417

2022-03-14 16:11 UTC, chris529 reviewed
Looks good, just a few very minor points 👍

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> +The Publish/Subscribe API is sometimes also called Event-Driven API.
```suggestion
The Publish/Subscribe API is sometimes also called an Event-Driven API.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> +The biggest difference between Event-Driven and regular REST API is not only technical.
```suggestion
The main difference between Event-Driven and regular REST API is not only technical.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> +Lisk Service leverages the two-way communication approach by utilizing the WebSocket library responsible for updating users about changes in the blockchain network and markets.
```suggestion
Lisk Service leverages the two-way communication approach by utilizing the WebSocket library responsible for updating users regarding changes in the blockchain network and markets.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> +The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the `action` is equivalent to method type performed on the ser
```suggestion
The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the `action` is equivalent to the method type performed on the server (i.e., `update`), and `entity` is a part of the application logic, ex. `accounts`, `transactions`.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to HTTP standard (GET, POST, PUT, etc
```suggestion
The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to the  HTTP standard (GET, POST, PUT, etc.), and `entity` is a part of the application logic, ex. `accounts`, transactions and so on.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +In the contrary to the original Lisk Core API, all timestamps used by the Lisk Service are in the UNIX timestamp format.
```suggestion
Contrary to the original Lisk Core API, all timestamps used by the Lisk Service are in the UNIX timestamp format.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Retrieves votes of a single account based on address, public key or delegate name.
```suggestion
Retrieves votes of a single account based on address, public key, or delegate name.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Retrieves voters for a delegate account based on address, public key or delegate name.
```suggestion
Retrieves voters for a delegate account based on address, public key, or delegate name.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Retrieves blocks from the blockchain based on ID, height or account.
```suggestion
Retrieves blocks from the blockchain based on ID, height, or account.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +In the following guides it is explained step by step how to create a very simple blockchain application by the example of the "Hello World" blockchain application, which allows users to save hello me
```suggestion
In the following guides, it is explained step by step how to create a very simple blockchain application by using the example of the "Hello World" blockchain application, which allows users to save hello messages in their accounts.
```

2022-03-14 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/decoding-transactions-blocks.adoc
> +In most scenarios it is beneficial to have a local node running (for example the {url_example_helloapp}[Hello World application^]) to which the client can send the API requests.
```suggestion
In most scenarios, it is beneficial to have a local node running (for example, the {url_example_helloapp}[Hello World application^]) to which the client can send the API requests.
```

2022-03-15 10:04 UTC, chris529 reviewed
Looks great! Only 1 very minor point 👍

2022-03-15 10:04 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> += Publish/Subscribe API (Lisk Sevice)
```suggestion
= Publish/Subscribe API (Lisk Service)
```

2022-03-17 10:49 UTC, shuse2 requested changes

2022-03-17 10:49 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +The following image provides an overview of the "Hello" application:
it feels little bit out of place to have hello world application here

2022-03-17 10:49 UTC, shuse2 commented on docs/modules/ROOT/pages/api/lisk-service-http-testnet.adoc
> += Testnet HTTP API (Lisk Service)
Maybe we don't need testnet api if we have service doc for future version?

2022-03-17 10:49 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Operations on the database are called *transactions*.
I think the below sentence is correct. maybe something like
`Triggers for the database operations are called *transactions*`?

2022-03-17 10:49 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Transactions are shared among users connected in a *P2P network* and are grouped together into *blocks*.
```suggestion
Transactions are shared among nodes connected in a *P2P network* and are grouped together into *blocks*.
```

2022-03-17 12:01 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +The following image provides an overview of the "Hello" application:
I changed the structure a little bit, is it better now?

2022-03-17 15:07 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +The following image provides an overview of the "Hello" application:
yes i think it looks better

2022-03-17 15:08 UTC, shuse2 approved these changes

2022-03-17 17:22 UTC, closed without merging