Create what is blockchain page in Lisk docs - Closes #1457
LiskArchive/lisk-legacy-docs pull request #1465
Opened 2022-04-28 14:29 UTC by chris529

2022-05-03 15:59 UTC, Tschakki requested changes

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Essentially, a blockchain is a database that is shared across multiple computers. +
Centralized databases can be shared between multiple computers as well. I think the really unique idea behind blockchain is, that the power of altering this shared database is not lying in the hand of a central authority, instead it s governed by a network of machines, or nodes. In this network, the nodes are competing to add new blocks to the chain, by rules defined in the consensus algorithm.

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +In general, the key attributes of blockchain technology are decentralization, accountability, and security, which also results in operational efficiency and significant cost savings. +
We should also mention, that there are also centralized blockchains and it depends a lot on the chosen consensus algorithm and the state of the network, if a blockchain can truly be considered fully decentralised. Also, we could discuss here, what does decentralization mean? We often refer to it when looking at the network itself, but other aspects might be also relevant for a blockchain project to be considered truly decentralized. Like, for example who is developing the needed software? And who decides about the new features to be added and how to prioritize and plan the development? Who can make changes in the Protocol? It is interesting to look at the different aspects of decentralization, and pointing out that true decentralization is very hard to reach, maybe also point out some examples of rather centralized and decentralized blockchain projects. After pointing out that true decentralizsation is veyr hard to reach, and that is can have some disadvantages on its own, wen can also introduce Lisk of being a hybrid approach, bringing together best of both worlds.

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +The transaction is now completed, and this block will remain permanently in the blockchain.
Fixed the styling for the list.
Also, I have some further points on this:
- what is the difference between `validation` and `verification`? not clear for me.
- `joiining the chain` is not really a separate step, this is already happening in the previous step, following the description.
- `transaction completed` is also no separate step, it happens when the block is added to the blockchain.

```suggestion
. *A transaction is sent*:
Once a transaction is sent, every node (computer), connected to the blockchain network is informed about it. 
. *The validation process*:
The transaction is then validated by each node connected to the network.
. *The verification process*:
After every node on the network has verified the transaction, the block of data (containing the transaction), will then be added to the distributed ledger.
. *Block creation*:
The verified transaction is now visible on the ledger as a block of data. All of the transactions that were included within the block, such as the sender, the receiver, the relevant data (e.g. the token/coin amount), the timestamp, and other technical criteria (which will be covered further in this section), are now present in this block.
. *Joining the chain*:
This block is now added permanently to the blockchain, whereby it cannot be altered, modified, replaced, or removed. Hence, it becomes completely immutable.
. *Transaction completed*:
The transaction is now completed, and this block will remain permanently in the blockchain.
```

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +All completed transactions are recorded in a chronological manner, which in turn results in an immutable chain. This ‘ledger’ which in reality is a  number of blocks chained together, and as mentione
That the txs are recorded chronologically is not really the reason why blockchain is immutable, it is more of a result of it. It would be nice to talk in a little more detail about why data in blockchains is considered immutable

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +image:intro/basic-blockchain.png[align="center"]
I would update this diagram to be more precise about, how the blocks are linked. In general, a block includes the hash of the previous block in the block header. If this is visible in the diagram, it is also easier to explain immutability by referring to it.

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +All new transactions (blocks), that occur within the network simultaneously update every fully participating node in the network ecosystem regardless of their location, so this results in what is kno
is this the definition of a decentralised system? Sounds a little confusing to me.

2022-05-03 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Finally, the contents of a block could represent data and transactions of many types. For example, this could be currencies/tokens, identity, digital rights, intellectual property, and many more diff
Maybe provide more details and/or some examples.

2022-05-04 07:37 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Essentially, a blockchain is a database that is shared across multiple computers. +
Excellent feedback Mona, thanks very much. I have tailored this accordingly and included it. 
I am trying not to delve too deeply into the details on this first introductory page, but allude to how the intricacies of blockchain will be explained in the following pages.

2022-05-04 07:49 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +In general, the key attributes of blockchain technology are decentralization, accountability, and security, which also results in operational efficiency and significant cost savings. +
Indeed, I agree totally. Coincidentally, I already started to include most of these topics on the following 'How blockchain works' page, (which is still a work in progress). However, I can amplify a bit on some of these points here... 👍

2022-05-04 12:18 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +The transaction is now completed, and this block will remain permanently in the blockchain.
Thanks for the stying update. Fair point, I have now described the validation and verification process in further detail, and have amalgamated the contents of the previous steps 'Joining the chain' and 'Transaction complete', which should make it clearer.

2022-05-04 13:32 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +All completed transactions are recorded in a chronological manner, which in turn results in an immutable chain. This ‘ledger’ which in reality is a  number of blocks chained together, and as mentione
Good point, I have now written a few paragraphs explaining immutability in more detail. 👍

2022-05-04 13:47 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +image:intro/basic-blockchain.png[align="center"]
Coincidentally, I already built this exact diagram, (showing the hashes, previous hash, timestamp, etc.) which is inserted into the following page "How blockchain works', as originally I wanted to delve deeper into this and try to keep this first page as more of a high-level overview...
OK, perhaps it would be better to insert it here, and then give a bit more of a detailed description of Decentralization and Consensus. I have now done it 👍

2022-05-05 16:30 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +All new transactions (blocks), that occur within the network simultaneously update every fully participating node in the network ecosystem regardless of their location, so this results in what is kno
I have rebuilt this and included a section on decentralization

2022-05-05 16:31 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Finally, the contents of a block could represent data and transactions of many types. For example, this could be currencies/tokens, identity, digital rights, intellectual property, and many more diff
I have also rebuilt and expanded on this.

2022-05-09 11:42 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +The benefits of using this structure are that at its core, it is a shared and immutable ledger that enables transactions to be recorded, and assets to be tracked. Furthermore, with this technology it
Should we also make a point about decentralization?

2022-05-09 11:42 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Firstly, as can be seen in the illustration below, a blockchain essentially consists  of a chain of blocks all containing information. Each individual block contains several components. However, to s
```suggestion
Firstly, as can be seen in the illustration below, a blockchain essentially consists  of a chain of blocks all containing information. Each individual block contains several components. However, to simplify this and give an initial high-level overview, these can roughly be characterized into the block header and the transaction list (data). +
```

2022-05-09 11:42 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +It is then verified by checking how many blocks now exist on top of the validated block. In other words, the block of data containing the transaction (this is also known as block confirmation), will
`It is verified by checking how many blocks now exist on top of the validated block.`

I am not sure what you mean here

2022-05-09 11:42 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Immutability is classed as one of the key advantages of blockchain and this is made possible by the deployment of cryptographic hashes. The key benefit here is that a hash cannot be reverse-engineere
Maybe we can add a sentence here that if an invalid block is detected it would be rejected in the network by other nodes.

2022-05-10 07:07 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +The benefits of using this structure are that at its core, it is a shared and immutable ledger that enables transactions to be recorded, and assets to be tracked. Furthermore, with this technology it
Hi Mitsu, Thanks. I have now built a section on decentralization. 👍

2022-05-10 08:02 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +It is then verified by checking how many blocks now exist on top of the validated block. In other words, the block of data containing the transaction (this is also known as block confirmation), will
I have reworded it, so it should be a bit clearer...

2022-05-10 08:14 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Immutability is classed as one of the key advantages of blockchain and this is made possible by the deployment of cryptographic hashes. The key benefit here is that a hash cannot be reverse-engineere
Good point, I have added a sentence to cover this 👍

2022-05-10 08:59 UTC, Tschakki requested changes

2022-05-10 08:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Essentially, a blockchain is a database that is shared across multiple computers. Centralized databases can also be shared between multiple computers as well, however, one of the key advantages of bl
Please remember to follow the best practice to start a new line for each sentence.
Also, for the last sentence `This will be explained in more detail further in this section.` I think the content was now moved to "How blockchain works", so maybe add a link to there here.

2022-05-10 08:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +====
Maybe explain here instead, what is a transaction in context of blockchain? What are its main properties, and explain that transaction can make all kinds of state mutations on the blockchain, not only transferring tokens from person A to B.

2022-05-10 08:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +The contents of each block, e.g. the transactions are created using a cryptographic hash function. This basically consists of an alphanumeric string that is generated by each block individually. Ever
Please use only one sentence per line.

Also, we explain here a very important concept, we should not take for granted, that it is immediately clear to people, why a block containing the hash of the previous block is making it coupled. Try to add more details, maybe start with explainig what a hash is, maybe by giving an example, and point out the important characteristics of hashes, especially in the context of blockchain. Make  an example how changing a tiny bit in a block of a blockchain will break the link between the blocks, to illustrate immutability. Please check this very good demo for some inspiration: https://andersbrownworth.com/blockchain/ (You can also link to it on the page, or maybe include the video, if we give the right credits)

2022-05-10 08:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +In the case whereby an invalid transaction occurs, the block containing this transaction will be detected, and subsequently rejected by the network.
This sentence feels a little out of context here, I don't see how this is connected to immutability and the content before and after this sentence.

2022-05-10 08:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +image::intro/blockchain-architecture.png[, align="center"]
I think the last block should be block 4 or 3 not "Block n", or add three dots or something between Block 3 and Block N, to indicate many more blocks are coming between them.

2022-05-10 13:04 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Essentially, a blockchain is a database that is shared across multiple computers. Centralized databases can also be shared between multiple computers as well, however, one of the key advantages of bl
Many thanks, Mona. Yes, I will follow the best practice here as recommended, You are correct, the Consensus section has now been moved to the next page, so I have added a link accordingly 👍

2022-05-10 14:55 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +====
I have created a paragraph on transactions to try and cover most of the points you mentioned. I think it would be wise to keep the 'how a blockchain transaction works' paragraph here, as it provides a high-level overview at this point. I have also alluded to the properties/transactions and referred to the 'Transactions' page in the docs. 
If I understand correctly, the state mutations are covered when we get into on-chain logic. However, if you have time, perhaps you could add in a sentence or two on this Mona if you feel it would be a good fit here..?

2022-05-10 15:59 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +The contents of each block, e.g. the transactions are created using a cryptographic hash function. This basically consists of an alphanumeric string that is generated by each block individually. Ever
Added a 'Hashing function' paragraph...Yes, that link is excellent, I think we could include it, maybe a the end of this page...

2022-05-10 16:03 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +In the case whereby an invalid transaction occurs, the block containing this transaction will be detected, and subsequently rejected by the network.
OK, I have moved it into the new 'What is a transaction' paragraph.

2022-05-10 16:13 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +image::intro/blockchain-architecture.png[, align="center"]
Updated diagram 👍

2022-05-12 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +image::intro/blockchain-architecture.png[, align="center"]
Thanks, but the arrow in the diagram still goes from Block N straight to Block 3. I think you want to indicate with block N, this is the latest block in the blockchain. I think it would be nice to indicate visually that there can be any more blocks between block 3 and block N on die diagram.

2022-05-12 14:37 UTC, Tschakki requested changes
Looking good, just a few minor suggestions :)

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== Introduction - The basics of blockchain
```suggestion
== Introduction - The basics of blockchain
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== What is a block?
```suggestion
== What is a block?
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== What is a transaction?
```suggestion
== What is a transaction?
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== How does a blockchain transaction work?
```suggestion
== How does a blockchain transaction work?
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== Immutability
```suggestion
== Immutability
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== Hashing function
```suggestion
== Hashing function
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +=== Decentralization
```suggestion
== Decentralization
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +:page-next-title: how blockchain works
these attributes are not required anymore since the update, and can be removed.

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +:url_how_blockchain_works: {docs_sdk}/root/intro/how-blockchain-works.adoc
```suggestion
:url_how_blockchain_works: intro/how-blockchain-works.adoc
```

2022-05-12 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +:url_transactions: https://lisk.com/documentation/lisk-sdk/protocol/transactions.html
```suggestion
:url_transactions: understand-blockchain/lisk-protocol/transactions.adoc
```

2022-05-16 07:12 UTC, chris529 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +image::intro/blockchain-architecture.png[, align="center"]
As discussed... 👍

2022-05-16 13:29 UTC, mitsuaki-u approved these changes
Great work :)

2022-05-16 14:26 UTC, Tschakki approved these changes
Thanks, looking good!

2022-05-17 08:54 UTC, merged