Create how blockchain works page in  Lisk docs - Closes #1467
LiskArchive/lisk-legacy-docs pull request #1475
Opened 2022-05-20 06:44 UTC by chris529

2022-06-16 13:21 UTC, Tschakki requested changes
Please see my remarks and add the new intro section with the 2 new pages about blockchain to the `nav.adoc`
And also you could make certain keywords in the sections bold to highlight them, if you feel it fits (or add links to further information)

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image:intro/cryptography.png[]
This diagram seems to be related to symmetrical encryption only, so I think it should be under the respective section about symmentric encryption.

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Cryptography
Please explain, where which encryption type is used in the context of blockchain here as well, so the reader can understand why cryptography is important here

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As described on the previous page from a high-level perspective blockchain is basically a 'digital ledger' which has many functionalities and use cases.
Add the title and a link to the previous page here

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, when compared to the other consensus mechanisms, it is somewhat inefficient as it requires a high amount of energy and processing power to reach a consensus, therefore being rather cumbersom
I think this not 100% correct, as the amount of energy required depends highly on the overall competition between miners in the network.

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Basically to validate transactions it requires the nodes to solve an arbitrary mathematical problem or complex equations, which prevents the network being hacked, and also provides a high level of se
I think we should add a little more info and context here about PoW

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Consensus algorithms
For each of the sections, it would be nice if you can include links to further information about the consensus algorithms, as well as links explaining certain concepts or terms that you use to explain the algorithm here on a high level in more detail.

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The proof-of-stake-mechanism uses a random algorithm for consensus building and eliminates the need for complex mathematical calculations, hence reducing the overall computing power and energy requir
How is it random, if it chooses validators based on the stake? Please elaborate, a little bit more on this as it might sound confusing

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, the DPoS has the advantage of being able to execute transactions and verifications much faster, which results in higher scalability.
Much faster than what? Clarify and maybe add links to sources for this statement

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +:toc: preamble
```suggestion
= How blockchain works
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: The How blockchain works page describes in more detail the functionalities of a blockchain.
:toc: preamble
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Overview
```suggestion
== Overview
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Key characteristics of blockchain
```suggestion
== Key characteristics of blockchain
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Consensus mechanisms
```suggestion
== Consensus mechanisms
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Consensus mechanisms
I don't think there is much difference between consensus mechanisms and algorithms, it is probably better to merge these two sections, and stick with one term for it (and maybe mention the other term as synonym once, if it is used often)

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Byzantine-Fault-Tolerance (BFT)
```suggestion
== Byzantine-Fault-Tolerance (BFT)
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Peer-2-Peer networks
```suggestion
== Peer-2-Peer networks
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +==== Unstructured P2P networks
```suggestion
=== Unstructured P2P networks
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +==== Structured P2P networks
```suggestion
=== Structured P2P networks
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +==== Hybrid P2P networks
```suggestion
=== Hybrid P2P networks
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Cryptography
```suggestion
== Cryptography
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== State machine
```suggestion
== State machine
```

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +By its very nature a P2P system offers a high level of security, as it is virtually immune to any Denial-of-Service (DoS, attacks), any also any censorship by a central governing body (for example, a
If we talk about DoS attacks, maybe it is more a higher availability than really a security advantage?

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +By its very nature a P2P system offers a high level of security, as it is virtually immune to any Denial-of-Service (DoS, attacks), any also any censorship by a central governing body (for example, a
Also, P2P alone doesn't prevent an entity from censoring something, so maybe it is not the right place to mention it here.

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To summarise, if blockchain technology is deployed using a P2P network architecture, then this will result in greater freedom, security, immutability, and enhanced decentralization.
What does it mean "if blockchain is deployed using P2P"? II think all blockchain run on P2P networks, but P2P alone doesn't ensure security and immutability, so I think the summary is wrong here.

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +==== Structured P2P networks
I don't think it is relevant to explain structured and hybrid P2P networks in much detail, unless they are used in other popular blockchain networks. At Lisk we have an unstructured partial mesh network, so it would be nice explain that to the reader.

Also, diagrams can be really helpful to explain differences between the different networks without the need of too many words.

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
I am not 100% sure but I think blocks alone can also alter the state of the blockchain?

2022-06-16 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The state store can mutate the state of the actual blockchain data, and it can also retrieve data from the blockchain.
The state store is a special data structure we use in the Lisk SDK, it is not exactly the same as a state machine, so I wouldn't explain the state store here at this place

2022-06-16 15:22 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image:intro/cryptography.png[]
Good point! I have revamped the Cryptography section, and also built an additional diagram for asymmetric encryption as well 👍

2022-06-16 16:04 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Cryptography
Good point, also now done and added to the asymmetric encryption section 👍

2022-06-16 16:10 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As described on the previous page from a high-level perspective blockchain is basically a 'digital ledger' which has many functionalities and use cases.
Done 👍

2022-06-16 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, when compared to the other consensus mechanisms, it is somewhat inefficient as it requires a high amount of energy and processing power to reach a consensus, therefore being rather cumbersom
I have updated this 👍

2022-06-16 17:33 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Basically to validate transactions it requires the nodes to solve an arbitrary mathematical problem or complex equations, which prevents the network being hacked, and also provides a high level of se
Done 👍

2022-06-17 08:06 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Consensus algorithms
OK, I have added some relevant links... 👍

2022-06-17 10:10 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The proof-of-stake-mechanism uses a random algorithm for consensus building and eliminates the need for complex mathematical calculations, hence reducing the overall computing power and energy requir
It should now be clearer 👍

2022-06-17 10:31 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, the DPoS has the advantage of being able to execute transactions and verifications much faster, which results in higher scalability.
Done 👍

2022-06-17 11:56 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Consensus mechanisms
Good point...Now done 👍

2022-06-17 11:59 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The state store can mutate the state of the actual blockchain data, and it can also retrieve data from the blockchain.
Agreed...OK, I have now removed this sentence 👍

2022-06-17 12:15 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +By its very nature a P2P system offers a high level of security, as it is virtually immune to any Denial-of-Service (DoS, attacks), any also any censorship by a central governing body (for example, a
I have reworded it 👍

2022-06-20 07:50 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +By its very nature a P2P system offers a high level of security, as it is virtually immune to any Denial-of-Service (DoS, attacks), any also any censorship by a central governing body (for example, a
Now updated 👍

2022-06-20 08:04 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To summarise, if blockchain technology is deployed using a P2P network architecture, then this will result in greater freedom, security, immutability, and enhanced decentralization.
Good point...I have now reworded this 👍

2022-06-20 10:08 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +==== Structured P2P networks
Good point. I have added an extra paragraph to explain unstructured partial mesh networks and a link to our P2P architecture 👍

2022-06-20 10:18 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
I don't think so...From my understanding, any given block cannot be altered retroactively without altering all subsequent blocks. So once a block has been added to the chain, it can be referenced in subsequent blocks, but it can't be changed as far as I am aware.

2022-06-21 10:14 UTC, Tschakki requested changes
Had a few ideas for improvement, please see my comments :)

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +
Intro section should be the first section, order of page should be the order defined in the docs site structure document

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
I was not talking about altering a previous block, my point is more, that a block without any transactions inside may alter the state of the blockchain as well I think. So it are blocks and transactions that can alter the state of the blockchain, but maybe one of the devs can clarify

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, xref:{url_hashing}[hashing] does not only provide the required security, as described earlier on the previous page, it is also deterministic and has the ability to provide immutability as
```suggestion
Therefore, {url_hashing}[hashing^] does not only provide the required security, as described earlier on the previous page, it is also deterministic and has the ability to provide immutability as well, which as we have learned is highly beneficial.
```

external url

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image:intro/asymmetric-encryption.png[]
I personally like the image of pub/priv key cryptography where the public key is in fact pictured as a lock, and the private key is the corresponding key to the lock. It might capture the relationship of public/private key better than two keys, what do you think?

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +:page-next-title: Lisk products
```suggestion
```

deprecated

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +:url_blockchain: /root/intro/what-is-blockchain.adoc
```suggestion
:url_blockchain: intro/what-is-blockchain.adoc
```

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +:url_account-store: {sdk-docs}references/lisk-elements/chain.adoc#state-store-and-database-mechanism
`sdk-docs` is not defined here, yet

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +:url_lisk-products: /root/intro/lisk-products.adoc
```suggestion
:url_lisk-products: intro/lisk-products.adoc
```

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Further more detailed information regarding PoS can be found xref:{url_pos}[here].
```suggestion
Further more detailed information regarding PoS can be found {url_pos}[here^].
```

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To summarise,  a xref:{url_p2p_networks}[P2P network architecture] offers numerous benefits as compared to a traditional client-server-based network and results in greater freedom, improved security,
```suggestion
To summarise,  a {url_p2p_networks}[P2P network architecture^] offers numerous benefits as compared to a traditional client-server-based network and results in greater freedom, improved security, and enhanced decentralization.
```

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, with this stake-weighted xref:{url_voting-mechanism}[voting mechanism] DPoS has the advantage of being able to execute transactions and verifications much faster than PoS or PoW, as ther
```suggestion
Furthermore, with this stake-weighted {url_voting-mechanism}[voting mechanism^] DPoS has the advantage of being able to execute transactions and verifications much faster than PoS or PoW, as there are a limited number of validators.
```

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Symmetric Key
Please include a statement that symmetric encryption is not really used in blockchain context, or if it is, mention where.

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As discussed, the encryption techniques play an important role here, as it is critical for a blockchain to use the most secure methodology, which ensures the key functions can be securely managed, su
Please elaborate more on these points, where asymmetric encryption is used in the blockchain context, and give concrete examples, for example for identity management, the example is that the public key is the account address, and the private key is the passphrase of the account.

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Cryptography
I think for easier reading we should highlight the most important information of these paragraphs in a concise way. 

For example create checklists for the following points for each kind of cryptography:

- Where is this used in blockchain and how?
- Why is it used here / what are the advantages?

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Proof-of-Work (PoW)
please add at least one link with a good resource with further information about PoW

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Consensus mechanisms
I think it would lighten up the reading here, if we add some simple diagrams, picturing the essence of the respective consensus algorithm. E.g. PoW you could picture someone mining in mountain to randomly finding a block/ the solution to the mathematical problem. In PoS there is a very rich blacksmith having the right to forge a new block. and PoS you could picture a democratic elected blacksmith forging a block, being cheered by his voters :)

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Consensus mechanisms
Please note down the following points as checklists for each consensus algorithm, to summarize:

- What are the advantages of this consensus?
- What are the possible disadvantages?

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This can offer the best of both worlds, and operate more efficiently as they generally contain an index/central server which can also connect and provide connections between the network nodes.
I don't think this is relevant, can be removed

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Unstructured partial mesh networks
This should be moved under `Unstructured P2P networks` section, because it is a subcategory of that network type

2022-06-21 10:14 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Unstructured partial mesh networks
Please note that we have already a section in our existing docs talking about the p2p network: https://liskhq.github.io/lisk-docs/understand-blockchain/index.html#p2p-unstructured-partial-mesh-network

Try to remove redundant content and update this, or the existing content in a way that is complements each other in a nice way.

2022-06-21 11:52 UTC, chris529 commented on docs/modules/ROOT/nav.adoc
> +
Done 👍

2022-06-21 13:31 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
@Incede Rishi, Can you clarify this point please, so if necessary I can update the diagram accordingly? Many thanks.

2022-06-21 13:32 UTC, chris529 commented on docs/modules/ROOT/nav.adoc
> +
Done 👍

2022-06-21 14:51 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Symmetric Key
Good point...now done 👍

2022-06-21 15:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As discussed, the encryption techniques play an important role here, as it is critical for a blockchain to use the most secure methodology, which ensures the key functions can be securely managed, su
I have elaborated on this 👍

2022-06-21 16:04 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Cryptography
Done 👍

2022-06-22 12:59 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Proof-of-Work (PoW)
Done 👍

2022-06-22 13:01 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This can offer the best of both worlds, and operate more efficiently as they generally contain an index/central server which can also connect and provide connections between the network nodes.
Done 👍

2022-06-23 09:54 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Consensus mechanisms
As discussed, I have now created a Trello card in the Design request board 👍

2022-06-23 12:14 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Consensus mechanisms
Done 👍

2022-06-23 12:18 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Unstructured partial mesh networks
Done 👍

2022-06-23 12:24 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image:intro/asymmetric-encryption.png[]
I have had a look at numerous depictions of how to explain this from a graphical image perspective, and imho I prefer the 2 key image. In addition, it maintains the uniformity with the first 1 key image describing the symmetric encryption, so I would prefer to leave it as it is. :pray:

2022-06-23 12:28 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Unstructured partial mesh networks
Done 👍

2022-07-08 16:26 UTC, Incede requested changes
Looks good in general. I commented & argued against some apparent controversial statements although I am eager to hear your opinion :)

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As described on the previous xref:{url_blockchain}[What is blockchain] page, from a high-level perspective a blockchain a 'digital ledger' which has many functionalities and use cases.
```suggestion
As described on the previous xref:{url_blockchain}[What is blockchain] page, from a high-level perspective a blockchain is a 'digital ledger' which has many functionalities and use cases.
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Once a block of data is added to the blockchain it will remain publicly viewable to anyone at any time.
'it will remain publicly viewable to anyone at any time.`
True only if the blockchain is public. Not true for permissioned/private chains

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This is a highly beneficial system as it enables permanent records to be kept, enabling the storage of almost any type of record.
`it enables permanent records to be kept`
This statement can be a bit controversial because some blockchains prune old history from time to time, in which case only a proof of some records can be retrieved but not the record itself. For eg. with Lisk Core v3 after re-genesis it wasn't possible to retrieve all historical transactions of some accounts.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As previously mentioned once created, the blocks are immutable and cannot be changed retroactively.
```suggestion
As previously mentioned once finalized, the blocks are immutable and cannot be changed retroactively.
```
A block needs to wait a few rounds to be finalized after creation, before which it can still be replaced.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Decentralization – The contents of each block in the blockchain can be accessed by any node on the network, as they are essentially network copies that are present on all participating nodes.
`Decentralization – The contents of each block in the blockchain can be accessed by any node on the network`

Controversial because :
1. Universal access doesn't make a database decentralized, just makes it public.
2. Access is restricted on private/permissioned chains
3. Decentralization is about the distribution of authority to change the rules from one/some entities to multiple/many. But since some blockchains(private/permissioned) are controlled by a pre-decided/limited number of entities or hosted on private servers, I'm not sure classifying all blockchains as decentralized is strictly correct.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, there is no central entity that holds each block in the chain, so this creates decentralization.
`no central entity that holds each block in the chain, so this creates decentralization.`
I am not sure what this means. Holding/storing the blocks is not related to decentralization, holding the `control` to change them is.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Immutability – A blockchain can be considered a permanent, unchangeable, and irreversible record of transactions.
`permanent`
As I explained earlier, this is not true. The blockchains are just database in the end and can be seized, destroyed, forked and pruned to remove earlier history. Only immutability holds.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, once a block is created and added to the blockchain it ensures the transaction is completely trustable.
```suggestion
Hence, once a block is finalized and added to the blockchain it ensures any transaction in that block is completely trustable.
```
`completely trustable`
Again a bit controversial :) as the level of trust changes depending upon various parameters of a particular network - reputation, hard forks, decentralization, layer 1,2,3 etc. but I wouldn't call it `completely` trustable.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Transparency – A blockchain by its very nature provides total open transparency.
`total open transparency`
not true for permissioned/private chains

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The consensus algorithm is responsible for ensuring that only 1 copy of the data encapsulated in each block exists within each node.
```suggestion
The consensus algorithm is responsible for ensuring that the exact same copy of the data encapsulated in each block exists within each node.
```
Optional : `only 1 copy` sounded a bit confusing for me so I rephrased it :)

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +It is also effective for crypto mining, minting new tokens, and validating transactions.
`It is also effective for crypto mining`
I am not sure if `mining` is a use-case, probably just a side-effect.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +On the other hand, the disadvantages consist of PoW being very energy intensive, hence high amounts of energy are consumed in the mining process.
```suggestion
On the other hand, the disadvantages consist of PoW being very energy intensive, since high amounts of energy are consumed in the mining process.
```
mining causes -> high energy consumption
not the other way around

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, when compared to the other consensus mechanisms, it is somewhat inefficient as it requires a high amount of energy and processing power which is often attributable to the degree of competiti
```suggestion
However, when compared to the other consensus mechanisms, it is somewhat inefficient as it requires a high amount of energy and processing power which is often attributable to the degree of competition between the miners in order to mine a block & win the block reward, therefore this results in being rather cumbersome and expensive to operate.
```
The competition b/w the miners (and hence the high hash-rate) is to win the block reward. Consensus can still be achieved with low hash rates during low network difficulty.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Basically, to validate transactions it requires the nodes to solve an arbitrary mathematical problem or complex equations, which prevents the network from being hacked, and also provides a high level
```suggestion
Basically, to create a block it requires the nodes to solve an arbitrary mathematical problem or complex equations, which prevents the network from being hacked, and also provides a high level of security.
```
`to validate transactions it requires the nodes to solve an arbitrary mathematical problem`
Not strictly true technically as the transactions are already validated prior to starting the "solve an arbitrary mathematical problem" process, which is by the way related to finding a suitable nonce for the block.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Proof-of-Stake is far more efficient than PoW as it does not require any energy intensive computer hardware, and does not require any complex cryptographic mathematical problems to be solved to compl
`does not require any complex cryptographic mathematical problems to be solved to complete the mining process`
Maybe a word of caution here when using the term `any` - A validator in PoS needs to perform atleast *some* cryptographic calculations to 
1. validate the transactions
2. create a block 
3. validate an incoming block

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Alternatively, the nodes that hold the most tokens/assets have the power to validate the transactions, which in turn results in this node receiving a reward, usually in newly minted tokens.
```suggestion
Alternatively, the nodes that hold the most tokens/assets have the power to validate the transactions, which in turn results in this node receiving a reward, usually in the form of newly minted tokens.
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS works in a similar fashion to PoS, however, one of the key advantages is that it utilizes a delegation and voting mechanism, which in turn incentives the users to use their staked collateral to
```suggestion
DPoS works in a similar fashion to PoS, however, one of the key advantages is that it utilizes a delegation and voting mechanism, which in turn incentivizes the users to use their staked collateral to secure the network.
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Safety: If 2 conflicting blocks occur on the network, then assuming two-thirds of the active delegates adhere honestly to the protocol, then these 2 conflicting blocks will not be finalized on the
```suggestion
* Safety: If 2 conflicting blocks occur on the network, then assuming two-thirds of the active delegates adhere honestly to the protocol, these 2 conflicting blocks will not be finalized simultaneously on the blockchain.
```
One of them may still be finalized.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The process of being able to tolerate a number of Byzantine process failures or crashes, whilst ensuring the network continues to function is defined as Byzantine-fault-tolerant.
```suggestion
The process of being able to tolerate a number of Byzantine process failures or crashes, whilst ensuring the network continues to function is defined as Byzantine fault tolerance.
```
I think:
Process is tolerance. System is tolerant.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +1. Termination: An output is decided by every non-faulty process.
`An output is decided`
It's a bit difficult to follow this, can you please rephrase ? Same for the statement below.
For eg. `An outcome is observed from every non-faulty process.`

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +By its very nature, a P2P decentralized system offers a high level of security and does not require any third-party intermediaries, and in addition, assets cannot be frozen or manipulated by any enti
`a P2P decentralized system offers a high level of security`
security against what ?

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, being able to store and protect large amounts of transactions, and provide protection from hackers or malicious actors are considered highly advantageous.
```suggestion
Furthermore, being able to store and protect large amounts of transactions, and provide protection from hackers or malicious actors is considered highly advantageous.
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Symmetric Key
```suggestion
=== Symmetric Key Encryption
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Asymmetric Key
```suggestion
=== Asymmetric Key Encryption
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Examples of some of the most widely used symmetric encryption are AES, Blowfish, and RC6.
```suggestion
Examples of some of the most widely used symmetric encryption algorithms are AES, Blowfish, and RC6.
```

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Subsequently, the public key is used for identity management and the account address, and the secret key is used for the passphrase of the user account to access the address, and hence be able to aut
`secret key is used for the passphrase of the user account to access the address`
Not sure what it means. Secret key is *derived* from a passphrase (not used for). Also `access the address` could be rephrased eg. `access the funds in the account associated with the address`

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, {url_hashing}[hashing^] does not only provide the required security, as described earlier on the previous page, it is also deterministic and has the ability to provide immutability as well
`provide the required security`
security against what ?

`has the ability to provide immutability`
what do you mean by this ? Is the input plain text mutable ? 

Probably what you want/need to mention is that hash function outputs can be used to efficiently verify the inputs without revealing the input itself.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, a state in this case, refers to the current state of the blockchain system and its transactions that are responsible for triggering state transitions.
```suggestion
Hence, a state in this case, refers to the current state of the blockchain system and the transactions are a way to transition from one state to another
```
Transactions itself are not part of the state.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
`a block without any transactions inside may alter the state of the blockchain as well`
Assuming this docs is intended for v5, technically speaking, each block header has a property called `stateRoot` which represents the root of the Merkle Tree encapsulating all the current information of accounts, chain & consensus at that particular moment (when the block is produced). This property is what we call the `state`. Currently the only way to alter this property(via altering individual account information) *externally* is via transactions (also cross chain messages in v6 which again need a transaction to be created). Although with a new block some of these properties can change internally, like `generator account balance` (due to block reward) or the account state,  `block headers of last 3 rounds` or the chain state, `finalized block height` or consensus state. Hence effectively the `stateRoot` changes even though there is no external input to the system. Or in other terms, a blockchain would continue to grow even without external intervention with the passage of time.

`From my understanding, any given block cannot be altered retroactively without altering all subsequent blocks`
This is true, however for the reasons I explained above each new block will have a different `stateRoot` compared to any previous block and hence it alters the previous state of the blockchain just because it comes into existence.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, it maintains a temporary state that exists during the processing of a block, as it exposes an interface that enables and results in the finalization of the snapshots.
`finalization of the snapshots`
which snapshot ?

I think this statement as a whole is not clear and needs to explain the process & terms or otherwise to be excluded altogether.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, it is best thought of as a temporary data structure that holds a temporary state while processing a block.
I am not sure what is it referring here but `state transition` is not a data structure. I'd say it is a reference to the process of going from 1 state to another via transactions.

2022-07-08 16:26 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +From a high-level perspective, the state store can be broken down into 3 separate states, namely the Accounts, the Chain, and the Consensus.
`state store`
Again, too many abstract terms are being introduced here which can be confusing/intimidating for inexperienced readers. Either need to be elaborated or omitted imo.

2022-07-11 07:17 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Once a block of data is added to the blockchain it will remain publicly viewable to anyone at any time.
Good point, I have added this in.  👍

2022-07-11 07:22 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This is a highly beneficial system as it enables permanent records to be kept, enabling the storage of almost any type of record.
Yes, this is true. However, I didn't really want to go into too much depth on this, although this is a valid point, so I reworded this sentence so that It reads " 'in general', it enables permanent records to be kept" 👍

2022-07-11 07:58 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Decentralization – The contents of each block in the blockchain can be accessed by any node on the network, as they are essentially network copies that are present on all participating nodes.
OK, I have reworded this paragraph to state the following:
 ''Decentralization -  This can be defined as storing the blocks over a network of nodes, and not in any one central location. The contents of each block in a public blockchain can be accessed by any node on the network, as they are essentially network copies that are present on all participating nodes.
Therefore, there is no central entity that holds each block in the chain, so this results in decentralization."

2022-07-11 08:39 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, there is no central entity that holds each block in the chain, so this creates decentralization.
Yes, good point. I have adapted the last sentence to reflect this point "Therefore, there is no central entity that holds any control to change each block in the chain, so this results in decentralization".

2022-07-11 08:42 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Transparency – A blockchain by its very nature provides total open transparency.
I have now stated that this statement refers to public blockchains.

2022-07-11 08:47 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Proof-of-Stake is far more efficient than PoW as it does not require any energy intensive computer hardware, and does not require any complex cryptographic mathematical problems to be solved to compl
Yes, good point. From my understanding with PoS, it requires less complexity, so I have reworded it to the following:
''....and does not require 'such' complex cryptographic mathematical problems to be solved to complete the mining process.

2022-07-11 08:57 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Subsequently, the public key is used for identity management and the account address, and the secret key is used for the passphrase of the user account to access the address, and hence be able to aut
Good point.  I have updated this paragraph to reflect this accordingly.

2022-07-11 09:19 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, there is no central entity that holds each block in the chain, so this creates decentralization.
Re adapted this to read "Therefore, there is no central entity that holds any control to change the rules of the chain, so this results in decentralization".

2022-07-11 09:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Immutability – A blockchain can be considered a permanent, unchangeable, and irreversible record of transactions.
Updated to Immutability – A blockchain can be considered an unchangeable, and irreversible record of transactions.

2022-07-11 09:23 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +It is also effective for crypto mining, minting new tokens, and validating transactions.
Updated to ''It is also effective for minting new tokens, and validating transactions''.

2022-07-11 09:33 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +By its very nature, a P2P decentralized system offers a high level of security and does not require any third-party intermediaries, and in addition, assets cannot be frozen or manipulated by any enti
Reworded to 'By its very nature, in a P2P decentralized system, assets cannot be frozen or manipulated by a centralized entity'.

2022-07-11 09:43 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, {url_hashing}[hashing^] does not only provide the required security, as described earlier on the previous page, it is also deterministic and has the ability to provide immutability as well
Therefore, {url_hashing}[hashing^] hash function outputs can be used to efficiently to verify the inputs without revealing the input itself., as described earlier on the previous page, it is also deterministic and is the key component in providing immutability of the blockchain data as well, which as we have learned is highly beneficial.

2022-07-11 09:45 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, it maintains a temporary state that exists during the processing of a block, as it exposes an interface that enables and results in the finalization of the snapshots.
Agreed, I have removed this part of the sentence.
Furthermore, it maintains a temporary state that exists during the processing of a block.

2022-07-11 09:49 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +From a high-level perspective, the state store can be broken down into 3 separate states, namely the Accounts, the Chain, and the Consensus.
Agreed , so have removed line 242

2022-07-11 10:03 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
Good point, I have now updated this 👍

2022-07-11 10:09 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Decentralization – The contents of each block in the blockchain can be accessed by any node on the network, as they are essentially network copies that are present on all participating nodes.
A minor update  to the last sentence: 'Therefore, there is no central entity that holds any control to change each block in the chain, so this results in decentralization'.

2022-07-11 11:00 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +1. Termination: An output is decided by every non-faulty process.
Now updated 👍

2022-07-11 11:29 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, it is best thought of as a temporary data structure that holds a temporary state while processing a block.
Good point...now reworded.

2022-07-11 11:41 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This is a highly beneficial system as it enables permanent records to be kept, enabling the storage of almost any type of record.
I have also updated this further in a bit more detail.

2022-07-11 14:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
Just for clarification, I think this introduction is already for v6, or am I missing something?

2022-07-14 10:57 UTC, Tschakki requested changes

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Once a block of data is added to the blockchain it will remain publicly viewable to anyone at any time, assuming it is not a permissioned or private blockchain.
Please add a section explaining differences and use cases of private and public blockchains

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +It is also effective for minting new tokens and validating transactions.
Please add descriptions/ resources to prove this claim to the reader.
Why is PoW here better than the others consensus algorithms?

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In addition, it can be vulnerable to malicious attacks (e.g. the well known 51% attack).
Please add descriptions/ resources to prove this claim to the reader.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Proof of Work is probably the most well-known and established consensus mechanism, as it is utilized by Bitcoin.
This paragraph with definition of PoW should come before you discuss advantages / disadavantages, right under the image of PoW

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, when compared to the other consensus mechanisms, it is somewhat inefficient as it requires a high amount of energy and processing power which is often attributable to the degree of competiti
This should be discussed in disadvantages, not here

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The term 'Proof of Work' stems from how the crypto minors effectively 'prove' that they have accomplished the necessary tasks in order to create a correctly formed block of transactions that will be
```suggestion
The term 'Proof of Work' stems from how the crypto miners effectively 'prove' that they have accomplished the necessary tasks in order to create a correctly formed block of transactions that will be added to the blockchain.
```

What are `miners`? Please explain here, maybe by referring to the PoW diagram.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In addition, PoS is more energy efficient than PoW, which requires miners to use a high level of electricity to complete their tasks.
```suggestion
In addition, PoS is more energy efficient than PoW, which means new blocks can be added to the chain with nearly no effort / energy required.
```

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, it allows the users to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly min
Again, move the description directly below the image

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, it allows the users to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly min
Also, I wouldn't say PoS "allows" to stake tokens, as every blockchain allows to store tokens in a user account, it is a basic feature

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Staking is defined as a number of tokens/assets that are held by the node.
```suggestion
Staking is defined as a number of tokens/assets that are held by the user.
```

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The DPoS mechanism possesses an open and transparent voting system, and furthermore provides faster transaction processing times than PoW and PoS.
Do you have a claim to prove this? Please add the related ressources / explanations here.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Finally, it is energy efficient and requires less computing power and cumbersome hardware.
How does the energy-efficiency compare to PoW/PoS?

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, it can be vulnerable to attacks as often there are only minimal participants in charge of keeping the network functional.
Please explain the disadvantages in more detail, e.g. why is DPoS partially centralized?

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS works in a similar fashion to PoS, however, one of the key advantages is that it utilizes a delegation and voting mechanism, which in turn incentivizes the users to use their staked collateral t
```suggestion
DPoS works in a similar fashion to PoS, however, one of the key differences is that it utilizes a delegation and voting mechanism, which in turn incentivizes the users to use their staked collateral to secure the network.
```

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Ultimately, the DPoS is considered the most advantageous mechanism here, as it was designed to negate most of the limitations that exist with PoW and PoS.
Can you provide proof for this statement?

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This consensus algorithm used in DPoS utilizes a unique election system that is able to select nodes that can perform block verification.
```suggestion
DPoS utilizes a unique election system that is able to select users that can perform block verification.
```

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In this system, generally delegates are voted in based on their reputation.
What are delegates in DPoS context? How can you become a delegate? Please explain, when introducing this new term to the reader. You can make important terms in the text also bold to highlight them to the reader. The first time you mention `delegate`, it should be bold, and it should be followed by an explanation f the term.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Each user who holds a minimum of one token/coin with the DPoS blockchain has the ability to vote specifically for the nodes that they want to perform the transaction validations.
```suggestion
Each user who holds a minimum of one token/coin with the DPoS blockchain has the ability to vote specifically for the delegates that they want to perform the transaction validations.
```

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +*Delegated-Proof-of-Stake* is the consensus mechanism used by Lisk, and hence every Lisk token holder is able to vote for delegates, and dependent on these votes, certain delegates are allowed to add
```suggestion
Dependent on these votes, certain delegates are allowed to add blocks to the blockchain in a specific order.
```

Don't mix Lisks solution with the general explanation of DPoS here. If you want you can add a separate sentence `*Delegated-Proof-of-Stake* is the consensus mechanism used on the Lisk Mainchain.` at the end of the DPoS explanation.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The delegates are actually normal Lisk accounts that have performed a delegate registration transaction.
Again, don't talk about the Lisk solution here, just explain general DPoS
e.g.
```suggestion
Every user account can register as delegate by spending a certain amount of tokens.
```

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, with this stake-weighted {url_voting-mechanism}[voting mechanism^] DPoS has the advantage of being able to execute transactions and verifications much faster than PoS or PoW, as there ar
Do you have a proof for this? Please link/explain here. Also, this could be moved under the advantages section for DPoS

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, although they are considered to be more efficient, they can be considered somewhat centralized.
Why are you explaining these 2 different P2P network types here? What is the connection to blockchain? Please provide more context here for the reader.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, this can be transmitted over an unsecured medium, as regardless of any third party or malicious actors intercepting this, they would not be able to decrypt the text, rendering it useless t
I wouldn't explain it here, as this can be explained in the section about asymmetric encryption. Can be removed

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +For example, When creating a wallet on a blockchain, a public-secret key pair will be generated.
Here you talk only about asymmetric encryption. Where are the other encryptions used and why?

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, transactions can be authenticated without having to reveal the identity of the account owner.
Is the identity of the transaction sender not always transparant/public?

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As discussed, the encryption techniques play an important role here, as it is critical for a blockchain to use the most secure methodology, which ensures the key functions can be securely managed, su
I think it would be great to structure this information better for the reader, not having only big chunks of text to digest. The main information the reader want to get here is

- what are the different encryption methods
- where are they used in blockchain context, followed by a simple example

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Hash Functions
What are the main benefits & characteristics of hashing?

Why is it important in blockchain context? Please explain and provide examples.

2022-07-14 10:57 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Lisk maintains a cryptography package that contains all the cryptographic functionalities required when interacting with the Lisk ecosystem and can be used on both the server and client-side.
Not sure if we should mention it here, but if, add a link to the package reference

2022-07-14 16:37 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Once a block of data is added to the blockchain it will remain publicly viewable to anyone at any time, assuming it is not a permissioned or private blockchain.
Done. I also included permissioned blockchains and links 👍

2022-07-14 16:55 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +It is also effective for minting new tokens and validating transactions.
OK, I have added more content to cover this in more detail. There is a link for a more in-depth explanation of PoW at the end of this section 👍

2022-07-14 17:34 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In addition, it can be vulnerable to malicious attacks (e.g. the well known 51% attack).
Done 👍

2022-07-14 17:34 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Proof of Work is probably the most well-known and established consensus mechanism, as it is utilized by Bitcoin.
Ah yes...good point, and well spotted Mona! 👍

2022-07-14 17:45 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, when compared to the other consensus mechanisms, it is somewhat inefficient as it requires a high amount of energy and processing power which is often attributable to the degree of competiti
Now moved, and updated accordingly 👍

2022-07-14 17:56 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, it allows the users to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly min
Done, and reworded accordingly 👍

2022-07-15 03:53 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This consensus algorithm used in DPoS utilizes a unique election system that is able to select nodes that can perform block verification.
Users(validators) perform block verification via nodes so probably the original fits better.

2022-07-15 03:59 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, transactions can be authenticated without having to reveal the identity of the account owner.
good point

2022-07-15 07:25 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The DPoS mechanism possesses an open and transparent voting system, and furthermore provides faster transaction processing times than PoW and PoS.
Added more content and a link to substantiate this 👍

2022-07-15 08:15 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Finally, it is energy efficient and requires less computing power and cumbersome hardware.
This is covered in the new link I added in the preceding paragraph which gives the reader the opportunity to read about DPoS in much more depth.

2022-07-15 09:05 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, it can be vulnerable to attacks as often there are only minimal participants in charge of keeping the network functional.
I have added a bit more content here 👍

2022-07-15 10:03 UTC, Incede commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
I noticed the terms `account state` `chain state` & `consensus state` being used which are only valid for v5, hence my assumption. If it's intended for v6 please remove these terms & related content or update them with v6 parameters. 

In any case, the fact that a new block always changes the state is still valid.

2022-07-15 11:19 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Ultimately, the DPoS is considered the most advantageous mechanism here, as it was designed to negate most of the limitations that exist with PoW and PoS.
Yes, maybe this statement about it being designed to negate the limitations could be misconstrued, so I have reworded it to cover these points 👍

2022-07-15 13:34 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In this system, generally delegates are voted in based on their reputation.
Good point...I have added in more content to cover this 👍

2022-07-15 13:43 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, with this stake-weighted {url_voting-mechanism}[voting mechanism^] DPoS has the advantage of being able to execute transactions and verifications much faster than PoS or PoW, as there ar
Done and link included 👍

2022-07-15 13:57 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, although they are considered to be more efficient, they can be considered somewhat centralized.
Yes, good point. I don't think we need to delve into the types of p2p networks here, so I have removed them 👍

2022-07-15 14:01 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, this can be transmitted over an unsecured medium, as regardless of any third party or malicious actors intercepting this, they would not be able to decrypt the text, rendering it useless t
Good point ..Done 👍

2022-07-15 14:13 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +For example, When creating a wallet on a blockchain, a public-secret key pair will be generated.
Done 👍

2022-07-15 14:45 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, transactions can be authenticated without having to reveal the identity of the account owner.
Have reworded this to make it a bit clearer 👍

2022-07-15 15:38 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Hash Functions
Reworded above, and added in more content to cover hashing. 👍

2022-07-15 16:08 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Lisk maintains a cryptography package that contains all the cryptographic functionalities required when interacting with the Lisk ecosystem and can be used on both the server and client-side.
I think it's good to mention this, and have added a link as requested 👍

2022-07-15 16:43 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
I have left them as they are for the moment, as if I am correct they are not all agreed and accepted as of yet? 
I saw there was a Trello card on V6 terminologies with a meeting scheduled for 22 July.

2022-07-19 15:18 UTC, Tschakki requested changes
Please see my remarks regarding the PoW advantages/disadvantages, and apply it for the PoS and DPoS sections in the same way, thanks!

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Once a block of data is added to the blockchain it will remain publicly viewable to anyone at any time, assuming it is not a permissioned or private blockchain.
```suggestion
Once a block of data is added to the blockchain it will remain publicly viewable to anyone at any time, assuming it is a <<public-private-and-permissioned-blockchains, public blockchain>>.
```

Add link to explanation of public blockchains

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To start to break down how the blockchain works, and before we delve into the detailed contents of a block, firstly we need to understand how the blocks are linked together, this is accomplished by u
```suggestion
To start to break down how the blockchain works, and before we delve into the detailed contents of a block, firstly we need to understand how the blocks are linked together, this is accomplished by using <<cryptography>>.
```

Add link to cryptography explanations

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, each block contains a cryptographic hash of the previous block, the transaction data,  and a timestamp.
```suggestion
Therefore, each block contains a cryptographic <<hash-functions,hash>> of the previous block, and its included transaction data.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Public, private, and permissioned blockchains
I think it would be better to structure the content a little bit more, to make it easier to digest and pull the most important information out quick.

Maybe work with tables, checklists or other elements to structure text here.

It would be great if it is easy to compare the following:

- definition
- use cases
- example blockchains

and maybe also:

- advantages
- disadvantages

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Consensus Driven – A consensus model independently verifies each block on the blockchain, and provides certain rules for validating a block, which may utilize key resources such as computing power,
`which may utilize key resources such as computing power, in order to demonstrate that this has been accomplished` - what exactly are you referring to in this sentence? It is not clear to me what is explained here

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Consensus Driven – A consensus model independently verifies each block on the blockchain, and provides certain rules for validating a block, which may utilize key resources such as computing power,
```suggestion
* Consensus Driven – A consensus model decides who is allowed to add a new block to the blockchain.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, once a block is finalized and added to the blockchain it ensures any transaction in that block is completely trustable.
Are we explaining anywhere, what is means, if a `block is finalized`?

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Immutability – A blockchain can be considered as an unchangeable and irreversible record of transactions.
```suggestion
* Immutability – A blockchain can be considered as an *unchangeable and irreversible record of transactions*.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Therefore, another highly beneficial advantage is that a blockchain creates provenance, as all transactions can be easily audited from the first to the last entry.
```suggestion
Therefore, another highly beneficial advantage is that a blockchain creates **provenance**, as all transactions can be easily audited from the first to the last entry.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Decentralization – This can be defined as storing the blocks over a network of nodes, and not in any one central location.
```suggestion
* Decentralization – This can be defined as storing the blocks over a **P2P network** of nodes, and not in any one central location.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Public, private, and permissioned blockchains
Also, please move this section below `Key characteristics of blockchain` section

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +
```suggestion
[TIP]
====
A very educational video, including a live demo that can be tried out directly in the browser, is the *Blockchain 101 Demo* by Anders Brownworth: https://andersbrownworth.com/blockchain/[^]
====
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The block containing this data is then distributed to all the nodes within the network.
This is done by the network layer, so I wouldn't explain it here.

Maybe just remove this sentence.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Various consensus mechanisms exist today, however, the 4 main mechanisms that are widely used consist of the *Proof-of-Work*, *Proof-of-Stake*, *Delegated-Proof-of-Stake*, and *Byzantine-Fault-Tolera
Add here direct links to the sections below, where the corresponding mechanism is explained.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* What are the advantages of PoW?
```suggestion
==== Advantages of PoW
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The major advantage regarding Proof-of-Work is that it is highly scalable, and generally very reliable.
This should be more structured, for example a check list, each item on the list one particular advantage, e.g.

- **highly scalable**: explanation why it is highly scalable
- **very reliable**: description why it is more reliable than other consensus algorithms

etc.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The major advantage regarding Proof-of-Work is that it is highly scalable, and generally very reliable.
Same goes for the disadvantages sections of this and the other consensus algorithms

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In essence, this can be thought of as a competition whereby the miners are attempting to outdo each other and solve the complex mathematical equations, which in turn then allows them to add the next
```suggestion
As shown in the image above, this can be thought of as a competition whereby the miners are attempting to outdo each other by using a significant amount of energy to mine a block. In reality, this is achieved by solving complex mathematical equations which are only solvable by a try-and-error approach, which in turn then allows them to add the next block to the blockchain.
```

Refer to the image in the description of PoW

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +It is also effective for minting new tokens and validating transactions.
For me it is still not clear why PoW is better in this regards compared to the other consensus algorithms. Please also see my remarks above concerning improvements of this section.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/pos-v3.png[ align="center" ,600]
Image is not shown on docs page, please fix

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, users are able to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly minted t
I am not sure if people need to actively stake their tokens on PoS, isn't it enough to have the tokens in the wallet?

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, users are able to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly minted t
```suggestion
To explain PoS briefly, users are able to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block.
```

` which then allows transaction fees, and/or newly minted tokens to be collected from the block as a reward.` - this is actually something that is true for every consensus algorithm, so it should be explained under the `Consensus mechanism` section

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Staking is defined as a number of tokens/assets that are held by the node.
```suggestion

NOTE: Staking is defined as a number of tokens/assets that are held by an account.

```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The proof-of-stake-mechanism uses an algorithm designed to select users that have the highest stakes as validators, this results in motivating the highest stakeholders to ensure a transaction is exec
```suggestion
The proof-of-stake-mechanism uses an algorithm designed to select users that have the highest stakes as validators.
The highest stakeholders are expected to have a high motivation to keep the network secure and healthy, as users with the highest amount of tokens or coins have the most to lose, if something goes wrong in the network.
Therefore it is in their interest to ensure the network continues to grow.
The PoS algorithm therefore favors users with high amounts of tokens and provides them with a much higher chance to be selected as the next validator, in relation to users with a smaller stake of tokens.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Key characteristics of blockchain
Somewhere on this page, or maybe even already on the "What is blockchain?" page, we should give an introduction to the main terminology that we use when talking about blockchain. 

One example is the term "validators", which we start using in the PoS description, without explaining before, what it means. 

There are probably a couple of other terminologies, which we should explain before as well to the reader.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In addition, it can be vulnerable to malicious attacks (e.g. the well known 51% attack).
I see you added an explanation of the attack, but I was more asking to explain, why you claim that PoW is more vulnerable to this attack than the other algorithms.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Alternatively, the nodes that hold the most tokens/assets have the power to validate the transactions, which in turn results in this node receiving a reward, usually in the form of newly minted token
Would remove this sentence

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, it allows the users to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly min
I think this whole paragraph is duplicated, please remove

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS works in a similar fashion to PoS, however, one of the key differences is that it utilizes a delegation and voting mechanism, which in turn incentivizes the users to use their staked collateral
```suggestion
DPoS works in a similar fashion to PoS, however, one of the key differences is that it utilizes a **delegation and voting mechanism**, where users to use their staked collateral to vote for validators, who are called *delegates* in DPoS.
Every user account can register as delegate by spending a certain amount of tokens.
A predefined number of delegates with the most votes is allowed to add new blocks to the blockchain in turns.
A delegate who has enough votes to be allowed to forge is called **active delegate**.
The forging process is divided in **forging rounds**. 
A forging round lasts until every active delegate has forged exactly one block.
After each forging round, the list of active delegates is calculated newly based on their current number of votes.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS is generally considered to be the most advantageous mechanism, as it negates most of the limitations that exist with PoW and PoS as previously described.
This statement is quite bold and we should check that after working on the advantages/disadvantages sections, this still holds true.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In this system, generally users, or as they are known in PoS and DPoS, *delegates* are voted in based on their reputation.
```suggestion
In this system, generally delegates are voted in based on their reputation or (financial) incentives that they offer for their voters.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Delegates can also be thought of as witnesses or users producing blocks.
Can be removed, as already stated in a comment above, we should explain the term `validators` already before the consensus section.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In this system, generally users, or as they are known in PoS and DPoS, *delegates* are voted in based on their reputation.
The term `delegate` should be explained before using the term for the first time.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS utilizes a unique election system that is able to select users that can perform block verification.
Remove this line

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Every user account can register as delegate by spending a certain amount of tokens.
Please remove, I added new description above

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In a nutshell, the BFT mechanism ensures that the same guaranteed data is received by every node present in the network.
```suggestion
In a nutshell, the BFT mechanism ensures that the same consistent data is received by every node present in the network at any time.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In essence, it allows consensus to be reached regardless if some of the nodes fail.
This can be removed, it is already mentioned before.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Safety: If 2 conflicting blocks occur on the network, then assuming two-thirds of the active delegates adhere honestly to the protocol, these 2 conflicting blocks will not be finalized simultaneous
```suggestion
* **Safety**: If 2 conflicting blocks occur on the network, then assuming two-thirds of the active delegates adhere honestly to the protocol, these 2 conflicting blocks will not be finalized simultaneously on the blockchain.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Accountability: In the case whereby the protocol is violated by the delegate, they will be held responsible for this.
```suggestion
* **Accountability**: In the case whereby the protocol is violated by the delegate, they will be held responsible for this.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Liveness: New blocks can still be finalized on the network, even in the case whereby one third of the active delegates are offline.
```suggestion
* **Liveness**: New blocks can still be finalized on the network, even in the case whereby one third of the active delegates are offline.
```

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The process of being able to tolerate a number of Byzantine process failures or crashes, whilst ensuring the network continues to function is defined as Byzantine fault tolerance.
Can be removed, already explained above.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Peer-2-Peer networks
Not sure what is the purpose of this section. What do we want to explain here, also compared to the section `decentralization` of the "What is blockchain?" page?

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This can be accomplished by using an encryption mechanism as depicted in the example diagram below, whereby a plain text document is sent as a ciphered version to the recipient.
What diagram? I think the whole sentence can be removed

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +These can be broken down into the following three types:
These sections do not answer where which type of cryptography is used in particular. Please make sure to include this information, and please try to highlight on this information, so that it is not part of one big text block, which makes it hard to find.

Where exactly which cryptography is used and why this is used here, is the most interesting part about the whole topic, so this information should be transmitted to the reader as clearly as possible.

It is less important to explain the mechanism themselves in much detail, because there are a lot of great online resources that we can link to, if people are unaware of it.

2022-07-19 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Finally, this is explained in more depth in the xref:{state_store}[Modules and Assets] page covering the state store changes and execution logic.
Should be removed, refers to v5

2022-08-01 09:05 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +* Consensus Driven – A consensus model independently verifies each block on the blockchain, and provides certain rules for validating a block, which may utilize key resources such as computing power,
Good point, I have removed this 👍

2022-08-01 09:31 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Hence, once a block is finalized and added to the blockchain it ensures any transaction in that block is completely trustable.
Good point, added in a brief explanation 👍

2022-08-01 09:46 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Public, private, and permissioned blockchains
Done 👍

2022-08-01 11:56 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The block containing this data is then distributed to all the nodes within the network.
Fair point...now done 👍

2022-08-01 12:08 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Various consensus mechanisms exist today, however, the 4 main mechanisms that are widely used consist of the *Proof-of-Work*, *Proof-of-Stake*, *Delegated-Proof-of-Stake*, and *Byzantine-Fault-Tolera
Done 👍

2022-08-01 17:13 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The major advantage regarding Proof-of-Work is that it is highly scalable, and generally very reliable.
I have now updated all the consensus mechanism sections to contain bullet point lists of the advantages and disadvantages.

2022-08-01 17:20 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/pos-v3.png[ align="center" ,600]
This has been updated. The image works for me, however, I have reinserted it again.

2022-08-01 17:26 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, users are able to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly minted t
From my understanding, any tokens that are just held in a wallet, are not actually staked tokens..You have to actively stake them to reap any rewards.

2022-08-02 07:08 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Key characteristics of blockchain
I have added an explanation for Validators, although it seems we have covered the explanations of other terminologies, and as you mentioned also on the previous 'What is blockchain' page.

2022-08-02 11:54 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Alternatively, the nodes that hold the most tokens/assets have the power to validate the transactions, which in turn results in this node receiving a reward, usually in the form of newly minted token
I have reworded the part on 51% attacks. 
I also removed the sentence above 👍

2022-08-02 11:56 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +To explain PoS briefly, it allows the users to stake an asset/token which in turn opens up the possibility to be chosen as a validator of a new block, which then allows transaction fees, or newly min
Yes, I noticed this and removed it earlier 👍

2022-08-02 12:09 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS is generally considered to be the most advantageous mechanism, as it negates most of the limitations that exist with PoW and PoS as previously described.
Well, we now list the highest amount of advantages when using the DPOS mechanism as compared to PoW & PoS 👍

2022-08-02 12:11 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In this system, generally users, or as they are known in PoS and DPoS, *delegates* are voted in based on their reputation.
Yes, it is now 👍

2022-08-02 12:20 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Delegates can also be thought of as witnesses or users producing blocks.
I have removed this line. In addition, I have added an explanation to explain what validators are, before any description of any process is described which pertains to validators. 👍

2022-08-02 12:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +DPoS utilizes a unique election system that is able to select users that can perform block verification.
Done 👍

2022-08-02 12:24 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Every user account can register as delegate by spending a certain amount of tokens.
Am not clear on this one.. Do you mean to remove this entire paragraph?

2022-08-02 12:31 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In essence, it allows consensus to be reached regardless if some of the nodes fail.
Maybe I am missing something, but I cannot see where this is duplicated?

2022-08-02 12:38 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +The process of being able to tolerate a number of Byzantine process failures or crashes, whilst ensuring the network continues to function is defined as Byzantine fault tolerance.
Done 👍

2022-08-02 12:42 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Peer-2-Peer networks
Yes, that is a fair point. Although it just highlights that P2P is a decentralized system and beneficial for blockchain usage..We can remove it if you wish, or alternatively, I could add it in to bolster the Decentralization paragraph on the 'What is blockchain' page...What do you think Mona..?

2022-08-02 12:44 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +This can be accomplished by using an encryption mechanism as depicted in the example diagram below, whereby a plain text document is sent as a ciphered version to the recipient.
Yes, fair point. I have removed this sentence 👍

2022-08-02 12:48 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Finally, this is explained in more depth in the xref:{state_store}[Modules and Assets] page covering the state store changes and execution logic.
Done 👍

2022-08-02 16:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Public, private, and permissioned blockchains
I have restructured it somewhat, and also built a table that covers the missing points.

2022-08-02 16:47 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +These can be broken down into the following three types:
I have restructured this to include, 'How', 'Why', and 'Where' it is used. In addition, I have added a link.

2022-08-04 10:36 UTC, Tschakki requested changes
Looking already pretty good, but please see my remaining comments below 🙏

2022-08-04 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In essence, it allows consensus to be reached regardless if some of the nodes fail.
Imho the line `231` just before is stating something similar, isn't it? Also, both sentences try to summarize, indicated by `In a nutshell ...` and `in essence ...` so I would only keep one of them.

2022-08-04 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Peer-2-Peer networks
Yes, sounds good! Let's remove it here for now, and add the missing parts to "What is blockchain?" page 👍

2022-08-04 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +These can be broken down into the following three types described below:
This section seems to be duplicated content with lines 276-280, would remove.

2022-08-04 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, it is important to note that there are two different methods of cryptography algorithms that are deployed within the blockchain, and these are the asymmetric model and the hashing function.
Would remove this line

2022-08-04 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, the hash is irreversible, ensuring it is impossible to generate any message from the message digest.
this paragraph seems to belong to the explanation of hashing below

2022-08-04 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Hash Functions
Please provide a concrete example for hashing in blockchain context. The most prominent example is probably hashing the previous block and adding the hash to the block header of the next block, to ensure immutability

2022-08-04 12:15 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +=== Hash Functions
OK, I have added a bit more content here and had already given examples (Bitcoin and Ethereum) 👍

2022-08-04 12:19 UTC, Incede approved these changes

2022-08-04 12:22 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +In essence, it allows consensus to be reached regardless if some of the nodes fail.
Ah yes...Good point Mona! I have condensed this into one sentence now 👍

2022-08-04 12:24 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +== Peer-2-Peer networks
Excellent! My thoughts exactly...I have now removed it, and will then create an issue later just to add this in to the 'What is blockchain?' page 👍

2022-08-04 12:42 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +These can be broken down into the following three types described below:
Done 👍

2022-08-04 12:45 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +However, it is important to note that there are two different methods of cryptography algorithms that are deployed within the blockchain, and these are the asymmetric model and the hashing function.
Done 👍

2022-08-04 12:46 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Furthermore, the hash is irreversible, ensuring it is impossible to generate any message from the message digest.
Yes indeed you are correct Mona, and I have already moved it now 👍

2022-08-05 12:54 UTC, Tschakki requested changes
I think we are nearly there, just a few comments :)

2022-08-05 12:54 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +image::intro/state-machine.png[]
I agree with @Incede , these terms are only valid for v5, and also they are specific for the Lisk SDK, so I would remove them here.

2022-08-05 12:54 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As described earlier on the previous page, it is also deterministic and is the key component in providing immutability of the blockchain data as well, which as we have learned is highly beneficial.
Please add a link to the previous page. Also, it is better to mention the page name directly, instead of `previous page`

2022-08-05 12:54 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Blockchains are also dependent on hashing, and the well-known SHA-256 (Secure Hash Algorithm), cryptographic hash function is used extensively in blockchain technology, including Bitcoin.
```suggestion
In the context of blockchain, the hashing function properties are used mainly within the consensus and application domains.
A popular use case for hashing in blockchain is to create a hash of the previous block, and to include that hash in the next block.
This way, a block is cryptographically connected to all its former blocks, forming the classical chain of blocks.
Even the smallest change in one of the former blocks would create a very different hash of that particular block, which wouldn't match with the hash in the header of the next block.
This would break the chain of blocks immediately.
Therefore, hashing is an important factor to ensure the *immuability* of the blockchain.
```

2022-08-05 13:52 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As described earlier on the previous page, it is also deterministic and is the key component in providing immutability of the blockchain data as well, which as we have learned is highly beneficial.
Done 👍

2022-08-05 14:36 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +As described earlier on the previous page, it is also deterministic and is the key component in providing immutability of the blockchain data as well, which as we have learned is highly beneficial.
Regarding the v5 terms, I have removed the old 'account store', 'chain state store', and 'consensus store' terms, and just described the general process. Let me know your thoughts if this works, otherwise we could always just remove this paragraph?

2022-08-08 09:58 UTC, Tschakki requested changes
We are nearly there, just a few more comments :)

2022-08-08 09:58 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +
The intro should be the first category in the navigation, please move this up

2022-08-08 09:58 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +:toc: preamble
```suggestion
:toc:
```

2022-08-08 09:58 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Finally, then the validator information, including the finalized block height, and the BFT voting ledger are then complete.
Please remove, as this is Lisk-specific

2022-08-08 17:17 UTC, chris529 commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +Finally, then the validator information, including the finalized block height, and the BFT voting ledger are then complete.
Done 👍

2022-08-08 17:19 UTC, chris529 commented on docs/modules/ROOT/nav.adoc
> +
Done 👍

2022-08-09 15:30 UTC, Tschakki approved these changes
thanks! 🎉

2022-08-09 15:31 UTC, merged