Create Lisk products page in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1483
Opened 2022-06-01 17:09 UTC by chris529

2022-06-16 13:26 UTC, Tschakki requested changes
Always use consecutive headlines in Asciidoc

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:toc: preamble
```suggestion
= Lisk products
Chris Braithwaite <christopher.braithwaite@lightcurve.io> Mona Bärenfänger <mona@lightcurve.io>
:description: The Lisk suite of products and their role in the Lisk ecosystem
:toc: preamble
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Overview
```suggestion
== Overview
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Software Development Kit (SDK)
```suggestion
== Lisk Software Development Kit (SDK)
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Core
```suggestion
== Lisk Core
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Service
```suggestion
== Lisk Service
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Desktop
```suggestion
== Lisk Desktop
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Mobile
```suggestion
== Lisk Mobile
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Improvement Proposals (LIPS)
```suggestion
== Lisk Improvement Proposals (LIPS)
```

2022-06-16 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Faucet
I don't think we should list this here

2022-06-21 09:20 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +=== Lisk Faucet
Good point, I have now removed the Faucet 👍

2022-06-21 15:02 UTC, Tschakki requested changes

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk SDK has been designed and built to provide a user-friendly, open-source software development kit.
Add a link to the Lisk SDK index page

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Core can be defined as the program that actually implements the Lisk protocol.
Add a link to the Lisk Core index page

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Service is a web application that enables interaction with the entire Lisk ecosystem.
Add link to Lisk Service index page

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Desktop is a graphical user interface (GUI), which can be used to perform many useful interactions with the Lisk blockchain network.
Add link to Lisk Desktop page

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Lisk Mobile is an app that can easily be downloaded on both iPhone and Android operating systems and offers LSK token transactions and account balance functionalities.
Add link to Lisk Mobile page

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +== Lisk Improvement Proposals (LIPS)
Add links to the research forum and the LIP repository on GitHub

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_restful_api: {docs-service}pages/api/lisk-service-http.adoc
Please check links, `docs_core` and `docs-service` need to be defined.

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:page-next-title: Blockchain Scalability
```suggestion
```

deprecated

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_restful_api: {docs-service}pages/api/lisk-service-http.adoc
```suggestion
:url_restful_api: api/lisk-service-http.adoc
```

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_microservices: {docs-service}pages/index.adoc#microservices
```suggestion
:url_microservices: lisk-service::index.adoc#microservices
```

this is how you refer to the Lisk Service docs for example

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Core can be defined as the program that actually implements the Lisk protocol.
I think this is now more true for the SDK than for Lisk Core. 

```suggestion
Lisk Core is the blockchain application that is maintaining the **Lisk Mainnet**.
```

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Firstly, the Lisk Core  needs to be installed to enable a node to be run which will then be able to participate in the network
This sentence sounds confusing, what are you trying to say?

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +For every node to function an instance of Lisk Core has to be installed, thus enabling the node to connect, and simultaneously communicate with other nodes residing in the Lisk network.
Explain what a node is and how it participates in the network before this sentence

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Lisk Mobile is an app that can easily be downloaded on both iPhone and Android operating systems and offers LSK token transactions and account balance functionalities.
```suggestion
Lisk Mobile is a digital wallet app to be installed on the smartphone.
It can easily be downloaded on both iPhone and Android operating systems and offers LSK token transactions and account balance functionalities.
```

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Each LIP document allows for open and transparent dialogue on how the Lisk network is further developed, coupled with defining the objectives on the latest version of the roadmap.
dialogue is only happening before a LIP is finalized. Please clarify this here. Would be also a good place to point to the research forum.

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +A Lisk Improvement Proposal (LIP), is a document that forms a proposal system that is usually created and structured by the research team.
```suggestion
LIPs (Lisk Improvements Proposals) are scientific papers, describing a particular part of the Lisk protocol.
```

2022-06-21 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk SDK has been designed and built to provide a user-friendly, open-source software development kit.
The first sentence is a little too general, it should be really on point with describing what the Lisk SDK is.

2022-06-21 15:29 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_microservices: {docs-service}pages/index.adoc#microservices
Thanks Mona 👍

2022-06-21 15:31 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Core can be defined as the program that actually implements the Lisk protocol.
Yes, agreed...It sounds good 👍

2022-06-23 14:08 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The SDK uses the ubiquitous language of Javascript as well as TypeScript and deploys the highly efficient and scalable DPoS consensus mechanism, and also the BFT (Byzantine-Fault-Tolerance), mechanis
```suggestion
The SDK uses the ubiquitous language of Javascript as well as TypeScript and deploys the highly efficient and scalable DPoS consensus mechanism, and also the BFT (Byzantine-Fault-Tolerance) mechanism.
```

2022-06-23 14:08 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Firstly, the Lisk Core  needs to be installed to enable a node to be run which will then be able to participate in the network
```suggestion
Firstly, the Lisk Core needs to be installed to enable a node to be run which will then be able to participate in the network
```

2022-06-24 09:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk SDK has been designed and built to provide a user-friendly, open-source software development kit.
Done 👍

2022-06-24 09:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Core can be defined as the program that actually implements the Lisk protocol.
Done 👍

2022-06-24 09:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Service is a web application that enables interaction with the entire Lisk ecosystem.
Done 👍

2022-06-24 09:23 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk Desktop is a graphical user interface (GUI), which can be used to perform many useful interactions with the Lisk blockchain network.
Done 👍

2022-06-24 09:23 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Lisk Mobile is an app that can easily be downloaded on both iPhone and Android operating systems and offers LSK token transactions and account balance functionalities.
Done 👍

2022-06-24 09:23 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_restful_api: {docs-service}pages/api/lisk-service-http.adoc
Done 👍

2022-06-24 10:11 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +== Lisk Improvement Proposals (LIPS)
Done 👍

2022-06-24 10:25 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Each LIP document allows for open and transparent dialogue on how the Lisk network is further developed, coupled with defining the objectives on the latest version of the roadmap.
Done 👍

2022-06-24 11:57 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Firstly, the Lisk Core  needs to be installed to enable a node to be run which will then be able to participate in the network
I have reworded this section 👍

2022-06-24 11:58 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +For every node to function an instance of Lisk Core has to be installed, thus enabling the node to connect, and simultaneously communicate with other nodes residing in the Lisk network.
Done 👍

2022-06-24 12:16 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +The Lisk SDK has been designed and built to provide a user-friendly, open-source software development kit.
I have amplified on this, and bolstered the description 👍

2022-06-28 14:53 UTC, mitsuaki-u approved these changes
Other than other comments LGTM

2022-07-05 14:22 UTC, Tschakki requested changes
Just a few link corrections, otherwise LGTM

2022-07-05 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_microservices: lisk-service::pages/index.adoc#microservices
```suggestion
:url_microservices: lisk-service::index.adoc#microservices
```

2022-07-05 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:url_restful_api: lisk-service::pages/api/lisk-service-http.adoc
```suggestion
:url_restful_api: api/lisk-service-http.adoc
```

2022-07-05 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +:page-next-title: Blockchain Scalability
```suggestion
```

deprecated attributes

2022-07-05 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +A xref:{url_lips}[Lisk Improvement Proposal] (LIP), is a document that forms a proposal system that is usually created and structured by the research team.
```suggestion
A {url_lips}[Lisk Improvement Proposal^] (LIP), is a document that forms a proposal system that is usually created and structured by the research team.
```

2022-07-05 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Further information can also be found here on the xref:{url_research}[Lisk Research Forum].
```suggestion
Further information can also be found here on the {url_research}[Lisk Research Forum^].
```

2022-07-06 09:22 UTC, Tschakki approved these changes
LGTM

2022-07-06 09:23 UTC, merged