Create blockchain scalability page in Lisk docs - Closes #1478
LiskArchive/lisk-legacy-docs pull request #1486
Opened 2022-07-04 07:53 UTC by chris529

2022-09-13 15:48 UTC, mitsuaki-u reviewed
Initial review

2022-09-13 15:48 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +The advent of blockchain technology has resulted in a wide array of many positive benefits on a global scale, whereby numerous blockchain applications are found in a variety of different industry sec
This sentence feels a bit wordy. Maybe `The advent of blockchain technology has resulted in a wide array of blockchain applications in a variety of different industry sectors worldwide.`

2022-09-13 15:48 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +However, this does not come without its challenges, as the many blockchains continue to grow and expand, coupled with the enormous growth in users, this subsequently results in scalability issues, wh
Same for this sentence. Maybe we can break it down into multiple sentences or trim it down.

2022-09-13 15:48 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +In the blockchain world, this mostly refers to the transaction throughput, bootstrap time, latency, and even the cost of the actual transaction.
`even the cost of the actual transaction.` Maybe we can specify what kind of cost. Like processing, etc.

2022-09-13 15:48 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To compound this further, issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction process to slow d
```suggestion
To compound this further, issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction processing to slow down, and often increases the transaction costs, whilst restricting further users from joining the network.
```

2022-09-13 15:48 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
Maybe we can include a quick explanation of why more nodes => less scalability as that connection is missing.

2022-09-13 15:48 UTC, mitsuaki-u commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +This can be characterized by referring to the blockchain network's ability to handle the continuing growth, ensuring the security is not compromised in any wave, shape, or form, whilst continuing to
```suggestion
This can be characterized by referring to the blockchain network's ability to handle the continuing growth, ensuring the security is not compromised in any way, shape, or form, whilst continuing to maintain the node synchronization, transparency, and fairness together in a fully functional decentralized network.
```

2022-09-15 11:36 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
The first part of this paragraph seems to be a duplication of the previous paragraph

2022-09-15 12:09 UTC, Tschakki requested changes
Please see my comments below.

I think another interesting solution is the re-genesis, would be nice to explain it here as well, imho

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As in all blockchain networks, each transaction has to be validated as described on the ‘how blockchain works’ (add link here) page.
link is missing

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +This can easily result in very high TPS (transactions per second), rates.
shouldn't it result in very low TPS?

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +There are various methods that can be used to address the scalability problem such as layer 1 and layer 2 solutions, scalable consensus methods, and DAGs (Directed Acyclic Graph).
The content of this sections is not really related to blockchain scalability problems, please rewrite or remove it to fit with the coming subsections

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To summarise, DAG’s fundamentally new design concept has the ability to address the scalability issues specifically with regard to large networks that require the transfer of high volume data rates a
This sounds very positive for DAGs. Please also describe, if there are any disadvantages / trade-offs of this approach, and give examples where it is used in reality.

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Plasma has proven abilities in assuring transaction execution is managed efficiently, and also has the added extra bonus of enhanced security.
Can you provide further links / resources about these solutions?

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Plasma has proven abilities in assuring transaction execution is managed efficiently, and also has the added extra bonus of enhanced security.
Also, it sounds very similar to Lisks approach with sidechains, please highlight the differences to the reader

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Sidechains can also utilize different consensus techniques as compared to the mainchain.
Please mention that this is an approach Lisk follows to improve blockchain scalability

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +In such cases, this may result in a subset of the blockchain community electing to make fundamental changes and modifications to the underlying blockchain.
How  do hard forks improve scalability? This section doesn't seem to fit here for me

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +The beauty of this is that to achieve faster and more efficient transaction throughput, there is no need to rely on the performance of individual nodes anymore.
Please provide links for further information about sharding, and also mention example blockchains, where sharding is used.

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Sidechains can also utilize different consensus techniques as compared to the mainchain.
Also, I would consider this solution an on-chain solution

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +The process works whereby when transactions are executed, the mainchain is able to record the end state of the actual channel, together with any other associated transactions.
please add examples and links to further resources

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Basically, DPoS is a very efficient consensus mechanism, whereby transaction validation is actually detached from the power required to run the nodes, therefore increasing the network scalability as
This sentence needs further explanations

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Furthermore, Lisk deploys deterministic block processing which actually results in almost zero variance with high scalability.
what kind of variance are we talking here?

2022-09-15 12:09 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Finally, the advent of sidechains will also have an additional positive effect on scaling for the Lisk ecosystem.
sidechains are actually a crucial part in solving scalability issue, please emphasize it more here

2022-09-15 14:10 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +The advent of blockchain technology has resulted in a wide array of many positive benefits on a global scale, whereby numerous blockchain applications are found in a variety of different industry sec
OK, I have trimmed it down as suggested.. 👍

2022-09-15 14:19 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +However, this does not come without its challenges, as the many blockchains continue to grow and expand, coupled with the enormous growth in users, this subsequently results in scalability issues, wh
Also trimmed down 👍

2022-09-15 15:07 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +In the blockchain world, this mostly refers to the transaction throughput, bootstrap time, latency, and even the cost of the actual transaction.
OK, I have alluded to this and tried to keep it short.. 👍

2022-09-15 15:37 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
Done 👍

2022-09-15 15:43 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
Good point, I have refined it 👍

2022-09-15 15:59 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As in all blockchain networks, each transaction has to be validated as described on the ‘how blockchain works’ (add link here) page.
Well spotted Mona! It is now done 👍

2022-09-15 16:16 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +This can easily result in very high TPS (transactions per second), rates.
Yes, indeed...well spotted Mona! 👍

2022-09-15 16:40 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +There are various methods that can be used to address the scalability problem such as layer 1 and layer 2 solutions, scalable consensus methods, and DAGs (Directed Acyclic Graph).
Hmmm...I'm not 100% with you here Mona...I thought it best to try and explain all possible solutions for increasing scalability, and vertical and horizontal scaling of the nodes is one of the potential solutions that can assist in improving scalability..?  
I have now trimmed it down and made it more basic and high-level. (I have removed the explanations of how it works).
Perhaps it might be better to move this paragraph to the end of the ''Increasing scalability - Solutions'' section...?

2022-09-16 07:16 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To summarise, DAG’s fundamentally new design concept has the ability to address the scalability issues specifically with regard to large networks that require the transfer of high volume data rates a
Done 👍

2022-09-16 09:26 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Plasma has proven abilities in assuring transaction execution is managed efficiently, and also has the added extra bonus of enhanced security.
Done 👍

2022-09-16 09:50 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Sidechains can also utilize different consensus techniques as compared to the mainchain.
Good point...I have now mentioned Lisk..
However, although sidechains are generally considered somewhat of a hybrid of layer 1 and layer 2, if I am correct, therefore it is considered as a sort of independent layer. I mentioned this, as this paragraph is currently located in the ''Layer 2- Solutions - Off-chain'' section, as I think that sidechains should be classed as a layer 2 scaling solution here, as a layer 2 solution takes the interactions off-chain, and then processes them before communicating or sending them back to the main chain..What are your thoughts on this Mona..?

2022-09-16 10:04 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +In such cases, this may result in a subset of the blockchain community electing to make fundamental changes and modifications to the underlying blockchain.
Yes, fair point...Although from my understanding,  hard forking can result in reducing the time required for creating a block, so that in turn can help to improve scalability.
However, I think you are right Mona, this section does n't fit so well, so I have now removed it. 👍

2022-09-16 11:59 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +The beauty of this is that to achieve faster and more efficient transaction throughput, there is no need to rely on the performance of individual nodes anymore.
Done 👍

2022-09-16 12:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +The process works whereby when transactions are executed, the mainchain is able to record the end state of the actual channel, together with any other associated transactions.
Done 👍

2022-09-16 13:22 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Basically, DPoS is a very efficient consensus mechanism, whereby transaction validation is actually detached from the power required to run the nodes, therefore increasing the network scalability as
I have beefed it up, included PoA, and added another link 👍

2022-09-16 13:57 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Furthermore, Lisk deploys deterministic block processing which actually results in almost zero variance with high scalability.
I was alluding to variance in processing times, however, I have removed it, as in hindsight it may not always be the case. 👍

2022-09-16 14:32 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Finally, the advent of sidechains will also have an additional positive effect on scaling for the Lisk ecosystem.
This has now been done in both the 'Sidechain' section and 'Scalability in Lisk' section.

2022-09-21 15:49 UTC, Tschakki requested changes
Looking good!

Please see my remaining comments :)

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
it still sounds duplicated. E.g. the first two sentences are exactly the same.

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Sidechains can also utilize different consensus techniques as compared to the mainchain.
ok, I see, sounds good to me! 👍

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Finally, more detailed information on state channels can be found xref:{url_state_channels}[here].
```suggestion
Finally, more detailed information on state channels can be found {url_state_channels}[here^].
```

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Finally, more detailed information on sharding can be found xref:{url_sharding}[here].
```suggestion
Finally, more detailed information on sharding can be found {url_sharding}[here^].
```

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Additional chains can be created on top of each child chain, resulting in a tree-like structure. As there are 4 main versions of the Plasma model, which results in different variants, the transaction
```suggestion
Additional chains can be created on top of each child chain, resulting in a tree-like structure.
As there are 4 main versions of the Plasma model, which results in different variants, the transaction process is not described in detail in this section, however, more detailed information can be found {url_plasma}[here^].
```

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +There are various methods that can be used to address the scalability problem such as layer 1 and layer 2 solutions, scalable consensus methods, and DAGs (Directed Acyclic Graph).
So first of all, I don't think it is true that more nodes in the network improve scalability. It might improve decentralization of the network, but I don't see how it helps with scaling.

For vertical scaling of nodes, i don't think it is a relevant factor in blockchain networks, and especially with Lisk, one can operate a node on very simple machine, which don't consume much energy.

Thats why I think mentioning these scaling solutions might be more confusing than helping in this context.

2022-09-21 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Furthermore, the transaction can also include cross-chain messages and therefore this acts as an envelope for messages from one chain to another.
Please only explain Lisks solution here, if you are directly comparing it to Plasma. I think for the reader, the connection between this and the previous paragraph is not entirely clear. And we also explain Lisk interoperability on other places, so i think it is better to remove it here.

Maybe just mention shortly the main difference between Plasma childchains and Lisk sidechains here.

2022-09-22 13:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As growth in blockchain networks continues to increase exponentially, this naturally results in an ever-increasing number of nodes within the blockchain networks.
Ah yes, good point Mona.. I have now removed the duplicated sentence 👍

2022-09-22 13:35 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +There are various methods that can be used to address the scalability problem such as layer 1 and layer 2 solutions, scalable consensus methods, and DAGs (Directed Acyclic Graph).
Yes, I see your point here Mona. OK, I have removed this section on vertical and horizontal scaling 👍

2022-09-22 13:59 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Furthermore, the transaction can also include cross-chain messages and therefore this acts as an envelope for messages from one chain to another.
Yes, very good point indeed Mona. You are right, we shouldn't be explaining Lisk interoperability solutions here, as now we explain our interoperability solution in much more detail on a separate page anyway, so I have removed this paragraph. 
In addition, I would rather not make comparisons between (Plasma) child chains and our sidechains here, as there are no comparisons made for all of the other off-chain solutions described in this section. Therefore, I think it's best to keep the basic description of the other solutions as they are 👍

2022-09-27 12:04 UTC, Tschakki requested changes
I found a few points to improve by going over it. 
Please let me know your thoughts! :)

2022-09-27 12:04 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Lisk is currently well-placed in this regard, firstly by its use of the DPoS consensus mechanism as explained in more detail on the xref:{url_blockchain}[What is blockchain] page.
I think the main point that increases scalability is not the consensus algorithms, but the interoperability solution of Lisk, allowing each application to run on their own sidechain. This is one of Lisks main USPs and it should be mentioned and explained here.

2022-09-27 12:04 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +This can easily result in very low TPS (transactions per second), rates.
Maybe add TPS as a separate bottleneck as well here?

I think of it, because Lisk improves TPS by allowing each app to run their own chain, which increases TPS of the whole Lisk ecosystem, even if response times are not decreased.

2022-09-27 12:04 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +== Future of scalability in blockchain
Who is doing the research? Lisk or someone else? Please add sources here, if there are good ones. Otherwise, I would tend to remove this paragraph.

2022-09-27 12:04 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To summarise, running sidechains results in reducing the load on the mainchain, therefore increasing the overall scalability of the network.
You summarize here that sidechains improve scalability, but before you are only talking about consensus algorithms. Please improve the flow of this sections, also see my comment above.

2022-09-27 12:04 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> -** xref:intro/lisk-products.adoc[]
I don' think these pages should be removed form nav

2022-09-28 09:14 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Lisk is currently well-placed in this regard, firstly by its use of the DPoS consensus mechanism as explained in more detail on the xref:{url_blockchain}[What is blockchain] page.
Good point Mona! I have now added this in 👍

2022-09-28 10:01 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +This can easily result in very low TPS (transactions per second), rates.
Yes, a good idea. I have now updated this section, added a TPS paragraph, and alluded to how our interoperability solution improves the TPS 👍

2022-09-28 12:18 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +== Future of scalability in blockchain
imho, I like the idea of ending the page by alluding to the future...So I have restructured this section and added the latest cutting-edge info on a groundbreaking new research project predicted to increase scalability phenomenally, (I also added the relevant links)..Let me know your thoughts Mona 👍

2022-09-28 13:01 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To summarise, running sidechains results in reducing the load on the mainchain, therefore increasing the overall scalability of the network.
Good point Mona. The summary paragraph was missing DPoS and PoA. I have now re-written it to summarise and reflect the contents of this section 👍

2022-09-28 13:20 UTC, chris529 commented on docs/modules/ROOT/nav.adoc
> -** xref:intro/lisk-products.adoc[]
Ah yes indeed..I have re-inserted them 👍

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To compound this further, issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction processing to slo
`To compound this further, issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction processing to slow down, and often increases the transaction costs, whilst restricting further users from joining the network.`

I suggest breaking this sentence into two sentences and making it more clear.

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +If we compare this to the well-known Visa card processing system, the number of transactions processed every second is around 17,000.
This looks very similar to lines 41-44 and 53, so it can possibly omitted to avoid repetition.

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Starting from the genesis block to the latest block and transactions consists of a large quantity of data, so it has to be taken into consideration that each network node does not possess adequate re
`Starting from the genesis block to the latest block and transactions consists of a large quantity of data, so it has to be taken into consideration that each network node does not possess adequate resources for the storage of such high volumes of data` is unclear and generally repeats the meaning of the previous sentence. Please consider omitting it or rewriting it for better clarity.

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +However, limiting the block size results in reducing the transaction speed, as if a low limit is used then that transaction can be stored in the block, and subsequently will have to wait to generate
`However, limiting the block size results in reducing the transaction speed, as if a low limit is used then that transaction can be stored in the block, and subsequently will have to wait to generate a new block.` 

Please consider rewriting this sentence to improve clarity.

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As the blockchain grows and more and more transactions are processed, with increasing block sizes this is the crux of the issue, as there is an inherent danger of overloading the network, coupled wit
`As the blockchain grows and more and more transactions are processed, with increasing block sizes this is the crux of the issue, as there is an inherent danger of overloading the network, coupled with the existing hardware limitations being utilized by many of the nodes, whereby they are simply unable to handle the vast quantities of data and bandwidth requirements.`

Please consider rewriting this sentence to improve clarity, or possibly breaking it in two shorter sentences.

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Basically, DPoS is a very efficient consensus mechanism, whereby transaction validation is actually detached from the power required to run the nodes, therefore increasing the network scalability as
`Secondly, scalability is further increased by the use of the DPoS consensus mechanism as explained in more detail on the xref:{url_blockchain}[What is blockchain] page.
Basically, DPoS is a very efficient consensus mechanism, whereby transaction validation is actually detached from the power required to run the nodes, therefore increasing the network scalability as compared to PoW.`

I don't see the reference to DPos on [What is blockchain](https://lisk.com/what-is-blockchain) page, maybe I am not looking at the right link. I would also suggest rephrasing or removing the second sentence, because it is not clear what is meant by  `whereby transaction validation is actually detached from the power required to run the nodes, therefore increasing the network scalability as compared to PoW`.

2022-10-14 18:50 UTC, mjerkov commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Further information on Setchain can be found xref:{url_setchain_imdea}[here].
`For example, researchers from xref:{url_imdea}[IMDEA Networks] have just developed a new data structure known as xref:{url_setchain}[Setchain], which implements a grow-only set object whose elements are not ordered, unlike conventional blockchain operations, which can phenomenally increase scalability.
Further information on Setchain can be found xref:{url_setchain_imdea}[here].`

Consider not using one specific example, especially in the conclusion, because it might mislead the reader to the wrong impression that this is the `final solution` to the scalability issues. I would rather suggest restating why scalability is still such an important topic.

2022-10-17 07:10 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +To compound this further, issues with its practical applications and the difficulties when an increased number of users wish to use the network occur, as this causes the transaction processing to slo
OK, now done 👍

2022-10-17 07:12 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +If we compare this to the well-known Visa card processing system, the number of transactions processed every second is around 17,000.
OK, I have removed it 👍

2022-10-17 08:57 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Starting from the genesis block to the latest block and transactions consists of a large quantity of data, so it has to be taken into consideration that each network node does not possess adequate re
Yes, I see your point. OK, I have removed this sentence 👍

2022-10-17 09:07 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +However, limiting the block size results in reducing the transaction speed, as if a low limit is used then that transaction can be stored in the block, and subsequently will have to wait to generate
I have restructured this sentence, which I think now simplifies, and improves the clarity and flow.

2022-10-17 09:19 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +As the blockchain grows and more and more transactions are processed, with increasing block sizes this is the crux of the issue, as there is an inherent danger of overloading the network, coupled wit
Good point...now done 👍

2022-10-17 09:39 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Basically, DPoS is a very efficient consensus mechanism, whereby transaction validation is actually detached from the power required to run the nodes, therefore increasing the network scalability as
Well spotted Miroslav! I have now corrected the link. In addition, I have reworded the following sentence accordingly 👍

2022-10-17 09:44 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Further information on Setchain can be found xref:{url_setchain_imdea}[here].
As discussed previously, I have removed all references to Setchain, just concluding with a high-level overview here 👍

2022-10-18 06:29 UTC, mjerkov approved these changes

2022-10-18 14:14 UTC, mitsuaki-u approved these changes

2022-10-18 14:19 UTC, Tschakki approved these changes
Thank you! 🎉

2022-10-18 15:40 UTC, merged