Explain key concepts of the Lisk blockchain - Closes #1488
LiskArchive/lisk-legacy-docs pull request #1503
Opened 2022-07-11 15:44 UTC by Tschakki

Closes #1488

2022-07-22 12:01 UTC, sergeyshemyakov reviewed
Just a couple of comments, otherwise looks good!

2022-07-22 12:01 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +This page explains the three domains of a blockchain, and introduces to blocks and transactions.
> introduces to blocks and transactions

I guess you wanted to say "introduces blocks and transactions" or "gives introduction to blocks and transactions"

2022-07-22 12:01 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. The <<block-assets,block assets>> allow modules to include specific data into a block.
I think at this point the reader would not be aware of the modules and what they do. Maybe some further comments would be helpful, e.g. explain why assets are needed here (to support a piece of custom blockchain logic).

2022-07-22 12:01 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The block header consists of the following properties:
I would suggest leaving only the most important/ non-technical properties here like `timestamp`, `height`, `previousBlockID`, `generatorAddress`, `transactionRoot`, `signature`. Otherwise the section looks a bit overwhelming.

You could say: all properties are listed in the block header schema and refer to the LIP for more explanations on other properties.

2022-07-22 12:01 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The full generation of a block is organized as follows.
I think it's important to explain and rationalize our block generating (and later block processing) architecture. I would comment that such block generation offers a lot of flexibility for custom logic without a virtual machine and makes all important verification steps explicit and obvious. Maybe you have some more arguments.

2022-07-22 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. The <<block-assets,block assets>> allow modules to include specific data into a block.
I tried to improve the explanation, let me know if you have some other suggestions!

2022-07-22 15:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The full generation of a block is organized as follows.
Yes good point, I tried to add some rationale, let me know if i need to add/adjust something.

2022-07-22 15:31 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The block header consists of the following properties:
I kept the explanations of the less important properties, but hid them in a collapsible box

2022-07-25 11:29 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. The <<block-assets,block assets>> allow modules to include specific data into a block.
I think it's good now, since you don't mention modules explicitly anymore.

2022-07-25 11:31 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The block header consists of the following properties:
Looks very good now!

2022-07-25 11:31 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The full generation of a block is organized as follows.
Nice explanation!

2022-07-25 11:32 UTC, sergeyshemyakov approved these changes
Now it looks very nice!

2022-07-25 20:38 UTC, shuse2 requested changes

2022-07-25 20:38 UTC, shuse2 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Furthermore, with this technology it is possible to track any item of value, and also trade it on a blockchain network, which in turn offers numerous benefits, such as reducing the costs and risk for
I think below `What is a block` also needs slight update because now block has `assets` and `transactions` as payload

2022-07-25 20:38 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Default transaction types
Terminology wise, i think we should say `commands that modules SDK provides`?
but I think it's better not to add this set here because this is explaining the concept, not specific feature

2022-07-25 20:38 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/sdk/index.adoc
> += Introduction to the Lisk SDK
is this page scope of this PR? maybe this page is duplicated or moved, but it contains outdated information

2022-07-25 20:38 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> += Key concepts of the Lisk blockchain
The images refers to `state machine domain`, but I think in LIP, it's updated to say `application domain` because in our SDK architecture, how we divided is not only about state machine. (ie: the `state machine` domain above contains concepts which are not `state machine`)

2022-07-26 07:26 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/index.adoc
> += Introduction to the Lisk SDK
No, it is not scope of this PR. Only the page "key concepts of Lisk blockchain" is the scope

2022-07-26 07:29 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> += Key concepts of the Lisk blockchain
As far as it was communicated, we always used `state machine`, and also in the docs site structure we planned it like this. If we really want to change this now, it should be updated there first, as this is the main source for creating the new docs structure, including names of pages.

2022-07-26 07:57 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Default transaction types
I think the table is super helpful and fits on the page, as it explains transactions to the reader. It is helpful to see an overview of existing examples while reading about the concept. Also, I don't know where it would fit better.

2022-07-26 07:59 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Default transaction types
And I would talk here about transaction types and then introducing commands in relation to transaction types. Otherwise it will be confusing for the reader imho. I think the connection between commands and transaction is explained sufficient on this page.

2022-07-26 07:59 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Furthermore, with this technology it is possible to track any item of value, and also trade it on a blockchain network, which in turn offers numerous benefits, such as reducing the costs and risk for
This is not scope of this PR

2022-07-26 08:15 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Furthermore, with this technology it is possible to track any item of value, and also trade it on a blockchain network, which in turn offers numerous benefits, such as reducing the costs and risk for
I think in `intro` section we talk about what is blockchain in general, not focussing on Lisks solution. And `understand-blockchain` is then the category, where we focus on the Lisk solution. In that context, I think it is fine to not mention block assets on this page, as I believe this property is pretty Lisk specific?

2022-07-26 08:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/index.adoc
> += Introduction to the Lisk SDK
It was the previous index page, I moved it now for now but it will be updated in #1509

2022-07-28 13:11 UTC, shuse2 commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
> +Furthermore, with this technology it is possible to track any item of value, and also trade it on a blockchain network, which in turn offers numerous benefits, such as reducing the costs and risk for
ah ok, yes, assets is very lisk specific 👍  make sense

2022-07-28 13:32 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Default transaction types
I think the concrete commands will fit better on each module explanation?
Interoperability module is actually MainchainInteroperability/SidechainInteroperability module (2 different modules), and we will have NFT/PoA and more in the future, so it will be quite a long list.

2022-07-28 14:14 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> += Key concepts of the Lisk blockchain
I think explaining `state machine` is fine.
The difference is when we split in to 3 parts, in the LIP55, we said we split in application/consensus/network domain, and state machine is part of the `application` domain.

It is because not all `module` logic are strictly speaking `state machine`. For example, `insertAsset` or `verifyTransaction` etc hooks are not mutating the state.

2022-07-28 15:10 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> += Key concepts of the Lisk blockchain
Ok, I have now updated the images and descriptions to mention the `application` domain instead of `state machine`

2022-07-28 15:12 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Default transaction types
ok, I commented the table out, in case I can reuse parts of it somewhere else :)

2022-07-28 15:58 UTC, shuse2 approved these changes

2022-07-29 12:22 UTC, gkoumout requested changes
Looks good in general! 

Some conctrete comments:

- In the "what is blockchain" file, the section "How does a blockchain transaction work" seems confusing in steps 3 and 4, since the term block (and hashing) is first mentioned in point 3 and then in point 4 the block creation step is described. Perhaps say more explicilty in point 3 that a transaction is included in the block. 

- In the "Key concepts of Lisk Blockchain file", in a later stage a link to the transaction schema LIP should be added (currently a PR is opened, but not merged yet)

2022-07-29 12:22 UTC, gkoumout commented on docs/modules/ROOT/pages/intro/what-is-blockchain.adoc
>  == What is a block?
in the last paragraph of this section, I guess the last phrase ", (each separate node) " should just be removed

2022-07-29 12:22 UTC, gkoumout commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. The <<block-assets,block assets>> are an array of objects containing data injected by the blockchain application during the block creation.
Perhaps rephrase: "block assets are an array...".

Example: `` Block assets: An array of objects ..."

2022-07-29 12:22 UTC, gkoumout commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +
Perhaps add the transactions section here; this would make it more consistent since the block consist of: header, assets, transactions. 

Now the order is a bit arbitrary by defining just header and asset, then proceed to block generation and then going back to transactions. 

If the reason for the current structure is that transactions section is kind of more important and special, we can just add here a small comment that transactions will be discussed in a later section and add a link to it.

2022-07-29 12:22 UTC, gkoumout commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Default transaction types
Actually I think that it is a good idea to have some table like that here. Somehow the first-time reader gets a sense of what is module is doing by viewing intuitive transaction names here (e.g,. register delegate in DPos, token transfer in Token etc.)

 I can see the point that it gets too long, but I would not view this as an issue. If you insist that a long table is bad, as an intermediate solution we could have an example like: 
 
Token Module includes the following transactions --> table
 DPos Module includes the following transactions  --> table
 
 Similarly all modules define transactions, see documentation/LIP, etc.

2022-07-29 13:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +
Yes valid point, I now moved the transaction section up, let me know if it's ok now!

2022-08-01 15:55 UTC, gkoumout approved these changes
No complaints! All my comments addressed  ;-)

2022-08-02 10:16 UTC, merged