Add state machine page - Closes #1495
LiskArchive/lisk-legacy-docs pull request #1504
Opened 2022-07-12 13:51 UTC by Tschakki

Closes #1495

2022-08-01 09:55 UTC, ricott1 requested changes

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +** *states:* A state machine typically has a set of different states, that it can enter.
```suggestion
** *states:* A state machine typically has a set of different states that it can enter.
```

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* A *state machine* is a concept in computer science, consisting of the following elements:
Not sure what the * should correspond to, but the rendered version shows nothing (no bold nor italics)

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* *Finite* means, the number of states, that the machine can reach is always finite.
```suggestion
* *Finite* means that the number of states that the machine can reach is finite (not infinite).
```

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* *Replicated* describes the characteristic of blockchains to consist of a network of nodes all storing an individual copy of the blockchain, which replicates the state machine on each connected node
Here I would describe what 'replicated' means in this more general context (i.e., the state machine is replicated across many nodes. Each node maintains independently the current state of the state machine). We could also mention that this only works for deterministic state machine

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +** **Module ID** = The ID of the module, identifying the key-value map. We will reserve all module IDs starting with a 0 in their binary representation to modules that are shipped with the SDK by def
```suggestion
** **Module ID**: The ID of the module, identifying the key-value map. We will reserve all module IDs starting with a 0 in their binary representation to modules that are shipped with the SDK by default. The IDs of modules developed as part of each blockchain application will start with a 1. The module ID has a fixed length of 4 bytes.
```

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +** **Module ID** = The ID of the module, identifying the key-value map. We will reserve all module IDs starting with a 0 in their binary representation to modules that are shipped with the SDK by def
I would use colons for consistency with the previous section

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +|Proofs-of-Inclusion for Transactions in a Block|`transactionRoot`|Each block header stores the `transactionRoot`.
We use regular Merkle trees for the transaction root

2022-08-01 09:55 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +|Proofs-of-Inclusion for Assets in a Block|`assetRoot`| The root of the event sparse Merkle tree is added to the block header to allow checking inclusion and non-inclusion of block assets.
Copy/paste error? the assetRoot is a regular Merkle tree root, I would just remove this line

2022-08-02 12:19 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* A *state machine* is a concept in computer science, consisting of the following elements:
It's bold effect in asciidoc, it'll show up in the docs, see: https://liskhq.github.io/lisk-docs/understand-blockchain/state-machine.html

2022-08-02 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +|Proofs-of-Inclusion for Assets in a Block|`assetRoot`| The root of the event sparse Merkle tree is added to the block header to allow checking inclusion and non-inclusion of block assets.
I actually was not sure, if we still use RMTs in the Lisk Protocol. In that case, I will mention them seperately, I think it is an interesting information.

2022-08-02 12:54 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* A *state machine* is a concept in computer science, consisting of the following elements:
ok

2022-08-02 12:54 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* A *state machine* is a concept in computer science, consisting of the following elements:
actually it was blocked by 'noscript' 😅 all good

2022-08-02 12:59 UTC, ricott1 requested changes

2022-08-02 12:59 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +|Proofs-of-Inclusion for Assets in a Block|`assetRoot`| The root of the event sparse Merkle tree is added to the block header to allow checking inclusion and non-inclusion of block assets.
the description still mentions events

2022-08-02 13:19 UTC, ricott1 approved these changes

2022-08-02 13:42 UTC, ishantiw approved these changes
Just a couple of suggestions otherwise lgtm

2022-08-02 13:42 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +* *tree:* The underlying data structure is organized as a tree, where each parent node is obtained by hashing the data from the child nodes in the layer below.
maybe these can also start with capital letter

2022-08-02 13:42 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +|Proofs-of-Inclusion for Assets in a Block|`assetRoot`| The root of the asset Merkle tree is added to the block header to allow checking inclusion and non-inclusion of block assets.
Maybe Proofs-of-(non-)Inclusion for Assets in a Block as check both of them

2022-08-03 10:55 UTC, merged