Create blockchain interoperability page in Lisk docs - Closes #1497
LiskArchive/lisk-legacy-docs pull request #1505
Opened 2022-07-15 06:41 UTC by chris529

Closes #1497

2023-12-04 10:04 UTC, sergeyshemyakov requested changes
Some remarks and suggestions.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Blockchain interoperability can be characterized by having the capability to freely, efficiently, and securely exchange data and information with other blockchains.
I would also add "trustlessly". You can always paste transactions from one blockchain into another, but then everyone will have to trust that you have not made any accidental or intentional mistakes.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Ultimately this will result in connected blockchain ecosystems becoming the norm, as opposed to {url_silo-based-blockchain}[silo-based blockchain^] ecosystems.
The reference you have about siloed blockchains concerns a different idea. Interoperability combats siloed blockchains in the sense that data from one chain will be available on other blockchains. The link that you provide describes a setup when a company puts a private (siloed) data onchain to make it publicly available to all necessary shareholders, it involves only one blockchain.
I would recommend just to remove the reference, alternatively you could find an article about the need to connect all blockchains via interoperability protocols.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The beauty of blockchain Interoperability will result in eliminating the necessity for third parties or intermediaries that are interconnected with centralized systems.
Something is wrong with this sentence.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +This will result in both faster and more secure transactions, and offer the possibility to utilize additional complex {url_smart-contract}[smart contract^] based applications.
The transactions do not become faster or more secure with interoperability. You are just able to send transactions cross-chain.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +For example, the possibility exists for private blockchains to communicate with public ones, and vice versa.
Private blockchains can only read from public blockchains, they cannot write. The reason is: public blockchains cannot verify the data integrity of transactions coming from a private network. 
Maybe remove this sentence, or specify that private blockchains can use data from public ones.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +With interoperable blockchain networks, this could raise privacy concerns as the potential to expose more user data across different blockchains exists which might not be handled correctly.
I would not say that interoperability raises additional privacy concerns. Whenever user data ends up on any blockchain, it is public forever by definition, so the potential problem exists even without interconnected chains.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Despite their connection to the parent blockchain, sidechains employ distinct {url_consensus_algorithm}[consensus algorithms^] and possess unique native tokens.
I would remove the first half of the sentence because it is not completely correct to say that the mainchain is a "parent" of a sidechain. They are more equal, the mainchain in Lisk is only responsible for interoperability.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +In addition to serving as layer 2 scaling solutions, sidechains contribute to blockchain interoperability by validating data from other blockchains.
Sidechains are not layer 2. Layer 2 means that the final settlement is done somewhere else (on Layer 1), however a sidechain settles on itself.
Also, I don't understand what you mean by "validating data from other blockchains".

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Furthermore, these secondary blockchains feature distinct xref:{url_consensus_protocols}[consensus protocols], enhancing a blockchain network's privacy and security while simultaneously reducing the
Strictly speaking, the blockchain security would be better if all chains relied on a single consensus protocol. A problem is: if a sidechain has its own validators, the total value of their staked tokens will be much lower than on the mainchain, thus making an economic attack much easier.
Sidechains only help with scaling blockchain, not making it more secure.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Finally, an essential aspect of sidechains lies in their capacity to streamline the exchange of assets between the mainnet and the sidechain.
The sidechains create a problem of transferring assets between the mainchain and the sidechain, not solve it. The whole paragraph should be removed IMO.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +=== Sidechains
The sidechain architecture that you explain here is quite specific to the Lisk ecosystem. E.g. in the Ethereum ecosystem there is no notion of mainchain, every chain is a sidechain of all connected chains. I suggest to say more explicitly that you speak about Lisk sidechains.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +=== Cross chain bridges
Usually cross-chain bridges do not involve any blockchain in the middle, two chains are connected directly (e.g. see [here](https://www.zeeve.io/blog/what-are-cross-chain-bridges-a-detailed-guide/)). Again, what you describe is more characteristic of Lisk ecosystem, where the mainchain can be seen as a cross-chain bridge between the sidechains, but this is not the most common way to connect two blockchains.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To give a brief example, an atomic swap involves the relocation of a token belonging to the primary blockchain by making it unavailable, whilst simultaneously generating a corresponding token on the
Atomic swaps do not make any tokens unavailable, neither do they generate new tokens. They just allow two people to trustlessly exchange x tokens on one chain for y tokens on another chain. No verification from any of the blockchains is needed, the data is exchanged only between the involved peers.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The Lisk interoperability solution facilitates communication with other chains via the concept of xref:{url_cross_chain_cert}[cross-chain] certification.
I would stress that you mean other Lisk chains, not other ecosystems like Ethereum or Cosmos.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> + - Flexibility
I would also add that Lisk interoperability allows sending arbitrary cross-chain messages.

2023-12-04 10:04 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +For example, applications such as {url_chaingpt}[Chain GPT^], {url_starkdefi}[Stark Defi^], and {url_moonpay}[MoonPay^], are accessible through conventional user interfaces and are completely reliant
I don't think Chain GPT or MoonPay rely on any interoperability. If you need another example, I think [Axie Infinity](https://axieinfinity.com/) is a good one, they definitely have a bridge.

2023-12-04 10:13 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Blockchain interoperability can be characterized by having the capability to freely, efficiently, and securely exchange data and information with other blockchains.
Thanks Sergey, Good point...I have now added it 👍

2023-12-04 11:38 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The beauty of blockchain Interoperability will result in eliminating the necessity for third parties or intermediaries that are interconnected with centralized systems.
OK, I have reworded this accordingly 👍

2023-12-04 11:44 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +This will result in both faster and more secure transactions, and offer the possibility to utilize additional complex {url_smart-contract}[smart contract^] based applications.
OK, I have reworded this. 👍

2023-12-04 11:49 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +For example, the possibility exists for private blockchains to communicate with public ones, and vice versa.
Updated. 👍

2023-12-04 11:53 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +With interoperable blockchain networks, this could raise privacy concerns as the potential to expose more user data across different blockchains exists which might not be handled correctly.
Fair point..I have removed this sentence 👍

2023-12-04 12:53 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +In addition to serving as layer 2 scaling solutions, sidechains contribute to blockchain interoperability by validating data from other blockchains.
To avoid any confusion, I have removed this sentence 👍

2023-12-04 13:39 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Furthermore, these secondary blockchains feature distinct xref:{url_consensus_protocols}[consensus protocols], enhancing a blockchain network's privacy and security while simultaneously reducing the
I have removed the reference to 'making it more secure'

2023-12-04 13:44 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Finally, an essential aspect of sidechains lies in their capacity to streamline the exchange of assets between the mainnet and the sidechain.
OK, I have reworded it accordingly 👍

2023-12-04 13:51 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +=== Sidechains
Yes, good point, I have now mentioned this at the end of the previous section,  which then leads into the Sidechain section, and ends with referring again to our solution. 👍

2023-12-04 14:08 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To give a brief example, an atomic swap involves the relocation of a token belonging to the primary blockchain by making it unavailable, whilst simultaneously generating a corresponding token on the
OK, it is now reworded to reflect this 👍

2023-12-04 14:12 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The Lisk interoperability solution facilitates communication with other chains via the concept of xref:{url_cross_chain_cert}[cross-chain] certification.
Done 👍

2023-12-04 14:17 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +For example, applications such as {url_chaingpt}[Chain GPT^], {url_starkdefi}[Stark Defi^], and {url_moonpay}[MoonPay^], are accessible through conventional user interfaces and are completely reliant
OK, I have amended this and added in Axie Infinity as suggested 👍

2023-12-04 14:37 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> + - Flexibility
Done 👍

2023-12-04 16:15 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +=== Cross chain bridges
Yes, I am trying more to promote and explain our solution, however that is a good point, so I have updated this section to highlight that the description given pertains to the Lisk ecosystem, and concluded with a paragraph regarding other solutions, complete with an external link for further reading if required. 👍

2023-12-05 09:57 UTC, sergeyshemyakov approved these changes
Just one more small comment, feel free to include it or not. Good job!

2023-12-05 09:57 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Within the Lisk ecosystem the solution for enabling blockchain networks to achieve interoperability, and interact with other blockchain networks involves utilizing a separate blockchain as a bridge t
I would add: 

> involves utilizing a separate blockchain **(Lisk Mainchain)** as a bridge

2023-12-05 10:36 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Within the Lisk ecosystem the solution for enabling blockchain networks to achieve interoperability, and interact with other blockchain networks involves utilizing a separate blockchain as a bridge t
Many thanks for all your great feedback Sergey! I have included your suggestion above. 👍

2023-12-06 11:19 UTC, Tschakki requested changes

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +This can be particularly useful when transferring an asset, for example, a crypto asset, such as Lisk, Ethereum, or Cardano.
If we talk about crypto assets/tokens here, maybe it is better to use the Token names and not names of the network.

```suggestion
This can be particularly useful when transferring an asset, for example, a crypto asset, such as LSK, ETH, or ADA.
```

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +:url_cross-chain: https://www.horizen.io/academy/cross-chain-transactions
This gives me an 404

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Within the Lisk ecosystem the solution for enabling blockchain networks to achieve interoperability, and interact with other blockchain networks involves utilizing a separate blockchain (Lisk maincha
This part is a little confusing to me, you are presenting different ways to achieve interoperability, but mention Lisk in two of the solutions, does it mean Lisk uses both at the same time?

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Generally speaking, blockchain bridges can be defined into two categories, trust-based bridges, and trustless bridges.
As we introduce different kinds of bridges to the reader, we should be precise here about what kind of bridge we are talking.

```suggestion
Generally speaking, Token bridges can be defined into two categories, trust-based bridges, and trustless bridges.
```

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +=== Token bridges
As cross-chain bridges and token bridges sound quite similar, maybe add their particular use case or highlight their main difference from each other. It is also always helpful, to inlcude real-world examples of these different interoperability solutions.

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The Lisk interoperability solution facilitates communication with other Lisk chains built within the Lisk ecosystem, via the concept of xref:{url_cross_chain_cert}[cross-chain] certification.
Imho it would be nice to mention here, which of the previously presented different interoperability solutions Lisk is following, before going into the details.

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +* One of the key aspects of security with the Lisk interoperability solution ensures that the requirement for xref:{url_certificates}[certificates] is signed by a significant proportion of xref:{url_
link to validators is broken

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +:url_certificates: understand-blockchain/consensus/certificates.adoc
please remove, the page doesn't exist yet

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The Lisk interoperability solution facilitates communication with other Lisk chains built within the Lisk ecosystem, via the concept of xref:{url_cross_chain_cert}[cross-chain] certification.
```suggestion
The Lisk interoperability solution facilitates communication with other Lisk chains built within the Lisk ecosystem, via the concept of cross-chain certification.
```

removed link to communication page, doesn't really fit the context

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +* One of the key aspects of security with the Lisk interoperability solution ensures that the requirement for xref:{url_certificates}[certificates] is signed by a significant proportion of xref:{url_
Also, here you could add link to CCM explanation, when mentioning `cross-chain messages`

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +* Cross-chain update transactions can be transmitted at any frequency, for example, whether it's every few seconds or just once a month.
here you could add link to CCU explanation, when mentioning cross-chain update

2023-12-06 11:19 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Interoperability enables different blockchain networks to share data transactions, unlocking a plethora of possibilities.
```suggestion
Interoperability enables different blockchain networks to share transaction data, unlocking a plethora of possibilities.
```

2023-12-06 12:53 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +This can be particularly useful when transferring an asset, for example, a crypto asset, such as Lisk, Ethereum, or Cardano.
Yes, fair point Mona..Now updated 👍

2023-12-06 13:34 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +:url_cross-chain: https://www.horizen.io/academy/cross-chain-transactions
Thanks, the trailing forward slash was missing from the end of the url. It should work now 👍

2023-12-06 14:28 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Within the Lisk ecosystem the solution for enabling blockchain networks to achieve interoperability, and interact with other blockchain networks involves utilizing a separate blockchain (Lisk maincha
OK, I have updated and restructured this section somewhat to improve the clarity, and now the first paragraph really pertains to the Lisk solution, followed by a brief general overview of other solutions in the second paragraph.

2023-12-06 14:54 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +:url_certificates: understand-blockchain/consensus/certificates.adoc
OK, I have removed the link and added a TODO for when the certificate page is completed.

2023-12-06 16:21 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +=== Token bridges
OK, I have summarised the difference between the two types of bridges at the end of the paragraph.

2023-12-06 16:29 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The Lisk interoperability solution facilitates communication with other Lisk chains built within the Lisk ecosystem, via the concept of xref:{url_cross_chain_cert}[cross-chain] certification.
Ah, well, it is actually mentioned above at the beginning of the Cross-chain bridges paragraph, but yes, I agree it's also good to highlight it again to keep the reader on track, so I have mentioned it as suggested 👍

2023-12-06 16:36 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +* One of the key aspects of security with the Lisk interoperability solution ensures that the requirement for xref:{url_certificates}[certificates] is signed by a significant proportion of xref:{url_
Good point, link now added 👍

2023-12-06 16:41 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +* Cross-chain update transactions can be transmitted at any frequency, for example, whether it's every few seconds or just once a month.
Link now added 👍

2023-12-07 09:29 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +* One of the key aspects of security with the Lisk interoperability solution ensures that the requirement for xref:{url_certificates}[certificates] is signed by a significant proportion of xref:{url_
Validator link should now work 👍

2023-12-08 10:43 UTC, Tschakki requested changes
Looking good already! Please see my remaining comments

2023-12-08 10:43 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Within the Lisk ecosystem the solution for enabling blockchain networks to achieve interoperability, and interact with other blockchain networks involves utilizing a separate blockchain (Lisk maincha
```suggestion
```

as we talk about the Lisk-specific solution below, i would keep the explanation of the different interoperability approaches more general

2023-12-08 10:43 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +This separate blockchain, (namely the Lisk mainchain regarding our solution), is in effect positioned between the two blockchains wishing to exchange data and upholds a cryptographically timestamped,
```suggestion
This separate blockchain, is in effect positioned between the two blockchains wishing to exchange data and upholds a cryptographically timestamped, secure ledger, that records messaging and transactional activities between them.
```

2023-12-08 10:43 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +The Lisk interoperability solution facilitates communication with other Lisk chains built within the Lisk ecosystem, via the concept of cross-chain certification, and deploys the cross-chain bridge m
```suggestion
The Lisk interoperability solution facilitates communication with other Lisk chains built within the Lisk ecosystem, via the concept of cross-chain certification, and deploys the <<cross-chain-bridges,cross-chain bridge>> methodology as described earlier on this page.
```

2023-12-08 10:43 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
```suggestion
```

2023-12-08 10:43 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
As i understood now from the other content on this page, Lisk is following cross-chain bridges approach, not sidechains. I would therefore remove all mentions of lisk and lisk sidechains here, and maybe even add a note, that this solution does not relate to sidechains in the Lisk ecosystem

2023-12-08 11:12 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +Within the Lisk ecosystem the solution for enabling blockchain networks to achieve interoperability, and interact with other blockchain networks involves utilizing a separate blockchain (Lisk maincha
OK, fair point 👍

2023-12-08 11:37 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
OK, I have removed the reference to our sidechain page. However, as this page is meant to be more of a general overview of Interoperability and the approaches and its different solutions, sidechains are one of these, so I think we should keep it. (In fact the proposed ToC for this page in the https://github.com/LiskHQ/lisk-docs/issues/1497 issue, it mentions sidechains).

2023-12-08 13:34 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
but arent sidechain also used in the cross-chain solution?

2023-12-08 14:00 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
Well yes, you are correct Mona, sidechains can be used as part of a cross-chain solution in blockchain interoperability. Although Cross-chain solutions often involve the use of various technologies, and sidechains are just one of the tools avaialble for achieving interoperability. 
I think the idea here was really to highlight that there are various methods and technologies employed in achieving interoperability, and sidechains are just one of the possible approaches. Nevertheless, if you feel it is a bit ambiguous or confusing, then we can easily just remove the entire sidechain paragraph. It is only imho that I would keep it :)

2023-12-08 14:30 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
@chris529 You don't need necessarily to remove the section, just make it clearer what are the different interoperability approaches, by highlighting their main features, differences, and the best would also be if you can include real world examples for each approach, e.g. pointing to different blockchain projects who are using this solution/approach.
@sergeyshemyakov can you please advise here? It looks indeed confusing to me, in the introduction sounds like different interoperability solutions are presented, but then the first two points seem to be features of the same interoperability solution?! Or is there a clear difference, please explain.

2023-12-12 09:26 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
@Tschakki As requested, I have now updated each of the described interoperability techniques, including giving examples of actual blockchain projects deploying these techniques, etc.

2023-12-12 11:11 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/intro/blockchain-interoperability.adoc
> +To gain a more in-depth understanding, coupled with how the Lisk sidechain solution works, it is recommended to read the xref:{url_sidechain}[Sidechain registration and recovery] page.
I would say that this section makes an overview of different technology involved in interoperability. Sidechains are connected with cross-chain bridges, however these two sections focus on different aspects (general sidechain architecture vs. how can a bridge work). IMO this is fine in an overview page.

2023-12-18 10:05 UTC, Tschakki approved these changes

2023-12-19 09:44 UTC, merged