Add version references for Commander - Closes #111
LiskArchive/lisk-legacy-docs pull request #154
Opened 2019-01-15 11:27 UTC by Tschakki

Closes #111

2019-01-15 13:53 UTC, shuse2 requested changes

2019-01-15 13:53 UTC, shuse2 commented on introduction.md
> +[v2.2.0](https://github.com/LiskHQ/lisk/releases/tag/v2.1.0) | 19/0x/xx | *Current version, live on lisk.io/documentation*
do we need this `2.2.0` link now?

2019-01-15 13:53 UTC, shuse2 commented on introduction.md
> +With Lisk Commander, it is easier and quicker to plug new commands into the CLI than building a Graphical User Interface (GUI) around every command.
these two sentence sounds like more of why create the lisk-commander, but not for external communication.

maybe it's good to communicate what exactly commander is right now?

2019-01-15 17:54 UTC, Tschakki commented on introduction.md
> +[v2.2.0](https://github.com/LiskHQ/lisk/releases/tag/v2.1.0) | 19/0x/xx | *Current version, live on lisk.io/documentation*
yes, as this PR will be merged into the v2.2.0 docs release for Lisk Elements. The exact release date will be added later when it's set.

2019-01-18 15:16 UTC, Tschakki commented on introduction.md
> +With Lisk Commander, it is easier and quicker to plug new commands into the CLI than building a Graphical User Interface (GUI) around every command.
I added suggestion for a new introduction text, feedback welcome! :)

2019-04-16 13:35 UTC, shuse2 approved these changes

2019-04-16 14:52 UTC, merged