Update with `npm ci` - Closes #152
LiskArchive/lisk-legacy-docs pull request #157
Opened 2019-01-18 16:16 UTC by Tschakki

Closes #152

2019-01-21 12:01 UTC, ghost requested changes

2019-01-21 12:01 UTC, fchavant commented on setup/source/source.md
> -sudo npm install -g pm2
Example usage of  `pm2` below must be updated to `./node_modules/.bin/pm2` / `npm run pm` or something equivalent.

2019-01-23 09:49 UTC, Tschakki commented on setup/source/source.md
> -sudo npm install -g pm2
I added now `npx` in front of the pm2 commands, in order to execute the locally installed npm package of pm2.

2019-01-23 14:35 UTC, ghost approved these changes

2019-01-23 14:41 UTC, merged