Add section about versioning schemes - Closes #62
LiskArchive/lisk-legacy-docs pull request #158
Opened 2019-01-21 16:59 UTC by Tschakki

Closes #62

2019-01-22 10:48 UTC, AndreasKendziorra requested changes
Besides the mentioned suggestions, it might be worth to add a "protocol version" column in the table in section "Versions". Then, one knows easily which protocol version is implemented by which software.

2019-01-22 10:48 UTC, AndreasKendziorra commented on introduction.md
> +  - [Versioning Scheme](#versioning-scheme)
#versioning-scheme -> #versioning-schemes

2019-01-22 10:48 UTC, AndreasKendziorra commented on introduction.md
> +The *Software Implementation Versioning* follows the popular SemVer scheme and gives a quick overview for developers about breaking and non-breaking changes in the software.
We should use consistently "Semver" or "SemVer"

2019-01-22 10:48 UTC, AndreasKendziorra commented on introduction.md
> +The *Protocol Versioning* theme is used e.g. in P2P Communication between Lisk Core nodes, in order to determine, if the nodes have compatible versions of the Lisk protocol implemented.
Maybe "The protocol version is used" instead of "The *Protocol Versioning* theme is used"?

2019-01-23 11:05 UTC, 2snEM6 approved these changes
No problems for me. Very clear :)

2019-01-23 11:21 UTC, AndreasKendziorra approved these changes
Looks good to me. But @MaciejBaj should confirm that v.1.5.0 does not imply a soft fork.

2019-01-23 14:41 UTC, merged