Add new page about conensus protocols - Closes #1492
LiskArchive/lisk-legacy-docs pull request #1586
Opened 2022-07-25 13:35 UTC by Tschakki

Closes #1492

2022-07-29 15:01 UTC, mitsuaki-u approved these changes

2022-08-03 21:04 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +:fn_validators: footnote:validators[Validators: Accounts eligible to add new blocks to the chain.]
Maybe we could avoid footnotes here and rather add these things to the glossary? The footnotes make things difficult to read and also the layout does not look so nice.

2022-08-03 21:05 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +A consensus protocol is the protocol for validators{fn_validators} to **agree on one chain of blocks**.
This is one aspect of consensus protocols, but does not cover everything, see first section in https://lisk.com/documentation/understand-blockchain/lisk-protocol/consensus-algorithm.html.

2022-08-03 21:09 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +* **Block frequency**: Defining when a block is added to the chain.
Do you mean here, for instance, that a block is added every 10 seconds? I don't think the block time is defined in the PoA or DPoS module at the moment.

2022-08-03 21:10 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|* **Fork{fn_fork} prevention**: Determining how validators choose the chain to which they add a new block.
I would rather call this "fork choice rule" as it does not prevent forks, but rather helps to resolve them.

2022-08-03 21:11 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +* **Chain finalization**: Determining when a block (and all included transactions) is irrevocably deemed part of the blockchain.
I would rather call it "block finalization" as generally not the whole chain is finalized (especially not the last one just added), but rather one block and all its ancestors.

2022-08-03 21:16 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|Cross-chain{fn_crosschain} agreement
I would rather put "certificate generation" here. There is not really a cross-chain agreement protocol, but rather certificate generation (in the sending blockchain) and certificate validation (in the receiving blockchain).

2022-08-03 21:22 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|* **Verifying cross-chain communication**: Attesting the correctness of cross-chain messages with certificates.
I would rather focus on the fact that certificates are automatically generated for finalized blocks. This happens now in the engine and is closely connected to the Lisk BFT protocol. You could mention the 3 steps in the certificate generation process (see blog post https://lisk.com/blog/research/certificate-generation-and-consensus) if you want to go into detail.

We could also mention that the certificates generation process is designed in a way to ensure that the generated certificates satisfy the chain of trust property.

2022-08-03 21:24 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +* **Chain of trust for validators **: Attesting updates about the current validator set of a chain in certificates.
If we want to say something about chain of trust, I would suggest something like:

> Generated certificates satisfy chain of trust property, i.e., they can be sequentially submitted to another blockchain via cross-chain update transactions.

2022-08-03 21:24 UTC, janhack requested changes
Overall, the page looks goods. I left a some comments and suggestions to improve the clarity in a few places.

2022-08-04 08:38 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +A consensus protocol is the protocol for validators{fn_validators} to **agree on one chain of blocks**.
Updated it to include more aspects, and structured it in a bullet list for better overview

2022-08-04 08:39 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +* **Block frequency**: Defining when a block is added to the chain.
ah ok, then I will remove it here

2022-08-04 08:45 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|Cross-chain{fn_crosschain} agreement
Hm, but don't the certificates in a sense enable cross-chain agreement about a certain state of the blockchain across chains? My thought of calling it `cross chain agreement` was that it explains the purpose in a more general way than `certificate generation`. Because for the later you would need to know what are certificates and what is their purpose in the application.

2022-08-04 08:59 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|* **Verifying cross-chain communication**: Attesting the correctness of cross-chain messages with certificates.
I added now additional information. But please take into account we only talk about certificates in a very short and general manner here, the details are then mentioned on the respective explanation of the consensus protocol, here as part of the Lisk interoperability solution.

2022-08-04 14:08 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +Blockchain applications built with the Lisk SDK achieve consensus in all important domains via dedicated modules, which each cover a specific aspect of the overall consensus of a blockchain.
Note that "Lisk-BFT" is no moved to the engine and will not be a module any more.

2022-08-04 14:14 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +Blockchain applications built with the Lisk SDK achieve consensus in all important domains via dedicated modules, which each cover a specific aspect of the overall consensus of a blockchain.
```suggestion
In the Lisk SDK, the different aspects of the consensus protocol are handled by different sub-protocols as outlined in the table below. 
```

2022-08-04 14:14 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +== Consensus protocols in Lisk
```suggestion
== Consensus protocol in Lisk
```

2022-08-04 14:14 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +== Consensus protocols in Lisk
I would say there is one consensus protocol which is organized into different sub-protocols.

2022-08-04 14:23 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|Cross-chain{fn_crosschain} agreement
Cross-chain agreement suggests that different blockchains communicate directly with each other (however, this only happens if there is a relayer) and there could be information flow into both direction. However, in the cross-chain certification approach, one blockchain just informs other blockchains about their state with the certificate signatures to attest for the correctness. So it is very much only a one-direction information flow that only happens if there is a relayer.

2022-08-04 14:25 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +Generated certificates satisfy chain of trust property, i.e., they can be sequentially submitted to another blockchain via cross-chain update transactions.
As mentioned before, I don't think the cross-chain communication belongs to the consensus protocol. Instead, I would suggest to remove the bullet point "Verifying cross-chain communication" and rename "[Cross-chain] agreement" to "Certificate generation"

2022-08-04 14:28 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|* **Verifying cross-chain communication**: Attesting the correctness of cross-chain messages with certificates.
You could have one bullet point here:
> - "**Certificate generation for interoperability**: Certificates are generated for finalized blocks. Certificates are crucial for submitting cross-chain updates to other blockchains as they attest outgoing cross-chain messages and changes of validators."

2022-08-04 14:28 UTC, janhack requested changes
I added a few more comments and suggestions.

2022-08-04 17:27 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|Consensus domain|Consensus protocol|Responsible for
```suggestion
|Domain|Protocol|Responsible for
```

2022-08-04 17:28 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|* **Chain of trust for validators **: Attesting updates about the current validator set of a chain in certificates.
I would remove this part as the chain of trust property of the generated certificates is not that important here in my opinion and it does not really fit under "Responsible for".

2022-08-04 17:32 UTC, janhack commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|Certificate generation
Maybe the domain could be "Certificates" and the protocol "Certificate generation protocol" or "Certificate generation mechanism". Note that this protocol is defined in [LIP 61](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md) and rather an add-on to the consensus, then the Lisk Interoperability protocol (that is rather what is defined in the Interoperability module).

2022-08-04 17:32 UTC, janhack requested changes
I still have some minor comments.

2022-08-09 15:43 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +|Certificate generation
Hm, but where in the current structure are we explaining certificates? I was imaging it is done in one of the pages explaining the Lisk interoperability solution. If it doesn't fit there, maybe we should think of adding an additional page, just talking about certificates, and linking to it here.

2022-08-11 16:52 UTC, janhack approved these changes
Looks all good.

2022-08-12 13:19 UTC, merged