Corrects the Typo on SRS guide - Closes 1587
LiskArchive/lisk-legacy-docs pull request #1592
Opened 2022-08-01 12:19 UTC by TalhaMaliktz

Closes #[1587](https://github.com/LiskHQ/lisk-docs/issues/1587)

2022-08-01 12:38 UTC, chris529 requested changes
Looks good, just one very minor point 👍

2022-08-01 12:38 UTC, chris529 commented on docs/modules/ROOT/pages/tutorial/srs.adoc
> +First, create the folder for the blockchain application, initialize a new Node.js project and install the xref:{url_lisk_sdk}[Lisk SDK] as dependency.
```suggestion
First, create the folder for the blockchain application, initialize a new Node.js project and install the xref:{url_lisk_sdk}[Lisk SDK] as a dependency.
```

2022-08-01 15:13 UTC, chris529 approved these changes
LGTM! 👍

2022-08-02 10:26 UTC, Tschakki approved these changes
Thanks!

2022-08-02 10:27 UTC, merged