Create bug bounty program page in Lisk docs - Closes #1506
LiskArchive/lisk-legacy-docs pull request #1597
Opened 2022-08-05 14:45 UTC by chris529

2022-08-24 09:39 UTC, Tschakki requested changes
Please fix the existing conflicts in `nav.adoc`, and see my comments below

2022-08-24 09:39 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> += Bug bounty program
```suggestion
= Lisk Bug Bounty Program
```

2022-08-24 09:39 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +image:intro/bug-bounty-update.jpeg[align="center"]
```suggestion
image::intro/bug-bounty-update.jpeg[align="center"]
```

use block image syntax here

2022-08-24 09:39 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +image:intro/remuneration1.png[ align="center"]
```suggestion
image::intro/remuneration1.png[ align="center"]
```

2022-08-24 09:39 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +image:intro/bug-report-form.png[align="center" ,400]
```suggestion
image:intro/bug-report-form.png[role="related thumb right",200]
To file a report, use this link to access the {url_submission_form}[submission form^].
Alternatively, if you prefer to file a report via email, use the following address: security@lisk.com
```
to improve image/text alignment

2022-08-24 13:35 UTC, TalhaMaliktz requested changes

2022-08-24 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +The Lisk bug bounty program is a long-standing initiative designed to offer an incentive in the form of a remuneration payment to anyone who locates any bugs or vulnerabilities that may exist within
```suggestion
The Lisk bug bounty program is a long-standing initiative designed to offer an incentive in the form of a remuneration to anyone who locates any bugs or vulnerabilities that may exist within the existing Lisk core network.
```

2022-08-24 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +image::intro/bug-bounty-update.jpeg[align="center"]
The quality of the images gets compromised when zoomed in. Please use the images from the following URLs:

- https://lisk.com/sites/default/files/media/bugbounty-hero_6.svg
- https://lisk.com/sites/default/files/pictures/2020-03/Bugbounty-payouttable-v2.svg
- https://lisk.com/sites/default/files/pictures/2022-06/Group%201062.png

2022-08-24 16:33 UTC, chris529 commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +The Lisk bug bounty program is a long-standing initiative designed to offer an incentive in the form of a remuneration payment to anyone who locates any bugs or vulnerabilities that may exist within
Thanks for the feedback. If you wish to remove the word  'payment' then we would also need to remove the indefinite article 'a' as well, as this is then redundant when used with an uncountable noun such as 'remuneration'
I  agree and have updated it accordingly 👍

2022-08-24 16:39 UTC, chris529 commented on docs/modules/ROOT/pages/intro/bug-bounty-program.adoc
> +image::intro/bug-bounty-update.jpeg[align="center"]
Cool..Many thanks for that Tahla. I will replace them 👍

2022-08-25 13:13 UTC, Tschakki commented
Just noticed, the base branch for this PR should be `main`, not `development`, because we need this page in the live docs.

For the `nav.adoc` file, this means the `Intro` section doesn't exist yet, so I would add it under `Products` in the nav.

2022-08-29 09:41 UTC, Tschakki commented
@chris529 it seems the base branch change results in a lot of unwanted changes to be part of this PR.

Please undo all changes not relevant for your PR. The probably easiest way to do it is to open a new PR on the base of the `main` branch, and just close this PR.

2022-08-29 16:54 UTC, closed without merging

2022-08-29 16:56 UTC, chris529 commented
This PR has been closed as it was originally on the development branch, and a new PR has now been created with the same content on the main branch.