Removes key-sequence module and HTTP Plugin API details - Closes -1542
LiskArchive/lisk-legacy-docs pull request #1608
Opened 2022-08-11 14:59 UTC by TalhaMaliktz

Closes #1542

2022-08-12 13:01 UTC, Tschakki requested changes

2022-08-12 13:01 UTC, Tschakki commented on docs/modules/ROOT/nav-sdk.adoc
> +// ****  xref:{url_sdk}references/lisk-framework/sequence-module.adoc[]
this file is currently not used in the docs, `nav.adoc` is the relevant one :)
For SDK, there is a separate `nav.adoc` file in the `docs-sdk` branch

2022-08-12 13:01 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-http.adoc
> +// = HTTP API for Lisk nodes
I think it's safer to completely remove the page

2022-08-12 13:01 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/index.adoc
> +The Lisk SDK contains two default modules: Token and DPoS.
That's not really true, but we can update this later as discussed

2022-08-12 13:01 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/transactions.adoc
> +The Lisk protocol contains two default modules: Token and DPoS. These modules contain five transactions as shown in the table below.
See above comment

2022-08-15 10:13 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/index.adoc
> +The Lisk SDK contains two default modules: Token and DPoS.
I have reverted back to the original sentence.

2022-08-15 10:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/transactions.adoc
> +The Lisk protocol contains two default modules: Token and DPoS. These modules contain five transactions as shown in the table below.
> See above comment

Should I revert these changes to their previous state?

2022-08-15 10:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-http.adoc
> +// = HTTP API for Lisk nodes
Alright, I have removed the file.

2022-08-15 10:49 UTC, TalhaMaliktz commented on docs/modules/ROOT/nav-sdk.adoc
> +// ****  xref:{url_sdk}references/lisk-framework/sequence-module.adoc[]
Should I revert this change? I have made changes in the `nav.adoc file in the `docs-sdk` branch as well. Those changes are present in the other pull request.

2022-08-15 10:49 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/index.adoc
> +The Lisk SDK contains two default modules: Token and DPoS.
Should I revert this change?

2022-08-15 10:51 UTC, Tschakki commented on docs/modules/ROOT/nav-sdk.adoc
> +// ****  xref:{url_sdk}references/lisk-framework/sequence-module.adoc[]
ah, no need, the changes can stay. I just wanted to clarify that changes need to be made in `nav.adoc`  👍

2022-08-15 10:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/nav-sdk.adoc
> +// ****  xref:{url_sdk}references/lisk-framework/sequence-module.adoc[]
Okay

2022-08-15 10:53 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/index.adoc
> +The Lisk SDK contains two default modules: Token and DPoS.
yes, if it doesn't make to much effort, that would be nice :) But they can also stay, because we will revisit this content anyway

2022-08-15 10:54 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/transactions.adoc
> +The Lisk protocol contains two default modules: Token and DPoS. These modules contain five transactions as shown in the table below.
yes, if it doesn't make to much effort, that would be nice :) But they can also stay, because we will revisit this content anyway

2022-08-15 10:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/transactions.adoc
> +The Lisk protocol contains two default modules: Token and DPoS. These modules contain five transactions as shown in the table below.
Ummmm, I have also removed `multisignature group registration` from the `transactions.adoc` file (From the table and from its subsection). What to do about that?

2022-08-15 11:10 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/transactions.adoc
> +The Lisk protocol contains two default modules: Token and DPoS. These modules contain five transactions as shown in the table below.
same. It is not really relevant of the changes stay or not :)

2022-08-15 11:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/lisk-protocol/transactions.adoc
> +The Lisk protocol contains two default modules: Token and DPoS. These modules contain five transactions as shown in the table below.
Cool! Thanks :)

2022-08-15 15:46 UTC, Tschakki approved these changes
LGTM

2022-08-16 08:36 UTC, merged