Removed HTTP Plugin Docs & Reference (SDK Docs)- Closes 1542
LiskArchive/lisk-legacy-docs pull request #1609
Opened 2022-08-12 07:20 UTC by TalhaMaliktz

Closes #1542

2022-08-12 13:04 UTC, Tschakki requested changes
Just one small comment, rest looks good to me!

2022-08-12 13:04 UTC, Tschakki commented on modules/ROOT/pages/plugins/http-api-plugin.adoc
> -= HTTP API plugin
Please remove the complete page directly

2022-08-15 10:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/plugins/http-api-plugin.adoc
> -= HTTP API plugin
Alright done

2022-08-15 15:47 UTC, Tschakki approved these changes
LGTM

2022-08-16 08:38 UTC, merged