Update modules and commands page - Closes #1510
LiskArchive/lisk-legacy-docs pull request #1610
Opened 2022-08-12 15:14 UTC by Tschakki

Closes #1510

2022-08-26 11:46 UTC, ishantiw requested changes

2022-08-26 11:46 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A module is a separate component that contains blockchain-related business logic related to one specific domain or topic of a blockchain application.
Maybe it's better to use a simple statement to make users understand the core purpose of modules.

```suggestion
A module is a component that contains application specific business logic of a blockchain application developed by users.
```

2022-08-26 11:46 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* Defining logic that is executed per transaction.
I think last 2 points enable the first point, maybe we can rephrase it? 
***
Modules perform state changes on Blockchain by,
* Defining logic that is executed per block.
* Defining logic that is executed per transaction.
***

2022-08-26 11:46 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/module.png["Module Anatomy",600, align="center"]
diagram doesn't show up in preview

2022-08-26 11:46 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +** `id`: The command ID.
we don't have command ID now

2022-08-26 11:46 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The module RPC endpoints of a blockchain application can be requested by external services, like a UIs, to get relevant data from the application.
```suggestion
The module RPC endpoints of a blockchain application can be requested by external services, like UIs, to get relevant data from the application.
```

2022-08-26 11:46 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Every module method always extends from the `BaseCommand` class.
```suggestion
Every module command always extends from the `BaseCommand` class.
```

2022-08-26 15:19 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/module.png["Module Anatomy",600, align="center"]
it shows up here: https://liskhq.github.io/lisk-docs/understand-blockchain/sdk/modules-commands.html#blockchain-events

2022-08-29 09:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A module is a separate component that contains blockchain-related business logic related to one specific domain or topic of a blockchain application.
maybe this explanation is a little to general and maybe also confusing, because users are generally people who use the blockchain app, but it is the developer who design the module. How about this?

```suggestion
A module is a discrete component that contains blockchain-related business logic, which is related to one specific domain or topic of the  blockchain application.
```

2022-08-31 13:42 UTC, TalhaMaliktz requested changes
Well, that was a long PR :D. Kudos for presenting everything nicely. I have left a few suggestions for you :)

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Block execution happens when the consensus receives a new block from a peer.
```suggestion
Block execution happens when the consensus domain receives a new block from a peer.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/module.png[right thumb,"Module Anatomy",600, align="center"]
Suggestions for better aesthetics

- The elements inside the diagram should be aligned with each other, either vertically, horizontally or both. 
- The size of all the rectangular elements should be the same just to get a synchronized look. 
- Please use fewer colors.
- Decrease the font size in the elements a bit to get a cleaner look. 
  - Use of bigger font size for elements that are big in scope i.e. components and use a lesser font size for elements that are part of a component.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/command.png["Command anatomy",600, align="center"]
Please see my earlier comment about the diagram aesthetics. Also, the caption is missing in this one so please add a caption.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A module is a separate component that contains blockchain-related business logic related to one specific domain or topic of a blockchain application.
I think breaking the sentences adds clarity to the text.

```suggestion
A module is a discrete component that contains blockchain-related business logic. This logic can be related to a specific domain or a topic of a blockchain application.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +All modules of a blockchain application combined define the complete *on-chain logic* of the blockchain application.
```suggestion
All modules of a blockchain application collectively define the *on-chain logic* of the application.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.The `BaseModule`
Shouldn't there be whitespace between "The" and "BaseModule"? It's there in the raw markdown, however, not in the preview.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +<<blockchain-events>> and <<stores>> of the module are registered in the constructor of a module, for later use in the module.
Is there a followed convention regarding the case of hyperlinks? Usually, hyperlinks are added in _sentence case_, however, I am not sure about the convention followed by us.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.Example: Schema of the `getAllDelegatesResponse` endpoint of the DPoS module
In the preview, it looks like this, the whitespace is skipped in the preview however, the markdown has whitespaces.

**Example: Schema of the**getAllDelegatesResponse**endpoint of the DPoS module**

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The endpoints are defined individually for each module, depending on the module purpose.
I think the readability can be improved with this:
```suggestion
An endpoint is an interface between a module and an external system. Lisk endpoints support RPC communication. The module-specific RPC endpoints can be invoked by external services, like UIs, to get relevant data from the application.

The endpoints are defined individually for each module, depending on the module's purpose.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.The `BaseEndpoint` class
A spacing issue as mentioned earlier.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +export class DPoSEndpoint extends BaseEndpoint {
I think the class name should be `HelloEndpoint` instead of `DPoSEndpoint`, not sure though.
```suggestion
export class HelloEndpoint extends BaseEndpoint {
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +== Stores
A brief description of `Stores` and its subsections such as `BaseStore` and `Off-chainStore` would be nice.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +If a module needs to access certain configuration options, it is required to validate and cache the respective configurations in the `init()` method of a module, like described in the code snippet be
```suggestion
If a module needs to access certain configuration options, it is required to validate and cache the respective configurations in the `init()` method of a module, as described in the code snippet below:
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A method is the interface for the module-to-module communication, and *can perform state mutations* on the blockchain.
```suggestion
A method is an interface for module-to-module communication, and *can perform state mutations* on the blockchain.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Methods are called from other modules or by the module itself, if certain module-specific data is desired to get or set data in the blockchain.
```suggestion
To get or set module-specific data in the blockchain, methods are either called by other modules or by the module itself. 
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +To see an example how to call a module method from another module, look at the following example in the module hooks.
```suggestion
To see an example of how to call a module method from another module, look at the following example in the module hooks.
```

I suppose this will have an example later on.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A command is a group of *state-transition logics triggered by a transaction*, identified by the module and command name of the transaction.
```suggestion
A command is a group of *state-transition logics triggered by a transaction* and is identified by the module and command name of the transaction.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Needs to be unique within the module the command belongs to.
```suggestion
The command name is the unique identifier for the command. 
It needs to be unique within the module the command belongs to.
```

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +You can read more about the id property on {url_json_schema_id}[^].
I think an alternate text for the URL would look nice here.

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* Use path like format for easy readability, (it is not an actual requirement).
Is this tentative information?

2022-08-31 13:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In order to ensure no mixing of any schema with other registered schemas occurs, use one fixed identifier for your app in each ID.
```suggestion
To avoid mixing any schema with other registered schemas, use a fixed identifier for your app in each ID.
```

2022-09-01 15:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.The `BaseModule`
yeah, i think it is an UI issue, when using monospace here. WIll remove monospace as a workaround for now

2022-09-01 15:19 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +<<blockchain-events>> and <<stores>> of the module are registered in the constructor of a module, for later use in the module.
This can be updated in the UI. Currently, all links look the same in regards to styling

2022-09-01 15:20 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.Example: Schema of the `getAllDelegatesResponse` endpoint of the DPoS module
see my comment above

2022-09-01 15:22 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The endpoints are defined individually for each module, depending on the module purpose.
```suggestion
An endpoint is an interface between a module and an external system.
Lisk endpoints support RPC communication.
The module-specific RPC endpoints can be invoked by external services, like UIs, to get relevant data from the application.

The endpoints are defined individually for each module, depending on the module's purpose.
```

2022-09-01 15:23 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +export class DPoSEndpoint extends BaseEndpoint {
There is already an existing todo to update the snippet. Currently, the DPoS endpoint is displayed, so no error here

2022-09-01 15:23 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +== Stores
it's WIP :)

2022-09-01 15:33 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* Use path like format for easy readability, (it is not an actual requirement).
nope

2022-09-02 10:13 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +<<blockchain-events>> and <<stores>> of the module are registered in the constructor of a module, for later use in the module.
I opened a corresponding discussion here: https://github.com/LiskHQ/discussions/discussions/51

2022-09-02 10:25 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.The `BaseModule`
I opened a new issue for this: https://github.com/LiskHQ/lisk-docs/issues/1620

2022-09-26 16:06 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/module.png[right thumb,"Module Anatomy",600, align="center"]
Thanks for the suggestions!

I have updated the diagram design, please let me know your thoughts!

2022-10-06 15:51 UTC, TalhaMaliktz requested changes
Looks great overall :)

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +
```suggestion
A sample `BaseModule` interface is shown in the following code snippet below:
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
Is custom module name an alias of some kind?
What is its efficacy?
Why would the user need to add a **custom module name**? How is this different from the name `HelloModule` itself? Isn't `HelloModule` a user-created module with a name given by the user? I think a little context will help the reader here.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +For a successful registration, each module needs to follow the expected module structure, which is described on this page.
```suggestion
For successful registration, each module needs to follow the expected module structure, which is described on this page.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Modules perform state changes on Blockchain by::
```suggestion
Modules perform state changes on the Blockchain by::
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Each module is constructed as a class which extends from the **BaseModule** interface.
```suggestion
Each module is constructed as a class that extends from the **BaseModule** interface.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
```suggestion
In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` that returns the custom module name.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* *assets*: The schemas to decode module assets in blocks.
A brief introduction to what **assets/schemas** are can be helpful here. I would add a link to a page/section as well that describes assets/schemas in detail. Just like we are doing above for _Commands, Endpoints, and Blockchain Events_.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +export const getDelegateRequestSchema = {
Is `getAllDelegatesResponse ` and `getDelegateRequestSchema ` the same? or is there a correction to be made?

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +. an <<off-chain-store>>
```suggestion
. An <<on-chain-stores,on-chain store, a.k.a module store>>.
. An <<off-chain-store>>.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Both stores are included in the state machine of the blockchain application, though only the data on the on-chain stores is shared and synchronized with other nodes in the network.
Please add the link to the **State Machine Page**.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A module can define one or multiple on-chain- or module stores, to store data in the blockchain that is part of the blockchain state.
```suggestion
A module can define one or multiple **on-chain** or **module stores**, to store data in the blockchain that is part of the blockchain state.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +For example, data like account balances, delegate names and multisignature keys are values that are stored in the on-chain module store.
```suggestion
For example, data like _account balances_, _delegate names_, and _multisignature keys_ are values that are stored in the on-chain module store.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Every module store is extended from the `BaseStore`:
```suggestion
Every module store is extended from the `BaseStore` class:
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +=== On-chain Stores
```suggestion
=== On-chain Store
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.`ModuleEndpointContext` interface
I think we should add info on what the `ModuleEndpointContext` is. A brief two-liner can be useful here for the reader as right now it seems that we are skipping something.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +To call a method of a module, simply send the respective RPC request.
```suggestion
To call an endpoint of a module, simply send the respective RPC request.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +== Endpoints
I would introduce the reader to a generic project/folder structure where they can find Endpoints, Modules, and anything related to the blockchain application as described on this page at the start somewhere and then refer to that directory or its child directory in each section so that the reader knows how we separate these concepts in our code. 

We are doing this in the config section at line # 489

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +An example of how to call a module method from another module:
```suggestion
A module method can be called from another module.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The method `getAvailableBalance` from the Token module is called inside the sidechain registration command verification of the Interoperability module to verify, if the sender of a transaction has en
```suggestion
For example, the method `getAvailableBalance` of the **Token** module is called from the **Interoperability** module at the sidechain registration and command verification step. This method is called to verify if the sender of a transaction has enough balance to pay the transaction fee.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.`interoperability/mainchain/commands/sidechain_registration.ts
```suggestion

.interoperability/mainchain/commands/sidechain_registration.ts
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Blockchain events, or module events, are logs of events that occurred in the blockchain network during block execution.
```suggestion
Blockchain events, or module events, are logs of events that occur in the blockchain network during block execution.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +IMPORTANT: In contrast to xref:{url_understand_rpc_events}[RPC events], Blockchain events are part of the on-chain logic: Each block includes the **event root in the block header**, which is the root
**Just wondering:**

I think from what I remember another difference between the RPC events and the blockchain events from our conversation with Ishan was that there are actually only blockchain events in reality. These events can be accessed through the RPC and we call them RPC events.

A key difference between both could be the reach/scope of each event I guess, like blockchain events strictly stay in the blockchain and if accessed through RPC they kind of become RPC events.

Is this the correct understanding or is there something that I misunderstood?

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +It is automatically emitted everytime a transaction is processed by a module.
```suggestion
The default event is indicating the result of a transaction processing (success/failure).
It is automatically emitted every time a transaction is processed by a module.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +NOTE: Only valid transactions are processed, and therefore *only valid transaction emit the default module event.*
```suggestion
NOTE: Only valid transactions are processed, and therefore *only valid transactions emit the default module event.*
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +See section xref:{url_understand_valid_invalid_txs}[Valid vs invalid transactions] for more ifnormation.
```suggestion
See section xref:{url_understand_valid_invalid_txs}[Valid vs invalid transactions] for more information.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +For example, the following data is required by the `TransferEvent` of thr Token module:
```suggestion
New event types that complement the on-chain business logic of the module can be created by extending from the `BaseEvent` class.

The only mandatory property to define in the event is the `schema`, which defines what custom `data` is required by the event to publish the correct information.

For example, the following data is required by the `TransferEvent` of the Token module:
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Beside the event `data`, `topics` are the second property that can be defined by the developer, when emitting/ publishing a blockhain event.
```suggestion
Besides the event `data`, `topics` are the second property that can be defined by the developer, when emitting/ publishing a blockchain event.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/module.png[600,"Module Anatomy", align="center"]
I think we should use the term **DataStore** instead of **Database** for synchronicity.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/command.png["Command anatomy",600, align="center"]
The text in the diagram such as **Initialization**, **ID**, **Parameters**, **Validation**, and **State changes** are not aligned with the center of the container. Kindly re-distribute the rectangles based on the first two rectangles: **addDependencies** and **init** and then align the text and the other rectangles accordingly.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A command is a group of *state-transition logics triggered by a transaction* and is identified by the module and command name of the transaction.
```suggestion
A command is a group of *state-transition logic triggered by a transaction* and is identified by the module and command name of the transaction.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the command, a custom command name can be defined by implementing a getter `name` which returns the custom command name.
```suggestion
In case it is desired to choose a different name for the command, a custom command name can be defined by implementing a getter `name` that returns the custom command name.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the command, a custom command name can be defined by implementing a getter `name` which returns the custom command name.
Similar comments to custom naming of a Module, what's the efficacy of custom name of a command? This should be elaborated on here.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Root type of the schema must be type object.
```suggestion
The root type of the schema must be a `type` object.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Each command has the following lifecycle hooks, which are executed separately for each command in a block.
I would add a hyperlink for the [hooks](https://en.wikipedia.org/wiki/Hooking).

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* `networkIdentifier`: The identifier of the blockchain network, in which this command is executed.
Is this still correct? I thought it was replaced by `chainID`. Or is this a different concept?

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Additionally, an event will be emitted that provides the information whether a command is executed successfully or failed.
```suggestion
Additionally, an event will be emitted that provides the information on whether a command is executed successfully or failed.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* `networkIdentifier`: The identifier of the blockchain network, in which this command is executed.
A similar question about `networkIdentifier ` as above.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +For example, the `seedReveal` property is added to the block asset in this hook by the Random module.
If the `seedReveal` property hasn't been discussed in the docs so far, I think a footnote to the relevant section of the relevant lip should be pasted here.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.Interface for `TransactionVerifyContext` context
```suggestion
.Interface for `verifyTransaction` context
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Each module must initialize their state using an associated block asset.
```suggestion
Each module must initialize its state using an associated block asset.
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The hook `finalizeGenesisState` is called at the end of xref:{url_understand_genesis_block_execution}[genesis block execution].
```suggestion
The hook `finalizeGenesisState` is called at the end of the xref:{url_understand_genesis_block_execution}[genesis block execution].
```

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  In the "Understand blockchain" category you learn the basic concepts of blockchain applications, including how they are structured and which topics and terms are important to know when developing wit
Since my PR #1635 is going to completely change this page, maybe it's better to safeguard the newly added content somewhere, until we revisit this.

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* Use path like format for easy readability, (it is not an actual requirement).
I see, maybe we should move the "it is not an actual requirement" to a footnote then

2022-10-06 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> += Modules and commands
The content looks good and in sync, however, I feel that the reader has to travel a lot through this page. Can we use `collapsible` for all long snippets to address that?

2022-10-07 08:56 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Modules perform state changes on Blockchain by::
```suggestion
Modules perform state changes on the blockchain by::
```

2022-10-07 09:02 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +
```suggestion
The `BaseModule` class is shown in the following code snippet below:
```

2022-10-07 09:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +
👍🏼

2022-10-07 09:14 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
There is no need to add a custom module name. It is just giving the developer the option to choose a different module name, if they like to.
It is not better or worse than the default module name, it is just different name. I tried to convey that it is purely optional, as I state in the beginning every module has a default module name. Only if a developer don't want to go with that module name for some reason, they have the flexibility to change it.

If you have a concrete suggestion how to make this point clearer here let me know!

2022-10-07 09:16 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Modules perform state changes on Blockchain by::
👍🏼

2022-10-07 09:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
Interesting, please consider this scenario:
If I create a `HelloModule` and later would like to call it `myHelloModule`. I would have to add the name in the getter of the module as you explain in the text.
What I want to know/understand is why would this be necessary. Will it be considered a change in the on-chain logic requiring a hard fork?
Coz if it doesn't require a hard fork, we can simply suggest that the name selection of a module can be improved later on if required with a hard fork as it doesn't affect the on-chain logic.

2022-10-07 10:03 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  In the "Understand blockchain" category you learn the basic concepts of blockchain applications, including how they are structured and which topics and terms are important to know when developing wit
good point, I have renamed the file now.

2022-10-07 10:24 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +export const getDelegateRequestSchema = {
good catch! I will update the title t fit the code example

2022-10-07 10:59 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +== Endpoints
I think it is described in line 620, or are you missing something specific?

2022-10-07 11:11 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +IMPORTANT: In contrast to xref:{url_understand_rpc_events}[RPC events], Blockchain events are part of the on-chain logic: Each block includes the **event root in the block header**, which is the root
Maybe @ishantiw can clarify, but from my understanding we have these 2 different event types:
- blockchain events: onchain, defined by the developer (except the default event)
- rpc events: off-chain, defined by application, list of rpc events is here: https://liskhq.github.io/lisk-docs/api/lisk-node-rpc.html#txpool_newtransaction

2022-10-07 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* Use path like format for easy readability, (it is not an actual requirement).
```suggestion
* It is recommended to use a path like format for easy readability, but it is not an actual requirement.
```
I rephrased the sentence now, to avoid footnote :)

2022-10-07 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Root type of the schema must be type object.
```suggestion
Root type of the schema must be of type `object`.
```

2022-10-07 11:38 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* `networkIdentifier`: The identifier of the blockchain network, in which this command is executed.
good catch! I think this code wasn't updated yet when i copied it. It is fixed now :)

2022-10-07 11:42 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +* `networkIdentifier`: The identifier of the blockchain network, in which this command is executed.
updated 👍

2022-10-07 12:00 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +For example, the `seedReveal` property is added to the block asset in this hook by the Random module.
added footnote

2022-10-07 15:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +== Endpoints
Ummmmm I was thinking about something similar to the following code snippet for each major section like **modules**. A sample directory is present in the [SDK Repository](https://github.com/LiskHQ/lisk-sdk/tree/development/framework/src/modules). 

I think that every blockchain application's module directory will be similar to the one mentioned earlier so I think a small generic structure of only the component that is being described on the page can ease things for the reader.

Modules 
 - Module 1
   - commands **folder**
   - events **folder**
   - stores **folder** 
   - endpoint.ts
   - method.ts
   - module.ts
 - Module 2

Later in the snippet, we can use something like this as a caption/description.
```
modules/Module1/endpoint.ts
modules/Module1/methods.ts
modules/Module1/module.ts
```
With this, by the end of this page, the reader will not only know what **Module and Commands** are but will also be familiar with how they co-exist in the project directory.

2022-10-11 22:20 UTC, ishantiw approved these changes
🎉

2022-10-17 08:06 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> += Modules and commands
Yes, I agree the page is getting very long.
But I already tried to hide various code snippets under `collapsible`, and hiding all of them will not improve overall readability imho.
If the page in total is too long, maybe we can reconsider splitting its contents into several pages, and create a new issue for this. For this PR though I would leave it on one page.

2022-10-17 08:12 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +image::understand-blockchain/sdk/module.png[600,"Module Anatomy", align="center"]
updated the diagram accordingly 👍

2022-10-17 08:49 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +== Endpoints
thanks for the explanation! I was intending to explain the file structure in the development guides, but I agree it makes sense to already introduce it here.

My first thought was to describe modules and commands here in a more general way, as the file structure like mentioned is not mandatory (e.g. if they don't use Lisk Commander to generate the module, they can have a very different file structure for the module).

2022-10-17 14:48 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
generally, the code of the module should not be changed by a developer, after it is added to the application. 
In most cases, it will mean a hardfork.

Updating the module name will always result in a hardfork, as it is the unique identifier of the module inside the application.

2022-10-20 13:27 UTC, TalhaMaliktz requested changes
Looks good! I have left some suggestions and have skipped the parts where you have mentioned TODOs. Regards 😊

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> += Modules and commands
Yes, I would go for splitting it into multiple pages. Creating a new issue sounds like a good idea. 👍🏼

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.The BaseModule
```suggestion
The `BaseModule` class is shown in the following code snippet below:

.The BaseModule
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
I see, in that case, we should add a **Note** somewhere to inform the reader that changing a module in any way once it has been deployed to a blockchain application will result in a hard fork.

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Modules have access to two kind of data stores:
```suggestion
Modules have access to two kinds of data stores:
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +IMPORTANT: Endpoints allow to conveniently *get data from the blockchain application*.
```suggestion
IMPORTANT: Endpoints allow us to conveniently *get data from the blockchain application*.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Methods from other modules are made available to the module by importing them, and adding them as private properties in the `addDependencies()` method, like shown in the code snippet below.
```suggestion
Methods from other modules are made available to the module by importing them, and adding them as private properties in the `addDependencies()` method, as shown in the code snippet below.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +IMPORTANT: In contrast to xref:{url_understand_rpc_events}[RPC events], Blockchain events are part of the on-chain logic: Each block includes the **event root in the block header**, which is the root
```suggestion
IMPORTANT: In contrast to xref:{url_understand_rpc_events}[RPC events], Blockchain events are part of the on-chain logic: Each block includes the **event root in the block header**, which is the root of a Sparse-Merkle-Tree of all blockchain events, that occur in that particular block.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +See section xref:{url_understand_valid_invalid_txs}[Valid vs invalid transactions] for more information.
```suggestion
See the section xref:{url_understand_valid_invalid_txs}[Valid vs invalid transactions] for more information.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +Each module is constructed as a class that extends from the **BaseModule** interface.
```suggestion
Each module is constructed as a class that extends from the **BaseModule** class.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The `BaseModule` interface defines all optional and required properties and hooks of a module that must be implemented for the blockchain application to recognize it as a valid module.
```suggestion
The `BaseModule` class defines all optional and required properties and hooks of a module that must be implemented for the blockchain application to recognize it as a valid module.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The module name is automatically calculated from the class name of the module, if it extends from the <<module-anatomy-the-basemodule,BaseModule>>:
Not sure where this URL points to, I think this needs a correction. 
`<<module-anatomy-the-basemodule,BaseModule>>:`

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +IMPORTANT: The data stored in the off-chain store is not part of the blockchain protocol, and it may be different from machine to machine.
```suggestion
IMPORTANT: The data stored in the off-chain store is not part of the blockchain protocol, and it may differ from machine to machine.
```

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +}
Please update as discussed on slack.

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.state_machine.ts
Please improve the caption as it doesn't describe/relate to the previous sentence and the code snippet.

2022-10-20 13:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +    try {
Please correct the indentation/formatting of the code by removing unnecessary spaces. This is also an issue in multiple snippets so please check and correct accordingly.

2022-10-20 13:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +}
done 👍

2022-10-20 14:06 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +The module name is automatically calculated from the class name of the module, if it extends from the <<module-anatomy-the-basemodule,BaseModule>>:
fixed 👍

2022-10-20 14:44 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +.state_machine.ts
After reviewing the below code snippet, I decided to add a different snippet at this place, and adjusted the content and caption accordingly, please check again :)

2022-10-20 15:01 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +In case it is desired to choose a different name for the module, a custom module name can be defined by implementing a getter `name` which returns the custom module name.
I added a note add the top of the page, because this is not only true for updating the module name, but any code of the module logic in general.

2022-10-20 15:44 UTC, TalhaMaliktz approved these changes
Looks Great 😊

2022-10-20 16:05 UTC, merged