Revamp `RPC API For Lisk Node` page - Closes 1538
LiskArchive/lisk-legacy-docs pull request #1611
Opened 2022-08-19 16:21 UTC by TalhaMaliktz

Closes #1538

2022-08-25 16:15 UTC, mitsuaki-u reviewed
Excellent work! Just one comment: the `chain_getGeneratorList` will now also provide a `nextAllocatedTime`(number) property once https://github.com/LiskHQ/lisk-sdk/pull/7448 is merged

2022-08-26 09:03 UTC, TalhaMaliktz commented
> Excellent work! Just one comment: the `chain_getGeneratorList` will now also provide a `nextAllocatedTime`(number) property once [LiskHQ/lisk-sdk#7448](https://github.com/LiskHQ/lisk-sdk/pull/7448) is merged

Thanks 👍🏼  . I have updated the content based on your feedback. Also, I have added an `Events` section that needs your review.

2022-08-26 15:18 UTC, Tschakki requested changes
Looking good, just a few small suggestions :)

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +== Module and plugin-specific endpoints and events
```suggestion
== Custom RPC endpoints for Modules and Plugins
```

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> += RPC API endpoints for Lisk nodes
```suggestion
= RPC API for Lisk nodes
```

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +TIP: For more information about the public, application endpoints, and events, check out the xref:{url_general_endpoints}[] page.
```suggestion
TIP: For more information about RPC endpoints, events, and the Lisk communication architecture in general, check out the xref:{url_general_endpoints}[] page.
```

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Modules and plugins often expose endpoints and events to the blockchain application. All endpoints and events registered with the application are available as RPC endpoints. For details about modules
```suggestion
Modules and plugins often expose custom endpoints to the blockchain application, which then become available as RPC endpoints.
For details about endpoints for modules and plugins, see xref:{url_modules}[] and xref:{url_plugins}[].
```

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Endpoints and events exposed by Lisk are categorized based on various namespaces. These namespaces point toward various, modules, plugins, and default application-specific endpoints and events. To in
```suggestion
RPC endpoints and events exposed by a blockchain application are categorized based on various namespaces. These namespaces point toward various, modules, plugins, and default application-specific domains.
To invoke an endpoint or to subscribe to an event, combine the name of an endpoint/event with its namespace.
For example:
```

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +. Chain
```suggestion
. <<chain>>
```

adding internal anchors here might be beneficial

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Events exposed by the Lisk RPC node can be subscribed as explained in the xref:{url_subscribe_event}[Subscribing to the events] section. To subscribe to an event, a WebSocket or Inter-Process Communi
Are these all events that are available? E.g. I think it was mentioned that every transactions triggers an event, announcing is the tx failed or was successful, is this included here?

2022-08-26 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +====
Please delete the old content, instead of commenting out.

2022-08-30 07:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +====
Will do.

2022-08-30 07:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Events exposed by the Lisk RPC node can be subscribed as explained in the xref:{url_subscribe_event}[Subscribing to the events] section. To subscribe to an event, a WebSocket or Inter-Process Communi
In total there are eight events as mentioned in the [events.ts file](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/engine/events.ts). Due to the unavailability of some content, I have left a note [here](https://github.com/LiskHQ/lisk-docs/issues/1538) after discussing it with Shu

2022-08-30 09:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +== Module and plugin-specific endpoints and events
Agreed, text updated.

2022-08-30 09:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +TIP: For more information about the public, application endpoints, and events, check out the xref:{url_general_endpoints}[] page.
Agreed, text updated

2022-08-30 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Modules and plugins often expose endpoints and events to the blockchain application. All endpoints and events registered with the application are available as RPC endpoints. For details about modules
Agreed, text updated

2022-08-30 10:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +. Chain
Agreedl text updated

2022-08-30 14:52 UTC, Tschakki approved these changes
Thank you! LGTM :)

Just added a few last suggestions

2022-08-30 14:52 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
A list of the events namespaces, analog to the list for the endpoints at line 42-47 would be nice

2022-08-30 14:52 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +== Usage
Aliases and usage examples are also described on the SDK RPC page updated in #1513 , please add links to the relevant sections at this place. Alternatively, you can update this section also in PR #1513, as you prefer :)

2022-08-30 16:21 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
Done

2022-08-30 16:30 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +== Usage
Ummmm, various Links to the **API Client** and **Subscribing Event** sections are present in this PR. Also, I already updated the Alias section in PR #1513 so not sure about the suggested change there.  The best I can do here is add a tip about the API Client and Subscribing Events section, however, that would be redundant. What do you think?

2022-08-31 12:18 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +== Usage
Hmm, yeah I think the content under the heading `Usage` is maybe not really fitting here, and you are right it is a little redundant to the `aliases` section in #1513. So maybe we can remove the content here, or merge it with the `aliases` section.

On the other hand, the content in the next section `Endpoints` in line 40 explains the usage of the RPC API, and also provides a link to the usage example in #1513. I think we could move this up under the `usage` section, if we want to keep this section(except of the last sentence in line 40).

- Btw we normally use a new line for every new sentence, it makes overview and review easier :)

2022-08-31 14:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +== Usage
Thanks, I have removed the `Usage` section as you suggested. I have also incorporated the new line convention in this file. Will follow it in the future as well :)

2022-09-01 14:56 UTC, merged