Updated `RPC endpoints of a Lisk node` page based on v6 - Closes 1513
LiskArchive/lisk-legacy-docs pull request #1612
Opened 2022-08-24 12:42 UTC by TalhaMaliktz

Closes #1513

2022-08-25 11:17 UTC, Tschakki requested changes

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +image::intro/Communication-architecture-transparent - v1.png[,600 ,align="center"]
The current position of `Endpoints` and `Events` could be a little confusing.

Maybe it makes sense to change the diagram more significantly, to improve the illustration of the Communication architecture.

E.g. There could be a separate component inside or attached to the `application` box, labelled `API Client`.

Inside of the API client, there are endpoints and events available.

From the API client, there could go 3 arrows to the 3 different Transport protocols HTTP, WS, IPC.

Also, I think we can improve the use of colors. Colors should be used for the most relevant parts in the diagram, so imho for example the API client and Transport protocols.

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +It provides an interface to *subscribe* to all events and to *invoke* endpoints of a blockchain application, its modules and plugins.
Should we clarify here, that we mean RPC events, not blockchain events?

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +=== HTTP
I would create this as a new tab, in the same way as the examples for WS & IPC

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +*HTTP* is stateless so, it can only be used for fetching data from an endpoint.
```suggestion
*HTTP* is stateless, so it can only be used for fetching data from an endpoint.
```

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +image::intro/Sdk-interfaces.png[,600 ,align="center"]
The image is not displayed here for me.

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
>  * ... `subscribe` means, the component can subscribe to events.
```suggestion
* ... `subscribe` means, the component can subscribe to RPC events.
```

as we also have blockchain events now, I think it's better to be precise here

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +== Endpoints
```suggestion
=== Endpoints
```

endpoints is a sub-section of interfaces

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +=== How to invoke endpoints
```suggestion
==== How to invoke endpoints
```

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
>  = RPC endpoints of a Lisk node
As this page discusses endpoints and events, maybe it's better to update the title to something more general

```suggestion
= RPC communication of a Lisk node
```

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
>  == Events
```suggestion
=== Events
```

2022-08-25 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +By default, Lisk exposes various events that can be subscribed to get the latest information regarding network, chain, and transactions. These events can be subscribed to, by the following:
Please add a note somewhere here, that mentions that there are also blockchain events which are different to RPC events. Once #1510 is merged, you can add a link to the blockchain events section.

2022-08-26 09:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +image::intro/Sdk-interfaces.png[,600 ,align="center"]
URL updated. It's visible now.

2022-08-26 09:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +=== How to invoke endpoints
Agreed, Updated

2022-08-26 09:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +== Endpoints
Agreed, updated.

2022-08-26 09:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
>  == Events
Agreed, updated

2022-08-26 10:00 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
>  = RPC endpoints of a Lisk node
Agreed, Updated heading.

2022-08-26 10:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +image::intro/Communication-architecture-transparent - v1.png[,600 ,align="center"]
Sure, I will redo the diagram.

2022-08-26 10:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
>  * ... `subscribe` means, the component can subscribe to events.
Agreed, text updated

2022-08-26 11:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +It provides an interface to *subscribe* to all events and to *invoke* endpoints of a blockchain application, its modules and plugins.
Agreed, updated the text accordingly.

2022-08-26 13:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +By default, Lisk exposes various events that can be subscribed to get the latest information regarding network, chain, and transactions. These events can be subscribed to, by the following:
Which page should I direct the reader to?

2022-08-26 16:27 UTC, shuse2 requested changes

2022-08-26 16:27 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +        const decodedBlock = client.block.decode(res);
i think with the new schema, you don't need to decode. it's in JSON by default.
Also, we can remove `process.exit`

2022-08-26 16:27 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +        const decodedBlock = client.block.decode(res);
same in below

2022-08-26 16:27 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +<<events>> and <<endpoints>> are identified by their aliases.
out of scope of this PR, but why is it called aliases?
it JSONRPC it's `method`

2022-08-26 16:27 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +Whilst invoking an endpoint, the first argument is always the <<aliases,alias>>.
`<<aliases,alias>>` is this correct?

2022-08-29 09:06 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +Whilst invoking an endpoint, the first argument is always the <<aliases,alias>>.
yes, it is asciidoc syntax for an internal anchor link

2022-08-29 09:19 UTC, Tschakki requested changes
<img width="437" alt="image" src="https://user-images.githubusercontent.com/1993505/187166024-8768eef2-fdda-4487-89be-cbb0805cd4dd.png">
Die diagram looks really nice overall, but the arrow from WS/IPC to endpoints looks a little off. Would look better attached to the left side of WS/IPC imho.

And for title, change`Communicating with Lisk node via RPV` to `RPC communication of a Lisk node`

2022-08-29 09:19 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +<<events>> and <<endpoints>> are identified by their aliases.
Aliases was a term we used in the past, because the method name in the code does not equal the method name used in the RPC request, because the module/plugin/app domain gets prepended to it in the RPC request. This process needs to be explained to the reader. 

e.g. in the example, `getNodeInfo()` is the method, and `system_getNodeInfo` is the alias for the method.

2022-08-30 08:00 UTC, TalhaMaliktz commented
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/1993505/187166024-8768eef2-fdda-4487-89be-cbb0805cd4dd.png">
> 
> Die diagram looks really nice overall, but the arrow from WS/IPC to endpoints looks a little off. Would look better attached to the left side of WS/IPC imho.
> And for title, change`Communicating with Lisk node via RPV` to `RPC communication of a Lisk node`

<img width="940" alt="Screenshot 2022-08-30 at 12 44 32 PM" src="https://user-images.githubusercontent.com/13951043/187380085-9309fd9c-0132-4faf-9c9e-bb99abf2fb28.png">

I did it this way earlier, however, I found this confusing for the reader. I tried multiple ways to connect these two and those didn't look aesthetically pleasing. That's why I joined the arrows the way they are connected right now. It's either this way or the way that I have earlier committed. So which one should I choose?

2022-08-30 09:14 UTC, Tschakki commented
The overlapping arrows are confusing, because visually, HTTP is also connected to events, which should not be the case. 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/1993505/187398221-b52008f3-7e34-440a-a206-5b83f5afeac7.png">
This is my suggestion for the arrow.

2022-08-30 13:16 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/endpoints.adoc
> +        const decodedBlock = client.block.decode(res);
Agreed, Code Snippets updated.

2022-08-30 14:58 UTC, Tschakki requested changes
I just noticed, that the current page name is not appropriate anymore, the page discusses endpoints and events, and `endpoints.adoc` doesn't reflect that. I suggest updating the page name to `rpc.adoc` because the RPC interfaces of the SDK are discussed here.

If the page name is updated, please also check for existing links on other pages to that page, that require an update as well.

Otherwise all looks good to me :)

2022-08-30 16:14 UTC, TalhaMaliktz commented
> I just noticed, that the current page name is not appropriate anymore, the page discusses endpoints and events, and `endpoints.adoc` doesn't reflect that. I suggest updating the page name to `rpc.adoc` because the RPC interfaces of the SDK are discussed here.
> 
> If the page name is updated, please also check for existing links on other pages to that page, that require an update as well.
> 
> Otherwise all looks good to me :)

Done

2022-09-01 14:45 UTC, Tschakki approved these changes
Thank you!

2022-09-01 14:55 UTC, merged