Update issue templates - Closes #1615
LiskArchive/lisk-legacy-docs pull request #1616
Opened 2022-08-31 12:51 UTC by Tschakki

Closes #1615

2022-09-02 12:54 UTC, chris529 reviewed
Looks good, just a few very minor points 👍

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +What is the intention/ motivation of creating it?
```suggestion
What is the intention/motivation for creating it?
```

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Create a TOC as bullet list, and add more information about the desired content as possible:
```suggestion
Create a TOC in the form of a bullet-point list, and add as much information as possible regarding the desired content:
```

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Choose the branch that should be used as base branch for this issue.
```suggestion
Choose the applicable branch that should be used as the base branch for this issue.
```

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/improvement.md
> +Why  does this content need improvement?
```suggestion
Why does this content need improvement?
```

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/improvement.md
> +Explain, how the content should be improved.
```suggestion
Explain how the content should be improved.
```

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/improvement.md
> +Choose the branch that should be used as base branch for this issue.
```suggestion
Choose the applicable branch that should be used as the base branch for this issue.
```

2022-09-02 12:54 UTC, chris529 commented on .github/ISSUE_TEMPLATE/update-content.md
> +Describe which content is outdated, and how it should be updated
```suggestion
Describe which content is outdated, and how it should be updated.
```

2022-09-05 09:40 UTC, TalhaMaliktz requested changes
Hey, nicely done. Just one small change as discussed. :)

2022-09-05 09:40 UTC, TalhaMaliktz commented on .github/ISSUE_TEMPLATE/improvement.md
> +Define the path and name for the new page in the documentation.
```suggestion
Insert the path of the affected page(s) in the documentation.
```

2022-09-05 16:11 UTC, TalhaMaliktz approved these changes

2022-09-06 09:21 UTC, merged