Update glossary terms in Lisk docs - Closes #1557
LiskArchive/lisk-legacy-docs pull request #1617
Opened 2022-09-01 09:56 UTC by chris529

Closes #1557

2022-09-15 09:35 UTC, vjaiman reviewed
Pushing back the PR.

2022-09-28 14:15 UTC, vjaiman requested changes

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +// An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain a
Not exactly.

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +The API can be defined as the interface for the module-to-module communication.
```suggestion
The API is defined as the interface for the module-to-module communication.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Generally speaking these are module methods which are called during the actual block generation.
```suggestion
These are module methods which are called during the actual block generation.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Within the mainchain, only active delegates are classed as consenters, hence this does not apply to standby delegates.
I am not sure if you have to follow these [aligned terminologies](https://docs.google.com/spreadsheets/d/1lfOiBytQwj9J_cQ7IS_H08g_nZJLwX9o27k0SZoyMGs/edit#gid=1394845996).

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +An active delegate is now known as a <<consenter>>.
I am not sure about it also. Please confirm if you have to follow [aligned terminologies](https://docs.google.com/spreadsheets/d/1lfOiBytQwj9J_cQ7IS_H08g_nZJLwX9o27k0SZoyMGs/edit#gid=1394845996).

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +The weight of a delegate is the sum of all votes for a particular delegate.
```suggestion
The weight of a delegate is the sum of all votes for a particular delegate that includes self-votes.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Simply put an endpoint is one end of a communication channel.
```suggestion
In general, an endpoint is one end of a communication channel.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Finally, a reward is added to the account sending the PoM
```suggestion
Finally, a reward is added to the account sending the PoM.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +A reducer can be classed as a function that can derives a new state from an input, and can also change the state.
```suggestion
A reducer is a function that derives a new state from an input, and can change the state.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +The reward is calculated depending on the rules of the <<Random Module>> and the <<BFT Module>>.
```suggestion
The reward can be reduced which depends on the rules of the <<Random Module>> and the <<BFT Module>>.
```

2022-09-28 14:15 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +The interoperability module provides basic functionalities that will allow the transmission of information between interoperable chains in the Lisk ecosystem using cross-chain messages.
```suggestion
The interoperability module provides functionalities that will allow the transmission of information between interoperable chains in the Lisk ecosystem using cross-chain messages.
```

2022-09-29 13:54 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +// An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain a
I have added in the following to complement the basic description, so it now reads as follows:
"An account can be classed as any data associated with an address. Accounts are serialized and deserialized according to the account schema".
Let me know your thoughts, and please adapt/update if necessary.

2022-09-29 14:46 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +Within the mainchain, only active delegates are classed as consenters, hence this does not apply to standby delegates.
Well, we currently have 2 terminology sheets at present, so I am trying to use both of them to build the terminology descriptions.
https://docs.google.com/spreadsheets/d/1lfOiBytQwj9J_cQ7IS_H08g_nZJLwX9o27k0SZoyMGs/edit#gid=1394845996 
https://docs.google.com/spreadsheets/d/1PEBQdKQj6WDsblT5qwLzRiODlNVce7ORV6HvZQB2RrY/edit?pli=1#gid=0 

One is maintained by the devs and the other is maintained by the research team.

2022-09-29 15:08 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +An active delegate is now known as a <<consenter>>.
See the comment above.

2022-10-12 09:04 UTC, vjaiman requested changes

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +An account is an address together with the state information associated to the address.
```suggestion
An account is an address with an amount of tokens referred to as balance. The address is a unique identifier which has state information associated with it.
```

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Furthermore, accounts are serialized and deserialized according to the account schema.
```suggestion
// Furthermore, accounts are serialized and deserialized according to the account schema.
```

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +
I suppose there is no address initialization now.

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Within the mainchain only active delegates are classed as consenters, hence this does not apply to standby delegates.
There is no consenter. I think we should use the aligned terminologies across all departments.

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +
General comment: All terms are not consistent. Either use Sentence case or the other one.

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +The general technique of how the mainchain and sidechains communicate.
You can add also: It means that information from another blockchain is accepted if the correctness of this information is attested by a certificate.

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Cross-chain commands (CCMs), are responsible for triggering the logic defined by the cross-chain command, that is identified by both the module name and the cross-chain command name.
```suggestion
Cross-chain messages (CCMs), are responsible for triggering the logic defined by the cross-chain command, that is identified by both the module name and the cross-chain command name.
```

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +In addition, information about the registered validators in its module store is maintained, together with providing the generator list.
```suggestion
// In addition, information about the registered validators in its module store is maintained, together with providing the generator list.
```

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
>  === Testnet
```suggestion
=== Lisk Testnet
```

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
>  === Mainnet
```suggestion
=== Lisk Mainnet
```

2022-10-12 09:04 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which locks the token used for votes.
```suggestion
A transaction type on all networks based on the Lisk protocol which unlocks the token used for votes.
```

2022-10-12 12:34 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +// An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain a
It sounds great!👍

2022-10-12 13:02 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +
I believe you are correct Vikas, as I understand this was for older versions of the protocol, therefore it has now been removed.

2022-10-12 13:20 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +
👍

2022-10-12 13:31 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +The general technique of how the mainchain and sidechains communicate.
Updated accordingly 👍

2022-10-12 16:41 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +Within the mainchain, only active delegates are classed as consenters, hence this does not apply to standby delegates.
As per our discussion the Consenter term has been removed 👍

2022-10-12 16:41 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +An active delegate is now known as a <<consenter>>.
Consenter is removed 👍

2022-10-12 16:48 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +Within the mainchain only active delegates are classed as consenters, hence this does not apply to standby delegates.
Consenter has been removed 👍

2022-10-14 10:26 UTC, vjaiman approved these changes
Looks all good.

2022-10-19 13:10 UTC, TalhaMaliktz requested changes
Looks good :) I have left some suggestions 👍🏼

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +:url_delegate_registration_tx: {lisk-docs}run-blockchain/forging.adoc#create-the-delegate-registraton-transaction
As the `glossary.adoc`is part of the `lisk-docs`, we don't need to mention the docs domain here for the correct path.
```suggestion
:url_delegate_registration: run-blockchain/forging.adoc#registering-a-delegate
:url_delegate_registration_tx: run-blockchain/forging.adoc#create-the-delegate-registraton-transaction
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +:url_data_structure: {lisk-docs}understand-blockchain/lcodec-schema.adoc#data-types
Same as the above comment, Please correct it at other places as well.
```suggestion
:url_data_structure: understand-blockchain/codec-schema.adoc#data-types
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +=== PoA - Proof of authority
```suggestion
=== PoA - Proof of Authority
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  In all front-end products, addresses are displayed in a human-readable representation called <<lisk32-representation>>.
I think the "**Lisk32 representation**" should be changed to the "**Lisk32 format**" as the term 'format' is a more familiar term in the computing domain. 
I am not sure whether this choice of terminology is from the Research so what do you think?

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  An example for an address in Lisk32 presentation is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
```suggestion
An example of an address in the Lisk32 presentation is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  In the Lisk protocol and SDK only the 20 byte value is stored for efficiency and sometimes the hexadecimal representation of the address is used.
```suggestion
In the Lisk protocol and SDK, only the 20-byte value is stored for efficiency and sometimes the hexadecimal representation of the address is used.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.
Haven't the terms 'delegate' and 'forging' depreciated?

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The API is defined as the interface for the module-to-module communication.
```suggestion
The API is defined as the interface for module-to-module communication.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +Furthermore, an updated multisignature registration is now used, based upon new registration params.
```suggestion
Furthermore, an updated multisignature registration process is now used, based on the new registration parameters.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
Should be the following on line 105:

=== BCH Codes - Bose, Chaudhuri, and Hocquenghem codes

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
Should be the following on line 112

A Beddow is the smallest unit of an LSK token. 100 million Beddows is equal to 1 <<LSK>>.

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  In a system whereby components need to come to an agreement to reach consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard t
```suggestion
In a system whereby components need to come to an agreement to reach a consensus,  byzantine failures will prevent those components from reaching an agreement, (usually caused by errors that are hard to detect).
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The weight of validators that is considered in Lisk-BFT for finalizing blocks and for creating valid certificate signatures.
```suggestion
The weight of validators that are considered in Lisk-BFT for finalizing blocks and for creating valid certificate signatures.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  and how to create a human readable mnemonic sentence including how to convert that mnemonic into a seed.
```suggestion
A Bitcoin Improvement Proposal (BIP), can be defined as a standard for proposing changes to the Bitcoin protocol.
For example, BIP39 is one of many bitcoin improvement proposals.
This particular proposal describes the mnemonic code or mnemonic sentence implementation,
and how to create a human-readable mnemonic sentence including how to convert that mnemonic into a seed.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The block assets contains data created by individual modules.
```suggestion
The block assets contain data created by individual modules.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.
What does the "Rank 1-101" describes? I think a one-liner should be added here.
```suggestion
An active delegate can mostly be considered as a forging delegate, who can forge new blocks for the Lisk blockchain. Rank 1-101.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +It is used when sending tokens to a specific chain and also prepended for signing to protect against replay attacks.
```suggestion
It is used when sending tokens to a specific chain and is also prepended for signing to protect against replay attacks.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +It is added the outbox of the sending chain, later to the respective certificates, and eventually to the inbox of the receiving chain.
```suggestion
It is added to the outbox of the sending chain, later to the respective certificates, and eventually to the inbox of the receiving chain.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A xref:{url_delegate_registration}[delegate registration] is achieved by sending a xref:{url_delegate_registration_tx}[delegate registration transaction] on the mainnet, which registers a delegate to
The terms delegate/s forge/r have been depreciated, so we need to update according to the new terms which are generator and block generation, etc. This goes for the entire docs for v6.
```suggestion
A xref:{url_delegate_registration}[delegate's registration] is achieved by sending a xref:{url_delegate_registration_tx}[delegate registration transaction] on the mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +If voting weight was added, the corresponding LSK are locked and cannot be used for any other transaction.
```suggestion
If voting weight was added, the corresponding LSKs are locked and cannot be used for any other transaction.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +It is computed from the self-votes and total amount of received votes.
```suggestion
The weight of delegates in DPoS determines whether a delegate is active, on standby, or not eligible to generate blocks.
It is computed from the self-votes and the total amount of received votes.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  The Lisk SDK provides dedicated genesis block and configurations to conveniently set up a local Devnet during development of a blockchain application.
```suggestion
The Lisk SDK provides a dedicated genesis block and configurations to conveniently set up a local Devnet during the development of a blockchain application.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  It is part of the consensus algorithm of a blockchain and used on Lisk Mainnet and in the Lisk SDK.
```suggestion
It is part of the consensus algorithm of a blockchain and is used on Lisk Mainnet and in the Lisk SDK.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +Events are on-chain data emitted during the processing of a block which add additional information regarding the execution of state transitions.
```suggestion
Events emit on-chain data during the processing of a block which adds additional information regarding the execution of state transitions.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  A fork can basically be defined as an occurrence of a blockchain diverging into two forward paths in the network.
```suggestion
A fork can be defined as an occurrence of a blockchain diverging into two forward paths in the network.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  In other words it is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.
```suggestion
In other words, it is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  For further detailed information regarding forking in the Lisk network, see the following {url_fork}[Lisk Mainnet hard fork process^] description in the Lisk Mainnet Regenesis page
```suggestion
For further detailed information regarding forking in the Lisk network, see the following {url_fork}[Lisk Mainnet hard fork process^] description on the Lisk Mainnet Regenesis page.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  A self-contained, off chain component which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin.
```suggestion
A self-contained, off-chain component that extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A generator can mostly be considered as a forging generator, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.
```suggestion
A generator can mostly be considered as a forging generator, which can forge new blocks for the Lisk blockchain. Rank 1-101.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  It defines the initial state of the blockchain on start of the network.
```suggestion
It defines the initial state of the blockchain at the start of the network.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The inbox is a data structures that contain information relevant to verify and process a certificate.
```suggestion
The inbox is a data structure that contains information relevant to the verification and processing of a certificate.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  Lisk Framework is an application framework responsible for establishing and maintaining the interactions between the modules of a blockchain application compatible with the Lisk protocol. It provides
```suggestion
Lisk Framework is an application framework responsible for establishing and maintaining the interactions between the modules of a blockchain application compatible with the Lisk protocol. It provides an application where off-chain and on-chain logic can be extended with user-defined plugins and modules.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  Furthermore, a LIP also describes the requirements, rationale and motivation for the required changes.
```suggestion
Furthermore, a LIP also describes the requirements, rationale, and motivation for the required changes.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The mainchain can be defined as series of blocks created from the initial genesis block to the latest block.
```suggestion
The mainchain can be defined as a series of blocks created from the initial genesis block to the latest block.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A method is the interface for the module-to-module communication.
```suggestion
A method is an interface for module-to-module communication.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +Modules are able to perform state changes on the related blockchain.
```suggestion
A module enables a blockchain application to have application-specific on-chain logic.
Modules can perform state changes on the related blockchain.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +If the message fee is at least the minimum return fee that the receiving sidechain guarantees, that in case of an error a failure message will be returned.
I am unable to understand the definition of Minimum return fee, so maybe we can re-word this somehow?

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A unique identifier in the Lisk ecoysystem for a specific NFT created by the NFT module.
```suggestion
A unique identifier in the Lisk ecosystem for a specific NFT created by the NFT module.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The outbox is a data structures that contain information relevant to verify and process a certificate.
```suggestion
The outbox is a data structure that contains information relevant to the verification and processing of a certificate.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  Nodes fulfill many important roles in the network, like synchronising new events in the network between each other, adding new blocks to the blockchain, and providing APIs for external services in or
```suggestion
Nodes fulfill many important roles in the network, like synchronising new events in the network with each other, adding new blocks to the blockchain, and providing APIs for external services in order to communicate with the network.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  Validators are responsible for ordering transactions and creating new blocks, so that all nodes are able to agree on the current state of the network.
```suggestion
Validators are responsible for ordering transactions and creating new blocks so that all nodes can agree on the current state of the network.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +By using a <<BFT - Byzantine fault tolerance>> algorithm with identity as a stake, PoA is an efficient mechanism, and enables relatively faster transactions to be completed.
```suggestion
By using a <<BFT - Byzantine fault tolerance>> algorithm with identity as a stake, PoA is an efficient mechanism as it enables relatively faster transaction completion.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  Hence, the PoW mechanism allows consensus to be reached whilst simultaneously maintaining the network security.
```suggestion
Hence, the PoW mechanism allows consensus to be reached whilst simultaneously maintaining network security.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  A peer to peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.
```suggestion
A peer-to-peer network is a group of nodes (devices), that make up a decentralized network that can collectively share and store data, whereby each node acts as an individual peer.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The Random module handles the validation of the inputs and computation of outputs for the commit and reveal process for a Lisk blockchain, and in addition defines a random substore whose value contai
```suggestion
The Random module handles the validation of the inputs and computation of outputs for the commit and reveal process for a Lisk blockchain, and in addition, defines a random substore whose value contains the validator reveals array.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +It can be thought of as an instance of a blockchain which is used for testing purposes, and consists of a the same version of the mainnnet underlying software.
```suggestion
It can be thought of as an instance of a blockchain which is used for testing purposes and consists of the same version of the mainnet underlying software.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Lisk Testnet
This should be moved to the "L" section.

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A unique identifier in the Lisk ecoysystem for a token type (e.g., LSK) created by the token module.
```suggestion
A unique identifier in the Lisk ecosystem for a token type (e.g., LSK) created by the token module.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  The votes are aggregated and used to compute the delegate weight, which in turn is used to assign blocks to delegates. However, it should be noted that as the delegate vote will be capped by the self
```suggestion
The votes are aggregated and used to compute the delegate weight, which in turn is used to assign blocks to delegates. However, it should be noted that as the delegate vote will be capped by the self-vote, the total votes might not be equal to the delegate weight.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  In other words it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.
```suggestion
In other words, it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +Participants in charge of generating and finalizing blocks in a sidechain.
```suggestion
Participants which are in charge of generating and finalizing blocks in a sidechain.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +In short a wallet will store the public and private keys and can interface with various blockchains, enabling the users to monitor their balance, send tokens and conduct other operations.
```suggestion
In short, a wallet will store the public and private keys and can interface with various blockchains, enabling the users to monitor their balance, send tokens and conduct other operations.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  They are actively maintained and provide the most secure and easiest way to access the users LSK tokens.
```suggestion
They are actively maintained and provide the most secure and easiest way to access the users' LSK tokens.
```

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  More details can be found in the xref:{url_hash_onion}[enable forging] section.
The URL is incorrect as now I think we are using type doc for code referencing instead of creating a .adoc file in the lisk docs repo. The URL that points to the type doc page is this:
https://liskhq.github.io/lisk-docs/lisk-sdk/references/typedoc/lisk-elements/modules/cryptography.html#hashOnion

I am not sure so maybe we can ask @Tschakki

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +:url_reclaim_lsk: {docs-core}index.adoc#lsk-reclaim
You need to define the `docs-core` variable for the URL to work correctly. Otherwise you can simply use the `lisk-core::` value instead of `{docs-core}`

2022-10-19 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  The xref:{url_state_store}[state store] is used to mutate the state of the blockchain data, or to retrieve data from the blockchain, and can also be thought of as a temporary data structure that hold
Similar case as described earlier about TypeDoc. The URL can be based on the following URL:

https://liskhq.github.io/lisk-docs/lisk-sdk/references/typedoc/lisk-elements/modules/chain.html

2022-10-19 13:10 UTC, TalhaMaliktz requested changes
Looks good :) I have left some suggestions 👍🏼

2022-10-19 15:00 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +:url_delegate_registration_tx: {lisk-docs}run-blockchain/forging.adoc#create-the-delegate-registraton-transaction
OK cool...Many thanks Talha! 👍

2022-10-19 15:31 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +:url_data_structure: {lisk-docs}understand-blockchain/lcodec-schema.adoc#data-types
Great! Many thanks again Talha, I have now updated the links accordingly 👍

2022-10-19 15:32 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +=== PoA - Proof of authority
Well spotted! 👍

2022-10-20 08:36 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  More details can be found in the xref:{url_hash_onion}[enable forging] section.
Thanks Talha, Yes I am also unsure about this one... I will check with Mona 👍

2022-10-20 09:02 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  In all front-end products, addresses are displayed in a human-readable representation called <<lisk32-representation>>.
Yes, good point. I also checked with Sergey, and he suggested it would be OK to change it to "Lisk32 format" 👍

2022-10-20 09:06 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  The xref:{url_state_store}[state store] is used to mutate the state of the blockchain data, or to retrieve data from the blockchain, and can also be thought of as a temporary data structure that hold
OK, I have updated the link as above, so it should be OK once the staging version is deployed online.

2022-10-20 09:32 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +If voting weight was added, the corresponding LSK are locked and cannot be used for any other transaction.
Good point. I have reworded it as follows "If voting weight was added, the corresponding LSK tokens are locked and cannot be used for any other transaction".

2022-10-20 09:39 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.
In general yes, although according to the terminology sheet we will still use 'delegate' when referring to DPoS. However, I have removed this entry 👍 
'Forging' is now 'Generating'

2022-10-20 09:48 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
I think it should remain as it is, as we usually would use 'a' if the following word begins with a consonant sound, and use 'an' if the word begins with a vowel sound.

2022-10-20 11:54 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.
Good point, and now updated as discussed in Slack 👍

2022-10-20 12:04 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Lisk Testnet
Done 👍

2022-10-20 12:38 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
> +If the message fee is at least the minimum return fee that the receiving sidechain guarantees, that in case of an error a failure message will be returned.
OK, I have reworded it 👍

2022-10-24 14:52 UTC, TalhaMaliktz requested changes
Looks Good. Just a few minor comments

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +An account is an address with an amount of tokens referred to as the balance.
```suggestion
An account is an address with a number of tokens referred to as the balance.
```

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  An example for an address in Lisk32 presentation is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
```suggestion
An example of an address in the Lisk32 format is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
```

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A total of 101 validators exist in Lisk blockchain, for this purpose and each validator is ranked from 1-101.
```suggestion
A total of 101 validators exist in the Lisk blockchain for this purpose, and each validator is ranked from 1-101.
```

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +All testing and experimentation can be performed on the testnet without jeopardizing the actual mainnet.
```suggestion
The official testing network of Lisk.
It can be thought of as an instance of a blockchain that is used for testing purposes and consists of the same version of the mainnet underlying software.
All testing and experimentation can be performed on the testnet without jeopardizing the actual mainnet.
```

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The minimum part of the fee should be burned, this is to avoid that validators can send transactions in the blocks they generate without cost.
```suggestion
The minimum fee should be burned to make sure that validators can't send transactions in the blocks they generate without a cost.
```

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A xref:{url_token_transfer}[Token transfer] transaction will transfer the amount of tokens specified in the amount property, from the sender of the transaction to the specified recipient.
```suggestion
A xref:{url_token_transfer}[Token transfer] transaction will transfer the number of tokens specified in the amount property, from the sender of the transaction to the specified recipient.
```

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
Should be the following on line 715:

A number of LSKs required for sending a transaction to the Lisk blockchain.

2022-10-24 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  BCH codes are error-correcting codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
```suggestion
BCH codes are error-correcting codes. The Bose, Chaudhuri, and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
```

2022-10-25 08:16 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
Done 👍

2022-10-25 08:21 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  More details can be found in the xref:{url_hash_onion}[enable forging] section.
As discussed, I have removed the line referring to the link 👍

2022-10-26 16:40 UTC, TalhaMaliktz approved these changes
Looks good, just one minor change, and then all is good from my side. :)

2022-10-26 16:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A property of a cross-chain message that is an amount of LSK tokens that are credited to the relayer in the receiving chain.
```suggestion
It is a property of a cross-chain message that represents the number of LSK tokens that are credited to the relayer in the receiving chain.
```

2022-10-27 08:00 UTC, merged