Updated SDK-->Application Cli - Closes 1540
LiskArchive/lisk-legacy-docs pull request #1621
Opened 2022-09-02 15:15 UTC by TalhaMaliktz

Closes #1540

2022-09-05 09:28 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output        The output directory. Default will set to current working directory.
It seems we are missing a verb and article here. The original statement looked correct, so I wondered why it was changed..?
If you don't like the original statement, we could always reword it to something along these lines.."The default setting will enable the current working directory''...?

2022-09-05 09:47 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output        The output directory. Default will set to current working directory.
Ummmm, I have copied/pasted the contents for all application CLI commands since I wasn't sure about the change. Hence, the original statements have been changed. Should we reword these descriptions? I didn't do it because I wanted to keep the content synchronous with the application CLI and the documentation.

2022-09-05 10:31 UTC, chris529 reviewed
Looks good, just a couple of minor points 👍

2022-09-05 10:31 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +Creates a transaction which can be broadcasted to the network.
```suggestion
Creates a transaction that can be broadcasted to the network.
```

2022-09-05 10:31 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -s, --sender-public-key=sender-public-key      Creates the transaction with provided sender publickey, when passphrase is not provided
```suggestion
  -s, --sender-public-key=sender-public-key      Creates the transaction with the provided sender publickey, when the passphrase is not provided
```

2022-09-05 11:33 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output        The output directory. Default will set to current working directory.
I think most of them look fine. You could maybe just check them again, and in addition, I will also have another look 
 on the next review round 👍

2022-09-05 11:37 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output        The output directory. Default will set to current working directory.
Cool, Will take another look :)

2022-09-06 08:36 UTC, chris529 reviewed
Looking good, just a few minor points 👍

2022-09-06 08:36 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  autocomplete  Displays autocomplete installation instructions
```suggestion
  autocomplete  Displays autocomplete installation instructions.
```

2022-09-06 08:36 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -f, --assets-file=assets-file                                                              Path to file which contains genesis block asset in JSON format
```suggestion
  -f, --assets-file=assets-file                                                              Path to the file which contains the genesis block asset in JSON format.
```

2022-09-06 08:36 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run transaction:create  Create a transaction that can be broadcasted to the network. Note: fee and amount should be in Beddows!!
```suggestion
  ./bin/run transaction:create  Create a transaction that can be broadcasted to the network. Note: The fee and amount should be in Beddows!!
```

2022-09-06 08:36 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  --network-identifier=network-identifier        Network identifier defined for the network or main | test for the Lisk Network.
Network identifier defined for the network or main | test for the Lisk Network.

This statement doesn't appear to be so clear...Do you think maybe we should enhance/reword this slightly..?

2022-09-06 08:36 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path                      Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path                      Directory path to specify where the node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-06 16:20 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  --network-identifier=network-identifier        Network identifier defined for the network or main | test for the Lisk Network.
How does this look?

```suggestion
  --network-identifier=network-identifier        A network identifier for Lisk. The accepted value is either "main" or "test".
```

2022-09-07 07:57 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  --network-identifier=network-identifier        Network identifier defined for the network or main | test for the Lisk Network.
Sounds good 👍

2022-09-07 08:20 UTC, chris529 submitted a review, later dismissed
LGTM 👍

2022-09-08 14:26 UTC, sitetester requested changes

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path                            Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
Defaults to `~/.lisk/dpos-mainchain/data/ `

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -l, --log=trace|debug|info|warn|error|fatal          File log level. Environment variable "LISK_FILE_LOG_LEVEL" can also be used.
In general, we should know, how much effect it has on logging if we change `level` to `debug`

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -n, --network=network                                [default: default] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
Possible options `mainnet`, `devnet`, `testnet`
TODO: Github issue/task

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run config:create  Creates network configuration file.
Creates `application`  configuration file.

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output                              [default: /Users/iamtalha/Documents/GitHub/lisk-sdk/examples/dpos-mainchain] Directory where the config file is saved
`/Users/iamtalha/` username shouldn't be shown in any kind of logs / outputs. 
Should be replaced with a dummy name

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -t, --token-distribution=token-distribution                                                [default: 100000000000] Amount of tokens distributed to each account.
`--token-distribution` could be renamed to `--tokens`, if we agree, then need a Github issue for that.

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  $ ./bin/run node:metadata
```
$ ./bin/run node:metadata --pretty
{
  "error": {
    "message": "Request 'node_getMetadata' is not registered to bus."
  }
}
```

Either this needs to be removed or code needs to be updated

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run transaction:create  Create a transaction that can be broadcasted to the network. Note: The fee and amount should be in Beddows!!
I think, 2nd form of `broadcast` is also `broadcast`

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run transaction:create token transfer 100000000 --params='{"amount":100000000,"recipientAddress":"ab0041a7d3f7b2c290b5b834d46bdc7b7eb85815","data":"send token"}'
```
$ ./bin/run transaction:create token transfer 100000000 --params='{"amount":100000000,"recipientAddress":"ab0041a7d3f7b2c290b5b834d46bdc7b7eb85815","data":"send token"}'
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
Warning: Passphrase contains 1 words instead of expected 12. Passphrase contains 0 whitespaces instead of expected 11. 
Error: Lisk validator found 1 error[s]:
Missing property, must have required property 'tokenID'
    at LiskValidator.validate (~/Projects/lisk-sdk/elements/lisk-validator/src/lisk_validator.ts:74:10)
    at Object.validateTransaction (~/Projects/lisk-sdk/elements/lisk-transactions/src/validate.ts:36:12)
    at Object.signTransactionWithPrivateKey (~/Projects/lisk-sdk/elements/lisk-transactions/src/sign.ts:109:27)
    at validateAndSignTransaction (~/Projects/lisk-sdk/commander/src/bootstrapping/commands/transaction/create.ts:132:23)
    at CreateCommand.run (~/Projects/lisk-sdk/commander/src/bootstrapping/commands/transaction/create.ts:319:24)
    at CreateCommand._run (~/Projects/lisk-sdk/node_modules/@oclif/command/lib/command.js:43:20)
    at Config.runCommand (~/Projects/lisk-sdk/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (~/Projects/lisk-sdk/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (~/Projects/lisk-sdk/node_modules/@oclif/command/lib/command.js:43:20)
```
it asks for `tokenID`, hence there should be example value of `tokenID` also

```
Please enter: tokenID:  0000000000000000
```

2022-09-08 14:26 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  080810011880cab5ee012220fd061b9146691f3c56504be051175d5b76d1b1d0179c5c4370e18534c58821222a2408641214ab0041a7d3f7b2c290b5b834d46bdc7b7eb858151a0a73656e6420746f6b656e324028edd3601cdc35a41bb23415a0d9f
How is this `hex` ID different from a `hex` ID of `eab06c6a22e88bca7150e0347a7d976acd070cb9284423e6eabecd657acc1263` ? (length wise)

2022-09-08 16:12 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  $ ./bin/run node:metadata
@ishantiw @shuse2 - https://github.com/LiskHQ/lisk-sdk/issues/7512

2022-09-08 16:19 UTC, shuse2 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path                            Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
it doesn't not default to `~/.lisk/dpos-mainchain/data/`. 
data path is `os.homedir()` `.lisk`, `application name`

2022-09-09 09:50 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path                            Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
Lisk commander could be updated to give this description, which is concatenation of os.homedir() .lisk, application name
TODO: Github issue/task

2022-09-09 10:37 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path                            Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
https://github.com/LiskHQ/lisk-sdk/issues/7511

2022-09-09 10:37 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  -n, --network=network                                [default: default] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
https://github.com/LiskHQ/lisk-sdk/issues/7511

2022-09-09 10:45 UTC, sitetester requested changes

2022-09-09 10:45 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  forger-info    Commands relating to dpos-mainchain forger-info data.
`forger-info` is removed

```
./bin/run forger-info --help

 ›   Error: command forger-info not found
 $ 

```
$ ./bin/run
Lisk-SDK Application

VERSION
  dpos-mainchain/0.1.0 darwin-x64 node-v16.15.0

USAGE
  $ dpos-mainchain [COMMAND]

TOPICS
  account        Commands relating to dpos-mainchain accounts.
  block          Commands relating to dpos-mainchain blocks.
  blockchain     Commands relating to dpos-mainchain blockchain data.
  blskey         Return bls public & private keys corresponding to the given passphrase.
  config         Commands relating to dpos-mainchain node configuration.
  endpoint       Invokes the provided endpoint.
  generator      Commands relating to dpos-mainchain forging and generator-info data.
  genesis-block  Creates genesis block file.
  keys           Commands relating to account, generator and bls keys.
  node           Commands relating to dpos-mainchain node.
  passphrase     Commands relating to dpos-mainchain passphrases.
  transaction    Commands relating to dpos-mainchain transactions.

COMMANDS
  autocomplete  display autocomplete installation instructions
  console       Lisk interactive REPL session to run commands.
  hash-onion    Create hash onions to be used by the forger.
  help          display help for dpos-mainchain
  start         Start Blockchain Node.
 $ 
```

2022-09-09 10:45 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  forging        Commands relating to dpos-mainchain forging.
same as above (removed)

2022-09-09 11:21 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  --offline                                      Specify whether to connect to a local node or not.
Lisk Commander's description needs to be updated to give more info what it means to be `online` or `offline` 
- https://github.com/LiskHQ/lisk-sdk/issues/7511

2022-09-09 16:39 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run config:create  Creates network configuration file.
Agree, text updated

2022-09-12 10:52 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output                              [default: /Users/iamtalha/Documents/GitHub/lisk-sdk/examples/dpos-mainchain] Directory where the config file is saved
Agreed, text updated

2022-09-12 10:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  forging        Commands relating to dpos-mainchain forging.
Agreed, text updated

2022-09-12 10:55 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  -o, --output=output                              [default: /Users/iamtalha/Documents/GitHub/lisk-sdk/examples/dpos-mainchain] Directory where the config file is saved
Agreed, text updated

2022-09-12 10:55 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  forger-info    Commands relating to dpos-mainchain forger-info data.
Agreed, text updated

2022-09-12 10:56 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  -t, --token-distribution=token-distribution                                                [default: 100000000000] Amount of tokens distributed to each account.
cc: @shuse2 @ishantiw

2022-09-12 11:20 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  $ ./bin/run node:metadata
Faced the same issue at my end, awaiting for advise regarding this issue.

2022-09-12 13:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run transaction:create token transfer 100000000 --params='{"amount":100000000,"recipientAddress":"ab0041a7d3f7b2c290b5b834d46bdc7b7eb85815","data":"send token"}'
Agreed, text updated.

2022-09-12 17:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  080810011880cab5ee012220fd061b9146691f3c56504be051175d5b76d1b1d0179c5c4370e18534c58821222a2408641214ab0041a7d3f7b2c290b5b834d46bdc7b7eb858151a0a73656e6420746f6b656e324028edd3601cdc35a41bb23415a0d9f
Not sure, maybe something happened during copy/paste.

2022-09-14 12:02 UTC, chris529 reviewed
Looks good, just a few minor points 👍

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  --overwrite-config                                   Overwrite network configs if they exist already
```suggestion
  --overwrite-config                                   Overwrite network configs if they exist already.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +? Are you sure you want to reset the db? yes
```suggestion
? Are you sure you want to reset the db? Yes
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  ./bin/run keys:encrypt  Encrypt keys from a file and overwrite the file
```suggestion
  ./bin/run keys:encrypt  Encrypt keys from a file and overwrite the file.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +Warning: Passphrase contains 24 words instead of expected 12. Passphrase contains 23 whitespaces instead of expected 11.
```suggestion
Warning: Passphrase contains 24 words instead of the expected 12. Passphrase contains 23 whitespaces instead of the expected 11. 
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -k, --key-derivation-path=key-derivation-path  [default: m/25519'/134'/0'/0'] Key derivation path to use to derive keypair from passphrase
```suggestion
  -k, --key-derivation-path=key-derivation-path  [default: m/25519'/134'/0'/0'] Key derivation path to use to derive keypair from passphrase.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -c, --count=count            [default: 1] Number of keys to create
```suggestion
  -c, --count=count            [default: 1] Number of keys to create.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -f, --offset=offset          Offset for the key derivation path
```suggestion
  -f, --offset=offset          Offset for the key derivation path.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -i, --chainid=chainid        Chain id
```suggestion
  -i, --chainid=chainid        Chain id.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -n, --no-encrypt             No encrypted message object to be created
```suggestion
  -n, --no-encrypt             No encrypted message object to be created.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  autocomplete  Display autocomplete installation instructions
```suggestion
  autocomplete  Display autocomplete installation instructions.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  help          Display help for dpos-mainchain
```suggestion
  help          Display help for dpos-mainchain.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -f, --force                Delete and overwrite existing blockchain data
```suggestion
  -f, --force                Delete and overwrite existing blockchain data.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH"
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" 
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH"
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" 
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH"
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" 
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 12:02 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" can also be used.
```

2022-09-14 15:16 UTC, chris529 submitted a review, later dismissed
LGTM! 👍

2022-09-14 18:57 UTC, sitetester requested changes

2022-09-14 18:57 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  console       Lisk interactive REPL session to run commands.
Need to mention, `Note that  it's only JavaScript REPL.`

2022-09-14 18:57 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +$ ./bin/run start --api-ipc --api-http
`./bin/run start --api-ipc`

2022-09-14 18:57 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +Provides the Lisk interactive {url_read_eval_print_loop}[REPL] session to run commands.
JavaScript REPL

2022-09-14 18:57 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +$ ./bin/run block:get 2 --pretty
- Here `./bin/run block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4 --pretty` doesn't work, I created issue for it - https://github.com/LiskHQ/lisk-sdk/issues/7527

```
$ ./bin/run block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4 --pretty
Error: Specified key 03e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4 does not exist
    at Object.convertRPCError (~/Projects/lisk-sdk/elements/lisk-api-client/src/utils.ts:19:2)
    at IPCChannel._listenToRPCResponse (~/Projects/lisk-sdk/elements/lisk-api-client/src/ipc_channel.ts:147:39)
```

- No action needed here

2022-09-14 18:57 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +ARGUMENTS
Arguments naming don't match 

```
$ ./bin/run generator:enable
 ›   Error: Missing 4 required args:
 ›   address                    Address of an account in a lisk32 format.
 ›   height                     Last forged block height.
 ›   maxHeightPreviouslyForged  Delegates largest previously forged height.
 ›   maxHeightPrevoted          Delegates largest prevoted height for a block.
 ›   See more help with --help
```
Issue created https://github.com/LiskHQ/lisk-sdk/issues/7529, but it's closed for now

2022-09-14 18:57 UTC, sitetester commented on modules/ROOT/pages/application-cli.adoc
> +  080810011880cab5ee012220fd061b9146691f3c56504be051175d5b76d1b1d0179c5c4370e18534c58821222a2408641214ab0041a7d3f7b2c290b5b834d46bdc7b7eb858151a0a73656e6420746f6b656e324028edd3601cdc35a41bb23415a0d9f
It comes from `./bin/run transaction:create token transfer 100000000 --json --passphrase="peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready" --key-derivation-path=legacy`

2022-09-15 07:17 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +$ ./bin/run start --api-ipc --api-http
I see that you have a strong opinion about it, may I know why? as the existing example is correct and it also shows the use of two parameters to the reader. It tells the reader that you can start your server with `--api-ipc` and `--api-http` together as well. I also see similar usage in SDK threads and repositories so why change that?

2022-09-15 09:07 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +  console       Lisk interactive REPL session to run commands.
Agreed, text updated.

2022-09-15 09:07 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +$ ./bin/run start --api-ipc --api-http
Agreed, text updated.

2022-09-15 09:07 UTC, TalhaMaliktz commented on modules/ROOT/pages/application-cli.adoc
> +Provides the Lisk interactive {url_read_eval_print_loop}[REPL] session to run commands.
Agreed, text updated.

2022-09-15 09:49 UTC, sitetester submitted a review, later dismissed

2022-09-15 10:01 UTC, chris529 reviewed
Looking very good, just a few very minor points 👍

2022-09-15 10:01 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -f, --assets-file=assets-file  (required) Path to file which contains genesis block asset in JSON format
```suggestion
  -f, --assets-file=assets-file  The path to the file which contains the genesis block asset in JSON format, (Mandatory).
```

2022-09-15 10:01 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH"
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" 
```

2022-09-15 10:01 UTC, chris529 commented on modules/ROOT/pages/application-cli.adoc
> +  -d, --data-path=data-path  Directory path to specify where node data is stored. The environment variable "LISK_DATA_PATH"
```suggestion
  -d, --data-path=data-path  Directory path to specify where the node data is stored. The environment variable "LISK_DATA_PATH" 
```

2022-09-15 10:13 UTC, chris529 approved these changes
LGTM! 👍

2022-09-15 10:48 UTC, merged