Create Interoperability & crosschain-communication pages - Closes #1516 & #1496
LiskArchive/lisk-legacy-docs pull request #1623
Opened 2022-09-05 15:29 UTC by Tschakki

Closes #1516 & #1496

2022-09-07 07:20 UTC, ricott1 requested changes

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
Adding comment here. CCM image is wrong, should use updated schema, see: https://github.com/LiskHQ/lips/blob/update-interoperability-LIPs/proposals/lip-0049.md#cross-chain-message-schema

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Basically, cross-chain certification means that information from one chain is submitted to another chain utilizing a signed object called a *certificate*.
```suggestion
Basically, cross-chain certification means that information from one chain is authenticated and included in another chain utilizing a signed object called a *certificate*.
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The information is transmitted across chains by issuing a Cross-Chain Update transaction, aka CCU, including a certificate, that verifies the correctness of the data in the CCU.
```suggestion
This information is transmitted across chains by issuing a Cross-Chain Update transaction, aka CCU.
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +A CCU can contain multiple cross-chain messages.
```suggestion
The CCU includes the certificate and the cross-chain messages coming from the sending chain.
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Cross-chain messages contain commands which can be executed on the opposite chain.
```suggestion
Cross-chain messages contain cross-chain commands which are executed on the receiving chain.
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +**The maximum of sidechains being simultaneously connected to the Lisk mainchain is currently around 3,5 million.**
I would remove this sentence, it is true in a sense, but maybe it is just confusing here. I would however change the following one as suggested

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +== Mainchain & sidechains
```suggestion
The maximum number of sidechains that can be registered in the Lisk ecosystem is only capped by the maximum number of CCU transactions that the Lisk Mainchain can integrate. In this sense, it is practically unlimited.
====

== Mainchain & sidechains
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +As explained in section <<cross-chain-network-topology>> above, the Lisk blockchain network is structured in two general kinds of network particpants:
```suggestion
As explained in section <<cross-chain-network-topology>> above, the Lisk blockchain network is structured in two general kinds of network participants:
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +the *Lisk Mainchain*, and *sidechains*, which are connected to each other via the Mainchain.
I see what you mean, but I find the formulation a bit strange, to say that mainchain and sidechains are connected via the mainchain. Maybe we could just rewrite the first two sentences as smtg like:

In the Lisk ecosystem, sidechains are connected to each other via the mainchain. 

And then explain that all sidechains have to first register on the mainchain, then register the mainchain on the sidechain and then post a first CCU to start communicate with each other. I would even go as far as to have a bullet list point that enumerates all the steps as clearly as possible.

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The token used on the mainchain, LSK, has a special role in the ecosystem, too:
And crucially LSK is used to pay transaction fees on the mainchain, where CCUs from the sidechains have to be posted

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Apart from the special roles of the mainchain mentioned above, *the mainchain is not different to any other sidechain in the network.*
I find this sentence misleading, like, of course apart from this major difference there is no other difference. I would remove it

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The mainchain and each sidechain differ mainly from each other by the modules which are registered in the blockchain application.
Here I think the real difference is that a user cannot modify the mainchain protocol. In order to develop and deploy a dapp they have to spin up a sidechain (we are not a smart contract platform)

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The LSK token is the only token that can be transferred to every chain within the Lisk ecosystem.
I don't think this is necessarily true. @gkoumout ?

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* The color of a transaction or cross-chain message is always the one of the receiving chain, except for a cross-chain update transaction whose color is the one of the sending chain.
this should maybe go in the caption of the image

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +.Additional educxational resources to learn about the Lisk interoperability solution
```suggestion
.Additional educational resources to learn about the Lisk interoperability solution
```

2022-09-07 07:20 UTC, ricott1 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Assume we have an exchange chain, a prediction market chain, and an oracle chain connected to the mainchain.
Maybe we can come up with a better example using one of the grant applications? Also, Penrose is not the most recent Nobel prize winner in physics anymore :)

2022-09-07 08:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
```suggestion
```

2022-09-07 09:21 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Apart from the special roles of the mainchain mentioned above, *the mainchain is not different to any other sidechain in the network.*
Ofc there is difference between different blockchains, but not structurally. Any sidechain could become mainchain if the network decides on it, as far as I understand.

I will try to rephrase to make it clearer.

2022-09-07 09:25 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The mainchain and each sidechain differ mainly from each other by the modules which are registered in the blockchain application.
This paragraph is comparing mainchain & sidechains structurally. The characteristics of blockchain applications compared to smart contract platforms will be covered on the `understand-blockchain/sdk/index.html` page

2022-09-07 09:29 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Assume we have an exchange chain, a prediction market chain, and an oracle chain connected to the mainchain.
We can take that as an improvement suggestion for the future, when we have more time ti improve. For first version, the example is good enough imho.

2022-09-07 10:32 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Assume we have an exchange chain, a prediction market chain, and an oracle chain connected to the mainchain.
created a corresponding issue for this: https://github.com/LiskHQ/lisk-docs/issues/1625

2022-09-22 13:09 UTC, chris529 reviewed
Looks great! Just some minor points.. 👍

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +On this page, we dive deeper into the details how cross-chain communication works in the Lisk ecosystem, by describing the different components and the general processes, how state changes are execut
```suggestion
On this page, we dive deeper into the details of how cross-chain communication works in the Lisk ecosystem, by describing the different components and the general processes, and how state changes are executed across chains in the Lisk ecosystem.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +But in case of a CCM, the command always refers to a cross-chain command, and the state changes are not only executed in the sending chain, but also in the receiving chain.
```suggestion
However in the case of a CCM, the command always refers to a cross-chain command, and the state changes are not only executed in the sending chain, but also in the receiving chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +nonce:: When a cross-chain message is created and added to the partner chain outbox, the nonce of the sending chain (total number of messages that were added to outboxes so far) is added to the messa
```suggestion
nonce:: When a cross-chain message is created and added to the partner chain outbox, the nonce of the sending chain (total number of messages that were added to outboxes so far), is added to the message in the nonce property.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Being the main utility token of the Lisk ecosystem, the LSK token is always the token ID for this fee for channels between the Lisk mainchain and registered sidechains.
```suggestion
Being the main utility token of the Lisk ecosystem, the LSK token is always the token ID for this fee for the channels between the Lisk mainchain and registered sidechains.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-1.png[,300,role="right"]
In the ccc-1.png diagram, I would recommend rewording the description in Step 2 to the following:
"Sidechain processes the CCT (executing the required state changes, creating CCMs, and moving them to the outbox)''

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Here is where *cross-chain transactions (CCTs)* come into play.
```suggestion
Here is where the *cross-chain transactions (CCTs)* come into play.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The only difference is, that a CCT refers to a **cross-chain command**, instead of a normal command.
```suggestion
The only difference is that a CCT refers to a **cross-chain command**, instead of a normal command.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +A cross-chain command will:
```suggestion
A cross-chain command will perform the following:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +In the example, the CC-transfer will deduct 5 LSK from Alices balances once the transaction is included in a block.
```suggestion
In the example, the CC-transfer will deduct 5 LSK from Alices balance once the transaction is included in a block.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Several cross-chain messages are collected together and posted to another chain as part of a cross-chain update transactions, aka CCU.
```suggestion
Several cross-chain messages are collected together and posted to another chain as part of the cross-chain update transaction, aka CCU.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/ccu.png[,300,role=right]
Minor point, but in this diagram just as we have 'Inbox Update', (both words starting with upper case), to maintain uniformity here, I think it would look better if we have 'Validators Update' instead of 'Validators update'?

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +If `newCertificateThreshold` is set to `0`, it implies that the certificate threshold has not been changed in the sending chain.
```suggestion
If the `newCertificateThreshold` is set to `0`, it implies that the certificate threshold has not been changed in the sending chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Therefore, obtaining the information required to post a cross-chain update transaction is straightforward, and can be done by anyone, simply by setting up a relayer node.
```suggestion
Therefore, obtaining the information required to post a cross-chain update transaction is straightforward, and can be performed by anyone, simply by setting up a relayer node.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-2.png[,300,role="right"]
In the ccc-2.png diagram, I would recommend rewording the description in Step 2 to the following:
"Sidechain processes the CCT (executing the required state changes, creating CCMs, and moving them to the outbox)''

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-3.png[,300,role="right"]
In diagram ccc-3.png, there is a minor error/typo in step 6a...It should read as the following:
"If validation is successful....''

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-4.png[,300,role="right"]
In diagram ccc-4.png, there is a minor error in step 10...It should read as the following:
"If validation **is** successful....''

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +To ensure, that only intended state changes are performed on the receiving chain, the CCM is validated at several stages of the cross-chain communication.
```suggestion
To ensure that only intended state changes are performed on the receiving chain, the CCM is validated at several stages of the cross-chain communication.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +This design choice allows sidechains to send messages to other chains without needing to monitor the status (or even existence) of every other chain.
```suggestion
This design choice allows sidechains to send messages to other chains without the need to monitor the status (or even existence), of every other chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|CHANNEL UNAVAILABLE|uint32|3|status assigned on the mainchain if the receiving chain is not available (it does not exist, it is not active, or it has been terminated).
```suggestion
|CHANNEL UNAVAILABLE|uint32|3|Status assigned on the mainchain if the receiving chain is not available (it does not exist, it is not active, or it has been terminated).
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The status code provides crucial information to the blockchain application how to process / forward a CCM.
```suggestion
The status code provides crucial information to the blockchain application on how to process/forward a CCM.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-2b.png[,300,role="right"]
In the ccc-2b.png diagram, I would recommend rewording the description in Step 2 to the following:
"Sidechain processes the CCT (executing the required state changes, creating CCMs, and moving them to the outbox)''
In Step 6b there is a minor typo (Validation), and it appears there are 2 different fonts used in this sentence.

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +When a CCU is relayed from a sending chain to the mainchain, the mainchain checks for all CCMs in the inbox update, if:
```suggestion
When a CCU is relayed from a sending chain to the mainchain, the mainchain checks for all CCMs in the inbox update, if the following criteria are met:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* the receiving chain exists
```suggestion
* the receiving chain exists.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Instead, a relayer on the mainchain will include the CCM in a new CCU and post is *back to the sending chain.*
```suggestion
Instead, a relayer on the mainchain will include the CCM in a new CCU and post it *back to the sending chain.*
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +For example, if Alice on Sidechain X sends 5 LSK to Bob on Sidechain Y, but Sidechain Y is not registered on the mainchain, the error handling would work as follows:
```suggestion
For example, if Alice on Sidechain X sends 5 LSK to Bob on Sidechain Y, but Sidechain Y is not registered on the mainchain, the error handling process would function as follows:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Mainchain receives corresponding CCM & performs validations
```suggestion
. Mainchain receives corresponding CCM & performs validations.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Sending chain undoes related state changes: 5 LSK are added back to Alice's account, because the cross-chain transfer was not successfull.
```suggestion
. Sending chain undoes related state changes: 5 LSK are added back to Alice's account, because the cross-chain transfer was unsuccessful.```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-3b.png[,300]
In diagram ccc-3b, There are some typos in Step 11b. It should read as: ''Relayer collects the CCM and includes it in a CCU''

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +When a CCU is relayed from the mainchain to the receiving chain, the receiving chain checks for all CCMs in the inbox update, if:
```suggestion
When a CCU is relayed from the mainchain to the receiving chain, the receiving chain checks for all CCMs in the inbox update, if the following criteria are met:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* the receiving application understands the particular command, i.e. if it includes the required module to interpret the command name
```suggestion
* the receiving application understands the particular command, i.e. if it includes the required module to interpret the command name.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* the CCM includes all parameters required for the CC-command
```suggestion
* the CCM includes all parameters required for the CC-command.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Instead, a relayer on the receiving chain will include the CCM in a new CCU and post is *back to the mainchain*, and from there to the sending chain.
```suggestion
Instead, a relayer on the receiving chain will include the CCM in a new CCU and post it *back to the mainchain*, and from there to the sending chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +For example, if Alice on Sidechain X sends 5 LSK to Bob on Sidechain Y, but Sidechain Y does not support the token module, the error handling would work as follows:
```suggestion
For example, if Alice on Sidechain X sends 5 LSK to Bob on Sidechain Y, but Sidechain Y does not support the token module, the error handling process would function as follows:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Mainchain receives corresponding CCM & performs validations
```suggestion
. Mainchain receives corresponding CCM & performs validations.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Mainchain relays CCM to the receiving chain via a CCU
```suggestion
. Mainchain relays CCM to the receiving chain via a CCU.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Sending chain undoes related state changes: 5 LSK are added back to Alices account, because the cross-chain transfer was not successful.
```suggestion
. Sending chain undoes related state changes: 5 LSK are added back to Alices account, because the cross-chain transfer was unsuccessful.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +To summarize, the complete flow of cross-chain communciation is described in the diagram:
```suggestion
To summarize, the complete flow of cross-chain communication is described in the diagram below:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/cc-cmmunication-flow.png[]
In the cc-cmmunication-flow.png diagram, I would recommend rewording the description in Step 2 to the following:
"Sidechain processes the CCT (executing the required state changes, creating CCMs, and moving them to the outbox)''

In Step 6a there is a minor typo, (Validation), and should read as:
''If validation is successful..."

In Step 6b there is a minor typo, (Validation), and it appears there are 2 different fonts used in this sentence.

In Step 10a it should read as: ''If validation is successful...."

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Cross-chain certificates are a scalable and efficient solution that allows the passing of any kind of information between chains.
```suggestion
Cross-chain certificates are a scalable and efficient solution that facilitates the transfer of all kinds of information between chains.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +This can mutate the state of the receiving chain in response to state changes that happened on the sending chain.
```suggestion
This can mutate the state of the receiving chain in response to state changes that occurred on the sending chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +For this, she sends a cross-chain token transfer transaction, `t`, on the sending chain.
```suggestion
To achieve this, she sends a cross-chain token transfer transaction, `t`, on the sending chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Similar to transactions, cross-chain messages have an `params` property.
```suggestion
Similar to transactions, cross-chain messages have a `params` property.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +As shown by the image above, a Lisk blockchain can become interoperable to any other blockchain in the Lisk ecosystem including the Lisk Mainchain, simply by registering itself to the mainchain.
```suggestion
As shown by the image above, a Lisk blockchain can become interoperable with any other blockchain in the Lisk ecosystem including the Lisk Mainchain, simply by registering itself to the mainchain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +.What is the maximum of connected sidechains to the Lisk Mainchain?
```suggestion
.What is the maximum number of connected sidechains to the Lisk Mainchain?
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +As explained in section <<cross-chain-network-topology>> above, the Lisk blockchain network is structured in two general kinds of network participants:
```suggestion
As explained in the section <<cross-chain-network-topology>> above, the Lisk blockchain network is structured with regard to the two following general types of networks:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +To become a sidechain in the Lisk ecosystem, a blockchain application needs to perform three simple steps:
```suggestion
To become a sidechain in the Lisk ecosystem, a blockchain application needs to perform the following three simple steps:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +. Register on the mainchain,
```suggestion
. Register on the mainchain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +. Register the mainchain on the sidechain,
```suggestion
. Register the mainchain on the sidechain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +NOTE: Because sidechains communicate through the mainchain with other sidechains, they only need to maintain one connection to the mainchain, which will reduce complexity and point-of-failure signifi
```suggestion
NOTE: Because sidechains communicate through the mainchain with other sidechains, they only need to maintain one connection to the mainchain, which will significantly reduce both the complexity and the point-of-failure.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Meaning, any sidechain could be used as mainchain, as long as it integrates the required interoperability modules.
```suggestion
This means that any sidechain could be used as the mainchain, as long as it integrates the required interoperability modules.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Actually this means, that sidechains can also register directly on another sidechain, and breaking the star topology.
```suggestion
Furthermore, this also means that sidechains can also register directly on another sidechain, and therefore break the star topology.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The token used on the mainchain, LSK, has a special role in the ecosystem, too:
```suggestion
The token used on the mainchain, LSK, has a special role in the ecosystem as described below:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Because of the network topology, there are two different ways for cross-chain communication:
```suggestion
Due to the topology of the network, there are two different ways for cross-chain communication:
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Involves creation of one CCU on the sending chain, that is posted to the receiving chain.
```suggestion
Involves the creation of one CCU on the sending chain, that is posted to the receiving chain.
```

2022-09-22 13:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Involves creation of two CCUs:
```suggestion
Involves the creation of two CCUs:
```

2022-10-12 08:23 UTC, AndreasKendziorra requested changes

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/consensus/bft.adoc
> += Lisk BFT
I guess this file, as well as the ones for certificates and dpos-poa are not related to the issues 1516 and 1496. Do you want to have these changes and this PR, or is it an accident?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
Right. I created this diagram some time ago, and I think it was never correct due intentional simplifications. Here, we could be correct. The content of the CCM could be displayed like this:
```
receivingChainID: 1234
params:
    amount: 800,000,000
    tokenID: <LSK tokenID>
    recipientAddress: <Bob's address>
    ...
...
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +== Example of Interoperability Usage
Capitalization of headers is not coherent. Here, it is used. In most other headers not.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +:fn_tx: footnote:tx[See xref:{url_understand_tx}[Understand blockchain, Transactions.] for more information about transactions.]
```suggestion
:fn_tx: footnote:tx[See xref:{url_understand_tx}[Understand blockchain, Transactions] for more information about transactions.]
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +:fn_command: footnote:command[See xref:{url_understand_command}[Modules and commands]. for more information about commands.]
```suggestion
:fn_command: footnote:command[See xref:{url_understand_command}[Modules and commands] for more information about commands.]
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +As shown by the image above, a Lisk blockchain can become interoperable with any other blockchain in the Lisk ecosystem including the Lisk Mainchain, simply by registering itself to the mainchain.
```suggestion
As shown by the image above, a Lisk blockchain can become interoperable with any other blockchain in the Lisk ecosystem including the Lisk Mainchain, simply by registering itself on the mainchain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The maximum number of sidechains that can be registered in the Lisk ecosystem is only capped by the maximum number of CCU transactions that the Lisk Mainchain can integrate.
Maybe "include" or "process" instead of "integrate"?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +[TIP]
This rather sounds like a note to me instead of a tip.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Each step of the lifecycle of a sidechain is explained in further detail on the page xref:{url_understand_sidechainlifecycle}[].
Do you really want to have this line when the linked content is empty?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +This means that any sidechain could be used as the mainchain, as long as it integrates the required interoperability modules.
```suggestion
This means that any sidechain could be used as the mainchain, as long as it integrates the interoperability module.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Structurally, the mainchain is not any different from any other sidechain.
This section assumes "direct sidechain communication" which will only be implemented in the diamond phase. Should the documentation be based on the Sapphire phase or should it include features coming in the Diamond phase?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Structurally, the mainchain is not any different from any other sidechain.
I also learned from @janhack that it is not clear yet if "direct sichechain channels" will be implemented eventually. Maybe this section should be skipped?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +The LSK token is the only token that can be transferred to every chain within the Lisk ecosystem.
This statement is true. Every chain implementing the token module supports the LSK token. See [here](https://github.com/LiskHQ/lips/blob/f753a106c38c0a308b3737e4e8f1df1ac05bccac/proposals/lip-0051.md?plain=1#L177)

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +It is the default token for transaction fees on sidechains, but it is possible to configure a sidechain token for the transaction fees.
This statement exists already in the previous section (line 123).

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +. CCU from mainchain chain to receiving chain
```suggestion
. CCU from mainchain to receiving chain
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +.Sidechain-to-Sidechain communication via the Mainchain: The color of a transaction or cross-chain message is always the one of the receiving chain, except for a cross-chain update transaction whose
```suggestion
.Sidechain-to-Sidechain communication via the mainchain: The color of a transaction or cross-chain message is always the one of the receiving chain, except for a cross-chain update transaction whose color is the one of the sending chain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +.Sidechain-to-Sidechain communication via the Mainchain: The color of a transaction or cross-chain message is always the one of the receiving chain, except for a cross-chain update transaction whose
I guess we only capitalize "Lisk Mainchain" but not "mainchain", right?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* All three cross-chain messages are delivered in one cross-chain update transaction, `CCU1`, to the mainchain, where `m1` and m3 are processed, but not `m2`.
```suggestion
* All three cross-chain messages are delivered in one cross-chain update transaction, `CCU1`, to the mainchain, where `m1` and `m3` are processed, but not `m2`.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* Later on, `m2` is delivered to sidechain 2 by a cross-chain update transaction, `CCU2`, from the mainchain to `sidechain 2`.
```suggestion
* Later on, `m2` is delivered to `sidechain 2` by a cross-chain update transaction, `CCU2`, from the mainchain to `sidechain 2`.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Another example use case for Lisk interoperability was presented at Lisk.js 2021 by Alessandro Ricottone:
The pirates of the 7 chains example is rather showing how to build an interoperable chain with the SDK. But i would not say it's an example use case of interoperability.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Cross-chain messages, or CCMs, are the central component of the cross-chain communication between different sidechains.
> between different sidechains.

it also holds for communication between mainchain and sidechains

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +However in the case of a CCM, the command always refers to a cross-chain command, and the state changes are not only executed in the sending chain, but also in the receiving chain.
> command [...] refers to a cross-chain command

I think it's bit misleading to say that a command is referring to a CC-command. It would be more correct to say that "the command is a specific command, called cross-chain command" 

> the state changes are not only executed in the sending chain, but also in the receiving chain.

I would remove this statement from here, because the state changes in the sending chain are not due to the CCM but due to the cross-chain transaction

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +sending-chain ID:: Used to identify the chain sending the cross-chain message.
It should be "sending chain ID". See the[sheet](https://docs.google.com/spreadsheets/d/1lfOiBytQwj9J_cQ7IS_H08g_nZJLwX9o27k0SZoyMGs/edit#gid=0&range=C31) on aligned names. The same holds for "receiving chain ID"

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +parameters:: The params property of the messages is defined by each module and can follow any schema, similar to the `params` property of a transaction.
```suggestion
parameters:: The `params` property of the messages is defined by each module and can follow any schema, similar to the `params` property of a transaction.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Let's look at a example of a simple cross-chain transfer between Alice and Bob.
```suggestion
Let's look at an example of a simple cross-chain transfer between Alice and Bob.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The only difference is that a CCT refers to a **cross-chain command**, instead of a normal command.
This is not correct. It refers to a "regular" command as any other transaction. The difference is that it creates one or more CCMs.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +sending-chain ID:: Identifies the chain sending the cross-chain update.
same as above: "sending chain ID"

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +validators update:: The chain account stores an array containing the BLS keys and BFT weights required to validate the certificate signature.
The property was at some point renamed to `activeValidatorsUpdate`

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +This array has to be updated if the validator set changes in the chain sending the certificate.
```suggestion
This array has to be updated if the validator set changes in the chain sending the CCU.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +certificate:: Verifies the correctness of the data sent in the CCU.
```suggestion
certificate:: Authenticates the data sent in the CCU.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Consists of aggregated signatures of a set of the current validators of the sending chain.
```suggestion
It contains an aggregate signature of a set of the current validators of the sending chain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +new certificate threshold:: The threshold of block generators required to validate the certificate signature.
It was renamed to `certificateThreshold`.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/ccu.png[,300,role=right]
It should be "BFT Weight" instead of "BLS Weight"

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +new certificate threshold:: The threshold of block generators required to validate the certificate signature.
```suggestion
new certificate threshold:: The threshold of block generators in term of BFT weight required to validate the certificate signature.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. the `crossChainMessages`:
for consistency, I would remove "the"

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. `messageWitness`:
It was renamed to `messageWitnessHashes`, and it's concept changed. It should be:

`messageWitnessHashes`: In the sending chain, all cross-chain messages are added to a regular Merkle tree attested by the outbox root. The `messageWitnessHashes` are the sibling hashes necessary for the Merkle proof. This Merkle proof is required if not all messages necessary to recompute the outbox root were given in `crossChainMessages`. If all messages required to compute the outbox root are included in `crossChainMessages` then `messageWitnessHashes` can be left empty.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The `outboxRootWitness` property is an inclusion proof into the state root of the outbox root computed from the receiving chain inbox, `crossChainMessages` and `messageWitness`.
I find this sentence easy to misinterpret and would split it like this (I know it's copied from the LIP):

The `outboxRootWitness` property is an inclusion proof into the state root of the outbox root. The outbox root itself can be computed from the from the receiving chain inbox, `crossChainMessages` and `messageWitness`.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.. If the certificateThreshold used to create `certificate.validatorsHash` is different from the one stored in the chain account, include the new value in the `newCertificateThreshold` property.
```suggestion
.. If the certificateThreshold used to create `certificate.validatorsHash` is different from the one stored in the chain account, include the new value in the `certificateThreshold` property.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +After the CCM has been created in step <<using-cross-chain-transactions-to-generate-ccms>>, it is added to the outbox of the sending chain X.
I'm not sure if this is supposed to refer to an existing section, and if it's supposed to be rendered nicely?

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +From the outbox, a *relayer* collects the CCMs and creates a CCU with the properties described in step <<transferring-ccms-in-a-ccu>>.
same as before

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +After the CCM is included in the inbox of the mainchain, the mainchain performs the most important validations on the CCM.
I guess here you are talking about a CCM that is coming from one sidechain and is supposed to be routed to another sidechain? If so, that's not very clear.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +== Executing the CCC on the receiving chain
Do you mean CCM instead of CCC? If you mean cross-chain command, then the abbreviation was never defined.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +If the validation is completed successfully, the CC-Transfer command is performing the intended state changes on the receiving chain, i.e. adding 5 LSK to Bobs account.
```suggestion
If the validation is completed successfully, the cross-chain command is performing the intended state changes on the receiving chain, i.e. adding 5 LSK to Bobs account.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|OK|uint32|0|The default status of a cross-chain message.
1. The values are not up-to-date. See [here](https://github.com/LiskHQ/lips/blob/4dfe5ef853277dbae3b6c925fa2e98ca20e6460e/proposals/lip-0045.md?plain=1#L189-L193)
2. the value CCM_STATUS_CODE_FAILED_CCM is missing

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|MODULE NOT SUPPORTED|uint32|1|Status assigned on the receiving chain if it does not implement any module with ID equal to the message module ID.
```suggestion
|MODULE NOT SUPPORTED|uint32|1|Status assigned on the receiving chain if it does not implement any module with the name equal to the `module` property of the CCM.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|CROSS CHAIN COMMAND NOT SUPPORTED|uint32|2|Status assigned on the receiving chain if it does not implement any command with ID equal to the message command ID.
```suggestion
|CROSS CHAIN COMMAND NOT SUPPORTED|uint32|2|Status assigned on the receiving chain if it does not implement any command with the name equal to the `crossChainCommand` property of the CCM.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Instead, a relayer on the mainchain will include the CCM in a new CCU and post it *back to the sending chain.*
```suggestion
Instead, the CCM is added to the outbox of the sending chain, i.e., it will eventually be included in a new CCU and posted *back to the sending chain.*
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Mainchain cannot find the receiving chain: CCM status is updated to 3 (`CHANNEL_UNAVAILABLE`) on the mainchain.
```suggestion
. Mainchain cannot find the receiving chain: CCM status is updated to `CHANNEL UNAVAILABLE` on the mainchain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Mainchain cannot find the receiving chain: CCM status is updated to 3 (`CHANNEL_UNAVAILABLE`) on the mainchain.
Note that the suggestion is also removing the underscore in order to match the format in the table above.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-2b.png[,300,role="right"]
I think it would be good to visualize that the failed CCM is added to the outbox of the sending chain on the mainchain. Because adding a CCM to the outbox is also visualized on the sidechain, and not visualizing it on the mainchain may suggest that this is not done in this case (which is not true).

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* the receiving application understands the particular command, i.e. if it includes the required module to interpret the command name.
```suggestion
* the receiving application understands the particular command, i.e. it includes the required module to interpret the command name.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +If the status is NOT OK, the CCM will NOT be processed to the receiving chain.
```suggestion
If the status is NOT OK, the state changes of the CCM will NOT be performed on the receiving chain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Instead, a relayer on the receiving chain will include the CCM in a new CCU and post it *back to the mainchain*, and from there to the sending chain.
```suggestion
Instead, the CCM will be added to the outbox of the mainchain on the receiving chain.
Thus, the CCM will eventually be included in a new CCU and posted *back to the mainchain*, and from there to the sending chain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Sidechain does not support module: CCM status is updated to 1 (`MODULE_NOT_SUPPORTED`) on the mainchain.
```suggestion
. Sidechain does not support module: CCM status is updated to `MODULE NOT SUPPORTED` on the receiving chain.
```

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/cc-cmmunication-flow.png[]
1. Also here, I would visualize that the failed CCM is added to the outbox on Sidechain Y and on the mainchain.
2. in the text in step 2, ")" is missing at the end
3. In step 6a, I would be more precise: "...to the outbox of Sidchain Y". I would also say "CCM" instead of "CCMs".
4. for steps 7a to 10a, the texts are using "7" to "10" instead of "7a" to "10a"
5. step 8b is talking about "CCM1", all other steps about "CCM"

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-3b.png[,300]
1. Also here, I would visualize that the failed CCM is added to the outbox on Sidechain Y and on the mainchain.
2. The text for step 12b is using "7b" instead of "12b". The same holds for 13b.
3. In step 13b, one talks about "CCM1", but in all other places just about "CCM". This should be aligned.

2022-10-12 08:23 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +If the status is NOT OK, the CCM will NOT be processed to the receiving chain.
or you could also say that the respective cross-chain command is not executed.

2022-10-18 11:20 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/bft.adoc
> += Lisk BFT
It is intended. The page is a placeholder for future content, and fixes some missing link errors, that were happening during docs compiling.

2022-10-18 12:43 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The only difference is that a CCT refers to a **cross-chain command**, instead of a normal command.
If this is true, then there is no real difference between a cc-comand and a regular command, so the distinction wouldn't make any sense. But at many points we talk about a cross-chain-command. So if there is no difference, I would suggest to completely refrain from using the term CC-command, or cross-chain command.

2022-10-18 13:37 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +After the CCM has been created in step <<using-cross-chain-transactions-to-generate-ccms>>, it is added to the outbox of the sending chain X.
fixed the internal link

2022-10-18 13:38 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +From the outbox, a *relayer* collects the CCMs and creates a CCU with the properties described in step <<transferring-ccms-in-a-ccu>>.
fixed 👍

2022-10-18 13:44 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +After the CCM is included in the inbox of the mainchain, the mainchain performs the most important validations on the CCM.
added a link to the previous section, where this is explained

2022-10-18 13:45 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +== Executing the CCC on the receiving chain
Interesting, I thought it was. So it is valid to say that the CCM is executed? Because I thought a CCM is only an envelope for a corss-chain command, as described above in line 15.

2022-10-18 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-2b.png[,300,role="right"]
thanks for clarification! This step was not clear to me before.

2022-10-18 14:25 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Sending chain undoes related state changes: 5 LSK are added back to Alice's account, because the cross-chain transfer was not successfull.
```suggestion
. Sending chain undoes related state changes: 5 LSK are added back to Alice's account, because the cross-chain transfer was unsuccessful.
```

2022-10-18 14:36 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/cc-cmmunication-flow.png[]
Concerning step 6a, I think it is correct to say `to the outbox of the mainchain` - I have updated it accordingly.

2022-10-18 14:50 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
@AndreasKendziorra do you have the original image somewhere, so I can update it?

2022-10-18 14:53 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Each step of the lifecycle of a sidechain is explained in further detail on the page xref:{url_understand_sidechainlifecycle}[].
the content will be added in another task, see PR https://github.com/LiskHQ/lisk-docs/pull/1632

2022-10-18 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Structurally, the mainchain is not any different from any other sidechain.
Oh, I thought it is actually already possible to do so, and communicating over the Lisk mainchain is rather optinal than mandatory. But if this is not the case, then I agree we should probably remove or update this section.

2022-10-18 15:02 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Another example use case for Lisk interoperability was presented at Lisk.js 2021 by Alessandro Ricottone:
Good point, I commented the section out.

2022-10-19 08:09 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
I only found the png file: https://drive.google.com/file/d/101jFKbQfrTiYok-CLBsFIMT80K2IvDJV/view?usp=sharing It was created for the blog post "high-level overview of lisk interoperability". It was created by the marketing team based on sketches from us. The sketches are here: https://docs.google.com/document/d/1VVXWsY4brDjXnDJjkgE2hIP8ycvN5QQ17aFAYyi8pAY/edit#heading=h.20f9g8ty34y4
This is related task card for marketing: https://trello.com/c/LEmkUM1h/877-illustrations-for-high-level-overview-of-lisk-interoperability-blog-post. I don't know if the marketing team can find working file for this illustration.

2022-10-19 08:09 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Structurally, the mainchain is not any different from any other sidechain.
No, it will definitely not be possible with the Sapphire phase SDK.

2022-10-19 08:28 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The only difference is that a CCT refers to a **cross-chain command**, instead of a normal command.
There is a difference between cc-command and regular command: cc-commands are triggered by CCMs whereas regular commands are triggered by transactions.

My previous statement about the "difference of transaction and cc-transaction" was also not correct. Because they are not different concepts. A cc-transaction is just a specific transaction. That is: A transaction `T` is a cc-transaction if it can create some CCMs.

2022-10-19 08:41 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +This array has to be updated if the set of active validators changes in the chain sending the certificate.
```suggestion
This array has to be updated if the set of active validators changes in the chain sending the CCU.
```

2022-10-19 08:41 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +This array has to be updated if the set of active validators changes in the chain sending the certificate.
I think this suggestion was missed in the previous round. Or ignored for some reason?

2022-10-19 08:41 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +certificate threshold:: The threshold of block generators required to validate the certificate signature.
```suggestion
certificate threshold:: The threshold of block generators in terms of BFT weight required to validate the certificate signature.
```

2022-10-19 08:41 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.. If the certificateThreshold used to create `certificate.validatorsHash` is different from the one stored in the chain account, include the new value in the `newCertificateThreshold` property.
this one is still open

2022-10-19 09:17 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|MODULE NOT SUPPORTED|uint32|2|Status assigned on the receiving chain if it does not implement any module with ID equal to the message module ID.
```suggestion
|MODULE NOT SUPPORTED|uint32|2|Status assigned on the receiving chain if it does not implement any module with the name equal to the `module` property of the CCM.
```

2022-10-19 09:17 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|CROSS CHAIN COMMAND NOT SUPPORTED|uint32|3|Status assigned on the receiving chain if it does not implement any command with ID equal to the message command ID.
```suggestion
|CROSS CHAIN COMMAND NOT SUPPORTED|uint32|3|Status assigned on the receiving chain if it does not implement any command with the name equal to the `crossChainCommand` property of the CCM.
```

2022-10-19 09:17 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +|CCM EXECUTION FAILED|uint32|4|Status assigned on the mainchain to a cross-chain message after it has been recovered from the outbox of a terminated sidechain.
```suggestion
|CCM EXECUTION FAILED|uint32|4|Status assigned on the receiving chain to a cross-chain message when the cross-chain command execution failed.
```

2022-10-19 09:17 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/cc-cmmunication-flow.png[]
1. regarding 6a: the mainchain can have several outboxes (one per sidechain). so, "the outbox of the mainchain" is not correct. you could say "an outbox" or "the outbox of Sidechain Y (on the mainchain)"
2. the "." is missing after "7b" and "8b" in the textboxes

2022-10-19 09:20 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image:understand-blockchain/interop/ccc-3b.png[,300]
the "." is missing after "12b" and "13b" in the text boxes

2022-10-19 13:49 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +The only difference is that a CCT refers to a **cross-chain command**, instead of a normal command.
Sorry, i meant CC-transaction, not CC-command. So, the original statement is correct then?
I would clarify as follows: 


```suggestion
NOTE: A cross-chain transaction (CCT) is a transaction that, upon its execution, creates one or more cross-chain messages.

In fact, a cross-chain transaction uses the identical schema as normal transactions, but it refers to a cross-chain command instead of a regular command.
Unlike regular commands, cross-chain commands can create CCMs.
```

2022-10-19 15:21 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +This array has to be updated if the set of active validators changes in the chain sending the certificate.
missed it somehow, thx!

2022-10-19 15:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
I see thanks! 

I think I will try to recreate and update the diagrams in Lucidchart

2022-10-20 12:10 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +As explained in section <<cross-chain-network-topology>> above, the Lisk blockchain network is structured in two general kinds of network participants:
```suggestion
As explained in section <<cross-chain-network-topology>> above, the Lisk blockchain network is structured in two types of network participants:
```

2022-10-24 07:31 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +However in the case of a CCM, the command is a specific command, called cross-chain command, which triggers state changes on another chain, a.k.a. the receiving chain.
imho I would restructure this sentence, as we have 3 instances of 'command' here in one sentence, which I think would sound better if we used something like the following:
"However, in the case of a CCM, a cross-chain command is specifically used here, which triggers state changes on another chain, a.k.a. the receiving chain".

2022-10-24 08:32 UTC, chris529 reviewed
Looks excellent! Only a few very minor points 👍

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +This property contains three elements:
```suggestion
This property contains the following three elements:
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +After the CCM has been created in step <<sending-cross-chain-transactions-to-generate-ccms>>, it is added to the outbox of the sending chain X.
```suggestion
After the CCM has been created in the step <<sending-cross-chain-transactions-to-generate-ccms>>, it is added to the outbox of the sending chain X.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +From the outbox, a *relayer* collects the CCMs and creates a CCU with the properties described in step <<relaying-ccms-in-a-ccu>>.
```suggestion
From the outbox, a *relayer* collects the CCMs and creates a CCU with the properties described in the step <<relaying-ccms-in-a-ccu>>.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +After the CCM is included in the inbox of the mainchain in step <<sidechain-to-mainchain>>, the mainchain performs the most important validations on the CCM.
```suggestion
After the CCM is included in the inbox of the mainchain in the step <<sidechain-to-mainchain>>, the mainchain performs the most important validations on the CCM.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +If the validation is completed successfully, the cross-chain command is performing the intended state changes on the receiving chain, i.e. adding 5 LSK to Bobs account.
```suggestion
If the validation is completed successfully, the cross-chain command is performing the intended state changes on the receiving chain, i.e. adding 5 LSK to Bob's account.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* execute the necessary changes on the sending chain (i.e. removing 5 LSK from Alices balance), and
```suggestion
* execute the necessary changes on the sending chain (i.e. removing 5 LSK from Alice's balance), and
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* also create CCMs to trigger the corresponding state changes in the receiving chain (i.e. add 5 LSK to Bobs balance).
```suggestion
* also create CCMs to trigger the corresponding state changes in the receiving chain (i.e. add 5 LSK to Bob's balance).
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +In the example, the CC-transfer will deduct 5 LSK from Alices balance once the transaction is included in a block.
```suggestion
In the example, the CC-transfer will deduct 5 LSK from Alice's balance once the transaction is included in a block.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Alice sends CC-Transfer: 5 LSK + Fee is deducted from Alices balance on Sidechain X.
```suggestion
. Alice sends CC-Transfer: 5 LSK + Fee is deducted from Alice's balance on Sidechain X.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Alice sends CC-Transfer: 5 LSK + Fee is deducted from Alices balance on Sidechain X.
```suggestion
. Alice sends CC-Transfer: 5 LSK + Fee is deducted from Alice's balance on Sidechain X.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +. Sending chain undoes related state changes: 5 LSK are added back to Alices account, because the cross-chain transfer was unsuccessful.
```suggestion
. Sending chain undoes related state changes: 5 LSK are added back to Alice's account, because the cross-chain transfer was unsuccessful.
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +Then, a user story could look like this:
```suggestion
Then, a user story could look like the example described below:
```

2022-10-24 08:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/cc-communication-flow.png[]
In this image, I think caption '6b' should read as the following:

"If validation fails:  Status of the CCM is set to error and it is posted back to the sending chain"

2022-10-24 08:56 UTC, AndreasKendziorra requested changes

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +
1. The name of the cc-transfer was recently changed to "transferCrossChain". See [here](https://github.com/LiskHQ/lips/blob/ce9b653f7210f0d997a599486243ec0d031ed30b/proposals/lip-0051.md?plain=1#L133)
2. There is no `sender` property in the parameter of the cc-transfer command. But you could add `senderPublicKey: <Alice's public key>` to the base transaction properties.
3. It's `recipientAddress` instead of `recipient`
4. I think it would be good to include the most important parameters of the CCM in this graphic: `tokenID`, `amount`, `senderAddress` and `recipientAddress`. But it's up to you.

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +In fact, a cross-chain transaction uses the identical schema as normal transactions, but it refers to a cross-chain command instead of a regular command.
```suggestion
In fact, a cross-chain transaction uses the identical schema as normal transactions.
```

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +In fact, a cross-chain transaction uses the identical schema as normal transactions, but it refers to a cross-chain command instead of a regular command.
Maybe even better: "In fact, a cross-chain transaction is a normal transaction." Because the current formulation may suggest that they only use the same schema but that cc-transactions are not transactions. See also [this outdated discussion](https://github.com/LiskHQ/lisk-docs/pull/1623#discussion_r991108227).

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Unlike regular commands, cross-chain commands can create CCMs.
```suggestion
Unlike regular transactions, cross-chain transactions can create CCMs.
```

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +image::understand-blockchain/interop/cc-cmmunication-flow.png[]
the "." is still missing after "7b" and "8b" in the textboxes

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Unlike regular commands, cross-chain commands can create CCMs.
I'm not even sure if this line and the one above is needed as they more or less just repeat the NOTE from line 65. Or the note could be removed.

2022-10-24 08:56 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
>  . Post a first CCU to start communicate with each other.
To become a "sidechain with status active", a CCU with at least on CCM needs to be send. But for simplicity one could also remove this step here completely. Then appears even less complex.

2022-10-25 08:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +In fact, a cross-chain transaction uses the identical schema as normal transactions, but it refers to a cross-chain command instead of a regular command.
```suggestion
In fact, a cross-chain transaction is a normal transaction.
```

2022-10-25 08:33 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Unlike regular commands, cross-chain commands can create CCMs.
removed the lines now

2022-10-25 10:07 UTC, chris529 reviewed
Looks excellent! Only 2 very minor points 👍

2022-10-25 10:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +However, in the case of a CCM, a cross-chain command is specifically used here, which triggers state changes on another chain, a.k.a. the receiving chain.
We should not use periods within the aka acronym. (The other usage of aka in this PR is correct, but I just spotted this one), so it should be as follows:
"However, in the case of a CCM, a cross-chain command is specifically used here, which triggers state changes on another chain, aka the receiving chain".

2022-10-25 10:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +To become a sidechain in the Lisk ecosystem, a blockchain application needs to perform the following three simple steps:
It looks like the third step below this statement is missing here..?
"To become a sidechain in the Lisk ecosystem, a blockchain application needs to perform the following three simple steps":

2022-10-25 10:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +To become a sidechain in the Lisk ecosystem, a blockchain application needs to perform the following three simple steps:
```suggestion
To become a sidechain in the Lisk ecosystem, a blockchain application needs to perform the following two simple steps:
```

ah yes. I removed the third step, as discussed with @AndreasKendziorra

2022-10-25 10:53 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +However, in the case of a CCM, a cross-chain command is specifically used here, which triggers state changes on another chain, a.k.a. the receiving chain.
```suggestion
However, in the case of a CCM, a cross-chain command is specifically used here, which triggers state changes on another chain, aka the receiving chain.
```

2022-10-25 11:36 UTC, chris529 approved these changes
LGTM! 👍

2022-10-26 08:09 UTC, AndreasKendziorra requested changes

2022-10-26 08:09 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
>  A cross-chain command will perform the following:
```suggestion
A cross-chain transaction will perform the following:
```

2022-10-26 09:00 UTC, AndreasKendziorra approved these changes

2022-10-26 09:07 UTC, merged