Updated `lisk-sdk/config.html` - Closes 1541
LiskArchive/lisk-legacy-docs pull request #1624
Opened 2022-09-06 16:26 UTC by TalhaMaliktz

Closes #1541

2022-09-07 19:06 UTC, sitetester requested changes

2022-09-07 19:06 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +	// Contains configuration options for the blockchain application.
- We should mention `system` (in backticks) (just like other comments) in beginning
- single line comments should start with a lower case letter & we don't need to put a DOT at end
- hence for consistency, above 2 points are applicable to all such comments

2022-09-07 19:06 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +		// dataPath defines the blockchain application name and folder within the root path.
as above & for rest of the file

2022-09-07 19:11 UTC, sitetester commented
Overall good job! :+1:

2022-09-08 11:30 UTC, Tschakki reviewed
The PR is looking great, thank you! 🎉 

I just have a question regarding the used terminology

2022-09-08 11:30 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +=== Delegate
Is it still called `delegates` in the config? I thought we change everything to `block generator` in the next version. @ishantiw can you give some insight here?

2022-09-08 11:37 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +	// Contains configuration options for the blockchain application.
Thanks for the feedback. Regarding the backticks, as mentioned in the huddle today, you are viewing the document in the Raw format. To view the file in the proper way, please clone the [lisk-docs](https://github.com/LiskHQ/lisk-docs) repository. Feel free to reach out if you need help with previewing the docs file locally.

Regarding capitalization, we follow Google's documentation writing style guide which suggests doing capitalization as one would do for American English. The terms such as `rpc` or `system` are written in smaller cases as these are nouns and they refer to a specific element in code. I will revisit these terminologies to ensure that their case is correct.

We don't change the case for inline comments as the entire document follows the guidelines mentioned by Google. For more information, please see [Text Formatting](https://developers.google.com/style/text-formatting?hl=en) and [Capatalization](https://developers.google.com/style/capitalization)

Also, the point regarding the use of period will be taken care of.

2022-09-08 11:46 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +=== Delegate
Ummm, I picked up these definitions from the latest [types.ts](https://github.com/LiskHQ/lisk-sdk/blob/22f83d967ac73315cab0083ee0ff68ca2706ab3d/framework/src/types.ts) file, so not sure about the change in terminology.

2022-09-08 15:58 UTC, sitetester commented
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/schema/application_config_schema.ts

2022-09-09 12:32 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +		chainID: 'yaE12vt6',
It should be `hex` value.
requirement is 4 bytes (so hex value 8 characters) and user defines what chainID they want to use and they register through transaction

2022-09-09 12:35 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +		chainID: 'yaE12vt6',
Alright, can you please quote an example value?

2022-09-14 13:53 UTC, Tschakki requested changes
Looking very nice overall, thank you! Just a few remarks :)

2022-09-14 13:53 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +export const DEFAULT_KEY_DERIVATION_PATH = "m/25519'/134'/0'/0'";
Out of curiosity, why is this property not included in the general config object?

2022-09-14 13:53 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +For more information, see {url_key_derivation_lip66}[Introduce tree based key derivation and account recovery].
```suggestion
For more information, see {url_key_derivation_lip66}[Introduce tree based key derivation and account recovery^].
```

add the `^` at the end, to open the link in a new tab

2022-09-14 13:53 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +TIP: For more information about the configuration schema, see the {url_github_sdk_configschema}[application config schema file] on GitHub.
```suggestion
TIP: For more information about the configuration schema, see the {url_github_sdk_configschema}[application config schema file^] on GitHub.
```

add the `^` at the end, to open the link in a new tab

2022-09-14 13:53 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +TIP: For more information, see {url_plain_object_schema}[plainKeysObjectSchema] and {url_encrypted_object_schema}[encryptedObjectSchema].
```suggestion
TIP: For more information, see {url_plain_object_schema}[plainKeysObjectSchema^] and {url_encrypted_object_schema}[encryptedObjectSchema^]. 
```

2022-09-14 13:53 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +=== network
Are this and the following chapter really sub-sections of the `Default configuration` ?

2022-09-14 13:53 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +TIP: For more information about the configuration schema, see the {url_github_sdk_configschema}[application config schema file] on GitHub.
Although it isn't updated yet, it would be nice to add a link here to the following guide as well: https://lisk.com/documentation/build-blockchain/configure-app.html

2022-09-14 14:22 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +=== network
Hmmmmm, so the idea was to present the `Default configuration` at the start (as a parent) and then describe various configuration elements that are part of a configuration (as a child). With each element, I tried to describe how each configuration element can be tweaked inside a config file. That said, should we go with a different terminology like `Configuration` instead of `Default configuration` to make it clearer? What do you suggest?

2022-09-14 14:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +export const DEFAULT_KEY_DERIVATION_PATH = "m/25519'/134'/0'/0'";
Not sure, maybe @ishantiw can guide us.

2022-09-14 15:17 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +=== network
Ok! Yes, I think `Configuration` as section title would make it clearer, thank you!

2022-09-14 15:28 UTC, sitetester requested changes

2022-09-14 15:28 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +| Set of peers that will always try to connect for outbound connections.
A bit confusion here, should be `Set of peers that will always be tried for outbound connections.

2022-09-14 15:28 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +| A hexadecimal string which identifies each chain.
You can add merge this info:
- chainID is 4 bytes which identifies each chain
- chainID is hex string length of 8

2022-09-14 15:28 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +| Contains a path to the "keys" file for the generator.
You can add info "In Lisk SDK, we can see such keys in sample file framework/src/testing/fixtures/keys_fixture.json"

2022-09-14 15:28 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +=== Delegate
Yes there is still `DelegateConfig` in `development` branch - https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/types.ts, but this configuration seems to unused in code, so we might possibly remove it at some point in future.

2022-09-14 15:28 UTC, sitetester commented on modules/ROOT/pages/config.adoc
> +| Lisk 32 address for the generator.
You can add reference - https://lisk.com/blog/research/new-lisk-id-system

2022-09-15 07:20 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| A hexadecimal string which identifies each chain.
What should be the sample value? any suggestions? I have used `0x00000000`, Is that correct?

2022-09-15 08:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +TIP: For more information about the configuration schema, see the {url_github_sdk_configschema}[application config schema file] on GitHub.
Agreed, text updated

2022-09-15 08:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +=== network
Agreed, text updated

2022-09-15 08:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| Set of peers that will always try to connect for outbound connections.
Agreed, text updated

2022-09-15 08:43 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| A hexadecimal string which identifies each chain.
Agreed, text updated

2022-09-15 08:43 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| Contains a path to the "keys" file for the generator.
Agreed, text updated

2022-09-15 08:43 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| Lisk 32 address for the generator.
Agreed, text updated

2022-09-15 09:19 UTC, sitetester submitted a review, later dismissed

2022-09-15 09:57 UTC, Tschakki approved these changes, later dismissed
Just some small suggestions, otherwise LGTM 👍

2022-09-15 09:57 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +TIP: For more information about the *configuration schema* and *configuring an application*, see the {url_github_sdk_configschema}[Application config schema^] and {url_configure_app_guide}[How to con
```suggestion
TIP: For more information about the *configuration schema* and *configuring an application*, see the {url_github_sdk_configschema}[Application config schema^] and {url_configure_app_guide}[How to configure a blockchain application]. 
```

internal links can open in the same tab :)

2022-09-15 09:57 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +	"cipherparams": {}
```suggestion
	"ciphertext": ,
	"kdf": ,
	"kdfparams" : {},
	"cipher": '',
	"cipherparams": {}
```

2022-09-15 09:57 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +	"blsKey": ""
```suggestion
	"generatorKey": "",
	"generatorPrivateKey" : "",
	"blsKey": "",
```

2022-09-15 10:31 UTC, ishantiw commented on modules/ROOT/pages/config.adoc
> +export const DEFAULT_KEY_DERIVATION_PATH = "m/25519'/134'/0'/0'";
I think you want to give flexibility to the user that with every sign or create command they are able to give key derivation path rather than just setting once in the general config

2022-09-15 11:03 UTC, Tschakki approved these changes
LGTM

2022-09-15 11:04 UTC, merged