Add jsdoc section - Closes #23
LiskArchive/lisk-legacy-docs pull request #163
Opened 2019-01-25 15:41 UTC by Tschakki

Closes #23

2019-02-06 09:00 UTC, ghost reviewed
Works as advertised.

2019-02-06 09:00 UTC, fchavant commented on user-guide/administration/source/admin-source.md
> +```
Maybe mention that the documentation will be in `docs/jsdoc/`?

2019-02-06 09:00 UTC, fchavant commented on user-guide/administration/source/admin-source.md
> +```
We could add some details regarding what happens when this command runs (webserver started on port 8080, can be stopped with `Ctrl-C`, there will be an informational message, etc.)

2019-02-07 13:00 UTC, ghost requested changes

2019-02-07 13:00 UTC, ghost commented on user-guide/administration/source/admin-source.md
> +To build the documentation site, run the following command inside the lisk folder:
```suggestion
To build the documentation site, run the following command inside the lisk installation directory:
```

2019-02-07 13:00 UTC, ghost commented on user-guide/administration/source/admin-source.md
> +This will start a webserver, and the docs will be accessible through the browser on port 8080, e.g. `localhost:8080`.
Should we really use an abbreviation like "docs"?

2019-02-07 13:00 UTC, fchavant commented on user-guide/administration/source/admin-source.md
> +The docs are generated inside of `docs/build`.
As far as I can tell the generated documentation ends up in the `docs/jsdoc/` directory.

2019-02-07 14:06 UTC, Tschakki commented on user-guide/administration/source/admin-source.md
> +The docs are generated inside of `docs/build`.
you are right :)

2019-02-07 14:07 UTC, Tschakki commented on user-guide/administration/source/admin-source.md
> +This will start a webserver, and the docs will be accessible through the browser on port 8080, e.g. `localhost:8080`.
I changed it to documentation

2019-02-07 14:41 UTC, ghost approved these changes

2019-02-07 14:49 UTC, merged