Add sidechain registration and recovery page in Lisk docs - Closes #1517
LiskArchive/lisk-legacy-docs pull request #1632
Opened 2022-09-21 14:49 UTC by chris529

2022-10-17 14:51 UTC, sergeyshemyakov reviewed
Generally looks good and thorough!

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Sidechain termination specifically occurs when the sidechain in question has been inactive for too long.
... or sends a malicious cross-chain message.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Therefore violating the liveness requirement (only on the mainchain), result in terminating the sidechain.
We now have added a [Liveness Termination Command](https://github.com/LiskHQ/lips/blob/187744ada9ce73b1543970b123f69b61b41c64e2/proposals/lip-0054.md#liveness-termination-command-1) (it is still in an open PR, but it should be merged very soon). So whenever a sidechain violated the liveness condition, anyone can submit a liveness termination transaction on the mainchain and the sidechain will be terminated. Maybe you can add this here.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +There are 4 recovery commands which can be used and are described further in this section below.
As I have mentioned above, now there is also fifth command (can be submitted only on the mainchain) to terminate a sidechian for liveness. It's a small and simple one, but still a part of the recovery process.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The users can recover the balance of LSK they had on a terminated sidechain by submitting a transaction with a <<State Recovery Command>>.
Recovering LSK (or other tokens) is just one possible use case of the State Recovery command. Generally, it can recover any module store value / values according to the logic specified in this module. So it can be customized by developers for their own modules (we also provide recovery of NFTs).

Ah, I see you mention it below.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command has two purposes.
This command has only one purpose: to initialize a terminated state account or update the state root stored in it if it was not set yet. It can only be submitted on a sidechain.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +n this case, the state root is generally not available and the terminated state account is created without setting the sidechain state root. Instead, the account stores the mainchain state root at th
A typo: "In this case, ..."

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In the second case, the command contains an inclusion proof against the mainchain state root, proving that another sidechain is either terminated (the status in the chain account is set to 'terminate
I think, you can just remove this paragraph.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The command ID is `COMMAND_ID_STATE_RECOVERY_INITIALIZATION` and the state recovery initialization command schema can be seen below:
In some of the recent updates we changed command IDs to command names, so now the following would be correct:
The command name is `COMMAND_STATE_RECOVERY_INITIALIZATION` and ...

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Initialization Command Schema
Also the schema has some small changes, e.g. `chainID` has type `bytes` now and we specify lengths of some byte arrays. The current version of the schema is here: https://github.com/LiskHQ/lips/blob/187744ada9ce73b1543970b123f69b61b41c64e2/proposals/lip-0054.md#parameters-3.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Assumming that `trs` is a transaction with module ID `MODULE_ID_INTEROPERABILITY`, and the command ID `COMMAND_ID_STATE_RECOVERY_INITIALIZATION` is to be verified, this can be seen as shown in the fo
... with module name `MODULE_NAME_INTEROPERABILITY`, and the command name `COMMAND_STATE_RECOVERY_INITIALIZATION` is to be verified ...

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Initialization Command Validation
The current verification process could be found here, it was also slightly updated: https://github.com/LiskHQ/lips/blob/187744ada9ce73b1543970b123f69b61b41c64e2/proposals/lip-0054.md#verification-3

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +To continue and process a transaction `trs` with the module ID `MODULE_ID_INTEROPERABILITY` and the command `ID COMMAND_ID_STATE_RECOVERY_INITIALIZATION`, this implies the following logic as displaye
The same concerning module name and command name.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Initialization Command Execution
I am not sure about the format of your documentation, but possibly for such precise details you could refer directly to the LIP.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For further information, including the `createTerminatedStateAccount` function can be found in {url_lip}[LIP 0045^].
Something is wrong with this sentence.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Command Schema
Again, the schemas and logic was slightly modified, the current version is here: https://github.com/LiskHQ/lips/blob/187744ada9ce73b1543970b123f69b61b41c64e2/proposals/lip-0054.md#state-recovery-command

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +recover(terminatedChainID, moduleID, storePrefix, storeKey, storeValue),
We have removed `moduleID` from the arguments of the function.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Message Recovery Command
Maybe create a new section "How to recover messages from the terminated chain outbox" similar to "How to recover information from a sidechain".

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command is used to recover pending messages from the outbox of a terminated sidechain.
This exact formulation was a bit confusing to me, so we have updated it in the LIP to:
"This mechanism allows to recover any CCM pending in the sidechain channel outbox. That is, those CCMs sent from the sidechain that have not been included in the (terminated) receiving chain yet."

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The message nonce is compared to the size of the inbox (this is also stored in the terminated outbox account), to check that the message had not been processed yet.
The size of the inbox is not stored in the terminated outbox account, it is taken from the channel stored on the terminated sidechain.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Message Recovery Command Schema
See the current version of the schemas and the logic here: https://github.com/LiskHQ/lips/blob/187744ada9ce73b1543970b123f69b61b41c64e2/proposals/lip-0054.md#message-recovery-command

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Message Recovery Initialization Command Schema
The current version of the schemas and logic: https://github.com/LiskHQ/lips/blob/187744ada9ce73b1543970b123f69b61b41c64e2/proposals/lip-0054.md#message-recovery-initialization-command

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +1. The sidechain is terminated for violating the liveness requirement or the token-module protocol.
The sidechain is terminated by submitting a Liveness Termination Command.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/mainchain-recovery.png[, align="center" ,500]
The link seems to be broken, but the picture itself is good.

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/sidechain-recovery.png[, align="center" ,500]
The same about pictures here

2022-10-17 14:51 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +On a sidechain, the process flow can occur in 3 scenarios which are described below and are also depicted in the corresponding 3 diagrams.
You don't mention anything about message recovery in this subsection. Basically it will be the same as on the mainchain.

2022-10-17 16:37 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Sidechain termination specifically occurs when the sidechain in question has been inactive for too long.
Thanks Sergey, I have now added it in as suggested 👍

2022-10-17 16:53 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Therefore violating the liveness requirement (only on the mainchain), result in terminating the sidechain.
Many thanks...Now added 👍

2022-10-18 11:59 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +There are 4 recovery commands which can be used and are described further in this section below.
Ok thanks Sergey. I have now added in that are 5 commands, and also included the liveness termination command and schema.. 👍

2022-10-18 12:40 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +1. The sidechain is terminated for violating the liveness requirement or the token-module protocol.
Now updated 👍

2022-10-18 12:43 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/mainchain-recovery.png[, align="center" ,500]
The link should now be fixed 👍

2022-10-18 12:47 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/sidechain-recovery.png[, align="center" ,500]
Very strange... the path is correct, and the pictures are all viewable in my Webstorm :thinking_face:

2022-10-18 14:03 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +On a sidechain, the process flow can occur in 3 scenarios which are described below and are also depicted in the corresponding 3 diagrams.
As discussed earlier in Slack, I have now added a sidechain message recovery sub-section 👍

2022-10-18 14:04 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command has two purposes.
As discussed earlier in Slack, it has now been updated 👍

2022-10-18 14:36 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Message Recovery Initialization Command Schema
OK, thanks very much Sergey. I have slightly reworded this section and added in the updated schemas from your link above. Can you please check this together with the schemas. 👍

2022-10-19 12:27 UTC, AndreasKendziorra requested changes
Overall, this site contains much redundant content as most statements are repeated several times due to copy and pasting several sections from the Rationale sections of some LIPs.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +A sidechain is actually a separate blockchain that is attached to its mainchain using a two-way peg.
> using a two-way peg.

I would not use the term two-way peg as it is not self explaining and also nowhere defined in this document. You could just drop this part, or replace "that is attached to its mainchain using a two-way peg" by "where the inclusion of a transaction in of the blockchains can have an effect in the other blockchain".

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Simply put, a sidechain will allow nodes containing assets or data from the parent blockchain to be securely used in a separate blockchain (the sidechain), and hence, these assets and data can then b
These lines rather explain cross chain communication (limited to moving assets though) instead of the concept of a sidechain, and they also contain several errors. I think they could be dropped and do not need a replacement. Only the next sentence should be adapted a bit, but should still highlight the main purpose of sidechains, namely increasing the overall amount of transactions.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In turn, the advent of sidechains will further increase the performance of the parent blockchain by taking some of the workload, and furthermore, this increases the level of security as all transacti
> will further increase the performance

this is not true. taking off some workload does not increase performance (amount of work done in a certain time). but it increases the performance of an ecosystem of blockchains.

> this increases the level of security

I don't see this and I would remove it.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Overview - What is a Sidechain?
I left several smaller comments below. Maybe one unified proposal how to replace this section:

"A sidechain is a separate blockchain next to the mainchain, where the inclusion of a transaction in of the blockchains can have an effect in the other blockchain. These effects on the other blockchain can facilitate, for example, moving digital assets between the mainchain and the sidechain. Having a mainchain and some sidechains in parallel results in a higher overall transaction throughput."

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/sidechain.png[, align="center" ,500]
the image does not visualize the general concept of sidechains. using "proof of locked ..." seems to visualize a very specific solution that is not explained in the text (and should not be explained in the text). 
We could just remove the image or replace it by one that visualizes "where the inclusion of a transaction in of the blockchains can have an effect in the other blockchain"

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechains in Lisk
This section contains many errors. I think it could be done shorter and simpler (and correct), for example, like this:

"Within the Lisk network, a transaction that can have an effect on another blockchain is called a cross-chain transaction (link to definition would be nice). Such a transaction emits one or more cross-chain messages (link) on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred to the sending chain via a so-called cross-chain updated transaction (CCU) (link). When the CCU is included in the receiving chain, the cross-chain messages induce some state changes. This is how a transaction from a sidechain (the mainchain) can have an effect on the mainchain (a sidechain)."

From the section title, I would also expect to hear the specific role sidechain in Lisk (although it is not important to understand the registration and recovery process). If yes, then something like the following could be used.

"The main purpose of sidechains in the Lisk ecosystem is scalability: More sidechains in the ecosystem mean more transactions that can be processed per second. It is intended that each blockchain serves one application. That means, for instance, there could be a sidechain dedicated to a decentralized exchange application."

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Specifically, it creates an entry in the chain data substore, with the initial status set to 'registered'; an entry in the channel data substore, with an empty inbox and outbox; coupled with an entry
```suggestion
This command creates the sidechain account on the mainchain with the initial status set to 'registered'.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Specifically, it creates an entry in the chain data substore, with the initial status set to 'registered'; an entry in the channel data substore, with an empty inbox and outbox; coupled with an entry
I would not talk about the substores. I'm sure most readers don't know (at this stage) what they are.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +(The liveness rule requires active sidechains to prove their liveness once every 30 days, or the sidechain account is terminated).
```suggestion
(The liveness rule requires active sidechains to prove their liveness once every 30 days by including a CCU in the mainchain, or the sidechain account is terminated).
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +(The liveness rule requires active sidechains to prove their liveness once every 30 days, or the sidechain account is terminated).
Also, I would move this sentence one line up as the sentence before is already talking about liveness. But it's not so important.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechain Registration
I'm not sure about the header levels. Is this header suppossed to be on the same level as the next one? I'd expect the next one to be one level higher.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Firstly sidechain registration is required to ultimately ensure interoperability with a separate chain can be achieved with the Lisk mainchain.
> interoperability with a separate chain can be achieved with the Lisk mainchain

I guess something is broken here. What is the "separate chain" here? Is it the sidechain for which the sidechain registration is performed?

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +To bring this to fruition a cross-channel chain protocol needs to be established, which is the chain registration process defining the necessary protocol rules and data structures.
> a cross-channel chain protocol

what is this?

> the necessary protocol rules and data structures

which protocol rules data structures are meant here?

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +At this point, it should be noted that there are two registration commands which are utilized depending on whether it is the Lisk mainchain or the sidechain we are dealing with.
> At this point

This statement was already made in the previous section. So, it can be removed here.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +From the sidechain perspective, this is performed by the mainchain registration command, both of these are covered further in this section.
> covered further in this section.

Related to my comment above: this section is finished here. Probably due to incorrect header levels.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechain Registration
In my opinion, this paragraph is not saying anything new. It is only repeating parts of the previous section, but in a less clear way. I would therefore remove it.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +However, at this point, the cross-channel is not active, so no cross-chain messages (CCMs) can be sent yet.
We don't really use the term "cross-channel". We only talk about the "channel".

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For the processing of this command, it signifies that a sidechain account in the mainchain state exists, and is associated with a name and a unique network identifier.
> it signifies that a sidechain account in the mainchain state exists

Maybe my English is too bad. But this sounds to me like the existence of the sidechain account is a condition for the processing. But instead it's a result.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Firstly, for a sidechain to be interoperable, it has to be registered in the Lisk mainchain via a <<Sidechain Registration Command>>.
I'm sure I read this statement for the 3rd or 4th time now :)

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Registration Message
this section comes quite unmotivated at this place. I would move it at least after the "sidechain registration process" section.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Therefore, each new sidechain occupies a certain namespace in the ecosystem.
This two sentences can be found already above (with minor differences). So, an unnecessary repetition.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The value of this extra registration fee is `REGISTRATION_FEE` is LSK.
This statement was needed in the Rationale section of the LIP. But I'm sure the readers of this page won't be interested in such a detail.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When a first valid cross-chain update command from this sidechain is processed, the sidechain status is changed to active, making it active in the ecosystem. Now it is possible to send CCMs to the si
Also this paragraph is to 100% repetition from the "Life Cycle of a Sidechain" chain, just in different words.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The values of these entries are initialized, and the `name`, `networkID`, and `initValidators`, properties are computed from the sidechain registration command.
```suggestion
The values of the account entries are initialized, and the `name`, `chainID`, and `initValidators`, properties are computed from the sidechain registration command.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This <<Sidechain Registration Command>> assigns a unique integer as the chain ID that identifies the sidechain in the ecosystem.
```suggestion
This <<Sidechain Registration Command>> assigns a unique bytes value as the chain ID that identifies the sidechain in the ecosystem.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This results in a new entry being created in the five different substores of the interoperability module store listed below, and can also be seen in the diagram below in figure 1.
do you mean figure 2?

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The account is initialized with an empty inbox and outbox, while the sidechain name and the initial validators set are given in the command parameters.
```suggestion
The account is initialized with an empty inbox and outbox, while the sidechain name, chain ID and the initial validators set are given in the command parameters.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The network ID is calculated from the address of the command sender and the genesis block ID, also given in the command parameters.
This sentence has to be removed as there is not network ID anymore.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* *Chain ID*
for consistency, I would write "chainID"

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `Chain ID` is responsible for uniquely identifying a chain in the Lisk ecosystem.
for consistency, I would write "the `chainID` property". Or "The chain ID is ..."

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When processing the sidechain registration command, the chain ID for a sidechain is deterministically computed.
It's not computed. It's given as a parameter in the registration transaction.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Furthermore, an additional advantage, is that it is easy to remember the integer assigned as the chain ID for a users favorite blockchain application.
these lines have to be removed

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Specifically, the Interoperability module, it serves a similar purpose for chains as addresses do for user accounts, as it is used to identify the chain account in the Interoperability module store.
Repetition of line 172

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For example, it has to be specified in the `receivingChainID` property of a CCM to this sidechain and in the `sendingChainId property` of a cross-chain update command from this sidechain.
```suggestion
For example, it has to be specified in the `receivingChainID` property of a CCM and in the `sendingChainID` property of a cross-chain update command.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In the sidechain registration command, the sidechain ID is given as a parameter.
```suggestion
In the sidechain registration command, the chaid ID of the sidechain is given as a parameter.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +=== Sidechain Network Identifier
This whole section needs to be removed.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This mainchain account has a similar structure as the one depicted in Figure 1 above.
Figure 2?

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +By protocol, the chain ID of the mainchain is a constant equal to `CHAIN_ID_MAINCHAIN` in the ecosystem.
```suggestion
By protocol, the chain ID of the mainchain is a constant equal to `0x00000000` in the ecosystem.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Certain parameters are set by the mainchain registration command in the sidechain that is related to the interoperability module, and also initialize the corresponding mainchain data structures.
```suggestion
Certain parameters are set by the mainchain registration command in the sidechain that are related to the interoperability module, and also initialize the corresponding mainchain data structures.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command requires the approval of the sidechain validators, as they have to agree on the content of this command and add their aggregated signatures accordingly.
```suggestion
This command requires the approval of the sidechain validators, as they have to agree on the content of this command and add their aggregate signatures accordingly.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Hence, it is recommended that once the transaction is correctly signed by the validators and ready to be submitted, a validator simply includes it in its next forged block, without including it in th
This was important for the Rationale section of the LIP. But I guess readers of the documentation are not interested in this.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `signature` property is an aggregated signature of the sidechain validators.
```suggestion
The `signature` property is an aggregate signature of the sidechain validators.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `aggregationBits` property is a bit vector used to validate the aggregated signature.
```suggestion
The `aggregationBits` property is a bit vector used to validate the aggregate signature.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +
```suggestion
    # Chain ID cannot be the mainchain chain ID.
    if trs.params.chainID == CHAIN_ID_MAINCHAIN:
        raise Exception("Chain ID cannot be the mainchain chain ID.")
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +        "chainID": chainID,
```suggestion
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +    # Emit CCM Processed Event.
```suggestion
    # Emit CCM Sent Event.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +        name = EVENT_NAME_CCM_SEND_SUCCESS,
```suggestion
        name = EVENT_NAME_CCM_SENT_SUCCESS,
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +[%collapsible]
It's hard to read this JSON file when it's flat.

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +        "chainID": CHAIN_ID_MAINCHAIN,
```suggestion
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +    # Emit CCM Processed Event.
```suggestion
    # Emit CCM Sent Event.
```

2022-10-19 12:27 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +        name = EVENT_NAME_CCM_SEND_SUCCESS,
```suggestion
        name = EVENT_NAME_CCM_SENT_SUCCESS,
```

2022-10-19 14:06 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +A sidechain is actually a separate blockchain that is attached to its mainchain using a two-way peg.
Many thanks Andreas. I have modified  this sentence as you suggested 👍

2022-10-19 14:25 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Simply put, a sidechain will allow nodes containing assets or data from the parent blockchain to be securely used in a separate blockchain (the sidechain), and hence, these assets and data can then b
As recommended, I have removed these 2 lines and reworded the last sentence as suggested 👍

2022-10-19 14:25 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In turn, the advent of sidechains will further increase the performance of the parent blockchain by taking some of the workload, and furthermore, this increases the level of security as all transacti
Many thanks. Now adapted accordingly 👍

2022-10-19 14:30 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Overview - What is a Sidechain?
Ah yes, I like your version Andreas... OK, I have now used it so then please ignore the other changes mentioned regarding this section. Many thanks 👍

2022-10-19 14:46 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/sidechain.png[, align="center" ,500]
I was just trying to give a high-level overview of the basic concept. However, I think you are right Andreas, we do not actually need it here as the main topics are the registration and recovery of a sidechain. Therefore, imho, by the time the reader is at this point in the docs, they should have some knowledge of the principle of sidechains. Therefore I have removed the image 👍

2022-10-20 13:24 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The command ID is `COMMAND_ID_STATE_RECOVERY_INITIALIZATION` and the state recovery initialization command schema can be seen below:
Thanks Sergey! I have updated it 👍

2022-10-20 15:45 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Initialization Command Schema
OK, as requested I have removed the old schema for the State Recovery Initialization Command and replaced it with the schema in the LIP 54 proposal link above 👍

2022-10-20 15:46 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Assumming that `trs` is a transaction with module ID `MODULE_ID_INTEROPERABILITY`, and the command ID `COMMAND_ID_STATE_RECOVERY_INITIALIZATION` is to be verified, this can be seen as shown in the fo
Thanks, now done 👍

2022-10-20 16:12 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +To continue and process a transaction `trs` with the module ID `MODULE_ID_INTEROPERABILITY` and the command `ID COMMAND_ID_STATE_RECOVERY_INITIALIZATION`, this implies the following logic as displaye
OK, so they should now be:  'MODULE_INTEROPERABILITY' and 'COMMAND_STATE_RECOVERY_INITIALIZATION' 👍

2022-10-20 16:13 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Initialization Command Execution
OK, Well I have tried where possible to mirror the LIP from a format and flow perspective.

2022-10-20 16:17 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For further information, including the `createTerminatedStateAccount` function can be found in {url_lip}[LIP 0045^].
I think you mean the link? It should be fine now 👍

2022-10-20 16:23 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Command Schema
OK, I have added in the updated schema from the link above 👍

2022-10-20 16:24 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +recover(terminatedChainID, moduleID, storePrefix, storeKey, storeValue),
OK thanks, now done 👍

2022-10-21 08:10 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechains in Lisk
@chris529 If you don't want to use my suggestion, it's totally fine. But then I have to list all individual errors in this section which I haven't done yet.

2022-10-21 08:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechains in Lisk
@AndreasKendziorra Many thanks, I like your suggestion very much, it is excellent and I plan to use it. I will try to get to it today 👍

2022-10-21 08:46 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The message nonce is compared to the size of the inbox (this is also stored in the terminated outbox account), to check that the message had not been processed yet.
OK, thanks. I have reworded it accordingly 👍

2022-10-21 08:54 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command is used to recover pending messages from the outbox of a terminated sidechain.
OK thanks Sergey. I have now modified this according to your statement above 👍

2022-10-21 09:44 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Assumming that `trs` is a transaction with module ID `MODULE_ID_INTEROPERABILITY`, and the command ID `COMMAND_ID_STATE_RECOVERY_INITIALIZATION` is to be verified, this can be seen as shown in the fo
Thanks, these are now updated 👍

2022-10-21 09:47 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +To continue and process a transaction `trs` with the module ID `MODULE_ID_INTEROPERABILITY` and the command `ID COMMAND_ID_STATE_RECOVERY_INITIALIZATION`, this implies the following logic as displaye
Done 👍

2022-10-21 13:30 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Message Recovery Command Schema
OK, I have redone the Message recovery Command section to take into account the new schemas. 👍

2022-10-21 13:55 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Initialization Command Validation
OK, I have updated all the schemas now in this section.

2022-10-21 14:29 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechains in Lisk
I have now updated this section with your recommendation Andreas, many thanks 👍

2022-10-21 14:36 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +(The liveness rule requires active sidechains to prove their liveness once every 30 days, or the sidechain account is terminated).
Good point...I have not committed this change, as I have updated it accordingly, and moved it 1 line up as suggested 👍

2022-10-21 14:41 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +== Sidechain Registration
OK, I can see your point, it is maybe a bit repetitive, so I have removed the "Sidechain Registration" section as suggested.

2022-10-21 14:44 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Firstly sidechain registration is required to ultimately ensure interoperability with a separate chain can be achieved with the Lisk mainchain.
This section has now been removed 👍

2022-10-21 14:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +To bring this to fruition a cross-channel chain protocol needs to be established, which is the chain registration process defining the necessary protocol rules and data structures.
This paragraph has been previously removed 👍

2022-10-21 14:54 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +At this point, it should be noted that there are two registration commands which are utilized depending on whether it is the Lisk mainchain or the sidechain we are dealing with.
Done 👍

2022-10-21 14:55 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +From the sidechain perspective, this is performed by the mainchain registration command, both of these are covered further in this section.
Yes, this was part of the previously removed section.

2022-10-21 14:58 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +However, at this point, the cross-channel is not active, so no cross-chain messages (CCMs) can be sent yet.
Cool...Now updated and replaced 'cross-channel" with "channel"

2022-10-21 15:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For the processing of this command, it signifies that a sidechain account in the mainchain state exists, and is associated with a name and a unique network identifier.
Your English is excellent Andreas!  In fact, I am not sure we even need to mention processing the command in this manner here, so how about we reword it to something like the following..?

"Hence, a sidechain account that is already associated with a name and a unique network identifier, exists in the mainchain state. Therefore, each new sidechain occupies a certain namespace in the ecosystem".

2022-10-21 15:14 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Firstly, for a sidechain to be interoperable, it has to be registered in the Lisk mainchain via a <<Sidechain Registration Command>>.
Ha Ha...Yes, you are right!! I think I was maybe trying to over-emphasize this point! :-) OK, I have removed it, and slightly adapted the first sentence accordingly 👍

2022-10-21 15:27 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Registration Message
Yes, I think it fits better there...Now done 👍

2022-10-21 15:34 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Therefore, each new sidechain occupies a certain namespace in the ecosystem.
Well spotted...I have now removed them 👍

2022-10-21 15:40 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The value of this extra registration fee is `REGISTRATION_FEE` is LSK.
Fair point...I have now removed it 👍

2022-10-21 16:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When a first valid cross-chain update command from this sidechain is processed, the sidechain status is changed to active, making it active in the ecosystem. Now it is possible to send CCMs to the si
I presume you mean the majority of this section? I have tried to reword it in a more high-level and concise manner, just to maintain the flow here..

2022-10-21 18:41 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This results in a new entry being created in the five different substores of the interoperability module store listed below, and can also be seen in the diagram below in figure 1.
Yes indeed, I meant figure 2... it is now updated, thanks 👍

2022-10-21 18:42 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The network ID is calculated from the address of the command sender and the genesis block ID, also given in the command parameters.
Thanks, it is now removed 👍

2022-10-21 18:51 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* *Chain ID*
OK, I have updated all instances of chain ID, so they are now "chainID"

2022-10-21 18:56 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `Chain ID` is responsible for uniquely identifying a chain in the Lisk ecosystem.
Done 👍

2022-10-21 19:01 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When processing the sidechain registration command, the chain ID for a sidechain is deterministically computed.
Updated accordingly 👍

2022-10-21 19:05 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Furthermore, an additional advantage, is that it is easy to remember the integer assigned as the chain ID for a users favorite blockchain application.
I presume you mean all 3 lines 174 to 176 above, so they have now all been removed 👍

2022-10-22 09:48 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Specifically, the Interoperability module, it serves a similar purpose for chains as addresses do for user accounts, as it is used to identify the chain account in the Interoperability module store.
OK, the last sentence above has now be removed 👍

2022-10-22 10:03 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +=== Sidechain Network Identifier
OK, the 'Sidechain Network Identifier' section has now been removed.

2022-10-22 10:06 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This mainchain account has a similar structure as the one depicted in Figure 1 above.
Yes indeed, many thanks and now updated to figure 2 👍

2022-10-22 10:10 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +By protocol, the chain ID of the mainchain is a constant equal to `CHAIN_ID_MAINCHAIN` in the ecosystem.
Thanks, now updated as recommended 👍

2022-10-22 10:18 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Hence, it is recommended that once the transaction is correctly signed by the validators and ready to be submitted, a validator simply includes it in its next forged block, without including it in th
OK, fair point...It has now been removed 👍

2022-10-22 12:08 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +[%collapsible]
It should be better now as the mainchain, verification, and execution schemas can now be viewed separately.

2022-10-22 13:11 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Message Recovery Command
OK, I have added a short overview description of the terminated chain outbox in the last section, 'Recovery process workflow'.

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
>  After a sidechain has been registered on the mainchain, it cannot receive any cross-chain message and does not need to follow the liveness rule, until the first sidechain CCU has been included in the
```suggestion
After a sidechain has been registered on the mainchain, it cannot receive any cross-chain message and does not need to follow the liveness rule, until the first sidechain CCU containing some cross-chain messages has been included in the mainchain.
```

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
>  After a sidechain has been registered on the mainchain, it cannot receive any cross-chain message and does not need to follow the liveness rule, until the first sidechain CCU has been included in the
I also missed in the previous review that CCUs without CCMs do not trigger the liveness requirement. Also at least one LIP is not totally up-to-date in this regard.

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Hence, a sidechain account that is already associated with a name and a unique network identifier, exists in the mainchain state.
```suggestion
Hence, a sidechain account that is already associated with a name and a unique chain ID, exists in the mainchain state.
```

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Sidechain Registration Process
should this be a level 3 header?

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +As described in the Lifecycle of a Sidechain section above, once the Sidechains registration process has been completed, it does not need to be activated on the mainchain, and will remain inactive un
```suggestion
As described in the Lifecycle of a Sidechain section above, once the Sidechains registration process has been completed, it does not need to be activated on the mainchain, and will remain inactive until the first valid CCU containing some cross-chain messages has been sent and processed.
```

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* *Chain ID*
Sorry. That was a misunderstanding. I meant consistency within this list. Because you used camel case for all other properties in this list as well (e.g. "certificateThreshold" instead of "certificate threshold").  In normal text where you don't use the highlighting/monospace format, I would still write "chain ID" instead of "chainID".

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command requires the approval of the sidechain validators, as they have to agree on the content of this command and add their aggregate signatures accordingly.
```suggestion
This command requires the approval of the sidechain validators, as they have to agree on the content of this command and add their aggregate signature accordingly.
```

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command requires the approval of the sidechain validators, as they have to agree on the content of this command and add their aggregate signatures accordingly.
If you want, you could also be more precise: "... as they have to agree on the content of this command and provide their signature accordingly. Based on the individual signatures, an aggregate signature must be added to the transaction."

But I guess it's not needed.

2022-10-24 10:11 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +[%collapsible]
What I meant is there are no indentations used in this JSON which makes it very hard to see the nesting.

2022-10-24 10:39 UTC, AndreasKendziorra requested changes

2022-10-24 10:39 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
>  This registration process always has to occur after the sidechain registration on the mainchain, since the sidechain has no prior knowledge of the current mainchain validators or its name.
```suggestion
This registration process always has to occur after the sidechain registration on the mainchain, since the sidechain has no prior knowledge of its name and must be certain that the correct chain ID has been registered.
```

2022-10-24 13:27 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command requires the approval of the sidechain validators, as they have to agree on the content of this command and add their aggregate signatures accordingly.
I like it...I have now added it, many thanks 👍

2022-10-24 13:36 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
>  After a sidechain has been registered on the mainchain, it cannot receive any cross-chain message and does not need to follow the liveness rule, until the first sidechain CCU has been included in the
No worries...now updated 👍

2022-10-24 14:28 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +[%collapsible]
Ah yes, sorry. It should be fixed now 👍

2022-10-25 07:17 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* *Chain ID*
But I would still use lower case ("chainID" instead of "ChainID") in line 133...for consistency with the list :)

2022-10-25 07:29 UTC, AndreasKendziorra requested changes

2022-10-25 07:29 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +            "dataType": "string",
```suggestion
            "dataType": "string",
            "minLength": MIN_CHAIN_NAME_LENGTH,
            "maxLength": MAX_CHAIN_NAME_LENGTH,
```

2022-10-25 07:29 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +                        "dataType": "bytes",
```suggestion
                        "dataType": "bytes",
                        "length": BLS_PUBLIC_KEY_LENGTH,
```

2022-10-25 07:29 UTC, AndreasKendziorra commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +            "dataType": "bytes",
```suggestion
            "dataType": "bytes",
            "length": BLS_SIGNATURE_LENGTH,
```

2022-10-25 11:50 UTC, sergeyshemyakov reviewed
Some more comments from my side to align with the current specification. Otherwise, the PR looks good :)

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Message Recovery Command
What I meant is that you have a header of level 4 "Message Recovery Command". The previous header of level 3 is "State recovery from the Sidechain Root", but structurewise this is not correct, as message recovery is not a subtopic of state recovery. 
So I suggest you introduce a new level 3 header "Message recovery" here.

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Message Recovery Command Verification Schema
This is not a schema, this is just "Message recovery command verification". Schema is a JSON file that describes a particular data type (for example, parameters for a command).
The same concerns "Message Recovery Command Execution" below, as well as Message Recovery Initialization and Liveness Termination commands.

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +=== Liveness Termination Command
I think, this should be level 4 header, not level 3.

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* `The chainID` is the ID of the respective sidechan to be terminated.
Typo: The `chainID`.

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The module name is `MODULE_NAME_INTEROPERABILITY`, and the command ID is `COMMAND_STATE_RECOVERY` and the state recovery command schema, verification, and execution can be seen below:
Here and in some other occurrences you use the notion "command ID". We have refactored this in some of the recent updates, now it is called "command name".
You can just search in the document and replace all "command ID" with "command name".

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Assuming `trs` is a transaction with the module `ID MODULE_ID_INTEROPERABILITY`, and the command ID `COMMAND_STATE_RECOVERY` is to be verified.
Here and in some other occurrences you use the notion "module ID". We have refactored this in some of the recent updates, now it is called "module name".
You can just search in the document and replace all "module ID" with "module name" and "`MODULE_ID`" with "`MODULE`".

2022-10-25 11:50 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Command Verification
Here and in the State Recovery Command Execution the code snippets need to be updated according to the last version: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0054.md#verification.
Note that the PR that was open is merged now.

2022-10-25 12:34 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* `The chainID` is the ID of the respective sidechan to be terminated.
well spotted! 👍

2022-10-25 12:35 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +=== Liveness Termination Command
Yes, you are right, it should be fixed now 👍

2022-10-25 12:58 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The module name is `MODULE_NAME_INTEROPERABILITY`, and the command ID is `COMMAND_STATE_RECOVERY` and the state recovery command schema, verification, and execution can be seen below:
Done 👍

2022-10-25 13:04 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Message Recovery Command Verification Schema
OK, Iall instances of 'schema' when describing the commands should now be removed 👍

2022-10-25 13:05 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Assuming `trs` is a transaction with the module `ID MODULE_ID_INTEROPERABILITY`, and the command ID `COMMAND_STATE_RECOVERY` is to be verified.
OK cool...Many thanks, it should now be done... 👍

2022-10-25 13:41 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.State Recovery Command Verification
OK, these have been updated... In addition, the State Recovery Command section has also been updated 👍

2022-10-25 13:44 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +==== Message Recovery Command
It should be done now 👍

2022-10-25 13:48 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* *Chain ID*
Sounds good...It should now be updated 👍

2022-10-25 14:33 UTC, sergeyshemyakov approved these changes
Nice!

2022-10-26 07:20 UTC, AndreasKendziorra approved these changes

2022-10-28 15:03 UTC, TalhaMaliktz requested changes
Looks Good :). Just some suggestions

2022-10-28 15:03 UTC, TalhaMaliktz commented on build/preview-site.yml
> +    branches: [docs-sdk, docs-service,1604-update_binary_setup_page-core,docs-manual]
Please undo these changes as these changes should only stay locally.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +A sidechain is a separate blockchain next to the mainchain, where the inclusion of a transaction in one of the blockchains can have an effect in the other blockchain.
```suggestion
A sidechain is a separate blockchain next to the mainchain, where the inclusion of a transaction in one of the blockchains can have an effect on the other blockchain.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The main purpose of deploying sidechains in the Lisk ecosystem is to increase scalability. Therefore, the more sidechains that exist in the ecosystem mean the more transactions that can be processed
```suggestion
The main purpose of deploying sidechains in the Lisk ecosystem is to increase scalability. Therefore, the more sidechains that exist in the ecosystem mean the more transactions can be processed per second.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When a sidechain is registered on the mainchain, as previously mentioned, an ecosystem wide chain ID and name are assigned to this chain.
```suggestion
When a sidechain is registered on the mainchain, as previously mentioned, an ecosystem-wide chain ID and name are assigned to this chain.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `name` property sets the name of the sidechain as a string of characters, and has to be unique within the Lisk ecosystem, and contains only characters from the set *a-z0-9!@$&_.*
```suggestion
The `name` property sets the name of the sidechain as a string of characters. It has to be unique within the Lisk ecosystem, and should contain only characters from the set *a-z0-9!@$&_.*
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Certain parameters are set by the mainchain registration command in the sidechain that is related to the interoperability module, and also initialize the corresponding mainchain data structures.
```suggestion
Certain parameters are set by the mainchain registration command in the sidechain that is related to the interoperability module. It also initializes the corresponding mainchain data structures.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For example, this could be caused by not posting a transaction with a cross-chain update (CCU), command for more than 30 days, or in the case whereby one was posted with a malicious CCU command on th
```suggestion
For example, this could be caused by not posting a transaction with a cross-chain update (CCU) command for more than 30 days, or in the case whereby one was posted with a malicious CCU command on the mainchain.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* `chainID` : The ID of the sidechain whose terminated state account is to be initialized or updated.
```suggestion
* `chainID`: The ID of the sidechain whose terminated state account is to be initialized or updated.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For further information, including the `createTerminatedStateAccount` function can be found in xref:{url_lip}[LIP 0045].
```suggestion
Further information including, the `createTerminatedStateAccount` function can be found in {url_lip}[LIP 0045].
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The module name is `MODULE_NAME_INTEROPERABILITY`, and the command name is `COMMAND_STATE_RECOVERY` and the state recovery command schema, verification, and execution can be seen below:
This breaks the flow for me, are you referring to an example here? I think this sentence should be improved somehow.
```suggestion
The module name is `MODULE_NAME_INTEROPERABILITY`, and the command name is `COMMAND_STATE_RECOVERY`. The state recovery command schema, verification, and execution can be seen in the following code snippet below:
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Figure 2: The Interoperability module store.
There is a specific way to add captions of images in the asciidoc, please update all captions of the images to match the following:

```suggestion
.The Interoperability module store.
image::understand-blockchain/interop/interoperability-module-store.png[ align="center" ,800]
```

The figure number will be automatically added, you just need to add the text.

Also, the code `image::` is correct as compared to `image:`

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Such a transaction emits one or more xref:{url_ccm}[cross-chain messages] on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred t
`xref:{url_ccm}[cross-chain messages]` and `xref:{url_ccu}[cross-chain updated transaction]` These URLs should point to the section where the said terminologies are defined and discussed.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This is how a transaction from a sidechain (the mainchain) can have an effect on the mainchain (a sidechain).
What do you mean here with "sidechain (the mainchain)" and "mainchain (a sidechain)". Please rephrase this to improve readability.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Such a transaction emits one or more xref:{url_ccm}[cross-chain messages] on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred t
It would be better IMHO to say the emit **from** the sending chain rather than emit **on** the sending chain.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Such a transaction emits one or more xref:{url_ccm}[cross-chain messages] on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred t
`The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred to the sending chain`?
Shouldn't that be transferred to the receiving chain?

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +It is intended that each blockchain serves one application, which means, for instance, there could be a sidechain dedicated to a decentralized exchange application.
```suggestion
It is intended that each sidechain serves one application, which means, for instance, there could be a sidechain dedicated to a decentralized exchange application.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command creates the sidechain account on the mainchain with the initial status set to 'registered'.
```suggestion
This command creates the sidechain account on the mainchain with the initial status set to `registered`.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +A message targeting a terminated chain is bounced on the mainchain instead of being forwarded.
```suggestion
A message targeting a terminated chain is bounced back to the mainchain instead of being forwarded.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +A sidechain account can also be terminated if the sidechain posts a CCU containing a CCM with an invalid schema or with an invalid sending chain ID.
```suggestion
A sidechain account can also be terminated if the sidechain posts a CCU containing a CCM with an invalid schema or with an invalid sending `chainID`.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +As described in the Lifecycle of a Sidechain section above, once the Sidechains registration process has been completed, it does not need to be activated on the mainchain, and will remain inactive un
Please add a reference for Lifecycle-of-a-Sidechain-section

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Each box represents a substore, where we indicate the `storeKey --> storeValue relation`.
```suggestion
Each box represents a substore, where we indicate the `storeKey -> storeValue relation`.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `initValidators` property defines the set of eligible xref:{url_bls}[BLS public keys] with their respective xref:{url_bft_weights}[BFT weights] required to sign the first certificate from the sid
xref:{url_bls}[BLS public keys] is not working, please correct.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The chain ID is a 4-byte constant set in the chain configuration.
```suggestion
The `chainID` is a 4-byte (8-character) hexadecimal string, which is set in the chain's configuration.
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Sidechain Parameters
```suggestion
.Sidechain Registration Parameters
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Mainchain Parameters
```suggestion
.Mainchain Registration Parameters
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/interoperability-module-store.png[ align="center" ,800]
- The elements in the images should be aligned (possibly center aligned). 
- Also, please only use either of the company-supported fonts such as  "Roboto" or "Poppins" in the diagrams.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image:understand-blockchain/interop/mainchain-recovery.png[, align="center" ,500]
- Same comments as above about images.
- Please use the company colors only.
- The vertical arrows are tilted slightly towards to right, please straighten them. 

This applies to the following images as well.

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Verification Parameters
```suggestion
.Mainchain Verification Parameters
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Execution Parameters
```suggestion
.Mainchain Execution Parameters
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Verification Parameters
```suggestion
.Sidechain Verification Parameters
```

2022-10-28 15:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +.Execution Parameters
```suggestion
.Sidechain Execution Parameters
```

2022-10-31 12:44 UTC, chris529 commented on build/preview-site.yml
> +    branches: [docs-sdk, docs-service,1604-update_binary_setup_page-core,docs-manual]
Done 👍

2022-10-31 13:54 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Such a transaction emits one or more xref:{url_ccm}[cross-chain messages] on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred t
Now done 👍

2022-10-31 13:57 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This is how a transaction from a sidechain (the mainchain) can have an effect on the mainchain (a sidechain).
Good point, now reworded to simplify it 👍

2022-10-31 14:13 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Such a transaction emits one or more xref:{url_ccm}[cross-chain messages] on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred t
Good point...now updated accordingly 👍

2022-10-31 14:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Such a transaction emits one or more xref:{url_ccm}[cross-chain messages] on the sending chain. The emitted cross-chain messages on the sending chain are then collected by a relayer and transferred t
Yes, it should...now corrected 👍

2022-10-31 14:18 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +As described in the Lifecycle of a Sidechain section above, once the Sidechains registration process has been completed, it does not need to be activated on the mainchain, and will remain inactive un
Done 👍

2022-10-31 14:39 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The `initValidators` property defines the set of eligible xref:{url_bls}[BLS public keys] with their respective xref:{url_bft_weights}[BFT weights] required to sign the first certificate from the sid
These entries have been removed from the Glossary, so I have removed the corresponding links 👍

2022-11-02 10:14 UTC, TalhaMaliktz requested changes
Looks great now, just one suggestion :)

2022-11-02 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image::understand-blockchain/interop/sidechain-recovery3-v1.png[, align="center" ,500]
The images look nice now, however, captions for each are missing for these images. An image must have a caption. Also, Please add Sidechain Recovery Command stage/step **x**, where x could be 1, 2, 3 inside the image to clarify that this is a step-by-step process.

2022-11-02 11:08 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image::understand-blockchain/interop/sidechain-recovery3-v1.png[, align="center" ,500]
Good point..now done 👍

2022-11-02 12:50 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +image::understand-blockchain/interop/sidechain-recovery3-v2.png[, align="center" ,500]
```suggestion
.Recovery process from the sidechain (Step 1)
image::understand-blockchain/interop/sidechain-recovery1-v2.png[, align="center" ,500]
.Recovery process from the sidechain (Step 2)
image::understand-blockchain/interop/sidechain-recovery2_v2.png[, align="center" ,500]
.Recovery process from the sidechain (Step 3)
image::understand-blockchain/interop/sidechain-recovery3-v2.png[, align="center" ,500]
```

2022-11-02 12:53 UTC, TalhaMaliktz approved these changes
LGTM :)

2022-11-02 14:47 UTC, merged