Merge `Introduction to the Lisk SDK` into the `Understand Blockchain` page, update based on v6. - Closes 1628
LiskArchive/lisk-legacy-docs pull request #1635
Opened 2022-09-28 14:48 UTC by TalhaMaliktz

Closes #1628

2022-09-28 15:52 UTC, Tschakki requested changes
Looking great already!

Please have a look at my comments :)

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +image::understand-blockchain/lisk-blockchain-overview.png["Lisk blockchain overview", 600, align="center"]
Some feedback concerning the image:

- I think Commander communicates to the blockchain via RPC as well
- Lisk Core is the blockchain application of the Lisk Mainchain, I would keep the diagram more general, naming the CLI blockchain application CLI (maybe sometimes it makes sense to use an abbreviation like `BApp CLI`, but currently we don't use this short term so we would need to clarify this).
- The CLI doesn't use Commander afaik
- A user can communicate directly with a node via RPC communication, this is not reflected in the diagram.
- The image of the blockchain network looks nice, but can be a little misleading: E.g., what is the difference between the small and big circles of the mainchain? Also, how the nodes are connected does not reflect reality (small circles are always connected to big circles?) maybe i wouldn't even picture the node network here (we also have network topology below, which could be updated to include mainchain and at least 2 sidechains) and just picture the chain of blocks are representation of the mainchain and sidechains.
- Also for clarify, I would include at least 2 different sidechains in the diagram, and color them differently

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +xref:{url_lisk_service}[Lisk Service] allows interaction with the blockchain network based on Lisk protocols. Lisk Service acts as a bridge between external software and the Lisk blockchain. We recom
Technically, it doesn't allow it, but it makes it a lot more convenient by aggregating the relevant data for external services, enriching it if needed with off-chain data, and providing additional endpoints to get the data efficiently.

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A blockchain is a chain of interconnected blocks on various nodes distributed across a P2P network.
We now have a separate page explaning `what-is-blockchain.adoc` in the intro section.
I think it would be nice to refer to this page at this point

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Applications built with Lisk blockchains are called "blockchain applications". These applications can have customized logic, UIs, and a blockchain as their application's database.
```suggestion
**Applications built with Lisk blockchains are called "blockchain applications". **These applications can have customized logic, UIs, and a blockchain as their application's database.
```

Would make that statement bold :)

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +image:architecture.png[lisk-framework-architecture, 900 , align="center"]
The diagram looks really nice!  
Just a few suggestions:

- On the bottom left: Would rename "blockchain" to "node network" or "blockchain network"
- right side: Data store image is not visible in dark mode
- What does the arrow between P2P and chain stand for? Do they have a special connection?
- top left: same remarkd for CLI & Commander as for the above diagram

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The frontend can then request this data via API requests from the middleware.
In v5, Lisk Service was only working for Lisk Core, this is why I wrote this section in more general terms, saying "Something _like_ Lisk service" - but with SDK v6, Service will become blockchain agnostic, so it will work for every other blockchain application, and can be customized further by the user. This is why this section should be updated to clearly mention and recommend Lisk Service as data aggregation service of choice (ofc they can still implement their own service if there is the need to)

2022-09-28 15:52 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> -In the "Understand blockchain" category you learn the basic concepts of blockchain applications, including how they are structured and which topics and terms are important to know when developing wit
Where did all this content go, is it moved somewhere else? I cannot see it included in this PR. The content is still valid and shouldn't get lost.

Also the 3 domains of blockchain section is something that would fit nicely in the beginning of this page imho.

2022-09-29 07:48 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each side chain is registered to the main chain and is specific to a blockchain application.
Throughout the docs, we should maintain uniformity with the 'mainchain' and 'sidechain' terms. For the most part, we use mainchain and sidechain and not main chain and side chain, so I would suggest we stick with 'mainchain' and 'sidechain'.

2022-09-29 08:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> -In the "Understand blockchain" category you learn the basic concepts of blockchain applications, including how they are structured and which topics and terms are important to know when developing wit
Ummmmm, I have kept a copy of both the files from my development branch locally.

2022-09-29 13:15 UTC, chris529 reviewed
Looks great Talha! just minor points so far... 👍

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Unlike Ethereum, where dApps have to share the same chain for their blockchain needs, Lisk provides the opportunity for each application to have its side chain.
```suggestion
Unlike Ethereum, where dApps have to share the same chain for their blockchain needs, Lisk provides the opportunity for each application to have its own sidechain.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It also provides faster block generation and lessens the burden on the network.
```suggestion
It also provides faster block generation, reduces the burden on the network, and increases scalability.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +These side chains can also communicate with other side chains with the help of xref:{lisk_cross_chain_communication}[Lisk Cross Chain Communication].
```suggestion
These sidechains can also communicate with other sidechains by utilizing the xref:{lisk_cross_chain_communication}[Lisk Cross-chain communication methodology].
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +An overview of Lisk Blockchain can be seen in the following diagram.
```suggestion
An overview of Lisk Blockchain can be seen below in the following diagram.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +xref:{url_lisk_service}[Lisk Service] allows interaction with the blockchain network based on Lisk protocols. Lisk Service acts as a bridge between external software and the Lisk blockchain. We recom
Fair point..Perhaps you could reword this sentence..? Perhaps something along the following lines:

''Lisk Service acts as a service layer and interacts with the Lisk ecosystem, offering the possibility to aggregate  the relevant data, coupled with enriching it with off-chain data if necessary, and also providing additional endpoints if required''

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It is also a partial mesh network, which means that every node is only connected to a small subset of nodes in the network.
```suggestion
It is also a partial mesh network, therefore every node is only connected to a small subset of nodes in the network.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +They also can scale extremely well, even for large networks with thousands of connected nodes.
```suggestion
In addition, they also have the ability to scale extremely well, even for large networks with thousands of connected nodes.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +As mentioned earlier, a blockchain application consists of a network of nodes connected via P2P. Each node has an instance of Lisk Protocol and together, these nodes form a chain. The on-chain logic
```suggestion
As mentioned earlier, a blockchain application consists of a network of nodes connected via P2P. Each node has an instance of Lisk Protocol and together, these nodes form a chain. The on-chain logic present in each instance of the Lisk protocol must be the same for a chain. However, the off-chain logic for each node can differ within a chain.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each blockchain application has its blockchain known as a side chain. This side chain is registered with the main chain.
```suggestion
Each blockchain application has its own separate blockchain which is known as a sidechain. This sidechain is registered with the main chain.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A node can only connect to a single network which can either be the main chain or the side chain.
```suggestion
A node can only connect to a single network, this can either be the mainchain or a sidechain.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The Lisk Protocol is divided into two layers:
```suggestion
The Lisk Protocol is divided into the following two layers:
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A detailed picture of the Lisk Protocol is present in the following architecture diagram.
```suggestion
A detailed illustration of the Lisk Protocol can be seen in the following architecture diagram below.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Its job is to connect with the outside world i.e. external services and software to send and receive data from them.
```suggestion
The function of the application layer acts as an interface to connect to the outside world, such as various external services in order to send and receive data.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* *States:* A state machine typically has a set of different states that it can enter. For example, a padlock represented as a state machine would have the two states "Open" and "Locked".
```suggestion
* *States:* A state machine is deterministic and can have multiple states, but only one state at any given time. For example, a basic analogy could be whereby a padlock represented as a state machine would have the following two states "Unlocked" and "Locked".
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* *Transitions*: A set of allowable operations that change one state to another. For example, to change from the state "Open" to "Locked", a transition would be "Close padlock", and from "Locked" to
```suggestion
* *Transitions*: A transition is defined as the instantaneous transfer from one state to another state. For example, using our padlock analogy, to change from the state "Unlocked" to "Locked", a transition would be "Close padlock", and then from "Locked" to "Unlocked", it would be "Insert key & turn".
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Lisk Protocol changes states with the help of modules, which define the on-chain logic for the blockchain application.
```suggestion
The Lisk protocol changes states by using modules, which define the on-chain logic for the blockchain application.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +For example, if Bob wants to send 10 LSKs to Alice then, behind the scenes a module will verify the validity of such a request.
```suggestion
For example, if Bob wants to send 10 LSK tokens to Alice then, behind the scenes a module will verify the validity of such a request.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Upon validation and verification, the module will ask the state machine to transfer 10 LSKs from Bob's account to Alice's account.
```suggestion
Upon validation and verification, the module will ask the state machine to transfer 10 LSK tokens from Bob's account to Alice's account.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +For example, consider a case where a node wants to investigate possible misbehaviors in the Lisk network. For that, the node operator must gather all the blocks' data from the network, store it somew
```suggestion
For example, consider a case whereby a node wants to investigate any possible misbehavior in the Lisk network. To achieve this, the node operator must acquire all the blocks' data from the network, save it, and then analyze it to determine if any misbehavior had occurred.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A node manager can write a script to perform the aforementioned task. However,  Lisk provides the xref:{url_references_report_misbbehavior_plugin}[Report Misbehavior Plugin] which listens to blocks'
```suggestion
A node manager can write a script to perform the aforementioned task. However, Lisk provides the xref:{url_references_report_misbbehavior_plugin}[Report Misbehavior Plugin] which listens to blocks' data and reports a node with regard to a generator's misbehavior.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +These configurations can be tweaked as per necessity.
```suggestion
These configurations can be individually tweaked as necessary.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +For off-chain domains and logic e.g. Plugins etc., the configurations can differ for each node.
```suggestion
For off-chain domains and logic, e.g. Plugins, etc., the configurations can differ for each node.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +However, the configurations for on-chain logic e.g. Modules etc., must be the same across the network of a blockchain application.
```suggestion
However, the configurations for on-chain logic, e.g. Modules, etc., must be the same across the network of a blockchain application.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Lisk understands the need for flexibility in terms of how a node should be run or how specific on-chain and off-chain logic should execute.
```suggestion
The Lisk solution is both convenient and flexible in terms of how to operate a node, coupled with how to execute both on-chain and off-chain logic. 
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It is similar to mempool in Ethereum.
```suggestion
It can be considered similar to mempool in Ethereum.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The transaction pool receives the new transaction, verifies it with the help of the Application layer, and then stores it in the transaction pool until its part of a block.
```suggestion
The transaction pool receives the new transaction, verifies it with the help of the Application layer, and then stores it in the transaction pool until it becomes part of a block.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Node operator can change transaction properties like _maximumTransactionsLimit_, _transactionPerAccount_, _minimumRequirementFee_, and _minimumReplacementFee_, etc.
```suggestion
The node operator can change the transaction properties, such as _maximumTransactionsLimit_, _transactionPerAccount_, _minimumRequirementFee_, and _minimumReplacementFee_, etc.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +After a consensus for a block is reached and the state has been changed, the new block's information is passed to the Chain.
```suggestion
After a block reaches consensus and the state has been changed, the new block's information is then passed to the Chain.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It also maintains an active connection with the Lisk Network.
```suggestion
It also maintains an active connection with the Lisk network. 
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +If the received block is verified, the receiving node adds it to their instance of blockchain.
This last line seems a bit unclear to me, so if I am correct shouldn't this read as follows..?

''If the received block is verified, then the receiving node adds it to its blockchain instance''.

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each blockchain node keeps data on various data stores inside its Lisk protocol instance. This data is of two types: on-chain and off-chain.
```suggestion
Each blockchain node keeps data on various data stores inside its Lisk protocol instance. This data contains the following two types: on-chain and off-chain.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Lisk also maintains off-chain data about the legacy chains.
```suggestion
Lisk also maintains off-chain data regarding the legacy chains.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Legacy data consists of blocks from depreciated versions of the protocol.
Shouldn't this be... "deprecated versions of the protocol"..?

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +More specifically, within the Lisk documentation, every time we talk about blockchain applications, we are referring to applications running on blockchains that are compatible with <<lisk-protocol>>.
```suggestion
More specifically, within the Lisk documentation, whenever blockchain applications are discussed, this is directly referring to applications running on blockchains that are compatible with the <<lisk-protocol>>.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +image::intro/ui-diagrams.png[different-structures-of-blockchain-application,700 ,align="center"]
In the ui-diagrams.png we should try to maintain uniformity, so with the first 2 node headings, they should read as follows:
"**Frontend** as a Plugin" and "Standalone **F**rontend + Backend"

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Blockchain applications usually consist of a frontend and a backend, like normal web applications.
```suggestion
Blockchain applications usually consist of a frontend and a backend, just like normal web applications.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +TIP: Although it is possible to build UI through plugins, It is recommended to separate the UI from the backend of the application for scalability.
```suggestion
TIP: Although it is possible to build a UI through plugins, It is recommended to separate the UI from the backend of the application to increase scalability.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Plugins can be used to develop UI for a blockchain application. You can create and register a UI xref:{url_introduction_plugins}[plugin] for your blockchain application.
```suggestion
. Plugins can be used to develop a UI for a blockchain application. You can create and register a UI xref:{url_introduction_plugins}[plugin] for your blockchain application.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Thus it is growing much slower in size and doesn't suffer so much from potential bottlenecks in the network, which can happen during times of high workload on many different dApps.
```suggestion
Hence it is growing much slower in size and doesn't suffer as much from potential bottlenecks in the network, which can happen during times of high workload on many different dApps.
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* Interoperability is another perk of Lisk. Various side chains registered to the main chain can communicate with each other and exchange value through the main chain.
```suggestion
* Interoperability is a key beneficial advantage of Lisk. Various sidechains registered to the mainchain can efficiently and securely communicate with each other and exchange data through the mainchain.  
```

2022-09-29 13:15 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> -In the "Understand blockchain" category you learn the basic concepts of blockchain applications, including how they are structured and which topics and terms are important to know when developing wit
Agreed 👍

2022-09-29 14:30 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Legacy data consists of blocks from depreciated versions of the protocol.
Ummmm the term depreciate is correct here. Here are the definitions for both

[depreciated](https://www.google.com/search?q=depreciated&rlz=1C5CHFA_enPK1012PK1012&sourceid=chrome&ie=UTF-8)
[deprecated](https://www.google.com/search?q=deprecated&rlz=1C5CHFA_enPK1012PK1012&sourceid=chrome&ie=UTF-8)

2022-09-29 14:30 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +If the received block is verified, the receiving node adds it to their instance of blockchain.
Yes, agreed.

2022-09-30 13:57 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Plugins can be used to develop a UI for a blockchain application. You can create and register a UI xref:{url_introduction_plugins}[plugin] for your blockchain application.
. Plugins can be used to develop a UI for a blockchain application, in case of a very simple and small UI.
You can create and register a UI xref:{url_introduction_plugins}[plugin] for your blockchain application.
It is *not* recommended to develop complex production-ready UIs in plugins.

2022-09-30 13:58 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Plugins can be used to develop a UI for a blockchain application. You can create and register a UI xref:{url_introduction_plugins}[plugin] for your blockchain application.
```suggestion
. Plugins can be used to develop a UI for a blockchain application, in case of a very simple and small UI.
You can create and register a UI xref:{url_introduction_plugins}[plugin] for your blockchain application.
It is *not* recommended to develop complex production-ready UIs in plugins.
```

2022-09-30 14:02 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Use your favorite framework/ programming language to develop a *standalone user interface*, and communicate to the node via the available <<communication-interfaces-apis>>.
```suggestion
. Use your favorite framework/ programming language to develop a *standalone user interface*, and communicate to the node via the available <<communication-interfaces-apis>>.
Please be aware, every node has only a few basic API endpoints(here link to RPC endpoints page), which might not be ideally suited for more complex UIs. 
In this case, we recommend to use the enriched API of Lisk Service as middleware to communicate between frontend and blockchain application.
```

2022-09-30 14:05 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The frontend can then request this data via API requests from the middleware.
```suggestion
. For later requirements in a production environment, we highly recommend to use xref:{url_lisk_service_intro}[Lisk Service], which will aggregate the data from the blockchain network and other 3rd party sources, and will provide an enriched API with a lot of more endpoints and  query options.
With Lisk Service, you can also create a custom services as per your business needs to support various UI projects like mobile and web applications.
The frontend can then request this data via API requests from Lisk Service.
```

2022-10-04 11:34 UTC, Tschakki requested changes
It's shaping up really nice!

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It is a combination of the mainchain and many interconnected sidechains.
```suggestion
It is a combination of the Lisk mainchain and many additional sidechains.
The mainchain and sidechains are independent blockchain networks, which are interconnected by following the xref:{url_understand_interoperability}[] protocol.
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each sidechain is registered to the mainchain and is specific to a blockchain application.
In this line, we mention the term "blockchain application" for the very first time. To improve the flow, please move the last paragraph explaining bapps (line 85 and following), right below this line.

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It also provides faster block generation, reduces the burden on the network, and increases scalability.
Add link to scalablity introduction page here

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Anything else discussed ahead, can be developed differently as long as they comply with the Lisk protocol rules.
I am not sure if this is accurate. Everything else doesn't need to comply with the protocol, as it is not defined in it, as far as I understand it.

```suggestion
Other components of the application that are not part of the 3 blockchain domains, like the Transaction Pool, etc. can be implemented differently by the developer if desired, without breaking the protocol.```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It is recommended to use Lisk's implementation of the protocol to avoid erroneous behavior.
This could be also highlighted as a TIP

```suggestion
TIP: It is recommended to use Lisk's implementation of the engine components to avoid erroneous behavior.
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +== What is Lisk Blockchain?
```suggestion
== What are Lisk Blockchain Applications?
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Lisk Network
```suggestion
=== Network topology
```
To make it more specific that this section is describing

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +image::intro/node-network.png[Side chain's node network, 800 ,align="center"]
The image is not accurate like this. It claims to describe network nodes, but the image shows a chain of blocks, not nodes.

Please update the diagram to show the acutal network topology of a Lisk ecosystem with 1 mainchain and 2 example sidechains. Also  include modules and plugins examples in nodes, like in this diagram: https://lisk.com/documentation/understand-blockchain/index.html#network-topology-diagram

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each chain such as a sidechain or mainchain consists of a network of servers, which are also called *nodes* in this context.
```suggestion
The Lisk ecosystem consists of various interconnected blockchain applications.
Each blockchain application maintains a separate, independent blockchain with a network of interconnected servers, which are also called *nodes* in this context. 

The different blockchain applications communicate with each other via relayer nodes by following the xref:{url_understand_interoperability}[] protocol.
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +All nodes in the network need to share the same on-chain logic as described in <<Modules>>. On the contrary, the off-chain logic as discussed in <<Plugins>> can differ from node to node.
```suggestion
All nodes belonging to the same blockchain application need to share the same on-chain logic as described in <<Modules>>.
On the contrary, the off-chain logic as discussed in <<Plugins>> can differ from node to node.
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +All nodes in the network need to share the same on-chain logic as described in <<Modules>>. On the contrary, the off-chain logic as discussed in <<Plugins>> can differ from node to node.
if we picture now a multi-blockchain network, we need to adjust this sentence.

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In addition, they also have the ability to scale extremely well, even for large networks with thousands of connected nodes.
This is only true for nodes belonging to the bapp. Maybe we can remove this section from here and add it to #1489

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +It does so by invoking the RPC endpoints available for cross-chain communication.
This would need to be improved, but for now I think we can just remove this paragraph, as we can refer to the interoperability explanation pages above.

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Lisk Protocol
We use the term "Lisk protocol" to describe the collection of LIPs, so this title here is not fitting. In this section, we talk about the bapp architecture, so the title should reflect that.

```suggestion
=== Architecture of blockchain applications
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A node can only connect to a single network, this can either be the mainchain or a sidechain.
Would remove, not relevant here

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The Lisk Protocol is divided into the following two layers:
```suggestion
The architecture of a blockchain application is divided into the following two layers:
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The Lisk Protocol is divided into the following two layers:
please update this on the other locations as well

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +****
This section is breaking the flow quite heavily - we are talking about bapps all the time on this page, and the last chapter is finally explaining what it is xD

I would move this part defining/explaining bapps to the respective section at line 78 and following at the beginning

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Structure of blockchain applications
Section title should be updated to be more fitting.
Something like:

```suggestion
=== Frontend & UI integration
```

2022-10-04 11:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Blockchain applications vs. dApps
```suggestion
=== Blockchain applications vs. dApps
```

2022-10-04 13:19 UTC, chris529 reviewed
Looks very good! ...just a few minor points 👍

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +This page explains the three domains of a blockchain, and gives introduction to blocks and transactions.
```suggestion
This page explains the three domains of a blockchain and provides an introduction to blocks and transactions.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +At a high level, there are three domains of a blockchain:
```suggestion
From a high-level perspective, there are three domains of a blockchain which are explained below:
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +Detailed descriptions of the main properties of a block are provided in the following sections.
```suggestion
A detailed description covering the main properties of a block is provided in the following sections.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +Blocks are serialized and deserialized accordingly to the following JSON schema.
```suggestion
Blocks are serialized and deserialized in accordance with the following JSON schema.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +The most important properties of the block header are:
```suggestion
The most important properties of the block header are as follows:
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +* `timestamp`: Time the block was created as Unix timestamp.
```suggestion
* `timestamp`: The time the block was created as a Unix timestamp.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +* `transactionRoot`: The transaction root is the root of the Merkle tree built from the ID of the <<transactions,transactions contained in the block>>.
Shouldn't this be as follows...?
<< transactions contained in the block >>.

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +The state root is the root of the sparse Merkle tree built from the state of the chain after the block has been processed{fn_stateroot}.
I think you are missing the link info here, shouldn't it be as follows..? 
xref:{fn_stateroot}[...] or {fn_stateroot}[...^]

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +Beside the above properties, each block header contains various additional properties, required for deeper technical aspects of the blockchain application.
```suggestion
Besides the above listed properties, each block header contains various additional technical properties that are required for the blockchain application to function.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +Expand below boxes for a description of the additional properties, and see the JSON schema for an overview of all properties included in the header.
```suggestion
To view a description of the additional properties, expand the boxes shown below, and also see the JSON schema for an overview of all properties included in the header.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +* `version`: The block header version must be equal the value of a block of the previous protocol plus one.
```suggestion
* `version`: The block header version must be equal to the value of a block of the previous protocol plus one.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +It is important for cross-chain certification and included in certificates.
```suggestion
This is important for cross-chain certification and included in certificates.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +Block headers are serialized and deserialized accordingly to the following JSON schema.
```suggestion
Block headers are serialized and deserialized in accordance with the following JSON schema.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +NOTE: Inserting the assets root rather than the full assets allows to bound the size of the block header to a fixed size, while still authenticating the content of the block assets.
```suggestion
NOTE: Inserting the assets root rather than the full assets allows the possibility to bound the size of the block header to a fixed size, while still authenticating the content of the block assets.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +To be accepted by the blockchain application, the transactions must be transmitted in the expected format, including all the required properties of a transaction, and pass the transaction & command v
```suggestion
To be accepted by the blockchain application, the transactions must be transmitted in the expected format, including all the required properties of a transaction, and pass the transaction & command verification steps explained in the <<block-processing>> description.
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +At a high level, there are three domains of a blockchain:
```suggestion
From a high level perspective, there are three domains of a blockchain which are described below:
```

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Anything else discussed ahead, can be developed differently as long as they comply with the Lisk protocol rules.
Yes, agreed. I think Mona's suggestion here covers this point well 👍

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Legacy data consists of blocks from depreciated versions of the protocol.
OK 👍

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +****
Agreed. 👍

2022-10-04 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +With Lisk Service, you can also create a custom service as per your business needs to support various UI projects like mobile and web applications.
```suggestion
With Lisk Service, you can also create a custom service as per your business requirements to support various UI projects, such as mobile and web applications. 
```

2022-10-04 15:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index-pre1628-old.adoc
> +* `transactionRoot`: The transaction root is the root of the Merkle tree built from the ID of the <<transactions,transactions contained in the block>>.
Ummmmm, I think this one is correct as the term "**transaction**" points to its particular section, and the "**transactions contained in the block**" is the alternate text that we would like to have for our hyperlink. So in the text preview, the reader will see "**transactions contained in the block**"; if they click on this link, they will be redirected to the "**Transactions**" section.

2022-10-06 09:20 UTC, chris529 reviewed
Looks great! just a few very minor points 👍

2022-10-06 09:20 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Other components of the application that are not part of the three blockchain domains, like the Transaction Pool, etc. can be implemented differently by the developer if desired, without breaking the
```suggestion
Other components of the application that are not part of the three blockchain domains, such as the Transaction Pool, etc. can be implemented differently by the developer if desired, without breaking the protocol.
```

2022-10-06 09:20 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each blockchain application has its own separate blockchain which is known as a sidechain. This sidechain is registered with the main chain.
```suggestion
Each blockchain application has its own separate blockchain which is known as a sidechain. This sidechain is registered with the mainchain.
```

2022-10-06 09:20 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The Lisk documentation refers to applications built with the Lisk protocol as "blockchain applications" and not "dApps". To clarify the difference, blockchain applications do not share a common block
```suggestion
The Lisk documentation refers to applications built with the Lisk protocol as "blockchain applications" and not "dApps". To clarify the difference, blockchain applications do not share a common blockchain, but instead, each runs on its own chain.
```

2022-10-06 09:28 UTC, chris529 approved these changes
LGTM! 👍

2022-10-19 12:40 UTC, Tschakki requested changes
I made some suggestions to improve the intro part, rest looks very good!

Maybe at the end, we should request additional review from Shu or Ishan, and maybe even someone from Marketing, just to ensure highest quality, because it is such a central page.

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +== What is Lisk Blockchain?
```suggestion
== What is the Lisk Blockchain?
```

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A xref:{url_what_is_blockchain}[blockchain] is a chain of interconnected blocks on various nodes distributed across a P2P network.
Imho it would be better to use a footnote here, something like "For a general introduction into blockchain, please check out the introduction page "What is blockchain""

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each node keeps its copy of the blockchain protocol and its related data. It syncs periodically with other nodes to ensure that the nodes' records are up to date.
```suggestion
Each node keeps its copy of the blockchain protocol and its related data.
It syncs periodically with other nodes to ensure that the nodes' records are up to date.
```

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The mainchain and sidechains are independent blockchain networks, which are interconnected by following the xref:{url_understand_interoperability}[] protocol.
```suggestion
The Lisk blockchain can actually be described as an **ecosystem of blockchains**, where many different blockchains are interconnected through a central blockchain, called the **Lisk Mainchain**.
All other connected blockchains are called *sidechains* in this context.
To become interoperable with any other blockchain in the Lisk ecosystem, a blockchain needs to follow the xref:{url_understand_interoperability}[] protocol.
```

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +**Applications built with Lisk blockchains are called "blockchain applications".**
```suggestion
Every blockchain is maintained by a network of blockchain nodes.
**If the nodes of a blockchain follow the https://github.com/LiskHQ/lips[Lisk protocol], they are called "blockchain applications"**.
```

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +:url_protocol: understand-blockchain/lisk-protocol/index.adoc
This page wont exist in the new version of docs, maybe refer to the LIPs on GitHub instead

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. For later requirements in a production environment, we highly recommend using xref:{url_lisk_service_intro}[Lisk Service], which will aggregate the data from the blockchain network and other 3rd pa
```suggestion
. **[recommended]** For later requirements in a production environment, we highly recommend using xref:{url_lisk_service_intro}[Lisk Service], which will aggregate the data from the blockchain network and other 3rd party sources and will provide an enriched API with a lot more endpoints and query options for the UI.
```

2022-10-19 12:40 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +image::intro/ui-diagrams.png[different-structures-of-blockchain-application,700 ,align="center"]
Connection between image and text could be improved by either adding a), b) and c) to the image, to match the list below, or to add titles to the list like "Frontend as plugin" and so on.

2022-10-21 13:47 UTC, TalhaMaliktz commented
> I made some suggestions to improve the intro part, rest looks very good!
> 
> Maybe at the end, we should request additional review from Shu or Ishan, and maybe even someone from Marketing, just to ensure highest quality, because it is such a central page.

Thanks for the feedback. I have applied your suggestions and It's ready for review. Yes, getting it reviewed by someone other than the docs team sounds like a good idea. 😊

2022-10-24 09:34 UTC, Tschakki requested changes
The page is looking excellent! Just a few minor points

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Unlike Ethereum, where dApps have to share the same chain for their blockchain needs, Lisk provides the opportunity for each application to have its own sidechain.
```suggestion
Unlike Ethereum, where smart contracts have to share the same chain for their blockchain needs, Lisk provides the opportunity for each application to have its own sidechain.
```

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Unlike Ethereum, where dApps have to share the same chain for their blockchain needs, Lisk provides the opportunity for each application to have its own sidechain.
following our terminology discussion, we should talk about smart contracts here  imho

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +As the name suggests, a state machine is relevant to the states of a machine. A blockchain application relies heavily on its state machine to mutate the state of a blockchain.
Please add a link to the state machine page here

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +xref:{url_introduction_modules}[Modules] are able to perform the following functions:
Please remove the link here and add it to line 183, when `Modules` is first mentioned

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +xref:{url_introduction_plugins}[] are able to perform the following:
Same here, please move link to Plugins page to line 201

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +However, the configurations for on-chain logic, e.g. Modules, etc., must be the same across the network of a blockchain application.
I think only modules and genesis config should not be different between nodes. Maybe we can be more precise here.

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +:url_consensus: understand-blockchain/consensus.adoc
this url is wrong. The url in line 18 is the correct one

2022-10-24 09:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +=== Blockchain applications vs. dApps
After our terminology discussion, this whole section will need to be updated. (also, a lot of content in the docs and on this page in general ^^)
I would suggest that we comment it out and update it once the discussion is completed.

2022-10-24 15:04 UTC, Tschakki approved these changes
Very nice!

2022-10-27 07:24 UTC, shuse2 requested changes
* on docs/modules/ROOT/images/architecture.png, it looks like it's sharing the same datastore between application and engine, but it's not sharing the same
* docs/modules/ROOT/images/intro/communication-architecture.png, it looks like endpoint cannot be accessed from other script, but it can be
* docs/modules/ROOT/images/intro/ui-diagrams.png, I think we said we can remove the pattern (a)?
* 
* i dont think we need to split http and other protocols
*

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +More specifically, within the Lisk documentation, whenever blockchain applications are discussed, this is directly referring to applications running on blockchains that are compatible with xref:{url_
this seems to be bit strange in global context. even if it doesn't follow the Lisk protocol (they create own protocol), it is still blockchain.
For example, new module they develop is not part of the Lisk protocol, or UI is not.

Also, `running on blockchains` vs `running using blockchains` might have slightly different meaning?

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each node keeps its copy of the blockchain protocol and its related data.
keeps its copy of the `blockchain data`?

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Unlike Ethereum, where smart contracts have to share the same chain for their blockchain needs, Lisk provides the opportunity for each application to have its own sidechain.
Instead of specifically saying Ethereum, we should say smart contract platform

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Their functionality is defined by Lisk and can only be configured if needed.
Application domain is where logic written by developer lives

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +*Each node has an instance of Lisk Protocol and together, these nodes form a chain*. The on-chain logic present in each instance of the Lisk blockchain application must be the same for a chain. Howev
instance of Lisk Protocol?

> The on-chain logic present in each instance of the Lisk blockchain application must be the same for a chain.

this should be either
`instance of the Lisk blockchain client` or `Lisk blockchain node`.

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* Provide a UI for the blockchain application.
this should be removed

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* Add a proxy to the application interfaces.
what do you mean by this?

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +To serve this purpose, the blockchain application accepts a configuration that is part of the state machine.
i don't really understand this. maybe we can rephrase. Also, configuration is not part of the state machine?

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +However, the Genesis configuration and the configuration for the on-chain logic such as Modules must be the same across the network of a blockchain application.
```suggestion
However, the Genesis configuration and the configuration for Modules must be the same across the network of a blockchain application.
```

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Engine layer
i don't think we need to explain engine layer in this level. Since the engine can be treated as a blackbox for developer, it can be in more nested place

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In contrast to normal server-client applications, there is not one central backend, but rather a whole network of nodes that together secure and maintain the status of the blockchain.
I think we should separate the network and server-client explanation here. (ie: we should not call blockchain node as `backend`

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Plugins can be used to develop a UI for a blockchain application, in the case of a very simple and small UI.
i think we shouldn't mention this in the first place since we don't recommened

2022-10-27 07:24 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +// TODO: this will be revised after terminology discussion.
👍

2022-10-27 12:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Plugins can be used to develop a UI for a blockchain application, in the case of a very simple and small UI.
I think this is mentioned since we have UI plugins such as faucet and dashboard etc. which are serving this purpose.

2022-10-27 12:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In contrast to normal server-client applications, there is not one central backend, but rather a whole network of nodes that together secure and maintain the status of the blockchain.
This page will be updated again, once the terminologies are finalized across all teams.

2022-10-27 13:00 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +. Plugins can be used to develop a UI for a blockchain application, in the case of a very simple and small UI.
yes, we do but those are specifically for development, and not intended for developer to build UI with the plugin

2022-10-27 13:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each node keeps its copy of the blockchain protocol and its related data.
Would this work for you?

```suggestion
Each node runs an instance of the blockchain client and also stores node-specific on-chain and off-chain data.
```

2022-10-27 13:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +To serve this purpose, the blockchain application accepts a configuration that is part of the state machine.
Ummmmm not sure what you mean. A configuration is part of the state machine as described in the text and the diagram. Can you please suggest more information about what change you might be looking for?

2022-10-27 14:11 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* Add a proxy to the application interfaces.
Not sure, it's existing text. @Tschakki can you please elaborate on this?

2022-10-27 14:13 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Engine layer
What would you like the engine layer to state? Please suggest changes in terms of text and also in the architecture.png diagram 🥲

2022-10-27 15:26 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Engine layer
For the beginning of the page, I think we can mention the engine layer, but without mentioning exact component of the engine.
We could say engine is responsible for network and consensus, and additionally it maintains transaction pool, RPC server and block generator. (I would specifically not mention `chain` because it's too low level)

I would refrain from writing the detail too much at this level, because if we change the internal working it will break the documentation although it is not breaking change.

2022-10-31 09:25 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Engine layer
Imho we don't add too much detail here, we just describe the purpose of each engine component briefly enough to understand its' purpose for the reader. I think it is important information to get the whole picture, and additionally, it complements our previous section of the 3 domains of blockchain, because 2 of that domains are actually inside the engine layer (p2p network & consensus).

Maybe what could be improved is to give more context to the reader, what exactly they can customize. Emphasize in the intro text of the engine layer, that this layer is not customizable by the developer (except they create their own engine, which is a very complex task).
And to complement it, we can also add a Note to the Application layer, that this part is completely customizable by the sidechain developer.

2022-10-31 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* Add a proxy to the application interfaces.
Not sure 100% as this is very old text, but i think in v5 you could add new actions / endpoints in a plugin, so you could provide additional RPC endpoints, and also create own APIs via plugin, like the HTTP plugin we had, maybe it is referring to that.

2022-10-31 14:04 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* Add a proxy to the application interfaces.
I have removed this line since we are unsure of it.

2022-10-31 14:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +==== Engine layer
Thanks for the feedback. I have pruned the text further and removed low-level details from the engine layer to make it more flexible. I have removed variable names, config properties, details related to the chain, etc. I have realigned the content to give an overview of the engine layer without going into too much detail. The diagram has also been updated.

2022-11-01 09:59 UTC, shuse2 approved these changes

2022-11-01 10:21 UTC, merged