Update Lisk SDK Overview page - Closes 1509
LiskArchive/lisk-legacy-docs pull request #1638
Opened 2022-10-07 13:38 UTC by TalhaMaliktz

Closes #1509

2022-10-07 14:49 UTC, chris529 reviewed
Looks great! Just 2 very minor points 👍

2022-10-07 14:49 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +* **One blockchain per app**: Each xref:{url_blockchain_apps}[blockchain applications] runs on its own customized blockchain.
```suggestion
* **One blockchain per app**: Each xref:{url_blockchain_apps}[blockchain application] runs on its own customized blockchain.
```

2022-10-07 14:49 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +* Completely modular: Configure, exchange or extend any of the blockchain-related logic in the application with *xref:{url_introduction_modules}[] and xref:{url_introduction_plugins}[]*.
```suggestion
* Completely modular: Configure, exchange, or extend any of the blockchain-related logic in the application with *xref:{url_introduction_modules}[] and xref:{url_introduction_plugins}[]*.
```

2022-10-21 14:30 UTC, Tschakki requested changes

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
>  * Consensus algorithm: *xref:{url_protocol_dpos}[Lisk DPoS] & xref:{url_protocol_bft}[Lisk BFT]*
protocol pages will be removed in the new docs

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The xref:{url_lisk_sdk}[Lisk SDK] operates on the {nodejs}[Node.js^] runtime and consists primarily of an application framework called xref:{url_lisk_framework}[Lisk Framework].
Links to Lisk SDK & Lisk Framework don't work

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +It contains a collection of libraries providing blockchain application functionalities (xref:{url_references_elements}[Lisk Elements]), and a powerful Command Line Interface (xref:{url_references_com
Link to Lisk Elements doesn't work

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +| xref:{url_references_framework}[Lisk Framework] | Lisk Framework is an application framework responsible for establishing and maintaining the interactions between the different components of a bloc
Link to Framework doesn't work

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +| xref:{url_references_elements}[Lisk Elements] | Lisk Elements is a collection of libraries, each of which implements a certain type of blockchain application functionality such as cryptography, tra
Link to Elements doesn't work

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Each library is designed to be compatible with xref:{url_protocol}[].
Protocol pages will be removed in new docs

2022-10-21 14:30 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +For example, it allows to xref:{url_guides_setup}[bootstrap] a complete blockchain application with just one command.
Bootstrap link doesn't work

2022-10-21 16:28 UTC, Tschakki requested changes

2022-10-21 16:28 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +== Lisk SDK ecosystem
```suggestion
== Lisk SDK overview
```

Maybe I would just call this section, because most times, when we talk about the Lisk ecosystem in the new docs, we don't mean the Lisk SDK, but the network of sidechains and mainchain.

2022-10-21 16:28 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +It contains a collection of libraries providing blockchain application functionalities (xref:{url_references_elements}[Lisk Elements]), and a powerful Command Line Interface (xref:{url_references_com
```suggestion
As shown in the image above, Lisk Framework is built on top of Lisk Elements and uses a lot of its functions to complement its logic.
Developers can use Lisk Commander to generate a default blockchain application that is based on the Framework components, and add their specific business logic on top.

The Lisk SDK operates on the {nodejs}[Node.js^]. Its three components Lisk Framework, Lisk Elements, and Lisk Commander each provide specific utilities to blockchain developers, as described in the following section.
```

I think there is no need to add a link to the glossary at this point, if the user wants to find out what the Lisk SDK is, they are already on exactly the right page :)

I also removed explanations of the SDK components, to remove duplication, as it is already explained in detail in the next section.

And I added 2 sentences before, which describe what can be seen on the image in more detail.

2022-10-21 16:28 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Each library is designed to be compatible with the Lisk Protocol.
```suggestion
Each library of Lisk Elements is also published as NPM package, and can be installed separately, if needed.
```

this is actually true for all components of Lisk SDK ^^ I adjusted it to add info that each pavkage can be installed separately, which I think is a more interesting information at this point.

2022-10-25 09:34 UTC, Tschakki approved these changes
Thank you!

2022-10-25 10:10 UTC, chris529 approved these changes
LGTM! 👍

2022-10-26 12:05 UTC, merged