Update configuration page in core docs  - Closes #1560
LiskArchive/lisk-legacy-docs pull request #1640
Opened 2022-10-11 14:01 UTC by chris529

Closes #1560

2023-01-04 12:44 UTC, TalhaMaliktz requested changes
A few suggestions :)

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> += Configuration
Please add a navigation link to the page in the following file:
https://github.com/LiskHQ/lisk-docs/blob/1560-update-configuration-page-core/modules/ROOT/nav.adoc

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +// == Enabling plugins
This section is still relevant and correct, so just remove the HTTP API Plugin from the description.

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +NOTE: A complete command reference with all available options for starting Lisk Core can be found in the xref:{url_config_start}[Lisk Core CLI].
```suggestion
//NOTE: A complete command reference with all available options for starting Lisk Core can be found in the xref:{url_config_start}[Lisk Core CLI].
NOTE: A complete command reference with all available options for starting Lisk Core can be found in Lisk Core CLI's reference page.
```

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +// $ lisk-core start --enable-forger-plugin
This section about `Enabling Plugin` is still relevant. The change suggested in the issue is to remove `--enable-forger-plugin --enable-http-api-plugin` and use a different plugin name, for example, you can use  the following snippet:
```suggestion
$ lisk-core start --enable-report-misbehavior-plugin
```

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +NOTE: Remember to xref:{url_pm2_restart}[restart] the node for the new config changes to take effect.
```suggestion
//NOTE: Remember to xref:{url_pm2_restart}[restart] the node for the new config changes to take effect.
NOTE: Remember to restart the node for the new config changes to take effect.
```

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +
```suggestion
//TODO: Update the commented out hyperlinks once the pages are available.
```

2023-01-04 12:44 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +Lisk Core uses the default config for connecting to the Mainnet by default.
```suggestion
Lisk Core uses the default config for connecting to the mainnet by default.
```

2023-01-04 13:44 UTC, chris529 commented on modules/ROOT/pages/management/configuration.adoc
> += Configuration
Good point! Thanks Talha, it is now done 👍

2023-01-04 13:50 UTC, chris529 commented on modules/ROOT/pages/management/configuration.adoc
> +// $ lisk-core start --enable-forger-plugin
OK cool..👍

2023-01-04 14:51 UTC, TalhaMaliktz requested changes
Looking better! 👍🏼

2023-01-04 14:51 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +See also Report Misbehaviour plugin and the `Lisk Core CLI: start` command.
```suggestion
See also the **Report Misbehaviour** plugin and the `Lisk Core CLI: start` command.
```

2023-01-04 14:51 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +A straightforward and easy method is to copy one of the network-specific default configs of Lisk Core and adjust it to suit your requirements.
```suggestion
A straightforward method is to copy one of the network-specific default configs of Lisk Core and adjust it to suit your requirements.
```

2023-01-04 14:51 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +Use the dedicated flags to enable them on application start:
```suggestion
Use the dedicated flags to enable them on the application start:
```

2023-01-04 14:51 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +NOTE: If you intend to connect the node to the mainnet, change `testnet` to `mainnet` in the snippet above.
```suggestion
NOTE: If you intend to connect the node to the mainnet, change the `testnet` to the `mainnet` in the snippet above.
```

2023-01-04 14:51 UTC, TalhaMaliktz commented on modules/ROOT/pages/management/configuration.adoc
> +<1> `NETWORK` may be `mainnet`, `testnet` or `devnet`.
```suggestion
<1> `NETWORK` may be `mainnet`, `testnet`, or `devnet`.
```

2023-01-05 07:33 UTC, TalhaMaliktz approved these changes, later dismissed
LGTM 👍🏼

2023-01-18 15:40 UTC, nagdahimanshu approved these changes
Looks good 👍

2023-01-18 16:03 UTC, merged