Update binary setup page - Closes # 1604
LiskArchive/lisk-legacy-docs pull request #1641
Opened 2022-10-13 10:08 UTC by chris529

Closes #1604

2022-10-21 09:01 UTC, sameersubudhi requested changes

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
>  include::partial$create-a-new-user.adoc[]
Is this a placeholder to share the instructions to create a new user? It currently shows up like a hyperlink: "[partial$create-a-new-user.adoc](https://github.com/LiskHQ/lisk-docs/blob/88569d5eedd1eb53bb1fe57141c354ef86a2ec65/modules/ROOT/pages/setup/partial$create-a-new-user.adoc)" when I view the file.

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +NOTE: When using a MAC with Apple Silicon (M1) please adhere to the relevant following setup instructions below:
```suggestion
NOTE: When using a MAC with Apple Silicon (M1 processor) please adhere to the relevant following setup instructions below:
```

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
>      "fileLogLevel": "error",
```suggestion
"system": {
    "logLevel": "info",
```

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +    "LogLevel": "none"
```suggestion
```

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
>  However, to verify that the node started correctly, update the log levels in the config to `info` or lower.
```suggestion
When the node is started, the logs will be visible in the console.
You can adjust level of logging as per your preference. Supported log levels are: `trace`, `debug`, `info`, `warn`, `error`, `fatal`.
To reduce the number of logs, it is recommended to set the log levels to `warn` or higher.
```

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
>  lisk-core start --network mainnet --console-log=info
```suggestion
lisk-core start --network mainnet --log=info
```

2022-10-21 09:01 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +.Environment Setup requirements
Hi @chris529, This content needs some restructuring. I'll try to share the same with you next week.

2022-10-24 09:22 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
>  include::partial$create-a-new-user.adoc[]
Ah yes, this also shows up like this in my Webstorm app. However, these partials (create-a-new-user. adoc, and the core-post-installation.adoc), can be seen in the updated binary setup page on the staging link below, so perhaps if there are any updates required to these 2 partials, then can you let me know please?

https://liskhq.github.io/lisk-docs/lisk-core/setup/binary.html

2022-10-24 09:58 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +.Environment Setup requirements
Many thanks Sameer! I will await your feedback 👍

2022-12-19 13:49 UTC, nagdahimanshu commented on modules/ROOT/partials/core-post-installation.adoc
> +:url_config_logrotation: lisk-docs::run-blockchain/logging.adoc#logrotation
We also need to update the section `.Example: Enable IPC via config.json` (schema of `rpc` is updated). 
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/types.ts#L88

2023-01-09 15:26 UTC, TalhaMaliktz requested changes
Looking good. A few suggestions :)

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +See the xref:{url_run_logging}[logging] guide for more information about logging.
Please add a TODO for uncommenting the hyperlink once the updated page is available.
```suggestion
// See the xref:{url_run_logging}[logging] guide for more information about logging.
```

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/partials/core-post-installation.adoc
>      "host": "127.0.0.1"
**Line 45**
Please comment it out as the updated page is not available, yet.

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
>  The binary installation offers an easy and automated approach to set up Lisk Core.
```suggestion
The binary installation offers an easy and automated approach to setup Lisk Core.
```

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +You can adjust level of logging as per your preference. Supported log levels are: `trace`, `debug`, `info`, `warn`, `error`, `fatal`.
```suggestion
You can adjust the level of logging as per your preference. Supported log levels are: `trace`, `debug`, `info`, `warn`, `error`, and `fatal`.
```

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +
```suggestion
====

```

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +--
```suggestion

```

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +* MacOS ARM
Is this the updated list of supported platforms?

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
>  Download Lisk Core:
**Line 139**
For uniformity, the `tabs` delimiter should be `=====` instead of `====`

https://github.com/asciidoctor/asciidoctor-tabs#syntax

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
>  Download Lisk Core:
**Line 185 - 206**

Since we also support macOS and it now contains `zshrc` terminal, please add similar steps for the `zshrc` terminal as well. You can see the following URL for guidance.
https://liskhq.github.io/lisk-docs/beta/build-blockchain/create-blockchain-app.html#using-the-application-cli-globally

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/partials/core-post-installation.adoc
> +    // In case if `modes` include `ws`, this port used
```suggestion
    // In case `modes` include `ws` then, the following port is used
```

2023-01-09 15:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +pyenv global 2.7.18
Please separate the installation steps from the commands that should be run to install dependencies.

2023-01-09 15:41 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +* MacOS ARM
Yes, it should be. @nagdahimanshu Could you please confirm this? Many thanks.

2023-01-10 14:45 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
>  Download Lisk Core:
Thanks, I have now added this in 👍

2023-01-11 13:26 UTC, TalhaMaliktz requested changes
Looking better! a few suggestions 😊

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
```suggestion

[source,bash]
----
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Now it is possible to add these binaries to your path in the .zsh_profile
```suggestion
Now it is possible to add these binaries to your path in the `.zsh_profile`
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Apple Silicon (ARM) brew writes binaries to the following: /opt/homebrew/bin
```suggestion
Apple Silicon (ARM) brew writes binaries to the following: `/opt/homebrew/bin`
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Intel brew binaries are stored (as usual), in the following location: /usr/local/Homebrew/bin
```suggestion
Intel brew binaries are stored (as usual), in the following location: `/usr/local/Homebrew/bin`
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +==== Optional
```suggestion

==== Optional
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Add the following lines to your ~/.zshrc
```suggestion
Add the following lines to your `~/.zshrc`
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +   export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
```suggestion
if [[ $(arch) = arm64 ]]; 
then
    echo 'Detected Apple Silicon, ARM Homebrew has precedence'
    export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
else
    echo 'Detected Intel CPU architecture, Intel Homebrew has precedence'
    export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Open a terminal in the Intel mode
```suggestion
Add a new session and set the iTerm to open in the **Intel** mode and then, set a shortcut key for opening iTerm in the aforesaid mode.

After that, open a terminal in Intel mode.
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Install docker for m1 by using google search for “docker install m1” and then run it.
This should be a **TIP**. Please add the appropriate variable for the URL pasted below and add the hyperlink to the guide in the TIP.

Also, please move the updated code to replace content on **Line 127**
```suggestion
TIP: For installing docker on m1 chips, check out the guide about [Installing on Mac](https://docs.docker.com/desktop/install/mac-install/)
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
The formatting of this section should be improved and should match [this section](https://liskhq.github.io/lisk-docs/beta/build-blockchain/plugin/plugin-endpoints.html#testing-helloinfoplugin).
- A numbered list with bold text at the start will improve the text a lot.

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +[source,bash]
```suggestion
Check the mode in which the terminal is running.

[source,bash]
```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
The formatting of this section should be improved and should match [this section](https://liskhq.github.io/lisk-docs/beta/build-blockchain/plugin/plugin-endpoints.html#testing-helloinfoplugin).
- A numbered list with guiding text, followed by the commands.

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +Remember to export the nvm path, (this should be performed automatically by the script).
This part should be converted into a `NOTE`

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
Since we already have a section to install node.js, we can remove it from here.
```suggestion

```

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +arch -x86_64 nvm install 16
Should be the latest version of the nodeJS, which is `18`. Please confirm the version

2023-01-11 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
>  Download Lisk Core:
```suggestion
Download Lisk Core
```

2023-01-11 13:53 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +arch -x86_64 nvm install 16
@nagdahimanshu Can you please confirm the Node.js version is 18?

2023-01-11 13:59 UTC, nagdahimanshu commented on modules/ROOT/pages/setup/binary.adoc
> +arch -x86_64 nvm install 16
We are currently using Nodejs `v16.15.0` version.

2023-01-11 15:01 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +----
Done 👍

2023-01-11 15:01 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +----
Done 👍

2023-01-11 15:01 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +Remember to export the nvm path, (this should be performed automatically by the script).
Done 👍

2023-01-11 15:02 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +arch -x86_64 nvm install 16
Thanks 👍

2023-01-11 16:01 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +* MacOS ARM
I spoke with Himanshu and he has now confirmed this is correct 👍

2023-01-25 12:24 UTC, TalhaMaliktz requested changes

2023-01-25 12:24 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
Both of these points install Homebrew, so IMHO these two points should be converted into two tabs. Where one tab will be for **ARM** and the other one will be for Intel.

2023-01-25 12:24 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
Here we install Homebrew and nvm again, I am not sure why there is repetition so please confirm which set of steps should be part of the guide. It is unclear at the moment which steps should be kept and which OS/platform these steps point towards.

It might also be possible to create two tabs for Mac M1 and Intel chip for installing Home brew
and another set of tabs for M1 and Intel Chips to install nvm.

2023-01-25 12:24 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +To install Python on an M1 Mac.
Do we only need Python for M1 Macs and not for Intel based chips?

2023-01-25 12:24 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +NOTE: When using a MAC with the Apple Silicon (M1 processor), please adhere to the relevant following setup instructions below:
Maybe this Note can be simply a text line?

2023-01-25 14:04 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +NOTE: When using a MAC with the Apple Silicon (M1 processor), please adhere to the relevant following setup instructions below:
OK, I have removed the note 👍

2023-01-25 14:05 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +To install Python on an M1 Mac.
@nagdahimanshu Do you know if this is the case, and we only need Python for M1 Macs?

2023-01-30 10:17 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +To install Python on an M1 Mac.
@sameersubudhi I believe Himanshu is on holiday, so do you know if this is the case, and we only need Python for M1 Macs?

2023-01-30 10:21 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +The binary installation offers an easy and automated approach to setup Lisk Core.
This should be `set up` since it is being used as a verb.
```suggestion
The binary installation offers an easy and automated approach to set up Lisk Core.
```

2023-01-30 10:21 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +To install Python on an M1 Mac.
Yes, this instruction was specific to M1. In case of x86 Intel Macbook we didn't need this.

2023-01-30 11:48 UTC, TalhaMaliktz requested changes
Looking good, just have some final suggestions :)

2023-01-30 11:48 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +When using a MAC with the Apple Silicon (M1 processor), please adhere to the relevant following setup instructions below:
```suggestion
When using a MAC, please adhere to the following setup instructions:
```

2023-01-30 11:48 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +--
```suggestion
--
For Intel, use the following command:
```

2023-01-30 11:48 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
I think this can be moved to a separate point, as suggested below
```suggestion

```

2023-01-30 11:48 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +
```suggestion
. Add Homebrew to your `~/.zshrc`
+
[source,bash]
----
if [[ $(arch) = arm64 ]];
then
    echo 'Detected Apple Silicon, ARM Homebrew has precedence'
    export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
else
    echo 'Detected Intel CPU architecture, Intel Homebrew has precedence'
    export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
----
```

2023-01-30 11:48 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +export PATH=/opt/homebrew/bin:/usr/local/Homebrew/bin:$PATH
Should be removed as we already tell the reader to add homebrew to the `$PATH` variable.
```suggestion

```

2023-01-30 11:48 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +To install Python on an M1 Mac.
```suggestion
=== Install Python (M1 Macs only)
To install Python on an M1 Mac, execute the following commands:
```

2023-01-30 13:04 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +export PATH=/opt/homebrew/bin:/usr/local/Homebrew/bin:$PATH
Good point 👍

2023-01-30 13:42 UTC, TalhaMaliktz approved these changes
Thanks for applying the feedback. The guide LGTM now 🎉 . Although, I have suggested some minor changes, otherwise, all is well.

2023-01-30 13:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
>  The binary installation offers an easy and automated approach to set up Lisk Core.
```suggestion
The binary installation offers an easy and automated approach to setting up Lisk Core.
```

2023-01-30 13:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +=== Environment Setup requirements
```suggestion
=== Environment setup requirements
```

2023-01-30 13:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
Just for the sake of sentence case, I would do the following:

Line 17: Pre-installation

Line 19: Supported platforms

2023-01-30 13:42 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/binary.adoc
> +----
The code block gets rendered, so it should be removed.
```suggestion

```

2023-01-30 13:51 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
Good point...well spotted 👍

2023-01-31 09:53 UTC, sameersubudhi requested changes
Please consider the following points.
Additionally, it'd be nice to have all the sections presented consistently: either as part of the list or as a separate section. Currently, `Install Homebrew` and `Install nvm` are part of the list whereas the remaining are separate sections of their own.

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/partials/core-post-installation.adoc
>      "port": 8080,
```suggestion
"rpc": {
    // Enable RPC communication over 'ipc' or 'ws'
    "modes": ["ipc", "ws"]

    // In case `modes` include `ws` then, the following port is used
    "port": 8080,

```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +* MacOS ARM
```suggestion
* MacOS ARM (Apple Silicon)
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +. Add a new session and set the iTerm to open in the **Intel** mode. Now set a shortcut key for opening the iTerm in the aforementioned mode.
```suggestion
. Add a new session and set the iTerm to open in the **Intel** mode. Now set a shortcut key (quick access) for opening the iTerm in the aforementioned mode.
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +For Redis and Apple Silicon use the following command:
```suggestion
ARM compatible binaries::
+
--
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +For Intel, use the following command:
```suggestion
Intel compatible binaries::
+
--
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
```suggestion
arch -arm64 /bin/bash -c "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +----
This entire section seems irrelevant can be removed. However, the verification step can be added to the second point after we ask the user to open iTerm in Intel mode.
```suggestion
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +Following that, open a terminal in Intel mode.
```suggestion
Following that, open a terminal in Intel mode. Optionally, to verify that the terminal is now running in Intel mode, execute the following.
[source,bash]
----
$ arch
i386
----
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +=== Install Rosetta
The section about installing rosetta must be the first step.

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +softwareupdate --install-rosetta"
```suggestion
softwareupdate --install-rosetta
```

2023-01-31 09:53 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +To install Python on an M1 Mac, execute the following commands:
```suggestion
=== Install Python (Macs running on Apple Silicon)
To install Python on a Mac powered by Apple Silicon, execute the following commands:
```

2023-01-31 14:02 UTC, sameersubudhi requested changes

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +----
The code-block indentation seems off. Kindly re-adjust.
Is it because of missing `+` sign on the preceding line?
```suggestion
+
[source,bash]
----
$ arch
i386
----
```

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +// ----
Homebrew is specific to MacOS. We can remove this entire section here corresponding `Ubuntu`.
```suggestion
```

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +. Install *Homebrew*
The list must continue here. However, it seems like a new list has begun from here (starting with `1`). Could it be because of the misaligned code-block?

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +----
Please move this above, just before the `Install Homebrew` section.

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +//----
Seems repetitive. Can be removed.
```suggestion
```

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +Now it is possible to add these binaries to your path in the `.zsh_profile`
This can be removed from here.
```suggestion
```

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +. Add Homebrew to your `~/.zshrc`
```suggestion
. Add Homebrew to your `~/.zshrc` or `.zsh_profile`
```

2023-01-31 14:02 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +----
This entire section needs some restructuring. Let us discuss offline for easier collaboration.

2023-01-31 15:01 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +----
OK, now done 👍

2023-01-31 15:01 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +. Install *Homebrew*
Yes, I have now fixed it 👍

2023-01-31 15:02 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +=== Install Rosetta
Now done 👍

2023-02-01 14:22 UTC, sameersubudhi approved these changes
Thank you for the prompt changes. LGTM :+1:

2023-02-01 14:22 UTC, sameersubudhi commented on modules/ROOT/pages/setup/binary.adoc
> +Unpack it and add it to the system path, in order to use it in the terminal:
```suggestion
Unpack and add it to the system path, in order to use it in the terminal:
```

2023-02-01 14:31 UTC, merged