Update docker setup page - Closes #1605
LiskArchive/lisk-legacy-docs pull request #1642
Opened 2022-10-14 11:01 UTC by chris529

Closes #1605

2023-01-04 15:23 UTC, nagdahimanshu commented on modules/ROOT/pages/setup/docker.adoc
> +docker run --volume lisk-data:/home/lisk/.lisk -it --rm lisk/core:4.0.0 blockchain:download --network=betanet --output=/home/lisk/.lisk/tmp/
```suggestion
docker run --volume lisk-data:/home/lisk/.lisk -it --rm lisk/core:4.0.0 blockchain download --network=betanet --output=/home/lisk/.lisk/tmp/
```

2023-01-04 15:23 UTC, nagdahimanshu commented on modules/ROOT/pages/setup/docker.adoc
> +docker run --volume lisk-data:/home/lisk/.lisk -it --rm lisk/core:4.0.0 blockchain:import /home/lisk/.lisk/tmp/blockchain.db.tar.gz
```suggestion
docker run --volume lisk-data:/home/lisk/.lisk -it --rm lisk/core:4.0.0 blockchain import /home/lisk/.lisk/tmp/blockchain.db.tar.gz
```

2023-01-06 15:03 UTC, TalhaMaliktz requested changes
Looking good! Just a few suggestion :)

2023-01-06 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/docker.adoc
> +Lisk Core version 4 does not have any external dependencies, and hence does not require using `docker-compose`.
```suggestion
Lisk Core version 4 does not have any external dependencies and hence does not require using `docker-compose`.
```

2023-01-06 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/docker.adoc
Line 52
`Please refer to the {url_docker_install_linux}[Docker installation for ubuntu]`

2023-01-06 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/docker.adoc
>  docker run --volume lisk-data:/home/lisk/.lisk \
Line 144
Please comment this line and add a TODO regarding updating hyperlinks to the page.

2023-01-06 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/docker.adoc
It is unclear where the User should be added, if the user is being added to the OS then similar steps should be mentioned here as they are described in the [Source Setup Guide](https://liskhq.github.io/lisk-docs/lisk-core/setup/source.html#create-a-new-user).

2023-01-06 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/docker.adoc
>  <1> Clone the repository.
Line 90
<2> Navigate into the `lisk-core` root folder.

2023-01-09 14:11 UTC, TalhaMaliktz approved these changes, later dismissed
Thanks, it LGTM 🥳. Just one small change though we need to comment out this line as the page it is referring to has not been updated yet.

2023-01-09 14:11 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/docker.adoc
>  See the xref:{url_run_logging}[] guide for more information about logging.
```suggestion
// See the xref:{url_run_logging}[] guide for more information about logging.
```

2023-01-11 15:50 UTC, nagdahimanshu approved these changes
We are not able to test these changes with `lisk-core` v4.0.0 but changes looks good to me 👍. Hence, approving the PR.

2023-01-13 13:44 UTC, merged