Update core docs overview page - Closes  #1559
LiskArchive/lisk-legacy-docs pull request #1646
Opened 2022-10-19 13:49 UTC by chris529

Closes #1559

2022-10-31 14:42 UTC, sameersubudhi requested changes

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
>  IMPORTANT: To access the latest Lisk Core version, please xref:master@{page-component-name}::{page-relative}[click here].
Currently, there's no hyperlink associated with the text `click here`. Is this expected?

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +The Lisk core can be defined as a blockchain application running on the Lisk Mainnet that implements the Lisk protocol, enabling a user to easily set up a node.
```suggestion
The Lisk Core can be defined as a blockchain application running on the Lisk Mainnet that implements the Lisk protocol, enabling a user to easily set up a node and participate in the network.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +* The possibility to connect to subset of peers in the network (P2P network).
```suggestion
* The possibility to connect to a subset of peers in the Lisk mainchain's P2P network.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +* To synchronize with Lisk blockchain including requesting, forwarding and processing blocks, together with transactions.
```suggestion
* To synchronize with the Lisk blockchain including requesting, forwarding and processing of the blocks, which also contain the transactions.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +* To generate new blocks (only delegate nodes).
The `To maintain the transaction pool.` and `To maintain a set of unconfirmed transactions.` can possibly be merged to avoid redundancy.
```suggestion
* To maintain the transaction pool, which contains a set of unconfirmed transactions.
* To request and forward the unconfirmed transactions.
* To possibly generate new blocks when running a delegate node.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +With the latest version of Lisk Core, there will be new configurable settings and the following modules listed below in the next sub section will also be used.
```suggestion
With the latest version of Lisk Core, there will be new configurable settings and the following modules listed below in the following sub-section will also be used.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +NOTE: To migrate from Lisk Core V3 to V4 please follow the migration process as covered in the xref:{migration}[migration guide].
The `xref` seems to be broken but works from under the Table of Contents.

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +The Lisk SDK v6 has introduced some new configurable settings, including certain constants that need to be specified for each chain, which must also be specified in Lisk Core v4.
I think the description here must be about the new underlying state-store with reference to LIP-0040 and the motivation for/advantages the migration has to offer. It would also be nice to refer the migration LIP (LIP-0063) and the lisk-migrator repo here.
```suggestion
The Lisk SDK v6 has introduced some new configurable settings, including certain constants that need to be specified for each chain, which must also be specified in Lisk Core v4.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +A brief overview of the migration process from Lisk Core v3 to Lisk Core v4 is depicted graphically in the illustration below in figure 1.
```suggestion
A brief overview of the migration process from Lisk Core v3 to Lisk Core v4 is depicted graphically in the illustration below in Figure 1.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +In figure 1 above, the elements in violet are created by Lisk Core v3, inclding the state snapshot.
Would it be more sensible to use `blocks` instead of elements within the text and replace `created` with `generated` to be consistent with the protocol/specifications?

```suggestion
Figure: 1

In Figure 1 above, the blocks in violet are generated by the Lisk Core v3 nodes, including the state snapshot.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Finally, the elements in yellow are created by Lisk Core.
```suggestion
The snapshot block is shown in green, and is generated by the migrator tool.
Finally, the blocks in yellow are generated by the Lisk Core v4 nodes.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +In addition, Lisk nodes are also required to generate/add new blocks to the blockchain.
```suggestion
In addition, Lisk Core nodes are also required to generate/add new blocks to the blockchain.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +* *Delegates* who have registered as a delegate and would like to actively generate.
```suggestion
* *Delegates* who have registered as a delegate and would like to actively generate new blocks.
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +- To have the option to xref:{url_config_forging}[generate] new blocks, (assuming you are an active delegate).
To keep things consistent please consider renaming `url_config_forging` to `url_config_block_generation` or something similar.

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Within the Lisk Core v4, the following modules will be used:
```suggestion
Within Lisk Core v4, the following modules will be used:
```

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +- xref:{dpos}[DPoS] (delegated proof-of-stake), module is responsible for handling delegate registration, votes, and computing the delegate weight.
The `xref` seems to be broken.

With the incoming changes, we're renaming `DPoS` to `PoS`. Please confirm the same with the research/SDK team and update this accordingly.

Also, would it also be beneficial to indicate the corresponding LIPs where the module specifications are specified?

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +- The xref:{bft}[BFT] module is responsible for maintaining the consensus participants, their BFT weights, and all information related to the consensus votes that have been cast as part of the block
The `xref` seems to be broken.

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +- The Interoperability module provides basic functionalities to transmit information between interoperable chains in the Lisk ecosystem using xref:{cross_chain}[cross-chain messages].
The `xref` seems to be broken.

2022-10-31 14:42 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +It allows chains to choose the token used to pay the fee, and to define a minimum fee for transactions to be valid.
```suggestion
- The Fee module is responsible for the handling of the transaction fees.
It allows chains to choose the token used to pay the fee, and to define a minimum fee for the transactions to be valid.
```

2022-11-03 16:00 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- xref:{dpos}[DPoS] (delegated proof-of-stake), module is responsible for handling delegate registration, votes, and computing the delegate weight.
Some of the xrefs do not work at the moment, as the docs is being restructured, however I will get to them 👍 
Regarding the renaming of DPos to POS, it was not mentioned in our terminology sheet below..?
https://docs.google.com/spreadsheets/d/1PEBQdKQj6WDsblT5qwLzRiODlNVce7ORV6HvZQB2RrY/edit?pli=1#gid=0
I will check it 👍

2022-11-03 22:08 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +- xref:{dpos}[DPoS] (delegated proof-of-stake), module is responsible for handling delegate registration, votes, and computing the delegate weight.
There recently was a cross-department agreement on the terminology updates and the same could be found here: https://docs.google.com/spreadsheets/d/1lfOiBytQwj9J_cQ7IS_H08g_nZJLwX9o27k0SZoyMGs

2022-11-04 13:02 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- xref:{dpos}[DPoS] (delegated proof-of-stake), module is responsible for handling delegate registration, votes, and computing the delegate weight.
OK many thanks, Sameer! I have spoken with Sergey from Research, and he has recommended we change it from DPoS to PoS, which I have now done 👍

2022-11-08 09:44 UTC, sameersubudhi requested changes

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +The Lisk Core can be defined as a blockchain application running on the Lisk Mainnet that implements the Lisk protocol, enabling a user to easily set up a node and participate in the network.
```suggestion
The Lisk Core can be defined as a blockchain application running on the Lisk Mainnet that implements/enforces the Lisk protocol, enabling a user to easily set up a node and participate in the network.
```

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +* To maintain the transaction pool, which contains a set of unconfirmed transactions.
```suggestion
* To maintain the transaction pool, which might contain a subset of unconfirmed transactions.
```

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +* To request and forward the unconfirmed transactions.
What was the intention behind this statement?
```suggestion
* To request and forward the unconfirmed transactions.
```

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Furthermore, Lisk Core nodes are able to store all current account balances and transactions.
Since we do not have the concept of accounts anymore, should we reword the statement to refer to `address(es)` instead?

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +With the latest version of Lisk Core, there will be new configurable settings and the following modules described in the <<Modules>> sub-section will also be used.
```suggestion
With the latest version of Lisk Core, there will be new configurable settings and the modules described in the <<Modules>> sub-section will also be used.
```

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +For the Lisk Migrator, Node.js v16 LTS is installed globally.
This statement seems irrelevant in the current context. Let us remove it.
```suggestion
```

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +.Migration process overview
Instead of a sub-section within the same page, should we make it a separate page and just refer to it here with a statement like that says something like, "To learn more about the migration process, check <\<Page title\>>".

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Finally, the elements in yellow are generated by the Lisk Core v4 nodes.
```suggestion
In Figure 1 above, the blocks in pink are generated by the Lisk Core v3 nodes, including the state snapshot.
The snapshot block is shown in green, and is generated by the xref:{url_lisk_migrator}[migrator tool].
Finally, the blocks in yellow are generated by the Lisk Core v4 nodes post the migration.
```

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +
In general, I think we should only provide a brief overview of the upcoming migration and the benefits (improved state store architecture, blockchain events, protocol updates such as dynamic rewards and reward sharing etc) it has to offer, in a small paragraph. All the details can be part of a separate page or can be omitted altogether but we must refer the readers to the above cited LIPs for more information.

2022-11-08 09:44 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +image::state_tree.png[align=center]
Same as above.

2022-11-08 10:27 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +* To request and forward the unconfirmed transactions.
It was just meant to be part of a basic list of one-line statements designed to give a high-level overview of the main functionalities of the Core, in this case, related to the transaction pool.
(See Manu's presentation "Essentials about Lisk" 
https://docs.google.com/presentation/d/1FCaIw10ZvdM3HembUJlC_mJ5td1KQmiElIzBfmQNnQE/edit#slide=id.gfa91be6131_0_198 )

2022-11-08 10:32 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Furthermore, Lisk Core nodes are able to store all current account balances and transactions.
Yes, that is a good point...
How about the following: "Furthermore, Lisk Core nodes are able to store all current addresses, balances, and transactions." ?

2022-11-08 10:36 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +For the Lisk Migrator, Node.js v16 LTS is installed globally.
OK, now done. 👍

2022-11-08 10:41 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +.Migration process overview
Ah, as we discussed yesterday, we do have a separate page that will just describe how to perform the migration, and we have a link to this page above in the note in line 72.
"NOTE: To migrate from Lisk Core v3 to v4 please follow the migration process as covered in the xref:{migration}[migration guide].''
There is a separate GH issue for rebuilding this page for the migration from v3 to v4.

2022-11-08 10:56 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +
OK, well perhaps we could use this content in the actual migration guide page then...? 
I can try to just give a brief overview then of the state store, (although the state store and the architecture are described below). Maybe I can try to trim it down somewhat.. 
I will have to add in blockchain events, and protocol updates...OK, then I will also refer to the LIPS as well.

2022-11-08 16:42 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +image::state_tree.png[align=center]
I have trimmed it down somewhat now (removed the constants, etc.), so it is a bit more high-level.

2022-11-08 16:44 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- The xref:{bft}[BFT] module is responsible for maintaining the consensus participants, their BFT weights, and all information related to the consensus votes that have been cast as part of the block
The BFT module has now been removed as I understand it will not be a separate module, instead, it will become a part of the engine in the upcoming engine/application separation.

2022-11-08 16:46 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- The Interoperability module provides basic functionalities to transmit information between interoperable chains in the Lisk ecosystem using xref:{cross_chain}[cross-chain messages].
It should work now.

2022-11-10 11:17 UTC, sergeyshemyakov requested changes
I think, this is going to be a very helpful page!

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +Hence, it manages the validation of the inputs for the commit and reveal process, as well as the computation of the random seeds from this process.
I would add that the random seeds are used for delegate ordering in a round and for picking standby delegates. I think, this would be more understandable for the reader.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +- The Fee module is responsible for the handling of the transaction fees.
Also with the [recent updates](https://github.com/LiskHQ/lips/pull/182) the Fee module is responsible for handling extra command fees (e.g. delegate registration fee).

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +- The Interoperability module provides basic functionalities to transmit information between interoperable chains in the Lisk ecosystem using xref:{url_cross_chain}[cross-chain messages].
I would add that Interop module also supports / defines the chain lifecycle.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +It is composed of a state store definition used to store tokens in the state.
This sentence doesn't make sense to me. I would just remove it.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +- This module allows any chain in the ecosystem to handle and transfer tokens in a coherent, secure, and controlled manner.
I would add that Token module also handles cross-chain token transfers.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +It computes the block rewards according to the delegate weight for active delegates, and induces specific logic after the application of a block.
I would not mention about the specific logic after the application of a block. Maybe instead of it you could say:
"..., and includes specific logic for rewarding standby delegates."

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +Within the protocol used by Lisk Core v4, each validator needs a generator key in order to generate blocks.
I would stress that each validator needs a separate key called generator key in order to generate blocks.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +Hence, the root of the SPM being the event root, is added as a new property to block headers.
SPM -> SMT

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +The whole state is thus authenticated by the tree Merkle root, the state root.
I would also mention [certificates](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md) here. Something in the direction: "As a part of interoperability solution, validators of each chain certify the current state of the chain. These certificates are signed once the block is finalized and used in cross-chain communication."
You can also check out intro to the linked LIP 0061. Also see `validatorsHash` and `aggregateCommit` [here](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0055.md#new-block-header-properties).

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +Alternatively, with the new state model, the balance of a user is stored in the token module state and is separated from all other properties.
I would change the end of the sentence as it is not completely correct:
".. is separated from the properties of other modules (e.g. public keys).".

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +For example, this could be the transactions defined within the module or the reducers that can be called by other modules.
Reducer is old terminology, I think we say "methods".

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +In addition, the chain also maintains a *global state store*, which can be determined as a collection of key-value pairs defining the state of the blockchain.
I would remove "In addition" and "also", since the state store introduced in previous paragraph is a part of the global state store.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +The state tree is the sparse Merkle tree built on top of the state store.
Would be nice to add a reference to the LIP about SMTs: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0039.md.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +// Need info to add in overview description of changed schemas for better user experience (changing type of most IDs to bytes, etc.).
Thinking about it again, this topic is relatively minor and should be mentioned somewhere else, e.g. complete list of protocol changes.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> -| Network | Port (default) | Network Identifier
Network identifier and Chain ID are different notions. You can have different chains in different networks (e.g. mainchain in Mainnet and Testnet, NFT-marketplace chain in Mainnet and Testnet). So I think we should still mention Net IDs.

Maybe additionally we can say that the chain ID of the mainchain is `0x00000000`.

2022-11-10 11:17 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
>  The native token for the Lisk Mainnet is the *LSK*.
A comment about custom modules section below: I think you can just remove it as now this is not a custom module but a part of the module suite running on the mainchain. And you have already mentioned this above :)

2022-11-10 13:18 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Hence, it manages the validation of the inputs for the commit and reveal process, as well as the computation of the random seeds from this process.
Many thanks, Sergey! Yes, I hope it will be a very helpful page.
OK, I have reworded the above statement slightly, to include your points regarding the random seeds 👍

2022-11-10 13:19 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- The Fee module is responsible for the handling of the transaction fees.
Many thanks...Have now added this in 👍

2022-11-10 13:35 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- The Interoperability module provides basic functionalities to transmit information between interoperable chains in the Lisk ecosystem using xref:{url_cross_chain}[cross-chain messages].
Done 👍

2022-11-10 13:43 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +It is composed of a state store definition used to store tokens in the state.
Done 👍

2022-11-10 13:45 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +- This module allows any chain in the ecosystem to handle and transfer tokens in a coherent, secure, and controlled manner.
Done 👍

2022-11-10 13:52 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +It computes the block rewards according to the delegate weight for active delegates, and induces specific logic after the application of a block.
Good point...done 👍

2022-11-10 14:07 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Within the protocol used by Lisk Core v4, each validator needs a generator key in order to generate blocks.
Thanks...now done 👍

2022-11-10 14:10 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Hence, the root of the SPM being the event root, is added as a new property to block headers.
Done.. 👍

2022-11-10 14:19 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The state tree is the sparse Merkle tree built on top of the state store.
Good point...now done 👍

2022-11-10 15:41 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The whole state is thus authenticated by the tree Merkle root, the state root.
Many thanks. I have now added this in, together with some additional content 👍

2022-11-10 15:46 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Alternatively, with the new state model, the balance of a user is stored in the token module state and is separated from all other properties.
Done 👍

2022-11-10 15:49 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +For example, this could be the transactions defined within the module or the reducers that can be called by other modules.
OK, now updated 👍

2022-11-10 15:51 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +In addition, the chain also maintains a *global state store*, which can be determined as a collection of key-value pairs defining the state of the blockchain.
Good point...now done 👍

2022-11-10 15:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +// Need info to add in overview description of changed schemas for better user experience (changing type of most IDs to bytes, etc.).
OK, I have removed them 👍

2022-11-10 15:58 UTC, chris529 commented on modules/ROOT/pages/index.adoc
>  The native token for the Lisk Mainnet is the *LSK*.
OK, it is now removed 👍

2022-11-11 08:11 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> -| Network | Port (default) | Network Identifier
OK, as discussed the original table has been inserted, together with an additional table showing the chain ID.
@sameersubudhi  Could you please confirm if the Network Identifiers are still the same..?

2022-11-11 10:35 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> -| Network | Port (default) | Network Identifier
We actually do not expose the network identifiers anymore. The network can be identified based on the chainID.
The most significant byte within the chainID can be used to determine the network. And, the remaining 3 bytes can be used to determine the chain. You can refer the following table for network identification and the subsequent table takes the Lisk mainchain as example:

| Network        | Network identifier |
| ------------- | ----------------- |
| mainnet         | 00                          |
| testnet           | 01                          |
| betanet          | 02                         |
| alphanet        | 03                         |
| devnet           | 04                         |

**Example**: The chainID for the Lisk mainchain
| Network        | Lisk mainchain chainID |
| ------------- | ---------------------- |
| mainnet         | 00000000                     |
| testnet           | 01000000                     |
| betanet          | 02000000                     |
| alphanet        | 03000000                     |
| devnet           | 04000000                     |

2022-11-11 12:45 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> -| Network | Port (default) | Network Identifier
Great! Many thanks, Sameer.. I will adapt the changes to reflect this accordingly 👍

2022-11-14 10:03 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
>  The native token for the Lisk Mainnet is the *LSK*.
I still don't understand why we mention anything about tokens and LSK Reclaim command here. I think, this belongs to a different doc page.

2022-11-14 10:14 UTC, sergeyshemyakov requested changes
Just one open comment from my side about the Token and LSK Reclaim sections. Otherwise the PR looks good.

2022-11-14 13:19 UTC, sergeyshemyakov reviewed
Just one comment, otherwise all good from my side.

2022-11-14 13:19 UTC, sergeyshemyakov commented on modules/ROOT/pages/index.adoc
> +The usage of the chain identifiers (previously known as network identifiers), which are currently used for transaction and block header signatures, to arbitrary signatures; are able to prevents repla
The sentence reads weird, I would reformulate somehow.

I would also add that chain identifiers are used in interoperability protocol to distinguish between different blockchain running in the ecosystem (in fact, I would say this is the main task of chain IDs).

2022-11-14 14:43 UTC, sergeyshemyakov submitted a review, later dismissed
I would just change one sentence to make it a bit more clear:
"The usage of the chain identifiers (previously known as network identifiers), which are mainly used within the interoperability protocol in order to distinguish between different blockchains running in the ecosystem."
into 
"The chain identifiers (previously known as network identifiers) are mainly used within the interoperability protocol in order to distinguish between different blockchains running in the ecosystem."
No further comments :)

2022-11-29 08:11 UTC, sameersubudhi requested changes
Looks almost ready. Just a few more things to consider.

2022-11-29 08:11 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +The Lisk SDK v6 has introduced some new configurable settings, including certain constants that need to be specified for each chain, which must also be specified in Lisk Core v4.
I think it might be nice to also attach a hyperlink to `Lisk SDK v6` in this statement.

2022-11-29 08:11 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Within Lisk Core v4, the following modules will be used:
```suggestion
Within Lisk Core v4, the following modules will be registered and used in the specified order:
```
Can we please adhere to the module order as stated [here](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0063.md#modules)?

2022-11-29 08:11 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +// Awaiting feedback from Vikas on the LIP number.
Relevant LIP: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0071.md

Also, it might be add a line stating that the rewards will now be automatically shared with LIP: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0070.md

2022-11-29 08:11 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +The chain identifiers (previously known as network identifiers), are mainly used within the interoperability protocol in order to distinguish between different blockchains running in the ecosystem.
```suggestion
The chain identifiers (synonymous to, the previously known, network identifiers), are mainly used within the interoperability protocol in order to distinguish between different blockchains running in the ecosystem.
```

2022-11-29 08:11 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Therefore, network identifiers (nethash), are not exposed anymore, and the network can be determined based on the `chainID`.
I'm unsure if this statement is factually correct. This could be confirmed with Shu or someone else from the research team.

2022-11-29 08:11 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +| Network | Name | Type | Value
```suggestion
| Network | Name | Type | ChainID Prefix
```

2022-11-30 06:20 UTC, sameersubudhi approved these changes, later dismissed
Thank you for your patience @chris529! The changes look good to me!
However, please consider the following minor points.

2022-11-30 06:20 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Moreover, the PoS module expects that each validator account has such a key specified in the snapshot block.
I think we can remove this statement.
```suggestion
```

2022-11-30 06:20 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Furthermore, As a part of the interoperability solution, validators of each chain certify the current state of the chain.
```suggestion
Furthermore, as a part of the interoperability solution, validators of each chain certify the current state of the chain.
```

2022-11-30 06:20 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +These events are included in a sparse Merkle tree, as leaf nodes.
```suggestion
These events are included in a sparse Merkle tree (SMT), as leaf nodes.
```

2022-11-30 06:20 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +For example, this could be the transactions defined within the module or the methods that can be called by other modules.
```suggestion
The state transitions could be induced by the transactions defined within the module or the methods that can be called by other modules.
```

2022-11-30 06:20 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
>  NOTE: To learn how to set up a node, please see the xref:{url_getting_started}[NPM setup] page.
Should we not refer to a page that lists all sorts of setup mechanisms we support?

2022-11-30 06:20 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Within this network the Lisk users can transfer LSK tokens from one account to another, register accounts as delegates; and vote for other validators.
```suggestion
Within this network the Lisk users can transfer LSK tokens from one account to another, register accounts as delegates, and vote for other validators.
```
---
Additionally, the following line (on L288) could also be updated:
Current statement:
```
To start using the Testnet, please download your free LSK Testnet from the {url_faucet_testnet}[Testnet faucet^].
```

Suggestion:
```
To start using the Testnet, please claim your free LSK tokens from the {url_faucet_testnet}[Testnet faucet^].
```

Also, the data in the APIs table for `Reference` column on L310 seems to be broken. Please check.

2022-11-30 13:28 UTC, sameersubudhi requested changes

2022-11-30 13:28 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +Furthermore, the {url_lip51}[token module^] also handles cross-chain token transfers.
```suggestion
Furthermore, the {url_lip51}[Token module^] also handles cross-chain token transfers.
```

2022-11-30 13:41 UTC, sameersubudhi approved these changes, later dismissed

2022-11-30 14:15 UTC, chris529 commented
Thanks for the message Sameer, as requested I have ignored these last 2 points 👍

2022-11-30 14:20 UTC, sameersubudhi approved these changes

2022-11-30 15:39 UTC, merged