Update `creating a new blockchain application` - Closes 1647
LiskArchive/lisk-legacy-docs pull request #1648
Opened 2022-10-26 15:08 UTC by TalhaMaliktz

Closes #1647

2022-10-27 12:21 UTC, Tschakki requested changes
Please update the terminology on this page with regard to the conclusions of our terminology discussion (once finalized)

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +   create .gitignore
imho the list of files can be removed, it doesn't add much valuable information.

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +As shown in the snippet above, a new folder `src/commands/` will be created, which contains all files for the available CLI commands of the application.
Remove, it can be explained in the file structure explanation below

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
>  NOTE: The application CLI offers various commands to conveniently manage your blockchain application.
This note feels a little out of context here

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +// ----
imho this can be removed

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +	registerPlugins(app); <3>
Before this issue is fixed, we shouldn't use callouts in the code snippets: https://github.com/LiskHQ/lisk-docs/issues/1481

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
>  These files create a ready-to-start blockchain application configured for a local devnet, which uses only the default modules of the Lisk SDK.
I think we didn't introduce to the reader yet, what are the modules which are part of the client by default? We should introduce the term and meaning of `default modules`, probably on page `understand-blockchain/index.adoc`. At this place, we could then link to that section explaining the default modules.

2022-10-27 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +<5> `modules/`: Contains modules of the application.
regarding my comment below, i think it is important to not that it only include the modules defined by the developer, not the default modules of the client.

2022-10-27 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +   create .gitignore
Remove from lines 173-227?

2022-10-28 11:30 UTC, ishantiw reviewed
Overall lgtm, just a few comments

2022-10-28 11:30 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +To get started with the development of a blockchain application most simply and efficiently, it is *recommended* to follow the guide <<bootstrapping-a-new-blockchain-application-with-lisk-commander>>
Maybe?
```suggestion
To get started with the development of a blockchain application simply and efficiently, it is *recommended* to follow the guide <<bootstrapping-a-new-blockchain-application-with-lisk-commander>>.
```

2022-10-28 11:30 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +Create a dedicated folder `hello/`, which will contain the files for the entire application.
not sure if this is a necessary step, a user can simply create an app anywhere without a dedicated folder so maybe we can mention that to accommodate both frontend and blockchain application we can create a dedicated folder...

2022-10-28 11:30 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +TIP: Lisk provides a range of default modules out of the box. These modules are created automatically whenever a blockchain application is bootstrapped via Lisk Commander. For more information, see t
You can mention that they can simply update the line
`const { app } = Application.defaultApplication(config);` in app.ts to load application without default modules
```
	const app = new Application(config);

```

2022-10-31 15:37 UTC, Tschakki requested changes
`hello_app` should be updated to `hello_client`

2022-10-31 15:37 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
>  === Starting the application
```suggestion
=== File- & folder structure
```

2022-10-31 15:37 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +
```suggestion

=== Starting the application
```

2022-10-31 15:37 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +TIP: Lisk provides a range of default modules out of the box. These modules are created automatically whenever a blockchain application is bootstrapped via Lisk Commander. For more information, see t
```suggestion
[#default-modules]
.Default modules
TIP: Lisk provides a range of *default modules* out of the box.
These modules are created automatically, whenever a blockchain application is bootstrapped via Lisk Commander.
The default modules provide basic blockchain functionality that a most basic sidechain client requires to run.
For more information, see the xref:{url_lisk_default_modules}[].
```

2022-10-31 15:37 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +replacing
```suggestion
In most cases, the <<default-modules,default modules>> don't need to be changed, as they provde basic funationality that most sidechain clients need.
But in case you want to replace the default modules with other modules, you can also run the application without the default modules by replacing 
```

2022-10-31 15:37 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +----
```suggestion
----

Please be aware that if you create the app with `const app = new Application(config);`, then you need to register all modules manually in the `modules.ts` file.

This way it is also possible to include some, but not all of the default modules in the client application.
```

2022-11-01 10:14 UTC, Tschakki approved these changes
LGTM 👍 

Terminology will be updated later, after final decision.

2022-11-03 16:25 UTC, ishantiw approved these changes
LGTM, just one minor comment but I'm approving from my end

2022-11-03 16:25 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +Please be aware that if you create the app with `const app = new Application(config);`, then you need to register all modules manually in the `modules.ts` file.
```suggestion
Please be aware that if you create the app with `const app = new Application(config);`, then you need to register all modules manually in the `app.ts` file.
```

2022-11-03 16:33 UTC, merged