Create module guide
LiskArchive/lisk-legacy-docs pull request #1649
Opened 2022-11-02 15:24 UTC by Tschakki

Closes #1519

2022-11-15 16:29 UTC, shuse2 requested changes

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +First, define the corresponding interface for the event in `tpes.ts`.
```suggestion
First, define the corresponding interface for the event in `types.ts`.
```

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +};
instead of splitting to types and schema, it can be just implemented in `new_hello.ts`, and in general that's better

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +* `log()`: A method to emit the event and add it to the event queue of the node.
`log` is not necessity, but it's more like utility during the development.
Also, `schema` is optional

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +        newHelloEvent.log(context.getMethodContext(), {
no need to path method context here. it can be just passing the context directly

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +////
we can remove this?

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +                )
for the fail case, you can just throw error for simplicity

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +        context.logger.info(validation,"validation");
validation log should exist, so maybe not needed here

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> + % ./bin/run transaction:create hello createHello 10000000 --params='{"message":"Hello Lisk SDK v6!"}' --json --key-derivation-path="m/44'/134'/0'" --pretty
`--key-derivation-path="m/44'/134'/0'"` this is default derivation path?

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +export const configSchema = {
config is not used for encoding/decoding, so `dataType` and `fieldNumber` shouldn't be used, but instead it should use `type`

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +        validator.validate(configSchema, config);
```suggestion
        validator.validate<ModuleConfig>(configSchema, config);
```

2022-11-15 16:29 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +		methodContext,
here it's missing type?

2022-11-16 09:24 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +////
yes, we can. 

Btw `////` indicates, that this content is currently commented out :)

2022-11-16 09:27 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +        validator.validate(configSchema, config);
Where does the `ModuleConfig` come from?

2022-11-16 09:32 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +* `log()`: A method to emit the event and add it to the event queue of the node.
but if `log()` and `schema` are not implemented, then the event is doing nothing, basically? Shouldn't it implement something?

2022-11-16 09:35 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +        context.logger.info(validation,"validation");
no, i don't think it exists currently, that is why i added it here

2022-11-16 09:36 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> + % ./bin/run transaction:create hello createHello 10000000 --params='{"message":"Hello Lisk SDK v6!"}' --json --key-derivation-path="m/44'/134'/0'" --pretty
yes, i think so

2022-11-16 13:05 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +        newHelloEvent.log(context.getMethodContext(), {
hmm, if I only pass the context, it complains the following: `Argument of type 'TransactionExecuteContext' is not assignable to parameter of type 'EventQueuer'.   Types of property 'eventQueue' are incompatible.`

2022-11-16 13:09 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +                )
Can you give an example? Not sure I understand

2022-11-16 13:18 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +export const configSchema = {
I updated `dataType` to `type` - anything lse that needs to be adjusted?

2022-11-16 14:25 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +		methodContext,
yes, I now set it to `ImmutableMethodContext`, is it correct like this?

2022-11-16 16:28 UTC, TalhaMaliktz requested changes
Looks nice already! 😊

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +As defined on page xref:{url_guides_index_helloapp}[Building blockchain applications with the Lisk SDK], the Hello module shall provide the following functionalities:
`xref:{url_guides_index_helloapp}` doesn't work. Please check and correct.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +:url_references_commander: {docs_sdk}references/lisk-commander
The URL is incorrect, please correct it.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +│    │    │      ├── commands/ <2>
The `commands` folder isn't generated automatically with module bootstrap. Please refer to the bootstrapped elements here as per the `generate:module` command. For reference:

```
iamtalha@Muhammads-MacBook-Pro hello_client % lisk generate:module helloTest
Creating module skeleton with module name "helloTest"
Using template "lisk-ts"
Generating module skeleton.
Registering module...
identical .liskrc.json
   create src/app/modules/hello_test/endpoint.ts
   create src/app/modules/hello_test/method.ts
   create src/app/modules/hello_test/module.ts
   create src/app/modules/hello_test/events/.gitkeep
   create src/app/modules/hello_test/stores/.gitkeep
   create test/unit/modules/hello_test/module.spec.ts
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +<2> The `commands/` folder contains the xref:{url_intro_modules_commands}[commands] of the module.
Introduce this in your **' How to create a command'** guide where a `commands` directory and its related files are being created.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +This already includes module, plugin and UI, and can be directly tried out by anyone.
```suggestion
This already includes module, plugin, and UI, and can be directly tried out by anyone.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +As defined on page xref:{url_guides_index_helloapp}[Building blockchain applications with the Lisk SDK], the Hello module shall provide the following functionalities:
```suggestion
As defined on the xref:{url_guides_index_helloapp}[Building blockchain applications with the Lisk SDK] page, the Hello module shall provide the following functionalities:
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +The event includes information about the sender address and the Hello message.
```suggestion
The event includes information about the sender's address and the Hello message.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +The hello message should be rejected, if it includes one of the words in the blacklist.
```suggestion
The hello message should be rejected if, it includes one of the words in the blacklist.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +Expects account `address` as parameter
```suggestion
Expects the account's `address` as a parameter.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +For more information how to create a command, check out the guide xref:{url_build_command}[].
```suggestion
For more information on how to create a command, check out the guide xref:{url_build_command}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +For more information how to create endpoints for a module, check out the guide xref:{url_build_endpoints_methods}[].
```suggestion
For more information on how to create endpoints for a module, check out the guide: xref:{url_build_endpoints_methods}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +For more information how to create a blockchain event, check out the guide xref:{url_build_blockchain_event}[].
```suggestion
For more information on how to create a blockchain event, check out the guide: xref:{url_build_blockchain_event}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +For more information how to create module methods, check out the guide xref:{url_build_endpoints_methods}[].
```suggestion
For more information on how to create module methods, check out the guide: xref:{url_build_endpoints_methods}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +For more information how to create a module store, check out the guide xref:{url_build_stores}[].
```suggestion
For more information on how to create a module store, check out the guide: xref:{url_build_stores}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +Now, open the configuration file and add the config option for the Hello module like this:
Are we describing anywhere how to create a `custom_config`? If not, please add a step to first create a custom config and elaborate a bit on what it means in a line or two before this "Define a custom module configuration"

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +If no value is set in the custom config, it will use the value of the default config.
Since no comparison was done on what custom and default config is, this becomes confusing. Are we talking about:

```
export const defaultConfig = {
	blacklist: ["illegalWord1"],
	maxMessageLength: 256,
	minMessageLength: 3
}; 
```

or `config.json` file?

Also, if we are talking about `custom_config.json` and `config.json` then we should use these names for more clarity.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +This allows to overwrite the default configurations of a module conveniently by updating the `config.json` file of the Hello client.
```suggestion
This allows you to overwrite the default configurations of a module conveniently by updating the `config.json` file of the Hello client.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +This configuration values will be used, if no custom values are set by the developer in `config.json`.
```suggestion
These configuration values will be used if no custom values are set by the developer in `config.json`.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +Please check out the guide xref:{url_build_command}[], especially the section xref:{url_build_command_try}[-> Try the new command out] for further details how to test and verify the config values.
```suggestion
Please check out the guide xref:{url_build_command}[], especially the section xref:{url_build_command_try}[-> Try the new command out] for further details on how to test and verify the config values.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +////
If the commented content is irrelevant, please remove it.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +Generally, there are two different types of stores that can be created: xref:{url_understand_modules_on_stores}[on-chain-] & xref:{url_understand_modules_off_stores}[off-chain stores].
```suggestion
Generally, there are two different types of stores that can be created: xref:{url_understand_modules_on_stores}[on-chain] & xref:{url_understand_modules_off_stores}[off-chain stores].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +	message: String;
Shouldn't this be `string` instead of `String`?

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +Here we only want to save a single number, which is the total number of sent Hello messages.
```suggestion
Here we only want to save an integer, which is the total number of sent Hello messages.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +For security reasons, every module maintains its' own stores.
```suggestion
For security reasons, every module maintains its own stores.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +Only the module B itself can get and set data in its' own stores.
```suggestion
Only the module B itself can get and set data in its own stores.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +. Counter data: The global Hello counter, counting the total number of sent Hello messages.
```suggestion
. Counter data: The global Hello counter, counts the total number of sent Hello messages.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +The answer in this case is pretty simple: For every account, we want to store their corresponding Hello message, if they send one to the network.
```suggestion
The answer, in this case, is pretty simple: For every account, we want to store their corresponding Hello message, if they send one to the network.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +So we choose to use the account address as key and the Hello message as value.
```suggestion
So we choose to use the "sender's account address" as the key and the "Hello message" as value.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +Analog to the message store, create a second store for the counter.
```suggestion
Just like the message store, create a second store for the counter.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +:url_github_hello_command: https://github.com/LiskHQ/lisk-sdk-examples/tree/188-hello-v6/tutorials/hello/hello_client/src/app/modules/hello/commands/create-hello.ts
These URLs should point to the `development` branch, as soon the branches will be merged and once that happens the URLs will work. For now, they don't.

BTW the file name is `create_hello_command.ts`

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. *Module name*: The name of the module the asset belongs to.
```suggestion
. *Module name*: The name of the module the command belongs to.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +:url_sdk_references_commander: {docs_sdk}references/lisk-commander
```suggestion
:url_sdk_references_commander: {docs_sdk}references/lisk-commander/index.adoc
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +│    │    │      ├── commands/
Here you should add the details which you added to **index.adoc:LN104**

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +To do this, create a new method `init()` in the command, that can be called int he `init()` function of the module, after the module received the values from the config:
```suggestion
To do this, create a new method `init()` in the command, that can be called in the `init()` function of the module, after the module received the values from the config:
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Now, the `blacklist`, `minMessageLength` and `maxMessageLength`, which are defined in the config.json file, are available in the command, and we can move on to implement the <<command-verification>>.
```suggestion
Now, the `blacklist`, `minMessageLength`, and `maxMessageLength`, which are defined in the **config.json** file, are available in the command, and we can move on to implement the <<command-verification>>.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +The command is always verified, before it is executed by the node like defined in the <<command-execution>>.
```suggestion
The command is always verified before it is executed by the node as defined in the <<command-execution>>.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +There `CreateHello` command expects only one single parameter in the transaction, and this is the Hello message.
```suggestion
In the `verify()` method, the `CreateHello` command expects only one single parameter in the transaction, and that is the Hello message.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. the message should not contain any of the words defined in the blacklist of module config.
```suggestion
. The message should not be shorter than the minimum message length defined in the command schema.
. The message should not be longer than the maximum message length defined in the command schema.
. The message should not contain any of the words defined in the blacklist of module config.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Point 3. however, the blacklisted words, cannot be checked with the schema.
```suggestion
For point 3. however, the blacklisted words, cannot be checked with the schema.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. Get account data of the sender of the CreateHello transaction.
```suggestion
. Get the account data of the sender of the "Create Hello" transaction.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. Save the Hello message to the message store, using the senderAddress as key, and the message as value
```suggestion
. Save the Hello message to the message store, using the `senderAddress` as the key, and the `message` as the value.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Use the password contained in the file `config/default/passphrase.json` when prompted for it.
```suggestion
Use the passphrase contained in the file `config/default/passphrase.json` when prompted for it.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. Send the transaction:
Please create referenceable IDs for "Create the Transaction" & "Send the Transaction" so that, they can be referenced elsewhere, if required.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +But in this case, we want the transaction to be invalid, to verify it is using the values defined in the custom module config, that we created in guide xref:{url_guides_module_config}[].
This sounds confusing, kindly rephrase this.

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. the Hello message contains none of the blacklisted words
```suggestion
. Minimum Hello message length: 5.
. Maximum Hello message length: 300.
. The Hello message contains none of the blacklisted words.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> ++
```suggestion

```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +For our example, we choose `createHello` as command name, and `hello`  as module name:
```suggestion
For our example, we choose `createHello` as the command name, and `hello`  as the module name:
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +The command parameters are data that is provided by the transaction, that is required by the command to execute its' business logic.
```suggestion
The command parameters are data that is provided by the transaction, that is required by the command to execute its business logic.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +The parameters interface and schema define the data type, order of the command.
```suggestion
The parameters interface and schema define the data type, and order of the command.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +The blacklist can be retrieved from the module config, which was defined in guide xref:{url_guides_module_config}[].
```suggestion
The blacklist can be retrieved from the module config, which was defined in the guide on xref:{url_guides_module_config}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +We don't need to validate point 1. and 2. in the `verify()` method, because it is already validated by the schema.
```suggestion
We don't need to validate points 1. and 2. in the `verify()` method, because they are already validated by the schema.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +. Get message and counter stores, that we created in the example in xref:{url_guides_module_stores}[].
```suggestion
. Get the message and counter stores, that we created in the example in xref:{url_guides_module_stores}[].
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Use the transaction in binary format to post the transaction to the node like shown below.
```suggestion
Use the transaction in binary format to post the transaction to the node as shown below.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Right now, there is only a way to post the hello message.
```suggestion
Right now, there is only one way to post a hello message.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Also the counter is created and incremented, but there is no way for an external service to request the data.
```suggestion
Also, although the counter is created and incremented, however, there is no way for an external service to request the data.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> + ./bin/run start --config=config/custom_config.json
Since this command is not the default one, Please mention some info about how it is different from `./bin/run start`

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +For this, a module needs to provide the dedicated <<endpoints>>.
```suggestion
For this, a module needs to provide dedicated <<endpoints>>.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +Initially, the modules doesn't include any endpoints:
```suggestion
Initially, the modules don't include any endpoints:
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +=== Get Hello message by address
```suggestion
=== Get a Hello message by address
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +Initially, the modules doesn't include any methods:
```suggestion
Initially, the modules don't include any methods:
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +=== Get Hello message by address
```suggestion
=== Get a Hello message by address
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +. Send at least one "Create Hello" transaction to the node, like explained in xref:{url_build_module_try}[How to create a command -> Try the new command out]
```suggestion
. Send at least one "Create Hello" transaction to the node, as explained in xref:{url_build_module_try}[How to create a command -> Try the new command out]
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +Create a new file inside the `events/` folder of the module, and import the above defined interface and schema.
```suggestion
Create a new file called `new_hello.ts` inside the `events/` folder of the module, and import the above-defined interface and schema.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +For an example how to listen to the event, check out the guide xref:{url_build_plugin}[]
```suggestion
For an example of how to listen to the event, check out the guide xref:{url_build_plugin}[]
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +Now that the event is registered with the module, you can call the `log()` method of the event any time inside the module.
```suggestion
Now that the event is registered with the module, you can call the `log()` method of the event at any time inside the module.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +Now, the module will create a new event everytime a "Create Hello" command is executed, and the event will include the sender address and the sent Hello message.
```suggestion
Now, the module will create a new event every time a "Create Hello" command is executed, and the event will include the sender address and the sent Hello message.
```

2022-11-16 16:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +.schema.ts
I think it is important to use full file paths Like on [Line 133] or at least the relevant module directory. `hello/schema.ts`

**P.S. This applies to all guides**

2022-11-17 08:18 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +        "address": "lskuz5p98kz3mqzxnu68qdrjxtvdvr2o7pprtj4yv"
Where does this address come from, I think we need to add detail about where can a reader find the sender's Address in their project. Without this step, they will not know how to request using an endpoint.

2022-11-17 17:03 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +There `CreateHello` command expects only one single parameter in the transaction, and this is the Hello message.
```suggestion
The `CreateHello` command expects only one single parameter inside of the transaction, and this is the Hello message.
```

2022-11-17 17:08 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +        validator.validate(configSchema, config);
```suggestion
        validator.validate<ModuleConfigJSON>(configSchema, config);
```

2022-11-17 17:13 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +The hello message should be rejected, if it includes one of the words in the blacklist.
```suggestion
The hello message should be rejected if it includes one of the words in the blacklist.
```

2022-11-17 17:17 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/stores.adoc
> +	message: String;
```suggestion
	message: string;
```

2022-11-18 09:13 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +Now, open the configuration file and add the config option for the Hello module like this:
added link to the general config guide 👍

2022-11-18 09:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +<6> `module.ts`: Registers modules with the sidechain client.
`module.ts` is the class for the module and `modules.ts` is where modules are registered.

2022-11-21 22:58 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +* `log()`: A method to emit the event and add it to the event queue of the node.
the BaseEvent has function `add` and directly using `add` is an option as well.
no schema just means there is no custom data, but you can still signal something happened by logging an event

2022-11-21 22:59 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +////
yea I notice on the view (at first i was wondering why it doesn't show up 😸

2022-11-21 23:00 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +                )
instead of return
```
status: VerifyStatus.FAIL,
                error: new Error(
                    `Illegal word in hello message: ${  found.toString()}`
                )
```
you can do
```
throw new Error(
                    `Illegal word in hello message: ${  found.toString()}`
                )
```
and framework will handle internally in the same way

2022-11-21 23:01 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +        context.logger.info(validation,"validation");
even in the debug mode?

2022-11-21 23:01 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> + % ./bin/run transaction:create hello createHello 10000000 --params='{"message":"Hello Lisk SDK v6!"}' --json --key-derivation-path="m/44'/134'/0'" --pretty
in case of `default` derivation path, i think you don't need to specify

2022-11-21 23:03 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +export const configSchema = {
i dont see the update, but below is equivalent 
```
 maxMessageLength: {
            type: 'integer',
            format: 'uint32',
        },
        minMessageLength: {
            type: 'integer',
            format: 'uint32',
        },
        blacklist: {
            type: 'array',
            items: {
                type: 'string',
                minLength: 1,
                maxLength: 40,
            },
        },
```

2022-11-21 23:07 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +        newHelloEvent.log(context.getMethodContext(), {
ah that is a bug, will create an issue

2022-11-21 23:09 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +		methodContext,
👍

2022-11-22 11:48 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +export const configSchema = {
I updated the client, but not the PR, yet, but will do soon, thanks 👍

2022-11-22 13:25 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +* `log()`: A method to emit the event and add it to the event queue of the node.
thanks, I updated the code and descriptions accordingly

2022-11-22 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +        newHelloEvent.log(context.getMethodContext(), {
Ok, in that case I already updated it to `context` in the example code and guide

2022-11-22 13:43 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> + % ./bin/run transaction:create hello createHello 10000000 --params='{"message":"Hello Lisk SDK v6!"}' --json --key-derivation-path="m/44'/134'/0'" --pretty
updated the command and added a TIP explaining default key derivaiton path

2022-11-24 14:35 UTC, TalhaMaliktz requested changes
Looks Good 😊. It would be nice to re-check the pasted snippets with the final code repo.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +			dataType: 'lisk32',
The schema doesn't match the code, please update accordingly.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +To create the event class, import the `BaseEvent` and `EventQueuer` from the `lisk-sdk`.
The code doesn't use the `EventQueuer` class so we can remove this.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +As defined on the xref:{url_build}[Building blockchain applications with the Lisk SDK] page, the Hello module shall provide the following functionalities:
Shouldn't this point to the `build-blockchain/index.adoc` instead of ` build-blockchain/module/index.adoc`?

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +:url_references_commander: {docs_sdk}references/lisk-commander/index.adoc
```suggestion
:url_references_commander: {docs_sdk}references/lisk-commander/cli.adoc#generate
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +<5> `module.ts`: the class of the module.
```suggestion
<5> `module.ts`: Contains the class of the `hello` module.
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +This will overwrite every value of the default config with the value of the user defined config.
```suggestion
This will overwrite every value of the default config with the value of the user-defined config.
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/configuration.adoc
> +Please check out the guide xref:{url_build_command}[], especially the section xref:{url_build_command_try}[-> Try the new command out] for further details on how to test and verify the config values.
```suggestion
Please check out the guide on xref:{url_build_command}[], especially the section xref:{url_build_command_try}[-> Try the new command out] for further details on how to test and verify the config values.
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +:url_github_hello_command: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/modules/hello/commands/create-hello-command.ts
```suggestion
:url_github_hello_command: https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello/hello_client/src/app/modules/hello/commands/create_hello_command.ts
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +:url_sdk_references_commander: {docs_sdk}references/lisk-commander/index.adoc
```suggestion
:url_sdk_references_commander: {docs_sdk}references/lisk-commander/cli.adoc#generate
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +		console.log("this.schema: ", this.schema);
Please remove as it is already removed in code.
```suggestion

```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +}
The snippet seems to be different in the code repo. Please check as I think you mean to pass config here, just like you have done in your code.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +        const helloBuffer = Buffer.from('hello','utf8');
Doesn't exist in code repo
```suggestion
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +            helloCounter = await counterSubstore.get(context, helloBuffer);
Please re-paste the code for the `execute()` to match the code repo, the `helloBuffer` doesn't exist anymore.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Then, <<send-transaction,send the transaction>> to the node, and wait for the response.
Does it go to the `send-transaction` for you? For me, it doesn't.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +For example, create the following Hello trasnaction, which is violating the third requirement by including a blacklisted word:
```suggestion
For example, create the following Hello transaction, which is violating the third requirement by including a blacklisted word:
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +		);
`Buffer` creation is different in code.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +import { CounterStore, CounterStoreData } from './stores/counter';
Please re-paste this snippet.
```suggestion
import { counterKey, CounterStore, CounterStoreData } from './stores/counter';
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +* `CounterStore` & `CounterStoreData`: The counter store which was created in the xref:{url_build_module_stores}[] guide.
Update according to the changes in the snippet below

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +----
The snippet needs an update. Please re-paste the snippet and also re-check the info related to the code snippet.

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +If desired, the time that events are kept in the database can be increased in the node config under `system.keepEventsForHeights`.
```suggestion
If desired, the number of blocks for which events are kept in the database can be increased in the node config under `system.keepEventsForHeights`.
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/blockchain-event.adoc
> +Even without schema, it is still possible signal something happened by logging an event.
```suggestion
Even without schema, it is still possible to signal that something happened, by logging an event.
```

2022-11-24 14:35 UTC, TalhaMaliktz commented on build/preview-site.yml
> +    branches: [docs-sdk, docs-sdk-v5, docs-core-v3, docs-core, docs-service-v0.6, docs-manual]
Is this change intentional?

2022-11-24 14:54 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +<5> `module.ts`: the class of the module.
```suggestion
<5> `module.ts`: Contains the class of the Hello module.
```

2022-11-24 14:57 UTC, Tschakki commented on build/preview-site.yml
> +    branches: [docs-sdk, docs-sdk-v5, docs-core-v3, docs-core, docs-service-v0.6, docs-manual]
yes 👍 

It includes all the versions that will be part of the docs on the beta release, because I think that at least during beta phase, we still want to document the previous version.

2022-11-24 15:42 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +As defined on the xref:{url_build}[Building blockchain applications with the Lisk SDK] page, the Hello module shall provide the following functionalities:
yes you are right, good catch 👍

2022-11-24 16:02 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +Then, <<send-transaction,send the transaction>> to the node, and wait for the response.
yes you are right, somehow the ID gets not created. I moved it a little, and it seems to work now

2022-11-24 16:13 UTC, shuse2 approved these changes
There are some indentation problem in the code block, but otherwise LGTM 🚀

2022-11-24 16:13 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +	VerifyStatus,
Indentation problem

2022-11-24 16:13 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +        });
indentation problem

2022-11-24 16:13 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +	}
indentation problem

2022-11-24 16:13 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/module/endpoints-methods.adoc
> +        // 1. Get message store
Indentation problem

2022-11-25 07:14 UTC, TalhaMaliktz reviewed
Just one correction! otherwise LGTM 🥳

2022-11-25 07:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +    public async init(blacklist: string[]): Promise<void> {
```suggestion
    public async init(args: ModuleInitArgs): Promise<void> {
```

2022-11-25 07:14 UTC, TalhaMaliktz approved these changes

2022-11-25 09:27 UTC, merged