Update "Build blockchain" overview page
LiskArchive/lisk-legacy-docs pull request #1651
Opened 2022-11-08 16:00 UTC by Tschakki

Closes #1518

2022-11-09 11:56 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +image::build-blockchain/hello-client.png["Hello client overview", 400]
imho I would reword the one line in the Stores box to read as follows:

"Is of a maximum length of 300 characters".

2022-11-09 11:57 UTC, chris529 approved these changes
LGTM! 👍

2022-11-10 12:22 UTC, TalhaMaliktz requested changes
Looks good! A few suggestions. . . .  :)

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> += Building a sidechain with the Lisk SDK
I think we should say 'sidechain client' instead of a sidechain.
```suggestion
= Building a sidechain client
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +The "Build Blockchain" category contains all the guides related to the development of a sidechain client.
```suggestion
The "Build Blockchain" category contains all the guides related to the development of a sidechain client with the Lisk SDK.
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +== The Hello World sidechain
```suggestion
== The "Hello World" client
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +NOTE: Although the example is kept very simple by intention, the Hello World client implements and uses all the most important components of a module, and is therefore a good example to understand th
```suggestion
NOTE: Although the example is kept very simple by intention, the Hello World client implements and uses all the most important components of a client such as modules, plugins, configurations, genesis blocks, etc., and is therefore a good example to understand the basics of a client's development.
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +The "Hello World" sidechain allows each account to save a greeting message on-chain.
```suggestion
The "Hello World" sidechain client allows each account to save a greeting message on-chain.
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
>  The following guides each focus on developing a specific part of the Hello application.
```suggestion
The following guides each focus on developing a specific part of the Hello client.
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +In the example, the plugin will return the latest Hello message which was sent to the network, and its' sender address.
```suggestion
In the example, the plugin will return the addresses of all the senders who sent a Hello Message to the network.
```

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +image::build-blockchain/hello-client.png["Hello client overview", 400]
- Please update the description of the plugin as per line 37.
- Also, the plugin will have DB, Endpoint, Schemas, and Configurations, and since this is the overview page of the sidechain client, I think these elements should go into the diagram as well.

2022-11-10 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
```suggestion
It also stores the addresses of senders of the greeting message, in an off-chain database.
```

2022-11-11 10:39 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> += Building a sidechain with the Lisk SDK
I disagree, I think "sidechain" is more fitting in the context, because this cateogry will also include guides how to register the app as a sidechain. So imho it should be either "sidechain" or "sidechain application" in the title.

2022-11-11 10:44 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +NOTE: Although the example is kept very simple by intention, the Hello World client implements and uses all the most important components of a module, and is therefore a good example to understand th
```suggestion
NOTE: Although the example is kept very simple by intention, the Hello World client implements all the most important components, and is therefore a good example to understand the basics of the development of a sidechain client.
```

2022-11-11 10:45 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +In the example, the plugin will return the latest Hello message which was sent to the network, and its' sender address.
Will it only return the adresses or the Hello messages as well?

2022-11-11 10:48 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +image::build-blockchain/hello-client.png["Hello client overview", 400]
@TalhaMaliktz could you update the plugin part of the diagram on Lucidchart? I can then update the diagram in the PR, or it can be updated again in the PR that updates the "How to create a plugin" guide

2022-11-11 12:24 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> += Building a sidechain with the Lisk SDK
Yeah in that case, sidechain application sounds good to me.

2022-11-11 12:26 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +In the example, the plugin will return the latest Hello message which was sent to the network, and its' sender address.
We can return both as long they are returned in the event, haven't decoded the event's data yet.

2022-11-11 12:26 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +image::build-blockchain/hello-client.png["Hello client overview", 400]
Sure, will update in during my "How to create a plugin" PR

2022-11-14 09:52 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +In the example, the plugin will return the latest Hello message which was sent to the network, and its' sender address.
```suggestion
In the example, the plugin will save all sent Hello messages and their corresponding sender address in an off-chain store, and provide endpoints to retrieve the data from the store.
```

2022-11-15 07:53 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2022-11-25 09:28 UTC, merged