Add how to register a sidechain page in lisk docs
LiskArchive/lisk-legacy-docs pull request #1653
Opened 2022-11-09 16:40 UTC by chris529

Closes #1524

2022-12-05 10:41 UTC, sergeyshemyakov requested changes

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Moreover, the liveness requirement to maintain the channel is not enforced, this means that there is no specific time requirement for a sidechain to be activated on the mainchain, it can stay in the
I think it would be good to explain the liveness condition here, at least in a couple of words. I would say that the liveness condition means that a sidechain sends any message to the mainchain at least once every 30 days.

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The following parameters below are included in the registration command:
I think you refer to the outdated version of the command. The current arguments could be found here: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0043.md#sidechain-registration-command.
The differences are: command sender explicitly passes `chainID`, `certificateThreshold` is a separate parameter.

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The network ID is calculated from the address of the command sender and the genesis block ID, also given in the command parameters.
This is slightly outdated, now the sidechain has the liberty of choosing the chain ID itself. Also the term "network ID" is not used anymore, it is replaced by "chain ID".

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +For PoS chains, the value of the elements of this array is usually 1 as every active validator has the same finality weight to sign the next certificate.
Now this parameter is called `bftWeight`. For PoS chains it should correspond to the stake of the validator, not be constant 1, this is also outdated with our latest changes in DPoS (PoS) module.

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +By using 4 bytes instead of 32 bytes this provides the distinct advantage whereby users are able to easily verify that they are signing a transaction for the correct blockchain.
I don't quite understand this or the following sentence. I think, we never thought about 32 byte values for chain ID (maybe you confused with 32 bits = 4 bytes?).
I would just mention that by checking chain ID users are able to easily verify that they are signing a transaction for the correct blockchain.

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +=== Chain ID
As I mentioned before, the chain ID is now not deterministically generated but rather chosen by the sidechain itself when submitting a sidechain reg command. See here: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0043.md#chainid.

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +All the sidechain registration, verification, and execution parameters can be found  xref:{url_sidechain_reg_commands}[here].
The link doesn't work.

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +One of the key differences here between the sidechain registration command, is to activate the mainchain registration command, this requires that a substantial majority of the current active sidechai
This sentence reads weird, I would try to reformulate (the content is correct).

2022-12-05 10:41 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +All the mainchain registration, verification, and execution parameters can be found  xref:{url_mainchain_reg_commands}[here].
The link doesn't work.

2022-12-05 13:52 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Moreover, the liveness requirement to maintain the channel is not enforced, this means that there is no specific time requirement for a sidechain to be activated on the mainchain, it can stay in the
Goop point..I have now added this in, thanks 👍

2022-12-05 15:53 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The network ID is calculated from the address of the command sender and the genesis block ID, also given in the command parameters.
OK thanks, I have reworded this 👍

2022-12-05 16:12 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +For PoS chains, the value of the elements of this array is usually 1 as every active validator has the same finality weight to sign the next certificate.
Thanks, I have updated this paragraph 👍

2022-12-05 16:21 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +By using 4 bytes instead of 32 bytes this provides the distinct advantage whereby users are able to easily verify that they are signing a transaction for the correct blockchain.
Ok, thanks. I have reworded this 👍

2022-12-05 16:42 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +=== Chain ID
Cool. OK, I have reworded this accordingly. Let me know your thoughts. 👍

2022-12-05 16:59 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +One of the key differences here between the sidechain registration command, is to activate the mainchain registration command, this requires that a substantial majority of the current active sidechai
Hmmm..OK, I have tried to reformulate it and make it somewhat more direct, please let me know your thoughts 👍

2022-12-07 15:21 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The following parameters below are included in the registration command:
Hi Sergey, As discussed, I have restructure this. 👍

2022-12-07 15:21 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +All the sidechain registration, verification, and execution parameters can be found  xref:{url_sidechain_reg_commands}[here].
It should work now.

2022-12-07 15:22 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +All the mainchain registration, verification, and execution parameters can be found  xref:{url_mainchain_reg_commands}[here].
It should work now 👍

2022-12-08 10:43 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The processing of this command is designed to create a sidechain account in the mainchain state associated with a unique network identifier and a name.
Here also the term "network identifier" should be changed to "chain identifier".

2022-12-08 10:43 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +All the mainchain registration, verification, and execution parameters can be found  xref:{url_mainchain_reg_commands}[here].
Hm, previous link was fixed, but this one still doesn't work.

2022-12-08 10:43 UTC, sergeyshemyakov requested changes
Just two small comments left!

2022-12-08 12:44 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The processing of this command is designed to create a sidechain account in the mainchain state associated with a unique network identifier and a name.
Ah yes...Well spotted Sergey! Many thanks, it is now corrected 👍

2022-12-09 14:15 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +All the mainchain registration, verification, and execution parameters can be found  xref:{url_mainchain_reg_commands}[here].
Try now, I had a lot of issues with my new version of Webstorm 👍

2022-12-12 09:19 UTC, sergeyshemyakov approved these changes
Looks good!

2022-12-12 11:44 UTC, Tschakki requested changes
Please see my comments.

Additionally, the guide needs to have the concrete steps and give examples which the reader can simply copy/paste, so please include the respective example requests for registering a sidechain in this guide. In how-to guides, explanations should be short and simple, and the focus should be on the concrete steps to achieve the goal of the guide.

2022-12-12 11:44 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +In this section, the registration process is explained.
We already explain what is a sidechain in the understand blockchain category, so we can asume here the reader knows what a sidechain is.

Please improve the introduction section and explain what the reader will learn in this guide.

2022-12-12 11:44 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +In addition, the mainchain maintains these aforementioned data structures for each registered sidechain.
Please add an overview of all required steps here, e.g. as a numbered list.

2022-12-14 14:28 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +In this section, the registration process is explained.
Yes, good point Mona, I have restructured the introduction section 👍

2022-12-28 15:56 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +In addition, the mainchain maintains these aforementioned data structures for each registered sidechain.
OK, I have restructured the first 2 sections, which does now give a numbered overview list.

2023-02-07 17:07 UTC, chris529 reviewed
Looking great.. just a few minor points 👍

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The chain ID, used as store key, is also given in the command parameters.
```suggestion
The chain ID, used as a store key, is also given in the command parameters.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The name and chain ID of the mainchain are global protocol constants in the whole ecosystem.
```suggestion
The name and chain ID of the mainchain are global protocol constants in the entire ecosystem.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When the first cross-chain update containing messages is sent to the sidechain, the equality between the properties in the registration message and the ones in the interoperability store is verified.
```suggestion
When the first cross-chain update containing messages is sent to the sidechain, the parity of the properties in both the registration message and the the interoperability store are verified.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +. It must contain a non-empty certificate
```suggestion
. It must not contain an empty certificate with no data.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When a sidechain is started and registered, the sidechain developers might decide to not activate the sidechain straight away (maybe to do further testing).
```suggestion
When a sidechain is started and registered, the sidechain developers might decide to not activate the sidechain straight away (maybe to perform further testing).
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +It could happen then (intentionally or not) that an old block header (almost 30 days old) is submitted to the mainchain to activate the sidechain.
```suggestion
It could occur (intentionally or not), that an old block header (almost 30 days old) is submitted to the mainchain to activate the sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +. on the mainchain: a chain is live if chain account exists, is not terminated and the last certificate was submitted less than 30 days ago;
```suggestion
. on the mainchain: a chain is live if a chain account exists, is not terminated, and the last certificate was submitted less than 30 days ago;
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +. on the sidechain: a chain is live if no "terminated state" account exists and no chain account with status `terminated` exists.
```suggestion
. on the sidechain: a chain is live if no "terminated state" account exists, and no chain account with the status `terminated` exists.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This rule guarantees that users do not send funds to inactive sidechains and that users who have tokens in a sidechain which stops communicating with the ecosystem can recover their tokens.
```suggestion
This rule guarantees that users do not send funds to inactive sidechains and that users who have tokens in a sidechain that stops communicating with the ecosystem can recover their tokens.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +If a module receives a CCM that it considers to be malicious, it can call the  xref:{url_lip_45_terminatechain}[`terminateChain`] method of the Interoperability module to terminate the sidechain.
```suggestion
If a module receives a CCM that it considers to be malicious, it can call the xref:{url_lip_45_terminatechain}[`terminateChain`] method of the Interoperability module to terminate the sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Note, that if a sidechain uses the Lisk Interoperability module, it is never violate the protocol.
```suggestion
Note, that if a sidechain uses the Lisk Interoperability module, it never violates the protocol.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +But in case another custom module is used for interoperability in a sidechain, and it sends for example CCUs that don't follow the expected format, this can also lead to the termination of the sidech
```suggestion
But in case another custom module is used for interoperability in a sidechain, and for example, it sends CCUs that don't follow the expected format, this can also lead to the termination of the sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This message allows to inform sidechains about other terminated sidechains efficiently.
```suggestion
This message allows informing sidechains about other terminated sidechains efficiently.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Indeed, this message will automatically trigger the creation of the terminated sidechain account as soon as the first message is unable to be delivered.
```suggestion
Hence, this message will automatically trigger the creation of the terminated sidechain account as soon as the first message is unable to be delivered.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This also prevents further messages to be sent to already terminated sidechains.
```suggestion
This also prevents further messages being sent to already terminated sidechains.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This is helpful in preventing users from sending transactions to a chain whilst the cross-chain update transaction will be invalid.
```suggestion
This is helpful in preventing users from sending transactions to a chain whilst the cross-chain update transaction is invalid.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This makes it possible to provide <<recovery-as-a-service>> to users, to simplify the recovery process further.
```suggestion
This makes it possible to provide <<recovery-as-a-service>> to users, to further simplify the recovery process.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +For example, in the case whereby escrowed LSK exists in the sidechain account on the mainchain, which could have been subtracted by prior malicious behavior in the terminated sidechain.
```suggestion
For example, in the case whereby escrowed LSK tokens exist in the sidechain account on the mainchain, which could have been subtracted by prior malicious behavior in the terminated sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In case any tokens or other assets are stored on another sidechain and this sidechain gets terminated, the assets can to be recovered from the terminated sidechain.
```suggestion
In case any tokens or other assets are stored on another sidechain and this sidechain gets terminated, the assets can be recovered from the terminated sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Recoverable modules expose a `recover` method if the recovery is supported, like for example the Token module, and the NFT module.
```suggestion
Recoverable modules expose a `recover` method if the recovery is supported, for example, such as the Token module, and the NFT module.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +On a sidechain, the process flow can occur in 3 scenarios which are described below.
```suggestion
On a sidechain, the process flow can occur in the following 3 scenarios described below:
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +If a sidechain is <<sending-malicious-ccms>> which are breaking the protocol of the corresponding module on the receiving chain, the chain will notice this during the validation of the CCM.
```suggestion
If a sidechain is <<sending-malicious-ccms>> which are breaking the protocol of the corresponding module on the receiving chain, the chain will recognize this during the validation of the CCM.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The receiving chain will then terminate account of the sending chain.
```suggestion
The receiving chain will then terminate the account of the sending chain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Sometimes it can happen that a sidechain is terminated on the mainchain, and still active on other sidechains.
```suggestion
Sometimes it can happen that a sidechain is terminated on the mainchain, and yet it is still active on other sidechains.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The receiving chain will then terminate account of the corresponding sidechain.
```suggestion
The receiving chain will then terminate the account of the corresponding sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Further information including, the `createTerminatedStateAccount` function can be found in {url_lip_45}[LIP 0045].
```suggestion
Further information including the `createTerminatedStateAccount` function can be found in {url_lip_45}[LIP 0045].
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command has two purposes: It can be used to...
```suggestion
This command has two purposes: It can be used to perform the following:
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The {url_typedoc_interop_state_recovery}[Recover State^] command is used to recover assets (for example fungible and non-fungible tokens) from a terminated sidechain.
```suggestion
The {url_typedoc_interop_state_recovery}[Recover State^] command is used to recover assets (for example, fungible and non-fungible tokens), from a terminated sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The recovery of the state is then handled by the relevant module (for example, the token module would refund the user) and the state root is updated.
```suggestion
The recovery of the state is then handled by the relevant module (for example, the token module would refund the user), and the state root is updated.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* Access to the specific asset to recover from the sidechain
```suggestion
* Access to the specific asset to recover from the sidechain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command contains the channel account of the mainchain stored in the state of the terminated sidechain and an inclusion proof for it against the state root stored in the corresponding terminated
```suggestion
This command contains the channel account of the mainchain stored in the state of the terminated sidechain, and an inclusion proof for it against the state root stored in the corresponding terminated state account.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The message nonce is compared to the size of the inbox (also stored in the terminated outbox account) to check that the message had not been processed yet.
```suggestion
The message nonce is compared to the size of the inbox (also stored in the terminated outbox account), to check that the message had not been processed yet.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The module responsible for recovering the dedicated assets (e.g. the Token module) will then emit a <<recover-event>> to inform the network about the performed recovery.
```suggestion
The module responsible for recovering the dedicated assets (e.g. the Token module), will then emit a <<recover-event>> to inform the network about the performed recovery.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This choice allows for shorter inclusion proofs for the outbox root, as the other properties of the Interoperability module are not needed to recalculate the state root if the outbox root is known.
```suggestion
This choice allows for shorter inclusion proofs for the outbox root, as the other properties of the Interoperability module are not required to recalculate the state root if the outbox root is known.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +** `size`: The current size of the tree, i.e. the number of cross-chain messages received from the partner chain and processed.
```suggestion
** `size`: The current size of the tree, i.e. the number of cross-chain messages received from the partner chain that have been processed.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +** `size`: The current size of the tree, i.e. the number of cross-chain messages sent to the partner chain.
```suggestion
** `size`: The current size of the tree, i.e., the number of cross-chain messages sent to the partner chain.
```

2023-02-07 17:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* `initialized`: A boolean value, indicating whether the terminated state account has been initialized, i.e. if the `stateRoot` property has been set.
```suggestion
* `initialized`: A boolean value, indicating whether the terminated state account has been initialized, i.e., if the `stateRoot` property has been set.
```

2023-02-08 09:52 UTC, sergeyshemyakov requested changes
Generally looks very good!

2023-02-08 09:52 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +. The list of active validators on the sidechain in the <<chain-validators-substore>>.
If you want to be slightly more precise here you could mention that we store the list of keys of active validators.

2023-02-08 09:52 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Certain xref:{url_understand_module}[modules] of a sidechain client have the ability to terminate a sidechain account.
I think it would be helpful to add an example: Token module on the mainchain can terminate a sidechain if it violates escrow, i.e. sends more LSK tokens to the mainchain that were sent to this sidechian.

2023-02-08 09:52 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +NOTE: Notice that a sidechain terminated for this reason is not terminated in the whole ecosystem.
This is not entirely correct. If the mainchain terminates a sidechain, then this chain is terminated in the whole ecosystem (e.g. when violating LSK escrow). 
However imagine that a sidechain A violates escrow on a sidechain B (by essentially trying to mint native tokens from B), then B will stop communicating with A as you write in the note. The mainchain and other sidechain could still be talking to sidechain A.

2023-02-08 09:52 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +=== Sidechain Terminated CCM
Somewhere in this section I would add that the Sidechain Terminated CCM is sent to a sidechain when it tries to send a message to a terminated sidechain (and of course fails). See here: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0049.md#creation-2.

Otherwise it sounds to me like the mainchain informs all the chains in the ecosystem when a sidechain is terminated.

2023-02-08 09:52 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +    chainID: 00000000,
Note that `chainID: 00000000` is true only in the mainnet, the testnet and the betanet have different chain IDs. See here: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0037.md#mainchain-chain-id.

I would mention that this object is valid for Lisk mainchain in the mainnet.

2023-02-08 09:52 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +As explained in <<life-cycle-of-a-sidechain>>, there are 3 possible statuses: `active`(0), `registered`(1), and `terminated`(2).
Should be: "there are 3 possible statuses: `registered`(0), `active`(1), and `terminated`(2)."

2023-02-08 10:38 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The chain ID, used as store key, is also given in the command parameters.
```suggestion
The chain ID, used as the store key, is also given in the command parameters.
```

2023-02-08 10:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This is helpful in preventing users from sending transactions to a chain whilst the cross-chain update transaction will be invalid.
```suggestion
This is helpful in preventing users from sending transactions to a chain ,since the cross-chain update transaction will be invalid.
```

2023-02-08 10:59 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This command has two purposes: It can be used to...
```suggestion
This command has two purposes.
It can be used to perform the following:
```

2023-02-08 10:59 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The {url_typedoc_interop_state_recovery}[Recover State^] command is used to recover assets (for example fungible and non-fungible tokens) from a terminated sidechain.
```suggestion
The {url_typedoc_interop_state_recovery}[Recover State^] command is used to recover assets (for example, fungible and non-fungible tokens) from a terminated sidechain.
```

2023-03-02 14:26 UTC, sergeyshemyakov approved these changes
The PR looks very good, all my comments are rather suggestions for the improvement. Very nice docs!

2023-03-02 14:26 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Additionally, every newly registered sidechain can increase the size of every cross-chain update command posted on the mainchain.
I would add "because of the longer Merkle proofs" in the end, but this might be too technical detail.

2023-03-02 14:26 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +        "messageFeeTokenID": "0300000000000000",
I am slightly confused about this value. This corresponds to LSK token ID in network with id `03`, but you have registered a sidechain with network ID `00`. I think this should not be possible. Could you please double check this example with SDK?

2023-03-02 14:26 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +* It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise the sidechain interoperable functionality may be
Maybe you could add that if the mainchain registration command was submitted with the wrong data, then the whole sidechain needs to be restarted. I am pretty sure that someone at some point will mess up and will look for solutions how to fix it :)

2023-03-03 10:26 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +        "messageFeeTokenID": "0300000000000000",
Good catch, I tested the process on the alphanet, but wanted the guide examples to refer to mainnet and forgot to update this value. Should be fixed now 👍

2023-03-03 10:29 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +* It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise the sidechain interoperable functionality may be
Just to clarify, what exactly do you mean with "it needs to be restarted"?

2023-03-03 15:50 UTC, ishantiw reviewed
Some comments related to Image
- `docs/modules/ROOT/images/understand-blockchain/interop/recovery_sidechain_2.png` can be improved, the arrow is not touching the box as in the other diagrams

- `docs/modules/ROOT/images/understand-blockchain/interop/sidechain-registration.png` maybe also can mention that relayer sends CCU from sidechain to mainchain as well to make it active but no checked for liveness I think

2023-03-03 15:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Set the `height` to the *latest block height on the sidechain* in the request parameters:
here you can also mention to retrieve the latest height from `system_getNodeInfo` RPC as some users might want to automate this

2023-03-03 15:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Copy the transaction and send it ot the node, for example by using the node CLI like so:
```suggestion
Copy the transaction and send it to the node, for example by using the node CLI:
```

2023-03-03 15:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    "method": "interoperability_getChainAccount",
FYI: we are going to change this RPC to `interoperability_getChainData` to align with the LIP

2023-03-03 15:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +lisk-core endpoint:invoke interoperability_getChannel '{"chainID": "00000001"}'
FYI: we are going to change this RPC to `interoperability_getChannelData` to align with the LIP

2023-03-03 15:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To create a valid signature, an amount of sidechain validators equal or greater to the <<sidechaincertificatethreshold>> need to individually sign the Mainchain registration with their account.
maybe to specifically mention that `sidechainValidators` with enough weight need to sign the mainchain registration message with `ownChainID`, `ownChainName`, `mainchainCertificateThreshold` and `mainchainValidators` and generate the aggregationBits and signature required for registration params.

2023-03-03 15:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To simplify the process, you may use the following script, which adds a validator signature to an existing list of signatures: {url_exmaples_guides_validatorsignatures}[validatorSignatures.ts]
also mention that for **testing only** we can use the script

2023-03-06 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To simplify the process, you may use the following script, which adds a validator signature to an existing list of signatures: {url_exmaples_guides_validatorsignatures}[validatorSignatures.ts]
Why for testing only? How should it be done in a real scenario?

2023-03-06 10:27 UTC, Tschakki commented
> Some comments related to Image
> 
> * `docs/modules/ROOT/images/understand-blockchain/interop/recovery_sidechain_2.png` can be improved, the arrow is not touching the box as in the other diagrams
> * `docs/modules/ROOT/images/understand-blockchain/interop/sidechain-registration.png` maybe also can mention that relayer sends CCU from sidechain to mainchain as well to make it active but no checked for liveness I think

- Concerning `recovery_sidechain_2.png`: This image was reused from an older blog post, and I don't have the original image to be able to change this detail quickly. As it would be a lot of work to recreate the diagrams to make them all look aligned, I suggest to leave it for now and revisit the images at a later point again.
- Concerning `sidechain-registration.png`: I have updated the diagram accordingly, please check if it is correct now. :)

2023-03-06 11:14 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +* It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise the sidechain interoperable functionality may be
I mean that a running chain should be discarded, all nodes shut down and a new chain with the same initial settings created. I think, this would be the easiest way to fix incorrect mainchain registration.
Alternatively, the chain could be hard forked and the Interoperability store could be edited, but I assume it will be more challenging for the devs.

2023-03-06 16:52 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To simplify the process, you may use the following script, which adds a validator signature to an existing list of signatures: {url_exmaples_guides_validatorsignatures}[validatorSignatures.ts]
I checked the `validatorSignatures.ts` and saw you commented the loop part for devnet validators. So i think this is correct. You can maybe simplify it by saying that individual validators can sign as below,

```ts
params = {
        ownChainID: Buffer.from(paramsJSON.ownChainID, 'hex'),
        ownName: paramsJSON.ownName,
        mainchainValidators: paramsJSON.mainchainValidators.map(v => ({
            blsKey: Buffer.from(v.blsKey, 'hex'),
            bftWeight: BigInt(v.bftWeight),
        })),
        mainchainCertificateThreshold: paramsJSON.mainchainCertificateThreshold.toString(),
    };

    // Create message by encoding params
    const message = codec.codec.encode(registrationSignatureMessageSchema, params);
    
    const signature = bls.signData(
          MESSAGE_TAG_CHAIN_REG,
          params.ownChainID,
          message,
          Buffer.from(blsKeys[0].plain.blsPrivateKey,"hex"),
        );
```

Maybe refine it a bit but they can simply share the signature to the person who is sending the registration transaction

2023-03-07 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To simplify the process, you may use the following script, which adds a validator signature to an existing list of signatures: {url_exmaples_guides_validatorsignatures}[validatorSignatures.ts]
I removed the commented code now to make it clearer, and added additional information into the guide :)

2023-03-09 16:22 UTC, ishantiw approved these changes
Some minor comments but LGTM. Great job on the extensive explanation of recovery mechanism

2023-03-09 16:22 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The recovery process for on the mainchain works as follows:
```suggestion
The recovery process on the mainchain works as follows:
```

2023-03-09 16:22 UTC, ishantiw commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +1b. A User can start recovering assets with a <<recover-state>> command.
```suggestion
1b. A user can start recovering assets with a <<recover-state>> command.
```

2023-03-13 12:48 UTC, TalhaMaliktz requested changes
Looking good already :)

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.Deep Dive into Cross Chain Messages
The caption isn't rendered properly for the videos, maybe we can rethink about the captions.

![Untitled](https://user-images.githubusercontent.com/13951043/224023534-e3fee59f-2264-4496-a4dd-9370801cf72a.jpg)

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.Deep Dive into Cross-Chain Update Transactions
Same thing with this caption as well.

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +On this page, we dive deeper into the details of how cross-chain communication works in the Lisk ecosystem, by describing the different components and the general processes how state changes are exec
```suggestion
On this page, we dive deeper into how cross-chain communication works in the Lisk ecosystem, by describing the different components and the general processes of how state changes are executed across chains in the Lisk ecosystem.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +Specifically you'll learn about:
```suggestion
Specifically, you'll learn about:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +.Overview about the Lisk Interoperability solution
Caption issue as described earlier.

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* [x] What is a sidechain
```suggestion
On this page, we discuss the Lisk interoperability protocol.
Specifically, you'll learn about the following:

* [x] How Lisk facilitates communication across chains?
* [x] General terminology related to interoperability across chains.
* [x] What is a mainchain?
* [x] What is a sidechain?
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +TIP: A full playlist of all videos presenting the full Lisk Interoperability solution can be found on the {url_yt_playlist}[Lisk youtube channel^].
```suggestion
TIP: A comprehensive playlist of all the videos presenting the entire Lisk Interoperability solution can be found on the {url_yt_playlist}[Lisk youtube channel^].
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
>  * *sidechains*: Blockchains built with the Lisk SDK.
```suggestion
* *Sidechains*: Blockchains built with the Lisk SDK.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
>  * the *Lisk Mainchain*:  Follows the Lisk Mainchain protocol and cannot be modified by a blockchain application developer, and
```suggestion
* The *Lisk Mainchain*:  Follows the Lisk Mainchain protocol and cannot be modified by a blockchain application developer, and
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +To become part of the Lisk blockchain ecosystem, they need to include the Lisk Interoperability module.
```suggestion
To become part of the Lisk blockchain ecosystem, a sidechain needs to include the Lisk Interoperability module.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +. They are prepended to the input of the signing function of every transaction, block, or message of the chain to avoid transaction replays between different chains in the ecosystem;
```suggestion
. They are prepended to the input of the signing function of every transaction, block, or message of the chain to avoid transaction replays between different chains in the ecosystem.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +In particular, in the Interoperability module, it serves a similar purpose for chains as addresses do for user accounts, as it is used to identify the chain account in the Interoperability module sto
```suggestion
In the Interoperability module, it serves a similar purpose for chains as addresses do for user accounts, as it is used to identify the chain account in the Interoperability module store.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +For example, it has to be specified in the `receivingChainID` property of a CCM to this sidechain and in the `sendingChainId` property of a cross-chain update command from this sidechain.
```suggestion
For example, it has to be specified in the `receivingChainID` property of a CCM to a sidechain and in the `sendingChainId` property of a cross-chain update command from a sidechain.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +. The *chain-specific sufffix*:
```suggestion
. The *chain-specific suffix*:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
>  |Use Case|RMT|Description
What does an "RMT" stand for? I think we should abbreviate it in the text as well, similar to what we do for SMT at line# 51

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
>  Using the `transactionRoot` and a proof-of-inclusion, it is be possible to check whether a certain transaction is part of the block without downloading the full block.
```suggestion
Using the `transactionRoot` and a proof-of-inclusion, it is possible to check whether a certain transaction is part of the block without downloading the full block.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +| The root of the asset Merkle tree is added to the block header to allow checking inclusion and non-inclusion of block assets.
```suggestion
| The root of the asset Merkle tree is added to the block header to allow checking the inclusion and non-inclusion of block assets.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +* [x] What data is stored on-chain to facilitate interoperability across chains
```suggestion
On this page, you learn about the sidechain registration and recovery process in the Lisk ecosystem.
Specifically, you'll learn about the following:

* [x] The lifecycle of a sidechain.
* [x] The sidechain registration process.
* [x] What happens when a sidechain is terminated?
* [x] Data recovery from a terminated sidechain.
* [x] What data is stored on-chain to facilitate interoperability across chains?
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The first step for sidechain to become interoperable with other sidechains and the Lisk Mainchain, is to register itself to the mainchain.
```suggestion
The first step for the sidechain to become interoperable with other sidechains and the Lisk Mainchain is to register itself to the mainchain.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +TIP: Please check out the guide xref:{url_build_regsidechain_sidechain}[How to register the mainchain on the sidechain] for a step-by-step explanation about the process.
```suggestion
TIP: Please check out the guide: xref:{url_build_regsidechain_sidechain}[How to register the mainchain on the sidechain] for a step-by-step explanation of the process.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +When the first cross-chain update containing messages is sent to the sidechain, the parity of the properties in both the registration message and the the interoperability store are verified.
```suggestion
When the first cross-chain update containing messages is sent to the sidechain, the parity of the properties in both the registration message and the interoperability store are verified.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +This is helpful in preventing users from sending transactions to a chain ,since the cross-chain update transaction will be invalid.
```suggestion
This is helpful in preventing users from sending transactions to a chain since the cross-chain update transaction will be invalid.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The recovery process for on the mainchain works as follows:
```suggestion
The recovery process for the mainchain works as follows:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +1.State recovery::
I think we can restart the list instead of hard-coding the number.

```suggestion
[start=1]
. State recovery::
```

Reference: https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +2b. A user can now recover pending messages with a <<recover-message>> command.
Same comment as above, about hardcoding list numbers.

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +a. A "terminated state" account containing the mainchain last certified state root is created in the sidechain state.
```suggestion
a. A "terminated state" account containing the mainchain's last certified state root is created in the sidechain state.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +//URLs
Throughout the page, there are hard-coded list numbers, which shouldn't be used as they don't format well, whilst viewing in the browser. We should use the available lists as per the following: 
https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +That is, because the mainchain does not inform other sidechains immediately about a termination.
```suggestion
That is because the mainchain does not inform other sidechains immediately about a termination.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +However, it is important to note that in this case, the terminated sidechain state root is set immediately, and there is no need for a <<initialize-state-recovery>> command.
```suggestion
However, it is important to note that in this case, the terminated sidechain state root is set immediately, and there is no need for an <<initialize-state-recovery>> command.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +a. A <<initialize-state-recovery>> command is sent.
```suggestion
a. An <<initialize-state-recovery>> command is sent.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Each substore and its contained data is described in detail below.
```suggestion
Each substore and the data in it are described in detail below.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +. on the sidechain: a chain is live if no "terminated state" account exists, and no chain account with the status `terminated` exists.
```suggestion
. On the mainchain: a chain is live if a chain account exists, is not terminated, and the last certificate was submitted less than 30 days ago.
. On the sidechain: a chain is live if no "terminated state" account exists, and no chain account with the status `terminated` exists.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The recovery process for this scenario 1 works as follows:
```suggestion
The recovery process for scenario 1 works as follows:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The recovery process for this scenario 2 works as follows:
```suggestion
The recovery process for scenario 2 works as follows:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In case it is already known that a sidechain is terminated by the users, they can avoid scenario 2, where a CCU is rejected, and directly initialize the state recovery.
```suggestion
In case it is already known that a sidechain is terminated by the users, they can avoid <<scenario-2-receiving-a-sidechain-terminated-ccm, scenario 2>>, where a CCU is rejected, and directly initialize the state recovery.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +The recovery process for this scenario 3 works as follows:
```suggestion
The recovery process for scenario 3 works as follows:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +NOTE: This command can only be submitted on a sidechain.
```suggestion
NOTE: The {url_typedoc_interop_init_recovery}[Initialize State Recovery^]  command can only be submitted on a sidechain.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +On the mainchain in the Lisk *Mainnet*, the own chain account is present by default, and set to an object with properties:
```suggestion
On the mainchain in the Lisk *Mainnet*, the own chain account is present by default and set to an object with the following properties:
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +Key:: Each store key is set to the ID of the partner chain `chainID`.
```suggestion
Key:: Each store key is set to the ID of the partner chain's `chainID`.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +** `validatorsHash`: The validators hash contained in the last certificate from the partner chain.
```suggestion
** `validatorsHash`: The validators hash present in the last certificate from the partner chain.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +In particular, the CCM fee must be larger or equal than the product of its size in bytes and `minReturnFeePerByte`.
```suggestion
In particular, the CCM fee must be larger or equal to the product of its size in bytes and `minReturnFeePerByte`.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +If the chain ID is still available, it should return `false`.
I think it will return `true` in case the chainID is available for use in the ecosystem, if a chainID is already being used, the code will return `false`.
Reference: https://github.com/LiskHQ/lisk-sdk/blob/84fbbfa717a45b757d67502b883ff7afb132874c/framework/src/modules/interoperability/mainchain/endpoint.ts#L55
```suggestion
If the chain ID is still available, it should return `true`.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Has to be *unique* within the Lisk ecosystem  and contain only characters from the set `[a-z0-9!@$&_.]`.
```suggestion
The name of the sidechain is a string that has to be *unique* within the Lisk ecosystem and should only contain characters from the set `[a-z0-9!@$&_.]`.
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +TIP: The `system_getNodeInfo` node endpoint can be requested, to retrieve the latest block height.
Please add a link to : https://liskhq.github.io/lisk-docs/beta/api/lisk-node-rpc.html#system_getnodeinfo

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +.sidechain_reg_params.json
```suggestion
.registerSidechain.json
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +.sidechain_reg_params.json
```suggestion
.registerSidechain.json
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Taking this into account, we decide for a `sidechainCertificateThreshold` of 65:
How do we decide that this number should be 65? please add more info about it. When I query the `consensus_getBFTParameters `, I get: `"certificateThreshold": "68"`, are these two values connected?

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +  ]
`consensus_getBFTParameters` also returns the following values as well:
```
    "certificateThreshold": "68",
    "precommitThreshold": "68",
    "prevoteThreshold": "68",
    "validatorsHash": "14c3b81db7bf2b2e211a753828f4e2cf7795450ef033e3c9a885bef670dbad70",
```

- Should we add them in the `registerSidechain.json`?
- How is the `certificateThreshold` returned by the endpoint different from the one we define in the subsequent text?

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +.registerSidechain.json
IMHO, it's better to add everything into the `registerSidechain.json` file, and turn it into a collapsable tab, so that the reader can see the full picture of what they should have by the end of this section.

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a04040000
Please add the entire hex string to avoid any confusion.

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +        "name": "sidechain_8",
For the sake of synchronization, let's use the same name.
```suggestion
        "name": "sidechain1",
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a04040000
Should this be `lisk-core` instead of `./bin/run`?

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +const message = codec.codec.encode(registrationSignatureMessageSchema, params);
```suggestion
const message = codec.encode(registrationSignatureMessageSchema, params);
```

2023-03-13 12:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run endpoint:invoke interoperability_getChainData '{"chainID": "00000000"}'
Endpoint's name might need an update!

2023-03-13 15:35 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.Deep Dive into Cross Chain Messages
I think this issue is actually UI related. I wouldn't change it in the PR, but I can open a new issue to improve the styling of captions in the UI, so that it looks nicer and is distinguishable from normal text content.

2023-03-13 16:20 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Taking this into account, we decide for a `sidechainCertificateThreshold` of 65:
I think the `certificateThreshold` is a valid default value, in the middle between the minimum and maximum possible values, But maybe @ishantiw can clarify.

65 is just chosen here in the example, it could be any value between 34 and 101, which is mentioned in the previous sentence.

2023-03-13 16:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18002080a8d6b9072a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0324a0a04040000
yes :)

2023-03-13 16:24 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +const message = codec.codec.encode(registrationSignatureMessageSchema, params);
i think this snippet is actually correct, the way codec is imported

2023-03-13 16:31 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +1.State recovery::
For me this breaks the styling with the `::` unfortunately :(

2023-03-13 16:40 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run endpoint:invoke interoperability_getChainData '{"chainID": "00000000"}'
I think this is correct considering the latest updates, maybe @ishantiw can clarify

2023-03-13 16:48 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
>  |Use Case|RMT|Description
Good catch, I updated the description slightly, to clarify what RMT stands for

2023-03-13 16:50 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +//URLs
I think in some places I did this intentionally, because using the ordered list format will break other stylings (`::` for example)

2023-03-13 17:00 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +  ]
I think `certificateThreshold` is just a valid default value for the threshold. About the other properties, I am not sure if they are relevant in this context, maybe @ishantiw can clarify :)

2023-03-15 10:01 UTC, TalhaMaliktz requested changes
Thanks for applying the feedback. A few more suggestions 😊

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +This will return a complete list of all active sidechain validators at the specified block height.
There is an existing [snippet ](https://github.com/LiskHQ/lisk-sdk-examples/blob/development/guides/chain-registration/sidechain/sidechainRegistration.ts) which should be referred to here and the text should be altered accordingly. Manually copying and pasting the `consensus_getBFTParameters ` response results in an error in transaction execution.

This error is caused because the `blskey` values are not sorted, the script mentioned earlier, not only gets the values of BFTParams but it also sorts them. Only a sorted list of sidechain registration parameters is successfull.

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Taking this into account, we decide for a `sidechainCertificateThreshold` of 65:
Cool, I have suggested additional information. It would be really helpful if we mention how the number: 65 will be used.
Like does 65 means that at least 65 validators should sign & validate this transaction for it to be valid and ready for execution? Or does it signify something else? I think clarity is required here.

```suggestion
The value of a `sidechainCertificateThreshold` can be between the minimum and the maximum value of the `aggregateBFTWeight`.
Taking this into account, we decide to have a `sidechainCertificateThreshold` of 65.
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18012080a8d6b9072a203972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c32e32a0a040300
```suggestion
lisk-core transaction:send 0a10696e7465726f7065726162696c6974791211726567697374657253696465636861696e18012080a8d6b9072a203972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c32e32a0a0403000008120b73696465636861696e2d381a340a308dffebf58c3ffeada90d1196d2587d4e8342a4caf7283351e12403d543cd7452b24f4a6d359b160c439dbbed11d7a8fe10011a340a3095ce3d5fb56fb8540f57f626b65fea8ea9a2792371854ffa011a2e99d8ca70abec0ef3a5bef57ad593e20466c9a2b1fa10011a340a308c9abeecbf578e6f6f50eb2c1148f80ec4058c51d7e442b899a6c7f9ec89db3bc20ed95488f2817c0e5ab64f8332cef610011a340a3080e1925e87e8435be1459e6e03f4aea41280e352ff0d30a356d31e9669587bb30de8cfc095fba2c4dcea145edaac3d9f10011a340a30aaafcac8e9fa128140a063a6b8ebe3db77df53b04bcc80c4998c27434b98cc9f8b2fc48a7e499209d4f986035b56f7bb10011a340a30b2f7593bf4b73356c758542f305518056d618415e96ffdf1f5ae4aab2de013d484f062ca2ec7fd6880e7df2345acfc0510011a340a30945f96d83664c47a0b7cd6f64933085e6bf43b382b6ce555c96d6f706c8800a9848605af7b59f7866346390122d8c6a410011a340a30a431b13fb40e7bae6fada4d32e64641704202a8e1f64ec95438d8b49e5cb6cbaece08daea219f43ed5de3162c005748010011a340a30a467fadad40ad44bc5b63abc2e0f43054032475cc8eac21fe93e0aaf6d0822fd390f7464608240f780c7905367aa4ef210011a340a30b7ff6780436377ae340c1081f04e5a4ce2c4459421278ca6198b982b044a8e2bb3143b8a1a7fdb2f4cc2c55020d1948c10011a340a30a3ba48f22c963c5400ee6206097573a333d67acaaae93ec8f3666cafbb6249db69ff0cb1ba13e612fec135ff2f3cc02310011a340a308d2c2ee2b55d7d19d6e42eebc881fcb28cf3b442db0ecd23307d89c3ed2ee25864a0f97fecdeca17a30c01648343d37610011a340a30afc6af040b6234b5d928c0c4fcd8bfa6715e6f779e26acc19b79c7be7629b0bb00cd39fb3ffee64fab1e8174ac1d959410011a340a3083a2728e7209144ce73eccf5bad1dd47ce48291c04c9970094bbdd7c6693a141daa39f98474a4c57c2515eb6ca5dc88210011a340a30ab58a1900ff71771aca333163ff0fa9f1112986347f6ec8e31c455978c6adb256af8313ce719d3da5e3c7c27d34267a210011a340a30881e474dbbaa65962491eeb3b747954658550c4fdb30246336db2bce83851d33b15f6cf44f25cd9deff484fc88c9ea8010011a340a3089df859598134753ad8adb525c36979ca5b17ec7bd37ef6ed7461fcb0680c336bffb159f6cdc06b6d78d73cf24c1f54910011a340a30978707c5713808cb16d048fa7b27545b14a2cd99d16adbdd4b141c92ff8658c71a5c66051450554c2a5bbf0cfbd34c3f10011a340a30b66bc3797dceb6567c8aea87a3887f12fe85fe9af8df19a5e66a1eb730d8f8288bca6f1bf24970dd2ad047df5376e3e010011a340a30b8b0050f1662a6b12fe95f632368ad963001c51ce04aac76aae21a51c1199551bfe1d7abe8a21de7364a132233d52eca10011a340a308da4a9262ec1f0d01640b94bec00ac51594cfaff14ea3b9b2f79773dc1c3ca63eb7d86da2570b88efa1fe33425a287b310011a340a30a11ee270162c55cb7985d4247985a33c7102aa4e637018e03119887c6e73910e8cef8ceb23d76e5dc4f73679b3f1e42110011a340a30b601f03ca5ebb416d82c070be4cd8232df28f37d92549d4d6381b082fb9b80a8777e44d324728f957a934a454e0cfb1510011a340a308f4e15c9a87132453e669b7dd6f10616a58b45f3eacae0e31dbe7bea232066db881ae00907234f230fca932d5986d3e010011a340a3083717971cbe501ea79594c5ceae80fe3c09d1990faffafa2ae273908f9c99d2b27f245a4e3b03e51e18e0b1a54b237e410011a340a30887d62bd098d331d647c57f52427eb1c991ac76a60881eba96c312a904014d8c261f42854f6a841951307959f8c2e41010011a340a308012798d2ac6b93df3bfa931192d9b2d496c3c947958a7408232e08872895557c06c1b94f5cc2555e28addbaadf3e0bd10011a340a30b3df1d6c635e97b7b2e9feb00870c6238b7bda7246d6849b1fd549616aba816f1a265c7eeed15a4c35655c2fee62e65710011a340a30b5d203c4555d4c7b3329ae1bd725a0a909a60322c7bbdc7a8630169ef7b1e8e3599fbac6336b1841b54b6bde9fef6b5a10011a340a30997efce2f5b5b0efc97b3d0c689813fb56e3ed0627fe6b88cee495466ebd604500a13cf7ed8808a63fbd915cc8a9c36610011a340a3092a25b59d8a5ff6484d45516a07080f890883d761562d7c177d747e9148ba92092c96f373348e65e0c89cca0c837efa710011a340a30b93b3f3ca115695b018229db563bfa024cdee752ef7e710b3818d4234dace5fd67e345fcb90f21198ebefe6c2d87d28d10011a340a30820f7ee17502c75c80b3830fa2912f174e7f0972414fba035973bba4cb873e9f21d594575f8db2255d58e69c136f90ce10011a340a30b49ec00ad81c92bc1137ba5ac09d41bdb3d7cba1679ccf793e5ca5991d8215bb32462c7af55c386ea8482181f72b165e10011a340a30afed4083c5523f6c76d82a00598673fc8fc33a89ed6d94a473cea54c044a0f0a77ae58e90ad808df9e23286d37a818f810011a340a308ff19b8a449c0b2c716e3041f58484e2e1f5ab7ba279fce30ddac50fb4ac14d146fe4ed57ac9581004b8cd4134256a0c10011a340a3096fbcdcc73487b93642d848007f4c5803f3aa6073789611071ec22ae28fa4d68e7480574023b4e8ab1e2026ae6d1bd5610011a340a3097ab2fbbd6302314ee1bb350156111d621268c4715c7e2fc17bca5fc8d4ac067f250d1ea383e6e12c4322d3d09d4786710011a340a30859c2f41d5c95638469796b4bed1f788b3a4da2aa3730953d96cd06fc0bdd1942213644f5415059710394b5c21970b2910011a340a30877342d9da45cdb72cea1b3f83ff391a25bbb40f0f17005aceb39a6102ea8ced78021bd830f378edd8a815b6c3f1628010011a340a30b3fea6464eb53f32f02dc3b6c313ba617466decf7f8bdc76a7cd5b1fbed45c85324654e131b0a54ec18c30c90ca1fc4610011a340a30a631f867d8196d249221ade60de85b2fdd2c420b253655c4db8129358ff9f1465b8bdefedc43b065328ac577102d838910011a340a308fd987c26195f8a16e8887c4da08e98a6ce2fcf566cc9aeb10a591b8cfc8b2dd63e352f7f89a34de508defc6fa74a38910011a340a30998cae9553f1b857679fea5483f62f7df90c6069067839444eca468427d5475ae8c30981fee9efce0d7ea051a9f8057b10011a340a3093b377e225e453e945772185dfcd804ffea9f15bf24db21945336f55b9bf477605116aec69321fbcb1ccfc42b6c7b7f510011a340a30acac37c80386a65aec329e2554a7603e1a225d4e2d66c338222b5c047b95f4f730717db707625ed95ec5e89f43e3931710011a340a30a68c525a3f41a5bfaf2da2d2c50868bd1cfa2dfa8b202692bc6f526f91fc783b400754ca1b20b8b02b61c740a828c66710011a340a30b07d6418604357a7d1c9d388175eb702ee17411db1cc0939015a9b4ba104addeaee14ab3e616a10444c72a94be518b2810011a340a308d23cdf74166e64a3163f3219ac4b7b233e34a455a789fad2faaf522523cfe75c4f817575ddbfd24710b3b2cdff08ebe10011a340a30a51c34b3b8a21df3aa05be07467c9b4d3d90dbcc7791c747c2f0f30d2ac871aaac3199716bf3e7248f25d3e9045d055210011a340a30af5b2dcb3ea14e0820d3d8b2b0d21594be9b8acfaf2cb77148cf3fe8e9900334ae60d0311278673e50753e5a3ff62bfa10011a340a3093ca96d5240a440cd0c51bee1ad76d3d9bf5d80208b8dc7af8f2acfb6183b8e600232b683ce8da402f52139b84c9946110011a340a3093111acc2098a914e9377be0c044695c37a3e3d69d1ccd2400eab59b0e846f27fd3a084ff3cff5b4de01890c4083921e10011a340a30873096d7b1d2cdf69d2a4b492b5d9d1ae0baf1c8cdde3b096a83a08e696bb9c4a18cafac212741064703dec95efd29e610011a340a30829ce5aaea989ae0fbe8afb2211f2630b7df1035a69462ca2b9c6d4aeef48d3232528ffb5ccb4ae01396a4654f1fbb4110011a340a308fe15645e54ffb3a815bc93f882986b42655e0b20cf112f71ed94b331b714d50c1a44d9c28b9bcd140741adec159c8ce10011a340a30a0465875b9eaba9270d4b288e3271f388174f8756b153537e32f8a1abd1e3df7e63029f59dff882859bac585e21a2bfc10011a340a3085ad6e9a5650864d4a332bace72a497e5df917362b4de8246095c985b571e13fa6f344e5d265f28cbf255f57edefb70410011a340a3089e65c4fec65d41861135cc1304ac2c5bf6da9099aa9c161b24cf68fc8fbc5835d54c62de475c6545676f252ba9bfc1610011a340a30ae8aa2862a9efa27515885f810be2ae2ebe8a681289a348b28a6f6f65d067bcc5bdaf82b2f7a26c8c3e6025cec257a0e10011a340a30a6b88f31d6ddcb1e195d166253f5629c2cf03430d946a9807b7c1b413b60186cf6588aad67a453c6d37a5c97a10f284510011a340a30862b40bafbe512e98c62ed88bef47531f180b60584163e550a7a94574f7cc5df2d768bc1eded57aa5d011b5c7ca1a0e910011a340a309070783523bcdd8d0ed5fdc7eb0d40d22d0dde03be06e1a6beb541efbb4b764dba27ad4c6fd7b0f3802abab7c4bf48fc10011a340a3090d95277900969ff5ebd7f92edebaa16e0af77a1622b36f76d8f93b790461529886fe7b132de3b31c82bf35f05274c0a10011a340a3091412ac7e9faa84f4d23dc821212b8eadee0094a29985776be57681373314561a53a6e7112d6b7e66076242752db885f10011a340a30b0638b4ecfd3413156c292b242a0c3378807f9346649498cb3fa4adc8926630df487c89033de5275ec400be830c569b110011a340a30b840b34a50c5dc3aa7c5d48e0fd803554eb6125e22c78f81e122ed6c418c069a98cf2c0f8c6e701ba8ef5c68eb4f6d9910011a340a3081b45d2107aa0eb61951d7cd4e19a7eb67135d790e6de0b17e31b8089a0efa52ae5b9e0a51da75692344a7e15008fc7710011a340a3095ecca2fe2fecfa5380a4eb2bc1a548fe4a7b9bd6c2d739df7b4b8330943319d0800ccba5dc8f4e797d526ee463dd10310011a340a30a3032a4a9dc05865b5472f04c40be6d22b44c0426657fbdb7140692adc5bd37cf6e016ebe248f503b39b6d21084e41b910011a340a30aacc9c3bce591c6df8c6d51ebedb10230278a6572eec45f2f9e16724860ae191de0a1ee5bff4dbc0a0b20c1b7b21404a10011a340a3083058f8ade0796d972870804d8f18266f5fb528e3c2e5e0f43244c316a95854ee4668962e3564ae35 [...]

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To verify that the account was created successfully, request the `interoperability_getChainData` endpoint from a mainchain node.
```suggestion
To verify that the account was created successfully, request the `interoperability_getChainAccount` endpoint from a mainchain node.
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    "method": "interoperability_getChainData",
```suggestion
    "method": "interoperability_getChainAccount",
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +lisk-core endpoint:invoke interoperability_getChannelData '{"chainID": "00000001"}'
```suggestion
lisk-core endpoint:invoke interoperability_getChannel '{"chainID": "00000001"}'
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    "method": "interoperability_getChannelData",
```suggestion
    "method": "interoperability_getChannel",
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +        "certificateThreshold": "66"
Since we say that we have chosen number **65**
```suggestion
        "certificateThreshold": "65"
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The transaction will be returned in hex format:
```suggestion
As a response, the CLI will ask for the `passphrase` of the mainchain node.
Once the correct `passphrase` is passed, the transaction will be returned in hex format:
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node paramsCreation.ts
Some minor changes to `paramCreation.ts`:

```
const { writeFileSync, fs } = require('fs-extra');
const { apiClient } = require('@liskhq/lisk-client');

// In case you want to access a remote node, use an RPC Websocket URL
// const RPC_ENDPOINT = 'ws://142.93.230.246:4002/rpc-ws';

const SC_CHAIN_ID = "04000001";
const SC_NAME = "interoperability";

(async () => {

	// For Using RPC Client with a remote node address.
	// const mainchainClient = await apiClient.createWSClient(RPC_ENDPOINT);

	const mainchainClient = await apiClient.createIPCClient('~/.lisk/lisk-core');
	const mainchainNodeInfo = await mainchainClient.invoke('system_getNodeInfo');

	
	// Get active validators from mainchain
	const {
		validators: mainchainActiveValidators,
		certificateThreshold: mainchainCertificateThreshold
	} = await mainchainClient.invoke('consensus_getBFTParameters', { height: mainchainNodeInfo.height });

	// Create Registration message parameters in JSON format
	// Update ownChainID and ownName to equal the sidechain ID and name that were registered on the mainchain
	const paramsJSON = {
		ownChainID: SC_CHAIN_ID,
		ownName: SC_NAME,
		mainchainValidators: mainchainActiveValidators.map(v => ({
			blsKey: v.blsKey,
			bftWeight: v.bftWeight
		})).sort((a, b) => Buffer.from(a.blsKey, 'hex').compare(Buffer.from(b.blsKey, 'hex'))),
		mainchainCertificateThreshold,
	};

	// Save params and params as JSON in a file params.json
	writeFileSync('./params.json', JSON.stringify(paramsJSON));

	process.exit(0);
})();
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +The next step is to collect and aggregate the corresponding signatures form the sidechain validators, see <<preparing-the-aggregated-signature>>.
```suggestion
The next step is to collect and aggregate the corresponding signatures from the sidechain validators, see <<preparing-the-aggregated-signature>>.
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +An integer defining the minimum BFT weight threshold required for the first mainchain certificate to be valid.
```suggestion
`mainchainCertificateThreshold` is an integer that defines the minimum BFT weight threshold required for the first mainchain certificate to be valid.
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +This file can be generated for a specific validator with the `keys:create` CLI command, by providing the passphrase.
```suggestion
```suggestion
. `keys.json`: A file with the `blskey` values of the validators intending to sign the registration transaction.
.. This file can be generated for a specific validator with the `keys:create` CLI command, by providing the passphrase.
+
[source,bash]
----
./bin/run keys:create --count 103 --output ./keys.json 
----

The `--count` flag can be altered according to the need of a sidechain.
```
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
This script needs an update according to the following file:

https://lightcurve.atlassian.net/wiki/pages/viewpage.action?pageId=6127961&pageVersion=37&preview=/6127961/8094237/prepare_mainchain_reg_params.ts

- The `keys.json` file is passed to the script, however, the signature is only created for the 1st index of the validator, the attached URL contains code (**Line 87-114**) for looping through the entire list one by one and then creating a signature accordingly.

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node mainchainRegistration.ts
The **Signature Verification Fails** with the given script, Please check the following script to correct any issues that might be causing this failure.

https://lightcurve.atlassian.net/wiki/pages/viewpage.action?pageId=6127961&pageVersion=37&preview=/6127961/8094237/prepare_mainchain_reg_params.ts

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run endpoint:invoke interoperability_getChainData '{"chainID": "00000000"}'
I tested it and it should be:
```suggestion
./bin/run endpoint:invoke interoperability_getChainAccount '{"chainID": "00000000"}'
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To verify that the account was created successfully, request the `interoperability_getChainData` endpoint from a sidechain node.
```suggestion
To verify that the account was created successfully, request the `interoperability_getChainAccount` endpoint from a sidechain node.
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    "method": "interoperability_getChainData",
```suggestion
    "method": "interoperability_getChainAccount",
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +//TODO: Add example output
```suggestion
.A newly registered mainchain account on the sidechain
[source,json]
----
{
  "lastCertificate": {
    "height": 0,
    "timestamp": 0,
    "stateRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "validatorsHash": "36d3f20ea724a9708ead8b00e52c68d9188f1655e057bb523b19db35271d9073"
  },
  "name": "lisk_mainchain",
  "status": 0
}
----
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +=== Check the mainchain channel
Here's an example for getting the mainchain channel:

```
╰─ ./bin/run endpoint:invoke interoperability_getChannel  '{"chainID": "04000000"}' --pretty                                                                              ─╯
{
  "messageFeeTokenID": "0400000000000000",
  "outbox": {
    "appendPath": [
      "4d48ae83b249d1b409d2d7f1ae18792e7aeb15f647bd8a607c6639723a76a487"
    ],
    "root": "4d48ae83b249d1b409d2d7f1ae18792e7aeb15f647bd8a607c6639723a76a487",
    "size": 1
  },
  "inbox": {
    "appendPath": [],
    "root": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "size": 0
  },
  "partnerChainOutboxRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "minReturnFeePerByte": "1000"
}
```

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +=== Check the mainchain validators
Here's an example of getting the mainchain validators:

```
╰─ ./bin/run endpoint:invoke interoperability_getChainValidators '{"chainID": "04000000"}' --pretty                                                                       ─╯
{
  "activeValidators": [
    {
      "blsKey": "817cdb74e2136473f579ec7c5ff341e98a36a7ebfd1baadded8fbb315fcda6e77fd73f2132be39a018fcc3ae10b4a0e6",
      "bftWeight": "1"
    },
    {
      "blsKey": "830b156d85886dc0ea00cf76643030b82b4b80660a99e6b38386cd3774b8f1252f243a5ae2b38df915b1f71d5f5dfda3",
      "bftWeight": "1"
    },
    {
      "blsKey": "832d2cdd741b0df3f80311ed90deec394c13ed05da115d3c1fc135c96556911c6b00592451de0ab37296417559852080",
      "bftWeight": "1"
    },
    {
      "blsKey": "8394e9cfa7c81ff453ea93e50aca110dc1bb823b2681d8b7900787abd207a6268b34ff7d95e0f60530e05e45607a924e",
      "bftWeight": "1"
    },
    {
      "blsKey": "851d06def623bafccf24911d7baac97dbbdfdd3d9ebef92a912bbb335223e9f73e111ed181fb46bd5fd31044820246de",
      "bftWeight": "1"
    },
    {
      "blsKey": "85657021983a5019c8bd7461bbe04b830291d1094e26534131770b14dd3a88768a6ee57a6324bb8fa726f7c24d3f4507",
      "bftWeight": "1"
    },
    {
      "blsKey": "859a15723bc6fbef835069e843cc6f8a8221ffded4e9d2455b5520f63538775a5de66501e514a1c37d85df1c5092c418",
      "bftWeight": "1"
    },
    {
      "blsKey": "86896756d01d6c5b03f23647d7bce1cdab601ae8adb20d86614d13aaaa0e40a6bb8e524a4637d47cfc4bb1cece538862",
      "bftWeight": "1"
    },
    {
      "blsKey": "877a80b466c2090b917726b305c6f3861aea2c7e8ae9d9653fe5b871b2873d8a045643e202c007c927f9c90d65946d68",
      "bftWeight": "1"
    },
    {
      "blsKey": "87e74f2352400144080e849248c668e16da593c1d661a11ee20d5c31f149ec546729f93950b673b66dea6a33c9260d78",
      "bftWeight": "1"
    },
    {
      "blsKey": "8824e9c41ead5ee18e5fe71709f100351a9724320b7c444b0f14fa5e8f877470872edb58533442c933ee97fae8dba785",
      "bftWeight": "1"
    },
    {
      "blsKey": "897597d4dc645d4aad51246ed1d9d6b0c8f81bd1809fa9106ce367a791f0b98151bfa4b49b1251d6b307240ba1dad106",
      "bftWeight": "1"
    },
    {
      "blsKey": "89ffe19409b06f1e7854a9a5512b0d045a4ec696dc74b7d7d33117c9a8e1cfd68e185b09ae276d1a1bc3942395eb4dce",
      "bftWeight": "1"
    },
    {
      "blsKey": "8ad40d292e82ffaf9f75517b03df7b5693adba8b0f1654791de0a92a3ab0bfb26bf7d90b4cfed334d5480c329ad81614",
      "bftWeight": "1"
    },
    {
      "blsKey": "8adb937e0050d9fcf66321e2b55bc89f76592f359a07559e76c2e0cebc4c1611feb852d9f9172b71dc970a4766f9c935",
      "bftWeight": "1"
    },
    {
      "blsKey": "8aeba1cc038ad2cf1ba6ae1479f293f1e3c074369c3afe623e6921ac4cd6c959647ca85fe197228c38dda1df18812d32",
      "bftWeight": "1"
    },
    {
      "blsKey": "8b517672ecb3b38a766baedd0cedd7a0f2f2a568c067ac7b75087452c7f879c68951661e82cc2e2d1224f57b24fd0874",
      "bftWeight": "1"
    },
    {
      "blsKey": "8c43fcdeed68cefc70e02af16b5d18938f12d6a994d0ceb1519a0bfdba07ebaa3b92cd64204f411f501defaa5bce0a98",
      "bftWeight": "1"
    },
    {
      "blsKey": "8c6a9cc624212b23d5e4afc935db990b99b2f6a46390b9819ec4c34e4da73ceb49ce247eadacddb39a874b5404ca8982",
      "bftWeight": "1"
    },
    {
      "blsKey": "8d4298f04a38dd65f2b8ba59276d8da350aaf08f2d5f8101f1d23001394f74389a8c7339b1ba4a9167ca663de4b36c28",
      "bftWeight": "1"
    },
    {
      "blsKey": "8e6b900d97becb167b6182f815a4c50797538d221b5fef9d0eaeba0771560f8ec5b78e1bd9f466a823c02cead6b00006",
      "bftWeight": "1"
    },
    {
      "blsKey": "8ed44b95d761d3534ea609c7a015f465f9829a0d68c5efb04d7a2043b6be5ebc175c52277b4bb064c727018164b3e41e",
      "bftWeight": "1"
    },
    {
      "blsKey": "8edcba4c5f1c12f2d4834146cc3685d63d0ddceac3eae8aa55bfe72fc3adfae9aad0fffdc244a6d84125929add786206",
      "bftWeight": "1"
    },
    {
      "blsKey": "8f1861579e9344ed88748206a2fce1a040f974c40733fafd2a98bef813250c602bc2d3e4dd97836c638f1e8522d9304f",
      "bftWeight": "1"
    },
    {
      "blsKey": "8f3d6b429550ba9e9cab338cccb803b8553f1ab8c393089a772f8d40580683bbdef82b6972f8cafb1a6e3703f186f731",
      "bftWeight": "1"
    },
    {
      "blsKey": "8f4c1f0421fc4e84a9aaff71b15ea5387f2c2023de5764018c6260ac756ea4bcc1fa1e1b2adca51c41f33788f977202e",
      "bftWeight": "1"
    },
    {
      "blsKey": "8f558a92ea2ddb97aaf1950b2ad8cacf3bbb6df0ba6f3bb2af7e7dd2bb8c8f695af1d4cf89148f36bc7cc1b6c3c9b3e6",
      "bftWeight": "1"
    },
    {
      "blsKey": "91de8f0b3e01dcf01973a8a7ba0c787fad98e9e485b71b78ea5f4d6d684f3f8f74f25120818729bdcf19dec78beac82b",
      "bftWeight": "1"
    },
    {
      "blsKey": "921fab12f32b83338acd846c4f2e22e78d5657a9ad6e26a1b953235b837c97c1994b410fb98ed9d60043046bc49cf04b",
      "bftWeight": "1"
    },
    {
      "blsKey": "945159215901b8094983b7c457d47350031a6894ca2168bd9902de0248e11f7a7b3849820e7bbf8d12c9111df5dd0c59",
      "bftWeight": "1"
    },
    {
      "blsKey": "946f53073e217c65c31f135950827706bffc53a1714ef6476751f88e499cb2405fdbc68bffb715b94774a37c6c49b695",
      "bftWeight": "1"
    },
    {
      "blsKey": "94db4e95e0bdf2a2f2dad6fe1758d598cf39e5f5013d30812d89983560fd630e730d7f8443f8f8f7dedb2817d7199dd3",
      "bftWeight": "1"
    },
    {
      "blsKey": "94eab1c0dd071eb08efffdfc9fa4a1a084f18b155c265cea14b897f9ef8da838f061d072aec8b1fddf64d982db5383f2",
      "bftWeight": "1"
    },
    {
      "blsKey": "94f3abffbb40e97d2b024c614377a49bc02ccb96f5c39d5f5240cabed3abf71a79dfd1415819c945bd7bfbd6ce974e29",
      "bftWeight": "1"
    },
    {
      "blsKey": "962ad95f9eb8de66f40ae8650e4a1b9715db8b93082f94a999c5513b59b34ae765bbdf52525348eb2c3bfae9b74be5d0",
      "bftWeight": "1"
    },
    {
      "blsKey": "9649a2666c4397e558ac70522551fa2282bc12cb9f0efaaaeb723916050115eb6a06944047e27b2765c48a8fdc54723b",
      "bftWeight": "1"
    },
    {
      "blsKey": "964bb701671ac2ff8c74479ac55edd73425552873f62b0f0c7e806d31b97b04b3c3fce13746b9758c577fabc35569484",
      "bftWeight": "1"
    },
    {
      "blsKey": "974e9ad5b6dc8589d13f6ea588e13e2f911d274bdca25a0eaf95e78070ada24ebf055e7e96f4bc5d54d1e1ecbb88891b",
      "bftWeight": "1"
    },
    {
      "blsKey": "97ec41664e973d6c47a6eb42a71cdab2b32cab143ebbff4987ca1f21b70d2a4a31865fa63e498172ddfcdc66c375df3c",
      "bftWeight": "1"
    },
    {
      "blsKey": "981ed9e0ecefede2baabe2190da98bcda364e9cd2cdc84294104f76baa96357b208b8a46b35815ff70a2782321c7a997",
      "bftWeight": "1"
    },
    {
      "blsKey": "988b6193525235d5c772e65b777d699b5a6a2c78b9588aba6ba791cc90f8ad64d811b60db840d6335af8c1b56e64a6a8",
      "bftWeight": "1"
    },
    {
      "blsKey": "98c1650f3954150884b93926f0b9bb2895a86b7f53548b55c54a8baaf6298011dda1d4c59b0de58ff0b7049c84d4bb91",
      "bftWeight": "1"
    },
    {
      "blsKey": "a07a39359e00f2dc70586643b0192b72bf5cac12664c9b3e86196b9ff8ab42d2de0c99feaabe150a2f158bc5655af28a",
      "bftWeight": "1"
    },
    {
      "blsKey": "a13d891ddf147982e0c9a5f131e06e9839fbfbc1c2e45a0e36047420cf096c7befdb2368999f9127ae1c1351cd006360",
      "bftWeight": "1"
    },
    {
      "blsKey": "a227caf7eaccffa90c894e8338f1bf792936d3e70392970f87246c88ba8e37ac48242c6b9d94f0f34f45cca988d723a4",
      "bftWeight": "1"
    },
    {
      "blsKey": "a377f60b451ee1824e4bcef98ee59ed2d9e9e79fda80e9f9cb4d5142ec6e34c3cb2ba0b58fa9cda79ccfecf9be1944e1",
      "bftWeight": "1"
    },
    {
      "blsKey": "a3d818681e97be169c51414f692f743ffeb5fbf60478710a8dd4ab883044d2bf8b318bbf931316a30755061338cbf857",
      "bftWeight": "1"
    },
    {
      "blsKey": "a4ae34b8c356805c5a71cc7b9344eb190004733dc6ec97f2cb19249595ac2ccfd11a25ddbf455be0b17573e306c71301",
      "bftWeight": "1"
    },
    {
      "blsKey": "a4f8a7ab03605906f89a6b3e2a6091c53feae76f3a9e48593732fc027babbbfd6cf6fa5c98251f8453cb6b57fda99ced",
      "bftWeight": "1"
    },
    {
      "blsKey": "a5966288b2fcc72df1a9ec5434dd3a4120bfad14b96939591ddc3312f5d4645ac9715fc9f261ea969a96122c94e71c8e",
      "bftWeight": "1"
    },
    {
      "blsKey": "a5c327e70f2d173b3bbb1dc69e57e03bd4b32f91a8874309656cf9a364e0ab6f1b2fe76e3690981c53e32223530f9009",
      "bftWeight":  [...]

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.Deep Dive into Cross Chain Messages
Cool, yes creating an issue sounds like a plan :)

2023-03-15 10:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +//URLs
I see, maybe we can correct the places where we haven't done this intentionally since this is a long page and it will increase the visibility of content.

2023-03-15 15:11 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +./bin/run endpoint:invoke interoperability_getChainData '{"chainID": "00000000"}'
Yeah but @ishantiw pointed outthat this endpoint will change to `interoperability_getChainData`

2023-03-15 15:20 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +//URLs
I am not aware of places where it was not done intentionally. As far as i am aware this is only done for the recovery steps. But also, for me it doesn't decrease readability on the page.

2023-03-15 15:51 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +This will return a complete list of all active sidechain validators at the specified block height.
good catch, would have been too easy the other way :D I have added a link to the script and adjusted the content

2023-03-15 15:53 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Taking this into account, we decide for a `sidechainCertificateThreshold` of 65:
I didn't apply the suggestion because imho it makes it more confusing, as there is no min/max for the aggregated weight, only for the thresholds. I adjusted the content slightly to make it clearer hopefully

2023-03-15 15:59 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +This file can be generated for a specific validator with the `keys:create` CLI command, by providing the passphrase.
Mentioning the count flag is not really relevant at this point, because the default and recommended scenario is that a user manages one validator account, not many

2023-03-15 16:00 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
This is intentional, because it is not a realistic scenario that one user creates all the signatures of the sidechain validators.

2023-03-16 09:38 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node paramsCreation.ts
what exactly are the changes and why did you do them?

2023-03-16 10:12 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node mainchainRegistration.ts
I have removed the broken verification for now, maybe we can revisit this later

2023-03-16 10:26 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +.Deep Dive into Cross Chain Messages
I have created a corresponding issue here: https://github.com/LiskHQ/lisk-docs/issues/1735

2023-03-16 11:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/communication.adoc
> +* [x] What happens, if a CCM cannot be transmitted/executed successfully?
```suggestion
====
On this page, we dive deeper into how cross-chain communication works in the Lisk ecosystem, by describing the different components and the general processes of how state changes are executed across chains in the Lisk ecosystem.

Specifically, you'll learn about:

* [x] What are cross-chain messages (CCMs)?
* [x] What are cross-chain updates (CCUs)?
* [x] When a cross-chain transaction is submitted, what are the exact steps involved, to induce the corresponding state changes on the receiving chain?
* [x] What happens, if a CCM cannot be transmitted/executed successfully?
```

2023-03-16 11:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +This file can be generated for a specific validator with the `keys:create` CLI command, by providing the passphrase.
Alright, I think we should at least mention the command about how they can create the `keys.json` to aid the reader. Alternatively, we can refer to the CLI command reference page as well:

https://liskhq.github.io/lisk-docs/lisk-sdk/v6/client-cli.html#keyscreate

2023-03-16 11:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node paramsCreation.ts
Defined constants in the same file, added lines for both IPC and WS client etc.

2023-03-16 11:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
IMHO we should either go with one validator on both the sidechain and mainchain registration process or use the list of validators we create on lines 166-176. Having a single validator here will lead to an error while trying out the guide. I think even with one validator, we can send a Register Sidechain and later a Register Mainchain transaction so, it should be in sync.

2023-03-16 11:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node mainchainRegistration.ts
Thanks, to aid the reader further, I guess we can leave a TIP somewhere with the aforementioned link suggesting that if they want to create the mainchain params using a single script, they can use this [file](https://lightcurve.atlassian.net/wiki/pages/viewpage.action?pageId=6127961&pageVersion=37&preview=/6127961/8094237/prepare_mainchain_reg_params.ts):

2023-03-16 13:32 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node paramsCreation.ts
Ok, I updated the script accordingly 👍

2023-03-16 13:42 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +This file can be generated for a specific validator with the `keys:create` CLI command, by providing the passphrase.
I have added the link 👍

2023-03-16 13:46 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
As this process happens in a decentralized environment, it is in fact not possible that a single person tried out this whole guide successfully, except of a development network, which is centralized. And there is no point to explain the artificial scenario of how to register a sidechain in a centralized network.

The normal scenario is that it is a decentralized network, and the process of mainchain registration is therefore decentralized as well, this is what the guide should explain and emphasize. If, after reading the guide, this particular part is still unclear to you, maybe we should improve the section explaining this particular topic.

2023-03-16 13:50 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node mainchainRegistration.ts
I don't think this file is public. But I created a new issue to add a signature verification at a later point here: https://github.com/LiskHQ/lisk-sdk-examples/issues/308

2023-03-16 14:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
I see, I would improve the distinction between these two perspectives

- The perspective of a mainchain node operator.
- The perspective of a sidechain node operator.

The content itself is valid, however, we might need to emphasize on the scenario you mention. Maybe we can separate the existing content in two separate guides, One for mainchain registration and the other one for sidechain registration. Since each node operator might not need info regarding the other one.

2023-03-16 14:03 UTC, TalhaMaliktz approved these changes
Thanks, I have left a comment on our discussion about scenarios. Other than that all looks great 😄 🎉

2023-03-16 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
From perspective of a normal mainchain node operator, there is nothing special to do. Also, not every sidechain node operator needs to do anything, only sidechain validators need to take action here. So not really sure what to improve, but if you agree we can improve it later in another issue :)

2023-03-16 14:18 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +node validatorSignatures.ts
Alright, thanks :)

2023-03-16 14:21 UTC, merged