Update enable forging guide
LiskArchive/lisk-legacy-docs pull request #1654
Opened 2022-11-15 16:32 UTC by Tschakki

Closes #1531

2023-01-25 08:47 UTC, TalhaMaliktz requested changes
Thanks for updating the understand blockchain page. I have left a few suggestions for you. 😊

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  image::intro/node-network.png[Side chain's node network, 800 ,align="center"]
I just made some alignment adjustments and have uploaded a high res image:

![node-network](https://user-images.githubusercontent.com/13951043/214268228-08b0305e-0f9a-4df5-9fe2-2f9176a27804.png)

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +image::understand-blockchain/3-domains.png["3-domains of blockchain", 500,align="center"]
Please add the high res image:

![3-domains](https://user-images.githubusercontent.com/13951043/214268566-a0964397-b4ba-4b62-ba36-9b9608247c86.png)

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  image::architecture.png[lisk-framework-architecture, 700 , align="center"]
Thanks for updating the image, considering your changes and the prior feedback on this diagram, I have made slight adjustments to refine the image.

![architecture - Page 1](https://user-images.githubusercontent.com/13951043/214320174-6f1131fb-778b-497c-9d29-8523b71e7ae0.png)

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A *sidechain application* (or, in short: *sApp*) refers to a software that contains a lisk based <<sidechain-client,sidechain client>>, a <<middleware,middleware>> and a <<ui,user interface>>.
```suggestion
A *sidechain application* (or, in short: *sApp*) refers to a software that contains a lisk based <<sidechain-client,sidechain client>>, a <<middleware,middleware>>, and a <<ui,user interface>>.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A middleware can prepare, aggregate and enrich data from the blockchain network, so it can be easily used and digested later by the application frontend.
```suggestion
A middleware can prepare, aggregate, and enrich data from the blockchain network, so it can be easily used and digested later by the application's frontend.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Although a middleware is *optional*, it will mst probably become essential for bigger blockchain applications in the long run.
```suggestion
Although a middleware is *optional*, it will most probably become essential for bigger blockchain applications in the long run.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Use your preferred exising Frameworks to develop an accessible and intuitive UI for users which fits your individual use case.
```suggestion
Use your preferred existing frameworks to develop an accessible and intuitive UI for users which fits your individual use case.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A sidechan client relies heavily on its state machine to mutate the state of a sidechain.
```suggestion
A sidechain client relies heavily on its state machine to mutate the state of a sidechain.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In the context of the Lisk blockchain, a *key-value-store* represents the current state of the blockchain, containing all on-chain data of the blockchain.
```suggestion
In the context of the Lisk blockchain, a *key-value store* represents the current state of the blockchain, containing all on-chain data of the blockchain.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Sidechain developers can create their own custom business logic for the sidechain here by creating their own modules or reuse existing ones, and registering them to the client.
```suggestion
Sidechain developers can create their own custom business logic for the sidechain by creating their own modules or reusing existing ones, and registering them to the client.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +However, the Genesis configuration and the configuration for Modules must be the same across the network of each a sidechain client.
```suggestion
However, the Genesis configuration and the configuration for Modules must be the same across the network of each sidechain client.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The communication architecture of a sidechain client allows internal application components and external services to communicate to the client via various channels.
```suggestion
The communication architecture of a sidechain client allows internal application components and external services to communicate with the client via various channels.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
Line 73:

`A blockchain footnote:blockchain_footnote[For a general introduction to the blockchain, please check out the introduction page xref:{url_what_is_blockchain}[What is blockchain].] is a chain of interconnected blocks on various nodes distributed across a P2P network.`

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The sidechain client is the central piece of software that is needed to establish and maintain a blockchain network between many different independent servers.
```suggestion
The sidechain client is the fundamental software that is needed to establish and maintain a blockchain network between various independent servers.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Servers with running sidechain clients are called *sidechain nodes* in this context.
```suggestion
These servers with running sidechain clients are called *sidechain nodes*.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Check out the guide xref:{url_build_index}[] for more information on the topic.
Re-arranged sentences to complement earlier sentences:

```suggestion
One of Lisk's offerings: the xref:{url_lisk_sdk}[] provides a lot of helpful tools to build a fitting sidechain client for your application.
Check out the guide xref:{url_build_index}[] for more information on the topic.
Furthermore, Lisk also offers the blockchain client to run Lisk Mainchain which is called xref:{url_lisk_core}[].
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +xref:{url_lisk_service}[Lisk Service] is an enriched node API that provides a convenient endpoints for sending or getting data from the Lisk blockchain.
```suggestion
With xref:{url_lisk_service}[Lisk Service], Lisk provides a ready-to-use middleware, which can be easily configured for any sidechain application.
Lisk Service is an enriched node API layer that provides a convenient set of endpoints for sending or getting data from the Lisk blockchain.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Any UI that is able to communicate over HTTP or WS to a server will work.
```suggestion
Any UI that is able to communicate over HTTP or WS protocol will work.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +* *Engine* layer (includes the <<net-domain,network- >> and <<con-domain,consensus domains>>)
```suggestion
* *Engine* layer (includes the <<net-domain,network >> and <<con-domain,consensus domains>>)
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +.Architecture of a Lisk sidechain client
I think this is still a sidechain application, considering that we also have a web/mobile application which is the UI part of the application. Also, we say that its a sApp's architecture on line 187.
```suggestion
.Architecture of a Lisk sidechain application
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In the context of the Lisk blockchain, a *transition* of states is triggered through *blocks* and their containing *transactions* which are added to the blockchain.
```suggestion
In the context of the Lisk blockchain, a *transition* of the state is triggered through *blocks* and the *transactions* present in those blocks; the addition of a block transits the state of the blockchain.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +*Modules* facilitate the state changes states in a sidechain client.
```suggestion
*Modules* facilitate the state changes in a sidechain.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  * Define logic that is executed per block footnote:block_footnote[For more information about blocks, check out xref:{url_protocol_blocks}[Blocks].]
```suggestion
* Define logic that is executed per block footnote:block_footnote[For more information about blocks, check out xref:{url_protocol_blocks}[Blocks].].
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  Each blockchain node is an instance of a particular sidechain and keeps the data on various data stores inside.
```suggestion
Each blockchain node is an instance of a particular sidechain and each node keeps its data on various data stores.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  This data contains the following two types: on-chain and off-chain.
```suggestion
This data is of the following two types: on-chain and off-chain.
```

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +The communication protocol of a sidechain client can be changed through xref:{url_advanced_architecture_config}[configurations].
The URL takes you to v5 docs, I think it should go to v6 docs.

2023-01-25 08:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +== Sidechain applications vs. dApps
Why have we commented this section?

2023-01-25 12:13 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +== Sidechain applications vs. dApps
I commented it, because we didn't update this section yet, it is also indicated by the TODO above.
Once the content is updated we can add it back in :)

2023-01-25 12:26 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Servers with running sidechain clients are called *sidechain nodes* in this context.
```suggestion
Servers with running sidechain clients are called *sidechain nodes*.
```

2023-01-25 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In the context of the Lisk blockchain, a *transition* of states is triggered through *blocks* and their containing *transactions* which are added to the blockchain.
```suggestion
In the context of the Lisk blockchain, a *transition* of the state is triggered through *blocks* and the *transactions* present in those blocks; i.e. every new block that is added to the blockchain mutates the state of the blockchain.
```

2023-01-31 20:48 UTC, shuse2 requested changes

2023-01-31 20:48 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +There are many possibilities to create the transaction, for example: {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
FYI: desktop can create a transaction, but it cannot generate validator keys. 
Also, dashboard plugin is a development tool, so no need to mention here

2023-01-31 20:48 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +== Safely enabling block generation on another node
you could also explain `generator_estimateSafeStatus` endpoint as well

2023-01-31 20:48 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +There are various different services and tools to stake tokens, for example: {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
Here, also no need to mention dashboard plugin

2023-01-31 20:48 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +IMPORTANT: The *minimum validator weight required* to be selected as a block generator is 1000 LSK in the Lisk Mainnet.
we could mention staking must be done in multiple of 10 LSK?

2023-01-31 20:48 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +Sidechain node::
In general for this page, it only applies to sidechain who uses our PoS module

2023-02-01 12:57 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +There are many possibilities to create the transaction, for example: {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
True, I removed the whole statement now

2023-02-01 13:10 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +There are various different services and tools to stake tokens, for example: {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
removed mention of dashboard and moved statement below where it fits the context.

2023-02-01 13:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +IMPORTANT: The *minimum validator weight required* to be selected as a block generator is 1000 LSK in the Lisk Mainnet.
Good point, I added this information under the section "(Un-)Staking"

2023-02-01 13:19 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +Sidechain node::
I added this information now to the page summary on top of the page

2023-02-01 13:39 UTC, TalhaMaliktz requested changes
Looking good already :)

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/tutorial/lns/1-blockchain.adoc
> +:url_guide_setup_init: build-blockchain/create-sidechain-app.adoc#initializing-a-new-blockchain-application
```suggestion
:url_guide_setup_init: build-blockchain/create-sidechain-app.adoc#initializing-a-new-sidechain-application
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/tutorial/nft.adoc
> +:url_build_bapp: build-blockchain/create-sidechain-app.adoc#bootstrapping-a-new-blockchain-application-with-lisk-commander
```suggestion
:url_build_bapp: build-blockchain/create-sidechain-app.adoc#bootstrapping-a-new-sidechain-application-with-lisk-commander
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
>  :url_advanced_schemas: understand-blockchain/sdk/codec-schema.adoc
Please also remove the following in the relevant files.
```suggestion

```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  :url_understand_sdk_modules: understand-blockchain/sdk/modules-assets.adoc
```suggestion

```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +Import the validator keys which were generated in step <<creating-the-validator-keys>> into the node.
```suggestion
== Import the validator keys

After creating the validator keys as suggested in the  <<creating-the-validator-keys>> section, the next step is to import them into the node.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +. Ensure the node is **fully synchronized** with the network.
How can this be done? Is there any information available for that anywhere in the Lisk ecosystem?

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +This is achieved by choosing a unique *validator name*, and posting a corresponding "Register Validator" transaction to the network.
```suggestion
This is achieved by choosing a unique *validator name* and posting a corresponding "Register Validator" transaction to the network.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +To do so, use the command xref:{url_sdk_cli_keyscreate}[keys create].
```suggestion
To do so, use the command xref:{url_sdk_cli_keyscreate}[keys:create].
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +It will be required everytime to enable block generation, in order to decrypt the generator keys in the node.
```suggestion
It will be required every time to enable block generation, in order to decrypt the generator keys in the node.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +To increase security, this key is different to the key used to sign transactions in the network{fn_lip44}.
```suggestion
To enhance security, the `generatorKey` is different from the key used to sign transactions in the network{fn_lip44}.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +The parameters 2, 3, 4 are all generated in step <<creating-the-validator-keys>>.
```suggestion
The parameters mentioned in 2, 3, and 4 are all generated in the step <<creating-the-validator-keys>>.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +Copy the transaction in binary format that was created in the previous step and post it to the node.
```suggestion
Copy the transaction in the binary format that was created in the previous step and post it to the node.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +The new validator name should be displayed in the response, along with the corresponding address and other public information about this particular validator.
```suggestion
The new validator's name should be displayed in the response, along with the corresponding address and other public information about the particular validator.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +After the validator keys are imported to the node, it is possible to verify that the import worked as expected with th following command:
```suggestion
After the validator keys are imported to the node, it is possible to verify that the import worked as expected with the following command:
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +There are some situation though, where it is needed to get the seed hash onion back, for example when xref:{url_run_block_generation_move}[moving from one node to another].
```suggestion
There are some situations though, where it is needed to get the seed hash onion back, for example, when xref:{url_run_block_generation_move}[moving from one node to another].
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +A good way to check what concrete validator weight is required to reach an active position, just check the validator weights of the currently 101 active validators.
```suggestion
A good way to check the exact validator weight required to reach an active position is to just check the validator weights of the currently active 101 validators.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +NOTE: Please note, that even if you have not enough validator weight to be in one of the active validator positions, there is still a chance each round to be selected as one of the two random validat
```suggestion
NOTE: Please note, that even if you do not have enough validator weight to be an active validator, there is still a chance for you in each round to be selected as one of the two random validators.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +To be considered for the random selection, a validator just needs to have a weight equal or greater to the minimum validator weight of the network.
```suggestion
To be considered for the random selection, a validator just needs to have a weight equal to or greater than the minimum validator weight of the network.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +To verify the concrete weight of your or any other validator, it is possible to directly request the required information via RPC endpoint.
```suggestion
To verify the concrete weight of your or any other validator, it is possible to directly request the required information via the RPC endpoint.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +There are many possibilities to create the transaction, for example: {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
```suggestion
There are various ways to create the transaction, for example, by using {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +This is also calld *self-staking*.
```suggestion
This is also called *self-staking*.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +== (Un-)Staking
I think the readability will increase if we separate the staking and un-staking here and do something like this:

- Staking
  - Create a Stake transaction
  - Send the Stake transaction
- Un-staking 
  - **Show how to un-stake and refer to the sending a transaction part** 
  - Unlocking tokens after un-stake
      - Checking for pending tokens ready to be unlocked
      - Create the Unlock transaction
      - Send the Unlock transaction

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +** `amount`: Amount of tokens to (un-)stake.
I feel it is easier to read stake and un-stake and their variations instead of (un-)stake so maybe we can use these terms in the text separately. 
```suggestion
** `amount`: Number of tokens to stake or un-stake.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +That means, the tokens used for staking stay in the account of the staker, but while they are used for staking, they cannot be used for any other purposes like for example token transfers.
```suggestion
That means, the tokens used for staking stay in the account of the staker, but while they are used for staking, they cannot be used for any other purposes for example token transfers.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +Staking is particulary important for validators, because they need to stake a significant amount of their own tokens for their validator account.
```suggestion
Staking is particularly important for validators because they need to stake a significant number of their own tokens for their validator account.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +Second, a lot of validators are rewarding stakers with a share of their block rewards, creating a financial incentive for users to stake their unused tokens and receive regular payout as reward.
```suggestion
Apart from self-staking, Lisk also incentivizes its users to stake their tokens for a different validator as well.
Staking for the most trustful and helpful validators in the community increases the decentralization and security of the network.
It also allows stakers to earn rewards as a lot of validators reward stakers with a share of their block rewards. 
This creates a financial incentive for users to stake their unused tokens and receive regular payouts as a reward.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +There are various different services and tools to stake tokens, for example: {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
```suggestion
There are various services and tools to stake tokens, for example {url_lisk_wallet}[Lisk Desktop^], xref:{url_sdk_elements}[Lisk Elements], the node CLI or the Dashboard plugin.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +* `selfStake` is the amount of tokens the validator staked for themselves, and
```suggestion
* `selfStake` is the number of tokens the validator staked for themselves.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
Considering the aforementioned definition: maybe we can remove this?

Stake from others = 250
self-stakes = 20
totalStakeReceived = 270
10% of 270 will be 27

```suggestion

```
or we can say something like
```suggestion
NOTE: The percentage of the self-stake needs to be at least 10% of the total validator weight of a particular validator, to be eligible to generate new blocks in the network.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
I would also suggest to re-add the definition of **totalStakeRecieved** in the glossary as well, as I think, self-stake, totalStakeRecieved, and validator weight are three different concepts. Please consider the following

https://docs.google.com/presentation/d/11wA1W1oP84yRSsNmii1MRYMgwWXcFTOWu5oBVpobat4/edit#slide=id.g33f2b95617_0_25

https://docs.google.com/presentation/d/1vL7xEGDCtPzVUy31V2B_x7Z64u9cHPH-PtGw_6LFYqQ/edit#slide=id.g1fe213ee9b7_2_102

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +* `stakes`: An array items with the following two properties:
```suggestion
* `stakes`: An array of items with the following two properties:
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +If you wish to check the amount of tokens that are ready to be unlocked in an account, query the `pos_getPendingUnlocks` RPC endpoint:
```suggestion
If you wish to check the `amount` of tokens that are ready to be unlocked in an account, query the `pos_getPendingUnlocks` RPC endpoint:
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +* `amount`: Amount of unstaked tokens.
```suggestion
* `amount`: Number of unstaked tokens.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +Next, post the transaction to the node, e.g. by using the node CLI like explained below:
```suggestion
Next, post the transaction to the node, e.g. by using the node CLI as explained below:
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +. If block generation is enabled for a validator for the **first time**, check out the dedicated guide xref:{url_run_validator}[].
```suggestion
. To enable block generation for a validator for the **first time**, check out the dedicated guide: xref:{url_run_validator}[].
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +To prefill the validator info data automatically, add the flag `--use-status-value` to the `generator:enable` command.
What does this data used to pre-fill mean? Is this dummy data? Where does it come from?

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +* `maxHeightPrevoted`: Validators largest prevoted height for a block.
```suggestion
* `maxHeightGenerated`: Validator's largest previously generated height.
* `maxHeightPrevoted`: Validator's largest prevoted height for a block.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +Sometimes it is desired or necessary to move to a new / different node, to generate blocks with a particular validator.
```suggestion
Sometimes it is desired or necessary to move to a new/different node, to generate blocks with a particular validator.
```

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +=== Start the blockchain application
This should be step 1 and should come before the "Creating the validator keys"

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +. `proofOfPossession`: The cryptographic proof that the validator owns the corresponding private key to the BLS key.
Since we have the property `blsProofOfPosession` in the keys.json file, we should tell the reader that the value of `proofOfPossesion` will be the value of `blsProofOfPosession` in the keys.json file.

2023-02-01 13:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +=== Send the transaction
Since we create a new account, I think it is pertinent to mention that this will return the `Insufficient Balance` error, so please add a step before this to send some tokens to the new account and reference to the `token_getBalance` endpoint for checking balance.

2023-02-01 14:38 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +=== Send the transaction
I don't think we should add this here, as it can be assumed that a person already own an account with enough tokens to perform the required steps. 
Maybe I can add this as a requirement for this guide above

2023-02-01 14:43 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +To prefill the validator info data automatically, add the flag `--use-status-value` to the `generator:enable` command.
this is no dummy data.
The validator info data is stored in the node and with this flag it is possible to directly use the values form the node database. It is the most convenient and safe way to use this flag when enabling block generation.

2023-02-01 14:57 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
I don't see how the statement in the note is incorrect. 
In your example, the validator weight will be `200`,  which is ten times the self-stake
To use all stakes, the validator would need to increase the self-stake to 30, in that case the weight would be `280` 
10% of this is `28`, so the validators self-stake is here more than 10%

2023-02-01 15:16 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +. Ensure the node is **fully synchronized** with the network.
I have added more information here now

2023-02-01 15:23 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
I still don't like having the terms in the glossary, because they are not relevant for anything else, than calculating the validator weight. I don't think we need to refer to it often. And if, I think it is better to link to the validator weight explanation, and not duplicating the content in the glossary.

2023-02-01 15:30 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +=== Start the blockchain application
For generating the keys file, the node doesn't need to be running :)
But acutally, it can be assumed that for most cases the node is running already, I have also added it to the prerequisites of the guide, so I will actually remove the section about starting the ndoe now

2023-02-01 15:35 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +. `proofOfPossession`: The cryptographic proof that the validator owns the corresponding private key to the BLS key.
good catch, added the info now

2023-02-02 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +== (Un-)Staking
Very good suggestion! I updated the structure accordingly, only difference is I moved Unlocking one level up in the structure, so that it is less nested.

I also added a new section at the top "Checking the current stakes of an account" and moved section "How to retrieve the current weight of a validator" from validator page to here, because i think it fits more.

2023-02-02 13:59 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +== Safely enabling block generation on another node
i have added a new section below regarding this topic

2023-02-03 21:05 UTC, shuse2 approved these changes
Some minor points but looks good to me

2023-02-03 21:05 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +To generate new blocks on a node, it is required to register as a validator.
```suggestion
To generate new blocks on a network, it is required to register as a validator.
```

2023-02-03 21:05 UTC, shuse2 commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +Copy the transaction in the binary format that was created in the previous step and post it to the node.
```suggestion
Copy the transaction in the hex format that was created in the previous step and post it to the node.
```

2023-02-06 10:14 UTC, TalhaMaliktz requested changes
Thank you. Looks good, just minor suggestions :).

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +This is particularly relevant for nodes who have been set up recently, because they might not have catched up with the current state of the network, yet.
```suggestion
This is particularly relevant for nodes who have been set up recently, because they might not have caught up with the current state of the network, yet.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +To verify that you node is fully synched, request the `system_getNodeInfo` endpoint.
```suggestion
To verify that your node is fully synched, request the `system_getNodeInfo` endpoint.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +=== Send the transaction
Adding it to the pre-requisite is good enough. However, please add a link to the `token_getBalance` endpoint as well. The endpoint will be added very soon as there is an issue for it.

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +* [x] ... unlock tokens after un-stake
Since we have a similar pattern in previous guides.

```suggestion
* [x] Retrieve the stakes of an account.
* [x] Stake tokens for a validator.
* [x] Un-stake tokens.
* [x] Unlock tokens after un-stake.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +On this page, you'll learn how to (un-)stake tokens for a validator on a blockchain that uses the Lisk PoS module, like the Lisk Mainnet.
```suggestion
On this page, you'll learn how to stake and un-stake tokens for a validator on a blockchain that uses the Lisk PoS module, like the Lisk Mainnet.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
I see, in that case, maybe we can use the second suggestion or something similar to it as I think this note should be more descriptive.

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +To verify the concrete weight of your or any other validator, it is possible to directly request the required information via the RPC endpoint.
```suggestion
To verify the concrete weight of your validator account or any other validator, it is possible to directly request the required information via the RPC endpoint.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +An account performing a staking is also called *staker*.
```suggestion
An account performing staking is also called a *staker*.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +Next, send the transaction like described in <<send-the-stake-transaction>>.
```suggestion
Next, send the transaction as described in <<send-the-stake-transaction>>.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
In that case, please add footnotes for the relevant lips' sections for these teminologies.

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +To prefill the validator info data automatically, add the flag `--use-status-value` to the `generator:enable` command.
```suggestion
To prefill the validator info data as stored on the node, automatically, add the flag `--use-status-value` to the `generator:enable` command.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +It can happen that a validator loses their <<validator-info-data>>, for example if their server crashes, or if general access to the node is lost.
```suggestion
A validator can lose their <<validator-info-data>>, for example, if their server crashes, or if general access to the node is lost.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +If you overestimate, you will never break the Lisk BFT protocol -  in worst case, you will lose a few block rewards.
```suggestion
If you overestimate, you will never break the Lisk BFT protocol -  in the worst case, you will lose a few block rewards.
```

2023-02-06 10:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +finalized, and that the finalized block header timestamp is greater than the last active height: `finalizedBlock.header.timestamp > timeShutdown`
```suggestion
. Start a new node with forging deactivated and synchronize with the Lisk blockchain until there is a block: `finalizedBlock`.
The finalized block header timestamp should be greater than the last active height: `finalizedBlock.header.timestamp > timeShutdown`.
```

2023-02-06 12:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +=== Send the transaction
I am not sure I understand your suggestion, should i mention the endpoint in the prerequisites, is that what you meant? Also, I am not sure where you want me to link to, and what issue you are referring to, please elaborate

2023-02-06 12:31 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
Imho my original note is clearer 😅

2023-02-06 13:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/staking.adoc
> +NOTE: This definition implies that *at least 10% of the validator weight always consist of self-stakes*.
I added a footnote to lip23 now, let me know if there are any other relevant LIPs to mention here concerning the topic

2023-02-06 13:19 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +finalized, and that the finalized block header timestamp is greater than the last active height: `finalizedBlock.header.timestamp > timeShutdown`
```suggestion
. Start a new node with forging deactivated and 
. Synchronize with the Lisk blockchain until there is a finalized block: `finalizedBlock` with a block header timestamp greater than the last active height: `finalizedBlock.header.timestamp > timeShutdown`.
```

2023-02-07 08:24 UTC, TalhaMaliktz approved these changes
Thank you! LGTM 🎉

2023-02-07 09:30 UTC, merged