Update core docs
LiskArchive/lisk-legacy-docs pull request #1657
Opened 2022-11-28 11:31 UTC by Tschakki

Closes #1561 

Removes outdated links to Core docs

2022-11-29 10:30 UTC, chris529 reviewed
Looks very good, only a few minor points 👍

2022-11-29 10:30 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Other key features include the ability to use a self-controlled node to perform actions on the Lisk blockchain, for example, with Lisk Desktop, and the opportunity to forge new blocks, (for active de
```suggestion
Other key features include the ability to use a self-controlled node to perform actions on the Lisk blockchain, for example, with Lisk Desktop, and also the opportunity for active delegates to forge new blocks.
```

2022-11-29 10:30 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
>  The most convenient way to manage your account is to use a user interface, such as Lisk Desktop.
```suggestion
The most convenient way to manage your account is to employ a user interface, such as Lisk Desktop.
```

2022-11-29 10:30 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
>  The most convenient way to manage your account is to use a user interface, such as Lisk Desktop.
imho I think the above line reads better, instead of using 2 instances of 'use' so close together.

2022-11-29 10:30 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/forging.adoc
> +If you would like to completely stop forging without being punished by the network, make sure to unvote yourself.
```suggestion
If you would like to stop forging completely without being punished by the network, make sure to unvote yourself.
```

2022-11-29 13:00 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Other key features include the ability to use a self-controlled node to perform actions on the Lisk blockchain, for example, with Lisk Desktop, and the opportunity to forge new blocks, (for active de
I think it is OK not to mention active delegates here, because at this stage the reader might not know yet what an active delegate is, so it can be confusing. We have other guides later which go into detail about how to enable block generation, this is why I prefer to just remove this info here.

2022-11-29 13:19 UTC, chris529 commented on docs/modules/ROOT/pages/intro/lisk-products.adoc
> +Other key features include the ability to use a self-controlled node to perform actions on the Lisk blockchain, for example, with Lisk Desktop, and the opportunity to forge new blocks, (for active de
Ah ha...OK, good point Mona, then that makes sense...understood 👍

2022-11-29 13:43 UTC, chris529 reviewed
Looks great! Just 2 very minor points..👍

2022-11-29 13:43 UTC, chris529 commented on docs/modules/ROOT/pages/glossary.adoc
>  Initialization was originally only required for the v2 chain as legacy addresses, generated from the first eight bytes of the public key, were used in older versions of the protocol.
```suggestion
Initialization was originally only required for the v2 chain, as legacy addresses generated from the first eight bytes of the public key were used in older versions of the protocol.
```

2022-11-29 13:43 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For example use the `lisk-client` package and write a small script which invokes the `reportMisbehavior:authorize` action on the node.
```suggestion
For example, use the `lisk-client` package and write a small script that invokes the `reportMisbehavior:authorize` action on the node.
```

2022-11-29 14:53 UTC, chris529 approved these changes
LGTM! 👍

2022-11-30 13:48 UTC, TalhaMaliktz requested changes
Looks Good! Just a few suggestions.

2022-11-30 13:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The Mainnet is a fully developed functional and independent blockchain, running on its own network and using its own protocol and technology.
```suggestion
The Mainnet is a fully developed, functional, and independent blockchain, running on its own network and using its own protocol and technology.
```

2022-11-30 13:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
Do we need this?
```suggestion
//TODO: Add link back once the page is updated
```

2022-11-30 13:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For example, use the `lisk-client` package and write a small script that invokes the `reportMisbehavior:authorize` action on the node.
```suggestion
For example, use the `lisk-client` package and write a small script that invokes the `reportMisbehavior:authorize` endpoint on the node.
```

2022-11-30 13:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> += How to enable the "Report Misbehavior" plugin
Shouldn't this be added to the `nav.adoc` as well?

2022-11-30 15:48 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> += How to enable the "Report Misbehavior" plugin
No. It just moved the location from core docs to here, but the content is not updated yet, so it shouldn't be added to `nav.adoc`

2022-11-30 15:49 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For example, use the `lisk-client` package and write a small script that invokes the `reportMisbehavior:authorize` action on the node.
this page isn't updated yet, just moved (not included in nav)

2022-11-30 15:50 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
yeah. link is only removed temporarily, so we need a todo here as reminder

2022-11-30 15:58 UTC, TalhaMaliktz reviewed
LGTM 😊

2022-11-30 15:59 UTC, TalhaMaliktz approved these changes

2022-12-01 12:48 UTC, merged