Update create a new plugin guides - Closes 1523
LiskArchive/lisk-legacy-docs pull request #1660
Opened 2022-11-29 15:02 UTC by TalhaMaliktz

Closes #1523

2022-11-29 21:09 UTC, shuse2 reviewed
Code samples looks good to me

2022-11-30 12:56 UTC, Tschakki requested changes
Finished review for the first 3 pages, will continue later but wanted already to submit the feedback so far

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
>  ** xref:build-blockchain/create-plugin.adoc[]
```suggestion
```

remove outdated links to guides from nav

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +*** xref:build-blockchain/plugin/plugin-endpoints.adoc[5. Creating an endpoint & Testing the plugin]
```suggestion
** xref:build-blockchain/plugin/index.adoc[]
*** xref:build-blockchain/plugin/schema-types.adoc[1. Defining off-chain data structures]
*** xref:build-blockchain/plugin/offchain-db.adoc[2. Setting up an Off-chain database]
*** xref:build-blockchain/plugin/configuring-plugin.adoc[3. Configuring a Plugin]
*** xref:build-blockchain/plugin/plugin-class.adoc[4. Updating the Plugin Class]
*** xref:build-blockchain/plugin/plugin-endpoints.adoc[5. Creating an endpoint & Testing the plugin]
** xref:build-blockchain/create-genesis-block.adoc[]
```

would move the plugin guide right below the module guide

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/index.adoc
> +.Salient features of Hello Client
```suggestion
.Salient features of the Hello Client
```

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +* [ ] The plugin should provide an endpoint to fetch hello messages, their sender addresses, and the height of the block where such an event was emitted.
```suggestion
* The plugin should retrieve all events from the sidechain.
* The plugin should filter out the events generated by the `Hello` module.
* A plugin should accept a custom configuration based on which it should sync on-chain `NewHelloEvent` with the plugin's database.
* The plugin should store all `NewHelloEvent` in a database.
* The plugin should provide an endpoint to fetch hello messages, their sender addresses, and the height of the block where such an event was emitted.
```

Remove the brackets, which are rendered as unchecked checkboxes

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +
```suggestion
. A new module `HelloModule` is created and contains all the functionalities as described in the guides for xref:{url_guides_module}[] 
```

I think it is enough to link to the index of the module guide, all corresponding guides are listed and linked on that page as well.

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +For a complete overview of all available options of the `generate:plugin` command, visit the xref:{url_references_commander_commands_plugin}[Lisk Commander command reference].
```suggestion
// TODO: Uncomment, once Commander reference is updated for v6.
//For a complete overview of all available options of the `generate:plugin` command, visit the xref:{url_references_commander_commands_plugin}[Lisk Commander command reference].
```

Commander reference is not included in beta.0 docs, therefore this should be commented out for now.

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +/* eslint-disable @typescript-eslint/no-empty-function */
```suggestion
```

this can be removed

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +The `HelloInfoPlugin` class is present in the `hello_info_plugin.ts` file and it contains the plugin's skeleton along with default functions for a plugin.
```suggestion
The `HelloInfoPlugin` class is defined in the `hello_info_plugin.ts` file and it contains the plugin's skeleton along with default functions for a plugin.
```

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +====
```suggestion
The `HelloInfoPlugin` will need to store data of events emitted by the `HelloModule`. To achieve this, first define the desired data structures as described on this page.

====
On this page, you will learn:

* [x] Defining types for required data structures.
* [x] Defining corresponding schemas for encrypting/decrypting the data.
* [x] Defining constants required by the plugin.
====
```

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +====
i adjusted the element to align with the module guide for consistency, and i changed the description to be more general, so it is better to understand what is explained on this page, without having much context.

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +. On-chain NewHelloEvent's data, which contains
```suggestion
. <<NewHelloEvent,On-chain NewHelloEvent's data>>, which contains
```

please add anchor links for the counter and last checked height as well

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +== Defining Types
I would describe the types before the schemas, because they are more simple to understand and schemas correspond to them.

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +Now that you are familiar with the various kinds of data to be stored in the plugin's database, On this page, you will learn:
```suggestion
```

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +====
```suggestion
====
On this page, you will learn:

```

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +export const newHelloEventSchema = {
The naming `newHelloEventSchema` is misleading and confusing, because we use the exact same name for the NewHello event of the module. But here, you include the height in the schema, so it is a different data structure, so it should use a different name. Please find another descriptive name here.

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +*A Counter for NewHelloEvents stored off-chain:* The HelloInfoPlugin will store a counter for the number of NewHelloEvent stored in the off-chain database.
Why is the plugin not using the counter from the Hello module?

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +* [x] Getting and Setting last checked Block Height.
Similar to my comment on schemas-types page, imho it is better to describe general skills/knowledge that can be gained on this page, for summarizing page contents we can use the table of contents.

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +Create the new file in the said directory.
```suggestion
Plugins use xref:{understand-blockchain/modules-commands.adoc#off-chain-store}[off-chain stores], analog to modules. Different to on-chain stores, off-chain stores are not shared with other nodes and can be considered as local database/key-value store of the particular node.

//TODO: Add back link once the related content is updated
// For this guide, we want to store the NewHelloEvent's data in an off-chain store by using xref:{url_lisk_db}[lisk-db]. 
For this guide, we want to store the NewHelloEvent's data in an off-chain store by using `lisk-db`. 
Lisk-db is a key-value store based on {url_rocks_db}[RocksDB].

The database-related operations will exist in a `db.ts` file which will exist in the plugin's root folder: `hello_info`. 
Create the new file in the said directory.

TIP: The relevant file discussed in this guide is {url_github_db}[db.ts].
```

2022-11-30 12:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +Create the new file in the said directory.
I think the intro flow can be improved, see my suggestion above

2022-11-30 14:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +Create the new file in the said directory.
```suggestion
Plugins can use any database for their off-chain data storage needs, contrary to modules that use both on-chain and off-chain data stores offered by the Lisk SDK. 
A plugin's data store stays only on the node that registers it to the sidechain and is not shared with other nodes.

//TODO: Add back link once the related content is updated
// For this guide, we want to store the NewHelloEvent's data in an off-chain store by using xref:{url_lisk_db}[lisk-db]. 
For this guide, we want to store the NewHelloEvent's data in an off-chain store by using `lisk-db`. 
Lisk-db is a key-value store based on {url_rocks_db}[RocksDB].

The database-related operations will exist in a `db.ts` file which will exist in the plugin's root folder: `hello_info`. 
Create the new file in the said directory.

TIP: The relevant file discussed in this guide is {url_github_db}[db.ts].
```

2022-11-30 14:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +*A Counter for NewHelloEvents stored off-chain:* The HelloInfoPlugin will store a counter for the number of NewHelloEvent stored in the off-chain database.
Do you mean the counter-store schema? Probably because your branch wasn't final at that time.

2022-12-01 08:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/schema-types.adoc
> +====
```suggestion
The `HelloInfoPlugin` will need to store data of events emitted by the `HelloModule`. To achieve this, first define the desired data structures as described on this page.
====
On this page, you will learn:
* [x] Defining types for required data structures.
* [x] Defining corresponding schemas for encoding/decoding the data.
* [x] Defining constants required by the plugin.
====
```

2022-12-05 15:27 UTC, Tschakki requested changes
Great work! Just a few small comments left from my side.

2022-12-05 15:27 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-class.adoc
> +But, how can we see that data, for that, let's create an endpoint and test our plugin in the next guide.
```suggestion
But how can we retrieve that data?
For that, let's create an endpoint and test our plugin in the next guide.
```

2022-12-05 15:27 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-endpoints.adoc
> +Since, you already know how to run the hello client, create and send a hello message as described in xref:{url_send_transaction}[How to create a command → Try the new command out].
```suggestion
Create and send a hello message as described in xref:{url_send_transaction}[How to create a command → Try the new command out].
```

2022-12-05 15:27 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-endpoints.adoc
> +== Testing HelloInfoPlugin
I would also include a small example how to query the plugin endpoint in this section

2022-12-05 15:27 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-class.adoc
> +export const onChainEventSchema = {
now the schema looks identical to `newHelloEventSchema`, so in this case it would have sense if they have the same name ^^ I think before there was `height` included, this is why I suggested to change the name.

But I think no need to change it again if it is a lot of work, just wanted to clarify this.

2022-12-06 12:33 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-class.adoc
> +export const onChainEventSchema = {
I have reused the schema available in the module, have updated the code, the guide and have also tested the application.

2022-12-06 13:24 UTC, Tschakki approved these changes
Thank you! 🎉

2022-12-06 13:47 UTC, merged