Create migration guide for SDKv5 to v6
LiskArchive/lisk-legacy-docs pull request #1661
Opened 2022-11-29 17:25 UTC by Tschakki

Closes #1179

2022-12-12 13:26 UTC, TalhaMaliktz requested changes
Looking good 😊

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +The release of the Lisk SDK v6 introduces many breaking changes and important improvements of the Lisk Protocol and the Lisk Framework.
```suggestion
The Lisk SDK v6 introduces many breaking changes and essential improvements to the Lisk Protocol and the Lisk Framework.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +|A type of node which has capability of generating a block.
```suggestion
|A type of node which has the capability of generating a block.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +It is used when sending tokens to a specific chain and also prepended for signing to protect against replay attacks.
```suggestion
It is used when sending tokens to a specific chain and is also prepended for signing to protect against replay attacks.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +|Events which are natively included in the Lisk Framework, and follow the publish/subscribe pattern.
```suggestion
|Events that are natively included in the Lisk Framework and follow the publish/subscribe pattern.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +To verify, if a transaction which is included in a block was executed successfully, Lisk SDK v6 introduces the <<addition-of-blockchain-events>>.
```suggestion
To verify, if a transaction that is included in a block was executed successfully, Lisk SDK v6 introduces the <<addition-of-blockchain-events>>.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Beside the newly introduced blockchain events, there are still a couple of xref:{url_understand_rpc_events}[RPC events] included in the Lisk Framework, which can be retrieved via public-subscribe, as
```suggestion
Besides the newly introduced blockchain events, there is still a couple of xref:{url_understand_rpc_events}[RPC events] included in the Lisk Framework, which can be retrieved via public-subscribe, as in v5.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +The sidechain developer can define new blockchain events per module as desired, but the RPC events are not customizable anymore.
```suggestion
The sidechain developer can define new blockchain events per module as desired, but the RPC events are not customizable any more.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +They can include a lot of additional data, if required, as the events themselves can be removed from the stores of the node after a certain time, and therefore don't "pollute" the blockchain itself.
```suggestion
They can include a lot of additional data if required, as the events themselves can be removed from the stores of the node after a certain time, and therefore don't "pollute" the blockchain itself.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +For more information how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
```suggestion
For more information on how to create the corresponding event class, please check out the guide on xref:{url_build_module_event}[]
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Chain identifiers (or chain IDs), for transaction signatures and block signatures were already introduced in Lisk SDK v5 as network identifiers to prevent replay attacks on other chains.
```suggestion
Chain identifiers (or chain IDs), for transaction signatures and block signatures, were already introduced in Lisk SDK v5 as network identifiers to prevent replay attacks on other chains.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Beside getting a more descriptive name, the chain ID is also constructed differently now:
```suggestion
Besides getting a more descriptive name, the chain ID is also constructed differently now:
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Module and command name are used as unique identifiers for modules and commands instead.
```suggestion
Instead of IDs, the name of a module and the name of a command are now used as unique identifiers for modules and commands, respectively.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Methods in Lisk SDK v6 still have the same purpose as reducers in v5, but beside the name change, they are also defined slightly different, as summarized below:
```suggestion
Methods in Lisk SDK v6 still have the same purpose as reducers in v5, but besides the name change, they are also defined a bit differently, as summarized below:
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Endpoints in Lisk SDK v6 still have the same purpose as actions in v5, but beside the name change, they are also defined slightly different, as summarized below:
```suggestion
Endpoints in Lisk SDK v6 still have the same purpose as actions in v5, but besides the name change, they are also defined a bit differently, as summarized below:
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +A store, aka key-value store is a special kind of database which follows a data storage paradigm designed for storing, retrieving, and managing associative arrays.
```suggestion
A store, aka key-value store is a special kind of database that follows a data storage paradigm designed for storing, retrieving, and managing associative arrays.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Each module has an own dedicated store, which only the module itself can access.
```suggestion
Each module has its own dedicated store, which only the module itself can access.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +In Lisk SDK v6, *the account store is removed completely*, and integrated in the respective module stores.
```suggestion
In Lisk SDK v6, *the account store is removed completely*, and integrated into the respective module stores.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +NOTE: The following changes were introduced to complement the improvements made in the module structure, see <<methods-replace-reducers>>, <<addition-of-blockchain-events>> and <<migration-of-store-f
```suggestion
NOTE: The following changes were introduced to complement the improvements made in the module structure, see <<methods-replace-reducers>>, <<addition-of-blockchain-events>>, and <<migration-of-store-from-v5-to-v6>>.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +:url_understand_txs: {docs-general}understand-blockchain/blocks-txs.adoc#transactions
Maybe?
```suggestion
:url_understand_txs: {docs-general}understand-blockchain/blocks-txs.adoc#successful-vs-failed-transactions
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +Increased developer experience::
```suggestion
Enhanced developer experience::
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +In the Lisk SDK, stores are used to store the on-chain and off-chain related data of a node persistent.
```suggestion
In the Lisk SDK, stores are used to store the on-chain and off-chain related data of a node.
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +:url_metadata: {docs-understand-modules}#metadata
```suggestion
:url_metadata: {docs-understand-modules}#module-metadata
```

2022-12-12 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +* Users can now query all relevant metadata about a module in a consistent manner.
```suggestion
* Users can now query all the relevant metadata about a module in a consistent manner.
```

2022-12-12 13:50 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +For more information how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
```suggestion
For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
```

2022-12-12 13:51 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +Improved developer experience::
```suggestion
Enhanced developer experience::
```

2022-12-13 13:26 UTC, TalhaMaliktz approved these changes, later dismissed
Just a minor suggestion, the rest of it LGTM. 👍🏼

2022-12-13 13:26 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
```suggestion
For more information on how to create the corresponding event class, please check out the guide on xref:{url_build_module_event}[]
```

2022-12-15 06:50 UTC, ishantiw reviewed
There are a few comments but mostly it looks good. Also, are we going to have a different guide to make an interoperable module?

2022-12-15 06:50 UTC, ishantiw commented on modules/ROOT/pages/references/migration.adoc
> +This means, if you wish to verify that a transaction was successfully executed, it is not sufficient anymore to check, if it is included in a finalized block.
the statement sounds a bit unclear, maybe it can be simplified

2022-12-15 06:50 UTC, ishantiw commented on modules/ROOT/pages/references/migration.adoc
> +|Blockchain events are a way for modules to store important information which is not included in the transactions or block assets, directly inside the block header.
```suggestion
|Blockchain events are a way for modules to store important information which is not included in the transactions or block assets, verifiable using eventRoot property present inside the block header.
```

2022-12-15 06:50 UTC, ishantiw commented on modules/ROOT/pages/references/migration.adoc
> +Chain identifiers (or chain IDs), for transaction signatures and block signatures, were already introduced in Lisk SDK v5 as network identifiers to prevent replay attacks on other chains.
we can also mention to identify chains for making cross chain transfers in the ecosystem

2022-12-15 11:37 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +This means, if you wish to verify that a transaction was successfully executed, it is not sufficient anymore to check, if it is included in a finalized block.
I tried to simplify it now, and removed the CAUTION admonition as well

2022-12-15 13:12 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
In my ears it doesn't sound right here to add an `on`, because the link label coming afterwards resolves to the page title of the guide: "How to create a blockchain event", so imho the sentence should be

- ..., please check out the guide "How to create a blockchain event".

2022-12-15 13:14 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
btw I also updated the terminology changes to include all pos related terminologies, please check

2022-12-15 14:02 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
The following three are correct, so you can use either one of them.

please check out the guide "How to create a blockchain event".
please check out the guide: How to create a blockchain event.
please check out the guide on How to create a blockchain event.

2022-12-15 14:41 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
so in that case, we agree my original sentence is correct?

2022-12-15 14:43 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
Nope, coz the original sentence will be like this:

- please check out the guide How to create a blockchain event.

2022-12-15 14:48 UTC, Tschakki commented
>  Also, are we going to have a different guide to make an interoperable module?

@ishantiw currently, I don't think we have planned that. The Hello World app currently only has one module which is not interoperable.
But actually it is a good idea, maybe it should be updated to include such a module, or maybe the Hello module should be directly constructed like that.

2022-12-16 09:28 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
Please be aware that the guide title is rendered as a link.

2022-12-16 13:26 UTC, Tschakki commented on modules/ROOT/pages/references/migration.adoc
> +For more information on how to create the corresponding event class, please check out the guide xref:{url_build_module_event}[]
```suggestion
For more information on how to create the corresponding event class, please check out the guide: xref:{url_build_module_event}[]
```

2022-12-19 09:10 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2022-12-19 14:16 UTC, ishantiw approved these changes
LGTM

2022-12-19 15:12 UTC, merged