Update "how to create a new genesis block" - Closes 1526
LiskArchive/lisk-legacy-docs pull request #1668
Opened 2022-12-07 07:36 UTC by TalhaMaliktz

Closes #1526

2022-12-07 13:04 UTC, chris529 reviewed
Looks great! Just a few very minor points 👍

2022-12-07 13:04 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
> +During the init process of a sidechain client, lisk-sdk bootstraps the first genesis block required for each sidechain and the relevant assets in the `config/default` directory of each client.
```suggestion
During the init process of a sidechain client, the lisk-sdk bootstraps the first genesis block required for each sidechain and the relevant assets in the `config/default` directory of each client.
```

2022-12-07 13:04 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
> +<3> `genesis_assets.json`: Contains details about the initial state of a sidechain such as account details for `token` and `pos` modules. Also contains the list of validators, etc.
```suggestion
<3> `genesis_assets.json`: Contains details about the initial state of a sidechain such as account details for `token` and `pos` modules. It also contains the list of validators, etc.
```

2022-12-07 13:04 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
> +To do that, you can regenerate a genesis block for various use cases, such as assigning different tokens to specific addresses of your choice.  You can also recreate the genesis block based on the ne
```suggestion
To achieve this you can regenerate a genesis block for various use cases, such as assigning different tokens to specific addresses of your choice. Furthermore, it is also possible to recreate the genesis block based on the module's requirements, for example, setting up the initial constraints required for a staking module, etc.
```

2022-12-08 12:22 UTC, chris529 approved these changes
LGTM! 👍

2022-12-09 11:02 UTC, shuse2 requested changes

2022-12-09 11:02 UTC, shuse2 commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
> +For every new sidechain, a unique genesis block is required. As mentioned earlier, a default genesis block becomes available right after the client's `init` process. However, while running a public n
for the public network, developers have to create a new genesis block. Initial genesis block are expected to be used only for development

2022-12-09 15:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
> +To achieve this you can regenerate a genesis block for various use cases, such as assigning different tokens to specific addresses of your choice. Furthermore, it is also possible to recreate the gen
```suggestion
To achieve this you can regenerate a genesis block for various use cases, such as assigning different tokens to specific addresses of your choice. 
Furthermore, it is also possible to recreate the genesis block based on the module's requirements, for example, setting up the initial constraints required for a staking module, etc.
```

2022-12-09 15:04 UTC, shuse2 approved these changes

2022-12-12 07:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
> +The initial genesis block is expected to be used only for the development purposes.
```suggestion
The initial genesis block is expected to be used only for development purposes.
```

2022-12-12 09:47 UTC, merged