Update terminologies in update v6 docs - Closes 1658
LiskArchive/lisk-legacy-docs pull request #1675
Opened 2022-12-16 15:23 UTC by TalhaMaliktz

Closes #1658

2022-12-27 14:55 UTC, Tschakki requested changes

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +A reference of all RPC endpoints and events is provided by the Lisk Framework for a sidechain application.
```suggestion
A reference of all RPC endpoints and events provided by a sidechain client through the Lisk Framework.
```

sApp also includes middleware, so it are not all endpoints. Should be client in this context

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +A reference of all RPC endpoints and events is provided by the Lisk Framework for a sidechain application.
```suggestion
A reference of all RPC endpoints and events provided by a sidechain client through the Lisk Framework.
```

sApp also includes middleware, so it are not all endpoints. Should be client in this context

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +<3> `genesis_assets.json` contains all the accounts and asset details for the sidechain.
```suggestion
<3> `genesis_assets.json` contains all the initial accounts and asset details.
Used to create the genesis block for the sidechain.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +An active validator, can mostly be considered as an entity, that can generate new blocks for the Lisk sidechain.
```suggestion
An active validator is an account that registered as validator and can generate new blocks in the next block generation round for the Lisk mainchain, or for a sidechain with DPoS as validator selection algorithm.
A registered validator turns from inactive to active, if they accumulated more <<validator-weight>> than one of the currently active validators.
```

I tried to improve the description to be more informative. Also, I discovered the term DPoS is not in the glossary currently. Imho, we should add it.

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A total of 101 validators exist in a Lisk sidechain for this purpose, and each validator is ranked from 1-101.
```suggestion
A total of 101 active validators exist on the Lisk Mainchain for this purpose, and each validator is ranked from 1-101.
Additionally, two random validators are selected each round for forging, resulting in 103 active delegates per round on the Lisk Mainnet.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A hash of a block header that uniquely identifies a block in a sidechain.
```suggestion
A hash of a block header that uniquely identifies a block in a Lisk blockchain.
```

Or `in the Lisk Mainchain or a sidechain`

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Short form of sidechain client.
Imho this shouldn't be official terminology, we use it only as a short form to avoid repetition.

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Typically, there is a state change on the sidechain.
I think this is outdated terminology, should be removed completely imho

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
>  // Any misbehavior of a delegate is xref:{url_discover_misbehavior}[indicated] by two contradicting block headers signed by the delegate.
DPoS is correct here, but maybe we can remove this terminology completely now

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +For Lisk sidechain clients, the faucet plugin can be registered with the client to provide a basic faucet, which is useful during the development phase, and also for proof-of-concept sidechain client
```suggestion
The faucet plugin can be registered with the sidechain client to provide a basic faucet, which is useful during the development phase, and also for proof-of-concept sidechains.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Analog to "forge" the term "generate" is also used within Lisk documentation.
This is outdated and can be removed

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
>  === Framework plugin
Is this official terminology?

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A generator can mostly be considered as a forging generator, which can forge new blocks for the Lisk sidechain. Rank 1-101.
Please remove, we use the term validator instead

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +The Lisk SDK is an open-source software development kit which enables developers to easily build scalable sidechains using JavaScript & Typescript.
Please add a link to the SDK docs

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Module endpoints enable data to be retrieved from a sidechain.
```suggestion
Module endpoints enable external services to retrieve data from a sidechain.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Module endpoints enable data to be retrieved from a sidechain.
```suggestion
Module endpoints enable external services to retrieve data from a sidechain.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +In the Lisk network, it can be defined as an integer that represents the number of outgoing transactions of an account.
```suggestion
In the Lisk protocol, it can be defined as an integer that represents the number of outgoing transactions of an account.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +It is part of the consensus algorithm of a sidechain and is used on Lisk Mainnet and in the Lisk SDK.
Lisk PoS is not a pure PoS algorithm, actually it is a hybrid of DPoS and PoS, imho we should emphasize this in the docs

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A standby validator is classed as a validator that is not able to generate new blocks for the Lisk blockchain, as each validator is not an <<active-validator>>.
```suggestion
A standby validator, or inactive validator, is classed as a validator that does not have the sufficient validator weight and therefore is not eligible to generate new blocks. A standby validator can become an <<active-validator>> if their <<validator-weight>> increases.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Rank 1~102.
```suggestion
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Rank 1~102.
```suggestion
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Stake validator transaction
Is this the real name of the transaction/command?

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +* The DPoS module
```suggestion
* The PoS module
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Secondly, scalability is further increased by the use of the PoS consensus mechanism as explained in more detail on the xref:{url_how_blockchain_works}[How blockchain works] page.
Please explain here that Lisk uses actually a combination of PoS and DPoS which includes the best of both worlds, and that we call it `Lisk PoS` for simplicity. Explain benefits of Lisk PoS, referring to DPoS and PoS when it fits in the context.

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* *sidechains*: Sidechain applications built with the Lisk SDK.
We define sApps to be bApps based on Lisk protocol, therefore i think it's repetitive to define it like this

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +A module is a discrete component that contains blockchain-related business logic. This logic can be related to a specific domain or a topic of a xref:{url_sidechain_glossary}[Sidechain Application (s
Currently we don't have any specific styling for glossary links, so imho it would be better to add the glossary links as footnotes until we ave a better solution to distinguish them from other links.

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +:url_sapp: glossary.adoc#sapp
Please add glossary links as footnotes

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +sApps to communicate with Lisk nodes.
any reason for the line-break here?

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +:url_sapp: glossary.adoc#sapp
Pls add as footnotes

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  For more information about Lisk Protocol, see {url_protocol}[Lisk Improvement Proposals].
After reading it several times, i am not sure what this paragraph wants to tell me. Maybe it can be removed?

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A sidechain application refers to a software that contains a lisk based sidechain client, a middleware and a UI.
Are we explaining what a sidechain client is as well? Would explain it before or add a link to explanation here.

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +More specifically, within the Lisk documentation, whenever xref:{url_sapp}[sApps] are discussed, this is directly referring to applications that run by using sidechain, which are compatible with Lisk
WIth the new terminology introduced, I think we can remove this sentence.

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each blockchain node keeps data on various data stores inside its Lisk sidechain\'s instance. This data contains the following two types: on-chain and off-chain.
```suggestion
Each blockchain node is an instance of a particular sidechain and keeps the data on various data stores inside.
This data contains the following two types: on-chain and off-chain.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Each blockchain node keeps data on various data stores inside its Lisk sidechain\'s instance. This data contains the following two types: on-chain and off-chain.
```suggestion
Each blockchain node is an instance of a particular sidechain and keeps the data on various data stores inside.
This data contains the following two types: on-chain and off-chain.
```

2022-12-27 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/index.adoc
> +//TODO: Content can be removed as it is present in understand-blockchain/index.adoc
I think this page can be removed completely.

2022-12-28 06:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Secondly, scalability is further increased by the use of the PoS consensus mechanism as explained in more detail on the xref:{url_how_blockchain_works}[How blockchain works] page.
Can you please share more information on this, like what part of DPoS is used and what part of PoS is used? I can then draw a better picture to fit the context.

2022-12-28 06:14 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* *sidechains*: Sidechain applications built with the Lisk SDK.
So should it be the following?
```suggestion
* *sidechains*: Blockchains built with the Lisk SDK.
```

2022-12-28 06:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +sApps to communicate with Lisk nodes.
No, I don't think so. Will remove the line-break.

2022-12-28 06:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A total of 101 validators exist in a Lisk sidechain for this purpose, and each validator is ranked from 1-101.
```suggestion
A total of 101 active validators exist on the Lisk Mainchain for this purpose, and each validator is ranked from 1-101.
Additionally, two random validators are selected for each round of block generation, resulting in 103 active validators per round on the Lisk Mainnet.
```

2022-12-28 06:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +A total of 101 validators exist in a Lisk sidechain for this purpose, and each validator is ranked from 1-101.
```suggestion
A total of 101 active validators exist on the Lisk Mainchain for this purpose, and each validator is ranked from 1-101.
Additionally, two random validators are selected for each round of block generation, resulting in 103 active validators per round on the Lisk Mainnet.
```

2022-12-28 12:06 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/index.adoc
> +* *sidechains*: Sidechain applications built with the Lisk SDK.
yes, looks good 👍

2022-12-28 12:25 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Stake validator transaction
I think so!
https://docs.google.com/spreadsheets/d/1KGcug-YQiookwVlOBula7eDVgpCMIfBjsfSLMdSNRhI/edit#gid=0

2022-12-28 12:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +The Lisk SDK is an open-source software development kit which enables developers to easily build scalable sidechains using JavaScript & Typescript.
Link to this page: https://liskhq.github.io/lisk-docs/lisk-sdk/index.html ?

2022-12-28 12:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
>  === Framework plugin
I am not sure, maybe @chris529 can guide.

2022-12-28 12:49 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/command.adoc
> +In the root folder of the sidechain application, generate a skeleton for the new command with Lisk Commander.
```suggestion
In the root folder of the sidechain client, generate a skeleton for the new command with Lisk Commander.
```

2022-12-28 12:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +* Lisk Commander is installed, and a basic sidechain application is already initialized, as explained in the previous guide xref:{url_build_init}[].
```suggestion
* Lisk Commander is installed, and a basic sidechain client is already initialized, as explained in the previous guide xref:{url_build_init}[].
```

2022-12-28 12:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/module/index.adoc
> +* Lisk Commander is installed, and a basic sidechain application is already initialized, as explained in the previous guide xref:{url_build_init}[].
```suggestion
* Lisk Commander is installed, and a basic sidechain client is already initialized, as explained in the previous guide xref:{url_build_init}[].
```

2022-12-28 12:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +. Lisk Commander is installed, and a basic sidechain application is already initialized, as explained in the guide xref:{url_guides_setup}[].
```suggestion
. Lisk Commander is installed, and a basic sidechain client is already initialized, as explained in the guide xref:{url_guides_setup}[].
```

2022-12-30 10:34 UTC, vjaiman requested changes

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +Used to create the genesis block for the sidechain.
```suggestion
It is used to create the genesis block for the sidechain.
```

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +The default modules provide basic sidechain functionality that the most basic sidechain client requires to run.
"basic" vs "most basic". Is there any difference? Also, "basic" seems repetitive here.

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
>  2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command voteDelegate
Verify once if the output will be in the form of "dpos module" or "pos module".

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +An active validator is an account that registered as validator and can generate new blocks in the next block generation round for the Lisk mainchain, or for a sidechain with DPoS as validator selecti
DPoS -> PoS

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +Refers to an instance of a blockchain client that is connected to other computers/nodes in a decentralized network of nodes/computers.
```suggestion
Refers to an instance of a blockchain client that is connected to other nodes in a decentralized network.```

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
>  === Proof of misbehavior - PoM
Proof of misbehavior is now "reportMisbehavior"

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +A block cannot contain two PoMs with the same block generating validator.
PoM -> reportMisbehavior

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +It is computed from the self-votes and the total amount of received votes.
There is no self-votes/votes in updated terminology.
self-voters -> self-stakes
votes -> stakes

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Validator vote
vote -> stake

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +A transaction type on the mainnet which submits votes for validators for staking purposes.
votes -> stakes

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +The weight of a validator will determine the sum of all votes for this validator.
votes -> stakes

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/understand-blockchain/interoperability/sidechain-registration-and-recovery.adoc
> +A sidechain is a separate blockchain registered to the mainchain, where the inclusion of a transaction in one of the blockchains can have an effect on the other blockchain.
```suggestion
A sidechain is a separate blockchain registered on the mainchain, where the inclusion of a transaction in one of the blockchains can have an effect on the other blockchain.
```

2022-12-30 10:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
>  Finally, a reward is added to the account sending the PoM.
PoM -> reportMisbehavior

2022-12-30 13:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-app.adoc
> +The default modules provide basic sidechain functionality that the most basic sidechain client requires to run.
```suggestion
The default modules provide basic sidechain functionality required by a sidechain client to work.
```

2022-12-30 13:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +An active validator is an account that registered as validator and can generate new blocks in the next block generation round for the Lisk mainchain, or for a sidechain with DPoS as validator selecti
```suggestion
An active validator is an account registered as a validator. It can generate new blocks in the next block generation round for the Lisk mainchain, or for a sidechain with PoS as a validator selection algorithm.
```

2022-12-30 13:21 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +Refers to an instance of a blockchain client that is connected to other computers/nodes in a decentralized network of nodes/computers.
```suggestion
Refers to an instance of a blockchain client that is connected to other nodes in a decentralized network.
```

2022-12-30 13:45 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
>  2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command voteDelegate
The output does suggest DPoS, as this page was updated very recently. I copied it from the terminal after creating a new genesis block.

2022-12-30 14:11 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
>  2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command voteDelegate
It looks like the log is outdated, it should be `pos module` and `voteDelegate` should be `stake` now. 

https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/pos/commands/stake.ts

2022-12-30 14:17 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-genesis-block.adoc
>  2022-12-02T12:59:33.114Z INFO XYZ application 30245 Registered dpos module has command voteDelegate
Updated.

2022-12-30 15:24 UTC, Tschakki requested changes
Looking good, just spotted a lot of things to improve in the glossary, it would be great if you can include them.

Furthermore, I think it might make sense to take a deeper look at the glossary in particulary again, maybe after we have created further content, or to update it as part of other issues along the way. Imho we should review the terms included in the glossary. For example, "block generation round" is missing, and other terms can be removed. Second, we need to review the descriptions and also enhance them with relevant links to further information later on, I already added some todos regarding this in the comments.

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A self stake is a vote that a validator casts for themselves. Self stakes are always at least 10% of the validator weight.
```suggestion
//TODO: Add footnote here linking to Lisk PoS explanation page
If a validator uses their tokens to increase their own <<validator-weight>>, this is called a self-stake.
The percentage of the self-stake needs to be at least 10% of the total validator weight of a particular validator, to be eligible to generate new blocks in the network.
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Standby validator
I think we are missing a terminology to distinguish between (A)validators who are theoretically able to forge by being selected in one of the two random spots each round, and (B)delegates who are not even considered for the random selection.

Can you check if this is considered somewhere in the new terminology proposals? Imho I would call (A) `standby delegates` and (B) `inactive delegates`. What do you think?

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +If staking weight was added, the corresponding LSK tokens are locked and cannot be used for any other transaction.
```suggestion
=== (Un-)staking

Staking is the process of using ones own tokens to vote for one or multiple validators.
Staking for a delegate will increase the <<validator-weight>> of the validator.
Staked tokens are locked in the account that performed the stake, until they are un-staked.

Un-staking is the process of removing tokens from one or multiple validators.
After he tokens are un-staked, they can be unlocked by posting an <<unlock-token-transaction>>. 

Staking and un-staking of tokens can be both performed by posting a <<stake-transaction>> to the network.
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Stake validator transaction
```suggestion
=== Stake transaction
```

I checked, it is only `stake` in current implementation

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +It is computed from the self-stakes and the total amount of received stakes.
```suggestion
//TODO: Add link to Lisk PoS explanation
It is computed from the <<self-stakes>> and the total amount of received <<un-staking, stakes>>.
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A user deploying their LSK to stake for their favourite validators.
```suggestion
A user deploying their LSK to <<un-staking, stake>> for their favorite validators.
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Validator registration transaction
```suggestion
=== RegisterValidator transaction
```

Please move under the letter `R`, too.

Also, please check the other transaction names with the actual implementation, it should match the corresponding command name.

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A xref:{url_delegate_registration}[validator's registration] is achieved by sending a xref:{url_delegate_registration_tx}[validator registration transaction] on the mainnet, which registers a validat
```suggestion
To be able to participate in the block generation process, an account needs to register as a validator in the network.
//TODO: Add link to related guide how to register a validator, once it is updated.
//TODO: Add link to the PoS module reference
The registration process is performed by posting a validator registration transaction to the network.
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +A transaction type on the mainnet which reports a validator's misbehavior.
Please remove, duplicate of `ReportMisbehavior` above

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== reportMisbehavior
```suggestion
=== ReportMisbehavior transaction
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== reportMisbehavior
Please move this to letter R

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +Finally, a reward is added to the account sending the reportMisbehavior transaction.
```suggestion
//TODO: Add link to PoS module reference
Finally, a reward is added to the account sending the reportMisbehavior transaction.
```

2022-12-30 15:24 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Total stakes received
The term here doesn't seem right, what is explained below is basically the `validator weight`. But also the explanation leaves room to improve, so imho i would remove this completely from the glossary.

2022-12-30 15:44 UTC, TalhaMaliktz commented
> Looking good, just spotted a lot of things to improve in the glossary, it would be great if you can include them.
> 
> Furthermore, I think it might make sense to take a deeper look at the glossary in particulary again, maybe after we have created further content, or to update it as part of other issues along the way. Imho we should review the terms included in the glossary. For example, "block generation round" is missing, and other terms can be removed. Second, we need to review the descriptions and also enhance them with relevant links to further information later on, I already added some todos regarding this in the comments.

Sounds like a plan to me, I think we should add it as part of every issue to check for updated terminologies and relevant terms in the glossary as well and make the relevant change if necessary, this way we can improve the glossary step by step.

2022-12-31 06:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Standby validator
The current definitions in the terminology sheet are as follows:

<img width="487" alt="Screenshot 2022-12-31 at 11 47 01 AM" src="https://user-images.githubusercontent.com/13951043/210127984-8542979d-98a1-4d6c-aaec-12836f4242e3.png">

We can add the new term: `inactive validator` if required. I think @vjaiman can add further to this conversation.

2022-12-31 07:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Total stakes received
I have removed the word "received" to make it correct. The terminology should stay as the last line differentiates between `total stakes` and `validator weight`.

> However, it should be noted that as the validator stake will be capped by the self-stake, the total stakes might not be equal to the validator weight.

2023-01-02 09:34 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Standby validator
In the LIPs, we don't have separate term for the standby validator who doesn't get selected in a round. I would keep the same terminology for the alignment.

2023-01-02 10:37 UTC, vjaiman requested changes
Looks better. There are broken links in some pages. I suppose it will be updated at the end.

2023-01-02 10:37 UTC, vjaiman commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
>  === Delegated-Proof-of-Stake
I would change this section since we don't use the DPoS terminology now. Also, it has some sentences which should be removed. For example " DPoS is generally considered to be the most advantageous mechanism". It should be written in the form of Lisk PoS.

2023-01-02 10:37 UTC, vjaiman commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +If you consider gaining an active forging position on the Lisk Mainnet, please be aware that the Lisk DPoS requires to xref:{url_glossary_selfvote}[self stake] with a certain amount of your own token
DPoS - > PoS 
In this document , at some places `DPoS`, `votes` have been used. I would change those terminologies.

2023-01-02 10:37 UTC, vjaiman commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +This gives delegates who don't have enough stakes weights the chance to profit from forging awards as well.
delegates -> validators
This document has old terminologies.

2023-01-02 10:37 UTC, vjaiman commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Secondly, scalability is further increased by the use of the PoS consensus mechanism as explained in more detail on the xref:{url_how_blockchain_works}[How blockchain works] page.
broken link.

2023-01-02 11:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +If you consider gaining an active forging position on the Lisk Mainnet, please be aware that the Lisk DPoS requires to xref:{url_glossary_selfvote}[self stake] with a certain amount of your own token
This page has been updated in a separate issue, the changes will be merged soon.

2023-01-02 11:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +This gives delegates who don't have enough stakes weights the chance to profit from forging awards as well.
Same comment as above.

2023-01-02 11:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Secondly, scalability is further increased by the use of the PoS consensus mechanism as explained in more detail on the xref:{url_how_blockchain_works}[How blockchain works] page.
The URL works for me, how are you viewing this page?

2023-01-03 12:24 UTC, vjaiman commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +Secondly, scalability is further increased by the use of the PoS consensus mechanism as explained in more detail on the xref:{url_how_blockchain_works}[How blockchain works] page.
I was viewing in GitHub only.

2023-01-03 13:42 UTC, vjaiman requested changes

2023-01-03 13:42 UTC, vjaiman commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
>  DPoS has a higher transaction volume and is considered one of the most effective and efficient mechanisms in use today.
I would avoid to make claim like this in this sentence. 
Since now we are using the hybrid version of DPoS and PoS, I would avoid to say that DPoS is the best algorithm currently.
Also, either we rewrite DPoS section by stating that it is a Lisk PoS now or we can keep the DPoS (using DPoS terminologies such as delegate, vote etc.) and don't show it as most advantageous algorithm.  

May be you can discuss it within team how to better write this section.

2023-01-04 08:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
>  DPoS has a higher transaction volume and is considered one of the most effective and efficient mechanisms in use today.
Thanks, feedback incorporated.

2023-01-05 14:34 UTC, vjaiman approved these changes

2023-01-05 14:34 UTC, vjaiman commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
> +A forging round lasts until every active delegate has generated exactly one block.
Not exactly since there might be missed blocks and some delegate might forge multiple blocks. You can write something like "A forging round lasts until all the blocks in that round are forged"

2023-01-05 14:34 UTC, vjaiman commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
>  More in-depth information on DPoS can be found in this article on {url_dpos}[DPoS^].
In my opinion, we should not reference the external link instead our doc should be self-contained with all the information or we should reference our docs. The external referenced docs might change over the time or they can be removed.

2023-01-06 07:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/how-blockchain-works.adoc
>  More in-depth information on DPoS can be found in this article on {url_dpos}[DPoS^].
I kinda agree with you on this, however, since this change will impact the entire documentation so it will be a good idea to start a discussion on this within docs first before making this improvement. Will discuss this internally.

2023-01-09 11:29 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Standby validator
@vjaiman what definition do you have in the LIPs for standby delegates? 

When I look at the definitions that Talha posted, I can see they are not fitting for every registered validator who is not active.

For me, it makes sense to distinguish them in our documentation for the following reason (not sure if it would be beneficial in the LIPs as well):

If we follow the definition for standby delegates in the terminology sheet as @TalhaMaliktz posted, it is only applying to the delegates who are considered by the random selection algorithm.
Banned delegates or delegates who don't have enough self-votes would be excluded from that definition.

By registering a delegate, you don't automatically get considered by the algorithm that chooses the two random delegates each round. That means there is a group of delegates that has the opportunity to forge blocks each round, and another group of delegates, who will never be allowed to forge a block. 
To explain this difference, I think it would be very beneficial to have different terms for the two groups.

2023-01-09 11:52 UTC, Tschakki requested changes
I left my thoughts about the definition of standby delegates, but maybe we can start a new discussion for that, we don't need to include it in this PR.

Only thing left, please remove "total stakes" from glossary, then all looks good to me :)

2023-01-09 11:52 UTC, Tschakki commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Total stakes
OK, I see now the difference between delegate weight. But, to avoid confusion, please remove this terminology from the glossary. We normally only refer to the delegate weight, and it is not really a terminology of its' own imho.

2023-01-09 13:22 UTC, Tschakki approved these changes
Thank you! 🎉

2023-01-09 13:36 UTC, merged

2023-01-09 17:03 UTC, vjaiman commented on docs/modules/ROOT/pages/glossary.adoc
> +=== Standby validator
@Tschakki Here is the terminology that we aligned on for the Emerald phase https://docs.google.com/spreadsheets/d/1j3Zd5c-slvydef17BI6Nv_JLRhJClwHkLdMhsJRgOdQ/edit#gid=150650993
If you would like to introduce it, please add it into the sapphire phase terminology sheet.

We also have the term active validators for the top 101 validators by weight so saying inactive validators or inactive standby validators can be confusing if we don't mean the complement of the first set.
If we really want to distinguish between them we can use "selected standby validators" for the 2 standby validators who get selected and for the rest we just call them "standby validators".