Update "Run Blockchain" index page as per v6 - Closes 1676
LiskArchive/lisk-legacy-docs pull request #1684
Opened 2022-12-28 12:13 UTC by TalhaMaliktz

Closes #1676

2022-12-28 14:21 UTC, Tschakki requested changes

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  A blockchain node is a server with a running blockchain application, like xref:{url_core}[].
```suggestion
A blockchain node is a server with a running blockchain client, like xref:{url_core}[].
```

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  A blockchain node is a server with a running blockchain application, like xref:{url_core}[].
```suggestion
A blockchain node is a server with a running blockchain client, like xref:{url_core}[].
```

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  A blockchain node is a server with a running blockchain application, like xref:{url_core}[].
```suggestion
A blockchain node is a server with a running blockchain client, like xref:{url_core}[].
```

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  Nodes are usually connected to other nodes running the same blockchain application via P2P.
```suggestion
Nodes are usually connected to other nodes running the same client via P2P.
```

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  Nodes are usually connected to other nodes running the same blockchain application via P2P.
```suggestion
Nodes are usually connected to other nodes running the same client via P2P.
```

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +image::run-blockchain/node-service-network.png[Node network, 800]
The picture needs one correction: RPC node is just like other nodes in the diagram, but with enabled RPC API. Would remove the circles and just color/name the RPC nodes differently

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +See the section xref:{url_service_setup_docker_coreconfig}[Configuring Lisk Core] of the Lisk Service setup guide for a concrete example of how to configure Lisk Core so that Lisk Service can connect
This page isn't updated yet, please remove the link for now

2022-12-28 14:21 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  === APIs
The link and text of this section can be updated to include a links to these pages:

- https://liskhq.github.io/lisk-docs/understand-blockchain/sdk/rpc.html
- https://liskhq.github.io/lisk-docs/api/lisk-node-rpc.html

2022-12-28 14:26 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +image::run-blockchain/node-service-network.png[Node network, 800]
Ah, and also the border for the blockchain network is barely visible, please make it more bold

2022-12-28 14:26 UTC, chris529 reviewed
Looks great! Just a few minor points 👍

2022-12-28 14:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +The "Run Blockchain" category contains all the guides concerning the management of a Lisk node and is therefore especially interesting for validators and other operators of a Lisk node.
```suggestion
The "Run Blockchain" category contains all the guides concerning the management of a Lisk node and is therefore especially interesting for validators and other Lisk node operators.
```

2022-12-28 14:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  A blockchain node is a server with a running blockchain application, like xref:{url_core}[].
```suggestion
A blockchain node is a server with a running blockchain application, such as xref:{url_core}[].
```

2022-12-28 14:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  A blockchain node is a server with a running blockchain application, like xref:{url_core}[].
```suggestion
A blockchain node is a server with a running blockchain application, such as xref:{url_core}[].
```

2022-12-28 14:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +image::run-blockchain/node-service-network.png[Node network, 800]
imho, only a very minor point, but just to maintain uniformity here, in the screenshot below of the node descriptions in the existing diagram, we have the "Validator node" and the "Lisk Service node" therefore, we should update the "RPC Node" to "RPC node"
<img width="1392" alt="node-network" src="https://user-images.githubusercontent.com/58468196/209823672-a01cca79-cbc1-487a-a4f2-c569a3b5abb0.png">

2022-12-28 14:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +These nodes fulfill a very important role in the network and therefore require certain additional configurations regarding enabling block generation and security measures, compared to regular nodes.
```suggestion
These nodes fulfill a very important role in the network and therefore require certain additional configurations regarding enabling block generation and security measures, as compared to regular nodes.
```

2022-12-29 10:30 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  A blockchain node is a server with a running blockchain application, like xref:{url_core}[].
```suggestion
A blockchain node is a server with a running blockchain client, such as xref:{url_core}[].
```

2022-12-29 12:34 UTC, chris529 approved these changes
LGTM! 👍

2022-12-29 16:54 UTC, Tschakki requested changes

2022-12-29 16:54 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +image::run-blockchain/node-service-network.png[Node network, 800]
It is still a little misleading now, because it looks like every RPC node is connected to only one node, this is not true. What I meant was not turning the circle into a square, but completely remove it, and turn the "node" connected to it into an RPC node with the respective color

2022-12-29 16:54 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== Validator nodes
In the section `How to set up a Lisk Core node` above, please update `blockchain application` to `blockchain client`

2022-12-29 16:54 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  :docs_core: lisk-core::
```suggestion
:docs_core: v4@lisk-core::
```

Links should point to the docs for the prerelease version

2022-12-29 16:54 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  :toc: preamble
table of contents is not rendered for me?

2022-12-29 16:54 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  === How to set up a Lisk Service node
This content isn't updated yet, so please remove this sections for now.

2022-12-30 14:00 UTC, Tschakki requested changes

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +These nodes fulfill a very important role in the network and therefore require certain additional configurations regarding enabling block generation and security measures, as compared to regular node
```suggestion
These nodes are called *validator nodes*.
Validator nodes fulfill a very important role in the network and therefore, they require certain additional configurations regarding enabling block generation and security measures, as compared to regular nodes.
```

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In PoS, only a certain set of nodes is selected by the network to add new blocks to the blockchain.
```suggestion
//TODO: Add link to Lisk PoS explanation, once it is created
In the Lisk PoS, a certain set of validators is selected by the network to add new blocks to the blockchain.
To participate in the block generation process, a validator needs to set up a node and configure it to enable block generation.
```

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +image::run-blockchain/node-service-network.png[Node network, 800]
The image looks good now, thanks! 
But I just realized the black color isn't visible in the dark theme, maybe update it to blue or some other color visible on both black/white background

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In PoS, only a certain set of nodes is selected by the network to add new blocks to the blockchain.
After checking the rest of the content, I think the text below the diagram should be moved and merged with the content under the "Validator nodes" section.

Furthermore, I think the flow would improve if the sections are ordered like this:

1. What is a blockchain node?
2. Nodes
  2.1 RPC API
3. Validator nodes
4. Service nodes
5. How to set up a node
  5.1 Lisk Core
(later we can add link to Lisk Service here as well)

I think it improves the flow, because we introduce the diagram in the first section, and then explain all the different node types we mention in the diagram right below. And I think it is better with starting explaining the normal nodes first, as validator node is a special case of a normal node.

Then, after we have introduced the different node types and their purpose, we can add the links for helpful related guides below.

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Generally, non-validator nodes are used to get data from or send data to the blockchain via one of the available APIs of the node.
```suggestion
Generally, non-validator nodes are used by external services to get or send data to the blockchain if they have enabled the RPC API.
```

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  === APIs
```suggestion
=== RPC API
```

2022-12-30 14:00 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +The following APIs can be enabled in a blockchain node via the available communication protocols:
```suggestion
If the RPC API of a node is enabled, it allows external services to send queries to the node and/or to subscribe to specific events that are happening in the network.
Depending on the node configuration, an RPC enabled node can accept different communication protocols like HTTP, WS and IPC.
```

2022-12-30 15:31 UTC, Tschakki approved these changes
LGTM, thank you! 🎉

2023-01-09 13:45 UTC, merged