Add TypeDoc references
LiskArchive/lisk-legacy-docs pull request #1685
Opened 2022-12-29 16:05 UTC by Tschakki

Closes #256

2023-01-10 16:57 UTC, chris529 commented on modules/ROOT/pages/modules/index.adoc
> +|Responsible for handling the fee of transactions.
I think we should reword this heading to the following:
Responsible for handling the transaction fees.

2023-01-10 17:04 UTC, chris529 commented on modules/ROOT/pages/modules/index.adoc
> +|Handles all aspects of the generator selection, this includes the registration of accounts as validators, the staking process, and potential reports of misbehavior.
imho, I think we should have either one of the following:
'Handles all aspects of the generator selection, this includes the registration of accounts for validators, the staking process, and potential reports of misbehavior.'

Or alternatively:

'Handles all aspects of the generator selection, this includes the registration of validator accounts, the staking process, and potential reports of misbehavior.'

2023-01-11 10:55 UTC, chris529 reviewed
Looks great! Just a few minor points 👍

2023-01-11 10:55 UTC, chris529 commented on modules/ROOT/pages/modules/index.adoc
> +a|Provides the base reward system for a blockchain developed with the Lisk SDK
```suggestion
a|Provides the base reward system for a blockchain developed with the Lisk SDK.
```

2023-01-11 10:55 UTC, chris529 commented on modules/ROOT/pages/modules/index.adoc
> +|Handles minting, burning, and transferring tokens int he Lisk ecosystem.
```suggestion
|Handles minting, burning, and transferring tokens into the Lisk ecosystem.
```

2023-01-11 10:55 UTC, chris529 commented on modules/ROOT/pages/modules/index.adoc
> +|Rresponsible for validating the eligibility of a validator for generating a block and the block signature.
```suggestion
|Responsible for validating the eligibility of a validator for generating a block and the block signature.
```

2023-01-11 10:55 UTC, chris529 commented on modules/ROOT/pages/plugins/index.adoc
> +|Provides a user interface to distributing testnet tokens from sidechain.
```suggestion
|Provides a user interface for distributing testnet tokens from a sidechain.
```

2023-01-11 10:55 UTC, chris529 commented on modules/ROOT/pages/references/lisk-commander/index.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  Display autocomplete installation instructions.
```

2023-01-11 11:24 UTC, Tschakki commented on modules/ROOT/pages/modules/index.adoc
> +|Handles minting, burning, and transferring tokens int he Lisk ecosystem.
```suggestion
|Handles minting, burning, and transferring tokens inside the Lisk ecosystem.
```

2023-01-11 11:25 UTC, Tschakki commented on modules/ROOT/pages/plugins/index.adoc
> +|Provides a user interface to distributing testnet tokens from sidechain.
```suggestion
|Provides a user interface to distributing testnet tokens for a sidechain.
```

2023-01-11 11:26 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/index.adoc
> +  autocomplete  display autocomplete installation instructions
This is autogenerated

2023-01-11 12:33 UTC, TalhaMaliktz requested changes
Looking good! A few suggestions 😊

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/modules/index.adoc
> +|Responsible for handling and verifying nonces and for transaction signature validation, including transactions from multi-signature accounts.
```suggestion
|Responsible for handling and verifying nonces and transaction signature validation, including transactions from multi-signature accounts.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/modules/index.adoc
> +|Handles minting, burning, and transferring tokens int he Lisk ecosystem.
```suggestion
|Handles minting, burning, and transferring tokens in the Lisk ecosystem.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/modules/index.adoc
> +|Rresponsible for validating the eligibility of a validator for generating a block and the block signature.
```suggestion
|Responsible for validating the eligibility of a validator for generating a block and the block signature.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/plugins/index.adoc
>  |Provides a user interface which enables developers to conveniently view and communicate with the blockchain application during the development.
```suggestion
|Provides a user interface that enables developers to conveniently view and communicate with the sidechain application during development.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/plugins/index.adoc
> +|Provides a user interface to distributing testnet tokens from sidechain.
```suggestion
|Provides a user interface for distributing testnet tokens from the sidechain.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
>    generate    Commands relating to Lisk generator.
```suggestion
  generate    Commands relating to the Lisk generator.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  Display autocomplete installation instructions.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
**Line 158**
"As all packages in Lisk Elements are independent **of** each other, they can be installed **separately**."

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
>  [NOTE]
**Line 66**
`apiClient`, `codec`, `cryptography`, `passphrase`, `transactions`, `utils`, `tree`, and `validator`.

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
**Line 250**
`npm update @liskhq/<package-name>`

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/modules/index.adoc
> +a|Provides the base reward system for a blockchain developed with the Lisk SDK
```suggestion
a|Provides the base reward system for a blockchain developed with the Lisk SDK.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/modules/index.adoc
> +Furthermore, it maintains information about the registered validators in its module store and provides the generator list.
```suggestion
Furthermore, it maintains information about the registered validators in its module store and provides the validator list.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
>  |===
**Line 130**
`|Node.js | v16.18.0 (latest LTS)`

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +This document describes how to install Node.js and NPM for installation via NPM.
```suggestion
The following section describes how to install dependencies such as Node.js and NPM.
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
Line 180
Contains an unrendered call-out, maybe we can remove it as we have done the same on other docs as well.

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
**Line 231**
`const api = lisk.apiClient.createWSClient('ws://localhost:7887/rpc-ws');`

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
>  * Decrypting/encrypting passphrases or messages.
Line 19
`* Bootstrapping a sidechain application.`

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
> +For further details please see the xref:{url_commander_cli}[].
```suggestion

For further details please see the xref:{url_commander_cli}[].
```

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
Line 38
|Node.js | v16.18.0 (latest LTS)

2023-01-11 12:33 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
**Line 29 & 47**
Is `8.3` the correct node version?

2023-01-12 10:25 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/index.adoc
>  * Decrypting/encrypting passphrases or messages.
Updated to `sidechain client` to be more precise

2023-01-12 10:26 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/index.adoc
not sure if this is still valid, removed the statements for now.

2023-01-12 11:54 UTC, Tschakki commented
Thanks, I addressed you feedback so far! But updating the Commander and Elements index is not really part of this PR, we can address it in another issue imho.

2023-01-12 12:22 UTC, TalhaMaliktz approved these changes
Sure, just a minor change as I think it can be made right away. The rest of it LGTM👍🏼.

2023-01-12 12:22 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +const lisk = require('@liskhq/lisk-codec');
I would keep the previous version of this line as in the caption we suggest: "Example with the client package"
```suggestion
const lisk = require('@liskhq/lisk-client');
```

2023-01-12 12:45 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +const lisk = require('@liskhq/lisk-codec');
👍

2023-01-12 12:56 UTC, chris529 approved these changes
LGTM! Agree with Talha 👍

2023-01-12 13:31 UTC, merged