Update source setup - closes #1606
LiskArchive/lisk-legacy-docs pull request #1687
Opened 2023-01-03 13:14 UTC by chris529

Closes #1606

2023-01-05 09:59 UTC, nagdahimanshu commented on modules/ROOT/partials/core-post-installation.adoc
>      "host": "127.0.0.1"
```suggestion
    "modes": ["ipc", "ws"]
    // In case if `modes` include `ws`, this port used
    "port": 8080,
    // Change to 0.0.0.0 to connect from a remote server
    "host": "127.0.0.1"
```

2023-01-06 13:58 UTC, TalhaMaliktz requested changes

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
>  ----
Line # 147 should be:
This section details how to install Lisk Core from the source code.

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
Line # 171 should be:
`# From another terminal`

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
>  git clone https://github.com/LiskHQ/lisk-core.git #<1>
On line # 19
Add the following hyperlink to the `README.md` file.
https://github.com/LiskHQ/lisk-core/blob/development/README.md#tests

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
>  cd lisk-core                                      #<2>
On line # 25
The internal link should be 
`<<installation, Installation>> section.`

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
> -git checkout v3.0.4 -b v3.0.4                     #<3>
On line # 94
The note doesn't add any value to the content and can be removed.

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
> +git checkout v4.0.0 -b v4.0.0                     #<3>
Line 104
`. Install NVM by following the {url_nvm_instructions}[official instructions^].`

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
>  npm install --global                              #<4>
Line 30-35 & 109
The OS versions should be re-checked coz for sidechain clients, the versions have been updated.
https://liskhq.github.io/lisk-docs/build-blockchain/create-blockchain-app.html#supported-operating-systems

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
>  ----
Line 159
<2> Navigate into the `lisk-core` root folder.

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/partials/core-post-installation.adoc
>  //Check the guide xref:{url_mgmt_pm2}[] for more information.
Line 16
`=== Enable IPC & WS in the config`

Line 20
`.Example: Enable IPC & WS via config.json`

2023-01-06 13:58 UTC, TalhaMaliktz commented on modules/ROOT/partials/core-post-installation.adoc
> +    // In case if `modes` include `ws`, this port used
```suggestion
    // In case `modes` include `ws` then, the following port is used
```

2023-01-06 14:10 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> -git checkout v3.0.4 -b v3.0.4                     #<3>
OK, I have commented it out 👍

2023-01-06 14:44 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
>  npm install --global                              #<4>
@nagdahimanshu  Can you please confirm the latest versions of dependencies for Lisk core? We have recently updated the version of dependencies and any requirements for SDK as well as mentioned in the above URL.

2023-01-12 09:37 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
>  [source,bash]
**Line 122**
Should be `16.x` since we are supporting the `16.15.0` node.js version.
`curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -`

2023-01-13 08:52 UTC, TalhaMaliktz approved these changes
Thanks, LGTM! 😊

2023-01-23 15:17 UTC, nagdahimanshu approved these changes
Looks good 👍

2023-01-23 18:10 UTC, merged