"Connecting to endpoints" guide - Closes 1583
LiskArchive/lisk-legacy-docs pull request #1689
Opened 2023-01-06 09:43 UTC by TalhaMaliktz

Closes #1583

2023-01-06 10:40 UTC, chris529 reviewed
Looks great! Just a few very minor points 👍

2023-01-06 10:40 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Blockchain applications developed with Lisk SDK communicate to a node via RPCs. RPC-based interfaces i.e. IPC, WS, or HTTP allow applications to *invoke* RPC endpoints.
```suggestion
Blockchain applications developed with the Lisk SDK communicate to a node via RPCs. RPC-based interfaces i.e., IPC, WS, or HTTP allow applications to *invoke* RPC endpoints. 
```

2023-01-06 10:40 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An API client can be imported into any JS client application as shown in the following snippets.
```suggestion
An API client can be imported into any JS client application as shown in the following snippets below.
```

2023-01-06 10:40 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Lisk also supports invoking endpoints from within the sidechain client. For more information, check out the xref:{url_sync_store}[syncing and storing] example for the `HelloInfoPlugin`. Specifically,
```suggestion
Lisk also supports invoking endpoints from within the sidechain client. For more information, check out the xref:{url_sync_store}[syncing and storing] example for the `HelloInfoPlugin`. Specifically, as shown in the the following example below:
```

2023-01-06 10:40 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Apart from the WS and IPC method, Lisk endpoints also support HTTP requests and response mechanisms. With a {JSON_RPC_Specs}[JSON RPC 2.0] based format, any endpoint can be invoked using a cURL reque
```suggestion
Apart from the WS and IPC method, Lisk endpoints also support HTTP requests and response mechanisms. With a {JSON_RPC_Specs}[JSON RPC 2.0] based format, any endpoint can be invoked using a cURL request. For example, as shown below:
```

2023-01-06 14:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An API client can be imported into any JS client application as shown in the following snippets.
"Following" and "below" are redundant.

2023-01-06 14:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Lisk also supports invoking endpoints from within the sidechain client. For more information, check out the xref:{url_sync_store}[syncing and storing] example for the `HelloInfoPlugin`. Specifically,
```suggestion
Lisk also supports invoking endpoints from within the sidechain client. For more information, check out the xref:{url_sync_store}[syncing and storing] example for the `HelloInfoPlugin`. Specifically, as shown in the the following example:
```

2023-01-09 12:21 UTC, Tschakki requested changes
Looks great already! :) Just a small remark.

2023-01-09 12:21 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Any endpoint within the Lisk ecosystem can be invoked via Lisk's CLI as well. For more information, check out the xref:{url_cli}[CLI reference page].
Would add a note for Lisk Core users

```suggestion
Any endpoint within the Lisk ecosystem can be invoked via Lisk's CLI as well.
For more information, check out the xref:{url_cli}[CLI reference page].

NOTE: If you are running *Lisk Core*, you can use nearly the same CLI commands as in the general Lisk CLI.
Just replace `./bin/run` with `lisk-core` in that case.
```

2023-01-09 13:24 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An API client can be imported into any JS client application as shown in the following snippets.
Oh yes, is not essential...it's just personal preference.

2023-01-09 13:33 UTC, chris529 approved these changes
LGTM! 👍

2023-01-09 13:35 UTC, Tschakki approved these changes
LGTM 👍

2023-01-09 13:38 UTC, merged