Update send a transaction page lisk docs
LiskArchive/lisk-legacy-docs pull request #1698
Opened 2023-01-17 08:06 UTC by chris529

Close #1579

2023-02-06 19:21 UTC, sameersubudhi requested changes
Please find my remarks below.

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  * The PoS module
Do we not plan to include the information for the supported transactions from the remaining modules as well?
Also, shouldn't they hyperlink to the respective pages?

- Auth
- Interoperability
- Legacy

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +It should be noted that in the Lisk SDK v6 the Module ID and Asset ID have been replaced with the Module name, command names, and params.
```suggestion
It should be noted that in the Lisk SDK v6 the `moduleID`, `assetID`, and `asset` properties have been replaced with the `module` (name), `command` (name), and `params` respectively.
```

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +It is sometimes used as an input or output format in the CLI when sending or creating transactions via the CLI (see xref:{url_sdk_cli}[] and xref:{url_core_cli}[Lisk core CLI]).
Do we need to mention both `url_sdk_cli` and `url_core_cli` documentation here? 🤔 
Also, hyperlink text missing: `xref:{url_sdk_cli}[]`

```suggestion
It is sometimes used as an input or output format in the CLI when sending or creating transactions via the CLI (see xref:{url_sdk_cli}[] and xref:{url_core_cli}[Lisk core CLI]).
```

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>    senderPublicKey: <Buffer 51 33 af 79 44 ac f5 27 8b 03 10 a1 1c 06 13 4f 80 ab 45 46 d7 7d 1b 0e 02 7c 84 30 a7 d2 bb 92>,
`asset` should be replaced with `params`. Also, the `params` should contain a `tokenID` for a token transfer transaction. Please consider using the example (for consistency reasons) below from L163.

It'd be better if we used the same transaction example across the entire page, including the buffer/encoded string examples.

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>    senderPublicKey: '5133af7944acf5278b0310a11c06134f80ab4546d77d1b0e027c8430a7d2bb92',
Same as above.

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  Any running node can be used to create a sendable transaction object, see xref:{url_sdk_cli}[] and Lisk Core CLI.
Hyperlink text missing: `xref:{url_sdk_cli}[]`

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +
```suggestion
$ ./bin/run transaction:send 0a05746f6b656e12087472616e7366657218002080c2d72f2a200fe9a3f1a21b5530f27f87a414b549e79a940bf24fdf2b2f05e7f22aeeecc86a32330a0800000000000000001080c2d72f1a14ab0041a7d3f7b2c290b5b834d46bdc7b7eb85815220c2273656e6420746f6b656e223a40dcca378fdaa4074e3636b0030764cd3cd5e044832cd2eea124aa4a4143da6f8077671c1294868b614df0e372dccd5ba2705ab512888632d4f43d4e13fe61f40b
Transaction with id: '364b5b273bd3d8c87df6266fd2f1a63bed7553f1bd48cd7f43255f840899032c' received by node.
```

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  After all relevant information about the transaction is given, the already encoded transaction object is returned:
```suggestion
After all relevant information for the transaction is input, the encoded transaction is returned:
```
or
```suggestion
After all relevant information for the transaction is supplied, the encoded transaction is returned:
```

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>      "senderPublicKey": "e03c09bdc8c023d94cf66a5d352e6258380210d97d545abbf75668ea3736e312",
Same as above. `asset` instead of `params`.

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  [TIP]
Missing hyperlink text below: `xref:{url_api_service_http}[]`

Also, `transactionId` in the response example must be `transactionID`.

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  const socket = io(WS_RPC_ENDPOINT, {
Missing hyperlink text in TIP below (L363): `xref:{url_api_service_rpc}[]`
Same on L370: `xref:{url_sdk_cli}[]`

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +.Creating a transaction
This section is about sending a transaction. Do we need the `Creating a transaction` section again? It's already been explained above on the same page. For user's convenience, we can perhaps set a hyperlink to the relevant section instead?

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  If the xref:{url_api_node_rpc}[] is enabled on a node, it is possible to send a transaction via WebSockets or IPC, depending on which protocol is enabled in the config.
Missing hyperlink text: `xref:{url_api_node_rpc}[]`

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>          asset: {
Same as above: `asset` instead of `params`.

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +	client.invoke("txpool_postTransaction", {
The entire example needs to be validated here, might be incorrect according to the SDKv6.
```suggestion
	client.invoke("txpool_getTransactionsFromPool", {
```

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +Finally, it is possible to perform a 'Dry run', which returns the results of executing a transaction without actually submitting it to the chain.
```suggestion
Finally, it is possible to 'dry run' a transaction, which returns the results of executing a transaction without actually submitting it to the chain.
```

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +|===
The `txpool_dryRunTransaction` endpoint also accepts a `skipVerify` boolean flag along with the `transaction` param. We should include the same here.

And, should we add a code snippet here as well, for consistency sake?

2023-02-06 19:21 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +{
This seems like a partial response. Should we include the entire response here?

2023-02-08 08:39 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  * The PoS module
Good point..However, the other modules have yet to be added to the docs as they have not yet been completed, so I have slightly restructured this paragraph to link to the modules overview page, and added in a 'TODO' comment to add the new modules in at a later date, once the respective module pages have been written.

2023-02-08 08:48 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +It is sometimes used as an input or output format in the CLI when sending or creating transactions via the CLI (see xref:{url_sdk_cli}[] and xref:{url_core_cli}[Lisk core CLI]).
Sure, we can remove the CLI links as they are provided later in this page 👍

2023-02-08 08:57 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  Any running node can be used to create a sendable transaction object, see xref:{url_sdk_cli}[] and Lisk Core CLI.
Done 👍

2023-02-08 09:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  If the xref:{url_api_node_rpc}[] is enabled on a node, it is possible to send a transaction via WebSockets or IPC, depending on which protocol is enabled in the config.
Done 👍

2023-02-08 09:12 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  [TIP]
Done 👍

2023-02-08 09:16 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  const socket = io(WS_RPC_ENDPOINT, {
Done 👍

2023-02-08 10:56 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +|===
Yes, as discussed we will add in the code snippet for consistency 👍

2023-02-08 10:59 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +{
Yes, as also discussed we will add in the snippet for the entire response here 👍

2023-02-08 11:21 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +.Creating a transaction
Good point, it is now removed 👍

2023-02-27 11:01 UTC, sameersubudhi approved these changes
LGTM 👍

2023-03-01 12:39 UTC, TalhaMaliktz requested changes

2023-03-01 12:39 UTC, TalhaMaliktz commented on build/preview-site.yml
>      idseparator: '-'
No changes should be made to the `preview-site.yml` file, so please revert these changes

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
The `Default transactions` section is outdated including the references mentioned in it. Please comment it out and add a TODO to update it once the latest information is available.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  }
Please improve the indentation.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +It should be noted that in the Lisk SDK v6 the `moduleID`, `assetID`, and `asset` properties have been replaced with the `module` (name), `command` (name), and `params` respectively.
```suggestion
It should be noted that in the Lisk SDK v6, the `moduleID`, `assetID`, and `asset` properties have been replaced with the `module` (name), `command` (name), and `params` respectively.
```

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  [source,js]
**LINE 147-150**

The API client allows external services/applications to connect with a particular node.
With an API client, information can be retrieved and sent to a node.
The API client is part of the `@liskhq/lisk-api-client` package and is also included in the `@liskhq/lisk-client` and `lisk-sdk` packages.

An example script about how to create a transaction object via the API client is described in the code snippet below:

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +
```suggestion

// For the apiClient to work in the WebSocket mode, the node must have the WebSocket mode enabled. This is true for HTTP mode as well.
```

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  === via CLI
Please add an example of sending the same transaction through a sidechain client as well. Alternatively, you can add a note about how the same transaction can be sent through a sidechain client. For example:
https://liskhq.github.io/lisk-docs/beta/integrate-blockchain/connecting-endpoints.html#invoking-via-lisk-cli

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  ----
The example is only for `ws`, however, we also support the usage of `HTTP`, and `IPC` as well. So please add a reference to the following page in a **note**, so that the reader knows about the other ways to create the `apiClient` as well.

https://liskhq.github.io/lisk-docs/beta/understand-blockchain/sdk/rpc.html#the-api-client

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  ====
The How to send the transaction section contains hyperlinks of outdated pages, please comment them.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +For more information, check out the xref:{url_api_service_http}[Mainnet HTTP API (Lisk Service)] reference.
Outdated content, the URL doesn't show anything.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +For more information, check out the xref:{url_api_service_rpc}[RPC endpoints (Lisk Service)] reference.
Might be outdated content, since we haven't updated this for v6

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +
Please add these examples in tabs, where one tab is for `lisk-core` and the other one is for the `sidechain` client.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +==== Invoking the action `txpool_postTransaction`
It is also possible to send a transaction using the `transaction.send` method so IMHO, we should rename this to something generic like sending via API client, and then add both examples to send a transaction in tabs. The other example can be found here: https://liskhq.github.io/lisk-docs/beta/integrate-blockchain/integrate-UI/faucet-transfer.html


Also hierarchy wise this should be a level 5 heading, same comment for the dry-run heading as well.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +==== `txpool_dryRunTransaction`
The section describes `txpool_dryRunTransaction` which is already described [here](https://liskhq.github.io/lisk-docs/beta/api/lisk-node-rpc.html#txpool_dryruntransaction).

On this page, we should mention its usage, via apiClient, CLI, and any other possible medium.

2023-03-01 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +	id: '08de6db36628b1f3a7175b1b889f661f9f184afa3df4eeb015698c4ac2de0d38'
Please improve the indentation.

2023-03-02 10:20 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
Done 👍

2023-03-02 12:54 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  [source,js]
Done 👍

2023-03-02 14:04 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  ----
Good point..now done 👍

2023-03-02 14:10 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  ====
I have commented them out accordingly 👍

2023-03-02 14:19 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +For more information, check out the xref:{url_api_service_rpc}[RPC endpoints (Lisk Service)] reference.
Yes, Now commented out and a TODO added 👍

2023-03-02 16:48 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +==== `txpool_dryRunTransaction`
I have added in an explanation to further complement this section 👍

2023-03-14 11:28 UTC, sameersubudhi requested changes

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> += How to create a transaction
```suggestion
= How to create and sign a transaction
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +This guide describes different methods of creating transactions to Lisk nodes.
```suggestion
This guide describes different methods of creating and signing transactions. The steps are applicable for all the applications developed with the Lisk SDK [v6](https://www.npmjs.com/package/lisk-sdk/v/latest), including the Lisk Core.
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +This guide describes different methods of creating transactions to Lisk nodes.
Please note: The [link](https://www.npmjs.com/package/lisk-sdk/v/latest) will now point to `5.2.2` (current active production version) but should refer to SDK v6 on the NPM registry once Lisk SDK is deployed to the production/mainnet.

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +// == Default transactions
This entire section for `Default transactions` can probably be moved to a separate page.

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>      amount: 800000000n,
```suggestion
  module: 'token',
  command: 'transfer',
  fee: 1000000n,
  params: {
    tokenID: <Buffer 04 00 00 00 00 00 00 00>,
    amount: 800000000n,
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +id: <Buffer 08 de 6d b3 66 28 b1 f3 a7 17 5b 1b 88 9f 66 1f 9f 18 4a fa 3d f4 ee b0 15 69 8c 4a c2 de 0d 38>
```suggestion
  },
  nonce: 0n,
  senderPublicKey: <Buffer 39 72 84 9f 2a b6 63 76 a6 86 71 c1 0a 00 e8 b8 b6 7d 88 04 34 cc 65 b0 4c 6e d8 86 df a9 1c 2c>,
  signatures: [
    <Buffer 96 0a 67 e3 04 7d bc 1b d2 e2 d1 30 6d 47 36 74 86 7e b8 1f df 90 ec 65 f5 75 9c 1a 1e c4 07 f5 ba f9 87 1c a7 63 75 55 7c 7b 23 e2 25 ae 60 cd da 65 ... 14 more bytes>
  ],
  id: <Buffer 08 de 6d b3 66 28 b1 f3 a7 17 5b 1b 88 9f 66 1f 9f 18 4a fa 3d f4 ee b0 15 69 8c 4a c2 de 0d 38>
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>      amount: '800000000',
```suggestion
  module: 'token',
  command: 'transfer',
  fee: '1000000',
  params: {
    tokenID: '0400000000000000',
    amount: '800000000',
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +id: '08de6db36628b1f3a7175b1b889f661f9f184afa3df4eeb015698c4ac2de0d38'
```suggestion
  },
  nonce: '0',
  senderPublicKey: '3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c',
  signatures: [
    '960a67e3047dbc1bd2e2d1306d473674867eb81fdf90ec65f5759c1a1ec407f5baf9871ca76375557c7b23e225ae60cdda65fdce385bae076131ad5f7e39df0b'
  ],
  id: '08de6db36628b1f3a7175b1b889f661f9f184afa3df4eeb015698c4ac2de0d38'
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
>  In the case whereby a higher level of security is desired, it is possible to create the transaction in a completely stand-alone offline environment.
```suggestion
In the case whereby a higher level of security is desired, it is also possible to create the transaction in a completely stand-alone offline environment.
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +With an API client, information can be retrieved and sent to a node.
```suggestion
The API client allows external services/applications to connect and interact with a particular node.
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +For further information regarding other methods for creating the `apiClient` this can be found on the xref:{url_api_client}[RPC] page.
```suggestion
The following example below demonstrates how to create a transaction using the Lisk API client. The API client can be instantiated using both `WS` and `IPC`.

The API client can also be used to query information from the node by invoking the supported endpoints over RPC. For more information regarding the same, please check the xref:{url_api_client}[RPC - The API client] page.
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +==== via IPC
Please merge the `via IPC` and `via WebSocket` sections and rename them to `Enabling IPC, WebSocket and HTTP APIs`. Also, remove the code snippets from under these sections.
```suggestion
==== Enabling IPC, WebSocket and HTTP APIs
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +This can be achieved by adding the IPC configuration option to your Lisk node's configuration file as shown below:
```suggestion
There are two ways to expose the node APIs via IPC, WS and HTTP.
1. Use the following command like flags when starting the application:
  - `--api-ipc`: Enable API over IPC
  - `--api-ws`: Enable API over WS
  - `--api-http`: Enable API over HTTP
  - `--api-host=127.0.0.1`: IP over which the API is exposed. Use `0.0.0.0` to expose the API on all available ethernet IP instances
  - `--api-port=7887`: Port on which the API is exposed
2. This can also be achieved by adding the RPC configuration option to your Lisk node's configuration file as shown below. To enforce the config changes `--overwrite-config` flag must be passed when starting the application. To supply a custom file use the `--config=</path/to/custom/config>` flag:
```

Also, please add the following information in a NOTE:
- When WS is enabled, the API can be accessed on `/rpc-ws` path
- When HTTP is enabled, the API can be accessed on `/rpc` path

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +----
```suggestion
[source,jsonc]
----
{
  "rpc": {
    "modes": ["ipc", "ws", "http"], // Only specify the modes you need to enable
    "port": 7887,
    "host": "127.0.0.1" // Use `0.0.0.0` to expose them on all available ethernet IP instances
  },
}
----
----
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +It will be necessary to replace the `/path/to/ipc/socket` in the snippet above with the path to your IPC socket file.
L249-339 (until before the `=== via CLI` section) can be removed.

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +An example for creating and sending a transfer transaction with the Lisk Core CLI is displayed below:
```suggestion
The application CLI can be used to create a sendable transaction object to any running node. An example for creating and sending a transfer transaction with the Lisk Core CLI is displayed below:
// see xref:{url_sdk_cli}[Application CLI] and xref:{url_core_cli}[Lisk Core CLI].
//TODO: Add in above links when SDKv6 and Core docsv4 are released
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +Just replace `lisk-core` with `./bin/run` in that case.
```suggestion
NOTE: When planning to run the same transaction through a sidechain client, the same CLI commands as in the general Lisk CLI. Just replace `lisk-core` with the application's CLI tool or use `./bin/run` building the application from the source code.
```

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +==== Lisk Core CLI / Sidechain CLI
Please remove L394-428 (before the `== How to sign a transaction` section begins) since this is no more necessary.

2023-03-14 11:28 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +== How to sign a transaction
This entire section can be removed now since all the methods above to create transaction now create signed transactions. Hence, the section is now irrelevant.

2023-03-14 13:10 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +This guide describes different methods of creating transactions to Lisk nodes.
Good point...This PR will be merged into our latest version of the docs which is currently in beta, and only available on staging at the moment. So I will add this in, but comment it out with a "TODO:" note, to uncomment it when SDK v.6 is ready 👍

2023-03-14 13:26 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +// == Default transactions
Yes, I think you are right, they are commented out at the moment. 👍

2023-03-14 22:22 UTC, sameersubudhi requested changes

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +The steps are applicable for all the applications developed with the Lisk SDK and Lisk Core.
```suggestion
The steps are applicable for all the applications developed with the Lisk SDK, including Lisk Core.
```

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +Further details can be found in the xref:{url_migration_guide}[SDK migration guide].
Could you please share the details specified within the SDK migration guide?
The contents will decide if we need to specify this here.

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +For convenience, it is recommended to use the API client or the CLI to communicate to a node for creating transactions.
```suggestion
For convenience, it is recommended to use the API client or the CLI to communicate to a node for creating and signing transactions.
```

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +1.Use the following command like flags when starting the application:
```suggestion
1. Use the following command line flags when starting the application:
```

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +2.This can also be achieved by adding the RPC configuration option to your Lisk node's configuration file as shown below.
```suggestion
2. This can also be achieved by adding the RPC configuration option to your Lisk node's configuration file as shown below.
```

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +To supply a custom file use the `--config=</path/to/custom/config>` flag:
The example config changes as suggested [here](https://github.com/LiskHQ/lisk-docs/pull/1698#discussion_r1135365533) seem to be missing below.

```suggestion
To supply a custom file use the `--config=</path/to/custom/config>` flag:

[source,jsonc]
----
{
  "rpc": {
    "modes": ["ipc", "ws", "http"], // Only specify the modes you need to enable
    "port": 7887,
    "host": "127.0.0.1" // Use `0.0.0.0` to expose them on all available ethernet IP instances
  },
}
----
```

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +In addition, when HTTP is enabled the API can be accessed via the `/rpc` path.
```suggestion
NOTE: Please note that when the WS mode is enabled, the API can be accessed via the `/rpc-ws` path.
And, when the HTTP mode is enabled the API can be accessed via the `/rpc` path.
```

2023-03-14 22:22 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +When using the CLI please ensure that the API is enabled over IPC.
```suggestion
NOTE: When creating the transaction against a sidechain node, same command (`transaction:create`) can be used. Please replace `lisk-core` with the corresponding application's CLI tool or use `./bin/run` as the CLI tool, when building the application binary from the source code.

When using the CLI please ensure that the API is enabled over IPC.
```

2023-03-17 11:31 UTC, Tschakki commented
As we are separating the guides, please also update the file name from `create-send-transactions.adoc` to something like `creating transactions.adoc`

2023-03-21 15:39 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-send-transactions.adoc
> +Further details can be found in the xref:{url_migration_guide}[SDK migration guide].
Discussed offline and now cleared 👍

2023-03-21 15:53 UTC, sameersubudhi approved these changes
Thank you for the changes. LGTM 👍

2023-03-22 13:56 UTC, TalhaMaliktz requested changes
Looking good! A few suggestions.

2023-03-22 13:56 UTC, TalhaMaliktz commented on build/preview-site.yml
> +    - ./lib/tabs-block/extension.js
```suggestion
  - ./lib/tabs-block/extension.js
```

2023-03-22 13:56 UTC, TalhaMaliktz commented on build/preview-site.yml
> +    snapshot: true
```suggestion
   url: ../ui/build/ui-bundle.zip
   snapshot: true
```

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +Used as an input/output format for functions in xref:{url_references_elements}[Lisk Elements].
No corresponding URL for variable: `url_references_elements`, please add the URL.

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +====
The content referred to in the note needs an update, please comment this note for now and add a TODO.

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +Furthermore, when the HTTP mode is enabled the API can be accessed via the `/rpc` path.
This section shouldn't be part of this guide IMHO. We should move this to the [page](https://liskhq.github.io/lisk-docs/beta/understand-blockchain/sdk/rpc.html) we are referring to at line 166 as that page is more suitable for such information.

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +====
The term 'Example' doesn't render nicely, I would remove the collapsible tab and will do something like:

```suggestion
[TIP]
====
To also see the decoded transaction object on creation, add the `--json` parameter:

.Transaction in binary and JSON format
[source,bash]
----
$ lisk-core transaction:create token transfer 100000000 --json
? Please enter passphrase:  [hidden]
Warning: Passphrase contains 24 words instead of expected 12. Passphrase contains 23 whitespaces instead of expected 11.
? Please enter: tokenID:  0400000000000000
? Please enter: amount:  800000000
? Please enter: recipientAddress:  lskt8ovj2shbxrtno8xqqt7cnmzzygdkbt6brnvmj
? Please enter: data:  Happy birthday!
{"transaction":"0a05746f6b656e12087472616e7366657218042080c2d72f2a203972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c32370a080400000000000000108090bcfd021a149bd82e637d306533b1e1ad66e19ca0047faa1a6a220f4861707079206269727468646179213a40c06cd0ef375911528d491971296532dbd58725f0fccc0f23e6c0656c43e75ecd12635616117e64d005f1c9f2a55de7cf2d8f5cb961927d839d141a18faa80e08"}
{"transaction":{"module":"token","command":"transfer","fee":"100000000","nonce":"4","senderPublicKey":"3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c","signatures":["c06cd0ef375911528d491971296532dbd58725f0fccc0f23e6c0656c43e75ecd12635616117e64d005f1c9f2a55de7cf2d8f5cb961927d839d141a18faa80e08"],"params":{"tokenID":"0400000000000000","amount":"800000000","recipientAddress":"lskt8ovj2shbxrtno8xqqt7cnmzzygdkbt6brnvmj","data":"Happy birthday!"},"id":"f3f537bbd52464d2f97c02f5ef0f9a805d19ad4f8ef1c7efa1da17cef0e5036a"}}
----
====
```

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +The steps are applicable for all the applications developed with the Lisk SDK, including Lisk Core.
```suggestion
The steps apply to all the applications developed with the Lisk SDK, including Lisk Core.
```

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +=== JSON compatible object
```suggestion
=== JSON-compatible object
```

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +A representation of the decoded transaction in a JSON compatible format.
```suggestion
A representation of the decoded transaction in a JSON-compatible format.
```

2023-03-22 13:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +The application CLI can be used to create a sendable transaction object to any running node. An example for creating and sending a transfer transaction with the Lisk Core CLI is displayed below:
```suggestion
The application CLI can be used to create a sendable transaction object to any running node. 
An example of creating and sending a transfer transaction with the Lisk Core CLI is displayed below:
```

2023-03-22 15:14 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +====
Now commented out and TODO added 👍

2023-03-23 11:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +Furthermore, when the HTTP mode is enabled the API can be accessed via the `/rpc` path.
Good point, it has now been removed and will be added in to complement the 'Communicating to a Lisk node via RPC' page 👍

2023-03-23 14:15 UTC, TalhaMaliktz approved these changes
Please correct the following minor issues. The rest LGTM 👍🏼

2023-03-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/nav.adoc
> +
The nav looks like the following image. I am not sure but probably, removing the spaces might correct the issue.
![Untitled](https://user-images.githubusercontent.com/13951043/227229815-2473df3d-84d0-491a-a704-ed29ea98d9ff.png)
```suggestion
// ** xref:integrate-blockchain/calculating-min-fee.adoc[]
** xref:integrate-blockchain/create-sign-transactions.adoc[]
```

2023-03-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-sign-transactions.adoc
> +:url_references_elements: lisk-sdk::references/lisk-elements/index.adoc
Points to SDK V5 docs
```suggestion
:url_references_elements: {sdk_docs}references/lisk-elements/index.adoc
```

2023-03-24 12:36 UTC, merged