Retrieving on-chain events - Closes 1584
LiskArchive/lisk-legacy-docs pull request #1699
Opened 2023-01-18 07:53 UTC by TalhaMaliktz

Closes #1584

2023-01-18 10:10 UTC, chris529 approved these changes
LGTM! 👍

2023-01-19 10:35 UTC, Tschakki requested changes
Looking really nice, just some small suggestions :)

2023-01-19 10:35 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +By default, a sidechain client is configured to store events for the latest 300 blocks.
Just to clarify and emphasize on this important information

```suggestion
By default, a sidechain client is configured to store events for the latest 300 blocks. 
That means, *blockchain events can only be received for the 300 latest blocks by default.*
```

2023-01-19 10:35 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +
This can be also a useful hint at this point.

```suggestion

TIP: To store the blockchain events on a node forever, set `keepEventsForHeights` to `0` in the sidechain client's config.

```

2023-01-19 10:35 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +
To clarify the important difference how events are retrieved.

```suggestion

NOTE: Different to the RPC events, blockchain events cannot be directly subscribed.
Instead, *blockchain events are requested for a particular block.*
The block is defined by the block height which is provided as a parameter in the request.

```

2023-01-20 10:03 UTC, Tschakki requested changes

2023-01-20 10:03 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +To store the blockchain events on a node forever, set `*keepEventsForHeights*` to `0` in the sidechain client's config.
```suggestion
The number of events stored by the event log depends on the configuration of the node. 
By default, a node is *configured to store the blockchain events from the latest 300 blocks* in the event log. 
Due to this, events from only those 300 blocks can be retrieved, by default. 
This can be changed by updating the `*keepEventsForHeights*` property in the xref:{url_sdk_config_system}[node configuration].

To store the blockchain events on a node forever, set `keepEventsForHeights` to `0` in the node configuration.
```

2023-01-20 10:03 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +To store the blockchain events on a node forever, set `*keepEventsForHeights*` to `0` in the sidechain client's config.
After reading it again, I think `node` fits better to the context here, as we talk about an instance of a `sidechain client`.

I also added a link to the relevant docs of the node configuration.

2023-01-20 10:03 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +:url_understand_events: {url_advanced_rpc}#events
```suggestion
:url_sdk_config_system: {docs_sdk}config.adoc#system
:url_understand_events: {url_advanced_rpc}#events
```

2023-01-20 10:44 UTC, Tschakki approved these changes
Nice!

2023-01-20 10:45 UTC, merged