Update in bug-bounty program page
LiskArchive/lisk-legacy-docs pull request #1706
Opened 2023-01-27 10:26 UTC by chris529

Closes #1703

2023-01-30 12:19 UTC, TalhaMaliktz requested changes

2023-01-30 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +image::intro/bug-bounty-diagram.png[ align="center"]
The label for **Medium** should be yellow, but it is green in the image.

2023-01-30 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +// image::intro/bug-bounty-payout1.png[ align="center"]
There is a point in the issue description, which I am not sure about. @Tschakki Please elaborate.
> Add a form somewhere on the new website.

2023-01-30 12:25 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
>  image::intro/bug-reportform1.png[role="related thumb right",200]
What is CHF? and should CHF be LSK?

2023-01-30 12:26 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +image::intro/bug-bounty-diagram.png[ align="center"]
What is **CHF**? and should **CHF** be **LSK**?

2023-01-30 12:28 UTC, chris529 commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +image::intro/bug-bounty-diagram.png[ align="center"]
This is correct as the payouts are in Swiss Francs, and the international currency symbol for the Swiss Franc is CHF.

2023-01-30 12:32 UTC, chris529 commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +// image::intro/bug-bounty-payout1.png[ align="center"]
Ah, this was choice between either adding a new report  form or requesting an email. imho, I think it is more preferable for the user to be able to describe the vulnerabilities/bugs found in his own words.

2023-01-30 12:34 UTC, chris529 commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +image::intro/bug-bounty-diagram.png[ align="center"]
Good point Talha, I will go back to Rita and ask her to update this 👍

2023-02-01 08:26 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-02-01 08:29 UTC, TalhaMaliktz requested changes

2023-02-01 08:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +image::intro/bug-bounty-diagram1.png[ align="center"]
I would replace the existing diagram (bug-bounty-diagram) and not add the new diagram file (bug-bounty-diagram1) as this file may have been referenced on other pages as well.

2023-02-02 08:20 UTC, chris529 commented on docs/modules/ROOT/pages/bug-bounty-program.adoc
> +image::intro/bug-bounty-diagram1.png[ align="center"]
Now done 👍

2023-02-07 08:33 UTC, TalhaMaliktz approved these changes
Thanks, LGTM 🎉

2023-02-07 11:17 UTC, closed without merging