Update mainnet and testnet urls in index page in service docs
LiskArchive/lisk-legacy-docs pull request #1709
Opened 2023-01-30 16:36 UTC by chris529

Closes #1627

2023-01-31 11:39 UTC, sameersubudhi requested changes
The API has been updated. Request you to kindly make the following changes to reflect the same.

2023-01-31 11:39 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
>  .Example request: Obtain a list of all 101 currently forging delegates
```suggestion
.Example request: Obtain a list of generators in the current round
```

2023-01-31 11:39 UTC, sameersubudhi commented on modules/ROOT/pages/index.adoc
> +curl -X GET "http://localhost:9901/api/v3/forgers" -H  "accept: application/json"
```suggestion
curl -X GET "http://localhost:9901/api/v3/generators" -H  "accept: application/json"
```

2023-02-01 09:33 UTC, sameersubudhi approved these changes
LGTM 👍

2023-02-01 13:48 UTC, TalhaMaliktz reviewed
The changes LGTM, however, I was not able to access the dynamic pages/content generated by swagger. Can you access them?

2023-02-01 14:46 UTC, sameersubudhi commented
@TalhaMaliktz The mainnet migration hasn't happened yet. So, deployments are not yet live. Hence, you won't be able to access them! 🙂

2023-02-01 14:54 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-02-01 15:41 UTC, Tschakki commented
@chris529 I think there was a misunderstanding, the issue #1627 is actually referring to a bug in our currently live documentation. That means, this PR should be opened against the `docs-service-v0.6` branch which is storing the docs for Lisk Service 0.6

2023-02-02 18:02 UTC, merged