Update mainnet and testnet urls in index page in service docs v0 6
LiskArchive/lisk-legacy-docs pull request #1711
Opened 2023-02-02 11:16 UTC by chris529

Closes #1627

2023-02-23 11:14 UTC, TalhaMaliktz requested changes

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +:url_api_mainnet: https://service.lisk.com/api/v3/
```suggestion
:url_api_mainnet: https://service.lisk.com/api/v2/
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +:url_api_testnet: https://testnet-service.lisk.com/api/v3/
```suggestion
:url_api_testnet: https://testnet-service.lisk.com/api/v2/
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +:url_rpc_api_testnet: wss://testnet-service.lisk.com/rpc-v3
```suggestion
:url_rpc_api_mainnet: wss://service.lisk.com/rpc-v2
:url_rpc_api_testnet: wss://testnet-service.lisk.com/rpc-v2
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +curl -X GET "http://localhost:9901/api/v3/generators" -H  "accept: application/json"
```suggestion
curl -X GET "http://localhost:9901/api/v2/forgers" -H  "accept: application/json"
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +const WS_RPC_ENDPOINT = 'ws://localhost:9901/rpc-v3';
```suggestion
const WS_RPC_ENDPOINT = 'ws://localhost:9901/rpc-v2';
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +//const WS_RPC_ENDPOINT = "wss://service.lisk.com/rpc-v3";
```suggestion
//const WS_RPC_ENDPOINT = "wss://service.lisk.com/rpc-v2";
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/reference/api-testnet.adoc
> +:page-swagger-url: https://testnet-service.lisk.com/api/v3/spec
```suggestion
:page-swagger-url: https://testnet-service.lisk.com/api/v2/spec
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/reference/api.adoc
> +:page-swagger-url: https://service.lisk.com/api/v3/spec
```suggestion
:page-swagger-url: https://service.lisk.com/api/v2/spec
```

2023-02-23 11:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/index.adoc
> +.Example request: Obtain a list of generators in the current round
```suggestion
.Example request: Obtain a list of all 101 currently forging delegates
```

2023-02-27 11:11 UTC, sameersubudhi approved these changes
LGTM 👍

2023-02-28 09:17 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-03-01 09:25 UTC, merged