Update run blockchain index page  in lisk docs
LiskArchive/lisk-legacy-docs pull request #1712
Opened 2023-02-03 16:27 UTC by chris529

Closes #1701

2023-02-15 12:34 UTC, Tschakki requested changes
Please double check the links on the page, see my comments below

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +:url_protocol_voting: understand-blockchain/lisk-protocol/consensus-algorithm.adoc#delegates-voting_and-delegates-weight
This link is outdated

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +A xref:{url_run_blockchain}[blockchain node] is a server with a running blockchain client, such as xref:{url_core}[].
this link is broken

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Nodes are usually connected to other nodes running the same client via xref:{url_p2p}[P2P].
this link is going to SDKv5 docs

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +To acquire a secure validator spot for a block generation round, it is necessary for a validator to be one of the top 103 validators with the most xref:{url_glossary_validatorweight}[validator weight
As we have a dedicated section explaining the validator weight in the docs, imho it is better to link to this section directly: `run-blockchain/staking.adoc#validator-weight`

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +For further information see xref:{url_protocol_voting}[Validators, staking, and validator weight] about the staking process in the Lisk Protocol.
again, this is going to outdated content

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +* xref:{url_run_reset}[Resetting and snapshotting the blockchain]
These links were commented out because they lead to outdated content. please leave them commented out.

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +// Further guides for validators
Remove/comment out link to Docker setup guide below

2023-02-15 12:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +To acquire a more in-depth overview of staking and how to earn additional LSK tokens within the Lisk network, please see the xref:{url_staking_guide}[Staking guide].
link is broken

2023-02-15 13:18 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +A xref:{url_run_blockchain}[blockchain node] is a server with a running blockchain client, such as xref:{url_core}[].
Ah yes, thanks Mona, this link is not actually required here so it has been removed 👍

2023-02-15 13:51 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +To acquire a secure validator spot for a block generation round, it is necessary for a validator to be one of the top 103 validators with the most xref:{url_glossary_validatorweight}[validator weight
Good point...done 👍

2023-02-15 14:14 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +For further information see xref:{url_protocol_voting}[Validators, staking, and validator weight] about the staking process in the Lisk Protocol.
Thanks Mona, now corrected accordingly 👍

2023-02-15 14:32 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +To acquire a more in-depth overview of staking and how to earn additional LSK tokens within the Lisk network, please see the xref:{url_staking_guide}[Staking guide].
Thanks Mona, Now fixed 👍

2023-02-15 16:20 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +:url_protocol_voting: understand-blockchain/lisk-protocol/consensus-algorithm.adoc#delegates-voting_and-delegates-weight
Thanks Mona, well spotted.. It has now been removed 👍

2023-02-16 14:28 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Nodes are usually connected to other nodes running the same client via xref:{url_p2p}[P2P].
Good point...This was going to the older version...It is now commented out, and the tentative link is pointing to a newer version of Typedocs for the Lisk/elements/P2P reference. So after the beta version is rolled out, we can uncomment this link.

2023-02-16 15:42 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Nodes are usually connected to other nodes running the same client via xref:{url_p2p}[P2P].
Good point...The older P2P link was pointing to SDKv5, and it is now updated (and commented out at the moment),as it is linked to a later version of Typedocs for Lisk elements/P2P. So if you agree, once the beta version is rolled out we can uncomment and check the updated link.

2023-02-17 14:17 UTC, Tschakki requested changes

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  Together, they form the network that is maintaining the blockchain.
Please read through the whole document to verify if diagrams and content actually match and complement each other. 

```suggestion
Together, they form the network that is maintaining the blockchain.

Depending on the node configuration, a node can have different roles in the network.
The two most important roles are <<rpc-enabled-nodes>> and <<validators-nodes>>, illustrated in the diagram below:
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  == Nodes
```suggestion
== RPC enabled nodes
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  Nodes are, as the name suggests, blockchain nodes without block generation enabled.
```suggestion
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
```suggestion
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Generally, non-validator nodes are used by external services to get or send data to the blockchain if they have enabled the <<RPC API>>.
```suggestion
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  Additionally, non-validator nodes can be used to create snapshots/backups of the blockchain, if desired.
```suggestion
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  If the RPC API of a node is enabled, it allows external services to send queries to the node and/or to subscribe to specific events that are happening in the network.
Please remove the line `=== RPC API` above.

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  == Nodes
Why do we still have this section with an explanation that has no connection to the diagram and content above?
Please update the section heading as suggested, and align the content as well.

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +// * *RPC endpoints*: xref:{url_understand_endpoints}[]
This can refer to here: https://liskhq.github.io/lisk-docs/beta/api/lisk-node-rpc.html

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  During a block generation round, every validator node has the opportunity to generate at least one block.
I would move this paragraph above the previous paragraph.

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +To learn how to become a validator, please check out the following guide: xref:{url_validator}[How to become a validator].
```suggestion
```

This is already covered int he next section

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +{url_github_lisk_service}[Lisk Service^] is a data aggregation service that connects to a particular blockchain node and aggregates the blockchain data, to provide enriched API endpoints for other ap
```suggestion
{url_github_lisk_service}[Lisk Service^] is a data aggregation service that connects to a particular <<rpc-enabled-nodes,RPC enabled node>> and aggregates the blockchain data, to provide enriched API endpoints for other applications and services that rely on data from the blockchain.
```

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== Block generation
This section has similar topic as section "Acquiring an active validator spot" so please try to merge them

2023-02-17 14:17 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +For further in-depth information and how to set up the "Report Misbehavior" plugin, please see the following guide: xref:{url_enabling_misbehavior}[Enabling report misbehavior] in this section.
I don't think we updated the "enabling misbehavior report plugin" guide, so please remove/comment out this section.

2023-02-17 15:51 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  If the RPC API of a node is enabled, it allows external services to send queries to the node and/or to subscribe to specific events that are happening in the network.
Done 👍

2023-02-17 17:02 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +// * *RPC endpoints*: xref:{url_understand_endpoints}[]
Done 👍

2023-02-20 10:55 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  == Nodes
Good point. I have now updated both the diagram and also the content below, so it now pertains more to the diagram.

2023-02-20 13:59 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== Block generation
Agreed.. Thanks for he feedback Mona, I think it does flow better now. 👍

2023-02-20 14:11 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +For further in-depth information and how to set up the "Report Misbehavior" plugin, please see the following guide: xref:{url_enabling_misbehavior}[Enabling report misbehavior] in this section.
Yes, good point Mona, the "enabling misbehavior report plugin" guide is not yet updated, so I have commented it out and left a TODO: to uncomment it when the guide is updated. 👍

2023-02-21 11:11 UTC, Tschakki approved these changes
Looking great  🎉

2023-02-21 11:11 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +This is covered in more detail, together with the necessary conditions required, which can be found on the xref:{url_enable_block_gen}[Enable block generation page].
```suggestion
This topic is covered in more detail on the xref:{url_enable_block_gen}[Enable block generation page].
```

2023-02-21 11:11 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +This is covered in more detail, together with the necessary conditions required, which can be found on the xref:{url_enable_block_gen}[Enable block generation page].
i think this sentence can be simplified

2023-02-21 15:21 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +This is covered in more detail, together with the necessary conditions required, which can be found on the xref:{url_enable_block_gen}[Enable block generation page].
Agreed...Now done 👍

2023-02-24 13:31 UTC, TalhaMaliktz requested changes
Looks good! Minor suggestions :)

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
>  image::run-blockchain/node-service-network.png[Node network, 800]
The border for the legend: "Ext" is gray, which should be pink.

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== RPC enabled nodes
```suggestion
== RPC-enabled nodes
```

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Staking can be defined as the process of holding and locking up a certain amount of LSK tokens to participate and validate transactions, in order to determine who secures the network.
```suggestion
Staking can be defined as the process of holding and locking up a certain amount of LSK tokens to participate in validating transactions, in order to determine who secures the network.
```

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +The two most important roles are <<RPC enabled nodes>> and <<Validator nodes>>, illustrated in the diagram below:
```suggestion
The two most important roles are <<RPC enabled nodes>> and <<Validator nodes>>, as illustrated in the diagram below:
```

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
```suggestion

For more information, see the following:
```

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
@Tschakki isn't the 103 validator thing true for sidechain as well?

2023-02-24 13:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +If starting to enable block generation for the first time, it is highly recommended to first check out the dedicated guide: xref:{url_validator}[How to become a validator].
```suggestion
When enabling block generation for the first time, it is highly recommended to first check out the dedicated guide: xref:{url_validator}[How to become a validator].
```

2023-02-24 14:25 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== RPC enabled nodes
@TalhaMaliktz I did have this as RPC-enabled nodes originally, although Mona suggested to change it to RPC enabled nodes.

2023-02-24 14:30 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== RPC enabled nodes
RPC and enabled should be read as compound modifiers, hence the hyphen.

2023-02-24 14:36 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== RPC enabled nodes
OK, yes, fair point...I will now update it 👍

2023-02-24 14:40 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
It is true for the default value in a newly initialized sidechain, but this can be configured differently by the sidechian developer :)

2023-02-24 14:47 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
@TalhaMaliktz @Tschakki  If i understand correctly, the number of validators on a sidechain can differ from the number of validators on the mainchain..However, perhaps we should we reword this line to the something like the following..?
"In the Lisk blockchain, there is a maximum number of 103 validators that can exist in the network for each block generation round".
Thoughts...?

2023-02-24 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
For mainnet the 103 number isn't configurable?

2023-02-24 14:55 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
If the mainnet 103 number isn't configurable then the current sentence is correct in my opinion. If both mainnet and sidechain are configurable then I guess we can use **Lisk Blockchain** instead of **Lisk Mainnet**.

2023-02-24 15:31 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
The number of validators is not configurable by a single node operator in a running network liek the Mainnet. Doing so would require a hardfork in the network. So this value can be considered as a constant in the current mainnet.

2023-02-24 15:35 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk Mainnet, exactly 103 validators exist in the network for each block generation round.
OK cool. Then we will leave it as it is, Many thanks 👍

2023-02-24 15:56 UTC, merged