Create "Integrate UI" related guides - Closes 1708
LiskArchive/lisk-legacy-docs pull request #1715
Opened 2023-02-17 09:31 UTC by TalhaMaliktz

Closes #1708

2023-02-21 15:05 UTC, chris529 reviewed
Looks great! Just some small points 👍

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +. xref:{url_faucet_transfer}[]: Seeding a new account with a faucet and transferring LSKs to a given account.
```suggestion
. xref:{url_faucet_transfer}[]: Seeding a new account with a faucet and transferring LSK tokens to a given account.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +View the complete sample code of the complete "Hello World" sidechain application on GitHub in the {url_github_guides_module}[Lisk SDK examples repository^].
```suggestion
View the complete sample code of the "Hello World" sidechain application on GitHub in the {url_github_guides_module}[Lisk SDK examples repository^].
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +View the complete sample code of the complete "Hello World" sidechain application on GitHub in the {url_github_guides_module}[Lisk SDK examples repository^].
We have too many instances of 'complete' in the above sentence.

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +image::integrate-blockchain/hello-sApp.png["Hello sApp overview", 650]
In the hello-sApp.png overview diagram, I would recommend we make the following minor updates:

In the “hello Frontend” section I would suggest we change the following statements regarding the UI:
‘A faucet to credit LSKs to a newly created account”  to the following:
“A faucet to credit LSK tokens to a newly created account”

“Send LSKs across accounts on the sidechain” should read as the following:
“Send LSK tokens across accounts on the sidechain”

In addition, in the “Hello Client” section, in the Hello module store boxes, I would suggest we make the following minor correction:

- Hallo message counter
		”is of type no.”    This should read as “Is of type no.” to maintain the uniformity, (starting with upper case).

Also in the adjacent “Config” box, The 3 lines below “Module config options” should also start with upper case
- Maximum message length
- Minimum message length
- Blacklist of censored words

Finally, in all 3 sections, (Hallo Frontend, Lisk Client and Hello Client), there are some statements that end with periods. To maintain uniformity we should either end all statements with a period, or have no periods at all.

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +TIP: The relevant files discussed in this guide are {url_newAccount}[newAccount.js] and {url_getAccountDetails}[getAccountDetails.js]
```suggestion
TIP: The relevant files discussed in this guide are the {url_newAccount}[newAccount.js] and the {url_getAccountDetails}[getAccountDetails.js].
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +To display the credentials generated above, we will need to update the `return` function as well.
```suggestion
To display the credentials generated above, it will also be necessary to update the `return` function.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +Start both xref:{url_start_client}[*hello_client*] and {url_start_frontend}[*hello_frontend*^] and click on the *Account->Create Account* option in the menu bar.
```suggestion
Start both the xref:{url_start_client}[*hello_client*] and the {url_start_frontend}[*hello_frontend*^], and then click on the *Account->Create Account* option in the menu bar.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +On page load, you'll see the credentials of the new account.
```suggestion
Once the page has loaded, the credentials of the new account will be visible.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +The UI will show you the details of the account similar to the following snapshot:
```suggestion
The UI will display the account details similar to the following snapshot:
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +Alternatively, if something goes wrong, the UI will also display the appropriate error, since in the `displayData` function we have implemented the UI for <<error-display, error handling>> as well.
```suggestion
In the case whereby an error occurs, this will be displayed in the UI, as in the `displayData` function we have also implemented <<error-display, error handling>>.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +With account creation and details retrieval working, on this page, you'll learn how to seed a new account with a faucet and how to transfer LSKs to a given account.
```suggestion
On this page, you'll learn how to seed a new account with a faucet, and how to transfer LSK tokens to a given account.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +With account creation and details retrieval working, on this page, you'll learn how to seed a new account with a faucet and how to transfer LSKs to a given account.
imho, I would suggest we omit the first part of the sentence above, (With account creation and details retrieval working), as we have already explained this.

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +* [x] How to send LSKs from/to a given account.
```suggestion
* [x] How to send LSK tokens both to and from a given account.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +TIP: The relevant files discussed in this guide are {url_faucet}[faucet.js] and {url_transfer}[transfer.js].
```suggestion
TIP: The relevant files discussed in this guide are the {url_faucet}[faucet.js] and the {url_transfer}[transfer.js].
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +The idea of a faucet is to allow an account holder to seed their account with 10 LSKs via a dedicated faucet account.
```suggestion
The aim of a faucet is to allow an account holder to seed their account with 10 LSK tokens via a dedicated faucet account.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +First up, define the necessary variables and the `handleChange` event.
```suggestion
Firstly, define the necessary variables and the `handleChange` event.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +        // 5. Once a transaction is created, it will be sent to the node and after block execution, the account's balance will increment with 10 LSKs.
```suggestion
        // 5. Once a transaction is created, it will be sent to the node and after block execution, the account's balance will increment with 10 LSK tokens.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Our code for creating and sending a transaction is complete, let's add the logic to display the response received from the node.
```suggestion
The code for creating and sending a transaction is now complete, let's add the logic to display the response received from the node.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Finally, the `return` function needs an update, so that form submission, listing data, and on-change event can be functional.
```suggestion
Finally, the `return` function needs an update, to ensure that the form submission, listing of data, and the on-change event can be functional.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +The faucet page is now ready, open the *Faucet* page and enter an account address in it.
```suggestion
The faucet page is now ready, open the *Faucet* page and enter an account address.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Click on the *Submit* button, if the address is correct and the faucet account has enough balance, your transaction will be successful and an appropriate response will be shown on the screen.
```suggestion
Click on the *Submit* button, if the address is correct and the faucet account has an adequate balance, your transaction will be successful and an appropriate response will be displayed on the screen.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +.Faucet to seed 10 LSKs to any account
```suggestion
.Faucet to seed 10 LSK tokens to any account
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +image::integrate-blockchain/integrate-ui/faucet.jpg["faucet page", 800]
In the Faucet.jpg diagram, imho I would suggest we mention the following:
“The faucet transfers tokens from the genesis account to another account”

Also regarding the transaction details,  it seems that the noun form is incorrect. Imho it should read as:  “ Your transaction details are:”

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +To check if the account balance has increased, use the xref:{url_checkBalance}[account's detail page] to fetch the account balance.
```suggestion
To check if the account balance has increased, use the xref:{url_checkBalance}[account details page] to fetch the account balance.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Since the faucet allows to seed an account with a specific number of tokens, we want our Hello sApp to also allow transferring of LSKs from/to our desired accounts.
```suggestion
Since the faucet allows to seed an account with a specific number of tokens, we require our Hello sApp to also allow transferring LSK tokens both to and from our desired accounts.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Similar to the faucet, we will start by importing necessary libraries, defining state variables, and `handleChange` event.
```suggestion
Similar to the faucet, we will start by importing the necessary libraries, defining the state variables, and the`handleChange` event.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Next, create the `handleSubmit` function, which will take all the inputs entered by the user and based on that will create a *token transfer* transaction.
```suggestion
Next, create the `handleSubmit` function, which will take all the inputs entered by the user, and based on that will create a *token transfer* transaction.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +                data: 'Hey! I am sending you LSKs. Enjoy!'
```suggestion
                data: 'Hey! I am sending you LSK tokens. Enjoy!'
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +        // 5. Once a transaction is created, it will be sent to the node and after block execution, the account's balance will increment with the amount of LSKs sent to the account.
```suggestion
        // 5. Once a transaction is created, it will be sent to the node and after block execution, the account's balance will increment with the amount of LSK tokens sent to the account.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Our code for creating and sending a transaction is complete, let's add the logic to display the response received from the node.
```suggestion
The code for creating and sending a transaction is now complete, let's add the logic to display the response received from the node.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Finally, the `return` function needs an update, so that form submission, listing data, and on-change event can be functional.
```suggestion
Finally, the `return` function needs an update, so that the form submission, listing of data, and the on-change event can be functional.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +To check if the account balance has increased, use the xref:{url_checkBalance}[account's detail page] to fetch the account balance.
```suggestion
To check if the account balance has increased, use the xref:{url_checkBalance}[account details page] to fetch the account balance.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +image::integrate-blockchain/integrate-ui/transfer.jpg["transfer page", 800]
In the transfer.jpg file imho it should read as : “ Your transaction details are:”

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +* The UI should have a page to transfer LSKs to any account on the sidechain.
```suggestion
* The UI should have a page to transfer LSKs tokens to any account on the sidechain.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +* The UI should also provide a faucet screen, where an account can be seeded with LSKs.
```suggestion
* The UI should also provide a faucet screen, where an account can be seeded with LSK tokens.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +TIP: The relevant files & folders discussed in this guide are {url_api}[api.js], {url_package}[package.json], and {url_frontend}[hello_frontend], respectively.
```suggestion
TIP: The relevant files & folders discussed in this guide are the {url_api}[api.js], the {url_package}[package.json], and the {url_frontend}[hello_frontend], respectively.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +Our goal in this chapter is to focus on the integration of Lisk sApp with a UI.
```suggestion
Our goal in this chapter is to focus on the integration of the Lisk sApp with a UI.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +Our frontend will use the `BigInt` type in the transaction creation process so, update the `eslintConfig` object in the *package.json* to match the following:
```suggestion
Our frontend will use the `BigInt` type in the transaction creation process, therefore it is required to update the `eslintConfig` object in the *package.json* to match the following:
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +Whilst building xref:{url_helloClient_overview}[Hello Client], we created `HelloModule` to send hello messages on the sidechain.
```suggestion
Whilst building the xref:{url_helloClient_overview}[Hello Client], we created the `HelloModule` to send hello messages on the sidechain. 
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +* [x] How to send a hello message through UI.
```suggestion
* [x] How to send a hello message through the UI.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +TIP: The relevant files discussed in this guide are {url_sendHello}[sendHello.js], {url_getHello}[getHello.js], and {url_messsageTimeline}[messageTimeline.js].
```suggestion
TIP: The relevant files discussed in this guide are the {url_sendHello}[sendHello.js], the {url_getHello}[getHello.js], and the {url_messsageTimeline}[messageTimeline.js].
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +To do the aforementioned process, let's update the `sendHello.js` file in the *hello_frontend/src/components/* directory.
```suggestion
To perform the aforementioned process, let's update the `sendHello.js` file in the *hello_frontend/src/components/* directory.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +First up, define the necessary variables and the `handleChange` event.
```suggestion
Firstly, define the necessary variables and the `handleChange` event.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +It will take in the information such as a passphrase, hello message, fee, etc., and will create a transaction using `apiClient`.
```suggestion
It will take in the information such as a passphrase, hello message, fee, etc., and will create a transaction using the `apiClient`.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +Upon clicking on the *Submit* button, the *send hello* transaction will be created and then it will be posted to the node.
```suggestion
Upon clicking on the *Submit* button, the *send hello* transaction will be created and it will then be posted to the node.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +The UI is now able to send hello messages on the sidechain, however, we want the UI to display a response to the user as well.
```suggestion
The UI is now able to send hello messages on the sidechain, however, we require the UI to display a response to the user as well.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +For that, let's add the `displayData` function:
```suggestion
To achieve this, let's add the `displayData` function:
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +Finally, the `return` function needs an update, so that form submission, listing data, and on-change event can be functional.
```suggestion
Finally, the `return` function needs an update, so that the form submission, listing of data, and the on-change event can be functional.
```

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +image::integrate-blockchain/integrate-ui/sendHello.jpg["sendHello page", 800]
Imho it should be the following: “Your transaction details are:”

2023-02-21 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +To display the hello messages sent on the sidechain, let's update the `getHello.js` file and define relevant state variables and the `getMessages` function.
```suggestion
To display the hello messages sent on the sidechain, let's update the `getHello.js` file and define the relevant state variables and the `getMessages` function.
```

2023-02-22 10:35 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +image::integrate-blockchain/hello-sApp.png["Hello sApp overview", 650]
I think we should'nt talk about LSK when we talk about the tokens we use in the Hello app, because they are not really LSK. In fact, they are currently unnamed tokens specific to the Hello blockchain application. So imho it's better to just call them "tokens", not LSK

2023-02-22 12:53 UTC, Tschakki requested changes
Looking great already! Please see my remarks.

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +====
To simplify it for the reader, I think this section can be improved.

The two main prerequisites are:

1. The Hello client
2. The UI boilerplate

We can provide the user the complete Hello client, like we also do for the boilerplate.
It can be mentioned that if the reader wants to know how the Hello client, they can check out this and the following guide `build-blockchain/index.html#the-hello-world-client` (this one link is enough imho).

Also it would be good to include the steps to set up the folder structure, like downloading the UI boilerplate and client, installing the dependencies, and starting boilerplate/ client to verify successful setup.

Once these steps are completed, it can be assumed everyone is on the same page to follow the rest of the guide successfully :)

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +As defined in the xref:{url_helloapp_overview}[Hello World sApp's overview], the UI should provide the following functionalities:
```suggestion
As defined in the xref:{url_helloapp_overview}[Hello World sApp's overview], this UI example should provide the following functionalities:
```

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +With the UI template ready, we now need to install the `@liskhq/lisk-client` package. Through `lisk-client`, the UI will communicate with the *hello_client*.
```suggestion
Now, navigate into the `hello_frontend` folder install the `@liskhq/lisk-client` package.
Through `lisk-client`, the UI will communicate with the *hello_client*.
```

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +Start both the xref:{url_start_client}[*hello_client*] and the {url_start_frontend}[*hello_frontend*^], and then click on the *Account->Create Account* option in the menu bar.
For creating a new account, it is actually not required to have the client running

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +        <>
What are theses brackets for?

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +import React, { useState } from "react";
```suggestion
```

duplicate import

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +import MessageTimeline from './messageTimeline';
i think this is duplicate import, too

2023-02-22 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +The `handleSubmit` function will use the *apiClient* to invoke the `token_getBalance` and `auth_getAuthAccount` endpoints.
It would be cool to display the Hello message in the account details, too

2023-02-23 06:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +        <>
These are for reactJS.

2023-02-23 06:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +import MessageTimeline from './messageTimeline';
Ummmmm, nope the import is correct.

2023-02-23 06:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +With the UI template ready, we now need to install the `@liskhq/lisk-client` package. Through `lisk-client`, the UI will communicate with the *hello_client*.
```suggestion
Now, navigate to the `hello_frontend` folder and install the `@liskhq/lisk-client` package.
Through `lisk-client`, the UI will communicate with the *hello_client*.
```

2023-02-23 07:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +====
> Also it would be good to include the steps to set up the folder structure, like downloading the UI boilerplate and client, installing the dependencies, and starting boilerplate/ client to verify successful setup.

The folder structure and how to set up the project for the Hello sApp are already described [here](https://liskhq.github.io/lisk-docs/beta/build-blockchain/create-sidechain-app.html#initializing-a-new-sidechain-application) and in the boiler plate's [README.md](https://github.com/LiskHQ/lisk-sdk-examples/blob/1582-UI-boiler-plate/guides/07-ui-boilerplate/hello_frontend/README.md) and are mentioned as pre-requisites.

My initial consideration was to download the boilerplate `hello_frontend` folder directly, but you can't do it with a simple command and it is kinda complex, so I created the boilerplate guide to ease things for the reader.

Starting boilerplate/client-related steps are already present in the guide.

Will update the pre-requisites as suggested.

2023-02-23 14:26 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/create-get-account.adoc
> +Alternatively, if something goes wrong, the UI will also display the appropriate error, since in the `displayData` function we have implemented the UI for <<error-display, error handling>> as well.
```suggestion
In the case whereby an error occurs, it will be displayed in the UI, as in the `displayData` function we have also implemented <<error-display, error handling>>.
```

2023-02-23 15:48 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +import MessageTimeline from './messageTimeline';
You can see here it is already included in the file: https://github.com/LiskHQ/lisk-sdk-examples/blob/1582-UI-boiler-plate/guides/07-ui-boilerplate/hello_frontend/src/components/getHello.js#L3

2023-02-23 15:50 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +import MessageTimeline from './messageTimeline';
Yes, this is a component for listing all the hello messages. It is being used on the following line
https://github.com/LiskHQ/lisk-sdk-examples/blob/1582-UI-boiler-plate/guides/07-ui-boilerplate/hello_frontend/src/components/getHello.js#L14

2023-02-23 16:00 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +import MessageTimeline from './messageTimeline';
I see what you mean. Will remove it. Good catch :-D 👍🏼

2023-02-24 12:30 UTC, chris529 approved these changes
LGTM! 👍

2023-02-24 12:38 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/send-get-hello.adoc
> +In case you want to fetch the latest hello message sent on the sidechain from an address, use the xref:{url_getLatestHello}[account's detail page].
```suggestion
In case you want to fetch the latest hello message sent on the sidechain from an address, use the xref:{url_getLatestHello}[account detail page].
```

2023-02-24 12:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/index.adoc
> +. The UI template: `hello_frontend` which is based on react and semantic-UI has been created as described in the boilerplate's {url_helloapp_readMe}[README.md] file.
```suggestion
. The UI template: `hello_frontend` which is based on the react and semantic-UI has been created as described in the boilerplate's {url_helloapp_readMe}[README.md] file.
```

2023-02-24 14:37 UTC, Tschakki approved these changes
Just a small remark left, rest looks good to me 👍

2023-02-24 14:37 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/integrate-UI/faucet-transfer.adoc
> +Since the faucet allows to seed an account with a specific number of tokens, we require our Hello sApp to also allow transferring tokens both to and from our desired accounts.
Maybe it would be nice to summarize a bit in the beginning of a section what is the goal here, or what we are trying to achieve in the following steps

```suggestion
The "transfer tokens" page shall provide an interface for users to transfer tokens to other accounts.
To perform a token transfer, a user needs to enter the recipient address, the amount of tokens they want to send and the transaction fee they want to pay.
They also need to provide their passphrase to sign the transaction.
Once the submit button is clicked, the provided information is used to create and send the transaction to the Hello sApp.
```

2023-02-24 14:59 UTC, merged