Rename `application-cli` page, update command reference & examples
LiskArchive/lisk-legacy-docs pull request #1717
Opened 2023-02-20 13:56 UTC by Tschakki

Closes #1700

2023-02-21 15:03 UTC, TalhaMaliktz requested changes
Looks good, just some suggestions. 
Please also create the issue for updating CLI again with reference to `passphrase:create` command.

2023-02-21 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +$./bin/run autocomplete bash
```suggestion
$ ./bin/run autocomplete bash
```

2023-02-21 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +  block:get 2
```suggestion
  ./bin/run block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4
  ./bin/run block:get 2
```

2023-02-21 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +  $ ./bin/run block get [INPUT] [-d <value>] [--pretty]
```suggestion
  $ ./bin/run block:get [INPUT] [-d <value>] [--pretty]
```

2023-02-21 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion

DESCRIPTION
  Get transaction from local node by ID.

```

2023-02-21 15:03 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  $ ./bin/run transaction:get [ID] [-d <value>] [--pretty]
```

2023-02-22 09:34 UTC, Tschakki commented on modules/ROOT/pages/client-cli.adoc
> +  block:get 2
as this is copied from the CLI, I would leave the example as is

2023-02-22 11:26 UTC, chris529 reviewed
Looks great! Just a few very minor points 👍

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  autocomplete  display autocomplete installation instructions
```suggestion
  autocomplete  Display autocomplete installation instructions.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -c, --count=<value>     [default: 1000000] Total number of hashes to produce
```suggestion
  -c, --count=<value>     [default: 1000000] Total number of hashes to produce.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -d, --distance=<value>  [default: 1000] Distance between each hashes
```suggestion
  -d, --distance=<value>  [default: 1000] Distance between each hash.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -o, --output=<value>    Output file path
```suggestion
  -o, --output=<value>    Output file path.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  --overwrite-config                  Overwrite network configs if they exist already
```suggestion
  --overwrite-config                  Overwrite network configs if they exist already.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -f, --force              Delete and overwrite existing blockchain data
```suggestion
  -f, --force              Delete and overwrite existing blockchain data.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -i, --chain-id=<value>  (required) ChainID in hex format. For example, Lisk mainnet mainchain is 00000000
```suggestion
  -i, --chain-id=<value>  (required) ChainID in hex format. For example, Lisk mainnet mainchain is 00000000.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -l, --label=<value>     App Label
```suggestion
  -l, --label=<value>     App label.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -o, --output=<value>    Directory where the config file is saved
```suggestion
  -o, --output=<value>    Directory where the config file is saved.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  ENDPOINT  Endpoint to invoke
```suggestion
  ENDPOINT  Endpoint to invoke.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  PARAMS    Endpoint parameters (Optional)
```suggestion
  PARAMS    Endpoint parameters (Optional).
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  --use-status-value              Use status value from the connected node
```suggestion
  --use-status-value              Use status value from the connected node.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -f, --file-path=<value>  (required) Path of the file to import from
```suggestion
  -f, --file-path=<value>  (required) Path of the file to import from.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -f, --assets-file=<value>  (required) Path to file which contains genesis block asset in JSON format
```suggestion
  -f, --assets-file=<value>  (required) Path to file which contains genesis block asset in JSON format.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -o, --output=<value>       [default: config] Output folder path of the generated genesis block
```suggestion
  -o, --output=<value>       [default: config] Output folder path of the generated genesis block.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -c, --count=<value>       [default: 1] Number of keys to create
```suggestion
  -c, --count=<value>       [default: 1] Number of keys to create.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -f, --offset=<value>      Offset for the key derivation path
```suggestion
  -f, --offset=<value>      Offset for the key derivation path.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -i, --chainid=<value>     Chain id
```suggestion
  -i, --chainid=<value>     Chain id.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -n, --no-encrypt          No encrypted message object to be created
```suggestion
  -n, --no-encrypt          No encrypted message object to be created.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -f, --file-path=<value>  (required) Path of the file to encrypt from
```suggestion
  -f, --file-path=<value>  (required) Path of the file to encrypt from.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  Encrypt keys from a file and overwrite the file
```suggestion
  Encrypt keys from a file and overwrite the file.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +  -f, --file-path=<value>  (required) Path of the file to import from
```suggestion
  -f, --file-path=<value>  (required) Path of the file to import from.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  ./bin/run passphrase:encrypt  Encrypt the secret passphrase using the password.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  Encrypt the secret passphrase using the password.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  -a, --params=<value>               Creates transaction with specific params information.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  -k, --key-derivation-path=<value>  [default: m/44'/134'/0'] Key derivation path to use to derive keypair from passphrase.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  -s, --sender-public-key=<value>    Set a custom senderPublicKey property for the transaction, to be used when account address does not correspond to signer's private key.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  --no-signature                     Creates the transaction without a signature. Your passphrase will therefore not be required.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  --send                             Create and immediately send transaction to a node.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  TRANSACTION  A transaction to be sent to the node encoded as hex string.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  TRANSACTION  The transaction to be signed encoded as hex string.
```

2023-02-22 11:26 UTC, chris529 commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion
  -k, --key-derivation-path=<value>  [default: m/44'/134'/0'] Key derivation path to use to derive keypair from passphrase.
```

2023-02-22 12:56 UTC, Tschakki commented
Hey @chris529 , I see your comments are all related to content which was copied form the client CLI. That is why I won't update it here in this PR. If you feel this should be updated, please create a corresponding issue in the lisk-sdk repo, thx.

2023-02-22 13:09 UTC, chris529 commented
@Tschakki Hey Mona, Yes I think most of the comments were related to the client CLI. Agreed and understood, so I will approve it.👍

2023-02-23 14:11 UTC, shuse2 approved these changes
Generally looks good. As @TalhaMaliktz mentioned, `node` command should be `system` (it will also need to be fixed in SDK as well

2023-02-23 14:14 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-02-23 14:55 UTC, merged