How to compute min fee
LiskArchive/lisk-legacy-docs pull request #1732
Opened 2023-03-07 17:53 UTC by Tschakki

Closes #1578

2023-03-15 15:37 UTC, shuse2 requested changes

2023-03-15 15:37 UTC, shuse2 commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +== Option 1: Send a transaction with zero fee
instead of sending the transaction with zero fee, it would be better to do dryRunTransaction. Actually, in option 1 or 2, it's always better to check with dryRunTransaction to see if the transaction will be executed successfully

2023-03-15 15:37 UTC, shuse2 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +So by choosing a higher fee, it can be ensured that the transaction is executed as quickly as possible.
in case network is crowded

2023-03-15 15:37 UTC, shuse2 commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +=== Connect the API client to a node
somehow it is rendered weird on the markdown here

2023-03-16 11:07 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +=== Connect the API client to a node
removed the sectnums for now

2023-03-17 12:19 UTC, TalhaMaliktz requested changes
Looks good! Just minor suggestions :)

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +:url_sdkexamples_minfee: https://github.com/LiskHQ/lisk-sdk-examples/blob/300-min-fee/guides/calculate-minfee/index.js
Will be effective after the code merges.
```suggestion
:url_sdkexamples_minfee: https://github.com/LiskHQ/lisk-sdk-examples/blob/development/guides/calculate-minfee/index.js
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +Finally, call the `getClient` function to get the API clint, and use it to calculate the fee with `client.transaction.computeMinFee(tx)`.
```suggestion
Finally, call the `getClient` function to get the API client, and use it to calculate the fee with `client.transaction.computeMinFee(tx)`.
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +// A URL pointing to a node with open API
What is open API?

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +Create a small script called `compute-minfee.js` like described in the following sections.
```suggestion
Create a small script called `compute-minfee.js` as described in the following sections.
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +A higher fee will create an incentive for validators to include the transaction in a block as quickly as possible, because most validators prioritize transactions with higher fees in the transaction
```suggestion
A higher fee will create an incentive for validators to include the transaction in a block as quickly as possible, because most validators prioritize transactions with higher fees in the transaction pool, because it means a personal higher reward for them, if they include these transactions in a block.
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +So by choosing a higher fee, it can be ensured that the transaction is executed as quickly as possible, in case network is crowded.
```suggestion
So by choosing a higher fee, it can be ensured that the transaction is executed as quickly as possible, in case the network is crowded.
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +The minimum fee required is calculated the following way:
```suggestion
The minimum fee required is calculated in the following way:
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +* If a transaction requires a command fee, and the command fee is not or only partially paid, the transaction will be <<valid-vs-invalid-transactions,invalid>>.
```suggestion
* If a transaction requires a command fee, and the command fee is partially paid or not paid at all, then, the transaction will be <<valid-vs-invalid-transactions,invalid>>.
```

2023-03-17 12:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +TIP: It is possible to configure a sidechain to have no transactions fees, by setting the `minFeePerByte` to 0 in the config.
```suggestion
TIP: It is possible to configure a sidechain to have no transaction fee, by setting the `minFeePerByte` to 0 in the config.
```

2023-03-17 13:05 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +// A URL pointing to a node with open API
open means enabled in this context,  i can update that

2023-03-17 13:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +// A URL pointing to a node with open API
Yes, thank you.

2023-03-17 14:06 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +// A URL pointing to a node with open API
i updated the entire section to improve the structure and align with the "how to post txs" guide i am working on currently

2023-03-17 14:23 UTC, TalhaMaliktz approved these changes
Thanks, just one comment, Rest LGTM 🎉

2023-03-17 14:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +Import the `getClient()` function and execute it to use the API client to calculate hte minimum fee, as shown in below snippet.
```suggestion
Import the `getClient()` function and execute it to use the API client to calculate the minimum fee, as shown in the snippet below.
```

2023-03-20 15:35 UTC, shuse2 commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +== Option 1: Dry-running a transaction with zero fee
I just realize this actually doesn't work. as soon as fee is added, the min fee will change because of the min fee size).
I think it should be
1. check if there is additional fee required
2. Use computeMinFee function
3. Check if the transaction has valid fee using dry run transaction

2023-03-20 15:35 UTC, shuse2 commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +== Option 1: Dry-running a transaction with zero fee
so pretty much viable option is the option 2

2023-03-20 16:07 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +== Option 1: Dry-running a transaction with zero fee
I think in most cases it will display the correct minimum fee nontheless. I would suggest just to add an extra step to Option 1, to verify the transaction with a dry-run one more time, and increase the fee again, if needed.

2023-03-20 16:14 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +== Option 1: Dry-running a transaction with zero fee
Ah I just checked and it doesn't really work even for small tx fees :( So then maybe that minimum fee statement when running a dry run is actually a bit confusing, as it is not displaying a correct minimum fee in most scenarios. I suggest to remove the minimum fee info and just inform the user that the fee is too low

2023-03-20 16:14 UTC, shuse2 commented on docs/modules/ROOT/pages/integrate-blockchain/calculating-min-fee.adoc
> +== Option 1: Dry-running a transaction with zero fee
I think if it starts from `0`, most of the first trial will be invalid.
even if the transaction is 1 byte (which is not possible), min fee is 1000, which is 1 byte more compare to `0` fee

2023-03-21 19:20 UTC, shuse2 approved these changes

2023-03-22 09:39 UTC, merged