Update how to create txs offline
LiskArchive/lisk-legacy-docs pull request #1749
Opened 2023-03-21 11:47 UTC by Tschakki

Closes #1580

2023-03-22 16:00 UTC, mosmartin approved these changes
LGTM 🚀

2023-03-23 09:33 UTC, mosmartin commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +? Please enter: amount:  1000000000
Hi @Tschakki , just did another round of review. I've noticed that the first prompt is `tokenID` from my end then amount. But am running from the pos example app. Should this be diff if say this is run from a bootstrapped app?

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/10962699/227160842-4f41dbbb-8c57-48bb-b05e-49cc912d157f.png">

2023-03-23 15:18 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +? Please enter: amount:  1000000000
Good catch, I added the tokenID, and moved the passphrase question up, as it is asked first for me 👍

2023-03-23 15:35 UTC, TalhaMaliktz requested changes

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +$ ./bin/run transaction:create token transfer 10000000 --chain-id=00000000 --nonce=0 --offline
```suggestion
$ ./bin/run transaction:create token transfer 10000000 --chain-id 00000000 --nonce 0 --offline --json
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +----
```suggestion
[source,bash]
----
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +}
Here's the updated snippet
```suggestion
{
	"transaction": {
		"module": "token",
		"command": "transfer",
		"fee": "10000000",
		"nonce": "0",
		"senderPublicKey": "a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0",
		"signatures": [
			"eee00368b7933b6bd06f7ba410261749197b800fc79a816ad15cb3225af6e48cc56c5af1961d6865b8c1ccf9466997e55e8edcf2681c3161a307270bd3d9b800"
		],
		"params": {
			"tokenID": "0400000000000000",
			"amount": "10000000",
			"recipientAddress": "lskzbqjmwmd32sx8ya56saa4gk7tkco953btm24t8",
			"data": "Hey there"
		},
		"id": "1da484cd297c7654b111987708220e53cb29535ae94276a2fe1486dcfee7e31d"
	}
}
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +./bin/run transaction:create token transfer 10000000 --chain-id=00000000 --nonce=0 --offline
```suggestion
./bin/run transaction:create token transfer 10000000 --chain-id 00000000 --nonce 0 --offline
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
>    "address": "lskuwzrd73pc8z4jnj4sgwgjrjnagnf8nhrovbwdn"
Are we using `address` anywhere? if not please remove it.
```suggestion

```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
>  */
Please separate the output from the code.

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
>  */
Please separate the output from the code.

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
>  );
Since this bit will come after the code for creating an unsigned transaction, I would move this into a new snippet and then will show its output separately.

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +    console.log("Dry-un result: ", res);
```suggestion
    console.log("Dry-run result: ", res);
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +    console.log("Error1: " + err);
```suggestion
    console.log("Error: " + err);
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +If the dry-run finishes without errors, the transaction is valid.
Would be nice to have a response to the dry-run here as well, just so the reader knows what to expect.

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +This creates reply as seen below:
```suggestion
This creates a response as seen below:
```

2023-03-23 15:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +Without dry-running the transaction, its' validity cannot be verified, and the transaction might fail.
```suggestion
Without dry-running the transaction, its validity cannot be verified, and the transaction might fail.
```

2023-03-23 15:47 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +./bin/run transaction:create token transfer 10000000 --chain-id=00000000 --nonce=0 --offline
Why remove the `=`?

2023-03-23 15:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +./bin/run transaction:create token transfer 10000000 --chain-id=00000000 --nonce=0 --offline
Ummmm! just for the sake of synchronization. Throughout the CLI examples, we use this format, even in the help section of commands as well.

2023-03-23 15:54 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
>    "address": "lskuwzrd73pc8z4jnj4sgwgjrjnagnf8nhrovbwdn"
I would like to keep it just as an human-readbale representation for the user of the account that these values belong to.

2023-03-24 13:27 UTC, mosmartin approved these changes

2023-03-24 16:19 UTC, TalhaMaliktz approved these changes
Thanks, just some minor suggestions, the rest of it LGTM 👍🏼

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +The transaction object is now returned, ready to be signed by the sender in the next step.
```suggestion
The transaction object is now returned, and ready to be signed by the sender in the next step.
```

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +Values for the properties `signatures` and `id` are added to a transaction when it is signed by a user.
```suggestion
Values for the properties such as `signatures` and `id` are added to a transaction when it is signed by a user.
```

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +? Please enter: data:  Happy Birthday!
Since the input sequence is the following, I suggest re-ordering the prompts accordingly. BTW the `passphrase` is only asked once.

```suggestion
? Please enter: tokenID:  0000000000000000
? Please enter: amount:  1000000000
? Please enter: recipientAddress: lsk44ejwrjb4g44hj9mbtc43h8bcu54g2gbbyyvrk
? Please enter: data:  Happy Birthday!
? Please enter passphrase:  [hidden]
```

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
```suggestion

.account.json
```

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +To sign the transaction, use `signTransaction()` function of the @liskhq/lisk-transactions` package.
```suggestion
To sign the transaction, use `signTransaction()` function of the `@liskhq/lisk-transactions` package.
```

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +It required the following parameters:
```suggestion
It requires the following parameters:
```

2023-03-24 16:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/create-tx-offline.adoc
> +Without dry-running the transaction, its' validity cannot be verified, and the transaction might fail.
```suggestion
Without dry-running the transaction, its validity cannot be verified, and the transaction might fail.
```

2023-03-27 08:48 UTC, merged