Add setup relayer node guide - Closes 1534
LiskArchive/lisk-legacy-docs pull request #1750
Opened 2023-03-21 15:19 UTC by TalhaMaliktz

Closes #1534

2023-03-22 09:37 UTC, Tschakki requested changes

2023-03-22 09:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +* [x] How to set up a relayer node on a mainchain?
```suggestion
On this page, you'll learn:

* [x] How to set up a relayer node on a sidechain
* [x] How to set up a relayer node on a mainchain
```

2023-03-22 09:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
In the context of the guide, i don't think this is accurate.
As the guide is targeting node operators, the requirement is, that they have set up a node connected to a blockchain, and have API access to a node on the receiving chain.

2023-03-22 09:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. Call the `encrypt` function to create an encrypted private key and pass the `generatorPrivateKey` of your account to it.
Please describe quickly, how they can obtain the `generatorPrivateKey` in case it is not clear to the user

2023-03-22 09:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +'kdf=argon2id&cipher=aes-256-gcm&version=1&ciphertext=57db80457db93a1abeceee5c6f951ca04579c447a06f45cf5e8b5398e207a26da53a6b191a02c479ede455950eacb48f32d6609f2cd4b5a1a51e895b210b587ef046e6c3151ef2212
Please separate command and response in the code snippets for better overview

2023-03-22 09:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Alternatively, the plugin can also be enabled using the `--enable-chain-connector-plugin` flag whilst starting the sidechain client, without updating the *app.ts* file.
Is this the alternative or the recommended way to enable the plugin?

2023-03-22 09:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Alternatively, the plugin can also be enabled using the `--enable-chain-connector-plugin` flag whilst starting the sidechain client, without updating the *app.ts* file.
It is an alternative way, there is no recommended way TBH. A user can go with any given method to enable the plugin as they like. Both are correct ways to do the same thing.

2023-03-22 09:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +* [x] How to set up a relayer node on a mainchain?
```suggestion
On this page, you'll learn:

* [x] How to set up a relayer node on a sidechain?
* [x] How to set up a relayer node on a mainchain?
```

2023-03-22 14:12 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Alternatively, the plugin can also be enabled using the `--enable-chain-connector-plugin` flag whilst starting the sidechain client, without updating the *app.ts* file.
I see. Maybe we can just change order of the two options, as this one looks more simple, but without recommending one option directly?

2023-03-22 14:24 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
Since registration is the last step for a node to be connected to the blockchain, I think the pre-requisite is accurate as it tells exactly what needs to be done for a node to be connected to the blockchain, and since a node operator or a validator will most probably be registering the chains I think it suffices to say that registration is necessary. 
If blockchain registers, it will automatically mean that the node of the blockchain are connected to the network and API access to nodes will be possible on receiving chain.

2023-03-22 14:26 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Alternatively, the plugin can also be enabled using the `--enable-chain-connector-plugin` flag whilst starting the sidechain client, without updating the *app.ts* file.
I have made the adjustment as suggested.

2023-03-22 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
The sidechain/mainchain registration is not something every node operator needs to perform in order to connect to the network. It is only required one time to do the registration process.

For the guide you are assuming that the reader has setup a node connected to the sending chain, and has access to node API of the receiving chain. Probably it should be recommended, that the user who is setting up a relayer also manages the node on the receiving chain, to ensure availability?

So in this case we can mention the following requirements:

1. Managing a node connected to the mainchain (link to Lisk Core)
2. Managing a node connected to the sidechain
3.  The sidechain should be registered to the mainchain according to the guide "How to register a sidechain"(link) and the status of the sidechain account should be `registered` or `active`.

2023-03-22 16:56 UTC, Tschakki requested changes

2023-03-22 16:56 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +.sidechain_client/src/app/app.ts
The plugin should be registered in the `plugins.ts` file instead off `app.ts`, to use the current file structure.

2023-03-22 16:56 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Isn't a first CCM created during the registration process on both chains? So that it can be expected that there is already 1 CCM present directly after registration? And if a node operator enables the chain connector plugin after the registration, how likely is it, that there are no CCMs to process when the plugin is enabled the first time? In case the default scenario is, that there are CCMs to be processed, so that it doesn't log the described error, it should explain the success message instead.

2023-03-22 18:23 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The mainchain expects the `chainID` of the receiving chain along with the mandatory fields.
Are you sure that the receivingchain ID is not required on the sidechain? In the readme of the interop example, it looks like both config have the value: https://github.com/LiskHQ/lisk-sdk/blob/development/examples/interop/README.md

2023-03-23 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +.sidechain_client/src/app/app.ts
This plugin is registered in the `app.ts` as per the following guide:
https://lightcurve.atlassian.net/wiki/spaces/SDK/pages/6095082/Chain+Connector+Plugin+Usage?NO_SSR=1

2023-03-23 07:33 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
AFAIK there is no CCM after registration. @ishantiw maybe can help us clarify this?

2023-03-23 07:34 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The mainchain expects the `chainID` of the receiving chain along with the mandatory fields.
Yes, Tried the example myself. Didn't throw any errors. For the mainchain, it does throw an error if you don't have a chainID in the config. The same is mentioned in the following guide as well.
https://lightcurve.atlassian.net/wiki/spaces/SDK/pages/6095082/Chain+Connector+Plugin+Usage?NO_SSR=1

2023-03-23 08:27 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The mainchain expects the `chainID` of the receiving chain along with the mandatory fields.
Can you please point me to where it is mentioned exactly? And why does the guide say `chainID`, while the Readme says `receivingChainID`?

2023-03-23 08:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The mainchain expects the `chainID` of the receiving chain along with the mandatory fields.
In this section, and yes it should be `receivingChainID` 👍🏼 
https://lightcurve.atlassian.net/wiki/spaces/SDK/pages/6095082/Chain+Connector+Plugin+Usage?NO_SSR=1#Prepare-config-for-chain-connector-plugin

2023-03-23 08:33 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
I am pretty sure there is: https://liskhq.github.io/lisk-docs/beta/understand-blockchain/interoperability/sidechain-registration-and-recovery.html#registration-ccm

2023-03-23 08:34 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +.sidechain_client/src/app/app.ts
I think the guide is not  following best practise in this case :)

2023-03-23 08:41 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Is there an endpoint or method which can be used to get details of such CCM?

2023-03-23 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +.sidechain_client/src/app/app.ts
Let me try registering it in the `plugin.ts` if it works then I can make the suggested change.

2023-03-23 08:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
Please share the links that you think are suitable here:
> Managing a node connected to the mainchain (link to Lisk Core)
Managing a node connected to the sidechain

2023-03-23 09:05 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
You can check the outbox size of the channel data store: https://liskhq.github.io/lisk-docs/beta/build-blockchain/register-sidechain.html#check-the-sidechain-channel 

Not sure if you can look at the individual CCMs, though 🤔

2023-03-23 09:11 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
1. I would link to this section: run-blockchain/index.html#how-to-set-up-a-lisk-mainnet-node
2. I am not sure we have a fitting guide for this. Also, the setup might be different on different sidechains, so maybe we can just add a footnote to refer to the setup guides of the respective sidechain.

2023-03-23 09:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Hmmm! I do get the size of the outbox: 1, not sure what it means for us though.

**Sidechain**
```
./bin/run endpoint:invoke interoperability_getChannel '{"chainID": "04000000"}' --pretty                                                                              
{
  "messageFeeTokenID": "0400000000000000",
  "outbox": {
    "appendPath": [
      "b947f78350104a72381044ae1a239752084215e0d5e2fc1cb0eba8956ec4761a"
    ],
    "root": "b947f78350104a72381044ae1a239752084215e0d5e2fc1cb0eba8956ec4761a",
    "size": 1
  },
  "inbox": {
    "appendPath": [],
    "root": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "size": 0
  },
  "partnerChainOutboxRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "minReturnFeePerByte": "1000"
}
```
**Mainchain**
```
lisk-core endpoint:invoke interoperability_getChannel '{"chainID": "04000002"}' --pretty                                                                               
{
  "messageFeeTokenID": "0400000000000000",
  "outbox": {
    "appendPath": [
      "1a8fd0bea33f8144853e4f86ea57c38e84046dd7def2776e6d6782b90357eae8"
    ],
    "root": "1a8fd0bea33f8144853e4f86ea57c38e84046dd7def2776e6d6782b90357eae8",
    "size": 1
  },
  "inbox": {
    "appendPath": [],
    "root": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "size": 0
  },
  "partnerChainOutboxRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "minReturnFeePerByte": "1000"
}
```

There is no success message for me, I get the error message. ⬇️
> In case the default scenario is, that there are CCMs to be processed, so that it doesn't log the described error, it should explain the success message instead.

2023-03-23 13:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
I have made the adjustment to the text.

2023-03-23 15:06 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
@ishantiw please clarify if this is expected behaviour of the chain connector plugin, and how to verify that the plugin was enabled successfully. Imho, the user should not wait for an error to show up, because this is not a sign that something works, but more that something doesn't work as expected. So there should be some additional log messages concerning a successfully sent CCU or some endpoints to query the required information to verify the plugin is working as expected.

2023-03-24 10:10 UTC, ishantiw requested changes

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +With these configurations, the details such as the receiver’s chainID, the receiving chain’s path, CCU frequency, private key, etc. can be set.
```suggestion
With these configurations, the details such as the receiver’s chainID, the receiving chain’s path, CCU frequency, encrypted private key, etc. can be set.
```

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +        "chainConnector": {
maybe mention `receivingChainID` as its mandatory field

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. Call the `encrypt` function to create an encrypted private key and pass the `generatorPrivateKey` of your account to it.
```suggestion
. Call the `encrypt` function to create an encrypted private key and password the `generatorPrivateKey` of your account to it.
```

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. Call the `encrypt` function to create an encrypted private key and pass the `generatorPrivateKey` of your account to it.
Ah this is not generatorPrivateKey but ed private key, you can simply say to encrypt private key of any account on the other chain that you want to use as a relayer address and has balance to sign and send the transaction

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The mainchain expects the `chainID` of the receiving chain along with the mandatory fields.
on both mainchain and sidechain you need chainID of the receiving chain

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +./bin/run --enable-chain-connector-plugin --overwrite-config
```suggestion
./bin/run start --enable-chain-connector-plugin --overwrite-config
```

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +./bin/run --overwrite-config
```suggestion
./bin/run start --overwrite-config
```

2023-03-24 10:10 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
When we register a chain, a registration CCM is created and added to the outbox but if there is no valid certificate to be created, then we wait for for the finalized height, meanwhile log "No valid CCU can be generated for the height: <>". Once the first finalized height is created then we can include the CCM with the first CCU and send it across, for subsequent CCUs, we can have a scenario where there are pending CCMs but no certificate, in that case we can still send a CCU with only pending CCMs and without certificate.

2023-03-27 09:26 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +. The mainchain has been registered on the sidechain, as described in the guide: xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain?]
Sorry, I do not see the requirement to have a running node in the text.
Also, I don't see why the sidechain relayer has prerequisite to habe the status `active` and `registered`, but not the mainchain relayer. Imho there is no need to separate between the two. For both, it is necessary to complete the registration process as explained in the guide (which already includes both, sc and mc registration)

2023-03-27 09:42 UTC, Tschakki requested changes

2023-03-27 09:42 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +== Configuring the Chain Connector plugin
This is more like an explanation, and there are no concrete steps that a user can do here. I would therefore merge this content with the section where we are actually configuring the plugin, under `=== Prepare config for chain connector plugin`

2023-03-27 09:42 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +
Sorry, I do not see the requirement to have a running node in the text.
Also, I don't see why the sidechain relayer has prerequisite to have the status `active` and `registered`, but not the mainchain relayer. Imho there is no need to separate between the two. For both, it is necessary to complete the registration process as explained in the guide (which already includes both, sc and mc registration)

2023-03-27 09:42 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Just to clarify, so in case the sidechain is newly registered, and we set up the first relayer, then this log message is expected, right? But for a running sidechain, a new relayer would be already able to send CCUs because the finalized height is reached? I think we need to find and explain a way to verify that the relayer was set up correctly for every use case. This guide is not only for people setting up a relayer after registration, but more how to setup a relayer in general.

2023-03-27 11:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +
> Sorry, I do not see the requirement to have a running node in the text.

Without a running node, it will not be possible to even do the registration. The reader is already aware or should be aware of running a node, before setting up the relayer node. IMHO this is a pre-req for the registration guide.

> Also, I don't see why the sidechain relayer has a prerequisite to have the status active and registered, but not the mainchain relayer. Imho there is no need to separate the two. 

Because the liveness condition is only for a sidechain and not for a mainchain. A mainchain is going to stay alive.
https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#life-cycle-of-a-sidechain

The separation of prerequisites is intentional as either a sidechain node operator will read it or a mainchain node operator, to set up the relayer. That's why content is separated for mainchain and sidechain, throughout the page.

2023-03-27 11:55 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +== Configuring the Chain Connector plugin
I tried that and this breaks the flow for me as in the suggested case, the introduction of the concept `encryptedPrivateKey` will come after the instruction: **Creating an encrypted private key**. If you agree, I would like to keep it.

2023-03-27 11:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
@Tschakki Good point. I agree. @ishantiw Is there a way to realize what Mona suggests?

Also if you guys agree, I think we should have a separate guide about sending CCU/CCMs and should also describe any edge cases a node operator has to face. This guide can be part two of the set-up relayer guide.

2023-03-27 14:11 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
> separate  guide about sending CCU/CCMs

I don't think there are many manual steps included after activating the plugin - what exactly do you imagine to be explained in the guide?

2023-03-27 14:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +
> Without a running node, it will not be possible to even do the registration. The reader is already aware or should be aware of running a node, before setting up the relayer node. IMHO this is a pre-req for the registration guide.

Just to be clear here: Completing the registration guide is NOT a prerequisite for a relayer, to setup a relayer. It is enough if SOMEONE has registered the sidechain before. So it cannot be assumed that every relayer went through the registration guide. So this is why I would make the changes to the prerequisites as I suggested.

And about making different prerequisites here for mainchain and sidechain, I do not see the benefit of separating them, because no one will only register mainchain to sidechain, without doing the second step. Both registration belong together. So for both relayer on mainchain and sidechain, it should be prerequisite to finish BOTH registrations.
This is why i would only refer to the registration guide as a whole as a prerequisite.

2023-03-27 17:43 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Not sure, as I am not familiar with the process. Discussing various ways of sending CCU/CCM (if there are any) can be explained there. Edge cases can be addressed as well. We can also show various responses like for a successful CCU/CCM, for failure, etc. More clarity can be achieved once we work on the topic.

2023-03-28 08:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +* The mainchain should be registered on the sidechain to which it intends to communicate as described in the xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain] guide{fn_m
Does this sound okay to you?
```suggestion
.Prerequisites
[NOTE]
====
To use this guide, it is assumed that the following criteria have been met:

* The sidechain must be registered to the mainchain as described in the xref:{url_guides_reg_sidechain}[] guide.
* The sidechain account on the mainchain{fn_mainnet} must have either the `registered` or `active` status.
```

2023-03-28 08:13 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +
I have made a suggestion above, please consider that.

2023-03-28 09:33 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +* The mainchain should be registered on the sidechain to which it intends to communicate as described in the xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain] guide{fn_m
It is going in the right direction, but as mentioned before, I would put in the prerequisites that they need to have nodes on sidechain and mainchain.

1. Managing a node connected to the mainchain (link to Lisk Core)
2. Managing a node connected to the sidechain
3. The sidechain should be registered to the mainchain according to the guide "How to register a sidechain"(link) and the status of the sidechain account should be `registered` or `active`.

2023-03-28 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +* The mainchain should be registered on the sidechain to which it intends to communicate as described in the xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain] guide{fn_m
Done.

2023-03-28 14:40 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Added a sentence to explain next step after the error message. Maybe it can be enhanced with a first log message of a successfully sent CCU.

```suggestion
The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.

The relayer node will start relaying CCUs to the receiving chain, once the finalized height is reached.
```

2023-03-28 14:40 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +* The mainchain should be registered on the sidechain to which it intends to communicate as described in the xref:{url_guides_reg_mainchain}[How to register the mainchain on the sidechain] guide{fn_m
thanks 👍

2023-03-28 14:46 UTC, Tschakki approved these changes
Looks great! :) Just a few minor comments.

2023-03-28 14:46 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
Yes I agree, let's keep that in mind and ocme back later to the topic, once we have more practical knowledge :)

2023-03-28 23:59 UTC, ishantiw reviewed
Looks good, just a few more minor comments

2023-03-28 23:59 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +With these configurations, the details such as the receiver’s chainID, the receiving chain’s path, CCU frequency, encrypted private key, etc. can be set.
```suggestion
With these configurations, the details such as the receiving chain’s chainID and it's IPC path or WS URL, CCU frequency, encrypted private key, etc. can be set.
```

2023-03-28 23:59 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +|`isSaveCCU`
I have recently added ccuSaveLimit which by default is 300 CCUs and user can set it to any value to tell how many CCUs it wants to save https://github.com/LiskHQ/lisk-sdk/pull/8315

2023-03-28 23:59 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate and there are no pending CCUs/CCMs to send across the chain.
```suggestion
The messages suggest that the blockchain doesn't have any finalized block height for which we can create a certificate or there are no pending CCUs/CCMs to send across the chain.
```

2023-03-29 08:52 UTC, ishantiw approved these changes

2023-03-29 10:02 UTC, merged