Update Run Blockchain Index.adoc - Closes 1535
LiskArchive/lisk-legacy-docs pull request #1753
Opened 2023-03-23 12:53 UTC by TalhaMaliktz

Closes #1535

2023-03-27 08:42 UTC, Tschakki requested changes

2023-03-27 08:42 UTC, Tschakki commented on docs/modules/ROOT/images/run-blockchain/node-service-network.png
For the diagram, 
- there should not be a connection from relayer to validator node
- the arrow should only go one direction relayer->RPC node, and not RPC node->relayer
- also, as relayers only communicate via CCUs, maybe it's good to indicate in the diagram that this is not a P2P connection, maybe with a different arrow.
- same for the connection between blockchain nodes and service nodes / external services
- Blockchain A Should be Mainchain
- Blockchain B should be Sidechain

2023-03-27 08:42 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +. <<Lisk Service nodes>>
I would put Lisk Service nodes as last point

2023-03-27 08:42 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Consider blockchain A with 20 nodes, out of which, a node is configured to act as a relayer node.
Please talk about sidechain and mainchain in the context of cross chain communication, to clarify a sidechain has always to communicate via the mainchain with other chains. If a sidechain A wants to communicate to another sidechain B, this would need a relayer on sidechain A and a relayer on mainchain to relay the CCU to sidechain B.

2023-03-27 08:45 UTC, TalhaMaliktz commented on docs/modules/ROOT/images/run-blockchain/node-service-network.png
What kind of connection is used for a relayer to relayer?
> also, as relayers only communicate via CCUs, maybe it's good to indicate in the diagram that this is not a P2P connection, maybe with a different arrow.

2023-03-27 08:52 UTC, chris529 reviewed
Looks very good! Just a few minor points.. 👍

2023-03-27 08:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +:fn_lips: footnote:witness[For more information about interoperability and cross-chain update mechanism, check out {url_lip45}[LIP 0045^] and {url_lip53}[LIP 0053^].]
```suggestion
:fn_lips: footnote:witness[For more information about interoperability and the cross-chain update mechanism, check out {url_lip45}[LIP 0045^] and {url_lip53}[LIP 0053^].]
```

2023-03-27 08:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk ecosystem, a node can be of the following four types.
```suggestion
In the Lisk ecosystem, a node can be any one of the following four types.
```

2023-03-27 08:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +.Various node types in the network of blockchains
IMHO, I would change this heading to the following:
'Various node types deployed in blockchain networks'

2023-03-27 08:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Depending on the node configuration, an xref:{url_communication}[RPC node] can accept different communication protocols such as {url_wiki_http_protocol}[Hypertext Transfer Protocol (HTTP)^], {url_web
```suggestion
Depending on the node configuration, an xref:{url_communication}[RPC node] can accept different communication protocols such as {url_wiki_http_protocol}[Hypertext Transfer Protocol (HTTP)^], {url_websocket}[WebSocket (WS)^], and {url_wiki_ipc}[Inter-Process Communication (IPC)^].
```

2023-03-27 08:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +In the Lisk ecosystem, nodes from different chains can communicate with each other as well and this communication is done via relayer nodes.
IMHO, I would suggest we reword this sentence as follows:
"Nodes from different chains are able to interact with one another in the Lisk ecosystem, and this interaction is carried out via relayer nodes."

2023-03-27 08:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +To become a relayer node, Lisk provides an easy-to-use plugin called Chain Connector.
```suggestion
To become a relayer node, Lisk provides an easy-to-use plugin called a Chain Connector.
```

2023-03-27 08:56 UTC, Tschakki commented on docs/modules/ROOT/images/run-blockchain/node-service-network.png
I think it is similar to RPC endpoints, it can be IPC or WS, depending on how the chain connector plugin is configured

2023-03-28 09:20 UTC, Tschakki approved these changes
Just left some suggestions, otherwise LGTM 👍

2023-03-28 09:20 UTC, Tschakki commented on docs/modules/ROOT/images/run-blockchain/node-service-network.png
The arrow from relayer to RPC node should be dark-blue as well (no HTTP possible).
Also, the pink arrows are hard to see, maybe try to make them bolder or use different style for the arrows.

2023-03-28 09:20 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +== How to set up a Validator node
```suggestion
=== How to set up a Validator node
```

2023-03-28 09:26 UTC, chris529 reviewed
Looks great! just a few minor suggestions 👍

2023-03-28 09:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +A sidechain has to always communicate with other blockchains via the mainchain.
```suggestion
A sidechain always has to communicate with other blockchains via the mainchain.
```

2023-03-28 09:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +Consider a sidechain *S1* with 20 nodes, out of which, a node is configured to act as a relayer node.
```suggestion
Consider a sidechain *S1* with 20 nodes, whereby one of these nodes has been configured to act as a relayer node.
```

2023-03-28 09:26 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +The job of this relayer node is to collect CCUs & CCMs from other nodes of *S1* and then pass them on to the receiving mainchain.
```suggestion
The job of this relayer node is to collect CCUs & CCMs from the other nodes of *S1* and subsequently pass them on to the receiving mainchain.
```

2023-03-28 09:53 UTC, chris529 approved these changes
LGTM! 👍

2023-03-28 11:16 UTC, merged