Update terminology of the build-blockchain category
LiskArchive/lisk-legacy-docs pull request #1757
Opened 2023-03-28 11:10 UTC by Tschakki

Closes #1740

2023-03-30 12:35 UTC, TalhaMaliktz requested changes

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/images/build-blockchain/hello-client.png
Please add the high res image.

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-client.adoc
**Line 92**
It is recommended to install Lisk Commander globally with NPM (Node Package Manager), to facilitate the convenient usage of the Lisk Commander CLI.

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-client.adoc
```suggestion

NOTE: In case you change the contents of the `app.ts` file, or any other source file of the client then, run the following command before starting the client:

[source,bash]
----
npm run build
----

```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-client.adoc
> +Executing the `start` command should kick off the sidechain client, which is currently running with a local single-node development network.
```suggestion
Executing the `start` command should kick off the blockchain client, which is currently running with a local single-node development network.
```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
> +.Features of the Hello plugin
Renders as `Example 1. Features of the Hello plugin` and also it's redundant.
```suggestion

```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/index.adoc
>  However, the only mandatory parts of a plugin are the `nodeModulePath()`, `load()` and `unload()` functions.
**Line 167**
Each plugin’s class must extend from the `BasePlugin`, which is imported from the `lisk-sdk` package.

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-class.adoc
>  The Plugin class contains the starting, ongoing, and concluding logic of a plugin.
```suggestion
The plugin class contains the starting, ongoing, and concluding logic of a plugin. 
```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-class.adoc
> +The `\_saveEventInfoToDB()` function will take the _decoded data_, the _block height_ where a `newHello` event is found, and an incremented _counter_ value and will store the aforementioned in their
```suggestion
The `\_saveEventInfoToDB()` function will take the _decoded data_ and the _block height_ where a `newHello` event is found, and an incremented _counter_ value and will store the aforementioned in their corresponding data structures.
```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/plugin/plugin-class.adoc
> +After you add all the aforementioned code, The HelloInfoPlugin is ready to sync and store `newHello` events data regularly.
```suggestion
After you add all the aforementioned code, The `HelloInfoPlugin` is ready to sync and store `newHello` events data regularly.
```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +If the given value is already taken by another sidechain, the "Sidechain Registration" transaction fails.
```suggestion
If the given value is already taken by another sidechain, the "Sidechain Registration" transaction will fail.
```

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  To check if a certain chain ID is still available in the network, call RPC endpoint `interoperability_isChainIDAvailable` with the chain ID as parameter.
**LINE 173**
An example of how to sort the validator list can be found in the example script {url_github_exmaples_sidechaintegistration}[sidechainRegistration.ts^].

2023-03-30 12:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  {url_exmaples_guides_createparams}[paramsCreation.ts^]
**Line 1679**
Copy the transaction and send it to the node, for example by using the node CLI like so:

2023-03-30 13:00 UTC, Tschakki commented on docs/modules/ROOT/images/build-blockchain/hello-client.png
Does it look bad for you?
I always use screen quality to export the documentation diagram, imho it is big enough

2023-03-30 13:00 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/create-blockchain-client.adoc
packet to package

2023-03-30 13:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/images/build-blockchain/hello-client.png
Yes, the earlier image was print quality 300 ppi. That looks much sharper.

2023-03-30 13:21 UTC, Tschakki commented on docs/modules/ROOT/images/build-blockchain/hello-client.png
Does it really look bad for you, when you look at it on the website?
I am not sure if we should use print quality, because it might decrease the loading speed of the docs, which is also not best for SEO.Using "screen" quality export sounds to me like it is optimized to look good on screens.

2023-03-30 14:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/images/build-blockchain/hello-client.png
It does! IMHO we should always use print quality, as it looks far better in terms of color reproduction, especially light colors, and also the text looks sharper as well. I always use print quality for all the diagrams. 
I am not sure about the effect on speed and if there is any I think it's negligible as the file size doesn't drastically increase between the screen and print quality. From what I have checked in the current `lisk-docs` repo, it's in KBs and not in MBs so shouldn't be a problem for our servers 🙂.

For reference, see the following two images. The first one is the recent image and the second one is the print quality:

- https://raw.githubusercontent.com/LiskHQ/lisk-docs/708d018c129152d87da1f05a000f82197e5482df/docs/modules/ROOT/images/build-blockchain/hello-client.png
- https://raw.githubusercontent.com/LiskHQ/lisk-docs/486c63541024ca639ac07bc1f5da3051961c8255/docs/modules/ROOT/images/build-blockchain/hello-client.png

2023-03-30 15:03 UTC, TalhaMaliktz approved these changes
Thank you. LGTM 🎉

2023-03-30 18:38 UTC, bobanm requested changes
Hope this feedback is helpful 🙂

2023-03-30 18:38 UTC, bobanm commented on docs/modules/ROOT/nav.adoc
> +** xref:integrate-blockchain/integrate-ui/index.adoc[Integrating a User-Interface]
This is the first time I've seen _user interface_ written with a hyphen: _user-interface_

2023-03-30 18:38 UTC, bobanm commented on docs/modules/ROOT/pages/build-blockchain/configuration.adoc
>  * xref:{url_references_config_modules}[`modules`]
The title on line 47 says "Configs for the node operator".

This is inconsistent not only with the previous title, which says "Configurations for the blockchain developer", but also with all other parts of the documents which use word "configuration" instead of "config".

2023-03-30 18:38 UTC, bobanm commented on docs/modules/ROOT/pages/build-blockchain/configuration.adoc
> +A *blockchain developer* sets the following configurations, - *a node operator should not change them.*
This comma followed by a hyphen looks weird.

How about splitting it in 2 sentences for better readability?

```suggestion
A *blockchain developer* sets the following configurations. *A node operator should not change them.*
```

2023-03-30 18:38 UTC, bobanm commented on docs/modules/ROOT/pages/build-blockchain/configuration.adoc
> +* [x] What config options can only be changed by blockchain developers?
Better check this with a native English speaker such as @chris529: I think that in this case since there are limited and known config options, "which config options" would be more suitable than "what config options".

2023-03-30 18:38 UTC, bobanm commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
> +The data path of a plugin inherits the data path of the blockchain client and is mentioned in the _config.json_ or _custom_config.json_ file.
Is "datapath" from line 42 the same thing as "data path" from line 43?

If yes, it would be good to align the spelling 🙂

2023-03-31 08:28 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +** xref:integrate-blockchain/integrate-ui/index.adoc[Integrating a User-Interface]
True, removed the hyphen

2023-03-31 08:30 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/configuration.adoc
>  * xref:{url_references_config_modules}[`modules`]
Replaced with `Configurations` 👍

2023-03-31 09:19 UTC, bobanm approved these changes

2023-03-31 09:41 UTC, merged