Update terminology in SDK docs
LiskArchive/lisk-legacy-docs pull request #1760
Opened 2023-03-29 12:25 UTC by Tschakki

Closes #1745

2023-03-31 14:20 UTC, mosmartin approved these changes

2023-04-03 10:13 UTC, TalhaMaliktz requested changes

2023-04-03 10:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +  transaction    Commands relating to transactions.
'sidechain' is the name of the blockchain client. I checked the latest CLI and it still has the client's name. IMHO it would be appropriate to use 'my-blockchain-client' (or a simpler name) in the description of commands instead of removing it.

2023-04-03 10:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +  ./bin/run config:show    Shows config.
Since we are using the term `node` in the subsequent snippets. I think we can use the same term throughout the document, instead of removing `application`

2023-04-03 10:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +TIP: For mor information on how to create and use a *custom configuration* for the client, please check out the guide xref:{url_configure_app_guide}[].
```suggestion
TIP: For more information on how to create and use a *custom configuration* for the client, please check out the guide xref:{url_configure_app_guide}[].
```

2023-04-03 11:43 UTC, Tschakki commented on modules/ROOT/pages/client-cli.adoc
> +  transaction    Commands relating to transactions.
I see it is not 100% accurate, but imho it is easier to understand like that. I would prefer not to change it.

2023-04-03 11:53 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2023-04-03 12:22 UTC, merged