Update terminology of the run blockchain category
LiskArchive/lisk-legacy-docs pull request #1762
Opened 2023-03-30 15:36 UTC by chris529

Closes #1741

2023-04-04 10:26 UTC, Tschakki requested changes
Looks good, just a small correction 👍

2023-04-04 10:26 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/process-management.adoc
> +Let's create a script for the xref:{url_build_hello_client}["Hello World"] or for a xref:{url_core_client}[Lisk Core] node.
This guide should be held general for node operators, no need to mention Hello World example app.

```suggestion
Let's create a script for the blockchain node.
```

2023-04-04 11:01 UTC, Tschakki approved these changes
LGTM

2023-04-05 14:46 UTC, Incede approved these changes

2023-04-05 14:46 UTC, Incede commented on docs/modules/ROOT/pages/run-blockchain/process-management.adoc
> +// It is recommended to set up an additional process management tool to run a blockchain client{fn_sidechain_client_glossary}.
```suggestion
```
I believe the comment was unintentional :)

2023-04-05 14:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/process-management.adoc
> +// It is recommended to set up an additional process management tool to run a blockchain client{fn_sidechain_client_glossary}.
It's intentional since we are going to update the glossary at a later stage. Till then, the URL mentioned in the commented line will not work. Will use this line when the glossary is ready.

2023-04-05 15:03 UTC, merged