Update node management section
LiskArchive/lisk-legacy-docs pull request #1763
Opened 2023-03-30 16:20 UTC by TalhaMaliktz

Closes #[745](https://github.com/LiskHQ/lisk-core/issues/745) in lisk-core

2023-03-31 06:25 UTC, chris529 approved these changes
LGTM! 👍

2023-03-31 12:50 UTC, Tschakki requested changes

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +For example, by broadcasting and receiving blocks or transactions from their peers.
Would remove this part or move to Lisk Core docs under https://liskhq.github.io/lisk-docs/lisk-core/v4/index.html#networks 

Also, I am not sure if the number 2,000 is up to date, we should probably double-check it is roughly correct, or remove the number.

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +* *Exchanges* and other services that rely on a stable API interface to the network.
Add here:

- 
```suggestion
* *Exchanges, Web3 app developer*and other services that rely on a stable API interface to the network.
* *Relayers*: Who participate in the Lisk cross-chain communication by relaying CCUs.
```

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +* *Validators* who have registered as a validator and would like to actively generate new blocks.
To become validator, you need to register, so the statement was a little redundant.

```suggestion
* *Validators* who would like to actively generate new blocks.
```

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +* *Users* who do not trust external sources and want to be in full control over their node.
```suggestion
* *Users* who do not trust external sources and want to be in full control over their own node.
```

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +- To acquire full control in order to configure the node to your specific requirements.
This sections sounds redundant to the previous section. Would remove/merge the two sections.

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +** xref:{url_configuration}[Client Configuration]
Would add this link under `How to set up a Lisk Mainnet node` section, under the setup guides, or remove here.

2023-03-31 12:50 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +** xref:{url_run_pm2}[]
Would add this link under `How to set up a Lisk Mainnet node` section

2023-03-31 17:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/index.adoc
> +For example, by broadcasting and receiving blocks or transactions from their peers.
Text removed

2023-04-03 09:29 UTC, Tschakki approved these changes
Thank you!

2023-04-03 09:31 UTC, merged