Understand blockchain terminology updates - bottom
LiskArchive/lisk-legacy-docs pull request #1766
Opened 2023-04-05 10:30 UTC by Tschakki

Partially closes #1739

2023-04-05 14:47 UTC, TalhaMaliktz requested changes

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +All modules of collectively define the *on-chain logic* of a Lisk application.
```suggestion
All modules collectively define the *on-chain logic* of a Lisk application.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +The Lisk apps emit RPC events and Blockchain events, which each follow very different concepts.
```suggestion
The Lisk apps emit RPC events and Blockchain events, whereby each follows very different concepts.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +A blockchain application communicates via interfaces i.e. <<endpoints>> and <<events>>.
```suggestion
A Lisk application communicates via interfaces i.e. <<endpoints>> and <<events>>.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +The three modes of communication i.e. IPC, WS, and HTTP allow blockchain applications to communicate with Lisk nodes.
```suggestion
The three modes of communication i.e. IPC, WS, and HTTP allow Lisk applications to communicate with Lisk nodes.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +TIP: To conveniently communicate with a blockchain application, use the `apiClient` included in the `@liskhq/lisk-client` and the `lisk-sdk` packages.
```suggestion
TIP: To conveniently communicate with a Lisk application, use the `apiClient` included in the `@liskhq/lisk-client` and the `lisk-sdk` packages.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/rpc.adoc
> +A blockchain application communicates to the blockchain by requesting the RPC endpoints of a blockchain node.
```suggestion
A Lisk application communicates to the blockchain by requesting the RPC endpoints of a blockchain node.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +* Data
This should be **elements** and not **data** as it describes all components of a plugin and not all of them can be categorized as data. Elements is a more suitable term here, as combining all or some of the elements make a plugin.

```suggestion
* Elements
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +=== Data
Same comment here as well.
```suggestion
=== Elements
Each plugin inherits functions and properties from the `BasePlugin` class.
```

2023-04-05 14:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +It's worth noting that the directory structure of a plugin can be customized as per the requirement of the blockchain application.
```suggestion
It's worth noting that the directory structure of a plugin can be customized as per the requirement of the Lisk application.
```

2023-04-05 15:12 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +* Data
I changed the term to avoid confusion with Lisk Elements.

Additionally, imho "Elements" doesn't fit well to describe the components, because interface and execution logic are also elements of the plugin. "Data" was just a quick guess from my side, but for me it is kind of fitting for attributes like name, data path, schemas, types and so on. At least more than just "elements".

2023-04-05 15:41 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +* Data
Even with Lisk elements, the analogy is the same. Elements combine together to make something bigger, which is true for both Lisk elements and Plugins in this case. 
As a second suitable term, I would suggest the term **component** as an alternative. The selected term also needs to be updated in the diagram as well.

2023-04-06 09:27 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +* Data
I restructured the list to start with execution logic, then interfaces, and as a third point i renamed "elements" to "other properties". I restrustured like this, because execution logic/interfaces are properties/elements of the plugin, as well.

2023-04-06 10:51 UTC, TalhaMaliktz approved these changes
Thanks, LGTM 🎉

2023-04-06 10:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +A Schema of a plugin contains the structural information of the data accepted by a plugin.
```suggestion
A schema of a plugin contains the structural information of the data accepted by a plugin.
```

2023-04-06 14:18 UTC, mjerkov requested changes
Looks good, only (mostly) minor comments.

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +This method is called to verify if the sender of a transaction has enough balance to pay the transaction fee.
I think that LIP 0043 (Introduce chain registration mechanism) had a `getAvailableBalance` call in some of the previous versions, but it doesn't have it any more. 
I see that `getAvailableBalance` is called only from LIP 0048 (Fee module) and LIP 0052 (NFT module), maybe you can use one of those two cases instead.

In case you change this, then the accompanying example should also be changed.

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +By default, a bootstrapped plugin has the `load()` and `unload` functions.
```suggestion
By default, a bootstrapped plugin has the `load()` and `unload()` functions.
```

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +More can be added if needed and all the functions have access to the methods and properties defined in the `BasePlugin` class.
For better readability:

```suggestion
Additional functions can be added if needed, and all the functions have access to the methods and properties defined in the `BasePlugin` class.
```

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
> +To subscribe to an event see, xref:{url_subscribe_events}[How to subscribe to events].
```suggestion
To subscribe to an event, see xref:{url_subscribe_events}[How to subscribe to events].
```

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
>  Usually, schemas are present inside the *schemas.ts* file located inside a plugin's folder.
I see that in some places you changed **filename.ts** to `filename.ts`. It would be good to be consistent with this change throughout the document.

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
>  The contents of the schemas.ts file are described below:
```suggestion
The contents of the `schemas.ts` file are described below:
```

2023-04-06 14:18 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
>  The contents of the schemas.ts file are described below:
```suggestion
The contents of the `schemas.ts` file are described below:
```

2023-04-06 15:12 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
>  Usually, schemas are present inside the *schemas.ts* file located inside a plugin's folder.
thanks, i applied your suggestions!

2023-04-06 15:29 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/sdk/modules-commands.adoc
> +This method is called to verify if the sender of a transaction has enough balance to pay the transaction fee.
I have updated the example 👍

2023-04-06 15:40 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/sdk/plugins.adoc
>  Usually, schemas are present inside the *schemas.ts* file located inside a plugin's folder.
Ah, OK, I understand. The first mention is bold, the other one is inside ` `, right? Feel free to resolve.

2023-04-06 15:41 UTC, mjerkov approved these changes
Looks good!

2023-04-06 16:42 UTC, merged