Understand blockchain terminology updates 2 - Closes 1739
LiskArchive/lisk-legacy-docs pull request #1767
Opened 2023-04-05 11:05 UTC by TalhaMaliktz

Closes #1739

2023-04-05 11:30 UTC, Tschakki requested changes
By searching for the term "sidechain", I found a lot of locations where it is still used. Imho, it should be replaced with "blockchain", unless it is in the context of blockchain interoperability.

2023-04-05 11:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  ****
`== The three domains of a sidechain`

should be 

`== The three domains of a blockchain`

2023-04-05 11:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
`The application layer handles state changes to the blockchain.`

2023-04-05 11:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +A blockchain client relies heavily on its state machine to mutate the state of a sidechain.
```suggestion
A blockchain client relies heavily on its state machine to mutate the state of a blockchain.
```

2023-04-05 11:30 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Lisk app developers can create their own custom business logic for the sidechain by creating their own modules or reusing existing ones, and registering them to the client.
```suggestion
Lisk app developers can create their own custom on-chain business logic by creating their own modules or reusing existing ones, and registering them to the client.
```

2023-04-05 12:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Lisk app developers can create their own custom business logic for the sidechain by creating their own modules or reusing existing ones, and registering them to the client.
```suggestion
Lisk app developers can implement custom on-chain business logic for the blockchain.
This can be done by either creating their own modules or reusing existing ones and registering them with the client.
```

2023-04-06 09:31 UTC, Tschakki approved these changes
LGTM 🎉

2023-04-06 12:21 UTC, mjerkov requested changes
Looks good, not many comments from my side.

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +The "Hello World" Lisk application provides the following features:
I don't know how important it is, but the Sapphire terminology table specifically uses "Lisk app", not "Lisk application". Probably an irrelevant comment. 
However, if this needs to be changed, then you should use "blockchain app" instead of "blockchain application" and "Lisk app" instead of "Lisk application" consistently throughout this and other documents. 
But I wouldn't be so exclusive and would allow for the usage of "application" word, too.

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +In contrast to normal server-client applications, there is not one central backend, but rather a whole network of nodes running instances of a similar blockchain client, that together secure and main
For better readability I inserted "However":

```suggestion
However, in contrast to traditional server-client applications, there is not one central backend, but rather a whole network of nodes running instances of a similar blockchain client, that together secure and maintain the status of the blockchain.
```

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
>  * *On-chain* data includes but is not limited to state data of the chain, account balance, nonce, multi-signature keys, generators' information, and the Sparse Merkel tree, etc.
```suggestion
* *On-chain* data includes but is not limited to state data of the chain, account balance, nonce, multi-signature keys, generators' information, and the Sparse Merkle tree, etc.
```

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +Lisk applications usually consist of a frontend and a backend (blockchain client), just like normal web applications.
```suggestion
Lisk applications usually consist of a frontend and a backend (blockchain client), just like traditional web applications.
```
Alternatively, you can use "usual" instead of "traditional", but (in my opinion) "traditional" is better.

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
>  A *sparse Merkle tree (SMT)* is very similar to a regular Merkle Tree, with the following difference:
```suggestion
A *Sparse Merkle Tree (SMT)* is very similar to a Regular Merkle Tree, with the following difference:
```

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
> +|Proofs-of-Inclusion for Events in a Block|`eventRoot`| The root of the event sparse Merkle tree is added to the block header to allow checking the inclusion and non-inclusion of events.
```suggestion
|Proofs-of-Inclusion for Events in a Block|`eventRoot`| The root of the event Sparse Merkle Tree is added to the block header to allow checking the inclusion and non-inclusion of events.
```

Please check also other parts of the document, in order to be consistent with the capitalization choice for SMTs and RMTs.

2023-04-06 12:21 UTC, mjerkov commented on docs/modules/ROOT/pages/understand-blockchain/state-machine.adoc
>  * The state machine is *replicated* across many nodes.
```suggestion
* The state machine is *replicated* across multiple nodes.
```

2023-04-06 12:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/index.adoc
> +The "Hello World" Lisk application provides the following features:
At the moment we are using the term "application" and its contraction: "app" as per need. I agree that we shouldn't be exclusive about the term "app" and should use "application" as well.

2023-04-06 12:57 UTC, mjerkov approved these changes
All good!

2023-04-06 13:28 UTC, merged