Update terminology frontend boilerplate docs - Closes 316 in lisk-sdk-examples
LiskArchive/lisk-legacy-docs pull request #1770
Opened 2023-04-13 15:12 UTC by TalhaMaliktz

Closes #316 in lisk-sdk-examples

2023-04-14 08:44 UTC, Tschakki requested changes

2023-04-14 08:44 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const bftParams = await blockchainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
Here, the sidechain client is meant in the context. Please revert the changes.

2023-04-14 08:55 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const bftParams = await blockchainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
Ummmm, the client can only be a blockchain client per the terminology agreement. A node can be for a sidechain or a mainchain, however, the client can only be a blockchain client. I can update the comment to say something like this:
"// Update the path to point to your blockchain client data folder for the sidechain" to make it clearer.

2023-04-14 09:57 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const bftParams = await blockchainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
Yes, that sounds good..I think to further enhance the clarity in this statement, imho I would suggest the following:
"// Update the path to point to your blockchain client data folder for the respective sidechain"

2023-04-14 09:58 UTC, chris529 reviewed
Looks great! Only 1 minor suggestion 👍

2023-04-14 15:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	// Update the path to point to your blockchain client data folder
```suggestion
	// Update the path to point to your blockchain client data folder for the respective sidechain
```

2023-04-14 15:44 UTC, chris529 approved these changes
LGTM! 👍

2023-04-17 08:41 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const bftParams = await blockchainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
I think this is unnecessary complicated. In this specific context of sidechain/mainchain communication, it still makes sense to talk about sidechain and mainchain nodes and blockchain clients. Also, if you want to be 100% precise here, you are connecting to a node, not the client. In the end, we would also need to update this in the code and I don't think it is necessary. Please just revert the changes.

2023-04-17 10:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const sidechainNodeInfo = await blockchainClient.invoke('system_getNodeInfo');
```suggestion
	// Update the path to point to your sidechain client data folder
	const sidechainClient = await apiClient.createIPCClient('~/.lisk/hello_client');
	const sidechainNodeInfo = await sidechainClient.invoke('system_getNodeInfo');
```

2023-04-17 10:43 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const bftParams = await blockchainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
```suggestion
	const bftParams = await sidechainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
```

2023-04-17 10:56 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	const bftParams = await blockchainClient.invoke('consensus_getBFTParameters', { height: sidechainNodeInfo.height });
Changes reverted.

2023-04-17 13:05 UTC, Tschakki approved these changes
LGTM

2023-04-18 11:13 UTC, merged