Add network page
LiskArchive/lisk-legacy-docs pull request #1773
Opened 2023-05-02 14:58 UTC by Tschakki

Closes #1489

2023-05-03 12:52 UTC, chris529 reviewed
Looks great! Just a few very minor points 👍

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +But it is also possible to whitelist or blacklist specific peers in the node config.
```suggestion
However, it is also possible to whitelist or blacklist specific peers in the node config.
```

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +. Every peer accepts up to 100 incoming connections from other peers, which are distinct from the outgoing peers.
imho, we should reword this line as follows:
"Every peer accepts up to 100 incoming connections from other peers, which are distinguishable from the outgoing peers.''

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +This makes the network more dynamic and prevents against network attacks.
```suggestion
This results in the network being more dynamic and also prevents against network attacks.
```

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +Furthermore, nodes announce that a new block has been received by sending the block hash to the rest of the connected peers, which can request the full block in case it has not been received yet (<<e
```suggestion
Furthermore, nodes announce that a new block has been received by sending the block hash to the remaining connected peers, which can request the full block in the case whereby it has not yet been received (<<eager-and-lazy-push-mechanism,lazy-push>>).
```

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +Lisk uses a hybrid of eager and lazy push mechanism for blocks, in order to save bandwidth while maintaining a fast propagation of information in the network.
```suggestion
Lisk uses a hybrid of an eager and lazy push mechanism for blocks, in order to save bandwidth whilst maintaining a fast propagation of information throughout the network.
```

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +Incoming and outgoing only refers to the node who initiated the connection first:
```suggestion
Incoming and outgoing only refer to the node that initiated the connection first:
```

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +* "Outgoing" means, the node initiated the connection,
```suggestion
* "Outgoing" means, the node initiated the connection.
```

2023-05-03 12:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +xref:{url_transactions_id}[Transactions] are propagated through the network via lazy push mechanism.
```suggestion
xref:{url_transactions_id}[Transactions] are propagated through the network via the lazy push mechanism.
```

2023-05-03 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +. Every peer accepts up to 100 incoming connections from other peers, which are distinct from the outgoing peers.
```suggestion
. Every node accepts up to 100 incoming connections from other peers, which are distinguishable from the outgoing connections.
```

2023-05-03 14:59 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +The peers are notified about the block after the block and its related state changes were executed successfully on the node.
imho, we should reword this statement slightly as it might be a bit confusing, so I would suggest the following:
"After the successful execution of the block and its related state changes on the node, the peers are then informed about the respective block."

2023-05-03 15:02 UTC, chris529 approved these changes
LGTM! 👍 
I just left 1 minor recommendation.

2023-05-03 15:20 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +The peers are notified about the block after the block and its related state changes were executed successfully on the node.
```suggestion
Furthermore, after the successful execution of the block and its related state changes on the node, the remaining peers are then informed about the respective block.
The nodes informs that a new block has been received by announcing the block hash to the peers, which can request the full block in the case whereby it has not yet been received (<<eager-and-lazy-push-mechanism,lazy-push>>).
```

2023-05-04 11:44 UTC, vjaiman requested changes
Looks good. Left some minor comments.

2023-05-04 11:44 UTC, vjaiman commented on docs/modules/ROOT/images/understand-blockchain/block-propagation.png
Diagram has been updated https://github.com/LiskHQ/lips/pull/333/files

2023-05-04 11:44 UTC, vjaiman commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +A node uses eager push for a small number of the connected peers and lazy push for the majority of the connected peers.
Would be good to explicitly state the eager and lazy push mechanism. For example, 
eager push: blocks are directly pushed to a subset of the peers
lazy push: new blocks are only announced to the peers by sending the block hash or header and not the full payload. 
If you think that it is clear from the text, you can discard the suggestion.

2023-05-04 13:49 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +A node uses eager push for a small number of the connected peers and lazy push for the majority of the connected peers.
Thanks, I added the definition now 👍

2023-05-04 14:03 UTC, vjaiman approved these changes
Looks good. Left some cosmetic changes.

2023-05-04 14:03 UTC, vjaiman commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +eager push:: blocks are directly pushed to a subset of the peers
```suggestion
Eager push:: Blocks are directly pushed to a subset of the peers.
```

2023-05-04 14:03 UTC, vjaiman commented on docs/modules/ROOT/pages/understand-blockchain/network.adoc
> +lazy push:: new blocks are only announced to the peers by sending the block hash or header and not the full payload.
```suggestion
Lazy push:: New blocks are only announced to the peers by sending the block hash or header and not the full payload.
```

2023-05-05 09:31 UTC, merged