Add pos poa explanations
LiskArchive/lisk-legacy-docs pull request #1774
Opened 2023-05-03 12:26 UTC by Tschakki

Closes #1245

2023-05-08 15:43 UTC, sergeyshemyakov reviewed
Generally looks very good as usual!

2023-05-08 15:43 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Blocks in the Lisk PoS protocol are grouped together into batches of 103 consecutive blocks, which are referred to as a *block generation round*.
I think the LIP does not use the term "block generation round", it just says "round". However, I don't see a problem with "block generation round".

2023-05-08 15:43 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +A *validator* is any account that successfully a Register Validator transaction.
Typo: "submitted" is missing.

2023-05-08 15:43 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +The first 101 validators in the validator list are also called *active validators*.
This sounds like the standby delegates forge in the end of the round. This is not how it happens according to [LIP0022](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0022.md): first the standby delegates are chosen and then the list of 103 validators is shuffled.

2023-05-08 15:43 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Additionally, PoA is suitable for blockchains where the expected staked capital in the case of PoS would not provide enough security, but staking the reputations of the active authorities would do so
I would quickly summarize this section concerning migration from PoA to PoS in the LIP: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0047.md#migration-from-poa-to-pos. I think it could be a popular case for apps to start with PoA and then plan a migration to PoS.

2023-05-08 15:46 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Blocks in the Lisk PoS protocol are grouped together into batches of 103 consecutive blocks, which are referred to as a *block generation round*.
I think we called it "forging round" before, just "round" sounds a bit too general for me. But if it is official(aligned) terminology, then I can change it

2023-05-08 16:14 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Additionally, PoA is suitable for blockchains where the expected staked capital in the case of PoS would not provide enough security, but staking the reputations of the active authorities would do so
Goodpoint, I have added a new section at the bottom

2023-05-09 11:20 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Blocks in the Lisk PoS protocol are grouped together into batches of 103 consecutive blocks, which are referred to as a *block generation round*.
I have confirmed with Greg, round is the official term.

2023-05-09 11:21 UTC, sergeyshemyakov approved these changes
Just one small comment standing from my side, otherwise everything is good.

2023-05-09 14:51 UTC, TalhaMaliktz requested changes
Looking good! Minor suggestions!

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
>  |* **Choosing validators**: Deciding who can be validator, i.e. who is allowed to add new blocks to the blockchain.
```suggestion
|* **Choosing validators**: Deciding who can be a validator, i.e. who is allowed to add new blocks to the blockchain.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/index.adoc
> +Certificates are crucial for submitting xref:{url_understand_ccu}[cross-chain updates] to other blockchains as they attest outgoing cross-chain messages and changes of validators.
```suggestion
Certificates are crucial for submitting xref:{url_understand_ccu}[cross-chain updates] to other blockchains as they attest to outgoing cross-chain messages and changes of validators.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +The higher the stake of a validator, the higher is the probablity to reach a spot und the active validators, who are allowed to generate new blocks in the network.
```suggestion
The higher the stake of a validator, the higher the probability to reach a spot of an active validator, who is allowed to generate new blocks in the network.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +The PoS consensus algorithm provides higher decentralization than <<poa>>, and a much lower computation effort than PoW (Proof of Work), and provides therefore a good middleground between decentraliz
```suggestion
The PoS consensus algorithm provides higher decentralization than <<poa>>, and a much lower computation effort than PoW (Proof of Work), and therefore, provides a good middle ground between decentralization and scalability.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +At the same time, the maintanance effort of PoS blockchains is significantly higher than for PoA blockchains, making it more suitable for middle-sized and big projects.
```suggestion
At the same time, the maintenance effort of PoS blockchains is significantly higher than for PoA blockchains, making it more suitable for middle-sized and big projects.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +To become an active validator, a validator needs to increase their validator weight, until they are among the top 101 validators with the most validator weight.
```suggestion
To become an active validator, a validator needs to increase its validator weight until they are among the top 101 validators with the most validator weight.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +By registering as validator, it is possible to *receive stakes* from other accounts.
```suggestion
By registering as a validator, it is possible to *receive stakes* from other accounts.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Depending on the stakes, every validator has an associated <<validator-weight>>, which is an indicator for the support for this validator in the network.
```suggestion
Depending on the stakes, every validator has an associated <<validator-weight>>, which is an indicator of the support for this validator in the network.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +That means, the tokens used for staking stay in the account of the staker, but while they are used for staking, they cannot be used for any other purposes for example token transfers.
```suggestion
That means, the tokens used for staking stay in the account of the staker, but while they are used for staking, they cannot be used for any other purposes, for example, for token transfers, etc.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +Moreover, add 2 standby validators to the list using a random selection proportional to validator weight.
```suggestion
Moreover, add 2 standby validators to the list using a random selection proportional to the validator weight.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +As a fail-safe mechanism, a validator that does not generate blocks for an extended period of time is banned.
```suggestion
As a fail-safe mechanism, a validator that does not generate blocks for an extended period is banned.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +This is to avoid the situation where a validator who is not running a node leads to frequent missed block slots.
```suggestion
This is to avoid the situation where a validator who is not running a node leads to frequently missing block slots.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +At one point, there may be an interest for some projects that started as a PoA chain to migrate to PoS.
```suggestion
At one point, there may be an interest in some projects that started as a PoA chain to migrate to PoS.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +PoA chains could implement no rewards at all, or block rewards as defined in {url_github_lip_42}[LIP 0042^], however PoS chains could profit from dynamic rewards proportional to weight of the generat
```suggestion
PoA chains could implement no rewards at all, or block rewards as defined in {url_github_lip_42}[LIP 0042^], however, PoS chains could profit from dynamic rewards proportional to the weight of the generator.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/images/understand-blockchain/validator-list.jpeg
Contains a type: stanby

Please also align the yellow stickers horizontally. The one on the right looks a bit higher as compared to the one on the left.

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +In Proof-of-Stake (PoS) blockchains validators stake tokens to increase their weight in the network.
```suggestion
In Proof-of-Stake (PoS) blockchains, validators stake tokens to increase their weight in the network.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +A *validator* is any account that successfully submitted a Register Validator transaction.
```suggestion
A *validator* is any account that successfully submits a Register Validator transaction.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/images/understand-blockchain/validator-list.jpeg
Please correct the typo: stanby
Please also align the yellow shapes horizontally as the one on the right seems a bit higher then the one on the left.

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +If every validator on the list manages to generate a block in their block slot building on the block by the previous validator, a round lasts 1030 seconds (around 17 minutes).
```suggestion
If every validator on the list manages to generate a block in their block slot building on the block by the previous validator, a round lasts 1,030 seconds (around 17 minutes).
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +
Please add an appropriate caption for the image.

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +The validator list for a round is assigning a block generation position for each validator eligible to generate a block in the round.
```suggestion
The validator list for a round assigns a block generation position for each validator eligible to generate a block in the round.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +. Update threshold for finality
```suggestion
. Remove/Add authorities (the length of the list of authorities can change as a result).
. Change the BFT weight of authorities.
. Update threshold for finality.
```

2023-05-09 14:51 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +. an _aggregate multi-signature_ whereby enough active authorities have contributed to, such that the sum of the corresponding BFT weights meets the finality threshold.
```suggestion
. An _aggregate multi-signature_ whereby enough active authorities have contributed to, such that the sum of the corresponding BFT weights meets the finality threshold.
```

2023-05-10 08:23 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +The higher the stake of a validator, the higher is the probablity to reach a spot und the active validators, who are allowed to generate new blocks in the network.
```suggestion
The higher the stake of a validator, the higher the probability to reach a spot as an active validator, who is allowed to generate new blocks in the network.
```

2023-05-10 08:23 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/consensus/pos-poa.adoc
> +The higher the stake of a validator, the higher is the probablity to reach a spot und the active validators, who are allowed to generate new blocks in the network.
```suggestion
The higher the stake of a validator, the higher the probability to reach a spot as an active validator, who is allowed to generate new blocks in the network.
```

2023-05-10 13:05 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-05-10 13:12 UTC, merged