Update PubSub API reference for Lisk Service
LiskArchive/lisk-legacy-docs pull request #1779
Opened 2023-05-10 14:22 UTC by Tschakki

Closes #1575

2023-05-11 16:04 UTC, sameersubudhi approved these changes
LGTM 👍

2023-05-12 10:47 UTC, TalhaMaliktz requested changes
Looking good already! Just a few minor suggestions.

2023-05-12 10:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
>  The specification below contains numerous examples how to use the API in practice.
```suggestion
The specification below contains numerous examples of how to use the API in practice.
```

2023-05-12 10:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> +* and `entity` is a part of the application logic, ex. `accounts`, `transactions`.
```suggestion
* and the `entity` is a part of the application logic, ex. `accounts`, `transactions`.
```

2023-05-12 10:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
> +[source,js]
```suggestion
[source,json]
```

2023-05-12 10:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-pubsub.adoc
>  [source,js]
```suggestion
[source,json]
```

2023-05-12 13:50 UTC, TalhaMaliktz approved these changes
LGTM

2023-05-12 14:29 UTC, merged