Update the resetting and snapshotting node guide in lisk docs
LiskArchive/lisk-legacy-docs pull request #1783
Opened 2023-05-12 09:18 UTC by chris529

Closes #1748

2023-05-22 13:28 UTC, TalhaMaliktz requested changes
Since the **export** and **import** blockchain features will be helpful for most users re-setting the blockchain db. Maybe we can restructure the content to the following TOC

- Export data (Taking a backup of the existing on-chain data)
- Reset Database
- Import existing data, once the database is reset.

Also, please update the `nav.adoc` file to include this page.

2023-05-22 13:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>  Stores blocks, transactions and states.
```suggestion
Stores blocks, transactions, and states.
```

2023-05-22 13:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +This stores on-chain data, specifically, the state of each module with the state merkle tree.
```suggestion
This stores on-chain data, specifically, the state of each module with the state Merkle tree.
```

2023-05-24 12:40 UTC, TalhaMaliktz requested changes

2023-05-24 12:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>  To export the blockchain data of an application, run the following command:
**Line 40** should be 
```
$ ./bin/run blockchain:export
```

2023-05-24 12:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>    blockchain:export --data-path ./data --output ./my/path/
The command reference mentioned in lines 45-62 is redundant. To avoid redundancy and ease content management, please replace the aforementioned text with a sentence that links to the reference of [blockchain:export](https://liskhq.github.io/lisk-docs/lisk-sdk/v6/client-cli.html#blockchainexport).

2023-05-24 12:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +----
The command reference mentioned in lines 94-115 is redundant. To avoid redundancy and ease content management, please replace the aforementioned text with a sentence that links to the reference of [blockchain:import](https://liskhq.github.io/lisk-docs/lisk-sdk/v6/client-cli.html#blockchainimport).

2023-05-24 12:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>  To import a snapshot of blockchain data, run the following command:
Line 89 should be
```
./bin/run blockchain:import /Users/xyz/blockchain.db.tar.gz
```

2023-05-24 14:35 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>  To export the blockchain data of an application, run the following command:
Well spotted! 👍

2023-05-24 15:10 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>    blockchain:export --data-path ./data --output ./my/path/
OK, it is now done.

2023-05-25 08:05 UTC, TalhaMaliktz requested changes

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
>  If plugins are registered in the application, they will have a separate key-value store for each plugin for the plugin-specific off-chain data under `~/.lisk/BAPP-NAME/plugins/data/`.
```suggestion
If plugins are registered in the application, they will have a separate key-value store for the plugin-specific off-chain data under `~/.lisk/BAPP-NAME/plugins/data/`.
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +In order to view the command reference, this can be found here on the xref:{url_client_cli_export}[Client CLI] page.
```suggestion
In order to view the `blockchain:export` command reference, check out the xref:{url_client_cli_export}[Client CLI] page.
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +Please note that the blockchain height will be reset back to 1 again the next time the application is started, and all existing accounts will be deleted. In addition, the genesis accounts will be res
```suggestion
Please note that the blockchain height will be reset back to 1 again the next time the application is started, and all existing accounts will be deleted.
In addition, the genesis accounts will be reset to the state defined in the respective genesis block.
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +This can be achieved by using the `blockchain:reset` command of the application CLI.
```suggestion
This can be achieved by using the `blockchain:reset` command of the client CLI.
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +bin/run blockchain:reset
```suggestion
$ ./bin/run blockchain:reset
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on build/preview-site.yml
Please discard all the changes to this file, the changes shown below are whitespaces that have been added at the start of each line.

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +
```suggestion
:url_client_cli_reset: {docs_sdk}client-cli.adoc#blockchainreset
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
```suggestion
For more information about the `blockchain:reset` command, see the xref:{url_client_cli_reset}[Client CLI] page.
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +./bin/run blockchain:import blockchain.db.tar.gz
```suggestion
$ ./bin/run blockchain:import blockchain.db.tar.gz
```

2023-05-25 08:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +In order to view the command reference, this can be found here on the xref:{url_client_cli}[Client CLI] page.
```suggestion
In order to view the `blockchain:import` command reference, check out the xref:{url_client_cli}[Client CLI] page.
```

2023-05-30 06:11 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +In order to view the `blockchain:export` command reference, check out the xref:{url_client_cli_export}[Client CLI] page.
I am not able to access any link here, can you re-verify!

2023-05-30 06:54 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +NOTE: Before using the command, ensure the application is stopped and is not running anymore.
Just a suggestion
```suggestion
NOTE: Before using the command, please make sure that the application is stopped and is not running anymore.
```

2023-05-30 08:21 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +In order to view the `blockchain:export` command reference, check out the xref:{url_client_cli_export}[Client CLI] page.
As discussed, now resolved.

2023-05-30 08:44 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/blockchain-reset.adoc
> +NOTE: Before using the command, ensure the application is stopped and is not running anymore.
As discussed, now updated accordingly.

2023-05-30 09:15 UTC, nagdahimanshu approved these changes
LGTM 👍

2023-05-31 12:20 UTC, TalhaMaliktz requested changes

2023-05-31 12:20 UTC, TalhaMaliktz commented on build/preview-site.yml
> +  snapshot: true
```suggestion
   url: ../ui/build/ui-bundle.zip
   snapshot: true
```

2023-06-01 08:02 UTC, TalhaMaliktz approved these changes
LGTM

2023-06-01 09:10 UTC, merged