Update RPC endpoints of Lisk Service - Closes #1574
LiskArchive/lisk-legacy-docs pull request #1786
Opened 2023-05-18 15:28 UTC by TalhaMaliktz

Closes #1574

2023-05-30 15:15 UTC, Tschakki requested changes

2023-05-30 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +For more information, see the guide on xref:{}[Connecting with Lisk Service endpoints].
Link is missing

2023-05-30 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +      "tokenID": "0400000000000000"
For docs, please use Testnet or Mainnet token- and chain IDs in the examples

2023-05-30 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|01967dba384998026fe028119bd099ecf073c05c045381500a93d1a7c7307e5b
Antora has difficulties in breaking long strings in tables in a pretty way.
To mitigate this, maybe consider to manually break long strings in a table in an uniform manner, and preserve the format by encapsulating the string between ` to make it monospace. e.g.

```suggestion
|`01967dba384998026fe028119bd099e
cf073c05c045381500a93d1a7c7307e5b`
```

2023-05-30 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +400 Bad Request::
I wouldn't document the error here, unless it is an endpoint-specific error, same for the documented error responses on the other endpoints.

2023-05-30 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`generatorAddress`
This parameter is not described in the HTTP API of Lisk Service - shouldn't both APIs offer the same API endpoints? Or does the RPC offer more endpoints/parameters for endpoints?

2023-05-30 15:15 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The endpoint can be invoked by sending a payload to it.
Isn't the payload the parameter?

2023-06-01 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`generatorAddress`
Please consider the following URL for new API content:
https://github.com/LiskHQ/lisk-service/blob/release/0.7.0/docs/api/version3.md#request-parameters

2023-06-01 11:17 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The endpoint can be invoked by sending a payload to it.
AFAIK No! Payload is passed into the body of a `POST` request, whereas params are passed in the URL of a `GET` request. For more information see [Parameters and Payload of an Operation](https://learn.openapis.org/specification/parameters.html#:~:text=Parameters%20are%20typically%20used%20to,provides%20content%20for%20that%20resource.).

> Parameters are typically used to identify a resource, whereas the message payload provides content for that resource.

2023-06-01 13:24 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`generatorAddress`
Ah yes, I probably overlooked it, thanks, it is there 👍 https://liskhq.github.io/lisk-docs/beta/api/lisk-service-http.html#/Blocks/get_blocks

2023-06-01 13:31 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The endpoint can be invoked by sending a payload to it.
I see, but then the naming is a little confusing, because we specify the payload as params, e.g. here: https://github.com/LiskHQ/lisk-docs/pull/1786/files#diff-4ae369dcd626f789e3bf5b28d232374fec7d3da314be9bf5a2c987cec481ef97R989

2023-06-01 13:50 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|01967dba384998026fe028119bd099ecf073c05c045381500a93d1a7c7307e5b
Thanks, the issue you mention is valid and to mitigate this, I have updated the width of columns to make more space for the content. Due to that, text-wrapping has improved. For strings like `blockID`, `publicKey`, `address`, etc. Antora manages okay and IMHO we shouldn't break these strings for better maintainability and easy copying of text if in case required.

In the past, I have broken strings such as transaction hash in the RPC API for Lisk nodes page coz that's where Antora fails to render an extremely long string. For stylistic preference and synchronicity of content throughout the page, I am avoiding the use of monospace.

2023-06-01 13:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The endpoint can be invoked by sending a payload to it.
That's because of the standard [Request Object](https://www.jsonrpc.org/specification#request_object) in JSON RPC 2.0.

2023-06-01 14:26 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +==== get.blocks
Can we also specify both RPC and HTTP endpoint here. For eg:

```suggestion
==== HTTP GET `/api/v3/blocks`
==== RPC `get.blocks`
```

2023-06-01 14:27 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +              "publicKey": null
```suggestion
              "publicKey": "e38fc26924497c4ec892e32d47c8d40c99791ae3e71bc2565f9e34a9c81825df"
```

2023-06-01 14:29 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +==== get.blocks.assets
Same as above. Let's add RPC and HTTP endpoint for all endpoints

2023-06-01 14:31 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Retrieves blocks from the blockchain based on properties such as `blockID`, `height`, `account`, etc.
```suggestion
Retrieves blocks from the blockchain based on the properties such as `blockID`, `height`, `address`, etc.
```

2023-06-01 14:41 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +==== get.blocks
Thanks, will make the change as discussed in huddle.

2023-06-01 14:49 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
>  |`transactionId`
```suggestion
|`transactionID`
```

2023-06-01 14:51 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|Command of a module e.g. `transfer` command of the token module.
```suggestion
|Combination of transaction moduleName:commandName.
```

2023-06-01 14:57 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +              "data": "welcome "
```suggestion
              "data": "welcome"
```

2023-06-01 14:58 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +                  "name": null
```suggestion
                  "publicKey": "1a186d8a1ab33501d6f04c6e98588c7aa0746800888f975f7481850bb193eab6",
                  "name": "genesis"
```

2023-06-01 14:59 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +  "skipVerify": false,
May be we can add a note to clarify these 2 properties:
skipVerify: A boolean indicator to skip the transaction verification
skipDecode: A boolean indicator to skip the auto-decoding of the event data

2023-06-01 15:06 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +          "command": "transfer",
```suggestion
          "command": "transferCrossChain",
```

2023-06-01 15:07 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +      },
Let's update the example response as request payload is for token:transferCrossChain transaction:
```suggestion
      "transactionFeeEstimates": {
          "minFee": "166000",
          "accountInitializationFee": {
              "tokenID": "0000000000000000",
              "amount": "5000000"
          },
          "messageFee": {
              "tokenID": "0000000000000000",
              "amount": "343000"
          }
      },
```

2023-06-01 15:09 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +          "0200000000000000": {
Lets try to use `mainnet` tokenID everywhere
```suggestion
          "0000000000000000": {
```

2023-06-01 15:10 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`transactionId`
```suggestion
|`transactionID`
```

2023-06-01 15:11 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Search can be done by passing an `address` or `transactionID` to the topic
```suggestion
Search can be done by passing an `address` or `transactionID` to the topic.
```

2023-06-01 15:14 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +      "address": "lskc94hx5zgu3vbydwj96v64r5pdfj4q3ytfxyw23"
```suggestion
      "address": "lskdwsyfmcko6mcd357446yatromr9vzgu7eb8y99"
```

2023-06-01 15:27 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +      "address": "lskc94hx5zgu3vbydwj96v64r5pdfj4q3ytfxyw23"
Why change this? 🤔

2023-06-01 15:28 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +      "address": "lskc94hx5zgu3vbydwj96v64r5pdfj4q3ytfxyw23"
Because `address` should be same for both request query as well for response meta.

2023-06-01 15:34 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`name`
```suggestion
|`chainName`
```

2023-06-01 15:34 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|Case-insensitive keyword search by `name`.
```suggestion
|Case-insensitive keyword search by `chainName`.
```

2023-06-01 15:35 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +      "name": "Lisk",
```suggestion
      "chainName": "Lisk",
```

2023-06-01 17:03 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +==== get.blocks
Please note that the HTTP API is already documented on a separate page, so imho it is not necessary to include it here as well

2023-06-02 06:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +==== get.blocks
If you both agree, I can remove the HTTP related content from the page and make it purely RPC related.

2023-06-02 07:01 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +==== get.blocks
Thank you for the clarification @Tschakki 👍. @TalhaMaliktz I agree to remove all the HTTP related content from this page to make it not confusing.

2023-06-02 10:21 UTC, Tschakki requested changes
Looking great already! Left some small remarks.

2023-06-02 10:21 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The endpoint can be invoked by sending a payload to it.
Well, then in a sense, payload is also param, if it is added in the params property? Maybe to avoid confusion we can just remove the phrase "No parameters required"?

2023-06-02 10:21 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +// ** xref:api/lisk-service-http.adoc[]
Can be removed

2023-06-02 10:21 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +** xref:api/lisk-service-rpc.adoc[]
Please move under the module-rpc-api pages

2023-06-02 11:29 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`senderPublicKey`
Currently, we don't support querying transactions by `senderPublicKey`. We can remove this.

2023-06-02 11:33 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Estimates the fee of a transaction before it is sent to the network node for execution.
```suggestion
Estimate the fees of a transaction before it is sent to the network node for execution.
```

2023-06-02 11:34 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +    "command": "transfer",
```suggestion
    "command": "transferCrossChain",
```

2023-06-02 11:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Estimates the fee of a transaction before it is sent to the network node for execution.
Does the endpoint allows multiple transactions to be passed in the request?

2023-06-02 11:39 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Estimates the fee of a transaction before it is sent to the network node for execution.
No, it allows only one transactions but returns different estimated fees for the given transaction. for example, dynamic fee, account initialisation fees, message fee etc.

2023-06-02 11:47 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +    "numberOfReqSignatures": 1,
```suggestion
    "numberOfSignatures": 1,
```

2023-06-02 12:00 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`tokenID`
`tokenID` should be required parameter for this endpoint

2023-06-02 12:05 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Retrieves the list of stakes sent by the specified user by their address, `publicKey`, or validator `name`.
```suggestion
Retrieves the list of stakes sent by the specified user by their `address`, `publicKey`, or validator `name`.
```

2023-06-02 13:26 UTC, Tschakki approved these changes
LGTM! 🎉

2023-06-02 13:26 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +The query parameters are passed in the `params` object. For example:
```suggestion
The query parameters or payload are passed in the `params` object. For example:
```

2023-06-06 13:38 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +  }
We either need to add `limit:25` to the params or update the description
```suggestion
  "params": {
      "address": "lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad",
      "limit:" 25
  }
```

2023-06-06 13:44 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +}
This endpoint only accept decoded payload. We can remove this.

2023-06-06 13:52 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|genesis_84
With tokenID, any one of these properties (name, address or publicKey) is required for this request. We can add comment highlighting this.

2023-06-06 13:55 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Endpoint related to dynamic fee module.
```suggestion
Endpoint related to dynamic fee estimates.
```

2023-06-06 13:56 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|genesis_84
One of the address, publicKey or name is required here

2023-06-06 14:02 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|Name of the blockchain.
```suggestion
|Name of the blockchain application.
```

2023-06-06 14:07 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|true, false value.
```suggestion
|Boolean value.
```

2023-06-06 14:09 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +|`chainID`
`chainID` is required parameter here.

2023-06-06 14:20 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +https://service.lisk.com/api/v3/exports/transactions_lsk9tovmsz2wvewcod7fd99p79wdbswtq9uyrs23t_2021-07-01_2023-05-26.csv
```suggestion
https://service.lisk.com/api/v3/export/download?filename=transactions_lsk9tovmsz2wvewcod7fd99p79wdbswtq9uyrs23t_2021-07-01_2023-05-26.csv
```

2023-06-09 10:06 UTC, nagdahimanshu reviewed
Looks good overall 👍 just couple of minor comments.

2023-06-09 10:06 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +Endpoint related to validators.
```suggestion
Endpoint related to validator module.
```

2023-06-09 10:06 UTC, nagdahimanshu commented on docs/modules/ROOT/pages/api/lisk-service-rpc.adoc
> +    "fileUrl": "/api/v3/exports/transactions_lskdxc4ta5j43jp9ro3f8zqbxta9fn6jwzjucw7yt_2021-03-16_2021-12-06.csv"
```suggestion
    "fileUrl": "/api/v3/export/download?filename=transactions_lsk9tovmsz2wvewcod7fd99p79wdbswtq9uyrs23t_2021-07-01_2023-05-26.csv"
```

2023-06-09 11:14 UTC, nagdahimanshu approved these changes
LGTM 👍

2023-06-09 12:47 UTC, merged