Update Lisk Elements index page
LiskArchive/lisk-legacy-docs pull request #1787
Opened 2023-05-22 07:36 UTC by chris529

Closes #1780

2023-05-31 13:33 UTC, ishantiw reviewed
If this update is related to 6.0.0 release in future then its correct but if its for beta or current release then it should `6.0.0-beta.1`

2023-05-31 14:09 UTC, TalhaMaliktz requested changes

2023-05-31 14:09 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-elements/index.adoc
>  `apiClient`, `codec`, `cryptography`, `passphrase`, `transactions`, `utils`, `tree`, and `validator`.
I would mention the names of the packages verbatim.
```suggestion
The `lisk-client` package is specifically designed to be used in the browser and other frontends.
It is a collection of the following packages:

`lisk-api-client`, `lisk-codec`, `lisk-cryptography`, `lisk-passphrase`, `lisk-transactions`, `lisk-utils`, `lisk-tree`, and `lisk-validator`.
```

2023-06-01 07:16 UTC, chris529 commented
@ishantiw Many thanks. However, this update is related to the v6.0.0 release. 👍

2023-06-01 07:18 UTC, TalhaMaliktz approved these changes
LGTM

2023-06-01 09:52 UTC, ishantiw approved these changes

2023-06-01 10:16 UTC, merged