Add new endpoint reference page for the Mainchain interoperability module
LiskArchive/lisk-legacy-docs pull request #1790
Opened 2023-05-24 14:08 UTC by Tschakki

Closes #1722

2023-05-31 13:29 UTC, TalhaMaliktz requested changes

2023-05-31 13:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +|number
```suggestion
|string
```

2023-05-31 13:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +.Parameters
The `parameters` seem redundant with `Specification`, I would remove the caption.
```suggestion

```

2023-05-31 13:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +.Parameters
```suggestion

```

2023-05-31 13:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +Returns the minimum fee per byte for CCMs.
Since CCM is Lisk terminology, I would either add a tooltip or a hyperlink to its definition.

2023-05-31 13:29 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +|The chain ID of a sidechain
```suggestion
|The chain ID of a sidechain.
```

2023-05-31 13:39 UTC, ishantiw reviewed
Are somewhere adding base endpoints as well? If not then you need to add below endpoints,
```
getChainAccount
getAllChainAccounts
getChannel
getOwnChainAccount
getTerminatedStateAccount
getTerminatedOutboxAccount
getChainValidators
```

2023-05-31 14:47 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +Returns the minimum fee per byte for CCMs.
tooltips are added to the content automatically, this is currently configured in the ui.

2023-05-31 14:53 UTC, Tschakki commented
@ishantiw this will be added in a separate issue: https://github.com/LiskHQ/lisk-docs/issues/1801

2023-05-31 14:55 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +.Parameters
I leave it as is for consistency with other guides. Also, return value description could also be part of specification, so it is not exactly the same.

2023-05-31 15:00 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +.Parameters
return value?

2023-05-31 15:01 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +Returns the minimum fee per byte for CCMs.
I see, then it could be useful to link CCM to this URL.
https://lisk.com/documentation/beta/understand-blockchain/interoperability/communication.html#inducing-state-changes-across-chains-with-ccms

2023-05-31 15:20 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +.Parameters
yeah, the endpoint response, in other words

2023-05-31 15:22 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +Returns the minimum fee per byte for CCMs.
I didn't test it yet to include urls in the tooltips, and it might not be straight forward... However, I think it goes beyond the scope of the current issue.

2023-05-31 15:25 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +Returns the minimum fee per byte for CCMs.
Oh, I didn't mean to add it in the tooltip. I meant to hyperlink CCM like this as we usually do in docs.
xref:{communication.adoc#inducing-state-changes-across-chains-with-ccms}[CCM].

2023-05-31 15:36 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/mainchain-interoperability-endpoints.adoc
> +Returns the minimum fee per byte for CCMs.
yeah, I doubt that the link will be generated correctly, if it is constructed like this

2023-06-01 07:17 UTC, TalhaMaliktz approved these changes
LGTM

2023-06-01 09:47 UTC, ishantiw approved these changes

2023-06-01 10:12 UTC, merged