Add new endpoint reference page for the validators module
LiskArchive/lisk-legacy-docs pull request #1811
Opened 2023-06-12 13:39 UTC by chris529

Closes #1727

2023-06-23 10:53 UTC, TalhaMaliktz requested changes

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> += Validators module: Endpoint reference
Please update the `nav.adoc` file to include this page.

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +:url_typedoc_auth: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.ValidatorModule.html
```suggestion
:url_typedoc_auth: {site-url}/lisk-sdk/v6/references/typedoc/classes/lisk_framework.ValidatorsModule.html
```

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +== `ValidatorBLSKey`
The names of endpoints should have the namespace as prefix as well.

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +lisk-core endpoint:invoke validateBLSKey '{ "blsKey": "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "ProofOfPossession": "b92b11d66348e197c62d14a
The endpoint name should have the namespace prefix.

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +lisk-core endpoint:invoke getValidator '{"address":"lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday"}' --pretty
Same issue as mentioned earlier about prefix!

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +[cols="1,1,2,2",options="header",stripes="hover"]
I would increase the column width to make more space for the lengthy content.
```suggestion
[cols="1,1,4,4",options="header",stripes="hover"]
```

2023-06-23 10:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +[cols="1,1,2,2",options="header",stripes="hover"]
```suggestion
[cols="1,1,4,4",options="header",stripes="hover"]
```

2023-06-26 08:36 UTC, TalhaMaliktz requested changes
Looking good already!

2023-06-26 08:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  This endpoint is used to retrieve the BLS public key of a specific validator in the network.
I am not sure if this is the correct description of the endpoint as the endpoint suggests whether or not the input passed is valid. Please re-check this description.

2023-06-26 08:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  Returns the `generatorKey` and the `blsKey` of the validator module.
```suggestion
Returns the `generatorKey` and the `blsKey` of a validator from the `validators` module.
```

2023-06-26 09:22 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  This endpoint is used to retrieve the BLS public key of a specific validator in the network.
@ishantiw Could you please confirm this is the correct description of the endpoint?

2023-06-26 13:46 UTC, ishantiw requested changes
Apart from a few minor comments, looks good to me

2023-06-26 13:46 UTC, ishantiw commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  This endpoint is used to retrieve the BLS public key of a specific validator in the network.
You can use the description from LIP https://github.com/LiskHQ/lips/blob/main/proposals/lip-0044.md#validateblskey

2023-06-26 13:46 UTC, ishantiw commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +|Validates and verifies ownership of tokens.
Maybe a better description would be, `Proof that the owner of a key pair actually has the private key associated with the public key`

2023-06-26 13:46 UTC, ishantiw commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +lisk-core endpoint:invoke validators_validateBLSKey '{ "blsKey": "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "ProofOfPossession": "b92b11d66348
```suggestion
lisk-core endpoint:invoke validators_validateBLSKey '{ "blsKey": "83d4f8300dda93e62b375264e8e47bc224cbb8f2ecf4c2e848ac9758d6d8fd263c22ef2d9be18b066b8efcab80d6bdaa", "proofOfPossession": "b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f" }' --pretty
```

2023-06-27 11:29 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +|Validates and verifies ownership of tokens.
Sounds good..now updated accordingly 👍

2023-06-27 11:39 UTC, chris529 commented
@ishantiw Many thanks, as requested I have updated, the heading to 'validateBLSKey'. 
Just wanted to check that for the 'getValidator', should this remain as 'validators_getValidator' in line 87?

2023-06-27 11:40 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  This endpoint is used to retrieve the BLS public key of a specific validator in the network.
Now done 👍

2023-06-27 11:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  This endpoint is used to retrieve the BLS public key of a specific validator in the network.
@chris529  The endpoints should always be named as `namespace_nameOfEndpoint `which in this case will be `validators_validateBLSKey`. This is the pattern we follow throughout docs for documenting APIs. Please undo this change.

I think Ishan's link was regarding the description of the endpoint rather than the name of the endpoint.

2023-06-27 12:06 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
>  This endpoint is used to retrieve the BLS public key of a specific validator in the network.
@TalhaMaliktz OK, yes, I thought the naming convention was the namespace_nameOfEndpoint. Apologies, my misunderstanding 👍

2023-06-27 13:21 UTC, TalhaMaliktz requested changes

2023-06-27 13:21 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +// This endpoint is used to retrieve the BLS public key of a specific validator in the network.
```suggestion
The API checks whether the specified `blsKey` is registered on the chain or not and whether the `proofOfPossession` for the BLS key is valid.
The API will return `false` if the `blsKey` is already registered.
```

2023-06-27 13:21 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/module-rpc-api/validators-endpoints.adoc
> +If there is no BLS key in the store it would return as `false`.
I think this might be the other way around as far as the [lip](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0044.md#validateblskey) is concerned.
``` suggestion
If there is no BLS key in the store it would return as `true`. If the input passed to the API is invalid, or the `blsKey` already exist, the response will be `false`.
```

2023-06-27 13:47 UTC, TalhaMaliktz approved these changes
Thanks! LGTM 👍🏼

2023-06-28 14:20 UTC, ishantiw approved these changes
🎉

2023-06-28 14:30 UTC, merged