Update node config reference
LiskArchive/lisk-legacy-docs pull request #1819
Opened 2023-06-21 13:22 UTC by Tschakki

Closes #1814 

Additionally, this PR includes several changes to the config reference, including restructuring of content and updating to align with latest config schema 

https://github.com/LiskHQ/lisk-sdk/blob/development/commander/src/utils/config.ts
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/schema/application_config_schema.ts

2023-06-29 09:05 UTC, ishantiw approved these changes
LGTM

2023-07-04 08:13 UTC, TalhaMaliktz requested changes

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +:toclevels: 3
```suggestion
:toclevels: 3
:page-toclevels: 3
```

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| [{"startHeight": 1,"snapshotHeight": 123,"snapshotBlockID": "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0"}]
I would turn this into a code snippet to improve aesthetics.

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +The `modules` holds module-specific configuration options of the blockchain client.
```suggestion
The `modules` hold module-specific configuration options for the blockchain client.
```

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +If a node operator changes any of the module-specific configurations, it might cause the node to a fork.
```suggestion
If a node operator changes any of the module-specific configurations, it might cause the node to fork.
```

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +The `plugins` holds plugin-specific configuration options of the blockchain client.
```suggestion
The `plugins` hold plugin-specific configuration options for the blockchain client.
```

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +For example, in Lisk Core v4, it will store the height from Core v3 where it starts from and where it ended.
```suggestion
For example, in Lisk Core v4, it will store the height from Core v3 where it starts from, and where it ended.
```

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +[*] allows all methods, [] none.
```suggestion
`[*]` allows all methods, `[]` none.
```

2023-07-04 08:13 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +		"advertiseAddress": true,
The sample seems incorrect. Shouldn't this have a `legacy` config object?

2023-07-04 08:29 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +The `modules` holds module-specific configuration options of the blockchain client.
```suggestion
`modules` contains the module-specific configuration options of the blockchain client.
```

2023-07-04 08:29 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +The `plugins` holds plugin-specific configuration options of the blockchain client.
```suggestion
`plugins` contains the plugin-specific configuration options for the blockchain client.
```

2023-07-04 12:41 UTC, TalhaMaliktz reviewed
Looking good already!

2023-07-04 12:41 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +`modules` contains the module-specific configuration options for the blockchain client.
```suggestion
`modules` contain module-specific configuration options for the blockchain client.
```

2023-07-04 12:41 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +`plugins` contains the plugin-specific configuration options for the blockchain client.
```suggestion
`plugins` contain plugin-specific configuration options for the blockchain client.
```

2023-07-04 12:41 UTC, TalhaMaliktz commented on modules/ROOT/pages/config.adoc
> +| `[{"startHeight": 1,"snapshotHeight": 123,"snapshotBlockID": "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0"}]`
I would match the snippet style used throughout the page. 
```suggestion
a|
[source,json]
----
[{"startHeight": 1,"snapshotHeight": 123,"snapshotBlockID": "0f4ea1c3cfb61b99d387b26aaadf57936a528e5c713c6e55aa06f4d621b7e6f0"}]
----
```

2023-07-04 13:50 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +`modules` contains the module-specific configuration options for the blockchain client.
Singular sounds here better to me, because it is referring to a specific config property called `modules`

2023-07-04 13:50 UTC, Tschakki commented on modules/ROOT/pages/config.adoc
> +`plugins` contains the plugin-specific configuration options for the blockchain client.
Singular sounds here better to me, because it is referring to a specific config property called `plugins`

2023-07-04 14:01 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-07-04 14:36 UTC, merged