Update connecting endpoints guide
LiskArchive/lisk-legacy-docs pull request #1821
Opened 2023-06-23 11:35 UTC by chris529

Closes #1802

2023-07-11 16:01 UTC, sameersubudhi requested changes

2023-07-11 16:01 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +:url_api_testnet: https://testnet-service.lisk.com/api/v2
```suggestion
:url_api_testnet: https://testnet-service.lisk.com/api/v3
```

2023-07-11 16:01 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +:url_rpc_api_mainnet: wss://service.lisk.com/rpc-v2
```suggestion
:url_rpc_api_mainnet: wss://service.lisk.com/rpc-v3
```

2023-07-11 16:01 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +More detailed information and examples can be found on the xref:{url_rpc_api}[RPC API of Lisk service page].
```suggestion
More detailed information and examples can be found on the xref:{url_rpc_api}[RPC API of Lisk Service page].
```

2023-07-11 16:01 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +There is a public Lisk Service HTTP API for every public Lisk blockchain network, which can be used to query the desired information from the network.
> There is a public Lisk Service HTTP API for every public Lisk blockchain network

This statement may not be factually correct. Most of the sidechains will responsible to deploy their own LS and share the information with us on the [app-registry](https://github.com/LiskHQ/app-registry/). This is highly recommended but not mandatory.

2023-07-11 16:01 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Using the xref:{url_api_http}[HTTP API] offers a RESTful API with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain applications bu
Technically, the blockchain applications need to be compliant with the Lisk protocol.

2023-07-11 16:01 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Axios::
Have shared the scripts offline. Please check.

2023-07-12 09:52 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +There is a public Lisk Service HTTP API for every public Lisk blockchain network, which can be used to query the desired information from the network.
OK, good point. I have slightly reworded this sentence.

2023-07-12 09:55 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Using the xref:{url_api_http}[HTTP API] offers a RESTful API with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain applications bu
Thanks, slightly reworded this accordingly. 👍

2023-07-12 13:20 UTC, sameersubudhi requested changes

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +== Connecting to a node
Should we also highlight (preferably in a NOTE) the fact that for invoking the node APIs over IPC, WS or HTTP, the corresponding APIs should be enabled either in the node config or the command line flag or setting up the environment when starting the blockchain application. Also, please consider adding a link to the documentation on how to enable the corresponding APIs on the node, which, IIRC, already exists.

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Invoking via the node CLI
It's also important to mention a NOTE that for the endpoints to be accessible, `rpc.allowedMethods` needs to specify `["*"]` for all the methods or the module name (`["consensus", "token", "pos"]`) or the exact method names (`["chain_getLastBlock", "system_getNodeInfo"]`) to expose them in the API. Ref: https://github.com/LiskHQ/lisk-core/tree/v4.0.0-beta.3#configuring-lisk-node (please check the NOTE).

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +	'request',
```suggestion
	'request', // channel on which Lisk Service handles the WS-RPC calls
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +		console.log('Request time out - could not get a response.');
```suggestion
		console.log('Request timeout - could not get a response.');
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +const getEndpoint = 'https://service.lisk.com/api/v2/network/status';
```suggestion
const getEndpoint = 'https://service.lisk.com/api/v3/network/status';
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An example of how execute a POST request to validate the BLS key is shown below.
```suggestion
An example of how to execute a POST request to validate a BLS key and Proof of Possession pair is shown below.
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +const postEndpointParams = {
Similar to the cURL notes, perhaps we can do the same for the Axios example too.
```suggestion
----
--
An example of how to execute a POST request to validate a BLS key and Proof of Possession pair is shown below.
--
[source,json]
----
const axios = require('axios');

const postEndpoint = 'https://service.lisk.com/api/v3/validator/validate-bls-key';
const postEndpointParams = {
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Subscribe - Any Event::
Perhaps, both `Subscribe - Specific Event` and the `Subscribe - All Events` can be two different tabs?
```suggestion
Subscribe - All Events::
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +onst io = require('socket.io-client');
```suggestion
const io = require('socket.io-client');
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +cconst io = require('socket.io-client');
```suggestion
const io = require('socket.io-client');
```

2023-07-12 13:20 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Subscribe - Any Event::
Seems like that was the intention all along but there's something wrong with the rendering. Could you please look into it? 🙏

2023-07-12 13:26 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Subscribe - Any Event::
Yes, I had already fixed, so it should be fine now 👍

2023-07-12 13:27 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Subscribe Events
```suggestion
=== Subscribe to Events
```

2023-07-12 13:33 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +== Connecting to a node
Yes, good point. I have added in a note to reflect this. 👍

2023-07-12 13:33 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +		console.log('Payload:', JSON.stringify(data, null, 2), '\n');
```suggestion
	(eventPayload) => {
		console.log(`Event: ${eventName}`);
		console.log('Payload:', JSON.stringify(eventPayload, null, 2), '\n');
```

2023-07-12 13:34 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +		console.log('Payload:', JSON.stringify(data, null, 2), '\n');
```suggestion
	(eventName, eventPayload) => {
		console.log(`Event: ${eventName}`);
		console.log('Payload:', JSON.stringify(eventPayload, null, 2), '\n');
```

2023-07-12 23:36 UTC, sameersubudhi requested changes

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  RPC-based interfaces i.e., IPC, WS, or HTTP allow applications to *invoke* RPC endpoints.
```suggestion
The RPC-based endpoint invocations to the nodes are possible over IPC, WS, or HTTP.
```
or
```suggestion
The RPC-based endpoint invocations to the nodes can be made over IPC, WS, or HTTP.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Invoking via the node CLI
```suggestion
=== Invoking via the CLI
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +To invoke an endpoint via node CLI, simply use the `endpoint:invoke` command as shown in the following code snippet.
```suggestion
To invoke an endpoint via the CLI, simply use the `endpoint:invoke` command as shown in the following code snippet.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +For further details please see the {url_readme}[Configuring Lisk Node] section in the Readme file.
```suggestion
For further details please see the {url_readme}[Configuring Lisk Node] section in the Lisk Core README file.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +For WS, the RPC endpoint name is passed in the method property after establishing a WebSocket connection using {url_socket_io}[socket.io].
```suggestion
For WS, the RPC endpoint name is passed in the `method` property after establishing a WebSocket connection using {url_socket_io}[socket.io].
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +More detailed information and examples can be found on the xref:{url_rpc_api}[RPC API of Lisk Service page].
```suggestion
For detailed information and examples please visit the xref:{url_rpc_api}[RPC API Lisk Service] page.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Using the xref:{url_api_http}[HTTP API] offers a RESTful API with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain applications th
```suggestion
Lisk Service also offers a RESTful xref:{url_api_http}[HTTP API] with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain applications that are compliant with the Lisk protocol.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +There is a public Lisk Service HTTP API, which can be used to query the desired information from the network.
```suggestion
There is a public Lisk Service HTTP API, which can be used to query the desired information from the Lisk Core mainchain network.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +In addition to the WS and IPC method, Lisk endpoints also support HTTP requests and response mechanisms, such as HTTP Axios and cURL.
```suggestion
The Lisk Service HTTP API can be accessed using request libraries such as Axios or a command-line tool such as cURL, as shown below.
```

2023-07-12 23:36 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Further information can be found in the xref:{url_subscribing_to_events}[Subscribing to events] page.
The reference for `Subscribing to events` is incorrect in this context. It should point to https://liskhq.github.io/lisk-docs/beta/api/lisk-service-pubsub.html instead. `url_subscribing_to_events` will need to be replaced with an appropriate variable name.
```suggestion
The Lisk Service Subscribe API allows subscribing to events to receive real-time updates or notifications, as shown in the examples below.
A detailed list of all available emitted events are available in the xref:{url_subscribing_to_events}[Publish/Subscribe API (Lisk Service)] page.
```

2023-07-13 11:31 UTC, sameersubudhi requested changes
Just a couple more minor changes 🙂

2023-07-13 11:31 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +:url_subscribing_to_events: ROOT::api/lisk-service-pubsub.adoc
For relevance, I'd also recommend renaming the variable 🙂 
```suggestion
:url_lisk_service_pubsub: ROOT::api/lisk-service-pubsub.adoc
```

2023-07-13 11:31 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +NOTE: To interact with the node APIs through IPC, WS, or HTTP, it is necessary to enable the corresponding APIs. This can be done by configuring them in the xref:{url_enable_apis}[node settings], usi
```suggestion
NOTE: To interact with the node APIs through IPC, WS, or HTTP, it is necessary to enable the corresponding APIs. This can be done by configuring them in the xref:{url_enable_apis}[node settings], using command line flags, or setting up the relevant environment variables when launching the blockchain application.
```

2023-07-13 11:31 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +For further details please see the {url_readme}[Configuring Lisk Node] section in the Lisk Core README file.
Perhaps we should move this `NOTE` above directly under the `Connecting to a node` header as this information is applicable for all the methods of endpoint invocation (WS/IPC/HTTP).

2023-07-13 11:31 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  ----
On L136, the source needs to be set to `[source,bash]`.

2023-07-13 11:37 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  ----
Yes, indeed..Now done 👍

2023-07-13 11:38 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +For further details please see the {url_readme}[Configuring Lisk Node] section in the Lisk Core README file.
Good point...Now done 👍

2023-07-13 11:40 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +A detailed list of all available emitted events are available in the xref:{url_subscribing_to_events}[Publish/Subscribe API (Lisk Service)] page.
```suggestion
A detailed list of all available emitted events are available in the xref:{url_lisk_service_pubsub}[Publish/Subscribe API (Lisk Service)] page.
```

2023-07-13 13:59 UTC, TalhaMaliktz requested changes

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +
```suggestion
```

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +
```suggestion
```

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +
```suggestion
```

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +For further details please see the {url_readme}[Configuring Lisk Node] section in the Lisk Core README file.
I would convert this into a block NOTE, with each sentence mentioned as a bullet point to enhance visibility and readability.

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  ----
Please convert this into two separate code blocks. The first one should be for the command and the second one should be a collapsable item that has the response in it.

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  NOTE: If you are running *Lisk Core*, you can use mostly the same CLI commands as in the general node CLI.
Please also combine this note in the below-mentioned NOTE block.

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +WS JSON-RPC API::
Since this is just a single tab, please remove the tab from here and make it a simple code snippet block with a caption.

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Subscribe to Events
Since we already have a dedicated page for [subscribing to events](https://lisk.com/documentation/beta/integrate-blockchain/subscribing-to-events.html), Please comment this section for now and create an issue to update the aforementioned page. You can reference this page for additional information.

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +By default, Lisk exposes xref:{url_advanced_rpc_endpoints}[a range of endpoints] to enable communicate with a node or via Lisk Service.
```suggestion
By default, Lisk exposes xref:{url_advanced_rpc_endpoints}[a range of endpoints] to enable communication with a node or via Lisk Service.
```

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  [[the-api-client]]
Please move this to line 58

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
Please also add a link to any module API reference, so that the reader knows where to look for module related apis

2023-07-13 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Muhammad Talha <muhammad.talha@lightcurve.io> Christopher Braithwaite <christopher.braithwaite@lightcurve.io>
Whilst generating a preview, I get the following errors, please resolve them.
![image](https://github.com/LiskHQ/lisk-docs/assets/13951043/8624bf43-0c18-4580-9e91-99574f5f8fc9)

2023-07-13 14:38 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Subscribe to Events
These are two different events we're talking about. The information contained here is for the events (over WS) from the `Subscribe API` that Lisk Service offers. The URL shared above mentions about fetch on-chain (blockchain) events from the node.

2023-07-13 14:38 UTC, sameersubudhi approved these changes
LGTM 👍

2023-07-13 14:52 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Subscribe to Events
The page mentioned will also be tweaked in the same manner this page has been tweaked. We consider this page to be a one-stop shop for whoever wants to invoke an endpoint in the Lisk ecosystem which means that all the practical info regarding invoking endpoints should be here.

The page for subscribing to events has been created with the same thought. It will house all the ways through which events can be subscribed to in the lisk ecosystem. The page should definitely talk about the type of events that are generated through the lisk service. It will also mention how one can subscribe to such an event. This content will move there.

2023-07-14 08:13 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +=== Subscribe to Events
As discussed, there is now an issue created to move the new subscribe to events section into the Subscribing to events page. https://github.com/LiskHQ/lisk-docs/issues/1843

2023-07-14 13:47 UTC, TalhaMaliktz requested changes
Looking good!

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  = Connecting to endpoints
```suggestion
= Connecting via endpoints
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Furthermore, xref:{url_intro_modules}[Modules] and xref:{url_intro_plugins}[Plugins] of a blockchain client can also expose endpoints as described in the guides about xref:{url_endpoints_modules}[imp
The introduction section needs some re adjustment IMHO. Please add the relevant hyperlinks to the bold text after committing. 

```suggestion
On this page, we discuss how endpoints of a Lisk blockchain node and Lisk products i.e., Lisk Service can be invoked.
By default, Lisk exposes xref:{url_advanced_rpc_endpoints}[a range of endpoints] to enable communication with a blockchain node.
On top of that, the Lisk service also provides its own set of **endpoints** that offer even more extensive blockchain data. 

Furthermore, xref:{url_intro_modules}[Modules] and xref:{url_intro_plugins}[Plugins] of a blockchain client can also expose endpoints.
By default, Lisk exposes various module-based endpoints as well, an example of which is the xref:{url_auth_module}[Auth module endpoints], and so on.
It is also possible to develop endpoints for custom modules and plugins.
For more information, see xref:{url_endpoints_modules}[implementing endpoints for a module] and xref:{url_endpoints_plugins}[creating an endpoint for a plugin] guides, respectively.
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +* Alternatively, it can specify the module name, for example, such as `["consensus","token","pos"]`, or the exact method names such as ["chain_getLastBlock", "system_getNodeInfo"] to expose them in t
```suggestion
* Alternatively, it can specify the module name, for example, `["consensus","token","pos"]`, or the exact method names such as ["chain_getLastBlock", "system_getNodeInfo"] to expose them in the API.
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +====
The `NOTE` starting at **lines 56 to 63** should be converted into a sub-section called Preliminaries or Preparing a node, etc. Please also take out the text from the `NOTE` mentioned on **line 75** and make it part of this section. Remove both notes.

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
**LINE 80:**

TIP: To conveniently communicate with a blockchain node, use the `*apiClient*` included in the `*@liskhq/lisk-client*` and the `*lisk-sdk*` packages.

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  Just replace `./bin/run` with `lisk-core` in that case.
```suggestion
Just replace `*./bin/run*` with `*lisk-core*` in that case.
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
```suggestion

.Invoking an endpoint via CLI
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +The API base URL is the base URL for the Lisk Service WS-RPC endpoints, that are available to query under the `/rpc-v3` namespace.
```suggestion
Lisk Service WS-RPC endpoints are available to query under the `/rpc-v3` namespace. 
The base URL of Lisk Service for WS-RPC is:
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An example using the WS JSON-RPC API can be seen below.
```suggestion
An example of using the WS JSON-RPC API can be seen below.
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +.WS JSON-RPC API
```suggestion
.Querying network status via WS JSON-RPC API
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +
```suggestion

// Establishing socket.io connection
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +
```suggestion

// Invoke "get.network.status" endpoint
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +For detailed information and examples please visit the xref:{url_rpc_api}[RPC API Lisk Service] page.
```suggestion
For detailed information and examples, please visit the xref:{url_rpc_api}[RPC API Lisk Service] page.
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +Lisk Service also offers a RESTful xref:{url_api_http}[HTTP API] with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain application
```suggestion
Lisk Service also offers the RESTful xref:{url_api_http}[HTTP API] with various additional endpoints, that for example, could be deployed to build user interfaces and wallets for blockchain applications that are compliant with the Lisk protocol.
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +The Lisk Service HTTP API can be accessed using request libraries such as Axios or a command-line tool such as cURL, as shown below.
Please add a hyperlink to Axios. You can use this URL: https://axios-http.com/docs/intro

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +[source,js]
```suggestion
An example of how to execute a `GET` request via `axios` in order to retrieve the network status is shown below:
[source,js]
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An example of how to execute a POST request to validate a BLS key and Proof of Possession pair is shown below.
```suggestion
An example of how to execute a `POST` request via `axios` to validate a BLS key and Proof of Possession pair is shown below:
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +// With a {JSON_RPC_Specs}[JSON RPC 2.0] based format, any endpoint can be invoked using a cURL request.
```suggestion
An example of how to execute a `GET` request via `curl` in order to retrieve the network status is shown below:
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +An example of how to execute a POST request to validate a BLS key and Proof of Possession pair is shown below.
```suggestion
An example of how to execute a `POST` request via `curl` to validate a BLS key and Proof of Possession pair is shown below:
```

2023-07-14 13:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +:url_readme: https://github.com/LiskHQ/lisk-core/tree/v4.0.0-beta.3#configuring-lisk-node
Since the page now has info about connecting via endpoints to the Lisk service. Please make a minor update in the `api/lisk-service-rpc.adoc` file.

Update line 7 to this:
`integrate-blockchain/connecting-endpoints.adoc#connecting-to-lisk-service`

2023-07-17 11:28 UTC, TalhaMaliktz approved these changes
Thank you! Just a few minor remarks. The rest LGTM 👍🏼

2023-07-17 11:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +The Lisk Service HTTP API can be accessed using request libraries such as xref:{url_axios}[Axios] or a command-line tool such as cURL, as shown below.
```suggestion
The Lisk Service HTTP API can be accessed using request libraries such as {url_axios}[Axios] or a command-line tool such as cURL, as shown below.
```

2023-07-17 11:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
>  * In order to make the endpoints accessible, the configuration setting `rpc.allowedMethods` must either specify `["*"]` to allow all methods.
```suggestion
* In order to make the endpoints accessible, the configuration setting: `rpc.allowedMethods` should specify `["*"]` to allow all methods.
```

2023-07-17 11:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +* To interact with the node APIs through IPC, WS, or HTTP, it is necessary to enable the corresponding APIs. This can be done by configuring them in the xref:{url_enable_apis}[node settings], using c
```suggestion
* To interact with the node APIs through IPC, WS, or HTTP, it is necessary to enable the corresponding APIs. This can be done by configuring them in the xref:{url_enable_apis}[node settings], using command line flags, or setting up the relevant environment variables when launching the Lisk application.
```

2023-07-17 11:28 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/connecting-endpoints.adoc
> +TIP: To conveniently communicate with a blockchain node, use the *apiClient* included in the *@liskhq/lisk-client* and the *lisk-sdk* packages.
```suggestion
TIP: To conveniently communicate with a blockchain node, use the `*apiClient*` included in the `*@liskhq/lisk-client*` and the `*lisk-sdk*` packages.
```

2023-07-17 11:51 UTC, merged