Connect node with with lisk service - Closes 1522
LiskArchive/lisk-legacy-docs pull request #1823
Opened 2023-06-27 13:28 UTC by TalhaMaliktz

Closes #1522

2023-06-27 14:05 UTC, sameersubudhi requested changes

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +In this guide, you'll learn to connect a blockchain node with Lisk Service.
```suggestion
In this guide, you'll learn to connect Lisk Service to a blockchain node.
```

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +* To connect with Lisk Service, make sure that you have set up a blockchain node e.g. Lisk Core node. See any of our setup guides, such as the xref:{url_npm_core_setup}[].
Also, please add another point to highlight the fact that it is important to set `system.keepEventsForHeight: -1` in the node config.

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Once the node starts, follow the steps mentioned in the xref:{url_connect_node}[Connecting Lisk Service to a blockchain node] section to connect Lisk service with a node.
```suggestion
Once the node starts, follow the steps mentioned in the xref:{url_connect_node}[Connecting Lisk Service to a blockchain node] section to connect Lisk Service with a node.
```

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Run the docker container for `lisk-service`, `redis`, and `mysql` or `mariadb`.
```suggestion
Run the docker container for `lisk-service`, `redis`, and `mysql` or `mariadb`. It is recommended to use `mariadb` instead of `mysql` when running on Darwin.
```

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +After both the blockchain client and the Lisk service are running, you'll see a similar message to the following on your node CLI.
```suggestion
After both the blockchain client and the Lisk Service are running, you'll see a similar message to the following on your node CLI.
```

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Another hint that your node is now connected to Lisk service is that a series of API calls will be made from the `indexer` service of Lisk service to index all the blocks from your node. This will al
```suggestion
Another hint that your node is now connected to Lisk Service is that a series of API calls will be made from the `indexer` service of Lisk Service to index all the blocks from your node. This will also enable Lisk Service to serve end-user requests.
```

2023-06-27 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Another hint that your node is now connected to Lisk service is that a series of API calls will be made from the `indexer` service of Lisk service to index all the blocks from your node. This will al
I'd rather recommend you to highlight the following log from the `blockchain-connector` service to verify that Lisk Service has successfully connected to the node.

```
2023-06-26T16:09:28.435 INFO [app] Found a node, starting service LISK-SERVICE-BLOCKCHAIN-CONNECTOR...
```

or 

```
2023-06-26T15:14:21.758 INFO [$NODE] Service '$node' stopped.
2023-06-26T15:14:21.758 INFO [CONNECTOR] Service 'connector' stopped.
2023-06-26T15:14:21.759 INFO [REGISTRY] Node '5ab791a48515-1' disconnected.
2023-06-26T15:14:21.760 INFO [BROKER] ServiceBroker is stopped. Good bye.
2023-06-26T16:09:28.371 INFO [BROKER] Moleculer v0.14.29 is starting...
2023-06-26T16:09:28.372 INFO [BROKER] Namespace: <not defined>
2023-06-26T16:09:28.372 INFO [BROKER] Node ID: 30e17793ffb7-1
2023-06-26T16:09:28.373 INFO [REGISTRY] Strategy: RoundRobinStrategy
2023-06-26T16:09:28.373 INFO [REGISTRY] Discoverer: LocalDiscoverer
2023-06-26T16:09:28.373 INFO [BROKER] Serializer: JSONSerializer
2023-06-26T16:09:28.374 INFO [BROKER] Validator: FastestValidator
2023-06-26T16:09:28.375 INFO [BROKER] Registered 13 middleware(s).
2023-06-26T16:09:28.376 INFO [TRANSPORTER] NATS lib version:,1.4.12
2023-06-26T16:09:28.376 INFO [BROKER] Transporter: NatsTransporter
2023-06-26T16:09:28.392 INFO [sqlite3] Creating schema for blocks
2023-06-26T16:09:28.396 INFO [sqlite3] Creating schema for transactions
2023-06-26T16:09:28.435 INFO [app] Found a node, starting service LISK-SERVICE-BLOCKCHAIN-CONNECTOR...
```

2023-06-27 14:07 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Lisk Service is installed in addition to a Lisk blockchain application such as Lisk Core or a sidechain client, to provide enriched network data for third-party services.
It'd be nice to hyperlink `sidechain` to it's definition/relevant glossary if it already exists in the docs.

2023-06-30 14:22 UTC, Tschakki requested changes

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +*** xref:integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc[]
The page title and path should be different

```suggestion
** xref:integrate-blockchain/aggregate-blockchain-data/index.adoc[]
```

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> += Connecting Lisk Service to a blockchain node
```suggestion
= Aggregate blockchain data with Lisk Service
```

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Lisk Service is a web application middleware that allows interaction with various blockchain networks based on the Lisk protocol.
`Lisk Service` should be a link to lisk service docs.

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +If you are starting from scratch, take a look at our xref:{url_blockchain_client}[How to create a new blockchain client] guide.
```suggestion
```

not necessary to mention here.

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +* Please make sure to set `system.keepEventsForHeights: -1` in the node config before synchronizing the node with the network.
Why is this important? Please explain it to the reader.

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Lisk Service is installed in addition to a Lisk blockchain application such as Lisk Core or a sidechain client, to provide enriched network data for third-party services.
```suggestion
```

Would remove here, as it is not fitting the context.
Could be moved to line 19 instead.

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Use the client CLI to start the node with the desired configurations.
Imho we should not recommend to use node CLI here.
They should probably use pm2 or something else, to start the node in the background.

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +You can also invoke an endpoint of the blockchain node via Lisk service API like this:
```suggestion
You can also invoke an endpoint of the blockchain node via Lisk service API like this, to verify that the connection was established successfully:
```

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +----
Maybe it would be nice to write some closing remarks and to guide the user to other useful resources like the API reference.

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +It is necessary to set up a blockchain node first, before setting up Lisk Service.
```suggestion
1. It is required to set up a blockchain node.
```

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +* Lisk Service must be set up via either the recommended xref:{url_service_docker_setup}[] or the xref:{url_service_source_setup}[] guide.
```suggestion
2. It is required to set up Lisk Service.

* Lisk Service must be installed. 
Please refer to the dedicated setup guides for xref:{url_service_docker_setup}[] and xref:{url_service_source_setup}[].
```

2023-06-30 14:22 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +* To connect with Lisk Service, make sure that you have set up a blockchain node e.g. Lisk Core node. See any of our setup guides, such as the xref:{url_npm_core_setup}[].
```suggestion
* Make sure that you have set up a blockchain node e.g. Lisk Core node.
Please refer to the dedicated setup guides, such as the xref:{url_npm_core_setup}[].
```

2023-07-04 12:21 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> += Connecting Lisk Service to a blockchain node
Thanks for the suggestion. However, IMHO, the term "aggregate" is rather specific and is suitable for content that describes a specific concept like data aggregation. It does not suit the contents of the page which focuses on connecting a node with Lisk Service. I also think that "Utilizing Lisk Service" is a broader term that can encapsulate a range of concepts related to Lisk Service in it.
There can be another guide that talks about this topic of data aggregation and this particular docs section can look like this, with that guide:

- Utilizing Lisk Service
    - Connecting Lisk Service to a blockchain node
    - Aggregate blockchain data with Lisk Service

2023-07-04 12:22 UTC, TalhaMaliktz commented on docs/modules/ROOT/nav.adoc
> +*** xref:integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc[]
Thanks, I have shared my thoughts on this in the following comment.

2023-07-04 12:42 UTC, sameersubudhi requested changes

2023-07-04 12:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +* Please make sure to set `system.keepEventsForHeights: -1` in the node config{fn_node_config} before synchronizing the node with the network.
Since this is a node config change, it must go under the node setup instructions.
```suggestion
* Alternatively, you can setup up a xref:{url_sidechain}[sidechain] node to connect with Lisk Service.
* Please make sure to set `system.keepEventsForHeights: -1` in the node config{fn_node_config} before synchronizing the node with the network.

2. It is required to set up Lisk Service.

* Lisk Service must be set up via either the recommended xref:{url_service_docker_setup}[] or the xref:{url_service_source_setup}[] guide.
```

2023-07-04 12:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +      "script": "./bin/run start --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
Can we also please mention that the script assumes that the application has been build with `npm run build` and the pm2.conf.json assumes that it lies within the application's parent directory.

```suggestion
      "name": "hello_client",
      "script": "./bin/run start --api-ws -n default --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
```
or
```suggestion
      "name": "hello_client",
      "script": "./bin/run start --api-ws -n mainnet --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
```

2023-07-04 12:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Another hint that your node is now connected to Lisk Service in the logs of the  is that a series of API calls will be made from the `blockchain-connector` service.
```suggestion
Another hint that Lisk Service is now connected to your node is the occurrence of the following entry in the logs from the `blockchain-connector` service.
```

2023-07-04 12:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +After both the blockchain client and the Lisk Service are running, you'll see a similar message to the following on your node CLI.
Just so that we're consistent, should we use `Lisk application client` instead of `blockchain client` throughout. @Tschakki what are your thoughts on this?

```suggestion
After both the blockchain client and the Lisk Service are running and connected, you should see a similar entry in the logs of the Lisk application node.
```

2023-07-04 12:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +After both the blockchain client and the Lisk Service are running, you'll see a similar message to the following on your node CLI.
The aligned term is `blockchain client`

2023-07-04 12:50 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +      "script": "./bin/run start --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
What do these flags mean?  `-n mainnet` & `-n default`

2023-07-04 12:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +      "script": "./bin/run start --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
The `-n, --network` flag signifies the network the client connects to (configs are present under the `./config/{default,mainnet,testnet,devnet,...}`) directories

2023-07-04 12:58 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +After both the blockchain client and the Lisk Service are running, you'll see a similar message to the following on your node CLI.
However, the above statement needs restructuring. Please adjust it accordingly.

2023-07-04 13:00 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +      "script": "./bin/run start --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
Is the `-n, --network` flag specific to Lisk-core, or does it also apply to a sidechain node?

2023-07-04 13:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +After both the blockchain client and the Lisk Service are running, you'll see a similar message to the following on your node CLI.
```suggestion
After both the blockchain client and the Lisk Service are running and connected, you should see a similar entry in the logs of the blockchain node.
```

2023-07-04 13:04 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +      "script": "./bin/run start --api-ws --api-ws-host=0.0.0.0 --api-ws-port=7887 --api-http"
`-n, --network` flag is applicable to all the blockchain applications bootstrapped with the Lisk Commander. The values however map to the sub-directory names under the `./config` directory holding the default/custom network/node configs. A freshly bootstrapped application will only have the `default` network config. Users need to create other network configs, if they've the need to.

2023-07-04 13:06 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +:fn_node_config: footnote:config[Events are necessary to determine the transaction execution status and the actual block generation rewards. Without this information, Lisk Service wouldn’t be able in
```suggestion
:fn_node_config: footnote:config[Events are necessary to determine the transaction execution status and the actual block generation rewards. Without this information, Lisk Service wouldn’t be able index the all the transactions. Thus, the indexing will be incomplete. Setting "system.keepEventsForHeights: -1" will ensure that the events are not deleted and are maintained on the node for all the block heights. By default, the node only maintains the events for the last 300 blocks.]
```

2023-07-04 13:20 UTC, sameersubudhi approved these changes
LGTM 👍

2023-07-04 14:28 UTC, Tschakki requested changes

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +== Configuring a node
```suggestion
== Enable API on the blockchain node
```

more precise heading

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Sidechain node::
Maybe it's better here to have the lisk core example in the first tab which is open by default.

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +Run the docker container for `lisk-service`, `redis`, and `mysql` or `mariadb`. It is recommended to use `mariadb` instead of `mysql` when running on Darwin.
What if Service was installed from Source?

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +[tabs]
Are these alternative ways to start lisk service, or does a user need to run them after each other? In case of the latter, please rempve the tabs and explain it step by step.

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +For more information about Lisk Service APIs, see xref:{rpc_api}[] or xref:{http_api}[] reference pages.
Please explain a little more detailed what users can now do after connecting Lisk Service to a node and provide links to all other Lisk Service related resources that might be interesting for the reader.

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +*** xref:integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc[]
I cannot find the comment here anymore, so I answer here: "Aggregate blockchain data with Lisk Service" was chosen as a title, because it is explaining *why* a user needs Lisk Service, and what is its purpose in the first place.
For example, you could also imagine the title to just be "How to aggregate blockchain data for your frontend" or something like this, which will be easier for people to understand what this page is about, even if they are not familiar with Lisks products, yet.

For example, the guide "Creating a blockchain client" Could also be called "Utilizing the SDK" or so, but it would be much less descriptive for outsiders.

2023-07-04 14:28 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +In this guide, you'll learn to connect Lisk Service to a blockchain node.
Please explain to the reader what could be the reasons why we want to connect Lisk Service to a Service node.

Also give a short general introduction to Lisk Service, as this can be considered to be a landing page for people who want to get started with Lisk Service.

2023-07-05 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +[tabs]
These are alternative ways.

2023-07-06 07:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/utilizing-lisk-service/connecting-lisk-service.adoc
> +For more information about Lisk Service APIs, see xref:{rpc_api}[] or xref:{http_api}[] reference pages.
As discussed, I have added a few links to this page and have also created a new issue: [#1836](https://github.com/LiskHQ/lisk-docs/issues/1836) for the rest of the links.

2023-07-06 10:26 UTC, Tschakki approved these changes
Thank you!

2023-07-06 12:38 UTC, merged