Service API migration reference
LiskArchive/lisk-legacy-docs pull request #1831
Opened 2023-06-29 13:10 UTC by Tschakki

Closes #1825

2023-07-04 07:57 UTC, sameersubudhi requested changes
Please consider the following. I've also updated the reference document accordingly.

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +This means there is currently no direct way to fetch incoming transactions for a given address.
```suggestion
|`senderPublickey`, `senderUsername`, `recipientUsername` and `recipientPublickey` request query params removed.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to calculate the fees for a signed/unsigned transaction.
```suggestion
|New endpoint to estimate the transaction fees for a signed/unsigned transaction.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|Returns all the available schemas for the Lisk application including blocks, header, transactions, event, all event data and all command params etc.
```suggestion
|Returns all the available schemas for the Lisk protocol compliant blockchain application including blocks, header, transactions, event, all event data and all command params etc.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to query events, introduced with SDK v6.
```suggestion
|New endpoint to query the block events, introduced with SDK v6.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to calculate the fees for a signed/unsigned transaction.
```suggestion
|
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to fetch the list of rewards currently locked by the PoS module.
```suggestion
|New endpoint to fetch the list of block generation rewards currently locked by the PoS module for the specified validator.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to fetch the claimable rewards currently locked by the PoS module.
```suggestion
|New endpoint to fetch the claimable rewards currently locked by the PoS module for the specified staker.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +* RPC: `get.tokens`
```suggestion
a|* HTTP: `GET /token/balances`
* RPC: `get.token.balances`
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +* RPC: `get.tokens.summary`
```suggestion
a|* HTTP: `GET /token/summary`
* RPC: `get.token.summary`
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +Sidechains proxy through the mainnet deployment.
```suggestion
Sidechains proxy through the mainchain deployment.
```

2023-07-04 07:57 UTC, sameersubudhi commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|Responds with the requested `endpoint` response, deserialized by schema while maintaining the original structure.
```suggestion
|Responds with the requested `endpoint` response, deserialized by schema while maintaining the original response structure.
```

2023-07-04 08:22 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|Returns all the available schemas for the Lisk application including blocks, header, transactions, event, all event data and all command params etc.
Lisk application is a new aligned terminology for blockchain apps following Lisk protocol, so i wouldn't change that.

2023-07-04 08:24 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to query events, introduced with SDK v6.
```suggestion
|New endpoint to query blockchain events, introduced with SDK v6.
```

We call it blockchain events in docs: https://lisk.com/documentation/beta/understand-blockchain/sdk/rpc.html#blockchain-events

2023-07-04 08:27 UTC, sameersubudhi approved these changes
Looks good 👍

2023-07-05 13:05 UTC, TalhaMaliktz requested changes

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +TIP: To see an overview about the available *events in Lisk Service API v3*, please check out the xref:{url_api_service_pubsub}[] reference.
```suggestion
TIP: To see an overview of the available *events in Lisk Service API v3*, please check out the xref:{url_api_service_pubsub}[] reference.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +Split into module specific endpoints.
```suggestion
Split into module-specific endpoints.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +Following are some of the endpoints that can be used to reconstruct the account related information:
```suggestion
Following are some of the endpoints that can be used to reconstruct the account-related information:
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|`senderPublickey`, `senderUsername`, `recipientUsername` and `recipientPublickey` request query params removed.
```suggestion
|`senderPublickey`, `senderUsername`, `recipientUsername`, and `recipientPublickey` request query params removed.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|Returns all the available schemas for the Lisk application including blocks, header, transactions, event, all event data and all command params etc.
```suggestion
|Returns all the available schemas for the Lisk application including blocks, header, transactions, event, all event data, and all command params, etc.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to fetch all the token summary which includes `totalSupply`, `escrowedAmount` and supported tokens information of the Lisk application.
```suggestion
|New endpoint to fetch all the token summary which includes `totalSupply`, `escrowedAmount`, and supported tokens information of the Lisk application.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to fetch the expected reward value at the specified height as per the node config. Actual reward might vary and can be determined from the `rewardMinted` event corresponding to the bloc
```suggestion
|New endpoint to fetch the expected reward value at the specified height as per the node config. 
The actual reward might vary and can be determined from the `rewardMinted` event corresponding to the block height.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/nav.adoc
> +** xref:api/lisk-service-api-migration.adoc[]
I would move these four into a section called Lisk Service APIs like this:
```suggestion
** Lisk Service APIs
*** xref:api/lisk-service/lisk-service-rpc.adoc[]
*** xref:api/lisk-service/lisk-service-http.adoc[]
*** xref:api/lisk-service/lisk-service-pubsub.adoc[]
*** xref:api/lisk-service/lisk-service-api-migration.adoc[]
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|
Missing an X?
```suggestion
^|*X*
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|
The comment is missing.

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|X
I would centrally align all the "X" and would make them bold to ensure visibility throughout the table.
```suggestion
^|*X*
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.peers.connected`
```suggestion
* RPC: `get.peers.connected`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.network.statistics`
```suggestion
* RPC: `get.network.statistics`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.network.statistics`
```suggestion
* RPC: `get.network.statistics`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.network.status`
```suggestion
* RPC: `get.network.status`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.fees`
```suggestion
* RPC: `get.fees`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.market.prices`
```suggestion
* RPC: `get.market.prices`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +RPC: `get.market.prices`
```suggestion
* RPC: `get.market.prices`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +
Since this is a very big table, I think it needs some sort of content separation. For each set of endpoints, we can add a span row that includes the `namespace` of the collection of APIs like this:
```suggestion

3+|*Blocks*
```
The names of each set of APIs are already available [here](https://liskhq.github.io/lisk-docs/beta/api/lisk-service-rpc.html#blocks) or [here](https://liskhq.github.io/lisk-docs/beta/api/lisk-service-rpc.html#transactions) and so on.

Another solution to this problem can be the separation of namespace-related endpoints into their own table.

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +Some of this information was priorly available from the `/v2/network/status` endpoint.
```suggestion
Some of this information was priorly available through the `/v2/network/status` endpoint.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +* RPC `get.pos.constants`
```suggestion
* RPC: `get.pos.constants`
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|New endpoint to calculate the fees for a signed/unsigned transaction.
```suggestion
|New endpoint that returns a list of stakes sent by the specified user by their `address`, `publicKey`, or validator `name`.
```

2023-07-05 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +Some of this information was priorly available from the `/v2/network/status` endpoint.
```suggestion
Some of this information was priorly available through the `/v2/network/status` endpoint.
```

2023-07-06 13:06 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +
Good suggestion, i updated the table and sorted endpoints alphabetically.

2023-07-07 07:31 UTC, TalhaMaliktz reviewed
Looking good already!

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|
```suggestion
^|*X*
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|
```suggestion
|The endpoint has now been moved under the `network` namespace.
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +^|*X*
```suggestion
| Changed the name of the endpoint.
Retrieves the list of stakers (received stakes) for the specified validator.
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +a|* HTTP: `POST /validator`
```suggestion
a|* HTTP: `GET /validator`
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +* RPC:  X
```suggestion
* RPC:  *X*
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +* RPC:  X
```suggestion
* RPC:  *X*
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +* RPC: `/blockchain/apps/meta/tokens`
```suggestion
* RPC: `get.blockchain.apps.meta.tokens`
```

2023-07-07 07:31 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-service-api-migration.adoc
> +|Now takes a *mandatory* query param `interval` and returns response in the same format.
```suggestion
|Now takes a *mandatory* query param `interval` and returns a response in the same format.
```

2023-07-07 08:27 UTC, TalhaMaliktz approved these changes
Thank you! LGTM 🎉

2023-07-25 13:26 UTC, merged