Move hex address computation under lisk32 computation
LiskArchive/lisk-legacy-docs pull request #1832
Opened 2023-06-29 13:10 UTC by Tschakki

Closes #1816

2023-06-29 16:44 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
>  Lower-case letters and digits are used, and to improve usability the characters i, l, 1 and 0 have been excluded.
```suggestion
Lower-case letters and digits are used, and to improve usability the characters i, l, 1, and 0 have been excluded.
```

2023-06-29 16:44 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +===== Obtain Lisk32 address from hex address
```suggestion
===== Obtain the Lisk32 address from the hex address
```

2023-06-29 16:52 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
>  Lower-case letters and digits are used, and to improve usability the characters i, l, 1 and 0 have been excluded.
In American English it should really be "Lowercase" without the hyphen.

2023-06-29 16:54 UTC, chris529 approved these changes
LGTM! 👍  Looks great, I have just left some minor suggestions.

2023-07-03 09:53 UTC, sergeyshemyakov requested changes
Some comments from my side.

2023-07-03 09:53 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +The *Lisk32 representation* displays addresses as a checksum with the "lsk" prefix to prevent accidental typing mistakes.
A checksum is only the last 6 letters of the address, so it is a bit incorrect to say that Lisk32 displays addresses as a checksum. I would say: "... displays addresses as a readable string with a checksum and the "lsk" prefix..."

2023-07-03 09:53 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +NOTE: A BCH checksum is used to check for {url_github_lip_18}[detection of small errors^] in the address.
I would remove "to check" from this sentence.

2023-07-03 09:53 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
In the line above, replace "SHA-236" with "SHA-256".

2023-07-03 09:53 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +===== Obtain the Lisk32 address from the hex address
I would suggest you continue the example from the LIP (at least put the final Lisk32 representation of the address `lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu`).

2023-07-03 09:53 UTC, sergeyshemyakov commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +:url_github_lip_18: https://github.com/LiskHQ/lips/blob/master/proposals/lip-0018.md
These links go to the `master` branch, which does not exist in LIPs repo. Change to `main`.

2023-07-03 10:38 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +===== Obtain the Lisk32 address from the hex address
I removed now explanations now, and added a direct link to the explanations in the LIP

2023-07-03 11:31 UTC, sergeyshemyakov approved these changes

2023-07-03 11:44 UTC, merged