Add page for token endpoint reference
LiskArchive/lisk-legacy-docs pull request #1833
Opened 2023-07-04 13:47 UTC by Tschakki

Closes #1726

2023-07-10 07:01 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/token-endpoints.adoc
> +Checks, if a specific token is supported by the network.
```suggestion
Checks if a specific token is supported by the network.
```

2023-07-10 10:02 UTC, chris529 requested changes
Looks great! Just a few very minor points 👍

2023-07-10 10:02 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/token-endpoints.adoc
> +Return the fees for initializing new user and escrow accounts.
```suggestion
Returns the fees for initializing new user and escrow accounts.
```

2023-07-10 10:02 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/token-endpoints.adoc
> +Checks, if an account exists for the provided address and token in the network.
```suggestion
Checks if an account exists for the provided address and token in the network.
```

2023-07-10 10:02 UTC, chris529 commented on docs/modules/ROOT/pages/api/module-rpc-api/token-endpoints.adoc
> +Checks, if an escrow account exists for the provided chain ID and token in the network.
```suggestion
Checks if an escrow account exists for the provided chain ID and token in the network.
```

2023-07-10 13:53 UTC, chris529 approved these changes
LGTM! 👍

2023-07-11 19:31 UTC, bobanm approved these changes

2023-07-12 08:23 UTC, merged