Document endpoints for the PoS module - Closes 1723
LiskArchive/lisk-legacy-docs pull request #1840
Opened 2023-07-11 14:47 UTC by TalhaMaliktz

Closes #1723

2023-07-12 11:56 UTC, Tschakki requested changes
Looking good already 👍

2023-07-12 11:56 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/pos-endpoints.adoc
> +Returns the constants used by the PoS module.
```suggestion
Returns the configuration of the PoS module.
```

The constants in the response are set in the node config

2023-07-12 11:56 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/pos-endpoints.adoc
> +  "pendingUnlocks": []
If possible, replace this with a non-empty response

2023-07-12 11:56 UTC, Tschakki commented on docs/modules/ROOT/pages/api/module-rpc-api/pos-endpoints.adoc
> +  "rewards": []
If possible, replace this with a non-empty response

2023-07-13 09:31 UTC, Tschakki approved these changes
Thank you!

2023-07-18 09:05 UTC, mosmartin approved these changes

2023-07-18 10:19 UTC, merged