Describe how to import old hash onion in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1841
Opened 2023-07-12 15:22 UTC by chris529

Closes #1798

2023-07-19 07:12 UTC, TalhaMaliktz requested changes

2023-07-19 07:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
Line 429
```
In that case, retrieve the hash onions from the node as described below and store them safely somewhere.
Later on, these values can be used to Import hash onions to a newer node.

```

2023-07-19 07:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +TIP: If you are trying to import your hash onion, or you are trying to enable your block generation on an newer node, it is recommended to copy the above values and store them somewhere securely.
I think we should add this information above, as I have mentioned in my earlier comment. We should remove this line
```suggestion
```

2023-07-19 07:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
>  . Stop the old node.
Since we have mentioned this earlier as well. I think this is redundant. Would re-adjust the text like this:

```suggestion
. After securely storing the hash onion of the old node, stop the old node.
```

2023-07-19 07:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
>  --
Line 387:
```
IMPORTANT: If you're trying to migrate to a new/different node, it is essential that the hash onions used in the setting process belong to the former node.
Use the previously stored hash onion to successfully migrate information from the former node to a newer node.
```

2023-07-19 07:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +Hence, the height of your node should be equal to the current network height.
```suggestion
. Ensure the node is fully synchronized with the network.
Synchronization ensures that the new node is up-to-date and has the latest blocks and transactions from the network.
After sync, the height of the newer node should be equal to the current network height.
```

2023-07-19 07:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enable-block-generation.adoc
> +
This is redundant as we already directed the user to import the hash onions in the preceding point. Having this point here will mean that the user has to redo the process again. I have added a comment above to add more information in the setting hash onion section.
```suggestion
```

2023-07-19 13:17 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
>  --
Yes, good point, thanks.. I have slightly reworded it 👍

2023-07-19 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +Later on, these values can be used to Import hash onions to a newer node.
```suggestion
Later on, these values can be used to import hash onions to a newer node.
```

2023-07-19 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
>  To get the hash onion seed of a validator, request the `random_getHashOnionSeeds` endpoint.
```suggestion
To get the hash onion seed, request the `random_getHashOnionSeeds` endpoint.
```

2023-07-19 13:59 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +Use the previously stored hash onion to successfully migrate information from the previous node to a newer node.
```suggestion
IMPORTANT: When attempting to migrate to a new or a different node, it is crucial that the hash onions from the previous node are used.
Use the previously stored hash onion seed values such as the `address`, `seed`, `count`, and `distance` to successfully migrate information from the previous node to a newer node.
```

2023-07-19 14:07 UTC, TalhaMaliktz approved these changes
Thank you! LGTM 👍🏼

2023-07-21 06:25 UTC, TalhaMaliktz approved these changes

2023-07-21 08:17 UTC, ishantiw approved these changes

2023-07-21 08:39 UTC, merged