Move subscribe events section from connecting-endpoints page to subscribing-to-events-page in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1849
Opened 2023-07-28 07:24 UTC by chris529

2023-08-01 14:05 UTC, sameersubudhi requested changes
Please consider the following. Also, I'm currently checking with the SDK team on the correct terminologies for `WS events` and `Blockchain events`. So, we might have to update them accordingly.

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  The Lisk blockchain generates various events that emit on-chain data.
Can we please add a footnote indicating how we define `Lisk blockchain`? Or, hyperlink it to the glossary (if it exists)?
- It's any application that adheres to the Lisk protocol.
- Includes the Lisk (Core) mainchain and sidechain applications built with Lisk SDK.

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +Lisk makes *WS events* accessible to everyone
```suggestion
Lisk makes *WS events* accessible to everyone.
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +To store the blockchain events on a node permanently, set `*keepEventsForHeights*` to `0` in the node configuration.
```suggestion
To store the blockchain events on a node permanently, set `*keepEventsForHeights*` to `-1` in the node configuration.
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +=== Subscribing to an WS event
```suggestion
=== Subscribing to a WS event
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  [[the-api-client]]
Should this be updated to be relevant to `Subscribing to a WS event` instead?

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +// Subscribe-Specific event code snippet to be updated.
The entire thing can be replaced with the following script:

```node
const io = require('socket.io-client');

const subscriptionEndpoint = 'wss://service.lisk.com/blockchain';

const socket = io(
 	subscriptionEndpoint,
 	{
 		forceNew: true,
 		transports: ['websocket'],
 	},
 );

const { onevent } = socket;
socket.onevent = function (packet) {
    const args = packet.data || [];
    onevent.call(this, packet);
    packet.data = ['*'].concat(args);
    onevent.call(this, packet);
};

const subscribe = subscribeEvent => {
	socket.on(
		subscribeEvent,
		(...args) => {
			let eventName;
			let eventPayload;

			if (subscribeEvent === '*') {
				[eventName, eventPayload] = args;
			} else {
				eventName = subscribeEvent;
				[eventPayload] = args;
			}

			console.log(`Event: ${eventName}`);
			console.log('Payload:', JSON.stringify(eventPayload, null, 2), '\n');
		},
	);
};

/* Subscribe to all the events */
subscribe('*');

/* Subscribe to specific events */
// subscribe('new.block');
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +The API client simplifies the WS event subscription process not only for a blockchain client but also for external plugins and services.
```suggestion
The API client simplifies the WS event subscription process not only for a blockchain client but also for the external plugins and services.
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +With the API client, RPC-based interfaces i.e., IPC and WS can be used to subscribe to *WS events*.
```suggestion
With the Lisk API client, it is possible to subscribe to the *WS events* both over IPC and WS.
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  The block is defined by the block height which is provided as a parameter in the request.
```suggestion
Instead, *blockchain events are requested for a particular block height* and is provided as a parameter in the request.
```

2023-08-01 14:05 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +WS events offered by Lisk can be subscribed to directly by any plugin, external service, or application.
Can we also specify that there can only be 8 `WS events` emitted and list the following?

- network_ready
- network_newBlock
- network_newTransaction
- chain_forked
- chain_newBlock
- chain_deleteBlock
- chain_validatorsChanged
- txpool_newTransaction

2023-08-02 08:37 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  The Lisk blockchain generates various events that emit on-chain data.
Good idea, I have added in an link as suggested 👍

2023-08-02 10:21 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +WS events offered by Lisk can be subscribed to directly by any plugin, external service, or application.
Sure, it is now done 👍

2023-08-02 15:11 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +// Subscribe-Specific event code snippet to be updated.
Done 👍

2023-08-02 16:51 UTC, sameersubudhi requested changes

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +.. Subscribing to events
```suggestion
.. Subscribing to WS events
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +=== Subscribing to events
```suggestion
=== Subscribing to WS events
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +The aforementioned events are different in terms of when and how they are *generated*, and also how these events can be *accessed*.
```suggestion
// update the following links etc., regarding RPC : now JSON-RPC and not RPC
// The emitted events can either be xref:{url_understand_rpc_events}[JSON-RPC Events] or xref:{url_understand_blockchain_events}[Blockchain Events].
The emitted events can either be xref:{url_understand_ws_events}[JSON-RPC] or xref:{url_understand_blockchain_events}[Blockchain] events.
The aforementioned events are different in terms of when and how they are *generated*, and also how these events can be *accessed*.
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +=== The difference between JSON-RPC events and blockchain events
```suggestion
=== The difference between JSON-RPC events and Blockchain events
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +// Lisk makes *JSON-RPC events* accessible to everyone by offering xref:{url_understand_events}[a range ofxxxWS  RPC-based events].
```suggestion
// Lisk makes *JSON-RPC events* accessible to everyone by offering xref:{url_understand_events}[a range of JSON-RPC-based events].
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +Lisk makes *JSON-RPC events* accessible to everyone.
```suggestion
The Lisk API client makes *JSON-RPC events* easily accessible to everyone.
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +To clarify this in more detail, only the following `JSON-RPC events` listed below can be emitted:
```suggestion
The subscribers can then get real-time information about the subscribed event, for example, the generation of a new block on the network, the addition of a new transaction in the transaction pool, a round state change event, etc. There are only eight known `JSON-RPC events` that can be emitted, and are as following:
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
Can we please replace the `IPC API client example` script with the following? It's a minor refactoring to keep both the scripts consistent.

```node
const { apiClient } = require('@liskhq/lisk-client');
let clientCache;
const nodePath = '~/.lisk/my-app';

const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createIPCClient(nodePath);
    }
    return clientCache;
};

getClient().then((client) => {
    client.subscribe('network_newBlock', (data) => {
    console.log('new block: ', data);
    });
});
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
Please replace the following lines for the `WS API client example` script as well 🙏 

```node
getClient().then((client) => {
    client.subscribe('network_newBlock', (data) => {
    console.log('new block: ', data);
    });
});
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +=== Retrieving a blockchain event
```suggestion
=== Retrieving a Blockchain event
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  For example, modules such as `Reward` emit the `rewardMinted` event after each block execution.
```suggestion
With each block execution, various events are generated and stored in the event log, and can offer various insights.
For example, the `dynamicReward` module emits the `rewardMinted` event after each block execution. It offers information about the exact reward earned for block generation by the block generator.
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +Instead, *blockchain events are requested for a particular block height* and are provided as a parameter in the request.
```suggestion
NOTE: In contrast to JSON-RPC events, Blockchain events cannot be directly subscribed to.
Instead, *Blockchain events are requested for a particular block height*, which must be provided as a parameter in the request.
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
We can remove `.fetchBlockchainEvent.js` from L165.

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  .Make sure your blockchain client is running before executing the script
Please replace L196-L206 with:

```node
getClient().then((client) => {
    // Returns the encoded event based on the 'height' passed
    client.invoke(
        "chain_getEvents",
        { height: 60 },
    ).then(events =>
        // Filter out the 'rewardMinted' event
        const rewardMintedEvent = events.find(e => e.name === 'rewardMinted');

        // Decode the aforementioned event's data by passing relevant schema and the encoded 'data'
        const parsedEventData = codec.decode(rewardMintedDataSchema, Buffer.from(rewardMintedEvent.data, 'hex'));

        // Print the event and the contained data
        console.log("Reward minted event: ", rewardEvent);
        console.log("Reward minted event data: ", parsedEventData);
    });
});
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +The Lisk Service Subscribe API allows subscribing to events to receive real-time updates or notifications, as shown in the example below.
```suggestion
The Lisk Service Subscribe API allows subscribing to the WS events to receive real-time updates or notifications, as shown in the example below.
```

2023-08-02 16:51 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +// Subscribe-Specific event code snippet to be updated.
```suggestion
```

2023-08-03 07:00 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
Good point...now done 👍

2023-08-03 07:44 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
Done 👍

2023-08-03 09:08 UTC, sameersubudhi approved these changes
LGTM 👍

2023-08-03 09:08 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +.. Retrieving a blockchain event
```suggestion
.. The difference between JSON-RPC events and Blockchain events
.. Subscribing to a JSON-RPC event
.. Retrieving a Blockchain event
```

2023-08-04 11:09 UTC, TalhaMaliktz requested changes

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
>  :url_advanced_rpc: api/lisk-node-rpc.adoc
Whilst generating the preview, I get the following errors! Please correct them.
![image](https://github.com/LiskHQ/lisk-docs/assets/13951043/be7fb52f-44fd-45fa-b41c-88aa9d913ec9)

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +On this page you'll learn about how events can be subscribed to, or retrieved from a Lisk blockchain.
```suggestion
On this page, you'll learn about how events can be subscribed to, or retrieved from a Lisk blockchain.
```

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +Specifically the following topics are covered:
```suggestion
Specifically, the following topics are covered:
```

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +.. Subscribing to WS events
Maybe use bullets rather than numbers?
```suggestion
* Events of Lisk Application
** [x] The difference between JSON-RPC events and Blockchain events.
** [x] Subscribing to a JSON-RPC event.
** [x] Retrieving a Blockchain event.
* Event of Lisk Service
** [x] Subscribing to WS events.
```

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +=====
```suggestion

```

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +--
```suggestion

```

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +== Lisk Service
Please add a brief intro to events generated by Lisk Service. What, how, and where they are generated, are they generated on the chain or on the middleware, etc?
Are these events similar to JSON-RPC events?

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +:url_understand_ws_events: understand-blockchain/sdk/rpc.adoc
```suggestion
:url_understand_ws_events: understand-blockchain/sdk/rpc.adoc#rpc-events
```

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +- `txpool_newTransaction`
Instead of listing the events here, I would refer to the event reference page https://liskhq.github.io/lisk-docs/beta/api/lisk-node-rpc.html#events to avoid duplicating content.

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +:url_lisk_service_pubsub: ROOT::api/lisk-service-pubsub.adoc
Should point to the `beta` version, not the `default`.

2023-08-04 11:09 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +/* Subscribe to all the events */
I would also add a response to the aforementioned subscription to aid the reader.

2023-08-04 12:55 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +- `txpool_newTransaction`
Yes, that would be another option, although Sameer recommended we display the events here.

2023-08-07 09:38 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +== Lisk Service
OK, I have mentioned this and referenced the appropriate link here 👍

2023-08-07 09:39 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +/* Subscribe to all the events */
Done 👍

2023-08-07 09:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +:url_references_elements_client: {sdk_docs}references/typedoc/classes/lisk-elements/client.adoc
These two lines generate the warning mentioned in the screenshot above. Please remove these two lines. 
```suggestion

```

2023-08-08 07:32 UTC, TalhaMaliktz reviewed
Looking good already!

2023-08-08 07:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +* Event of Lisk Service
```suggestion
* Events of Lisk Service
```

2023-08-08 07:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +There are only eight known `JSON-RPC events` that can be emitted, and these are described in more detail here in the xref:{url_events}[events section] of the RPC API for Lisk nodes page.
```suggestion
There are only eight known `JSON-RPC events` that can be emitted, and these are described in more detail in the xref:{url_events}[events section] of the RPC API for the Lisk nodes page.
```

2023-08-08 07:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +A detailed list of all available emitted events are available in the xref:{url_lisk_service_pubsub}[Publish/Subscribe API (Lisk Service)] page.
```suggestion
A detailed list of all available emitted events is available on the xref:{url_lisk_service_pubsub}[Publish/Subscribe API (Lisk Service)] page.
```

2023-08-08 07:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +Further updated information regarding WS events generated by Lisk Service can also be found here in the {url_lisk_service_repo}[Lisk Service] GitHub repository.
```suggestion
Further updated information regarding WS events generated by Lisk Service can also be found here in the {url_lisk_service_repo}[Lisk Service^] GitHub repository.
```

2023-08-08 07:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +The API client simplifies the JSON-RPC event subscription process not only for a blockchain client but also for the external plugins and services.
```suggestion
The API client simplifies the JSON-RPC event subscription process not only for a blockchain client but also for external plugins and services.
```

2023-08-08 07:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/subscribing-to-events.adoc
> +Lisk Service utilizes the WebSocket library to facilitate two-way communication, ensuring users are kept informed about blockchain network and market changes.
```suggestion
Lisk Service utilizes the WebSocket library to facilitate two-way communication, ensuring users are kept informed about a blockchain network and market changes.
```

2023-08-08 07:46 UTC, TalhaMaliktz approved these changes
LGTM! 👍🏼

2023-08-08 13:34 UTC, merged