Add mainnet overview page
LiskArchive/lisk-legacy-docs pull request #1853
Opened 2023-07-31 15:20 UTC by Tschakki

Closes #1289

2023-08-01 15:51 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +There are two permanently accessible public Lisk blockchain networks which are entirely independent of each other: the <<lisk-mainnet>> the <<lisk-testnet>>.
```suggestion
There are two permanently accessible public Lisk blockchain networks which are entirely independent of each other: the <<lisk-mainnet>> and the <<lisk-testnet>>.
```

2023-08-01 15:56 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Additional to the permanent networks, it is also possible to spin up a local network for development, called <<devnet>>, or to connect to a public <<lisk-betanet>>, which is accessible during beta re
```suggestion
In addition to the permanent networks, it is also possible to spin up a local network for development, known as the <<devnet>>, or to connect to a public network such as the <<lisk-betanet>>, which is accessible during beta releases for new Lisk Core versions.
```

2023-08-01 15:58 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Table 1 below compares Mainnet and Testnet mainchain and their specific properties and configurations:
```suggestion
Table 1 below provides a comparison between the Mainnet and the Testnet mainchain, and lists their specific properties and configurations:
```

2023-08-02 06:58 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +<<table1,Table 1>> below compares Mainnet and Testnet mainchain and their specific properties and configurations:
```suggestion
<<table1,Table 1>> below compares the Mainnet and the Testnet mainchain, and lists their specific properties and configurations:
```

2023-08-02 07:00 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Within this network the Lisk users can transfer LSK tokens from one account to another, register accounts as validators to generate new blocks, or register their xref:{url_understand_sidechains}[side
```suggestion
Within this network, the Lisk users can transfer LSK tokens from one account to another, register accounts as validators to generate new blocks, or register their xref:{url_understand_sidechains}[sidechains] to make them interoperable with any other registered sidechain.
```

2023-08-02 07:20 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The native token for the Lisk Mainchain is *LSK*, pronounced like "Lisk".
```suggestion
The native token for the Lisk Mainchain is *LSK*, pronounced as "Lisk".
```

2023-08-02 07:27 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Testnet is an independent replica of the Lisk Mainnet, whose main function is to test the upgrades first before they are run on the Lisk Mainnet.
```suggestion
The Testnet is an independent replica of the Lisk Mainnet, primarily designed to test upgrades before implementing them on the Lisk Mainnet.
```

2023-08-02 07:31 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +For users, the Testnet provides the possibility to perform their own tests of their Lisk applications, or to test their validator node setup, without spending any real LSK, or risking punishment on t
```suggestion
For users, the Testnet provides the possibility to perform their own tests of their Lisk applications, or to test their validator node setup, without spending any real LSK, or risking punishment on the Mainnet.
```

2023-08-02 07:36 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +.Testnet LSK are "play money"
```suggestion
.Testnet LSK serves as "play money"
```

2023-08-02 07:39 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +IMPORTANT: Testnet LSK have no monetary value themselves, their only purpose is to test things in the Lisk testnet, without the need of spending "real" LSK tokens.
```suggestion
IMPORTANT: Testnet LSK holds no intrinsic monetary value; they are purely intended for testing purposes within the Lisk Testnet, eliminating the necessity to spend "real" LSK tokens. Furthermore, Testnet LSK cannot be exchanged for Mainnet LSK or any other currency.
```

2023-08-02 07:42 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +In contrast to the <<lisk-testnet>>, the Lisk Betanet is only available during beta testing phases of Lisk Core, which generally happen in preparation of bigger updates of the blockchain protocol.
```suggestion
In contrast to the <<lisk-testnet>>, The Lisk Betanet is exclusively accessible during the beta testing phases of Lisk Core, which typically occur in preparation for significant updates to the blockchain protocol.
```

2023-08-02 07:46 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The purpose of the Devnet is to provide an easy to setup local blockchain network for specific tests which the user has full control over.
```suggestion
The purpose of the Devnet is to provide a user-friendly locally set up blockchain network for performing specific tests, granting the user complete control over the environment.
```

2023-08-02 07:49 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +This can be useful if it is intended to run the blockchain with different configurations and/or modules, or to test specific stuff that would be too complicated or complex to test it on the Testnet.
```suggestion
This can be beneficial when planning to operate the blockchain with various configurations and/or modules, or to test specific functionalities that might be too intricate or complex to evaluate on the Testnet.
```

2023-08-02 07:51 UTC, chris529 reviewed
Looks great! I just made a few minor suggestions 👍

2023-08-02 08:58 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +In contrast to the <<lisk-testnet>>, the Lisk Betanet is only available during beta testing phases of Lisk Core, which generally happen in preparation of bigger updates of the blockchain protocol.
```suggestion
In contrast to the <<lisk-testnet>>, the Lisk Betanet is exclusively accessible during the beta testing phases of Lisk Core, which typically occur in preparation for major updates to the blockchain protocol.
```

2023-08-02 09:00 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +This can be useful if it is intended to run the blockchain with different configurations and/or modules, or to test specific stuff that would be too complicated or complex to test it on the Testnet.
```suggestion
This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too intricate or complex to evaluate on the Testnet.
```

2023-08-02 09:44 UTC, sameersubudhi requested changes

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Table 1 below compares Mainnet and Testnet mainchain and their specific properties and configurations:
Please consider adding a hyperlink to `Table 1` in the statement as well.

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Additional to the permanent networks, it is also possible to spin up a local network for development, called <<devnet>>, or to connect to a public <<lisk-betanet>>, which is accessible during beta re
Maybe specify it as `which is temporarily accessible`.

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +<<table1,Table 1>> below compares Mainnet and Testnet mainchain and their specific properties and configurations:
```suggestion
<<table1,Table 1>> below compares the Mainnet and the Testnet mainchain and their specific properties and configurations:
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|<<proof-of-stake-testnet,PoS(Testnet)>>
```suggestion
|<<proof-of-stake-mainnet,PoS (Mainnet)>>
|<<proof-of-stake-testnet,PoS (Testnet)>>
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
```suggestion
|Maximum block/transaction size
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
```suggestion
|LSK Token ID
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|7001
@shuse2 @Nazgolze Should we update the default Lisk Core configs to use `7667` for p2p on both mainnet and testnet?

```suggestion
|Default P2P Port
|8001
|7001

|Default RPC Port
|7887
|7887

```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|For 300 blocks
```suggestion
|Keeps blockchain events (default)
|For last 300 blocks
|For last 300 blocks
```
or
```suggestion
|Keeps blockchain events (default)
|For latest 300 blocks
|For latest 300 blocks
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|0.05 LSK
Should we specify the values in Beddows followed by LSK, for consistency, just like `Minimum fee per byte` above?

```suggestion
|User account initialization fee
|5000000 Beddows (0.05 LSK)
|5000000 Beddows (0.05 LSK)
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|0.05 LSK
Same as above.
```suggestion
|Escrow account initialization fee
|5000000 Beddows (0.05 LSK)
|5000000 Beddows (0.05 LSK)
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token
Let us also specify the Genesis height for the networks on the first row.

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Within this network, the Lisk users can transfer LSK tokens from one account to another, register accounts as validators to generate new blocks, or register their xref:{url_understand_sidechains}[sid
```suggestion
Within this network, Lisk users can transfer LSK tokens from one account to another, register accounts as validators to generate new blocks, or register their xref:{url_understand_sidechains}[sidechains] to make them interoperable with any other registered sidechain.
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +At this time there are no other tokens supported.
I think, we should skip this line as we technically will support all the tokens on the mainchain. I'm not quite sure if we want to communicate it openly. We'll need some clarification here.
```suggestion
Each LSK is further subdivided into 10^8^ *Beddows*.
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|101
```suggestion

|Minimum weight for standby delegates
|1000 LSK

|Round length
|103 blocks

|Number of active validators
|101
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Max number of pending unlocks
It'd be nice for the people to understand what validator/stake/unlock/active validator/standby validator is? Can we link these terms to the Glossary please?

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|1000 LSK
```suggestion
|Minimum weight for standby validators
|100000000000 Beddows (1000 LSK)
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +=== Rewards (Mainnet)
Can we also add a Glossary entry to explain the Rewards related properties stated below and link them here?

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +. {url_github_legacy}[Legacy module^]
Should we not link these to their corresponding LIPs? Also, [LIP-0045](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md) only defines it as `Interoperability` module. Should we not specify it the same way but highlight that only Lisk Core can act as the `mainchain` others will always be the `sidechains`?

Also, currently [the pages](https://lisk.com/documentation/lisk-sdk/v6/references/typedoc/classes/lisk_framework.MainchainInteroperabilityModule.html) they refer to do not seem to be consistent in CSS styling with the current page.
```suggestion
. {url_typedoc_auth}[Auth module^]
. {url_typedoc_token}[Token module^]
. {url_typedoc_fee}[Fee module^]
. {url_typedoc_reward}[Reward module^]
. {url_typedoc_random}[Random module^]
. {url_typedoc_validator}[Validator module^]
. {url_typedoc_pos}[PoS module^]
. {url_typedoc_mc}[Interoperability module^]
. {url_github_legacy}[Legacy module^]
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Subsequently, this is where new/updated versions and fixes of the Lisk Core are tested.
```suggestion
The Testnet is an independent replica of the Lisk Mainnet, primarily designed to test upgrades before implementing them on the Lisk Mainnet.

This is where the new upcoming versions and fixes of the Lisk Core are tested, and, subsequently applied to the Lisk Mainnet.
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +For users, the Testnet provides the possibility to perform their own tests of their Lisk applications, or to test their validator node setup, without spending any real LSK, or risking punishment on t
Should we highlight what `punishment` here refers to?

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +. {url_github_legacy}[Legacy module^]
Same as above for the highlighted sections.

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Lisk Betanet is a temporarily accessible public blockchain network, that is used to test new beta releases of Lisk Core.
```suggestion
The Lisk Betanet is a temporarily accessible public blockchain network, that is used to test new beta releases of Lisk Core, prior to testing them on the Testnet.
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +In contrast to the <<lisk-testnet>>, the Lisk Betanet is exclusively accessible during the beta testing phases of Lisk Core, which typically occur in preparation for major updates to the blockchain p
```suggestion
In contrast to the <<lisk-testnet>>, the Lisk Betanet is exclusively accessible only during the beta testing phases of Lisk Core, which typically occur in preparation for major updates to the blockchain protocol.
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
```suggestion
|LSK Token ID
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
```suggestion
|LSK Token ID
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
```suggestion
|LSK Token ID
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Betanet
Please consider adding all the highlighted properties above (Mainnet/Testnet) for Betanet too.

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Devnet is a local development network which is running on a single node.
This statement is incorrect. One could actually set up a devnet network with multiple nodes. But, usually used for development purposes.

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too in
```suggestion
This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too intricate or complex to evaluate on one of our public networks, such as the Betanet or the Testnet.
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
```suggestion
|LSK Token ID
```

2023-08-02 09:44 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Devnet
Should we also make the table consistent with all the details specified above for the Mainnet/Testnet?

2023-08-02 10:26 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
Isn't this only transaction size? If transaction can already be 15kB, then block would be probably bigger size?

2023-08-02 10:29 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +At this time there are no other tokens supported.
already removed :)

2023-08-02 10:34 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
This config [here](https://github.com/LiskHQ/lisk-core/blob/v4.0.0-beta.4/config/mainnet/config.json#L20) actually refers to the block size, viz. sum total of the size of all the transactions contained within a block. Hence, also limits the max transaction size to 15 kB, in which case the block can only contain 1 transaction.

LIP-0055 explains it in the Block validation section [here](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0055.md#validation).

2023-08-02 10:36 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +. {url_github_legacy}[Legacy module^]
TO address your valid questions:

1. We link to TypedDocs instead of LIPs, because we expect them to provide all the information relevant for developers in the future. Additionally, they should be easier to read than the LIPs. This info will be added soon via TypeDoc code comments in the respective module. Inside of the Typedocs, we will also add lnks to all relevant LIPs for the module.
2. Interoperability module includes both mainchain and sidechain module. on mainchain, only mainchain module is used, so this is correct imho.
3. About CSS styling, this is the default TypeDoc styling. We have an issue about creating our own custom Typedoc UI, but currently we have other priorities to work on first.

2023-08-02 10:43 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too in
I wouldn't update that like this, because betanet is only temporary, and we would need to update this section every time we add/remove a betanet

2023-08-02 10:45 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +. {url_github_legacy}[Legacy module^]
> Interoperability module includes both mainchain and sidechain module. on mainchain, only mainchain module is used, so this is correct imho.

Actually, both [LIP-0045](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md) and the [SDK implementation](https://github.com/LiskHQ/lisk-sdk/tree/v6.0.0-beta.5/framework/src/modules/interoperability) only have `Interoperability` module defined/implemented. However, when we [initialize the application](https://github.com/LiskHQ/lisk-core/blob/development/src/application/index.ts#L19), the mainchain commands are explicitly enabled on Lisk Core by setting the `mainchain` flag to `true`. This is set to `false` by default. Hence, the sidechains only have access to the sidechain commands.

2023-08-02 10:45 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
I would prefer to leave it as `Token ID`, because LSK is very specific identifier of the Mainnet token, we should not use it anywhere else.

2023-08-02 10:48 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too in
Or, maybe consider updating it as: `the Betanet (whenever operational/available)`, so that we do not have to maintain it?

2023-08-02 10:48 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
I see, but it is not really precise and a little confusing tbh. There should be two different values for max block size and max tx size

2023-08-02 10:50 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
And i am not sure if adding this will cause any clearance, for me it would be really confusing to read max block/tx size is the same, and it might irritate the reader unneccessarily

2023-08-02 10:52 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
Actually, we consistently use `LSK` for the Lisk token on all the networks. This is the exact symbol we use on the wallets for all the networks too. To me, only specifying `Token ID` doesn't give enough information and sounds vague.

2023-08-02 10:54 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
Then, if we were to choose only one, I'd prefer having it as `Maximum block size`.

2023-08-02 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +. {url_github_legacy}[Legacy module^]
I see your point, but imho it is more fitting to say mainchain registers mainchainInteroperability module, and sidechain registers sidechain interoperability module, this is also what the `mainchain` flag will affect: https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/application.ts#L172-L178

2023-08-02 11:05 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +In contrast to the <<lisk-testnet>>, the Lisk Betanet is exclusively accessible during the beta testing phases of Lisk Core, which typically occur in preparation for major updates to the blockchain p
`exclusively` makes it clear already here imho

2023-08-02 11:06 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Betanet
Imho we shouldn't ad additional values here, because they will be only temporarily valid as long as the betanet exists.

2023-08-02 11:08 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Devnet
We could add the default values here, highlighting that anything can be changed by the developer in the devnet, if they have the desire.

2023-08-02 11:10 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Maximum transaction size
```suggestion
|Maximum block size
```

2023-08-02 11:12 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
Imho this is something to consider to be changed in the UI as well, it can cause unnecessary confusion. I would suggest to use a new abbreviation for Tesnet Lisk and Betanet Lisk, something like TLSK and BLSK, because otherwise there is no easy way for user to distinguish the cifferent currencies, other than looking at the tokenID, which is not very user-friendly

2023-08-02 11:17 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too in
```suggestion
This can be beneficial when planning to operate the blockchain with different configurations and/or modules compared to the public mainchains, or to test specific functionalities that might be too intricate or complex to evaluate on one of our public networks, such as the Betanet (whenever operational/available) or the Testnet.
```

2023-08-02 12:10 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Betanet
Then, do we plan to remove the `Betanet` section after we move into the RC phase?

2023-08-02 12:16 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Token ID
I think, we are correct in using LSK on all the networks, since the user is already aware of the network they are connected to. But so that we're all aligned, could you please bring this discussion to slack? 🙏 

BTW Ethereum uses the same symbol (ETH) even on their testnet, but they do explicitly state `testnet ETH`.
Ref: https://ethereum.org/en/developers/docs/networks/. Please check the second paragraph.

2023-08-02 12:35 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Devnet is a local development network which is running on a single node.
updated it slightly

2023-08-02 12:36 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Betanet
No, this is why i would like to keep it general, only including information that is valid for every beta release

2023-08-03 11:05 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +In principle, if percentage of rewards shared equally among active validators is set to 0%, then it will be a proof-of-stake system where rewards are proportional to the validator weight.
```suggestion
In principle, if the percentage of rewards shared equally among active validators is set to 0%, then it will be a proof-of-stake system where rewards are proportional to the validator weight.
```

2023-08-03 11:07 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +On the other hand, if the percentage of rewards shared equally among active validators is set to 100%, it will be the previous proof-of-stake (PoS) system where each validator received the same rewar
```suggestion
On the other hand, if the percentage of rewards shared equally among the active validators is set to 100%, it will be the previous proof-of-stake (PoS) system where each validator received the same reward for generating a block irrespective of their weights.
```

2023-08-03 11:08 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +For the Lisk mainchain, factor is: 1000 (10%).
```suggestion
For the Lisk mainchain, the factor is: 1000 (10%).
```

2023-08-03 12:56 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +The remaining stake rewards i.e. `stakeRewardActiveValidators` are distributed proportional to the validators weight.
```suggestion
The remaining stake rewards i.e., `stakeRewardActiveValidators` are distributed proportional to the validators weight.
```

2023-08-03 12:57 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +* `Pos.getActiveValidatorsNumber` correspond the number of active validators in the network.
```suggestion
* `Pos.getActiveValidatorsNumber` corresponds to the number of active validators in the network.
```

2023-08-03 12:58 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +The default reward `defaultRewardStandByValidators` is assigned to all stand-by validators i.e. there is a fixed reward irrespective of the validator weight.
```suggestion
The default reward `defaultRewardStandByValidators` is assigned to all stand-by validators i.e., there is a fixed reward irrespective of the validator weight.
```

2023-08-03 13:04 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +For the Lisk mainchain,
imho I think we should remove the space on line 341 and list the sentence as follows:
"For the Lisk mainchain, this helps the stand-by validators to cover the costs of running a node even though the probability of the selection is low in a round."

2023-08-03 13:44 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +If a validator misses a block then a validator generating the block second time will get the reward proportional to their weight.
```suggestion
If a validator misses a block, then a validator generating the block the second time will get the reward proportional to their weight.
```

2023-08-03 13:49 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +For the Lisk mainchain,
Imho we can just remove the line 340

```suggestion
```

2023-08-03 13:58 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +This results in imbalancing the total reward in a round.
```suggestion
If a validator misses a block then another validator will be chosen to generate the block.
```

2023-08-03 14:43 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +A minimum reward i.e. `minimumRewardActiveValidators` is assigned per round to all active validators to cover the minimal operational cost to run a validator.
```suggestion
A minimum reward i.e., `minimumRewardActiveValidators` is assigned per round to all active validators to cover the minimal operational cost to run a validator.
```

2023-08-03 14:48 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +In terms of inflation, currently in the Lisk mainchain, there is a maximum minting of `6 * 60 * 24 * 365 = 3153600 LSK` per year.
```suggestion
Currently, in the Lisk mainchain, the inflation is limited to a maximum minting of `6 * 60 * 24 * 365 = 3153600 LSK` per year.
```

2023-08-03 14:52 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +This is done after all transactions in the payload have been applied.
```suggestion
This is completed after all transactions in the payload have been applied.
```

2023-08-03 14:55 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Configurations of the {url_typedoc_reward}[Dynamic Reward module^] of Lisk Mainnet mainchain.
```suggestion
Configurations of the {url_typedoc_reward}[Dynamic Reward module^] of the Lisk Mainnet mainchain.
```

2023-08-03 14:56 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Configurations of the {url_typedoc_pos}[PoS module^] of Lisk Testnet mainchain.
```suggestion
Configurations of the {url_typedoc_pos}[PoS module^] of the Lisk Testnet mainchain.
```

2023-08-03 15:04 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Betanet is most interesting for validators and Lisk application developers, because they can explore new releases already before they are deployed on Testnet and Mainnet, to learn about new featu
imho I would just slightly reword this as follows:

"The Betanet holds significant appeal for validators and Lisk application developers, offering them the opportunity to explore new releases ahead of their deployment on the Testnet and the Mainnet. This allows them to gain insights into new features and stay updated with the latest advancements in the protocol."

2023-08-03 15:05 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +Also, it is the first publicly accessible network for new releases of Lisk Core, which is testing the new release in a broader scope.
```suggestion
Furthermore, it is the first publicly accessible network for new releases of Lisk Core, which is testing the new release in a broader scope.
```

2023-08-03 15:06 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Lisk Alphanet is used to test alhpa releases for new Lisk Core versions.
```suggestion
The Lisk Alphanet is used to test alpha releases for new Lisk Core versions.
```

2023-08-03 15:08 UTC, chris529 reviewed
It is looking great! I just made a few suggestions. 👍

2023-08-03 15:27 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +The Betanet is most interesting for validators and Lisk application developers, because they can explore new releases already before they are deployed on Testnet and Mainnet, to learn about new featu
```suggestion
The Betanet holds significant appeal for validators and Lisk application developers, offering them the opportunity to explore new releases ahead of their deployment on the Testnet and the Mainnet. This allows them to gain insights into new features and stay updated with the latest advancements in the protocol.
```

2023-08-03 16:09 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +`blockHeader.height` corresponds to the current block height and `getDefaultRewardAtHeight` return the <<default-block-reward>> for the respective height.
```suggestion
`blockHeader.height` corresponds to the current block height and `getDefaultRewardAtHeight` returns the <<default-block-reward>> for the respective height.
```

2023-08-03 16:11 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +* `blockHeader.height` corresponds to the current block height and `getDefaultRewardAtHeight` return the <<default-block-reward>> for the respective height.
```suggestion
* `blockHeader.height` corresponds to the current block height and `getDefaultRewardAtHeight` returns the <<default-block-reward>> for the respective height.
```

2023-08-03 16:32 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +For every block generated, the amount of available tokens increases, as new tokens are minted for the <<block-rewards.
```suggestion
For every block generated, the amount of available tokens increases, as new tokens are minted for the <<block-rewards>>.
```

2023-08-03 16:58 UTC, chris529 approved these changes
LGTM! 👍 I just left a few suggestions..

2023-08-07 09:42 UTC, sameersubudhi requested changes

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +This is performed by the Dynamic Rewards module, whose main purpose is to compute the block rewards according to the validator weight for active validators:
Ref: https://github.com/LiskHQ/lips/pull/438
```suggestion
This is performed by the `Dynamic Reward` module, whose main purpose is to compute the block rewards according to the validator weight for active validators as explained below.
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +SharedRewardsFactor::
```suggestion
factorMinRewardActiveValidators::
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +Here `blockHeader.height` is the current block height.
Perhaps we can add this explanation at the beginning so that we do not have to repeat it every time it is specified?

`blockHeader.height` is the current block height.

Same is applicable for `getDefaultRewardAtHeight` too.

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +To respect the maximum of 3153600 newly minted LSK per year, and to ensure it will not be profitable for any validator if any other validator misses a block, validators who generate blocks for the se
Can we also explain what happens to the remaining reward after assigning the `minimumRewardActiveValidators` to the second time block generator within a given round?

Also, it'd be nice to highlight that this is applicable within a single round.

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +==== Reward for Missed blocks
```suggestion
==== Minting of the rewards
After applying the block, a certain quantity of the native token of the blockchain is minted.
The exact amount assigned to the block generator.

Currently, in the Lisk mainchain, the inflation is limited to a maximum minting of `6 * 60 * 24 * 365 = 3153600 LSK` per year.
Every time a validator misses their block, 1 LSK less is minted per year.

==== Reward for missed blocks
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +==== Default Reward for StandBy Validators
```suggestion
==== Default reward for standby validators
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +==== Rewards Proportional to the Validators Weight
```suggestion
==== Rewards proportional to the validators weight
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +==== Minimum Reward for Active Validators
```suggestion
==== Minimum reward for active validators
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +=== Block Rewards
```suggestion
=== Block rewards
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +==== Minting of the Rewards
```suggestion
==== Minting of the rewards
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +Each transaction included in a block contains its own <<transaction-fees>>, which were paid by the sender of the transaction.
```suggestion
Each transaction included in a block contains its own <<transaction-fees>>, paid the transaction sender.
```

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +This increase is obtained by subtracting the burned fees from the block reward.
Should we link `<<minimum-transaction-fee>>` to the term `burned fees` in the statement above so that the users clearly understand what gets burned?

2023-08-07 09:42 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|7001
We'll update the ports in this issue: https://github.com/LiskHQ/lisk-core/issues/818
```suggestion
|Default P2P Port
|7667
|7667
```

2023-08-07 10:47 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +Each transaction included in a block contains its own <<transaction-fees>>, which were paid by the sender of the transaction.
```suggestion
Each transaction included in a block contains its own <<transaction-fees>>, which were paid by the transaction sender.
```

2023-08-07 11:49 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +To respect the maximum of 3153600 newly minted LSK per year, and to ensure it will not be profitable for any validator if any other validator misses a block, validators who generate blocks for the se
I am not sure what you are referring to, can you please elaborate?

2023-08-07 12:04 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +To respect the maximum of 3153600 newly minted LSK per year, and to ensure it will not be profitable for any validator if any other validator misses a block, validators who generate blocks for the se
Please ignore the second part, it's already covered. 👍

2023-08-07 12:28 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +To respect the maximum of 3153600 newly minted LSK per year, and to ensure it will not be profitable for any validator if any other validator misses a block, validators who generate blocks for the se
I verified that the 0.9 LSK do not get minted at all, so imho we can leave the content as-is

2023-08-07 12:48 UTC, sameersubudhi approved these changes
Looks much better. Thank you for the changes 🙇 
However, please consider the following before merging the PR.

2023-08-07 12:48 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +To respect the maximum of 3153600 newly minted LSK per year, and to ensure it will not be profitable for any validator if any other validator misses a block, validators who generate blocks for the se
I think, it'd be better to make it explicit with an additional statement similar to:

```
This results in minting of the lesser tokens than expected, i.e. with every missed block the Dynamic Reward module mints `getDefaultRewardAtHeight(blockHeader.height) - minimumRewardActiveValidators` less tokens.
```

2023-08-07 12:48 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +.Milestones for the default block rewards of the Lisk Mainnet
```suggestion
.Default block reward milestones on the Lisk Mainnet
```

2023-08-07 12:48 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Brackets (Reward reduction in Beddows for each milestone)
```suggestion
|Brackets (Block reward for each milestone in Beddows)
```

2023-08-07 12:48 UTC, sameersubudhi commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
> +|Brackets (Reward reduction in Beddows for each milestone)
```suggestion
|Brackets (Block reward for each milestone in Beddows)
```

2023-08-07 12:53 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/blocks-txs.adoc
> +To respect the maximum of 3153600 newly minted LSK per year, and to ensure it will not be profitable for any validator if any other validator misses a block, validators who generate blocks for the se
This is already mentioned in line 388

2023-08-07 12:55 UTC, merged