Add guide about multi-signature accounts
LiskArchive/lisk-legacy-docs pull request #1856
Opened 2023-08-03 15:49 UTC by Tschakki

Close #1263

2023-08-28 13:35 UTC, TalhaMaliktz requested changes

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +For a step-by-step guide how to create a new account with Lisk Desktop, please refer to: {url_lisk_learn_create_account}[^]
```suggestion
For a step-by-step guide about how to create a new account with Lisk Desktop, please refer to: {url_lisk_learn_create_account}[Create an Account^].
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +For a step-by-step guide how to create a new account with the node CLI, please refer to the xref:{url_run_accounts}[] guide.
```suggestion
For a step-by-step guide regarding how to create a new account with the node CLI, please refer to the xref:{url_run_accounts}[] guide.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +For a step-by-step guide how to create a new account with the Lisk Elements, please refer to the xref:{url_integrate_accounts}[] guide.
```suggestion
For a step-by-step guide on creating a new account with the Lisk Elements, please refer to the xref:{url_integrate_accounts}[] guide.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Members are added by pasting their respective public keys and selecting kbd:[Mandatory] or kbd:[Optional] for the specific member.
What does being `optional` or `mandatory` mean in this context?

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from above in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<collecting-signatures>>.
What is the process of collecting signatures using Node CLI?

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +... }
Do these dots `...` mean anything like string concatenation or are they for cosmetic purposes?

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +isk-core > api.then((client) => {
```suggestion
lisk-core > api.then((client) => {
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +...     recipientAddress: 'lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz',
What does a `recipientAddress` mean in this context? and where is the MSG transaction payload in this example?

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +lisk-core > let hexTx
What does `let hexTx` mean?

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +In this case the minimum required signatures are two, which is also displayed in the transction details.
```suggestion
In this case, the minimum required signatures are two, which is also displayed in the transaction details.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +{"transaction":{"module":"token","command":"transfer","fee":"100000000","nonce":"4","senderPublicKey":"3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c","signatures":["c06cd0ef3759115
Please format this as pretty JSON and then paste it here. The transaction in a single line makes it hard to read.

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +When the transaction was accepted, the following confirmation message will be displayed.
```suggestion
When the transaction is accepted, the following confirmation message will be displayed.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from the last step in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<how-to-sign-a-multi-signature-transaction>>.
How to use CLI to sign a transaction?

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Considering the wallet is configured to be 2-of-3 multi-sig wallet, the third key in above case is given to the arbiter.
```suggestion
Considering the wallet is configured to be a 2-of-3 multi-sig wallet, the third key in the above case is given to the arbiter.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Based on arbiter’s judgment the funds can be given either to Alice or to Bob.
```suggestion
Based on the arbiter’s judgment the funds can be given either to Alice or to Bob.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Another  use case are "validator pools".
```suggestion
Another use case is of "validator pools".
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +A multi-signature account can be registered as validator, or an existing validator user account can be converted to a multi-signature validator account.
```suggestion
A multi-signature account can be registered as a validator, or an existing validator user account can be converted to a multi-signature validator account.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Therefore, it is not possible for a single person to issue any transactions for the validator, like staking, changing the commission or transferring tokens.
```suggestion
Therefore, a single individual can't issue any transactions for the validator, like staking, changing the commission, or transferring tokens as they would require the authorization of other members of the group.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +This way, not only one person controls the account.
```suggestion
This way, a single person does not control the account.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +CAUTION: However, using multi-signature as two-factor authentication can be risky, especially if it is a set of 2-of-2 multi-sig address.
```suggestion
CAUTION: However, using multi-signature as two-factor authentication can be risky, especially if it is a set of 2-of-2 multi-sig addresses.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Or consider a corporation with four board of directors.
```suggestion
Or consider a corporation with four board members serving as board of directors.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +=== Pick account for becoming multi-signature
```suggestion
=== Pick an account to become multi-signature
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Depending on the use case, you might want to turn one of your existing accounts into a multi-signature account, or to create a new account which will be used as multi-signature account.
```suggestion
Depending on the use case, you might want to turn one of your existing accounts into a multi-signature account or create a new account that will be used as a multi-signature account.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Click on the "Register multisignature account" button in the top left menu::
```suggestion
Click on the "Register multi-signature account" button in the top left menu::
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +To convert the current account into a multi-signature account, click on the top-left menu and select kbd:[Register multisignature account].
```suggestion
To convert the current account into a multi-signature account, click on the top-left menu and select kbd:[Register multi-signature account].
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +When all parameters are defined, click on kbd:[Go to confirmation] button to go proceed with the next step.
```suggestion
When all parameters are defined, click on the kbd:[Go to confirmation] button to go proceed with the next step.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The transaction to be signed is provided as JSON file or can be directly copied to clipboard.
```suggestion
The transaction to be signed is provided as a JSON file or can be directly copied to the clipboard.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +NOTE: The `000..0` signatures are placeholder for the pending signatures from the members of the multi-signature group.
```suggestion
NOTE: The `000..0` signatures are placeholders for the pending signatures from the members of the multi-signature group.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Put as `address` a hex string of the account address which you wish to convert to a multi-signature account.
```suggestion
Put as `address` a hex string of the account address that you wish to convert to a multi-signature account.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Therefore, it is recommended to choose a first member of the group to share the transaction, and as soon as the member has signed the transaction, to pass the resulting JSON on to the next member.
```suggestion
Therefore, it is recommended to choose the first member of the group to share the transaction, and as soon as the member has signed the transaction, pass the resulting JSON on to the next member.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Don't forget to specify the other required parameters for `ed.signDataWithPrivateKey()`, especially `chainID` should be the correct chain ID for the account, and `tag` for multi-signature registratio
```suggestion
Don't forget to specify the other required parameters for `ed.signDataWithPrivateKey()`, especially `chainID` should be the correct chain ID for the account, and the `tag` for multi-signature registrations should always be `LSK_RMSG_`.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Only when you log in to the original multi-sig account, it is possible to create the transaction object like described below.
```suggestion
Only when you log in to the original multi-sig account, it is possible to create the transaction object as described below.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Prepare a transaction, for example a token transfer::
```suggestion
Prepare a transaction, for example, a token transfer::
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +First the required signatures need to be collected.
```suggestion
First, the required signatures need to be collected.
```

2023-08-28 13:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +If the multi-sig-account itself is member of the group, one signature will be appended under signatures, additional to two placeholders for remaining signatures of other members.
```suggestion
If the multi-sig-account itself is a member of the group, one signature will be appended under signatures, and additionally, there will be two placeholders for the remaining signatures of other members.
```

2023-08-29 09:42 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +This way, not only one person controls the account.
```suggestion
This way, no single person controls the account.
```

2023-08-29 09:44 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Or consider a corporation with four board of directors.
```suggestion
Or consider a corporation with a board of four directors.
```

2023-08-29 09:45 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Click on the "Register multisignature account" button in the top left menu::
the button label is without the hyphen

2023-08-29 09:45 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +To convert the current account into a multi-signature account, click on the top-left menu and select kbd:[Register multisignature account].
the button label is without the hyphen

2023-08-29 09:48 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Members are added by pasting their respective public keys and selecting kbd:[Mandatory] or kbd:[Optional] for the specific member.
The parameters `mandatoryKeys` and `optionalKeys` are explained in section "How to create a multi-signature account"

2023-08-29 09:49 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from above in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<collecting-signatures>>.
there is non afaik

2023-08-29 09:52 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +lisk-core > let hexTx
defines a variable

2023-08-29 09:52 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +...     recipientAddress: 'lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz',
`recipientAddress ` is a parameter for the token transfer tx.

What do you mean with "MSG transaction payload"?

2023-08-29 09:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +... }
i think this is how it is copied from the lisk console, no meaning afaik

2023-08-29 09:56 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from the last step in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<how-to-sign-a-multi-signature-transaction>>.
it basically says you should use Lisk Desktop, as there is no straight-forward way to do it via cli

2023-08-31 07:58 UTC, TalhaMaliktz requested changes

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from above in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<collecting-signatures>>.
I think we should remove the NODE CLI tab completely. Having a tab that doesn't describe the required content can be confusing.

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +...     recipientAddress: 'lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz',
So this is how I understand this:
A token transfer transaction (as shown in the snippet) has been initiated from a multi-sig account. This transaction now requires signatures from all the mandatory and optional keys. I am wondering about those signatures; the snippet displays a single signature value. How would the same transaction look like when signed by multiple parties?

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +lisk-core > const tx = {
For me, `lisk console` opens `lisk-commander >`, why is this different?
```suggestion
lisk-commander > const tx = {
```

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from the last step in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<how-to-sign-a-multi-signature-transaction>>.
IMHO, we should remove the NODE CLI to avoid confusion.

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Once all required signatures for the respective multi-sig transaction are collected, it can be sent like a normal transaction, like described here: xref:{url_integrate_posttxs_apiclient}[].
```suggestion
Once all required signatures for the respective multi-sig transaction are collected, it can be sent like a normal transaction, as described here: xref:{url_integrate_posttxs_apiclient}[WS & IPC API example with API client].
```

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Create a transaction like normally for example with the API client, like explained here: xref:{url_integrate_createtxs_apiclient}[How to create a transaction via API client].
```suggestion
Create a transaction like normally for example with the API client, as explained here: xref:{url_integrate_createtxs_apiclient}[How to create a transaction via API client].
```

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The main thing that needs to updated in the script, is the transaction object to be signed.
1. I ran the script at my end by passing a private key to it, what is the next step in case two signatures are required? I think this should be mentioned here.
2. The signatures returned by the script are in the `buffer` format, I think these should be in the JSON hex format.

![image](https://github.com/LiskHQ/lisk-docs/assets/13951043/df8cc41f-b0b9-43e9-a53b-184e2cf1d25c)

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Extend the script from <<how-to-create-a-multi-signature-account>> and append some code that asks the private key of a user, and uses it to sign the prepared transaction JSON.
What script are we talking about here? 🤔 The hyperlink takes you to the section where all the properties are described.

2023-08-31 07:58 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Prepare a JSON object that contains all required <<parameters>> for sending a multi-signature registration.
```suggestion
Prepare a JSON object that contains all required <<parameters, parameters>> for sending a multi-signature registration.
```

2023-08-31 08:23 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +...     recipientAddress: 'lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz',
>  How would the same transaction look like when signed by multiple parties?

In that case there would be multiple signatures under the `signatures` property of the tx. In this case it was in fact only one signature, so I updated it now to be multiple signatures 👍

2023-08-31 08:24 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +lisk-core > const tx = {
console can be opened from both commander and node CLI :)

2023-08-31 08:34 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Extend the script from <<how-to-create-a-multi-signature-account>> and append some code that asks the private key of a user, and uses it to sign the prepared transaction JSON.
Was leading to the wrong section, updated it now.

2023-08-31 11:37 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Copy the transaction from above in JSON string format and proceed to sign the transaction object in Lisk Desktop, as explained in <<collecting-signatures>>.
I see your point, I have commented out the related content for now 👍

2023-08-31 11:45 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The main thing that needs to updated in the script, is the transaction object to be signed.
I updated the script to return the params in JSON

2023-08-31 14:20 UTC, TalhaMaliktz approved these changes
Looks great now! I have left a few comments for the final corrections to be made. Thank you 🚀

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +... hexTx = encodedTxtoString('hex');
```suggestion
... hexTx = encodedTx.toString('hex');
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +When using this script for several members, the `paramsStr` variable should be updated to the params that were returned from running `node mutisig.js PRIVATEKEY`.
```suggestion
When using this script for several members, the `paramsStr` variable should be updated to the params that were returned from running `node multisig.js PRIVATEKEY`.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
>  To collect all required signatures for a transaction from a multi-signature account, you can use a similar script the {url_github_guides_multisig}[multisig.js^], which was used in step <<collecting-s
```suggestion
To collect all required signatures for a transaction from a multi-signature account, you can use a similar script as the {url_github_guides_multisig}[multisig.js^], which was used in step <<collecting-signatures>> above.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +This way the accountant approves every transaction, which in turn allows them to keep an eye on all the club's expenditure.
```suggestion
This way the accountant approves every transaction, which in turn allows them to keep an eye on all the club's expenditures.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +For example, three people could each participate in a multisignature account with three mandatory keys and register this account as a validator.
```suggestion
For example, three people could each participate in a multi-signature account with three mandatory keys and register this account as a validator.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +When all parameters are defined, click on the kbd:[Go to confirmation] button to go proceed with the next step.
```suggestion
When all parameters are defined, click on the kbd:[Go to confirmation] button to proceed with the next step.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Extend the script from <<converting-a-user-account-into-a-multi-signature-account>> and append some code that asks the private key of a user, and uses it to sign the prepared transaction JSON.
```suggestion
Extend the script from <<converting-a-user-account-into-a-multi-signature-account>> and append some code that asks for the private key of a user, and uses it to sign the prepared transaction JSON.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +When all required signatures are added, the parameters can be used to xref:{url_integrate_createtxs_apiclient}[create] a multi-signature registration transaction from the account that should be conve
```suggestion
When all required signatures are added, the parameters can be used to xref:{url_integrate_createtxs_apiclient}[create] a multi-signature registration transaction from the account that should be converted to a multi-signature account.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +First, all required signatures need to be collect, like explained in <<how-to-sign-a-multi-signature-transaction>>.
```suggestion
First, all required signatures need to be collected, as explained in <<how-to-sign-a-multi-signature-transaction>>.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +That is why you want the transaction to be returned in JSON format in most cases, so all data to be signed is human-readable and can be reviewed verified by the respective group members.
```suggestion
That is why you want the transaction to be returned in JSON format in most cases, so all data to be signed is human-readable and can be reviewed and verified by the respective group members.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Like the name suggests, multi-signature transaction require signatures from multiple accounts to be valid.
```suggestion
As the name suggests, a multi-signature transaction requires signatures from multiple accounts to be valid.
```

2023-08-31 14:20 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The main thing that needs to updated in the script are the `module`, `command` and `params` properties of the transaction.
```suggestion
The main thing that needs to be updated in the script are the `module`, `command`, and `params` properties of the transaction.
```

2023-09-01 14:19 UTC, ishantiw approved these changes
Very nicely done 👏

2023-09-04 08:07 UTC, merged