Update Enabling Report Misbehavior plugin - Closes 1532
LiskArchive/lisk-legacy-docs pull request #1861
Opened 2023-08-09 14:29 UTC by TalhaMaliktz

Closes #1532

2023-08-10 09:41 UTC, Tschakki requested changes

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +The {url_plugin_report_misbehavior}[Report Misbehavior plugin^] provides automatic detection of the validator's misbehavior and sends a `reportDelegateMisbehavior` transaction to the running node.
"delegate" sounds like old terminology, please update

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +=== Registering via PM2
Maybe rename it, as there are also other ways to set environment variables
```suggestion
=== Enabling via environment variable
```

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +Otherwise, you can set up the `*pm2.conf.json*` file as suggested in the section: xref:{url_pm2_conf}[Using a JSON config file] for PM2.
I wouldn't include this info here, and keep it more general for other sidechains. Also, it is a little inconsistent with next section where we use `./bin/run` in the examples

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +== Starting the node
I would restructure this section to already be included separately in the above examples

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +The plugin uses a specified sender account to sign the `reportDelegateMisbehavior` transactions.
outdated terminology

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +Otherwise, you can set up the `*pm2.conf.json*` file as suggested in the section: xref:{url_pm2_conf}[Using a JSON config file] for PM2.
Actually, in most cases users want to enable it on Lisk Core, so maybe we should include the respective examples. Either as tabs, starting with Lisk Core examples followed by SDK, or replace the existing examples with Lisk Core

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For this guide, the Report Misbehavior plugin is registered to the xref:{url_guides_setup}[Hello World application], though the steps mentioned below can be applied to any Lisk-based blockchain clien
Would also explain for Lisk Core, see comment below

2023-08-10 09:41 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +The plugin is designed to work with PoS based blockchains only.
Maybe you can add a little more info here what misbehavior exactly will be reported, and maybe refer to the corresponding LIP as well, in a footnote for example.

2023-08-11 08:44 UTC, Incede requested changes
Looks good, just a couple of minor points

2023-08-11 08:44 UTC, Incede commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +With the latest version of Lisk Core v4 and Lisk SDK v6, the default plugins come pre-installed after an client is installed or initiated, respectively.
```suggestion
With the latest version of Lisk Core v4 and Lisk SDK v6, the default plugins come pre-installed after a client is installed or initiated, respectively.
```

2023-08-11 08:44 UTC, Incede commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For a *sidechain*, It is possible to register the plugin through the `plugins.ts` file.
question for my understanding - why is it not possible to do the same for mainchain ?

2023-08-11 08:44 UTC, Incede commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +It is possible to enable the Report Misbehavior plugin without updating the configuration, the `plugins.ts` file, or using PM2.
```suggestion
It is also possible to enable the Report Misbehavior plugin without updating the configuration, the `plugins.ts` file, or using PM2.
```

2023-08-11 08:44 UTC, Incede commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +Add the encrypted private key retrieved above under `plugins.reportMisbehavior.encryptedPrivateKey` in the node configuration:
```suggestion
Add the encrypted private key retrieved above under `plugins.reportMisbehavior.encryptedPrivateKey` to the node configuration:
```

2023-08-11 09:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For a *sidechain*, It is possible to register the plugin through the `plugins.ts` file.
`lisk-core` comes pre-configured with the default plugins. There is no `plugins.ts` file in `lisk-core` which can be edited to register a plugin via source.

2023-08-11 10:18 UTC, Tschakki requested changes
Looking good already, just a few minor comments

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +This transaction contains the information necessary to prove that the validator who signed the {url_blocks_header}[block headers^] has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] a
not sure why we are referring here to the block header specifically? I would just say "the validator who generated the block", to keep it simple.

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +This transaction contains the information necessary to prove that the validator who signed the {url_blocks_header}[block headers^] has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] a
A ToDo should be added here to update the link to BFT LIP with link to docs BFT page, once the page is created

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +:url_rep_mis_transaction: https://github.com/LiskHQ/lips/blob/1e27a5ba99a55d71e6d83f44b6e21f18dda98741/proposals/lip-0057.md#report-misbehavior
```suggestion
:url_consensus_bft: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0014.md
:url_consensus_bft_punishment: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0024.md
:url_rep_mis_transaction: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0057.md#report-misbehavior
```

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +Using this guide, the Report Misbehavior plugin can be registered to a xref:{url_core_index}[Lisk Core] or a xref:{url_guides_setup}[Hello World application] node, though the steps mentioned below ca
```suggestion
Using this guide, the Report Misbehavior plugin can be registered to a xref:{url_core_index}[Lisk Core] node or any Lisk-based blockchain client.
```

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For a sidechain, you can check the `package.json` file of the blockchain client to ensure the installation.
This is also valid for Lisk Core.

```suggestion
You can check the `package.json` file of the blockchain client to ensure the installation.
```

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +It is essential to enable WS API and configure the `allowedMethods` property before registering the `ReportMisbehaviorPlugin`.
How exactly should it be configured for the plugin? Please elaborate.

2023-08-11 10:18 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +For a *sidechain*, It is possible to register the plugin through the `plugins.ts` file.
```suggestion
For blockchain clients that were initialized with Lisk Commander, it is possible to register the plugin through the `plugins.ts` file.
```

2023-08-11 10:33 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +This transaction contains the information necessary to prove that the validator who signed the {url_blocks_header}[block headers^] has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] a
If you run the command `reportMisbehavior`, it expects two header values to be passed to it, which is why I have mentioned the headers to be specific.

2023-08-11 10:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +It is essential to enable WS API and configure the `allowedMethods` property before registering the `ReportMisbehaviorPlugin`.
Ummmm! it's mentioned in the URL referenced in the next line.

2023-08-11 11:45 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +This transaction contains the information necessary to prove that the validator who signed the {url_blocks_header}[block headers^] has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] a
In this case, I would rephrase it to make it clearer, and also, please replace link to block header with internal link to https://liskhq.github.io/lisk-docs/beta/understand-blockchain/blocks-txs.html#block-header


```suggestion
This transaction contains two xref:{}[block headers] necessary to prove that the validator who generated the blocks has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] and is deemed to be punished{fn_lip24} once proven guilty.
```

2023-08-11 11:48 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +It is essential to enable WS API and configure the `allowedMethods` property before registering the `ReportMisbehaviorPlugin`.
In the URL we explain to set allowedMethods to "*", but here for the guide we should mention the specific methods that should be enabled for this plugin to work correctly.

2023-08-11 12:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/enabling-misbehavior-report.adoc
> +This transaction contains the information necessary to prove that the validator who signed the {url_blocks_header}[block headers^] has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] a
```suggestion
This transaction contains two xref:{url_blocks_header}[block headers] that are necessary to prove that the validator who generated the blocks has violated the {url_consensus_bft}[Lisk-BFT consensus protocol^] and is deemed to be punished{fn_lip24} once proven guilty.
```

2023-08-11 13:25 UTC, Tschakki approved these changes
LGTM

2023-08-11 13:34 UTC, Incede approved these changes

2023-08-14 10:12 UTC, merged