Create section describing wallet passphrase & security in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1862
Opened 2023-08-10 09:58 UTC by chris529

Closes #1847

2023-08-28 15:49 UTC, Ade-kola approved these changes

2023-08-29 07:23 UTC, TalhaMaliktz requested changes

2023-08-29 07:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +As previously discussed, Lisk accounts employ a 12-word xref:{url_mnemonic_passphrase}[Mnemonic Passphrase] to ensure robust security.
```suggestion
As previously discussed, Lisk accounts employ a 12-word {url_mnemonic_passphrase}[Mnemonic Passphrase^] to ensure robust security.
```

2023-08-29 07:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +Wallets in general come in different forms, including a variety of software wallets, such as hot wallets, custodial/non-custodial and web wallets; to hardware wallets, and even paper wallets.
```suggestion
Wallets in general come in different forms, including a variety of software wallets, such as hot wallets, custodial/non-custodial, and web wallets; hardware wallets, and even paper wallets.
```

2023-08-29 07:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +A more in-depth overview can be found here regarding the overall xref:{url_wallet_types}[types of wallets] available.
```suggestion
For a more in-depth overview regarding the wallets, see {url_wallet_types}[types of wallets^].
```

2023-08-29 07:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/account-management.adoc
> +With 12 words offering a staggering 2^128 potential combinations, the probability of arriving at the correct combination is exceedingly remote.
```suggestion
With 12 words offering a staggering 2^128^ potential combinations, the probability of arriving at the correct combination is exceedingly remote.
```

2023-08-29 09:17 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2023-08-29 15:36 UTC, merged