Align code snippets
LiskArchive/lisk-legacy-docs pull request #1864
Opened 2023-08-11 11:33 UTC by Tschakki

Closes #1828

2023-08-17 13:54 UTC, TalhaMaliktz requested changes

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
Please use `[source,bash]` for the responses as well, since the output will also be visible in the bash. Secondly, to stay in sync with what we have done for `docs-service`. I suggest using captions with each snippet to improve the outlook.

PS: This applies to the entire page

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
Same comment as above!

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +
```suggestion

.Response
```

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
Same comment: Highlight as bash, and use captions to differentiate between lines.

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
Same comment as above

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
Would be nice to have caption here describing, what's happening below.

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/index.adoc
>  [source,bash]
**LINE 51:**
Confirm that Node.js and NPM have been successfully installed by executing the following commands:

2023-08-17 13:54 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
> +
A caption here would help with the outlook.

2023-08-21 08:23 UTC, chris529 reviewed
I concur with Talha's suggestions, otherwise all looks good 👍

2023-08-21 09:42 UTC, Tschakki commented on modules/ROOT/pages/client-cli.adoc
> +----
Specifying bash as source highlighter only makes sense if there are bash commands that should be highlighted correctly. If plain text is returned in the command line, i don't see the benefit to mark it as bash, as it might highlight words that are not supposed to be highlighted in the plain text.

2023-08-21 09:43 UTC, Tschakki commented on modules/ROOT/pages/client-cli.adoc
> +----
Conserning the captions, i am not sure what you mean? I added a lot of captions already

2023-08-21 09:50 UTC, Tschakki commented on modules/ROOT/pages/client-cli.adoc
> +----
Imho it is self-explanatory what is happening.

And it is just a reference, I wouldn't use too much words and explanations here. but if you have a short and descriptive caption in mind please share, then i can add it :)

2023-08-21 09:51 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
> +
What caption do you have in mind?

2023-08-21 11:09 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
I see your point! Considering your thoughts, I suggest we make a rule of thumb here! Use `bash` for **Commands** and `bash` or `JSON` for **Responses** and can have the simple text highlighter for cases where a user has to input some info into the terminal. For example, The following style guide:

<img width="1109" alt="image" src="https://github.com/LiskHQ/lisk-docs/assets/13951043/1153bd99-0db7-4aa0-ac89-66cdc1d2f6a4">

There are places where the response formatting doesn't match with the other (Example Line # 823 & 969), so I think, we can use a consistent convention throughout the page and the docs. If we agree then, I can replicate this style guide for optimizing snippets from `lisk-docs` as well, so that everything is in sync.

What do you say?

2023-08-21 11:19 UTC, TalhaMaliktz commented on modules/ROOT/pages/references/lisk-commander/sensitive-inputs.adoc
> +
I think the suggestion above regarding formatting could mitigate the need for a caption here IMHO! The only reason I suggest the addition of a caption here is that there are two snippets with the same styling and to me, something seems missing aesthetically. Different formatting can also serve the purpose.

2023-08-21 15:21 UTC, Tschakki commented on modules/ROOT/pages/client-cli.adoc
> +----
Ah ok, yes when it is for the styling, I think we can do that, bash doesn't really highlight much anyway.

Another option we could consider is to update the docs UI so that plain text code snippets have the black background as well. What do you think?

2023-08-22 05:14 UTC, TalhaMaliktz commented on modules/ROOT/pages/client-cli.adoc
> +----
Yeah! That could work as well. Will we be using a specific keyword in the markdown to indicate the use of this particular style?

2023-08-22 09:06 UTC, TalhaMaliktz approved these changes
LGTM

2023-08-22 09:16 UTC, merged