Add app endpoints to RPC API page in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1865
Opened 2023-08-17 08:18 UTC by chris529

Closes #1857

2023-08-22 13:34 UTC, ishantiw approved these changes

2023-08-22 13:37 UTC, TalhaMaliktz requested changes
Looks good already! Minor cosmetic touch-ups are required.

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +=== App
```suggestion
=== `App`
```

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Lists all endpoints in the App.
```suggestion
Lists all endpoints registered to the Lisk application.
```

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +]
Improve indentation
```suggestion
[
  "app_getRegisteredActions",
  "app_getRegisteredEvents",
  "auth_getAuthAccount",
  "auth_isValidSignature",
  "auth_isValidNonce",
  "auth_getMultiSigRegMsgSchema",
  "auth_sortMultisignatureGroup",
  "auth_getMultiSigRegMsgTag",
  "validators_validateBLSKey",
  "validators_getValidator",
  "token_getBalances",
  "token_getBalance",
  "token_getTotalSupply",
  "token_getSupportedTokens",
  "token_isSupported",
  "token_getEscrowedAmounts",
  "token_getInitializationFees",
  "token_hasUserAccount",
  "token_hasEscrowAccount",
  "fee_getFeeTokenID",
  "fee_getMinFeePerByte",
  "interoperability_getRegistrationFee",
  "interoperability_getMinimumMessageFee",
  "interoperability_isChainIDAvailable",
  "interoperability_isChainNameAvailable",
  "interoperability_getChainAccount",
  "interoperability_getAllChainAccounts",
  "interoperability_getChannel",
  "interoperability_getOwnChainAccount",
  "interoperability_getTerminatedStateAccount",
  "interoperability_getTerminatedOutboxAccount",
  "interoperability_getChainValidators",
  "pos_getStaker",
  "pos_getValidator",
  "pos_getAllValidators",
  "pos_getLockedStakedAmount",
  "pos_getConstants",
  "pos_getPendingUnlocks",
  "pos_getPoSTokenID",
  "pos_getValidatorsByStake",
  "pos_getLockedReward",
  "pos_getClaimableRewards",
  "pos_getRegistrationFee",
  "pos_getExpectedSharedRewards",
  "random_isSeedRevealValid",
  "random_setHashOnion",
  "random_getHashOnionSeeds",
  "random_hasHashOnion",
  "random_getHashOnionUsage",
  "random_setHashOnionUsage",
  "dynamicReward_getExpectedValidatorRewards",
  "dynamicReward_getDefaultRewardAtHeight",
  "dynamicReward_getRewardTokenID",
  "dynamicReward_getAnnualInflation",
  "chainConnector_load",
  "chainConnector_getSentCCUs",
  "chainConnector_getAggregateCommits",
  "chainConnector_getBlockHeaders",
  "chainConnector_getCrossChainMessages",
  "chainConnector_getLastSentCCM",
  "chainConnector_getValidatorsInfoFromPreimage",
  "chainConnector_authorize"
]
```

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +Lists all the events in the App.
```suggestion
Lists all the events registered to the Lisk application.
```

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +curl --location --request POST 'localhost:7887/rpc' \
Just to be in sync with the rest of the document!
```suggestion
curl --location --request POST 'http://localhost:7887/rpc' \
```

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +curl --location --request POST 'localhost:7887/rpc' \
```suggestion
curl --location --request POST 'http://localhost:7887/rpc' \
```

2023-08-22 13:37 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +]
```suggestion
[
  "app_ready",
  "app_shutdown"
]
```

2023-08-24 10:21 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +=== App
It seems that there is an inconsistency with the level-3 headings as some of them are wrapped in monospace whilst others aren't. Please remove monospace from all level-3 headings.

2023-08-24 14:34 UTC, chris529 commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +=== App
Done 👍

2023-08-25 06:26 UTC, TalhaMaliktz approved these changes
Thanks! LGTM 👍🏼

2023-08-25 09:02 UTC, merged