Describe new architecture - Closes #180
LiskArchive/lisk-legacy-docs pull request #187
Opened 2019-03-27 15:40 UTC by Tschakki

Closes #180

2019-04-02 07:54 UTC, nazarhussain commented
@Tschakki I am not sure to which version these changes to documentation applies to. But I would suggest to align the configuration with the changes we have here which are supposed to be released with 1.7.

https://github.com/LiskHQ/lisk/tree/feature/improve_overall_configuration

2019-04-02 07:54 UTC, nazarhussain requested changes
@Tschakki I am not sure to which version these changes to documentation applies to. But I would suggest to align the configuration with the changes we have here which are supposed to be released with 1.7.

https://github.com/LiskHQ/lisk/tree/feature/improve_overall_configuration

2019-04-10 08:01 UTC, Tschakki commented
@nazarhussain these are changes for Lisk Core 1.6 docs, see https://github.com/LiskHQ/lisk-docs/milestone/16

2019-04-12 11:10 UTC, nazarhussain commented on configuration.md
>  }
@Tschakki This section is completed change in current `development` branch. Pleas refer to this file for overview 

https://github.com/LiskHQ/lisk/blob/development/config/mainnet/config.json

and if have any question let's discuss.

2019-04-12 11:13 UTC, nazarhussain approved these changes

2019-04-12 12:32 UTC, merged