Check, Correct & Improve Hyperlinks - Closes 1867
LiskArchive/lisk-legacy-docs pull request #1870
Opened 2023-08-29 07:27 UTC by TalhaMaliktz

Closes #1867

2023-08-29 15:24 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/plugin/configuring-plugin.adoc
>  A plugin can have its own set of configurations, and as we want our plugin to sync with the on-chain data after a specific interval, a config will help.
```suggestion
A plugin is capable of having its own set of configurations, and since we aim for our plugin to sync with on-chain data at specific intervals, having a config will be beneficial.
```

2023-08-29 15:25 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
>  The database-related operations will exist in a `db.ts` file which will exist in the plugin's root folder: `hello_info`.
```suggestion
The database-related operations will exist in a `db.ts` file which will be located in the plugin's root folder: `hello_info`. 
```

2023-08-29 15:25 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/plugin/offchain-db.adoc
>  Create the new file in the said directory.
```suggestion
Create the new file in the afore mentioned directory.
```

2023-08-30 08:02 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/index.adoc
>  In addition, Lisk Service makes it possible to access all the live blockchain data like the Lisk SDK API.
```suggestion
In addition, Lisk Service makes it possible to access all the live blockchain data such as the Lisk SDK API.
```

2023-08-30 09:51 UTC, chris529 commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +For more information, see the glossary page about {url_plasma}[Plasma^].
```suggestion
For more information, see the description regarding {url_plasma}[Plasma^] in the Glossary page.
```

2023-08-30 10:06 UTC, chris529 commented on docs/modules/ROOT/pages/understand-blockchain/mainchain.adoc
>  <<table1,Table 1>> provides a comparison between the Mainnet and the Testnet mainchain, and lists their specific properties and configurations:
```suggestion
<<table1,Table 1>> provides a comparison between the Mainnet and the Testnet, and lists their specific properties and configurations:
```

2023-08-30 12:01 UTC, chris529 approved these changes
LGTM 👍 I left some suggestions

2023-08-30 12:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/intro/blockchain-scalability.adoc
> +For more information, see the glossary page about {url_plasma}[Plasma^].
```suggestion
For more information, see {url_plasma}[Plasma's^] description on the Glossary page.
```

2023-08-30 14:46 UTC, Tschakki requested changes
Looks good, just a minor comment :)

2023-08-30 14:46 UTC, Tschakki commented on docs/modules/ROOT/pages/api/lisk-node-rpc.adoc
> +:url_lisk_codec: https://lisk.com/documentation/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_codec.html
please use the dynamic site url for links to typedocs:

```suggestion
:url_lisk_codec: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_codec.html
```

2023-08-30 14:46 UTC, Tschakki commented on docs/modules/ROOT/pages/understand-blockchain/index.adoc
> +:url_references_report_misbbehavior_plugin: https://lisk.com/documentation/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_framework_report_misbehavior_plugin.html
please use dynamic site url here
```suggestion
:url_references_report_misbbehavior_plugin: {site-url}/lisk-sdk/v6/references/typedoc/modules/_liskhq_lisk_framework_report_misbehavior_plugin.html
```

2023-08-30 14:56 UTC, Tschakki approved these changes
🚀

2023-08-30 16:16 UTC, merged