Add update in how to enable a faucet for testing in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1886
Opened 2023-10-05 16:06 UTC by chris529

Closes #1529

2023-10-10 08:45 UTC, ishantiw requested changes
Looks good, a few minor points

2023-10-10 08:45 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +This account was created using the same passhrase.
we can remove this line as we already talk about it in the example below L64
```suggestion
```

2023-10-10 08:45 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +Choose a simple password to encrypt the `PrivateKey` symmetrically.
```suggestion
Choose a simple password to encrypt the `privateKey` symmetrically.
```

2023-10-10 08:45 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +    },
This section can go after 160-173, so the sequence could be,
- All properties that can be configured
- Defaults
- Mandatory properties

2023-10-11 10:23 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +    },
Done as discussed 👍

2023-10-12 14:31 UTC, ishantiw requested changes
Looks good, couple of minor comments

2023-10-12 14:31 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +<2> `host`: Host of the Faucet plugin.
To be more precise
```suggestion
<2> `host`: Host address of the Faucet plugin.
```

2023-10-12 14:31 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +        "encryptedPrivateKey": "iterations=1000000&cipherText=643bfbf1b6f1dc0ce740dd9fc9f27a682e476dc5de4e6c023deded4d3efe2822346226541106b42638db5ba46e0ae0a338cb78fb40bce67fdec7abbca68e20624fa6b0d7&
need to update it based on new encrypt function
```suggestion
        "encryptedPrivateKey": "kdf=argon2id&cipher=aes-128-gcm&version=1&ciphertext=f4fdbc925fc8a30da86935e7d51d363623a9e3c5c2f865de73bd7ca24d9edf47f7849be1764f7cc9dfb797ecb72673ff81cb4371ff1a4261b2a5f7919a823249a8b933409c9a1723dfc66eba9ffba6e2374b3ed334acb582c7b12e11e9e87c44bf3154a4e83e55e39dde4a8d821f9078b709dfc80dd21aa58b3edd86894792fa&mac=d076e5d64f232f01a320cddf32325decd0a670f924e97378182d2331c932429b&salt=3e911dd3ef883677&iv=4952b61723622bdf86d9db8f6760f94c&tag=c5632106794c16b5625500a571272f41&iterations=1&parallelism=4&memorySize=2097023",
```

2023-10-13 08:36 UTC, ishantiw approved these changes

2023-10-13 08:42 UTC, TalhaMaliktz requested changes

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> -= How to enable a faucet for testing
Please update the link to this page in the `nav.adoc` file as well.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +For example, use one of the genesis validators for the faucet account, e.g., the first account in `dev-validators.json` which was generated during xref:{url_guide_genesisblock}[].
I think this needs to be corrected. 

A genesis block is created when a client is initialized. Along with the Genesis block, all the accounts for the devnet are created. These accounts are for testing purposes only and later on, different accounts can be created with different/same passphrases using the `keys:create` command. A user can generate new passphrases using the `lisk console` and can then use these passphrases to generate as many accounts as they wish. 

The guide you mention above is for the case where you manually create a Genesis block. I would skip this reference, here, or would reference to any dev-validators.json file in the `lisk-sdk-examples` repository.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +		},
Please correct the indentation!

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +lisk message:encrypt "d0b159fe5a7cc3d5f4b39a97621b514bc55b0a0f1aca8adeed2dd1899d93f103a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0" --pretty
What value are we passing here? If it is a passphrase then the example should be aligned accordingly.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  Open the config file of the sidechain client and scroll down to the bottom of the file.
```suggestion
Open the config file of the blockchain client and scroll down to the bottom of the file.
```

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +<12> `logoURL?`: Web address for any custom logo.
Since we don't use callouts any more, I would rather have this information as part of a table.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>      }
Starting the client won't work since you didn't use the `--overwrite-config` flag.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>          "captchaSitekey": "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
**Line 221**
Please remove callout

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>          "captchaSecretkey": "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe",
**Line 242-257**
The snippet is outdated.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>      "faucet": {
**Line 198**
The section `== Enable the Faucet plugin` should also have info about enabling the faucet plugin using the `--enable-faucet-plugin` flag. You can replicate the structure of this section to match this:
https://lisk.com/documentation/beta/build-blockchain/using-dashboard.html#starting-the-node


@ishantiw please confirm the existence of the aforementioned flag! I couldn't find it in the SDK repo.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> + {
There is no `captchaSecret` in the [plugin's config schema](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework-plugins/lisk-framework-faucet-plugin/src/plugin/schemas.ts#L15C15-L15C15). Please remove that.

@ishantiw Please confirm the aforementioned.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
**Line 88**
I don't think that we are passing the `passphrase` in the following example, in fact, it is the `privateKey` of the account.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +		{
This example should match the snippet mentioned on **line 93**. It seems like you have mentioned a different account here and are using a different account's `privateKey` later on in the `message:encrypt` example.

2023-10-13 08:42 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +The xref:{url_plugin_faucet}[Faucet plugin] provides a user interface in the browser to receive a certain amount of tokens on request.
The link to the Faucet Plugin is outdated. Please link it to the typedoc

2023-10-19 08:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> + {
there is `captchaSecretkey`

2023-10-19 08:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>      "faucet": {
`--enable-faucet-plugin` flag exists and is used to enable the plugin

2023-10-19 08:50 UTC, ishantiw commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>      }
@TalhaMaliktz You don't always have to use `--overwrite-config`, its to overwrite existing config, if you are running it for the first time then you don't need it

2023-10-19 09:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>      }
@ishantiw That is true, however, I think most of the time it will be the existing client that enables a plugin, hence the flag.

2023-10-19 15:12 UTC, TalhaMaliktz requested changes

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> += How to enable a Faucet for testing
Please correct the following:
<img width="1210" alt="image" src="https://github.com/LiskHQ/lisk-docs/assets/13951043/6f7eb171-3d20-4e17-9163-929b35b5ea20">

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +|`logoURL?`| Web address for any custom logo
```suggestion
|`logoURL`| Web address for any custom logo
```

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +// `captchaSecretkey`: The secret API key for the CAPTCHA.
```suggestion
```

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  }
There is no need for these anymore, the information should be merged with the table below where another column: `Type` should be added and all the datatypes should be mentioned there.

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
Line 168
`[source,typescript]`

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +// +
Commenting out these lines results in this:
https://liskhq.github.io/lisk-docs/beta/run-blockchain/reward-sharing.html

Please correct that.

2023-10-19 15:12 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +// =====
Why have we commented out these lines?

2023-10-19 15:18 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +[types.ts]
```suggestion
[source,typescript]
```

2023-10-19 15:19 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +2023-07-28T08:42:18.189Z INFO XYZ.local application 92756 dashboard Loading in-memory plugin
Please add the correct log message
```suggestion
2023-07-28T08:42:18.189Z INFO XYZ.local application 92756 dashboard Loading in-memory plugin
```

2023-10-19 15:41 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  }
Good point, now done 👍

2023-10-23 14:15 UTC, TalhaMaliktz requested changes
Looking good already!

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +.hello_client/package.json
```suggestion
.package.json
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  Now open `plugins.ts`, import the Faucet plugin, and register it with the application as shown below:
```suggestion
Now open the `plugins.ts` file of the blockchain client, import the Faucet plugin, and register it with the application as shown below:
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +
```suggestion

After updating the *custom_config.json* file, build the blockchain client again:

[source,bash]
----
npm run build
----

```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +NOTE: Multiple accounts can be created using the same passphrase, and can be differentiated with the `keyPath`.
This sentence doesn't add any value in my opinion, I would either improve it by adding a context according to this page or completely remove this.

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +		},
```suggestion
	},
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  Save the password securely as it will be required to enable and disable the faucet later.
```suggestion
Use Lisk Commander to encrypt the `privateKey` of the account with a `password`.
Save the `password` securely as it will be required to enable and disable the faucet later.
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  .~/.lisk/lns/config/default/config.json
```suggestion
.config.json
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
LINE 198
Start the blockchain client again:

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +.Change this to the password used above to encrypt the passphrase in the Faucet plugin configuration.
```suggestion
.Change the following value of the password to the one used above to encrypt the passphrase in the Faucet plugin configuration.
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +It is also possible to enable the Faucet plugin without updating the `plugins.ts` file as suggested in the aforementioned steps described above in the <<plugin>> description.
```suggestion
It is also possible to enable the Faucet plugin without updating the `plugins.ts` file as suggested in the <<plugin, plugin registration text>> described above.
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +Once the plugin is installed, you can add the `--enable-faucet-plugin` flag to the `start` command to run the node.
```suggestion
Once the plugin is installed and configured as described in the <<configuration>> section, you can add the `--enable-faucet-plugin` flag to the `start` command to run the node.
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +./bin/run start --config=config/custom_config.json --enable-faucet-plugin
```suggestion
./bin/run start --config=config/custom_config.json
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +Now it is possible to access the Faucet plugin on the browser under `localhost: 4004`
```suggestion
Now it is possible to access the Faucet plugin on the browser under {url_faucet}[^].
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  It is now possible to use the faucet under {url_faucet} .
```suggestion
It is now possible to use the faucet under {url_faucet}[^].
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
>  Go to {url_dashboard} to access the dashboard.
```suggestion
Go to {url_dashboard}[^] to access the dashboard.
```

2023-10-23 14:15 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +The following values, including their descriptions listed in the table below can be configured if required:
```suggestion
The following values, including their descriptions listed in the table below, can be configured if required:
```

2023-10-23 14:25 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
Done 👍

2023-10-23 14:30 UTC, chris529 commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +NOTE: Multiple accounts can be created using the same passphrase, and can be differentiated with the `keyPath`.
Yes, fair point 👍

2023-10-23 14:40 UTC, TalhaMaliktz approved these changes
Just a minor correction, rest LGTM!

2023-10-23 14:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/enable-faucet.adoc
> +The password will be required later to enable the faucet plugin through the action `faucet_authorize`.
```suggestion
The password will be required later to enable the faucet plugin through the `faucet_authorize` endpoint.
```

2023-10-23 14:56 UTC, ishantiw approved these changes

2023-10-24 09:04 UTC, merged