Update sidechain registration guide
LiskArchive/lisk-legacy-docs pull request #1890
Opened 2023-10-16 10:03 UTC by Tschakki

Close #1889 

Code examples are based on interop example scripts, including the following changes: https://github.com/LiskHQ/lisk-sdk/pull/9109

Preview: https://liskhq.github.io/lisk-docs/beta/build-blockchain/register-sidechain.html

2023-10-20 14:33 UTC, sitetester requested changes

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	// Get node info data from sidechain and mainchain
Can ignore `data`, since `info` means the same thing

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	};
To avoid performing a `.map` on line 599, can do like this 
```
const mainchainValidators = mainchainValidators: (mainchainActiveValidators as { blsKey: string; bftWeight: string }[])
 			.map(v => ({ 
    blsKey: Buffer.from(v.blsKey, 'hex'), 
    bftWeight: BigInt(v.bftWeight) 
}));

const paramsJSON = {
 		ownChainID: sidechainNodeInfo.chainID,
 		ownName: sc.replace(/-/g, '_'),
 		mainchainValidators: mainchainValidators.sort((a, b) => a.blsKey.compare(b.blsKey)), 
 		mainchainCertificateThreshold,
 	};
```

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +		})),
Ater above change
```
mainchainValidators: paramsJSON.mainchainValidators
```

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +for (const validator of activeValidatorsWithPrivateKey) {
```suggestion
for (const blsPublicPrivateKey of blsPublicPrivateKeys) {
```
After above change

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    );
```suggestion
for (const activeValidator of sidechainActiveValidators as { blsKey: string; bftWeight: string }[]) {
    const sidechainDevValidator = sidechainDevValidators.find(
        devValidator => devValidator.plain.blsKey === v.blsKey,
    );
```
Can use proper names

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +const activeValidatorsWithPrivateKey: { blsPublicKey: Buffer; blsPrivateKey: Buffer }[] = [];
```suggestion
const blsPublicPrivateKeys: { blsPublicKey: Buffer; blsPrivateKey: Buffer }[] = [];
```
Can rename to `blsPublicPrivateKeys`, since it's merely a collection of keys

2023-10-20 14:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    module: 'interoperability',
```suggestion
    module: MODULE_NAME_INTEROPERABILITY,
```
For compatibility with `register_mainchain` script

2023-10-23 08:26 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    module: 'interoperability',
Imho, for better readability, this should be changed to `'interoperability'` in `register_mainchain.ts`, in case we want to align it?

2023-10-23 08:26 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	// Get node info data from sidechain and mainchain
```suggestion
	// Get node info from sidechain and mainchain
```

2023-10-23 08:40 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	};
In that case, it looks like the paramsJSON wouldn't have the expected schema anymore, which we need for the `mainchainRegParams`

2023-10-23 08:44 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +const activeValidatorsWithPrivateKey: { blsPublicKey: Buffer; blsPrivateKey: Buffer }[] = [];
Renamed it to `activeValidatorsBLSKeys`

2023-10-23 08:44 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    );
what is the difference here?

2023-10-23 09:04 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +		})),
see my comment above

2023-10-23 09:06 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +for (const validator of activeValidatorsWithPrivateKey) {
imho `validator` is more descriptive here

2023-10-23 12:54 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +    );
Updated

2023-10-23 12:58 UTC, sitetester approved these changes

2023-10-24 10:06 UTC, TalhaMaliktz requested changes
Please consider the following!

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  .How to calculate minimum and maximum certificate thresholds for sidechain validators
LINE 261
The `datapath` should match any one of the two sidechain aliases described above, not `hello_client`.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +* the <<mainchaincertificatethreshold>>
```suggestion
* The <<sidechaincertificatethreshold>> and
* The <<mainchaincertificatethreshold>>
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  If the node accepted the transaction, it will respond with the transaction ID.
```suggestion
The node will respond with the transaction ID if it accepts the transaction.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  === Check the sidechain account
The ChainID should match with the chain ID of either sidechain.
**Line 337 & 352**
`lisk-core endpoint:invoke interoperability_getChainData '{"chainID": "04000001"}'`

Please also update the chain IDs mentioned in all the subsequent examples accordingly.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
**LINE 375**
The name should match with either sidechain.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  Send the `registerSidechain` transaction to a node that is connected to the mainchain.
```suggestion
Send the `registerMainchain` transaction to a node that is connected to the mainchain.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  If the node accepted the transaction, it will respond with the transaction ID.
```suggestion
The node will respond with the transaction ID if it accepts the transaction.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  Once the "Register Mainchain" command is processed, the mainchain account is initialized and its `status` is set to `registered`.
Please match the mainchain ChainID with the interop example, in all the subsequent snippets.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +====
Should be moved to **line 1446** IMHO.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  // Footnotes
**Line 55**
Register a blockchain as **a** sidechain on the mainchain

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +// Replace this with the path to a file storing the public and private key of a mainchain account who will send the sidechain registration transaction.
```suggestion
// Replace this with the path to a file storing the public and private keys of a mainchain account that will send the sidechain registration transaction.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	// Replace this with alias of the sidechain node(s)
```suggestion
	// Replace this with the alias of the sidechain node(s)
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +	// Note: Number of mainchain nodes should be equal to sidechain nodes, for this script to work properly.
```suggestion
	// Note: The number of mainchain nodes should be equal to sidechain nodes, for this script to work properly.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Next, get the basic node information from mainchain and sidechain node.
```suggestion
Next, get the basic node information from the mainchain and sidechain nodes.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +* `CHAIN_ID` (Sidechain): The chain ID of the sidechain as parameter of the transaction.
```suggestion
* `CHAIN_ID` (Sidechain): The chain ID of the sidechain is required as a parameter of the transaction.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Create the Register Sidechain transaction using the prepared parameters, and sign it with a mainchain account, that has enough funds to send pay the required transaction fees.
```suggestion
Create the Register Sidechain transaction using the prepared parameters, and sign it with a mainchain account, that has enough funds to send the transaction and pay the required transaction fees.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +To check if a certain chain ID is still available in the network, call RPC endpoint xref:{url_api_mainchain_endpoints_chainid}[interoperability_isChainIDAvailable] with the chain ID as parameter.
```suggestion
To check if a certain chain ID is still available in the network, call RPC endpoint xref:{url_api_mainchain_endpoints_chainid}[interoperability_isChainIDAvailable] with the chain ID as a parameter.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  * It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise the sidechain interoperable functionality may be
```suggestion
* It is of key importance that the sidechain validators ensure that they are signing the registration command with the correct information, otherwise, the sidechain interoperable functionality may be unusable.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  ==== ownChainID
LINE 620
`Should be identical to the <<name>>.`

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  By signing the mainchain registration message, they verify the correctness of the following values: `ownChainID`, `ownChainName`, `mainchainCertificateThreshold` and `mainchainValidators`.
```suggestion
By signing the mainchain registration message, they verify the correctness of the following values: `ownChainID`, `ownChainName`, `mainchainCertificateThreshold`, and `mainchainValidators`.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +// Sort active validators from sidechain lexicographically after their BLS public key
```suggestion
// Sort active validators from the sidechain lexicographically after their BLS public key
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  The validator signatures need to be collected by the person intending to send the Register Mainchain transaction.
LINE 699
`Once the aggregated BFT weight of the validators who signed is equal to or above the <<sidechaincertificatethreshold>>, enough validators have signed the registration parameters.`

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +When enough validators added their signatures, the list of signatures is aggregated into one single signature, which is then appended to the registration params that we created in step <<preparing-th
```suggestion
When enough validators add their signatures, the list of signatures is aggregated into one single signature, which is then appended to the registration params that we created in step <<preparing-the-register-mainchain-parameters>>.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  === Check the mainchain account
**Line 786**
If you maintain your own instance of a sidechain node, it is possible to invoke endpoints directly via the node CLI:

**Line 839**
If you maintain your own instance of a sidechain node, it is possible to invoke endpoints directly via the node CLI:


**Line 896**
If you maintain an own instance of a sidechain node, it is possible to invoke endpoints directly via the node CLI:

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
**LINE 1265**
xref:{url_run_index_relayer}[Relayer nodes] are required to send cross-chain messages from the sidechain to the mainchain and vice-versa.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
**LINE 1277**
The data can be provided as a pull request to the repository, which adds a new folder under the respective network with the following structure:

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  To be able to pay the CCM transaction fees, it is necessary to move a sufficient amount of LSK tokens from mainchain to sidechain via a cross-chain transfer transaction.
```suggestion
To be able to pay the CCM transaction fees, it is necessary to move a sufficient amount of LSK tokens from the mainchain to the sidechain via a cross-chain transfer transaction.
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  Create the following transaction with your mainchain node:
**LINE 1271**
Please check the guide xref:{url_run_relayer}[] for a step-by-step explanation of how to turn a node into a relayer.

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Only a CCM from sidechain to mainchain will enable the xref:{url_sidechain_reg_recovery_liveness}[liveness condition].
```suggestion
NOTE: Sending CCMs from the mainchain to the sidechain does not <<activate-the-sidechain>>, yet.
Only a CCM from the sidechain to the mainchain will enable the xref:{url_sidechain_reg_recovery_liveness}[liveness condition].
```

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
**LINE 1456**
`* Once the sidechain is *active*, it needs to fulfill the xref:{url_sidechain_reg_recovery_liveness}[liveness condition], otherwise, it will be *terminated*.`

2023-10-24 10:06 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
**LINE 1459**
Once the first CCU is sent successfully from the sidechain to the mainchain, the sidechain is activated and is interoperable with the mainchain and other sidechains within the Lisk ecosystem.

2023-10-24 11:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +When enough validators added their signatures, the list of signatures is aggregated into one single signature, which is then appended to the registration params that we created in step <<preparing-th
```suggestion
Once enough validators added their signatures, the list of signatures is aggregated into one single signature, which is then appended to the registration params that we created in step <<preparing-the-register-mainchain-parameters>>.
```

2023-10-24 12:02 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
>  .How to calculate minimum and maximum certificate thresholds for sidechain validators
For using the script with their sidechain, they need to update the data-path manually in the script anyway, imho there is no need to update it. The script is also not part of the interop example.

2023-10-24 13:38 UTC, TalhaMaliktz approved these changes
Just a minor comment, rest LGTM 🚀

2023-10-24 13:38 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/register-sidechain.adoc
> +Once enough validators added their signatures, the list of signatures is aggregated into one single signature, which is then appended to the registration params that we created in step <<preparing-th
```suggestion
Once enough validators add their signatures, the list of signatures is aggregated into one single signature, which is then appended to the registration params that we created in step <<preparing-the-register-mainchain-parameters>>.
```

2023-10-24 15:30 UTC, merged