Bump Core version to 3.1.0 (v2)
LiskArchive/lisk-legacy-docs pull request #1899
Opened 2023-10-17 15:12 UTC by chris529

Closes #1884

2023-10-17 16:36 UTC, sameersubudhi approved these changes
LGTM 👍

2023-10-18 15:02 UTC, TalhaMaliktz requested changes

2023-10-18 15:02 UTC, TalhaMaliktz commented on modules/ROOT/pages/setup/source.adoc
> +git checkout v3.1.0 -b v3.1.0                     #<3>
Why are we using `-b v3.1.0`? I think this is wrong as it will create a new branch. 
```suggestion
git checkout v3.1.0                      #<3>
```

2023-10-18 15:20 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +git checkout v3.1.0 -b v3.1.0                     #<3>
Yes. good point Talha 👍

2023-10-18 15:25 UTC, TalhaMaliktz approved these changes
LGTM

2023-10-19 08:08 UTC, merged