How to enable reward sharing guide - Closes 1796
LiskArchive/lisk-legacy-docs pull request #1901
Opened 2023-10-19 14:15 UTC by TalhaMaliktz

Closes #1796

2023-10-20 09:28 UTC, Tschakki requested changes

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +On this page, we'll talk about how a registered validator can enable reward sharing with its stakers and how such rewards can be later claimed.
```suggestion
On this page, we'll talk about how registered validators can enable reward sharing with their stakers and how such rewards can be later claimed.
```

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The set of validators that generate blocks is chosen based on the total stake of each validator (self-stake and sum of staked amounts from stakers).
This is already explained [here](https://lisk.com/documentation/beta/understand-blockchain/consensus/pos-poa.html#validator-weight), imho we do not need to mention this here.

```suggestion
```

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +Rewards are shared between validators and stakers as follows: a certain part of the rewards is awarded to the validator as a commission.
```suggestion
Rewards are distributed between validators and their stakers as follows: a certain part of the rewards is awarded directly to the validator as a commission.
```

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared by the validator and the stakers proportionally to their staked amounts.
```suggestion
The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared among the stakers of the validator, proportionally to their staked amounts.

NOTE: Because validators need to self-stake for their accounts to become eligible to generate blocks, validators will receive additional rewards here, like their other stakers, too. For example, consider an active validator has 0% commission, and at the same time no other accounts are staking for the validator. In this case, the validator would still receive 100% of the block rewards.
```

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +Afterward, it can be decreased by submitting a commission change transaction.
I would add a note below, explaining commission can be descreased by any value, but for increase it can only happen in steps

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After reaching the offset height, rewards for each validator are credited to their account.
This seems to be an edge case after a hardfork, I wouldn't mention it here

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `85`.
Maybe we should use a low commission as an example, maybe even 0%, as we want to incentivize validators to set low commisions

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +=====
This step could be skipped, by adding a `--send` flag to the `transaction:create` command

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
Why does it increment `lockedBalance` of the validator?

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
Does this only count for the commission, or also from the rewards that the validator receives from the self-stake?

2023-10-20 09:28 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +. xref:{url_posting_transaction}[Post the transaction] to the node for execution and once the block is executed, check your xref:{url_getbalance}[token_getBalance] endpoint.
As above, this step could be skipped, by adding a `--send` flag to the `transaction:create` command

```suggestion
. Once the transaction is executed, check your xref:{url_getbalance}[token_getBalance] endpoint.
```

2023-10-20 15:50 UTC, sameersubudhi requested changes
Please consider the following.

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +On this page, we'll talk about how a registered validator can enable reward sharing with its stakers and how such rewards can be later claimed.
```suggestion
On this page, we'll talk about how a validator can enable reward sharing with their stakers and how the shared rewards can be later claimed by the stakers.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The set of validators that generate blocks is chosen based on the total stake of each validator (self-stake and sum of staked amounts from stakers).
```suggestion
The set of validators that generate blocks, called generators, is chosen based on the total stake of each validator (self-stake and sum of staked amounts from stakers).
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +Rewards are shared between validators and stakers as follows: a certain part of the rewards is awarded to the validator as a commission.
```suggestion
Rewards are shared between the validators and the stakers as follows: a certain part of the rewards is awarded to the validator as a commission.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared by the validator and the stakers proportionally to their staked amounts.
```suggestion
The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared by the validator and the stakers in proportion to their staked amounts.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The values of all constants related to commissions are between *0* and *10000*, corresponding to percentages with two decimal places, which can be obtained by dividing the value by *100*. For example
```suggestion
The commission values can range between *0* and *10000* (both inclusive), corresponding to percentages with two decimal places, which can be obtained by dividing the value by *100*. For example, a commission value of *1000*, corresponds to a *10%* commission.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +If the validator is in the returned list then, soon your validator will be generating a block and as a result will earn rewards.
We should be specifying the `chain_getGeneratorList` endpoint for the user to query.
Also, the output of the [chain_getGeneratorList](https://liskhq.github.io/lisk-docs/beta/api/lisk-node-rpc.html#chain_getgeneratorlist) endpoints seems to be incorrect. The addresses are expected in `lsk` format.

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After reaching the offset height, rewards for each validator are credited to their account.
```suggestion
After reaching the offset height, rewards for each validator are credited to their account on generating new blocks.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The estimated rewards of a validator can be checked via the xref:{url_getexpectedvalidatorrewards}[dynamicReward_getExpectedValidatorRewards] endpoint.
```suggestion
The estimated rewards for a validator can be checked via the xref:{url_getexpectedvalidatorrewards}[dynamicReward_getExpectedValidatorRewards] endpoint.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `85`.
```suggestion
In this example, the validator is set to keep *85%* of the rewards as a commission and share the remaining *15%* with their stakers, hence the value of `85`.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `8500`.
```suggestion
In this example, the validator is set to keep *85%* of the rewards and share *15%* with their stakers, hence the value of `8500`.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +=====
I think, we should add it as a NOTE instead in the previous point. If the `--send` flag is used along with the `transaction:create` command, `transaction:send` command doesn't need to be executed.

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
> Why does it increment lockedBalance of the validator?

This is by protocol. AFAIK, the portion of rewards earned from block generation to be shared with the stakers are locked with the validator's lockedBalance and whenever the stakers claim the rewards, it's then transferred to the stakers account. The commission amount from the rewards are directly credited to the validator's available balance. And, applicable in both the cases you stated above. However, this is super simplification of the protocol and skips a lot of details 🙂 

@gkoumout could you please confirm this? Also, could you please share the scenarios where the reward distribution is triggered automatically so that we can include those information too?

AFAIK the automatic distribution happens in the following scenarios:
- ~~Validator updates commission, existing locked rewards are automatically sent to the stakers~~
- Staker updates their stake, the portion of claimable rewards against the (un-)staked validator is automatically claimed

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +. Once the transaction is executed and the block is finalized, the staker's account balance will increase as per the earned reward.
```suggestion
. Once the transaction is executed, the staker's account balance will increase as per the earned reward and the corresponding amount is reduced from the validator's locked balance.
```

2023-10-20 15:50 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +./bin/run transaction:create pos claimRewards 1000000 --json --pretty
The suggested transaction fees are quite high here. Perhaps we should specify a lower transaction fee?
Based on the testnet transaction size, I've recommended `127000`.

Ref: https://testnet-service.lisk.com/api/v3/transactions?moduleCommand=pos:claimRewards&limit=1

Also, as recommended above it's convenient to specify the `--send` flag while creating the transaction itself to eliminate an additional step.

```suggestion
lisk-core transaction:create pos claimRewards 127000 --json --pretty --send
----
--
Sidechain Node::
+
--
[source,bash]
----
./bin/run transaction:create pos claimRewards 127000 --json --pretty --send
```

2023-10-20 15:53 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +----
Same [comment](https://github.com/LiskHQ/lisk-docs/pull/1901#discussion_r1367170671) is applicable here too.

Ref: https://testnet-service.lisk.com/api/v3/transactions?moduleCommand=pos:changeCommission&limit=1

```suggestion
lisk-core transaction:create pos changeCommission 134000 --json --pretty  
----
--
Sidechain Node::
+
--
[source,bash]
----
./bin/run transaction:create pos changeCommission 134000 --json --pretty 
----
```

2023-10-24 10:26 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +If the validator is in the returned list then, soon your validator will be generating a block and as a result will earn rewards.
Alright, I have reported the bug: https://github.com/LiskHQ/lisk-docs/issues/1905

2023-10-24 14:25 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
Once @gkoumout has confirmed it, it should be added to the guide, as a note or something, imho it is useful information for stakers, that in certain situation, they will claim rewards automatically.

Concerning the locked balance, it would be nice if it is explained more in the guide how it works.

```suggestion
For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
The `availableBalance` in incremented by rewards corresponding to the commission and self-stake, the rest of the rewards belongs to validators and stakers according to their staked amount and is added to the `lockedBalance` of the validators, until the stakers claim the rewards.
```

2023-10-24 14:29 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The set of validators that generate blocks is chosen based on the total stake of each validator (self-stake and sum of staked amounts from stakers).
Don't know why this was resolved, the sentence is still there.

2023-10-24 14:31 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After reaching the offset height, rewards for each validator are credited to their account.
Sentence is still there, this should not have been resolved.

2023-10-24 14:31 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `85`.
Commission is still 85%, this should not have been resolved.

2023-10-24 14:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The set of validators that generate blocks is chosen based on the total stake of each validator (self-stake and sum of staked amounts from stakers).
The comment was resolved since another suggestion on the same line was accepted.

2023-10-24 14:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +
```suggestion
```

2023-10-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After reaching the offset height, rewards for each validator are credited to their account.
IMHO this should stay, while I was performing the steps necessary for reward sharing, It was unclear to me for sometime as to why the rewards were not being shared. I later learned that there is this `offset` value and I think, for any new node or even with hard forks, this info adds value.

2023-10-24 14:35 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `85`.
I think the value 85 serves the purpose of this guide and there is not need to change it.

2023-10-24 14:40 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After reaching the offset height, rewards for each validator are credited to their account.
I see, but imho it is still out of scope for the guide, because this guide is targeted to validators(not sidechain developers), and they generally join an existing networks, so there is no offset to consider. The only time this is to consider is after a hardfork, which is a very special case, where consequences of the `offset` can be communicated seperatly.

2023-10-24 14:40 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After reaching the offset height, rewards for each validator are credited to their account.
Fair point!

2023-10-24 14:45 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `85`.
Afaik it was communicated to change commision of our testnet validators, to incentivize users to also choose lower commissions, too. Imho it would also help if the example in the guide doesn't choose a too high commission, for this purpose. 

But I can see 85 is used in the screenshots and it is cumbersome to change it now. I would suggest to add at least a TODO, to lower the commission in the future, if new screenshots need to be created anyway.

2023-10-24 14:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *85%* of the rewards and share *15%* with their staker, hence the value of `85`.
TODO added!

2023-10-24 14:56 UTC, Tschakki approved these changes
LGTM 👍

2023-10-25 14:06 UTC, gkoumout commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
The information that Sameer gave above is correct. This logic is described [here](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0071.md#after-transactions-execution).

2023-10-25 14:21 UTC, gkoumout commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
I will add a suggestion from my side in a few minutes

2023-10-25 14:25 UTC, gkoumout commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +After each block generated by the validator, both the validator and the staker(s) will earn a set percentage of rewards.
```suggestion
After each block is generated, both the block generator and the staker(s) supporting them will earn a set percentage of rewards.

The part of rewards that is attributed to the validator that generated the block is automatically assigned to them by the Lisk Protocol. This is done by incrementing the `availableBalance` of the validator's account by the amount of rewards corresponding to the commission and self-stake.

On the other hand, stakers needs to manually claim their rewards, and that can be done via both Lisk Desktop and CLI. The part of rewards belonging to stakers gets locked in the validator's account (by increasing its `lockedBalance`) until each staker claims their rewards.
```

2023-10-25 14:30 UTC, gkoumout commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
@sameersubudhi About the case of automatic distribution it is not exactly as you described. In particular:

 - In case you (re) stake with a validator (either increase or decrease staked amount), indeed the rewards are assigned automatically to you. 
 - However, in case commission changes, nothing happens from the side of stakers.

2023-10-25 14:32 UTC, gkoumout commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
I am not sure where is the best place to write this. Perhaps at the end, since in the very beginning it might be distracting from the context.

2023-10-25 14:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
Thank you for the clarification @gkoumout 🙏 
I've updated my comment above to strikethrough the incorrect information.

2023-10-25 14:39 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +For validators, the Lisk Protocol automatically increments the `lockedBalance` and `availableBalance` of the validator's account.
I have applied the feedback from Greg which also complements Mona's suggestion. @sameersubudhi the PR is ready for your review.

2023-10-30 14:03 UTC, sameersubudhi requested changes
Looks much better than before. However, please look into the following 🙏

2023-10-30 14:03 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared among the stakers of the validator, proportionally to their staked amounts.
I think, this information is also important to share. Please feel free to rephrase the suggestion.
```suggestion
The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared among the stakers of the validator (including themselves for their self-stakes), proportionally to their staked amounts.
```

2023-10-30 14:03 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +NOTE: Validators need to self-stake for their accounts to become eligible to generate blocks.
Also, it might be a good idea to add a hyperlink to the `enable generation` documentation.
```suggestion
NOTE: Validators need to self-stake for their accounts and enable generation to become eligible to generate blocks.
```

2023-10-30 14:03 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The validator has to then wait for the next commission increase period. For more information, see {url_constraints-on-commission-increase}[Constraints on Commission Increase^].
It'd be nice to explicitly state that the validator can reduce the commission by any amount and at any frequency. The commission increase, however, is restricted to a maximum of 5% and cannot be increased again (but decreased) until after the commission increase period, viz. approx. 28 days.

Please double check this with @gkoumout 🙏

2023-10-30 14:03 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The part of rewards belonging to stakers, gets locked in the validator's account (by increasing its `lockedBalance`) until each staker claims their rewards.
```suggestion
The part of rewards belonging to stakers, gets locked in the validator's account, by the PoS module, (by increasing its `lockedBalance`) until each staker claims their rewards.
```

2023-10-30 14:03 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +. Any `reward` higher than `0` can be claimed by the staker by executing the `claimRewards` command.
Could you please confirm with @gkoumout if this is `0` or if there's a lower threshold?

2023-10-30 14:49 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The precise percentage of the commission is chosen by each validator; then, the remaining rewards are shared among the stakers of the validator, proportionally to their staked amounts.
```suggestion
Each validator chooses the precise percentage of the commission; then, the remaining rewards are shared among the stakers of the validator. Since a validator also self-stakes, they earn rewards along with other stakers, proportionally to their staked amounts.
```

2023-10-31 12:02 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +The validator has to then wait for the next commission increase period. For more information, see {url_constraints-on-commission-increase}[Constraints on Commission Increase^].
```suggestion
NOTE: A validator’s commission can be decreased at any time, by any value, however, the commission can only be increased by 5% in a single change commission transaction.
The validator has to wait for 28 days until they can increase the commission again.
For more information, see {url_constraints-on-commission-increase}[Constraints on Commission Increase^].
```

2023-10-31 12:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +. Any `reward` higher than `0` can be claimed by the staker by executing the `claimRewards` command.
```suggestion
. Any `reward` can be claimed by the staker by executing the `claimRewards` command.
```

2023-10-31 12:26 UTC, sameersubudhi approved these changes
LGTM 👍

2023-10-31 12:26 UTC, sameersubudhi commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +Each validator chooses the precise percentage of the commission; then, the remaining rewards are shared among the stakers of the validator. Since a validator also self-stakes, they earn rewards along
```suggestion
Each validator chooses the precise percentage of the commission; then, the remaining rewards are shared among the stakers of the validator. Since a validator also self-stakes, they earn rewards along with other stakers, in proportion to their staked amounts.
```

2023-10-31 12:27 UTC, merged