Add interoperable module guide
LiskArchive/lisk-legacy-docs pull request #1903
Opened 2023-10-23 14:52 UTC by Tschakki

Closes #1678

2023-10-30 15:42 UTC, sitetester requested changes

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +	public crossChainMethod = new HelloInteroperableMethod(this.stores, this.events);
```suggestion
       // Assign HelloInteroperableMethod to crossChainMethod
	public crossChainMethod = new HelloInteroperableMethod(this.stores, this.events);
```

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +}
```suggestion
       // Create a private member to store the methods of the interoperability module
	private _interoperabilityMethod!: InteroperabilityMethod;

	// ...

       // Assign the methods of the interoperability module to _interoperabilityMethod
	public addDependencies(interoperabilityMethod: InteroperabilityMethod) {
		this._interoperabilityMethod = interoperabilityMethod;
	}

	// Lifecycle hooks
	// eslint-disable-next-line @typescript-eslint/require-await
	public async init(_args: ModuleInitArgs) {
              // Pass the methods of the interoperability module to the reactCrossChain command
		this.commands[0].init({
			interoperabilityMethod: this._interoperabilityMethod,
		});
	}
}
```

<img width="810" alt="Screenshot 2023-10-30 at 04 56 07 PM" src="https://github.com/LiskHQ/lisk-docs/assets/1403133/6fd474d0-4700-4721-9c25-301135414129">

- Let's align the comments with code 
- Also please check other places

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +	reactModule.addDependencies(method.interoperability);
- First we register module with app & then add dependencies ? 
- Can rearrange these lines ?

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +	app.registerModule(reactModule);
```suggestion
export const getApplication = (config: PartialApplicationConfig): Application => {
    const { app, method } = Application.defaultApplication(config);
    const reactModule = new ReactModule();
    app.registerModule(reactModule);
    ...
```

<img width="775" alt="Screenshot 2023-10-30 at 05 04 12 PM" src="https://github.com/LiskHQ/lisk-docs/assets/1403133/440fe912-9ff3-4823-8ba1-9aace9b8364e">

This code seems to have 8 spaces indent from left. I suggest to make it 4 spaces only. 
Expected example: 
<img width="737" alt="Screenshot 2023-10-30 at 05 06 17 PM" src="https://github.com/LiskHQ/lisk-docs/assets/1403133/2d82418e-6115-412b-a852-1cb262147a46">

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +	public method = new HelloMethod(this.stores, this.events);
```suggestion
       public endpoint = new HelloEndpoint(this.stores, this.offchainStores);
	public method = new HelloMethod(this.stores, this.events);
```
Mismatched alignment

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +}
- It's a type, not a schema, so should be in `types.ts` file
- Are the comments auto generated ? Alignment issue.
- Some comments are single line, others - multi-line. Can chose one ?

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +        throw new Error('Invalid CCM status code.');
```suggestion
        throw new Error(`Invalid CCM status code. Must be <= ${MAX_RESERVED_ERROR_STATUS}.`);
```

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		const { ccm, logger } = ctx;
Class body is too much right aligned. Please adjust alignment.

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		// Decode the provided CCM parameters
Can remove commented code

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		}
`logger.info` & `logger.error` ?  
Since there is `throw error;` on next line, so can just choose one.

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		if (reactionType === 0) {
For easier understanding, It's better we make comparison against an Enum type, since comparison against an integer will make it difficult to understand what `0` stands for ?

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export class ReactModule extends BaseInteroperableModule {
Same alignment issues in class body (as mentioned before)

2023-10-30 15:42 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +	reactModule.addDependencies(method.interoperability);
> First we register module with app & then add dependencies ?
Can rearrange these lines ?

Same as above

2023-11-02 13:19 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export class ReactModule extends BaseInteroperableModule {
Replaced all tabs with spaces now, it should have fixed all indentation issues

2023-11-02 13:21 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +	reactModule.addDependencies(method.interoperability);
This should first be fixed in the script that this guide is based on.

2023-11-02 13:22 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		if (reactionType === 0) {
this is something that should be updated in the corresponding script first.

2023-11-02 13:25 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		}
This should be updated in the corresponding script first.

2023-11-03 07:46 UTC, TalhaMaliktz requested changes
Please consider the following.

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +NOTE: To learn more about the wat how sidechain communicate to each other via CCM, check out the page about xref:{url_understand_interopcommunication}[].
```suggestion
NOTE: To learn more about how sidechains communicate with each other via CCM, check out the page about xref:{url_understand_interopcommunication}[].
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +The example can be extended to include more reaction types, like dislikes or replies for Hello messages, if desired.
```suggestion
The example can be extended to include more reaction types such as likes, dislikes, or replies for Hello messages if desired.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +If two sidechain intend to interact with each other, for example, if a sidechain A wishes to utilize services that a sidechain B provides, this can be achieved via *interoperable modules*.
```suggestion
If two sidechains intend to interact with each other, for example, if sidechain A wishes to utilize services that sidechain B provides, this can be achieved via *interoperable modules*.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. *Both* the sending-, and the receiving chain need to be *registered as sidechains* to the same mainchain.
```suggestion
. *Both* the sending and the receiving chains need to be *registered as sidechains* to the same mainchain.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. *Both* the sending-, and the receiving chain need to be *active sidechains*, with at least one relayer node connected to the mainchain.
```suggestion
. *Both* the sending and the receiving chains need to be *active sidechains*, with at least one relayer node connected to the mainchain.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. The *receiving chain* needs to implement a module cc_command that is *accepting* and *executing the CCM*.
```suggestion
. The *sending chain* needs to implement a module command that *creates* and *sends a CCM*.
. The *receiving chain* needs to implement a module cc_command that *accepts* and *executes the CCM*.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +To try out the cross-chain communication of interoperable modules locally, go the {url_github_sdk_interop}[interop/example] in the `lisk-sdk` repository.
```suggestion
To try out the cross-chain communication of interoperable modules locally, go to the {url_github_sdk_interop}[interop/example^] in the `lisk-sdk` repository.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Here, you find a `README.md` which is describing all required steps to set up a simple interoperability example, as illustrated in _Figure 1_.
```suggestion
There, you find a `README.md` which describes all the required steps to set up a simple interoperability example, as illustrated in _Figure 1_.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Additionally, you find examples how to execute cross-chaon token transfers between the chains.
```suggestion
Additionally, you find examples of how to execute cross-chain token transfers between the chains.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Follow the instructions until {url_github_sdk_interop_cctransfer}[here^], where you successfully sent tokens from the mainchain to both sidechains.
```suggestion
Follow the instructions until {url_github_sdk_interop_cctransfer}[Transfer from mainchain to sidechain one^] step, where you successfully send tokens from the mainchain to both sidechains.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +The account sending the `reactCrossChain` command, whichwill create a new CCM needs to provide the fees for the execution of the CCM in tokens that are native on the mainchain.
```suggestion
The account sending the `reactCrossChain` command, which will create a new CCM needs to provide the fees for the execution of the CCM in tokens that are native on the mainchain.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +If you followed the instructions in the `README.md` until {url_github_sdk_interop_cctransfer}[here^], the account `lskx5uqu2zzybdwrqswd8c6b5v5aj77yytn4k6mv6` of `pos-sidechain-exmaple-two` should hav
```suggestion
This is why it should be verified, that the account that intends to send the transaction owns enough mainchain tokens.
If you followed the instructions in the `README.md` until the {url_github_sdk_interop_cctransfer}[Transfer from mainchain to sidechain two^] step, the account `lskx5uqu2zzybdwrqswd8c6b5v5aj77yytn4k6mv6` of `pos-sidechain-exmaple-two` should have the required funding.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
```suggestion
.pos-sidechain-example-two
[source,bash]
----
./bin/run endpoint:invoke token_getBalances '{"address":"lskx5uqu2zzybdwrqswd8c6b5v5aj77yytn4k6mv6"}' --pretty
----
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +As the response shows, the account has more than enough sidechain and mainnet tokens to pay the required fees.
Just for the sake of synchronicity with the page
```suggestion
As the response shows, the account has more than enough sidechain and mainchain tokens to pay the required fees.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
```suggestion
.pos-sidechain-example-one
[source,bash]
----
./bin/run transaction:create hello createHello 10000000 --json --pretty --key-derivation-path="m/44'/134'/12'" --send
----
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +[source,json]
```suggestion

.Response
[source,json]
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
```suggestion

.pos-sidechain-example-one
[source,bash]
----
./bin/run endpoint:invoke hello_getHello '{"address":"lskmjwp8z88avvxn4voktmx8cu9wk4opjkna5owt5"}'
----
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +[source,json]
```suggestion
.Response
[source,json]
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
Please use separate code blocks with captions for each.

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +* http://localhost:4007[^]
Is this a URL of the dashboard on sidechain 2?

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
Please add appropriate caption for this code block.

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
Please add an appropriate caption for this code block.

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
```suggestion
.pos-sidechain-example-two
[source,bash]
----
./bin/run endpoint:invoke chainConnector_getLastSentCCM --pretty --data-path=/Users/mona/.lisk/mainchain-node-one
----
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +----
Please use individual code blocks with appropriate caption for each code block.

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +=== Create Hello message on sidechain 1
```suggestion
=== Create a Hello message on sidechain 1
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +=== Observe execution of the CCM
```suggestion
=== Observe the execution of the CCM
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +To achieve cross-chain communication, the two sidechains need to fulfil the following requirements:
```suggestion
To achieve cross-chain communication, the two sidechains need to fulfill the following requirements:
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +As interaction between two sidechains always involves three chain (sending chain, receiving chain, and mainchain), it is quite complicated to test newly implemented interoperable modules locally.
```suggestion
As the interaction between two sidechains always involves three chains (sending chain, receiving chain, and mainchain), it is quite complicated to test newly implemented interoperable modules locally.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Now, to test the newly implemented interoperable modules, all is prepared to proceed an test the React cross chain command.
```suggestion
Now, to test the newly implemented interoperable modules, the setup is ready to proceed with the testing of the **React cross-chain command**.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +TIP: The {url_github_sdk_interop}[interop example^] fulfils already all requirements after setup, if you simply want to try it out, refer to the next section <<testing-interoperable-modules>>.
```suggestion
TIP: The {url_github_sdk_interop}[interop example^] contains a complete interoperable set up for you to try out. If you simply want to try it out, refer to the next section <<testing-interoperable-modules>>.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Now import the `ReactInteroperableMethod` and use it to create a new member `crossChainMethod` inside the module.
```suggestion
Now import the `ReactInteroperableMethod` and use it to create a new method called `crossChainMethod` inside the module.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +In this example, we will only implement type `0`, which is representing a like.
```suggestion
In this example, we will only implement type integer and will have a value such as `0`, which represents a like.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.Additional parameters for the reactCrossChain command
```suggestion
Additional parameters for the `reactCrossChain` command are:
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Export the types and interfaces as shown int he example below:
```suggestion
Export the types and interfaces as shown in the example below:
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Update the methods to expect the `interoperabilityMethod` as argument, and assign is to the private property `_interoperabilityMethod` of the `reactCrossChain` command.
```suggestion
Update the methods to expect the `interoperabilityMethod` as an argument, and assign it to the private property `_interoperabilityMethod` of the `reactCrossChain` command.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +In the `react_command.ts` file, and implement the command verification.
```suggestion
In the `react_command.ts` file, implement the command verification.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +To keep the example simple, we only check if the `receivingChainID` parameter doesn't equal the value of the sending chain.
```suggestion
To keep the example simple, we only check if the `receivingChainID` parameter isn't equal to the value of the sending chain.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Extend the `verify()` hook to include more checks for the other parameters as well, as desired.
```suggestion
As desired, extend the `verify()` hook to include more checks for the other parameters as well.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +    }
```suggestion
    const { params, logger } = context;

    logger.info('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++');
    logger.info(params);
    logger.info('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++');

    try {
        if (params.receivingChainID.equals(context.chainID)) {
            throw new Error('Receiving chain cannot be the sending chain.');
        }
    } catch (err) {
        return {
            status: VerifyStatus.FAIL,
            error: err as Error,
        };
    }
    return {
        status: VerifyStatus.OK,
    };
}
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +    }
```suggestion
    const {
        params,
        transaction: { senderAddress },
    } = context;

    const reactCCM: CCReactMessageParams = {
        reactionType: params.reactionType,
        data: params.data,
        helloMessageID: params.helloMessageID,
    };

    await this._interoperabilityMethod.send(
        context.getMethodContext(),
        senderAddress,
        'hello',
        CROSS_CHAIN_COMMAND_NAME_REACT,
        params.receivingChainID,
        params.messageFee,
        codec.encode(crossChainReactMessageSchema, reactCCM),
        context.header.timestamp,
    );
}
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Because the `ReactModule` is an *interoperable module*, it is required to call `app.registerInteroperableModule()` additionally.
```suggestion
As the `ReactModule` is an *interoperable module*, it is required to call `app.registerInteroperableModule()` additionally.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Could be used to send custom data or reaction, like small replies.
```suggestion
Could be used to send custom data or a reaction, like small replies.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Go the file `react/commands/react_command.ts` and import the constants, schemas and types defined above.
```suggestion
Go to the file `react/commands/react_command.ts` and import the constants, schemas, and types defined above.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +Last but not least, call the `addDependencies()` method of the `ReactModule` with the methods of the interoperability module as parameter.
```suggestion
Last but not least, call the `addDependencies()` method of the `ReactModule` with the methods of the interoperability module as a parameter.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +When a user now posts a `reactCrossChain` transaction on a sidechain that registered the React module, a corresponding CCM is sent to the mainchain by a xref:{url_run_relayer}[relayer node], where it
```suggestion
When a user posts a `reactCrossChain` transaction on a sidechain that registered the React module, a corresponding CCM is sent to the mainchain by a xref:{url_run_relayer}[relayer node], where it will be forwarded to the designated receiving sidechain.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +* Set the command schema to equal `CCReactMessageParamsSchema`.
```suggestion
* Set the command schema to match `CCReactMessageParamsSchema`.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    }
```suggestion
public async execute(ctx: CrossChainMessageContext): Promise<void> {
    const { ccm, logger } = ctx;
    logger.info('Executing React CCM');
    // const { sendingChainID, status, receivingChainID } = ccm;
    // Decode the provided CCM parameters
    const params = codec.decode<CCReactMessageParams>(CCReactMessageParamsSchema, ccm.params);
    logger.info(params, 'parameters');
    // Get helloMessageID and reactionType from the parameters
    const { helloMessageID, reactionType } = params;
    const reactionSubstore = this.stores.get(ReactionStore);
    const messageCreatorAddress = cryptography.address.getAddressFromLisk32Address(helloMessageID);
    let msgReactions: ReactionStoreData;

    // Get existing reactions for a Hello message, or initialize an empty reaction object, if none exists,yet.
    try {
        msgReactions = await reactionSubstore.get(ctx, messageCreatorAddress);
    } catch (error) {
        if (!(error instanceof db.NotFoundError)) {
            logger.info({ helloMessageID, crossChainCommand: this.name }, (error as Error).message);
            logger.error({ error }, 'Error when getting the reaction substore');
            throw error;
        }
        logger.info(
            { helloMessageID, crossChainCommand: this.name },
            `No entry exists for given helloMessageID ${helloMessageID}. Creating a default entry.`,
        );
        msgReactions = { reactions: { like: [] } };
    }

    // Check if the reactions is a like
    if (reactionType === 0) {
        const hasLiked = msgReactions.reactions.like.indexOf(ctx.transaction.senderAddress);
        // If the sender has already liked the message
        if (hasLiked > -1) {
            // Remove the sender address from the likes for the message
            msgReactions.reactions.like = msgReactions.reactions.like.splice(hasLiked, 1);
        // If the sender has not liked the message yet
        } else {
            // Add the sender address to the likes of the message
            msgReactions.reactions.like.push(ctx.transaction.senderAddress);
        }
    } else {
        logger.error({ reactionType }, 'invalid reaction type');
    }
    // Update the reaction store with the reactions for the specified Hello message
    await reactionSubstore.set(ctx, messageCreatorAddress, msgReactions);
}
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +Last but not least, call the `addDependencies()` method of the `ReactModule` with the methods of the interoperability module as parameter.
```suggestion
Last but not least, call the `addDependencies()` method of the `ReactModule` with the methods of the interoperability module as a parameter.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +An example implementation of the interoperable modules React and Hello on two different sidechain is available in the Lisk SDK repository under {url_github_sdk_interop}[examples/interop^]
```suggestion
An example implementation of the interoperable modules React and Hello on two different sidechains is available in the Lisk SDK repository under {url_github_sdk_interop}[examples/interop^].
Feel free to check it out.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +Create a new file `constants.ts` inside the `hello` module, to store required constants.
```suggestion
Create a new file `constants.ts` inside the `hello` module, to store the required constants.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +Now, open the file `hello/cc_commands/react_command.ts` and import the constants, schemas and types defined above.
```suggestion
Now, open the file `hello/cc_commands/react_command.ts` and import the constants, schemas, and types defined above.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +        // Get existing reactions for a Hello message, or initialize an empty reaction object, if none exists,yet.
```suggestion
        // Get existing reactions for a Hello message, or initialize an empty reaction object, if none exists, yet.
```

2023-11-03 07:46 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +        // Check if the reactions is a like
```suggestion
        // Check if the reaction is a like
```

2023-11-03 12:14 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +In this example, we will only implement type `0`, which is representing a like.
imho the sentence changes meaning here, and makes it more confusing, so I prefer to keep the original sentence.

2023-11-03 12:25 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +The account sending the `reactCrossChain` command, whichwill create a new CCM needs to provide the fees for the execution of the CCM in tokens that are native on the mainchain.
```suggestion
The account sending the `reactCrossChain` command, which will create a new CCM, needs to provide the fees for the execution of the CCM in tokens that are native on the mainchain.
```

2023-11-03 12:27 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +If you followed the instructions in the `README.md` until {url_github_sdk_interop_cctransfer}[here^], the account `lskx5uqu2zzybdwrqswd8c6b5v5aj77yytn4k6mv6` of `pos-sidechain-exmaple-two` should hav
```suggestion
This is why it should be verified, that the account, that intends to send the transaction, owns enough mainchain tokens.
If you followed the instructions in the `README.md` until the {url_github_sdk_interop_cctransfer}[Transfer from mainchain to sidechain two^] step, the account `lskx5uqu2zzybdwrqswd8c6b5v5aj77yytn4k6mv6` of `pos-sidechain-exmaple-two` should have the required funding.
```

2023-11-03 12:29 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +* http://localhost:4007[^]
yes

2023-11-03 15:32 UTC, sitetester approved these changes

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/commands/react_command.ts
```suggestion
.react/commands/react_cc_command.ts
```

`export class ReactCrossChainCommand extends BaseCommand`
file name should match it's class name

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/schemas.ts
Reminder: since you already mentioned `.react/types.ts` below, hence, can move  all such types `export interface` there

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +    const reactCCM: CCReactMessageParams = {
```suggestion
    const ccReactMessageParams: CCReactMessageParams = {
```
This comment is about best practice: _Variable name should match it's type_

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    // Decode the provided CCM parameters
Can remove such comments

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +        }
- `msgReactions.reactions.like` keeps repeating
- can replace with a constant to simplify usage

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +image::build-blockchain/interop-example.png[,300,role="right"]
It shows 404

2023-11-03 15:32 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +}
It would be better to just stick to single line comment `//` in such cases
- as visually it looks inconsistent
- there is no absolute reason to choose `/** ` here

2023-11-06 16:51 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/commands/react_command.ts
It seems this is more a best practice than a requirement? Do we have agreed on certain best practices somewhere? Regarding the naming, this is another question I have: 

Is it required that the command names for commands creating and executing a specific CCM must match? You can also see this question in the code. it would be nice to receive an answer here, and maybe other information about best practices that should be respected in the examples.

2023-11-06 17:33 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/commands/react_command.ts
- This comment is generally valid (irrespective of interoperability module)
- Specifically, in Interoperability module, we have commands & cross chain commands. Some examples:

<img width="600" alt="Screenshot 2023-11-06 at 07 39 42 PM" src="https://github.com/LiskHQ/lisk-docs/assets/1403133/9c869897-b041-4dfc-bc95-9f0560187ed1">

2023-11-15 10:23 UTC, TalhaMaliktz requested changes
Looking good already! Just some minor remarks

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Next you will be prompted for a Hello message. This can be any string with a minimum length of 3, and a maximum of 256 characters.
```suggestion
Next, you will be prompted for a Hello message. This can be any string with a minimum length of 3 and a maximum of 256 characters.
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +If the node accepted the transaction, it should respond with the corresponding transaction ID.
```suggestion
The node should respond with the corresponding transaction ID if it accepts the transaction.
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Scroll down on the Dashboards for to the "Events" section, and filter for the following events: `CCM Processed`, `CCMSendSuccess`, `CCMSentFailed`
```suggestion
Scroll down on the Dashboards to the "Events" section, and filter for the following events: `CCM Processed`, `CCMSendSuccess`, `CCMSentFailed`
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. `reactionType`: The type of the reactions represented as in integer.
```suggestion
. `reactionType`: The type of the reactions represented as an integer.
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +Once the CCM was received and executed an the node, it is possible to request the reaction on sidechain 1 with the endpoint `hello_getReactions` which we implement in section xref:{url_build_executec
```suggestion
Once the CCM is received and executed on the node, it is possible to request the reaction on sidechain 1 with the endpoint `hello_getReactions` which we implement in the section xref:{url_build_executeccm_endoint}[Creating a new endpoint for getting reactions for a Hello message].
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +To completely reset the interop example, and start from fresh, there is a very handy command which will perform all necessary steps for you:
```suggestion
To completely reset the interop example, and start fresh, there is a very handy command which will perform all the necessary steps for you:
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +To completely reset the interop example, and start from fresh, there is a very handy command which will perform all necessary steps for you:
```suggestion
To completely reset the interop example, and start fresh, there is a very handy command which will perform all the necessary steps for you:
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. *Both* the sending and the receiving chains need to be *registered as sidechains* to the same mainchain.
Please link this to the sidechain registration guide.

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. *Both* the sending and the receiving chains need to be *active sidechains*, with at least one relayer node connected to the mainchain.
Please link this to the Setting up a relayer node guide.

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/nav.adoc
> +*** xref:build-blockchain/interoperable-module/execute-ccm.adoc[]
Since these three guides depend on sidechain registration, I think we should move them to after the "How to register a sidechain" guide in the `build-blockchain` section.

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +In this example, we will only implement type `0`, which is representing a like.
Type 0 could be misleading as it can be perceived either as a number `0` or a string `"0"`, I would explicitly mention type `integer` or `number`. You can alter the rest of the sentence in any way that makes sense for you.

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +To learn how to implement cross-chain commands on the receiving chain, check out the next guide: xref:{url_build_execccm}[]
```suggestion
To learn how to implement cross-chain commands on the receiving chain, check out the next guide: xref:{url_build_execccm}[].
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +In this example, we store the reactions for a Hello message und the sender address of the Hello message, because it is a unique identifier for a Hello message.
```suggestion
In this example, we store the reactions for a Hello message and the sender address of the Hello message, because it is a unique identifier for a Hello message.
```

2023-11-15 10:23 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +To execute and test the implemented corss-chain command, please refer to section xref:{url_build_interop}[Testing interoperable modules].
```suggestion
To execute and test the implemented cross-chain command, please refer to section xref:{url_build_interop}[Testing interoperable modules].
```

2023-11-15 10:33 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +		// Decode the provided CCM parameters
I added the comments on purpose to provide more context

2023-11-15 10:41 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +In this example, we will only implement type `0`, which is representing a like.
In the sentence right before, it is mentioned that this is a number, which makes it clear that it is not a string, and also we do not use quotes around the number, which we would do in case it is a string, so imho it is clear enough.

2023-11-15 14:15 UTC, sitetester requested changes

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +// Schema for the parameters of the react reactCrossChain command
```suggestion
// Schema for the parameters of the reactCrossChain command
```
`react` seems redundant

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +	public schema = CCReactCommandParamsSchema;
```suggestion
export class CrossChainReactCommand extends BaseCommand {
    private _interoperabilityMethod!: InteroperabilityMethod;
    ....
```
4 spaces indent _for entire file_

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/commands/react_command.ts
```suggestion
.react/commands/react_cc_command.ts
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/commands/react_command.ts
```suggestion
.react/commands/react_cc_command.ts
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +    return {
```suggestion
    }
    
    return {
```
Since this `return` is a separate block from above `try/catch`

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +        'hello',
Can replace this with a constant (if defined somewhere)

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +   	public endpoint = new ReactEndpoint(this.stores, this.offchainStores);
```suggestion
export class ReactModule extends BaseInteroperableModule {
    public endpoint = new ReactEndpoint(this.stores, this.offchainStores);
    ...
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +	private _interoperabilityMethod!: InteroperabilityMethod;
```suggestion
    // Create a private member to store the methods of the interoperability module
    private _interoperabilityMethod!: InteroperabilityMethod;
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    public crossChainMethod = new HelloInteroperableMethod(this.stores, this.events);
```suggestion
export class HelloModule extends BaseInteroperableModule {
    public endpoint = new HelloEndpoint(this.stores, this.offchainStores);
    public method = new HelloMethod(this.stores, this.events);
    public commands = [new CreateHelloCommand(this.stores, this.events)];
    // Assign HelloInteroperableMethod to crossChainMethod
    public crossChainMethod = new HelloInteroperableMethod(this.stores, this.events);
    ...
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export const CCReactMessageParamsSchema = {
This is already define in `create_ccm.adoc` section (so can remove from here)

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export interface CCReactMessageParams {
Already defined  in `.react/types.ts`
Since both are inside `interoperable-module`, can put them in a common place ?

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +}
```suggestion
    public get name(): string {
        return CROSS_CHAIN_COMMAND_REACT;
	}
}
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +.hello/cc_commands/react_command.ts
```suggestion
.hello/cc_commands/react_cc_command.ts
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +Go back to the file `hello/module.ts` and update it as seen below.
```suggestion
Go back to the file `hello/module.ts` and update it as shown below.
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +			status: 1,
```suggestion
			status: VerifyStatus.OK, // ? 
```

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export const getApplication = (config: PartialApplicationConfig): Application => {
indentation issue

2023-11-15 14:15 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export class HelloModule extends BaseInteroperableModule {
indentation issue

2023-11-16 09:02 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +// Schema for the parameters of the react reactCrossChain command
```suggestion
// Schema for the parameters of the crossChainReact command
```

2023-11-16 09:10 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +   	public endpoint = new ReactEndpoint(this.stores, this.offchainStores);
Please explain why you added the three dots

2023-11-16 09:11 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    public crossChainMethod = new HelloInteroperableMethod(this.stores, this.events);
why 3 dots

2023-11-16 09:11 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export const CCReactMessageParamsSchema = {
this is a different module

2023-11-16 09:11 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export interface CCReactMessageParams {
different module

2023-11-16 09:12 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +			status: 1,
should be updated in script first...

2023-11-16 11:55 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +.hello/cc_commands/react_command.ts
in Hello module the file name is `react_command.ts`

2023-11-16 11:59 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export class HelloModule extends BaseInteroperableModule {
should be fixed now

2023-11-16 12:00 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export const getApplication = (config: PartialApplicationConfig): Application => {
should be fixed

2023-11-16 12:41 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-11-22 11:58 UTC, sitetester requested changes

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +.react/schemas.ts
To avoid repetition, can define separate properties

e.g., 
```
 const reactionType: {
             dataType: 'uint32',
             fieldNumber: 1,
        };
```
& then 
```
properties: {
         reactionType,
         helloMessageID,
         data,
        ...
   ...
```

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +        },
Since properties are repeating, can use `const`s from above

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +In the `react_cc_command.ts` file, implement the command verification.
```suggestion
In the `react_cc_command.ts` file, implement the verification.
```
`command` seems redundant here

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +For this, adjust the `execute()` hook as shown in the snippet below.
```suggestion
For this, adjust the `execute()` method as shown in the snippet below.
```

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    const params = codec.decode<CCReactMessageParams>(CCReactMessageParamsSchema, ccm.params);
```suggestion
    const ccReactMessageParams = codec.decode<CCReactMessageParams>(CCReactMessageParamsSchema, ccm.params);
```
After `decode`, we get an object of _type_ `CCReactMessageParams`

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    const params = codec.decode<CCReactMessageParams>(CCReactMessageParamsSchema, ccm.params);
As above

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    await reactionSubstore.set(ctx, messageCreatorAddress, msgReactions);
- `message` vs `msg` - inconsistent naming
- `messageCreatorAddress` could be `msgCreatorAddress` then

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +        cryptography.address.getAddressFromLisk32Address(address),
```
export const getAddressFromLisk32Address = (
	base32Address: string,
	prefix = DEFAULT_LISK32_ADDRESS_PREFIX,
): Buffer => {
	validateLisk32Address(base32Address, prefix);
        ...
```
Since it calls `validateLisk32Address` internally, can drop this call on line 320

2023-11-22 11:58 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    reactions: {
Do we really need to have this `reactions` property (as an upper layer) ? After all, we are storing `likes[]` in DB store. Can simply call it `LikesStoreData` ?

2023-11-27 09:02 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +.hello/cc_commands/react_command.ts
` extends BaseCCCommand`
Child class should have same pattern as parent (& based on this, file name will change to `react_cc_command.ts`)

2023-11-29 08:32 UTC, TalhaMaliktz requested changes
Some thought after successfully running the code PR.

2023-11-29 08:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +./bin/run endpoint:invoke hello_getReactions '{"address":"lskmjwp8z88avvxn4voktmx8cu9wk4opjkna5owt5"}
```suggestion
./bin/run endpoint:invoke hello_getReactions '{"address":"lskmjwp8z88avvxn4voktmx8cu9wk4opjkna5owt5"}'
```

2023-11-29 08:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +./bin/run endpoint:invoke chainConnector_getLastSentCCM --pretty --data-path=/Users/mona/.lisk/mainchain-node-one
Please remove the `datapath` property, it throws an error when executed exactly since the user's name might differ. 

I have tried it without the `datapath` and it works fine. I would also recommend removing the datapath from the next few snippets.
```suggestion
./bin/run endpoint:invoke chainConnector_getLastSentCCM --pretty
```

2023-11-29 08:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +.Authorize sidechain 2
I would use the same name throughout the example, just to be consistent.
```suggestion
.Authorize pos-sidechain-example-two
```

2023-11-29 08:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +==== How to authorize the chain connector plugin
I missed performing this step earlier, and I think that is why the example didn't work for me. Is it possible that this step could be moved before the `Create Reaction on sidechain 2`? Or are these two things not related to each other.

2023-11-29 13:51 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +==== How to authorize the chain connector plugin
this only needs to be done when restarting a node, the authorization is already part of the README as well as the start example script, so it shouldn't be missed

2023-11-29 13:52 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +.Authorize sidechain 2
imho it is easier to read like it is

2023-11-29 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +./bin/run endpoint:invoke chainConnector_getLastSentCCM --pretty --data-path=/Users/mona/.lisk/mainchain-node-one
replaced it with a more general path

2023-11-29 13:56 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +    reactions: {
yeah because we want this example to be extendable with additional reactions types

2023-11-29 16:23 UTC, sitetester approved these changes

2023-11-29 16:23 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +	required: ['reactionType', 'helloMessageID', 'receivingChainID', 'data', 'messageFee'],
```suggestion
	required: [...CCReactMessageParamsSchema.required, 'messageFee'],
```
Can simplify :)

2023-11-29 16:23 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +export const CROSS_CHAIN_COMMAND_NAME_REACT = 'crossChainReact';
```suggestion
export const CROSS_CHAIN_COMMAND_REACT = 'crossChainReact';
```

- Since previously, in `react/commands/react_cc_command.ts`, we have 
```
import { CROSS_CHAIN_COMMAND_REACT } from '../constants';
```
- Naming should be consistent

2023-11-29 16:23 UTC, sitetester commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +export class CrossChainReactCommand extends BaseCommand {
file name indicates, it's `_cc_`, but it doesn't extend from `BaseCCCommand` (as in SDK, we have `BaseCommand` & `BaseCCCommand`)

2023-11-29 17:06 UTC, Tschakki commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/create-ccm.adoc
> +export class CrossChainReactCommand extends BaseCommand {
i don't see this followed in the default modules, see here for example: https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/token/commands/transfer_cross_chain.ts

2023-11-30 08:53 UTC, TalhaMaliktz approved these changes
Few minor suggestions, rest LGTM 👍🏼

2023-11-30 08:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +. `helloMessageID`: We use the address of the account who created the Hello message to identify the Hello message.
```suggestion
. `helloMessageID`: We use the address of the account that created the Hello message to identify the Hello message.
```

2023-11-30 08:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/index.adoc
> +If the node accepted the transaction, it should respond with the corresponding transaction ID.
```suggestion
If the node accepts the transaction, it should respond with the corresponding transaction ID.
```

2023-11-30 08:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +To indicate that this command will accept and execute a CCM, move it to a new folder `cc_commands` and rename the file to `react_cc_command.ts`.
```suggestion
To indicate that this command will accept and execute a CCM, move it to a new folder `cc_commands`, and rename the file to `react_cc_command.ts`.
```

2023-11-30 08:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/build-blockchain/interoperable-module/execute-ccm.adoc
> +It is used as unique identifier of a Hello message, to get the corresponding reactions from the <<create-a-store-for-reactions,store>>.
```suggestion
It is used as a unique identifier of a Hello message, to get the corresponding reactions from the <<create-a-store-for-reactions,store>>.
```

2023-11-30 08:57 UTC, TalhaMaliktz commented
BTW! We need to update the `preview-site.yml` file as I think the `release/4.0.0` of `lisk-core` and `release/0.7.0` branch of `lisk-service` have either been altered or deleted. Putting `development` in place of the aforementioned branches correctly generates the preview.

2023-12-04 09:27 UTC, merged