Update managing logs page in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1904
Opened 2023-10-24 10:07 UTC by chris529

Closes #1533

2023-11-02 10:37 UTC, Tschakki requested changes
Please add the new page to the navigation as well.

2023-11-02 10:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +For monitoring or debugging your node, the Lisk SDK v6 tracks all activities that occur within the node by creating applicable log messages.
Please check, if the numbers (10-60) are still used to identify log levels, or if they can be removed.

2023-11-02 10:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +By using the following config setting listed in the snippet below, it is possible to set the log level of the app.
```suggestion
To change the node log level, update the `logLevel` property in the `config.json` file, under xref:v6@lisk-sdk::config.adoc#system[system.logLevel] as listed in the snippet below.
```

2023-11-02 10:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +----
Please add indentation.

2023-11-02 10:37 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +[source,bash]
```suggestion

.`system` options in config.json
[source,json]
```

2023-11-03 09:03 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +For monitoring or debugging your node, the Lisk SDK v6 tracks all activities that occur within the node by creating applicable log messages.
Yes, they are still valid and correct 👍

2023-11-03 10:51 UTC, Incede approved these changes

2023-11-03 11:05 UTC, Tschakki requested changes
Looking good already, just left two small remarks :)

2023-11-03 11:05 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +./bin/run start  > app.log will output stdout to a file app.log
the part after app.log seems to be a comment
```suggestion
./bin/run start  > app.log # will output stdout to a file app.log
```

2023-11-03 11:05 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/logging.adoc
> +./bin/run start  >> app.log
Looks like the same command as above, can be removed.

2023-11-03 12:43 UTC, Tschakki approved these changes
Thank you!

2023-11-03 15:58 UTC, merged