Update Multi-signature account registration guide - Closes 1880
LiskArchive/lisk-legacy-docs pull request #1908
Opened 2023-10-29 07:22 UTC by TalhaMaliktz

2023-11-09 13:53 UTC, Tschakki requested changes
Looking really good already! 👍

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +As mentioned in the <<parameters, parameters>> section, we need three accounts.
```suggestion
Following our example in the <<parameters, parameters>> section, we need three different accounts credentials to register the multi-signature account.
```

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +We will be using the first account among the three as the sender of the registerMultisignature transaction.
```suggestion
The first account among the three will also be used to send the registerMultisignature transaction.
```

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +In the next step, we will collect signatures from each optional account.
At this point, it would be nice to motivate the reader to run the script to test the current implementation. 
If they implemented everything correctly, it should display the unsigned data in the console

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
>  How to send the transaction is described in the next step.
Before going to the next step, please motivate the reader to run the script to test correct implementation. If all works well, it should display the transaction params in the console.
Maybe the script can be updated to log the fully signed transaction object, too.

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +[source,js]
Just to avoid confusion, mention at the beginning of each chapter briefly in what file we need to add the new code snippets, and maybe even where exaclty ("right below the function XY()")

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Since the multi-signature account set up in this guide requires two signatures, two public keys should be mentioned after the `--optional-keys` flag.
Not sure, but from my understanding we mention all three optional keys, but only need to add 2 signatures?

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Also, mention the `--key-derivation-path` of the signatory account.
In most cases this wont be necessary, because it will use the default key deriviation path, if omitted, I think

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +. Define the functions for dry running or posting the transaction:
at this point, the reader should try the script and verify correct console output (please provide an example)

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The script is ready and it can be used to either dry run or send the transaction to the node after properly signing the token transfer transaction.
Please provide example how to run the scripts

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +[,js]
please provide info in what file /place the code should be added

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +{"module":"token","command":"transfer","params":{"tokenID":{"type":"Buffer","data":[0,0,0,1,0,0,0,0]},"recipientAddress":{"type":"Buffer","data":[249,75,79,196,106,113,215,201,19,216,156,191,48,204,1
in a somewhat realistic scenario, the second signer would like to verify the txJSON befor signing, but it looks like important params are encoded as Buffer. Can this be updated to human-readbale values? Otherwise it is hard to verify correct params.

2023-11-09 13:53 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The second signatory should repeat the same process with two changes, update the transaction hash with the recently signed transaction, and update the key derivation path to match the second signator
Typically the different multi-sig members do not have different key-deriviation paths, as most accounts use default paths.

2023-11-14 12:53 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +As mentioned in the <<parameters, parameters>> section, we need three accounts.
```suggestion
Following our example in the <<parameters, parameters>> section, we need three different account credentials to register the multi-signature account.
```

2023-11-14 12:54 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +We will be using the first account among the three as the sender of the registerMultisignature transaction.
```suggestion
The first account among the three will also be used to send the `registerMultisignature` transaction.
```

2023-11-15 13:05 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +. Define the functions for dry running or posting the transaction:
Running the script is mentioned in the next section at line 1175 and is kept separate intentionally, since running the script has its own flow.

2023-11-15 13:06 UTC, Phanco commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +? Please enter: data:
If data is optional, would it be better if 
```
Please enter: data (Optional):
```

2023-11-15 13:07 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +The script is ready and it can be used to either dry run or send the transaction to the node after properly signing the token transfer transaction.
Running the script is mentioned in the next section at line 1175 and is kept separate intentionally, since running the script has its own flow.

2023-11-15 13:08 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Since the multi-signature account set up in this guide requires two signatures, two public keys should be mentioned after the `--optional-keys` flag.
Whilst registering a multi-signature account, the number of signatures should be equal to the number of keys passed (mandatory + optional). 

But when creating a transaction using a multi-sig account, one only needs to pass the required number of keys which we pass to the `numberOfSignatures` variable.

2023-11-15 13:10 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +? Please enter: data:
This is something that the SDK needs to update! The console text is just copied and pasted here. The prompt texts come from the framework.

2023-11-15 16:13 UTC, Phanco commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +? Please enter: data:
Ah sorry, understand 👍

2023-11-16 09:57 UTC, Phanco approved these changes

2023-11-16 12:45 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Since the multi-signature account set up in this guide requires two signatures, two public keys should be mentioned after the `--optional-keys` flag.
ok, then do we really need the `--optional-keys` flag at all in this case?

2023-11-16 12:47 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/integrate-blockchain/multisignature-accounts-and-transactions.adoc
> +Since the multi-signature account set up in this guide requires two signatures, two public keys should be mentioned after the `--optional-keys` flag.
Yes, we do. Skipping the flag with throw this error: 

```
./bin/run transaction:sign 0a05746f6b656e12087472616e73666572180320c0843d2a20e98e8a6325730be6bf2644af83d5a0b004bb31c15858fedbd0ac2c1f89e2eece32270a0800000001000000001080dac4091a14f94b4fc46a71d7c913d89cbf30cc698f3ee3120d2200 c61cd862a8b7f73857b248a4358a7b35c29ca273d76ba3819e8c54b62801f16e e98e8a6325730be6bf2644af83d5a0b004bb31c15858fedbd0ac2c1f89e2eece  --json --pretty        
 ›   Error: Unexpected arguments: c61cd862a8b7f73857b248a4358a7b35c29ca273d76ba3819e8c54b62801f16e, e98e8a6325730be6bf2644af83d5a0b004bb31c15858fedbd0ac2c1f89e2eece
 ›   See more help with --help
```

2023-11-16 14:09 UTC, Tschakki approved these changes
Thank you!

2023-11-23 10:07 UTC, merged