Sign multisignature transactions offline - Closes 1290
LiskArchive/lisk-legacy-docs pull request #1914
Opened 2023-11-16 08:32 UTC by TalhaMaliktz

2023-11-17 11:35 UTC, Tschakki requested changes
Just some small remarks, looks great overall!

2023-11-17 11:35 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
> +** xref:integrate-blockchain/create-multiSig-tx-offline.adoc[]
Maybe it would improve the overview to create a new sub-category "Transaction creation and signing", where all these guides would be included

2023-11-17 11:35 UTC, Tschakki commented on docs/modules/ROOT/pages/integrate-blockchain/create-multiSig-tx-offline.adoc
> +In case, you have a different setup for the multi-signature account, where the account requires a different number of mandatory and optional keys, adjust the following process accordingly.
```suggestion
In case you have a different setup for the multi-signature account, where the account requires a different number of mandatory and optional keys, adjust the following process accordingly.
```

2023-11-17 13:15 UTC, Tschakki approved these changes
LGTM 👍 added only one small suggestion

2023-11-17 13:15 UTC, Tschakki commented on docs/modules/ROOT/nav.adoc
>  ** xref:integrate-blockchain/posting-transactions.adoc[]
Just noticed that these two guides are also connected to the above, maybe we can include them in the sub-category, and rename it accordingly. 

```suggestion
** Transaction creation, signing, and posting
*** xref:integrate-blockchain/create-sign-transactions.adoc[]
*** xref:integrate-blockchain/create-tx-offline.adoc[]
*** xref:integrate-blockchain/multisignature-accounts-and-transactions.adoc[]
*** xref:integrate-blockchain/create-multiSig-tx-offline.adoc[]
*** xref:integrate-blockchain/calculating-min-fee.adoc[]
*** xref:integrate-blockchain/posting-transactions.adoc[]
```

2023-11-22 09:13 UTC, Phanco approved these changes

2023-11-23 10:08 UTC, merged