Create API reference for Chain Connector Plugin - Closes 1883
LiskArchive/lisk-legacy-docs pull request #1920
Opened 2023-11-23 14:29 UTC by TalhaMaliktz

Closes #1883

2023-11-27 12:48 UTC, chris529 commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +|Boolean flag that tells whether or not to authorize the Chain Connector plugin.
```suggestion
|A Boolean flag that indicates whether or not to authorize the Chain Connector plugin.
```

2023-11-27 12:48 UTC, chris529 approved these changes
LGTM! :) I just left a small suggestion.

2023-11-27 16:47 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns the CCUs sent onchain.
Whenever a CCU is successfully sent, it's saved in plugin store DB. This endpoint will return all such sent CCUs.

2023-11-27 16:47 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns aggregate commits of the blockchain
Returns [aggregate commits](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md#aggregate-commits-1) stored in plugin store DB.

2023-11-27 16:47 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns block headers.
Returns [block headers](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0055.md#block-header).

2023-11-27 16:47 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns the cross-chain messages sent across chains.
Returns the cross-chain messages sent across chains. This includes CCMs parsed from [CrossChainMessageSentSuccess](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#crosschainmessagesentsuccess) & [CrossChainMessageProcessed](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#crosschainmessageprocessed) events.

2023-11-27 16:47 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns the last sent cross-chain message.
Returns the last sent cross-chain message, if any, otherwise, it can throw error with `No CCM was sent so far` message.

2023-11-27 16:47 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns validator info.
from [validatorsHashPreimage](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md#approach-1-certificate-computation-from-aggregate-commits) key value store.

2023-11-28 09:33 UTC, sitetester requested changes

2023-11-28 09:33 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Whenever a CCU is successfully sent, it's saved in plugin store.
plugin store DB

2023-11-28 09:33 UTC, sitetester commented on docs/modules/ROOT/pages/api/plugin-rpc-api/chain-connector-api.adoc
> +Returns the last sent cross-chain message, if any, otherwise, it throws an error: "No CCM was sent so far" message.
```suggestion
Returns the last sent cross-chain message, if any, otherwise, it throws an error: "No CCM was sent so far".
```

2023-11-28 09:41 UTC, sitetester approved these changes

2023-12-04 10:49 UTC, merged