Update reward sharing guide in Lisk docs
LiskArchive/lisk-legacy-docs pull request #1921
Opened 2023-12-01 11:18 UTC by chris529

Closes #1909

2023-12-08 14:51 UTC, Incede approved these changes

2023-12-13 12:41 UTC, TalhaMaliktz requested changes
Please consider the following!

2023-12-13 12:41 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
>  === Sharing via CLI
The **Sharing via CLI** example also needs an update as the value of `commission` is still `85` in the aforementioned example.

2023-12-13 12:41 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
>  :url_constraints-on-commission-increase: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0070.md#constraints-on-commission-increase
Please delete the old images!

2023-12-13 13:31 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
>  === Sharing via CLI
Good point, now done. 👍

2023-12-13 13:31 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
>  :url_constraints-on-commission-increase: https://github.com/LiskHQ/lips/blob/main/proposals/lip-0070.md#constraints-on-commission-increase
Done 👍

2023-12-13 13:36 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *75%* of the rewards and share *25%* with their stakers, hence the value of `8500`.
Please follow this and change all the values accordingly!
```suggestion
In this example, the validator is set to keep *25%* of the rewards and share *75%* with their stakers, hence the value of `2500`.
```

2023-12-13 14:03 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/reward-sharing.adoc
> +In this example, the validator is set to keep *25%* of the rewards as a commission and share the remaining *75%* with their stakers, hence the value of `2500`.
```suggestion
In this example, the validator is set to keep *25%* of the rewards as a commission and share the remaining *75%* with their stakers, hence the value of `25`.
```

2023-12-13 14:07 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2023-12-13 14:07 UTC, TalhaMaliktz approved these changes

2023-12-19 09:44 UTC, merged