New guide about monitoring a validator node
LiskArchive/lisk-legacy-docs pull request #1932
Opened 2023-12-07 09:51 UTC by TalhaMaliktz

Closes #1422

2023-12-08 11:04 UTC, Tschakki requested changes

2023-12-08 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The Monitor plugin takes the data reported by {url_prometheus}[Prometheus (an open-source systems monitoring and alerting toolkit)^] and exposes the data into a standard format using its own <<retrie
Does the monitor plugin really take data from prometheus, or is it the other way around?

2023-12-08 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The {url_plugin_monitor}[Monitor plugin^] provides insights about a running node, for example, if a node is down or a node is missing blocks, etc.
The link doesnt provide much useful information, as we wont be updating the typedocs, so imho its better to remove the link
```suggestion
The *Monitor plugin* provides insights about a running node, for example, if a node is down or a node is missing blocks, etc.
```

2023-12-08 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +:url_core_index: v4@lisk-core::index.adoc
```suggestion
:url_core_index: lisk-core::index.adoc
```

2023-12-08 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* [x] Retrieving various types of data from the Monitor plugin.
if this is the only content on this page, it should be renamed to "How to enable the Monitor plugin" or something similar, as it doesn't provide any additional approach and also no bigger picture like context and use cases for monitoring different metrics.

2023-12-08 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The {url_plugin_monitor}[Monitor plugin^] provides insights about a running node, for example, if a node is down or a node is missing blocks, etc.
Instead, please introduce the Monitor plugin a little more directly in the intro of this guide, what are its main features and use cases?

2023-12-08 11:04 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +== Retrieving data
Here is miss usage examples, how to invoke the different endpoints, and how the responses look like. It should also include a link to a guide / docs that explain how to track endpoints with prometheus

2023-12-12 13:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The Monitor plugin takes the data reported by {url_prometheus}[Prometheus (an open-source systems monitoring and alerting toolkit)^] and exposes the data into a standard format using its own <<retrie
Corrected

2023-12-12 13:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The {url_plugin_monitor}[Monitor plugin^] provides insights about a running node, for example, if a node is down or a node is missing blocks, etc.
Done

2023-12-12 13:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* [x] Retrieving various types of data from the Monitor plugin.
Text updated

2023-12-12 13:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +== Retrieving data
Usage example added

2023-12-13 10:37 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* The Monitor plugin gives hints for debugging the network, and if there is an attack on the network.
```suggestion
* The Monitor plugin gives hints for debugging the network, and detecting any network attacks.
```

2023-12-13 10:39 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* One can also receive information about the performance of the custom module via the Monitor plugin.
```suggestion
* Information regarding the performance of the custom module can also be obtained through the Monitor plugin.
```

2023-12-13 10:46 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +On this page, you'll learn:
```suggestion
On this page, you'll learn how to perform the following:
```

2023-12-13 10:47 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* [x] Registration of the Monitor plugin to a blockchain client.
```suggestion
* [x] Register the Monitor plugin to a blockchain client.
```

2023-12-13 10:47 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* [x] Configuring the Monitor plugin.
```suggestion
* [x] Configure the Monitor plugin.
```

2023-12-13 10:47 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* [x] Retrieving various types of data from the Monitor plugin.
```suggestion
* [x] Retrieve various types of data from the Monitor plugin.
```

2023-12-13 10:48 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +With the latest version of Lisk Core v4 and Lisk SDK v6, the default plugins come pre-installed after a client is installed or initiated, respectively.
```suggestion
With the latest version of Lisk Core v4 and Lisk SDK v6, the default plugins come pre-installed after a client is installed or initiated respectively.
```

2023-12-13 10:51 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +You can check the `package.json` file of the blockchain client to ensure the installation.
```suggestion
You can check the `package.json` file of the blockchain client to ensure the installation has been performed correctly.
```

2023-12-13 10:53 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +You can opt for any of the below-mentioned to register the plugin to the blockchain client.
```suggestion
You can opt for any of the below-mentioned options to register the plugin to the blockchain client.
```

2023-12-13 10:53 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +It is essential to enable WS API and configure the `allowedMethods` property before registering the `MonitorPlugin`.
```suggestion
It is essential to enable the WS API and configure the `allowedMethods` property before registering the `MonitorPlugin`.
```

2023-12-13 10:57 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +Depending on how you chose to register the plugin, start the blockchain client, accordingly.
```suggestion
Depending on how you chose to register the plugin, start the blockchain client accordingly.
```

2023-12-13 11:02 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The Monitor plugin comes with a set of pre-defined configurations, which can be tweaked as per the node operator's needs.
```suggestion
The Monitor plugin comes with a set of pre-defined configurations, which can be tweaked as per the node operator's requirements.
```

2023-12-13 11:05 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +|Defines the {url_cors_intro}[CORS^] properties such as `origin` and allowed `methods` which should be entertained by the Monitor plugin.
imho we should just slightly reword this line to the following:
Defines the {url_cors_intro}[CORS^] properties such as `origin` and allowed `methods` which should be handled by the Monitor plugin.

2023-12-13 11:10 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The following table briefly describes each:
```suggestion
The following table briefly describes them:
```

2023-12-13 11:15 UTC, chris529 commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +Configuring the Prometheus to automatically invoke the aforementioned endpoint and then, plugging such data to visualizing tools like Grafana can enable a node operator to stay up to date with the la
```suggestion
Configuring the Prometheus to automatically invoke the aforementioned endpoint and then plugging such data into visualizing tools such as Grafana, can enable a node operator to stay up to date with the latest status of their node.
```

2023-12-13 11:17 UTC, chris529 reviewed
Looks great! I just left a few minor suggestions/recommendations 👍

2023-12-13 11:48 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +|Defines the {url_cors_intro}[CORS^] properties such as `origin` and allowed `methods` which should be entertained by the Monitor plugin.
```suggestion
|Defines the {url_cors_intro}[CORS^] properties such as origin and allowed methods which should be handled by the Monitor plugin.
```

2023-12-13 12:50 UTC, chris529 approved these changes
LGTM! 👍

2023-12-14 10:42 UTC, ishantiw requested changes
There are few comments around functionality of monitor plugin

2023-12-14 10:42 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* Information regarding the performance of the custom module can also be obtained through the Monitor plugin.
I'm not sure if we can get any insight around performance of custom module

2023-12-14 10:42 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* It provides developers with vital information on block processing and network performance.
```suggestion
* It provides information about blocks and transactions received from the network.
```

2023-12-14 10:42 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* It also provides information to determine machine performance relative to network activity.
It does not have any information about machine performance but more like network activity on your node
```suggestion
* It provides information about connected/disconnected/banned peers and including some other network activities.
```

2023-12-14 10:42 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +* The Monitor plugin gives hints for debugging the network, and detecting any network attacks.
```suggestion
* The Monitor plugin gives hints for debugging the network, and detecting any network splits or attacks.
```

2023-12-14 10:42 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +|Returns the data about the number of connected/disconnected peers, and the number of outgoing/incoming connections with several peers at a certain height.
```suggestion
|Returns the data about the number of connected/disconnected/banned peers, and the number of outgoing/incoming connections with several peers at a certain height.
```

2023-12-14 10:42 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The monitor plugin exposes four endpoints that return important data about a validator's node.
I'm not sure if it really helps validator node with any information around forging a block but yes in general it does help a node to see how it is connected and receiving information with the network

2023-12-14 11:32 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/monitoring-node.adoc
> +The monitor plugin exposes four endpoints that return important data about a validator's node.
I have removed the term `validator`.

2023-12-14 13:26 UTC, ishantiw approved these changes
Great job @TalhaMaliktz 🙌

2023-12-19 09:53 UTC, Tschakki approved these changes

2023-12-19 09:54 UTC, merged