Add guide about extending Lisk Indexer service
LiskArchive/lisk-legacy-docs pull request #1933
Opened 2023-12-13 09:02 UTC by TalhaMaliktz

Closes #1585

2023-12-13 13:01 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The data of the new transactions can then be used by the Indexer service for any customized logic, for example, in this guide, the `applyTransaction` hook is extended to record the addresses of all a
```suggestion
The data of the new transactions can then be used by the Indexer service for any customized logic. For example, in this guide the `applyTransaction` hook is extended to capture the addresses of all accounts that have engaged in any activity within the network.
```

2023-12-13 13:03 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The `chain_deleteBlock` event is triggered to cater to the finalized height, for example, if the finalized block height of the blockchain is 95 and some nodes are at height 97 then, the `chain_delete
```suggestion
The `chain_deleteBlock` event is triggered to cater to the finalized height. For example, if the finalized block height of the blockchain is 95 and some nodes are at a height of 97, then the `chain_deleteBlock` event will be triggered on such nodes, and the additional two blocks will be deleted from these nodes as well in order to sync with the network.
```

2023-12-13 13:08 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +To extend Lisk Service, and implement hooks for a custom module, see the following steps:
```suggestion
To extend Lisk Service, and implement hooks for a custom module, perform the following steps:
```

2023-12-13 13:11 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Create a file specific to the command for which there is a need to implement the custom hooks. For example: {url_transfer}[transfer.js^].
```suggestion
. Create a file specific to the command that requires the implementation of custom hooks. For example: {url_transfer}[transfer.js^].
```

2023-12-13 13:12 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Take out the `recipientAddress` out of the transaction and then store it in the Lisk Indexer service database via the `applyTransaction` hook.
```suggestion
. Take out the `recipientAddress` of the transaction and then store it in the Lisk Indexer service database via the `applyTransaction` hook.
```

2023-12-13 13:13 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. In case, the block is deleted, update the Lisk Indexer service database by deleting the corresponding `recipientAddress` through the `revertTransaction` hook.
```suggestion
. In the case whereby the block is deleted, update the Lisk Indexer service database by deleting the corresponding `recipientAddress` through the `revertTransaction` hook.
```

2023-12-13 13:14 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +For more examples of extending the Indexer service for various modules and their commands, see:
```suggestion
For more examples of extending the Indexer service for various modules and their commands, see the following list:
```

2023-12-13 13:15 UTC, chris529 reviewed
Looks great! Just a few minor points 👍

2023-12-13 14:16 UTC, chris529 commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +To extend Lisk Service, and implement hooks for a custom module, perform the following steps:
```suggestion
To extend Lisk Service and implement hooks for a custom module, perform the following steps:
```

2023-12-13 14:19 UTC, chris529 approved these changes
LGTM! 👍  I just left 1 minor suggestion.

2023-12-13 16:32 UTC, sameersubudhi requested changes
Please consider the following.

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> += Extending the Indexer service
```suggestion
= Extending the Indexer microservice
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The Blockchain Indexer service is primarily responsible for indexing all the blockchain information, based on the scheduled jobs by the Blockchain Coordinator.
```suggestion
The Blockchain Indexer microservice is primarily responsible for indexing all the blockchain information, based on the scheduled jobs by the Blockchain Coordinator.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +In the data service mode, it serves user request queries made via the RESTful API or WebSocket-based RPC calls. It can run both the indexer and data service modes simultaneously and is enabled by def
```suggestion
In the data service mode, it serves user request queries made via the RESTful API or the WebSocket-based RPC calls. It can run both the indexer and data service modes simultaneously, both enabled by default.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The data of the new transactions can then be used by the Indexer service for any customized logic.
```suggestion
When the new block contains transactions, the corresponding `applyTransaction` hook is invoked internally to process the transaction and its parameters.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +For example, in this guide the `applyTransaction` hook is extended to capture the addresses of all accounts that have engaged in any activity within the network.
```suggestion
For example, in this guide we demonstrate the `applyTransaction` hook implemented corresponding to the `transfer` transaction from the `token` module. The hook indexes the addresses of all accounts engaged in the transaction. This information can help us determine the number of accounts on the chain.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The `chain_deleteBlock` event is triggered to cater to the finalized height.
```suggestion
The node triggers the`chain_deleteBlock` event when it deletes blocks from it's current chain to reorganize itself to a different fork on the network.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The `revertTransaction` hook can then be customized to delete or manipulate the transaction data present in the Indexer service's database.
I'd remove the first statement here. Chain reorgs do not always have to happen until a finalized height. Blocks are deleted only to the height (finalized or non-finalized, mostly non-finalzed) from where the node switches to a forked chain.

```suggestion
The `revertTransaction` hook can then be customized to delete or manipulate the transaction data present in the Indexer service's database. It basically reverts the effects of the corresponding `applyTransaction` hooks, as applicable.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +== Extending the Indexer service
```suggestion
== Extending the Indexer microservice
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +Existing hooks are located in the {url_sharedIndexer_directory}[shared/indexer/transactionProcessor^] directory.
```suggestion
All the hooks are placed under the {url_sharedIndexer_directory}[shared/indexer/transactionProcessor^] directory.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The value must match the module name as registered within the application.
```suggestion
The value must exactly match the module name (in camelCasing) as registered within the application.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +You should also define database instances, import constants, and logger, etc.
I don't think it is necessary to specify this statement here.
```suggestion
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +const getTransactionsTable = () => getTableInstance(transactionsTableSchema, MYSQL_ENDPOINT);
```suggestion
/**
 * Make necessary imports, and define the necessary helper methods and constants
*/
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Take out the `recipientAddress` of the transaction and then store it in the Lisk Indexer service database via the `applyTransaction` hook.
```suggestion
. Extract the `recipientAddress` from the transaction and index it in the Lisk Indexer microservice's database via the `applyTransaction` hook.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Export a `COMMAND_NAME` variable. The value must match the command name as registered within the application.
```suggestion
. Define and export the `COMMAND_NAME` variable. The value must exactly match the command name (in camelCasing) as registered within the application.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Export a `MODULE_NAME` variable.
```suggestion
. Define and export the `MODULE_NAME` variable.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. In the case whereby the block is deleted, update the Lisk Indexer service database by deleting the corresponding `recipientAddress` through the `revertTransaction` hook.
```suggestion
. In the case whereby the block is deleted, update the Lisk Indexer microservice database by deleting the corresponding `recipientAddress` through the `revertTransaction` hook.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Now, whenever a token transfer transaction is executed on the chain, Lisk Indexer Service will take out the `recipientAddress` of the transaction and will keep it in the list of active accounts, wh
```suggestion
. Now, whenever a token transfer transaction is executed on the chain, Lisk Service's Blockchain Indexer microservice will extract the `recipientAddress` of the transaction and will index it in the list of active accounts, which can be served to applications such as Lisk Wallet upon request.
```

2023-12-13 16:32 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +For more examples of extending the Indexer service for various modules and their commands, see the following list:
```suggestion
For more examples of extending the Indexer microservice for various modules and their commands, see the following list:
```

2023-12-14 08:45 UTC, sameersubudhi approved these changes
LGTM with a couple of minor remarks 👍

2023-12-14 08:45 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +The `revertTransaction` hook can then be customized to delete or manipulate the transaction data present in the Indexer service's database.
```suggestion
The `revertTransaction` hook can then be customized to delete or manipulate the transaction data present in the Indexer microservice's database.
```

2023-12-14 08:45 UTC, sameersubudhi commented on docs/modules/ROOT/pages/integrate-blockchain/aggregate-blockchain-data/extend-indexer.adoc
> +. Now, whenever a token transfer transaction is executed on the chain, Lisk Service's Blockchain Indexer microservice will extract the `recipientAddress` of the transaction and will index it in the l
```suggestion
. Now, whenever a token transfer transaction is executed on the chain, Lisk Service's Blockchain Indexer microservice will extract the `recipientAddress` of the transaction and index it in the list of active accounts, which can be served to applications such as Lisk Wallet upon request.
```

2023-12-19 09:45 UTC, merged