Add explanation about creating a bigger Hash Onion
LiskArchive/lisk-legacy-docs pull request #1938
Opened 2023-12-20 12:40 UTC by TalhaMaliktz

Closes #1931

2023-12-20 13:22 UTC, Tschakki requested changes

2023-12-20 13:22 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +== Generating the hash onion
Please don't create a new section for this, it creates redundancy and inconsistency with the next section.

Add the info as an alternative und "Set the hash onion", maybe as info box or if it's too big for that create tabs and explain both options how to create hashonions (default way vs custom way)

Also, I wouldn't explain how to create a bash script step by step here - either provide the commands directly for easy copy-paste, or provide the complete bash script and show a usage example of the script

2023-12-21 14:39 UTC, Tschakki approved these changes
LGTM

2023-12-21 14:39 UTC, Tschakki commented on docs/modules/ROOT/pages/run-blockchain/become-a-validator.adoc
> +For every block that a validator generates, a hash onion is consumed.
```suggestion
```

would remove this here, this is already covered in the intro text of the section

2023-12-28 12:21 UTC, ishantiw approved these changes
LGTM

2023-12-28 12:26 UTC, merged