Update "Setting up a relayer node" guide
LiskArchive/lisk-legacy-docs pull request #1942
Opened 2023-12-29 10:08 UTC by TalhaMaliktz

Closes #1940

2023-12-29 12:32 UTC, Phanco approved these changes

2024-01-02 14:48 UTC, ishantiw requested changes
a few suggestions

2024-01-02 14:48 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +It's an optional value, and is only used if the user passes a value higher than the minimum calculated fee.
```suggestion
It's an optional value, and is only used if the user wants to pay fee higher than the minimum calculated fee.
```

2024-01-02 14:48 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +In that case the the minimum calculated fee is overriden with the value passed with the `ccuFee` property.
```suggestion
In that case the the minimum calculated fee is overridden with the value passed with the `ccuFee` property. If the user provided fee is lower than the calculated minimum fee then the calculated minimum fee will be used in that case.
```

2024-01-02 14:48 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
>              "ccuFee": "100000000",
Maybe in the document we can give a lower value so to avoid users giving large values for fee by mistake while following the document.

```suggestion
            "ccuFee": "800000",
```

2024-01-02 14:48 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
>      "ccuFee": "100000000",
```suggestion
    "ccuFee": "800000",
```

2024-01-02 14:48 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
>      "ccuFee": "100000000",
```suggestion
    "ccuFee": "800000",
```

2024-01-08 10:45 UTC, ishantiw approved these changes
LGTM 🎉

2024-01-08 11:04 UTC, merged