Update setup relayer node guide and Chain Connector API page
LiskArchive/lisk-legacy-docs pull request #1945
Opened 2024-03-21 14:41 UTC by TalhaMaliktz

Resolves #1944

2024-03-22 11:52 UTC, ishantiw requested changes
Overall it looks nice, just a few comments on adding some more information and references.

2024-03-22 11:52 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +==== What are Prefixes and how to get them?
maybe to know more about prefixes we can simply refer to LIP https://github.com/LiskHQ/lips/blob/main/proposals/lip-0040.md#module-store-prefix

2024-03-22 11:52 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Then, look for the `outbox` store of the `interoperability` module.
reference for outbox substore https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#outbox-root-substore

2024-03-22 11:52 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Then, look for the `outbox` store of the `interoperability` module.
```suggestion
Then, look for the `outbox` store of the `interoperability` module and note down the value of `key` property.
```

2024-03-22 11:52 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +| The first 8 bytes of the `key` value is the `MODULE_PREFIX`.
```suggestion
| The first 4 bytes of the `key` value is the `MODULE_PREFIX`.
```

2024-03-22 11:52 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +|The last 4 bytes of the `key` value is the `SUBSTORE_PREFIX`.
```suggestion
|The last 2 bytes of the `key` value is the `SUBSTORE_PREFIX`.
```

2024-03-22 11:52 UTC, ishantiw commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +
You can mention that MODULE_PREFIX+SUBSTORE_PREFIX can be found from the `getMetadata` modules, store's "key" part

2024-03-22 11:57 UTC, TalhaMaliktz commented on docs/modules/ROOT/pages/run-blockchain/setup-relayer.adoc
> +Then, look for the `outbox` store of the `interoperability` module.
```suggestion
Then, look for the `outbox` store of the `interoperability` module and note down the value of the `key` property.
```

2024-03-22 12:54 UTC, Tschakki approved these changes
LGTM 👍

2024-03-26 10:22 UTC, ishantiw approved these changes
Nicely done 👏

2024-03-26 13:02 UTC, merged