Create SDK introduction, Closes #205
LiskArchive/lisk-legacy-docs pull request #209
Opened 2019-04-29 14:35 UTC by Tschakki

Closes #205

2019-05-17 07:28 UTC, MaciejBaj requested changes

2019-05-17 07:28 UTC, MaciejBaj commented on introduction.md
> +To start using the Lisk SDK you need to install one NPM package - [lisk-framework](https://www.npmjs.com/package/lisk-framework):
This is outdated installation instructions, also please think of the basic "steps" of running an app using Lisk SDK.

This section should be divided:

using Alpha SDK
- install Alpha SDK
- run your first app 
- the next steps of developing on Alpha SDK

contributing to Alpha SDK 
- compile the following packages - Elements, Framework, SDK 
- Linking the packages for the development ease (please ask @ishantiw for the more details)

2019-05-31 08:50 UTC, RachBLondon requested changes
Some small grammatical changes, otherwise all good 👍

2019-05-31 08:50 UTC, RachBLondon commented on configuration.md
> +Here is a complete list of all available configuration options of the Lisk SDK.
Here is a complete list of all *the* available configuration options of the Lisk SDK.

2019-05-31 08:50 UTC, RachBLondon commented on configuration.md
> +The values below are the default values. They will be used automatically when starting the application like described in [start with default values](#start-with-default-values).
application *as* described

2019-05-31 08:50 UTC, RachBLondon commented on configuration.md
> +Inside of `app.genesisConfig`, specific constants for the blockchain application are set.
Inside `app.genesisConfig` specific constants for the blockchain application are set.

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +
Should we add a specific message to indicate that the genesis creation and delegate accounts are not secure with this release? @Tschakki @MaciejBaj

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +The Lisk SDK operates on the NodeJS runtime and consists primarily of an application framework (Lisk Framework), a collection of libraries providing blockchain application functionalities (Lisk Eleme
tool (Lisk Commander) *which allows* developers to manage a Lisk node instance and interact with a Lisk compatible network.

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +| [Framework](lisk-framework/introduction.md) | The application framework is establishing and maintaining the interactions between the modules of a Lisk blockchain application.                     |
The application framework *establishes and maintains* the interactions between the modules of a Lisk blockchain application.

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +| [Commander](lisk-commander/introduction.md) | A command line tool allowing developers to manage a Lisk node instance and interact with a Lisk compatible network.                                  |
A command line tool *which allows* developers to manage a Lisk node instance and interact with a Lisk compatible network.

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +First steps to start developing your blockchain application:
*The* first steps to start developing your blockchain application:

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +Below you see the minimal version of `index.js` that is needed to successfully kick-start the blockchain application:
Below *is* the minimal version of `index.js` that is needed to successfully kick-start *a* blockchain application:

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +This should start the application with predefined default configurations, what will connect your app to a local Devnet.
This should start the application with *the* predefined default configurations,*which* will connect your app to a local *devnet*.

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +To test out your local changes of the Lisk SDK, use a blockchain application(e.g. [Lisk Core](../lisk-core/introduction.md)) as basis and link your locally customized `lisk-sdk`  to it.
To test out your local changes of the Lisk SDK, use a blockchain application(e.g. [Lisk Core](../lisk-core/introduction.md)) as basis *, and link it to your locally customized `lisk-sdk`.*

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +1) At root of `lisk-sdk` repo,  run `npx lerna link`
At root of *the* `lisk-sdk` repo,  run `npx lerna link`

2019-05-31 08:50 UTC, RachBLondon commented on introduction.md
> +1) If you have made changes in `elements` lib then make sure you run `npm run build` to see the changes
If you have made changes in *the* `elements` *library* then make sure you run `npm run build` to see the changes

*If we are using lib else where then we can go for that, but I thought library was more consistent*

2019-06-04 11:35 UTC, Tschakki commented on introduction.md
> +
Yes, ideally we should direct from here to the disclamie

2019-06-04 15:23 UTC, RachBLondon approved these changes

2019-06-04 15:33 UTC, merged