Create Log section, Closes #28
LiskArchive/lisk-legacy-docs pull request #215
Opened 2019-05-03 16:07 UTC by Tschakki

Closes #28

2019-05-13 15:17 UTC, shuse2 requested changes

2019-05-13 15:17 UTC, shuse2 commented on configuration.md
> +| None(>60) | No events are logged.                                                                                                       |
None doesnt have log level number

2019-05-13 15:17 UTC, shuse2 commented on setup/source.md
>  git clone https://github.com/LiskHQ/lisk-sdk.git
this should be `lisk-core`?

2019-05-14 07:27 UTC, Tschakki commented on setup/source.md
>  git clone https://github.com/LiskHQ/lisk-sdk.git
this is fixed in #217

2019-05-15 09:23 UTC, nazarhussain requested changes

2019-05-15 09:23 UTC, nazarhussain commented on monitoring.md
> +The [log files](configuration.md#file-log-stream) provide a chronological list of all events that happened on a node.
> list of all events 

Here events are something very specific to NodeJS events or module events we specified in our protocol. We rather use different term here. 

```suggestion
The [log files](configuration.md#file-log-stream) provide a chronological list of activities that happened on a node.
```

2019-05-15 09:23 UTC, nazarhussain commented on monitoring.md
> +These events can be analyzed further in order to provide monitoring for a particular node or for the network in general.
```suggestion
These activities can be analyzed further in order to provide monitoring for a particular node or for the network in general.
```

2019-05-15 09:23 UTC, nazarhussain commented on configuration.md
> +For monitoring or debugging your node, Lisk Core tracks all important events that happen on the node by creating log messages for them.
```suggestion
For monitoring or debugging your node, Lisk Core tracks all activity that happen in the node by creating log messages for them.
```

2019-05-16 13:28 UTC, nazarhussain submitted a review, later dismissed

2019-05-16 13:35 UTC, nazarhussain approved these changes

2019-05-16 13:36 UTC, merged