Create start page, Closes #200
LiskArchive/lisk-legacy-docs pull request #220
Opened 2019-05-13 10:43 UTC by Tschakki

Closes #200

2019-05-13 14:14 UTC, MaciejBaj commented on start.md
> +Beside the **Lisk Protocol**, you find all you need to **setup, run and configure** the different parts of the **Lisk ecosystem**.
```suggestion
Here you will find all you need to **setup, run and configure**  a Lisk Node and join the network. 
We also describe the **Lisk Protocol**  and **Lisk products**.
```

2019-05-13 14:15 UTC, MaciejBaj commented on start.md
> +## The Lisk Protocol
Move to the bottom.

2019-05-13 14:16 UTC, MaciejBaj commented on start.md
> +
Try referring to Lisk Academy chapters.

2019-05-13 14:18 UTC, MaciejBaj commented on start.md
> +Currently, the official implementations of the Lisk protocol are [Lisk Core](../lisk-core/introduction.md) and [Lisk Elements](../lisk-sdk/lisk-elements/introduction.md), which are written in Javascr
```suggestion
Currently, the official implementations of the Lisk protocol are [Lisk Core](../lisk-core/introduction.md) and [Lisk Elements](../lisk-sdk/lisk-elements/introduction.md), which are written in Typescript and [Lisk Framework](../lisk-sdk/lisk-framework/introduction.md) written in Javascipt.
```

2019-05-13 14:18 UTC, MaciejBaj commented on start.md
> +## The Lisk ecosystem
```suggestion
## Lisk products
```

2019-05-13 14:24 UTC, MaciejBaj commented on start.md
> +[Lisk SDK](../lisk-sdk/introduction.md) > [Lisk Framework](../lisk-sdk/lisk-framework/introduction.md) | Modular set of building blocks with specific blockchain related functionality.
```suggestion
[Lisk SDK](../lisk-sdk/introduction.md) |  Set of modular software products that provide developers with all the tools they need to develop their own custom blockchain applications.
[Lisk SDK](../lisk-sdk/introduction.md) > [Lisk Framework](../lisk-sdk/lisk-framework/introduction.md) | Modular set of building blocks with specific, blockchain-related, functionality.
```

2019-05-13 14:24 UTC, MaciejBaj commented on start.md
> +The Lisk Ecosystem consists of a set of modular software products that provide developers with all the tools they need to develop their own custom blockchain applications.
```suggestion
```

2019-05-13 14:24 UTC, MaciejBaj commented on start.md
> +It also consists of software that is needed to maintain and monitor the Lisk Main network.
```suggestion
```

2019-05-13 14:25 UTC, MaciejBaj commented on start.md
> +[Lisk SDK](../lisk-sdk/introduction.md) > [Lisk Commander](../lisk-sdk/lisk-commander/introduction.md) | CLI-tool to interact with the network.
```suggestion
[Lisk SDK](../lisk-sdk/introduction.md) > [Lisk Commander](../lisk-sdk/lisk-commander/introduction.md) | Command line tool to interact with the network and maintain a node.
```

2019-05-13 14:28 UTC, MaciejBaj commented on start.md
> +[Lisk SDK](../lisk-sdk/introduction.md) > [Lisk Elements](../lisk-sdk/lisk-elements/introduction.md)   | JS library for interacting with the network.
```suggestion
[Lisk SDK](../lisk-sdk/introduction.md) > [Lisk Elements](../lisk-sdk/lisk-elements/introduction.md)   | Set of libraries implementing Lisk protocol, contains all of the cryptography tools you may need to implement Lisk network interactions into your application.
```

2019-05-13 14:30 UTC, MaciejBaj commented on start.md
> +[Lisk Hub](../lisk-hub/introduction.md)                      | UI for users to interact with the network, e.g. to manage their accounts, or to send or receive tokens.
```suggestion
[Lisk Hub](../lisk-hub/introduction.md)                      | Lisk wallet and UI tool for users to interact with the network, e.g. to manage their accounts, send or receive tokens or vote for delegates.
```

2019-05-13 14:33 UTC, MaciejBaj commented on start.md
> +- Have your **private entry point** to [communicate](../lisk-core/api) with the network
```suggestion
- Have your **private entry point** to [communicate](../lisk-core/api) with the network, it's important if you are an **exchange** implementing LSK tokens.
```

2019-05-13 14:34 UTC, MaciejBaj commented on start.md
> +5. Build the frontend<br>
Remove that part for nm
```suggestion
```

2019-05-13 14:35 UTC, MaciejBaj commented on start.md
> +While your network is up and running, use [Lisk Commander](../lisk-sdk/lisk-commander/introduction.md) to interact with the network via the CLI (Command-Line-Interface).
Include a note of liskhq/cryptohraphy implemeting all of the needed crypto libraries

2019-05-13 14:36 UTC, MaciejBaj commented on start.md
> +It is also possible to create own custom Modules from scratch, if needed.
Mention architecture and following the interfaces specs so the modules can communicate

2019-05-13 14:45 UTC, MaciejBaj commented on start.md
> +Blockchain applications are applications that communicate with a blockchain network in the background.
```suggestion
Blockchain applications communicate within a network to agree upon which data is valid and should be stored and which should be rejected and bad actors potentially punished. The set of blockchain rules is already implemented by Lisk modules and libraries. By re-using them and implementing well-designed Lisk SDK Framework it's easy to compose new case-specific applications. Explore more great content of [Blockchain Business](https://lisk.io/academy/blockchain-business) in [Lisk Academy](https://lisk.io/academy).
```

2019-05-13 14:45 UTC, MaciejBaj commented on start.md
> +This blockchain network can be used as decentralized database layer to create, read, update or delete data within the system.
```suggestion
```

2019-05-13 14:45 UTC, MaciejBaj commented on start.md
> +A **pure blockchain application** has no central data storage at all, and all information that is needed to perform its actions is actually stored within the blockchain itself.
```suggestion
```

2019-05-13 14:45 UTC, MaciejBaj commented on start.md
> +A **hybrid blockchain application** may have certain data stored inside of a blockchain, but might additionally use centralized data storage solutions in certain areas.
```suggestion
```

2019-05-13 14:46 UTC, MaciejBaj commented on start.md
> +#### And why do I need it?
Remove for now.

2019-05-13 14:48 UTC, MaciejBaj commented on start.md
> +
Explore the packages of Elements and describe Lisk Client.

2019-05-13 14:48 UTC, MaciejBaj requested changes
Please address the left suggestions.

2019-05-14 08:39 UTC, Tschakki commented on start.md
> +While your network is up and running, use [Lisk Commander](../lisk-sdk/lisk-commander/introduction.md) to interact with the network via the CLI (Command-Line-Interface).
Why here?

2019-05-14 13:17 UTC, MaciejBaj commented on start.md
> +## The Lisk Protocol
Before the "Contribute" section.

2019-05-27 12:56 UTC, MaciejBaj requested changes

2019-05-27 12:56 UTC, MaciejBaj commented on start.md
> +[Build a blockchain application](build-blockchain-app.md)         | <PRE>1. Alpha SDK [step by step guide](build-blockchain-app.md#how-to-build-a-blockchain-application-with-the-lisk-sdk)<br>  a) How
Chapter names are not consistent with the file names, please do so and use the following titles:
1. How to set up and start Lisk SDK?
2. How to customise blockchain parameters to suit an application use-case?
3. How to add new custom transaction types to implement an application use-case?
4. How to interact with the network?

2019-05-27 12:56 UTC, MaciejBaj commented on start.md
> +[Maintain a node](maintain-node.md)                               | <PRE>1. [Deploy](maintain-node.md#how-to-set-up-a-node) your first blockchain node in 5 minutes<br>2. Maintain your existing \[[Bin
Same as above - please unify the section file names and titles. Also, make the full sentences being the link here - "How to set up a node"

2019-05-27 12:56 UTC, MaciejBaj commented on start.md
> +[Lisk SDK](../lisk-sdk/introduction.md)                      |  Set of modular software products that provide developers with all the tools they need to develop their own custom blockchain applicatio
In descriptions please reflect the GitHub READMEs: https://github.com/LiskHQ/lisk-sdk

2019-05-31 14:18 UTC, RachBLondon requested changes

2019-05-31 14:18 UTC, RachBLondon commented on resources.md
> +- [LiskHQ Github](https://github.com/LiskHQ) - Source code of all software products of Lisk.
```suggestion
- [LiskHQ Github](https://github.com/LiskHQ) - Source code for all software products of Lisk.
```

2019-05-31 14:18 UTC, RachBLondon commented on resources.md
> +- [LiskHQ NPM packages](https://www.npmjs.com/~lisk) - List of all published NPM packages of LiskHQ.
```suggestion
- [LiskHQ NPM packages](https://www.npmjs.com/~lisk) - Lists all NPM packages published by LiskHQ.
```

2019-05-31 14:18 UTC, RachBLondon commented on resources.md
> +- [Roadmap](https://lisk.io/roadmap) - Explore the development roadmap as we make progress towards the SDK
```suggestion
- [Roadmap](https://lisk.io/roadmap) - Explore Lisk's development roadmap. 
```

2019-05-31 14:18 UTC, RachBLondon commented on resources.md
> +- [Lisk Improvement Proposals](https://github.com/LiskHQ/lips) - A collection of proposed improvements to the Lisk protocol
```suggestion
- [Lisk Improvement Proposals](https://github.com/LiskHQ/lips) - A collection of proposed improvements to the Lisk protocol.
```

2019-05-31 15:16 UTC, RachBLondon commented on resources.md
> +Join the community!
```suggestion
Join our community!
```

2019-05-31 15:17 UTC, RachBLondon commented on resources.md
> +Below are the most essential links to the official Lisk community channels.
```suggestion
Below are the essential links to the Lisk community channels.
```

2019-05-31 15:19 UTC, RachBLondon commented on start.md
> +For each product we provide a general introduction, step-by-step How-Tos and detailed specifications.
```suggestion
For each product we provide a general introduction, step-by-step guides and detailed specifications.
```

2019-05-31 15:35 UTC, RachBLondon commented on start.md
> +[Interact with the network](interact-with-network.md)             | Interact with the blockchain network through the [API](https://lisk.io/documentation/lisk-core/api) and install useful [tools](inte
```suggestion
[Interact with the network](interact-with-network.md)             | Interact with the blockchain network through its [API](https://lisk.io/documentation/lisk-core/api) and install useful [tools](interact-with-network.md#a-use-the-command-line) to facilitate the process.
```

2019-05-31 15:38 UTC, RachBLondon submitted a review, later dismissed

2019-06-04 13:35 UTC, RachBLondon commented on resources.md
> +- [Subscribe to the Lisk newsletter](https://mailchi.mp/lisk/newsletter) - Updates straight to your inbox
```suggestion
- [Subscribe to our Lisk newsletter](https://mailchi.mp/lisk/newsletter) - Updates straight to your inbox
```

2019-06-04 13:38 UTC, RachBLondon approved these changes

2019-06-04 15:37 UTC, merged