Interact with the network, Closes #201
LiskArchive/lisk-legacy-docs pull request #227
Opened 2019-05-21 09:24 UTC by Tschakki

Closes #201

2019-05-31 13:46 UTC, RachBLondon requested changes

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +- __Developers__ test and prove the functionality of their blockchain application. For quick interaction we recommend to use [Lisk Commander](#a-use-the-command-line).
```suggestion
- __Developers__ test and improve the functionality of their blockchain application. For quick interaction we recommend to use [Lisk Commander](#a-use-the-command-line).
```

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +> The following tools are suited for interacting with the Main- and Testnet of Lisk, but they can be used for interaction with other blockchain applications that have been developed with the Lisk SDK
```suggestion
> The following tools are suited for interacting with the Mainnet and Testnet of Lisk, but they can be used for interaction with other blockchain applications that have been developed with the Lisk SDK as well
```

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +It consists of wallet functionalities like sending transactions and view account history, and more extended features like delegate voting or registering as a delegate.
```suggestion
It consists of wallet functionalities like sending transactions and viewing account history, as well as more extended features like delegate voting or registering as a delegate.
```

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +> When hitting the "Try it out" button beside each endpoint, it is possible to execute the corresponding API request and get a live response from the Lisk Testnet.
```suggestion
> When hitting the "Try it out" button beside each endpoint, it is possible to execute the corresponding API request and get a live response from Lisk Testnet.
```

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +> It will also display the corresponding Curl command to make the request from the Command-line
```suggestion
> It will also display the corresponding curl command to make the request from the command-line
```

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +To change this, it is possible to define exclusive [whitelists](../lisk-core/configuration#api-access-control), that allow specific addresses to perform API requests on the node.
```suggestion
To change this, it is possible to define exclusive [whitelists](../lisk-core/configuration#api-access-control), that allows specific addresses to perform API requests on the node.
```

2019-05-31 13:46 UTC, RachBLondon commented on interact-with-network.md
> +[Lisk Service](https://github.com/LiskHQ/lisk-service) combines various services in the Lisk ecosystem and makes it available through an extended API with a bigger selection of endpoints.
```suggestion
[Lisk Service](https://github.com/LiskHQ/lisk-service) combines various services in the Lisk ecosystem and makes it available through an extended API with a larger selection of endpoints.
```

2019-05-31 15:07 UTC, Tschakki commented on interact-with-network.md
> +To change this, it is possible to define exclusive [whitelists](../lisk-core/configuration#api-access-control), that allow specific addresses to perform API requests on the node.
`allow` should be correct here or not?

2019-05-31 15:48 UTC, RachBLondon commented on interact-with-network.md
> +To change this, it is possible to define exclusive [whitelists](../lisk-core/configuration#api-access-control), that allow specific addresses to perform API requests on the node.
allows is correct in this context 👍

2019-06-04 07:47 UTC, RachBLondon submitted a review, later dismissed

2019-06-04 07:47 UTC, RachBLondon commented on interact-with-network.md
> +There are several groups that need/want to interact with the network. Below you find a list with the most relevant groups and their recommended tools:
```suggestion
There are several groups that need/want to interact with the network. Below is a list with the most relevant groups and their recommended tools:
```

2019-06-04 07:47 UTC, RachBLondon commented on interact-with-network.md
> +- __Exchanges__ interact heavily with the network, e.g. by transferring tokens for their customers. For exchanges, it is recommended to [set up their own node](maintain-node.md) to interact with the
```suggestion
- __Exchanges__ interact heavily with the network, e.g. by transferring tokens for their customers. Exchanges are recommended to [set up their own node](maintain-node.md) to interact with the network reliably.
```

2019-06-04 07:47 UTC, RachBLondon commented on interact-with-network.md
> +> The following tools are suited for interacting with the Mainnet and Testnet of Lisk, but they can be used for interaction with other blockchain applications that have been developed with the Lisk S
```suggestion
> The following tools are suited for interacting with the Mainnet and Testnet of Lisk, but they can be used to interact with other blockchain applications that have been developed using the Lisk SDK.
```

2019-06-04 07:47 UTC, RachBLondon commented on interact-with-network.md
> +You can choose from up to 5 ways to interact with an existing network based on what is most convenient for your case:
```suggestion
You can choose from up to 5 ways to interact with an existing network based on what is most convenient for your needs:
```

2019-06-04 07:47 UTC, RachBLondon commented on interact-with-network.md
> +> It will also display the corresponding curl command to make the request from the command-line
```suggestion
> It will also display the corresponding curl command to make the request from the command-line.
```

2019-06-04 07:47 UTC, RachBLondon commented on interact-with-network.md
> +To change this, it is possible to define exclusive [whitelists](../lisk-core/configuration#api-access-control), that allow specific addresses to perform API requests on the node.
```suggestion
To change this, it is possible to define exclusive [whitelists](../lisk-core/configuration#api-access-control), that allow specific addresses to perform API requests on that node.
```

2019-06-04 09:22 UTC, RachBLondon approved these changes

2019-06-04 10:37 UTC, merged