Create 'build blockchain application' page, Closes #203
LiskArchive/lisk-legacy-docs pull request #231
Opened 2019-05-21 14:54 UTC by Tschakki

Closes #203

2019-05-29 05:37 UTC, MaciejBaj commented on build-blockchain-app.md
> +## How to build a blockchain application with the Lisk SDK
```suggestion
## How to build a blockchain application with the Lisk SDK?
```

2019-05-29 05:48 UTC, MaciejBaj requested changes

2019-05-29 05:48 UTC, MaciejBaj commented on build-blockchain-app.md
> +### 3. Build the frontend
```suggestion
### 3. How to interact with my network?
```

2019-05-29 05:48 UTC, MaciejBaj commented on build-blockchain-app.md
> +#### 2.c Write own Modules
Let's have this part only in the framework section.

It's better to focus on the most important and fully supported parts of the SDK on the introduction page, i.e.:
1. Customise blockchain parameters to suit an application use-case
2. Add new custom transaction types to implement an application use-case

2019-05-29 05:48 UTC, MaciejBaj commented on build-blockchain-app.md
> +### 2. Configure and customize the application
## Add new **custom transaction** types to implement an application use-case

2019-05-29 05:48 UTC, MaciejBaj commented on build-blockchain-app.md
> +#### 2.b Design custom transaction types
```suggestion
```

2019-05-29 05:48 UTC, MaciejBaj commented on build-blockchain-app.md
> +#### 2.a Configure Modules and Components
## Customise blockchain parameters to suit an application use-case

2019-05-29 05:48 UTC, MaciejBaj commented on build-blockchain-app.md
> +After the first successful start, feel free to [configure](../lisk-sdk/lisk-framework/introduction.md#configuration) the [Modules](../lisk-sdk/lisk-framework/introduction.md#modules) and [Components]
Start from the genesis config.

Introduce the full config of the modules, mention it's the same process as configuring a network node.

2019-05-29 08:05 UTC, Tschakki commented on build-blockchain-app.md
> +### 2. Configure and customize the application
about headings, maybe @LindsaysDarkAlley can give some feedback here. I personally prefer more catchy headings than long ones.

2019-05-29 08:09 UTC, Tschakki commented on build-blockchain-app.md
> +### 3. Build the frontend
```suggestion
### 3. Interact with the network
```

2019-05-29 08:10 UTC, Tschakki commented on build-blockchain-app.md
> +#### 2.b Design custom transaction types
What should this be replaced with?

2019-05-29 08:20 UTC, Tschakki commented on build-blockchain-app.md
> +After the first successful start, feel free to [configure](../lisk-sdk/lisk-framework/introduction.md#configuration) the [Modules](../lisk-sdk/lisk-framework/introduction.md#modules) and [Components]
I do explain this on the `configuration.md` page of the Lisk SDK. See my other open PR: #209 
https://github.com/LiskHQ/lisk-docs/blob/205-sdk-introduction/configuration.md

Above, I link to this file, so all information should be there.

2019-05-31 10:11 UTC, Tschakki commented on build-blockchain-app.md
> +## How to build a blockchain application with the Lisk SDK
I wouldn't add the `?` here, imho

2019-05-31 13:17 UTC, RachBLondon requested changes

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Blockchain applications communicate within a network to agree upon which data is valid and should be stored, or whether it should be rejected and bad actors potentially punished.
```suggestion
Blockchain applications communicate within a network to agree upon which data is valid and therefore should be stored, or whether it should be rejected and bad actors potentially punished.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Explore more great content of Blockchain Business in [Lisk Academy](https://lisk.io/academy/blockchain-business/blockchain-in-business).
```suggestion
For more information on use-cases visit Blockchain Business in [Lisk Academy](https://lisk.io/academy/blockchain-business/blockchain-in-business).
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +- [Lisk Framework](../lisk-sdk/lisk-framework/introduction.md): Consists of a selection of various Modules and Components which each provide specific functionality or logic related to blockchain netw
```suggestion
- [Lisk Framework](../lisk-sdk/lisk-framework/introduction.md): Consists of a selection of various Modules and Components which each provide specific functionality or logic for use in blockchain networks.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +The blockchain application is built in 3 steps:
```suggestion
Blockchain applications can be built in 3 steps:
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +To get started in building a blockchain application, [set up the Lisk SDK](../lisk-sdk/introduction.md#setup).
```suggestion
To get started building a blockchain application, [set up the Lisk SDK](../lisk-sdk/introduction.md#setup).
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +The [Modules](../lisk-sdk/lisk-framework/introduction.md#modules) and [Components](../lisk-sdk/lisk-framework/introduction.md#components) of the [Lisk Framework](../lisk-sdk/lisk-framework/introducti
```suggestion
The [Modules](../lisk-sdk/lisk-framework/introduction.md#modules) and [Components](../lisk-sdk/lisk-framework/introduction.md#components) of [Lisk Framework](../lisk-sdk/lisk-framework/introduction.md) come with a set of predefined default configurations, allowing you to start and test your network immediately.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +To get the blockchain application started for the first time, follow the steps described in the [Lisk SDK - Usage](../lisk-sdk/introduction.md#usage) section.
```suggestion
To get your blockchain application started for the first time, follow the steps described in the [Lisk SDK - Usage](../lisk-sdk/introduction.md#usage) section.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +After the first successful start, feel free to [configure](../lisk-sdk/lisk-framework/configuration.md) the [Modules](../lisk-sdk/lisk-framework/introduction.md#modules) and [Components](../lisk-sdk/
```suggestion
After the first successful start, feel free to [configure](../lisk-sdk/lisk-framework/configuration.md) the [Modules](../lisk-sdk/lisk-framework/introduction.md#modules) and [Components](../lisk-sdk/lisk-framework/introduction.md#components) to suit your specific needs.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +It is possible as well to exchange Modules with other ones, or to add new Modules that provide new functionality.
```suggestion
It is also possible to exchange Modules with different ones, or to add new Modules to provide additional functionality.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +To see which ready-to-use Modules and Components already exist, check out the [list of Modules](../lisk-sdk/lisk-framework/introduction.md#list-of-core-modules) and the [list of Components](../lisk-s
```suggestion
To view the list of currently available ready-to-use Modules and Components, check out this [list of Modules](../lisk-sdk/lisk-framework/introduction.md#list-of-core-modules) and this [list of Components](../lisk-sdk/lisk-framework/introduction.md#components).
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Transactions are the main way for users to add data to the blockchain.
```suggestion
Transactions are the main way for users to add data to their blockchain.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +The most basic transaction types that are part of nearly any blockchain are for example a transaction type for creating a new account on the network, or a transaction type to send tokens from one acc
```suggestion
The most basic transaction types are part of almost all blockchains, for example a transaction type for creating new accounts on the network, or a transaction type to send tokens from one account to another.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Depending on the use-case for your network, you need to pick the fitting transaction types for your application.
```suggestion
You can choose the appropriate transaction types for your application and its use-case.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +For comparison, see a [list of all transaction types](../lisk-protocol/transactions), which are implemented in the Lisk Protocol.
```suggestion
For comparison, please view the [list of all transaction types](../lisk-protocol/transactions) which are implemented in the Lisk Protocol.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +See the [Examples page](examples.md) for creating custom transaction types and how to add them to the application.
```suggestion
See the [Examples page](examples.md) for creating custom transaction types and how to add them to your application.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Depending on the level of customization, it might be needed to customize the Lisk Explorer and Lisk Commander as well, or otherwise certain services might fail.
```suggestion
Depending on the level of customization, Lisk Explorer and Lisk Commander may require some configuration to prevent certain services from failing.
```
We can't say specifically which services these might be, right?

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Another simple way to make first interactions with the network is by connecting to it with [Lisk Hub](https://github.com/LiskHQ/lisk-hub).
```suggestion
Another simple way to interact with the network is by connecting to it with [Lisk Hub](https://github.com/LiskHQ/lisk-hub).
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +Lisk Hub provides a simple and beautiful User Interface to create and manage accounts in the network and to interact with it by sending different types of transactions.
```suggestion
Lisk Hub provides a simple and beautiful user interface to create and manage accounts in the network and to interact with it by sending different types of transactions.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +When everything works as expected, it is time to build a nice frontend for your application, so that users are happy to use it.
```suggestion
Once your blockchain is finished, and it is possible to send the transactions and custom transactions your use case requires,  you can create a frontend to allow users to interact and use your blockchain application.
```

2019-05-31 13:17 UTC, RachBLondon commented on build-blockchain-app.md
> +To let your frontend interact with the network, we recommend to make use of [Lisk Elements' packages](../lisk-sdk/lisk-elements/packages.md) like [lisk-api-client](../lisk-sdk/lisk-elements/packages/
```suggestion
To connect your frontend to your network, we recommend to make use of [Lisk Elements' packages](../lisk-sdk/lisk-elements/packages.md) like [lisk-api-client](../lisk-sdk/lisk-elements/packages/api-client.md).
```

2019-05-31 13:17 UTC, RachBLondon commented on examples.md
> +A simple application which is rewarding it's users for sending tokens.
```suggestion
A simple application which rewards its users for sending tokens. 
```

2019-05-31 13:17 UTC, RachBLondon commented on examples.md
> +It extends the already existing transaction type `TransferTransaction`.
```suggestion
It extends the pre-existing transaction type `TransferTransaction`.
```

2019-05-31 13:17 UTC, RachBLondon commented on examples.md
> +The here Cashback transaction type return half of the amount of tokens that are transferred back to the senders account.
```suggestion
Here the Cashback transaction type pays out a 50% bonus reward to the sender of any Cashback transaction type.
```

2019-05-31 15:23 UTC, Tschakki commented on build-blockchain-app.md
> +Depending on the level of customization, it might be needed to customize the Lisk Explorer and Lisk Commander as well, or otherwise certain services might fail.
no, this depends on the level of customization and what is customized, so could be nearly anything ;) I would stick to term `customization`, as `configuration` indicates for me, I can just set some configuration options differently and it will work again, but that's not always the case as normally the user would need to fork the project and make the changes inside of the code logic.

```suggestion
Depending on the level of customization, Lisk Explorer and Lisk Commander may require some customization to prevent certain services from failing.
```

2019-06-03 12:31 UTC, RachBLondon commented on build-blockchain-app.md
> +Depending on the level of customization, it might be needed to customize the Lisk Explorer and Lisk Commander as well, or otherwise certain services might fail.
```suggestion
Depending on the level of customization,  Lisk Explorer and Lisk Commander as well, or otherwise certain services might fail.
```





```suggestion
Depending on the level of customization, Lisk Explorer and Lisk Commander may also require customization to prevent other services from failing.
```

OK makes sense, how about he above?

2019-06-03 12:39 UTC, RachBLondon submitted a review, later dismissed

2019-06-03 12:39 UTC, RachBLondon commented on build-blockchain-app.md
> +Another simple way to interact with the network is by connecting to it with [Lisk Hub](https://github.com/LiskHQ/lisk-hub).
```suggestion
Another simple way to interact with the network is by connecting it to [Lisk Hub](https://github.com/LiskHQ/lisk-hub).
```

2019-06-03 12:39 UTC, RachBLondon commented on build-blockchain-app.md
> +Lisk Hub provides a simple and beautiful user interface to create and manage accounts in the network and to interact with it by sending different types of transactions.
```suggestion
Lisk Hub provides a simple and beautiful user interface to create and manage accounts on the network, and also to interact with the network by sending different types of transactions.
```

2019-06-03 12:39 UTC, RachBLondon commented on build-blockchain-app.md
> +Once your blockchain is finished, and it is possible to send the transactions and custom transactions your use case requires,  you can create a frontend to allow users to interact and use your blockc
```suggestion
Once your blockchain is finished, and it is possible to send the transactions (and custom transactions), you can create a frontend to allow users to interact and use your blockchain application.
```

2019-06-04 09:33 UTC, RachBLondon commented on examples.md
> +A simple App, showcasing a minimal setup of a blockchain application with 1 custom transaction type: the "Hello" transaction.
```suggestion
A simple App, showcasing a minimal setup of a blockchain application with 1 custom transaction type: the "HelloWorld" transaction.
```

2019-06-04 10:22 UTC, Tschakki commented on examples.md
> +A simple App, showcasing a minimal setup of a blockchain application with 1 custom transaction type: the "Hello" transaction.
imho it should be clear enough. See my comment here https://github.com/LiskHQ/lisk-docs/pull/247#discussion_r290220964

2019-06-04 15:27 UTC, RachBLondon approved these changes

2019-06-04 15:39 UTC, merged