Add Commander option on Binary setup page, Closes #240
LiskArchive/lisk-legacy-docs pull request #241
Opened 2019-05-23 16:05 UTC by Tschakki

Closes #240

2019-05-24 12:04 UTC, ManuGowda commented on setup/binary.md
> +| Mainnet | 8000           | 8001        |
For the commander, the port can be different, based on the installation, I am not sure how to document that, but after the installation `lisk core:status NAME` will the details about port related to the specific installation.
@fchavant what's your thought on this? how can we convey it?

2019-05-24 12:23 UTC, fchavant commented on setup/binary.md
> +| Mainnet | 8000           | 8001        |
Mark this as relevant only installations performed with `installLisk.sh`?

2019-05-24 14:54 UTC, ghost requested changes

2019-05-24 14:54 UTC, fchavant commented on setup/binary.md
>  - Ubuntu 18.04 x86_64
```suggestion
- Ubuntu 18.04 (LTS) x86_64
```

2019-05-24 14:54 UTC, fchavant commented on setup/binary.md
> +| Mainnet | 8000           | 8001        |
To be clear: users that installed Core using `lisk core:install` will still need to open up 2 ports but those are not static. They will need to find out which ports to open with `lisk core:status`.

2019-05-24 15:03 UTC, Tschakki commented on setup/binary.md
> +| Mainnet | 8000           | 8001        |
So they can only know which ports to open, after they installed it?
Should I add this as post-installation step then?

2019-05-24 15:07 UTC, fchavant commented on setup/binary.md
> +| Mainnet | 8000           | 8001        |
> So they can only know which ports to open, after they installed it?

That is my understanding. @ManuGowda can confirm.

> Should I add this as post-installation step then?

Yes

2019-05-27 12:12 UTC, ManuGowda commented on setup/binary.md
> +| Mainnet | 8000           | 8001        |
yes, the user can know the ports after installation using `status` command.

2019-05-27 15:38 UTC, fchavant commented on upgrade/binary.md
> +lisk core:upgrade <location>
`lisk core:upgrade --help` prints:
```
USAGE
  $ lisk core:upgrade NAME
[...]
```

2019-05-27 15:46 UTC, Tschakki commented on upgrade/binary.md
> +lisk core:upgrade <location>
yes but `location` is more precise imo, as it is the name of the root folder of the node.

also, we explain precisely what is meant here in the line below.

2019-05-27 15:50 UTC, ghost approved these changes

2019-05-27 15:53 UTC, merged