Split up tutorials into several pages, Closes #252
LiskArchive/lisk-legacy-docs pull request #253
Opened 2019-06-05 14:40 UTC by Tschakki

Closes #252

2019-06-06 16:12 UTC, RachBLondon commented on build-blockchain-app.md
> +- [Hello World App](tutorials/hello-world.md): A very basic example of a Lisk blockchain application with 1 custom transaction type.
```suggestion
- [Hello World App](tutorials/hello-world.md): A example of a Lisk blockchain application with 1 custom transaction type, which extends the BaseTransaction type.
```
I have changed the wording, to make not appear that it is more simple than the Cashback transaction.

2019-06-06 16:18 UTC, RachBLondon commented on build-blockchain-app.md
> +- [Cashback App](tutorials/cashback.md): A simple example blockchain app, that implements the new transaction type `Cashback`.
```suggestion
- [Cashback App](tutorials/cashback.md): A more practical example creating the new transaction type `Cashback`. Cashback extends the pre-existing transaction type TransferTransaction, making for a straightforward implementation.
```
Re-worded to give some more context to the tutorial

2019-06-07 14:56 UTC, RachBLondon commented on tutorials/hello-world.md
> +## 6. Interact with the network
Not part of the changes in the PR - but do we need to import 
```
const { validateAddress, validatePublicKey } = require('@liskhq/lisk-validator');
const { getAddressFromPublicKey } = require('@liskhq/lisk-cryptography');
```
on line 332 and 333?

2019-06-07 15:25 UTC, RachBLondon commented on tutorials/cashback.md
> +First, let's reuse the script [create_sendable_transaction.js](https://github.com/LiskHQ/lisk-sdk-examples/blob/development/scripts/create_sendable_transaction_base_trs.js) which we already described
```suggestion
First, let's reuse the script [create_sendable_transaction.js](https://github.com/LiskHQ/lisk-sdk-examples/blob/development/scripts/create_sendable_transaction_base_trs.js) which was created in step 6 of the other example application [Hello World](#6-interact-with-the-network).
```

2019-06-07 15:29 UTC, RachBLondon submitted a review, later dismissed

2019-06-12 13:20 UTC, RachBLondon requested changes

2019-06-12 13:20 UTC, RachBLondon commented on tutorials.md
> +A hello world application of the alpha SDK.
```suggestion
A hello world application built using the alpha SDK.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials.md
> +The example of a simple but valid use-case - cashback.
```suggestion
The example of a simple but valid use-case - a cashback transaction.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials.md
> +On top of the regular balance transfer, the example implements the cashback functionality.
```suggestion
Built by extending the balance transfer transaction, in addition to the regular transfer functionality, the cashback transaction also applies an inflationary 10% to senders account.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials.md
> +Explains how to create a new transaction type that inherits from an already existing transaction type.
```suggestion
This example shows you how to create a new custom transaction inheriting from a pre-existing transaction type.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials.md
> +- [Full code example of Cashback app](https://github.com/LiskHQ/lisk-sdk-examples/tree/development/cashback) on Github.
```suggestion
- [A full example Cashback application's codebase ](https://github.com/LiskHQ/lisk-sdk-examples/tree/development/cashback) is available Github.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials.md
> +- [Cashback Tutorial](tutorials/hello-world.md)
```suggestion
- [Cashback Tutorial](tutorials/cashback.md)
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +- __Steps 1-5__ describe what needs to be implemented on the server-side of the blockchain application.
```suggestion
- __Steps 1-5__ describes the sever-side implementation of the blockchain application.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +- __Step 6__ explains how to interact with the network from the client-side.
```suggestion
- __Step 6__  shows how to interact with the network from the (blockchain) client-side using a node script.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +> Check out the __full code example__ for the [Cashback App on Github](https://github.com/LiskHQ/lisk-sdk-test-app/cashback).
```suggestion
> Check out the __full code example__ of the [Cashback App on Github](https://github.com/LiskHQ/lisk-sdk-test-app/cashback).
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +Create 2 folders `client` and `server`, which will hold the corresponding scripts for the blockchain application.
```suggestion
Create two folders `client` and `server`, which will hold the corresponding scripts for the blockchain application.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +mkdir client server # create the 2 folder inside the root directory of your blockchain application
```suggestion
mkdir client server # creates the folder inside the root directory of your blockchain application
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +Next, let's configure the application, to provide basic information about the app we are going to build:
```suggestion
Next, let's configure the application, to provide basic information about the application we are going to build:
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +In the `line 2`, we require the needed dependencies from the `lisk-sdk` package.
```suggestion
On `line 2`, we require the needed dependencies from the `lisk-sdk` package.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +The application instance will start the whole application at the bottom of `index.js`.
```suggestion
The application instance is used to start the blockchain application at the bottom of `index.js`.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +By passing the parameters for the [genesis block](../lisk-sdk/configuration.md) and the [configuration template](https://github.com/LiskHQ/lisk-sdk/blob/development/sdk/src/samples/config_devnet.json
```suggestion
By passing the parameters for the [genesis block](../lisk-sdk/configuration.md) and the [configuration template](https://github.com/LiskHQ/lisk-sdk/blob/development/sdk/src/samples/config_devnet.json), the application is configured with the most basic configurations to start the node.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +In difference to the normal `TransferTransaction`, the Cashback transaction type pays out a 10% bonus reward to the sender of any Cashback transaction type.
```suggestion
The difference between the regular `TransferTransaction` and the `CashbackTransaction`, is that Cashback transaction type also pays out a 10% bonus reward to its sender.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +> If you compare the methods below with the methods we implemented for the `HelloTransaction`, you will notice, that we implement less methods for the `CashbackTransaction`.
```suggestion
> If you compare the methods below with the methods we implemented in the `HelloTransaction`, you will notice, that we implement fewer methods for the `CashbackTransaction`.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +> As a result, all required methods are implemented already inside the `Transfertransaction` class, and we only need to overwrite/extend explicitely the methods we want to customize.
```suggestion
> As a result, all required methods are implemented already inside the `TransferTransaction` class, and we only need to overwrite/extend explicitely the methods we want to customize.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +If something went wrong, the process should stop and an error with debug information is displayed.
```suggestion
If an error occurs, the process should stop and the error with debug information will be displayed.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +If everything is ok, you should be able to see the following console logs:
```suggestion
If everything is ok, the following logs will be displayed:
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +Now that the network is started, let's try to send a `CashbackTransaction` to our node to see if it gets accepted.
```suggestion
Now that your network is running, let's try to send a `CashbackTransaction` to our node to see if it gets accepted.
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +First, let's reuse the script [create_sendable_transaction_base_trs.js](https://github.com/LiskHQ/lisk-sdk-examples/blob/development/scripts/create_sendable_transaction_base_trs.js) which we already
```suggestion
First, let's reuse the script [create_sendable_transaction_base_trs.js](https://github.com/LiskHQ/lisk-sdk-examples/blob/development/scripts/create_sendable_transaction_base_trs.js) which we already described in [step 6 of Hello World app](/hello-world.md#6-interact-with-the-network).
```
👆 Not sure if that link is correct, but I think it needs changing to point to the Hello World tutorial.

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +We can use this function in our script for printing a sendable `CashbackTransaction` object:
```suggestion
We can call the `createSendableTransaction` function to print a sendable `CashbackTransaction` object:
```

2019-06-12 13:20 UTC, RachBLondon commented on tutorials/cashback.md
> +For this, we utilize the API of the node and post the created transaction object to the transaction endpoint of the API.
```suggestion
For this, we utilize the http API of the node and post the created transaction object to the transaction endpoint of the API.
```

2019-06-12 13:28 UTC, Tschakki commented on tutorials/cashback.md
> +First, let's reuse the script [create_sendable_transaction_base_trs.js](https://github.com/LiskHQ/lisk-sdk-examples/blob/development/scripts/create_sendable_transaction_base_trs.js) which we already
@RachBLondon: This part of docs might be outdated soon, when this branch is merged: https://github.com/LiskHQ/lisk-sdk/compare/release/2.1.0...3739-create_sendable

I hope it gets merged today :)

2019-06-12 16:13 UTC, RachBLondon approved these changes

2019-06-13 07:40 UTC, merged