Update postgreSQL commands, Closes #276
LiskArchive/lisk-legacy-docs pull request #277
Opened 2019-06-24 11:55 UTC by Tschakki

Closes #276

2019-06-25 12:45 UTC, RachBLondon requested changes

2019-06-25 12:45 UTC, RachBLondon commented on setup/source.md
> +This is a simple way to install postgres on your machine.
```suggestion
Running Postgres inside a Docker container will setup the correct version of Postgres and containerize it away from any existing versions you may have locally on your machine. Chose this setup if you are not familiar with Postgres, or if you run in to issues with a previously installed version of Postgres.
```

2019-06-26 17:14 UTC, 4miners submitted a review, later dismissed

2019-06-27 13:54 UTC, RachBLondon submitted a review, later dismissed

2019-06-27 14:56 UTC, RachBLondon approved these changes

2019-06-28 07:44 UTC, merged