Chris1
LiskArchive/lisk-legacy-docs pull request #375
Opened 2019-12-03 14:49 UTC by chris529

grammar and punctuation updates

2019-12-10 14:59 UTC, Tschakki requested changes
Thank you very much!

Only a few small remarks/suggestions from my side :)

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The default database name is `lisk_dev`, so for the development purposes, a command `createdb lisk_dev` must be used for the set up.
```suggestion
The default database name is `lisk_dev`, so for the development purposes, a command `createdb lisk_dev --owner lisk` must be used for the set up.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +<1> Require the Lisk-SDK package.
We should either write `lisk-sdk` when referring to the NPM package, or Lisk SDK when we talk about the product in general. "Lisk-SDK" I would avoid if possible.

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +<2> Install the Lisk-SDK package as dependency of your project.
We should either write lisk-sdk when referring to the NPM package, or Lisk SDK when we talk about the product in general. "Lisk-SDK" I would avoid if possible.

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Ensure the installed dependencies of the Lisk-SDK are completed beforehand.
Same here.

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Installation of the Lisk Alpha SDK is straightforward and limited to getting a single NPM package, `lisk-sdk`, to your Node.js project:
Remove "Alpha" here

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
>  Another simple way to interact with the network is by connecting it to https://github.com/LiskHQ/lisk-hub[Lisk Hub].
Rename to `Lisk Desktop`
```suggestion
Another simple way to interact with the network is by connecting it to https://github.com/LiskHQ/lisk-desktop[Lisk Desktop].
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Lisk Hub provides a simple and user-friendly interface to create and manage accounts on the network, and also to interact with the network by sending different types of transactions.
```suggestion
Lisk Desktop provides a simple and user-friendly interface to create and manage accounts on the network, and also to interact with the network by sending different types of transactions.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/lisk-framework/index.adoc
> +Multiple modules can be defined by using commas, as shown below: `LISK_CHILD_PROCESS_MODULES=httpApi,chain`.
It's not really below, it's on same line, maybe just remove that
```suggestion
Multiple modules can be defined by using commas: `LISK_CHILD_PROCESS_MODULES=httpApi,chain`.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/cashback.adoc
> +The next step  is to provide the basic information about the application to be built.
```suggestion
The next step is to provide the basic information about the application to be built.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/cashback.adoc
> +The default database name is lisk_dev, so for the development purposes, a command createdb lisk_dev can be used.
```suggestion
The default database name is lisk_dev, so for the development purposes, a command `createdb lisk_dev --owner lisk` can be used.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +Firstly, a simple App can be used which showcases a minimal setup of a blockchain application with 1 xref:customize.adoc[custom transaction] type: the "Hello" transaction.
```suggestion
The Hello World application is a simple blockchain app that showcases a minimal setup of a blockchain application with 1 xref:customize.adoc[custom transaction] type: the "Hello" transaction.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +Welcome to the step-by-step guide of creating the Hello World application with the Lisk Alpha SDK.
```suggestion
Welcome to the step-by-step guide of creating the Hello World application with the Lisk SDK.
```

2019-12-10 14:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +The default database name is `lisk_dev` The following command,  `createdb lisk_dev` should be used.
```suggestion
The default database name is `lisk_dev` The following command,  `createdb lisk_dev --owner lisk` should be used.
```

2019-12-10 16:13 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +<1> Require the Lisk-SDK package.
Good point Mona.

2019-12-10 16:24 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +<1> Require the Lisk-SDK package.
Agreed

2020-01-06 10:49 UTC, Tschakki approved these changes

2020-01-06 10:52 UTC, merged