New protocol documentation.
LiskArchive/lisk-legacy-docs pull request #380
Opened 2019-12-19 10:35 UTC by janhack

2020-01-16 11:01 UTC, AndreasKendziorra requested changes

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
> +At its core, a [#index-blockchain-1]#*blockchain*# is a database shared across multiple computers. Operations on the database are called *transactions*. The data contained in a transaction specifies
```suggestion
At its core, a [#index-blockchain-1]#*blockchain*# is a database shared across multiple computers. Operations on the database are called *transactions*. The data contained in a transaction specifies the operation to be performed. Generally speaking, users are allowed to perform operations on their [#index-accounts-1]#*accounts*#, corresponding to a portion of the database identified by their account [#index-address-1]#*address*#. The cost of processing the transaction and updating the blockchain is specified in the transaction fee and paid using [#index-tokens-1]#*tokens*#. Transactions are shared among users connected in a [#index-P2P_network-1]#*P2P network*# and are grouped together into [#index-blocks-1]#*blocks*#. The validity of a block (and therefore of all transactions within it) is determined against the accounts state. The [#index-consensus_protocol-1]#*consensus protocol*# specifies who has the right to [#index-forge-1]#*forge*# a new block and how agreement on the validity of a block is reached. After the block has been forged, it is added to the blockchain, and all state changes induced by the block transactions are applied.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
> +At its core, a [#index-blockchain-1]#*blockchain*# is a database shared across multiple computers. Operations on the database are called *transactions*. The data contained in a transaction specifies
> Generally speaking, users are allowed to perform operations on their [#index-accounts-1]#*accounts*#

Maybe this sentence is simplifying the concept to much? 
1. Even the most common transactions in blockchain (balance transfers) perform operations on other accounts, namely the receiver accounts. 
2. And the concept of account and address is also not used in general.
Especially in combination with the next section, which is saying that Lisk is an account based blockchain, this is a bit confusing, because from here you get the impression that every blockchain is account based.

Maybe this sentence could be remove here, and in the next section the concept of `account` and `address` is introduced, without saying that one can operate only on its own account?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
> +The Lisk Protocol is the formal set of rules that defines the Lisk blockchain. Lisk is an [#index-account_based-1]#*account-based*# blockchain, where the validity of a new transaction is checked agai
"account state" -> "accounts state"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +A Lisk account is a unique identifier called address, an amount of LSK tokens referred to as balance and possibly some extra properties used in other parts of the Lisk protocol.
```suggestion
A Lisk account consists of a unique identifier called address, an amount of LSK tokens referred to as balance and possibly some extra properties used in other parts of the Lisk protocol.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +An address is the main identifier of the account. It is used, for example, to identify the recipient when transferring balance between users. The address is calculated as the first 20 bytes of the SH
```suggestion
The address is the main identifier of the account. It is used, for example, to identify the recipient when transferring balance between users. The address is calculated as the first 20 bytes of the SHA-256 of the public key.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +For the front end we provide a link:6-appendix.adoc#user-friendly-address[user-friendly address format], where each address starts with the prefix “_lsk”_ and a checksum is appended to signal acciden
that's a point that also popped up in the serialization LIPs reviews. My understanding was different, and we also specified it differently in the address system LIP.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +The public key is set only when the user sends the very first transaction from the account.
I would be more explicit to prevent any misinterpretations:

"The public key is set only when the first transaction originating from the account is included into the blockchain."

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +The account asset contains all extra information that is specific to a transaction or to the blockchain the account belongs to. In the following, we list the properties there are part of an account a
```suggestion
The account asset contains all extra information that is specific to a transaction or to the blockchain the account belongs to. In the following, we list the properties that are part of an account asset in the Lisk mainchain.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +===== `delegate`
the visual difference between 
"==== `asset`"
and
"===== `delegate`"
is so low, that it's almost impossible to see. Could we use a list instead for these 3 properties?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +In link:4-consensus-algorithm.adoc#lisk-delegated-proof-of-stake[Lisk delegated Proof-of-Stake], users link:2-transactions.adoc#vote[vote] for accounts who have registered themselves as delegates. Vo
```suggestion
In link:4-consensus-algorithm.adoc#lisk-delegated-proof-of-stake[Lisk delegated Proof-of-Stake], users link:2-transactions.adoc#vote[vote] for accounts that are registered as delegate accounts. Votes issued by a user are stored in their account as a list of tuples, each with the voted-delegate address and the amount of voted tokens (in Beddows). Tokens used for voting are [#index-locked-1]#locked*#, and cannot be used (or moved from the account) before they have been [#index-unlocked-1]#unlocked*#.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +In link:4-consensus-algorithm.adoc#lisk-delegated-proof-of-stake[Lisk delegated Proof-of-Stake], users link:2-transactions.adoc#vote[vote] for accounts who have registered themselves as delegates. Vo
something is wrong with the formatting in the last sentence.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> += Protocol Documentation
This header should probably be contained in 0-introduction.adoc?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, the state of the blockchain is updated by transactions included in a link:3-blocks.adoc[block]. Every account can issue a transaction, with the corresponding signature and data. There is a s
```suggestion
In Lisk, the state of the blockchain is updated by transactions included in a link:3-blocks.adoc[block]. Every account can issue a transaction, with the corresponding signature and data. There is a set of different transaction types and each of these types define a specific logic for modifying accounts depending on the transaction data. In the table below, there is a summary of these transaction types and the purpose each of them serve. 
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Every transaction object in the Lisk protocol, regardless of the type, has a common set of properties which are:
I thinks it's not so nice to read when "which are:" is followed by a header. Maybe we could convert these section into a list, or we just list the properties once and keep their explanations in the subsections?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +An integer that can be used only once by the `senderPublicKey`. If due to  network congestion, a transaction was not included in a block because its fee was too low, a user can broadcast a new transa
"by the `senderPublicKey`" -> "by the account"?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Fee in Beddows to be spent by the transaction. This fee has to be equal or greater than a minimum value for the transaction to be valid. The minimum value is calculated as the size of the transaction
```suggestion
The fee in Beddows to be spent by the transaction. This fee has to be equal or greater than a minimum value for the transaction to be valid. The minimum value is calculated as the size of the transaction object multiplied by a constant, `minFeePerByte`, given by the protocol. The value of `minFeePerByte` is 10^-5^ LSK/byte (or 1000 Beddows/byte). Note that for *Delegate Registration* transactions there is an extra summand of 10 LSK added to the minimum fee to account for the name space used by this type of transaction. 
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +For example, for a <<Balance Transfer>> transaction with a size of 133 bytes, the minimum fee is 10^-5^ LSK/byte × 133 bytes = 0.00133 LSK. In the case of <<Delegate Registration>> transaction with a
```suggestion
For example, for a <<Balance Transfer>> transaction with a size of 133 bytes, the minimum fee is 10^-5^ LSK/byte × 133 bytes = 0.00133 LSK. In the case of <<Delegate Registration>> transaction with a size of 124 bytes, the__ __minimum fee of the transaction is 10 LSK + 10^-5^ LSK/byte × 124 bytes = 10.00124 LSK.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +The public key of the account issuing the transaction. Note that, this public key does not necessarily sign the transaction. For simplicity, the account issuing the transaction is called sender accou
```suggestion
The public key of the account issuing the transaction. Note that this public key does not necessarily sign the transaction. For simplicity, the account issuing the transaction is called sender account in the rest of the document.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +The public key of the account issuing the transaction. Note that, this public key does not necessarily sign the transaction. For simplicity, the account issuing the transaction is called sender accou
Maybe "Note that for accounts that were registered as a multisignature account, a transaction does not necessarily need a signature for this public key."

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data logic specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the `asset` property of the dif
"data logic specific" -> "data specific"? for me, "logic" does not make sense in this context.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data logic specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the `asset` property of the dif
> The next section describes the `asset` property of the different transaction types.

Not true.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
"link:1-accounts.adoc#keys[`keys` property]" -> "link:1-accounts.adoc#keys[`keys`] property"

this looks nicer to me :)

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
> the object containing the five properties introduced above has to be signed

from the structure of this document it is not super easy to see which properties are meant. should we name them explicitly?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
> Otherwise, the signing process has to be repeated for each of the private keys associated with the applicable public keys specified in the keys property of the account. 

1. "repeated" could be misleading. 
2. "for each" not true for the optional keys.

Maybe:
"Otherwise, the array needs to contain signatures for some public keys specified in the `keys` property of the account."

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
> a detailed of the signing process is given.

-> "a detailed specification of the signing process is given"?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, every transaction is associated with a transaction ID, which uniquely identifies a transaction in the blockchain. The transaction ID is the SHA-256 hash of the serialized  transaction.  +
as far as I remember we agreed once on "transactionID". Is this correct?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
I find this sentence redundant.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
the link to `transaction pool` is broken

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +==== Minimum Balance
using the same header level suggests that `minimum balance` belongs to the common set of properties of transactions.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +The 7 transactions types available in the Lisk protocol are listed in the table above. Each of them induces a concrete operation on the blockchain state and is defined by a unique schema and transact
```suggestion
The 7 transactions types available in the Lisk protocol are listed in the table above. Each of them induces a concrete operation on the blockchain state and is defined by a unique schema and transaction logic. The type-specific data is given in the `asset` property mentioned before. The key points and useful information for each of these transaction types are:
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +The 7 transactions types available in the Lisk protocol are listed in the table above. Each of them induces a concrete operation on the blockchain state and is defined by a unique schema and transact
As above, I find the structure of the document hard to follow if "...types are:" is followed by some new sections (starting with headers). A list would be better.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction type transfers the amount of Beddows specified in `amount` property from the link:1-account.adoc[account] corresponding to the `senderPublicKey`, i.e. the sender account, to the acco
link to `account` is broken

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction type transfers the amount of Beddows specified in `amount` property from the link:1-account.adoc[account] corresponding to the `senderPublicKey`, i.e. the sender account, to the acco
```suggestion
This transaction type transfers the amount of Beddows specified in the `amount` property from the link:1-account.adoc[account] corresponding to the `senderPublicKey`, i.e. the sender account, to the account specified in `recipientId`. This transaction allows to send a message in the optional property `data`. 
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction [#index-unlocked-2]#*unlocks*# the LSK tokens specified in `amount` that were previously unvoted for the delegate in `delegateAddress` by vote transaction at the height given in the
" by vote transaction at the height given" -> " by a vote transaction at the height given"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction [#index-unlocked-2]#*unlocks*# the LSK tokens specified in `amount` that were previously unvoted for the delegate in `delegateAddress` by vote transaction at the height given in the
"for the delegate in `delegateAddress`" -> "for the delegate specified by `delegateAddress`"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +==== Multisignature
```suggestion
==== Multisignature Registration
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction registers the sender account as a multisignature account. The set of [#index-mandatory-2]#*mandatory*# keys needs to be specified in `mandatoryKeys` whereas the set of [#index-option
"by the applicable set of signatures." -> "by an applicable set of private keys."

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction contains the information necessary to prove that a delegate who signed the block headers given in `header1` and `header2` has violated the link:4-consensus-algorithm.adoc#lisk-bft[Li
```suggestion
This transaction contains the information necessary to prove that a delegate who signed the block headers given in `header1` and `header2` has violated the link:4-consensus-algorithm.adoc#lisk-bft[Lisk-BFT protocol]. The link:4-consensus-algorithm.adoc#punishment-of-lisk-bft-protocol-violations[Punishment of Lisk-BFT Protocol Violations] section of Consensus gives the details of the implications of this transaction type.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction contains the information necessary to prove that a delegate who signed the block headers given in `header1` and `header2` has violated the link:4-consensus-algorithm.adoc#lisk-bft[Li
> The Punishment of Lisk-BFT Protocol Violations section of Consensus gives

I would remove "of Consensus" or would reword it to "of the Consensus documentation"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transactions allows to access the balance given in `amount` stored in a legacy address associated with the account of the `senderPublicKey`.
I don't like "stored in a legacy address". Could we write something like the following?

"This transactions allows to access the balance that was sent to a legacy address without any associated public key. This legacy address needs to match with the `senderPublicKey` of the transaction."

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +A blockchain is composed of blocks. Each block is composed of a header and of a list of transactions called the payload. Blocks included on the blockchain have been verified by participating nodes an
```suggestion
A blockchain is composed of blocks. Each block is composed of a header and of a list of transactions called the payload. Blocks included in the blockchain have been verified by participating nodes and their payloads constitute the blockchain ledger. 
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +During each block slot, a <<4-consensus-algorithm.adoc#forging-delegate-selection, delegate>> account receives the right to add a new block to the blockchain. This delegate will select valid transact
>  a delegate account receives the right

-> "one delegate account has the right"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The block payload is an array of transactions. The transactions in the payload are considered as [#index-included-1]#*included*# in the blockchain once the block has been added to the blockchain. The
we should not forget to fix the link before it gets published

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The block header is generated by the block forger after the block payload. It is composed of the following properties:
As before, I find it hard to follow when "is composed of the following properties:" is followed by a new section instead of a list.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +An epoch timestamp of when the block is created by the block producer, the timestamp is the number of seconds since the genesis block. Therefore, the genesis block has timestamp 0. This timestamp is
```suggestion
An epoch timestamp of when the block is created by the block producer. The timestamp is the number of seconds since the genesis block. Therefore, the genesis block has timestamp 0. This timestamp is used to determine for which block slot the block is created.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The signature of the block. This signature has to be generated by the private key associated to generatorPublicKey. This signature scheme is described in the <<6.appendix.adoc#signature, Appendix>>.
link to Appendix is broken

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +This property is used to store information about the chain that is not necessarily present on all chains created with the SDK. On the Lisk mainchain, this property contains:
As above, I'd prefer a list after ":" instead of subsections

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The maximum height at which the public key in `generatorPublicKey` forged a block. See <<4-consensus-algorithm#consensus-votes-on-blocks-and-fork-choice-rule, Consensus Votes on Blocks and Fork Choic
> See Consensus Votes on Blocks and Fork Choice Rule

There is no section with this name

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +[https://github.com/LiskHQ/lips/blob/master/proposals/lip-0022.md#block-header[2]] for details.
is there a reason why we use "[2]" instead of using corresponding section name? I would even prefer "see here", where "here" links to the corresponding section.

The same at some other places.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +=== Block ID
I think also for blocks we agreed once on "blockID" instead of "block ID".
But I'm not 100%ly sure.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +| From 4’451’520 to 1’451’519   | 4
```suggestion
| From 4’451’520 to 7’451’519   | 4
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The genesis block is the very first block on the blockchain. It contains all the information about the initial distribution of tokens and the initial information necessary to start generating new blo
```suggestion
The genesis block is the very first block on the blockchain. It contains all the information about the initial distribution of tokens and the initial information necessary to start generating new blocks. This block has: height=1, timestamp=0, previousBlock=null.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> += Consensus Algorithm
this header level (1) is different to the ones for introduction, accounts, transactions and blocks (2).

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +A delegate is an account which performed a link:2-transactions.adoc#{delegate-registration}[Delegate Registration Transaction]. An account can vote for any delegate using a link:2-transactions.adoc#v
"link:2-transactions.adoc#{delegate-registration}[Delegate Registration Transaction]"
-> "link:2-transactions.adoc#delegate-registration[Delegate Registration Transaction]"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The forger list is computed taking into account the delegate weights and some random values submitted by delegates as part of their block. The top 101 delegate by delegate weight are called [#index-a
```suggestion
The forger list is computed taking into account the delegate weights and some random values submitted by delegates as part of their block. The top 101 delegates by delegate weight are called [#index-active_delegate-1]#*active delegates*#, whereas all other delegates  with at least delegate weight 1000 LSK  are referred to as [#index-standby_delegate-1]#*standby delegates*#. More specifically, the forger list for a round is generated as follows:
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The forger list is computed taking into account the delegate weights and some random values submitted by delegates as part of their block. The top 101 delegate by delegate weight are called [#index-a
"with at least delegate weight 1000 LSK" -> "with a delegate weight of at least 1000 LSK"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The random selection of two standby delegates and commit-reveal scheme that the `seedReveal` values provided by the delegates in the block header must follow are described in detail in https://github
```suggestion
The random selection of the two standby delegates and the commit-reveal scheme that the `seedReveal` values provided by the delegates in the block header must follow are described in detail in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0022.md[LIP 0022].
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +As a fail-safe mechanism, a delegate that does not forge blocks for an extended period of time is banned. This is to avoid that a delegates which is not running a node leads to frequent missed block
" that a delegates which is " -> " that a delegate that is "

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +As a fail-safe mechanism, a delegate that does not forge blocks for an extended period of time is banned. This is to avoid that a delegates which is not running a node leads to frequent missed block
"from current height of the chain" -> "from the current height of the chain"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The Lisk-BFT protocol is formally defined in the related research paper <<consensus-algorithm-ref1,[1]>>. This section provides a high-level overview of the Lisk-BFT protocol and its security guarant
I think we should link directly to arxive instead of to a reference at the bottom of the document. Then it's more consistend to all other links (to LIPs and other docu pages).

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +Consensus Votes on Blocks and Fork Choice Rule
is this supposed to be a header?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The [#index-fork_choice_rule-1]#*fork choice rule*# defines to which chain a delegate is supposed to add a block in case there are multiple chains. In the Lisk-BFT protocol delegates choose the chain
The last sentence and the usage of the term "ancestor block" in the next section is confusing me. Is an ancestor block
1. a predecessor block, or
2. a predecessor block with at least 68 prevotes?
I think in the following section, definition 1 is required, but here it sounds like definition 2 is used.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The [#index-fork_choice_rule-1]#*fork choice rule*# defines to which chain a delegate is supposed to add a block in case there are multiple chains. In the Lisk-BFT protocol delegates choose the chain
ok, now i see that definition 1 is used. Maybe we could reformulate it to avoid confusion:

"has to be equal to the largest height of an ancestor block with at least 68 prevotes (an ancestor block is a predecessor block in the chain)."

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +==== PoM
I think it is worth to repeat in this section what "PoM" stands for.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/5-network.adoc
> +Connections in the https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md[*Lisk P2P]* are established as _websockets_ [https://en.wikipedia.org/wiki/WebSocket[1]] using the _SocketCluster_
also here I find it weird to used "[1]" for a link instead of adding a link to the word "websockets".

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/5-network.adoc
> +Connections in the https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md[*Lisk P2P]* are established as _websockets_ [https://en.wikipedia.org/wiki/WebSocket[1]] using the _SocketCluster_
same for "[2]" and "[3]"

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/5-network.adoc
> +On top of SocketCluster, lies the _Lisk RPC and Events_ layer, which manages interactions between nodes using Remote Procedural Calls [https://en.wikipedia.org/wiki/Remote_procedure_call[3]].
```suggestion
On top of SocketCluster lies the _Lisk RPC and Events_ layer, which manages interactions between nodes using Remote Procedural Calls [https://en.wikipedia.org/wiki/Remote_procedure_call[3]].
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +The Lisk protocol specifies in [1] how to serialize objects used by the protocol. Generating a binary message from a JavaScript object is done following a stricter version of the https://developers.g
should we leave something more obvious in the text to not forget to replace [1] by a proper link to the serialization LIP?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +The Lisk blockchain uses the Ed25519 signature scheme (see [https://en.wikipedia.org/wiki/Digital_signature[5]] and [https://ed25519.cr.yp.to/[6]]). The signing procedure uses the message and the pri
As before, I find a bit weird to use "[5]" for a link that is pointing to something external and not referring to some other part within the document.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Prepend the 32 bytes network identifier to the binary message (see [https://github.com/LiskHQ/lips/blob/master/proposals/lip-0009.md#specification[7]] and [https://github.com/LiskHQ/lips/blob/maste
```suggestion
. Prepend the 32 bytes network identifier to the binary message (see [https://github.com/LiskHQ/lips/blob/master/proposals/lip-0009.md#specification[7]] and [https://github.com/LiskHQ/lips/blob/master/proposals/lip-0024.md#update-to-the-block-header-signing-procedure[8]]). The network identifier  uniquely binds a transaction or a block to one network. Different blockchains created with the Lisk SDK should use different network identifiers to avoid transaction replay between chains.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Compute the signature of the output of step 2 as described in the ed25519 specifications.
We should use consistently "Ed25519" or "ed25519".

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Remove the signature from the object received.
It is not obvious what the received object is.
- a binary message that to be deserialized first?
- a JS object?
- or an abstract object (dictionary)?

From the previous section, it is also not obvious that the signature is added to the transaction/block object and then the transaction/block object is serialized again and that this output is sent.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
there is no link for [1]

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
> a 12-words passphrase from the BIP39 wordlist [1] is generated

do we really want to have this sentence in the protocol documentation? if so, we become somehow responsible for the low entropy of the key space.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +==== Account Creation
> Account Creation

from this title, I would expect how an account is created on the blockchain, i.e., added to the accounts state/blockchain state. I would rather use "Key Pair Creation" or "Address Creation" or "Key Pair and Address Creation".

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
```suggestion
To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as the seed to generate the [#index-private_key-1]#*private key*# and the [#index-public_key-1]#*public key*# using Ed25519 signature scheme. Finally, the [#index-address-1]#address# is generated by taking the first 20 bytes of the public key.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
Just for curiosity: Did somebody check if Lisk Elements is doing it as stated here?

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
> Finally, the address is generated by taking the first 20 bytes of the public key.

the first 20 bytes of the SHA-256 hash of the public key.

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate the checksum of the 20 byte address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typi
```suggestion
. Calculate the checksum of the 20 byte address of the account using a BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidentally typing mistakes.
```

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate the checksum of the 20 byte address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typi
I would also mention that the checksum is a 30-bit checksum

2020-01-16 11:01 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Add the prefix lsk to the output of step 3. This means that all Lisk addresses used in the Lisk wallet start with lsk and that the final address is 41 characters long.
```suggestion
. Add the prefix "lsk" to the output of step 3. This means that all Lisk addresses used in the Lisk wallet start with "lsk" and that the final address is 41 characters long. 
```

2020-01-16 14:59 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +The Lisk Protocol is the formal set of rules that defines the Lisk blockchain. Lisk is an [#index-account_based-1]#*account-based*# blockchain, where the validity of a new transaction is checked agai
done

2020-01-16 15:01 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +The public key is set only when the user sends the very first transaction from the account.
done

2020-01-16 16:10 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +For the front end we provide a link:6-appendix.adoc#user-friendly-address[user-friendly address format], where each address starts with the prefix “_lsk”_ and a checksum is appended to signal acciden
Do you think it is clear the way it is written now?

2020-01-20 12:37 UTC, janhack commented on modules/ROOT/pages/3-blocks.adoc
> +=== Block ID
I think we need to distinguish between a variable name used in the implementation and the general concept. Here we talk about the general concept (identifier for a block) and therefore write `block ID`.

2020-01-20 12:39 UTC, janhack commented on modules/ROOT/pages/3-blocks.adoc
> +| From 4’451’520 to 1’451’519   | 4
I think we also agreed on comma or no separator for multiples of 1000.

2020-01-20 12:39 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> += Consensus Algorithm
As concluded in the STM we keep it like this.

2020-01-20 13:05 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +A delegate is an account which performed a link:2-transactions.adoc#{delegate-registration}[Delegate Registration Transaction]. An account can vote for any delegate using a link:2-transactions.adoc#v
Fixed.

2020-01-20 13:07 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The forger list is computed taking into account the delegate weights and some random values submitted by delegates as part of their block. The top 101 delegate by delegate weight are called [#index-a
Will fix it.

2020-01-20 13:18 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The random selection of two standby delegates and commit-reveal scheme that the `seedReveal` values provided by the delegates in the block header must follow are described in detail in https://github
I think the two definite articles are not mandatory and I would prefer without because I talk about selecting 2 standby delegates in general rather than how two specific delegates were selected. This was also not remarked by Chris.

2020-01-20 13:30 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +As a fail-safe mechanism, a delegate that does not forge blocks for an extended period of time is banned. This is to avoid that a delegates which is not running a node leads to frequent missed block
For the first one, changed to 
>This is to avoid the situation where a delegate who is not running a node leads to frequent missed block slots. 

Note that for essential relative clauses both that and which are okay and for non-essential only which is permitted: https://english.stackexchange.com/questions/78/when-to-use-that-and-when-to-use-which#

2020-01-20 13:32 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +As a fail-safe mechanism, a delegate that does not forge blocks for an extended period of time is banned. This is to avoid that a delegates which is not running a node leads to frequent missed block
Fixed the second.

2020-01-20 13:43 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The Lisk-BFT protocol is formally defined in the related research paper <<consensus-algorithm-ref1,[1]>>. This section provides a high-level overview of the Lisk-BFT protocol and its security guarant
Changed to agreed style.

2020-01-20 13:43 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +Consensus Votes on Blocks and Fork Choice Rule
Yep. I will fix it.

2020-01-20 13:55 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The [#index-fork_choice_rule-1]#*fork choice rule*# defines to which chain a delegate is supposed to add a block in case there are multiple chains. In the Lisk-BFT protocol delegates choose the chain
Good point. Changed to your suggestion.

2020-01-20 15:32 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +===== `delegate`
After the STM, I edited the headers so that everything now is a level higher. If that still does not help, I will use a list

2020-01-20 15:32 UTC, ricott1 commented on modules/ROOT/pages/5-network.adoc
> +Connections in the https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md[*Lisk P2P]* are established as _websockets_ [https://en.wikipedia.org/wiki/WebSocket[1]] using the _SocketCluster_
edited as per STM conclusion

2020-01-20 15:32 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +A blockchain is composed of blocks. Each block is composed of a header and of a list of transactions called the payload. Blocks included on the blockchain have been verified by participating nodes an
changed

2020-01-20 15:33 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +During each block slot, a <<4-consensus-algorithm.adoc#forging-delegate-selection, delegate>> account receives the right to add a new block to the blockchain. This delegate will select valid transact
changed

2020-01-20 15:35 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +The block header is generated by the block forger after the block payload. It is composed of the following properties:
changed slightly. In essence, I am not sure the new way is much easier to follow. As discussed in the STM, we will see how it looks on the website rendering.

2020-01-20 15:35 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +An epoch timestamp of when the block is created by the block producer, the timestamp is the number of seconds since the genesis block. Therefore, the genesis block has timestamp 0. This timestamp is
changed

2020-01-20 15:37 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +The signature of the block. This signature has to be generated by the private key associated to generatorPublicKey. This signature scheme is described in the <<6.appendix.adoc#signature, Appendix>>.
fixed

2020-01-20 15:38 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +This property is used to store information about the chain that is not necessarily present on all chains created with the SDK. On the Lisk mainchain, this property contains:
changed

2020-01-20 15:39 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +The maximum height at which the public key in `generatorPublicKey` forged a block. See <<4-consensus-algorithm#consensus-votes-on-blocks-and-fork-choice-rule, Consensus Votes on Blocks and Fork Choic
I don't understand this comment

2020-01-20 15:40 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +[https://github.com/LiskHQ/lips/blob/master/proposals/lip-0022.md#block-header[2]] for details.
changed

2020-01-20 15:41 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +=== Block ID
as Jan said.

2020-01-20 15:42 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +| From 4’451’520 to 1’451’519   | 4
thank you.
Comma it is.

2020-01-20 15:44 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +The genesis block is the very first block on the blockchain. It contains all the information about the initial distribution of tokens and the initial information necessary to start generating new blo
done

2020-01-21 09:25 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +The block payload is an array of transactions. The transactions in the payload are considered as [#index-included-1]#*included*# in the blockchain once the block has been added to the blockchain. The
yes, will leave this open!

2020-01-21 09:27 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +The Lisk protocol specifies in [1] how to serialize objects used by the protocol. Generating a binary message from a JavaScript object is done following a stricter version of the https://developers.g
changed to LIP-00xx. We will have to update this once the LIPs have a number.

2020-01-21 09:30 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +The Lisk blockchain uses the Ed25519 signature scheme (see [https://en.wikipedia.org/wiki/Digital_signature[5]] and [https://ed25519.cr.yp.to/[6]]). The signing procedure uses the message and the pri
yes, changed.

2020-01-21 09:32 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Prepend the 32 bytes network identifier to the binary message (see [https://github.com/LiskHQ/lips/blob/master/proposals/lip-0009.md#specification[7]] and [https://github.com/LiskHQ/lips/blob/maste
added

2020-01-21 09:35 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Remove the signature from the object received.
This is on purpose. This section doesn't really talk about transmitting objects. So I consider you have an object, in some form. 
Maybe we could add a section about transmitting objects? I think it will probably wait for the technical documentation.

2020-01-21 09:38 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +==== Account Creation
changed to "Key Pair and Address Creation"

2020-01-21 09:38 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
added

2020-01-21 09:41 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
true the entropy is not high enought.
But I don't think this documentation is about becoming responsible. It is done like this and we should say so in the documentation.
We should definitely go up to 16 words, but I don't think this is on the agenda for now.

2020-01-21 09:46 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
changed.
Lisk elements is doing it as stated here. Except that the address is generated from the first 8 bytes reversed. We only document the future 20 bytes address here.

2020-01-21 09:47 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new account, first a 12-words passphrase from the BIP39 wordlist [1] is generated. The passphrase is then hashed using SHA-256 into a 256-bit string and the resulting hash is used as seed
changed

2020-01-21 09:49 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate the checksum of the 20 byte address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typi
changed

2020-01-21 09:49 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate the checksum of the 20 byte address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typi
added

2020-01-21 09:50 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Add the prefix lsk to the output of step 3. This means that all Lisk addresses used in the Lisk wallet start with lsk and that the final address is 41 characters long.
added

2020-01-21 09:51 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Compute the signature of the output of step 2 as described in the ed25519 specifications.
changed, thanks

2020-01-21 12:07 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +The public key of the account issuing the transaction. Note that, this public key does not necessarily sign the transaction. For simplicity, the account issuing the transaction is called sender accou
Going for the first option for simplicity and being more generic

2020-01-21 12:09 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data logic specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the `asset` property of the dif
reformulated the 'asset' sentence to make it more correct.

2020-01-21 12:22 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
that is why I said "applicable public keys". This is, for the public keys that apply to the specific case. I think that conveys the message better than saying "some public keys".

2020-01-21 12:25 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, every transaction is associated with a transaction ID, which uniquely identifies a transaction in the blockchain. The transaction ID is the SHA-256 hash of the serialized  transaction.  +
note that ID here is not the specific name of the property/variable/object in the protocol but just the name of the section

2020-01-21 12:28 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
the second sentence tries to put in perspective (respect to other parts of the protocol/application) what happens after all these things are calculated. I could remove it if needed, but I think it is not a big deal and clarifies the basics for a novel reader.

2020-01-21 13:55 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +==== Minimum Balance
note that the name of the section containing this one is "Transaction Properties, Transaction ID and Minimum Balance", so in that regard it should not be a big issue. Given that, I also think that the minimum balance concept does not fit in any section properly as of now.

2020-01-22 14:32 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
> +. link:4-consensus-algorithm.adoc[*Consensus Algorithm*]: In this section illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
```suggestion
. link:4-consensus-algorithm.adoc[*Consensus Algorithm*]: This section illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
```

2020-01-22 14:34 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +For the front end we provide a link:6-appendix.adoc#user-friendly-address[user-friendly address format], where each address starts with the prefix “_lsk”_ and a checksum is appended to signal acciden
yes, it is

2020-01-22 14:41 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +===== `delegate`
It's still not so great on GitHub, but we should check the rendering on the Lisk page before adding more changes to this.

2020-01-22 14:49 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +Tokens used for voting are [#index-locked-1]#locked*#, and cannot be used (or moved from the account) before they have been [#index-unlocked-1]#unlocked*#.
#locked*#       -> #locked#
#unlocked*#   -> #unlocked#
?
Or the words "locked" and "unlocked" supposed to be in bold? If so, they aren't.

2020-01-22 14:55 UTC, AndreasKendziorra commented on modules/ROOT/pages/1-accounts.adoc
> +These public keys can be either [#index-mandatory-1]#mandatory*# or [#index-optional-1]#optional*#: All mandatory keys have to sign the transaction, and the total number of signatures (mandatory plus
#mandatory*# -> #mandatory#
#optional*#      -> #optional#
?

2020-01-22 15:08 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Every transaction object in the Lisk protocol, regardless of the type, has a common set of properties. These properties are shown in the subsections below.
Despite the graphic, I think that it is not obvious which properties are the common properties, because all following headers, including the ones for ID and Minimum Balance, have level 3.

I think it would be good add an additional header, "Common Properties" or so, of level 3 before this line or before the graphic, and then change header level of these properties to 4.

2020-01-22 15:20 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the different transaction types respe
> The next section describes the different transaction types respect to the `asset` property of each of them.

But the next section is `signatures` and not "Transaction Types". Or is a section for you always starting with a level 2 header? If so, I would reformulate it to "The section Transaction Types describes ..." and add a link.

2020-01-22 15:32 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
But I would say that every public key from the keys property is applicable in every case. I'm not sure what you mean with "apply to the specific case".

2020-01-22 15:36 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, every transaction is associated with a transaction ID, which uniquely identifies a transaction in the blockchain. The transaction ID is the SHA-256 hash of the serialized  transaction.  +
I was referring to "transaction ID" in line 53. By reading the all serialization LIPs, I also got the impression that "transation ID" and "block ID" are preferred over "transactionID" and "blockID". Was it decided at some point we use this way?

2020-01-22 15:43 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
The ID is not even strictly needed for transmission. Me removed the ID properties from the transaction schema in the "Remove redundant properties" LIP. I'm not even sure how the API works, i.e., if a front end tool is sending a transaction with or without ID to a node. But this is anyway just an implementation detail and work in theory without transactionID.

2020-01-22 15:45 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +==== Minimum Balance
please see my other comment: https://github.com/LiskHQ/lisk-docs/pull/380/files/76ba3fcd3be096b1011366dadf9929203b3fc418..6bf96e0851528c0286929147030649c4ff055327#r369615581

2020-01-22 16:05 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction registers the sender account as a multisignature account. The set of [#index-mandatory-2]#*mandatory*# keys needs to be specified in `mandatoryKeys` whereas the set of [#index-option
"signed by ... set of signatures" -> "signed by ... set of private keys"?

2020-01-22 16:13 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the different transaction types respe
```suggestion
This property contains the data specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the different transaction types with respect to the `asset` property of each of them.
```

2020-01-22 16:16 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +The 6 transactions types available in the Lisk protocol are listed in the table displayed above. Each one induces a concrete operation on the blockchain state and is defined by a unique schema and tr
```suggestion
The 6 transactions types available in the Lisk protocol are listed in the table displayed above. Each one induces a concrete operation on the blockchain state and is defined by a unique schema and transaction logic. The type-specific data is given in the `asset` property previously mentioned. The key points and useful information for each of these transactions are commented in the following subsections.
```

2020-01-22 16:22 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +During each block slot, a <<4-consensus-algorithm.adoc#forging-delegate-selection, delegate>> account receives the right to add a new block to the blockchain. This delegate will select valid transact
not "one delegate" instead of "a delegate"?

2020-01-22 16:26 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The block header is generated by the block forger after the block payload. It is composed of the following properties:
In this case, I find it much better, because first header that does not belong to this list is of level two which looks very different (on GitHub). We have to check again on our page, but I will resolve this one here.

2020-01-22 16:32 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The maximum height at which the public key in `generatorPublicKey` forged a block. See <<4-consensus-algorithm#consensus-votes-on-blocks-and-fork-choice-rule, Consensus Votes on Blocks and Fork Choic
Sorry, I also don't know anymore what the problem was here.

2020-01-23 08:04 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +[https://github.com/LiskHQ/lips/blob/master/proposals/lip-0022.md#block-header[LIP-0022]] for more details.
I would remove the square brackets around "LIP-0022"

2020-01-23 08:59 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +The block ID is computed last, and is obtained by hashing the <<6-appendix#serialization, serialized>> block header.
> The block ID is computed last,

This is not really true anymore since do not include the ID in the block anymore (unless we talk about something different from block forging). That means, a delegate could create a block and send it to other nodes without computing the ID. Therefore, I would just write 
"The block ID is obtained by .."

2020-01-23 09:17 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
We need to state that this is the future protocol and not the current one.

2020-01-23 09:17 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
> += Introduction
We need to state that this is the future protocol and not the current one.

2020-01-23 10:50 UTC, AndreasKendziorra commented on modules/ROOT/pages/3-blocks.adoc
> +Blockchains following the Lisk protocol do not not have a bounded token supply. For every block forged, the amount of available token increases. This increase is obtained by subtracting the burned fe
```suggestion
Blockchains following the Lisk protocol do not not have a bounded token supply. For every block forged, the amount of available tokens increases. This increase is obtained by subtracting the burned fees from the block reward. 
```

2020-01-23 10:56 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The top 101 delegates by delegate weight are called [#index-active_delegate-1]#*active delegates*#, whereas all other delegates with a delegate weight of at least 10^11^ are referred to as [#index-st
```suggestion
The top 101 delegates by delegate weight are called [#index-active_delegate-1]#*active delegates*#, whereas all other delegates with a delegate weight of at least 10^11 Beddows are referred to as [#index-standby_delegate-1]#*standby delegates*#. 
```

2020-01-23 11:02 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The random selection of two standby delegates and commit-reveal scheme that the `seedReveal` values provided by the delegates in the block header must follow are described in detail in https://github
I see it for the first one, but for "commit-reveal scheme" I find it weird without article. Don't you agree?

2020-01-23 11:10 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +As a fail-safe mechanism, a delegate that does not forge blocks for an extended period of time is banned. This is to avoid that a delegates which is not running a node leads to frequent missed block
> a delegate who is not

do we really want to consider a delegate to be a person? In fact, a delegate account could be managed by an organisation or any other group of people.

2020-01-23 11:19 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +==== PoM
@IkerAlus you don't agree? If not, it's ok.

2020-01-23 12:42 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +The Lisk protocol uses the Ed25519 signature scheme, please see the signatures page on https://en.wikipedia.org/wiki/Digital_signature[Wikipedia] and the specification page for https://ed25519.cr.yp.
> please see the signatures page on https://en.wikipedia.org/wiki/Digital_signature[Wikipedia] and the specification page for https://ed25519.cr.yp.to/[Ed225519])

there is a closing bracket, but not an opening one.

2020-01-23 12:45 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Remove the signature from the object received.
should be ok as it is

2020-01-23 12:59 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +The signing procedure uses the message and the private key of the signatory to generate 64 bytes, called the signature.
> signatory

I think this term is not common at all in the context of digital signatures. But it's also not super important.

2020-01-23 13:11 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate a 30-bit checksum of the 20 byte address of the account using a BCH code, see https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[bip-0173]. This step provvides protection agai
```suggestion
. Calculate a 30-bit checksum of the 20 byte address of the account using a BCH code, see https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[bip-0173]. This step provides protection against accidentally typing mistakes.
```

2020-01-23 13:59 UTC, ricott1 commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate the checksum of the 20 byte address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typi
```suggestion
. Calculate the checksum of the 20 bytes address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typing mistakes.
```
not sure

2020-01-28 14:34 UTC, AndreasKendziorra commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new address, first a 12-words passphrase from the https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt[english BIP39 wordlist] is generated.
Generating the 12-word passphrase is done as described in bib39: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic. That means, the words are not arbitrarily chosen, but derived from 128-bit number that was randomly chosen.
We could write:
"To create a new address, a 12-word passphrase is generated following the specifications of BIP39 (link to https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic)."

2020-01-29 10:26 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +During each block slot, a <<4-consensus-algorithm.adoc#forging-delegate-selection, delegate>> account receives the right to add a new block to the blockchain. This delegate will select valid transact
I mis-read your comment, I thought you wanted to insist on "has" vs "receives".
Changed "a" for "one"

2020-01-29 10:31 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +[https://github.com/LiskHQ/lips/blob/master/proposals/lip-0022.md#block-header[LIP-0022]] for more details.
yes, thanks

2020-01-29 10:33 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +The block ID is computed last, and is obtained by hashing the <<6-appendix#serialization, serialized>> block header.
changed

2020-01-29 10:35 UTC, MaximeGagnebin commented on modules/ROOT/pages/3-blocks.adoc
> +Blockchains following the Lisk protocol do not not have a bounded token supply. For every block forged, the amount of available token increases. This increase is obtained by subtracting the burned fe
changed

2020-01-29 10:36 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +The Lisk protocol uses the Ed25519 signature scheme, please see the signatures page on https://en.wikipedia.org/wiki/Digital_signature[Wikipedia] and the specification page for https://ed25519.cr.yp.
removed, thanks

2020-01-29 10:37 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate a 30-bit checksum of the 20 byte address of the account using a BCH code, see https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[bip-0173]. This step provvides protection agai
changed

2020-01-29 10:37 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Calculate the checksum of the 20 byte address of the account using BCH code [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki[1]]. This step gives a protection against accidental typi
will leave it

2020-01-29 10:42 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +To create a new address, first a 12-words passphrase from the https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt[english BIP39 wordlist] is generated.
yes, done

2020-01-29 10:45 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +The signing procedure uses the message and the private key of the signatory to generate 64 bytes, called the signature.
I agree. This was changed following one of Chris comments.
I will leave it for now, and see if more comments ask to change it.

2020-01-29 10:49 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +Every transaction object in the Lisk protocol, regardless of the type, has a common set of properties. These properties are shown in the subsections below.
going point, changed

2020-01-29 10:51 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the different transaction types respe
done!

2020-01-29 10:52 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +This property contains the data specific to the type of the transaction. For each `type` value, there exist a unique `asset` property. The next section describes the different transaction types respe
done

2020-01-29 10:59 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, every transaction is associated with a transaction ID, which uniquely identifies a transaction in the blockchain. The transaction ID is the SHA-256 hash of the serialized  transaction.  +
I don't recall the exact moment and places, but I remember Jan making the point a couple of times that transaction/block/etc IDs should be written separately because it is a concept and not a property name per se. The same one would say about block header or transaction signature. Probably this was discussed on one of these doc style meetings before Christmas.

2020-01-29 11:01 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
would you just remove the whole sentence? or do you think it is ok to not be totally precise here to connect this with the transaction pool concept?

2020-01-29 11:03 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +==== Minimum Balance
addressed in that comment as you said.

2020-01-29 11:04 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +This transaction registers the sender account as a multisignature account. The set of [#index-mandatory-2]#*mandatory*# keys needs to be specified in `mandatoryKeys` whereas the set of [#index-option
good catch, changed

2020-01-29 11:05 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +An array with the signatures of the transaction. If the account associated to `senderPublicKey` does not have the link:1-accounts.adoc#keys[`keys` property], the object containing the five properties
changed to undefined set as suggested for the multisig case.

2020-01-30 13:07 UTC, AndreasKendziorra commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
I would remove it.

2020-01-30 14:10 UTC, chris529 commented on modules/ROOT/pages/0-introduction.adoc
> +. link:4-consensus-algorithm.adoc[*Consensus Algorithm*]: In this section illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
Agreed.

2020-01-30 14:15 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +A Lisk account consists of a unique identifier called address, an amount of tokens referred to as balance and possibly some extra properties used in other parts of the Lisk protocol.
```suggestion
A Lisk account consists of a unique identifier address, an amount of tokens which are referred to as the balance, and possibly some additional properties which are also used within the Lisk protocol.
```

2020-01-30 14:15 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +The account state is not stored as part of the blockchain, however it can be computed by executing all transactions contained in past blocks. Verification of the validity of a transaction requires th
```suggestion
The account state is not stored as part of the blockchain, however it can be computed by executing all transactions contained in previous blocks. Verification of the validity of a transaction requires the state of the referenced accounts.
```

2020-01-30 14:16 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +The address is the main identifier of the account. It is used, for example, to identify the recipient when transferring balance between users. The address is calculated as the first 20 bytes of the S
```suggestion
The address is the main identifier of the account. For example, it is used to identify the recipient when transferring the balance between users. The address is calculated as the first 20 bytes of the SHA-256 of the public key.
```

2020-01-30 14:16 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +Balance can be sent from one account to another using a link:2-transactions.adoc#balance-transfer[Balance Transfer Transaction].
```suggestion
The balance can be sent from one account to another using a link:2-transactions.adoc#balance-transfer[Balance Transfer Transaction].
```

2020-01-30 14:18 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +Users can update the keys property with a link:2-transactions.adoc#multisignature[Multisignature Registration Transaction], specifying the mandatory and optional keys and the number of required signa
```suggestion
Users can update the key's property with a link:2-transactions.adoc#multisignature[Multisignature Registration Transaction], specifying the mandatory and optional keys and the number of required signatures.
```

2020-01-30 14:18 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +This allows signing and sending multiple transactions with the same asset using different nonces, while at the same time preventing transaction replay.
```suggestion
This allows signing and sending multiple transactions with the same asset using different nonces, whilst at the same time preventing transaction replay.
```

2020-01-30 14:21 UTC, chris529 commented on modules/ROOT/pages/1-accounts.adoc
> +Tokens used to vote for a delegate are frozen, and have to be unlocked to make them available again. Similarly to the `votes` property, this property stores the voted-delegate's address and the amoun
```suggestion
Tokens used to vote for a delegate are frozen, and have to be unlocked to make them available again. Similarly to the `votes` property, this property stores the voted-delegate's address and the amount, and also the block in which the votes have been removed from the delegate.
```

2020-01-30 14:36 UTC, chris529 reviewed
Only minor grammar issues

2020-01-31 07:22 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +Tokens used for voting are [#index-locked-1]#locked*#, and cannot be used (or moved from the account) before they have been [#index-unlocked-1]#unlocked*#.
removed *

2020-01-31 07:22 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +. link:4-consensus-algorithm.adoc[*Consensus Algorithm*]: In this section illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
fixed

2020-01-31 07:24 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +These public keys can be either [#index-mandatory-1]#mandatory*# or [#index-optional-1]#optional*#: All mandatory keys have to sign the transaction, and the total number of signatures (mandatory plus
removed *

2020-01-31 07:25 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> += Introduction
I thought the protocol version would be implied by the docs version, and we would keep past version available. Maybe I'm wrong. I'm adding a placeholder (I don't know which protocol version we are documenting here)

2020-01-31 07:26 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +The account state is not stored as part of the blockchain, however it can be computed by executing all transactions contained in past blocks. Verification of the validity of a transaction requires th
done

2020-01-31 07:45 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +Once the transaction has all the required signatures and ID, it is ready to be broadcast to the network so that it can be included into the link:6-network.adoc#transaction-pool[transaction pool] and
removed

2020-01-31 07:46 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +==== PoM
added

2020-01-31 08:11 UTC, AndreasKendziorra commented on modules/ROOT/pages/0-introduction.adoc
> += Introduction
I'm also not sure which version number it will be. I guess 5.0. But I still think that it's worth to add that this a FUTURE protocol. I think that many readers do not know which protocol version is currently implemented in the SDK or used on the mainchain.

2020-02-03 08:19 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +A Lisk account consists of a unique identifier called address, an amount of tokens referred to as balance and possibly some extra properties used in other parts of the Lisk protocol.
partially changed

2020-02-03 08:20 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +Users can update the keys property with a link:2-transactions.adoc#multisignature[Multisignature Registration Transaction], specifying the mandatory and optional keys and the number of required signa
Keys is the name of the property, changed to monospace font to clearly distinguish it

2020-02-03 08:21 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +This allows signing and sending multiple transactions with the same asset using different nonces, while at the same time preventing transaction replay.
I think (correct me if I'm wrong) that 'while' is the more common term for American english, while 'whilst' is more common in British english. As such, I would keep 'while' as the docs are written in American english

2020-02-03 08:22 UTC, ricott1 commented on modules/ROOT/pages/1-accounts.adoc
> +Tokens used to vote for a delegate are frozen, and have to be unlocked to make them available again. Similarly to the `votes` property, this property stores the voted-delegate's address and the amoun
I used 'but' to introduce something contrasting with what has already been mentioned

2020-02-03 08:24 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> += Introduction
Maxime suggested to otherwise mention the roadmap milestones, so that people can check in that page if they have been implemented already.

2020-02-05 10:20 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The top 101 delegates by delegate weight are called [#index-active_delegate-1]#*active delegates*#, whereas all other delegates with a delegate weight of at least 10^11^ are referred to as [#index-st
Beddows is only the unit of the Lisk mainnet. Here we describe the default Lisk SDK.

2020-02-05 10:21 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The random selection of two standby delegates and commit-reveal scheme that the `seedReveal` values provided by the delegates in the block header must follow are described in detail in https://github
I will add the second "the".

2020-02-06 08:31 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +_This documentation only describes the general features of the Lisk protocol version *XXX*. Notice that this ia a future version of the Lisk protocol. For a detailed technical explanation go [here]._
```suggestion
_This documentation only describes the general features of the Lisk protocol version *XXX*. Notice that this is a future version of the Lisk protocol. For a detailed technical explanation go [here]._
```

2020-02-06 12:33 UTC, AndreasKendziorra commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The top 101 delegates by delegate weight are called [#index-active_delegate-1]#*active delegates*#, whereas all other delegates with a delegate weight of at least 10^11^ are referred to as [#index-st
I see. But I find it anyway confusing to not have a unit. For example, it is not clear how this  translates to Lisk main chain. Is it 2^11 LSK, 2^11 Beddows or 2^11 easter eggs (as my physics teacher used to say)? Could we write something like

"delegates with a delegate weight that exceed a specific threshold that has to be defined for each chain"

or

"delegates with a delegate weight at least 2^11 times the smallest non-fractional amount of this chain".

2020-02-07 10:05 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +It has been running for many years and has a few specificities that are not part of the basic Lisk protocol.
Maybe be more precise: "The genesis block has been forged on [insert date here]"

2020-02-07 10:05 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +The Lisk Mainnet is build using the Lisk protocol.
```suggestion
The Lisk Mainnet follows the Lisk protocol. 
```

2020-02-07 10:06 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +==== Reclaim
```suggestion
=== Reclaim
```

2020-02-07 10:06 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +==== Regenesis
```suggestion
=== Regenesis
```

2020-02-07 10:08 UTC, IkerAlus requested changes
Couple of comments regarding formulation

2020-02-07 10:08 UTC, IkerAlus commented on modules/ROOT/pages/7-mainnet.adoc
> +This transaction defines precisely the accounts state and the chain state at a specified regenesis height.
Suggestion: I am not a big fan of using "define precisely" when it is just the hash of those data structures. Maybe something simpler like: "This transaction contains the hash of the accounts state and chain state at a certain height".

2020-02-07 10:08 UTC, IkerAlus commented on modules/ROOT/pages/7-mainnet.adoc
>  This transactions allows to access the balance that was sent to a legacy address without any associated public key. This legacy address needs to match with the `senderPublicKey` of the transaction.
I think it is not clear to say `This legacy address needs to match with the `senderPublicKey` of the transaction.` What about `This legacy address has to be associated with (the account of) the `senderPublicKey`.

2020-02-07 10:08 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +This transactions allows to access the balance that was sent to a legacy address without any associated public key. This legacy address needs to match with the `senderPublicKey` of the transaction.
```suggestion
This transaction allows to access the balance that was sent to a legacy address without any associated public key. This legacy address needs to match with the `senderPublicKey` of the transaction.
```
Furthermore, we never introduced the concept of legacy address, so it may be worth spending a line here. Maybe something like: "The legacy address corresponds to the last 8 bytes of the `senderPublicKey` of the transaction in reversed order."
or something similar

2020-02-07 10:09 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +This transaction defines precisely the accounts state and the chain state at a specified regenesis height.
```suggestion
This transaction contains a cryptographic reference to the accounts state and the chain state at a specified regenesis height.
```

2020-02-07 10:11 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +This allows for lighter nodes in terms of storage and lighter software.
```suggestion
In this way, non backwards-compatible nodes can participate in the Lisk protocol, allowing for a more consistent and lighter codebase.
```
not a fun of my formulation either, actually.

2020-02-07 10:18 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +It has been running for many years and has a few specificities that are not part of the basic Lisk protocol.
done

2020-02-07 10:18 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +The Lisk Mainnet is build using the Lisk protocol.
changed

2020-02-07 10:18 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +==== Reclaim
always for more equality

2020-02-07 10:18 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +==== Regenesis
changed

2020-02-07 10:20 UTC, AndreasKendziorra commented on modules/ROOT/pages/7-mainnet.adoc
> +It has been running for many years and has a few specificities that are not part of the basic Lisk protocol.
> has been running for many years
I would find it much nicer to write down the exact date.

2020-02-07 10:27 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +It has been running for many years and has a few specificities that are not part of the basic Lisk protocol.
yes, changed

2020-02-07 10:30 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +It has been running for many years and has a few specificities that are not part of the basic Lisk protocol.
actually went for "It has been launched in May 2016".

2020-02-07 10:31 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +This transaction defines precisely the accounts state and the chain state at a specified regenesis height.
changed

2020-02-07 10:37 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +This transactions allows to access the balance that was sent to a legacy address without any associated public key. This legacy address needs to match with the `senderPublicKey` of the transaction.
added a precision in this regard.

2020-02-07 10:38 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +This transaction defines precisely the accounts state and the chain state at a specified regenesis height.
yes, thanks.

2020-02-07 10:39 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
>  This transactions allows to access the balance that was sent to a legacy address without any associated public key. This legacy address needs to match with the `senderPublicKey` of the transaction.
changed

2020-02-07 10:40 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +This allows for lighter nodes in terms of storage and lighter software.
yes. I think I like the actual wording a bit better.

2020-02-07 10:44 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +This allows for lighter nodes in terms of storage and lighter software.
I don't think lighter software is very common though. Also, more than not needing to apply all blocks prior to it, the new nodes really can not apply them. This transaction thus allows for these nodes to exist

2020-02-07 10:49 UTC, ricott1 commented on modules/ROOT/pages/7-mainnet.adoc
> +Legacy addresses are generated with the first eight bytes of the public key, they were used in older versions of the protocol.
```suggestion
Legacy addresses, generated from the first eight bytes of the public key, were used in older versions of the protocol. 
```

or add a period between the 2 sentences

2020-02-07 11:04 UTC, IkerAlus submitted a review, later dismissed

2020-02-07 14:32 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +This allows for lighter nodes in terms of storage and lighter software.
hmmm, so if you sync from regenesis, you don't need to apply all the prior blocks. This allows you to run simpler software, I agree lighter is not the best word here. After a bit of googling it seems that the terminology is "lightweight". Will change accordingly.

2020-02-07 14:36 UTC, MaximeGagnebin commented on modules/ROOT/pages/7-mainnet.adoc
> +This allows for lighter nodes in terms of storage and lighter software.
I would not emphasis that you cannot apply the previous blocks. Though I agree that it is the case.
The condition to run the lightweight software is "I don't need/want to apply the blocks".

2020-02-10 11:24 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +== User Interface
I think "Address" would be a better title because this section explains both the binary address used in the protocol as well as the base32 representation.

2020-02-10 11:26 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +=== User-Friendly Address
As decided in the last meeting, the user-friendly address is supposed to be called "Base32 Address". I would therefore use "Base32 Address" or "Base32 Representation" as title with a personal preference towards the second.

2020-02-10 11:27 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +We display addresses in a user-friendly representation including a checksum and the “lsk” prefix.
```suggestion
We display addresses in a Base32 representation including a checksum and the “lsk” prefix. 
```

2020-02-10 11:28 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +The procedure to obtain the [#index-user_friendly_address-1]#*user-friendly address*# from the address is as follows:
```suggestion
The procedure to obtain the [#index-user_friendly_address-1]#*Base32 address*# from the address is as follows:
```

2020-02-10 11:29 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +. Add the prefix "lsk" to the output of step 3. This ensures that all Lisk addresses used in the Lisk wallet start with "lsk" and that the final address is 41 characters long.
```suggestion
. Add the prefix "lsk" to the output of step 3. This ensures that the Base32 addresses used in the Lisk wallet start with "lsk" and that the final address is 41 characters long. 
```

2020-02-10 11:30 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +As an example, the address `0xc247a42e09e6aafd818821f75b2f5b0de47c8235` corresponds to the user-friendly address `lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu`.
```suggestion
As an example, the address `0xc247a42e09e6aafd818821f75b2f5b0de47c8235` has the Base32 representation `lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu`.
```

2020-02-10 11:30 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +. Encode the output of step 2 in a custom base32 format. Lower-case letters and digits are used, the characters i, l, 1 and 0 are removed for usability reasons.
```suggestion
. Encode the output of step 2 in a custom Base32 format. Lower-case letters and digits are used, the characters i, l, 1 and 0 are removed for usability reasons.
```

2020-02-10 11:31 UTC, janhack commented on modules/ROOT/pages/6-appendix.adoc
> +. Encode the output of step 2 in a custom base32 format. Lower-case letters and digits are used, the characters i, l, 1 and 0 are removed for usability reasons.
I think Base32 should be capitalized as it is a proper name https://en.wikipedia.org/wiki/Base32.

2020-02-10 11:32 UTC, janhack commented on modules/ROOT/pages/7-mainnet.adoc
> +=== Regenesis
Maybe we omit this section until the LIP is finalized?

2020-02-10 11:46 UTC, Tschakki commented on modules/ROOT/pages/7-mainnet.adoc
> +=== Regenesis
FYI you can comment sections out like this: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments

2020-02-10 13:32 UTC, janhack commented on modules/ROOT/pages/4-consensus-algorithm.adoc
> +The top 101 delegates by delegate weight are called [#index-active_delegate-1]#*active delegates*#, whereas all other delegates with a delegate weight of at least 10^11^ are referred to as [#index-st
As discussed in the meeting, I know but the equivalent LSK amount for Lisk Mainnet in brackets.

2020-02-10 14:41 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +_This documentation only describes the general features of the Lisk protocol version *XXX*. Notice that this is a future version of the Lisk protocol. For a detailed technical explanation go [here]._
```suggestion
_This documentation gives an overview of the Lisk protocol, the set of rules followed by a blockchain created with the Lisk SDK using the default configuration. A blockchain that uses custom constants or adds custom transactions (see the [Lisk SDK documentation](https://lisk.io/documentation/lisk-sdk/index.html) for details) may therefore deviate from the protocol described here. The differences between the Lisk Mainnet protocol and Lisk protocol is covered in the last section of the documentation. Note that the documentation describes the Lisk protocol after the completion of the ["Network Longevity" roadmap objective](https://lisk.io/roadmap), which is currently not yet implemented. 

The aim of this documentation is to provide a high-level overview of the protocol. A complete technical specification of most parts of the protocol is given in the respective [Lisk Improvemet Proposals](https://github.com/LiskHQ/lips)._
```

2020-02-10 14:42 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +_This documentation only describes the general features of the Lisk protocol version *XXX*. Notice that this is a future version of the Lisk protocol. For a detailed technical explanation go [here]._
The documentation is supposed to be published soon. Therefore, we shouldn't use placeholders for things that are not defined yet or not written yet.

2020-02-10 14:46 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +The [#index-consensus_protocol-1]#*consensus protocol*# specifies who has the right to [#index-forge-1]#*forge*# a new block and how agreement on the validity of a block is reached.
```suggestion
The [#index-consensus_protocol-1]#*consensus protocol*# specifies who has the right to [#index-forge-1]#*forge*# a new block and how agreement on blocks is reached.
```

2020-02-10 14:48 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +The [#index-consensus_protocol-1]#*consensus protocol*# specifies who has the right to [#index-forge-1]#*forge*# a new block and how agreement on the validity of a block is reached.
The validity rules for blocks should be all the same and consensus is rather about reaching agreement on which block belongs to the blockchain rather than whether a block is valid.

2020-02-10 14:52 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +insert big diagram from https://projects.invisionapp.com/share/SRVCPRZ7F83#/screens/398517617_Infographic_-_Contracted[here]
I think it would be better to put the diagram at the end of the "Overview of the Lisk Protocol" section. We could also add an introductory sentence such as "The main characteristics of the Lisk protocol are shown in the following diagram.".

2020-02-10 14:52 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +In an [#index-account_based-1]#*account-based*# blockchain (such as Ethereum, see https://en.wikipedia.org/wiki/Ethereum[Wikipedia page]), the validity of a new transaction is checked against a datab
I would remove the example in brackets here.

2020-02-10 14:53 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +. link:5-network.adoc[*Network*]: This section describes the Lisk P2P network used to exchange information such as blocks or transactions between nodes.
Section 6 and 7 are missing. I would also say that "Lisk Mainnet" should come before the appendix.

2020-02-10 14:59 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +Transactions are gathered in blocks by [#index-delegates-1]#*delegates*#, which are selected using a [#index-delegated_proof_of_stake-1]#*delegated proof-of-stake*# mechanism.
```suggestion
Transactions are gathered in blocks by [#index-delegates-1]#*delegates*#, which are selected using a [#index-delegated_proof_of_stake-1]#*Delegated Proof-of-Stake (DPoS)*# mechanism.
```

2020-02-10 14:59 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +Transactions are gathered in blocks by [#index-delegates-1]#*delegates*#, which are selected using a [#index-delegated_proof_of_stake-1]#*delegated proof-of-stake*# mechanism.
The term in brackets is optional.

2020-02-10 15:26 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +insert big diagram from https://projects.invisionapp.com/share/SRVCPRZ7F83#/screens/398517617_Infographic_-_Contracted[here]
done

2020-02-10 15:26 UTC, janhack commented on modules/ROOT/pages/0-introduction.adoc
> +Transactions are gathered in blocks by [#index-delegates-1]#*delegates*#, which are selected using a [#index-delegated_proof_of_stake-1]#*delegated proof-of-stake*# mechanism.
Same in the accounts section.

2020-02-10 15:27 UTC, janhack commented on modules/ROOT/pages/1-accounts.adoc
> +In link:4-consensus-algorithm.adoc#lisk-delegated-proof-of-stake[Lisk delegated Proof-of-Stake], users link:2-transactions.adoc#vote[vote] for accounts that are registered as delegate accounts.
```suggestion
In link:4-consensus-algorithm.adoc#lisk-delegated-proof-of-stake[Lisk Delegated Proof-of-Stake], users link:2-transactions.adoc#vote[vote] for accounts that are registered as delegate accounts.
```

2020-02-10 15:27 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +Transactions are gathered in blocks by [#index-delegates-1]#*delegates*#, which are selected using a [#index-delegated_proof_of_stake-1]#*delegated proof-of-stake*# mechanism.
done

2020-02-10 15:27 UTC, janhack commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, the state of the blockchain is updated by transactions included in a link:3-blocks.adoc[block]. Every account can issue a transaction, with the corresponding signature and data. There is a s
```suggestion
In Lisk, the state of accounts is updated by transactions included in a link:3-blocks.adoc[block]. Every account can issue a transaction, with the corresponding signature and data. There is a set of different transaction types and each of these types defines a specific logic for modifying accounts depending on the transaction data. In the table below, a summary of these transaction types and the purpose each of them serve is shown. 
```

2020-02-10 15:27 UTC, janhack commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, the state of the blockchain is updated by transactions included in a link:3-blocks.adoc[block]. Every account can issue a transaction, with the corresponding signature and data. There is a s
This would be more inline with the intro and other parts of the protocol documentation.

2020-02-10 15:28 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +The [#index-consensus_protocol-1]#*consensus protocol*# specifies who has the right to [#index-forge-1]#*forge*# a new block and how agreement on the validity of a block is reached.
done

2020-02-10 15:29 UTC, janhack commented on modules/ROOT/pages/2-transactions.adoc
> +The 6 transactions types available in the Lisk protocol are listed in the table displayed above. Each one induces a concrete operation on the blockchain state and is defined by a unique schema and tr
```suggestion
The 6 transactions types available in the Lisk protocol are listed in the table displayed above. Each one induces a concrete operation on accounts and is defined by a unique schema and transaction logic. The type-specific data is given in the `asset` property previously mentioned. The key points and useful information for each of these transactions are commented in the following subsections.
```

2020-02-10 15:29 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +In an [#index-account_based-1]#*account-based*# blockchain (such as Ethereum, see https://en.wikipedia.org/wiki/Ethereum[Wikipedia page]), the validity of a new transaction is checked against a datab
Only the ethereum one? What is the reason?

2020-02-10 15:29 UTC, janhack commented on modules/ROOT/pages/2-transactions.adoc
> +The 6 transactions types available in the Lisk protocol are listed in the table displayed above. Each one induces a concrete operation on the blockchain state and is defined by a unique schema and tr
We talk about operations on the accounts state rather than blockchain state in the other sections.

2020-02-10 15:32 UTC, ricott1 commented on modules/ROOT/pages/0-introduction.adoc
> +. link:5-network.adoc[*Network*]: This section describes the Lisk P2P network used to exchange information such as blocks or transactions between nodes.
done

2020-02-10 15:33 UTC, janhack commented on modules/ROOT/pages/3-blocks.adoc
> +|===
The table needs to be updated to give the values in Beddows (and maybe a separate column for Lisk Mainnet).

2020-02-10 15:44 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +The 6 transactions types available in the Lisk protocol are listed in the table displayed above. Each one induces a concrete operation on the blockchain state and is defined by a unique schema and tr
done

2020-02-10 15:44 UTC, IkerAlus commented on modules/ROOT/pages/2-transactions.adoc
> +In Lisk, the state of the blockchain is updated by transactions included in a link:3-blocks.adoc[block]. Every account can issue a transaction, with the corresponding signature and data. There is a s
done

2020-02-11 08:54 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +== User Interface
changed

2020-02-11 08:54 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +We display addresses in a user-friendly representation including a checksum and the “lsk” prefix.
changed

2020-02-11 08:56 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +=== User-Friendly Address
changed

2020-02-11 08:56 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +The procedure to obtain the [#index-user_friendly_address-1]#*user-friendly address*# from the address is as follows:
changed

2020-02-11 08:57 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Add the prefix "lsk" to the output of step 3. This ensures that all Lisk addresses used in the Lisk wallet start with "lsk" and that the final address is 41 characters long.
changed

2020-02-11 08:58 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +As an example, the address `0xc247a42e09e6aafd818821f75b2f5b0de47c8235` corresponds to the user-friendly address `lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu`.
changed

2020-02-11 08:59 UTC, MaximeGagnebin commented on modules/ROOT/pages/6-appendix.adoc
> +. Encode the output of step 2 in a custom base32 format. Lower-case letters and digits are used, the characters i, l, 1 and 0 are removed for usability reasons.
done

2020-02-13 11:16 UTC, ricott1 submitted a review, later dismissed

2020-02-13 12:23 UTC, IkerAlus submitted a review, later dismissed

2020-02-13 12:37 UTC, AndreasKendziorra submitted a review, later dismissed

2020-02-13 12:57 UTC, MaximeGagnebin approved these changes

2020-02-13 13:18 UTC, IkerAlus approved these changes

2020-02-13 13:29 UTC, AndreasKendziorra approved these changes

2020-02-14 13:36 UTC, merged