Add meta descriptions to Lisk-SDK, closes #371
LiskArchive/lisk-legacy-docs pull request #387
Opened 2020-01-13 09:58 UTC by Tschakki

Closes #371

2020-01-15 15:43 UTC, chris529 requested changes

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-commander/index.adoc
> +:description: The Lisk Commander overview gives an introduction to the Lisk Commander CLI tool its setup and usage.
```suggestion
:description: The Lisk Commander overview provides an introduction to the Lisk Commander CLI tool its setup and usage.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-commander/user-guide.adoc
> +:description: The Lisk Commander user guide describes how to use and how to configure the Lisk Commander to suit your needs.
```suggestion
:description: The Lisk Commander user guide describes how to use and configure the Lisk Commander to suit your requirements.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-commander/user-guide/commands.adoc
> +:description: The Lisk Commander Command Reference lists all available commands of Lisk Commander as a technical reference. For each it comprises all available options, a usage example and an example
```suggestion
:description: The Lisk Commander Command Reference lists each available command of Lisk Commander as a technical reference. For all commands this consists of all available options, a usage example and an example response.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-commander/user-guide/lisk-core.adoc
> +:description: Technical reference about all available commands to manage Lisk Core with Lisk Commander.  For command it lists all available options, a usage example and an example response.
```suggestion
:description: Technical reference regarding each available command used to manage Lisk Core with Lisk Commander.  For all commands all available options, a usage example and an example response are listed.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-commander/user-guide/sensitive-inputs.adoc
> +:description: The sensitive Inputs page describes the different ways how to provide sensitive data like passphrases to Lisk Commander.
```suggestion
:description: The sensitive Inputs page describes the different methods of how to provide sensitive data such as passphrases to the Lisk Commander.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/index.adoc
> +:description: The Lisk Elements overview gives an introduction to the Lisk Elements libray and it's different sub-packages. It describes the basic usage and how to upgrade with NPM.
```suggestion
:description: The Lisk Elements overview provides an introduction to the Lisk Elements library and the different sub-packages. The overall basic usage and how to upgrade with NPM is described here..
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages.adoc
> +:description: The Lisk Elements packages page gives an overview about all available packages of Lisk Elements and direct links to their technical reference. It also comprises the basic usage of a Lis
```suggestion
:description: The Lisk Elements packages page provides an overview regarding all available packages of Lisk Elements and direct links to their associated technical references. In addition, it also comprises of the basic usage of a Lisk Elements package.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client.adoc
> +:description: Technical reference for the API Client package of Lisk Elements. It copmrises usage examples, available options and example responses.
```suggestion
:description: Technical references regarding the API Client package of Lisk Elements. This consists of usage examples, available options and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/accounts.adoc
> +:description: Technical reference for the Accounts endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Account endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/accounts.adoc
> +:description: Technical reference for the Accounts endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Account endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/accounts.adoc
> +:description: Technical reference for the Accounts endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Account endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/accounts.adoc
> +:description: Technical reference for the Accounts endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Account endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/blocks.adoc
> +:description: Technical reference for the Blocks endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Blocks endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/dapps.adoc
> +:description: Technical reference for the DApps endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the DApps endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/delegates.adoc
> +:description: Technical reference for the Delegates endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Delegate endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/node.adoc
> +:description: Technical reference for the Node endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Nodes endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/peers.adoc
> +:description: Technical reference for the Peers endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Peers endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/signatures.adoc
> +:description: Technical reference for the Signatures endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Signatures endpoints of the API Client package of Lisk Elements.This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/transactions.adoc
> +:description: Technical reference for the Transactions endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Transactions endpoints of the API Client package of Lisk Elements.This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/voters.adoc
> +:description: Technical reference for the Voters endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Voter endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/votes.adoc
> +:description: Technical reference for the Votes endpoints of the API Client package of Lisk Elements. It copmrises Usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Vote endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/client.adoc
> +:description: Technical reference for the Client package of Lisk Elements. It copmprises references to all included sub-packages and general usage instructions.
```suggestion
:description: Technical references regarding the Clients packages of Lisk Elements. This consists of references to all included sub-packages and general usage instructions.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/constants.adoc
> +:description: Technical reference for the Constants package of Lisk Elements. It copmrises setup instructions and usage examples.
```suggestion
:description: Technical references regarding the Constants packages of Lisk Elements. This consists of setup instructions and usage examples.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/cryptography.adoc
> +:description: Technical reference for the Cryptography package of Lisk Elements. It copmrises usage examples, available options and example responses.
```suggestion
:description: Technical references regarding the Cryptography packages of Lisk Elements. This consists of usage examples, available options and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/passphrase.adoc
> +:description: Technical reference for the Pasphrase package of Lisk Elements. It copmrises usage examples, available options and example responses.
```suggestion
:description: Technical references regarding the Passphrase package of Lisk Elements. This consists of usage examples, available options and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/transactions.adoc
> +:description: Technical reference for the Transactions package of Lisk Elements. It copmrises usage examples, available options and example responses.
```suggestion
:description: Technical references regarding the Transactions packages of Lisk Elements. This consists of usage examples, available options and example responses.
```

2020-01-15 15:43 UTC, chris529 commented on modules/ROOT/pages/lisk-framework/index.adoc
> +:description: The Lisk Framework overview provides a high-level overview of the Lisk Framework architecture, its modules and components, how they communicate and how to change the default configurati
```suggestion
:description: The Lisk Framework overview provides a high-level overview of the Lisk Framework architecture, including it's modules and components, how they communicate and how to change the default configuration.
```

2020-01-16 07:59 UTC, chris529 submitted a review, later dismissed
minor updates

2020-01-16 07:59 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/signatures.adoc
> +:description: Technical references regarding the Signatures endpoints of the API Client package of Lisk Elements.This consists of usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Signature endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-16 07:59 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/transactions.adoc
> +:description: Technical references regarding the Transactions endpoints of the API Client package of Lisk Elements.This consists of usage examples, available parameters and example responses.
```suggestion
:description: Technical references regarding the Transactions endpoints of the API Client package of Lisk Elements. This consists of usage examples, available parameters and example responses.
```

2020-01-16 08:53 UTC, Tschakki commented on modules/ROOT/pages/lisk-elements/packages/api-client/signatures.adoc
> +:description: Technical references regarding the Signatures endpoints of the API Client package of Lisk Elements.This consists of usage examples, available parameters and example responses.
I would use plural here, because the endpoint is in plural as well

2020-01-16 08:55 UTC, chris529 commented on modules/ROOT/pages/lisk-elements/packages/api-client/signatures.adoc
> +:description: Technical references regarding the Signatures endpoints of the API Client package of Lisk Elements.This consists of usage examples, available parameters and example responses.
Agreed.

2020-01-16 08:56 UTC, chris529 approved these changes

2020-01-16 09:24 UTC, merged