Describe Betanet - Closes #404
LiskArchive/lisk-legacy-docs pull request #420
Opened 2020-01-29 15:32 UTC by Tschakki

Closes #404 
Partially closes #415

2020-01-30 09:09 UTC, chris529 requested changes

2020-01-30 09:09 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To get started in Testnet, get your free Testnet LSK from the {url_faucet_testnet}[Testnet Faucet].
To start using the Testnet, please download your free LSK Testnet from the {url_faucet_testnet}[Testnet Faucet].

2020-01-30 09:09 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The Betanet is the place where the most recent releases of Lisk Core are tested, before moving to Testnet and Mainnet.
The Betanet is where the most recent releases of Lisk Core are tested

2020-01-30 09:09 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The releases for Lisk Core 3.0, 4.0 and 5.0 will all be published on Betanet first.
on the Betanet

2020-01-30 09:09 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +After the new releases have been released on Betanet gradually, they will be released on Testnet and later Mainnet all together, to reduce the number of hard forks in the networks.
After the new releases have been gradually released on the Betanet, they will then be released on the Testnet, and finally all together on the Mainnet , in order to reduce the number of hard forks in the network.

2020-01-30 09:09 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To get started in Betanet, get your free Betanet LSK from the {url_faucet_betanet}[Betanet Faucet].
To start using the Betatnet, please download your free LSK Betanet from the {url_faucet_betanet}[Betanet Faucet].

2020-01-30 09:09 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To connect to Testnet via {url_lisk_desktop}[Lisk Desktop], simply enable the "Network Switcher" in the Settings.
To connect to the Testnet

2020-01-30 15:32 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +To get started in Testnet, get your free Testnet LSK from the {url_faucet_testnet}[Testnet Faucet].
There is nothing to download, it's a faucet that gives you free testnet LSK

2020-01-30 15:33 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The Betanet is the place where the most recent releases of Lisk Core are tested, before moving to Testnet and Mainnet.
Where did the other part of the sentence go?

2020-01-30 15:33 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The releases for Lisk Core 3.0, 4.0 and 5.0 will all be published on Betanet first.
Something is missing here

2020-01-30 15:36 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +After the new releases have been released on Betanet gradually, they will be released on Testnet and later Mainnet all together, to reduce the number of hard forks in the networks.
Not sure if this is clear here: The new version will be released on Betanet gradually, and on Testnet AND Mainnet they will be released together, to reduce the hardforks on Testnet and Mainnet. Myabe this can be formulated better?

2020-01-30 15:36 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +To get started in Betanet, get your free Betanet LSK from the {url_faucet_betanet}[Betanet Faucet].
Same as the comment above, we are not downloading anything :)

2020-01-30 16:37 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The Betanet is the place where the most recent releases of Lisk Core are tested, before moving to Testnet and Mainnet.
Now fixed.

2020-01-30 16:40 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The releases for Lisk Core 3.0, 4.0 and 5.0 will all be published on Betanet first.
Also fixed now.

2020-01-30 16:52 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +After the new releases have been released on Betanet gradually, they will be released on Testnet and later Mainnet all together, to reduce the number of hard forks in the networks.
Yes you are right Mona, it was not so clear. I have now re-formulated this sentence.

2020-01-30 16:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To get started in Betanet, get your free Betanet LSK from the {url_faucet_betanet}[Betanet Faucet].
Good point..I have updated it accordingly.

2020-01-30 17:00 UTC, chris529 requested changes
Hi Mona, It is looking good now, have a look and see what you think :-)

2020-01-31 14:33 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To get started in Betanet, get your free Betanet LSK from the {url_faucet_betanet}[Betanet Faucet].
```suggestion
To get started in Betanet, get your free Betanet LSK from the {url_faucet_betanet}[Betanet Faucet].
```

2020-01-31 14:35 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +To get started in Testnet, get your free Testnet LSK from the {url_faucet_testnet}[Testnet Faucet].
```suggestion
To get started in Testnet, get your free Testnet LSK from the {url_faucet_testnet}[Testnet Faucet].
```

2020-01-31 14:37 UTC, chris529 reviewed
OK, it looks good.

2020-01-31 16:16 UTC, chris529 approved these changes

2020-01-31 16:25 UTC, merged