Update api spec - Closes #419
LiskArchive/lisk-legacy-docs pull request #426
Opened 2020-02-03 14:54 UTC by Tschakki

Closes #419, #415

2020-02-03 15:02 UTC, chris529 commented on modules/ROOT/pages/reference/api.adoc
> +By default, only the nodes' local IP is included in the whitelist, you can change the setting in `config.json` in the section `forging.access.whitelist`.
```suggestion
By default, only the nodes' local IP is included in the whitelist, it is possible to change the setting in `config.json` in the section `forging.access.whitelist`.
```

2020-02-03 15:06 UTC, chris529 requested changes
Only one minor issue :-)

2020-02-03 15:12 UTC, Tschakki commented on modules/ROOT/pages/reference/api.adoc
> +By default, only the nodes' local IP is included in the whitelist, you can change the setting in `config.json` in the section `forging.access.whitelist`.
I will apply this now, but keep in mind the swagger spec is auto generated from the `swagger.yml` file of the Lisk SDK.

So to fix this for good, it needs to be fixed there.

2020-02-04 07:46 UTC, chris529 approved these changes
Looks good Mona :-)

2020-02-04 08:59 UTC, merged