Fix Grammar - Closes #422
LiskArchive/lisk-legacy-docs pull request #428
Opened 2020-02-04 08:49 UTC by chris529

Closes #422

2020-02-04 09:41 UTC, Tschakki requested changes

2020-02-04 09:41 UTC, Tschakki commented on modules/ROOT/pages/getting-started.adoc
> +The xref:{url_binary_installation}[Binary installation] is an easy and automated way to set up Lisk Core, which includes automated update scripts that are almost complete, together with a selection o
```suggestion
The xref:{url_binary_installation}[Binary installation] is an easy and automated way to set up Lisk Core, which includes almost completely automated update scripts, together with a selection of tools to assist with seamlessly maintaining a Lisk Node.
```

2020-02-04 09:41 UTC, Tschakki commented on modules/ROOT/pages/reference/config.adoc
> +<13> Milestone 4. <14> Start rewards at block (n).
Format issues again. Also for the lines below.

2020-02-04 09:41 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +If this is not possible, please refer to the xref:{url_troubleshooting}[Troubleshooting Section].
The Troubleshooting page got removed, we should refer to the new dev forum here

2020-02-06 09:38 UTC, Tschakki requested changes

2020-02-06 09:38 UTC, Tschakki commented on modules/ROOT/pages/update/docker.adoc
> +To updatee a Lisk installation using Docker Compose it is only required to export the new version number in `ENV_LISK_VERSION`.
```suggestion
To update a Lisk installation using Docker Compose it is only required to export the new version number in `ENV_LISK_VERSION`.
```

2020-02-06 09:38 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +TIP: All available options for the Lisk Commander can be seen in the xref:{url_sdk_commander_liskcore}[Command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[general Comman
```suggestion
TIP: All available options can be seen in the xref:{url_sdk_commander_liskcore}[Lisk Commander Command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[general Command reference].
```

2020-02-06 09:38 UTC, Tschakki commented on modules/ROOT/pages/reference/config.adoc
> +Default: 1000 <73> Contains forging options for delegates.
Format broken

2020-02-06 10:17 UTC, chris529 commented on modules/ROOT/pages/reference/config.adoc
> +Default: 1000 <73> Contains forging options for delegates.
It should be fixed now..

2020-02-06 10:26 UTC, Tschakki approved these changes

2020-02-06 10:31 UTC, merged