Create README - Closes #3
LiskArchive/lisk-legacy-docs pull request #43
Opened 2018-08-22 15:12 UTC by Tschakki

Adds a README.md

Closes #3

2018-08-28 13:43 UTC, karmacoma requested changes
I have pushed a number of commits to fix spelling, grammar and improve the standards and readability.

Overall the workflow is great 👍 

Thanks @Tschakki

2018-08-28 13:43 UTC, karmacoma commented on README.md
> +### Hotfixes
Is it a `hotfix` or a `patch`? I feel we should be consistent in our use of terminology here.

2018-09-03 13:26 UTC, karmacoma approved these changes

2018-09-03 14:35 UTC, IkerAlus approved these changes

2018-09-04 10:30 UTC, Nazgolze approved these changes

2018-09-04 13:05 UTC, merged