Update nodejs version to 12 - Closes #356
LiskArchive/lisk-legacy-docs pull request #437
Opened 2020-02-06 11:33 UTC by chris529

Closes #356

2020-02-06 14:55 UTC, Tschakki requested changes

2020-02-06 14:55 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +There are several different methods and version managers used to install Node.JS on your system. Please ensure the latest version is used.
Add `LTS` here.

```suggestion
There are several different methods and version managers used to install Node.JS on your system. Please ensure the latest LTS version is used.
```

2020-02-06 14:55 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +. Install the latest version of Node.js using NVM:
```suggestion
. Install the latest LTS version of Node.js using NVM:
```

2020-02-06 15:21 UTC, Tschakki approved these changes
Thanks!

2020-02-06 16:44 UTC, merged

2020-02-07 10:15 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +nvm install 12.14.1
12.15.1

2020-02-07 10:15 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +brew install node@12.14.1
12.14.1