Create overview pages for core docs - closes #424
LiskArchive/lisk-legacy-docs pull request #457
Opened 2020-02-19 08:24 UTC by chris529

This PR closes issue no. 424 - The creation of overview pages and update to the nav. adoc in the core docs

2020-02-19 16:42 UTC, Tschakki requested changes
Please see my comments :)

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/getting-started.adoc
> +For example, running a Lisk node inside of a Docker on Windows and connecting it via a custom node on Lisk desktop to Lisk Core, without the necessity to rent an additional server.
This sentence is a little weird, imho we can remove it.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +This section covers how to perform the installation of Lisk core using the Lisk commander.
Product names should start with a capital letter.

```suggestion
This section covers how to perform the installation of Lisk Core using the Lisk Commander.
```

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +:url_binary: binary.adoc
Relative URLs always need to start from the `pages` folder.

```suggestion
:url_binary: management/binary.adoc
```

Same for the other URLs below

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +Initially the management section comprises of the following types of Lisk core installation distribution possibilities listed below:-
This paragraph and the following are not quite correct.

The management section includes guides and references concerning the configuration and management of Lisk Core.
It provides a command reference specific for each distribution, and many further guides for example how to enable forging or how to control the API access of a node.

The installation of Lisk Core is explained in the "Setup" section, please make this clear on the overview pages.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +:url_betanet: api.adoc
Relative URLs always need to start from the pages folder.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +The reference overview section covers the api xref:{url_betanet}[Betanet], xref:{url_mainnet}[Mainnet] and the xref:{url_configuration}[configuration] options.
```suggestion
The reference overview section covers the API xref:{url_betanet}[Betanet] and the xref:{url_configuration}[configuration] options.
```

In the current version, we only provide the Betanet API for Lisk Core 3.0.0 (The mainnet api is not linked in the navigation and therefore not visible to the user).
Also, API is an abbreviation and should be in capital letters.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +:url_binary: binary.adoc
Relative URLs always need to start from the pages folder.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/getting-started.adoc
> +This is described in the xref:{url_core_distributions}[Lisk Core Overview] page.
This link is leading to content that is similar to the content displayed on this page.

Please try to remove the redundant content, e.g. by removing it form the Lisk Core Overview page.

Also, the content of the setup overview and the getting-started page might be overlapping/redundant and could be merged as well.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +
I think the structure of this page could be improved: This page shall give the reader a quick overview about what are the different distributions they can choose from, and it should describe characteristics and advantages of each distribution, so the reader can choose quickly which is suiting.

Try to merge the content of the getting started page into here, or maybe just copy it completely and take it as new Setup overview page ;)

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +:url_binary: binary.adoc
Relative URLs always need to start from the pages folder.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +:url_binary: binary.adoc
Relative URLs always need to start from the pages folder.

2020-02-19 16:42 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +This section describes how to perform the necessary updates for xref:{url_binary}[Binary], xref:{url_commander}[Commander], xref:{url_docker}[Docker] and xref:{url_source}[Source] installations. Firs
```suggestion
This section describes how to perform the necessary updates for xref:{url_binary}[Binary], xref:{url_commander}[Commander], xref:{url_docker}[Docker] and xref:{url_source}[Source] installations. 
```

I think the furthermore..  and finally.... phrasing is not entirely fitting here, because we never expect the reader to read through all the updating guides. They will be only interested in the updating guide that is specific to their installed distribution. 

Maybe work with formatting elements like lists and tables to divide the content for the reader in a better way.

2020-02-20 07:54 UTC, chris529 commented on modules/ROOT/pages/getting-started.adoc
> +For example, running a Lisk node inside of a Docker on Windows and connecting it via a custom node on Lisk desktop to Lisk Core, without the necessity to rent an additional server.
Agreed...it does seem somewhat superfluous :-)

2020-02-20 07:55 UTC, chris529 commented on modules/ROOT/pages/management/commander.adoc
> +This section covers how to perform the installation of Lisk core using the Lisk commander.
Agreed

2020-02-20 08:47 UTC, chris529 commented on modules/ROOT/pages/management/index.adoc
> +Initially the management section comprises of the following types of Lisk core installation distribution possibilities listed below:-
```suggestion
The management section includes guides and references concerning the configuration and management of Lisk Core. It provides a command reference specific for each distribution, including many further useful guides. For example, how to enable forging and also how to control the API access of a node.
```

2020-02-20 10:48 UTC, chris529 commented on modules/ROOT/pages/getting-started.adoc
> +This is described in the xref:{url_core_distributions}[Lisk Core Overview] page.
Good point...I have now updated it and merged the contents of the getting-started page, in the overview page.

2020-02-20 11:11 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +
Excellent idea Mona...I have just done this.

2020-02-20 11:11 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +:url_binary: binary.adoc
done

2020-02-20 12:56 UTC, chris529 commented on modules/ROOT/pages/update/index.adoc
> +This section describes how to perform the necessary updates for xref:{url_binary}[Binary], xref:{url_commander}[Commander], xref:{url_docker}[Docker] and xref:{url_source}[Source] installations. Firs
OK, I have re-done it in a different manner. Very simple and concise..  :-)

2020-02-20 14:08 UTC, Tschakki requested changes
Now that you have moved the content form the getting-started page, please remove the getting-started page, which also includes:
- delete the page
- update the navigation
- search for links to the removed page and update them as well

Also please remove the redundant content form the Core overview page like discussed

2020-02-20 14:08 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +Firstly, the information required to install Lisk Core using pre-built binary packages is covered, followed by the
To keep the content of the overview page as concise as possible, I would remove the section from line 17-20

2020-02-21 10:50 UTC, Tschakki requested changes
Please see all my open comments

2020-02-21 10:50 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +For example, running a Lisk node inside of a Docker on Windows and connecting it via a custom node on Lisk desktop to Lisk Core, without the necessity to rent an additional server. This offers the po
I think we agreed to remove this line :)

2020-02-21 10:50 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +Initially the management section comprises of the following types of Lisk core installation distribution possibilities listed below:-
please fix this from your local machine :)

2020-02-24 09:13 UTC, chris529 commented on modules/ROOT/pages/management/index.adoc
> +Initially the management section comprises of the following types of Lisk core installation distribution possibilities listed below:-
OK,  now done..

2020-02-24 12:20 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +Firstly, the information required to install Lisk Core using pre-built binary packages is covered, followed by the
OK, done  :-)

2020-02-24 12:23 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +For example, running a Lisk node inside of a Docker on Windows and connecting it via a custom node on Lisk desktop to Lisk Core, without the necessity to rent an additional server. This offers the po
Yes, OK I have removed it and replaced it with a single sentence.

2020-02-24 15:56 UTC, Tschakki approved these changes
LGTM

2020-02-24 16:11 UTC, merged