Create overview pages for sdk docs - closes #423
LiskArchive/lisk-legacy-docs pull request #458
Opened 2020-02-20 09:53 UTC by chris529

2020-02-20 12:09 UTC, Tschakki requested changes
Please see my comments!

2020-02-20 12:09 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
This overview might be outdated soon, as we will add a lot of other guides to this section.

Try to describe the content of this section in a more general way.

2020-02-20 12:09 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +The reference section is designed to provide the user with a comprehensive description of all the necessary specifications, including user guides for the xref:{url_lisk_commander}[Lisk Commander], xr
Please rephrase this section.
You are describing the reference section, but mention "guides" for Lisk Commander, which is confusing because we have a dedicated guides section for this, so I would avoid to use the word "guides" here. In this section we are describing the technical reference for the Lisk Elements packages and the command reference for Lisk Commander (do not mention Core here).

You can take this blog post as orientation in case you are not sure: https://www.divio.com/blog/documentation/

2020-02-20 14:14 UTC, chris529 commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
OK, I am not really sure how we can make this more general, as there is not much content I can only briefly describe the 2 guides we have at the moment. I have re-worded it, so maybe this helps..

2020-02-20 15:08 UTC, chris529 commented on modules/ROOT/pages/reference/index.adoc
> +The reference section is designed to provide the user with a comprehensive description of all the necessary specifications, including user guides for the xref:{url_lisk_commander}[Lisk Commander], xr
OK, I have tried to re-phrase it somewhat which should be better now..

2020-02-21 08:58 UTC, Tschakki requested changes

2020-02-21 08:58 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +The references for all the following available packages listed below can be found in this section:
Please make clear, that these are references for packages of Lisk Elements.

And you could provide a similar form the  links to the Command references of Commander.

For example like this:

The Lisk Commander reference includes:
- Overview(link)
- Usage Guide(link)
- Command reference(link)
- Core command reference(link)

2020-02-21 08:58 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
I see, hm maybe we can have a first sentence which is more general, like "In the guides section you find concise, goal-oriented how-to guides that help to solve a specific problem."
 And then below you can leave the 2 short descriptions until we have more content 👍

2020-02-21 10:06 UTC, chris529 commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
OK sounds good

2020-02-21 12:55 UTC, chris529 commented on modules/ROOT/pages/reference/index.adoc
> +The references for all the following available packages listed below can be found in this section:
Yes, I have now done this by adding in a link in the first paragraph for the Commander references. This is now followed by the bulk of the references which are the packages, and I have included separate links for all of these, which should assist the user in easily navigating to the required package reference.

2020-02-21 13:33 UTC, Tschakki requested changes

2020-02-21 13:33 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +The references for all the following available packages listed below can be found in this section:
Did you push the changes? I do not see them :/

2020-02-21 13:33 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
I cannot see the discussed change

2020-02-21 13:45 UTC, chris529 commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
Strange...as I can see it on my local drive, and I pushed it a while ago now..There are not massive changes, but if you see the opening statement this has been changed.

2020-02-21 13:51 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +The following guides in this section cover how to configure a blockchain application, which explains how to modify the default values, lists the xref:{url_config}[configuration] options, and describe
Just go to the commits tab to see all commits that you pushed in a chronological order. You also see a chronological overview of all events on the conversation tab of this PR

2020-02-21 14:55 UTC, chris529 commented on modules/ROOT/pages/reference/index.adoc
> +The references for all the following available packages listed below can be found in this section:
It should now be done :-)

2020-02-21 14:57 UTC, Tschakki approved these changes
Thank you!

2020-02-21 15:12 UTC, merged