SDK minor changes and command changes - closes #469
LiskArchive/lisk-legacy-docs pull request #470
Opened 2020-03-02 15:01 UTC by chris529

Minor changes and also minor but important command changes in  SDL docs

2020-03-02 16:11 UTC, Tschakki requested changes
LGTM!
Just left some small comments.

2020-03-02 16:11 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +....
Please use this syntax to display code snippets. It enables syntax highlighting.

```suggestion
[source,bash]
----
touch index.js
----
```

2020-03-02 16:11 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +....
Same here

2020-03-02 16:11 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +<2> Create the folder for the client-side scripts inside the Hello_World folder.
When referring to the folder, use the code syntax. When referring to a name, start with a capital letter and leave spaces between words.

```suggestion
<1> Check that the root folder of the Hello World application is open.
<2> Create the folder for the client-side scripts inside the `hello_world` folder.
```

2020-03-02 16:11 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +<1> Navigate into the root folder of the Hello_World application.
```suggestion
<1> Navigate into the root folder of the Hello World application.
```

2020-03-03 15:57 UTC, Tschakki requested changes

2020-03-03 15:57 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +....
Please check https://asciidoctor.org/docs/user-manual/#applying-source-highlighting

2020-03-04 09:34 UTC, chris529 reviewed
Minor corrections

2020-03-04 09:34 UTC, chris529 commented on modules/ROOT/pages/setup.adoc
> +Install the `lisk-sdk` package as dependency of your project.
```suggestion
Install the `lisk-sdk` package as a dependency of your project.
```

2020-03-04 09:34 UTC, chris529 commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +IMPORTANT: IMPORTANT: Ensure your node is running, before sending the transaction
```suggestion
IMPORTANT: Ensure your node is running  before sending the transaction.
```

2020-03-05 08:49 UTC, Tschakki approved these changes

2020-03-05 09:57 UTC, merged