Fixes broken core docs links - closes #473
LiskArchive/lisk-legacy-docs pull request #474
Opened 2020-03-02 15:46 UTC by chris529

Closes #473

2020-03-03 14:18 UTC, Tschakki requested changes
Please see my comments :)

2020-03-03 14:18 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +The "Interact with the network" page explains the different possibilities for other applications to
This is a weird line break. Please use only 1 sentence per line :)

2020-03-03 14:18 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +A wrapper is a library that holds methods to easily
Here is another weird line break

2020-03-03 14:18 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +brew install curl wget tar unzip zip ntp
this is only macOS specific. Please use the tab-element here to describe both methods:
for Linux with `apt get` and for macOS with `brew`

2020-03-03 14:18 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> ---
Why remove this?

2020-03-03 15:31 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> ---
After discussions with Michiel, he suggested that we should omnly have the Betanet here and not the Mainnet.

2020-03-04 09:23 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +brew install curl wget tar unzip zip ntp
Am not sure how to set up the tabs in Webstorm yet, so I have added in 2 separate sentences  which describes which system is required for each command, followed by the corresponding relevant commands. Please have a look and see if this is OK Mona.

2020-03-04 10:04 UTC, Tschakki requested changes

2020-03-04 10:04 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +brew install curl wget tar unzip zip ntp
It's ok for now, we can add the tabs later.

2020-03-04 10:04 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> -sudo apt-get install curl wget tar unzip zip ntp
This line should not be removed

2020-03-04 10:04 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> ---
I do not agree on this. Right now, we already link to the 2.1.5 version here, which is totally fine imho.
Please undo these changes for now, we can discuss it further in the next docs weekly!

2020-03-04 10:25 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> ---
OK,  I have done this. However, please check it Mona, as I am not convinced this is 100% correct. many thanks!

2020-03-04 10:29 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> -sudo apt-get install curl wget tar unzip zip ntp
As far as I can see, this command on line 41 it has already been removed

2020-03-04 10:37 UTC, Tschakki requested changes

2020-03-04 10:37 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> -sudo apt-get install curl wget tar unzip zip ntp
Yes, that's the problem ;) Please add this line again, it installs the dependencies for linux systems

2020-03-04 10:43 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> -sudo apt-get install curl wget tar unzip zip ntp
Ah yes...sorry. OK, it is now added back in :-)

2020-03-04 10:44 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> ---
I pushed a fix to your branch :)

2020-03-04 10:48 UTC, Tschakki approved these changes
Thank you!

2020-03-04 10:50 UTC, merged