Unify headings titles and breadcrumbs for SDK 2.3.7 - Closes #480
LiskArchive/lisk-legacy-docs pull request #491
Opened 2020-03-09 14:55 UTC by chris529

closes #480

2020-03-11 09:45 UTC, Tschakki requested changes
Please see my comments!

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> += Lisk Commander documentation overview
Change overview title to introduction:
Change to:
```suggestion
= Lisk Commander introduction
```

Also, the banner image seems to be missing still.

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> += Introduction
```suggestion
= Lisk SDK Introduction
```

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/reference/api.adoc
> += Lisk API documentation
The content of this page is auto generated from the `swagger.yml` of the lisk-sdk.
To make the changes permanent, we need to change it over there.

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/reference/config.adoc
> +:url_guide_config: basic-guides/configuration.adoc#modify defaultvalues
what happened here?

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> += Lisk Elements overview
```suggestion
= Lisk Elements introduction
```

Also, the banner image is missing.

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-framework/index.adoc
> += Lisk framework overview
```suggestion
= Lisk Framework introduction
```

Lisk Framework is the product name, and therefore capitalized.

Please fix also all other occurences of this on this page.

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-framework/index.adoc
> +===== List of Core modules
```suggestion
===== List of core modules
```

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/tutorials/cashback.adoc
> +The cashback application implementation steps are described below:
Imho, "Cashback" is the name of the app and therefore should bbe capitalized.

```suggestion
The Cashback application implementation steps are described below:
```

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/setup.adoc
> += SDK setup
Please ensure that all headings of the pages are identical with the links in the navigation (`nav.adoc`).
In this case, it should be
 ```suggestion
= Prerequisites
```

2020-03-11 09:45 UTC, Tschakki commented on modules/ROOT/pages/tutorials/transport0.adoc
> +=== Software pre-requisites
```suggestion
=== Software prerequisites
```

2020-03-11 15:58 UTC, chris529 commented on modules/ROOT/pages/reference/config.adoc
> +:url_guide_config: basic-guides/configuration.adoc#modify defaultvalues
Good question...Am not sure, but I have fixed it.. (see below)

:toc:
:url_guide_config: basic-guides/configuration.adoc##modify_default_values

2020-03-12 08:51 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> += Lisk Elements overview
OK, I have added the banner...I am not sure this is the correct one, so can you please check it Mona..Thanks :-)

2020-03-12 08:57 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-framework/index.adoc
> += Lisk framework overview
OK, its now done :-)

2020-03-12 09:34 UTC, chris529 commented on modules/ROOT/pages/setup.adoc
> += SDK setup
OK it should now be fine..

2020-03-12 09:35 UTC, chris529 commented on modules/ROOT/pages/reference/api.adoc
> += Lisk API documentation
OK,  if this is auto generated do I need to make any changes here..?

2020-03-13 09:18 UTC, Tschakki commented on modules/ROOT/pages/reference/api.adoc
> += Lisk API documentation
We can leave the existing changes for now, but they will be overwritten the next time we generate updated Lisk SDK API docs.

2020-03-13 09:42 UTC, Tschakki requested changes

2020-03-13 09:42 UTC, Tschakki commented on modules/ROOT/pages/reference/config.adoc
> +:url_guide_config: basic-guides/configuration.adoc##modify_default_values
```suggestion
:url_guide_config: basic-guides/configuration.adoc#modify_default_values
```

2020-03-13 09:42 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image::lisk_docu_blog_elements.png[Logo]
I think it is outdated.
Use the same banner as in the lisk-sdk repo: https://github.com/LiskHQ/lisk-sdk/tree/development/elements

2020-03-13 09:42 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +image::diagram_sdk.png[Logo]
Use same banner as here: https://github.com/LiskHQ/lisk-sdk/tree/development/commander

2020-03-13 09:42 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-framework/index.adoc
> += Lisk framework overview
Looks like the title is still wrong. Please simply apply my suggestion.

2020-03-13 09:42 UTC, Tschakki commented on modules/ROOT/pages/tutorials/transport1.adoc
> += Supply chain tutorial part 1: Track a packet on the blockchain
This title does not match the link in the nav. Please ensure for all other titles that they match the nav link, there are probably more to fix.

2020-03-16 16:26 UTC, chris529 commented on modules/ROOT/pages/basic-guides/configuration.adoc
> += Lisk SDK configuration
Done.

2020-03-16 16:27 UTC, chris529 commented on modules/ROOT/pages/basic-guides/customize.adoc
> +=== Required properties
Done.

2020-03-16 16:27 UTC, chris529 commented on modules/ROOT/pages/basic-guides/customize.adoc
> +=== Required methods
Done.

2020-03-16 16:28 UTC, chris529 commented on modules/ROOT/pages/basic-guides/customize.adoc
> +=== Additional methods
Done

2020-03-16 16:33 UTC, chris529 reviewed
Looks good..

2020-03-17 17:00 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image::lisk_docu_blog_elements.png[Logo]
OK, it is nw done..

2020-03-17 17:03 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +image::diagram_sdk.png[Logo]
OK, it is also now done..

2020-03-18 11:05 UTC, chris529 commented on modules/ROOT/pages/tutorials/transport1.adoc
> += Supply chain tutorial part 1: Track a packet on the blockchain
should be ok now..

2020-03-19 09:56 UTC, Tschakki requested changes
Looks good, but the banner images are missing / not displayed, please check again!

2020-03-19 09:56 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image::banner_elements.png[Logo]
The image is not displayed, please check

2020-03-19 09:56 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +:imagesdir: ../../../assets/images
Image is not displayed

2020-03-20 09:14 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image::banner_elements.png[Logo]
OK, it should now work :-)

2020-03-20 09:31 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +:imagesdir: ../../../assets/images
OK, it should now work :-)

2020-03-20 09:43 UTC, Tschakki requested changes
Nearly done, only some nav links are still bold, please fix this :)

2020-03-20 09:43 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  * *Basic Guides*
Please remove bold styling in all navigation items

2020-03-20 09:49 UTC, chris529 commented on modules/ROOT/nav.adoc
>  * *Basic Guides*
oops..yes I seem to have missed this. It should be fixed now ;-)

2020-03-20 09:57 UTC, Tschakki approved these changes
Thank you!

2020-03-20 12:04 UTC, merged