Add new guide: Connect a frontend - Closes #490
LiskArchive/lisk-legacy-docs pull request #492
Opened 2020-03-09 15:32 UTC by Tschakki

Closes #490

2020-03-11 11:02 UTC, slaweet reviewed
I have the following thoughts:
- To guide promises to connect a fontend, but using pug and nodeJs implies that the example is doing all lisk-specific in node on backend. So to me, the guide doesn't deliver what it promises by the title. It's even sending passphrases over the network, which we definitely shouldn't encourage in official examples.
- Who is it aimed at? Beginner front-end dev? Experienced front-end dev? Backend dev? It's not clear now. IMO the assumed knowledge should be clearly stated at the beginning of the guide.
- I was trying to use the hello_world based the guide but couldn't because I got this error: 
<img width="733" alt="Screenshot 2020-03-11 at 11 53 47" src="https://user-images.githubusercontent.com/1254342/76409738-10b51f00-638f-11ea-9d23-80970371f84c.png">

2020-03-11 12:31 UTC, Tschakki commented
@slaweet thanks for feedback!
Concerning your thoughts:

- What content would you have expected by reading the title? For me it's about explaining how to create a client application that useses the lisk-api-client to communicate with a blockchain network, and how to create a basic frontend with the most common actions that people would need to implement in their own client app.
- Imho it is a guide for beginners, not total beginners though. Will add anote about that to the introduction!
- I cannot reproduce your error, for me it works :/

2020-03-11 13:10 UTC, slaweet commented
> * What content would you have expected by reading the title? For me it's about explaining how to create a client application that useses the lisk-api-client to communicate with a blockchain network, and how to create a basic frontend with the most common actions that people would need to implement in their own client app.

It'd expect that it shows how to get lisk-api-client running in a browser (e.g. with webpack) so that it doesn't send the passphrase over the network. With the other frameworks mentioned (React, Vue, Angular) this is the case by default. There might be a way to do it with pug ( there is https://www.npmjs.com/package/html-webpack-pug-plugin) but I'm not too familiar with pug to say for sure.

> * Conserning the passphrase: yeah, its only a basic template ^^ But good point we shouldn't teach bad practices. How should this be realized from your perspective?

> * I cannot reproduce your error, for me it works :/

The problem was that I was running:
```sh
git clone https://github.com/LiskHQ/lisk-sdk-examples.git
cd lisk-sdk-examples/hello_world/client
npm install
node app
```

But I should have also installed node modules in `lisk-sdk-examples/hello_world`:
```sh
git clone https://github.com/LiskHQ/lisk-sdk-examples.git
cd lisk-sdk-examples/hello_world
npm install
cd client 
npm install
node app
```
:point_up_2: this might be worth to have in the guide or in `lisk-sdk-examples/hello_world/client/README.md`

2020-03-12 10:14 UTC, chris529 reviewed
Looks good :-)

2020-03-18 09:43 UTC, slaweet requested changes
Mostly looks great. I have the following ideas and thoughts.

2020-03-18 09:43 UTC, slaweet commented on modules/ROOT/pages/guides/frontend.adoc
> +npm i
Given the guide is using yarn to start the react app, I'd suggest using yarn here as well.
```suggestion
yarn install
cd react-client
yarn install
```

... or the other way - use npm in both

2020-03-18 09:43 UTC, slaweet commented on modules/ROOT/pages/guides/frontend.adoc
> +        this.setState({ data: accountsArray });
I get this loop is fine for a PoC, but might be worth to add some comment explaining it should not be used in production as it doesn't scale with a lot of data.

2020-03-18 09:43 UTC, slaweet commented on modules/ROOT/pages/guides/frontend.adoc
> +node index.js | npx bunyan - o short
Typo:
```suggestion
node index.js | npx bunyan -o short
```

Also, guide assumes that I installed all the non-npm dependencies like postgres, created some database, but doesn't say.

2020-03-18 09:43 UTC, slaweet commented on modules/ROOT/pages/guides/frontend.adoc
> +----
To me, it would make sense to have these bash commands and the other bash commands for starting the app next to each other (maybe here, maybe at the end) and group it by (1) instal and run backend and (2) install and run frontend.

"instal and run backend" might even link to another guide if we have it...

2020-03-18 10:35 UTC, Tschakki commented on modules/ROOT/pages/guides/frontend.adoc
> +npm i
I will change it to npm, as we use it everywhere else in the docs :)

2020-03-18 10:48 UTC, Tschakki commented on modules/ROOT/pages/guides/frontend.adoc
> +        this.setState({ data: accountsArray });
I added warnings everywhere where the loop is used :)
What would be a good approach to make it scale better? Probably adding some kind of pagination right?

2020-03-18 10:51 UTC, slaweet commented on modules/ROOT/pages/guides/frontend.adoc
> +        this.setState({ data: accountsArray });
Pagination, or a button to "Load more", or infinite scroll...

2020-03-18 11:15 UTC, slaweet approved these changes
Perfect 👍

2020-03-18 11:27 UTC, chris529 requested changes
Looks great Mona, just a few very minor points :-)

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +Some popular frameworks for developing apps are for example:
```suggestion
Some popular framework examples for developing apps are listed below:
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +We call it `app.js` in this example.
```suggestion
In this example it is called `app.js`.
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +Note, that this client app is relying on a node with a reachable API, so it might be needed to adjust `API_BASEURL`.
```suggestion
Note, that this client app is relying on a node with a reachable API, so it may be necessary to adjust `API_BASEURL`.
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +In order to process custom transactions, it is needed to require these transaction in the client app as well.
```suggestion
In order to process custom transactions, it is also necessary to require these transactions in the client app as well.
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +To start the web server, run:
```suggestion
To start the web server, execute the following command:
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +With all of the above, you should now have a basic frontend for the Hello world application, that allows users to
```suggestion
At this stage, you should now have a basic frontend for the Hello world application, that allows users to perform the following:
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +TIP: Use this client as template or reference for your own client applications, and adjust it to your needs.
```suggestion
TIP: Use this client as template or reference for your own client applications, and adjust it to suit your requirements.
```

2020-03-18 11:27 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +Alternatively or additionally to the CDN, it is possible to require local CSS files.
```suggestion
Alternatively or additionally to the CDN, it is possible to require the local CSS files.
```

2020-03-18 14:18 UTC, chris529 requested changes
Looks good Mona, just recommended a few minor changes :-)

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +First make sure, you have all xref:{url_setup}[Lisk SDK dependencies] installed, and have a fresh database `lisk_dev`.
```suggestion
Firstly, please  ensure you have all xref:{url_setup}[Lisk SDK dependencies] installed, and have a fresh database `lisk_dev`.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +You should now see a basic frontend for the Hello world application, that allows users to:
```suggestion
At this point, it should now be possible to see a basic frontend for the Hello world application, that allows users to perform the following tasks:
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +TIP: Use this client as template or reference for your own client applications, and adjust it to your needs.
```suggestion
TIP: Use this client as a template or reference for your own client applications, and adjust it to suit your requirements.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +// unregister() to register() below. Note this comes with some pitfalls.
```suggestion
// unregister() to register() below. Please note:  this comes with some pitfalls.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +The `Home` component, which is defined as function at the bottom of `App.js`, is rendered as start page:
```suggestion
The `Home` component, which is defined as function at the bottom of `App.js`, is rendered as the start page:
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +Although classes give more flexibility, functional components can be convenient, for example because less code is needed to write them.
```suggestion
Although classes give more flexibility, functional components can be convenient. For example, as less code is needed to write them.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +If the API url changes in the future, it is only needed to update the `API_BASEURL`.
```suggestion
If the API url changes in the future, it is only required to update the `API_BASEURL`.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +We will import the API client in the necessary components below.
```suggestion
The API client will be imported into the necessary components shown below:
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +A faucet is usually connected to a well funded account in the network, that is used as source to send funds to accounts in order to get started.
```suggestion
A faucet is usually connected to a well funded account in the network, that is used as the source to send funds to accounts in order to get started.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +It is therefore primary useful for Devnets or Testnets.
```suggestion
It is therefore primarily useful for Devnets or Testnets.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +To keep it simple, we do not set any restrictions for the maximum amount and the frequency of requesting new tokens.
```suggestion
In order to simplify this no restrictions are set for the maximum amount and the frequency of requesting new tokens.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +In this example, we send a transfer transaction.
```suggestion
In this example, a transfer transaction is sent.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +In this example, we send the hello transaction.
```suggestion
In this example, a hello transaction is sent.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +This is ok for proof of concept application with not much data.
```suggestion
This is adequate for proof of concept applications with a minimal amount of data.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +For production networks, implement a solution that scales with a big amount of data.
```suggestion
However, for production networks, it would be necessary to implement a solution that has the ability to scale with a large amount of data.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +This is ok for proof of concept application with not much data.
```suggestion
This is adequate for proof of concept applications with a minimal amount of data.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +For production networks, implement a solution that scales with a big amount of data.
```suggestion
However, for production networks, it would be necessary to implement a solution that has the ability to scale with a large amount of data.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +In this example, we filter for hello transactions.
```suggestion
In this example, it is shown how to filter for hello transactions.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +For production networks, implement a solution that scales with a big amount of data.
```suggestion
However, for production networks, it would be necessary to implement a solution that has the ability to scale with a large amount of data.
```

2020-03-18 14:18 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +This is ok for proof of concept application with not much data.
```suggestion
This is adequate for proof of concept applications with a minimal amount of data.
```

2020-03-18 14:54 UTC, chris529 requested changes
Looks very good Mona..I just noticed a few more minor issues :-)

2020-03-18 14:54 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +                  A <Switch> looks through all its children <Route>
```suggestion
                  A <Switch> looks through all of its child <Route> elements, and renders the first one whose path matches the current URL. Use a <Switch> whenever you have multiple routes, but only require one of them to be rendered at a time.
```

2020-03-18 14:54 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +Although classes give more flexibility, functional components can be convenient. For example, as less code is needed to write them.
```suggestion
Although classes give more flexibility, functional components can be convenient. For example, as less code is required to write them.
```

2020-03-18 14:54 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +It is recommended to define the API client in a single file, and import it where needed.
```suggestion
It is recommended to define the API client in a single file, and import it where required.
```

2020-03-18 14:54 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +In this example, we use the genesis account in the faucet.
```suggestion
In this example, the genesis account is used in the faucet.
```

2020-03-18 14:58 UTC, Tschakki commented on modules/ROOT/pages/guides/frontend.adoc
> +                  A <Switch> looks through all its children <Route>
This code is part of the react app, we should not change it.

2020-03-18 15:08 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +                  A <Switch> looks through all its children <Route>
Ah ah..OK then leave it..

2020-03-18 15:10 UTC, chris529 approved these changes
Excellent!

2020-03-18 15:20 UTC, merged