Add new guide: launch a blockchain application - Closes #386
LiskArchive/lisk-legacy-docs pull request #494
Opened 2020-03-11 15:11 UTC by Tschakki

Closes #386

2020-03-19 16:39 UTC, ManuGowda commented on modules/ROOT/pages/guides/launch.adoc
> +They are used by client applications to interact with the blockchain network.
I hope this content is for 2.x.x core version? because some of the information will change for 3.0.0 core

2020-03-20 09:45 UTC, Tschakki commented on modules/ROOT/pages/guides/launch.adoc
> +They are used by client applications to interact with the blockchain network.
This content is for 3.0.2 Lisk SDK docs. What needs to be updated?

2020-03-20 10:45 UTC, ManuGowda submitted a review, later dismissed
Overall LGTM, but one question, this document is intended to 2.x.x? because in 3.x.x many things change.

2020-03-22 11:02 UTC, shuse2 submitted a review, later dismissed

2020-03-22 11:02 UTC, shuse2 commented on modules/ROOT/pages/guides/launch.adoc
> +Client nodes::
Is this the general term that we agree on?
I think we should define the term involving research team to use in the documentation

2020-03-22 11:02 UTC, shuse2 commented on modules/ROOT/pages/guides/launch.adoc
> +const myConfig = {
this looks good as of 2.x and 3.x, but please remember this will slightly change in 4.0

2020-03-23 09:04 UTC, Tschakki commented on modules/ROOT/pages/guides/launch.adoc
> +Client nodes::
I will ask them :)

2020-03-23 09:05 UTC, Tschakki commented on modules/ROOT/pages/guides/launch.adoc
> +const myConfig = {
how will it change?

2020-03-24 09:20 UTC, Tschakki commented on modules/ROOT/pages/guides/launch.adoc
> +Client nodes::
We agreed now, to change the term to `API node`

2020-03-24 10:43 UTC, chris529 requested changes
It is very good Mona, just some minor changes and tidying up.. :-)

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +That enables other users to join the network, which will turn your local 1-node Devnet into an actual blockchain network.
```suggestion
After following this guide it will enable other users to join the network, and will turn your local 1-node Devnet into an actual blockchain network.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Nodes can have different roles in the network:
```suggestion
Nodes can have different roles in the network as described below:
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Beside this, the seed node is a normal node like the others.
```suggestion
Apart from this, the seed node is considered a normal node, and exhibits the same properties as all of the other nodes.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +This is why it must be ensured, that the seed nodes are always reachable and connected to the network.
```suggestion
Hence, this is the reason why the seed nodes must always be both reachable and connected to the network.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +To be actively forging, the delegate needs to be in the top 101.
```suggestion
In order to actively forge, the delegate has to be present in the top 101 delegate list.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The client application communicates via API requests with one or multiple nodes in the network, in order to provide its services.
```suggestion
The client application communicates via API requests with one or more multiple nodes in the network, in order to provide its services.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +For example there can be an additional application that connects a particular IoT device to the blockchain.
```suggestion
For example, there can be an additional application that connects a particular IoT device to the blockchain.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +As shown in the diagram, the plan is to connect a second node with public API, which has forging disabled.
```suggestion
As shown in the diagram below, the plan is to connect a second node with public API which has forging disabled.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +With a setup like this, the client application communicates through the HTTP API with the new node.
```suggestion
With this type of setup, the client application communicates through the HTTP API with the new node.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The seed node communicates at the same time with the new node via WebSockets.
```suggestion
The seed node communicates simultaneously with the new node via WebSockets.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +This way the seed node gets informed by the API node each time a new transaction is sent to the network.
```suggestion
This in turn ensures that the seed node is informed by the API node, each time a new transaction is sent to the network.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +TIP: This architecture is a good way to test, if the WebSocket connection between the seed node and the new node is established.
```suggestion
TIP: Using this architecture it is convenient to test if the WebSocket connection between the seed node and the new node is established.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The exposed `genesisBlockDevnet` and `configDevnet` should only be used during development in a local Devnet, because all credentials of the Devnet genesis delegates and genesis account are public.
```suggestion
The exposed `genesisBlockDevnet` and `configDevnet` should only be used during development in a local Devnet, as all the credentials of the Devnet genesis delegates and genesis account are public.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +This new genesis block should create new genesis accounts, and the created passphrases need to be kept private, so that the genesis accounts cannot be hijacked.
```suggestion
This new genesis block should create new genesis accounts, and the created passphrases need to be kept private in order to ensure that the genesis accounts cannot be hijacked.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The current version of the Lisk SDK does not support to create own genesis blocks, yet.
```suggestion
The current version of the Lisk SDK does not yet support the possibility to create its own genesis blocks.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +In case you still want to create a new genesis block with the current release, check out the {url_lisk_community}[community] tools, for example the {url_github_corbifex}[Genesis block generator by Co
```suggestion
In the case whereby it is required to create a new genesis block with the current release, please see the {url_lisk_community}[community] tools, for example the {url_github_corbifex}[Genesis block generator by Corbifex].
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +When setting up a new node, each new node will firstly connect to the seed nodes when booting for the first time.
```suggestion
When setting up a new node, each new node will initially connect to the seed nodes when booting for the first time.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +CAUTION: It's recommended to keep the config of the seed nodes to yourself, especially if it contains the `defaultpassword` to decrypt the passphrases of the genesis delegates.
```suggestion
CAUTION: It is recommended to keep the config of the seed nodes to yourself, especially if it contains the `defaultpassword` to decrypt the passphrases of the genesis delegates.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +//TODO: Check out the xref:{}[Best practices: seed nodes] section for further recommendations how to configure a seed node.
```suggestion
//TODO: Please see the xref:{}[Best practices: seed nodes] section for further recommendations how to configure a seed node.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +It's recommended to create a config object with all the options that are different to the default config options.
```suggestion
It is recommended to create a config object with all the options that differ from the default config options.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Most of the configurations can stay the same to what is defined in the default config options.
```suggestion
Most of the configurations can remain the same as those already defined in the default config options.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +This provides everyone the opportunity to download the application and deploy it on a server in order to connect with the network.
```suggestion
This provides all users with the opportunity to download the application, and deploy it on a server in order to connect with the network.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +A node application consists of at least the following files:
```suggestion
The minimum amount of files required for a node application can be seen listed below:
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The client application should be distributed in a separate project, and can have any desired structre.
```suggestion
The client application should be distributed in a separate project, and may contain any desired structure as required.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The API node is talking via the API with the `client` app, and over the WebSocket connection to the seed node.
```suggestion
The API node is communicating via the API with the `client` app, and over the WebSocket connection to the seed node.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Just follow the instructions of the `README` file, that was created in the step before.
```suggestion
Just follow the instructions of the `README` file, that was created in the previous step.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Now, the new API node will receive transactions from the client app and vice versa.
```suggestion
At this point the new API node will now receive transactions from the client app and vice versa.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The received transactions are visible in the logs of the lcient node (if log level is at least `info`).
```suggestion
The received transactions will be visible in the logs of the client node, (assuming the log level is at least `info`).
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +.Logs of newly added API node
```suggestion
.Logs of the newly added API node
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +It first synchronizes the missing blocks up to the current height and then broadcasts the received transactions from the client app to the seed node, whereby the delegates can then add the transactio
```suggestion
It first synchronises the missing blocks up to the current height, and then broadcasts the received transactions from the client app to the seed node, whereby the delegates can then add the transactions to blocks and forge them.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +.Please be aware that broadcast hickups can occur.
```suggestion
.Please be aware that broadcast anomalies may occur.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +There is no cause for concern here, as the node will re-start the sync process again; and in the majority of cases it is successful on the next attempt.
```suggestion
There is no cause for concern here as the node will re-start the sync process again; and in the majority of cases it is successful on the next attempt.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +As a result, also the following blocks are also discarded by the node.
```suggestion
As a result, the following blocks are also discarded by the node.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +. Create an own, private account on the network
```suggestion
. Create an own, private account on the network.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +.. Send some funds(at least enough to register as a delegate) to the newly generated address.
```suggestion
.. Send some funds, (which must be an adequate amount in order to register as a delegate) to the newly generated address.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +. Register a delegate
```suggestion
. Register a delegate.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +** Is helpful
```suggestion
** Is helpful.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +** Is accountable
```suggestion
** Is accountable.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +** Is sharing rewards
```suggestion
** Is sharing rewards.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +** Is offering useful services or tools
```suggestion
** Is offering useful services or tools.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +If a delegate joins the network on a very early stage, he or she will probably replace one of the genesis delegates.
```suggestion
If a delegate joins the network at a very early stage, it is likely they will probably replace one of the genesis delegates.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Therefore, when replacing a genesis delegate, the new delegate will need to convince the person who controls the genesis account of the network; which will be most likely the app developer.
```suggestion
Therefore, when replacing a genesis delegate, the new delegate will need to convince the person who controls the genesis account of the network; which will most likely be the app developer.
```

2020-03-24 10:43 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +Later, when the majority of the existing tokens are distributed among the different private accounts, the new delegate needs to gain the trust of the community in order to be voted into a forging pos
```suggestion
Later, when the majority of the existing tokens are distributed amongst the different private accounts, the new delegate needs to gain the trust of the community in order to be voted into a forging position.
```

2020-03-24 10:43 UTC, chris529 requested changes
It is very good Mona, just some minor changes and tidying up.. :-)

2020-03-24 11:08 UTC, Tschakki commented on modules/ROOT/pages/guides/launch.adoc
> +The client application communicates via API requests with one or multiple nodes in the network, in order to provide its services.
Do you say "more multiple?" is this correct?

2020-03-24 11:17 UTC, Tschakki commented on modules/ROOT/pages/guides/launch.adoc
> +.Please be aware that broadcast hickups can occur.
Idk here, but "anomalie" sounds like something serious.... But the heading should already tell the user it's no concern if they occur.
```suggestion
.Broadcast "hickups" are no concern
```

2020-03-24 14:50 UTC, chris529 requested changes
Looks very good Mona, please see the comments.. :-)

2020-03-24 14:50 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +The client application communicates via API requests with one or multiple nodes in the network, in order to provide its services.
Yes, ''more multiple nodes''  is definitely correct.. :-)

2020-03-24 14:50 UTC, chris529 commented on modules/ROOT/pages/guides/launch.adoc
> +.Please be aware that broadcast hickups can occur.
Well, you could have 'irregularities or even 'inconsistencies' if you don't like anomalies...However hiccups is not really the correct word in these circumstances.  In this case I would then suggest ''irregularities''  :-)

2020-03-24 15:17 UTC, chris529 approved these changes
Wunderbar! :-)

2020-03-24 15:21 UTC, merged