Unify headings titles and breadcrumbs for SDK 3.0.2 - closes#479
LiskArchive/lisk-legacy-docs pull request #495
Opened 2020-03-11 15:18 UTC by chris529

closes #479

2020-03-13 10:23 UTC, Tschakki requested changes
Please see my comments, and also check the points in the issue description again, e.g.

- nav.adoc still has bold links .  OK,  this one is now fixed..
- title redundancy not removed (see config reference)  - done.
- unify headings and nav links: not all are unified (see e.g. lisk transport tutorial)  - also done..

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/reference/api.adoc
> +== Access restrictions
As already mentioned in the SDK 2.3.7 PR, this content is auto generated, so will be overridden in future ;)

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +image:diagram_sdk.png[Logo]
Please use this banner: https://github.com/LiskHQ/lisk-sdk/tree/development/commander

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +:description: The Lisk elements overview provides an introduction to the Lisk elements library and the different sub-packages. The overall basic usage and how to upgrade with NPM is described here.
```suggestion
:description: The Lisk Elements overview provides an introduction to the Lisk elements library and the different sub-packages. The overall basic usage and how to upgrade with NPM is described here.
```

Lisk Elements is the product name :) Please capitalize, see also the other occurrences on the page.

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/packages/api-client.adoc
> +:description: Technical references regarding the API client package of Lisk elements. This consists of usage examples, available options and example responses.
```suggestion
:description: Technical references regarding the API client package of Lisk Elements. This consists of usage examples, available options and example responses.
```

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-framework/index.adoc
> +:description: The Lisk framework overview provides a high-level synopsis of the Lisk framework architecture, including it's modules and components, how they communicate, and also how to change the de
```suggestion
:description: The Lisk Framework overview provides a high-level synopsis of the Lisk Framework architecture, including it's modules and components, how they communicate, and also how to change the default configuration.
```

Please fix everywhere

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/tutorials/transport1.adoc
> +In order to save and exit `nano`, using the following keys:
I think it was correct like it was, no change needed

2020-03-13 10:23 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image:lisk_docu_blog_elements.png[Logo]
Please use same banner image as in lisk-sdk repo

2020-03-17 09:47 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +image:diagram_sdk.png[Logo]
OK, now the correct logo is inserted :-)

2020-03-17 09:49 UTC, chris529 commented on modules/ROOT/pages/tutorials/transport1.adoc
> +In order to save and exit `nano`, using the following keys:
OK, let's leave it as it is.

2020-03-17 09:57 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image:lisk_docu_blog_elements.png[Logo]
OK, it is done..

2020-03-17 13:37 UTC, Tschakki requested changes

2020-03-17 13:37 UTC, Tschakki commented on modules/ROOT/pages/reference/changelog.adoc
> +Due to the changes that have been introduced for the structure of transaction objects, the genesis block and it's transactions were recently generated for Lisk SDK version 3.0.
```suggestion
Due to the changes that have been introduced for the structure of transaction objects, the genesis block and it's transactions were created new for Lisk SDK version 3.0.
```

2020-03-17 13:37 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-commander/user-guide/commands.adoc
> +This command uses Lisk-elements passphrase module to encrypt a message you provide for a given public key using a randomly generated nonce.
```suggestion
This command uses Lisk Elements passphrase module to encrypt a message you provide for a given public key using a randomly generated nonce.
```

2020-03-17 13:37 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +:description: The Lisk Elements overview provides an introduction to the Lisk elements library and the different sub-packages. The overall basic usage and how to upgrade with NPM is described here.
Lisk Elements is the product name, please capitalize everywhere.

```suggestion
:description: The Lisk Elements overview provides an introduction to the Lisk Elements library and the different sub-packages. The overall basic usage and how to upgrade with NPM is described here.
```

2020-03-17 13:37 UTC, Tschakki commented on modules/ROOT/pages/tutorials/transport.adoc
> +For convenient usage of the system, a client application called Lisk transport will be provided that visualizes all relevant information regarding the supply chain tracking system. In turn the Lisk t
```suggestion
For convenient usage of the system, a client application called Lisk Transport will be provided that visualizes all relevant information regarding the supply chain tracking system. In turn the Lisk Transport application enables the users to interact with the system by posting custom transactions.
```

Lisk Transport is the name of the app, please update everywhere

2020-03-17 13:37 UTC, Tschakki commented on modules/ROOT/pages/tutorials/transport1.adoc
> +In order to save and exit `nano`, using the following keys:
can you then please undo the change?

2020-03-19 10:05 UTC, Tschakki requested changes
Please check the banner images again - did you upload them to the images folder?

2020-03-19 10:05 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +image:banner_commander.png[Logo]
Please check image

2020-03-19 10:05 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image:banner_elements.png[Logo]
Image missing

2020-03-19 14:21 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-commander/index.adoc
> +image:banner_commander.png[Logo]
OK, I think it has now worked :-)

2020-03-19 14:23 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/index.adoc
> +image:banner_elements.png[Logo]
It should now be OK

2020-03-19 15:11 UTC, Tschakki approved these changes
Thank you!

2020-03-19 15:19 UTC, merged