Unify headings titles and breadcrumbs for Core docs 2.1.5 - closes #477
LiskArchive/lisk-legacy-docs pull request #496
Opened 2020-03-16 14:01 UTC by chris529

closes #477

2020-03-17 12:57 UTC, Tschakki requested changes

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:setup/source.adoc[Setup Source]
Remove redundancy in titles: 

```suggestion
** xref:setup/binary.adoc[Binary]
** xref:setup/commander.adoc[Commander]
** xref:setup/docker.adoc[Docker]
** xref:setup/source.adoc[Source]
```

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:update/source.adoc[Update Source]
```suggestion
** xref:update/binary.adoc[Binary]
** xref:update/commander.adoc[Commander]
** xref:update/docker.adoc[Docker]
** xref:update/source.adoc[Source]
```

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  * *Management*
Please remove boldness from all navigation links
```suggestion
* Management
```

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:image:lisk_docu_blog_core.png[Logo]
Use this banner: https://github.com/LiskHQ/lisk-core

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +When to update, and when to migrate to Lisk Core?
```suggestion
When to update, and when to migrate Lisk Core?
```

We are migrating Lisk Core to a new version, it should be correct like this.

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +=== A - Write scripts in javascript
```suggestion
=== A - Write scripts in JavaScript
```

Please use this capitalisation everywhere

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The Lisk Core is the program that actually implements the Lisk protocol.
```suggestion
Lisk Core is the program that actually implements the Lisk protocol.
```

2020-03-17 12:57 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> += Setup Binary
```suggestion
= Binary
```

Please remove redundant titles on the other pages as well.

2020-03-17 15:40 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:image:lisk_docu_blog_core.png[Logo]
done

2020-03-19 15:17 UTC, Tschakki requested changes

2020-03-19 15:17 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:image:banner_core.png[Logo]
The image is missing.

2020-03-19 16:29 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:image:banner_core.png[Logo]
OK it should be there now.. ;-)

2020-03-20 09:36 UTC, Tschakki requested changes
Nearly good!  Just 2 small issues, see comments.

2020-03-20 09:36 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  * *Setup*
Please remove bold styling here and on all other bold navigation items

2020-03-20 09:36 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:image:banner_core.png[Logo]
Ok nice! Only one small issue:
```suggestion
image:banner_core.png[Logo]
```

2020-03-20 11:01 UTC, chris529 commented on modules/ROOT/nav.adoc
>  * *Setup*
ok it is done..

2020-03-20 11:06 UTC, Tschakki approved these changes
LGTM

2020-03-20 12:15 UTC, merged