Add guide: Enable forging - Closes #498
LiskArchive/lisk-legacy-docs pull request #500
Opened 2020-03-20 10:56 UTC by Tschakki

Closes #498

2020-03-20 13:31 UTC, chris529 requested changes
Excellent, just a few minor issues ;-)

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +Forging in DPoS networks is the same as mining in PoW network: It is the process of adding new blocks to the chain.
```suggestion
Forging in DPoS networks is the same as mining in a PoW network: It is the process of adding new blocks to the chain.
```

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +In DPoS system, each account that has enough balance to send a "register delegate" transaction can register a new delegate on the network.
```suggestion
In a DPoS system, each account that has an adequate enough balance to send a "register delegate" transaction can register a new delegate on the network.
```

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +The 101 delegates with the most accumulated vote weight are in the active forging positions and each of them is allowed to forge one block in each round (a round lasts 101 blocks, then a new round st
```suggestion
The 101 delegates with the most accumulated vote weight are in the active forging positions, and each of them is allowed to forge one block in each round, (a round lasts for 101 blocks, after this then a new round starts).
```

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +As reward for securing the network, the forging nodes receive the transaction fees and the block rewards of the forged blocks and their included transactions.
```suggestion
As a reward for securing the network, the forging nodes receive the transaction fees and the block rewards of the forged blocks and their included transactions.
```

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +<6> Replace with the IP address which will be used to access the node
```suggestion
<6> Replace with the IP address which will be used to access the node.
```

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +TIP: Restart the node apply the changes in the config.
```suggestion
TIP: Restart the node and apply the changes in the config.
```

2020-03-20 13:31 UTC, chris529 commented on modules/ROOT/pages/guides/forging.adoc
> +* The HTTP Port can be different based on your configuration, therefore it is recommended to check the `httpPort` in your config/
```suggestion
* The HTTP Port can be different based on your configuration, therefore it is recommended to check the `httpPort` in your config.
```

2020-03-23 09:22 UTC, Tschakki commented on modules/ROOT/pages/guides/forging.adoc
> +TIP: Restart the node apply the changes in the config.
```suggestion
TIP: Restart the node to apply the changes in the config.
```

2020-03-23 13:13 UTC, chris529 approved these changes
Perfect.. :-)

2020-03-23 13:32 UTC, merged