Unify headings titles and breadcrumbs for Core 3.0.0 beta 0 - closes #478
LiskArchive/lisk-legacy-docs pull request #506
Opened 2020-03-23 17:12 UTC by chris529

closes #478

2020-03-24 09:19 UTC, Tschakki requested changes

2020-03-24 09:19 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +:url_api: reference/lisk-elements/api.adoc
Why change this?

2020-03-24 09:19 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +:description: The Lisk Core commander administration describes all relevant commands to manage Lisk Core through the command-line with Lisk Commander.
```suggestion
:description: The Lisk Core Commander administration describes all relevant commands to manage Lisk Core through the command-line with Lisk Commander.
```

2020-03-24 09:19 UTC, Tschakki commented on modules/ROOT/pages/migration.adoc
> +<1> Change to Lisk user.
```suggestion
<1> Change to `lisk` user.
```

2020-03-24 09:19 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/packages/api-client/transactions.adoc
> += Transactions
This complete page belongs to SDK docs, please remove it here

2020-03-24 09:19 UTC, Tschakki commented on modules/ROOT/pages/update/source.adoc
> +:description: The Lisk Core Source upgrade page describes how to upgrade Lisk Core to the latest version from source.
```suggestion
:description: The Lisk Core Source update page describes how to update Lisk Core to the latest version from source.
```

2020-03-24 09:19 UTC, Tschakki commented on modules/ROOT/pages/update/source.adoc
> +This section describes how to upgrade Lisk Core from source.
```suggestion
This section describes how to update Lisk Core from source.
```

2020-03-24 11:05 UTC, chris529 commented on modules/ROOT/pages/interact-with-network.adoc
> +:url_api: reference/lisk-elements/api.adoc
Ah, yes...good point..leave it as it was originally 👍

2020-03-24 13:38 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/packages/api-client/transactions.adoc
> += Transactions
Ah yes...now done :-)

2020-03-24 14:08 UTC, Tschakki requested changes

2020-03-24 14:08 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +:url_api: reference/lisk-elements/api.adoc
Did you push the change? :)

2020-03-25 10:12 UTC, chris529 commented on modules/ROOT/pages/interact-with-network.adoc
> +:url_api: reference/lisk-elements/api.adoc
yes

2020-03-25 11:35 UTC, Tschakki requested changes

2020-03-25 11:35 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +:url_api: reference/lisk-elements/api.adoc
I don't think so. The link gets still updated. You wanted to revert it to its original state.

2020-03-25 11:49 UTC, Tschakki approved these changes
Thank you!

2020-03-25 15:25 UTC, merged