Update test guide - Closes #514
LiskArchive/lisk-legacy-docs pull request #518
Opened 2020-04-01 12:07 UTC by Tschakki

Closes #514

2020-04-02 15:47 UTC, chris529 requested changes
Looks good, just a few minor points :-)

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +To explain how to write unit tests for custom transactions, we will use the example of the `applyAsset()` method of the {url_github_hello_world}[hello world app] .
```suggestion
In order to explain how to write unit tests for custom transactions, the `applyAsset()` method of the {url_github_hello_world}[hello world app] example is used here.
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  You can use it as template to write unit tests for your own custom transactions.
```suggestion
It can be used as a template to write unit tests for your own custom transactions.
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +First, let's look at the `applyAsset()` function of the {url_github_hello_world_tx}[HelloTransaction].
```suggestion
Firstly, it is recommended to view the `applyAsset()` function of the {url_github_hello_world_tx}[HelloTransaction].
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  This allows replace the call with a custom return value.
```suggestion
This allows the possibility to replace the call with a custom return value.
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +<2> Here starts the first test, with a short and precise description of what the test is about.
```suggestion
<2> Now the first test can begin, with a short and precise description of the actual test itself.
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  Therefore, we check if `storeStub.account.set()` got called with the right parameters:
```suggestion
Therefore, a check is performed to ensure that the `storeStub.account.set()` was called with the correct parameters:
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +If the function got called with the expected parameters, we know that the sender account was updated correctly.
```suggestion
If the function was called with the expected parameters, then this proves that the sender account was updated correctly.
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +In the second test, we want to verify that the transaction gets rejected, in case the sender has already a hello string in their account.
```suggestion
In the second test it is necessary to verify that the transaction is rejected, in the case whereby the sender already has a hello string in their account.
```

2020-04-02 15:47 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +Therefore, we check if the expected `TransactionError` is returned when `applyAsset()` is executed.
```suggestion
Therefore, it is necessary to check if the expected `TransactionError` is returned when the `applyAsset()` is executed.
```

2020-04-03 13:42 UTC, chris529 requested changes
excellent, just a few minor points :-)

2020-04-03 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  Therefore it is recommended to write {url_unit_tests}[unit tests], that verify the logic of the transaction type.
```suggestion
Therefore it is recommended to write {url_unit_tests}[unit tests], that verifies the logic of the transaction type.
```

2020-04-03 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +First, let's look at the `applyAsset()` function of the {url_github_hello_world_tx}[HelloTransaction].
```suggestion
Firstly, it is recommended to view the `applyAsset()` function of the {url_github_hello_world_tx}[HelloTransaction].
```

2020-04-03 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +To test, that the `applyAsset()` function is working as expected, write a unit test with {url_jest}[jest]: {url_github_transport_test_register}[hello_transaction.test.js]:
```suggestion
To test that the `applyAsset()` function is working as expected, write a unit test with {url_jest}[jest]: {url_github_transport_test_register}[hello_transaction.test.js]:
```

2020-04-03 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +    it('should reject the transaction, if the sender has already a hello string in their account.', async () => {
```suggestion
    it('should reject the transaction, if the sender already has a hello string in their account.', async () => {
```

2020-04-03 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  This allows replace the call with a custom return value.
```suggestion
This allows the user to have the opportunity to replace the call with a custom return value.
```

2020-04-03 13:45 UTC, Tschakki commented on modules/ROOT/pages/guides/test.adoc
> +First, let's look at the `applyAsset()` function of the {url_github_hello_world_tx}[HelloTransaction].
I would not say "it's recommended" here.
It's just normal to look at the method you want to test.

2020-04-03 13:45 UTC, Tschakki commented on modules/ROOT/pages/guides/test.adoc
>  Therefore it is recommended to write {url_unit_tests}[unit tests], that verify the logic of the transaction type.
I think it was correct as it was

2020-04-06 08:31 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  Therefore it is recommended to write {url_unit_tests}[unit tests], that verify the logic of the transaction type.
yes, you are right Mona, please leave it as it was.

2020-04-06 08:32 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +First, let's look at the `applyAsset()` function of the {url_github_hello_world_tx}[HelloTransaction].
OK, then in this case we can leave it as it is.. :-)

2020-04-06 08:41 UTC, chris529 reviewed
Looks very good, just a couple of small points :-)

2020-04-06 08:41 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
> +Stubbing allows to replace the call of a function with a custom return value.
```suggestion
Stubbing provides the opportunity to replace the call of a function with a custom return value.
```

2020-04-06 08:41 UTC, chris529 commented on modules/ROOT/pages/guides/test.adoc
>  <3> When `storeStub.account.get` is called with `asset.senderId`, we replace the return value with the `mockedSenderAccount`.
```suggestion
<3> When `storeStub.account.get` is called with `asset.senderId`,the return value is replaced with the `mockedSenderAccount`.
```

2020-04-06 14:10 UTC, chris529 approved these changes
Perfect :-)

2020-04-06 14:12 UTC, merged