Fix titles in test, broadcast and interact with network pages in SDK docs - closes #540
LiskArchive/lisk-legacy-docs pull request #542
Opened 2020-04-09 15:44 UTC by chris529

closes #540

2020-04-14 08:53 UTC, Tschakki requested changes
Why are you fixing Hello World here? Isn't this already done in #539 ?

2020-04-15 09:40 UTC, chris529 commented
Hi Mona, Apologies this was an error...You are correct 'Hello World' was done in #539

2020-04-15 09:49 UTC, chris529 reviewed
Looks good..

2020-04-15 11:12 UTC, chris529 reviewed
Only 1 minor point :-)

2020-04-15 11:12 UTC, chris529 commented on modules/ROOT/pages/guides/index.adoc
> +If you wish to follow the guides on a 1-to-1 basis, it is recommend to set up the 'Hello World' app as described below.
```suggestion
If you wish to follow the guides on a 1-to-1 basis, it is recommended to set up the 'Hello World' app as described below.
```

2020-04-15 11:26 UTC, Tschakki requested changes
Please check for occurrences of the old titles in the other pages, and update them as well

2020-04-15 15:34 UTC, chris529 commented
OK, I found a couple of occurrences of references to the old titles and have now updated and pushed them into this branch.  Please have a quick look Mona, thanks.

2020-04-16 10:33 UTC, Tschakki requested changes
Ok great! Please resolve the conflict, then it should be good to go :)

2020-04-17 10:43 UTC, chris529 reviewed
Look good :-)

2020-04-17 10:49 UTC, Tschakki requested changes
Please fix the conflict

2020-04-17 13:30 UTC, Tschakki approved these changes
Thank you! :)

2020-04-17 13:32 UTC, merged