Update connect frontend/supply chain pages and remove hello world page in SDK docs - closes #548
LiskArchive/lisk-legacy-docs pull request #549
Opened 2020-04-16 10:16 UTC by chris529

Closes #548

2020-04-16 11:01 UTC, Tschakki requested changes
Please remove hello world tutorials also from navigation, and check if there are any remaining references go the tutorials that need to be removed as well.

2020-04-16 11:01 UTC, Tschakki commented on modules/ROOT/pages/guides/frontend.adoc
> +However, it is recommended to use React to create a frontend.
I would remove this line here. We are generally framework agnostic.

2020-04-16 11:01 UTC, Tschakki commented on modules/ROOT/pages/guides/frontend.adoc
> -Choose a framework based on personal preference.
Keep this line, and add something like:

NOTE: Lisk uses React.js as framework of choice for the examples in the documentation

2020-04-16 14:23 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> +However, it is recommended to use React to create a frontend.
OK, now done 👍

2020-04-16 14:31 UTC, chris529 commented on modules/ROOT/pages/guides/frontend.adoc
> -Choose a framework based on personal preference.
Excellent idea Mona...now done 👍

2020-04-16 14:44 UTC, Tschakki requested changes

2020-04-16 14:44 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_tutorials_hello}[Hello World guide] is used as an example here.
```suggestion
The `HelloTransaction` of the xref:{url_tutorials_hello}[Hello World app] is used as an example here.
```

2020-04-16 14:44 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_tutorials_hello}[Hello World guide] is used as an example here.
```suggestion
The `HelloTransaction` of the xref:{url_tutorials_hello}[Hello World app] is used as an example here.
```

2020-04-16 14:44 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_tutorials_hello}[Hello World guide] is used as an example here.
```suggestion
The `HelloTransaction` of the xref:{url_tutorials_hello}[Hello World app] is used as an example here.
```

2020-04-16 14:44 UTC, Tschakki commented on modules/ROOT/pages/tutorials/index.adoc
> +:url_hello: guides/index.adoc#_the_hello_world_app
We should not link to the guides index here, as the tutorial got removed, so should the link here be removed.

2020-04-17 09:56 UTC, chris529 commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_tutorials_hello}[Hello World guide] is used as an example here.
done...suggestion committed.

2020-04-17 10:36 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +:url_hello: guides/index.adoc#_the_hello_world_app
Ok, now done 👍

2020-04-17 10:56 UTC, Tschakki requested changes
Please set a custom anchor id for the hello world app on the `guides/index.adoc` page, to follow the style guide.

2020-04-17 10:59 UTC, Tschakki requested changes
And also please remove the whole table row of hello world in the tutorials index .

2020-04-17 11:01 UTC, Tschakki requested changes

2020-04-17 11:01 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_guides_hello}[Hello World App] is used as an example here.
```suggestion
The `HelloTransaction` from the xref:{url_guides_hello}[Hello World app] is used as an example here.
```

2020-04-17 11:01 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_guides_hello}[Hello World App] is used as an example here.
```suggestion
The `HelloTransaction` from the xref:{url_guides_hello}[Hello World app] is used as an example here.
```

2020-04-17 11:01 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +The `HelloTransaction` from the xref:{url_guides_hello}[Hello World App] is used as an example here.
```suggestion
The `HelloTransaction` from the xref:{url_guides_hello}[Hello World app] is used as an example here.
```

2020-04-21 14:00 UTC, chris529 commented
Hi Mona, the 2 requested changes above should now be done.. :-)

2020-04-22 09:51 UTC, Tschakki requested changes
Ok great! Please also fix the existing conflicts.

2020-04-22 11:55 UTC, Tschakki requested changes
OK great! Just one minor issue

2020-04-22 11:55 UTC, Tschakki commented on modules/ROOT/pages/guides/broadcast.adoc
> +:url_guides_hello: guides/index.adoc#_the_hello_world_app
Please create a custom ID and use it here

2020-04-23 09:40 UTC, chris529 commented on modules/ROOT/pages/guides/broadcast.adoc
> +:url_guides_hello: guides/index.adoc#_the_hello_world_app
OK done..

2020-04-24 07:49 UTC, Tschakki requested changes
Please fix the conflicts :)

2020-04-24 10:02 UTC, chris529 commented
Conflicts should be resolved now :-)

2020-04-24 12:51 UTC, Tschakki approved these changes
Thank you!

2020-04-24 12:52 UTC, merged