Remove kirby styles from protocol, Partially closes #39
LiskArchive/lisk-legacy-docs pull request #56
Opened 2018-08-28 10:55 UTC by Tschakki

Partially closes #39

2018-08-28 11:40 UTC, janhack commented on consensus/consensus.md
> +|  | milestones: [
The info note links seems to be not working.

2018-08-28 11:47 UTC, janhack commented on deprecated-transactions/deprecated-transactions.md
>  This section acts as historical documentation and is presented for transaction types that are no longer supported, but still active within the system. These transactions refer to legacy applications
If @IkerAlus agrees, I would remove the folder deprecated-transactions as this is not used any more and all content got already merged into the transactions sections.

2018-08-28 11:48 UTC, janhack commented on network-rewards/network-rewards.md
This file seems to be also an old version that already was merged into the consensus section. If @IkerAlus agrees, I would also remove it as the content is already contained in the consensus section.

2018-08-28 11:56 UTC, janhack commented on peer-to-peer-communication/p2p-comunication.md
>  ##Transaction Propagation
I think there is a whitespace missing after the ## so that the headings are formatted correctly in Github.

2018-08-28 11:56 UTC, janhack commented on peer-to-peer-communication/p2p-comunication.md
>  ##Transaction Pool
I think there is a whitespace missing after the ## so that the headings are formatted correctly in Github.

2018-08-28 11:58 UTC, janhack commented on security/security.md
>  ```
You missed the following above:  (image: lisk_protocol-keypair.png)

2018-08-28 12:01 UTC, janhack requested changes
I went through everything, but only quickly checked if the Github output was correct and if there were any pictures missing. I did not read all the source thoroughly again.

2018-08-28 12:57 UTC, IkerAlus commented on deprecated-transactions/deprecated-transactions.md
>  This section acts as historical documentation and is presented for transaction types that are no longer supported, but still active within the system. These transactions refer to legacy applications
Agreed!

2018-08-28 12:57 UTC, IkerAlus commented on network-rewards/network-rewards.md
Same agreed!

2018-08-28 13:02 UTC, IkerAlus submitted a review, later dismissed
Once @janhack 's changes are implemented, this looks good to go.

2018-08-28 13:34 UTC, Tschakki commented
Hey, thanks for the fast feedback! I made the suggested changes, please approve if everything is alright :)

2018-08-28 14:19 UTC, janhack commented on introduction.md
> +[Blocks](blocks/blocks.md) | [Peers Communication](peer-to-peer-communication/p2p-communication.md)
The link for the p2p communication is broken because you spelled the file name only with one m.

2018-08-28 14:21 UTC, janhack commented on peer-to-peer-communication/p2p-comunication.md
>  The transaction pool provides the Lisk network a robust solution for preserving unconfirmed transactions that have overflowed into the next block. As described in  [**blocks**](/documentation/lisk-pr
The link to the blocks section is invalid.

2018-08-28 14:24 UTC, janhack commented on transactions/transactions.md
All links to other sections above are invalid. Please also check all other links to sections in this document.

2018-08-28 14:25 UTC, janhack requested changes
I now checked the links (most of them to other sections in the documentation) and found that quite a few of them are invalid (see comments).

2018-09-03 14:46 UTC, janhack commented on peer-to-peer-communication/p2p-communication.md
> +The transaction pool provides the Lisk network a robust solution for preserving unconfirmed transactions that have overflowed into the next block. As described in [**blocks**](/documentation/lisk-pro
The links to the `blocks` sections in the Transaction Pool paragraph is not working.

2018-09-03 14:48 UTC, janhack commented on consensus/consensus.md
The link to the p2p section in the Broadhash Consensus section is not working.

2018-09-03 14:49 UTC, janhack requested changes
I still found two broken links.

2018-09-03 15:18 UTC, IkerAlus reviewed
Do we know why the JSON object examples of all the transaction types show this weird red colour for the text explaining each field? is it something expected?

2018-09-03 15:29 UTC, Tschakki commented
@IkerAlus Yes, it is because we are highlighting JSON syntax for these code-snippets.

I aggree it looks ugly.

We have 2 options here:
1. Make the  code snippets proper JSON syntax, will make the red go away
2. Just remove the JSON syntaxhighlighting from code snippet.

Any preferences?

2018-09-03 16:22 UTC, janhack approved these changes

2018-09-04 12:50 UTC, merged