Update amend add content to reference pages in SDK docs - closes #550
LiskArchive/lisk-legacy-docs pull request #564
Opened 2020-04-21 11:32 UTC by chris529

closes #550

2020-04-22 10:20 UTC, Tschakki requested changes
Please have a look at the reference overview again.

I notice you explain briefly, what every software tool is.
As this should be already be explained in other parts of the documentation, it is not necessary to explain it here again. Where adequate, you can instead link to the existing content.

Just focus on what content they can find in the reference pages and try to keep it as short as possible, when describing single pages.

Also, please make a decision if you want to make a list of every existing page in references (as already mentioned I wouldn't favor that, because it is hard to maintain) or rather have a summary with the most important links and explanations about what content to find in this section.

If you want to go for a full list, please find a way to make it clear which pages are child pages of other pages, and also ensure to not only include links to lisk commander and lisk elements, as the reference section has more pages, like the config reference, the api reference and the developer changelog. In a summary, these 3 should of course be mentioned as well,  because they are quite important.

2020-04-22 10:20 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +Lisk Commander is an effective, convenient and user-friendly tool designed for all levels of developers, and further useful information is included within the reference section to assist the user.
I think at this point we should not explain what Lisk Commander is, as we do this already on the SDK overview page, but rather give a quick summary of what content is to find in the Lisk Commander reference.

2020-04-22 14:51 UTC, chris529 commented on modules/ROOT/pages/reference/index.adoc
> +Lisk Commander is an effective, convenient and user-friendly tool designed for all levels of developers, and further useful information is included within the reference section to assist the user.
Agreed.

2020-04-23 08:50 UTC, Tschakki requested changes
Almost good! Just left 2 suggestions :)

2020-04-23 08:50 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +The Lisk xref:{url_commander_overview}[Commander] reference section comprises of the setup, installation and configuration. In addition the following  xref:{url_lisk_commander_commands}[Commands], xr
```suggestion
The xref:{url_commander_overview}[Lisk Commander] reference section comprises of the setup, installation and configuration. In addition the following  xref:{url_lisk_commander_commands}[Commands], xref:{url_lisk_core}[Core commands] and xref:{url_sens_inputs}[Sensitive inputs] are also covered separately, together with useful examples in order to assist the end-user.
```

2020-04-23 08:50 UTC, Tschakki commented on modules/ROOT/pages/reference/index.adoc
> +Firstly the  xref:{url_api_specification}[API specification] references provide an in-depth definition of the specifications, followed by the  xref:{url_config}[Configuration] which contains a detail
```suggestion
Firstly the  xref:{url_api_specification}[API specification] provides an in-depth definition of the API endpoints, followed by the  xref:{url_config}[SDK Configuration reference] which contains a detailed example explaining the default values. This is followed by the xref:{url_changelog}[Developer changelog] which encompasses an extensive description of the updated database and api changes that are relevant for developers when updating their application to the latest version of the Lisk SDK.
```

2020-04-23 09:01 UTC, chris529 commented
Agreed, thanks Mona!

2020-04-24 12:54 UTC, Tschakki approved these changes

2020-04-24 12:56 UTC, merged