Update elements reference - Closes #552
LiskArchive/lisk-legacy-docs pull request #570
Opened 2020-04-23 13:10 UTC by Tschakki

Closes #552

2020-04-24 08:50 UTC, chris529 requested changes
Looks good, minor points, and 1 sentence that didn't seem to be clear to me.. :-)

2020-04-24 08:50 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/transactions.adoc
> +<1> The network identifier of the network, you want to post the transaction to.
```suggestion
<1> The network identifier of the network, where you wish to post the transaction.
```

2020-04-24 08:50 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/transactions.adoc
> +It is also possible to get the minimum fee for this particular trasnaction, to be accepted by the network:
```suggestion
It is also possible to get the minimum fee for this particular transaction, to be accepted by the network:
```

2020-04-24 08:50 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/transactions.adoc
> +Verifies if an account has enough remaining balance in the account.
```suggestion
Verifies if the remaining balance in the account is sufficient.
```

2020-04-24 08:50 UTC, chris529 commented on modules/ROOT/pages/reference/lisk-elements/p2p.adoc
> +- `p2p.send(message: P2PMessagePacket)`: sends information to 16 connected peers chosen by peer selection for send.
"sends information to 16 connected peers chosen by peer selection for send".

This sentence  doesn't seem to be clear to me..?  Perhaps we could say " sends information to 16 connected peers chosen by  the peer selection process, which is required for the sending procedure". ?

2020-04-24 13:11 UTC, Tschakki commented on modules/ROOT/pages/reference/lisk-elements/p2p.adoc
> +- `p2p.send(message: P2PMessagePacket)`: sends information to 16 connected peers chosen by peer selection for send.
Its coming from here: https://github.com/LiskHQ/lisk-sdk/tree/development/elements/lisk-p2p
Maybe you can ask @ishantiw about it :)
docs for the p2p package are very basic at the moment.

2020-04-27 12:04 UTC, chris529 requested changes
Perfect...just one minor typo :-)

2020-04-27 12:04 UTC, chris529 commented on modules/ROOT/pages/reference/changelog.adoc
> +:description: This section contains the devloper changelog information from the transaction types and updated genesis block for the devnet, to the database changes including the peers, delegates and
```suggestion
:description: This section contains the developer changelog information from the transaction types and updated genesis block for the devnet, to the database changes including the peers, delegates and nodes.
```

2020-04-27 14:29 UTC, chris529 approved these changes
Perfect.. 👍

2020-04-27 14:56 UTC, merged