Update issues in binary, commander, docker, and source pages in Core docs - closes#569
LiskArchive/lisk-legacy-docs pull request #571
Opened 2020-04-23 14:25 UTC by chris529

closes #569

2020-04-24 08:36 UTC, Tschakki requested changes

2020-04-24 08:36 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +
```suggestion
----
--
```

2020-04-24 08:36 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +This will configure the environment, download and install Lisk Core to the Betanet.
```suggestion
This will configure the environment, download and install Lisk Core.
```

No need to mention the network here. Also it sounds little weird like this.

2020-04-24 08:36 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
>  --
Remove this line

2020-04-24 08:36 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
>  ====
```suggestion
Please note that Docker for Windows includes Docker Compose.
--
====
```

2020-04-24 13:07 UTC, Tschakki requested changes
please see my comment

2020-04-28 12:09 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
>  --
OK, it is done :-)

2020-04-28 13:59 UTC, Tschakki approved these changes
LGTM

2020-04-29 13:35 UTC, merged