Update add links in setup pages, remove mainnet, testnet in commander & source pages, fix typo in Core docs - closes #572
LiskArchive/lisk-legacy-docs pull request #573
Opened 2020-04-24 14:55 UTC by chris529

closes #572

2020-04-27 08:09 UTC, Tschakki requested changes
Following points of the issue are not fixed, yet:
- Binary commands: Source Administration page doesn’t exist update with new link
- Source commands: Mainnet/Testnet - should be Betanet

Please make sure to fix them as well.

2020-04-27 08:09 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +
```suggestion
Betanet::
+
```

Please do the same for all other tabs, otherwise it will break the styling

2020-04-28 14:11 UTC, Tschakki requested changes
Looks good! Just a few minor issues :)

2020-04-28 14:11 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +:url_source: management/source.adoc
This link was correct, please restore.

2020-04-28 14:11 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +To connect to another network, specify the `network` when starting the Lisk Core, as described in xref:{url_source}[Source commands].
```suggestion
To connect to another network, specify the `network` when starting the Lisk Core, as described in xref:{url_source}[Config reference].
```

2020-04-28 14:11 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +4. xref:{url_source}[*Source commands*] -  This offers the user the possibility to develop on the Lisk Core codebase, and has an extensive test suite which can provide the advanced user and developer
Either add `commands` to the other links as well, or remove it again for consistency.

2020-04-29 12:19 UTC, chris529 commented on modules/ROOT/pages/management/index.adoc
> +4. xref:{url_source}[*Source commands*] -  This offers the user the possibility to develop on the Lisk Core codebase, and has an extensive test suite which can provide the advanced user and developer
Done

2020-04-29 13:21 UTC, chris529 commented on modules/ROOT/pages/management/configuration.adoc
> +:url_source: management/source.adoc
OK, now done..

2020-04-30 12:39 UTC, Tschakki requested changes
Just one issue left :)

2020-04-30 12:39 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +To connect to another network, specify the `network` when starting the Lisk Core, as described in xref:{url_source}[Config reference].
This link is not going to the reference, like the label indicates. Please fix either the link or the label so it fits to the content and context.

2020-05-06 16:40 UTC, chris529 commented on modules/ROOT/pages/management/configuration.adoc
> +To connect to another network, specify the `network` when starting the Lisk Core, as described in xref:{url_source}[Config reference].
OK, it should work now..

2020-05-11 08:46 UTC, Tschakki requested changes
Please fix the remaining conflicts.

2020-05-12 13:35 UTC, Tschakki approved these changes
Thanks!

2020-05-12 13:38 UTC, merged