Align protocol docs with style guide
LiskArchive/lisk-legacy-docs pull request #575
Opened 2020-04-27 12:03 UTC by Tschakki

Fix image and links, add meta description and no-next and no-previous attributes

2020-04-29 16:28 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +:description: The account section of the Lisk protocol covers user accounts which are forming the underlying database.
```suggestion
:description: This section explains the different account properties and how these relate to different transaction types.
```

2020-04-29 16:31 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +:description: The account section of the Lisk protocol covers user accounts which are forming the underlying database.
- "user account" -> I tried to keep it general here, as it could be an account by a delegate or group of people (multisig).
- "Lisk protocol" seems redundant and also "the account section" seems redundant as description of the account section.
- "forming the unterlying database" is a bit unclear. Also blocks and transactions are stored in the database.

2020-04-29 16:41 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +The section <<types,Transaction types>> describes the different transaction types with respect to the `asset` property of each of them.
I am not an expert on style (rather consult Chris), but I find it odd to reference to a section title without quotation marks. In particular, as there is suddenly upper case in the middle of the sentence.

2020-04-29 16:42 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +:description: The transactions section of the Lisk protocol outlines the default transactions present in the Lisk protocol.
```suggestion
:description: This section describes the default transactions present in the Lisk protocol.
```

2020-04-29 16:42 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +:description: The transactions section of the Lisk protocol outlines the default transactions present in the Lisk protocol.
Two times "Lisk protocol" seems redundant and also repeating the section title seems redundant.

2020-04-29 16:50 UTC, janhack commented on modules/ROOT/pages/blocks.adoc
> +Please see xref:{url_consensus_delegate_fork_choice_rule}[Consensus votes on blocks and fork choice rule], Consensus votes on blocks and fork choice rule>> for more details.
I think `, Consensus votes on blocks and fork choice rule>> ` needs to be removed.
Otherwise, same comment as in transaction file: This style of referencing seems odd.

2020-04-29 16:52 UTC, janhack commented on modules/ROOT/pages/blocks.adoc
> +:description: The blocks section of the Lisk protocol describes the actual data stored in a block and how new blocks are created.
```suggestion
:description: This section describes the structure and properties of blocks in the Lisk protocol.
```

2020-04-29 16:55 UTC, janhack commented on modules/ROOT/pages/consensus-algorithm.adoc
> +:description: The consensus algorithm section of the Lisk protocol illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
```suggestion
:description: This section illustrates how the delegates eligible to create blocks are selected and how they reach agreement on new blocks.
```

2020-04-29 16:59 UTC, janhack commented on modules/ROOT/pages/network.adoc
> +:description: The network section of the Lisk protocol describes the Lisk P2P network used to exchange information such as blocks or transactions between nodes.
```suggestion
:description: This section describes the Lisk P2P network used to exchange information such as blocks or transactions between nodes.
```

2020-04-29 17:01 UTC, janhack commented on modules/ROOT/pages/mainnet.adoc
> +:description: The Mainnet section of the Lisk protocol lists the properties specific to the Lisk Mainnet.
```suggestion
:description: This section lists the properties specific to the Lisk Mainnet.
```

2020-04-29 17:02 UTC, janhack commented on modules/ROOT/pages/mainnet.adoc
> +:description: The Mainnet section of the Lisk protocol lists the properties specific to the Lisk Mainnet.
Do we write "Lisk mainnet" or "Lisk mainnet"? Similarly, "Lisk Testnet" or "Lisk testnet"?

2020-04-29 17:04 UTC, janhack commented on modules/ROOT/pages/appendix.adoc
> +:description: The appendix section of the Lisk protocol contains additional information related to the Lisk protocol.
```suggestion
:description: The appendix contains additional information related to the Lisk protocol.
```

2020-04-29 17:05 UTC, janhack approved these changes

2020-04-29 17:07 UTC, janhack requested changes
Thanks for all the fixes. I left a few small comments and suggestions.

2020-04-30 11:01 UTC, Tschakki commented on modules/ROOT/pages/transactions.adoc
> +The section <<types,Transaction types>> describes the different transaction types with respect to the `asset` property of each of them.
It is displayed as link, so bold and blue, imho that makes separation pretty clear.

2020-04-30 11:04 UTC, Tschakki commented on modules/ROOT/pages/mainnet.adoc
> +:description: The Mainnet section of the Lisk protocol lists the properties specific to the Lisk Mainnet.
We were using Lisk Mainnet, and Lisk Testnet, Devnet, Betanet as it are the specific names for our different networks :)

2020-04-30 11:06 UTC, Tschakki commented on modules/ROOT/pages/blocks.adoc
> +Please see xref:{url_consensus_delegate_fork_choice_rule}[Consensus votes on blocks and fork choice rule], Consensus votes on blocks and fork choice rule>> for more details.
```suggestion
Please see xref:{url_consensus_delegate_fork_choice_rule}[Consensus votes on blocks and fork choice rule] for more details.
```

2020-04-30 11:47 UTC, janhack approved these changes
Looks good.

2020-04-30 11:55 UTC, merged