Update issues in binary commander docker and source pages in core docs 2.1.5 - closes #595
LiskArchive/lisk-legacy-docs pull request #596
Opened 2020-05-12 08:54 UTC by chris529

closes #595

2020-05-15 12:33 UTC, Tschakki requested changes
As discussed, please keep Testnet and Mainnet in this version (and remove betanet and alphanet if present).

2020-05-15 14:25 UTC, chris529 commented
Yes, you are right Mona it is now done.

2020-05-18 08:39 UTC, Tschakki requested changes

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +====
Remove these lines

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +If all of the above steps have been successfully completed, then the next step is to move on to the configuration documentation. If you wish to enable forging or SSL, please see the xref:{url_config}
Please use a new line for each sentence

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/binary.adoc
> +* In this case it is recommended to set up a xref:{url_config_logrotation}[log rotation].
```suggestion
* It is recommended to set up a xref:{url_config_logrotation}[log rotation].
```

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Please choose the name of your Lisk Core instance.
Imho, we shouldn't use 'please' too often in the docs. Also it is changing the sence of the sentence here a little imho. The tip just says it is possible to change the name, not that the user should do it.

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Betanet::
This tabs are not correct, please just restore the original content...

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +In addition it is also recommended to set up a xref:{url_config_logrotation}[log rotation].
Is this `in addition` really needed here?

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +:url_lisk_explorer_betanet: https://betanet-explorer.lisk.io/
Again... Mainnet and Testnet should stay here

2020-05-18 08:39 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +// [tabs]
Tabs format is broken here

2020-05-18 08:54 UTC, chris529 commented on modules/ROOT/pages/setup/binary.adoc
> +====
OK, now done.. :-)

2020-05-18 09:14 UTC, chris529 commented on modules/ROOT/pages/setup/commander.adoc
> +Please choose the name of your Lisk Core instance.
Yes, I see your point Mona, OK it is now resolved.. :-)

2020-05-18 12:55 UTC, chris529 commented on modules/ROOT/pages/setup/commander.adoc
> +Betanet::
OK, this should now work..

2020-05-18 13:00 UTC, chris529 commented on modules/ROOT/pages/setup/commander.adoc
> +In addition it is also recommended to set up a xref:{url_config_logrotation}[log rotation].
Well, we could live without it, however I think it fits well within the flow of this paragraph. Nevertheless, we can always change it if you wish Mona.. For example,  we could have something like this..."At this stage it is recommended to set up a log rotation" ?   :-)

2020-05-18 13:43 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +:url_lisk_explorer_betanet: https://betanet-explorer.lisk.io/
OK, they should be fixed now :-)

2020-05-19 12:26 UTC, Tschakki requested changes

2020-05-19 12:26 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +====
The tabs format is broken again... please just restore the original content, no need to change anything here.

2020-05-19 12:26 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +In addition it is also recommended to set up a xref:{url_config_logrotation}[log rotation].
Ok thanks for explanation. I think its cool like that 👍

2020-05-19 12:26 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +====
Tabs format broken, please fix.

2020-05-19 12:26 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +
Why is this content added here?

2020-05-19 12:26 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +To fully verify that your node is synchronised with the network, go to the {url_lisk_explorer_betanet}[Lisk Explorer(Betanet)] and compare the network height in the explorer with the height of your n
This should not be changed...

2020-05-19 13:12 UTC, chris529 commented on modules/ROOT/pages/setup/commander.adoc
> +====
OK, I think this is OK now, could you please check it Mona, thx . :-)

2020-05-19 16:00 UTC, Tschakki approved these changes
Looking good now, thanks!

2020-05-19 16:02 UTC, merged