Update issues in management binary commander docker and source pages in core docs 2.1.5 - closes #599
LiskArchive/lisk-legacy-docs pull request #600
Opened 2020-05-14 07:25 UTC by chris529

closes #599

2020-05-15 12:31 UTC, Tschakki requested changes
please fix the conflicts first.

2020-05-18 08:56 UTC, Tschakki requested changes

2020-05-18 08:56 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +Check the status of the Lisk Core Node.
```suggestion
Check the status of the Lisk Core node.
```

2020-05-18 08:56 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> -:url_config_cl: reference/config.adoc#clo
Why remove the link attribute? It is still used in the document.

2020-05-19 12:45 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> -:url_config_cl: reference/config.adoc#clo
OK, I have replaced it.. :-)

2020-05-22 08:01 UTC, Tschakki requested changes

2020-05-22 08:01 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> -:url_config_cl: reference/config.adoc#clo
I think you replaced it in the wrong file (mannagement/commander.adoc), please fix.

2020-05-26 08:56 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> -:url_config_cl: reference/config.adoc#clo
OK, I have put the link attribute back in management/docker.adoc

2020-05-26 10:16 UTC, Tschakki requested changes

2020-05-26 10:16 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> -:url_config: management/configuration.adoc
Why did you remove this link? It is used in this document. Please restore.

2020-05-26 10:22 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> -:url_config: management/configuration.adoc
Ah yes, sorry that was an error...It has now been restored :-)

2020-05-26 10:46 UTC, Tschakki approved these changes
LGTM

2020-05-26 10:48 UTC, merged