Remove all links to migration page and update nav page in Core docs 2.1.5 - closes #603
LiskArchive/lisk-legacy-docs pull request #604
Opened 2020-05-14 12:47 UTC by chris529

closes #603

2020-05-15 12:34 UTC, Tschakki requested changes
Please resolve the conflicts first.

2020-05-22 08:14 UTC, Tschakki requested changes
Please focus in the PR on the issue you are solving. There are many unrelated changes in this PR.

2020-05-25 15:39 UTC, Tschakki requested changes

2020-05-25 15:39 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> -:url_config_cl: reference/config.adoc#clo
Why are you removing this link?

2020-05-26 11:20 UTC, Tschakki requested changes

2020-05-26 11:20 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> -:url_config: management/configuration.adoc
Why are you removing this link?

2020-05-26 11:21 UTC, Tschakki commented
Also, please fix the conflicts

2020-05-26 13:24 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> -:url_config: management/configuration.adoc
OK, it is now restored.

2020-05-26 14:07 UTC, Tschakki approved these changes
Thank you!

2020-05-26 14:08 UTC, merged