Update dist names in core docs 3.0.0 - closes #613
LiskArchive/lisk-legacy-docs pull request #618
Opened 2020-06-02 16:14 UTC by chris529

Parent issue #589

2020-06-05 08:35 UTC, Tschakki requested changes
Please always check, if the docs are talking about Lisk Commander, or the Lisk Core Commander distribution, which is only a part of it.

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +TIP: It is recommended to use xref:{url_admin_binary_snapshot}[Lisk Core Application] for creating your own snapshots, as a script is provided to conveniently create snapshots.
Lisk Core should not be changed

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +Depending on their preferences, node operators may wish to use <<javascript,Lisk Elements>>, <<commandline,Lisk Commander application>> or a graphical interface such as <<lisk_desktop,Lisk Desktop>>.
No change here

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +xref:{url_commander}[Lisk Commander application] is the CLI-tool that allows interaction with the network in a convenient manner through the command line.
No change here

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/application.adoc
> +:description: The Lisk Core application describes all relevant commands to manage Lisk Core through the command-line.
```suggestion
:description: The Lisk Core application commands page describes all relevant commands to manage Lisk Core through the command-line.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/application.adoc
> +This section covers how to work with an application installation of Lisk Core.
This sentence sounds weird

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/application.adoc
> +If Lisk Core has been installed with the application package and you wish to use additional tools such as `pm2` and `psql`, the corresponding PATH variables need to be set by typing the following com
```suggestion
If Lisk Core application has been installed and you wish to use additional tools such as `pm2` and `psql`, the corresponding PATH variables need to be set by typing the following command:
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/application.adoc
> +PM2 is bundled with the Lisk Core application distribution and will be available after <<update_path, Updating the PATH environment>>.
```suggestion
PM2 is bundled with the Lisk Core application and will be available after <<update_path, Updating the PATH environment>>.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +:description: The Lisk Core Commander application commands covers all relevant commands to manage Lisk Core through the command-line.
```suggestion
:description: Covers all relevant commands to manage Lisk Core through the command-line with Lisk Commander.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +This section covers how to perform the installation of Lisk Core using the Lisk Commander application.
This page is about management not installation or not?

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +NOTE: For more information, please see the xref:{url_setup_commander}[Setup page of Lisk Core with Lisk Commander application].
```suggestion
NOTE: For more information, please see the xref:{url_setup_commander}[Setup page of Lisk Core via Lisk Commander].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +NOTE: For more information, please see the xref:{url_upgrade_commander}[Upgrade page of Lisk Core with Lisk Commander application].
```suggestion
NOTE: For more information, please see the xref:{url_upgrade_commander}[Update page of Lisk Core via Lisk Commander].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +For *Source code* distributions, the config file needs to be created seperately and needs to be passed as described below:
```suggestion
For the *Source code*, the config file needs to be created separately and needs to be passed as described below:
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +Lisk Commander application provides a custom `config.json` which is stored in the root folder of your Lisk Core instance by default.
```suggestion
Lisk Commander provides a custom `config.json` which is stored in the root folder of your Lisk Core instance by default.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> +:description: The Lisk Core Docker image commands covers all relevant commands required to manage Lisk Core with Docker.
```suggestion
:description: Covers all relevant commands required to manage Lisk Core with a Docker image.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> +To perform this, open the `.env` file, that was created during the xref:{url_setup_docker_install}[docker image installation], and adjust the values to your requirements.
```suggestion
To perform this, open the `.env` file, that was created during the xref:{url_setup_docker_install}[Docker image installation], and adjust the values to your requirements.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +* xref:{url_sdk_commander_commands}[Lisk Commander application] via `encrypt passphrase` command.
```suggestion
* xref:{url_sdk_commander_commands}[Lisk Commander] via `encrypt passphrase` command.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +The first alternative with the Lisk Commander application is described in detail below.
```suggestion
The first alternative with Lisk Commander is described in detail below.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +Please ensure the Lisk Commander application is installed in a secure environment.
```suggestion
Please ensure, that Lisk Commander is installed in a secure environment.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +For example, for Application install, execute the following command: `bash lisk.sh reload`
```suggestion
For example, for the Lisk Core application, execute the following command: `bash lisk.sh reload`
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +2. xref:{url_commander}[*Commander application commands*] -   The Lisk Commander application offers an alternative method to install and further manage Lisk Core.
```suggestion
2. xref:{url_commander}[*Commander application commands*] -   The Lisk Commander offers an alternative method to install and further manage Lisk Core.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +3. xref:{url_docker}[*Docker image commands*] -  Docker image provides the options to run Lisk nodes on other platforms.
```suggestion
3. xref:{url_docker}[*Docker image commands*] -  Docker provides the options to run Lisk nodes on other platforms.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/management/source.adoc
> +For creating xref:{url_core_snapshots}[snapshots] in the most convenient manner, it is recommended to use Lisk Core from the xref:{url_admin_binary}[application distribution].
```suggestion
For creating xref:{url_core_snapshots}[snapshots] in the most convenient manner, it is recommended to use the xref:{url_admin_binary}[Lisk Core application].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
>  :page-next: /lisk-core/3.0.0/management/binary.html
```suggestion
:page-next: /lisk-core/3.0.0/management/application.html
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
> +This document details how to setup a Lisk Core application distribution on a system.
```suggestion
This document details how to setup a Lisk Core application on a system.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
> +If you are looking to upgrade your current Lisk Core installation, please see the xref:{url_upgrade_binary}[Upgrade Application] section.
```suggestion
If you are looking to upgrade your current Lisk Core installation, please see the xref:{url_upgrade_binary}[Update Application] section.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Setup and manage your Lisk node conveniently with the Lisk Commander application.
```suggestion
Setup and manage your Lisk Core node conveniently with Lisk Commander.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +=== Install Lisk Commander application
```suggestion
=== Install Lisk Commander
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Please access the Lisk Commander application docs and follow the xref:{url_sdk_commander_setup}[installation instructions].
```suggestion
Please access the Lisk Commander docs and follow the xref:{url_sdk_commander_setup}[installation instructions].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Once the Lisk Commander appliction is set up on your system, it is possible to use the commands below to set up and manage your Lisk Core node.
```suggestion
Once Lisk Commander is set up on your system, it is possible to use the commands below to set up and manage your Lisk Core node.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Please refer to the {url_binary_download}[application release^] for the file naming convention.
```suggestion
Please refer to the {url_binary_download}[Lisk Core application releases^] for the file naming convention.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +Please refer to {url_docker_install_mac}[docker image installation for mac^].
```suggestion
Please refer to {url_docker_install_mac}[docker image installation for mac^].
```
```suggestion
Please refer to {url_docker_install_mac}[Docker installation for Mac^].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +Please refer to {url_docker_install_windows}[docker image installation for windows^].
```suggestion
Please refer to {url_docker_install_windows}[Docker installation for Windows^].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +To proceed to the next step, please see the xref:{url_admin_docker}[Docker image] to learn how to manage your node.
```suggestion
To proceed to the next step, please see the xref:{url_admin_docker}[Docker image management] to learn how to manage your node.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +This section comprises of the setup prerequisites necessary for the Application, Commander application, Docker image and Source code installation distributions.
```suggestion
This section comprises of the setup prerequisites necessary for the Application, Commander application, Docker image and Source code installation distributions of Lisk Core.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +Use xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core. This version offers the possibility to configure various options which are described in the lin
```suggestion
Use xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core. 
```
Would remove that, not sure what it refers to.

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +xref:{url_docker}[Docker image] adds support for additional platforms upon which to run a Lisk node.
```suggestion
The xref:{url_docker}[Docker image] adds support for additional platforms upon which to run a Lisk node.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +An installation performed from the xref:{url_source}[source code] enables a developer to work on the latest codebase for Lisk Core, which may not have been tagged for a release yet.
```suggestion
An installation performed from the xref:{url_source}[source code] enables a developer to work on the latest codebase of Lisk Core, which may not have been tagged for a release yet.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +TIP: It is recommended to use Postgres with Docker image for a straight forward and fast setup of Postgres.
```suggestion
TIP: It is recommended to use Postgres with Docker for a straight forward and fast setup of Postgres.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +Postgres with Docker image::
```suggestion
Postgres with Docker::
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +To manage the Docker image container, use the following commands displayed below:
```suggestion
To manage the Docker container, use the following commands displayed below:
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +If you wish to upgrade your current Lisk Core installation, please see xref:{url_upgrade_source}[Upgrade from Source code].
```suggestion
If you wish to update your current Lisk Core installation, please see xref:{url_upgrade_source}[Update Source code].
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
>  :page-previous: /lisk-core/3.0.0/management/binary.html
```suggestion
:page-previous: /lisk-core/3.0.0/management/application.html
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
> +To upgrade Lisk Core from the Application please follow the instructions below.
```suggestion
To update the Lisk Core application please follow the instructions below.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
> +== Update with Lisk Commander application
This whole section should be removed here.

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
> +:description: The Lisk Core Commander application update page describes how to upgrade Lisk Core to the latest version via Lisk Commander.
```suggestion
:description: Describes how to upgrade Lisk Core to the latest version via Lisk Commander.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
> +Please refer to the {url_binary_release}[application release^] for the file naming convention.
```suggestion
Please refer to the {url_binary_release}[Lisk Core application releases^] for the file naming convention.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/docker.adoc
> +:description: The Lisk Core Docker image update page describes how to upgrade Lisk Core to the latest version with Docker.
```suggestion
:description: Describes how to upgrade Lisk Core to the latest version with Docker.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +This section describes how to perform the necessary updates for the  Application, Commander application, Docker image and Source code installations.
```suggestion
This section describes how to perform the necessary updates for the Lisk Core application, Lisk Core Commander application, Docker image and Source code installations.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +The xref:{url_update_docker}[Docker image] process explains how to upgrade the minor versions and update the major versions.
```suggestion
The xref:{url_update_docker}[Docker image] update explains how to upgrade to minor versions and major versions.
```

2020-06-05 08:35 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +The xref:{url_update_source}[Source code] update details how to upgrade Lisk Core and also pull the latest tagged releases.
```suggestion
The xref:{url_update_source}[Source code] update details how to update Lisk Core and also pull the latest tagged releases.
```

2020-06-05 09:03 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +TIP: It is recommended to use xref:{url_admin_binary_snapshot}[Lisk Core Application] for creating your own snapshots, as a script is provided to conveniently create snapshots.
OK will fix capitalisation (application)

2020-06-05 09:04 UTC, chris529 commented on modules/ROOT/pages/management/application.adoc
> +This section covers how to work with an application installation of Lisk Core.
This section describes how to manage the Lisk Core application

2020-06-08 08:00 UTC, Tschakki requested changes
A lot of my comments are not addressed, please check again!

2020-06-08 12:21 UTC, chris529 commented on modules/ROOT/pages/management/commander.adoc
> +This section covers how to perform the installation of Lisk Core using the Lisk Commander application.
Yes, you are correct Mona, I have updated it accordingly :-)

2020-06-08 15:35 UTC, Tschakki requested changes
Please see my comments, also, you missed a lot of my previous suggestions, please revisit :)

2020-06-08 15:35 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +*Application* and *Commander application* distributions both provide a config.json, which can be customized as desired.
```suggestion
The *Application* and *Commander application* both provide a `config.json`, which can be customized as desired.
```

2020-06-08 15:35 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +The application script provides a custom `config.json` which is stored in the root folder of your Lisk Core installation by default.
```suggestion
The application provides a custom `config.json` which is stored in the root folder of your Lisk Core installation by default.
```

2020-06-08 15:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +Setup and manage your Lisk node conveniently with the Lisk Commander application.
Please see my suggestion above

2020-06-08 15:35 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +=== Install Lisk Commander application
Please see my suggestion above

2020-06-09 09:18 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +Use xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core. This version offers the possibility to configure various options which are described in the lin
agreed :-)

2020-06-09 09:28 UTC, chris529 commented on modules/ROOT/pages/update/application.adoc
> +== Update with Lisk Commander application
Hi Mona, Am not sure exactly which part you are referring to here..?

2020-06-10 15:31 UTC, Tschakki requested changes
Looking pretty good already! Just a few minor suggestions :)

2020-06-10 15:31 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +To successfully perform the command shown below, install Docker as described in the Setup page of xref:{url_docker_setup][Lisk Core Docker image distribution].
```suggestion
To successfully perform the command shown below, install Docker as described in the Setup page of the xref:{url_docker_setup][Lisk Core Docker image].
```

2020-06-10 15:31 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
> +== Update with Lisk Commander application
The whole Section `Update with Lisk Commander` should be covered already on the "Update Commander application" page. On this page it should be only explained how to update the Lisk Core application.

2020-06-10 15:31 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +The Lisk xref:{url_update_commander}[Commander application] update process covers the available options with their descriptions.
```suggestion
The Lisk Core xref:{url_update_commander}[Commander application] update process covers the available options with their descriptions.
```

2020-06-10 15:31 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +This section comprises of the setup prerequisites necessary for the Application, Commander application, Docker image and Source code installation distributions of Lisk Core.
```suggestion
This section comprises of the setup prerequisites necessary for the Application, Commander application, Docker image and Source code installations of Lisk Core.
```

2020-06-10 15:31 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +The application provides a custom `config.json` which is stored in the root folder of your Lisk Core installation by default.
```suggestion
The Lisk Core application provides a custom `config.json` which is stored in the root folder of your Lisk Core installation by default.
```

2020-06-11 13:07 UTC, chris529 commented on modules/ROOT/pages/update/application.adoc
> +== Update with Lisk Commander application
OK, I think this should be OK now, please have a look Mona, thanks :-)

2020-06-11 15:22 UTC, Tschakki requested changes
Just 2 comments left :)

2020-06-11 15:22 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
>  --
Remove this line

2020-06-11 15:22 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
>  Betanet::
```suggestion
=== Betanet
```

2020-06-11 15:31 UTC, chris529 commented on modules/ROOT/pages/update/commander.adoc
>  --
Ah yes...good point :-)

2020-06-11 16:06 UTC, Tschakki approved these changes
Thank you!

2020-06-12 07:59 UTC, merged