Update dist names in core docs 2.1.6 - closes #619
LiskArchive/lisk-legacy-docs pull request #620
Opened 2020-06-04 17:16 UTC by chris529

Parent issue #589

2020-06-12 14:49 UTC, Tschakki requested changes
Looking good, just a few minor comments.

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/getting-started.adoc
> +Use xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core.
```suggestion
Use the xref:{url_lisk_commander}[Lisk Commander application] to conveniently install and manage Lisk Core.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Use xref:{url_setup_commander}[Lisk Commander application] to conveniently install and manage Lisk Core.
```suggestion
Use the xref:{url_setup_commander}[Lisk Commander application] to conveniently install and manage Lisk Core.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +xref:{url_setup_docker}[Docker image] adds support for running a Lisk node with other platforms.
```suggestion
The xref:{url_setup_docker}[Docker image] adds support for running a Lisk node with other platforms.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +Depending on their preferences, node operators may wish to use <<javascript,Lisk Elements>>, <<commandline,Lisk Commander application>> or a graphical interface such as <<lisk_desktop,Lisk Desktop>>.
```suggestion
Depending on their preferences, node operators may wish to use <<javascript,Lisk Elements>>, <<commandline,Lisk Commander>> or a graphical interface such as <<lisk_desktop,Lisk Desktop>>.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/interact-with-network.adoc
> +xref:{url_commander}[Lisk Commander application] is the CLI-tool that allows interaction with the network in a convenient manner through the command line.
```suggestion
xref:{url_commander}[Lisk Commander] is the CLI-tool that allows interaction with the network in a convenient manner through the command line.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +This section covers how to work with an application installation of Lisk Core.
```suggestion
This section covers how to work with the commander application installation of Lisk Core.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +NOTE: For more information, please see the xref:{url_setup_commander}[Setup page of Lisk Core via Lisk Commander application].
```suggestion
NOTE: For more information, please see the xref:{url_setup_commander}[Setup page of Lisk Core via Lisk Commander].
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +TIP: For all available options, see the Lisk Commander application xref:{url_sdk_commander_liskcore}[command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[General command
```suggestion
TIP: For all available options, see the Lisk Commander xref:{url_sdk_commander_liskcore}[command reference for Lisk Core] as well as the xref:{url_sdk_commander_commands}[General command reference].
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +It is also required to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander application to check the integrity of the application.
```suggestion
It is also required to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander to check the integrity of the application.
```

2020-06-12 14:49 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
> +:description: The Lisk Core aApplication update page describes how to upgrade Lisk Core to the latest version.
```suggestion
:description: The Lisk Core application update page describes how to upgrade Lisk Core to the latest version.
```

2020-06-17 10:11 UTC, chris529 commented
Thanks Mona!

2020-06-17 11:34 UTC, Tschakki approved these changes
LGTM

2020-06-17 11:36 UTC, merged