Move node management related guides from core docs closes #561
LiskArchive/lisk-legacy-docs pull request #629
Opened 2020-06-17 09:39 UTC by chris529

2020-06-18 10:04 UTC, Tschakki requested changes
Looking pretty good already! 

Please see my comments and also remember to git remove the empty index pages in the app development and node management directories.

2020-06-18 10:04 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:guides/node-management/logging.adoc[Logging]
```suggestion
** Application development
*** xref:guides/app-development/configuration.adoc[Configure a blockchain application]
*** xref:guides/app-development/customize.adoc[Create a custom transaction]
*** xref:guides/app-development/test.adoc[Test a transaction]
*** xref:guides/app-development/interact.adoc[Interact with the API]
*** xref:guides/app-development/broadcast.adoc[Broadcast a transaction]
*** xref:guides/app-development/frontend.adoc[Connect a frontend]
*** xref:guides/app-development/launch.adoc[Launch a blockchain application]
** Node management
*** xref:guides/node-management/forging.adoc[Enable forging]
*** xref:guides/node-management/api-access.adoc[API access]
*** xref:guides/node-management/enable-ssl.adoc[Enable SSL]
*** xref:guides/node-management/logging.adoc[Logging]
```

2020-06-18 10:04 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> += Management guides
```suggestion
= Guides
```

2020-06-18 10:04 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +:description: This section provides an overview of the application development and node management guides.
```suggestion
:description: This section provides an overview of the application development and node management guides for the Lisk SDK.
```

2020-06-18 10:04 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +
Although we could list here all the development related guies, I would prefer to focus here only on the most important ones. So imho the section from the old guides index can be used here again, no change needed.

2020-06-18 10:04 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/logging.adoc
> +:url_monitoring_logs: {v_core}@lisk-core::pages/monitoring.adoc#log_monitoring
```suggestion
:url_monitoring_logs: {v_core}@lisk-core::monitoring.adoc#log_monitoring
```

2020-06-18 10:04 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/logging.adoc
> +:toc:
```suggestion
:toc:
:v_core: master
```

2020-06-18 13:30 UTC, chris529 commented on modules/ROOT/pages/guides/index.adoc
> +
OK, agreed and now done :-)

2020-06-19 10:22 UTC, Tschakki requested changes
Looking good, but on the `guides/index.adoc` page, there was a little misunderstanding, I think its good to have an additional section for the node management related guides, like you had it before. 

I would imagine to have 2 sections in the guides index, one called `App development` and one called `Node management`, each followed by a short description what this section is.

Then this can be followed by the overview of the main guides for the app development, like it is now.
For the node management, you can add back the overview of the node management guides that you created before.

The `Hello world app` should be a subsection of the `App development` section.

2020-06-19 14:11 UTC, Tschakki requested changes
Please make sure, to catch all links to the guides, that need to be updated.

On the following pages, I spotted broken links on staging:
https://liskhq.github.io/lisk-docs/lisk-sdk/setup.html
https://liskhq.github.io/lisk-docs/lisk-sdk/index.html
https://liskhq.github.io/lisk-docs/lisk-sdk/tutorials/hello-world.html
https://liskhq.github.io/lisk-docs/lisk-sdk/tutorials/transport1.html
https://liskhq.github.io/lisk-docs/lisk-sdk/reference/config.html
https://liskhq.github.io/lisk-docs/lisk-sdk/reference/lisk-commander/lisk-core.html
https://liskhq.github.io/lisk-docs/lisk-sdk/reference/lisk-framework/index.html

2020-06-19 15:20 UTC, chris529 commented
Hi Mona, OK, they should all work now.. :-)

2020-06-22 12:39 UTC, Tschakki requested changes

2020-06-22 12:39 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +The guides are listed in chronological order, walking the user through the basic steps of developing a blockchain application with the Lisk SDK.
```suggestion
The guides in the application development section are aimed towards developers, who want to built their own blockchain application with the Lisk SDK.

The guides are listed in chronological order, walking the user through the basic steps of developing a blockchain application by the example of the <<hello_world_app, Hello World app>>.

=== Guides overview (application development)
```

2020-06-22 12:39 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +The node management guides are designed to assist the user by covering all the relevant aspects, right from providing recommendations to monitoring and debugging a node.
```suggestion
The node management guides are aimed towards admins and delegates, who operate a node that runs with the Lisk SDK.
Each of these guides covers a specific topic of node management, gives examples, and explains the available options.
```

2020-06-22 12:39 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +. The xref:{url_api_access}[API access guide] covers the options as well as how to control the access to a node, including the configurable flags.
```suggestion
. The xref:{url_api_access}[API access guide] explains, how to manage the API access to a node.
```

2020-06-22 12:46 UTC, chris529 commented
Good points Mona.. 👍

2020-06-22 13:38 UTC, Tschakki approved these changes
Thank you!

2020-06-22 13:46 UTC, merged