Update config pages - Closes #26
LiskArchive/lisk-legacy-docs pull request #63
Opened 2018-09-04 16:06 UTC by Tschakki

Port Updates from Readme to docs:
- Command lines operations
- new config management

Remove `minVersion` and `version` from configuration description.

Closes #26

2018-09-05 12:09 UTC, 4miners requested changes

2018-09-05 12:09 UTC, 4miners commented on user-guide/administration/source/admin-source.md
> +There are plenty of options available that you can use to override configuration on runtime while starting the lisk.
`while starting the Lisk Core`.

2018-09-05 12:09 UTC, 4miners commented on user-guide/configuration/configuration.md
> +- Configurations will be loaded in following order, lowest in the list have highest priority:
`lowest in the list have highest priority` - this can be misleading, maybe something like `each one will override the previous one`

2018-09-05 12:09 UTC, 4miners commented on user-guide/configuration/configuration.md
> +   4. Command line configurations, specified as command `flags` or `env` variables
Command line configurations, specified as command-line flags or `ENV` variables

2018-09-05 12:09 UTC, 4miners commented on user-guide/configuration/configuration.md
> +- For development purposes use `devnet` as network option, others network are specific to public lisk networks.
`as a network`, `other networks`, `Lisk`

2018-09-05 15:46 UTC, 4miners approved these changes

2018-09-11 15:13 UTC, ManuGowda approved these changes

2018-09-11 15:22 UTC, merged