Add links to protocol docs in SDK docs - closes #598
LiskArchive/lisk-legacy-docs pull request #631
Opened 2020-06-19 12:23 UTC by chris529

2020-06-24 08:25 UTC, Tschakki requested changes
Please look for more places, where the Lisk protocol docs can be referred. And try to refer to the different pages of the protocol, where it fits int he context.

2020-06-24 08:25 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/customize.adoc
> +TIP: For a complete list of all default transaction types, please see the section xref:{url_lisk_protocol_transactions}[Lisk Protocol transactions] of  the xref:{url_lisk_protocol}[Lisk Protocol].
```suggestion
TIP: For a complete list of all default transaction types, please see the section xref:{url_lisk_protocol_transactions}[transactions of  the Lisk protocol].
```

2020-06-24 08:25 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/customize.adoc
> +:url_lisk_protocol: {v_protocol}@lisk-protocol::lisk-protocol/introduction.adoc
```suggestion
:v_protocol: master

:url_lisk_protocol: {v_protocol}@lisk-protocol::lisk-protocol/introduction.adoc
```

2020-06-24 08:25 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/customize.adoc
> +Transaction types 0-12 are reserved for the xref:{url_lisk_protocol}[Lisk Protocol].
```suggestion
Transaction types 0-12 are reserved for the xref:{url_lisk_protocol}[Lisk protocol].
```

2020-06-24 08:25 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_lisk_protocol: {v_protocol}@lisk-protocol::lisk-protocol/introduction.adoc
```suggestion
:v_protocol: master

:url_lisk_protocol: {v_protocol}@lisk-protocol::lisk-protocol/introduction.adoc
```

2020-06-25 16:08 UTC, chris529 reviewed
Cool...well spotted Mona! Yes..these are some good valid areas to further mention the appropriate corresponding pages in the Lisk protocol docs 👍

2020-06-26 08:56 UTC, Tschakki submitted a review, later dismissed
LGTM

2020-06-26 09:47 UTC, chris529 reviewed
Looks very good, just one very minor point 👍

2020-06-26 09:47 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Forging in xref:{url_protocol_dpos}[DPoS] networks is the same as mining in a PoW network: It is the process of adding new blocks to the chain.
```suggestion
Forging in xref:{url_protocol_dpos}[DPoS] networks is the same as mining in a PoW network, which is the process of adding new blocks to the chain.
```

2020-06-26 14:01 UTC, Tschakki approved these changes

2020-06-29 08:59 UTC, merged