Update testnet branch to testnet rc - Closes #60
LiskArchive/lisk-legacy-docs pull request #65
Opened 2018-09-05 13:50 UTC by Tschakki

Update `testnet-master` to `testnet-rc`

Closes #60

2018-09-11 13:54 UTC, MaciejBaj requested changes
It should be testnet-master. I will merge it so it's up to date.

2018-09-11 14:48 UTC, Tschakki commented
Alright, I'll close this PR then!

2018-09-12 12:10 UTC, MaciejBaj requested changes

2018-09-12 12:10 UTC, MaciejBaj commented on setup/install/source/installation-source.md
> +*Please check if there is no latest 1.1.0-rc.\* release on https://github.com/LiskHQ/lisk/releases*
Let's change it to `1.1.\*-rc.\*`

2018-09-12 12:52 UTC, MaciejBaj requested changes
Also, we need to support the installation of 1.0 version on Mainnet for now. I would leave the section of `### Mainnet` compatible with 1.0 and `### Testnet` section compatible with 1.1 version,

2018-09-12 12:59 UTC, nazarhussain requested changes

2018-09-12 12:59 UTC, nazarhussain commented on setup/install/source/installation-source.md
> +pm2 start --name lisk app.js -- -n [network]
To avoid any confusion for users please use `--network` here as well, as used in above commands without pm2.

2018-09-12 16:25 UTC, nazarhussain submitted a review, later dismissed

2018-09-13 09:18 UTC, Tschakki commented
After discussion with @MaciejBaj, we decided now to add references for the latest archived version of Lisk Core, as the version upgrade for Testnet and Mainnet is always delayed by a few days / weeks and so there is need to reference both versions of the documentation during that time.

2018-09-13 16:37 UTC, MaciejBaj commented on setup/install/source/installation-source.md
> +![info note](../../../info-icon.png "Info Note") | The installation process has changed from Lisk Core `1.0` to `1.1`. If you wish to install the `1.0` version of Lisk Core, please visit the [Lisk Do
The installation process has changed from Lisk Core `1.0` to `1.1` -> 
The described installation process is valid since Lisk Core 1.1 version. 

And the following.

2018-09-20 08:18 UTC, MaciejBaj approved these changes

2018-09-21 08:05 UTC, merged