Remove public key
LiskArchive/lisk-legacy-docs pull request #651
Opened 2020-06-25 13:04 UTC by ricott1

Remove public key from accounts, modify transaction page, modify account image

2020-06-25 13:26 UTC, IkerAlus requested changes
The link looks broken, the rest looks good to me.

2020-06-25 13:26 UTC, IkerAlus commented on modules/ROOT/pages/transactions.adoc
> +Note that this public key link:1-accounts.adoc#keys[does not necessarily sign the transaction].
This link looks broken. There is no `1-accounts.adoc` file. Following the link formatting I think it should be:
```
xref:{url_accounts_keys}[`keys`]
```

2020-06-25 13:36 UTC, IkerAlus submitted a review, later dismissed

2020-06-25 16:14 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +The `senderPublicKey` is used to generate the address under which the sender account information is stored.
```suggestion
The `senderPublicKey` is used to compute the address under which the sender account information is stored.
```

2020-06-25 16:14 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +The `senderPublicKey` is used to generate the address under which the sender account information is stored.
Generate sounds like a new address is created.

2020-06-25 16:14 UTC, janhack reviewed
Consider updating the formulation as suggested.

2020-06-26 06:50 UTC, MaximeGagnebin submitted a review, later dismissed

2020-06-26 07:42 UTC, MaximeGagnebin approved these changes

2020-06-26 07:43 UTC, janhack approved these changes

2020-06-26 07:43 UTC, IkerAlus approved these changes

2020-06-29 09:00 UTC, merged