Review html page names in SDK docs - closes #532
LiskArchive/lisk-legacy-docs pull request #655
Opened 2020-06-30 15:17 UTC by chris529

Closes issue #532

2020-06-30 15:31 UTC, Tschakki requested changes
Looking good already, just a few suggestions :)

2020-06-30 15:31 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:guides/customize-transactions.adoc[Create a custom transaction]
```suggestion
** xref:guides/custom-transactions.adoc[Create a custom transaction]
```

2020-06-30 15:31 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  * xref:reference/index.adoc[References]
```suggestion
* xref:references/index.adoc[References]
```

I think we wanted to rename this to `references`.

2020-06-30 15:31 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  ** xref:reference/config.adoc[Configuration]
```suggestion
** xref:references/configuration.adoc[Configuration]
```

2020-07-01 07:07 UTC, chris529 commented on modules/ROOT/nav.adoc
>  * xref:reference/index.adoc[References]
Yes, well spotted Mona 👍

2020-07-01 12:29 UTC, Tschakki requested changes
Please go back to this and rename the files/ folders everywhere consistently, and also update the links everywhere afterwards accordingly.

2020-07-01 12:29 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  *** xref:reference/lisk-elements/api-client.adoc[API client]
Please also fix the links for the other pages and rename the `reference` folder to `references`

2020-07-01 12:29 UTC, Tschakki commented on modules/ROOT/pages/guides/customize-transactions.adoc
> +:page-aliases: customize-transactions.adoc
This page alias should not be changed

2020-07-01 12:29 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +:url_custom: guides/customize-transactions.adoc
After renaming the filename of the page to `custom-transactions.adoc`, you also need to update all links referring to it.

2020-07-02 09:05 UTC, chris529 commented on modules/ROOT/nav.adoc
>  *** xref:reference/lisk-elements/api-client.adoc[API client]
OK, this should now be OK 👍

2020-07-02 09:09 UTC, chris529 commented on modules/ROOT/pages/guides/customize-transactions.adoc
> +:page-aliases: customize-transactions.adoc
OK, I am not 100% sure on this one Mona, I presume it should be customize.adoc then..?

2020-07-02 09:10 UTC, chris529 commented on modules/ROOT/pages/guides/index.adoc
> +:url_custom: guides/customize-transactions.adoc
OK, done 👍

2020-07-02 09:20 UTC, Tschakki submitted a review, later dismissed
Looks good!

2020-07-02 09:45 UTC, closed without merging