Review html page names in Core docs - closes #657
LiskArchive/lisk-legacy-docs pull request #658
Opened 2020-07-01 12:47 UTC by chris529

Closes Parent issue #532

2020-07-01 14:18 UTC, Tschakki requested changes
Please see my comments!

2020-07-01 14:18 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  * xref:management/index.adoc[Management]
I think we discussed the html names of the different distributions when we were renaming them, and agreed to leave them with the short name.

2020-07-01 14:18 UTC, Tschakki commented on modules/ROOT/nav.adoc
>  * xref:interact-with-network.adoc[Interact with the network]
This name could be improved to `interact-with-the-api.adoc`.

If you do, please think of updating the title of the page as well.

2020-07-01 14:18 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:management/source-commands.adoc[Source code commands]
I would not add `-commands` here. 

To make it consistent, I suggest to change the titles in `management` from e.g. `Docker commands` to `Docker image`

```suggestion
** xref:management/application.adoc[Application]
** xref:management/commander.adoc[Commander application]
** xref:management/docker.adoc[Docker image]
** xref:management/source.adoc[Source code]
```

2020-07-01 14:18 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:setup/source-code.adoc[Source code]
I think we discussed the html names of the different distributions when we were renaming them, and agreed to leave them with the short name.

2020-07-02 12:37 UTC, chris529 commented on modules/ROOT/nav.adoc
>  * xref:interact-with-network.adoc[Interact with the network]
Agreed...now done 👍

2020-07-02 13:45 UTC, chris529 commented on modules/ROOT/nav.adoc
> +** xref:setup/source-code.adoc[Source code]
OK, I think I should have caught all the associated links related to the page name changes etc. :-)

2020-07-03 08:11 UTC, Tschakki approved these changes
LGTM

2020-07-03 08:20 UTC, merged