Fix broken links in interact-with-api.adoc in Core docs 3.0.0 - Closes #666
LiskArchive/lisk-legacy-docs pull request #670
Opened 2020-07-10 14:25 UTC by chris529

2020-07-15 07:58 UTC, Tschakki requested changes
Pages with broken links:
https://liskhq.github.io/lisk-docs/lisk-core/3.0.0/index.html
https://liskhq.github.io/lisk-docs/lisk-core/3.0.0/setup/application.html
https://liskhq.github.io/lisk-docs/lisk-core/3.0.0/setup/commander-application.html
https://liskhq.github.io/lisk-docs/lisk-core/3.0.0/setup/docker-image.html
https://liskhq.github.io/lisk-docs/lisk-core/3.0.0/setup/source-code.html

2020-07-16 08:08 UTC, chris529 commented
Hey Mona! OK I have reinstated the original page names under setup, and have updated the associated links, so hopefully this should be OK now.

2020-07-16 10:22 UTC, Tschakki requested changes

2020-07-16 10:22 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:url_getting_started: management/index.adoc
This link is still broken, because is duplicated. Please remove one of them.
And update the other to point to the setup index, not management.

2020-07-16 10:22 UTC, Tschakki commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:url_elements_pkg: {v_sdk}@lisk-sdk::references/lisk-elements/index.adoc#package_list
The internal anchor does not work.

2020-07-16 10:22 UTC, Tschakki commented on modules/ROOT/pages/interact-with-the-api.adoc
> +In the xref:{url_elements_pkg}[Lisk Elements] page all available libraries are listed and documented.
```suggestion
In the xref:{url_elements_pkg}[Lisk Elements] page all available packages are listed and documented.
```

2020-07-16 11:46 UTC, chris529 commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:url_elements_pkg: {v_sdk}@lisk-sdk::references/lisk-elements/index.adoc#package_list
This is a strange one Mona, as in the above line no 24. it shows the following link :url_commander_commands: {v_sdk}@lisk-sdk::reference/lisk-commander/user-guide/commands.adoc
However in my branch, ( see excerpt below) it appears to be correct as we removed the 'user-guide' directory a while ago.
:url_commander_commands: {v_sdk}@lisk-sdk::references/lisk-commander/commands.adoc
I have pushed it again, so maybe it will appear correctly now..?

2020-07-16 12:47 UTC, Tschakki requested changes

2020-07-16 12:47 UTC, Tschakki commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:url_elements_pkg: {v_sdk}@lisk-sdk::references/lisk-elements/index.adoc#package_list
It looks ok now for me!
```suggestion
:url_elements_pkg: {v_sdk}@lisk-sdk::references/lisk-elements/index.adoc#packages
```
But I was referring to the internal anchor in line 22. To fix it please apply my suggestion

2020-07-16 12:50 UTC, chris529 commented
OK cool...now done 👍

2020-07-16 13:18 UTC, Tschakki approved these changes
LGTM

2020-07-16 13:27 UTC, merged