Review html page names in core docs 2.1.6 - Closes #672
LiskArchive/lisk-legacy-docs pull request #673
Opened 2020-07-14 15:28 UTC by chris529

Closes #672 and parent epic issue #532

2020-07-15 08:20 UTC, Tschakki requested changes

2020-07-15 08:20 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:setup/source-code.adoc[Source code]
These should not be changed imho.
It is also inconsistent with the page names in the `Update` and `Management` section.
Please fix this also for the Core 3.0.0 docs

2020-07-16 08:21 UTC, chris529 commented on modules/ROOT/nav.adoc
> +** xref:setup/source-code.adoc[Source code]
Hey Mona! OK, it should be done now, can you please check it. 👍

2020-07-16 10:14 UTC, Tschakki requested changes
Please fix the existing conflicts

2020-07-16 11:26 UTC, chris529 commented
Ah yes.. OK conflicts should now be resolved 👍

2020-07-16 11:32 UTC, Tschakki requested changes
One small issue left

2020-07-16 11:32 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> +:url_setup_docker_install: setup/docker-image.adoc#install
This should not be changed

2020-07-16 11:35 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +:url_setup_docker_install: setup/docker-image.adoc#install
Oh yes, already done now..well spotted again Mona! 👍

2020-07-16 13:26 UTC, Tschakki approved these changes
LGTM

2020-07-16 13:27 UTC, merged