Overall review of Core docs 2.1.6 - Closes #674
LiskArchive/lisk-legacy-docs pull request #676
Opened 2020-07-20 13:17 UTC by chris529

2020-07-27 14:54 UTC, Tschakki requested changes
Looks good to me, just 2 minor points

2020-07-27 14:54 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +* The ability to use Lisk Core to perform actions on the Lisk blockchain, e.g. with {url_lisk_desktop}[Lisk Desktop].
```suggestion
* The ability to use a self-controlled node to perform actions on the Lisk blockchain, e.g. with {url_lisk_desktop}[Lisk Desktop].
```

2020-07-27 14:54 UTC, Tschakki commented on modules/ROOT/pages/management/logs.adoc
> +|Trace(10) |Logging from external libraries used by your node, or otherwise very detailed application logging.
```suggestion
|Trace(10) |Logging from external libraries used by your node, or other very detailed application logging.
```

2020-07-30 09:18 UTC, chris529 commented
Thanks Mona! Well spotted! 👍

2020-07-31 08:13 UTC, Tschakki approved these changes
Thank you!

2020-07-31 08:26 UTC, merged