Update setup section - Closes #678
LiskArchive/lisk-legacy-docs pull request #679
Opened 2020-07-24 12:07 UTC by Tschakki

Closes #678

2020-08-04 08:36 UTC, MichalTuleja requested changes
Thanks for the contribution, it looks really awesome!

One thing I see missing is the Docker install for Postgres and Redis dependency during manual PM2-based install. 

Another tab might explain it how to leverage using Docker on local setup.

![Screenshot 2020-08-04 at 10 31 56](https://user-images.githubusercontent.com/4547510/89272087-eca7f200-d63d-11ea-87fa-a89986693b4d.png)

I think it makes sense to lead user to install Docker only for dependencies and describe it as follows:
```
cd docker/postgres
make up # to start PostgreSQL
make down # to stop PostgreSQL
```

and

```
cd docker/redis
make up
make down
```

Having this would make the documentation complete.

2020-08-04 14:38 UTC, MichalTuleja submitted a review, later dismissed

2020-08-05 11:24 UTC, chris529 requested changes
Looks very good...just some minor points 👍

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/docker.adoc
> +After updating the `Makefile` like described above, start Lisk Service again:
```suggestion
After updating the `Makefile` as described above, start Lisk Service again:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/docker.adoc
> +You will see the following contents:
```suggestion
The following contents below will be displayed:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/docker.adoc
> +The two existing options `LISK_CORE_HTTP` and `LISK_CORE_WS` are examples, how to set config options in this file.
```suggestion
The two existing options `LISK_CORE_HTTP` and `LISK_CORE_WS` are examples of how to set config options in this file.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/docker.adoc
> +To check see the complete list of all available config options of Lisk Service, go to the xref:{url_references_config}[configuration reference].
```suggestion
To check and view the complete list of all available config options of Lisk Service, go to the xref:{url_references_config}[configuration reference].
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/docker.adoc
> +.How to update the `Makefile`, to use a custom configuration
```suggestion
.How to update the `Makefile` to use a custom configuration
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/docker.adoc
> +All left to do is to start Lisk Service again:
```suggestion
All that is now remaining is to start Lisk Service again:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[ecosystem file^] allows to configure behavior, options, environment variables, logs files with {url_pm2}[PM2^] of each application.
```suggestion
The {url_pm2_ecosystem_file}[ecosystem file^] provides the possibility to configure the behavior, options, environment variables, and the logs files with {url_pm2}[PM2^] of each application.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +There are 2 default ecosystem files in the root folder of `lisk-service`:
```suggestion
There are 2 default ecosystem files in the root folder of `lisk-service`as shown below:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +To create a custom configuration, a good start is to copy one of the default configuration.
```suggestion
To create a custom configuration, it is recommended to copy one of the default configurations.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +Now it is possible to open the new file `ecosystem.custom.config.js` and adjust as desired.
```suggestion
Now it is possible to open the new file `ecosystem.custom.config.js` and adjust it as desired.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +Finally, if you want to use `npm start` and `npm stop` to start and stop Lisk Service with the custom configuration, dont forget to update the scripts in `package.json`:
```suggestion
Finally, if you want to use `npm start` and `npm stop` to start and stop Lisk Service with the custom configuration, don't forget to update the scripts in `package.json`:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +More commands how to manage Lisk Service with PM2 are described on the xref:{url_management_pm2}[PM2 commands] page.
```suggestion
Additional commands for managing Lisk Service with PM2 are described on the xref:{url_management_pm2}[PM2 commands] page.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +|The Template service is an abstract service that all of Lisk Service services are inherited from.
```suggestion
|The Template service is an abstract service whereby all of the services from Lisk Service are inherited from.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +Its purpose is to reduce code duplication and increase consistency between each service, hence simplifying code maintenance and testing.
```suggestion
The purpose here is to reduce code duplication and increase consistency between each service, hence simplifying code maintenance and testing.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The xref:{url_api_http}[HTTP API] offers a RESTful API with various additional endpoints compared to the HTTP API of a normal Lisk node.
```suggestion
The xref:{url_api_http}[HTTP API] offers a RESTful API with various additional endpoints as compared to the HTTP API of a normal Lisk node.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +The API reference also allows to send **interactive requests** to Lisk Service, to retrieve live data from the Lisk Mainnet.
```suggestion
The API reference also offers the possibility to send **interactive requests** to Lisk Service, in order to retrieve live data from the Lisk Mainnet.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +.Example request: Get a list of all 101 currently forging delegates
```suggestion
.Example request: Obtain a list of all 101 currently forging delegates
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/management/docker.adoc
> +This will start Lisk Service with the default configuration, which will connect to a Lisk Core Mainnet node.
```suggestion
This will start Lisk Service with the default configuration, which in turn will connect to a Lisk Core Mainnet node.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/management/source.adoc
> +To manage a Lisk Service instance, that is connected to a different network than the Lisk Mainnet, replace `ecosystem.mainnet.config.js` with `ecosystem.testnet.config.js` or `ecosystem.custom.config
```suggestion
To manage a Lisk Service instance that is connected to a different network than the Lisk Mainnet, replace `ecosystem.mainnet.config.js` with `ecosystem.testnet.config.js` or `ecosystem.custom.config.js`.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +These options are available for all micro-services provided by Lisk Service.
```suggestion
The following options below are available for all micro-services provided by Lisk Service.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +# Make sure that all micro-services are able to connect with ir
```suggestion
# Ensures that all micro-services are able to connect with it
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/references/configuration.adoc
> +# Note it is a different DB that SERVICE_BROKER uses
```suggestion
# Note: SERVICE_BROKER uses a different DB
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +Alternative ways how to install Lisk Service are described on the xref:{url_setup}[Setup] page.
```suggestion
Alternative options of how to install Lisk Service are described on the xref:{url_setup}[Setup] page.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +If you already have Brew installed, make sure it is working and up-to-date.
```suggestion
If you already have Brew installed, ensure it is working and up-to-date.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +TIP: Configure Docker, so it can be run without `sudo` rights: {url_docker_linux_post_install}[linux post install^].
```suggestion
TIP: To configure Docker so it can be run without `sudo` rights, follow: {url_docker_linux_post_install}[linux post install^].
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +In case you wish to build from your local version of Lisk Service, you need to run `make build` before:
```suggestion
In case you wish to build from your local version of Lisk Service, firstly you need to run `make build` as shown below:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +You can stop Lisk Service again with:
```suggestion
You can stop Lisk Service again with the following command:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +TIP: Check the xref:{url_index_usage}[Usage] section for examples, how to use and interact with Lisk Service.
```suggestion
TIP: Check the xref:{url_index_usage}[Usage] section for examples of how to use and interact with Lisk Service.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +TIP: Install from source code if you want to customize the codebase of Lisk Service, for example by adjusting the API to be fully compatible your blockchain application.
```suggestion
TIP: Install from source code if you want to customize the codebase of Lisk Service. For example, by adjusting the API to be fully compatible with your blockchain application.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +As alternative to the Docker image setup, it is also possible to install Lisk Service xref:{url_setup_source}[from source code].
```suggestion
As an alternative to the Docker image setup, it is also possible to install Lisk Service xref:{url_setup_source}[from source code].
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +This setup requires more steps than the Docker image installation, but enables the developer to customize Lisk Service codebase.
```suggestion
This setup requires more steps than the Docker image installation, however this provides the developer with the possibility to customize the Lisk Service codebase.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +This guide describes, how to setup Lisk Service with PM2.
```suggestion
This guide describes how to setup Lisk Service with PM2.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Alternative ways how to install Lisk Service are described on the xref:{url_setup}[Setup] page.
```suggestion
Alternative options of how to install Lisk Service are described on the xref:{url_setup}[Setup] page.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +In Ubuntu and its derivatives APT is the base package management application. Make sure your local APT registry is up-to-date.
```suggestion
In Ubuntu and its derivatives APT is the base package management application. Ensure your local APT registry is up-to-date.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Next, make sure your package sources are up to date:
```suggestion
Next, ensure your package sources are up to date:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
>  To install Postgres follow the instructions.
```suggestion
To install PostgresSQL follow the instructions below:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the Installation with Docker page.
```suggestion
Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the Installation with the Docker page.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +.How to install and start PostgreSQL with Docker
```suggestion
.How to install and start PostgreSQL with Docker is shown below:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the "Installation with Docker" page.
```suggestion
Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the "Installation with the Docker" page.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +The above commands should be enough to install Redis ready to use with Lisk Service.
```suggestion
The above commands should be enough to install Redis which is ready to use with Lisk Service.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Lisk Service not compatible with this service right now.
```suggestion
Lisk Service is not compatible with this service right now.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +If you haven't already, clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder and check out the latest release.
```suggestion
If you have not already done so, clone the {url_github_service}[lisk-service^] GitHub repository and then navigate into the project folder and check out the latest release.
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Now it is possible to start Lisk Service:
```suggestion
Now it is possible to start Lisk Service as shown below:
```

2020-08-05 11:24 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +TIP: Check the xref:{url_index_usage}[Usage] section for examples, how to use and interact with Lisk Service.
```suggestion
TIP: Check the xref:{url_index_usage}[Usage] section for examples of how to use and interact with Lisk Service.
```

2020-08-05 12:28 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +The {url_pm2_ecosystem_file}[ecosystem file^] allows to configure behavior, options, environment variables, logs files with {url_pm2}[PM2^] of each application.
```suggestion
The {url_pm2_ecosystem_file}[ecosystem file^] provides the possibility to configure behavior, options, environment variablesand the logs files of each application with {url_pm2}[PM2^].
```

2020-08-05 12:32 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +There are 2 default ecosystem files in the root folder of `lisk-service`:
Is there any reason, why you ad to the colon `as shown below`?

Isn't the colon making this obvious?

2020-08-05 14:21 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +TIP: Install from source code if you want to customize the codebase of Lisk Service, for example by adjusting the API to be fully compatible your blockchain application.
```suggestion
TIP: Install from source code if you want to customize the codebase of Lisk Service, e.g. if you want to adjust the API to be fully compatible your blockchain application.
```

2020-08-05 15:27 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the Installation with Docker page.
```suggestion
Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the "Installation with Docker" page.
```

2020-08-05 15:28 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +.How to install and start PostgreSQL with Docker
I don't think this is necessary to add here.

2020-08-05 15:29 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the "Installation with Docker" page.
`the` doesn't make sense here imho. We refer to the title of the Docker setup page here.

2020-08-05 15:30 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +Now it is possible to start Lisk Service:
not sure this is needed

2020-08-06 10:04 UTC, chris529 commented on modules/ROOT/pages/configuration/source.adoc
> +There are 2 default ecosystem files in the root folder of `lisk-service`:
Yes you are right the colon does make it obvious. There is no definitive rule here, as it is more a case of personal preference in this sentence. In other words, in this case both sentences above are actually technically correct, so feel free to decide which one you prefer Mona.

2020-08-06 10:12 UTC, chris529 reviewed
Looking very good, have left a few comments.. 👍

2020-08-06 10:12 UTC, chris529 commented on modules/ROOT/pages/setup/docker.adoc
> +If you already have Brew installed, ensure it is working and up-to-date.
```suggestion
If you already have Brew installed, ensure it is working and is the latest version.
```

2020-08-06 10:12 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +We recommend to use the latest LTS version
```suggestion
We recommend to use the latest LTS version.
```

2020-08-06 10:12 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +.How to install and start PostgreSQL with Docker
OK, you are right...it is not absolutely necessary. It is just personal preference again..

2020-08-06 10:12 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Follow the steps described in the xref:{url_setup_docker_docker}[Prerequisites > Docker] section of the "Installation with Docker" page.
Oops...yes you are right Mona, that was my mistake! Please leave it as it is 👍

2020-08-06 10:12 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +Now it is possible to start Lisk Service:
Ah yes...same as before...personal preference, so leave it as it is.

2020-08-06 10:44 UTC, Tschakki commented on modules/ROOT/pages/configuration/source.adoc
> +There are 2 default ecosystem files in the root folder of `lisk-service`:
Ok, in that case I tend to prefer the version with less words :)

2020-08-06 13:02 UTC, chris529 reviewed
99.9% ! Looks very good indeed..just a few very minor points 👍

2020-08-06 13:02 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +This API can be utilized to build powerful Wallets and user interfaces for blockchain applications which are built with the Lisk SDK.
```suggestion
This API can be utilized to build powerful wallets and user interfaces for blockchain applications which are built with the Lisk SDK.
```

2020-08-06 13:02 UTC, chris529 commented on modules/ROOT/pages/setup/index.adoc
> +TIP: Install from source code if you want to customize the codebase of Lisk Service, e.g. if you want to adjust the API to be fully compatible your blockchain application.
```suggestion
TIP: Install from source code if you want to customize the codebase of Lisk Service, e.g. if you want to adjust the API to be fully compatible with your blockchain application.
```

2020-08-06 13:02 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +During this step it is possible to change your port if you wish to have more Postgres instances in the future.
```suggestion
During this step it is possible to change your port if you wish to have more PostgresSQL instances in the future.
```

2020-08-07 08:04 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +.Check for the latest LTS version
```suggestion
.Check for the latest LTS version.
```

2020-08-07 08:04 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +.Install the latest LTS version
```suggestion
.Install the latest LTS version.
```

2020-08-07 08:05 UTC, chris529 commented on modules/ROOT/pages/setup/source.adoc
> +.How to install and start PostgreSQL with Docker
```suggestion
.How to install and start PostgreSQL with Docker.
```

2020-08-07 08:09 UTC, chris529 approved these changes
LGTM!

2020-08-07 08:20 UTC, merged