Overall review of SDK docs 3.0.2 - closes #686
LiskArchive/lisk-legacy-docs pull request #697
Opened 2020-08-13 06:25 UTC by chris529

Parent issue #665

2020-09-15 12:15 UTC, Tschakki requested changes
Please fix the conflicts first :)

2020-09-16 09:25 UTC, chris529 commented
Hi Mona, The conflicts seem to be resolved, although I seem to have a merging blocked message. Can you check this please when you have a minute? Many thanks.

2020-09-18 11:22 UTC, Tschakki requested changes
Overall looking really good!
Just a few things I found, which I mentioned in the comments.

2020-09-18 11:22 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/custom-transactions.adoc
> +The `store` is available inside the `prepare()`, `applyAsset()` and `undoAsset()` methods, and provides procedures to get and set the data from the database.
methods is the correct terminology in this context

2020-09-18 11:22 UTC, Tschakki commented on modules/ROOT/pages/guides/index.adoc
> +. The xref:{url_logging}[activate logging guide] describes the logging messages, including the log level destinations and rotations, for monitoring or debugging a node.
remove including here
```suggestion
. The xref:{url_logging}[activate logging guide] describes the logging messages, the log level destinations and rotations, for monitoring or debugging a node.
```

2020-09-18 11:22 UTC, Tschakki commented on modules/ROOT/pages/references/api-specification.adoc
>  == Access restrictions
The contents here are autogenerated, and need to be updated in the `swagger.yml` file in the lisk-sdk repository, if required. For now, please revert all changes made in this file.

2020-09-18 11:22 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> -__optional__|Current height of the network|integer (int32)|
Starting from this line, all below content is coming from the `swagger.yml` file, so no changes should be done here, as it is auto generated content. If necessary, create a PR to update the contents of `swagger.yml` in the lisk-sdk repository.

2020-09-23 08:38 UTC, chris529 commented on modules/ROOT/pages/references/api-specification.adoc
>  == Access restrictions
OK, it should be fine now..

2020-09-23 08:51 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> -__optional__|Current height of the network|integer (int32)|
OK, this should also be fine now.

2020-09-24 11:02 UTC, Tschakki requested changes
Looking great! Just one very minor issue left 👍

2020-09-24 11:02 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +and `Database layer SDK 3.x`
Please use 1 line per sentence.

2020-09-24 13:00 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +and `Database layer SDK 3.x`
Good catch Mona! Now done.. 👍

2020-09-24 13:22 UTC, Tschakki approved these changes
LGTM

2020-09-24 13:29 UTC, merged