ChangeLog 3.x to 4.x - Closes #560
LiskArchive/lisk-legacy-docs pull request #720
Opened 2020-08-21 10:59 UTC by Tschakki

Closes #560

2020-08-26 08:53 UTC, chris529 reviewed
Just a few minor points 👍

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +The voting process has changes as shown in the code snippet below.
```suggestion
The voting process now has certain changes which can be seen in the code snippet below.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +The `applyAsset()` function of custom transaction has become asynchronous, so you need to adjust the function in your implementation to something like this:
```suggestion
The `applyAsset()` function of custom transaction has become asynchronous, so it is necessary to adjust the function in your implementation to something similar as shown below:
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +The accounts that are returned from the xref:{url_guides_tx_store}[store] in transactions are now returned as instances of the Account class instead of pure objects.
```suggestion
The accounts that are returned from the xref:{url_guides_tx_store}[store] in transactions are now returned as instances of the account class instead of pure objects.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +Because of this, it is recommended to mutate the received account instance directly.
```suggestion
Due to this, it is recommended to mutate the received account instance directly.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +The properties of custom transactions can now be updated like so:
```suggestion
The properties of custom transactions can now be updated as shown below:
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It defines the minimum amount of tokens that need to paid per Byte of a particular transaction type.
```suggestion
This defines the minimum amount of tokens that need to paid per byte of a particular transaction type.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It defaults to `1000`, but can be overwritten as desired.
```suggestion
This defaults to `1000`, but can be overwritten as desired.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It defines an absolute amount of tokens that always need to be paid as transaction fee, in addition to the fees generated by the `MIN_FEE_PER_BYTE` property.
```suggestion
This defines a specific amount of tokens that always need to be paid as a transaction fee, in addition to the fees generated by the `MIN_FEE_PER_BYTE` property.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It defaults to `0`, but can be overwritten as desired.
```suggestion
This defaults to `0`, but can be overwritten as desired.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +The timestamp which has been a required property previously has been replaced by a nonce.
```suggestion
The timestamp which was previously a required property has been replaced by a nonce.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +Nonces prevent transaction replays and enable users to invalidate transactions, in case of need.
```suggestion
Nonces prevent transaction replays and enable users to invalidate transactions, if so required
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +If the minimum balance for accounts is set to a reasonable value, it prevents the network from certain spam attacks, like creating a lot of new accounts with basically no balance.
```suggestion
If the minimum balance for accounts is set to a reasonable value, it prevents the network from certain spam attacks, such as the creation of many new accounts with zero balance.
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +__optional__|The value indicating if the account is a deleage or not.|boolean
```suggestion
__optional__|The value indicating if the account is a delegate or not.|boolean
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +__required__|The current nonce associated to account for transaction processing. +
```suggestion
__required__|The current nonce associated to an account for transaction processing. +
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
```suggestion
This can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
```suggestion
This can be used to validate that the private key belongs to the owner, but does not provide access to the owners private key. +
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +It is unique and cannot be changed later. +
```suggestion
It is unique and cannot be changed. +
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +The signature can be generated locally, either by using Lisk Commander or with Lisk elements. +
```suggestion
The signature can be generated locally, either by using Lisk Commander or with Lisk Elements. +
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +__optional__|Contains the second signature, if the transaction is sent from an account with second passphrase activated. +
```suggestion
__optional__|Contains the second signature, if the transaction is sent from an account with a second passphrase activated. +
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +__optional__|Second public key to query|string (publicKey)|
```suggestion
__optional__|Second public key to query.|string (publicKey)|
```

2020-08-26 08:53 UTC, chris529 commented on modules/ROOT/pages/references/changelog.adoc
> +__optional__|Second public key to query|string (publicKey)|
```suggestion
__optional__|Second public key to query.|string (publicKey)|
```

2020-08-26 11:30 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +The accounts that are returned from the xref:{url_guides_tx_store}[store] in transactions are now returned as instances of the Account class instead of pure objects.
```suggestion
The accounts that are returned from the xref:{url_guides_tx_store}[store] in transactions are now returned as instances of the `Account` class instead of pure objects.
```

2020-08-26 12:15 UTC, chris529 approved these changes, later dismissed
LGTM!

2020-08-27 11:59 UTC, shuse2 requested changes
Assuming that the API doc comes from swagger, some small minor points.
Otherwise LGTM

2020-08-27 11:59 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/custom-transactions.adoc
> +To increase your application’s performance, the following functions should be overidden: `MIN_FEE_PER_BYTE`, `NAME_FEE`, `verifyAgainstTransactions`, `assetFromSync`, `fromSync`.
Maybe rephrase this paragraph because fee does not increase performance.
Also, 
> verifyAgainstTransactions`, `assetFromSync`, `fromSync`. no longer exist and requried.

2020-08-27 11:59 UTC, shuse2 commented on modules/ROOT/pages/references/changelog.adoc
> +    fee: '250000',
I think as general practice, senderPublicKey should be included when instantiating
because with the new multi-sig, it's possible that senderPublicKey does not associate with the signature

2020-08-27 11:59 UTC, shuse2 commented on modules/ROOT/pages/references/changelog.adoc
> +MultisignatureTransaction {
Do we need to show this class instance?

2020-08-27 12:08 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +    fee: '250000',
Imho it is not necessary to provide the senderPublicKey in this step, because it gets added automatically once the transaction is signed with the `sign()` method.

2020-08-27 12:16 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +MultisignatureTransaction {
Not necessarily.. I removed it now 👍

2020-08-27 12:53 UTC, shuse2 commented on modules/ROOT/pages/references/changelog.adoc
> +    fee: '250000',
it does now for the single signature account, but for multi-signature account it will be required to put the sender public key. (sender public key cannot be derived from the passphrase anymore

2020-08-27 14:21 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +    fee: '250000',
What does this mean from UX perspective? Can it be derived from the Address?
If so, do I need to add my address/public key to every transaction before I can sign it with my passphrase?
Sounds not like an optimal solution to me UX-wise. 
Can you provide with a good UX solution for this? 
Otherwise I would keep it like this for now, as for 4.x this is still absolutely valid.

2020-08-27 16:23 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +    fee: '250000',
I see! I will add a new section about creating multisig transactions in the changelog, and also in the app-development guides, to cover the topic. I wouldn't update the general examples, to keep it simple.

2020-08-28 07:46 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/custom-transactions.adoc
> +It's recommended to override the values of `MIN_FEE_PER_BYTE`, `NAME_FEE` properties of a custom transaction depending on the use case.
im not sure we should recommend this? it's more like if u have solid reason to change, then it can be changed, but otherwise it should remain as default

2020-09-16 11:48 UTC, shuse2 approved these changes

2020-09-16 11:52 UTC, merged