Explanations about DPoS and voting - Closes #558
LiskArchive/lisk-legacy-docs pull request #723
Opened 2020-08-27 14:24 UTC by Tschakki

Add new explanations category to the docs.

Closes #558

2020-09-18 15:21 UTC, itstheandre reviewed
Looks great to me!
Understandable and clear

2020-09-21 08:19 UTC, chris529 requested changes
Looks good, just a few small points.. 👍

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +In PoS-based blockchains the creator of the next block is chosen via a selection mechanism that is somehow related to the stake that an individual account holds.
```suggestion
In PoS-based blockchains the creator of the next block is chosen via a selection mechanism that is related to the stake that an individual account holds.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +A higher stake means in this regard generally increased chances to forge a new block to the blockchain.
```suggestion
In this regard, a higher stake generally means there is an increased chance to forge a new block to the blockchain.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +In DPoS based blockchains, the consensus about who can forge the next block is reached by users who vote with their stake for other users.
```suggestion
In DPoS based blockchains, the consensus regarding who can forge the next block is reached by users who vote with their stake for other users.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +NOTE: The DPoS used by Lisk is in fact more of a middle way between PoS and DPoS, as it also requires delegates to hold and lock a certain amount of tokens in their account.
```suggestion
NOTE: The DPoS used by Lisk is in fact more of a middle ground between PoS and DPoS, as it also requires delegates to hold and lock a certain amount of tokens in their account.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +The process of forging hardly consumes any energy and is therefore an extremely *energy-friendly* consensus algorithm compared to "mining", which is the analog process for blockchains that run with P
```suggestion
The process of forging consumes a minimal amount of energy and is therefore an extremely *energy-friendly* consensus algorithm as compared to "mining", which is the analog process for blockchains that run with Proof of Work (PoW).
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +The order in which the selected delegates forge new blocks is random and not connected to the delegate weight.
```suggestion
The order in which the selected delegates forge new blocks is a random process and is not connected to the delegate weight.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +During a forging round, no new calculations need to be done, which makes the process so efficient.
```suggestion
During a forging round, no new calculations are required which makes the process highly efficient.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +This allows a very energy efficient process of adding new blocks, which enables to run forging nodes even on very weak machines, like a Raspberry Pi.
```suggestion
This technique enables a very energy efficient process of adding new blocks, which allows forging nodes to run even on machines with very limited processing capabilities, such as a Raspberry Pi.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +The delegate weight is defined like this:
```suggestion
The delegate weight is defined as shown below:
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +All accounts in the network can register as delegate by sending a delegate registration transaction.
```suggestion
All accounts in the network can register as a delegate by sending a delegate registration transaction.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +Once an account is registered as delegate, it is possible for other accounts in the network to vote for this delegate.
```suggestion
Once an account is registered as a delegate, it is possible for other accounts in the network to vote for this delegate.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +Lets assume you hold an account with a balance of 100 tokens.
```suggestion
For instance, lets assume you hold an account with a balance of 100 tokens.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +It is of course possible to split your tokens among multiple delegates, or to use all to vote for only one delegate.
```suggestion
It is of course possible to split your tokens among multiple delegates, or to use all of them to vote for only one delegate.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +For example you could use it to vote for 10 delegates with 10 tokens, or on one delegate with the full 100 tokens.
```suggestion
For example you could use it to vote for 10 delegates with 10 tokens, or alternatively just on one delegate with the full 100 tokens.
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +To use those tokens, the account has to submit a xref:{url_protocol_transactions_vote}[delegate vote transaction] with a negative amount (also called “unvote”).
```suggestion
To use those tokens, the account has to submit a xref:{url_protocol_transactions_vote}[delegate vote transaction], with a negative amount (also called “unvote”).
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +This will start the unlocking procedure and the LSK will be ready for unlock 2000 blocks later (roughly 5 hours and 30 minutes).
```suggestion
This will start the unlocking procedure and the LSK will be ready for unlocking 2000 blocks later (roughly 5 hours and 30 minutes).
```

2020-09-21 08:19 UTC, chris529 commented on modules/ROOT/pages/explanations/consensus.adoc
> +Future improvements of the Lisk blockchain (particularly on the database level) could render this unlock transaction unnecessary.
```suggestion
Future improvements of the Lisk blockchain (particularly on the database level), could render this unlock transaction unnecessary.
```

2020-09-21 08:39 UTC, chris529 approved these changes
Looks perfect 👍

2020-09-21 08:45 UTC, merged