Update to doc for the new on-chain architecture
LiskArchive/lisk-legacy-docs pull request #728
Opened 2020-09-15 14:46 UTC by IkerAlus

changes to the following sections:
- accounts
-transactions
-mainnet

2020-09-21 16:08 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +This transaction reports a proof of misbehaviour of a certain delegate.
```suggestion
This transaction can be utilized to report a misbehavior of a certain delegate.
```

2020-09-21 16:09 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +This transaction reports a proof of misbehaviour of a certain delegate.
Report a proof seems a bit redundant. Note that also the spelling is changed to American English.

2020-09-21 16:12 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +:description: This section explains the different account properties and how these relate to different transactions.
```suggestion
:description: This section explains the different account properties and their correspondence to different modules.
```

2020-09-21 16:19 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +This section lists the properties stored in a Lisk account. Except for `address`, they are contained in four property modules: `token`, `sequence`, `keys`, and `dpos`.
```suggestion
This section lists the properties of a Lisk account. The properties, except the `address` as account identifier,  are organized into four different objects, each corresponding to one of the four default modules: `token`, `sequence`, `keys`, and `dpos`. 
```

2020-09-21 16:22 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +This section lists the properties stored in a Lisk account. Except for `address`, they are contained in four property modules: `token`, `sequence`, `keys`, and `dpos`.
I would say a module is the transaction schemas, account schema, transaction validation and logic together. So I would  say that the different objects in an account correspond to modules rather than calling these objects "property modules". But maybe Shu could give feedback on that.

2020-09-21 16:28 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +The balance is an integer value indicating how many tokens are stored in the account and available to be used. It belongs to the `token` module of the account.
```suggestion
The balance is an integer value indicating how many tokens are stored in the account and available to be used. It belongs to the `token` object of the account.
```

2020-09-21 16:29 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +The balance is an integer value indicating how many tokens are stored in the account and available to be used. It belongs to the `token` module of the account.
In JSON you call a collection of properties (key-value pairs) object. I am unsure whether it makes sense to say "module of the account".

2020-09-21 16:30 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +This property stores the current xref:{url_transactions_nonce}[*`nonce`*] of the account. It belongs to the `sequence` module of the account.
```suggestion
This property stores the current xref:{url_transactions_nonce}[*`nonce`*] of the account. It belongs to the `sequence` object of the account.
```

2020-09-21 16:31 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +The following properties are part of the `dpos` module in the default Lisk protocol.
```suggestion
The following properties are part of the `dpos` object in the default Lisk protocol.
```

2020-09-21 16:33 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +It contains all the information relevant to the specific DPoS protocol of the chain.
```suggestion
The `dpos` object contains all account properties related to the DPoS protocol.
```

2020-09-21 16:34 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +It contains all the information relevant to the specific DPoS protocol of the chain.
As we don't use the account asset as container for sidechain-specific properties, I would not add "of the chain". Otherwise, we could add the same to the balance or keys object.

2020-09-21 16:35 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
>  Tokens used to vote for a delegate are frozen, and have to be unlocked to make them available again. Similarly to the `votes` property, this property stores the voted-delegate's address and the amoun
```suggestion
Tokens used to vote for a delegate are locked, and have to be unlocked to make them available again. Similarly to the `votes` property, this property stores the voted-delegate's address and the amount, but also the block in which the votes have been removed from the delegate.
```

2020-09-21 16:36 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
>  Tokens used to vote for a delegate are frozen, and have to be unlocked to make them available again. Similarly to the `votes` property, this property stores the voted-delegate's address and the amoun
I would not use synonyms here as it can rather lead to confusion. `frozen` may sound indefinitely.

2020-09-21 16:37 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +After the appropriate waiting time, the user can then unlock the tokens with an xref:{url_transactions_unlock}[token unlock transaction].
```suggestion
After the appropriate waiting time, the user can then unlock the tokens with a xref:{url_transactions_unlock}[token unlock transaction].
```

2020-09-21 16:39 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +|*Transaction*|*Purpose*
Maybe I would add a "Module" column to the table.

2020-09-21 16:41 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +|*delegate misbehavior report*|Report a proof-of-misbehavior of a delegate
```suggestion
|*delegate misbehavior report*|Report a misbehavior of a delegate
```

2020-09-21 16:42 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +|*multisignature group registration*|Register a multisignature group in the account
```suggestion
|*multisignature group registration*|Register a multisignature group for the account
```

2020-09-21 16:44 UTC, janhack commented on modules/ROOT/pages/mainnet.adoc
>  The Lisk Mainnet supports one additional transaction.
```suggestion
Lisk Mainnet additionally contains the `legacyAccount` module which contains the following transaction.
```

2020-09-21 17:00 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +There is a set of different transaction and each of these transactions defines a specific logic for modifying accounts depending on the transaction data.
```suggestion
Similar transactions are grouped together into one module. 
Apart from the module-specific account properties, a module defines the validation and execution logic for every transaction contained within that module. 
```

2020-09-21 17:01 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +In the table below, a summary of these transaction  and the purpose each of them serve is shown.
```suggestion
The Lisk protocol contains four default modules, `token`, `sequence`, `keys`, and `dpos`, which define the transactions shown in the table below.
```

2020-09-21 17:06 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +The 6 different transactions available in the Lisk protocol are listed in the table displayed above.
```suggestion
The 6 different transactions from the default modules of the Lisk protocol are listed in the table displayed above.
```

2020-09-21 17:10 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +This transaction registers the sender account as a xref:{url_consensus_voting_and_weight}[delegate] with the name given in `username`. A valid name contains only characters from the set _[a-z0-9!@$&_
I think the typesetting of the regular expression is broken. Maybe use `code` for it?

2020-09-21 17:21 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Given a specific value for the  properties `moduleID` and `assetID`, there exists a unique `asset` property.
>  The values of `moduleID` and `assetID` together uniquely correspond to one asset schema.
Or
>  Every pair of values  `(<moduleID>,<assetID>)` must uniquely correspond to one asset schema defined in the respective module.

2020-09-21 17:23 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Given a specific value for the  properties `moduleID` and `assetID`, there exists a unique `asset` property.
As it is not just one value, but the two values which define it. And it is rather a unique schema than a unique asset property (key-value pair).

2020-09-22 13:28 UTC, janhack requested changes
Please have a look at the comments and maybe double-check with Shu regarding the wording related to modules.

2020-09-22 14:19 UTC, IkerAlus commented on modules/ROOT/pages/accounts.adoc
> +This section lists the properties stored in a Lisk account. Except for `address`, they are contained in four property modules: `token`, `sequence`, `keys`, and `dpos`.
@shuse2 considering Jan's comment, what would you think is the proper way to refer to the account objects for the different modules? Are you ok with "object that correspond to a default module"?

2020-09-22 14:26 UTC, shuse2 commented on modules/ROOT/pages/accounts.adoc
> +This section lists the properties stored in a Lisk account. Except for `address`, they are contained in four property modules: `token`, `sequence`, `keys`, and `dpos`.
yes i think 
> different objects, each corresponding to one of the four default modules: `token`, `sequence`, `keys`, and `dpos`.

make sense. maybe 
```
each corresponding to one of the account schema defined in four default modules
```
is slightly more descriptive?

2020-09-23 07:53 UTC, janhack commented on modules/ROOT/pages/accounts.adoc
> +This section lists the properties stored in a Lisk account. Except for `address`, they are contained in four property modules: `token`, `sequence`, `keys`, and `dpos`.
Sounds good. Just small grammar fix
> each corresponding to one of the account schema**s** defined in **the** four default modules

2020-09-23 08:19 UTC, IkerAlus commented on modules/ROOT/pages/transactions.adoc
> +In the table below, a summary of these transaction  and the purpose each of them serve is shown.
modified the wording because I think that a module does not define a transaction (the specific asset does)

2020-09-23 08:24 UTC, IkerAlus commented on modules/ROOT/pages/transactions.adoc
> +There is a set of different transaction and each of these transactions defines a specific logic for modifying accounts depending on the transaction data.
worded differently because I think that a module does not define a transaction (the specific asset does)

2020-09-23 08:25 UTC, IkerAlus commented on modules/ROOT/pages/transactions.adoc
> +In the table below, a summary of these transaction  and the purpose each of them serve is shown.
Also, `sequence` module does not contain any transaction per se, but I think it is ok to leave it like this

2020-09-23 16:45 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Every account can issue a transaction, with the corresponding signature and data. There is a set of different transaction and each of these transactions has an specific validation and execution logic
It would be nice to stick to one sentence = one line as it makes the GitHub review a bit easier.

2020-09-23 16:46 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Every account can issue a transaction, with the corresponding signature and data. There is a set of different transaction and each of these transactions has an specific validation and execution logic
Just to put here my original comment and suggestions to remove
>There is a set of different transaction and each of these transactions has an specific validation and execution logic.

and add the following after the sentence "Similar transactions ...".

> Apart from the module-specific account properties, a module defines the validation and execution logic for every transaction contained within that module.

2020-09-23 16:49 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Every account can issue a transaction, with the corresponding signature and data. There is a set of different transaction and each of these transactions has an specific validation and execution logic
Could we have feedback from @shuse2  whether it makes sense to phrase it like that. I agree that there is a BaseModul and BaseAsset interface and you need to implement the second for implementing the transaction logic. My understanding is that conceptually everything is still referred to as module

2020-09-23 16:58 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
>  image::unif_diagrams/BaseTransaction.png[TxDiagram,width=339,height=310]
The term `type-specific Asset` may be a bit unclear/misleading. We could also but `Bytes` here and the write below:
>Every pair of values (moduleID,assetID) must uniquely correspond to one asset schema defined in the respective module, which defines how to deserialize the bytes provided in the transaction asset.

2020-09-23 17:01 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +In the table below, a summary of these transaction  and the purpose each of them serve is shown.
The new formulation sounds good!

2020-09-23 17:02 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +There is a set of different transaction and each of these transactions defines a specific logic for modifying accounts depending on the transaction data.
I created a new comment below so I resolve this one.

2020-09-23 17:10 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Every pair of values (`moduleID`,`assetID`) must uniquely correspond to one asset schema defined in the respective module. The section <<types,Transactions>> describes the different transaction with
```suggestion
Every pair of values (`moduleID`,`assetID`) must uniquely correspond to one asset schema defined in the respective module. 
The section <<types,Transactions>> describes the asset schema and general transaction logic for all transaction in the default modules listed above.
```

2020-09-23 17:15 UTC, janhack commented on modules/ROOT/pages/transactions.adoc
> +Every pair of values (`moduleID`,`assetID`) must uniquely correspond to one asset schema defined in the respective module. The section <<types,Transactions>> describes the different transaction with
I tried to make the sentence a bit more precise and clear. E.g., "the different transactions" is a bit vague.

2020-09-23 17:22 UTC, janhack requested changes
Overall looks good, there are a few open comments left.

2020-09-24 15:26 UTC, IkerAlus commented on modules/ROOT/pages/transactions.adoc
>  image::unif_diagrams/BaseTransaction.png[TxDiagram,width=339,height=310]
added the sentence at line 78. Modified the diagram as requested.

2020-09-24 15:39 UTC, IkerAlus commented on modules/ROOT/pages/transactions.adoc
> +Every account can issue a transaction, with the corresponding signature and data. There is a set of different transaction and each of these transactions has an specific validation and execution logic
changed as suggested and added a link to accounts section for clarity

2020-09-25 15:34 UTC, janhack approved these changes
Looks all good.

2020-09-26 07:06 UTC, shuse2 approved these changes

2020-09-29 07:13 UTC, merged