Restructure mgmt guides from Core docs 2.0.0 to SDK docs - closes #731
LiskArchive/lisk-legacy-docs pull request #745
Opened 2020-09-21 12:31 UTC by chris529

Which content is outdated?
The content in the management guides is partly redundant with the guides in the SDK docs.

What should be the new content?
Update the Lisk Core documentation (e.g. add references to the Lisk SDK documentation) so that only Lisk Core specific topics are being covered in it.

For the general guides, refer to the Lisk SDK docs.

2020-09-23 08:12 UTC, Tschakki requested changes

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:page-no-previous: true
Duplicate line, please remove

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:page-aliases: troubleshooting.adoc
Why is `getting-started.adoc` being removed?

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:page-aliases: migration.adoc
Please remove these lines, no change in page aliases needed here.

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +How to rebuild from a snapshot and to create your own snapshots is explained in the administration section for each xref:{}[distribution] of the Lisk Core.
A link attribute is missing here

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +- To have the option to xref:{url_config_forging}[forge] new blocks, (assuming you are an active delegate)
```suggestion
- To have the option to xref:{url_config_forging}[forge] new blocks, (assuming you are an active delegate).
```

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:url_api: reference/api.adoc
The old link for `url_api` was correct, please restore.

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:url_config_api_access: {v_sdk}@lisk-sdk::guide/node-management/api-access.adoc
```suggestion
:url_config_api_access: {v_sdk}@lisk-sdk::guides/node-management/api-access.adoc
```

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/migration.adoc
> +:v_sdk: master
No need to add this

2020-09-23 08:12 UTC, Tschakki commented on modules/ROOT/pages/update/source.adoc
> +:v_sdk: master
No need to add this here.

2020-09-23 09:50 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:page-aliases: troubleshooting.adoc
Ah yes...this was an error, have now fixed it.

2020-09-23 09:52 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +:page-aliases: migration.adoc
Done 👍

2020-09-23 09:57 UTC, chris529 commented on modules/ROOT/pages/index.adoc
> +How to rebuild from a snapshot and to create your own snapshots is explained in the administration section for each xref:{}[distribution] of the Lisk Core.
Yes, indeed..It should be fixed now.

2020-09-23 10:04 UTC, chris529 commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:url_api: reference/api.adoc
OK it should be fine now 👍

2020-09-23 10:06 UTC, chris529 commented on modules/ROOT/pages/migration.adoc
> +:v_sdk: master
Yes, indeed this was an error as there is no reference to the SDK here. It is now removed 👍

2020-09-23 10:07 UTC, chris529 commented on modules/ROOT/pages/update/source.adoc
> +:v_sdk: master
Same error as above..now corrected 👍

2020-09-25 11:54 UTC, Tschakki approved these changes
LGTM

2020-09-25 11:55 UTC, merged