Revisit page meta descriptions in core docs - Closes #738
LiskArchive/lisk-legacy-docs pull request #753
Opened 2020-09-28 14:28 UTC by chris529

Some meta descriptions of pages in the documentation need to be updated to improve the SEO value.

[] Core docs 2.1.6
[] SDK docs 3.02

Closes #738

2020-10-09 08:35 UTC, Tschakki requested changes
I am just going through the meta descriptions PR, and I think it would be better style, if we rephrase the descriptions to not use the term (on) this page, so e.g. `How to check, enable and disable forging on a Lisk node is described on this page.` should be `How to check, enable and disable forging on a Lisk node.`

and also descriptions like this `Covers all Docker image commands relevant to manage Lisk Core with a Docker image.` should be `All Docker image commands relevant to manage Lisk Core with a Docker image.`

2020-11-09 13:46 UTC, Tschakki requested changes

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +:description: The Lisk Core introduction describes the different networks, distributions and technology stack of Lisk Core.
I think for the introduction/overview pages, it would be good to refer to the general description of the product documentation, e.g. 
```suggestion
:description: References and guides how to setup, update and manage a Lisk Core node.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/interact-with-the-api.adoc
> +:description: The "Interact with the network" section covers interacting with applications such as Lisk Desktop & Lisk Explorer.
```suggestion
:description: How to interact with applications such as Lisk Desktop & Lisk Explorer via the Lisk Core API.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/management/commander.adoc
> +:description: All Lisk Commander application commands to manage Lisk Core via the command-line.
```suggestion
:description: A reference of all Lisk Commander application commands to manage Lisk Core via the command-line.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +:description: All config file handling including the configuration of Lisk Core.
```suggestion
:description: How to configure Lisk Core.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/management/docker.adoc
> +:description: All Docker image commands relevant to manage Lisk Core with a Docker image.
```suggestion
:description: How to manage Lisk Core with Docker.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +:description: Links for the guides and references required for the management of Lisk Core.
```suggestion
:description: How to manage Lisk Core. Includes command references for the different Lisk Core distributions and general management related guides, like how to enable forging, or how to control the API access of a Lisk Core node.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/management/source.adoc
> +:description: The Source code commands cover all relevant commands required to manage Lisk Core with pm2.
```suggestion
:description: Covers all relevant commands required to manage Lisk Core from Source with pm2.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/reference/api.adoc
> +:description: The API endpoints of connected nodes are described, including how to send requests to a node and receive live responses.
```suggestion
:description: The API endpoints of Lisk Core nodes connected to the Betanet are covered here, including sending requests and receiving live responses..
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/reference/api-mainnet.adoc
> +:description: The Lisk Core API endpoints of Lisk Core nodes connected to the Mainnet are covered here, including sending requests and receiving live responses.
```suggestion
:description: The API endpoints of Lisk Core nodes connected to the Mainnet are covered here, including sending requests and receiving live responses.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/reference/config.adoc
> +:description: The Lisk Core configuration covers the command line, env variables and configuration options.
```suggestion
:description: Covers the different configuration options of Lisk Core, including env variables.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
> +:description: The Lisk Core Application setup describes all requirements and dependencies to install the Lisk SDK.
```suggestion
:description: Describes all requirements and dependencies to install Lisk Core.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/setup/commander.adoc
> +:description: The Lisk Core Commander application setup describes all options including pre-install, install & post-install to manage your Lisk Core node.
```suggestion
:description: Describes all requirements and dependencies to setup a Lisk Core node with Lisk Commander.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/setup/docker.adoc
> +:description: The Lisk Core Docker image setup describes how to install the Lisk SDK with Docker, the configuration & makefile & setting environment variables.
```suggestion
:description: Describes all requirements and dependencies to install Lisk Core with Docker.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/setup/index.adoc
> +:description: The Set up provides an overview of the prerequisites required for setting up a node.
```suggestion
:description: How to install and setup up a Lisk Core node.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +:description: The Lisk Core Source code setup covers how to perform the installation, including the toolchain components, PostgreSQL, PM2 & Redis.
```suggestion
:description: Describes all requirements and dependencies to install Lisk Core from Source.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/update/application.adoc
> +:description: The Lisk Core application update describes how to upgrade Lisk Core to the latest version.
```suggestion
:description: How to upgrade Lisk Core to the latest version.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/update/commander.adoc
> +:description: How to upgrade Lisk Core to the latest version via Lisk Commander application.
```suggestion
:description: How to upgrade Lisk Core to the latest version via Lisk Commander.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/update/docker.adoc
> +:description: The Docker image information covers how to upgrade Lisk Core with Docker compose.
```suggestion
:description: How to upgrade Lisk Core with Docker.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/update/index.adoc
> +:description: The Update provides a brief overview with the associated links for updating all Lisk Core installations.
```suggestion
:description: How to upgrade Lisk Core to the latest version.
```

2020-11-09 13:46 UTC, Tschakki commented on modules/ROOT/pages/update/source.adoc
> +:description: How to use the Lisk Core Source code to update Lisk Core to the latest version from source.
```suggestion
:description: How to upgrade Lisk Core from source.
```

2020-11-09 14:18 UTC, chris529 commented on modules/ROOT/pages/management/index.adoc
> +:description: Links for the guides and references required for the management of Lisk Core.
We should keep the meta descriptions below 160 characters, so as this one is a bit long, I would suggest we re-word it the following "How to manage Lisk Core & the different Lisk Core distributions, management guides, enabling forging, & how to control the API access of a Lisk Core node''

2020-11-12 10:39 UTC, Tschakki approved these changes
Looking good, thanks!

2020-11-12 10:39 UTC, Tschakki commented on modules/ROOT/pages/management/index.adoc
> +:description: Links for the guides and references required for the management of Lisk Core.
sounds good for me 👍

2020-11-16 15:56 UTC, merged