Jan protocol docs update on chain architecture
LiskArchive/lisk-legacy-docs pull request #757
Opened 2020-09-29 10:11 UTC by janhack

Update the introduction, blocks, consensus and network section with respect to the following:

- On-chain architecture changes, removal of transaction types and introduction of the module concept.
- New transaction terminology.
- Minor formulation improvements.

Closes #752

2020-09-29 13:21 UTC, IkerAlus commented on modules/ROOT/pages/index.adoc
> +The Lisk SDK contains four default modules: token, sequence, keys, and dpos.
I think it is ok to explain this point here and in transactions section. However I suggest to follow here the same format (i.e., `token`) as in the transaction section.

2020-09-29 13:27 UTC, IkerAlus commented on modules/ROOT/pages/consensus-algorithm.adoc
> +:url_blocks_genesis: blocks.adoc#genesis_block
the right link handle is `blocks.adoc#genesis-block`

2020-09-29 13:28 UTC, IkerAlus requested changes
Apart from the minor format fixes, the rest LGTM.

Also, a little detail in the block.png diagram, for consistency the transaction object should be updated to the new version (`asset: Bytes`)

2020-10-06 19:25 UTC, janhack commented on modules/ROOT/pages/index.adoc
> +The Lisk SDK contains four default modules: token, sequence, keys, and dpos.
I am not sure about the suitable typesetting. On the one hand "token" is the actual string name of the module in the code, on the other hand we also don't use monospace when we write "transfer transaction", even though transfer was the string name of the base asset (now the name is token transfer transaction though). If I write "... is defined in the token module", I am not sure if monospace is nice.

2020-10-06 19:48 UTC, janhack commented on modules/ROOT/pages/consensus-algorithm.adoc
> +:url_blocks_genesis: blocks.adoc#genesis_block
Good catch. I fixed it.

2020-10-07 10:29 UTC, IkerAlus approved these changes
LGTM

2020-10-07 10:45 UTC, merged