Overall review of SDK docs 4.0.0 - closes #760
LiskArchive/lisk-legacy-docs pull request #761
Opened 2020-10-02 14:01 UTC by chris529

2020-10-26 15:02 UTC, Tschakki requested changes

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/broadcast.adoc
> +Before any transaction can be sent to the network, it is required for the account sender to sign the transaction object.
```suggestion
Before any transaction can be sent to the network, it is required for the sender account to sign the transaction object.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/launch.adoc
> +These servers have a <<node_app,node application>> installed that handles all communication between other nodes in the network.
```suggestion
These servers have a <<node_app,node application>> installed that handles all communication to other nodes in the network.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/launch.adoc
> +When setting up a new node, each new node will initially connect to the seed nodes when bootstrapping for the first time.
```suggestion
When setting up a new node, each new node will initially connect to the seed nodes when it starts for the first time.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/api-access.adoc
> +For optimal security, disable all access settings `modules.http_api.enabled` to `false`.
```suggestion
For optimal security, disable all access by setting `modules.http_api.enabled` to `false`.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +For more information about forging, please see the xref:{url_explanations_consensus}[Forging] section in the Concensus in Lisk page.
Duplicated sentence

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +To enable your node to forge for a particular delegate, firstly it is required to insert some data into the config file under the `chain.forging.delegates` array as described below:
```suggestion
To enable your node to forge for a particular delegate, firstly it is required to insert some data into the config file under the `forging.delegates` array as described below:
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The following diagram below provides a high level overview of the architecture:
```suggestion
The following diagram provides a high level overview of the architecture:
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +Installation of the Lisk Alpha SDK is straightforward and only requires adding a single NPM package `lisk-sdk`, to your Node.js project as shown below:
```suggestion
Installation of the Lisk Alpha SDK is straightforward and only requires adding a single NPM package `lisk-sdk` to your Node.js project as shown below:
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The xref:{url_tutorials}[Tutorial] guides explains in detail how to build a specific blockchain application.
```suggestion
The xref:{url_tutorials}[Tutorial] guides explain in detail how to build a specific blockchain application.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/api-specification.adoc
>  :v_core: 3.0.0
This is autogenerated content from swagger. Please revert all changes made here.

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +For Multisignature registration transaction, `signatures` also contain additional signatures corresponding to the public keys participating in the multisignature account.
```suggestion
For Multisignature registration transaction, `signatures` also contains additional signatures corresponding to the public keys participating in the multisignature account.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +This can be used to validate that the private key belongs to the owner, however it does not provide access to the owners private key. +
Everything below here is autogenerated content from swagger, so it should not be changed

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +This returns a randomly-generated mnemonic passphrase with its corresponding public/private key pair and Lisk address as shown in the code snippet below:
I am concerned to add here everywhere the phrase ` as shown in the code snippet below` over and over again - this should be very clear from the context, no need to mention it all the time. Imho it makes the sentences just longer, and harder to scan / filter the actual information.

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +When the `api.nodes` are empty, the Lisk Commander will connect to the official Lisk seed nodes depending on the network specified in the `api.network`.
```suggestion
When `api.nodes` is empty, the Lisk Commander will connect to the official Lisk seed nodes depending on the network specified in `api.network`.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +If the `api.nodes` are set to one or more multiple nodes, the Lisk Commander will ignore the `api.network` and will make all requests to the specified Lisk node.
```suggestion
If `api.nodes` is set to one or more multiple nodes, the Lisk Commander will ignore `api.network` and will make all requests to the specified Lisk node.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +The 'gets delegate' information from the blockchain can be seen in the code snippet below:
This sounds weird. Maybe this is better:

```suggestion
How to get delegate information from the blockchain.	
```

Please fix the other occurrences as well.

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/lisk-core-commands.adoc
> +Upgrade an instance of Lisk Core (Binary), to a specified or latest version.
```suggestion
Upgrade an instance of Lisk Core, to a specified or latest version.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +In order to  add a Lisk Client as a dependency of your project, execute the following command below:
I would keep it short like it was before.
```suggestion
This adds the Lisk API client as a dependency to your project:
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +To upgrade Lisk Client, execute the following command below:
```suggestion
To upgrade the Lisk API client, execute the following command below:
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +Not applicable.
```suggestion
None.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +Not applicable.
```suggestion
None.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +Not applicable.
```suggestion
None.
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/api-client/accounts.adoc
> +This is a resource for interacting with the `accounts` endpoint provided by the Lisk public API. Each of the following methods listed here can be accessed via the `accounts` property of an `APIClient
Isn't it kind of double to say `following methods listed here`?
The `following` already implies it is below for me.

Please fix the occurrences on the other pages as well.

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/client.adoc
> +To import using the ES6 modules syntax, execute the following command below:
```suggestion
How to import `lisk-client` using the ES6 modules syntax:
```

Please fix the occurrences on the other pages accordingly.

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +*Complete library*:
```suggestion
*Complete library:*
```

Please fix also the other occurences below alike.

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/index.adoc
> +`LISK_CHILD_PROCESS_MODULES=httpApi,chain`.
```suggestion
Multiple modules can be defined by using commas: `LISK_CHILD_PROCESS_MODULES=httpApi,chain`
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/index.adoc
> +Configuration options are located in the following:
```suggestion
Configuration options are located in:
```

2020-10-26 15:02 UTC, Tschakki commented on modules/ROOT/pages/tutorials/index.adoc
> +| xref:tutor/tutorials/hello-world.adoc[Hello World]
```suggestion
| xref:{{url_tutor}}[Hello World]
```

2020-10-27 12:52 UTC, chris529 commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +This returns a randomly-generated mnemonic passphrase with its corresponding public/private key pair and Lisk address as shown in the code snippet below:
As agreed, I have removed all instances of ''code snippet below'' 👍

2020-10-27 13:50 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/api-client/accounts.adoc
> +This is a resource for interacting with the `accounts` endpoint provided by the Lisk public API. Each of the following methods listed here can be accessed via the `accounts` property of an `APIClient
Agreed, I have now already made the changes 👍

2020-10-27 15:27 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/client.adoc
> +To import using the ES6 modules syntax, execute the following command below:
All should now be updated 👍

2020-10-28 08:14 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/index.adoc
> +*Complete library*:
Done 👍

2020-10-28 08:15 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +For more information about forging, please see the xref:{url_explanations_consensus}[Forging] section in the Concensus in Lisk page.
Now removed 👍

2020-10-28 09:36 UTC, chris529 commented on modules/ROOT/pages/references/api-specification.adoc
>  :v_core: 3.0.0
Reverted, and made some text updates 👍

2020-11-10 09:59 UTC, Tschakki requested changes
Overall looking good, just a few minor points!

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/launch.adoc
> +The default options for modules are as follows: +
```suggestion
The default options for modules are located in: +
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/launch.adoc
> +The default options for components are as follows: +
```suggestion
The default options for components are located in: +
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/api-access.adoc
> +<5> This parameter allows connections to the API by IP. The defaults are to only allow a local host.
```suggestion
<5> This parameter allows connections to the API by IP. The default is to only allow a local host.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/logging.adoc
> +All logs that have equal or higher log levels than in the `config.json` are saved in a `.log`-file for further analysis.
```suggestion
All logs that have equal or higher log levels than in the log level specified in the config are saved in a `.log`-file for further analysis.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +The xref:{url_tutorials}[Tutorial] guides explain in detail how to build a specific blockchain application.
```suggestion
The xref:{url_tutorials}[Tutorials] explain in detail how to build a specific blockchain application.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +Once the account is registered as a multisignature account, every outgoing transaction requires as signature for every public key in `mandatoryKeys`.
```suggestion
Once the account is registered as a multisignature account, every outgoing transaction requires a signature for every public key in `mandatoryKeys`.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/references/changelog.adoc
> +New accounts always always with a nonce equal to 0.
```suggestion
New accounts always start with a nonce equal to 0.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +This command displays the Network identifier based on the payloadhash of the xref:{url_guides_config_genesis_block}[genesis block] of the network.
```suggestion
This command displays the network identifier based on the payload hash of the xref:{url_guides_config_genesis_block}[genesis block] of the network.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +The Network identifier needs to be provided everytime a transaction is signed, which ensures that the transaction can only be broadcast in the dedicated network.
```suggestion
The network identifier needs to be provided every time a transaction is signed, which ensures that the transaction can only be broadcast in the dedicated network.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/cryptography.adoc
> +`secondPassphrase`: The optional second secret passphrase required to sign the message.
```suggestion
`secondPassphrase`: The optional second secret passphrase to sign the message.
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/index.adoc
> +This is used to subscribe to events occurring on the controller as shown below:
Here and in the lines below, there are still a lot of ` as shown below` statements. Please remove them all.
```suggestion
How to subscribe to events occurring on the controller:
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/setup.adoc
> +To connect to the desired network with Lisk Core, ensure that the corresponding ports are open:
```suggestion
To connect to the desired network, ensure that the corresponding ports are open:
```

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/setup.adoc
> +For more information, see the diagram on the xref:{url_core_network}[Interact with the API] page.
Please remove this complete line.

2020-11-10 09:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/index.adoc
>  | xref:tutorials/supply-chain/index.adoc[Supply Chain]
```suggestion
| xref:{url_tutorials}[Supply Chain]
```

2020-11-10 15:45 UTC, chris529 commented on modules/ROOT/pages/setup.adoc
> +For more information, see the diagram on the xref:{url_core_network}[Interact with the API] page.
Ok, it is done 👍

2020-11-10 16:30 UTC, Tschakki approved these changes
Thank you!

2020-11-10 16:33 UTC, merged