Update Lisk Elements packages reference - Closes #770
LiskArchive/lisk-legacy-docs pull request #790
Opened 2020-11-17 16:44 UTC by Tschakki

Closes #770

2020-11-23 11:35 UTC, ishantiw requested changes
Some interfaces are missing comparing to latest sdk v5 and some improvement in descriptions

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +const { createIPCClient, createWSClient } from '@liskhq/lisk-transactions';
```suggestion
const { createIPCClient, createWSClient } from '@liskhq/lisk-api-client';
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +client = await createWSClient('ws://localhost:8080');
```suggestion
client = await createWSClient('ws://localhost:8080/ws');
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +    decode: (input: Buffer) => Record<string, unknown>;
```suggestion
    decode: (input: Buffer) => Record<string, unknown>;
    toJSON(account: Record<string, unknown>) => Record<string, unknown>;
    fromJSON(account: Record<string, unknown>) => Record<string, unknown>;
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +    decode: (input: Buffer) => Record<string, unknown>;
```suggestion
    decode: (input: Buffer) => Record<string, unknown>;
    toJSON(
		block: BlockType,
	) => {
		header: Record<string, unknown>;
		payload: Record<string, unknown>[];
	};
	fromJSON(
		block: BlockType<string>,
	) => {
		header: Record<string, unknown>;
		payload: Record<string, unknown>[];
	};
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +    decode: (input: Buffer) => Record<string, unknown>;
```suggestion
    decode: (input: Buffer) => Record<string, unknown>;
    toJSON(transaction: Record<string, unknown>) => Record<string, unknown>;
    fromJSON(transaction: Record<string, unknown>) => Record<string, unknown>;
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/api-client.adoc
> +interface APIClient {
Missing,
`public disconnect() => Promise<void>;`

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +== Usage
Do we need `Interface` section here?

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +The P2P part is the main entry point of the P2P library that manages PeerPool, PeerBook and PeerServer.
```suggestion
The P2P class is the main entry point of the P2P library that manages PeerPool, PeerBook and PeerServer.
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +* Expose actions and emit events bubbling up from  Peer, PeerPool and PeerServer.
```suggestion
* Expose actions and emit events bubbling up from Peer, PeerPool and PeerServer.
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +* Manage CRUD operations on PeerBook that holds and manages all the peerInfo.
```suggestion
* Manage CRUD operations on PeerBook that holds and manages all the peerInfos of all known peers.
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +* Load  previous peers and start the discovery through all the seed peers, if not many triedPeers (see section PeerBook).
```suggestion
* Loads previous peers and does the discovery, in case, if it doesn't have at least 100 triedPeers then it starts the discovery through seed peers provided in the config.
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +* Emit all events.
```suggestion
* Emit all the peer related events including the ones coming from the network.
```

2020-11-23 11:35 UTC, ishantiw commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +It consists of  a list of 128 buckets with each bucket having 32 peers.
```suggestion
It consists of a list of 128 buckets with each bucket having 32 peers.
```

2020-11-23 16:50 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/genesis.adoc
> +== Usage
Hmm not sure, I created one now, as I didnt find it in the docs, can you check if it correct?

2020-11-24 16:08 UTC, ishantiw approved these changes
LGTM

2020-11-24 16:57 UTC, merged