Update Core docs to 3.0.0-beta.2 - Closes #800
LiskArchive/lisk-legacy-docs pull request #801
Opened 2020-11-25 08:51 UTC by Tschakki

Closes #800

2020-11-25 15:03 UTC, ManuGowda reviewed
Overall LGTM
- update node.js version everywhere to `12.20.0`
- the lisk core version to 3.0.0-beta.2

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/index.adoc
> +//It is possible to view the live network statistics by accessing the following URL: {url_explorer}[Lisk’s Blockchain Explorer^].
will this be published to public? todo looks weird in public maybe

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/index.adoc
> +- To create create transactions and send them to the network.
```suggestion
- To create transactions and send them to the network.
```

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/management/account-management.adoc
> +NOTE: The Lisk Core node needs to run in order to create transactions.
i guess this is not true? you could create trx offline as well

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/management/account-management.adoc
> +=== Broadcasting transactions to the network
this is only broadcasting the transaction to local node? we can broadcast to network

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/management/configuration.adoc
> +<1> `NETWORK` may be `devnet` or `betanet`.
maybe include only the public network? betanet, testnet, mainnet?

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/management/forging.adoc
> +CAUTION: When you enable forging as a delegate on a new node, you need to use the exact same hash onion in the config as on the old node, to enable forging successfully.
```suggestion
CAUTION: When you enable forging as a delegate on a new node, you need to use the exact same hash onion in the config as on the old node, to enable forging successfully. If you lose the hash onions, you could generate a new hash onion config and use it, but you will loose the first block reward.
```

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/management/forging.adoc
> +curl http://127.0.0.1:4000/api/node/status
```suggestion
curl http://127.0.0.1:4000/api/node/info
```

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/management/index.adoc
> +    "LISK_PORT": 5000
```suggestion
    "LISK_PORT": 8000
```

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/reference/config.adoc
> +  lisk-core/3.0.0-beta.2.5 darwin-x64 node-v12.18.4
probably this should be updated to `3.0.0-beta.2` once released?

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/setup/application.adoc
> +wget https://downloads.lisk.io/mainnet/xxx.tar.gz
i am not sure about this, please check with francios once

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/setup/source.adoc
> +nvm install 12.19.1
```suggestion
nvm install 12.20.0
```

2020-11-25 15:03 UTC, ManuGowda commented on modules/ROOT/pages/setup/source.adoc
> +brew install node@12.19.1
```suggestion
brew install node@12.20.0
```

2020-11-25 15:34 UTC, Tschakki commented on modules/ROOT/pages/index.adoc
> +//It is possible to view the live network statistics by accessing the following URL: {url_explorer}[Lisk’s Blockchain Explorer^].
yes, it should be a comment

2020-11-25 15:36 UTC, Tschakki commented on modules/ROOT/pages/management/configuration.adoc
> +<1> `NETWORK` may be `devnet` or `betanet`.
testnet and mainnet might be confusing, because they wont work with this release, yet. So I would better not mention them here yet.

2020-11-25 15:42 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +NOTE: The Lisk Core node needs to run in order to create transactions.
true, if you set the `--offline` flag, it also works without running node 👍

2020-11-25 15:48 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +=== Broadcasting transactions to the network
Yes it is posting to local node. To which other node should it post? And how to do it?

2020-11-25 15:52 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +NOTE: The Lisk Core node needs to run in order to create transactions.
I updated the note, please check again. For the below example to work, the node should run in order to successfully sign the tx.

2020-11-26 08:37 UTC, ManuGowda commented on modules/ROOT/pages/management/account-management.adoc
> +=== Broadcasting transactions to the network
sorry my english was wrong, what i meant to say was, we can only broadcast to local node, we can not broadcast to other nodes. So `Broadcasting transactions to the network` statement can be misleading?

2020-11-26 08:38 UTC, ManuGowda approved these changes, later dismissed

2020-11-26 10:50 UTC, Tschakki commented on modules/ROOT/pages/management/account-management.adoc
> +=== Broadcasting transactions to the network
well, as the node is connected to the network, it is kind of the same, but I get your point :) Will rename it

2020-11-26 11:11 UTC, Tschakki commented on modules/ROOT/pages/setup/application.adoc
> +wget https://downloads.lisk.io/mainnet/xxx.tar.gz
Updated 👍

2020-11-26 17:22 UTC, shuse2 requested changes
https://liskhq.github.io/lisk-docs/lisk-core/v3/reference/api.html
is outdated, but that will be out of scope right?
Also, it would be nice to have explanation about `--api-ws` too and how it should protected (but maybe we can omit from initial version

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/index.adoc
>  | HTTP port | 8000 | 7000 | 5000
there is no http port. I think we can simply remove them since it's not relevant anymore

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/partials/core-ports.adoc
> +To connect to the desired network with Lisk Core, please ensure that the corresponding ports listed below are open.
just so u know, those are `default` ports. User can change to any port they want, and that port just needs to be opened.
Also, after v3, default http port for all network is the same, and configurable when starting the node

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/setup/application.adoc
> +lisk-core start
this only works after we release to `mainnet`.
We should probably say
```
lisk-core start --network betanet
```
for now

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/setup/npm.adoc
> +nvm install 12.19.1
now we use `12.20.0`

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/setup/npm.adoc
> +lisk-core start
same here `--network` must be specified until we release to `mainnet`

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/setup/source.adoc
>  npm install pm2 -g
it would be nice to have how to manage node section using `pm2` for example in general (not only source)

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/setup/source.adoc
> +./bin/run start --network devnet
i need to check, but from source installation, we can do
```
npm install --global
```
at the end of the step, so that management will be exactly same for all the installation

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/management/index.adoc
> +pm2 start lisk-core start --enable-ipc --name 'lisk-core'
```suggestion
pm2 start "lisk-core start --network betanet --api-ipc"--name 'lisk-core'
```

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/management/forging.adoc
> +  modules: {
module config is outdated, if it's not required here we can just simply remove it

2020-11-26 17:22 UTC, shuse2 commented on modules/ROOT/pages/management/forging.adoc
> +curl http://127.0.0.1:4000/api/node/info
instead of calling HTTP API, we can do
```
lisk-core node:info
```
which will work even if http api is not enabled

2020-11-27 09:01 UTC, Tschakki commented on modules/ROOT/partials/core-ports.adoc
> +To connect to the desired network with Lisk Core, please ensure that the corresponding ports listed below are open.
In this case, I will remove this partial from the setup pages for now.

2020-11-27 09:02 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
>  npm install pm2 -g
This is explained on the management index page, no?

2020-11-27 09:04 UTC, Tschakki commented on modules/ROOT/pages/setup/source.adoc
> +./bin/run start --network devnet
Can you check? Also, is it still needed to run `npm ci`, or is `npm i` enough?

2020-11-27 11:35 UTC, Tschakki commented
@shuse2 I now updated the URL for the API reference to https://betanet5.lisk.io/api/spec.
Can you verify that `api/spec` will stay the correct path for the swagger specification?

2020-11-27 16:30 UTC, shuse2 commented on modules/ROOT/pages/setup/source.adoc
>  npm install pm2 -g
it is explained in the management, then why only source installation has this point?

2020-11-27 16:40 UTC, shuse2 commented on modules/ROOT/pages/setup/source.adoc
> +./bin/run start --network devnet
```
npm install --global 
```
works!

2020-11-30 09:50 UTC, merged