Update meta descriptions in SDK docs v5 - Closes #828
LiskArchive/lisk-legacy-docs pull request #829
Opened 2020-12-04 14:15 UTC by chris529

Closes #828

2020-12-09 09:21 UTC, Tschakki requested changes
A lot of the pages. you reviewed were pages that are not part of the SDKv5 docs yet, so the pages have not been updated yet. No point of updating the meta descriptions there.

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/architecture/communication-architecture.adoc
> +:description: The Communication Architecture covers the action & events interfaces, API client, invoking actions & application actions & events.
```suggestion
:description: Covers the action & events interfaces and explains how the different components of the Lisk SDK communicate via channels.
```

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/architecture/index.adoc
> +:description: The Lisk Framework architecture overview covers the on & off chain architecture, registering modules, configuration & the genesis block.
```suggestion
:description: Provides an overview of the Lisk SDK architecture, including on-chain, off-chain and the communication architecture.
```

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/architecture/off-chain-architecture.adoc
> +:description: The off-chain architecture covers how to create a plug in, including custom, timesamp, and default plug ins.
```suggestion
:description: Explains what are plugins and how to create and use them in a blockchain application.
```

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/architecture/on-chain-architecture.adoc
> +:description: The on-chain architecture covers modules, custom assests and examples, together with the SDK default modules.
```suggestion
:description: Explains what are modules and how to create and use them in a blockchain application.
```

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/index.adoc
> +:description: The Lisk Framework overview covers its modules and components including the BaseModule, the BaseAsset, and the BasePlugin.
```suggestion
:description: Covers references of the Lisk Framework, like the BaseModule, the BaseAsset and the BasePlugin. 
```

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/tutorials/hello-world.adoc
> +:description: The Hello World implementation, including the blockcahin & client application, setup, modules, components & transactions are covered here.
```suggestion
:description: How to create a simple blockchain application including a react frontend.
```

2020-12-09 09:21 UTC, Tschakki commented on modules/ROOT/pages/tutorials/index.adoc
> +:description: The SDK Tutorials overview gives a summary of the Hello World app, including the complexity, estimated time required, and the content.
```suggestion
:description: The SDK Tutorials overview gives a summary of all available tutorials, including the complexity, estimated time required, and the content.
```

Please use general descriptions of the page, so we don't need to update it too often int he future.

2020-12-09 09:51 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +:description: The SDK Tutorials overview gives a summary of the Hello World app, including the complexity, estimated time required, and the content.
OK, good point.

2020-12-11 16:14 UTC, Tschakki requested changes

2020-12-11 16:14 UTC, Tschakki commented on modules/ROOT/pages/architecture/communication-architecture.adoc
> +:description: Covers the action & events interfaces and explains how the different components of the Lisk SDK communicate via channels.
```suggestion
:description: Introduces the Lisk communication architecture, which is based on IPC Unix Sockets and WebSocket.
```

action and events interfaces will be moved to rpc endpoints page as discussed

2020-12-11 16:14 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +:description: How to configure a blockchain application together with all the config options, constants and genesis block.
```suggestion
:description: How to configure a blockchain application together with the most important config options and the genesis block.
```

2020-12-11 16:14 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/chain.adoc
> +:description: Technical references regarding the chain package pf Lisk Elements including updates, state store, & data access.
```suggestion
:description: Technical references regarding the chain package pf Lisk Elements including state store & data access.
```

2020-12-11 16:14 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/transactions.adoc
> +:description: Technical references regarding the transactions packages consisting of usage examples, available options and example responses.
```suggestion
:description: Technical references regarding the transactions package consisting of usage examples, available options and example responses.
```

2020-12-11 16:18 UTC, chris529 commented on modules/ROOT/pages/architecture/communication-architecture.adoc
> +:description: Covers the action & events interfaces and explains how the different components of the Lisk SDK communicate via channels.
👍

2020-12-16 09:00 UTC, Tschakki requested changes

2020-12-16 09:00 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/chain.adoc
> +:description: Technical references regarding the chain package pf Lisk Elements including state store & data access.
```suggestion
:description: Technical references regarding the chain package of Lisk Elements including state store & data access.
```

2020-12-16 09:00 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/client.adoc
> +:description: Technical references for the client packages of Lisk Elements, including all sub-packages and general usage instructions.
```suggestion
:description: Technical references for the client package of Lisk Elements, including all sub-packages and general usage instructions.
```

2020-12-16 09:00 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/transaction-pool.adoc
> +:description: This section covers the installation, updates, constants, specifications and data structures for the Transaction pool library.
```suggestion
:description: This section covers the installation, updates, constants, specifications and data structures for the transaction pool package of Lisk Elements.
```

2020-12-16 15:30 UTC, Tschakki approved these changes

2020-12-16 15:31 UTC, merged