Add strong password note to passphrase encryption
LiskArchive/lisk-legacy-docs pull request #831
Opened 2020-12-08 08:24 UTC by IkerAlus

In the pages _forging.adoc_ and _cryptography.adoc_

2020-12-09 08:54 UTC, Tschakki requested changes
Maybe it would help to describe what is considered a strong password in this context. Or Add a link to a page, which is covering the topic.

2020-12-09 09:49 UTC, IkerAlus commented
> Maybe it would help to describe what is considered a strong password in this context. Or Add a link to a page, which is covering the topic.

I was planning to do so and link to [this wiki article](https://en.wikipedia.org/wiki/Password_strength) which has a very comprehensive description of the concept. But I did not see any external link in these pages so I thought maybe we prefer not to include those. If you think it is ok to have an external here I will add the mentioned link as suggested.

2020-12-09 11:46 UTC, Tschakki commented
Hmm the article is very general. It does not give me an answer what is secure in this regard. I think we should give concrete guidelines here to avoid confusion. For example if we expect to use the 12 word mnemonic for the password as well, we should mention it directly. We can still include this external link for reference. Generally, there are no places in docs where it's forbidden to add external links :)

2020-12-09 12:42 UTC, IkerAlus commented
The point here is that this is not a basic user level application where we can set strict rules, but a tool aimed to delegates and node operators. There should be not limitations or basic guidelines. If we wanted to be precise and complete regarding the password strength concept we would need to elaborate like in the wiki article, which is not the point of these doc pages. Moreover, that article has the precise guidelines for what we understand as a _strong password_ in the section "Guidelines for strong passwords". What we can do is reference to that exact section to avoid the reader to get lost in the bigger wiki article.

2020-12-16 09:10 UTC, Tschakki requested changes

2020-12-16 09:10 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Be sure to use a link:https://en.wikipedia.org/wiki/Password_strength#Guidelines_for_strong_passwords[strong password].
Please always use link attributes to insert links:
On top of the page under settings:

```
:url_wikipedia_password_strength: https://en.wikipedia.org/wiki/Password_strength#Guidelines_for_strong_passwords
```

Then use the attribute in the text.
```
Be sure to use a strong password.

See the {url_wikipedia_password_strength}[Guidelines for password strength^] at Wikipedia for reference. 
```

The caret at the end will open the link in a new tab.

2020-12-18 10:27 UTC, IkerAlus commented on modules/ROOT/pages/guides/node-management/forging.adoc
> +Be sure to use a link:https://en.wikipedia.org/wiki/Password_strength#Guidelines_for_strong_passwords[strong password].
added, thanks!

2020-12-18 13:45 UTC, Tschakki approved these changes
Thank you!

2020-12-18 14:08 UTC, merged