Add new page about rpc endpoints - Closes #838
LiskArchive/lisk-legacy-docs pull request #856
Opened 2020-12-10 12:16 UTC by Tschakki

Closes #838

2020-12-16 12:06 UTC, nazarhussain requested changes

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +    enabled: boolean,
I believe its `enable` not `enabled`

https://github.com/LiskHQ/lisk-sdk/blob/dd3f397d265fe5605dee2f3abf7d218b79234a6d/framework/src/schema/application_config_schema.ts#L342

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +.How action and event labels are constructed
```suggestion
.How action and event names are constructed
```

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/nav.adoc
> +* xref:rpc-endpoints.adoc[RPC endpoints]
I suggest it should go under `Reference`

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +TIP: To conveniently communicate with the API from a client application, use the xref:{url_references_elements_apiclient}[]
That package intended for NodeJS use. If one want to use from browser, he/she must use `@liskhq/lisk-client`. It would be nice to mention that here.

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +TIP: To conveniently communicate with the API from a client application, use the xref:{url_references_elements_apiclient}[]
Please move this TIP before warning message below. Otherwise it break flow of content.

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +        },
Is there a way to put inline scroll with maximum lines for this code block? otherwise the documentation page itself feels like infinite scroll.

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +----
Missing output... Please check the implemeation to specify some sample output here. 

https://github.com/LiskHQ/lisk-sdk/blob/dd3f397d265fe5605dee2f3abf7d218b79234a6d/framework/src/node/network/network.ts#L453

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +----
Same here.

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +////
This event also emits block information same as new block event.

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +----
This event emits the block at which the fork was detected.

2020-12-16 12:06 UTC, nazarhussain commented on modules/ROOT/pages/rpc-endpoints.adoc
> +////
This event emits the updated list of validators.

2020-12-16 14:55 UTC, Tschakki commented on modules/ROOT/pages/rpc-endpoints.adoc
> +        },
unfortunately antora uses asciidoc 1.x, which doesnt include the feature of collapsible content, I already checked. It comes with Asciidoc 2.x. But I guess it is OK as you have the side nav on the left to conveniently browse the content.

2020-12-16 15:02 UTC, Tschakki commented on modules/ROOT/pages/rpc-endpoints.adoc
> +----
Based on the code, it is really heard for me to create en example output here. I would like to leave this as todo for future iterations of the documentation, as there are other updates in the docs which have higher priority at the moment.

2020-12-16 15:02 UTC, Tschakki commented on modules/ROOT/pages/rpc-endpoints.adoc
> +----
Same here :)

2020-12-16 15:05 UTC, Tschakki commented on modules/ROOT/pages/rpc-endpoints.adoc
> +////
This example output will also be added later

2020-12-17 09:53 UTC, nazarhussain approved these changes

2020-12-17 09:54 UTC, Tschakki commented on modules/ROOT/pages/rpc-endpoints.adoc
> +----
Related issue: https://github.com/LiskHQ/lisk-docs/issues/870

2020-12-17 09:57 UTC, merged