Update guide 'Configuring a blockchain application`
LiskArchive/lisk-legacy-docs pull request #874
Opened 2020-12-17 13:55 UTC by Tschakki

Closes #872

2020-12-18 11:12 UTC, nazarhussain requested changes

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +    enabled: boolean,
```suggestion
    enable: boolean,
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +  // ipc defines IPC communication behavior
```suggestion
  // rpc defines communication behavior
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +    // In case of WS, this port used
```suggestion
    // In case of `mode` is set to `ws`, this port used
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +    // waitThreshold defines the maximum waiting time for the last block before forging on top
```suggestion
    // waitThreshold defines the extra waiting time for the last block before forging
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +    // fixedPeers defines peers which will always try to connect by outbound connections
```suggestion
    // fixedPeers defines peers which will always try to connect for outbound connections
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +    // Since all genesis config options will be passed, developer can add extra config specific for a module
```suggestion
    // Since all genesis config options will be passed to all modules, developer can add extra config specific for a module
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/architecture/index.adoc
> +    // Optional. Default: 15360
```suggestion
    // Optional. Default: 15360 (15kb)
```

2020-12-18 11:12 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +The application will use the default configuration options in case a config option is not specified.
```suggestion
It is not necessary to include all options that are included in the schema. The application will use the default configuration options in case a config option is not specified.
```

2020-12-18 13:29 UTC, nazarhussain requested changes

2020-12-18 13:29 UTC, nazarhussain commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +=== Most important configuration options
```suggestion
=== Important configuration options
```

2020-12-18 13:31 UTC, nazarhussain approved these changes, later dismissed

2020-12-18 14:27 UTC, chris529 reviewed
Looks very good, just a few minor points 👍

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +The application config object is passed to the `Application` and must follow the  configuration schema.
```suggestion
The application config object is passed to the `Application` and must follow the configuration schema.
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +    // force defines wether to use a default password and enable forging by default
```suggestion
    // force defines whether to use a default password and enable forging by default
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +    // whitelistedPeers defines peers which will always allow to connect to the node on inbound connections
```suggestion
    // whitelistedPeers defines peers that are always allowed to connect to the node on inbound connections
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +    // peerBanTime defines the length of banning in millisecond
```suggestion
    // peerBanTime defines the length of banning in milliseconds
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +    // maxPeerDiscoveryResponseLength defines a maximum peer information allowed for response of peer discovery
```suggestion
    // maxPeerDiscoveryResponseLength defines the maximum peer information allowed for the response of peer discovery
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +    // Since all genesis config options will be passed to all modules, developer can add extra config specific for a module
```suggestion
    // Since all genesis config options will be passed to all modules, the developer can add an extra config specific for a module
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +    // transactionExpiryTime defines timeout of the transaction in the pool in millisecond
```suggestion
    // transactionExpiryTime defines timeout of the transaction in the pool in milliseconds
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +  // pluginAlias is a variable name which is depending on the installed plugin
```suggestion
  // pluginAlias is a variable name that is dependant on the installed plugin
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +<1> Imports `Application`, `configDevnet`, `genesisBlockDevnet` and `utils` from the `lisk-sdk` package.
```suggestion
<1> Imports `Application`, `configDevnet`, `genesisBlockDevnet`, and `utils` from the `lisk-sdk` package.
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +Please see the xref:{url_rpc_endpoints}[] and xref:{}[url_architecture_communication] pages for mor information about the API access options.
```suggestion
Please see the xref:{url_rpc_endpoints}[] and xref:{}[url_architecture_communication] pages for more information about the API access options.
```

2020-12-18 14:27 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +When the application instance is created, the `Application` expects a configuration JSON object as first argument the xref:{url_architecture_genesis_block}[genesis block].
```suggestion
When the application instance is created, the `Application` expects a configuration JSON object as the first argument in the xref:{url_architecture_genesis_block}[genesis block].
```

2020-12-30 13:21 UTC, Tschakki commented on modules/ROOT/pages/architecture/index.adoc
> +    // maxPeerDiscoveryResponseLength defines a maximum peer information allowed for response of peer discovery
```suggestion
    // maxPeerDiscoveryResponseLength defines a maximum length for the peer information response of peer discovery
```

2020-12-31 09:53 UTC, chris529 reviewed
Looks good, just a couple of minor points 👍

2020-12-31 09:53 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +When the application instance is created, the `Application` expects a configuration JSON object as second argument (first one is the genesis block).
```suggestion
When the application instance is created, the `Application` expects a configuration JSON object as the second argument, (the first one is the genesis block).
```

2020-12-31 09:53 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/configuration.adoc
> +You can use this genesis block, together with the `configDevnet` to quickstart your application with a preconfigured devnet.
```suggestion
This genesis block can be used together with the `configDevnet` to quickstart your application with a preconfigured devnet.
```

2020-12-31 10:15 UTC, chris529 approved these changes
LGTM!

2020-12-31 10:41 UTC, merged