Add custom module guide - Closes #881
LiskArchive/lisk-legacy-docs pull request #882
Opened 2020-12-31 14:38 UTC by Tschakki

Closes #881

2021-01-05 17:35 UTC, shuse2 requested changes

2021-01-05 17:35 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +DataType must be one of `string`, `bytes`, `boolean`, `uint32`, `sint32`, `uint64` or `sint64`.
this explanation should be separately explained and link to there? this encoding/decoding is not only related to account

2021-01-05 17:35 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +const { myAsset } = require('./my-asset.js');
```suggestion
const { MyAsset } = require('./my-asset.js');
```

2021-01-05 17:35 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +async beforeBlockApply(block, stateStore, reducerHandler) {
input is object here

2021-01-05 17:35 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +async afterBlockApply(block, stateStore, reducerHandler, consensus) {
saje as above

2021-01-05 17:35 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The data access is mainly used in the implementation of the actions to retrieve certain information from the blockchain.
```suggestion
The data access is only used in the implementation of the actions to retrieve certain information from the blockchain.
```

2021-01-05 17:35 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +
seems like there is empty block here?

2021-01-06 09:08 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +DataType must be one of `string`, `bytes`, `boolean`, `uint32`, `sint32`, `uint64` or `sint64`.
Fair point! Do you have a suggestion where the content should be moved to in the current structure? Or would it make sense to have a dedicated page for explaining schemas in the `references`?

2021-01-06 09:09 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +
I added now the file tree

2021-01-06 10:25 UTC, shuse2 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +DataType must be one of `string`, `bytes`, `boolean`, `uint32`, `sint32`, `uint64` or `sint64`.
I think it would make sense to have dedicated page

2021-01-06 13:26 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +DataType must be one of `string`, `bytes`, `boolean`, `uint32`, `sint32`, `uint64` or `sint64`.
I added now a new page to references, and added a link to it in the module guide, please check :)

2021-01-07 14:00 UTC, shuse2 requested changes

2021-01-07 14:00 UTC, shuse2 commented on modules/ROOT/pages/references/schemas.adoc
> +These data types are used to save the respective data in the *database*.
DataType is not related to the `Database`. It is defining the encoding method.
JavaScript Object is how decoded object is handled within the application.
JSON object ok, it is format used in actions and events

2021-01-07 14:08 UTC, Tschakki commented on modules/ROOT/pages/references/schemas.adoc
> +These data types are used to save the respective data in the *database*.
I removed one sentence. Does it make more sense now?

2021-01-08 08:47 UTC, chris529 reviewed
Looks good, just very small points 👍

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/architecture/on-chain-architecture.adoc
>  In addition, all of the logic implemented using a module / asset must be deterministic and executable within the block time.
```suggestion
In addition, all of the logic implemented using a module/asset must be deterministic and executable within the block time.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +This guide explains step-byb-step, how to create a custom module for a blockchain application built with the Lisk SDK.
```suggestion
This guide explains step-by-step, how to create a custom module for a blockchain application built with the Lisk SDK.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +* a basic blockchain application is already initiated, like explained in the previous guide xref:{url_guides_setup}[].
```suggestion
* a basic blockchain application is already initiated as explained in the previous guide xref:{url_guides_setup}[].
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +To follow this guide, the following is assumed:
```suggestion
To follow this guide, the following criteria is assumed:
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The ID is used for example to for creation of transactions of the module.
```suggestion
The ID is used for example in the creation of transactions of the module.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +For better overview, let's create a new file `schemas.js`, which will export the account schema for our new module:
```suggestion
To achieve a better overview, it is recommended to create a new file `schemas.js`, which will export the account schema for our new module:
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Assuming you have created an asset `myAsset` for the module, then it can be included like this:
```suggestion
Assuming an asset, `myAsset` has been created for the module, then it can be included as shown below:
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Each module allows to define certain reducers, actions and events, which provide the module with an interface, that allows other modules and plugins or external services to interact with the module.
```suggestion
Each module allows the user to define certain reducers, actions, and events which provide the module with an interface, that allows other modules and plugins or external services to interact with the module.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Plugins and external services an subscribe to these events with the API client.
```suggestion
Plugins and external services can subscribe to these events with the API client.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +A list of actions that plugins and external services can invoke  via the API client.
```suggestion
A list of actions that plugins and external services can invoke via the API client.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +What events, actions and reducers to create for a module, or if these interfaces are needed at all is individual for every module, as it heavily depends on which functionality the module intends to p
```suggestion
What events, actions, and reducers are used within the creation for a module, or even if these interfaces are actually required at all, will be a specific individual requirement for every module; as it is heavily dependant on which functionality the module intends to provide to the application.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The best way to understand what to provide here is to look at existing examples in the Lisk SDK default modules, or examples of other blockchain applications built with the Lisk SDK, for example the
```suggestion
The best way to understand the necessary requirements here is to look at existing examples in the Lisk SDK default modules, or examples of other blockchain applications built with the Lisk SDK, for example the xref:{url_tutorials_hello}[] application.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Code in here is applied before each transaction is applied.
```suggestion
The code here is applied before each transaction is applied.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Code in here is applied after each transaction is applied.
```suggestion
The code here is applied after each transaction is applied.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Code in here is applied after the genesis block is applied.
```suggestion
The code here is applied after the genesis block is applied.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Code in here is applied before each block is applied.
```suggestion
The code here is applied before each block is applied.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Code in here is applied after each block is applied.
```suggestion
The code here is applied after each block is applied.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The last thing needed to do is to register the newly created module in the application:
```suggestion
The final requirement is to register the newly created module in the application:
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The new module `MyModule` will now be available, the next time you start the application with `node index.js`.
```suggestion
The new module `MyModule` will now be available, the next time the application is started with `node index.js`.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +NOTE: All blockchain related data like blocks, transactions, account state and chain state are encoded using `@liskhq/lisk-codec`.
```suggestion
NOTE: All blockchain related data such as blocks, transactions, account state, and chain state are encoded using `@liskhq/lisk-codec`.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +Especially, schemas are used in:
```suggestion
Schemas are specifically used in the following:
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +* *modules* to define the `accountSchema`, which consists of module-specific properties, that are added to each account by the module.
```suggestion
* *modules* to define the `accountSchema`, which consists of module-specific properties that are added to each account by the module.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +* *assets*, for the `schema`, which is defines the data structure and formats of the transaction asset.
```suggestion
* *assets*, for the `schema`, which defines the data structure and formats of the transaction asset.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +* modules and/or assets, to *decode/encode* other specific data from the database, like blocks, transactions, account state and chain state data.
```suggestion
* modules and/or assets, to *decode/encode* other specific data from the database, such as blocks, transactions, account state, and chain state data.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +Schemas must be defined as the example below, which is a modified JSON schema.
```suggestion
Schemas must be defined as shown in the example below, which is a modified JSON schema.
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +When the data is retrieved from the database by a module or plugin of the blockchain application, it is returned as JavaScript object or JSON, depending on the context:
```suggestion
When the data is retrieved from the database by a module or plugin of the blockchain application, it is returned as a JavaScript object or JSON, depending on the context:
```

2021-01-08 08:47 UTC, chris529 commented on modules/ROOT/pages/references/schemas.adoc
> +This data types are used *internally* in the blockchain application to handle data from the database.
```suggestion
These data types are used *internally* in the blockchain application to handle data from the database.
```

2021-01-08 11:30 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The ID is used for example to for creation of transactions of the module.
```suggestion
The ID is used for example during the creation of transactions of the module.
```

2021-01-08 11:36 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +What events, actions and reducers to create for a module, or if these interfaces are needed at all is individual for every module, as it heavily depends on which functionality the module intends to p
```suggestion
What events, actions and reducers are used within a module, or if these interfaces are actually required at all , will be a specific individual requirement, as it is heavily dependant on which functionality the module intends to provide to the application.
```

2021-01-08 13:42 UTC, chris529 reviewed
Looks great, just 3 very minor points 👍

2021-01-08 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +The account schema defines which propeties are added to user accounts by the module.
```suggestion
The account schema defines which properties are added to user accounts by the module.
```

2021-01-08 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +Inside this new key, the module-specific properties for every account are saved.
```suggestion
The module-specific properties for every account are saved inside this key.
```

2021-01-08 13:42 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +== Adding an interface by providing reducers, actions and events
```suggestion
== Adding an interface by providing reducers, actions, and events
```

2021-01-08 14:04 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/module.adoc
> +== Adding an interface by providing reducers, actions and events
I don't think a comma here is correct.

2021-01-08 14:11 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/module.adoc
> +== Adding an interface by providing reducers, actions and events
Well, normally you would have a comma before 'and' in this type of sentence whereby one is describing 3 separate topics. However, it is certainly not critical. Let's leave it as you had it originally Mona, as this is your guide. (Which by the way looks excellent).

2021-01-08 14:14 UTC, chris529 approved these changes
LGTM!

2021-01-08 14:46 UTC, merged