Add new guide how to create a plugin - Closes #888
LiskArchive/lisk-legacy-docs pull request #894
Opened 2021-01-07 12:40 UTC by Tschakki

Closes #888

2021-01-12 13:59 UTC, mitsuaki-u requested changes

2021-01-12 13:59 UTC, mitsuaki-u commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +What properties should bbe added to the application config is defined in the `defaults()` getter.
```suggestion
What properties should be added to the application config is defined in the `defaults()` getter.
```

2021-01-12 13:59 UTC, mitsuaki-u commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +What properties should bbe added to the application config is defined in the `defaults()` getter.
The wording for this sentence seems off

2021-01-12 13:59 UTC, mitsuaki-u commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +For a better overview, create a new file `defaults.js` and define the schema for the configuration options here like in the example below:
```suggestion
For a better overview, create a new file `defaults.js` and define the schema for the configuration options here as in the example below:
```

2021-01-12 13:59 UTC, mitsuaki-u commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +Next, the block is decoded and the timestamp of the block is pushed into the `_knownTimestamps` array.
what is the purpose of `_knownTimestamps`?

2021-01-12 13:59 UTC, mitsuaki-u commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +
The purpose of this example plugin is a little bit confusing. It is storing the latest delegate and also storing the timestamps for each new block. Are they related somehow?

2021-01-12 14:22 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +Next, the block is decoded and the timestamp of the block is pushed into the `_knownTimestamps` array.
it is a list of timestamps of the blocks that where added to the chain, while the plugin was active.

2021-01-12 14:24 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +What properties should bbe added to the application config is defined in the `defaults()` getter.
```suggestion
Which properties are added to the application config by the plugin is defined in the `defaults()` getter.
```

Better like this?

2021-01-12 14:26 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +What properties should bbe added to the application config is defined in the `defaults()` getter.
```suggestion
The `defaults()` getter defines which properties are added to the application config by the plugin.
```

Or this.

2021-01-12 14:29 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +
The purpose is to give an example how to create a plugin, and I wanted to include common examples. Decoding blocks and transactions are both pretty common and relevant examples, that's why I included them here both. Do you maybe have other suggestions?

2021-01-13 07:21 UTC, Incede approved these changes, later dismissed

2021-01-13 10:34 UTC, chris529 reviewed
Looks good, just a few very minor points 👍

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +* a basic blockchain application is already initiated, like explained in the previous guide xref:{url_guides_setup}[].
```suggestion
* a basic blockchain application is already initiated, as explained in the previous guide xref:{url_guides_setup}[].
```

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +To follow this guide, the following is assumed:
```suggestion
To use this guide, it is assumed that the following criteria have been met:
```

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +For a better overview, create a new file `defaults.js` and define the schema for the configuration options here as in the example below:
```suggestion
For a better overview, create a new file `defaults.js` and define the schema for the configuration options as shown in the example below:
```

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +This defines that the configuration options for the plugin can be provided in the following way:
```suggestion
This defines that the configuration options for the plugin can be provided in the following manner:
```

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +The `channel`, which is available inside of the `load()` function, allows to access the xref:{url_rpc_endpoints}[] in order to subscribe to events or to invoke certain actions within the application,
```suggestion
The `channel`, which is available inside of the `load()` function, allows access to the xref:{url_rpc_endpoints}[] in order to subscribe to events or to invoke certain actions within the application, to retrieve the desired data.
```

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +* If `getKnownTimestamp` is invoked, it returns the list of timestamps of the blocks that where added to the chain, while the plugin was active.
```suggestion
* If `getKnownTimestamp` is invoked, it returns the list of timestamps of the blocks that were added to the chain, while the plugin was active.
```

2021-01-13 10:34 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/plugin.adoc
> +The last thing needed to do is to register the newly created module in the application:
```suggestion
Finally, it is required to register the newly created module in the application:
```

2021-01-13 11:29 UTC, chris529 approved these changes
LGTM!

2021-01-13 11:40 UTC, merged