Generalize migration page - Closes #87
LiskArchive/lisk-legacy-docs pull request #90
Opened 2018-10-23 11:17 UTC by Tschakki

Closes #87

2018-10-24 10:24 UTC, Nazgolze commented on upgrade/migration/migration.md
> +- The next section introduces a tool we have consciously implemented to make a gapless migration. We expect it to be executed in an Ubuntu 16 environment that follows the recommended specs you can fi
Why only Ubuntu 16? We're currently supporting 14-18 (although we should look at dropping support for 14 soon as it hits EOL in 6 months)

2018-10-25 09:17 UTC, Tschakki commented on upgrade/migration/migration.md
> +- The next section introduces a tool we have consciously implemented to make a gapless migration. We expect it to be executed in an Ubuntu 16 environment that follows the recommended specs you can fi
I now removed the whole sentence, because this is already mentioned in line 39 (including Ubuntu 14-18)

2018-10-26 13:45 UTC, Nazgolze submitted a review, later dismissed
Noticed a few minor things, otherwise it looks good

2018-10-26 13:45 UTC, Nazgolze commented on upgrade/migration/migration.md
> +Beside the normal update- script, the `lisk-bridge` script might include additional scripts, e.g. if the new update includes changes in the structure of the configuration file, the script would try t
s/update-/update

2018-10-26 13:45 UTC, Nazgolze commented on upgrade/migration/migration.md
> +- The next section introduces a tool we have consciously implemented to make a gapless migration.
~consciously~

2018-10-26 13:45 UTC, Nazgolze commented on upgrade/migration/migration.md
> +We introduced a tool to perform the migration called [Lisk Bridge](https://downloads.lisk.io/lisk/test/lisk_bridge.sh).
I'm not sure we should link directly to the testnet one. Or maybe link to testnet and mainnet

2018-10-26 13:47 UTC, Nazgolze commented on upgrade/migration/migration.md
> +Beside the normal update- script, the `lisk-bridge` script might include additional scripts, e.g. if the new update includes changes in the structure of the configuration file, the script would try t
Oh -- Beside should also be Besides

2018-11-01 12:19 UTC, nazarhussain requested changes

2018-11-01 12:19 UTC, nazarhussain commented on upgrade/migration/migration.md
> +If you're doing a fully automated migration, you could run `lisk_bridge.sh` inside of tmux, screen, byobu or another terminal multiplexer and detach your session even days ahead of time, though you'd
The whole section for `LISK_MASTER_PASSWORD` only applies when some one upgrading from `0.9.x` version to latest version. So we should highlight this explicitly.

2018-11-01 12:19 UTC, nazarhussain commented on upgrade/migration/migration.md
> +Keep in mind you might need to run some [additional migration scripts](#additional-migration-scripts) beforehand, so that your node is fully prepared for the upgrade.
This also applies that you do that migration before 2 rounds are forged further, otherwise the upgrade will fail. And user have to build from the snapshot.

2018-11-01 12:19 UTC, nazarhussain commented on upgrade/migration/migration.md
>  -n <NETWORK>     -- choose main or test
Please double check, the flag `-f` is mentioned in details but its not in the command line Usage reference.

2018-11-01 12:19 UTC, nazarhussain commented on upgrade/migration/migration.md
> +2. Run the necessary [utility scripts](#utility-scripts).
When you say `necessary` utility scripts, user must be confused which of these are required to run during migration. So please mention these explicitly.

2018-11-01 12:19 UTC, nazarhussain commented on upgrade/migration/migration.md
> +### Console
I am not sure we ship this script in the binary build, please double check.  Its sole purpose was to facilitate the development. So either we remove it from documentation or mention it explicitly that its not available in binary builds.

2018-11-01 17:10 UTC, Tschakki commented on upgrade/migration/migration.md
> +2. Run the necessary [utility scripts](#utility-scripts).
I have now grouped all 0.9 - 1.0 migration specific content to a separate section, so that the rest of the document can stay in a general description that fits to migrations in general.

2018-11-02 09:21 UTC, Tschakki commented on upgrade/migration/migration.md
>  -n <NETWORK>     -- choose main or test
checked, flag exists :)
It is mentioned in the command line usage reference, see: https://github.com/LiskHQ/lisk-scripts/blob/development/downloaded/lisk_bridge.sh#L78

2018-11-02 15:21 UTC, Nazgolze approved these changes
lgtm

2018-11-07 09:36 UTC, nazarhussain approved these changes
@Tschakki It seems good. Just one additional feedback. If we add complete log of one migration as an example. That will help people to understand what will be happening, rather than the video.

2018-11-07 10:11 UTC, merged