Add page about the report misbehavior plugin - Closes #908
LiskArchive/lisk-legacy-docs pull request #915
Opened 2021-01-13 11:13 UTC by Tschakki

Closes #908

2021-01-15 08:56 UTC, chris529 reviewed
Looks good, just a couple of very minor points 👍

2021-01-15 08:56 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
> +<2> `cleanupFrequency`(optional): Frequency of cleaning up the outdated data in second.
```suggestion
<2> `cleanupFrequency`(optional): Frequency of cleaning up the outdated data in seconds.
```

2021-01-15 08:56 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
> +<5> `fee`(optional): The fee required to report misbehavior transaction.
```suggestion
<5> `fee`(optional): The fee required to report a misbehavior transaction.
```

2021-01-15 08:58 UTC, shuse2 requested changes

2021-01-15 08:58 UTC, shuse2 commented on modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
> +<4> `defaultPassword`(optional): Default password to decrypt the encrypted passphrase.
`defaultPassword` this seems not used right now, so let's remove it

2021-01-15 09:02 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/report-misbehavior-plugin.adoc
> +<5> `fee`(optional): The fee required to report misbehavior transaction.
```suggestion
<5> `fee`(optional): The fee required to send a report misbehavior transaction.
```

2021-01-18 12:30 UTC, shuse2 approved these changes, later dismissed

2021-01-18 14:39 UTC, merged