Add page about the monitor plugin - Closes #909
LiskArchive/lisk-legacy-docs pull request #916
Opened 2021-01-13 11:37 UTC by Tschakki

Closes #909

2021-01-15 09:00 UTC, shuse2 requested changes

2021-01-15 09:00 UTC, shuse2 commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> += Monitor plugin
For monitor plugin, not only action/events it also has endpoint for prometheus.
I think it would be better if we can explain them

2021-01-15 09:24 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> += Monitor plugin
I added a note at line 10, but if you have more info about it i am happy to add it :)

2021-01-15 11:47 UTC, nazarhussain commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> +description
It needs some description.

2021-01-15 11:47 UTC, nazarhussain submitted a review, later dismissed

2021-01-18 08:53 UTC, chris529 reviewed
Looks good, just 2 very minor points 👍

2021-01-18 08:53 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> +<10> `delayAfter`: Minimum delay after an API call in ms
```suggestion
<10> `delayAfter`: Minimum delay after an API call in ms.
```

2021-01-18 08:53 UTC, chris529 commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> +<13> `serverSetTimeout`: Time to wait for response from the server before timing out.
```suggestion
<13> `serverSetTimeout`: Time to wait for a response from the server before timing out.
```

2021-01-18 13:59 UTC, shuse2 approved these changes

2021-01-18 13:59 UTC, shuse2 commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> += Monitor plugin
```
# HELP lisk_avg_times_blocks_received_info Average number of times blocks received
# TYPE lisk_avg_times_blocks_received_info gauge
lisk_avg_times_blocks_received_info 16.666666666666668

# HELP lisk_avg_times_transactions_received_info Average number of times transactions received
# TYPE lisk_avg_times_transactions_received_info gauge
lisk_avg_times_transactions_received_info 0

# HELP lisk_node_height_total Node Height
# TYPE lisk_node_height_total gauge
lisk_node_height_total 17945

# HELP lisk_finalized_height_total Finalized Height
# TYPE lisk_finalized_height_total gauge
lisk_finalized_height_total 17822

# HELP lisk_unconfirmed_transactions_total Unconfirmed transactions
# TYPE lisk_unconfirmed_transactions_total gauge
lisk_unconfirmed_transactions_total 1

# HELP lisk_peers_total Total number of peers
# TYPE lisk_peers_total gauge
lisk_peers_total{state="connected"} 16
lisk_peers_total{state="disconnected"} 4

# HELP lisk_fork_events_total Fork events
# TYPE lisk_fork_events_total gauge
lisk_fork_events_total 4
```
this is the current prometheus exported info

2021-01-18 13:59 UTC, shuse2 commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> += Monitor plugin
but maybe it's too much

2021-01-18 14:35 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-framework/monitor-plugin.adoc
> += Monitor plugin
I wouldn't add it here, bbut we could add a new management guide about using prometheus to monitor the node?

2021-01-18 14:36 UTC, merged