Describe to mono repo structure - Closes #78
LiskArchive/lisk-legacy-docs pull request #93
Opened 2018-10-23 14:46 UTC by Tschakki

Closes #78

2018-11-01 16:12 UTC, shuse2 requested changes
Great job in general!!

2018-11-01 16:12 UTC, shuse2 commented on setup/setup.md
> +**Complete library**
For Load via CDN section, I think it's ok to mention only 
`@liskhq/lisk-client` package because in the future, complete package will not be available.
(not all version will be possible to be published for web)

2018-11-01 16:12 UTC, shuse2 commented on setup/setup.md
> +where `<package-name>` can be any of the sub packages in Lisk Elements.
`package-name` is correct, but maybe it's better to show that the actual package name will be `@liskhq/xxx`
maybe here or it could be in `package.md`

2018-11-05 09:48 UTC, shuse2 requested changes
Other than the variable names, it looks good =) thanks1

2018-11-05 09:48 UTC, shuse2 commented on packages/passphrases/passphrases.md
> +import LiskPassphrase from '@liskhq/lisk-passphrase';
```suggestion
import liskPassphrase from '@liskhq/lisk-passphrase';
```

2018-11-05 09:48 UTC, shuse2 commented on packages/passphrases/passphrases.md
> +const { Mnemonic } = LiskPassphrase;
```suggestion
const { Mnemonic } = liskPassphrase;
```

2018-11-05 09:48 UTC, shuse2 commented on packages/passphrases/passphrases.md
> +import LiskPassphrase from '@liskhq/lisk-passphrase';
```suggestion
import passphrase from '@liskhq/lisk-passphrase';
```

2018-11-05 09:48 UTC, shuse2 commented on packages/passphrases/passphrases.md
> +const errors = LiskPassphrase.validation.getPassphraseValidationErrors('   this passphrase is not  valid');
```suggestion
const errors = passphrase.validation.getPassphraseValidationErrors('   this passphrase is not  valid');
```

2018-11-05 09:48 UTC, shuse2 commented on packages/transactions/transactions.md
> +import LiskTransactions from '@liskhq/lisk-transactions';
```suggestion
import transactions from '@liskhq/lisk-transactions';
```

2018-11-05 09:48 UTC, shuse2 commented on packages/transactions/transactions.md
> +LiskTransactions.constants.FIXED_POINT; // Number to use when converting between the smallest possible denomination and 1 LSK.
same as above

2018-11-06 10:53 UTC, Tschakki commented on packages/passphrases/passphrases.md
> +import LiskPassphrase from '@liskhq/lisk-passphrase';
why using `liskPassphrase` above, and here only `passphrase` ?

2018-11-06 10:58 UTC, shuse2 commented on packages/passphrases/passphrases.md
> +import LiskPassphrase from '@liskhq/lisk-passphrase';
sorry, I think i was having second thought during the review.
it's good for me either `liskPassphrase` or `passphrase` consistently. and same for other modules

2018-11-09 10:33 UTC, shuse2 requested changes
`upgrade.md` need to be update (remove CDN part) and change to `lisk-client`

2018-11-09 10:33 UTC, shuse2 commented on packages/constants/constants.md
> +LiskConstants.EPOCH_TIME; // Date from which timestamps are calculated.
these variable needs to be changed

2018-11-09 10:33 UTC, shuse2 commented on setup/setup.md
> +**Specific package**
Specific library doesn't need to be mentioned on CDN

2018-11-10 12:18 UTC, shuse2 commented on packages/transactions/transactions.md
>  The Lisk Elements transactions module provides functions for creating transactions of every type, plus a set of utility functions.
I couldn't catch it last time, but the below explanation seems to be duplicated

2018-11-10 12:20 UTC, shuse2 requested changes
Found small duplication found (maybe merge conflict?)
Also passphrase package is not linked on the PR, but maybe because this is PR?
https://github.com/LiskHQ/lisk-docs/blob/61ba0bcd1f0d72a58623f641fd12d1a64602290c/introduction.md

2018-11-13 09:27 UTC, Tschakki commented
True, there was a typo in the link, it should be working now :)

2018-11-14 09:47 UTC, shuse2 approved these changes

2018-11-15 09:25 UTC, merged