Build Glossary and Abbreviations page in References in SDK docs 5.0.3 - Closes #897
LiskArchive/lisk-legacy-docs pull request #952
Opened 2021-01-25 13:27 UTC by chris529

Closes #897

2021-02-05 13:58 UTC, Tschakki requested changes
Please add a link to the new glossary page to the `nav.adoc` file under references :)

2021-02-08 10:29 UTC, Tschakki requested changes

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +How we describe the overarching account based on an email address.
I don't think this is how we use the term in the documentation

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Active Delegate +
Are we using this term in the docs? I thought we talk about forging delegates most of the time. Also, since v5 there are 103 active delegates each round.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A human-readable representation of a public key on the Lisk blockchain, e.g. 8746385184555771012L.
The address format changed in v5

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The process of sending the first transaction on the Lisk blockchain. With that the public key is permanently stored as part of your address in the Lisk blockchain and checked every time you send a tr
This is not needed in v5 anymore.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocke
Maybe add a link here to more information about the  standard

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Alphanet +
Are we using this in the docs?

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Alpha Candidate +
Are we using this in the docs?

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Alpha Stage +
We left alpha stage, no reason to talk about it anymore.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Avatar +
Not sure we use this in the docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem (BCH) codes form a
Maybe add link for further information

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Beta Candidate +
I don't think we use this in the documentation

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Beta Stage +
Thats more something for the roadmap than glossary

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Blockchain Application Platform +
I don't think we mention this in the docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Bug +
I don't think this is relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Candidate +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== CEO - Chief Executive Officer +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Community +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Community Member +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Contractors +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== CTO - Chief Technical Officer +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegate Misbehaviour Report (previously called `Proof-of-Misbehavior` or `PoM`) +
We have places in the documentation giving more information about the topic, please link them here.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegate Pool +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegated Proof-of-Stake +
We have several places in the documentation giving more information about the topic, please link them here.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegated Proof-of-Stake +
We mainly usse the abbreviationn DPoS, so it should be mentioned here as well.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on Mainnet which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.
We have places in the documentation giving more information about the topic, please link them here.

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Developer +
Not relevant for docs

2021-02-08 10:29 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== DPoS - Delegated Proof of Stake +
this is explained twice

2021-02-08 12:51 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +How we describe the overarching account based on an email address.
Good point, I have changed it 👍

2021-02-08 12:56 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Active Delegate +
Yes, thanks...updated 👍

2021-02-08 13:10 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The process of sending the first transaction on the Lisk blockchain. With that the public key is permanently stored as part of your address in the Lisk blockchain and checked every time you send a tr
Now removed 👍

2021-02-08 13:25 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The Advanced Encryption Standard (AES), has a key length of 256 bits and is a block cipher adopted as an encryption standard by the U.S. government for military and government use. CBC (Cipher Blocke
Good idea as AES  is a complex subject. I have added a link 👍

2021-02-08 13:26 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Alphanet +
No we are not, so I have removed it.

2021-02-08 13:27 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Alpha Candidate +
Nope, we are passed that stage, so also removed now 👍

2021-02-08 13:28 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Alpha Stage +
Good point...done 👍

2021-02-08 13:29 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Avatar +
No its not actaully mentioned in our docs, so has now been removed 👍

2021-02-08 13:32 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:references/glossary.adoc[]
I would put the glossary link at the bottom of references

2021-02-08 13:37 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem (BCH) codes form a
Done 👍

2021-02-08 13:39 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Beta Candidate +
True, we don't use it, so I have removed it 👍

2021-02-08 13:39 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Beta Stage +
Good point, removed 👍

2021-02-08 13:43 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Blockchain Application Platform +
Well, we do mention it on the Passphrase page and also in the Appendix page, so I think maybe we should really keep it.

2021-02-08 13:45 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Bug +
OK, well it was in the Lisk internal terminology doc, however I think you are right, this is not really necessary as it is rather obvious. I have removed it 👍

2021-02-08 13:47 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Candidate +
It is mentioned in the Passphrase page, but again maybe a bit too obvious, so I have removed it 👍

2021-02-08 14:28 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== CEO - Chief Executive Officer +
OK, removed 👍

2021-02-08 14:29 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Community +
removed 👍

2021-02-08 14:30 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Community Member +
removed 👍

2021-02-08 14:30 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Contractors +
removed 👍

2021-02-08 14:30 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== CTO - Chief Technical Officer +
removed 👍

2021-02-08 14:32 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegate Pool +
OK, removed 👍

2021-02-08 14:35 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Developer +
Removed 👍

2021-02-08 14:37 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== DPoS - Delegated Proof of Stake +
Well spotted, now corrected 👍

2021-02-08 14:38 UTC, chris529 commented on modules/ROOT/nav.adoc
> +** xref:references/glossary.adoc[]
Yes, OK , I have moved it to the top of references 👍

2021-02-09 10:02 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegate Misbehaviour Report (previously called `Proof-of-Misbehavior` or `PoM`) +
OK I have added two links 👍

2021-02-09 10:22 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegated Proof-of-Stake +
OK, now done 👍

2021-02-09 10:38 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on Mainnet which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.
OK, have added a link, (which also in the linked explanation, refers to another link for even more info on the delegate registration). 👍

2021-02-09 13:21 UTC, Tschakki requested changes

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:references/glossary.adoc[]
But it should go to the bottom imho

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Blockchain Application Platform +
Can you provide links to the pages you are referring to? I cannot find it

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_misbehavior: pages/consensus.adoc#how-to-discover-misbehavior-of-a-delegate
this link has the wrong format

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_dpos: pages/consensus.adoc#delegated-proof-of-stake-(dpos)
this link has the wrong format

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_registration: pages/consensus.adoc#registering-as-delegate
this link has the wrong format

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Feature +
not relevant for docs

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The first actual block created in the blockchain.
We have places in the documentation giving more information about the topic, please add it here.

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Lisk +
not relevant for docs

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Lisk Foundation Council +
not relevant for docs

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Our wallet for desktop platforms.
```suggestion
Official Lisk wallet for desktop platforms.
```

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Our wallet for mobile platforms.
```suggestion
Official Lisk wallet for mobile platforms.
```

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The token for the Lisk blockchain application platform.
```suggestion
The token used in the Lisk Mainnet.
```

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== LSK holder +
not relevant for docs

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on Mainnet which converts a previously non-initialized account’s address to the new address system. This is required because the public key is required to convert from the old addr
similar to the transaction types above, please add a link to a more detailed explanation in the protocol docs.

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which registers a multisignature group.
similar to the transaction types above, please add a link to a more detailed explanation in the protocol docs.

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet.
We have a broader definition of a node in our documentation, please update

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Objective +
not relevant for docs

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Phase +
not relevant for docs

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Platform Development Team +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== PoM - Proof of Misbehavior +
I think we changed the term, and PoM is not used anymore

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Production Candidate +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Production Stage +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Protocol Roadmap +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== RC Stage +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +An embedded persistent key value store for fast storage.
```suggestion
=== RocksDB 

A high performance embedded database.
An embedded persistent key value store for fast storage.
```

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Account +
```suggestion
=== Account
```

Please remove the plusses, they are not really necessary

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Second Passphrase +
not relevant anymore

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Stage +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A standby delegate, as each delegate is not able to forge new blocks for the Lisk blockchain. Rank 103-∞.
Can you verify, I think it should be rank `102-infinity`

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +How we refer to LSK or any sidechain token.
Don't us `we` or `us` when explaining glossary terms

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which transfers LSK from one Lisk address to another one.
similar to the transaction types above, please add a link to a more detailed explanation in the protocol docs.

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which locks the token used for votes.
similar to the transaction types above, please add a link to a more detailed explanation in the protocol docs.

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Version +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Vulnerability +
not relevant

2021-02-09 13:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +How we generally describe our desktop and mobile user interfaces.
Don't us `we` or `us` when explaining glossary terms

2021-02-09 14:10 UTC, chris529 commented on modules/ROOT/nav.adoc
> +** xref:references/glossary.adoc[]
Yes, you are correct, it should be at the bottom. It is now done 👍

2021-02-09 14:12 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A human-readable representation of a public key on the Lisk blockchain, e.g. 8746385184555771012L.
it has been updated 👍

2021-02-09 14:18 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Blockchain Application Platform +
Sorry, that was an error as I was referring to BIP39. You are correct, there is no mention of a 'Blockchain Application platform' in our docs, so I have now removed it 👍

2021-02-09 14:25 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_misbehavior: pages/consensus.adoc#how-to-discover-misbehavior-of-a-delegate
Oops, yes there should be underscores between the words after the hash. Now done 👍

2021-02-09 14:26 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_dpos: pages/consensus.adoc#delegated-proof-of-stake-(dpos)
Now corrected 👍

2021-02-09 14:27 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_registration: pages/consensus.adoc#registering-as-delegate
Now corrected 👍

2021-02-09 14:28 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Feature +
Now removed 👍

2021-02-09 14:28 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Lisk +
Now removed 👍

2021-02-09 14:30 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Lisk Foundation Council +
Now removed 👍

2021-02-09 14:34 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== LSK holder +
Now removed 👍

2021-02-09 14:36 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Objective +
Now removed 👍

2021-02-09 14:36 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Phase +
Now removed 👍

2021-02-09 14:37 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Platform Development Team +
Now removed 👍

2021-02-09 14:38 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Production Candidate +
Now removed 👍

2021-02-09 14:38 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Production Stage +
Now removed 👍

2021-02-09 14:38 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Protocol Roadmap +
Now removed 👍

2021-02-09 14:39 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== RC Stage +
Now removed 👍

2021-02-09 14:43 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Second Passphrase +
Now removed 👍

2021-02-09 14:43 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Stage +
Now removed 👍

2021-02-09 14:45 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +How we refer to LSK or any sidechain token.
Good point, now done 👍

2021-02-09 14:46 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Version +
Removed 👍

2021-02-09 14:53 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +How we generally describe our desktop and mobile user interfaces.
Amended 👍

2021-02-09 15:04 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A standby delegate, as each delegate is not able to forge new blocks for the Lisk blockchain. Rank 103-∞.
Well spotted Mona! You are right it is 102..Now updated 👍

2021-02-09 15:25 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The first actual block created in the blockchain.
I have added a bit more detail about the genesis block and added a link, (which also in the linked explanation, refers to another link for even more info on the genesis block)  👍

2021-02-10 09:54 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on Mainnet which converts a previously non-initialized account’s address to the new address system. This is required because the public key is required to convert from the old addr
Good point, now done 👍

2021-02-10 10:10 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which registers a multisignature group.
Done 👍

2021-02-10 10:18 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet.
Done 👍

2021-02-10 10:20 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== PoM - Proof of Misbehavior +
Well spotted Mona! Good point indeed. It is now removed 👍

2021-02-10 10:41 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which transfers LSK from one Lisk address to another one.
OK, done 👍

2021-02-10 10:57 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which locks the token used for votes.
Done 👍

2021-02-10 10:58 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Vulnerability +
Now removed 👍

2021-02-10 14:50 UTC, Tschakki requested changes
please update the consensus page links, the content there got moved to the DPoS module page.

2021-02-10 14:50 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_misbehavior: pages/consensus.adoc#discover
consensus page is outdated, dont link to it anymore

2021-02-10 14:50 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_dpos: pages/consensus.adoc#dpos
consensus page is outdated and will be removed, dont link to it anymore

2021-02-10 14:50 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_registration: pages/consensus.adoc#delegate
consensus page is outdated and will be removed, dont link to it anymore

2021-02-10 15:05 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet. It can be described as a resource for interacting with the node endpoint provided by the Lisk publ
I meant more something like this:
```suggestion
A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to a blockchain network.
Nodes fulfill many important roles in the network, like synchronising new events in the network between each other, adding new blocks to the blockchain, and providing APIs for external services in order to communicate with the network.
```

2021-02-10 15:06 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_misbehavior: pages/consensus.adoc#discover
OK, now done 👍

2021-02-10 15:08 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_dpos: pages/consensus.adoc#dpos
OK, now done 👍

2021-02-10 15:11 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_registration: pages/consensus.adoc#delegate
Done 👍

2021-02-10 15:12 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A server having Lisk Core installed and therefore being part of a Lisk network, e.g. Lisk’s mainnet. It can be described as a resource for interacting with the node endpoint provided by the Lisk publ
OK, cool..yes my version was a bit long-winded 👍

2021-02-11 13:52 UTC, Tschakki requested changes
As discussed, please read through the docs and see if any relevant terms are still missing in the glossary.

2021-02-11 13:52 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_genesis_block: pages/architecture/index.adoc#genesis_block
Wrong link format. Remove `pages/` to fix

2021-02-12 12:07 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +:url_genesis_block: pages/architecture/index.adoc#genesis_block
OK, done 👍

2021-03-04 16:09 UTC, Tschakki requested changes
Please remove all the outdated pages that were added back in the PR, check and fix the links, and remove how terms where called previously from the glossary.

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/consensus.adoc
> += Blockchain gonvernace
Why do you add this page? Please remove again.

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/index.adoc
> +:url_npm_glossary: references/glossary.adoc#npm
link does not work

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +:url_aes_glossary: references/glossary.adoc#aes
link does not work

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/chain.adoc
> +:url_bft_glossary: references/glossary.adoc#bft
I tried three of the placed links, they all do not work. Please go through the other links and check, if they need to be fixed as well.

In this case, the correct link is

```suggestion
:url_bft_glossary: references/glossary.adoc#bft-byzantine-fault-tolerance
```

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/tutorials/supply-chain/part1.adoc
> += Part 0: Installation & setup
Please remove again.

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/tutorials/supply-chain/part2.adoc
> += Part 1: Track a packet on the blockchain
Please remove again.

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/guides/app-development/broadcast.adoc
> += Broadcast a transaction
Please don't add random pages, remove again

2021-03-04 16:09 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegate Misbehaviour Report (previously called `Proof-of-Misbehavior` or `PoM`)
Everywhere, where it is mentioned how something was previously called, please remove it.

2021-03-05 08:01 UTC, chris529 commented on modules/ROOT/pages/consensus.adoc
> += Blockchain gonvernace
This was an error, the page is now removed 👍

2021-03-05 08:05 UTC, chris529 commented on modules/ROOT/pages/references/lisk-commander/index.adoc
> +:url_npm_glossary: references/glossary.adoc#npm
OK, it should work now 👍

2021-03-05 15:12 UTC, chris529 commented on modules/ROOT/pages/references/lisk-commander/commands.adoc
> +:url_aes_glossary: references/glossary.adoc#aes
OK, it should work now 👍

2021-03-05 16:03 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/chain.adoc
> +:url_bft_glossary: references/glossary.adoc#bft
👍

2021-03-05 16:06 UTC, chris529 commented on modules/ROOT/pages/tutorials/supply-chain/part1.adoc
> += Part 0: Installation & setup
👍

2021-03-05 16:06 UTC, chris529 commented on modules/ROOT/pages/tutorials/supply-chain/part2.adoc
> += Part 1: Track a packet on the blockchain
👍

2021-03-05 16:09 UTC, chris529 commented on modules/ROOT/pages/guides/app-development/broadcast.adoc
> += Broadcast a transaction
👍

2021-03-05 16:13 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Delegate Misbehaviour Report (previously called `Proof-of-Misbehavior` or `PoM`)
👍

2021-03-09 13:32 UTC, Tschakki requested changes

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/consensus.adoc
> += Blockchain gonvernace
This page does not seem to be removed

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +It implements peer buckets for newPeers and triedPeers as described in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md[LIP 0004].
please add this link as attribute at the top, and use the attribute here :)

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +:url_crud_glossary: references/glossary.adoc#crud-create-read-update-&-delete
```suggestion
:url_crud_glossary: references/glossary.adoc#crud-create-read-update-delete
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A human-readable representation of a public key on the Lisk blockchain. It has a length of 160 bits, making it computationally infeasible that two independent users would end up with the same address
I think we should be more precise about the different address formats that exist.
The binary address and base32 address should be explained separately.

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Forge
```suggestion
=== Forging
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A self-contained, off chain module which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin. Typically there is no state ch
```suggestion
A self-contained, off chain component which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin. Typically there is no state change on the blockchain.
```

avoid the term "module" here, to avoid confusion with modules

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
link doesn't work

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_protocol_transaction_pom}[delegate misbehavior report] refers to a transaction type on the Mainnet which reports a delegates misbehavior. Any xref:{url_delegate_misbehavior}[misbehavior o
link doesn't work.

And please use a new line for the new sentence.

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_delegate_registration{[delegate registration] is achieved via a transaction type on the Mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algori
link doesn't work

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain. It defines the initial state of the blockchain on start of the network. A genesis block must be given to
link doesn't work

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== LSK reclaim (previously called `reclaim`)
```suggestion
=== LSK reclaim
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_reclaim_lsk}[LSK reclaim] transaction type on the Mainnet converts a previously non-initialized account’s address to the new address system. This is required because the public key is req
link doesn't work

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== multisignature group registration (previously called `multisignature registration`)
```suggestion
=== Multisignature group registration
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to a blockchain network.
```suggestion
A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to other nodes. Together, they form a blockchain network.
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A configurable package manager used for the node JavaScript platform. It can manage dependency conflicts and put modules in place so that nodes can locate them.
Use new lines for new sentences

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== token transfer (previously called `balance transfer`)
```suggestion
=== Token transfer
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== token unlock (previously called `unlock vote`)
```suggestion
=== Token unlock
```

2021-03-09 13:32 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A Lisk wallet is available on both Lisk desktop and Lisk mobile. They are actively maintained and provide the most secure and easiest way to access the users LSK tokens.
```suggestion
A Lisk wallet is available on both Lisk Desktop and Lisk Mobile.
They are actively maintained and provide the most secure and easiest way to access the users LSK tokens.
```

2021-03-09 14:09 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
Yes, it seems that it does not work anymore and requires a private connection. OK, I have found a better link now 👍

2021-03-09 14:32 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A human-readable representation of a public key on the Lisk blockchain. It has a length of 160 bits, making it computationally infeasible that two independent users would end up with the same address
Good point Mona! Agreed. I have now created 2 separate entries in the glossary explaining both addresses 👍

2021-03-09 14:57 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_protocol_transaction_pom}[delegate misbehavior report] refers to a transaction type on the Mainnet which reports a delegates misbehavior. Any xref:{url_delegate_misbehavior}[misbehavior o
New line added, and link should now work 👍

2021-03-09 15:01 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_delegate_registration{[delegate registration] is achieved via a transaction type on the Mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algori
It should now work 👍

2021-03-09 15:07 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain. It defines the initial state of the blockchain on start of the network. A genesis block must be given to
OK, it should work now 👍

2021-03-09 16:00 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_reclaim_lsk}[LSK reclaim] transaction type on the Mainnet converts a previously non-initialized account’s address to the new address system. This is required because the public key is req
Ir should work now 👍

2021-03-09 16:29 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A configurable package manager used for the node JavaScript platform. It can manage dependency conflicts and put modules in place so that nodes can locate them.
👍

2021-03-09 16:30 UTC, chris529 commented on modules/ROOT/pages/references/lisk-elements/p2p.adoc
> +It implements peer buckets for newPeers and triedPeers as described in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md[LIP 0004].
Now done 👍

2021-03-10 11:14 UTC, Tschakki requested changes

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
>  <2> Opens the firehol config file.
duplicated content

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/consensus.adoc
> += Blockchain gonvernace
page is still existent... please remove

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Mona Bärenfänger <mona@lightcurve.io>
```suggestion
Christopher Braithwaite <christopher.braithwaite@lightcurve.io>
```

as you created the page, feel free to put yourself in the author details :)

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +
```suggestion
== A
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_del_misbehavior: dpos-module.adoc#how-to-discover-misbehavior-of-a-delegate
```suggestion
:url_del_misbehavior: dpos-module.adoc#discover
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_delegate_registration{[delegate registration] is achieved via a transaction type on the Mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algori
```suggestion
A xref:{url_delegate_registration}[delegate registration] is achieved via a transaction type on the Mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_registration: dpos-module.adoc#registering-as-delegate
```suggestion
:url_delegate_registration: dpos-module.adoc#delegate_registration
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_genesis_block: protocol:blocks.adoc#_genesis_block
```suggestion
:url_genesis_block: protocol:blocks.adoc#genesis-block
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_multisignature: protocol:transactions.adoc#multisignature-group-registration
```suggestion
:url_multisignature: protocol:transactions.adoc#multisignature
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_token_transfer: protocol:transactions.adoc#transactions
```suggestion
:url_token_transfer: protocol:transactions.adoc#transfer
```

2021-03-10 11:14 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_token_unlock: protocol:transactions.adoc#transactions
```suggestion
:url_token_unlock: protocol:transactions.adoc#unlock
```

2021-03-10 11:19 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A Base32 address is constructed using the base-32 numeral system. It works by using a set of 32 digits, whereby each digit can be represented by 5 bits (25). A common method used to represent Base32
This explanation is very broad and not specific enough to what the Base32 address is in context of the Lisk documentation.

2021-03-10 11:21 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A human-readable representation of a public key on the Lisk blockchain. It has a length of 160 bits, making it computationally infeasible that two independent users would end up with the same address
```suggestion
A human-readable representation of a public key on the Lisk blockchain. It has a length of 160 bits, making it computationally infeasible that two independent users would end up with the same address. A binary address example used at protocol level is shown here: 0xc247a42e09e6aafd818821f75b2f5b0de47c8235.
```
The binary address it not really the human-readable form, this is the Base32 address.
Please check the explanation and example provided here are correct.

2021-03-10 13:44 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
>  <2> Opens the firehol config file.
OK, now removed 👍

2021-03-10 14:14 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A Base32 address is constructed using the base-32 numeral system. It works by using a set of 32 digits, whereby each digit can be represented by 5 bits (25). A common method used to represent Base32
Good point. OK, I have rewritten both descriptions pertaining to Lisk 👍

2021-03-10 14:15 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A human-readable representation of a public key on the Lisk blockchain. It has a length of 160 bits, making it computationally infeasible that two independent users would end up with the same address
Good point, now done 👍

2021-03-11 10:26 UTC, Tschakki requested changes

2021-03-11 10:26 UTC, Tschakki commented on modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
> +<1> Installs xref:{url_firehol_glossary}[firehol].
What is happening here?

2021-03-11 10:26 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Having a length of 160 bits makes it computationally infeasible that two independent users would end up with the same address. A binary address example used at protocol level is shown here: 0xc247a42
I think the description here should be improved. Please check with @shuse2 and/or @janhack

2021-03-11 10:26 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A Base32 address is a user-friendly, human readable address system in the Base32 format and includes a checksum which detect typing errors. The user interface address format is always 41 characters i
Explain the connection between binary and base 32 here.

And please use for each sentence a new line.

2021-03-12 10:35 UTC, chris529 commented on modules/ROOT/pages/guides/node-management/forging-node-protection.adoc
> +<1> Installs xref:{url_firehol_glossary}[firehol].
Now done 👍

2021-03-12 13:51 UTC, AndreasKendziorra requested changes

2021-03-12 13:51 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +=== Base32 Address
I admit that I introduced this term in LIP 0018, but it's not ideal and shouldn't be used, because it suggests that we have two kinds of addresses (binary addresses and Base32 addresses), whereas we only have one kind of address and additionally a special format for the user interfaces. It should be:
- Base32 Encoding,
- Base32 Encoding of Addresses,
- Base32 Format, 
- Base32 Format of Addresses,
- Base32 Representation, or
- Base32 Representation of Addresses.

I have a slight preference for "Base32 Format".

2021-03-12 13:51 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +=== Binary Address
Similar to may comment above: It could suggest that we have several kinds of addresses (binary addresses, Base32 addresses, ...), although we have only one kind of address plus a special format for user interfaces (Base32 format). Therefore, it should just be "Address".

2021-03-12 13:51 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +A Base32 address is a user-friendly, human readable address system in the Base32 format and includes a checksum which detect typing errors. The user interface address format is always 41 characters i
```suggestion
The Base32 format is a user-friendly, human readable representation of addresses in a Base32 encoding and includes a checksum which detect typing errors. It is used to represent addresses on user interfaces. An address in this format is always 41 characters in length and contains decimal digits and lower-case letters, and finally starts with the prefix 'lsk'. An example address in this format will look like the following: ‘lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu’.
```

2021-03-12 13:51 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +A binary address is used for an account with a public key, (pubkey), which is generated by computing the SHA-256(pubkey) and truncating the output to its first 160 bits.
```suggestion
Addresses are used to identify accounts, and are derived from a public key, (pubkey), by computing SHA-256(pubkey) and truncating the output to its first 160 bits.
```

2021-03-12 13:51 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +Having a length of 160 bits makes it computationally infeasible that two independent users would end up with the same address. A binary address example used at protocol level is shown here: 0xc247a42
1. The statement in the first sentence is correct. But if we want to highlight the security, it would be more important to say "Having a length of 160 bits makes it computationally infeasible that an adversary can find a key-pair for an uninitialized account".
2. If we keep the second sentence, then we need to say that this is "a representation of an address in hex." But I would rather remove it completely, because (a) we don't really use hex representation of addresses anywhere and (b) everyone knows how a 160-bit value looks like in hex.

2021-03-12 13:51 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
Just spotted this by chance: I think it is not very important that it is a cyclic code. But is very important to say that it is an error-correcting code. That's its main property.

2021-03-12 15:20 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Having a length of 160 bits makes it computationally infeasible that two independent users would end up with the same address. A binary address example used at protocol level is shown here: 0xc247a42
Hi Andreas, thanks very much. OK, I have taken your points on board, perhaps it was too much information in the first place, so I have removed the second sentence. Ideally, it really just needs to be a short and concise description 👍

2021-03-12 15:31 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Base32 Address
I see. However, we have instances of 'Base32 addresses' and instances of 'Binary addresses' in the documentation, so that is why we tried to list them individually. 
So would you recommend we change this title for 'Base32 Address' in the glossary to 'Base32 Format' then?

2021-03-12 15:41 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Binary Address
OK, we can change it to just 'Address' and I can move it under the topics described beginning with the letter ''A'' However, as mentioned above there are instances of 'Binary Addresses' in the docs that ideally we wanted to refer to in the glossary. 
Of course, we can easily rename it to ''Address'' Please let us know which you feel would be the best solution taking the points mentioned above into consideration?

2021-03-12 15:43 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are cyclic codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
OK, I have re-worded it to reflect this. Many thanks 👍

2021-03-15 09:10 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +=== Base32 Address
hm. Ideally we would change the wording in the documentation. If this is not an option, them I'm afraid we have to keep the wording but we must make clear in the description that Base32 addresses are just (binary) addresses in a special format.

2021-03-15 09:10 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +BCH are error-correcting codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
```suggestion
BCH codes are error-correcting codes. The Bose, Chaudhuri and Hocquenghem ({url_bch_codes}[BCH^]) codes form a
```

2021-03-15 09:10 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +=== Binary Address
The best would be to rename it to "address" within the documentation. If this is not an option, then I would keep the title "binary address" here as well.

2021-03-15 09:10 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +A binary address is used for an account with a public key, (pubkey), which is generated by computing the SHA-256(pubkey) and truncating the output to its first 160 bits.
The statement "A binary address is used for an account with a public key" is a bit weird because: 
1. There may be accounts for which no public key is known. But these accounts have an address.
2. You could still argue that there exists a public key for the accounts in case 1., i.e., for accounts where the public key is not publicly known. But with this view point, every account has a public key. Therefore, "for an account with a public key" is a bit weird.

2021-03-15 09:10 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +A binary address is used for an account with a public key, (pubkey), which is generated by computing the SHA-256(pubkey) and truncating the output to its first 160 bits.
"the SHA-256(pubkey)" sounds also a bit weird to me

2021-03-15 09:50 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Base32 Address
OK, I have re-worded it as follows, please let me know if this is more accurate.

The Base32 format is a user-friendly, human-readable representation of addresses in Base32 encoding and includes a checksum that detects typing errors. They are used to represent addresses on user interfaces. Base32 addresses are actually binary addresses in a special format and are always 41 characters in length. They contain decimal digits and lower-case letters and finally start with the prefix 'lsk'. An example address in this format will look like the following: ‘lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu’.

2021-03-15 09:52 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Binary Address
OK thanks, then we will keep the title as 'Binary Address'

2021-03-15 12:44 UTC, AndreasKendziorra requested changes

2021-03-15 12:44 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +=== Base32 Address
If we don't add the term "Base32 format" to the glossary, I would not use it. Otherwise, it could be mixed up with the [general Base32 encoding](https://en.wikipedia.org/wiki/Base32). I made a suggestion how to avoid it. Of course, you could improve the formulations if you want to.

2021-03-15 12:44 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +The Base32 format is a user-friendly, human readable representation of addresses in Base32 encoding and includes a checksum that detects typing errors. They are used to represent addresses on user in
```suggestion
On user interfaces, a user-friendly, human readable representation of binary addresses is used that uses a Base32 encoding and includes a checksum that detects typing errors. A binary address represented in this format is called Base32 address. They are always 41 characters in length. They contain decimal digits and lower-case letters and finally start with the prefix 'lsk'. An example address in this format will look like the following: ‘lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu’.
```

2021-03-15 12:44 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +A binary address is generated by computing the SHA-256(pubkey) and truncating the output to its first 160 bits.
```suggestion
A binary address is generated by computing the SHA-256 hash digest of the public key of an account and truncating the output to its first 160 bits.
```

2021-03-15 12:44 UTC, AndreasKendziorra commented on modules/ROOT/pages/references/glossary.adoc
> +A binary address is generated by computing the SHA-256(pubkey) and truncating the output to its first 160 bits.
pubkey was not defined anymore

2021-03-15 13:36 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The Base32 format is a user-friendly, human readable representation of addresses in Base32 encoding and includes a checksum that detects typing errors. They are used to represent addresses on user in
Great thanks very much 👍

2021-03-15 13:36 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A binary address is generated by computing the SHA-256(pubkey) and truncating the output to its first 160 bits.
Super, thanks again 👍

2021-03-15 13:55 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +=== Base32 Address
Hi Andreas, I have taken your suggestions below on board and accepted them, thanks very much 👍

2021-03-15 14:07 UTC, AndreasKendziorra approved these changes, later dismissed

2021-03-24 11:47 UTC, Tschakki requested changes
Hey, I found multiple smaller and bigger issues in the glossary, please have a look again.

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:toc: preamble
```suggestion
:toc:
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A Lisk account consists of a unique identifier consisting of an address, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the Lisk protocol.
```suggestion
An account consists of a unique identifier / <<account-address,address>>, an amount of tokens referred to as balance and possibly some additional properties used in other parts of the blockchain application.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +For further details regarding other address representations this can be seen here in the different data structures xref:{url_data_structure}[table].
```suggestion
=== Account Address

Addresses are unique identifiers for accounts in the Lisk blockchain.
They are the 20-byte hash value of the public key that controls the account initially.
In all front-end products, addresses are displayed in a human-readable representation called <<Lisk32-representation>>.
An example for an address in Lisk32 presentation is `lskxwnb4ubt93gz49w3of855yy9uzntddyndahm6s`.
When referring to addresses in Lisk, we always assume the Lisk32 representation, without explicitly having to mention it.
In the Lisk protocol and SDK only the 20 byte value is stored for efficiency and sometimes the hexadecimal representation of the address is used.
Further details regarding other address representations can be seen here in the xref:{url_data_structure}[table for different data types] on the schema reference page.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A set of 12 words used to access the Lisk address.
```suggestion
A set of 12 words used to access an <<account>>.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-103.
```suggestion
An active delegate can mostly be considered as a forging delegate, who is able to forge new blocks for the Lisk blockchain. Rank 1-101.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The smallest unit of account. 100 million beddows make one LSK.
```suggestion
The smallest unit of account. 100 million Beddows make one LSK.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A temporary, external testing network of a Lisk Core beta candidate.
```suggestion
A temporary, public testing network for the Lisk Core beta candidate.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A Lisk account which performed the delegate registration and is now able to receive votes.
```suggestion
An account which performed the delegate registration and is now able to receive votes.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_misbehavior: dpos-module.adoc#reporting-a-delegate
```suggestion
:url_delegate_misbehavior: protocol:transactions.adoc#pom
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Any xref:{url_del_misbehavior}[misbehavior of a delegate] is indicated by two contradicting block headers signed by the delegate.
```suggestion
Any misbehavior of a delegate is xref:{url_discover_misbehavior}[indicated] by two contradicting block headers signed by the delegate.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +
```suggestion
=== Lisk32 representation

The Lisk32 representation of <<account-addresses>> starts with the letters "lsk" followed by a custom Base32 encoding of the 20 bytes of the address appended with a BCH checksum.
The checksum is used to check for small errors in the address.
Any errors in up to 4 characters are guaranteed to be detected and errors in more than 5 characters are likely to be detected.
The choice of the Lisk32 representation of addresses does not modify the address, but is introduced to provide a safer and more pleasant experience to users.

```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Official Lisk wallet for mobile platforms.
These descriptions could be improved, and also they might be slightely outdated.
Please wait until the terminology document was updated or remove these terms for now.

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which registers a xref:{url_multisignature}[multisignature group]. This transaction registers the sender account as a multisignature grou
```suggestion
A transaction type on all networks based on the Lisk protocol which registers a xref:{url_multisignature}[multisignature group].
This transaction registers the sender account as a multisignature group account. 
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to other nodes. Together, they form a blockchain network.
```suggestion
A blockchain application built with the Lisk SDK, e.g. Lisk Core, which is connected to other nodes.
Together, they form a blockchain network.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A configurable package manager used for the node JavaScript platform. +
```suggestion
NPM is the default package manager for the JavaScript runtime environment Node.js.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +It can manage dependency conflicts and put modules in place so that nodes can locate them.
```suggestion
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Distribution of a library.
```suggestion
NPM distribution of a library.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network. With PoS the consensus is determined based upon the stake of each user in the network.
This description should be improved or removed

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Work is is a type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to solve com
This description should be improved or removed

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A proposed new version of Lisk Core for the testnet.
Release candidate is a general term and not targeted to Lisk Core. Please explain the general term here or remove this completely.

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +REST refers to the Representational State Transfer, which is a client-server, stateless, cacheable communications protocol. In the majority of cases HTTP is used.
```suggestion
REST refers to the Representational State Transfer, which is a client-server, stateless, cacheable communications protocol.
In the majority of cases HTTP is used.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +An embedded persistent key value store for fast storage.
Add link to their official homepage

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +RPC is a session protocol which enables a host to make a procedure call that appears to be local, however it has the ability to execute remotely on a separate machine connected to the network.
```suggestion
RPC is a request–response protocol.
An RPC is initiated by the client, which sends a request message to a known remote server to execute a specified procedure with supplied parameters.
The remote server sends a response to the client, and the application continues its process.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Semantic versioning (also referred as SemVer), is a versioning system that provides a universal way of versioning software development projects in order to track changes and updates, such as plugins,
Explain semVer  in more detail or provide a link to an explanation here

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A standby delegate, as each delegate is not able to forge new blocks for the Lisk blockchain. Rank 102-∞.
```suggestion
A standby delegate, as each delegate is not an <<active-delegate>>.
Rank 102-∞.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +TLS is the transport layer security. The application-layer protocol negotiation is a transport layer security extension that allows the application layer to negotiate over a secure connection which p
```suggestion
TLS is the transport layer security.
The application-layer protocol negotiation is a transport layer security extension that allows the application layer to negotiate over a secure connection which protocol should be performed.
This occurs in a manner that avoids additional round trips and which is independent of the application-layer protocols.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A token refers to LSK or any sidechain token.
Should have a little more detail

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +An interaction with the Lisk blockchain which permanently writes data to it. A transaction can have multiple purposes, e.g. a balance transfer or a delegate registration.
```suggestion
An interaction with the Lisk blockchain which permanently writes data to it.
A transaction can have multiple purposes, e.g. a balance transfer or a delegate registration.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol which transfers LSK from one Lisk address to another one. A xref:{url_token_transfer}[token transfer] transaction will transfer the amoun
```suggestion
A transaction type which transfers tokens from one account to another one.
A xref:{url_token_transfer}[token transfer] transaction will transfer the amount of tokens specified in the amount property, from the sender of the transaction to the specified recipient.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A custom message you can attach to a balance transfer.
```suggestion
A custom message you can attach to a <<token-transfer>>.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on all networks based on the Lisk protocol. The xref:{url_token_unlock}[token unlock] transaction unlocks the tokens specified in the amount that were previously unvoted for the de
```suggestion
The xref:{url_token_unlock}[token unlock] transaction unlocks the tokens which have been locked previously byb voting for a specific delegate.
The delegate needs to be unvoted before unlocking the tokens by sending a <<delegate-vote>> transaction.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol. In addition, it can also cover an implementation or a non technical process surrounding Li
```suggestion
A LIP is a document usually structured by the research team defining technical changes in the Lisk protocol.
In addition, it can also cover an implementation or a non technical process surrounding Lisk.
Furthermore, a LIP also describes the requirements, rationale and motivation for the required changes.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_delegate_registration: dpos-module.adoc#delegate_registration
```suggestion
:url_delegate_registration: dpos-module.adoc#delegate_registration
:url_delegate_registration_tx: protocol:transactions.adoc#delegate

```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_delegate_registration}[delegate registration] is achieved via a transaction type on the Mainnet, which registers a delegate to participate in the Delegated Proof-of-Stake consensus algori
```suggestion
A xref:{url_delegate_registration}[delegate registration] is achieved by sending a xref:{url_delegate_registration_tx}[delegate registration transaction], which registers a delegate to participate in the Delegated Proof-of-Stake consensus algorithm.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on Mainnet which submits votes for delegates. If the votes are positive it adds the voting weight, if they are negative it removes the voting weight again. If voting weight was add
This is an outdated description and needs to be updated

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A temporary, internal-only testing network running on an individual developer’s machine during development.
```suggestion
A blockchain network for development purposes.
The Lisk SDK provides dedicated genesis block and configurations to conveniently set up a local Devnet during development of a blockchain application.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +xref:{url_dpos}[DPoS] is the mechanism of determining eligible block creators achieved by voting for registered delegate accounts, which are then able to create blocks depending on their vote weight.
```suggestion
xref:{url_dpos}[DPoS] is the mechanism of determining eligible block creators achieved by voting for registered delegate accounts, which are then able to create blocks depending on their vote weight.
It is part of the consensus algorithm of a blockchain and used on Lisk Mainnet and in the Lisk SDK.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +FireHOL is a shell script designed as a wrapper for iptables written in order to ease the customization of the Linux kernel's firewall netfilter. FireHOL does not have a graphical user interface, but
```suggestion
FireHOL is a shell script designed as a wrapper for iptables written in order to ease the customization of the Linux kernel's firewall netfilter.
FireHOL does not have a graphical user interface, but is configured through a user-friendly and easy to understand plain text configuration file.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +How delegates produce blocks on the Lisk blockchain.
```suggestion
How delegates produce new blocks on the Lisk blockchain.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A fork in the network is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.
This description should be improved

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A self-contained, off chain component which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin. Typically there is no state
```suggestion
A self-contained, off chain component which extends the standard feature set of the Lisk SDK by a specific use case, e.g. a node monitor plugin or delegate forging plugin.
Typically there is no state change on the blockchain.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain. It defines the initial state of the blockchain on start of the network. A genesis block must be given to
```suggestion
The xref:{url_genesis_block}[genesis block] describes the very first block in the blockchain.
It defines the initial state of the blockchain on start of the network.
A genesis block must be given to the application, and all networks should have a different genesis block.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption. This can also be referred to as a nonce.
```suggestion
An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption.
This can also be referred to as a nonce.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption. This can also be referred to as a nonce.
I think we should explain the term "nonce" as well in the glossary.

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A xref:{url_reclaim_lsk}[LSK reclaim] transaction type on the Mainnet converts a previously non-initialized account’s address to the new address system. This is required because the public key is req
```suggestion
This transaction is only part of Lisk Core and not the Lisk SDK.
A xref:{url_reclaim_lsk}[LSK reclaim] transaction type on the Mainnet converts a previously non-initialized legacy account’s address to the new address system.
This is required because the public key is required to convert from the old address system to the new address system.
Non-initialized accounts don’t have a public key associated with them yet.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +UTXO is an unspent output. In other words it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.
```suggestion
UTXO is an unspent output.
In other words it can be thought of as an indivisible chunk of a token, which is under the control of the private keys belonging to the owners.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A user deploying their LSK to vote for their favourite delegates.
```suggestion
An account deploying their LSK to vote for their favourite delegates.
```

2021-03-24 11:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A Lisk wallet is available on both Lisk Desktop and Lisk Mobile.
Here it should also be explained what a wallet is.

2021-03-24 13:12 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +An initialization vector (IV) is classed as an arbitrary number that can be used in conjuction with a secret key for data encryption. This can also be referred to as a nonce.
Yes, good idea Mona. I will add it in 👍

2021-03-24 13:17 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A Lisk wallet is available on both Lisk Desktop and Lisk Mobile.
Agreed, I will add in an explanation 👍

2021-03-24 13:27 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Official Lisk wallet for mobile platforms.
OK, agreed. I will make a note of these, and we'll let's remove them for now. We can then add in the new updated versions of these points in due course 👍

2021-03-24 13:36 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network. With PoS the consensus is determined based upon the stake of each user in the network.
OK, I tried to keep it concise, however, I think I can improve it 👍

2021-03-24 13:37 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Work is is a type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to solve com
The same as with PoS, however, I think I can improve it 👍

2021-03-24 13:38 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A proposed new version of Lisk Core for the testnet.
👍

2021-03-24 13:41 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +An embedded persistent key value store for fast storage.
👍

2021-03-24 13:42 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Semantic versioning (also referred as SemVer), is a versioning system that provides a universal way of versioning software development projects in order to track changes and updates, such as plugins,
👍

2021-03-24 13:45 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A token refers to LSK or any sidechain token.
👍

2021-03-24 13:55 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A transaction type on Mainnet which submits votes for delegates. If the votes are positive it adds the voting weight, if they are negative it removes the voting weight again. If voting weight was add
OK, will update it 👍

2021-03-24 14:04 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A fork in the network is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously.
OK 👍

2021-03-29 11:48 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +
The Lisk32 explanation is still missing in the glossary

2021-03-29 12:47 UTC, Tschakki requested changes

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +The smallest unit of account. 100 million Beddows make one LSK.
```suggestion
The smallest unit of account. 100 million Beddows make one <<LSK>>.
```

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +For example, a BIP39 describes the mnemonic code or mnemonic sentence implementation. It is a protocol that describes how to create a human readable mnemonic sentence and how to convert that mnemonic
This does not really describe what BIPs are.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A block is composed of a block header and a payload of transactions. The block header contains all information related to the block as well as a hash of the payload.
Not sure we need to describe it in the glossary, it is already described pretty good in the protocol: https://liskhq.github.io/lisk-docs/lisk-sdk/protocol/blocks.html#block-header

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A hash of a block header that uniquely identifies a block in the Lisk blockchain.
Same as for block header

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +In addition, the weight of a delegate will determine the sum of all votes for this delegate. Hence, to maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.
To what previous implementation are you referring? Sounds confusing.
This needs to be improved or removed, as it is already explained here: https://lisk.io/documentation/lisk-sdk/dpos-module.html#vote

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A fork can be defined as a change in the network. It is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously. +
The first sentence seems not quite correct. Also, use for every sentence a new line.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Generally speaking, a fork can be defined into one of three categories, a soft, hard, or temporary fork. A soft fork can occur when the blockchain protocol is changed into a backward-compatible manne
what is `SW` here?
Also new line per sentence, and remove the `+` at the end of the line.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Alternatively, if the blockchain protocol is changed into a non backward-compatible manner. For example, the release of a new SW upgrade that is not compatible with the previous versions, which would
This sounds incorrect and confusing. 
`Alternatively, if the blockchain protocol is changed into a non backward-compatible manner.` doesn't even sound like a complete sentence here.
Please provide a clear and fitting description of a fork in a Lisk blockchain.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Finally, in the case whereby two miners mine a new block simultaneously, then the occurrence of a temporary fork will happen.
Why are you talking about miners here?

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +This is the onion of hashes used by the delegate.
Why is the hash onion needed? This should provide more info about the hash onion and what it is used for.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +This can also be referred to as a nonce.
This should be removed. It is not so relevant for the documentation, and we use the nonce term in different context so it could be confusing.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Internet Protocol version 4 is the fourth version of the Internet Protocol.
Add here an example how a IPv4 IP generally looks

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Internet Protocol version 6 is the latest up to date version of the Internet Protocol
Add here an example how a IPv6 IP generally looks

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +=== Lisk32 representation
```suggestion

=== Lisk32 representation
```

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Nonces are generated for a specific purpose and are most commonly used to modify the result of a function in a cryptographic communication.
In the Lisk docs, when we refer to the nonce we always mean the account nonce which is incrementing with each transaction. Please explain the nonce like it is used in the Lisk context instead of providing a general description of the term.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Work is the original type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to s
What do you mean with `original` here? I would remove that or explain more.
One line per sentence, and please remove the`+` at the end of the line.

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network. With PoS the consensus is determined based upon the stake of each user in the network. +
```suggestion
Proof of Stake is a type of consensus mechanism used to achieve agreement over a distributed network.
With PoS the consensus is determined based upon the stake of each user in the network. +
```

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +With PoS users are required to stake their tokens in order to become a validator in the network. Validators are responsible for ordering transactions and creating new blocks, so that all nodes are ab
```suggestion
With PoS users are required to stake their tokens in order to become a validator in the network.
Validators are responsible for ordering transactions and creating new blocks, so that all nodes are able to agree on the current state of the network.
```

2021-03-29 12:47 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +A release candidate can be described as a SW build released internally for testing purposes and not usually for production deployment. It is also defined as a version of the software, which should be
```suggestion
A release candidate can be described as a software build released internally for testing purposes and not usually for production deployment.
It is also defined as a version of the software, which should be functional but not necessarily ready to be released.
```

2021-03-30 13:22 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +The smallest unit of account. 100 million Beddows make one LSK.
I think we should really say the following:  100 million Beddows is equal to 1 <<LSK>>.

2021-03-30 13:25 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +For example, a BIP39 describes the mnemonic code or mnemonic sentence implementation. It is a protocol that describes how to create a human readable mnemonic sentence and how to convert that mnemonic
OK, I will try to amplify the description here 👍

2021-03-30 13:27 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A block is composed of a block header and a payload of transactions. The block header contains all information related to the block as well as a hash of the payload.
OK, good point. I will remove it 👍

2021-03-30 13:28 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A hash of a block header that uniquely identifies a block in the Lisk blockchain.
OK,  I will also remove it 👍

2021-03-30 13:31 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +In addition, the weight of a delegate will determine the sum of all votes for this delegate. Hence, to maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.
OK, I will try to improve it.

2021-03-30 13:33 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +A fork can be defined as a change in the network. It is whereby an alternative version of the blockchain is created by generating two blocks on different parts of the network simultaneously. +
OK 👍

2021-03-30 13:47 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Generally speaking, a fork can be defined into one of three categories, a soft, hard, or temporary fork. A soft fork can occur when the blockchain protocol is changed into a backward-compatible manne
Ok done 👍

2021-03-30 14:06 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Alternatively, if the blockchain protocol is changed into a non backward-compatible manner. For example, the release of a new SW upgrade that is not compatible with the previous versions, which would
Yes, it is also very 'long-winded so I have rebuilt it and referred to a specific link for more detailed info regarding forking in the Lisk network 👍

2021-03-30 14:07 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Finally, in the case whereby two miners mine a new block simultaneously, then the occurrence of a temporary fork will happen.
Now not required as the description has been rebuilt 👍

2021-03-30 14:47 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +This is the onion of hashes used by the delegate.
OK now done 👍

2021-03-30 14:48 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +This can also be referred to as a nonce.
Ok, good point. It is now removed 👍

2021-03-30 15:47 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Internet Protocol version 4 is the fourth version of the Internet Protocol.
👍

2021-03-30 15:47 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Internet Protocol version 6 is the latest up to date version of the Internet Protocol
👍

2021-03-30 15:54 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Nonces are generated for a specific purpose and are most commonly used to modify the result of a function in a cryptographic communication.
Ok now done 👍

2021-03-30 15:56 UTC, chris529 commented on modules/ROOT/pages/references/glossary.adoc
> +Proof of Work is the original type of consensus mechanism used to achieve agreement over a distributed network. With PoW in order to complete the transactions on a given network, the miners have to s
Understood..I have removed the term 'original' 👍

2021-03-31 10:10 UTC, Tschakki requested changes
Looking great already!
Just a few small suggestions left :)

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_del_misbehavior: dpos-module.adoc#discover
```suggestion
:url_discover_misbehavior: dpos-module.adoc#discover
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +For a delegate to cast a vote they are required to specify how much Lisk will be voted or unvoted with each vote.
```suggestion
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +In addition, the weight of a delegate will determine the sum of all votes for this delegate.
```suggestion
The weight of a delegate will determine the sum of all votes for this delegate.
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +Hence, to maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.
```suggestion
To maintain a secure and effective setup, the delegate weight is bound to 10 times the self-votes.
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +For further detailed information regarding forking in the Lisk network, see the following xref:{url_fork}[Lisk Mainnet hard fork process] description in the Lisk Mainnet Regenesis page
```suggestion
For further detailed information regarding forking in the Lisk network, see the following {url_fork}[Lisk Mainnet hard fork process^] description in the Lisk Mainnet Regenesis page
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +:url_hash_onion: node-management/forging.adoc#add-forging-data-to-config
```suggestion
:url_hash_onion: guides/node-management/forging.adoc#add-forging-data-to-config
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +In the Lisk network it can be defined as an integer that accounts for the number of transactions from the sender account.
```suggestion
In the Lisk network it can be defined as an integer that represents for the number of outgoing transactions of an account.
```

2021-03-31 10:10 UTC, Tschakki commented on modules/ROOT/pages/references/glossary.adoc
> +For a transaction to be valid, this integer has to be equal to the nonce stored in the sender account.
```suggestion
For a transaction to be valid, transaction nonce has to be equal to the nonce stored in the sender account.
```

2021-03-31 10:24 UTC, chris529 commented
Thanks for the excellent feedback Mona! 👍

2021-03-31 10:30 UTC, Tschakki approved these changes
Thank you!

2021-03-31 12:39 UTC, merged