Add RPC API reference - Closes #948
LiskArchive/lisk-legacy-docs pull request #954
Opened 2021-01-26 09:55 UTC by Tschakki

Closes #948

2021-02-03 17:41 UTC, MichalTuleja requested changes
Looks good, a few minor changes found

2021-02-03 17:41 UTC, MichalTuleja commented on modules/ROOT/pages/references/rpc-api.adoc
> +==== get.votes
`get.votes_sent`

Update: we've changed it to make it less ambiguous, the old API call `get.votes` still work as legacy API.

2021-02-03 17:41 UTC, MichalTuleja commented on modules/ROOT/pages/references/rpc-api.adoc
> +==== get.voters
`get.votes_received`

2021-02-03 17:41 UTC, MichalTuleja commented on modules/ROOT/pages/references/rpc-api.adoc
> +.Example: Get 20 item, skip 50 first
"Get 20 items, ..."

2021-02-03 17:41 UTC, MichalTuleja commented on modules/ROOT/pages/references/rpc-api.adoc
> +==== get.network.statistic
`get.network.statistics`

2021-02-04 10:34 UTC, chris529 reviewed
Looks good, just a couple of suggestions, and a couple of minor points 👍

2021-02-04 10:34 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
> +You can also access the testnet network by `wss://testnet-service.lisk.io/rpc-v1`.
```suggestion
The testnet network can also be accessed by `wss://testnet-service.lisk.io/rpc-v1`.
```

2021-02-04 10:34 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
> +The logic of the endpoints comes as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to HTTP standard (GET, POST, PUT, etc.) an
```suggestion
The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the action is equivalent to HTTP standard (GET, POST, PUT, etc.) and `entity` is a part of the application logic, ex. `accounts`, transactions and so on.
```

2021-02-04 10:34 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
> +Retrieves network details and constants such as network height, broadhash, fees, reward amount etc.
```suggestion
Retrieves network details and constants such as network height, broadhash, fees, reward amount, etc.
```

2021-02-04 10:34 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
> +Retrieves network statistics such as number of peers, node versions, heights etc.
```suggestion
Retrieves network statistics such as the number of peers, node versions, heights, etc.
```

2021-02-04 12:49 UTC, chris529 reviewed
Looks great to me Mona, although I just noticed 2 headlines that I think would appear to be clearer to the reader with my suggestions. Let me know your thoughts 👍

2021-02-04 12:49 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
> +.Example: Get address with certain Lisk account ID
```suggestion
.Example: Get address with a specific Lisk account ID
```

2021-02-04 12:49 UTC, chris529 commented on modules/ROOT/pages/references/rpc-api.adoc
> +.Example: Get hosts with certain IP
```suggestion
.Example: Get hosts with a specific IP address
```

2021-02-04 13:03 UTC, Tschakki commented on modules/ROOT/pages/references/rpc-api.adoc
> +.Example: Get address with certain Lisk account ID
```suggestion
.Example: Get account with a specific Lisk account ID
```

2021-02-05 17:36 UTC, MichalTuleja approved these changes

2021-02-08 08:47 UTC, merged