Add page about the subscribe API - Closes #949
LiskArchive/lisk-legacy-docs pull request #955
Opened 2021-01-26 14:48 UTC by Tschakki

Closes #949

2021-02-03 17:46 UTC, MichalTuleja requested changes

2021-02-03 17:46 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +== Endpoint logic
Those section can be updated based on:
https://github.com/LiskHQ/lisk-service/blob/v0.2.0-rc.1/docs/api/websocket_subscribe_api.md#endpoint-logic

2021-02-03 17:46 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +
Those section can be updated based on:
https://github.com/LiskHQ/lisk-service/blob/v0.2.0-rc.1/docs/api/websocket_subscribe_api.md#responses

2021-02-03 17:46 UTC, MichalTuleja commented on modules/ROOT/pages/references/subscribe-api.adoc
> +== Date Format
Those section can be updated based on:
https://github.com/LiskHQ/lisk-service/blob/v0.2.0-rc.1/docs/api/websocket_subscribe_api.md#date-format

2021-02-04 12:03 UTC, chris529 reviewed
Looks good...just a few minor suggestions 👍

2021-02-04 12:03 UTC, chris529 commented on modules/ROOT/pages/references/subscribe-api.adoc
> +The Subscribe API is sometimes called publish/subscribe or Event-Driven API.
```suggestion
The Subscribe API is sometimes called the publish/subscribe or Event-Driven API.
```

2021-02-04 12:03 UTC, chris529 commented on modules/ROOT/pages/references/subscribe-api.adoc
> +The logic of the endpoints comes as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the `action` is equivalent to method type performed on server (ie.
```suggestion
The logic of the endpoints is derived as follows: the method naming is always based on the following pattern: `<action>.<entity>`, where the `action` is equivalent to method type performed on the server (ie. `update`) and `entity` is a part of the application logic, ex. `accounts`, `transactions`.
```

2021-02-04 12:03 UTC, chris529 commented on modules/ROOT/pages/references/subscribe-api.adoc
> +Updates the current forgers' list, so the current forger is on the first position.
```suggestion
Updates the current forgers' list, so the current forger is in the first position.
```

2021-02-04 12:03 UTC, chris529 commented on modules/ROOT/pages/references/subscribe-api.adoc
> +You might also be interested in accessing the testnet network by using the https://testnet-service.lisk.io/blockchain endpoint.
```suggestion
If you are interested in accessing the testnet network, this can be accomplished by using the https://testnet-service.lisk.io/blockchain endpoint.
```

2021-02-04 12:40 UTC, chris529 approved these changes
LGTM 👍

2021-02-04 13:06 UTC, merged