Add guide how to protect a non forging node - Closes #843
LiskArchive/lisk-legacy-docs pull request #957
Opened 2021-01-28 12:26 UTC by Tschakki

Closes #843

2021-02-03 16:26 UTC, Nazgolze commented on modules/ROOT/pages/guides/node-management/non-forging-node-protection.adoc
> +<3> `sever` sets the backend server and expects the domain name as first argument, and the IP and port as second argument.
```suggestion
<3> `server` sets the backend server and expects the domain name as first argument, and the IP and port as second argument.
```

2021-02-03 16:30 UTC, Nazgolze commented on modules/ROOT/pages/guides/node-management/non-forging-node-protection.adoc
> +<3> `sever` sets the backend server and expects the domain name as first argument, and the IP and port as second argument.
Also, it's not a domain name that it's taking, but just an arbitrary name 
https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#server%20(Alphabetically%20sorted%20keywords%20reference)

2021-02-04 10:09 UTC, Nazgolze commented on modules/ROOT/nav.adoc
> +** xref:guides/node-management/forging.adoc[]
Not sure if this line was meant for a different PR

2021-02-04 10:09 UTC, Nazgolze requested changes
I think this is everything :+1:

2021-02-04 10:45 UTC, Tschakki commented on modules/ROOT/nav.adoc
> +** xref:guides/node-management/forging.adoc[]
the link was missing in the nav, I fixed it as part of this PR.

2021-02-05 13:18 UTC, Nazgolze approved these changes

2021-02-05 13:19 UTC, merged