Add NFT tutorial - Closes #844
LiskArchive/lisk-legacy-docs pull request #982
Opened 2021-02-16 12:10 UTC by Tschakki

Closes #844

2021-03-09 10:30 UTC, mitsuaki-u requested changes
Looks great! Some minor comments

2021-03-09 10:30 UTC, mitsuaki-u commented on modules/ROOT/pages/architecture/index.adoc
> +* is verifiable by anyone by synchroniying with the blockchain
```suggestion
* is verifiable by anyone by synchronizing with the blockchain
```

2021-03-09 10:30 UTC, mitsuaki-u commented on modules/ROOT/pages/architecture/index.adoc
> +In short, the on-chain logic:
```suggestion
In short, the off-chain logic:
```

2021-03-09 10:30 UTC, mitsuaki-u commented on modules/ROOT/pages/tutorials/nft.adoc
> +      throw new Error("Token can not be purchased value is too low. Minimum value: " + tokenMinPurchaseValue);
```suggestion
      throw new Error("Token can not be purchased. Purchase value is too low. Minimum value: " + tokenMinPurchaseValue);
```

2021-03-09 10:30 UTC, mitsuaki-u commented on modules/ROOT/pages/tutorials/nft.adoc
> +* a list of all transactions, including their module and asset IDs and the transaction asset.
do you mean a list of all NFT related transactions only?

2021-03-09 10:30 UTC, mitsuaki-u commented on modules/ROOT/pages/tutorials/nft.adoc
> +    if (token && token.minPurchaseMargin === 0) {
what if `token.minPurchaseMargin` is less than zero

2021-03-09 11:28 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +    if (token && token.minPurchaseMargin === 0) {
Good point. Will update this from `===` to `<=`

NNeeds to be updated in the example app as well.

2021-03-09 11:29 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +      throw new Error("Token can not be purchased value is too low. Minimum value: " + tokenMinPurchaseValue);
Needs to be updated in the example app as well.

2021-03-09 11:30 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +* a list of all transactions, including their module and asset IDs and the transaction asset.
no, it actually keeps track of all transactions that are sent inn the network, the way it is implemented at the moment.

2021-03-09 15:05 UTC, mitsuaki-u commented on modules/ROOT/pages/tutorials/nft.adoc
> +* a list of all transactions, including their module and asset IDs and the transaction asset.
why is it tracking all instead of only the NFT related transactions?

2021-03-09 15:05 UTC, mitsuaki-u commented on modules/ROOT/pages/tutorials/nft.adoc
> +    if (token && token.minPurchaseMargin === 0) {
yes, it should be added to the validation

2021-03-09 15:14 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +* a list of all transactions, including their module and asset IDs and the transaction asset.
The application also offers to do transfer transactions from the token module, so these transactions would be missing on the transaction page if it would only keep track of NFT related transactions.

2021-03-09 15:18 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +    if (token && token.minPurchaseMargin === 0) {
oh I accidentally changed the if statement, changed it now back :)

2021-03-10 15:06 UTC, shuse2 commented on modules/ROOT/pages/tutorials/nft.adoc
> +    <Card>
jsx format is not visible in the web

2021-03-10 15:06 UTC, shuse2 commented on modules/ROOT/pages/tutorials/nft.adoc
> +==== NFT component
im not sure if we really need to go so deep in the frontend. (There is lots of frontend tutorial, and the component explanation doesn't look very specific to Lisk

2021-03-10 15:06 UTC, shuse2 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<1> First verify, that the NFT which is purchased exists in the database.
If it's numbered, do we need `First` `Next` `Finally`?

2021-03-10 15:06 UTC, shuse2 commented on modules/ROOT/pages/tutorials/nft.adoc
> +You can choose any module name, but it has to be unique in the network.
This is correct, but within the network, not only the name and logic must be the same for all the nodes in the network too.

2021-03-11 09:11 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +==== NFT component
Hm yes it is not main focus here, but maybe it is nice to look at Homepage and NFT components here just to make the picture complete. Also we use  certain methods here that we have defined and explained above.

It's not super Lisk specific, but specific for the NFT app imho.

2021-03-11 09:41 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +You can choose any module name, but it has to be unique in the network.
Updated the description 👍

2021-03-11 09:42 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +<1> First verify, that the NFT which is purchased exists in the database.
Not really. Removed it now 👍

2021-03-11 09:47 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +    <Card>
thats a UI issue. Syntax highlighting theme needs to be changed for this.

2021-03-11 14:09 UTC, chris529 reviewed
Looks great, just some minor points 👍

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +* introduces state mutations through blocks or transactions
```suggestion
* introduces state mutations through blocks or transactions.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +* is part of the blockchain protocol
```suggestion
* is part of the blockchain protocol.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +* is verifiable by anyone by synchronizing with the blockchain
```suggestion
* is verifiable by anyone by synchronizing with the blockchain.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
>  It could be a simple use case as creating HTTP API for your blockchain or providing some aggregation service.
```suggestion
It could be a simple use case such as creating an HTTP API for your blockchain or providing some aggregation service.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +* introduces new blockchain application features
```suggestion
* introduces new blockchain application features.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +* is not part of the blockchain protocol
```suggestion
* is not part of the blockchain protocol.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
> +* is optional to execute on a full node
```suggestion
* is optional to execute on a full node.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
>  More information can be found in section xref:{url_explanations_off_chain}[Off-chain architecture]
```suggestion
More information can be found in the section xref:{url_explanations_off_chain}[Off-chain architecture]
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
>  The communication architecture provides two industry standard communication formats, one is Inter Process Communication (IPC) and other is Web Sockets (WS).
```suggestion
The communication architecture provides two industry standard communication formats, one is Inter Process Communication (IPC) and the other is Web Sockets (WS).
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +* ...a blockchain application which allows to create, transfer and purchase NFTs.
```suggestion
* ...a blockchain application that allows a user to create, transfer and purchase NFTs.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +* ...3 different transaction asset to create, transfer and purchase NFTs.
```suggestion
* ...3 different transaction assets to create, transfer and purchase NFTs.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/index.adoc
> +* ...a frontend application, which allows to use the blockchain application in the browser.
```suggestion
* ...a frontend application, which allows the user to utilize the blockchain application in the browser.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +|Charactericitics
```suggestion
|Characteristics
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Not unique
```suggestion
* Not unique.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Divisible
```suggestion
* Divisible.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Mutually interchangeable
```suggestion
* Mutually interchangeable.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Unique
```suggestion
* Unique.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Indivisible
```suggestion
* Indivisible.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Not mutually interchangeable
```suggestion
* Not mutually interchangeable.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Digital token: Bitcoin(BTC) or Lisk(LSK).
```suggestion
* Digital tokens: Bitcoin(BTC) or Lisk(LSK).
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Digital token: Crypto collectables(like Cryptokitties), event tickets or other virtual assets.
```suggestion
* Digital tokens: Crypto collectibles (e.g. Cryptokitties), event tickets, or other virtual assets.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +As the above image describes, we need to create the following components:
```suggestion
As can be seen in the above image, it is necessary to create the following components:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +. The NFT module (on-chain)
```suggestion
. The NFT module (on-chain).
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +.. Three new transaction assets for the NFT module
```suggestion
.. Three new transaction assets for the NFT module.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +. The NFT plugin (off-chain)
```suggestion
. The NFT plugin (off-chain).
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Additional to the blockchain application, we will also implement **frontend application**, which allows us to interact with the blockchain applicationn through a UI in the browser.
```suggestion
In addition to the blockchain application, we will also implement a **frontend application**, which allows us to interact with the blockchain application through a UI in the browser.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Next, create a new file `index.js` and paste the following:
```suggestion
Next, create a new file `index.js` then copy and paste the following:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +We will use this app as basis for the NFT app and extend it with a module and a plugin in the next steps, to suit the desired use case.
```suggestion
We will use this app as a basis for the NFT app and extend it with a module and a plugin in the following steps, to suit the desired use case.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +You might have spotted that we use special parameters in the functions, like `stateStore` and `_dataAccess`.
```suggestion
You may have noticed that we use special parameters in the functions, like `stateStore` and `_dataAccess`.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Now open the file and paste the code below:
```suggestion
Now open the file and copy and paste the code below:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Therefore, create the schema like described below:
```suggestion
Therefore, create the schema as described below:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* `stateStore`: The xref:{url_statestore}[state store] is a data structure that holds temporary state while processing a block.
```suggestion
* `stateStore`: The xref:{url_statestore}[state store] is a data structure that holds a temporary state while processing a block.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* `reducerHandler`: Allows to use reducer functions of other modules inside the `apply()` function.
```suggestion
* `reducerHandler`: Allows the user to utilize reducer functions of other modules inside the `apply()` function.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<1> Import `getAllNFTTokens`, `setAllNFTTokens` and `createNFTToken` fromt her `nft.js` file.
```suggestion
<1> Import `getAllNFTTokens`, `setAllNFTTokens` and `createNFTToken` from here `nft.js` file.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +We use here the `reducerHandler` and invoke `token:debit` from xref:{url_references_token_module}[] which allows to conveniently debit tokens from an account.
```suggestion
We use the `reducerHandler` here and invoke `token:debit` from xref:{url_references_token_module}[] which allows us to conveniently debit tokens from an account.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +We use here the `reducerHandler` and invoke `token:debit` from xref:{url_references_token_module}[] which allows to conveniently credit tokens to an account.
```suggestion
We use the `reducerHandler` here and invoke `token:debit` from xref:{url_references_token_module}[] which allows us to conveniently credit tokens to an account.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<2> Next verify, that the account who wants to transfer the NFT actually owns the NFT.
```suggestion
<2> Next verify, that the account that wants to transfer the NFT actually owns the NFT.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<3> Next, it is needed to remove the NFT from the current owner account.
```suggestion
<3> Next, it is necessary to remove the NFT from the current owner account.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Let's start with the most easy ones: defining the module name and id.
```suggestion
It is recommended to start with the easiest ones: defining the module name and id.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +You can choose any module name, but it has to be unique in the network.
```suggestion
You can choose any module name, however, it has to be unique in the network.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Same goes for the ID, though the minimum value for it is `1024`, as the other IDs are reserved for future default modules of the Lisk SDK.
```suggestion
The same goes for the ID, though the minimum value for it is `1024`, as the other IDs are reserved for future default modules of the Lisk SDK.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +This property defines the properties, that are added to each network account by the module, if it is registered with the application later.
```suggestion
This property defines the properties, that are added to each network account by the module if it is registered with the application later.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Add them to the `tansactionAssets` property like shown in the snippet below.
```suggestion
Add them to the `transactionAssets` property as shown in the snippet below.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +It's a good practise to name the imported transaction assets after their corresponding classname.
```suggestion
It is a good practice to name the imported transaction assets after their corresponding classname.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +As a last feature for the NFT module, we create an action `getAllNFTTokens` which will allow the NFT plugin later to retrieve a list of all existing NFT tokens.
```suggestion
The last remaining feature for the NFT module consists of creating the following action `getAllNFTTokens` which will allow the NFT plugin to retrieve a list of all existing NFT tokens later.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +The parameter `this._dataAccess` is passed as parameter.
```suggestion
The parameter `this._dataAccess` is passed as a parameter.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +The NFT plugin shall provide a HTTP API which offers new endpoints for NFT related data from the blockchain.
```suggestion
The NFT plugin shall provide an HTTP API that offers new endpoints for NFT related data from the blockchain.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Move out of the `nft_module` folder back into the `blockchain_app` folder.
```suggestion
Navigate out of the `nft_module` folder back into the `blockchain_app` folder.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<1> `DB_KEY_TRANSACTIONS`: The key we use to save the transactions in the key-value store.
```suggestion
<1> `DB_KEY_TRANSACTIONS`: The key used to save the transactions in the key-value store.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Here, we define a simple array, which contains the adresses of the current and all previous owners of the NFT.
```suggestion
Here, we define a simple array, which contains the addresses of the current and all previous owners of the NFT.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +We define all of this inside of the `load()` function.
```suggestion
This will all be defined inside of the `load()` function.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Now that the NFT module and plugin have been implemented, we need to let the blockchain application know about them.
```suggestion
Now that the NFT module and plugin have been implemented, it is necessary to let the blockchain application know about them.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +This is done by registering them with the blockchain application like shown below.
```suggestion
This is done by registering them with the blockchain application as shown below.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +When you start the application now again with `node index.js`, the blockchain application will load the newly created NFT module and the plugins and the new features become availalbe to the blockchai
```suggestion
Now when the application is started again with `node index.js`, the blockchain application will load the newly created NFT module and the plugins and the new features will become available to the blockchain application.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +The development of the frontend application is absolutely flexible, and you can use any technology stack that you feel comfortable with.
```suggestion
The development of the frontend application is completely flexible, and you can use any technology stack that you feel comfortable with.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +This tutorial is mainly about explaining how to build with the Lisk SDK, therefore other parts of the frontend app wont be explained in much detail.
```suggestion
This tutorial is mainly about explaining how to build with the Lisk SDK, therefore other parts of the frontend app are not explained in much detail here.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +You can get more information about how to build React application for example at the {url_react_docs}[official React documentation^].
```suggestion
You can get more information about how to build a React application for example at the {url_react_docs}[official React documentation^].
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +At this point you can already try out the frontend an verify that the NFT blockchain application works as expected:
```suggestion
At this point it is now possible to already try out the frontend and verify that the NFT blockchain application works as expected:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +First open a second terminal window, navigate to `nft/blockchain_app` and start the blockchain application with `node index.js`, if it is not already running.
```suggestion
First, open a second terminal window and navigate to the `nft/blockchain_app`. Now start the blockchain application with `node index.js`, if it is not already running.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +In the first terminal window, start the frontend application with
```suggestion
In the first terminal window, start the frontend application with the following:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +We will do the following:
```suggestion
We will perform the following:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +. Create 3 different accounts
```suggestion
. Create 3 different accounts.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +. Send an initial amount of tokens to each account
```suggestion
. Send an initial amount of tokens to each account.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +. Create a new NFT with the first account
```suggestion
. Create a new NFT with the first account.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +But you can also create new credentials by using the `Create Account` dialog:
```suggestion
However, you can also create new credentials by using the `Create Account` dialog:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +On the first start of the app, the page is pretty empty, but once we created the first NFTs, the home page will display all existing NFTs and their details.
```suggestion
On the first start of the app, the page is quite empty. However, once we have created the first NFTs, the home page will display all existing NFTs and their details.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +On the bottom right, there is a button that allows to open the different dialogs for creating a new account, transferring tokens from one account to another and, most importantly, for creating new NF
```suggestion
On the bottom right, there is a button that can be used for opening the different dialogs for creating a new account, transferring tokens from one account to another, and most importantly, for creating new NFTs.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Click on the `Transfer tokens` dialog and transfer a decent amount of tokens to the above described demo accounts.
```suggestion
Click on the `Transfer tokens` dialog and transfer an adequate amount of tokens to the above described demo accounts.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +In our example, we transfer 2000 tokens to the artist account, and each 1000 tokens to the collector accounts.
```suggestion
In our example, we transferred 2000 tokens to the artist account and 1000 tokens each to the collector accounts.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +As passphrase, use the passphrase of the genesis account, by clicking on the button `Use genesis account`.
```suggestion
For the passphrase, use the passphrase of the genesis account, by clicking on the button `Use genesis account`.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +It is possible to verify the transaction got included in ablock by observing the logs of the blockchain application:
```suggestion
It is possible to verify the transaction was included in a block by observing the logs of the blockchain application:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +After approx. 10 seconds, the NFT should appear on the home page, after refreshing the page.
```suggestion
After approximately 10 seconds, the NFT should appear on the home page, after refreshing the page.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +At the bottom of the NFT card, the user has now the option to `transfer` or `purchase` the NFT.
```suggestion
At the bottom of the NFT card, the user now has the option to `transfer` or `purchase` the NFT.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +If a different account than the owner tries to transfer the NFT, the application will throw an error `An NFT can only be transferred by the owner of the NFT.`, which we defined before in the <<transf
```suggestion
If a different account than the owner tries to transfer the NFT, the application will throw an error `An NFT can only be transferred by the owner of the NFT.`, which we defined previously in the <<transfernft-asset>> section.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Click on the account addresses in the NFT history, to go see the account details of the corresponding account on a new page:
```suggestion
Click on the account addresses in the NFT history, to view the account details of the corresponding account on a new page:
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Have a close look at the `Token value` property, which has increased from 120 to 132 because of the purchase.
```suggestion
Have a close look at the `Token value` property, which has increased from 120 to 132 due to the purchase.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Click on the `Transactions` link in the top bar, to get to the transaction explorer.
```suggestion
Click on the `Transactions` link in the top bar, to go to the transaction explorer.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Here you see a list of all transactions, which have been posted in the network so far, including a few details like their respective module and asset name, the sender address and the transaction ID.
```suggestion
Here you see a list of all transactions, which have been posted in the network so far, including a few details such as their respective module and asset name, the sender address and the transaction ID.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +If you feel like it, play around a little more with the NFT app by creating more NFTs.
```suggestion
To become more familiar with the process, play around a little more with the NFT app by creating more NFTs.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Used to retrieve general blockchain infromation from the database.
```suggestion
Used to retrieve general blockchain information from the database.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +** `sendTransactions(tx)`: Sends a specified transaction obbject `tx` to the node.
```suggestion
** `sendTransactions(tx)`: Sends a specified transaction object `tx` to the node.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +** `fetchAllNFTTokens()`: Fetches a list of all registered NFTs int he network.
```suggestion
** `fetchAllNFTTokens()`: Fetches a list of all registered NFTs in the network.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +** `getAllTransactions()`: Returns a list of all posted trasnactions int he network.
```suggestion
** `getAllTransactions()`: Returns a list of all posted transactions in the network.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Below you find the code examples for the `HomePage` and `NFTToken` components.
```suggestion
The code examples for the `HomePage` and `NFTToken` components can be found below.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +As you might know, there are two different representations of the account address in the Lisk protocol: the **binary address** and the **base32 address**.
```suggestion
As you may be aware, there are two different representations of the account address in the Lisk protocol: the **binary address** and the **base32 address**.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +For *backend*, it is always recommended to work with the **binary address**, because this is how the Lisk SDK handles adresses internally.
```suggestion
For *backend*, it is always recommended to work with the **binary address**, as this is how the Lisk SDK handles addresses internally.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* **Name**: The name of the NFT as title.
```suggestion
* **Name**: The name of the NFT as the title.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +** a custom module for handeling NFTs
```suggestion
** a custom module for handling NFTs.
```

2021-03-11 14:09 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +** a custom plugin which adds additional features for the NFTs
```suggestion
** a custom plugin that adds additional features for the NFTs.
```

2021-03-12 08:54 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Not unique
I am ont sure we need points here, as it are no full sentences, just checkpoints

2021-03-12 08:59 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +<1> Import `getAllNFTTokens`, `setAllNFTTokens` and `createNFTToken` fromt her `nft.js` file.
```suggestion
<1> Import `getAllNFTTokens`, `setAllNFTTokens` and `createNFTToken` from the `nft.js` file.
```

2021-03-12 09:01 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +Let's start with the most easy ones: defining the module name and id.
```suggestion
It is recommended to start with the easiest ones: defining the module name and ID.
```

2021-03-12 09:06 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +The parameter `this._dataAccess` is passed as parameter.
```suggestion
The variable `this._dataAccess` is passed as a parameter.
```

2021-03-15 13:58 UTC, mitsuaki-u approved these changes, later dismissed

2021-03-16 10:38 UTC, chris529 reviewed
Looks very good, just a few minor points 👍

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
>  Some business flows or requirements implementation required to perform some computation which is based on the blockchain data but not required to change alter any blockchain state.
```suggestion
Some business flows or requirements are necessary to be implemented to perform certain computations, which are based on the blockchain data but are not actually required to change or alter any blockchain states.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/architecture/index.adoc
>  More information can be found in section xref:{url_explanations_communication}[Communication architecture]
```suggestion
More information can be found in the section xref:{url_explanations_communication}[Communication architecture]
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +In the NFT tutorial, you learn step-by-step how to create a blockchain application which supports NFTs.
```suggestion
In the NFT tutorial, you will learn step-by-step how to create a blockchain application that supports NFTs.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +You will learn how to create a custom module which adds the feature to create and purchase NFTs to a blockchain application, and a custom plugin which provides additional NFT-related features.
```suggestion
You will learn how to create a custom module that adds the feature to create and purchase NFTs in a blockchain application, and a custom plugin that provides additional NFT-related features.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* Not unique
OK, that is fine as long as we list all the checkpoints with the same ending, (so without a full-stop) 👍

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +* `createNFTToken()`: Creates a new NFT based on provided `name`, `ownerAddress`, `nonce`, `value` and  `minPurchaseMargin`.
```suggestion
* `createNFTToken()`: Creates a new NFT based on the provided `name`, `ownerAddress`, `nonce`, `value` and  `minPurchaseMargin`.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<3> Push the ID of the newly created NFT into the sender account.
```suggestion
<3> Push the ID of the newly created NFT into the sender account and save the updated sender account in the database.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Save the updated sender account in the database.
```suggestion

```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Analog to the implementation of the `createNFT` asset, create the `purchaseNFT` asset by pasting the snippet below.
```suggestion
In parallel to the implementation of the `createNFT` asset, create the `purchaseNFT` asset by pasting the snippet below.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<2> Export the module, so it can be imported later into the application.
```suggestion
<2> Export the module, so it can be imported into the application later.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +The module name should be unique within the network as well.
```suggestion
The module name should be unique within the network as well, otherwise, it will lead to confusion.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Otherwise it will lead to confusion, for example when subscribing to events or invoking actions of that module.
```suggestion
For example, when subscribing to events or invoking actions of that module.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +<4> Export the plugin, so it can be imported later into the application.
```suggestion
<4> Export the plugin, so it can be imported into the application later.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +For a better overview, first create another file which will contain the functions related to the plugin database.
```suggestion
For an enhanced overview, first, create another file that will contain the functions related to the plugin database.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Paste the below snippet into the newly created file `db.js`.
```suggestion
Copy and paste the below snippet into the newly created file `db.js`.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +We will then create an HTTP server and create the required API endpoints to serve the data to the frontend application.
```suggestion
We will then create an HTTP server and also create the required API endpoints to serve the data to the frontend application.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Open again the `nft/blockchain_app/index.js` file and paste the following code:
```suggestion
Open the `nft/blockchain_app/index.js` file again and copy and paste the following code:
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +You can get more information about how to build a React application for example at the {url_react_docs}[official React documentation^].
```suggestion
You can find more information about how to build a React application, for example in the {url_react_docs}[official React documentation^].
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Before we explore the code of the frontend app, lets first take a tour through the frontend in the browser, to see how it all works together.
```suggestion
Before we explore the code of the frontend app, let's first take a tour through the frontend in the browser to see how it all works together.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Currently, it should be empty as well, as we haven't send any transactions yet.
```suggestion
Currently, it should be empty as well, as we haven't sent any transactions yet.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Here you see a list of all transactions, which have been posted in the network so far, including a few details such as their respective module and asset name, the sender address and the transaction I
```suggestion
Here you can see a list of all transactions, which have been posted in the network so far, including a few details such as their respective module and asset name, the sender address, and the transaction ID.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +That's it, the frontend walkabout in the browser is complete.
```suggestion
That's it, the frontend walkabout in the browser is now complete.
```

2021-03-16 10:38 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +The transactions are created and signed by utilizing the `signTransaction()`  from the `@liskhq/lisk-client` package.
```suggestion
The transactions are created and signed by utilizing the `signTransaction()` from the `@liskhq/lisk-client` package.
```

2021-03-16 11:23 UTC, Tschakki commented on modules/ROOT/pages/tutorials/nft.adoc
> +Analog to the implementation of the `createNFT` asset, create the `purchaseNFT` asset by pasting the snippet below.
Analog sounds more accurate here to me.

2021-03-16 11:58 UTC, chris529 commented on modules/ROOT/pages/tutorials/nft.adoc
> +Analog to the implementation of the `createNFT` asset, create the `purchaseNFT` asset by pasting the snippet below.
This is one of these ''either/or'' cases, whereby both are actually correct.
However, this is your excellent tutorial Mona, so let's keep it as 'Analog' 👍

2021-03-16 12:08 UTC, chris529 approved these changes
LGTM!

2021-03-16 17:31 UTC, shuse2 approved these changes

2021-03-16 17:58 UTC, merged