Minor updates in enabling forging in Core docs v3 beta-4 - Closes #984
LiskArchive/lisk-legacy-docs pull request #985
Opened 2021-02-19 09:30 UTC by chris529

2021-02-24 13:49 UTC, Tschakki requested changes
Please see my comments and also solve the existing conflicts in the PR.

2021-02-24 13:49 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +The height of your node should be equal to the current network height. This can be achieved by executing the command below:
The sentence is confusing, as it is not achieved by the elow command. Please completely undo this change.

2021-02-24 13:49 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +. Restore the `forger_info` table by executing the following command below:
not necessary to add this here

2021-02-24 13:49 UTC, Tschakki commented on modules/ROOT/pages/management/forging.adoc
> +. Dump the data in the `forger_info` table of the db of your node by executing the following command below:
not necessary to add this here

2021-02-24 15:40 UTC, chris529 commented on modules/ROOT/pages/management/forging.adoc
> +The height of your node should be equal to the current network height. This can be achieved by executing the command below:
OK, now done 👍

2021-02-24 15:41 UTC, chris529 commented on modules/ROOT/pages/management/forging.adoc
> +. Restore the `forger_info` table by executing the following command below:
OK, now done 👍

2021-02-24 15:42 UTC, chris529 commented on modules/ROOT/pages/management/forging.adoc
> +. Dump the data in the `forger_info` table of the db of your node by executing the following command below:
OK, done 👍

2021-02-25 11:27 UTC, Tschakki approved these changes

2021-02-25 11:28 UTC, merged